### ISSUE TITLE
HiCDCPlus

### ISSUE THREAD

**Issue by mervesa** [Bioconductor/Contributions#1720] opened 2020-10-15 13:26 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mervesa/HiCDCPlus

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by lshep** [comment] 2020-11-19 17:43
When i ran build and check locally I got an ERROR with a segmentation fault... Since this appeared in earlier reports too I'm slightly concerned over stability and reproduciblity? 
```
* checking files in 'vignettes' ... OK
* checking examples ... ERROR
Running examples in 'HiCDCPlus-Ex.R' failed
The error most likely occurred in:

> ### Name: gi.list.topdom
> ### Title: gi.list.topdom
> ### Aliases: gi.list.topdom
> 
> ### ** Examples
> 
> hic_path<-system.file("extdata", "GSE63525_HMEC_combined_example.hic",
+ package = "HiCDCPlus")
> gi_list=hic2icenorm.gi.list(hic_path,binsize=50e3,chrs='chr22')
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARN [2020-11-19T12:36:32,174]  [Globals.java:138] [main]  Development mode is enabled
Loading required package: BSgenome
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: 'S4Vectors'

The following objects are masked from 'package:base':

    I, expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: Biostrings
Loading required package: XVector

Attaching package: 'Biostrings'

The following object is masked from 'package:base':

    strsplit

Loading required package: rtracklayer
Start filtering  ...2020-11-19 12:36:32
Filter out 342 rows and columns ...
Start Iterative Correction ...
it=1 2020-11-19 12:36:32
it=2 2020-11-19 12:36:32
it=3 2020-11-19 12:36:32
it=4 2020-11-19 12:36:33
it=5 2020-11-19 12:36:33
it=6 2020-11-19 12:36:33
it=7 2020-11-19 12:36:33
it=8 2020-11-19 12:36:33
it=9 2020-11-19 12:36:33
it=10 2020-11-19 12:36:34
Did not converged. Stop at iteration 10
> tads<-gi.list.topdom(gi_list)
[1] "#########################################################################"
[1] "Step 0 : File Read "
[1] "#########################################################################"
[1] "-- Done!"
[1] "Step 0 : Done !!"
[1] "#########################################################################"
[1] "Step 1 : Generating binSignals by computing bin-level contact frequencies"
[1] "#########################################################################"
[1] "Step 1 Running Time :  0.00400000000000489"
[1] "Step 1 : Done !!"
[1] "#########################################################################"
[1] "Step 2 : Detect TD boundaries based on binSignals"
[1] "#########################################################################"
[1] "Process Regions from  1 to 685"
[1] "Step 2 Running Time :  0.0069999999999979"
[1] "Step 2 : Done !!"
[1] "#########################################################################"
[1] "Step 3 : Statistical Filtering of false positive TD boundaries"
[1] "#########################################################################"
[1] "-- Matrix Scaling...."
[1] "-- Compute p-values by Wilcox Ranksum Test"
[1] "Process Regions from  1 to 685"
[1] "-- Done!"
[1] "-- Filtering False Positives"
[1] "-- Done!"
[1] "Step 3 Running Time :  0.356999999999999"
[1] "Step 3 : Done!"
[1] "Done!!"
[1] "Job Complete !"
Warning: stack imbalance in '<-', 2 then -5

 *** caught segfault ***
address 0x7f6b02f2efe0, cause 'memory not mapped'
Segmentation fault (core dumped)
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running ‘runTests.R’
 OK
```

**Comment by mervesa** [comment] 2020-11-20 16:55
Hi @lshep , can you please provide more context so that I can see where I can best replicate on my end? Specifically what are your .Platform$OS.type, sessionInfo(), java --version and javac --version? Thanks!

**Comment by lshep** [comment] 2020-12-02 15:31
It seems to have resolved itself like it did on the builders but keep this in mind if it reoccurs in the future (even intermittent) it might be worth looking into. 

I'm working on a review right now and should have something posted later today or tomorrow at the latest.  
Cheers and I apologize for the delay.

**Comment by lshep** [comment] 2020-12-02 15:53
Please see comments below: 


**DESCRIPTION**

- [ ] We recommend removing `LazyData: true`. We have rarely found it useful and
  can slow package installation.

**NAMESPACE**

- [ ] Remove `exportPattern("^[[:alpha:]]+")`. This exports everything. You
  should only export functions that should be executable by the user.

- [ ] (Optional but recommended) We don't recommed naming functons with `.` in
  the name.  The `.` has an underlying meaning of S3 dispatch of a given class
  object. Please update to  `_` or camelcase.

**build**

- [ ] This directory should be removed. vignettes should be in the vignette
  directory.

**inst**

- [ ] Please include an inst/script that describes the data provided in
  inst/extdata.  This can be code, sudo code, or text but should indicate source
  information and generaly information for regenerating files.


Please comment or address the issues above. When ready please do a version bump and push to git.bioconductor.org to trigger a new build.  

Cheers,

**Comment by mervesa** [comment] 2020-12-03 14:47
Thanks @lshep for your review, will look into the issues and trigger a new build soon! I still couldn't replicate the `segfault,` you've mentioned but please do let me know if it recurs, along with `.Platform$OS.type`, `sessionInfo()`, `java --version` and `javac --version`.

**Comment by mervesa** [comment] 2020-12-24 07:37
> Please see comments below:
> 
> **DESCRIPTION**
> 
> * [x]  We recommend removing `LazyData: true`. We have rarely found it useful and
>   can slow package installation.
> 
> **NAMESPACE**
> 
> * [x]  Remove `exportPattern("^[[:alpha:]]+")`. This exports everything. You
>   should only export functions that should be executable by the user.
> * [x]  (Optional but recommended) We don't recommed naming functons with `.` in
>   the name.  The `.` has an underlying meaning of S3 dispatch of a given class
>   object. Please update to  `_` or camelcase.
> 
> **build**
> 
> * [x]  This directory should be removed. vignettes should be in the vignette
>   directory.
> 
> **inst**
> 
> * [x]  Please include an inst/script that describes the data provided in
>   inst/extdata.  This can be code, sudo code, or text but should indicate source
>   information and generaly information for regenerating files.
> 
> Please comment or address the issues above. When ready please do a version bump and push to git.bioconductor.org to trigger a new build.
> 
> Cheers,

Incorporated all comments and pushed version 0.99.3

**Comment by mervesa** [comment] 2020-12-24 08:40
Hi @lshep, happy holidays! Do we have more visibility into where the examples check might be stuck for Windows i386? This could also be a recurrence of the `segfault` issue you've encountered earlier.

**Comment by lshep** [comment] 2021-01-07 15:52
Thank you for those modifications.  A few comments on the code: 

- [ ] Please use message instead of print. Using message also should not need
  paste0 calls inside. Multiple calls in a row should be consoladated into a
  single call. All prints should be changed but an example of consolidating
  
```
	 print("#########################################################################")
        print("Step 2 : Detect TD boundaries based on binSignals")
        print("#########################################################################")


should be changed to


message("#########################################################################\nStep 2 : Detect TD boundaries based on binSignals\n#########################################################################")

or if you would like to keep line spacing in the file
message("#########################################################################\n",
        "Step 2 : Detect TD boundaries based on binSignals\n",
	"#########################################################################")

```

- [ ] In generally we do not like to see large bodies of repeated code.
  HiCDCplus and HiCDCPlus_chr for instance have extreme overlap. All of the
  helper functions defined are the exact same. These functions should be pulled
  out and into a file perhaps helpers.R or utilities.R and referenced from one
  place.  They can still be internal functions without deocumentation (we
  encourage a dot in front to indicate internal functions (ex: .GLM ).
  Additional reasoning to not repeat code and have functions nested inside other
  functions:  1. It makes code extremely hard to read. You don't know what code
  is in an internal function vs what code is the main function.   2. Repeating
  functions and code in multiple places should always be avoided. Repeated code
  should have its own function so that it is easier and more efficient to
  debug. If a bug is found it only needs to be fixed in one location instead of
  several. Often functions that only differ by an argument or a few lines of
  code can still be combined into a single function and a distiction made with a
  seperate argument.  

- [ ] There are several files that nest multiple functions inside a main
  function. Again, it is better to pull these functions into their own file so
  that there is a clear distinction of what code is being run in the main
  function call.


- [ ] straw\_dump.R :  So each time a user runs this function it redownloades
  the file from aws?  This doesn't seem efficient.  I would recommend looking
  into a caching mechanism that will download the file and only redownload if
  the file has been updated or doesn't exist.  There is an existing Bioconductor
  package to help with this (BiocFileCache) or feel free to use another existing
  method. This way too if aws is ever down but the file was already downloaded
  the function could still work.


Please address the above issues and comment back when ready for a review. 
Cheers

**Comment by lshep** [comment] 2021-02-05 14:29
Hello @mervesa   Is there an update on the status of the package?  Are you planning on follow up the review?

**Comment by mervesa** [comment] 2021-02-05 14:50
Hi @lshep , I am working on it, I will push a version bump as soon as possible. Is there a deadline I should be aware of?

**Comment by lshep** [comment] 2021-02-05 14:53
No but we like to move people through the review process to get into Bioconductor as quickly as possible and like to see updates within 3-4 weeks of review.  No problem if it will take a little time, but please provide some updates occasionally to ensure progression.  The main deadline to be aware of will be the next release deadline -- we do not have the official release date for the next Bioconductor release but it is often late March/April.  Cheers

**Comment by mervesa** [comment] 2021-02-06 19:28
> Thank you for those modifications. A few comments on the code:
> 
> * [x]  Please use message instead of print. Using message also should not need
>   paste0 calls inside. Multiple calls in a row should be consoladated into a
>   single call. All prints should be changed but an example of consolidating
> 
> ```
> 	 print("#########################################################################")
>         print("Step 2 : Detect TD boundaries based on binSignals")
>         print("#########################################################################")
> 
> 
> should be changed to
> 
> 
> message("#########################################################################\nStep 2 : Detect TD boundaries based on binSignals\n#########################################################################")
> 
> or if you would like to keep line spacing in the file
> message("#########################################################################\n",
>         "Step 2 : Detect TD boundaries based on binSignals\n",
> 	"#########################################################################")
> ```
> 
> * [x]  In generally we do not like to see large bodies of repeated code.
>   HiCDCplus and HiCDCPlus_chr for instance have extreme overlap. All of the
>   helper functions defined are the exact same. These functions should be pulled
>   out and into a file perhaps helpers.R or utilities.R and referenced from one
>   place.  They can still be internal functions without deocumentation (we
>   encourage a dot in front to indicate internal functions (ex: .GLM ).
>   Additional reasoning to not repeat code and have functions nested inside other
>   functions:  1. It makes code extremely hard to read. You don't know what code
>   is in an internal function vs what code is the main function.   2. Repeating
>   functions and code in multiple places should always be avoided. Repeated code
>   should have its own function so that it is easier and more efficient to
>   debug. If a bug is found it only needs to be fixed in one location instead of
>   several. Often functions that only differ by an argument or a few lines of
>   code can still be combined into a single function and a distiction made with a
>   seperate argument.
> * [x]  There are several files that nest multiple functions inside a main
>   function. Again, it is better to pull these functions into their own file so
>   that there is a clear distinction of what code is being run in the main
>   function call.
> * [x]  straw_dump.R :  So each time a user runs this function it redownloades
>   the file from aws?  This doesn't seem efficient.  I would recommend looking
>   into a caching mechanism that will download the file and only redownload if
>   the file has been updated or doesn't exist.  There is an existing Bioconductor
>   package to help with this (BiocFileCache) or feel free to use another existing
>   method. This way too if aws is ever down but the file was already downloaded
>   the function could still work.
> 
> Please address the above issues and comment back when ready for a review.
> Cheers

Hey @lshep I have eliminated repeated code and moved internal functions into a `utils.R` with `.` preambles on the functions. I've also replaced the print statements with message, and with no `paste(...)` likes. Thanks for suggesting `BiocFileCache` as well, I now use that package to download and maintain the AWS file.

**Comment by lshep** [comment] 2021-02-18 14:28
Great!  Last two minor points: 


**General**

When I run: 
```
> library(HiCDCPlus)
Warning message:
multiple methods tables found for 'export' 
```
Not sure if it is significant or able to be corrected but so you are aware as
you might get some questions about it from users.


This also occurs in your vignette when I assume you run this in a hidden code
chunk. You might want to add options to hide output or hide warnings for code
chunks esp those code chunks that are hidden.



**vignette**

Is this warning significant or can it be ignored? I assume its some system
requirement I don't have set but could be set? 
```
> hicdc2hic(gi_list,hicfile=paste0(outdir,'/GSE63525_HMEC_combined_result.hic'),
+           mode='normcounts',gen_ver='hg19')
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARN [2021-02-18T08:44:39,859]  [Globals.java:138] [main]  Development mode is enabled
```

Please comment on the above else the package looks ready to accept.

**Comment by lshep** [comment] 2021-02-19 13:18
It looks like this is not related to your package
```
Warning message:
multiple methods tables found for 'export' 
```
So nothing to fix on your end,  however I would still hide the warning output in the vignette since the code is not shown.

**Comment by mervesa** [comment] 2021-02-20 03:33
Hi @lshep , thanks for your suggestions and for your due diligence with regards to the `multiple methods tables` warning---I wasn't able to replicate on my end. I've now hidden the warning output in the vignette.

**Comment by mtmorgan** [comment] 2021-02-27 19:11
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mervesa.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HiCDCPlus")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HiCDCPlus

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2021-02-27 19:11 UTC
Labels: 3a. accepted, OK
