### ISSUE TITLE
SpliceWiz R package submission

### ISSUE THREAD

**Issue by alexchwong** [Bioconductor/Contributions#2685] opened 2022-06-02 05:55 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/alexchwong/SpliceWiz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by alexchwong** [comment] 2022-06-02 05:59
Dear Reviewers,

Please be aware that SpliceWiz is intended to replace the NxtIRFcore R package already in Bioconductor (and should be reviewed in this context). It includes some performance improvements as well as the introduction of a shiny-based GUI. SpliceWiz is submitted as a separate package to facilitate the package name change.

**Comment by alexchwong** [comment] 2022-06-06 23:10
@Kayla-Morrell CHECK is timing out at ~15 min for MacOS but runs fine at 4.5 min on Linux.

Seems like Bioconductor's MacOS is much slower than Linux. Running R cmd check on GitHub action, I am getting 8min 41sec for MacOS. Also the longest example "NxtSE-class" is taking 65 sec on Bioconductor's MacOS, whereas it takes 28 sec on GitHub action's MacOS.

Is there something going on with the MacOS server on Bioconductor's end that is slowing it down?

**Comment by Kayla-Morrell** [comment] 2022-06-07 18:49
@alexchwong - I can confirm that on my personal Mac it only took about 7 minutes to run R CMD check. I'm not sure what might be happening on the Bioc Mac but I can review in the meantime and perhaps the issue will work itself out. If there needs to be further investigation we can do that while the review is taking place. I should have the initial review posted by the beginning of next week.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2022-06-16 15:20
@alexchwong - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: In the README file, the installation instructions should also
  include how to install the package from Bioconductor.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
	ATACSeq, DNASeq, RIPSeq, Microarray, mRNAMicroarray, CRISPR

## Data

- [ ] REQUIRED: The `inst/extdata/` files need to have documentation in the
  `inst/script/` directory.  There needs to be documentation on how the data was
generated and source information. It should include source URLs and any key
information regarding filtering or processing. It can be executable code, sudo
code, or a text description. Users should be able to download and roughly
reproduce the file or object that is present as data.

## Vignettes

- [ ] REQUIRED: Most of the code chunks in the `SW_Cookbook.Rmd` file contain
  `eval = FALSE`. We don't allow for static vignettes and executable code is a
must.
- [ ] SUGGESTION: We encourage the use of `BiocStyle` for formatting.
- [ ] REQUIRED: I couldn't find reference to `img/MenuBar.jpg` or
  `img/Settings.jpg` in the vignettes. If these images aren't needed they should
be removed.

*SW_QuickStart.Rmd*

- [ ] REQUIRED: The 'Introduction' section needs more detail about the package
  itself. It should serve as an abstract to introduce the objective, models,
unique functions, key points, etc. that distinguish the package from other
packages in the same area. This should also include a short motivation for the
package in general as well as motivation for inclusion in Bioconductor.
- [ ] SUGGESTION: I would suggest not hiding results so if a user is running
  through the vignette code they will be able to compare their results to yours
to be sure they are getting the correct output.

## Man pages

- [ ] REQUIRED: Usage of `dontrun{}` / `donttest{}` tags found in man page
  examples. This is acceptable if the functions are run elsewhere, such as in
the vignette(s) or tests. I could not find where `calculateMappability()`,
`STAR_buildRef()`, `STAR_alignReads()`, `STAR_alignExperiment()`, or
`findFASTQ()` were run. Please make sure these functions are being run in code
somewhere (i.e., man page examples, vignette executable code, or runnable unit
tests).
- [ ] REQUIRED: For those functions that are being run else where but you don't
  want to have run in the man page examples use `donttest{}` over `dontrun{}`,
since `donttest{}` requires valid R code.

## R code

- [ ] REQUIRED: Avoid `cat` and `print` outside of `show` methods.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 146
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 229 lines that are not.

Best,
Kayla

**Comment by alexchwong** [comment] 2022-06-17 03:54
Thanks @Kayla-Morrell for the initial review / feedback. I have addressed all **REQUIRED**
sections in the comments below:

> ## General package development
> 
>     * [ ]  REQUIRED: In the README file, the installation instructions should also
>       include how to install the package from Bioconductor.
> 

Added instructions for installation from Bioconductor (for devel / 3.16)
 
> ## DESCRIPTION
> 
>     * [ ]  SUGGESTION: Consider adding these automatically suggested biocViews:
>       ATACSeq, DNASeq, RIPSeq, Microarray, mRNAMicroarray, CRISPR
> 
> 
> ## Data
> 
>     * [ ]  REQUIRED: The `inst/extdata/` files need to have documentation in the
>       `inst/script/` directory.  There needs to be documentation on how the data was
>       generated and source information. It should include source URLs and any key
>       information regarding filtering or processing. It can be executable code, sudo
>       code, or a text description. Users should be able to download and roughly
>       reproduce the file or object that is present as data.
> 

The data in `inst/extdata/` can be reproduced by calling the `make_example_NxtSE`
function found within `inst/scripts/make-data.R` file. I have updated the documentation
as comments above this function in `make-data.R`

> ## Vignettes
> 
>     * [ ]  REQUIRED: Most of the code chunks in the `SW_Cookbook.Rmd` file contain
>       `eval = FALSE`. We don't allow for static vignettes and executable code is a
>       must.
> 
I have removed `SW_Cookbook.Rmd`

>     * [ ]  SUGGESTION: We encourage the use of `BiocStyle` for formatting.
> 
>     * [ ]  REQUIRED: I couldn't find reference to `img/MenuBar.jpg` or
>       `img/Settings.jpg` in the vignettes. If these images aren't needed they should
>       be removed.
> 
I have added an extra section that utilises `img/MenuBar.jpg`. `img/Settings.jpg` is now removed

> _SW_QuickStart.Rmd_
> 
>     * [ ]  REQUIRED: The 'Introduction' section needs more detail about the package
>       itself. It should serve as an abstract to introduce the objective, models,
>       unique functions, key points, etc. that distinguish the package from other
>       packages in the same area. This should also include a short motivation for the
>       package in general as well as motivation for inclusion in Bioconductor.
> 
I have updated the vignette to briefly explain SpliceWiz.

>     * [ ]  SUGGESTION: I would suggest not hiding results so if a user is running
>       through the vignette code they will be able to compare their results to yours
>       to be sure they are getting the correct output.
> 
Thanks Kayla. I have run all the code in the non-hidden cells and found that the
output reproduces what is displayed in the non-hidden cells in the vignette.

> ## Man pages
> 
>     * [ ]  REQUIRED: Usage of `dontrun{}` / `donttest{}` tags found in man page
>       examples. This is acceptable if the functions are run elsewhere, such as in
>       the vignette(s) or tests. I could not find where `calculateMappability()`,
>       `STAR_buildRef()`, `STAR_alignReads()`, `STAR_alignExperiment()`, or
>       `findFASTQ()` were run. Please make sure these functions are being run in code
>       somewhere (i.e., man page examples, vignette executable code, or runnable unit
>       tests).
I have removed all `dontrun{}` segments except the one for `Mappability-methods`.
`calculateMappability()` is now tested via unit tests (`tests\testthat\test-Mappa.R`)

The STAR methods have now been removed, as well as `findFASTQ`. They were wrapper
functions for the STAR RNA-seq aligner, that would only work on linux systems with
STAR installed.

>     * [ ]  REQUIRED: For those functions that are being run else where but you don't
>       want to have run in the man page examples use `donttest{}` over `dontrun{}`,
>       since `donttest{}` requires valid R code.
> 
I have tried using `donttest{}` for `Mappability-methods` segment but this throws a
warning in R CMD CHECK. This is because the example calls `Rsubread::buildindex`
which would only work if the current directory is the reference directory. Calling
`setwd` throws the warning. This is otherwise a working example that is essentially
replicated in `tests\testthat\test-Mappa.R`, and I ask that you consider this an exceptional
circumstance and allow this instance of `dontrun{}`.

> ## R code
> 
>     * [ ]  REQUIRED: Avoid `cat` and `print` outside of `show` methods.
> 
All `cat` calls occur in the context of the `show` method of the `ASEFilter` S4 object.

All `print` calls occur in the context of `renderPlotly()` segments of the SpliceWiz GUI.
They are essential to correctly display the plotly interactive plots in the GUI. I ask
that you consider `renderPlotly(print(x))` as equivalent to `show` in context
of the shiny-based GUI, otherwise there is no way to render plots via the shiny app.

I'd be grateful if you could re-review SpliceWiz. On a side note, it seems that the MacOS
issues has resolved itself. Thanks!

**Comment by Kayla-Morrell** [comment] 2022-07-05 17:24
@alexchwong - Thank you for the thorough comments and making the necessary changes. I have looked everything over and I'd be more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment] 2022-07-06 18:27
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alexchwong.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpliceWiz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpliceWiz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-07-06 18:27 UTC
Labels: OK, 3a. accepted
