### ISSUE TITLE
BloodCancerMultiOmics2017

### ISSUE THREAD

**Issue by MalgorzataOles** [Bioconductor/Contributions#568] opened 2017-11-28 23:43 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MalgorzataOles/BloodCancerMultiOmics2017

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

**Comment by lshep** [comment] 2017-11-30 13:40
Continuing the conversation from [pace](https://github.com/Bioconductor/Contributions/issues/551):
Packages are generally expected to meet the package guidelines which require a check time in < 5 min so 10 is already double this allotted amount; there are exceptions in the case of workflows and some experiment packages but this is decided on a per package basis.  You indicated that the package takes > 1 hr to build;  This will not be allowable even on the daily builders.  It will never build under the daily builder time constraints, it must be reduced to well under the max time limit or should be converted to a workflow.

**Comment by MalgorzataOles** [comment] 2017-12-04 13:06
Hi Lori,
to be more precise, package BUILD and CHECK takes 1h01 and 1h04, respectively. This is due to the vignettes which recapitulate the complete analysis of multi-omics data for the paper (in press) and thus, take long time to execute. I thought that experimental data packages are there in Bioconductor to promote research reproducibility, and in order to publish this piece of research in such fashion I cannot do much about shortening the vignettes. Any interference with the code (like commenting out chunks with long execution times & pre-saving the intermediate steps, etc.) would void the reproducibility paradigm. The project wrapped up in the BloodCancerMultiOmics2017 package was huge, with multiple people involved and a lot of different analyses being performed. The package includes valuable data resource. It is easy to predict that the number of such broad studies will only increase in the future, so it would be really great if Bioconductor would support them by providing infrastructure to facilitate reproducible research. Please let me know if there is anything I could do here to publish the package under Bioconductor but still have it reproduce all the analyses?
Best wishes, Gosia

**Comment by lshep** [comment] 2017-12-04 17:01
Our current builders will not allow this for a software or experiment data package; the package will always TIMEOUT.  I will discuss the need for a better solution with members of the core team (@mtmorgan @hpages ).  Currently, if you cannot shorten the vignette, the only option would be to include the package as a workflow. Would you like to include in Bioconductor as a workflow?

**Comment by hpages** [comment] 2017-12-04 21:21
Hi @MalgorzataOles,

A workflow package is likely to be the right choice. I'm just mentioning an alternative approach that we discussed today with Lori which is to submit an ordinary software package and use intermediate pre-computed datasets in your vignette. You can still maintain and guarantee reproducibility by re-computing these datasets on a regular basis and compare them to the pre-computed ones that are included in the package. This re-computing and comparison can easily be automated via _long tests_.

_Long tests_ are a new feature that was announced on the bioc-devel mailing list about 1 month ago: https://stat.ethz.ch/pipermail/bioc-devel/2017-November/012326.html

They are basically like the classic tests that one would put in the `tests/` folder of a package except that they need to be put in the `longtests/` folder and then will be run by our build system once a week with a 6 h timeout limit. If the pre-computed datasets are too big for inclusion in the software package (which should be limited to 4Mb), then they should go in a companion data experiment package.

Please refer to the announcement on bioc-devel for more information. Don't hesitate to ask on the bioc-devel mailing list if you have questions or need help with this.

Best,
H.

**Comment by hpages** [comment] 2017-12-05 14:15
Hi @MalgorzataOles,

After further discussion today at EuroBioc2017 with someone you know and Martin Morgan, we've decided to double the timeout limit from 40 to 80 min our daily data experiment builds (https://bioconductor.org/checkResults/devel/data-experiment-LATEST/). Andrzej made the point that the real nature of BloodCancerMultiOmics2017 is a data experiment package, something I didn't realize earlier, so it really belongs to our data-experiment repository. So you don't need to change anything to the package for now.

@lshep: Is it worth tweaking the SPB to also allow 80 min for data experiment packages (recognizable by the presence of `ExperimentData` in their `biocViews` field)? How hard would that be? For now we (reviewers) can always start a review even though the SPB reports timeouts, as long as we know what's going on...

H.

**Comment by MalgorzataOles** [comment] 2017-12-05 15:30
This is really great news, thank you! I am looking forward to collaborating throughout the review on getting the package published in Bioc.
Best wishes, Gosia

**Comment by lshep** [comment] 2017-12-05 16:10
I can tweak the SPB to align with this time constraint.  I'll review when I get back from BiocEurope.

**Comment by lshep** [comment] 2017-12-13 12:38
I have increased the time on the single package builder for data experiment packages.  Please see ERROR, WARNINGS and current NOTES.

**Comment by MalgorzataOles** [comment] 2017-12-13 12:50
Thank you Lori for increasing the time for building experiment data packages. BiocCheck throws an error caused by a bug which I reported already in June: https://github.com/Bioconductor/BiocCheck/issues/17

**Comment by lshep** [comment] 2017-12-13 12:52
I'll speak to the team about this.  In the meantime can you look at the Warnings and Notes.

**Comment by hpages** [comment] 2017-12-15 04:52
Hi @lshep, @MalgorzataOles,

Just to let you know that I've doubled the timeout limit from 40 to 80 min for our daily data experiment builds.This will be reflected on the daily report in devel (https://bioconductor.org/checkResults/devel/data-experiment-LATEST/) and release (https://bioconductor.org/checkResults/release/data-experiment-LATEST/), starting tomorrow evening.

H.

**Comment by lshep** [comment] 2018-01-17 15:53
Sorry for the long delay. There were some issues that were preventing me for be able to build and check the package locally. 

It looks in fairly good order. 

Please correct all the notes in the build report esp those concerning
- [ ] R dependencies in code
- [ ] global variable and function definition

Vignettes:
pace-dataOverview.Rmd
- [ ] The experimentHub section seems wrong - You would not generally use loadResource you would query to find the resource and [[ -  did the data ever get put into experimenthub? I don't think it did - were you still interested in doing this? 
pace.Rmd
- [ ] What does PACE stand for? Since the package name changed does this reference also need to change? 

Please bump the version and kick off a new build once the above are addressed and comment back here. 
Cheers

**Comment by MalgorzataOles** [comment] 2018-01-27 15:21
Thank you Lori. I addressed all the points from your last comment:

- "R dependencies in code" and "global variable and function definition" don't produce any NOTEs anymore

- names of the vignettes were changed from PACE to current and final name of the package

- the way to load ExperimentHub resource was changed according to your comment, and the submission process of the above resource was started

Greetings,
Małgorzata

**Comment by lshep** [comment] 2018-02-05 12:49
Please update the ExperimentHub section and then this will be ready for acceptance.  Also please submit CLLmethylation package as soon as possible.  Cheers.

**Comment by MalgorzataOles** [comment] 2018-02-06 11:28
AdditionalPackage: https://github.com/MalgorzataOles/CLLmethylation

**Comment by lshep** [comment] 2018-02-06 13:06
A few minor notes on the CLLmethylation package -   
1. Please add a NEWS file for potential updates and changes
2.  in the inst/scripts/make-data.R  we normally like some display of how the data was generated from raw files - even if it is not entirely executable and more like sudo code 
3. please add to vignette/readme the installation instructions through bioconductor. 

Once these are addressed I think the packages will be ready for acceptance.  
Cheers

**Comment by MalgorzataOles** [comment] 2018-02-07 22:52
Hi Lori,

thank you and I'm sorry that I forgot to report back here. I addressed all your points: added README with installation instructions, added NEWS and code which produces the object. I also included appropriate citation.

Cheers,
Małgorzata

**Comment by lshep** [comment] 2018-02-09 12:40
Thank you! Minor Note.  The NEWS file should not have .Rd extension -  should just be NEWS which is why it isn't finding it in the build report. 

Marking as accepted but please considering making that update.

**Comment by MalgorzataOles** [comment] 2018-02-09 13:19
Thank you very much Lori for all your efforts troughout this journey! That is great news! I changed NEWS.Rd to NEWS, bumped the version and pushed the changes.
All the best,
Małgorzata

**Comment by mtmorgan** [comment] 2018-02-12 14:57
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MalgorzataOles.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"BloodCancerMultiOmics2017\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BloodCancerMultiOmics2017

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by mtmorgan** [comment] 2018-02-12 14:57
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MalgorzataOles.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CLLmethylation\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CLLmethylation

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Closed by mtmorgan** 2018-02-12 14:57 UTC
Labels: 3a. accepted, OK
