### ISSUE TITLE
autonomics

### ISSUE THREAD

**Issue by bhagwataditya** [Bioconductor/Contributions#1874] opened 2021-02-02 19:02 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhagwataditya/autonomics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment] 2021-02-12 10:11
12 February, 2021

DESCRIPTION

- I'm concerned that the large number of dependencies (149, I think) makes your package very fragile and difficult to maintain. Give serious consideration to reducing dependencies, e.g., through restriction of functionality to those central and novel to your package.

vignettes

- looks good!

- using_autonomics.Rmd: 63 do NOT write to the 'home directory'; instead use `tempdir()` / `fl <- tempfile(); dir.create(fl)`

- include `sessionInfo()` in final section

R (comments apply throughout code)

- impressive!

- 0_download.R:18 how is the user to know what valid file names are? Generally, the parameter documentation strings are very terse; a user reading the help pages would have difficultly understanding what valid values are

- 0_download.R:46 use `tempdir()` / `tempfile()` for default download location; consider using [BiocFileCache][] to manage file downloads.

[BiocFileCache]: https://bioconductor.org/packages/BiocFileCache

- 0_import.R:79 use of `globalVariables()` masks potentially important information; use programming idioms (e.g., `dplyr::.data` and quoted arguments) to avoid need for this. Note also that `globalVariables(c("."))` makes 0_download.R:49 unnecessary.

- 1_filter.R:91 use `&&` for scalar comparison, e.g., to 'short circuit' evaluaton of rhs when lhs is FALSE.

- 1_filter.R:248 I find this indentation style hard to read; consider

    ```
    analysis(object)$nsamples %<>%
        c(structure(sum(idx), names = expr_text(condition)))
    ```
    
- 1_filter.R:263 consider adopting `message()`, or at least consistent use of `cmessage()` (see line 242 for a similar message presented with `message()`). Is indentation by three tabs really helpful? Consider output to a standard 'terminal' of 80 characters. Also, tabs are configurable in most shells, e.g., to 8 spaces, so (a) these consume signifcant amount of line real estate and (b) generate inconsistent output across systems.

- 1_get_set.R:52 I do not think it is helpful to the user to re-define the interface to standard classes, or to re-define generics defined in Bioconductor base packages -- a user loading your package will not be able to use `exprs()` on the eSet class hierarchy for which it was intended. One possibility, if the goal is to have a unified vocabulary, is to use a prefix `auto_exprs` or similar and define methods for data types you wish to support.

test

- It would be very useful to develop unit tests that cover a signficant amount of your code. The 'long tests' look like they are 'integration' tests covering high-level functionality; in contrast unit tests provide fine-grained assessment of whether, e.g., numerical results on demonstration data, including edge cases such as a SummarizedExperiment with no rows / columns, produce expected results.

**Comment by bhagwataditya** [comment] 2021-02-14 11:15
Thank you Martin, for the nice review. I will accommodate your recommendations in the coming few days and then get back!

**Comment by bhagwataditya** [comment] 2021-03-17 16:59
17 March 2021, 

Dear Martin,

> * I'm concerned that the large number of dependencies (149, I think) makes your package very fragile and difficult to maintain. Give serious consideration to reducing dependencies, e.g., through restriction of functionality to those central and novel to your package.

I moved all non-essential dependencies to Suggests.

> vignettes
> 
> * looks good!
> * using_autonomics.Rmd: 63 do NOT write to the 'home directory'; instead use `tempdir()` / `fl <- tempfile(); dir.create(fl)`

Thank you :-). I am now using BiocFileCache, as you suggested.

> * include `sessionInfo()` in final section

Done.

> R (comments apply throughout code)
> 
> * impressive!
> * 0_download.R:18 how is the user to know what valid file names are? Generally, the parameter documentation strings are very terse; a user reading the help pages would have difficultly understanding what valid values are

Thank you :-). I updated the documentation so that it shows all valid filenames

> * 0_download.R:46 use `tempdir()` / `tempfile()` for default download location; consider using [BiocFileCache](https://bioconductor.org/packages/BiocFileCache) to manage file downloads.

Oh, interesting suggestion, download_data now uses BiocFileCache.

> * 0_import.R:79 use of `globalVariables()` masks potentially important information; use programming idioms (e.g., `dplyr::.data` and quoted arguments) to avoid need for this. Note also that `globalVariables(c("."))` makes 0_download.R:49 unnecessary.

all utils::globalVariables(.) lines have been replaced.

> * 1_filter.R:91 use `&&` for scalar comparison, e.g., to 'short circuit' evaluaton of rhs when lhs is FALSE.

Done

> * 1_filter.R:248 I find this indentation style hard to read; consider
>   ```
>   analysis(object)$nsamples %<>%
>       c(structure(sum(idx), names = expr_text(condition)))
>   ```

Done

> * 1_filter.R:263 consider adopting `message()`, or at least consistent use of `cmessage()` (see line 242 for a similar message presented with `message()`). Is indentation by three tabs really helpful? Consider output to a standard 'terminal' of 80 characters. Also, tabs are configurable in most shells, e.g., to 8 spaces, so (a) these consume signifcant amount of line real estate and (b) generate inconsistent output across systems.

I now use message consistently everywhere. The tabs are designed like this to allow fit into a larger whole, so I think it would better to keep them like this.

> * 1_get_set.R:52 I do not think it is helpful to the user to re-define the interface to standard classes, or to re-define generics defined in Bioconductor base packages -- a user loading your package will not be able to use `exprs()` on the eSet class hierarchy for which it was intended. One possibility, if the goal is to have a unified vocabulary, is to use a prefix `auto_exprs` or similar and define methods for data types you wish to support.

True. Now renamed into values()

> test
> 
> * It would be very useful to develop unit tests that cover a signficant amount of your code. The 'long tests' look like they are 'integration' tests covering high-level functionality; in contrast unit tests provide fine-grained assessment of whether, e.g., numerical results on demonstration data, including edge cases such as a SummarizedExperiment with no rows / columns, produce expected results.

True, unit tests have now been added for all core functionality.

Looking forward to your feedback!

Aditya

**Comment by vjcitn** [comment] 2021-03-19 13:29
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bhagwataditya.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("autonomics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/autonomics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-03-19 13:29 UTC
Labels: 3a. accepted
