### ISSUE TITLE
topdownr

### ISSUE THREAD

**Issue by sgibb** [Bioconductor/Contributions#512] opened 2017-10-04 21:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/sgibb/topdownrdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput ~genomic~ *proteomic* data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

---

*This is just the data package for* https://github.com/sgibb/topdownr.

**Comment by sgibb** [comment] 2017-10-05 12:34
AdditionalPackage: https://github.com/sgibb/topdownr

**Comment by sgibb** [comment] 2017-10-05 17:52
I am somehow puzzled with the build failures on Windows.

I can't reproduce the test failure 1 and 2 in the penultimate build report (neither on Windows nor on Linux): https://bioconductor.org/spb_reports/topdownr_buildreport_20171005084652.html
>  1. Failure: show (@test_FragmentViews.R#46) 
>  2. Failure: show (@test_FragmentViews.R#62) 

The current build fails on Windows because of missing `mzR`: https://bioconductor.org/spb_reports/topdownr_buildreport_20171005130806.html
> Error in library.dynam(lib, package, package.lib) : 
  DLL 'mzR' not found: maybe not installed for this architecture?

Is there a way to trigger a build without increasing the version number or should I increase the number and hope that `mzR` is available on Windows?

**Comment by vobencha** [comment] 2017-10-05 17:57
I would just bump the version to get a new build. Once the package is in release it's bumped to 1.0.0 anyhow so these previous 'z' bumps don't matter.

I just updated R to 3.4.1 on the windows builders this morning (we've decided to not use 3.4.2; long story soon to be posted to the list). Let's get a build on 3.4.1 and see what the errors are.

Thanks.
Valerie

**Comment by vobencha** [comment] 2017-10-05 18:00
It's possible the SPB did run after I updated. Because the nightly builds have not run yet not all dependencies are installed. Either your package or one it depends on my not specify a dependency. I'll need some time to look into this but have a meeting now. I'll get back after I've done some checking.

**Comment by vobencha** [comment] 2017-10-13 17:55
I'll get this review done today.
Valerie

**Comment by vobencha** [comment] 2017-10-13 20:09
Hi,

Data package:

1) Data should be under inst/extdata/ not just inst/
2) man page

    a) Mention that there are 323 files.
```
~/topdownrdata/inst >find . -type f | wc -l
323
```
b) Describe the 4 categories of files:
```
~/topdownrdata/inst >ls 2017_06_29_myo/
experiments  fasta  header  mzml
```
c) Explain why you need all 4 categories to run an analysis. How would the user use these files together? In the example in the man page, load the data and do some manipulation. Show the user how the data are intended to be used.

You have this info in the vignette of the software package. You can reuse some/all of that - just include enough to give a big picture idea of what's going on.

Software package:
No substantial comments/suggestions here. Package looks good, nice job with the documentation.

Valerie

**Comment by sgibb** [comment] 2017-10-15 19:50
Dear Valerie, thanks for your review!

>    1. Data should be under inst/extdata/ not just inst/

Done. Now I get a few NOTEs about non-portable file names:
```
* checking for portable file names ... NOTE
Found the following non-portable file paths:
  topdownrdata/inst/extdata/2017_06_29_myo/experiments/myo_1211_ETDReagentTarget_1e+06_1.experiments.csv.gz
  topdownrdata/inst/extdata/2017_06_29_myo/experiments/myo_1211_ETDReagentTarget_1e+06_2.experiments.csv.gz
...
```

Is that a real problem? Should I shorten these paths? (I could simply rename the `experiments` folder into `exp` which should fix it.)

> a) Mention that there are 323 files.
> b) Describe the 4 categories of files:
> c) Explain why you need all 4 categories to run an analysis. How would the user use these files together? 

Done, please see https://github.com/sgibb/topdownrdata/blob/80ba5005382597f84edd4c408bcc94cc12bb57b9/man/topdownrdata-package.Rd#L16-L47

> In the example in the man page, load the data and do some manipulation. Show the user how the data are intended to be used.

In that case I have to add `topdownr` to *Suggests:* Wouldn't that create a cylcic dependency
(`topdownr` suggests `topdownrdata` and `topdownrdata` suggests `topdownr`)?

**Comment by vobencha** [comment] 2017-10-16 14:33
Hi,
Thanks for making the changes.

* The data package contains a class defined in the software package -> data package must Depend on software. The software package is enhanced by the data package but does not need it to function -> software Suggests the data package. 

    With this arrangement you will not have a cyclic dependency. There will be a little snafu when we initially add both packages to the build system but that should only take one nightly build to work itself out.

* I'm not seeing the 'non-portable' NOTE in the SPB output. Where are you seeing this?

    I would think the problem is related to the '+' in the file name itself, not the 'experiments' directory. For the package to work on Windows, Linux and OS X you must use file names that work on all platforms. The easiest way to do this is to stick to letters, numbers, underscores and dashes.

Valerie

**Comment by sgibb** [comment] 2017-10-16 20:29
Now `topdownrdata` depends on `topdownr` and `topdownr` suggests `topdownrdata`.

I also added a hint to the software package vignettes and an example to the data package as 
you suggested:
https://github.com/sgibb/topdownrdata/blob/b453cb5ed255d55eb822b5fafafb96b53f8a5803/man/topdownrdata-package.Rd#L100-L151

> I'm not seeing the 'non-portable' NOTE in the SPB output. Where are you seeing this?

It was on my local machine with Debian stretch and R-devel. In the old build report it was not present but now *malbec* throws a NOTE, too:
https://bioconductor.org/spb_reports/topdownrdata_buildreport_20171016154900.html#malbec1_check_anchor

Could we ignore it? Otherwise I will shorten the path.

**Comment by vobencha** [comment] 2017-10-16 20:51
If the NOTE/WARNING/ERROR is not in the SPB output we don't need to worry about it. Packages are approved. Thanks for your work on these.
Valerie

**Comment by mtmorgan** [comment] 2017-10-22 17:09
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sgibb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"topdownrdata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/topdownrdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment] 2017-10-22 17:09
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sgibb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"topdownr\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/topdownr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Closed by mtmorgan** 2017-10-22 17:09 UTC
Labels: 3a. accepted, OK
