### ISSUE TITLE
ComPrAn

### ISSUE THREAD

**Issue by Petra-P** [Bioconductor/Contributions#1828] opened 2020-12-19 20:41 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Scavetta/ComPrAn

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment] 2021-01-19 19:17
Hi @Petra-P ,

Thanks for submitting ComPrAn. Package looks good and is well documented but I noticed that some plots in the proteinWorkflow.html vignette are empty. The problematic plots are:

- In the "Co-migration plot of single protein group between label states" section:

![Screenshot from 2021-01-19 11-06-52](https://user-images.githubusercontent.com/8810451/105081257-c8eb3380-5a46-11eb-9de6-36ce03bbcae4.png)

- In the "Co-migration plot of two protein groups within label state" section:

![Screenshot from 2021-01-19 11-07-24](https://user-images.githubusercontent.com/8810451/105081270-cd175100-5a46-11eb-8596-868c708c5c9f.png)

Also the SILACcomplexomics.html vignette repeats these 2 sections and has the same problematic figures. Note that this kind of repetition in the documentation should be avoided ("Don't Repeat Yourself (DRY)" principle in software engineering which also applies to the documentation).

Thanks,
H.

**Comment by Petra-P** [comment] 2021-01-26 13:13
Hi @hpages ,

Thank you very much for your comments. I edited the vignettes, removing the repeated part and replacing it with a link between SILACcomplexomics.html and proteinWorkflow.html. 

I am not sure what might be causing the plots to show empty as I was not able to replicate the issue. After running 
`devtools::install_github("https://github.com/Scavetta/ComPrAn", build_vignettes = TRUE)`
`browseVignettes("ComPrAn")`
I could see both plots in proteinWorkflow.html on Windows (R version 4.0.3 (2020-10-10); Platform: x86_64-w64-mingw32/x64 (64-bit); Running under: Windows 10 x64 (build 19041)) and Linux (R version 4.0.3 (2020-10-10); Platform: x86_64-pc-linux-gnu (64-bit); Running under: Ubuntu 20.04.1 LTS). Is there anything you would suggest to try to identify and solve the issue? Thank you!

**Comment by hpages** [comment] 2021-02-19 08:46
Hi @Petra-P ,

It looks like you're using the wrong version of R. You're submitting a package for inclusion to BioC 3.13 which is based on R 4.1 (the current devel version of R) so you need to use that version to develop and test your package. After running:
```
library(devtools)
devtools::install_github("https://github.com/Scavetta/ComPrAn", build_vignettes=TRUE)
library(ComPrAn)
browseVignettes("ComPrAn")
```
here is my **sessionInfo()**:
```
R Under development (unstable) (2021-02-05 r79941)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Matrix products: default
BLAS:   /home/hpages/R/R-4.1.r79941/lib/libRblas.so
LAPACK: /home/hpages/R/R-4.1.r79941/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ComPrAn_0.99.2 devtools_2.3.2 usethis_2.0.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6           tidyr_1.1.2          prettyunits_1.1.1   
 [4] ps_1.5.0             assertthat_0.2.1     rprojroot_2.0.2     
 [7] digest_0.6.27        R6_2.5.0             cellranger_1.1.0    
[10] futile.options_1.0.1 ggplot2_3.3.3        pillar_1.4.7        
[13] rlang_0.4.10         curl_4.3             readxl_1.3.1        
[16] VennDiagram_1.6.20   rstudioapi_0.13      data.table_1.13.6   
[19] callr_3.5.1          DT_0.17              shinyjs_2.0.0       
[22] desc_1.2.0           stringr_1.4.0        foreign_0.8-81      
[25] htmlwidgets_1.5.3    munsell_0.5.0        compiler_4.1.0      
[28] pkgconfig_2.0.3      pkgbuild_1.2.0       htmltools_0.5.1.1   
[31] tidyselect_1.1.0     tibble_3.0.6         rio_0.5.16          
[34] crayon_1.4.1         dplyr_1.0.4          withr_2.4.1         
[37] later_1.1.0.1        grid_4.1.0           gtable_0.3.0        
[40] lifecycle_1.0.0      DBI_1.1.1            magrittr_2.0.1      
[43] formatR_1.7          scales_1.1.1         zip_2.1.1           
[46] cli_2.3.0            stringi_1.5.3        cachem_1.0.4        
[49] fs_1.5.0             promises_1.2.0.1     remotes_2.2.0       
[52] testthat_3.0.2       futile.logger_1.4.3  ellipsis_0.3.1      
[55] generics_0.1.0       vctrs_0.3.6          openxlsx_4.2.3      
[58] lambda.r_1.2.4       RColorBrewer_1.1-2   tools_4.1.0         
[61] forcats_0.5.1        glue_1.4.2           purrr_0.3.4         
[64] hms_1.0.0            processx_3.4.5       pkgload_1.1.0       
[67] fastmap_1.1.0        colorspace_2.0-0     sessioninfo_1.1.1   
[70] shinydashboard_0.7.1 memoise_2.0.0        haven_2.3.1         
```
Best,
H.

**Comment by LiNk-NY** [comment] 2021-03-05 19:38
Hi @Petra-P @hpages 

I've tested this on my computer and I can see the points
with Bioconductor 3.13. 

Best,
Marcel

<details> <summary> sessionInfo </summary>
> sessionInfo()
R Under development (unstable) (2020-12-12 r79621)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ComPrAn_0.99.2

loaded via a namespace (and not attached):
 [1] zip_2.1.1            Rcpp_1.0.6           later_1.1.0.1       
 [4] cellranger_1.1.0     pillar_1.5.0         compiler_4.1.0      
 [7] formatR_1.7          RColorBrewer_1.1-2   futile.logger_1.4.3 
[10] shinyjs_2.0.0        tools_4.1.0          forcats_0.5.1       
[13] futile.options_1.0.1 digest_0.6.27        lifecycle_1.0.0     
[16] tibble_3.1.0         gtable_0.3.0         debugme_1.1.0       
[19] pkgconfig_2.0.3      rlang_0.4.10         openxlsx_4.2.3      
[22] DBI_1.1.1            curl_4.3             VennDiagram_1.6.20  
[25] haven_2.3.1          rio_0.5.26           stringr_1.4.0       
[28] dplyr_1.0.4          hms_1.0.0            generics_0.1.0      
[31] vctrs_0.3.6          htmlwidgets_1.5.3    shinydashboard_0.7.1
[34] grid_4.1.0           DT_0.17              tidyselect_1.1.0    
[37] data.table_1.14.0    glue_1.4.2           R6_2.5.0            
[40] fansi_0.4.2          readxl_1.3.1         foreign_0.8-81      
[43] tidyr_1.1.3          purrr_0.3.4          ggplot2_3.3.3       
[46] lambda.r_1.2.4       magrittr_2.0.1       promises_1.2.0.1    
[49] scales_1.1.1         ellipsis_0.3.1       htmltools_0.5.1.1   
[52] assertthat_0.2.1     colorspace_2.0-0     utf8_1.1.4          
[55] stringi_1.5.3        munsell_0.5.0        crayon_1.4.1        
</details>

**Comment by hpages** [comment] 2021-03-05 20:34
Thanks @LiNk-NY for testing this. Really confusing that you can't reproduce this given that you're using the exact same OS as I do (Ubuntu 20.10).

BTW an easier way to reproduce (for me) is to just run the `oneGroupTwoLabelsCoMigration` example:
```
library(ComPrAn)
example(oneGroupTwoLabelsCoMigration)
# ...
# Hit <Return> to see next plot:
```
After hitting \<Return\> I get the following warning:
```
Warning message:
In grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size) :
  semi-transparency is not supported on this device: reported only once per page
```
and the following plot:
![Screenshot from 2021-03-05 12-22-44](https://user-images.githubusercontent.com/8810451/110169458-8ccd2180-7dad-11eb-95f4-aa824ca48f20.png)

However, if I use `alphaValue=1`:
```
oneGroupTwoLabelsCoMigration(forAnalysis, max_frac, groupDV, groupName, alphaValue=1)
```
then everything is fine:
![Screenshot from 2021-03-05 12-27-48](https://user-images.githubusercontent.com/8810451/110169916-3dd3bc00-7dae-11eb-9230-6b24b44172b1.png)

@Petra-P So maybe an easy workaround would be to just set `alphaValue` to 1 by default?

**Comment by LiNk-NY** [comment] 2021-03-05 21:25
@hpaes I am able to output the plot.
Could it be differences in the R-devel version? 
I am not sure what is causing this. 

![image](https://user-images.githubusercontent.com/4392950/110175167-56a09980-7dcf-11eb-9beb-041023f288bb.png)

**Comment by hpages** [comment] 2021-03-05 21:55
Not sure either. I have the exact same `capabilities()`.

FWIW I also tried with an older R-devel installation that I kept around (2020-11-18 r79449) and got the same thing (i.e. an empty plot). Maybe the semi-transparency capability of the X11 device is provided via an additional deb package? I'm starting to suspect a missing deb package in the X11 family.

This problem is real i.e. many users have reported the "semi-transparency is not supported on this device" problem. Until we understand what's going on exactly, let's avoid using `alphaValue` < 1.

**Comment by Petra-P** [comment] 2021-03-07 01:44
Hi @hpages  @LiNk-NY ,
Thank you for testing the package! I changed the default value of  `alphaValue` to 1 in both functions to avoid the warning message for now.  I also added a `CITATION` file as paper describing ComPrAn has been published recently (https://doi.org/10.1016/j.bbabio.2021.148399).

I am getting the semi-transparency waring message on Linux with R 4.1 (session info below). When using Rstudio I was able to display the plot correctly with alphaValue <1 after setting `options(bitmapType="cairo")`.

On Windows with R 4.1 plot is displayed fine with alphaValue<1 (session info below).

Best,
Petra

Linux **sessionInfo()**:
```
R Under development (unstable) (2021-02-20 r80030)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

atrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8
 [2] LC_NUMERIC=C
 [3] LC_TIME=sk_SK.UTF-8
 [4] LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=sk_SK.UTF-8
 [6] LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=sk_SK.UTF-8
 [8] LC_NAME=C
 [9] LC_ADDRESS=C
[10] LC_TELEPHONE=C
[11] LC_MEASUREMENT=sk_SK.UTF-8
[12] LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods
[7] base

other attached packages:
[1] ComPrAn_0.99.2

loaded via a namespace (and not attached):
 [1] zip_2.1.1
 [2] Rcpp_1.0.6
 [3] later_1.1.0.1
 [4] cellranger_1.1.0
 [5] pillar_1.5.0
 [6] compiler_4.1.0
 [7] formatR_1.7
 [8] RColorBrewer_1.1-2
 [9] futile.logger_1.4.3
[10] shinyjs_2.0.0
[11] forcats_0.5.1
[12] futile.options_1.0.1
[13] tools_4.1.0
[14] digest_0.6.27
[15] lifecycle_1.0.0
[16] tibble_3.1.0
[17] gtable_0.3.0
[18] pkgconfig_2.0.3
[19] rlang_0.4.10
[20] openxlsx_4.2.3
[21] curl_4.3
[22] VennDiagram_1.6.20
[23] haven_2.3.1
[24] rio_0.5.16
[25] withr_2.4.1
[26] stringr_1.4.0
[27] dplyr_1.0.4
[28] hms_1.0.0
[29] generics_0.1.0
[30] vctrs_0.3.6
[31] htmlwidgets_1.5.3
[32] shinydashboard_0.7.1
[33] grid_4.1.0
[34] DT_0.17
[35] tidyselect_1.1.0
[36] glue_1.4.2
[37] data.table_1.14.0
[38] R6_2.5.0
[39] fansi_0.4.2
[40] readxl_1.3.1
[41] foreign_0.8-81
[42] farver_2.0.3
[43] tidyr_1.1.2
[44] purrr_0.3.4
[45] ggplot2_3.3.3
[46] lambda.r_1.2.4
[47] magrittr_2.0.1
[48] promises_1.2.0.1
[49] scales_1.1.1
[50] ellipsis_0.3.1
[51] htmltools_0.5.1.1
[52] colorspace_2.0-0
[53] utf8_1.1.4
[54] stringi_1.5.3
[55] munsell_0.5.0
[56] crayon_1.4.1
```
Windows **sessionInfo()**:
```
R Under development (unstable) (2021-02-27 r80043)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Slovak_Slovakia.1250  LC_CTYPE=Slovak_Slovakia.1250
[3] LC_MONETARY=Slovak_Slovakia.1250 LC_NUMERIC=C
[5] LC_TIME=Slovak_Slovakia.1250

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ComPrAn_0.99.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6           tidyr_1.1.3          prettyunits_1.1.1
 [4] ps_1.5.0             assertthat_0.2.1     rprojroot_2.0.2
 [7] digest_0.6.27        utf8_1.1.4           R6_2.5.0
[10] cellranger_1.1.0     futile.options_1.0.1 ggplot2_3.3.3
[13] pillar_1.5.1         rlang_0.4.10         curl_4.3
[16] readxl_1.3.1         VennDiagram_1.6.20   rstudioapi_0.13
[19] data.table_1.14.0    callr_3.5.1          DT_0.17
[22] shinyjs_2.0.0        desc_1.2.0           devtools_2.3.2
[25] stringr_1.4.0        foreign_0.8-81       htmlwidgets_1.5.3
[28] munsell_0.5.0        compiler_4.1.0       pkgconfig_2.0.3
[31] pkgbuild_1.2.0       htmltools_0.5.1.1    tidyselect_1.1.0
[34] tibble_3.1.0         rio_0.5.26           fansi_0.4.2
[37] later_1.1.0.1        crayon_1.4.1         dplyr_1.0.5
[40] withr_2.4.1          grid_4.1.0           gtable_0.3.0
[43] lifecycle_1.0.0      magrittr_2.0.1       formatR_1.7
[46] scales_1.1.1         zip_2.1.1            cli_2.3.1
[49] stringi_1.5.3        cachem_1.0.4         farver_2.1.0
[52] promises_1.2.0.1     fs_1.5.0             remotes_2.2.0
[55] testthat_3.0.2       futile.logger_1.4.3  ellipsis_0.3.1
[58] generics_0.1.0       vctrs_0.3.6          openxlsx_4.2.3
[61] lambda.r_1.2.4       RColorBrewer_1.1-2   tools_4.1.0
[64] forcats_0.5.1        glue_1.4.2           purrr_0.3.4
[67] hms_1.0.0            processx_3.4.5       pkgload_1.2.0
[70] fastmap_1.1.0        colorspace_2.0-0     sessioninfo_1.1.1
[73] shinydashboard_0.7.1 memoise_2.0.0        haven_2.3.1
[76] usethis_2.0.1
```

**Comment by hpages** [comment] 2021-03-09 07:54
Thanks!

**Comment by vjcitn** [comment] 2021-03-17 14:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Petra-P.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ComPrAn")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ComPrAn

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-03-17 14:02 UTC
Labels: 3a. accepted, OK
