### ISSUE TITLE
Affinity Network Fusion (ANF)

### ISSUE THREAD

**Issue by BeautyOfWeb** [Bioconductor/Contributions#469] opened 2017-09-01 00:00 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BeautyOfWeb/ANF

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by BeautyOfWeb** [comment] 2017-09-01 00:01
AdditionalPackage: https://github.com/BeautyOfWeb/HarmonizedTCGAData

**Comment by lshep** [comment] 2017-09-20 16:43
@BeautyOfWeb @dvantwisk will provide some feedback on the software package soon.  The data package HarmonizedTCGAData, provides a very large data file: Wall.rda.  We would require this package to be transitioned into an ExperimentHubData package that would provide access to the data via Biocondcutor's ExperimentHub.   Documentation on the required files and process in achieving this can be found [here](https://github.com/Bioconductor/ExperimentHub/blob/master/vignettes/CreateAnExperimentHubPackage.Rmd)

**Comment by BeautyOfWeb** [comment] 2017-10-11 02:59
Hello @lshep ! Sorry for late reply. I have transformed HarmonizedTCGAData into an ExperimentHubData package and uploaded data to S3 today. I still need assistance to add the data to the production database and finalize the data package. Thank you very much.

**Comment by lshep** [comment] 2017-10-11 10:57
Has the location of your repository changed? https://github.com/BeautyOfWeb/HarmonizedTCGAData  returned a page not found and I will need the metadata.csv file from the package to add to the production database.

**Comment by lshep** [comment] 2017-10-11 11:34
I found your repo - you renamed it so it will have to be resubmitted here as additional package with the correct link  - you will also have to make sure the webhook is set up on that repository.  

If you would like to use "HamornizedTCGADataset/" as the name, then the directory on S3 of associated data should also be "HamornizedTCGADataset/"  

only the data files should be uploaded to S3.  You seem to have uploaded the entire package. Please try again uploading only the directories and files containing your data. 

The metadata.csv file needs an RDataPath field - 
```
> library(AnnotationHub)
> temp = readMetadataFromCsv("HamornizedTCGADataset/")
Error in readMetadataFromCsv("HamornizedTCGADataset/") : 
  missing fields in metadata file metadata.csv: RDataPath
```
This field should contain the file path in S3 that will be appended to "https://s3.amazonaws.com/experimenthub/":  The directory structure of the loaded files in S3
e.g 
"HamornizedTCGADataset/Wall.rds" 
or if you are going to include the data directory 
"HamornizedTCGADataset/data/Wall.rda"

Also the The BiocVersion in the metadata.csv should be 3.6  and if your package does not get approved by next Tue this will have to be updated to 3.7. 

Please let me know when you have made the above changes and uploaded the data to S3. The credentials I have previously sent for access should still be active.

**Comment by BeautyOfWeb** [comment] 2017-10-12 02:43
Hi @lshep ! Thank you very much for your detailed instruction! I have made the above changes:
1. Changed the repo's name back to HarmonizedTCGAData
2. Uploaded the data files to S3:
HarmonizedTCGAData\Wall.rda, HarmonizedTCGAData\project_ids.rda, HarmonizedTCGAData\surv.plot.rda
3. Added RDataPath field  in metadata.csv: HarmonizedTCGAData/Wall.rda, etc.
4. Changed BiocVersion in metadata.csv to 3.7

Since this is my first time to contribute to Bioconductor, I was not very familiar with the process. I really appreciated your detailed instructions. Please let me know if there is any other problem. Thanks!

**Comment by lshep** [comment] 2017-10-12 12:42
No problem at all. I have recently taken over managing this part of the system so there are details I forget to tell people as well. The BiocVersion could remain 3.6 for now. If it does not get approved by next Tue to be included in the 3.6 release then it should be 3.7  (I know this is a little confusing - sorry).   apparently the SourceVersion in metadata.csv cannot contain commas (just changing the date to June 29 2017). I fixed both of these on a temporary version I copied over to be able to add the data into the database but if you could fix in your metadata.csv that would be great.

The data has been added to Bioc devel 3.6 ExperimentHub as shown: 
```
> library(ExperimentHub)
> eh = ExperimentHub()
snapshotDate(): 2017-10-12
> query(eh, "HarmonizedTCGAData")
ExperimentHub with 3 records
# snapshotDate(): 2017-10-12 
# $dataprovider: Harmonized Cancer Datasets Genomic Data Commons Data Portal
# $species: Homo sapiens
# $rdataclass: Character, List, data.frame
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH1014"]]' 

           title                                                              
  EH1014 | Processed harmonized TCGA data of five cancer types for patient ...
  EH1015 | TCGA project IDs for 14551 cases                                   
  EH1016 | Survival Data for 12899 TCGA Cases                                 
```

**Comment by dvantwisk** [comment] 2017-10-12 14:16
Sorry for the delay!  We've completed the review.  There is a required change in vignettes that relates to submitting the data as an experimenthub package.  Once you are done making these changes, please message us back to tell us.

GENERAL:
- [CONSIDER] In many functions in this pacakge, I am seeing the parameter
`type` (or similar) that requires some kind of numeric scalar for input and
seems to direcetly refer to some kind of way to perform an operation.
This looks like it would be confusing for the user so it is recommended that you
use `match.arg()`.  For example, in the `spectral_clustering()` declaration use:
```
spectral_clustering <- function(A, k, type=c('Laplacian', 'Another_choice', verbose=FALSE)
```
And then call `type <- match.arg(type)` to get the user's input.  The default
option is the first option given in the vector.

DESCRIPTION
- [REQUIRED] License: Choose specific version of LGPL license.

NAMESPACE
- [CONSIDER] Use `importFrom()` to speicify specific symbols to import from a
package.

R/AffinityNetworkFusion.R
- [REQUIRED] L7: Misspelling - should be "'a' transition matrix ....".
- [REQUIRED] L19: Don't call an error here since this doesn't stop the program
from functioning.  `message()` is preferable to `print()` here.
- [REQUIRED] L34-39: Be specific with param types.  For example, what type of
object should a user input as `weight`?
- [REQUIRED] L66: In general, when giving diagnostic messages to the user about
how the program is performing a task, it is better to use `message()` than
'print()'.
- [REQUIRED] L73-75: Replace for loop with:
```
Wall <- lapply(Wall, function(elt) elt/rowSums(elt))
```
- [REQUIRED] L89, 94, 129: Call `warning()` instead of using `print()`.
- [REQUIRED] L112-115: Replace expensive copy and append pattern with:
```
Sall <- lapply(Wall, function(elt) kNN_graph(elt, K))
```
- [REQUIRED] L118: Use `seq_len()` instead of `:`.
- [REQUIRED] L149: Use `seq_len()` instead of `:`.

R/SpectralClustering.R
- [CONSIDER] L29: import `dnorm()` from `stats` package. Be sure to include the
stats package in description.
- [REQUIRED] L34: specify type of input for `Y`.
- [REQUIRED] L81: Use `message()` instead of `print()`. `paste()` is not
required either.
- [REQUIRED] L116: use `message()`.
- [CONSIDER] L174-175,180-182: Unnecessary to call functions from packages if already imported.
- [REQUIRED] L187-190: Use `message()`

tests
- [CONSIDER] Add unit tests using the `testthat` pacakge.

vignettes
- [REQUIRED] Do not use eval=FALSE in code blocks in vignettes.
- [CONSIDER] There are long chunks of code with explanation, consider being more
descriptive in these sections.
- [REQUIRED] L118-129: This section downloads Rdata from a github repositoru and
is not a reliable way of obtaining example data for a vignette.  Include the
Rdata files in an `inst/data` directory and load it from there.  In addition,
try to keep data files to a small size (none larger than 10Mb).

**Comment by BeautyOfWeb** [comment] 2017-10-13 20:51
Thank you very much @lshep ! I changed BiocVersion to 3.6 and  the date to "June 29 2017". I updated metadata.csv and vignettes, man/, etc. in GitHub. If there are other problems, please let me know. Thanks again!

**Comment by BeautyOfWeb** [comment] 2017-10-13 21:22
Hi @dvantwisk ! I really appreciated your many good suggestions and very detailed feedback!! I have made changes accordingly. 
1. I have changed the input parameter type as characters as you suggested using "type <- match.arg(type)". 
2. Used @importFrom when applicable. 
3. Used message() and warning() to replace print() when applicable.
4. Replaced unnecessary for loops with lapply()
5. Used seq_len() when applicable
6. Added more documentations in man/ and vignettes/
7. Added some unit tests using the testthat pacakge
8. Other required changes

There is one issue. Now the vignettes needs to run at least several minutes to reproduce all the results of the companion paper. Is that OK? (For demonstration of the usage of ANF, we don't need to reproduce all the figures in the paper, and it will take much less time.)

If there are still other problems I have missed, please let me know. Thank you very much!

**Comment by BeautyOfWeb** [comment] 2017-10-13 22:30
Hi @dvantwisk ! Since the vignettes takes more than 10 minutes to run, the build will fail. I have to temporarily use `eval=FALSE` in the last section of vignettes. The last section is to reproduce the results of paper, it will need to run ANF package 210 times, and generate figures. Is it OK to use `eval=FALSE` for that? Or should I remove this section?

Now there is still another build error on windows platform, which is related to loading data from the companion ExperimentHub package: HarmonizedTCGAData. I am not sure how to fix this error. Could you give me some hints on this? Thank you.

**Comment by llrs** [comment] 2017-10-16 15:42
Sorry to jump in the conversation but as a user in the vignette I would expect to learn how to use a package not how to reproduce a paper. If you want to provide code for your article (and the journal doesn't provide with enough space to do so) maybe it could be a separate vignette, or you could host it separately on github.

BTW, looking at the vignette, you might find useful to know that one can provide a function to perform to the combinations created with `combn`. In the vignette you also use sometimes `print` instead of `message`.

The package doesn't use any of the existing [MultiData](https://www.bioconductor.org/packages/MultiDataSet) or [MultiAssayExperiment](https://www.bioconductor.org/packages/MultiAssayExperiment) data structures when you are clearly using several data /omics (in the vignette miRNA and gene expression are mentioned). Maybe it is worth to mimic or use those structures in your packages to facilitate the usage of your package and integrate with other packages/methods.

**Comment by dvantwisk** [comment] 2017-10-16 18:55
I agree with @llrs that the vignette should show how the package functions instead of reproducing the results of paper.  Creating a separate vignette is a way of showing your results, but since you are getting a timeout due to this section of code, I would recommend removing it from the package and adding it to a separate github repository.  You can add a link to the end of your vignette to this repo showing the results of your experiment.

Putting `eval=FALSE` for code visible to the user in your vignette is not acceptable since the code must run correctly.

You should swap print with message in your vignette as well, as per the suggestion by @llrs.

I'll defer to @lshep for help on the error with ExperimentHub on Windows since she is more knowledgeable on the subject than me.

**Comment by BeautyOfWeb** [comment] 2017-10-16 23:21
Thank you very much @llrs and @dvantwisk for your good suggestions! 
1. As suggested I have create another repository storing the vignettes for reproducing results of a paper, added a link to it at the end the ANF vignettes.
2. I have swapped message with message in the vignettes. 
3. It is also a very good suggestion to use MultiData or MultiAssayExperiment data structures. However, the associated data package does not contain the original omic data, but only a list of patient affinity matrices calculated from omic datasets. 
The original data is downloaded from GDC data portal: the UUIDs of these10328 files are provided here: https://github.com/BeautyOfWeb/HarmonizedTCGAData/blob/master/inst/extdata/fileUUIDs.csv 
(These files are >30GB)
I have extracted 25 matrices from these files and stored them in .rda format. For these data, it is best to use MultiData or MultiAssayExperiment data structures as suggested by @llrs . However, since it is more than 10GB, I did not put it in this data package. I am not sure if it is worth to make another data package using MultiAssayExperiment data structure for this ~10GB data.
As for now, only the pre-computed patient affinity matrices (Wall.rda ~200MB) and other relevant information (project_ids.rda, surv.plot.rda) for cancer patient clustering were included in the package. These data can be directly used for cancer patient clustering algorithms that use patient affinity matrices as input. More details about the data processing procedure is provided in the data package: https://github.com/BeautyOfWeb/HarmonizedTCGAData/blob/master/inst/scripts/make-data.R

Again thank you very much for your suggestions and feedback!

**Comment by llrs** [comment] 2017-10-17 10:10
When I mentioned MultiDataSet and MultiAssayExperiment it was not only to provide the data in that format, but to make your functions available to work with those structures. So if a user uses them it would be compatible with your methods, but this is up to you (ie I am not an official reviewer of your package).

HTH

**Comment by dvantwisk** [comment] 2017-10-17 14:13
We didn't identify using `MultiDataSet` and `MultiAssayExperiment` in our original review, so we won't require it now.  Although, it would be useful functionality to support these objects as well as the list of matrices as input in the future, if possible.

I'm reviewing the new changes to your package and if everything is addressed, I'll move to accept the package today.

**Comment by lshep** [comment] 2017-10-17 14:26
The Data Package should also be checked and have a clean build report  - Please don't forget to make sure the webhook is set up on HarmonizedTCGAData -  Please resubmit the addtional package line as comment: 
`AdditionalPackage: https://github.com/BeautyOfWeb/HarmonizedTCGAData`

**Comment by dvantwisk** [comment] 2017-10-17 14:46
A few last nitpicks with your documentation:

R/AffinityNetworkFusion.R
- L51: you say an input is a "Boolean".  This type doesn't exist in R and should be corrected to `logical(1)`.

R/SpectralClustering.R
- L46: Use `logical(1)`.

**Comment by llrs** [comment] 2017-10-17 15:18
@dvantwisk About the `MultiDataSet` and `MultiAssayExperiment`, I was aware you didn't mention them that is one of the reasons I pointed to them. 
Lately there have been more attention on integration of several omics or other data types and having a standard class in Bioconductor would be ideal for future work.

**Comment by dvantwisk** [comment] 2017-10-17 15:31
`HarmonizedTCGA` should only have `ExperiemntHub` in its `Imports`, the packages should only used in the vignette, so it should be listed in the `Suggests` section.  It looks like you use `ANF` in `inst/scripts/make-data.R`, but it would be better to only include information on how to use the package in the vignettes.

**Comment by dvantwisk** [comment] 2017-10-17 18:37
Hello,
Can you please add the HarmonizedTCGA Experiemental Data Package again with, AdditionalPackage: https://github.com/BeautyOfWeb/HarmonizedTCGAData ? We'll need this done soon if we will accept you package today.

**Comment by BeautyOfWeb** [comment] 2017-10-17 23:26
AdditionalPackage: https://github.com/BeautyOfWeb/HarmonizedTCGAData

**Comment by BeautyOfWeb** [comment] 2017-10-17 23:44
Hello, @dvantwisk! Very sorry to reply late. (I only checked my email and read the messages until the evening today. In order to focus on my research project during the day, I disabled email notifications:()
1. I have changed Boolean to logical(1) in the package.
2. @lshep In the .csv file of HarmonizedTCGAData package, I changed BiocVersion to 3.7
3. @llrs thank you very much for your good suggestions. In the future development, I will definitely try my best to make use of existing data structures and consider interoperability and extensibility.

Thank you all for your help and feedback @dvantwisk @lshep @llrs . I have learned a lot during the process!

**Comment by dvantwisk** [comment] 2017-10-18 19:03
We have one last change to `HarmonizedTCGA`.  We can still include the package in the 3.6 release, but you'll need to change the `BiocVersion` in your metadata back 3.6.

**Comment by dvantwisk** [comment] 2017-10-18 19:51
I've accepted the package so it can be included in the 3.6 release, but the change to `HarmonizedTCGA`'s metadata mentioned above must still be made.

**Comment by BeautyOfWeb** [comment] 2017-10-18 23:08
I just changed BiocVersion back to 3.6. 
Thank you very much @dvantwisk !

**Comment by mtmorgan** [comment] 2017-10-22 17:09
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BeautyOfWeb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ANF\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ANF

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Comment by mtmorgan** [comment] 2017-10-22 17:09
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/BeautyOfWeb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"HarmonizedTCGAData\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HarmonizedTCGAData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Closed by mtmorgan** 2017-10-22 17:09 UTC
Labels: 3a. accepted, OK
