### ISSUE TITLE
ACE

### ISSUE THREAD

**Issue by jpoell** [Bioconductor/Contributions#759] opened 2018-05-24 12:18 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tgac-vumc/ACE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jpoell** [comment] 2018-05-28 09:20
Dear Bioconductor team member,

I have recently started the submission process of my R package “ACE”. In my most recent attempt, the build report mentions WARNINGS on the Windows system check. It does not specify any warnings in the report detail below though. Anything I should do to proceed with package submission? I hope to hear from Bioconductor soon!

Kind regards,

Jos Poell

Summary:
ERROR count: 0
WARNING count: 0
NOTE count: 10
For detailed information about these checks, see the BiocCheck
vignette, available at
https://bioconductor.org/packages/3.8/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#interpreting-bioccheck-output

**Comment by jpoell** [comment] 2018-05-28 14:26
One last thing I haven't found a good answer on: for Bioconductor submission I need to set the R dependency to version 3.5, but this is very annoying for anyone trying to install the package who runs a lower version of R (as a lot of potential users probably do). Currently I have to instruct them to download the repository, manually change the DESCRIPTION file, and build locally and install manually. Much more work than install_github("tgac-vumc/ACE"). Is there a workaround? If not, at what point (if ever) can I reduce the R version requirement?

Cheers, 

Jos Poell

**Comment by Liubuntu** [comment] 2018-06-05 13:57
HI @jpoell , 

The warning for Windows system comes from here: 
```
WARNING: check time exceeded 5 min. 
```
Since the windows do check longer than the other two platforms, so we can skip this warning and go ahead with the package review. Thanks for your contribution to Bioconductor.

Best,
Qian

**Comment by Liubuntu** [comment] 2018-06-06 14:31
Hi @jpoell ,

Like I said in last comment, there are 2 versions of Bioconductor, a stable version (Bioc release) and a development version (Bioc devel). The setting of 2 versions of Bioconductor is correlated with the versions of R. Since R have new version for every 6 months, Bioconductor does the same too. So that the Bioc devel is always depending on the R devel version. New packages always go to Bioc devel for new users to test, and then after the 6 months cycle (in April / October), it goes to the Bioc release as a stable package. So it's the best practice for the new packages to depend on R-devel version. One thing you can do maybe let the server administrator to install R-3.5 on the server, which would enable you to a lot of new packages on Bioc devel. But anyway, I just confirmed with my supervisor, that it's ok to stick with R3.4 for an inclusion. 

Best,
Qian

**Comment by jpoell** [comment] 2018-06-06 14:40
Hi Qian,

That's great. If it's okay, I would like to push the package again, without version bump, but changing Depends: R (>= 3.4)

Jos

**Comment by Liubuntu** [comment] 2018-06-19 21:56
Hi @jpoell , 

Thanks for your contribution to Bioconductor. This is the initial review of your package, please look into address all the points and comment back here when you are ready for a 2nd review. Please also look into the data structure I have mentioned in the "R/" section and comment back here. Thanks! 

## DESCRIPTION
- looks good.

## NAMESPACE
- looks good.

## vignette/

The vignette is generally very well written. Look for the following points to make it better:

1. Please add a "Installation" section in the beginning of the vignette, ideally after the "Introduction", and show users how to download and attach the package as if it is already available in Bioconductor. E.g.,
```{r, eval=FALSE}
source("https://bioconductor.org/biocLite.R")
biocLite("ACE")
```
You can also choose to add a subsection for installing the developmental version from github, e.g.,
```{r, eval=FALSE}
devtools::install_github("tgac-vumc/ACE")
```
*Make sure* to use `eval=FALSE` for both scripts.

1. In the "2.1 Getting started" section, it would be more general for a show case to define the:
```{r}
userpath <- tempdir()  ## OR
userpath <- tempfile()
```
to return a unique file path for the current R session, instead of:
```{r}
userpath <- "D:/DATA/bam-files"
```
Because the package is suppose to be used on all platforms of Linux, Windows and Mac.

3. section "2.3 model selection", it should be better to have the scripts for "plot1" and follow (print) with each corresponding plot directly with some explanations before each script, for different sample, ploidy number, whether a error list... I understand your logic to have all figures together for a direct comparision, but by adding a 1-line explanation and 2 lines of script between each plot would not affect the direct comparision, but also will have a more organized format and the user would not go back far to check script for each plot.

## R/

1. data structure?

When you are deciding on the data structure to use here, did you explore the `RaggedExperiment` and `RangedSummarizedExperiment`? The `RaggedExperiment` seems to be a good fit for copy number data? Also it would be nice to support the `GenomicRanges` structure (by use of `RangedSummarizedExperiment` or simply support `GenomicRanges`) to be better interoperating with the Bioconductor ecosystem.

2. replace "1:..." with `seq_len` or `seq_along` for a more robust coding. check [here](https://bioconductor.org/developers/how-to/efficient-code/).

3. avoid using "@" for accessing the object slots. Try to use or define accessor functions. Check the last paragraph of [here](https://bioconductor.org/developers/how-to/efficient-code/)

## man/
- looks good!

Cheers,
Qian

**Comment by jpoell** [comment] 2018-06-28 09:20
Hi Qian,

I have just pushed a new version of my package. Thank you so much for all the helpful comments:
### vignette
All suggestions incorporated!
### R
1. Data structure: I really like your suggestion of GenomicRanges. Unfortunately, I have already coded extensively using the data frame structure that is very similar to the one used in QDNAseq. Moreover, many of our pipelines feeding into ACE or using its output do this as well, and I didn't see a way of incorporating GenomicRanges without breaking those. That said, I found it very easy to go back and forth between the data frame structure I use and GenomicRanges. For instance, the function makeGRangesFromDataFrame works perfectly on my template data frames. Conversely, it is quite easy to derive ACE templates from a GRanges object. I hope this answers your question.
2. Done!
3. Done!

As always, looking forward to your feedback.

Kind regards,

Jos

**Comment by jpoell** [comment] 2018-06-28 09:31
I pushed without removing the man/linkmutationdata.Rd from the repository in version 0.99.4. I pushed a new version to keep things going. Sorry for the spam.

**Comment by Liubuntu** [comment] 2018-07-16 15:56
Hi @jpoell , 

Thank you for your reply with the explanations, and sorry for the delay of my response. 

For the data structure, using the `QDNAseq` is technically nothing wrong, but as Bioconductor encourages people to use the more standardized data structure as a lot efforts have already been put in the specific area (like copy number variations, etc.) and many methods have been implemented. When your package is more interoperable with Bioconductor ecosystem, it becomes more robust and potentially more widely used. 

However considering that `RaggedExperiment` is relatively new, it's ok that if you want to reimplement it for your future versions. But be compatible with `GenomicRanges` would be strongly encouraged!! Please consider making use of `SummarizedExperiment`, `RangedSummarizedExperiment`, and `GenomicRanges` in your future work as in genomic studies!

Now I will accept your package and look forward to your future contributions to Bioconductor!

Best,
Qian

**Comment by mtmorgan** [comment] 2018-07-20 14:54
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jpoell.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"ACE\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ACE

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-07-20 14:54 UTC
Labels: 3a. accepted
