### ISSUE TITLE
methodical

### ISSUE THREAD

**Issue by richardheery** [Bioconductor/Contributions#3169] opened 2023-09-27 16:31 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/richardheery/methodical

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2023-10-02 13:15
It looks like you are using kallisto in some functionality but it is not listed as a system dependency.  See http://contributions.bioconductor.org/description.html#description-sysdep  
If files are downloaded from external sources (like illumina, gencode, etc) we highly recommend using caching mechanism to help users with subsequent runs and to be able to use offline.  See [BiocFileCache](https://bioconductor.org/packages/release/bioc/html/BiocFileCache.html).

**Comment by richardheery** [comment] 2023-10-02 15:48
I've added kallisto as a system dependency in the description and also an INSTALL file stating where it can be downloaded from. The only call to download a file is in an example which isn't run (for the kallisto_index function). Would it still be better to cache this file?

**Comment by lshep** [comment] 2023-10-06 18:25
You use BSgenome.Hsapiens.UCSC.hg19 in your man pages but currently do not list it in the Suggest of your package DESCRIPTION. Please make the changes to fix the ERROR in the build report before a reviewer is assigned to the package

**Comment by richardheery** [comment] 2023-10-11 16:20
Hi Dario,

I'm just in the process of adding another vignette, which should be finished over the next day or two.

Cheers,

Richard

**Comment by richardheery** [comment] 2023-10-17 22:04
Hello,

The only issue I seem to be having is a timeout due to some of the examples taking a while to run. Could we still add it to the manifest and I'll find some faster examples?

**Comment by richardheery** [comment] 2023-10-18 10:55
@lshep I haven't received any feedback yet, but I'm passing all checks now. I just have one warning as I call library inside some of my code. I think this is justified since I do this while setting up a cluster wrapping the call in suppressMessages as I don't want to print the package startup messages on each node to the user.

**Comment by DarioS** [comment] 2023-10-19 01:00
The methodical package provides a set of analyses for DNA methylation data. It largely does not conform to the development guidlines set out in the [Package Developer's Guide](https://contributions.bioconductor.org/index.html) which is the second check box of the initial checklist above.

- Vignette needs to have BiocStyle. See the [Vignettes section](https://contributions.bioconductor.org/docs.html?q=BiocStyle#vignettes) of Chapter 12.
- Variable assignment uses `=` operator. See [Code Syntax section](https://contributions.bioconductor.org/r-code.html#code-syntax-and-efficiency) of R Code chapter.
- Variables and function names use `snake_case` style. See [Function Names](https://contributions.bioconductor.org/r-code.html#rcode-function-names) and [Variable Names](https://contributions.bioconductor.org/r-code.html#variable-names) sections.
 Using consistent variable and function naming style helps users when switching between Bioconductor packages.
 
 - Various data sets are downloaded from the internet. For example, 
```r
 mcrpc_wgbs_hg38_chr11 = download_meth_dataset(dataset = "mcrpc_wgbs_hg38_chr11")
 download.file("https://zenodo.org/record/8422703/files/mcrpc_transcript_counts.tsv.gz"
```
  Please refer to Chapter 13 Package Data's [Other Data](https://contributions.bioconductor.org/data.html#other-data) section.

> Downloads of files and external data from the web should be avoided.

- Package needs better integration with existing Bioconductor resources. For example,

```r
transcript_annotation = rtracklayer::import.gff3("gencode.v38.annotation.gff3.gz")
 ```
 
  This should be obtained via [AnnotationHub](https://bioconductor.org/packages/release/bioc/html/AnnotationHub.html).
   
- The vignette does not show and interpret any results. It does not execute any code. I notice:

```t
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", eval = FALSE)
```

Please change `eval` to `TRUE` and resubmit the package.

- Not all packages used are listed in DESCRIPTION file. For instance, vignette has `library(DESeq2)` but it is not in Suggests. Please read [Chapter 6: The DESCRIPTION File](https://contributions.bioconductor.org/description.html?q=Suggests#depends-imports-suggests-enhances) for what to put in your DESCRIPTION file. There is also an indirect dependency on [R.utils](https://cran.r-project.org/web/packages/R.utils/index.html).

```r
> download.file("https://zenodo.org/record/8422703/files/mcrpc_transcript_counts.tsv.gz", destfile = "mcrpc_transcript_counts.tsv.gz")
trying URL 'https://zenodo.org/record/8422703/files/mcrpc_transcript_counts.tsv.gz'
Content type 'application/octet-stream' length 13824482 bytes (13.2 MB)
downloaded 13.2 MB

> mcrpc_transcript_counts = data.frame(data.table::fread("mcrpc_transcript_counts.tsv.gz"), row.names = 1)
Error in data.table::fread("mcrpc_transcript_counts.tsv.gz") : 
  To read gz and bz2 files directly, fread() requires 'R.utils' package which cannot be found. Please install 'R.utils' using 'install.packages('R.utils')'.
```

- There is no checking of input variable type. S4 methods should be considered because they have a `signature` which does this. Alternatively, use `!is(parameter, Class)`.

- Parallelisation uses `doParallel` package. Bioconductor packages must use[ BiocParallel](https://bioconductor.org/packages/release/bioc/html/BiocParallel.html) framework. See [Package Reiewer Checklist](https://[contributions.bioconductor.org/docs/package-review-checklist.md](https://contributions.bioconductor.org/docs/package-review-checklist.md)).

- Some functions seem to reimplement what already exists in Bioconductor and is maintained by the core team. For example, `expand_granges` is essentially

```r
  genomic_regions_starts[on_plus] = genomic_regions_starts[on_plus] - upstream
  genomic_regions_starts[on_minus] = genomic_regions_starts[on_minus] - downstream
  genomic_regions_ends[on_plus] = genomic_regions_ends[on_plus] + downstream
  genomic_regions_ends[on_minus] = genomic_regions_ends[on_minus] + upstream
```

 which is already available in [GenomicRanges](https://bioconductor.org/packages/release/bioc/html/GenomicRanges.html) as the `promoters` or perhaps `flank` function.
 
 Major revisions required.

**Comment by richardheery** [comment] 2023-10-30 15:13
Thanks for your feedback @DarioS . 

I think I have addressed most of your comments now:

. I changed the output of vignettes to BiocStyle::html_document and added chunks for installing the package
. I replaced = with <- for variable assignment. 
. I now use camelCase for function names. I left internal variables used by functions in snake_case as I found the code became difficult to read otherwise.
. The WGBS and RNA-seq count datasets are now donwloaded from the TumourMethData ExperimentHub package. 
. I am now using AnnotationHub to retrieve the transcript annotation used by the vignette. 
. I changed the vignette options so that all code is evaluated. 
. I added dependencies for DESeq2 and R.utils
. For each function, I now check the class of each input variable using is().
. Parallelization now makes use of BiocParallel
. I removed the expand_granges() function since GenomicRanges::promoters() can be used to achieve the same thing. 

I still have some warnings regarding the use of suppressWarnings(), but I think this should be retained as otherwise thousands of warnings can be printed to the user's screen.

Let me know if there is anything else you think should be addressed.

**Comment by DarioS** [comment] 2023-11-05 00:00
- Vignettes need some proofreading, e.g. "identifcation", "jsut".
- DESCRIPTION file still has doParallel and example has `%dopar%`.
- Result seems unintended.

```r
> head(tubb6_cpg_meth_transcript_cors)
data frame with 0 columns and 0 rows
> 
> # Extract the location of the TSS from the results
> attributes(tubb6_cpg_meth_transcript_cors)$tss_range
NULL
```

**Comment by lshep** [comment] 2023-12-27 14:34
@richardheery did you see the above comment on re-review and may we expect changes soon?

**Comment by richardheery** [comment] 2023-12-27 15:05
Hi, sorry I was very busy with the submission of a paper, but I should be able to address the comments and resubmit within the next week or so.

**Comment by lshep** [comment] 2024-01-08 12:48
Please ignore the bioc-devel mailing list ERROR;   I can confirm the email is registered and we are looking into why BiocCheck is reporting an ERROR in mistake.

**Comment by DarioS** [comment] 2024-01-08 22:00
The package has been substantially improved.

**Comment by lshep** [comment] 2024-01-09 12:50
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/richardheery.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("methodical")`. The package 'landing page' will be created at

https://bioconductor.org/packages/methodical

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-01-09 12:50 UTC
Labels: OK, 3a. accepted

**Comment by lshep** [comment] 2024-04-09 13:55
Your package has been failing on our devel builders for over 6 weeks.  Please fix to avoid removal from Bioconductor

**Comment by richardheery** [comment] 2024-04-09 14:11
Hello,

Sure I will take a look at the issues in the coming days.

Best wishes,

Richard

**Comment by richardheery** [comment] 2024-04-18 18:17
Since my package is on the devel version of Bioconductor, do I need to still push any changes to the devel branch of Bioconductor at git@git.bioconductor.org:packages or is it enough just to my Git repository? 

Is there also a way to trigger a BBS build report without waiting for the nightly build?

**Comment by lshep** [comment] 2024-04-18 18:19
You need to push to git.bioconductor.org.  Bioconductor no longer makes any connection or reference to the github repo.  You will need to push changes to git.bioconductor.org with a valid version bump in order for them to appear and propagate to users

**Comment by lshep** [comment] 2024-04-18 18:20
Currently builds are only once a day.  But I encourage you to run R CMD build and R CMD check on your own, perhaps with the bioconductor docker image to test changes.
