### ISSUE TITLE
Please help submit my CleanUpRNAseq package to Bioconductor

### ISSUE THREAD

**Issue by haibol2016** [Bioconductor/Contributions#3442] opened 2024-05-24 02:04 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/haibol2016/CleanUpRNAseq

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by haibol2016** [comment] 2024-06-01 16:25
How long will it take to get a package submitted?

**Comment by lshep** [comment] 2024-06-03 14:58
I moderate packages normally once a week. Once moderated, if a package passes the
pre-check, it will build/check on our system and will require a clean build/check
to be assigned a reviewer. If there were pre-review concerns those should be
addressed before it will be put on our system.   Reviewers generally respond in
1-2 week time frame. Any concerns should be addressed and then once accepted we
will add to the Bioconductor public repository.

- [ ] Please don't have an empty news file.  You can initiate with something like

```
# Version 0.99.0

*  initial submission to Bioconductor 

```

- [ ] You will also need an inst/script directory that describes how the data in inst/extdata is created. It can be text, pseudo code or code but should describe how a user would re-create data and contain any licensing/source information.

- [ ] Please remove CleanUpRNAseq.html. This file should be generated
  automatically from the RMD during the R CMD build process.

- [ ] Data can not be stored on a dropbox or google drive.  Please move to a
  secure location preferrably zenodo but an institutional server or
  ExperimentHub would also suffice.

**Comment by haibol2016** [comment] 2024-06-04 21:25
All the listed  issues are fixed.  Thank you.

**Comment by haibol2016** [comment] 2024-06-07 20:47
Hello,
     I ran devtools::check() on my Windows platform a moment ago. I didn't encounter any error, though. Could you let me know the platform information where the package was checked? Based on th error report, I can't figure out what caused the error.

Thank you.

Haibo

**Comment by vjcitn** [comment] 2024-06-07 23:06
The platform information is on the report: https://bioconductor.org/spb_reports/CleanUpRNAseq_buildreport_20240607124952.html#nebbiolo2_buildsrc_anchor

Linux (Ubuntu 22.04.3 LTS)/x86_64

The error is pretty clear -- a function is called with argument maxMOp, but the function doesn't want such an argument 'CleanUpRNAseq.Rmd' failed with diagnostics:
unused argument (maxMOp = 10)

maybe it is a spelling error or the function's requirements changed

**Comment by haibol2016** [comment] 2024-06-08 00:15
Thank you for you reply.
However, in the Vignette Line 194-219, there is no such argument at all: https://github.com/haibol2016/CleanUpRNAseq/blob/devel/vignettes/CleanUpRNAseq.Rmd#L194-L219.

Haibo

**Comment by lshep** [comment] 2024-06-10 12:22
```
> 
invisible({
    capture.output({
        counts_list <- summarize_reads(
            metadata = metadata,
            isPairedEnd = TRUE,
            strandSpecific = 0,
            saf_list = saf_list,
            gtf = gsub(".gz", "", gtf),
            threads = 1,
            verbose = FALSE
        )
    })
})
Error in featureCounts(files = bamfiles, annot.ext = annotation, isGTFAnnotationFile = isGTF,  : 
  unused argument (maxMOp = 10)

```
Reproducible.  While this is not directly in this code I think it is a cascade affect from [`Rsubread::featureCounts` removing this argument](https://code.bioconductor.org/search/search?q=maxMOp) recently.  You are still using that argument in your summarize_reads which eventually gets called through this code in your vignette

**Comment by haibol2016** [comment] 2024-06-10 17:07
Got it. I will correct it.
Thank you.

Haibo

**Comment by haibol2016** [comment] 2024-06-10 18:31
Thank you. I just fixed the bug.

Haibo

**Comment by lshep** [comment] 2024-06-14 13:30
You need to push to bioconductor and trigger a new build to continue.  Please see [this previous message](https://github.com/Bioconductor/Contributions/issues/3442#issuecomment-2155185123)

**Comment by haibol2016** [comment] 2024-06-17 14:59
Thank you, lshep. I finally figured out how to do that. It is first time to sumbit a package to Bioconductor. If feel it is not easy to follow the direction here [this documentation](http://contributions.bioconductor.org/git-version-control.html#new-package-workflow].

**Comment by haibol2016** [comment] 2024-06-18 14:40
Hello,

       My package is now error-free but with a warning message, "WARNING: R
CMD check exceeded 10 min requirement". This is because many examples are
run. Is this OK?

Thank you,

Haibo

**Comment by LiNk-NY** [comment] 2024-07-16 16:49
> Hello, My package is now error-free but with a warning message, "WARNING: R CMD check exceeded 10 min requirement". This is because many examples are run. Is this OK? Thank you, Haibo

Hi @haibol2016 

Please make sure that the package examples do not exceed the time limit. 
Use small example datasets to demonstrate the functionality rather than biological accuracy.

Best,
Marcel

**Comment by haibol2016** [comment] 2024-07-17 12:03
Hello Marcel,

          Is this really a dead rule to keep the R CMD check time < 10 min? The manuscript reporting this package has been accepted by a journal and we are expected to submit the proofread this week. We need a Bioconductor link to show that the package has been accepted by Bioconductor.  If  the issue of exceeding 10 min runtime is not that important and not other problems detected, could you accept the package as it is? I will try my best to change the examples to shorten the R CMD check time shorten than 10 min as soon as possible.

Thank you,

Haibo

**Comment by LiNk-NY** [comment] 2024-07-17 15:06
Hi Haibo, @haibol2016 
Yes, due to the high costs of running our systems, 
we would like that all packages conform to this rule. 
Best regards,
Marcel

**Comment by haibol2016** [comment] 2024-07-18 12:09
Hello Marcel,

     I fixed the timeout issue. Please review the package again.

Best,

HAibo

**Comment by LiNk-NY** [comment] 2024-07-18 19:02
Hi Haibo, @haibol2016 

Thank you for your contribution. 
Please see the review below. 

Best regards,
Marcel

--- 

# CleanUpRNAseq #3442

The package is quite extensive and has a lot of functionality. It would be
good to consider splitting the package into smaller packages with more focused
functionality. Currently, it tries to do too much, i.e. data processing,
statistical metrics, plotting, BSgenome forging, etc. Consider also
contributing to existing packages such as `BSgenomeForge` and others.

## DESCRIPTION

* add `BugReports` and `URL` fields
* Remove `BiocManager` from `Suggests` field
* Update `Depends` field to `R (>= 4.4.0)`
* Remove `LazyData` field or set to `false`
* Consider using `desc::desc` to reformat the `DESCRIPTION` file.

## NAMESPACE

* `UCSC2Ensembl` may require a more descriptive name
* Perhaps helper functions (e.g., `forge_BSgenome`, `make_BSgenome`,
`make_ensdb`) should be in a separate package?
* Consider using shorter function names

## vignettes

* Consider removing the lightweight wrappers from the vignette and pacakge,
e.g., `make_ensdb`
* Enable caching in the vignette and use `BiocFileCache` for downloading files
rather than `retry_download`
* Avoid `invisible` and `capture.output` in the vignette
* No need to explicitly use `print()` in the vignette
* Are the plots provided by the functions in the package? If so, consider
removing the saved `png` files from the vignette as they are generated by the
functions in the package.

## R

* Use `BiocFileCache` for downloading files in the examples
* Avoid the extra emphasis (`!`) in error messages.
* Use `seq_len` or `seq_along` instead of `2:ncol(...)` in
`check_read_assignment_stat`
* Avoid mixing analysis and graphing functions and consider separating
functionalities (in `check_read_assignment_stat`, `check_read_distribution`,
`check_sample_correlation`, etc.)
* It seems like some of the functions should be using `SummarizedExperiment` to
represent the counts e.g., `check_expr_distribution`.
* Consider reducing the cyclomatic complexity of functions by creating a class
(with an established `metadata` slot) that automatically checks the data
rather than having multiple checks in the functions (e.g.,
`check_expressed_gene_percentage`).
* Remove `retry_download` and use `BiocFileCache` for downloading files.
* Remove `dontrun` from the examples and use `BiocFileCache` to retrieve
the downloaded external files.
* The arguments for `correct_for_contamination` seem to be overloaded and could
be helped by using a class that already has the metadata information.
* Avoid saving PDF or any output files for the user by default. The user
should be able to save the output in the desired format (in
`create_diagnostic_plot`).
* Avoid using vague function names like `exploratory_analysis`. This may more
appropriate for a separate package with a set of functions for EDA.
* Consider removing the `cache_env` feature in the package. Interactive
analyses will use the `.GlobalEnv`.
* For usability, it would be preferable to avoid syntax such as
`cache_env$counts_summary$gtf$counts_junction`.
* Where possible, avoid using numeric indices and use names instead (found in
`gc_bias_correction`).
* For `UCSC2Ensembl`, have you considered using `seqlevelsStyle` to convert the
`seqlevels` instead? The function here might not be necessary.
* Consider moving `make_BSgenome` and `make_ensdb` creation functions into a
separate package.

## tests

* We strongly recommend adding unit tests to ensure that the code in the
package is robust and reliable.

**Comment by haibol2016** [comment] 2024-07-18 21:07
Hello Marcel,

        Thank you very much for the detailed review and suggestions. This is my first full-blown R package. I know I still can improve the package. However, given that our manuscript has been accepted and we have to submit the proofread in a short time, I don't think it is possible to overhaul the package at this moment.

        Is it possible to accept the package as it is this moment? Otherwise, I will have to remove "Bioconductor" from the title of the manuscrip: "CleanUpRNAseq: An R/Bioconductor Package for Detecting and Correcting DNA Contamination in RNA-Seq Data".

Thank you,

Haibo

**Comment by LiNk-NY** [comment] 2024-07-18 21:21
Hi Haibo, @haibol2016 

Sorry to hear that and apologies for the delay in the review. 

Unfortunately for now, we cannot accept the package as-is but we
are happy to accept the package after consideration of the review 
and the appropriate changes.

Best regards,
Marcel

**Comment by haibol2016** [comment] 2024-07-19 15:07
Hello Marcel,
        For time reason, I may not to fix all the issues you pointed out. Do I have to address all of the issues to my package to be considered by Bioconductor? Otherwise, could you please let me know what are compulsory and what are suggestion?  


Thanks,

Haibo

**Comment by LiNk-NY** [comment] 2024-07-22 15:48
Hi @haibol2016 
Yes, please respond to the review before proceeding. 
Best,
Marcel

**Comment by haibol2016** [comment] 2024-07-22 18:23
Hello Marcel,
       _I will respond to your comment below each of them in italics._
 
The package is quite extensive and has a lot of functionality. It would be
good to consider splitting the package into smaller packages with more focused
functionality. Currently, it tries to do too much, i.e. data processing,
statistical metrics, plotting, BSgenome forging, etc. Consider also
contributing to existing packages such as BSgenomeForge and others.

_I have decided to move the helper fuctions for creating BSgenome from a multifasta file out of the package._


DESCRIPTION
add BugReports and URL fields
Remove BiocManager from Suggests field
Update Depends field to R (>= 4.4.0)
Remove LazyData field or set to false
Consider using desc::desc to reformat the DESCRIPTION file.

_These issues in the DESCRIPTION file have been easily fixed using desc::desc. Thank you for the suggested tool._

NAMESPACE
UCSC2Ensembl may require a more descriptive name
Perhaps helper functions (e.g., forge_BSgenome, make_BSgenome,
make_ensdb) should be in a separate package?
Consider using shorter function names

_make_ensdb is deleted because it is a shallow wrapper function. forge_BSgenome and make_BSgenome and the other related to create a BSgenome from a multifasta file have been removed from the package.

The UCSC2Ensembl function is renamed as style_BSgenome._


vignettes
Consider removing the lightweight wrappers from the vignette and pacakge,
e.g., make_ensdb

_make_ensdb function is deleted_

Enable caching in the vignette and use BiocFileCache for downloading files
rather than retry_download

_Yes, I will use BiocFileCache for downloading files._

Avoid invisible and capture.output in the vignette

_I used these functions so that the large amount of information output by featureCounts will not pollute the vignette. I can remove those functions if it is OK with lots of irrelevant information are captured in the vignette._

No need to explicitly use print() in the vignette

_print() is removed_

Are the plots provided by the functions in the package? If so, consider
removing the saved png files from the vignette as they are generated by the
functions in the package.

_Because the time limit of 10 mins, I saved the png files to the vignette directory from a interactive run of the R chuncks to shorten the runtime._


R
Use BiocFileCache for downloading files in the examples

_Yes, BioCFileCache is a very good package to meet my purpose here._

Avoid the extra emphasis (!) in error messages.

_sure_

Use seq_len or seq_along instead of 2:ncol(...) in
check_read_assignment_stat

_OK_

Avoid mixing analysis and graphing functions and consider separating
functionalities (in check_read_assignment_stat, check_read_distribution,
check_sample_correlation, etc.)

_Here the plots is the main output. the data generated during the process is not of interest once the plots are generated._


It seems like some of the functions should be using SummarizedExperiment to
represent the counts e.g., check_expr_distribution.
Consider reducing the cyclomatic complexity of functions by creating a class
(with an established metadata slot) that automatically checks the data
rather than having multiple checks in the functions (e.g.,
check_expressed_gene_percentage).

_I will create a S4 class to represt the data output by summariz_reads () (a wrapper of featureCounts()) and salmon_res() (a wrapper of tximport()), along with the metadata._

Remove retry_download and use BiocFileCache for downloading files.

_sure_

Remove dontrun from the examples and use BiocFileCache to retrieve
the downloaded external files.

The two big wrapper function create_diagnostic_plots() and correct_for_contaminaiton() are main APIs to make many function calls chained together as a pipeline. To save time, I just used dontrun since the individual functions have their own examples. I am planning to remove the two major pipeline-like wrapper functions from the package.

The arguments for correct_for_contamination seem to be overloaded and could
be helped by using a class that already has the metadata information.

_Yes, I will do that_

Avoid saving PDF or any output files for the user by default. The user
should be able to save the output in the desired format (in
create_diagnostic_plot).

_Since this in the pipeline-like wrapper function create_diagnostic_plots(), I decide to save the plots as PDF if their sizes are not too big, otherwise tiff. To give the users the flexibility, I also return the ggplot objects._

Avoid using vague function names like exploratory_analysis. This may more
appropriate for a separate package with a set of functions for EDA.

_I will rename the function to sample_similarity()._

Consider removing the cache_env feature in the package. Interactive
analyses will use the .GlobalEnv.

_cache_env is an environment object used to hold download files to avoid repeated downloading for running examples. Yes, I will remove cache_env, instead use BiocFileCache._

For usability, it would be preferable to avoid syntax such as
cache_env$counts_summary$gtf$counts_junction.

_This is only used in examples to access elements from nested lists_

Where possible, avoid using numeric indices and use names instead (found in
gc_bias_correction).

_OK_

For UCSC2Ensembl, have you considered using seqlevelsStyle to convert the
seqlevels instead? The function here might not be necessary.

_seqlevelsStyle() can only change the main chromosome names, from chr1, chr2, ... chrX to 1, 2, ..., X, but it can change the names of scaffolds._

Consider moving make_BSgenome and make_ensdb creation functions into a
separate package.

_Those functions will be removed from the package_

tests
We strongly recommend adding unit tests to ensure that the code in the
package is robust and reliable.

_I will add tests_

**Comment by LiNk-NY** [comment] 2024-07-22 18:59
Hi Haibo, @haibol2016 
> _Here the plots is the main output. the data generated during the process is not of interest once the plots are generated._

Please rename the functions so that it is explicit that they are plotting functions and not statistical functions. 

> The UCSC2Ensembl function is renamed as style_BSgenome._

Can you rename the function to reflect the functionality? It seems that `seqlevelsStyle<-` already does this but you mention that you are also changing the scaffold names.  

> Because the time limit of 10 mins, I saved the png files to the vignette directory from a interactive run of the R chuncks to shorten the runtime.

This is not prefereable. We would rather have the interactive run with a shorter run time. If the computation is too intense, please consider using a smaller dataset to demonstrate the functionality  or profiling the code to improve efficiency. 


> The two big wrapper function create_diagnostic_plots() and correct_for_contaminaiton() are main APIs to make many function calls chained together as a pipeline. To save time, I just used dontrun since the individual functions have their own examples. I am planning to remove the two major pipeline-like wrapper functions from the package.

The examples run in sequence so your examples can take outputs from previous examples (by using `example("topic")`) within the examples. An alternative is to use a saved and exported data object (mainly for packages that create their own class) to use as an example dataset throughout the package examples.

> Since this in the pipeline-like wrapper function create_diagnostic_plots(), I decide to save the plots as PDF if their sizes are not too big, otherwise tiff. To give the users the flexibility, I also return the ggplot objects.

Add an option that allows users to decide whether or not to save PDF plots. It is generally discouraged to create files on the users' systems without their consent. 

> For usability, it would be preferable to avoid syntax such as cache_env$counts_summary$gtf$counts_junction.
> 
> _This is only used in examples to access elements from nested lists_

These examples are not very productive for users. Accessing deeply nested lists hurts the usability. Please remove them or provide a helper function. 

 
> _I will add tests_

> _Yes, I will use BiocFileCache for downloading files._

Thank you, please make the changes and bump the version number for another build. 

Best regards,
Marcel

**Comment by haibol2016** [comment] 2024-07-22 20:28
Hello Marcel,

     > Add an option that allows users to decide whether or not to save PDF
plots. It is generally discouraged to create files on the users' systems
without their consent.
     In this function, I do ask the users to provide an output directory
for saving plots. Isn't that enough?

     > The examples run in sequence so your examples can take outputs from
previous examples (by using example("topic")) within the examples.
     I am curious about what determines the running sequences of examples.
Can you point to me a concrete example where example("topic") is used. I am
not sure how to do that.

Thank you,

Haibo

**Comment by LiNk-NY** [comment] 2024-07-22 21:31
> In this function, I do ask the users to provide an output directory for saving plots. Isn't that enough?

Yes, that is enough as long as it doesn't write files by default. 



> I am curious about what determines the running sequences of examples.

I believe they are run in alphabetical order by default. 
You can also modify a `Collate` field in the `DESCRIPTION` using the `@include file.R` Roxygen tag. 
Here is an example: 
https://code.bioconductor.org/browse/SingleCellExperiment/blob/devel/R/combine.R#L95

Best,
Marcel

**Comment by haibol2016** [comment] 2024-07-25 14:22
Thank you, Marcel, for the tips.

Can using example("topic")  avoid repeated running of an example?  For
example, I have a function called foo() and another function bar(),
which takes the output of foo() as input. Will the foo() example run once
or twice?

...
#' examples
#'  a <- foo( x, y)
#'
#'
foo <- function(x, y) {
      ...
}

...
#' examples
#' example(foo)
#'
#'  bar(a)

bar <- function(a) { ...}


Thank you,

Haibo

**Comment by LiNk-NY** [comment] 2024-07-31 14:57
> Thank you, Marcel, for the tips. Can using example("topic") avoid repeated running of an example? For example, I have a function called foo() and another function bar(), which takes the output of foo() as input. Will the foo() example run once or twice? ... #' examples #' a <- foo( x, y) #' #' foo <- function(x, y) { ... } ... #' examples #' example(foo) #' #' bar(a) bar <- function(a) { ...} Thank you, Haibo

I think it depends on the collation order. 
If you have `bar` run first (based on collation order) then it won't run the examples twice only once but I am not 100% sure on this. I'd have to test further. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment] 2024-07-31 15:14
I see the changes you made. Your package has been accepted. 
Thank you for your contribution. 
Best regards,
Marcel

**Comment by haibol2016** [comment] 2024-07-31 15:24
Thank you, Marcel and Bioconductor team, for your help with reviewing the
package.

Best,

Haibo

**Comment by lshep** [comment] 2024-08-05 14:03
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/haibol2016.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CleanUpRNAseq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CleanUpRNAseq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-08-05 14:03 UTC
Labels: OK, 3a. accepted
