### ISSUE TITLE
CaDrA

### ISSUE THREAD

**Issue by RC-88** [Bioconductor/Contributions#2850] opened 2022-11-02 14:58 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/montilab/CaDrA

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment] 2022-12-02 15:10
Hi Reina, 
Thank you for your submission. 
Please see the review below. 
Best regards,
Marcel

---


# CaDrA #2850

Unfortunately, I do not see a strong use case of Bioconductor in the package.
The `ExpressionSet` class has been superseded by `SummarizedExperiment` for many
years now. Many of the exported functions in the package return a `list` or
`data.frame` which do not integrate well with the rest of Bioconductor.
We recommend using `SummarizedExperiment` as the main representation for
input and output objects.

## DESCRIPTION

* Looks good.
* Consider using an easier-to-type package name without mixed case, e.g.,
'cadra' or 'CADRA'.

## NAMESPACE

* Avoid exporting the `%>%` pipe and use the native `|>` pipe.

## vignettes

* Consider moving vignettes that reproduce manuscript figures into their own
repository rather than the `CaDrA` package
* The vignettes should exhibit the functionality of the package with a small
example dataset
* Consider updating `Biobase` to `SummarizedExperiment`. New users are more
likely to be familiar with the latter.
* Remove `devtools::load_all` function calls

## R

* `custom_genescore_mat` and others do not take an `ExpressionSet` as input
but rather a `matrix`. It would be better if the function could take both.
* Avoid ambiguous abbreviations, e.g., `ES` in arguments stands for
ExpressionSet but some functions have `ES` for enrichment score.
* Consider reducing the cyclomatic complexity of some functions. The top 6
as reported by `cyclocomp` are:
```r
      candidate_search revealer_genescore_mat                  CaDrA
                    72                     57                     47
    revealer_genescore   custom_genescore_mat      ks_gene_score_mat
                    43                     41                     35
```

## tests

* Please add unit tests

**Comment by LiNk-NY** [comment] 2023-01-24 16:29
Hi Reina, @RC-88 

Any updates in response to the review? 
If you need more time, we can close the issue and you can re-open when ready. 

Best regards,
Marcel

**Comment by RC-88** [comment] 2023-01-24 16:53
Hi Marcel, @LiNk-NY 

Thanks for your feedback! and Sorry for the lack of responses! My collaborators and I are working diligently to address some of the concerns that you mentioned. We are almost there. Just a few more unit tests in place to make sure the tool is working as expected.  In brevity, we made quite a significant changes to our package based on your feedback (such as replacing ExpressionSet with SummarizedExperiment object, renaming our variable "ES" to "FS" in order to align with our vignettes and documentation, reduce complexity of our core functions, etc.) I will keep you posted next week with in-depth details of our changes, and hopefully, these changes will meet up to current BioConductor's usage.

**Comment by RC-88** [comment] 2023-02-28 14:21
Hi Marcel, @LiNk-NY 

My collaborators and I are almost done with the revision of the CaDrA package with newly optimized functions ready for resubmission. Just curious how long does it take until a BioConductor submission expired? Thanks!

**Comment by LiNk-NY** [comment] 2023-02-28 15:03
Hi @RC-88 
Submissions do not really expire. But we try to stick to a max 14 day non-response period.

**Comment by RC-88** [comment] 2023-02-28 16:15
@LiNk-NY, I see. Apologize for the lack of responses! Will try to keep you up-to-date with our progress or changes!

**Comment by RC-88** [comment] 2023-03-29 14:20
Hi @LiNk-NY, how are you? I recently pushed out the new build for our updated package CaDrA. However, it seems that the package passed RCMD check in MAC OS  platform but failed in Linux. I tried to recheck the build on our Linux system, and it seems that the package built successfully without any errors. I expect some package dependencies required by CaDrA (such as R.cache and SummarizedExperiment) does not exist in the library of BioConductor Linux build system. We used R.cache package to do some caching for future loading of the permutation-based testing results. This step would help users save time in recomputing the permutation-based testings with similar parameters as this task is intensive and time-consuming. We also updated our BioBase:ExpressionSet() objects to use SummarizedExperiment::assay() objects as recommended. Is there a way for us to resolve this issue? Thanks so much!

**Comment by LiNk-NY** [comment] 2023-04-18 19:36
Hi Reina, @RC-88 

Apologies for the delayed response. We get a lot of packages to review around this time. 
Please respond to the issue bullet points for the review to continue. 

Best regards,
Marcel

**Comment by RC-88** [comment] 2023-04-18 22:12
Hi Marcel, @LiNk-NY 

No worries! I'm glad we didn't lose you and would need to resubmit our package again. Thanks for being patience with us!

Finally, my collaborators and I had finalized all of the changes needed to push our CaDrA package toward review again. We had spent a significant amount of effort to address the feedback that you shared with us a while back. 

Here is a list of things that we didn't changed and why:
1. We didn't change the name of our package, CaDrA, and would like to keep its original name. The reason is that CaDrA is actually short for **Ca**ndidate **Dr**iver **A**nalysis. It is a statistical framework that our lab developed to identify (epi) genetic drivers of a molecular phenotype of interest. We previously published a paper that is associated with the name of this package. Please see our associated manuscript, [Kartha et al. (2019)](https://www.frontiersin.org/articles/10.3389/fgene.2019.00121/full), for more details.
2. Right now, some of our exported functions are still returning a list of objects such as candidate_search() and CaDrA() functions. The reason we prefer a list of objects as output rather than a SummarizedExperiment object is because our core functions performs heuristic search to identify candidate drivers of a molecular phenotype of interest over a given set of features with top N scores. Therefore, the result will consist of a list of objects including a set of meta-features in form of a SummarizedExperiment object,  its observed input_score as a vector of continuous scores, and a corresponding best score pertaining to each top N feature searches. Thus, it is quite difficult to contain the results into one giant SummarizedExperiment object. In the future, we are considering to convert our analysis results into a S6 class object.

Here is a list of things that we had changed:
1. Removed the %>% pipe and used the native |> pipe
2. Removed **BioBase** and used **SummarizedExperiment** package instead
3. Moved vignettes that reproduce manuscript figures into their own repository rather than the CaDrA package. Completed! We created a separate Github repo, CaDrA-shiny, which we are currently used to showcase the examples of how run CaDrA through an R Shiny interface (also see our web portal, [https://cadra.bu.edu/](https://cadra.bu.edu/))
4. The vignettes should exhibit the functionality of the package with a small example dataset. Agreed, right now, we are using a small simulation dataset to document all of the vignettes in the package.
5. Removed `devtools::load_all` function calls
6. All functions in the package currently take a SummarizedExperiment/data matrix as inputs and some time both especially for the `custom_rowscore()` function
7. Avoided ambiguous abbreviations, e.g., ES in arguments stands for ExpressionSet but some functions have ES for enrichment score. Agreed. We had thoroughly rewritten the arguments to make it clearer for our users to look up our documentation (see the reference on [our github pages](https://montilab.github.io/CaDrA/reference/)).
8. Added additional unit tests
9. Optimized the complexity of our core functions using `cyclocomp` 

before:      

name | cyclocomp
:-- | :--
candidate_search | 72
revealer_genescore_mat | 57
CaDrA | 47
revealer_genescore | 43
custom_genescore_mat | 41
ks_gene_score_mat | 35

after:

name | cyclocomp
:-- | :--
custom_rowscore | 33
check_data_input | 31
CaDrA | 26
candidate_search | 23
wilcox_score | 21
check_top_N | 16
cond_assoc | 10
generate_permutations | 6
stacked_gtable_max | 5
forward_backward_check | 4
ks_rowscore_calc | 4
ks_test_double_wrap | 4
revealer_rowscore | 4
calc_rowscore | 3
ks_genescore_wrap | 3
ks_rowscore | 3
topn_plot | 3
verbose | 3
ks_plot_coordinates | 2
permutation_plot | 2
prefilter_data | 2
setup_tab_heights | 2
cond_mutual_inf | 1
ks_genescore_mat_ | 1
ks_genescore_wrap_ | 1
ks_plot | 1
ks_plot_wrap_ | 1
ks_test_d_wrap_ | 1
meta_plot | 1

Let me know if there are other areas that you think we should improve. Look forward to hear from you!

**Comment by LiNk-NY** [comment] 2023-04-19 21:47
Hi Reina, @RC-88 

Thank you for making those changes. 

> 1. We didn't change the name of our package, CaDrA, and would like to keep its original name. The reason is that CaDrA is actually short for **Ca**ndidate **Dr**iver **A**nalysis. It is a statistical framework that our lab developed to identify (epi) genetic drivers of a molecular phenotype of interest. We previously published a paper that is associated with the name of this package. Please see our associated manuscript, [Kartha et al. (2019)](https://www.frontiersin.org/articles/10.3389/fgene.2019.00121/full), for more details.

That's okay but users may find the mixed case inconvenient. Note that the `cadra.R` file does not have mixed case. So if it is inconvenient for the developer, it may likely be inconvenient for users. 

> 2. Right now, some of our exported functions are still returning a list of objects such as candidate_search() and CaDrA() functions. The reason we prefer a list of objects as output rather than a SummarizedExperiment object is because our core functions performs heuristic search to identify candidate drivers of a molecular phenotype of interest over a given set of features with top N scores. Therefore, the result will consist of a list of objects including a set of meta-features in form of a SummarizedExperiment object,  its observed input_score as a vector of continuous scores, and a corresponding best score pertaining to each top N feature searches. Thus, it is quite difficult to contain the results into one giant SummarizedExperiment object. In the future, we are considering to convert our analysis results into a S6 class object.

This deviates from Bioconductor standards of a centralized representation. It is not clear to me how an S6 class would be an improvement. 

> Here is a list of things that we had changed:
> 
...
> 6. All functions in the package currently take a SummarizedExperiment/data matrix as inputs and some time both especially for the `custom_rowscore()` function

This doesn't seem to be the case. Am I missing something here? 
https://github.com/montilab/CaDrA/blob/9226dbd3f093461b3b1ae519c6cba53bc42f9226/R/custom_rowscore.R#L7-L9

Best,
Marcel

**Comment by RC-88** [comment] 2023-04-25 15:29
Hi Marcel, @LiNk-NY 

Thanks for your feedback and to address your previous comments:

1. Thank you for your concern, and we understand the possible inconvenience of having mixed cases. However, we accept the trade-off, as we deem maintaining the connection with the published methodology more important.

2. The use of a SummarizedExperiment is not really an option, since the value returned by the function is a list of multiple objects of different sizes/dimensions for which the SS is not suitable. CaDrA does not simply perform some processing of a SummarizedExperiment (such as, e.g., scaling or normalization), rather it uses a SS as _one of_ its inputs, and the output has multiple parts. We could define a new R class to represent its multi-part output, but it seemed a bit of an overkill for our purposes.

6. To clarify, `calc_rowscore()` is actually the main function that is used to run the `custom_rowscore()` (behind the scene) by specifying method = "custom". The required parameters to run both `calc_rowcore()` and `custom_rowscore()` are a set of **binary features** (e.g. somatic mutations, CNV, etc.) and a vector of **continuous scores** representing a phenotypic readout of interest (e.g. protein expression, pathway activity, etc.)  For the `custom` method only, you have full control of your defined function, thus, you can easily pass the feature set as a summarized experiment or a data matrix to your customized function as long as your function has a way to handle different types of feature set objects.

Here are two examples that demonstrate the usage of having a summarized experiment or a data matrix as an input to the `custom` method:

## Installation
```
library(devtools)
devtools::install_github("montilab/CaDrA", ref="devel")
```

## Quickstart
```
library(CaDrA)
library(SummarizedExperiment)
```

## A customized function using `ks.test()` that can handle both SummarizedExperiment or data matrix as an input object
```
customized_rowscore <- function(FS_mat, input_score, alternative="less"){

  # Check if FS_mat is a matrix or a SummarizedExperiment class object
  if(!is(FS_mat, "SummarizedExperiment") && !is(FS_mat, "matrix"))
    stop("'FS_mat' must be a matrix or a SummarizedExperiment class object
         from SummarizedExperiment package")
  
  # Retrieve the feature binary matrix
  if(is(FS_mat, "SummarizedExperiment")){
    mat <- as.matrix(SummarizedExperiment::assay(FS_mat))
  }else{
    mat <- FS_mat
  }

  ks <- apply(mat, 1, function(r){
    x = input_score[which(r==1)];
    y = input_score[which(r==0)];
    res <- ks.test(x, y, alternative=alternative)
    return(c(res$statistic, res$p.value))
  })

  # Obtain score statistics and p-values from KS method
  stat <- ks[1,]

  # Change values of 0 to the machine lowest value to avoid taking -log(0)
  pval <- ks[2,]
  pval[which(pval == 0)] <- .Machine$double.xmin

  # Compute the -log(pval)
  # Make sure scores has names that match the row names of FS_mat object
  scores <- -log(pval)
  names(scores) <- rownames(mat)

  return(scores)

}
```

## A customized function using `ks.test()` with a data matrix as an input
```
# Load pre-computed feature set
data(sim_FS)

# Load pre-computed input-score
data(sim_Scores)

# Main function is calc_rowscore() with a given method = "custom"
custom_rowscore_result_v1 <- calc_rowscore(
  FS_mat = SummarizedExperiment::assay(sim_FS),   ## <--- Here FS_mat takes assay(sim_FS) which is a data matrix
  input_score = sim_Scores,
  method = "custom",
  custom_function = customized_rowscore,
  custom_parameters = NULL
)
```

```
head(custom_rowscore_result_v1)
## TN_716 TN_963 TP_8 TP_9 TN_844 TN_108
## 7.206006 5.471405 5.387492 5.387492 5.387492 5.289084
```

## A customized function using  a SummarizedExperiment object as an input
```
  # Load pre-computed feature set
  data(sim_FS)

  # Load pre-computed input-score
  data(sim_Scores)

  # Main function is calc_rowscore() with a given method = "custom"
  custom_rowscore_result_v2 <- calc_rowscore(
    FS_mat = sim_FS,              ## <--- here FS_mat takes sim_FS which is originally a SummarizedExperiment object
    input_score = sim_Scores,
    method = "custom",
    custom_function = customized_rowscore,
    custom_parameters = NULL
  )
```

```
head(custom_rowscore_result_v2)
## TN_716 TN_963 TP_8 TP_9 TN_844 TN_108
## 7.206006 5.471405 5.387492 5.387492 5.387492 5.289084
```

Hope we address your concerns this time and look forward to your feedback!

Best,

Reina C.

**Comment by LiNk-NY** [comment] 2023-04-25 18:49
Hi Reina, @RC-88 

Thank you for your response. 

It seems that you expect the user to be able to write a "customized" function that can handle both `matrix` and `SummarizedExperiment`. I am wondering, why not have the function handle both type of inputs?

This strategy would improve the usability of your `calc_rowscore` function. In other words, `calc_rowscore` would 
accept and work with both types of inputs for the `FS_mat` argument (which may have to be renamed). 

The examples that you show above would then be reduced into a single function call because the user will not 
have to jump through hoops to use your interface. 

Best,
Marcel

**Comment by RC-88** [comment] 2023-05-01 16:26
Hi Marcel, @LiNk-NY 

Thank you for your feedback! I agreed with your strategy of utilizing both `SummarizedExperiment` and `data matrix` as inputs to our core functions (calc_rowscore(), candidate_search(), CaDrA()). This definitely improves the usability of our package. I had implemented an update to the package which now can handle both type of inputs. 

I attached a pdf document generated from an Rmd which showcases the usage of taking both `SummarizedExperiment` and `data matrix` as inputs to our core functions 

[testing_cadra_functions.pdf](https://github.com/Bioconductor/Contributions/files/11366577/testing_cadra_functions.pdf)

Hope this updated changes would get your approval :) Thanks again!

**Comment by RC-88** [comment] 2023-05-15 14:38
Hi Marcel, how are you?

I just wanted to check in to see if you are okay with our updated changes.

Best,

Reina C.

**Comment by LiNk-NY** [comment] 2023-05-22 21:57
Hi Reina, 
Sorry for the delay. 
Thank you for your patience. 
The changes look good. 
Consider removing the `donttest` markers in the examples and using a small example dataset if possible. 
Best,
Marcel

**Comment by RC-88** [comment] 2023-06-05 15:08
Hi Marcel, how are you?

I had removed the `donttest` markers in the examples. The `sim_FS` dataset that was used in the samples is quite small, 100 features by 100 samples.  Let me know if this works with you.

Thanks again!

Reina C.

**Comment by LiNk-NY** [comment] 2023-06-05 15:52
Hi Reina, @RC-88 
Thank you for making those changes. 
The small dataset is great. 
Your package has been accepted. 
Best regards,
Marcel

**Comment by RC-88** [comment] 2023-06-05 16:07
Hi Marcel, @LiNk-NY 

It is a great news to hear that our package has gotten accepted! Thank you so much for your thorough review that guided me through this submission process!

Best,

Reina C.

**Comment by lshep** [comment] 2023-06-20 14:39
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/RC-88.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CaDrA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CaDrA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-06-20 14:39 UTC
Labels: OK, 3a. accepted
