### ISSUE TITLE
MoleculeExperiment

### ISSUE THREAD

**Issue by shazanfar** [Bioconductor/Contributions#3001] opened 2023-03-30 21:36 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SydneyBioX/MoleculeExperiment

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by shazanfar** [comment] 2023-04-03 14:12
Update: maintainer added package name to Watched Tags on Support Site

**Comment by nilseling** [comment] 2023-04-05 15:55
Hi @shazanfar,

thanks for submitting `MoleculeExperiment` to Biocondcutor. The package is in a really good shape. There are only a few comments that could be addressed.
Please respond to those either by explaining the changes to the package or by explaining the design choice.


## General package development

- [ ] I would recommend to add the Bioconductor installation instructions to the README file.
- [ ] Should the files in `nobuildscripts` be part of the Github repository? 
- [ ] As you can see, the files in `docs` cause warnings when building the package. Are they necessary to include?

## The NEWS file

- [ ] I would recommend to add a NEWS file that tracks the changes to your package.

## Documentation

- [ ] I would recommend to provide simple wrapper functions for the `ggplot2` calls in the vignette
- [ ] Would it make sense to create classes for the molecules and boundaries lists which would allow you to implement show methods
- [ ] Please provide an "Installation" section in your vignette

## Unit tests

- [ ] It is highly recommended to add unit tests to the package that cover the main functionality

## R code

- [ ] Please check that you use the provided getter/setter functions in your internal R code (e.g. `me@molecules` in `.flatten_molecules`)
- [ ] Please try to address the following NOTEs:

```
    * NOTE: Avoid sapply(); use vapply()
    * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
```

- [ ] Please check that function arguments are tested for validity. For example:

```
> countMolecules("test")
The boundaries were retrieved from the "cell" assay. A
different assay (e.g., "nucleus") can be specified in the boundaries_assay
argument)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘molecules’ for signature ‘"character"’
```

**Comment by lgeistlinger** [comment] 2023-04-07 20:20
Hi @shazanfar - two comments on `countMolecules`:

1. the function calculates spatial overlaps between molecules and cells using functionality from the [sp](https://cran.r-project.org/web/packages/sp/index.html) package. there are two better options for that: 1. the [sf](https://cran.r-project.org/web/packages/sp/index.html) package and 2. the [terra](https://cran.r-project.org/web/packages/terra/index.html) package. In some of my evaluations I find `sf::st_intersects` to be roughly 4x faster than `sp::over`; and `terra::relate` to be roughly 6x faster than `sp::over` - which makes a difference especially for larger datasets.
2. maybe this is by design to keep things plain and accessible (which would make sense), but wouldn't it make sense for the returned `SpatialExperiment` to also store the molecules in another assay in the form of a `BumpyMatrix`? (this one only containing the molecules that have been assigned to cells)

**Comment by shazanfar** [comment] 2023-04-14 08:53
Hi @nilseling 

Thanks so much for your work reviewing our MoleculeExperiment package! See below each point and changes we have made. 

## General package development

- [X] I would recommend to add the Bioconductor installation instructions to the README file.
- [X] Should the files in `nobuildscripts` be part of the Github repository? 
- [X] As you can see, the files in `docs` cause warnings when building the package. Are they necessary to include?
- These are for the pkgdown site. We have added them to build ignore.

## The NEWS file

- [X] I would recommend to add a NEWS file that tracks the changes to your package.

## Documentation

- [X] I would recommend to provide simple wrapper functions for the `ggplot2` calls in the vignette
- We have created three ggplot wrapper functions which allow users to build custom ggplots with points and polygons.

- [X] Would it make sense to create classes for the molecules and boundaries lists which would allow you to implement show methods
- We thought of this, but it is not clear to us how to do this without losing the current nested list structure. As an alternative, we have changed strMolecules and strBoundaries to showMolecules and showBoundaries, which hopefully is a more intuitive name. 

- [X] Please provide an “Installation” section in your vignette

## Unit tests

- [X] It is highly recommended to add unit tests to the package that cover the main functionality

## R code

- [X] Please check that you use the provided getter/setter functions in your internal R code (e.g. `me@molecules` in `.flatten_molecules`)
- [X] Please try to address the following NOTEs:

```
    * NOTE: Avoid sapply(); use vapply()
    * NOTE: Avoid ‘cat’ and ‘print’ outside of ‘show’ methods
```

- [X] Please check that function arguments are tested for validity. For example:

```
> countMolecules(“test”)
The boundaries were retrieved from the “cell” assay. A
different assay (e.g., “nucleus”) can be specified in the boundaries_assay
argument)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘molecules’ for signature ‘“character”’
```

- In addition, we have replaced countMolecules to work with terra, instead of sp.

Thank you @lgeistlinger for your input on using terra for countMolecules! In our testing it has dramatically reduced the time compared to the original sp based implementation. Regarding the output to BumpyMatrix we will add this as an issue to be added in the near future!

Best wishes,
Shila

**Comment by nilseling** [comment] 2023-04-14 14:54
Hi @shazanfar 

thanks for addressing my previous comments. There are still a couple of minor things that need to be looked at before I can accept the package:

- [ ] As a general guide, the `pkgdown` files should be located in a different branch. I usually use Github actions to build the site automatically in the `gh-pages` branch.
- [ ] There is no need to use `paste` in messages. You can simply use `message("The ", moleculesAssay, "assay ...")` 
- [ ] Could you please explain the need for `suppressMessages` in `countMolecules.R`?
- [ ] You could use `importFrom(rlang, .data)` and `.data[[segment_id]]` to get rid of the last `checking R code for possible problems ...` NOTEs
- [ ] Please double check the formatting of the `NEWS` file and have a look [here](https://contributions.bioconductor.org/news.html) on how to format it.

**Comment by shazanfar** [comment] 2023-04-17 03:41
Thanks for this @nilseling ! We have made the changes you've listed accordingly,

- [x] As a general guide, the `pkgdown` files should be located in a different branch. I usually use Github actions to build the site automatically in the `gh-pages` branch.
- [x] There is no need to use paste in messages. You can simply use `message(“The “, moleculesAssay, “assay ...“)`
- [x] Could you please explain the need for `suppressMessages` in `countMolecules.R`?
- The idea was to avoid messages when using getters internally, but the code has been rewritten now to avoid using as many suppressMessages(). Now there is only one use of it remaining, to avoid repetition of the getter message.
- [x] You could use `importFrom(rlang, .data)` and `.data[[segment_id]]` to get rid of the last checking R code for possible problems ... NOTEs
- [x] Please double check the formatting of the NEWS file and have a look [here](https://contributions.bioconductor.org/news.html) on how to format it.

Thanks again for your feedback on our MoleculeExperiment package!

Best wishes,
Shila

**Comment by nilseling** [comment] 2023-04-17 08:19
This looks great, thanks! I'm happy to accept the package.

**Comment by lshep** [comment] 2023-04-17 12:20
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shazanfar.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MoleculeExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MoleculeExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-04-17 12:20 UTC
Labels: OK, 3a. accepted
