### ISSUE TITLE
SpaceMarkers

### ISSUE THREAD

**Issue by atuldeshpande** [Bioconductor/Contributions#3196] opened 2023-09-30 00:48 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/atuldeshpande/SpaceMarkers

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2023-10-02 15:01
You currently download example data for the man example and vignette from github.  Downloading from personal github and dropboxes are not allowed.  A smaller dataset should be included in the package or the data should be hosted on a trusted public server like zenodo, AWS S3 buckets, Azure Microsoft Data Lakes, etc  , minimally an institutional level server.  See also ExperimentHub

**Comment by atuldeshpande** [comment] 2023-10-06 22:09
Hi @lshep 
We've updated the package to avoid downloads from the GitHub repository.

**Comment by lshep** [comment] 2023-10-13 17:17
I'm manually kicking off a rebuild of the package to see if the linux error was a temporary situation.

**Comment by atuldeshpande** [comment] 2023-11-02 14:33
Hi @Kayla-Morrell , can you please advise on whether we will need to resubmit the package or if we could continue the review in this thread itself?

**Comment by Kayla-Morrell** [comment] 2023-11-02 14:50
@atuldeshpande - Why would you need to resubmit? If you were thinking because of the release, things were a bit busy but now that we are post-release I will be working on reviews again. The review will continue on this thread.

**Comment by atuldeshpande** [comment] 2023-11-03 15:56
Thanks! That makes sense.

**Comment by Kayla-Morrell** [comment] 2023-11-16 16:33
@atuldeshpande - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: Running R CMD check resulted in "Running examples in 'SpaceMarkers-Ex.R' failed."
- [ ] REQUIRED: Running R CMD check resulted in "Error(s) in re-building vignettes."
- [ ] REQUIRED: The README file should also demonstrate to users how to install
  the package from Bioconductor.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.3.0 to 4.4.0.
- [ ] SUGGESTION: We encourage including the 'BugReports:' field with a relevant
  link to GitHub for reporting issues.

## NAMESPACE

- [ ] REQUIRED: Generally `importFrom()` is encouraged over importing an entire
  package. If there are many functions from a single package being used, than
`import()` is acceptable but its use should be kept to a minimum.
- [ ] REQUIRED: There are some packages listed under 'Imports:' in the
  DESCRIPTION file that do not show up in the NAMESPACE file, and vice versa.

## Data

- [ ] REQUIRED: Generally data used in tests belongs in the 'inst/extdata/'
  directory and would need corresponding documentation persent in the
'inst/scripts/' directory.

## Vignette

- [ ] SUGGESTION: I would rename the vignette file to something a little more
  relevant to the package, i.e. SpaceMarkers_vignette.
- [ ] REQUIRED: All code blocks should be evaluated.
- [ ] SUGGESTION: We suggest the use of the 'BiocStyle' package for formatting.
- [ ] REQUIRED: The Installation section should not be commented out and should
  demonstrate to the user how to install the package from Bioconductor. The code
should remain in an `eval = FALSE` code chunk.
- [ ] SUGGESTION: We strongly encourage the use of table of contents.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to main functions. Users should be able to have a relevant
page display with `?SpaceMarkers`.


Best,
Kayla

**Comment by lshep** [comment] 2024-01-26 12:49
@atuldeshpande  do you plan on pushing updates soon? We like to keep package submissions moving forward

**Comment by atuldeshpande** [comment] 2024-02-08 21:03
Hi @lshep yes, we are nearly done with the updates. Will submit the package by this Friday! Sorry did not notice your message sooner.

**Comment by atuldeshpande** [comment] 2024-02-14 16:21
Hi @Kayla-Morrell , we have updated the package in response to the review comments. 
Thanks!

**Comment by Kayla-Morrell** [comment] 2024-03-06 18:06
@atuldeshpande - Thank you for making the necessary changes. I have just one requirement that needs to be met before I can accept the package. Please see the requirement below and let me know when the change(s) have been made.

## Data

- [ ] REQUIRED: Thank you for including 'inst/extdata'. There needs to be an 'inst/script/' directory that contains documentation about the data present in 'inst/extdata'. The scripts in the directory can vary. Most importantly the documentation should include information about how the data was generated and source information. It should include source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description. Users should be able to download and be able to roughly reproduce the file or object that is present as data.

Best,
Kayla

**Comment by atuldeshpande** [comment] 2024-03-18 16:53
Thanks, will push an update soon!

**Comment by Kayla-Morrell** [comment] 2024-04-02 19:35
@atuldeshpande - Thank you for making that change. I've reviewed everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by atuldeshpande** [comment] 2024-04-04 01:21
Hi @Kayla-Morrell , We have pushed a new version with the requested changes.

**Comment by lshep** [comment] 2024-04-04 14:13
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/atuldeshpande.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpaceMarkers")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpaceMarkers

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-04-04 14:13 UTC
Labels: OK, 3a. accepted
