### ISSUE TITLE
ptairData

### ISSUE THREAD

**Issue by camilleroquencourt** [Bioconductor/Contributions#1948] opened 2021-03-05 15:28 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/camilleroquencourt/ptairData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by camilleroquencourt** [comment] 2021-03-12 14:51
AdditionalPackage: https://github.com/camilleroquencourt/ptairMS

**Comment by Kayla-Morrell** [comment] 2021-03-25 16:43
@camilleroquencourt - Thank you for submitting to _Bioconductor_. Please see the initial review of
the packages below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

# ptairData

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less
  that 3 sentences. Please consider expanding this field and structure it as a
full paragraph.

- [ ] SUGGSTION: We strongly encourage including the 'BugReports:' field with a
  relevant link to GitHub for reporting Issues.

## NEWS

- [ ] REQUIRED: If you intend to include a NEWS file please add at least one
  entry to it. See our documentation here,
https://bioconductor.org/developers/package-guidelines/#news for proper
formatting of the NEWS file.

## Data

- [ ] REQUIRED: We require that documentation for 'inst/extdata/' files be
  present in an 'inst/script/' directory. The scripts in this directory can
vary. Documentation should very cleary state how the data was generated. It
should include source urls and any important information regarding filtering or
processing. It can be executible code, sudo code, or a text description. A user
should ber able to download the data and roughly reproduce the file or object
that is present as data.

## Vignette

- [ ] REQUIRED: I would add an 'Installation' section that demonstrates to the
  user how to install/load the package from Bioconductor. The code should look
something like the following and should include `eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ptairData")
```

- [ ] REQUIRED: The last section of the vignette should be 'Session Information'
  and should include `sessionInfo()`.

# ptairMS

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to 'false'. It is our experience that
  when this field is set to 'true' it can slow down the loading of the package,
especially if it contains data.

- [ ] SUGGESTION: Based on the biocViews you provided, consider adding these
  automatically suggested biocViews:
	SingleCell
	QualityControl

- [ ] SUGGESTION: We encourage the use of the 'BugReports:' field with a
  relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: There are many packages listed in the 'Imports:' field of your
  DESCRIPTION file that aren't listed here. Please be sure that these files
match up.

- [ ] REQUIRED: Generally `importFrom()` is encouraged over importing an entire
  package, however if there are many functions from a single package than
`import()` is okay. Please change accordingly.

## NEWS

- [ ] REQUIRED: Thank you for providing a NEWS file but it doesn't seem to be
  formatted properly. Please take a look at our documentation here,
https://bioconductor.org/developers/package-guidelines/#news, that will show how
to format the document as well as how to check to make sure it is correct.

## Data

- [ ] REQUIRED: We require documentation on any files present in the
  'inst/extdata' directory. The documentation should be present in an
'inst/script' directory. The scripts in this directory can vary but they should
very clearly state how the data was generated. It should include source urls and
any important information regarding filtering or processing. It can be
executible code, sudo code, or a text description. A user should be able to
download the data and roughly reproduce the file or object that is present as
data.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to install/load the package from Bioconductor. The code should
look like the following and should inclue `eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ptairMS")
```

- [ ] REQUIRED: In order for your vignette to be reproducable, most (if not all)
  code chunks need to be visable to the user. There are many plotting sections
that are `echo = FALSE` so then the user has no idea how to run the proper
function to get those plots. These should be shown to the user as much as
possible.

## Man pages

- [ ] REQUIRED: In the data documentation (exhaledPtrset.Rd and
  mycobacteriaSet.Rd) they state the data comes from 'inst/extdata' but these
files are not here. Perhaps they are from the ptairData package? If so, please
edit the documentation to reflect that.

- [ ] SUGGESTION: For any non exported function that is documented I would
  suggest adding the `@keywords internal` tag to the documentation. This will
remove the function from the documentation index.

- [ ] REQUIRED: We normally don't allow the usage of dontrun{}/donttest{} found 
in man page examples without valid reasons. If it is absolutely necessary to use
one of these we suggest using donttest{} instead of dontrun{} since donttest{}
requires proper R code. Found in the following files:
        changeTimeLimits.Rd
        convert_to_mzML.Rd
        writeEset.Rd

## Unit tests

- [ ] SUGGESTION: There is an incomplete final line found in the test file 
'test-annotation.R'. I think to clear this up you just have to remove the extra
empty lines at the end of the document.

## R code

- [ ] REQUIRED: Avoid the use of direct slot access with `@` or `slot()`. 
Accessor methods should be created and utilized instead.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 746
  lines that are > 80 characters long.

- [ ] SUGGESTION. For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 1162 lines that are not.

## C/Fortran code

- [ ] REQUIRED: Is there a reason why you have multiple src directories?
  Normally we only need one, the 'src/' directory.

Best,
Kayla

**Comment by camilleroquencourt** [comment] 2021-04-08 14:31
@Kayla-Morrell - Thank you for reviewing our package. I have made most of your suggestions and requests, detailed here : 

> # ptairData
> ## DESCRIPTION
> * [x]  SUGGESTION: The Description field in the DESCRIPTION is made up by less
>   that 3 sentences. Please consider expanding this field and structure it as a
>   full paragraph.
> * [x]  SUGGSTION: We strongly encourage including the 'BugReports:' field with a
>   relevant link to GitHub for reporting Issues.
> 
> ## NEWS
> * [x]  REQUIRED: If you intend to include a NEWS file please add at least one
>   entry to it. See our documentation here,
>   https://bioconductor.org/developers/package-guidelines/#news for proper
>   formatting of the NEWS file.
> 
> ## Data
> * [x]  REQUIRED: We require that documentation for 'inst/extdata/' files be
>   present in an 'inst/script/' directory. The scripts in this directory can
>   vary. Documentation should very cleary state how the data was generated. It
>   should include source urls and any important information regarding filtering or
>   processing. It can be executible code, sudo code, or a text description. A user
>   should ber able to download the data and roughly reproduce the file or object
>   that is present as data.
> 
> ## Vignette
> * [x]  REQUIRED: I would add an 'Installation' section that demonstrates to the
>   user how to install/load the package from Bioconductor. The code should look
>   something like the following and should include `eval = FALSE`.
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("ptairData")
> ```
> 
> * [x]  REQUIRED: The last section of the vignette should be 'Session Information'
>   and should include `sessionInfo()`.
> 
> # ptairMS
> ## DESCRIPTION
> * [x]  REQUIRED: 'LazyData:' should be set to 'false'. It is our experience that
>   when this field is set to 'true' it can slow down the loading of the package,
>   especially if it contains data.

> * [ ]  SUGGESTION: Based on the biocViews you provided, consider adding these
>   automatically suggested biocViews:
>   SingleCell
>   QualityControl

Those biocViews suggestion don't match with our package.

> * [x]  SUGGESTION: We encourage the use of the 'BugReports:' field with a
>   relevant link to GitHub for reporting Issues.
> 
> ## NAMESPACE
> * [ ]  REQUIRED: There are many packages listed in the 'Imports:' field of your
>   DESCRIPTION file that aren't listed here. Please be sure that these files
>   match up.

As is recommended here https://r-pkgs.org/namespace.html, I did not import the function, I used pckname::fct for all external function used. That explain why the entire imported package in description are not in namespace. It is okay?

> * [x]  REQUIRED: Generally `importFrom()` is encouraged over importing an entire
>   package, however if there are many functions from a single package than
>   `import()` is okay. Please change accordingly.
> 
> ## NEWS
> * [x]  REQUIRED: Thank you for providing a NEWS file but it doesn't seem to be
>   formatted properly. Please take a look at our documentation here,
>   https://bioconductor.org/developers/package-guidelines/#news, that will show how
>   to format the document as well as how to check to make sure it is correct.
> 
> ## Data
> * [x]  REQUIRED: We require documentation on any files present in the
>   'inst/extdata' directory. The documentation should be present in an
>   'inst/script' directory. The scripts in this directory can vary but they should
>   very clearly state how the data was generated. It should include source urls and
>   any important information regarding filtering or processing. It can be
>   executible code, sudo code, or a text description. A user should be able to
>   download the data and roughly reproduce the file or object that is present as
>   data.
> 
> ## Vignette
> * [x]  REQUIRED: There should be an 'Installation' section that demonstrates to
>   the user how to install/load the package from Bioconductor. The code should
>   look like the following and should inclue `eval = FALSE`.
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("ptairMS")
> ```
> 
> * [x]  REQUIRED: In order for your vignette to be reproducable, most (if not all)
>   code chunks need to be visable to the user. There are many plotting sections
>   that are `echo = FALSE` so then the user has no idea how to run the proper
>   function to get those plots. These should be shown to the user as much as
>   possible.
> 
> ## Man pages
> * [x]  REQUIRED: In the data documentation (exhaledPtrset.Rd and
>   mycobacteriaSet.Rd) they state the data comes from 'inst/extdata' but these
>   files are not here. Perhaps they are from the ptairData package? If so, please
>   edit the documentation to reflect that.
> * [x]  SUGGESTION: For any non exported function that is documented I would
>   suggest adding the `@keywords internal` tag to the documentation. This will
>   remove the function from the documentation index.

> * [ ]  REQUIRED: We normally don't allow the usage of dontrun{}/donttest{} found
>   in man page examples without valid reasons. If it is absolutely necessary to use
>   one of these we suggest using donttest{} instead of dontrun{} since donttest{}
>   requires proper R code. Found in the following files:
>   changeTimeLimits.Rd
>   convert_to_mzML.Rd
>   writeEset.Rd

convert_to_mzML and writeEset are functions that write a file in a absolute file path. I removed dontrun() and added a line that delete the file created, to not have file in the package directory. But the function changeTimeLimits run a shiny app, and I didn’t find a solution to close the app from R consol. That make problems when I use devtools::check : run_examples never finish, even if I useddonttest{}. So I let dontrun{} for this function. Do you know about this problems? 

> ## Unit tests
> * [x]  SUGGESTION: There is an incomplete final line found in the test file
>   'test-annotation.R'. I think to clear this up you just have to remove the extra
>   empty lines at the end of the document.
> 
> ## R code
> * [x]  REQUIRED: Avoid the use of direct slot access with `@` or `slot()`.
>   Accessor methods should be created and utilized instead.
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 746
>   lines that are > 80 characters long.

> * [ ]  SUGGESTION. For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 1162 lines that are not.
> 
I formated the code with formatR package, the lines that are not indents by 4 spaces are lines that are aligned with the previous ones (line break) . 

> ## C/Fortran code
> * [x]  REQUIRED: Is there a reason why you have multiple src directories?
>   Normally we only need one, the 'src/' directory.

I hope the changes will be satisfactory, I remains at your disposal if you have more suggestions. 
Best regards,
Camile

**Comment by Kayla-Morrell** [comment] 2021-04-20 15:53
@camilleroquencourt - Thank you for making the necessary changes and justifying where needed. I've reviewed both packages and everything looks good now. I'm more than happy to accept them.

Best,
Kayla

**Comment by camilleroquencourt** [comment] 2021-04-20 16:02
@Kayla-Morrell , thank you very much for reviewing the two pakages, I'm happy that both are accepted.

Best, 
Camille

**Comment by vjcitn** [comment] 2021-04-21 13:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/camilleroquencourt.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ptairData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ptairData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment] 2021-04-21 13:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/camilleroquencourt.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ptairMS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ptairMS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-04-21 13:02 UTC
Labels: 3a. accepted, OK
