### ISSUE TITLE
SGC-Pipeline

### ISSUE THREAD

**Issue by na396** [Bioconductor/Contributions#2828] opened 2022-10-07 16:32 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/na396/SGC-Pipeline

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-10-11 11:09
Thanks for this submission.   The example data documentation includes
```
An object of class matrix with 1500 rows * 10 columns, where rows and columns are the genes and samples respectively.
```
for "cheng".  Bioconductor packages should use SummarizedExperiment for data in this form, so that metadata and data are tightly coupled.  Please use this class in your package.

**Comment by lshep** [comment] 2022-10-11 12:48
I noticed you changed the name of your repository to try to force it through the review process.  Sorry I could not assist on Friday as I was away for the US holiday weekend.  There was a previous package from a different group that had tried to submit a SGC package back in 2019 which was causing the issue.   Currently the name of the package is malformed as there should not be a hyphen in a package name.  We do recommend something more informative that just SGC; especially since there is a SGC standing for The Structural Genomics Consortium that could easily be confused. We would recommend closing this issue and reopening with a valid name.

**Comment by vjcitn** [comment] 2022-10-11 13:50
Yes, use a valid and suggestive name like semisupGeneClust

**Comment by na396** [comment] 2022-10-13 00:36
Hello Ishep and vjcitn
Many thanks for the message and help. If I change the package name, then I have to change many functions consequently. So I decided to pick "SGCP" as it stands for self-training gene clustering pipeline. But before changing anything, I was wondering if you could tell me that this name ("SGCP") is fine with Bioconductor?
Many thanks in advance

**Comment by na396** [comment] 2022-10-13 01:32
Hello @vjcitn 
Thanks for your comment on "cheng.Rd". I read the package " SummarizedExperiment" and I was hoping if you accept that not to use this class for my data, as the input of my package is only a matrix and a vector. " SummarizedExperiment" is very interesting, however, this makes my pipeline to rely on one more package, and makes things more complicated. My main aim was to make the package as simple as possible.

**Comment by vjcitn** [comment] 2022-10-13 01:46
The issue isn't the simplicity of the software but the use of a standard representation familiar to bioconductor users.  There is no reason to refrain from depending on SummarizedExperiment.  There are many reasons to use it.  So please reconsider.

**Comment by na396** [comment] 2022-10-13 19:23
Greetings @vjcitn 
I have corrected the data. Please let me know if I need to change anything else.

**Comment by na396** [comment] 2022-10-13 19:26
Hello @lshep 
Many thanks for your help so far. I decided to pick "SGCP" for my package, just wondering if is available?
Thank you so much

**Comment by vjcitn** [comment] 2022-10-13 20:12
Thanks for using SummarizedExperiment.  I think you should take advantage of its capabilities.  I see 
```
> cheng
class: SummarizedExperiment 
dim: 1000 5 
metadata(0):
assays(1): ''
rownames: NULL
rowData names(1): geneEntrezID
colnames: NULL
colData names(0):
> head(colData(cheng))
DataFrame with 5 rows and 0 columns
> assay(cheng[1:4,1:3])
         [,1]      [,2]      [,3]
[1,] 4.608516  4.822920 11.477016
[2,] 6.566498 11.170815 10.721761
[3,] 6.925341  9.098948  9.550381
[4,] 6.020677 10.545173  6.398164
> rowData(cheng[1:4,])
DataFrame with 4 rows and 1 column
  geneEntrezID
   <character>
1         7503
2    100462977
3         4878
4         4879
```
It would be helpful to users to have more information in rowData -- for example, the associated gene symbols.  Also, the 5 samples have some characteristics, don't they?  Do they have an identifier?  Is there a treatment or other sample characteristic?  Those would go in the colData.  The documentation of `cheng` references a paper that is behind a firewall.  Please describe the data and how they were normalized, etc., in the documentation.  The metadata component of the SummarizedExperiment could also supply some information.

**Comment by na396** [comment] 2022-10-13 20:35
@vjcitn 
Thank you so much for the comment. Actually, that metadata is not very practical for my case, i.e. gene co-expression networks. Unlike single cell clustering, in gene co-expression networks, only the cluster of genes matter. That's why I was not very interested in "summarizedExperiment" class.  I can say no one in gene co-expression network is using this class (example: https://www.bioconductor.org/packages/release/bioc/vignettes/CEMiTool/inst/doc/CEMiTool.html)
But I will add the gene symbol in addition to the Entrez ID for more information. And I will add the normalization method in the document.
Many thanks

**Comment by na396** [comment] 2022-10-13 21:57
@vjcitn I added more information to the data. Thanks

**Comment by vjcitn** [comment] 2022-10-14 12:09
just tagging @lshep in case i get something wrong here -- the package should be renamed in DESCRIPTION, close this issue, start a new one with the correct name SGCP

**Comment by lshep** [comment] 2022-10-14 12:12
Yes please rename the repository and the DESCRIPTION,  close this issue and start a new one. We can mark the new issue as passing precheck right away so it is ready for processing and to be assigned a reviewer.  Cheers

**Comment by na396** [comment] 2022-10-14 14:56
Thank you so much

**Comment by na396** [comment] 2022-10-14 15:05
@lshep 
I submitted the "SGCP" , is #2840. Thank you so much

**Closed as completed** 2022-10-14 15:05 UTC
