### ISSUE TITLE
epiNEM

### ISSUE THREAD

**Issue by MartinFXP** [Bioconductor/Contributions#245] opened 2017-01-13 12:17 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/cbg-ethz/epiNEM

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment] 2017-01-13 13:54
At first glance it is somewhat surprising that a package which "extends the NEM package" does not depend on it (and the package name is lowercase). The vignette is a wall of code without any explanation.

**Comment by vobencha** [comment] 2017-01-23 17:47
Hi,

I've done a first review of epiNEM. Please see comments / suggestions below.

(1) R CMD check

This NOTE from R CMD check is telling you something is wrong with the dependencies. Packages used only in man page examples and/or the vignette need to be in the Suggests field.
```
* checking for unstated dependencies in vignettes ... NOTE
'library' or 'require' calls not declared from:
  ‘STRINGdb’ ‘bnem’ ‘devtools’ ‘minet’ ‘pcalg’
```
Please correct the imports.

(2) incomplete man pages for data sets

The man pages for the datasets must describe the following:
- download location
- qc or processing to get them in the current format
- what type of R object they are; dimensions; row and column names if any

(3) inconsistent function names vs man page names

- the man page is MLL (all caps) but the name of the function is Mll (l's are small)
- the man page is createExtendedAdjacency but the name of the function is CreateExtendedAdjacency

(4) epiNEM.Rd man page

i) Please enhance the description to describe what the function does.
```
\description{
Epistatic NEMs - main function
}
```
ii) value{} section
What does this mean? Is this a class? Are there rows and/or columns with meaning?
```
\value{
optimized logical network
}
```
iii) Please remove this argument if not used:
```
\item{plotsy}{atm not used}
```
(5) GenerateData man page

The man page does not explain what type of data is generated or why a user would use it. What are the column and row names, dimensions, etc.

Is this function necessary? You have saved datasets as examples and presumably others will have their own data to analyze. Please explain.
```
> head(sortedData)
           A B B.C C A B B.C C A B B.C C
reporter-1 0 1   1 1 0 1   0 1 1 0   0 1
reporter-2 0 1   1 0 0 1   1 0 0 1   0 0
reporter-3 1 0   0 1 1 0   0 1 1 0   1 1
reporter-4 0 1   1 0 0 0   1 0 0 1   0 0
reporter-5 0 1   1 0 0 1   1 0 0 1   0 0
reporter-6 0 0   0 1 1 0   0 1 1 0   0 1
```
(6) outputs

Why not output the igraph classes of igraph and dgCMatrix? It does not make sense to say (in the man page) the function outputs an an adjacency matrix when it simply produces a matrix. Please modify these functions to output

Output dgCMatrix:
CreateExtendedAdjacency(), CreateTopology(), ExtendTopology()

Output igraph:
CreateRandomGraph()

I realize the nem package may not be integrated with these igraph objects. That package, however, is very old (in Bioconductor 10+ years) and the infrastructure has come a long way since it was added to the repo. We ask that new packages be integrated with the current infrastructure to promote interoperability, easy of use etc.

(7) vignette: loading packages

Everything your package needs should be in one of Depends, Imports or Suggests. When this is properly specified you only need to load packages with library(). If something is not installed, it can be 'got' with biocLite().

Please replace install.packages() with biocLite() in this statement:
```
install.packages("devtools", repos = "https://cloud.r-project.org/")
```
(8) vignette: github code

The package cannot depend on or use code from github. Dependencies must be in CRAN or Bioconductor. You can point users to additional code or documentation on github but it must not be used in the package. Please remove these lines from the vignette:

install_github("MartinFXP/B-NEM")
install_github("rstudio/rmarkdown")

(9) vignette: structure

I have no idea what is going on in lines 96 - 385. Is this a helper function? What is it doing? It's ok to define small helpers in the vignette but substantial functions necessary for analysis should be in R/, have a man page and be exported. Also not sure what is going on in lines 388-475. The vignette needs to have text explaining what the code is doing. There are many examples of good vignette layouts. Here are a couple of examples,

http://www.bioconductor.org/packages/release/bioc/vignettes/affycoretools/inst/doc/RefactoredAffycoretools.pdf

http://www.bioconductor.org/packages/release/bioc/vignettes/snm/inst/doc/snm.pdf

Please add a TOC, use BiocStyle and re-work the vignette so explanatory text and code are interspersed.

(10) Where is the bnem package? I don't see it in CRAN or Bioconductor.

(11) imports

If you fully import igraph adding selective imports is redundant:
import(igraph)
importFrom(igraph,graph.adjacency)
importFrom(igraph,plot.igraph)

Please remove the importFrom() statements.

Let me know if you have questions.

Valerie

**Comment by MartinFXP** [comment] 2017-01-25 13:33
Dear Valerie,

thank you very much for your time and input. In the following I address all points you make.

> (1) R CMD check
> 
> This NOTE from R CMD check is telling you something is wrong with the dependencies. Packages used only in man page examples and/or the vignette need to be in the Suggests field.
> 
> * checking for unstated dependencies in vignettes ... NOTE
> 'library' or 'require' calls not declared from:
>   ‘STRINGdb’ ‘bnem’ ‘devtools’ ‘minet’ ‘pcalg’
> Please correct the imports.

I updated the Suggests field accordingly.

> (2) incomplete man pages for data sets
> 
> The man pages for the datasets must describe the following:
> 
> download location
> qc or processing to get them in the current format
> what type of R object they are; dimensions; row and column names if any

I improved the man pages accordingly.

> (3) inconsistent function names vs man page names
> 
> the man page is MLL (all caps) but the name of the function is Mll (l's are small)
> the man page is createExtendedAdjacency but the name of the function is CreateExtendedAdjacency

I fixed those inconsistencies.

> (4) epiNEM.Rd man page
> 
> i) Please enhance the description to describe what the function does.
> 
> \description{
> Epistatic NEMs - main function
> }
> ii) value{} section
> What does this mean? Is this a class? Are there rows and/or columns with meaning?
> 
> \value{
> optimized logical network
> }
> iii) Please remove this argument if not used:
> 
> \item{plotsy}{atm not used}

I improved the description of the main function and also added a detailed description of the returned object. "plotsy" has been removed.

> (5) GenerateData man page
> 
> The man page does not explain what type of data is generated or why a user would use it. What are the column and row names, dimensions, etc.
> 
> Is this function necessary? You have saved datasets as examples and presumably others will have their own data to analyze. Please explain.
> 
> > head(sortedData)
>            A B B.C C A B B.C C A B B.C C
> reporter-1 0 1   1 1 0 1   0 1 1 0   0 1
> reporter-2 0 1   1 0 0 1   1 0 0 1   0 0
> reporter-3 1 0   0 1 1 0   0 1 1 0   1 1
> reporter-4 0 1   1 0 0 0   1 0 0 1   0 0
> reporter-5 0 1   1 0 0 1   1 0 0 1   0 0
> reporter-6 0 0   0 1 1 0   0 1 1 0   0 1

I updated the descripton of this function.

> (6) outputs
> 
> Why not output the igraph classes of igraph and dgCMatrix? It does not make sense to say (in the man page) the function outputs an an adjacency matrix when it simply produces a matrix. Please modify these functions to output
> 
> Output dgCMatrix:
> CreateExtendedAdjacency(), CreateTopology(), ExtendTopology()
> 
> Output igraph:
> CreateRandomGraph()
> 
> I realize the nem package may not be integrated with these igraph objects. That package, however, is very old (in Bioconductor 10+ years) and the infrastructure has come a long way since it was added to the repo. We ask that new packages be integrated with the current infrastructure to promote interoperability, easy of use etc.

A simple matrix is exactly what an adjacency matrix is. I realize igraph is a general package for graph manipulation. So it makes sense to use a sparse "matrix" object, which radically reduces memory usage for large graphs. However, epiNEM is not designed for graphs the size of more than 20 nodes (I'd say everything over 50 is _really_ pushing it).

Additionally, if someone wants to play around with epiNEM results and use the igraph package for subsequent analysis steps, igraph offers lots of ways to handle "normal" adjacency matrices, e.g. graph.adjacency().

For this reason I would like to keep the epiNEM outputs as "simple" matrices, which is more general and flexible.

> (7) vignette: loading packages
> 
> Everything your package needs should be in one of Depends, Imports or Suggests. When this is properly specified you only need to load packages with library(). If something is not installed, it can be 'got' with biocLite().
> 
> Please replace install.packages() with biocLite() in this statement:
> 
> install.packages("devtools", repos = "https://cloud.r-project.org/")

I fixed this accordingly.

> (8) vignette: github code
> 
> The package cannot depend on or use code from github. Dependencies must be in CRAN or Bioconductor. You can point users to additional code or documentation on github but it must not be used in the package. Please remove these lines from the vignette:
> 
> install_github("MartinFXP/B-NEM")
> install_github("rstudio/rmarkdown")

B-NEM is the official abbreviation of Boolean Nested Effects Models. As with the original NEM, the package name is in lower case. So NEM is nem and B-NEM is bnem. This is just for clarification.
bnem is not yet available on CRAN or Bioconductor. EpiNEM itself does not depend on bnem. However, we provide a comparison of the two related methods in the vignette. The goal is to submit bnem to bioconductor also, but since bnem is a much larger package with a much more complex underlying model, it requires additional code cleaning before it is submitted. The simulation study results are included in a data object. Hence, it is not actually necessary to install, load or run bnem. I added the availability of bnem as a github repository/R-package in the running text and as comments in the code. Is that ok?

The automated single package builder at bioconductor.org gave an error exclusively for the Windows build:

http://bioconductor.org/spb_reports/epiNEM_buildreport_20170113094452.html

I researched that error message and found evidence that adding the rmarkdown repository would solve the issue, which it did. I removed the github install and added the dependency on rmarkdown and it is now being installed with biocLite() during build_vignettes.

> (9) vignette: structure
> 
> I have no idea what is going on in lines 96 - 385. Is this a helper function? What is it doing? It's ok to define small helpers in the vignette but substantial functions necessary for analysis should be in R/, have a man page and be exported. Also not sure what is going on in lines 388-475. The vignette needs to have text explaining what the code is doing. There are many examples of good vignette layouts. Here are a couple of examples,
> 
> http://www.bioconductor.org/packages/release/bioc/vignettes/affycoretools/inst/doc/RefactoredAffycoretools.pdf
> 
> http://www.bioconductor.org/packages/release/bioc/vignettes/snm/inst/doc/snm.pdf
> 
> Please add a TOC, use BiocStyle and re-work the vignette so explanatory text and code are interspersed.

I am still revising this point. Apart from adding more explanation to the vignette, I'm trying to figure out how to make it less bloated (e.g. 96 - 385), but still functional.

> (10) Where is the bnem package? I don't see it in CRAN or Bioconductor.

Please see above (point 8).

> (11) imports
> 
> If you fully import igraph adding selective imports is redundant:
> import(igraph)
> importFrom(igraph,graph.adjacency)
> importFrom(igraph,plot.igraph)
>
> Please remove the importFrom() statements.

I fixed this accordingly.

Best,
Martin

**Comment by MartinFXP** [comment] 2017-01-25 14:33
I have no idea how and why that error on mac exists all of a sudden. I personally tested it on El Capitan and it works.

**Comment by MartinFXP** [comment] 2017-01-25 16:57
I have no idea how and why that error on mac exists all of a sudden. I personally tested it on El Capitan and it works.

**Comment by vobencha** [comment] 2017-01-31 21:26
While you're working on tidying up the vignette remember the built tarball must be <=4MB:
http://www.bioconductor.org/developers/package-guidelines/#correctness

**Comment by MartinFXP** [comment] 2017-02-10 13:45
Ok, I cleaned up the vignette. Let me know what you think. The tarball size should be fine.

Is it me or is there something wrong with the automatic build system? The error which happened during the mac os x build, now happens during the linux build and mac os x vanished. What's up with that?

**Comment by lshep** [comment] 2017-02-14 13:49
When you are saving or writing files in your vignette/man please save to a tempdir() not a system directory. This is the cause of the ERROR.

**Comment by MartinFXP** [comment] 2017-02-14 13:57
Thx, I'll try to figure out how to change that. However, I'm pretty sure it has to do with the STRINGdb package and not by me manually saving/writing files. Anyway, this does not explain why it did work on Linux before, when the exact same error happended on MacOs, on which it also worked before. Also, since when does the automatic build skip the BiocCheck and still claims everything ok?

**Comment by lshep** [comment] 2017-02-14 14:03
We changed the single package builder to prevent writing to system directories. This is why it is now occurring.  I will look into why BiocCheck is not running on windows. Thank you for bringing this to our attention.

**Comment by vobencha** [comment] 2017-02-21 20:23
Hi,

Thanks for making the changes - the vignette is looking better. Still a few things to address.

1) vignette
* TOC
-- How about section numbers 1, 2, 3 ... instead of 0.1, 0.2, 0.3 ...?
-- Add a section for sessionInfo() and References.

* commented out code chunks
There are several chunks of commented out code, for example, one starts on line 250:
```
## ---- eval=FALSE---------------------------------------------------------
## for (i in 1:ncol(llmat)) {
##     if (sum(!(llmat[, i] %in% c(0,-Inf))) > 0) {
##         top30 <- llmat[, i]
##         top30[which(top30 == 0)] <- -Inf
...
```

  Are these the curation steps to produce the sameith_string data loaded just after the chunk? If yes, these steps should be mentioned in the man page and included as code in the epiNEM/inst/scripts/ directory.

* reduce size of yeast knockout section
I think the yeast section tries to accomplish too much - it spans pages 8-32. There is a lot of code and plots but not much explanation. Please reduce the number of code chunks and plots and add more text explanation of what is going on. You don't' need to demonstrate every possible analysis - just hit the highlights and mention the others. You can also refer the interested reader to the man pages.

  It would also be helpful to add subsections in the yeast section and have them numbered in the TOC.

* remove all instances of biocLite'ing packages:
Sorry if I wasn't clear in my previous comments.  The devtools, rmarkdown and STRINGdb packages are in 'Suggests' so there is no need to re-download all of these in the vignette. You only need to load them with library().  You can show an unevaluated chunk of how the user can download biocLite() but this is generally unnecessary:
```
source("https://bioconductor.org/biocLite.R")
```
Please remove these biocLite() statements and use only library().
```
source("https://bioconductor.org/biocLite.R")
biocLite("devtools")
biocLite("rmarkdown")
source("https://bioconductor.org/biocLite.R")
biocLite("STRINGdb")
```

* HeatmapOP plots
The x-axis on the plots created by HeatmapOP() are completely unreadable.

2) epiAnno() man page
Explain more about what this function does. It looks like a baseline or reference of sorts. When would it be used, why is it important to export, etc.?

3) documentation of static data objects
All data object man pages refer the reader to the vignette for an explanation of how the files were created. You have a couple of options:
- option 1: In the man pages refer the user to the vignette (as you have done). Make a separate section in the vignette, at the end, that describes creation of the data objects include in the package. This code should not be evaluated; the point of static files is to save time and memory when running R CMD build and check.
-  option 2: Briefly describe the curation process in the data man pages. Include relavant code in inst/scripts. Do not re-create the data files in the vignette.

    I would like to see the vignette cleaned up with respect to the large chunks of commented out code mentioned above in (1) and the sections that start with these downloads from holstegelab. Both should either be in a separate vignette section or inst/scripts.
```
file <- paste("http://www.holstegelab.nl/",
              "publications/sv/signaling_redundancy/downloads/DataS1.txt",
              sep = "")

file <- paste("http://www.holstegelab.nl/",
              "publications/GSTF_geneticinteractions/",
              "downloads/del_mutants_limma.txt", sep = "")
```

4) data objects in data/
Please re-save all .rda files in data/ with
```
save(..., compress='xz')
```

5) bnem
It would be helpful to have more detail in the 'Simulation' section about bnem. Specifically mention
- why it was necessary to use bnem in the simulations but not the epiNEM software package (why not just wait until bnem is ready to submit to Bioconductor and include bnem-related analysis there)
- what object has bnem simulations results and how this impacts a user of epiNEM, specifically a user that does not install bnem from github

**Comment by MartinFXP** [comment] 2017-02-23 10:03
Hi,

thanks again for the feedback.

> 1. vignette
> - TOC
> -- How about section numbers 1, 2, 3 ... instead of 0.1, 0.2, 0.3 ...?
> -- Add a section for sessionInfo() and References.

Done.

> - commented out code chunks
> There are several chunks of commented out code, for example, one starts on line 250:
> 
> ```{r}
> ## ---- eval=FALSE---------------------------------------------------------
> ## for (i in 1:ncol(llmat)) {
> ##     if (sum(!(llmat[, i] %in% c(0,-Inf))) > 0) {
> ##         top30 <- llmat[, i]
> ##         top30[which(top30 == 0)] <- -Inf
> ...
> ```
> Are these the curation steps to produce the sameith_string data loaded just after the chunk? If yes, these steps should be mentioned in the man page and included as code in the epiNEM/inst/scripts/ directory.

Added section "Creation of data objects".

> - reduce size of yeast knockout section
> I think the yeast section tries to accomplish too much - it spans pages 8-32. There is a lot of code and plots but not much explanation. Please reduce the number of code chunks and plots and add more text explanation of what is going on. You don't' need to demonstrate every possible analysis - just hit the highlights and mention the others. You can also refer the interested reader to the man pages.
>
> It would also be helpful to add subsections in the yeast section and have them numbered in the TOC.

The yeast section is supposed to a) include code for the manuscript of the Pirkl et al., 2017 reference and b) include supplementary analysis not vital for the manuscript itself.
I added more explanation to the supplementary analysis (graph based Go similarity and GO enrichment). The previous analysis steps are described in more detail in the manuscript.

> - remove all instances of biocLite'ing packages:
> Sorry if I wasn't clear in my previous comments. The devtools, rmarkdown and STRINGdb packages are in 'Suggests' so there is no need to re-download all of these in the vignette. You only need to load them with library(). You can show an unevaluated chunk of how the user can download biocLite() but this is generally unnecessary:
> 
> ```{r}
> source("https://bioconductor.org/biocLite.R")
> ```
> Please remove these biocLite() statements and use only library().
> 
> ```{r}
> source("https://bioconductor.org/biocLite.R")
> biocLite("devtools")
> biocLite("rmarkdown")
> source("https://bioconductor.org/biocLite.R")
> biocLite("STRINGdb")
> ```

Done.

> - HeatmapOP plots
> The x-axis on the plots created by HeatmapOP() are completely unreadable.

Improved.

> 2. epiAnno() man page
> Explain more about what this function does. It looks like a baseline or reference of sorts. When would it be used, why is it important to export, etc.?

Improved.

> 3. documentation of static data objects
> All data object man pages refer the reader to the vignette for an explanation of how the files were created. You have a couple of options:
> 
> - option 1: In the man pages refer the user to the vignette (as you have done). Make a separate section in the vignette, at the end, that describes creation of the data objects include in the package. This code should not be evaluated; the point of static files is to save time and memory when running R CMD build and check.
> 
> - option 2: Briefly describe the curation process in the data man pages. Include relavant code in inst/scripts. Do not re-create the data files in the vignette.
> 
> I would like to see the vignette cleaned up with respect to the large chunks of commented out code mentioned above in (1) and the sections that start with these downloads from holstegelab. Both should either be in a separate vignette section or inst/scripts.
> 
> ```{r}
> file <- paste("http://www.holstegelab.nl/",
>               "publications/sv/signaling_redundancy/downloads/DataS1.txt",
>               sep = "")
> 
> file <- paste("http://www.holstegelab.nl/",
>               "publications/GSTF_geneticinteractions/",
>               "downloads/del_mutants_limma.txt", sep = "")
> ```

Improved accordingly.

> 4. data objects in data/
> Please re-save all .rda files in data/ with
> ```{r}
> save(..., compress='xz')
> ```

Done.

> 5. bnem
> It would be helpful to have more detail in the 'Simulation' section about bnem. Specifically mention
> - why it was necessary to use bnem in the simulations but not the epiNEM software package (why not just wait until bnem is ready to submit to Bioconductor and include bnem-related analysis there)
> - what object has bnem simulations results and how this impacts a user of epiNEM, specifically a user that does not install bnem from github

I added more explanation of when and why B-NEM is necessary and when it is not.

Best,
Martin

**Comment by vobencha** [comment] 2017-03-02 16:11
Thanks for the work you've done to improve the package. I'm marking as accepted and you should get an email in the next few days with svn credentials and explaining next steps.

Valerie

**Comment by MartinFXP** [comment] 2017-03-03 08:07
Great. Thanks for all the feedback.

Martin

**Closed** 2017-03-04 09:42 UTC
Labels: 3a. accepted, OK
