### ISSUE TITLE
RBioFormats

### ISSUE THREAD

**Issue by aoles** [Bioconductor/Contributions#2793] opened 2022-10-03 23:33 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/aoles/RBioFormats

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-10-04 10:07
Please add an introductory paragraph to vignette indicating role in the Bioconductor ecosystem and general scientific value of the package, so that a newcomer to your package could appreciate its value.

**Comment by aoles** [comment] 2022-10-04 14:47
I've followed the instructions on setting up the remote upstream repo but for some reason I'm unable to push, see below. Any ideas?

```
$ git remote add upstream git@git.bioconductor.org:packages/RBioFormats.git
$ git remote -v
origin	https://github.com/aoles/RBioFormats.git (fetch)
origin	https://github.com/aoles/RBioFormats.git (push)
upstream	git@git.bioconductor.org:packages/RBioFormats.git (fetch)
upstream	git@git.bioconductor.org:packages/RBioFormats.git (push)
$ git fetch --all
Fetching origin
Fetching upstream
From git.bioconductor.org:packages/RBioFormats
 * [new branch]      master     -> upstream/master
$ git push upstream master
FATAL: W any packages/RBioFormats a.oles DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by lshep** [comment] 2022-10-04 14:49
Have you activated the GitCredentials account for ssh keys?

**Comment by lshep** [comment] 2022-10-04 14:53
I think I see what the issue is.  I tried an adjustment on our end. Can you please try again.

**Comment by aoles** [comment] 2022-10-04 14:55
Thanks a lot Lori for your prompt help! ❤️

**Comment by LiNk-NY** [comment] 2022-10-13 17:18
Hi Andrzej, @aoles 
Thank you for your submission. 
Please see the review below. 
Best regards,
Marcel

---

# RBioFormats #2793

* Overall, the package looks to be in good shape. 
* The classes exported are primarily S4. I don't really understand the need for
S3 method definitions. Can you please clarify?

## DESCRIPTION

* Consider adding a URL pointing to the GitHub repository landing page.
* Looks good.

## NAMESPACE

* Looks good.

## vignettes/

* Include an installation section with the `BiocManager` code needed to
install the package from Bioconductor.
* Have you considered using `xml2`? If so, are there any advantages to using
`XML`?
* Avoid mentioning the GitHub package in the vignette once the package
has been accepted to Bioconductor.
* Remove the `html` product from the folder.
* Minor. It's more natural to use `library` instead of `require` in the
vignette.
* Minor. For readability and maintenance, consider staying within the 80-width
character limit in the vignette.

## R

* I am not sure what is `print.AnnotatedImage` needed for when there is a `show`
method?
* Consider using `setAs` rather than `as.Image.AnnotatedImage` coercion.
* It may be better to have explicit arguments in the constructor function, e.g.,
`AnnotatedImage(Image = Image())` and have the validity checks be part of the
function.
* There may be more value to using the `setClass` generator function rather than
`new` within the constructor function. See https://stackoverflow.com/a/16248773
* Use the `metadata` and `metadata<-` generics in `S4Vectors` and avoid creating
a `metadata<-` generic
* Consider adding robustness in terms of internet connectivity to `.bioformats_jar_url`

## tests

* Most functions have some coverage, consider adding coverage to those with 0%.

```r
> covr::package_coverage()
RBioFormats Coverage: 60.00%
R/read.metadata.R: 0.00%
R/read.omexml.R: 0.00%
R/zzz.R: 5.26%
R/ImageMetadata.R: 5.71%
R/AnnotatedImage.R: 16.67%
R/utils.R: 16.67%
R/metadataAccessors.R: 51.28%
R/read.image.R: 87.50%
R/write.image.R: 91.30%
R/mockFile.R: 100.00%
```

## /

* Move or remove the `misc` directory from the top level

**Comment by lawremi** [comment] 2022-10-22 18:33
Does it really need to attach rJava to the search path?

**Comment by aoles** [comment] 2022-10-22 19:34
Good catch @lawremi , thank you for pointing this out! I've moved rJava from `Depends` to `Imports`.

**Comment by aoles** [comment] 2022-10-24 23:16
Dear Marcel @LiNk-NY,

Thank you very much for the thorough review of my package. Please find my inline answers below.

I really hope the package can still make it into the upcoming release. 

Looking forward to hearing from you soon. 
Cheers! 

---

>     * The classes exported are primarily S4. I don't really understand the need for
>       S3 method definitions. Can you please clarify?

While indeed the classes are S4, there are a few S3 methods which come in handy when interacting with these classes such as `print` and `as.Image`. You will find more details in my comments below. 

As for `seriesCount` I would say that from the practical point of view it probably doesn't make much difference whether it is defined as an S3 generic or a S4 method as long as it dispatches only on a single argument. The advantage of the S3 approach I see is that it avoids all of the S4 dispatch overhead. What would be the practical benefits of rewriting these methods to S4?

> ## DESCRIPTION
> 
>     * Consider adding a URL pointing to the GitHub repository landing page.

Done.

> ## vignettes/
> 
>     * Include an installation section with the `BiocManager` code needed to
>       install the package from Bioconductor.
> 
>     * Have you considered using `xml2`? If so, are there any advantages to using
>       `XML`?
> 
>     * Avoid mentioning the GitHub package in the vignette once the package
>       has been accepted to Bioconductor.
> 
>     * Remove the `html` product from the folder.
> 
>     * Minor. It's more natural to use `library` instead of `require` in the
>       vignette.
> 
>     * Minor. For readability and maintenance, consider staying within the 80-width
>       character limit in the vignette.

I've addressed all of the above issues.

> ## R
> 
>     * I am not sure what is `print.AnnotatedImage` needed for when there is a `show`
>       method?

The `print` methods are there primarily because, unlike the `show` generics, they can have additional arguments. These arguments allow for a handy way to control how the object data is  being displayed. See the example use of `short` and `list.len` arguments in the package vignette.

>     * Consider using `setAs` rather than `as.Image.AnnotatedImage` coercion.

This one is actually quite tricky. As `AnnotatedImage` class `contains` its superclass `Image` normally there wouldn't be any need for defining the coercion explicitly. However, `AnnotatedImage` sets `dimnames` on `.Data` which might be undesired for `Image`. Consider the following example.
``` r
library(RBioFormats)
#> BioFormats library version 6.10.1
library(EBImage)

f <- system.file("images", "sample-color.png", package="EBImage")

img_ebimage <- readImage(f)
img_rbioformats <- read.image(f)

img_coerced <- as(img_rbioformats, "Image")

identical(img_ebimage, img_coerced)
#> [1] FALSE
identical(img_ebimage, unname(img_coerced))
#> [1] TRUE
identical(img_ebimage, as.Image(img_rbioformats))
#> [1] TRUE
```
In fact, `as.Image.AnnotatedImage` uses the default coercion method internally and just removes `dimnames` from its product. Because there is an `as.Image` generic already provided such solution seemed quite natural to me. Do you think there are better ways of addressing this?

>     * It may be better to have explicit arguments in the constructor function, e.g.,
>       `AnnotatedImage(Image = Image())` and have the validity checks be part of the
>       function.

I've refactored the the code to provide default arguments in the constructor rather than in `prototype`argument to `setClass`. I'm not sure, however, I understand the point about moving validity checks to the constructor. Could you maybe clarify please?

>     * There may be more value to using the `setClass` generator function rather than
>       `new` within the constructor function. See https://stackoverflow.com/a/16248773

Thanks a lot for pointing this out. I've followed Martin's suggestions from the SO answer and I think they are a great improvement to the code and it's readability.

>     * Use the `metadata` and `metadata<-` generics in `S4Vectors` and avoid creating
>       a `metadata<-` generic

Done.

> ## tests
> 
>     * Most functions have some coverage, consider adding coverage to those with 0%.

Improved coverage:

```r
> covr::package_coverage()
RBioFormats Coverage: 70.75%
R/zzz.R: 15.79%
R/AnnotatedImage.R: 16.67%
R/ImageMetadata.R: 48.65%
R/metadataAccessors.R: 51.35%
R/read.metadata.R: 85.71%
R/read.image.R: 90.48%
R/write.image.R: 91.30%
R/mockFile.R: 100.00%
R/read.omexml.R: 100.00%
R/utils.R: 100.00%
```

> ## /
> 
>     * Move or remove the `misc` directory from the top level

I've listed the `misc` directory under `.Rbuildignore` such that it won't be included in the package tarball. I believe it is fine to keep the directory, especially considering that it takes up only a few KBytes on disk.

**Comment by aoles** [comment] 2022-10-24 23:21
> Please add an introductory paragraph to vignette indicating role in the Bioconductor ecosystem and general scientific value of the package, so that a newcomer to your package could appreciate its value.

Fair point, thanks a lot @vjcitn! I've added a brief introduction to the vignette as you recommended.

**Comment by LiNk-NY** [comment] 2022-10-28 15:50
Hi Andrzej, @aoles 
Thank you for making those changes. 

> The `print` methods are there primarily because, unlike the `show` generics, they can have additional arguments. These arguments allow for a handy way to control how the object data is  being displayed. See the example use of `short` and `list.len` arguments in the package vignette.

It is a bit unusual to have a `print` for an S4 class but I suppose it doesn't hurt to have the additional `print` functionality around. 

> In fact, `as.Image.AnnotatedImage` uses the default coercion method internally and just removes `dimnames` from its product. Because there is an `as.Image` generic already provided such solution seemed quite natural to me. Do you think there are better ways of addressing this?

It's more natural, I think, to coerce using the `as("class", object)` method with S4 classes. The `dimnames` can be removed with the coercion function definition. Generally, mixing syntax from both S3 and S4 might confuse users in the long run. 

> I've refactored the the code to provide default arguments in the constructor rather than in `prototype`argument to `setClass`. I'm not sure, however, I understand the point about moving validity checks to the constructor. Could you maybe clarify please?

I meant that the validity checks could be part of the checks for the inputs in `AnnotatedImage` but they seem to be redundant because you are constructing `Image` from the `...` inputs. According to `?validObject`, the validity methods will be run for `Image` superclass so no need to check for `is(object, "Image")` as a validity method.
 
Note also that the `metadata` argument in `AnnotatedImage` could be made more flexible by supporting `list` inputs and / or taking the metadata from the `Image(...)` input. 

Best regards,
Marcel

**Comment by lshep** [comment] 2022-12-16 12:12
@aoles  What is the status of this submission? Did you have any responses to @LiNk-NY comments above?

**Comment by vjcitn** [comment] 2023-01-03 15:57
@aoles i do hope this can move forward soon!

**Comment by aoles** [comment] 2023-01-06 20:59
Dear Lori @lshep,

thanks for checking in! I've been quite busy over the past few months and haven't managed to address all of the reviewers comments. Now when catching up, I've run into the following error on **merida1**. Any idea whether there is anything I can do on my side to resolve this, or is it rather a problem with the Mac builder?

Happy New Year!  🎉 
Andrzej

```
===============================

 R CMD BUILD

===============================

* checking for file RBioFormats/DESCRIPTION ... OK
* preparing RBioFormats:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building RBioFormats.Rmd using rmarkdown
No Java runtime present, requesting install.
2023-01-05 19:43:51.523 R[43280:494512394] JLRequestRuntimeInstall: Error calling: CFMessagePortCreateRemote
```

**Comment by vjcitn** [comment] 2023-01-06 21:45
@jwokaty could you have a look at this?

**Comment by jwokaty** [comment] 2023-01-09 22:58
I started looking into this, but I need to dig a little deeper because it's not clear why it's not building since Java is installed:

```
> library(rJava)
> .jinit()
> .jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
[1] "14.0.1+7"
```

**Comment by jwokaty** [comment] 2023-01-10 23:28
Merida1 seems to have trouble with line 169 in the vignette:

```{r read.image slices, fig.small=TRUE}
for(t in seq_len(coreMetadata(metadata)$sizeT)) {
  frame <- read.image(f, subset = list(T = t)) # Line 169
  EBImage::display(frame)
}
```

The rest of the vignette seems fine, but running that line takes me out of my session:

```
> library(RBioFormats)
BioFormats library version 6.10.1
> f <- system.file("images", "nuclei.tif", package = "EBImage")
> metadata <- read.metadata(f)
> read.image(f)
No Java runtime present, requesting install.
merida1:tmp biocbuild$ 
```

**Comment by aoles** [comment] 2023-01-11 14:50
Thanks @jwokaty for looking into this!

This is really strange, I haven't experienced such issues on any other system before. I'm afraid there is too little information for me to follow up on this, however, I suspect there might still be some problem with the Java setup on the builder. Does it have JDK rather than JRE installed? The installation instructions at https://github.com/aoles/RBioFormats#mac-os-x are a few years old and probably outdated, but they still might give you some hints.

Cheers!

**Comment by vjcitn** [comment] 2023-01-11 21:02
I am turning off the error.  We think this is a problem with merida1.  Proceed with review/response and let's wrap this up.

**Comment by aoles** [comment] 2023-01-11 23:00
Dear Marcel, @LiNk-NY 

Thank you for all your feedback and let me apologize for my delayed response. I had quite a busy time before Christmas, and then I was off the grid during the holiday season.

> > In fact, `as.Image.AnnotatedImage` uses the default coercion method internally and just removes `dimnames` from its product. Because there is an `as.Image` generic already provided such solution seemed quite natural to me. Do you think there are better ways of addressing this?
> 
> It's more natural, I think, to coerce using the `as("class", object)` method with S4 classes. The `dimnames` can be removed with the coercion function definition. Generally, mixing syntax from both S3 and S4 might confuse users in the long run.

In order to reduce the S3/S4 confusion I have implemented the S4 coerce method as suggested. Furthermore, I have converted `seriesCount` S3 generics to S4 methods. Apart from the `print` methods the only S3 method now left is `as.Image.AnnotatedImage`. I would argue that as a method for the generic defined in EBImage it should be fine to keep it, see `?EBImage::as.Image`.

> Note also that the `metadata` argument in `AnnotatedImage` could be made more flexible by supporting `list` inputs and / or taking the metadata from the `Image(...)` input.

Thanks, this is indeed an appealing idea which I will certainly consider as a possible further improvement. For the time being, however, I believe the current interface is sufficient for the initial release on BioC.

Last but not least, the timeout behavior on jar download has been improved in https://github.com/aoles/RBioFormats/commit/a8051c9012924c86c1ee6c46548625a27581a814.

I really appreciate the time you took to review my code and I would like to use the opportunity to thank you again for your advises which, I believe, truly improved the quality of the package. I also hope that all of your concerns have been addressed by now and that the package could be accepted soon. 🤞 

Cheers,
Andrzej

**Comment by LiNk-NY** [comment] 2023-01-12 00:00
Hi Andrzej, @aoles 

I hope you had a nice holiday. 

Thank you for following up and working on those points. 

The package looks to be in good shape, I ran build and check on the most recent checkout and it passes. 

As you continue to maintain your package, consider addressing notes produced by `BiocCheck::BiocCheck`. 

Best regards,
Marcel

**Comment by aoles** [comment] 2023-01-12 10:12
Awesome, great news! 🎉 

Thanks again Marcel @LiNk-NY for the review, and thank you Vince @vjcitn for your help throughout this process.

**Comment by lshep** [comment] 2023-01-20 12:45
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aoles.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RBioFormats")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RBioFormats

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-01-20 12:45 UTC
Labels: OK, 3a. accepted
