### ISSUE TITLE
hmdbQuery package submitted

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/Contributions#493] opened 2017-09-23 16:11 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/vjcitn/hmdbQuery

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment] 2017-10-05 19:45
# hmdbQuery review

 Build and install ok.

 ## DESCRIPTION

 * Describe utilities, description not enough to get an idea what the package does.

 ## NAMESPACE

 * ok

 ## vignette

 * ok

 ## man

 * ok

 ## R

 * hmreg.R is completely commented out. Remove this if not needed.

 * formatting R code in S4.R would help in readability. (consider formatR)

 * You don't need `cat(paste(`, you can just use `cat`. (S4.R, l19-24)

 * Address warnings :

     * WARNING: Update R version dependency from 3.3 to 3.4.

 ## Data

 * More description is needed for the data, for how it has been processed.

**Comment by nturaga** [comment] 2017-10-16 14:06
Hi @vjcitn 

Your package looks good for acceptance except for the build error caused by the vignette. If it is fixed by tomorrow, it can go in the Bioconductor 3.6 release.

**Comment by vjcitn** [comment] 2017-10-16 14:17
Thanks Nitesh.  It was failing owing to a server error and I am trying
again.
The package will need to be bulletproofed against that but I can't do it
today.
I am trying to trigger a new build.  We'll see if it makes it.  It is ok if
it is held
back.

**Comment by nturaga** [comment] 2017-10-16 18:10
Hi @vjcitn 

I see that it builds now without error.

**Comment by nturaga** [comment] 2017-12-10 16:16
Hi @vjcitn,

Since the release is done, i'm hoping you are ok with getting in it now. You will have till next release to fix or improve some functionality. 

Let me know.

**Comment by nturaga** [comment] 2018-01-11 17:45
@vjcitn Since the package seemed acceptable, I have accepted it. It will be in devel, and you can make further changes there.

**Comment by vjcitn** [comment] 2018-01-11 17:52
thanks

**Comment by mtmorgan** [comment] 2018-01-11 18:12
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/vjcitn.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"hmdbQuery\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hmdbQuery

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Closed by mtmorgan** 2018-01-11 18:12 UTC
Labels: 3a. accepted, OK
