### ISSUE TITLE
faers

### ISSUE THREAD

**Issue by Yunuuuu** [Bioconductor/Contributions#3227] opened 2023-11-01 08:00 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Yunuuuu/faers

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Yunuuuu** [comment] 2023-11-20 17:42
Thank you for the review. I have subscribed to the mailing list, but it appears that there is a delay

**Comment by Kayla-Morrell** [comment] 2024-01-04 14:36
@Yunuuuu - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: Installation instructions in the README file should also
  include Bioconductor installation instructions.

## DESCRIPTION

- [ ] SUGGESTION: The Description field is made up by less than 3
  sentences. Please consider expanding this field and structuring it as a full
paragraph.
- [ ] REQUIRED: Update R version dependency from 3.5.0 to 4.4.0.
- [ ] SUGGESTION: Provide either the 'URL' or 'BugReports' field.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file so your package news will be
  included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: Since you are including data in the `inst/extdata` directory
  there needs to be documentation of the data included in the `inst/script`
directory. We don't allow for the `data-raw` directory within our packages so I
assume the files here could belong in the `inst/script` directory. Documentation
scripts should clearly state how the data within `inst/extdata` was generated
and provide source information. It should include source URLs and any key
information regarding filtering or processing. It can be executable code, sudo
code, or text description. Users should be able to download and roughly
reproduce the file or object that is present as data.

## Vignette

- [ ] SUGGESTION: We encourage the use of the `BiocStyle` package for
  formatting.
- [ ] REQUIRED: There should be an 'Introduction' section that serves as an
  abstract to introduce the objective, models, unique functions, key points,
etc. that distinguish the package from other packages in the same area.
- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how to
  install the package from Bioconductor, not your github.
- [ ] SUGGESTION: We strongly encourage the use of table of contents.

## Man pages

- [ ] REQUIRED: There need to be runnable examples for all exported objects.
  Ideally this means runnable examples within man pages, but we would also take
vignette code or tests. It's important to know that these functions indeed work
and be able to easily catch when they don't. This applies to the following two
functions which have no runnale code, have the tests skipped if there is not a
specific directory present, and are not used in the vignette code.
        - faers_counts()
        - faers_standardize()

## R code

- [ ] REQUIRED: Avoid '<<-' if possible (found 1 times),
  R/import-standalone-cli.R line 88
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 169
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 68 lines that are not.

Best,
Kayla

**Comment by Yunuuuu** [comment] 2024-01-13 14:40
Dear @Kayla-Morrell , we extend our sincerest gratitude for your unwavering dedication and valuable time in meticulously evaluating our package. Please find below our responses to your insightful review

# General package development
- [x] Installation instructions in the README file should also include Bioconductor installation instructions.

# DESCRIPTION
- [x] SUGGESTION: The Description field is made up by less than 3 sentences. Please consider expanding this field and structuring it as a full paragraph.
- [x] REQUIRED: Update R version dependency from 3.5.0 to 4.4.0.
- [x] SUGGESTION: Provide either the 'URL' or 'BugReports' field.

# NEWS
- [x] SUGGESTION: Consider adding a NEWS file so your package news will be included in Bioconductor release announcements.

We greatly appreciate your valuable suggestion. After reviewing the BioConductor Package development book, we found that employing an `md` file would be deemed acceptable. Consequently, we have made the choice to augment our project by incorporating a NEWS.md file.

# Data
- [x] REQUIRED: Since you are including data in the inst/extdata directory there needs to be documentation of the data included in the inst/script directory. We don't allow for the data-raw directory within our packages so I assume the files here could belong in the inst/script directory. Documentation scripts should clearly state how the data within inst/extdata was generated and provide source information. It should include source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or text description. Users should be able to download and roughly reproduce the file or object that is present as data.

Yes, we have put the code generate data in `inst/extdata` into `data-raw`  folder, by following your advice, we have moved it into `inst/script` folder and taken the necessary steps to ensure that the documentation scripts, providing detailed and comprehensive information on how the data within inst/extdata was generated. 

# Vignette
- [x] SUGGESTION: We encourage the use of the BiocStyle package for formatting.

In the new submission, we have used BiocStyle package to generate `html_document` document

- [x] REQUIRED: There should be an 'Introduction' section that serves as an abstract to introduce the objective, models, unique functions, key points, etc. that distinguish the package from other packages in the same area.

In the new submission, we added the introduction section in our vignette

- [x] REQUIRED: The 'Installation' section should demonstrate to the user how to install the package from Bioconductor, not your github.

Added

- [x] SUGGESTION: We strongly encourage the use of table of contents.

Added

# Man pages
REQUIRED: There need to be runnable examples for all exported objects. Ideally this means runnable examples within man pages, but we would also take vignette code or tests. It's important to know that these functions indeed work
and be able to easily catch when they don't. This applies to the following two functions which have no runnale code, have the tests skipped if there is not a specific directory present, and are not used in the vignette code.
- [x] faers_counts() 
fixed by using internal example data

- faers_standardize()

Apologies for the inconvenience caused by the restriction on the `faers_standardize` function, which internally used MedDRA data to standardize the FAERS database. MedDRA, being a specialized and comprehensive terminology for regulatory information sharing in the field of medical products, plays a vital role in encoding the adverse effects within FAERS.

However, we do not possess the legal rights to distribute the MedDRA data, making it challenging for us to include it within our package. Nevertheless, scholars can easily obtain MedDRA data after appropriate application. As a result, we cannot provide a fully runnable example code involving MedDRA but do lots of tests in local computer. 

We appreciate your understanding in this matter and thank you for your comprehension of the limitations surrounding the distribution of MedDRA.

# R code
- [x] REQUIRED: Avoid '<<-' if possible (found 1 times), R/import-standalone-cli.R line 88
Removed

- [] SUGGESTION: For formatting reasons, consider shorter lines. There are 169 lines that are > 80 characters long.

Lots of long lines are running message not the code self which make it challenging to reduce their length. 

- [] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 68 lines that are not.

We have tried to re-style our package with 4 spaces as the indents, but there remains 49 lines, which we are unable to locate the specific locations. We apologize for any inconvenience caused.

**Comment by Kayla-Morrell** [comment] 2024-02-21 15:08
@Yunuuuu - Thank you for making the necessary changes. I have reviewed everything and I am more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment] 2024-02-22 18:28
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Yunuuuu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("faers")`. The package 'landing page' will be created at

https://bioconductor.org/packages/faers

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-02-22 18:28 UTC
Labels: OK, 3a. accepted
