### ISSUE TITLE
VplotR

### ISSUE THREAD

**Issue by js2264** [Bioconductor/Contributions#1547] opened 2020-07-08 14:08 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/js2264/VplotR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by js2264** [comment] 2020-07-16 18:45
Dear @dvantwisk, 
I've addressed the different error/warning messages obtained from initial build/check runs. I am now left with only minor "Note" messages. 
Let me know if the package seems to be ready for review or if you want me to do anything else before that!
Best, Jacques

**Comment by js2264** [comment] 2020-08-03 15:42
Hi @dvantwisk,
Any idea of when the review would be done?
Best, J

**Comment by Kayla-Morrell** [comment] 2020-08-07 13:00
Hello @js2264 - Thank you for your patience, I will be posting the initial review here within the next couple days.

**Comment by Kayla-Morrell** [comment] 2020-08-07 15:15
@js2264 - 

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The TODO file should be removed.

## DESCRIPTION

- [ ] SUGGESTION: The GPL-3 is a standard license so you don't have to include 
the LICENSE file.

- [ ] REQUIRED: I see `GenomicAlignments` listed under 'Imports:' but I don't 
see it listed in the NAMESPACE file. Please either remove from 'Imports:' or be 
sure it is included in the NAMESPACE.

## Data

- [ ] REQUIRED: I was able to find the use of all the data files, whether that 
be in the vignette, in R code/examples, or in tests, but I wasn't able to locate 
where 'seqinfos' is used? Is this file necessary? If not, please remove it.

## Vignettes

- [ ] REQUIRED: There should be an 'Introduction' section that serves as an 
abstract to introduce the package and functionality of it.

- [ ] REQUIRED: There should be an 'Installation' section that demonstates to 
the user how to install/download the package from Bioconductor. The code should 
look like the following and include `eval = FALSE`,

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("VplotR")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: All code chunks should be executable and therefore should not 
include `eval = FALSE`. Having this option defeats the purpose of having a 
reproducable vignette.

- [ ] REQUIRED: Line 72, data should not be accessed from a website, there is no 
guarantee that the user will be able to access this data. The data should either 
be included in the package or be included in a seperate experiment data package.

- [ ] REQUIRED: Line 225, if this a static plot for the vignette you can include 
the figure in the vignette directory. This will bypass having to get it from 
GitHub.

## Man pages

- [ ] REQUIRED: The 'figures' directory does not belong here. You should create 
an 'inst/figures/' directory and move them there.

- [ ] SUGGESTION: For all of the function you have documented that are not 
exported I would suggest adding the tag `@keywords internal`. This will remove 
the function from the documentation index.

- [ ] REQUIRED: There should be a runnable example for the following man pages 
since it documents and exported object:
        - importPEBamFiles.Rd

## Unit tests

- [ ] REQUIRED: Tests should be testable, therefore you should remove any `skip()` 
use in the tests. Ideally broken tests should be fixed, but if that isn't 
possible they should be removed. 

Best,
Kayla

**Comment by js2264** [comment] 2020-08-14 18:43
@Kayla-Morrell -

Thank you very much for your comments. I have addressed all the required comments and suggestions. I bumped the version and the checks only return Notes messages. 

Let me know if there is something else you'd like me to change/improve. 
Best, 
Jacques

> @js2264 -
> 
> Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.
> 

## General package development
* [x]  REQUIRED: The TODO file should be removed.

## DESCRIPTION
* [x]  SUGGESTION: The GPL-3 is a standard license so you don't have to include
  the LICENSE file.
* [x]  REQUIRED: I see `GenomicAlignments` listed under 'Imports:' but I don't
  see it listed in the NAMESPACE file. Please either remove from 'Imports:' or be
  sure it is included in the NAMESPACE.

## Data
* [x]  REQUIRED: I was able to find the use of all the data files, whether that
  be in the vignette, in R code/examples, or in tests, but I wasn't able to locate
  where 'seqinfos' is used? Is this file necessary? If not, please remove it.

## Vignettes
* [x]  REQUIRED: There should be an 'Introduction' section that serves as an
  abstract to introduce the package and functionality of it.
* [x]  REQUIRED: There should be an 'Installation' section that demonstates to
  the user how to install/download the package from Bioconductor. The code should
  look like the following and include `eval = FALSE`,

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("VplotR")
```

* [x]  SUGGESTION: We strongly encourage the use of table of contents.
* [x]  REQUIRED: All code chunks should be executable and therefore should not
  include `eval = FALSE`. Having this option defeats the purpose of having a
  reproducable vignette.
* [x]  REQUIRED: Line 72, data should not be accessed from a website, there is no
  guarantee that the user will be able to access this data. The data should either
  be included in the package or be included in a seperate experiment data package.
* [x]  REQUIRED: Line 225, if this a static plot for the vignette you can include
  the figure in the vignette directory. This will bypass having to get it from
  GitHub.

## Man pages
* [x]  REQUIRED: The 'figures' directory does not belong here. You should create
  an 'inst/figures/' directory and move them there.
* [x]  SUGGESTION: For all of the function you have documented that are not
  exported I would suggest adding the tag `@keywords internal`. This will remove
  the function from the documentation index.
* [x]  REQUIRED: There should be a runnable example for the following man pages
  since it documents and exported object:
  - importPEBamFiles.Rd

## Unit tests
* [x]  REQUIRED: Tests should be testable, therefore you should remove any `skip()`
  use in the tests. Ideally broken tests should be fixed, but if that isn't
  possible they should be removed.

> Best,
> Kayla

**Comment by Kayla-Morrell** [comment] 2020-08-24 18:16
@js2264 - Thank you for making the necessary changes. I have reviewed them and they look good. I am more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment] 2020-08-24 18:27
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/js2264.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("VplotR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/VplotR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-08-24 18:27 UTC
Labels: 3a. accepted, OK
