### ISSUE TITLE
SomaScan.db

### ISSUE THREAD

**Issue by amanda-hi** [Bioconductor/Contributions#3165] opened 2023-09-26 18:06 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SomaLogic/SomaScan.db

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2023-10-02 12:32
Please fix the maintainer field.  The maintainer field should be an individual (yourself or someone from your lab) not maintainer@bioconductor.org.  It looks like you specify the maintainer in Authors@R so you can remove the manual Maintainer field entirely from the DESCRIPTION completely.

**Comment by vjcitn** [comment] 2023-10-05 11:44
please fix the failing test and we can start a review

**Comment by amanda-hi** [comment] 2023-10-05 14:46
Hi! I'm unable to push to `git@git.bioconductor.org:packages/SomaScan.db`. I sent an email about it to bioc-devel@bioconductor.org on Tuesday but have gotten no response. 

I set up my upstream remote (`git@git.bioconductor.org:packages/SomaScan.db.git`) following the instructions in the New Package Workflow [git version control guide](https://contributions.bioconductor.org/git-version-control.html#new-package-workflow), but if I commit my changes and push to it (via `git push upstream main:devel`), I get the following error:

```
FATAL: W any packages/SomaScan.db maintainer DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.
```
Looks like my upstream remote is set up correctly, though:

```
> git remote -v
origin  git@github.com:amanda-hi/SomaScan.db.git (fetch)
origin  git@github.com:amanda-hi/SomaScan.db.git (push)
upstream        git@git.bioconductor.org:packages/SomaScan.db.git (fetch)
upstream        git@git.bioconductor.org:packages/SomaScan.db.git (push)
```

Additionally, `ssh -T git@git.bioconductor.org` shows that I only have "R" (read) access to my package repo, not write. And finally, I tried activating my account with BiocCredentials to update my ssh keys, but my email address (the one in the DESCRIPTION file and the one associated with my GitHub account) was not found. 

Can I be granted access to the package in the Bioc git repository so I can fix the failing test?

**Comment by lshep** [comment] 2023-10-05 14:50
The credentials got messed up with you using the maintainer@bioconductor.org email as the maintainer.  I will post when the issue is resolved.

**Comment by lshep** [comment] 2023-10-05 14:56
You should have an email from bioconductorcoreteam@gmail.com with temporary password for log in.  It should be straightened out now.

**Comment by amanda-hi** [comment] 2023-10-05 15:06
Thank you! I logged in to BiocCredentials without issue, but I'm still getting the "FATAL: ... DENIED by fallthru" error when I push to the upstream repo. I think I still only have read access:

```
> ssh -T git@git.bioconductor.org | grep "SomaScan" 
 R      packages/SomaScan.db
 ```

But according to BiocCredentials, I should have access to `SomaScan.db` (it's listed as packages I have access to), and the SSH keys in my account look right.

**Comment by lshep** [comment] 2023-10-05 15:09
Can you show your command and full output?

**Comment by amanda-hi** [comment] 2023-10-05 15:13
See below:

```
» git status
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

» git remote -v 
origin  git@github.com:SomaLogic/SomaScan.db.git (fetch)
origin  git@github.com:SomaLogic/SomaScan.db.git (push)
upstream        git@git.bioconductor.org:packages/SomaScan.db.git (fetch)
upstream        git@git.bioconductor.org:packages/SomaScan.db.git (push)

» git push upstream main:devel
FATAL: W any packages/SomaScan.db maintainer DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by lshep** [comment] 2023-10-05 15:16
Can you do a `git fetch --all` and try again.  You may also need to add a new ssh key to the credentials app.

**Comment by amanda-hi** [comment] 2023-10-05 15:48
`git fetch --all` didn't do it, but adding a new SSH key did! Thank you!!

**Comment by amanda-hi** [comment] 2023-10-10 03:16
UPDATE: Came up with a solution to my question that hopefully will suffice, so feel free to ignore the comment below! Please see [this bimap man page](https://github.com/SomaLogic/SomaScan.db/blob/main/man/SomaScanALIAS2PROBE.Rd#L28) as an example of the text I added to all `.Rd` files that were missing a `\value{}` field.

------------------------------------------------------------

Good morning! @Kayla-Morrell I have a clarification question. I'm receiving the following warning when `BiocCheck` is run on the tarball of my package in the Bioconductor Build System:

```
* Checking man page documentation...
    * WARNING: Empty or missing \value sections found in man pages.

    * NOTE: Consider adding runnable examples to man pages that
      document exported objects.
```

This warning pertains to the man pages for bimap objects (in this package, `SomaScanALIAS2PROBE`, `SomaScanSYMBOL`, etc.). Here's the full details of this warning, from the BiocCheck log:

```
* WARNING: Empty or missing \value sections found in man pages.
Found in files:
man/SomaScanALIAS2PROBE.Rd
man/SomaScanBASE.Rd
man/SomaScanENSEMBL.Rd
man/SomaScanENTREZID.Rd
man/SomaScanENZYME.Rd
man/SomaScanGENENAME.Rd
man/SomaScanGO.Rd
man/SomaScanMAP.Rd
man/SomaScanOMIM.Rd
man/SomaScanORGANISM.Rd
man/SomaScanPATH.Rd
man/SomaScanPMID.Rd
man/SomaScanREFSEQ.Rd
man/SomaScanSYMBOL.Rd
man/SomaScanTARGETFULLNAME.Rd
man/SomaScanUNIPROT.Rd
```

Do bimap objects typically need a `\value` field in their documentation, and if so, what do you suggest? Bimaps don't return an object/value the way a function typically would - based on my understanding, they need other functions like `as.list()`, `toTable()`, `mget()`, etc. to retrieve values from them. My fix for this warning would likely be to add a `\value` field describing the "returned" values as a `ProbeAnnDbBimap` object (which is just the class of the bimap). Or should I say that NULL is invisibly returned? Thanks!

**Comment by amanda-hi** [comment] 2023-10-11 17:06
Hi @Kayla-Morrell, I'm still getting a few R CMD check NOTES in my build report but some of them are (hopefully) justified. Here's a breakdown of each note and why I haven't fully addressed them:

```
NOTE: Problems with news in NEWS.md: No news entries found.
```
- Resolving this now, will push fix once I hear about the remaining notes

```
NOTE: Unexported objects imported by ':::' calls:
  AnnotationDbi:::annoStartupMessages AnnotationDbi:::dbObjectName
  See the note in ?`:::` about the use of this operator.
```
- Resolving this now, same as above

```
NOTE: Update R version dependency from 4.2.0 to 4.3.0.
```
- A number of the intended users of this package will be working in R 4.2 (I know this because I expect the package will be used in part by a team of analysts who currently must work in R 4.2). Is it possible for me to leave the minimum R version dependency at >4.2.0, the way it's currently set [in the DESCRIPTION file](https://github.com/SomaLogic/SomaScan.db/blob/main/DESCRIPTION#L19)? Or does the R version dependency *have* to be 4.3.0 because this package will (if accepted) be in the 3.18 release of Bioconductor?

```
NOTE: Consider shorter lines; 23 lines (1%) are > 80 characters long.
NOTE: Consider 4 spaces instead of tabs; 4 lines (0%) contain tabs.
NOTE: Consider multiples of 4 spaces for line indents; 151 lines (4%) are not.
```
- I've done my best to address these syntax and spacing notes, but I couldn't resolve these remaining issues. Some of the lines >80 characters are URLs or contain other strings that I can't easily break into <80 characters. The 4 lines with tabs are from imported documentation from `AnnotationDbi` (for the `keys` method, see where this is imported [in allMethods.R](https://github.com/SomaLogic/SomaScan.db/blob/main/R/allMethods.R#L13).)

**Comment by Kayla-Morrell** [comment] 2023-10-12 13:48
@amanda-hi - Since these are just notes, I can go ahead and do my initial review when every you think the package is ready. We prefer to have all ERRORs fixed before reviewing, so fixing all NOTEs are not necessary. Just let me know when you want me to proceed (please keep in mind the deadline of 10/18 for new packages to get accepted into the next release).

Best,
Kayla

**Comment by amanda-hi** [comment] 2023-10-12 16:06
In that case, the package is ready for your review now! I will add the fixes for the first 2 notes to my next update, based on your feedback.

**Comment by Kayla-Morrell** [comment] 2023-10-13 19:31
Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.
Keep in mind that the deadline to accept new packages into the Bioconductor 3.18
release is 10/18. Any packages accepted after this date will be included in the
next release.

## General package development

- [ ] REQUIRED: The README files should also include Bioconductor installation
  instructions.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.2.0 to 4.3.0.
- [ ] REQUIRED: Depends are packages that provide essential functionality for
  users of your package. It is unusual for more than three packages to be listed
as Depends. I would suggest moving some to Imports, which is meant for packages
that provide functions, methods, or classes that are used inside your package
name space.
- [ ] SUGGESTION: There are some fields in the DESCRIPTION file that we
  generally do not see from packages within Bioconductor. These fields would be
'organism', 'species', 'manufacturer', 'chipName', and 'LazyLoad'. Unless these
are absolutely necessary I would suggest removing them.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an
  entire package. If there are many functions from a single package than
`import()` may be expectable but should be selective.

## NEWS

- [ ] REQUIRED: It is great practice to include a NEWS file but it doesn't look
  like the file is formated properly. See our documentation
[here](https://contributions.bioconductor.org/news.html) about NEWS files and
formatting them. You should be able to see the rendered file when running
`utils::news(package="SomaScan.db")`.

## Data

- [ ] REQUIRED: The script in `data-raw/` belongs in an `inst/scripts/`
  directory instead. This is where documentation goes for processing the
extdata.
- [ ] REQUIRED: There needs to be more documentation about the sqlite file in
  `inst/extdata/`. Any source information or information about how the data was
genereated should be included. Also include any source URLS or key information
regarding filtering or processing. This can be executable code, sudo code, or 
a text description. 

## Vignettes

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

## Man pages

- [ ] REQUIRED: There should be no figures within the `man/` directory. I would
  suggest moving them to an `inst/figures/` directory.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 23 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
  There are 4 lines that contain tabs.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 151 lines that are not.

Best,
Kayla

**Comment by amanda-hi** [comment] 2023-10-16 05:59
Hi @Kayla-Morrell, I've implemented the changes you listed and pushed them to the upstream repo. I resolved every point except for the fast few suggestions, see my questions & notes at the bottom of this comment. 

Here's a summary of the changes I made with their corresponding commit SHAs:

**Changes Made**
---
- [372e177](https://github.com/SomaLogic/SomaScan.db/commit/372e17766aa032368aea9a2d984def983865bc8d): Add Bioconductor installation instructions to README
- [faae5a1](https://github.com/SomaLogic/SomaScan.db/commit/faae5a1f5399242177d1f1d2dec8f0b62daa24ab): Update R version dependency from 4.2.0 to 4.3.0.
- [0d51233](https://github.com/SomaLogic/SomaScan.db/commit/0d51233af4ae6b0310bb3ac332b0d95555aa55ce): Remove or relocate packages from Depends to Imports in the package DESCRIPTION file & utilize `importFrom()` instead of importing entire packages, whenever possible
- [6abdf92](https://github.com/SomaLogic/SomaScan.db/commit/6abdf924b2f268912ad6b51a1795e0d1daef9c0a): Remove uncommon or unnecessary fields from DESCRIPTION, including: 'organism', 'species', 'manufacturer', 'chipName', and 'LazyLoad'
- [381630c](https://github.com/SomaLogic/SomaScan.db/commit/381630c65d7b5241188a420fcd2cb2f7e26ef254): Format NEWS.md according to Bioconductor documentation
- [12e4812](https://github.com/SomaLogic/SomaScan.db/commit/12e4812a6163e1ded47aa06aaefb0d5de7d59db3): Move the script in `data-raw/` to `inst/scripts/` instead
- [4733725](https://github.com/SomaLogic/SomaScan.db/commit/47337257a36bc02161a506e0be8bf1c8d8a2ecd3): Add documentation about the sqlite file in `inst/extdata/`, including information about how the data was
generated
-  [f28ddb0](https://github.com/SomaLogic/SomaScan.db/commit/f28ddb09bcdd2d84d6a53a6a1f128c264ce24654): Move image file from `man/` directory to `inst/figures/`

**Questions**
---
I have a question about the suggestion below:
- We strongly encourage the use of table of contents. 

The vignettes already have a table of contents, see below for an excerpt from the YAML header at the top of each vignette:

```
output: 
  BiocStyle::html_document:
      toc_float: true
```
Is there a different/preferred way to implement a ToC in the vignettes?

**Notes**
---
I tried to cut down lines >80 chars long as much as possible ([53c2ba8](https://github.com/SomaLogic/SomaScan.db/commit/53c2ba8a93ee6d0ba6be6ffd70ebbc4d368d8486)). I can & will continue to work on this, but many of the remaining long lines are URLs or some other long string that can't easily split up. I'll think about ways to continue to reduce instances of these. 

The 4 instances of tabs (rather than spaces) are found in the imported documentation from `AnnotationDbi::keys()`. 

Please let me know if there are additional changes that I need to make. **The package is ready for a 2nd round of review**, whenever you have time. Thank you so much for your feedback!

**Comment by Kayla-Morrell** [comment] 2023-10-16 17:39
@amanda-hi - To answer your question, you need to change a line in the YAML header of the vignette. What you currently have is:

```{r}
vignette: >
  %\VignetteIndexEntry{Introduction to SomaScan.db}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
```
You should change the vignette engine to `knitr::rmarkdown`. This will render the vignette correctly in BiocStyle with the table of contents.

Everything else looks good and once this change is made I'd be happy to accept the package.

Best,
Kayla

**Comment by amanda-hi** [comment] 2023-10-16 17:41
Oh oops! Will fix that now, thanks for catching that.

**Comment by amanda-hi** [comment] 2023-10-16 18:25
Hi @Kayla-Morrell, I updated the vignette engine to use `knitr::rmarkdown`, see [this commit](https://github.com/SomaLogic/SomaScan.db/commit/37c02d07e405b4da7b7ea906f42cefe6d6b65b92).

**Comment by amanda-hi** [comment] 2023-10-16 20:25
Awesome, thanks so much @Kayla-Morrell!!! Do I need to perform another version bump now that the package is accepted, i.e. to version 1.0.0? Or will that happen automatically when 3.18 is released, [based on the version numbering docs](https://contributions.bioconductor.org/versionnum.html#new-packages)?

**Comment by lshep** [comment] 2023-10-17 18:25
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/amanda-hi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SomaScan.db")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SomaScan.db

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-10-17 18:25 UTC
Labels: OK, 3a. accepted
