### ISSUE TITLE
VeloViz

### ISSUE THREAD

**Issue by LylaAtta123** [Bioconductor/Contributions#2107] opened 2021-05-05 22:27 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/JEFworks-Lab/veloviz

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by LylaAtta123** [comment] 2021-05-18 19:42
Hi @Kayla-Morrell, 

I addressed the errors above and followed the instructions to push to `git@git.bioconductor.org:packages/veloviz` but I get the following error:

```
git push upstream package 
Enumerating objects: 54, done.
Counting objects: 100% (54/54), done.
Delta compression using up to 12 threads
Compressing objects: 100% (31/31), done.
Writing objects: 100% (33/33), 1.51 MiB | 35.85 MiB/s, done.
Total 33 (delta 23), reused 0 (delta 0)
remote: FATAL: W refs/heads/package packages/veloviz LylaAtta123 DENIED by fallthru
remote: error: hook declined to update refs/heads/package
To git.bioconductor.org:packages/veloviz
 ! [remote rejected] package -> package (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/veloviz'
```
Do you have any insight as to what might be the issue? (Note: the default github branch is `package`)

**Comment by LylaAtta123** [comment] 2021-05-19 02:29
Hi @Kayla-Morrell, 

I am currently getting one warning related to setting a seed in one of the functions. This is necessary for reproducibility as one of the internal functions is stochastic. Users can set the seed via the `seed` argument. Please let me know if this is sufficient or if there is a further modification that should be made.

Thanks!

**Comment by Kayla-Morrell** [comment] 2021-05-24 15:03
Hello @LylaAtta123 - Sorry for the late reply. Please remove any calls to `set.seed()` from within your code. While the user seeking reproducibility must call `set.seed()` explicitly, they will see immediately what the problem is. Whereas a user incorporating your package into their workflow will wonder why their calls to `set.seed()` are apparently being ignored / over-ridden by some mystery function. This is standard practice in Bioconductor and in the R community in general. If you are demonstrating these functions in example or vignette code I would suggest calling `set.seed()` before running the function. Let me know if you have any further questions.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-06-15 15:15
@LylaAtta123 - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: What is the purpose of the 'docs/' directory. This is not a
  directory that we normally allow in Bioconductor package and won't be
included. If the files are needed I would suggest moving them to a different
location, such as in the 'inst/' directory. Please let me know if you have any
questions about these files and where they might belong.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' in the DESCRIPTION file should be set to false or
  removed.

- [ ] REQUIRED: Update R version dependency from 3.6 to 4.1.

- [ ] REQUIRED: Add the packages 'grDevices', 'graphics', and 'stats' to the
  'Imports:' in the DESCRIPTION file. Also be sure these get added to the
NAMESPACE file as well.

- [ ] SUGGESTION: We encourage the use of the 'BugReports:' field which
  includes the relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: 'importFrom' is encouraged over importing an entire package. If
  there are many functions from a single package, 'import()' is okay, but we
really prefer using 'importForm'.

## Vignette

- [ ] REQUIRED: There should be an 'Introduction' section that serves as an
  abstract to introduce the objective, models, unique functions, key points,
etc that distinguish the package from other packages of similar types.

- [ ] REQUIRED: There should be an 'Installation' section that shows users how
  to download and load the package from Bioconductor. The code should look
like the following and should include `eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("veloviz")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: There should be some text along with code chunks to explain
  why/what the code is demonstrating or doing.

- [ ] REQUIRED: The last section of the vignette should be 'Session
  Information' and should include `sessionInfo()`.

## R code

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` if applicable. Found in
files:
        import.R, line 142
        projectedNeighbors.R, line 86 and 92

- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` if
applicable. Found in files:
        import.R, lines 101 and 123
        main.R, lines 105, 165, 183, and 185
        normalize.R, lines 241, 279, and 281
        projectedNeighbors.R, lines 62, 79, 86, 92, 168, 279, and 283

- [ ] REQUIRED: Avoid the use of 'paste' in condition signals. Found in files:
        main.R, line 102
        normalize.R, lines 15, 13, and 17

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are
162 lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for
line indents. There are 506 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-07-07 11:45
@LylaAtta123 - I'm just checking in to see if there has been any progress made on the review I posted. We normally like to see activity within 2-3 weeks to be sure the package is actively being worked on. Let me know if you have any further questions or need clarification on any of the points.

Best,
Kayla

**Comment by LylaAtta123** [comment] 2021-07-19 20:40
@Kayla-Morrell Sorry for the late reply - all the points should be addressed in the latest push. Thanks!

**Comment by Kayla-Morrell** [comment] 2021-07-22 15:20
@LylaAtta123 - Thank you for making the necessary changes. I have but 2 changes before I can accept the package. Please see them below and let me know when you are ready for me to re-review.

## DESCRIPTION

- [ ] REQURIED: 'LazyData:' should be set to false or removed.

- [ ] REQUIRED: Update the R version dependency from 4.0 to 4.1.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-08-05 13:47
@LylaAtta123 - Thank you for making those changes. Everything looks good and I'm more than happy to accept the package.

Best,
Kayla

**Comment by LylaAtta123** [comment] 2021-08-05 13:50
@Kayla-Morrell Great, thanks for your help!

**Comment by vjcitn** [comment] 2021-08-17 11:49
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LylaAtta123.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("veloviz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/veloviz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-08-17 11:49 UTC
Labels: OK, 3a. accepted
