### ISSUE TITLE
survtype

### ISSUE THREAD

**Issue by dongminjung** [Bioconductor/Contributions#991] opened 2019-02-05 07:14 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dongminjung/survtype

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2019-02-05 13:41
Please update all user-facing functions to accept and return [standard Bioconductor objects][1] such as [SummarizedExperiment][2]

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/
[2]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by hpages** [comment] 2019-03-18 17:10
Hi @dongminjung ,

Thanks for your submission. After taking a quick look at survtype, I found the following thing that could be improved. Lines like
```
laml.maf <- system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
laml.clin <- system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')
```
need to fail if maftools is not installed. Right now they don't. Instead the calls to `system.file()` return an empty string which causes a failure downstream, and the cause of the failure is not immediately obvious. Generally speaking it's always better to catch problems early than late. In this case this can be done by using `mustWork=TRUE` in the calls to `system.file()`, or by preceding these calls with `library(maftools)`.

Other than that the package meets our requirements. 

Thanks,
H.

**Comment by dongminjung** [comment] 2019-03-19 11:04
Hello. @hpages.

According to your review, I changed from

`laml.maf <- system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')`
`laml.clin <- system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')`

to

`library(maftools)`
`laml.maf <- system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools', mustWork = TRUE)`
`laml.clin <- system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools', mustWork = TRUE)`

However, I cannot push the commit anymore because I pushed it with version 1.X.X by mistake.

**Comment by hpages** [comment] 2019-03-21 17:12
Hi @dongminjung ,

Thanks for the change. Please bump the version of the package (from 0.99.9 to 0.99.10) in order to trigger a new build from our Single Package Builder. Thanks!

Please note that using the same non-informative commit message for all your commits is really not a good idea:
```
hpages@spectre:~/survtype$ git log -9
commit a244711cd145dde08ffef3155706faef6249c076
Author: dongminjung <dmdmjung@gmail.com>
Date:   Wed Mar 20 08:23:10 2019 +0900

    Update

commit e5db566f922ff3e4b5a1034dc9ed36308f32deed
Author: dongminjung <dmdmjung@gmail.com>
Date:   Tue Mar 19 19:52:06 2019 +0900

    Update

commit cae58f9d2d6f280e062332174bf21bb6b5d2319b
Author: dongminjung <dmdmjung@gmail.com>
Date:   Tue Mar 19 19:21:38 2019 +0900

    Update

commit 230633410dc53d1e6c6b4af1feef02a2bbdaca47
Author: dongminjung <dmdmjung@gmail.com>
Date:   Tue Mar 19 19:17:34 2019 +0900

    Update

commit 7dd791f8079d76a24dc4e7bb99d83c0cd56212c2
Author: dongminjung <dmdmjung@gmail.com>
Date:   Tue Mar 19 19:12:24 2019 +0900

    Update

commit 0647346e33e25d6bee04f97dba5242a2efdc298e
Author: dongminjung <dmdmjung@gmail.com>
Date:   Tue Mar 19 19:09:44 2019 +0900

    Update

commit 1dd697ed5ca99a1a58e08bc418539e6ec541d2b3
Author: dongminjung <dmdmjung@gmail.com>
Date:   Tue Mar 19 19:07:38 2019 +0900

    Update

commit 11401509083ac91bc2b8b0638a5e9056a18a6071
Author: dongminjung <dmdmjung@gmail.com>
Date:   Wed Feb 6 17:10:03 2019 +0900

    Update

commit 1aed2fed72544428e6206175c4a7583a85bbedc2
Author: dongminjung <dmdmjung@gmail.com>
Date:   Wed Feb 6 16:53:15 2019 +0900

    Update
```
This won't help you in the long term maintenance of your package. Also some advanced users might care about what's going on with the development of your package and these non-informative commit messages won't make it easy for them to follow the changes.

Best,
H.

**Comment by hpages** [comment] 2019-04-04 18:01
Hi @dongminjung 

Thanks for bumping the version. Package looks good and meets our guidelines.

Cheers,
H.

**Comment by mtmorgan** [comment] 2019-04-04 21:37
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dongminjung.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("survtype")`. The package 'landing page' will be created at

https://bioconductor.org/packages/survtype

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-04-04 21:37 UTC
Labels: 3a. accepted, WARNINGS
