### ISSUE TITLE
fenr

### ISSUE THREAD

**Issue by MarekGierlinski** [Bioconductor/Contributions#3017] opened 2023-04-18 11:26 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bartongroup/fenr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

Note: BiocCheck generates an error "Maintainer must register at the support site". However, I am registered, see https://support.bioconductor.org/u/7369/, and my e-mail address (M.Gierlinski@dundee.ac.uk) is the same as in the DESCRIPTION file. The following query: `https://support.bioconductor.org/api/email/M.Gierlinski%40dundee.ac.uk` returns `false`, indicating a problem with the bioconductor site. I raised this issue (https://support.bioconductor.org/p/88856/#9146483), but received no help.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by MarekGierlinski** [comment] 2023-04-21 10:19
NIH/NCAS took down the entire BioPlanet web site with no alternative (so far). I have enquired them and waiting for a reply. `fenr` depends on BioPlanet to create its vignette, mostly because it is the smallest and fastest of the databases in the package. Therefore, an attempt to build the package with vignettes will end up in failure. After I've heard from NCAS I will fix this one way or another. Please hold the moderation until then.

**Comment by MarekGierlinski** [comment] 2023-04-25 08:47
BioPlanet issue fixed, the package is ready for moderation.

**Comment by vjcitn** [comment] 2023-05-20 11:36
Please check on a clean system
```
Running examples in 'fenr-Ex.R' failed
The error most likely occurred in:

> ### Name: fetch_bp
> ### Title: Get functional term data from BioPlanet
> ### Aliases: fetch_bp
>
> ### ** Examples
>
> bioplanet_data <- fetch_bp()
Error in UseMethod("select") :
  no applicable method for 'select' applied to an object of class "c('xml_document', 'xml_node')"
Calls: fetch_bp -> <Anonymous> -> <Anonymous>
Execution halted
* checking for unstated dependencies in 'tests' ... OK
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  > test_check("fenr")
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 181 ]
```

**Comment by MarekGierlinski** [comment] 2023-05-24 17:11
This was again a BioPlanet issue. As their server has SSL certificate fixed, I removed a hack circumventing it and reverted to using read_csv. Did check in a clean system. Pushed updates to GitHub.

**Comment by MarekGierlinski** [comment] 2023-08-04 14:36
The two errors are from missing subscriptions. I've just subscribed to bioc-devel list, so one error should be sorted out.

However, the second error is on your side. I have been registered to Bioconductor support for many years, see https://support.bioconductor.org/u/7369/, and my e-mail address ([M.Gierlinski@dundee.ac.uk](mailto:M.Gierlinski@dundee.ac.uk)) is the same as in the DESCRIPTION file. The following query: https://support.bioconductor.org/api/email/M.Gierlinski%40dundee.ac.uk returns false, indicating a problem with the bioconductor site. I raised this issue (https://support.bioconductor.org/p/88856/#9146483), but received no help.

**Comment by lshep** [comment] 2023-08-04 14:39
I will investigate the issue with the support site registration error that is occurring.

**Comment by PeteHaitch** [comment] 2023-08-24 00:29
Hi @MarekGierlinski,

Thank you for submitting **fenr** to Bioconductor.

**fenr**:

1. Downloads functional data from widely used databases (GO, KEGG, BioPlanet, Reactome and WikiPathways)
2. Processes the data into a **fenr**-specific format
3. Provides a function for performing Fisher's exact test for enrichment of a given gene set against this processed data from a functional data database.

Bioconductor already contains packages that provide data from some (if not all) of these databases and other packages that perform gene set enrichment tests, so the main motivation for **fenr** is that (3) is "optimised for speed for use in interactive applications, e.g., Shiny".

In my review below I have separated the issues into **Required** and **Recommended** points that I would ask you to address before the package can be accepted.
Would you please provide line-by-line comments to my initial review so that I know what changes I'm looking for in my re-review.

Cheers,
Pete

### Required

- [ ] Given that much of the functionality in **fenr** is already available in Bioconductor, there needs to be a clearer motivation for **fenr** by comparing it to existing packages in terms of what databases **fenr** provides access to that are not already provided by other packages and some demonstration that the performance of **fenr** is superior to other packages. 
  - This comparison would probably go in the vignette. It doesn't need to be a big, systematic benchmarking exercise, but is more about helping a new user understand where **fenr** fits into the broader Bioconductor package ecosystem and when they would choose to use it or a different Bioconductor package for performing gene set enrichment analysis.
  - In general, why does **fenr** re-invent ways to download and parse data from GO, KEGG, etc. instead of using existing solutions. Perhaps it's needed, but it's not clear to me why this is.
- [ ] Since **fenr** is implementing methods to download data from the web, it must cache the files it downloads, preferably using [**BiocFileCache**](https://bioconductor.org/packages/BiocFileCache/).
  - For example, compare **fenr** functions to `biomaRt::getBM()` and its `useCache` argument.
  - Caching would provide some performance improvements since files wouldn't need to be re-downloaded each time a database was accessed.
  - Please see the [**BiocFileCache**](https://bioconductor.org/packages/BiocFileCache/) documentation, https://contributions.bioconductor.org/r-code.html?q=biocfilecach#web-querying-and-file-caching and https://contributions.bioconductor.org/querying-web-resources.html for general advice. 
  - Caching would also mean that examples may not need to be a in a `\dontrun{}` block (I think) because the Bioconductor build machines would be able to use the cached data (after the first run) and so the files wouldn't need to be re-downloaded or prolong the time to perform package checks.
- [ ] The `README.md` and vignette 'Installation' section should include the official Bioconductor installation instructions and not `remotes::install_github()` (or, if you  insist, in addition to the `remotes::install_github()` version; see https://contributions.bioconductor.org/readme.html?q=readme#readme).
- [ ] The documentation of the example data seems to have fallen out-of-sync with the actual data. `length(exmpl_all)` is 6985, not 7075 as documented, and seems to be yeast, not human as documented. Similar issue with `exmpl_sel`.
- [ ] A general principal is that no (or a minimal number of) disabled code blocks should be present in vignette. Therefore, the `interactive_prepare`-chunk should be evaluated, even though it's not used elsewhere in the vignette in an evaluated chunk (it's fine and correct that the chunks that launch Shiny apps aren't evaluated). If `fetch_terms_for_example()` (and functions underpinning it) used caching, this would effectively have no cost.
- [ ] It's a requirement that all man pages have runnable examples. That's not currently the case, but many of the pages that don't are documenting non-exported functions. If you make this documentation internal, then that will likely address/sidestep this requirement.

### Recommended

- [ ] It would be highly desirable to have simpler/better interoperability with other Bioconductor packages. The inputs and outputs of most of the **fenr** functions are *tibble*/*data.frame* objects, but things like DE results and gene sets have well-developed and widely-used data structures (e.g., *DGELRT* or *TopTags* from **edgeR** for results of a differential expression analysis).
- [ ] Vignette code is too wide for screen and scroll bar obscures it in parts. Recommend splitting the code up over multiple lines to make it easier to read.
- [ ] Just a question, but why do we get different results for `go_data_ensembl <- fetch_go(mart =  biomaRt::useEnsembl(biomart = "ensembl", dataset = "scerevisiae_gene_ensembl"))` and `go <- fetch_go(species = "sgd")`? 
- [ ] Minor: `N_with` vs. `n_with_sel` in `enr` from vignette; it seems odd to change capitalisation of `N`/`n`.
- [ ] In the vignette you write, "You can view the step-by-step process by examining the function code on GitHub.". Another simple alternative is to run `fetch_terms_for_example` in R, which will show the function code.
- [ ] Why the need for `vignettes/style.css`? Removing it doesn't seem to visually change the HTML vignette.
- [ ] Generally, commented out code ('dead code') should be removed, e.g., in `R/bioplanet.R` the `fetch_bp()` function has 'A NASTY HACK' section commented out.
- [ ] `?fetch_kegg` says "This function is based on BioConductor package KEGGREST." but **KEGGREST** is not actually used by **fenr**. Is the documentation outdated or does this mean code was copied or adapted from **KEGGREST**?
- [ ] You probably don’t want to document unexported functions. If you want to use roxygen comments for internal documentation, include the `@noRd` tag to suppress the creation of the .Rd file and/or add `@keywords internal`.
- [ ] Please try to address `NOTES` raised by `BiocCheck::BiocCheck()`.
- [ ] Title in `DESCRIPTION` could provide more context. It's currently, 'fast functional enrichment', but enrichment of what? See https://contributions.bioconductor.org/description.html#description-title.
- [ ] It's generally recommended to use selective imports using `importFrom` (`@importFrom` in **roxygen2**) rather than `import`. E.g., you have in your `NAMESPACE` the line `import stringr` but that's likely overkill because you don't need all of stringr (`grep stringr:: R/*` shows which functions seem to be actually used).
- [ ] Please check formatting (and spelling) of `NEWS.md`. Once installed, the `news()` function seems to render it as intended but there are some formatting issues in the `NEWS.md` file (e.g., whitespace before `##`-level heading and before `-` bullet points).
- [ ] Consider adding a `inst/CITATION` file if there is a publication that accompanies the software; see https://contributions.bioconductor.org/citation.html?q=citation#citation.
- [ ] Minor: The recommendation is that the vignette has an *Introduction* section. This is largely the 'Purpose` section you already have, so you could perhaps rename but it's not important.
- [ ] Consider adding a package-level man page; see https://contributions.bioconductor.org/docs.html?q=man%20pa#package-level-documentation.
- [ ] Please take a look at the results of running `covr::report()` to identify areas of the package that are lacking unit test coverage.

**Comment by MarekGierlinski** [comment] 2023-08-24 07:16
Hi Peter,

Thank you for your in-depth analysis of fenr. I'm about to go on holiday
and will address all the issues you listed after I've come back in two
weeks.

Best regards,
Marek

**Comment by PeteHaitch** [comment] 2023-08-24 11:22
No worries, enjoy your holiday!

**Comment by MarekGierlinski** [comment] 2023-09-15 11:29
Hi Pete,

Here is what I managed to do:

> ### Required
> * [x]  Given that much of the functionality in **fenr** is already available in Bioconductor, there needs to be a clearer motivation for **fenr** by comparing it to existing packages in terms of what databases **fenr** provides access to that are not already provided by other packages and some demonstration that the performance of **fenr** is superior to other packages.
>   
>   * This comparison would probably go in the vignette. It doesn't need to be a big, systematic benchmarking exercise, but is more about helping a new user understand where **fenr** fits into the broader Bioconductor package ecosystem and when they would choose to use it or a different Bioconductor package for performing gene set enrichment analysis.

I have added a new section "Comparison to other functional enrichment packages" to the vignette. I have also added a figure demonstrating the workflow of *fenr*. I hope this should help understanding the purpose of the package better.

>   * In general, why does **fenr** re-invent ways to download and parse data from GO, KEGG, etc. instead of using existing solutions. Perhaps it's needed, but it's not clear to me why this is.

In an earlier version *fenr* used *KEGGREST* and *ontologyIndex* to download and process KEGG and GO data. However, I wanted to keep the footprint of the package small and reduce the dependencies, where possible. *KEGGREST* provides APIs for KEGG, and this was replaced with one simple function `fetch_kegg_data`. The other functions in `kegg.R` file were needed anyway. *ontologyIndex* was used to parse OBO file, but the package is large, so I decided to write my own parser. As a result, *fenr* is smaller and works faster.

> * [x]  Since **fenr** is implementing methods to download data from the web, it must cache the files it downloads, preferably using [**BiocFileCache**](https://bioconductor.org/packages/BiocFileCache/).
>   
>   * For example, compare **fenr** functions to `biomaRt::getBM()` and its `useCache` argument.
>   * Caching would provide some performance improvements since files wouldn't need to be re-downloaded each time a database was accessed.
>   * Please see the [**BiocFileCache**](https://bioconductor.org/packages/BiocFileCache/) documentation, https://contributions.bioconductor.org/r-code.html?q=biocfilecach#web-querying-and-file-caching and https://contributions.bioconductor.org/querying-web-resources.html for general advice.
>   * Caching would also mean that examples may not need to be a in a `\dontrun{}` block (I think) because the Bioconductor build machines would be able to use the cached data (after the first run) and so the files wouldn't need to be re-downloaded or prolong the time to perform package checks.

Thank you for pointing me to *BiocFileCache*, I didn't know about it. Now, all static URL files are cached. The data accessed by APIs are not, I don't even think it is possible.

> * [x]  The `README.md` and vignette 'Installation' section should include the official Bioconductor installation instructions and not `remotes::install_github()` (or, if you  insist, in addition to the `remotes::install_github()` version; see https://contributions.bioconductor.org/readme.html?q=readme#readme).

It is done.

> * [x]  The documentation of the example data seems to have fallen out-of-sync with the actual data. `length(exmpl_all)` is 6985, not 7075 as documented, and seems to be yeast, not human as documented. Similar issue with `exmpl_sel`.

Corrected.

> * [x]  A general principal is that no (or a minimal number of) disabled code blocks should be present in vignette. Therefore, the `interactive_prepare`-chunk should be evaluated, even though it's not used elsewhere in the vignette in an evaluated chunk (it's fine and correct that the chunks that launch Shiny apps aren't evaluated). If `fetch_terms_for_example()` (and functions underpinning it) used caching, this would effectively have no cost.

Done.

> * [x]  It's a requirement that all man pages have runnable examples. That's not currently the case, but many of the pages that don't are documenting non-exported functions. If you make this documentation internal, then that will likely address/sidestep this requirement.

All exported functions, except for `fetch_bp` and `enrichment_interactive` have now runnable examples. The reason I excluded `fetch_bp` is due to flakiness of the BioPlanet web site (https://tripod.nih.gov/bioplanet/) in the last few months it has been down numerous times, sometimes for many days. Leaving `fetch_bp` as a runnable example can lead to build errors (see my earlier discussion with bioc-issue-bot).

> 
> ### Recommended
> * [ ]  It would be highly desirable to have simpler/better interoperability with other Bioconductor packages. The inputs and outputs of most of the **fenr** functions are _tibble_/_data.frame_ objects, but things like DE results and gene sets have well-developed and widely-used data structures (e.g., _DGELRT_ or _TopTags_ from **edgeR** for results of a differential expression analysis).

The input for *fenr* are two tibbles/data frames with simple structure. I'd like to keep it as it is. I cannot see how this could be replaced with other structures, such as the differential expression objects you mention. As for the `fenr_terms` object used by `functional_enrichment` it is specifically designed for fast access and it needs to be in the format I used (specifically, I use environments for fast hashing - this is a result of many experiments with various formats and tools).

> * [x]  Vignette code is too wide for screen and scroll bar obscures it in parts. Recommend splitting the code up over multiple lines to make it easier to read.

Done.

> * [x]  Just a question, but why do we get different results for `go_data_ensembl <- fetch_go(mart =  biomaRt::useEnsembl(biomart = "ensembl", dataset = "scerevisiae_gene_ensembl"))` and `go <- fetch_go(species = "sgd")`?

The first call returns data from Ensembl, the second from geneontology.org, as explained in the documentation to this function.

> * [x]  Minor: `N_with` vs. `n_with_sel` in `enr` from vignette; it seems odd to change capitalisation of `N`/`n`.

The idea behind it is that `N` refers to the gene background, while `n` to the gene selection. There are other quantities, internal to the function, that use `N` and `n`. In an earlier version more columns where exported in the result, and the distinction between `N` and `n` was more clear. I keep this for the moment, but if you insist, I can convert all to lowercase.

> * [x]  In the vignette you write, "You can view the step-by-step process by examining the function code on GitHub.". Another simple alternative is to run `fetch_terms_for_example` in R, which will show the function code.

Changed the text accordingly.

> * [x]  Why the need for `vignettes/style.css`? Removing it doesn't seem to visually change the HTML vignette.

Indeed, this file is not needed, removed.

> * [x]  Generally, commented out code ('dead code') should be removed, e.g., in `R/bioplanet.R` the `fetch_bp()` function has 'A NASTY HACK' section commented out.

Removed.

> * [x]  `?fetch_kegg` says "This function is based on BioConductor package KEGGREST." but **KEGGREST** is not actually used by **fenr**. Is the documentation outdated or does this mean code was copied or adapted from **KEGGREST**?

As mentioned earlier, this was a leftover from the previous version, removed.

> * [x]  You probably don’t want to document unexported functions. If you want to use roxygen comments for internal documentation, include the `@noRd` tag to suppress the creation of the .Rd file and/or add `@keywords internal`.

Added `@noRd` to all internal functions.

> * [x]  Please try to address `NOTES` raised by `BiocCheck::BiocCheck()`.

Ah, well, we might have to disagree on some of these issues. Limiting line length to 80 characters is a bit restrictive, considering modern high-resolution monitors we use nowadays. Anyway, I don't have any lines exceeding 120 characters. As for function longer than 50 lines, I'm not even sure which one are these, as `BiocCheck` does not tell me. As doe runnable examples, I explained the exceptions above. And I much prefer indents with multiple of 2 spaces, not 4.

> * [x]  Title in `DESCRIPTION` could provide more context. It's currently, 'fast functional enrichment', but enrichment of what? See https://contributions.bioconductor.org/description.html#description-title.

I changed the title slightly, not sure what else to add. There is description in the same file.

> * [x]  It's generally recommended to use selective imports using `importFrom` (`@importFrom` in **roxygen2**) rather than `import`. E.g., you have in your `NAMESPACE` the line `import stringr` but that's likely overkill because you don't need all of stringr (`grep stringr:: R/*` shows which functions seem to be actually used).

I have limited imports and use `stringr::` inside the function instead.

> * [x]  Please check formatting (and spelling) of `NEWS.md`. Once installed, the `news()` function seems to render it as intended but there are some formatting issues in the `NEWS.md` file (e.g., whitespace before `##`-level heading and before `-` bullet points).

Corrected.

> * [x]  Consider adding a `inst/CITATION` file if there is a publication that accompanies the software; see https://contributions.bioconductor.org/citation.html?q=citation#citation.

There is no publication (yet).

> * [x]  Minor: The recommendation is that the vignette has an _Introduction_ section. This is largely the 'Purpose` section you already have, so you could perhaps rename but it's not important.

I leave it as it is.

> * [x]  Consider adding a package-level man page; see https://contributions.bioconductor.org/docs.html?q=man%20pa#package-level-documentation.

Done.

> * [x]  Please take a look at the results of running `covr::report()` to identify areas of the package that are lacking unit test coverage.

Great package, thank you for pointing me there. I have re-written large sections of tests and increased testing coverage. I don't test `fetch_bp()` for reasons mentioned above, and the interactive app.

**Comment by PeteHaitch** [comment] 2023-09-18 01:11
Please remember when making changes to your repository to push to
git@git.bioconductor.org:packages/fenr to trigger a new build.
I'll then review your comments alongside the updated package.

**Comment by MarekGierlinski** [comment] 2023-09-18 07:54
Ah, there is a problem here. I don't have the SSH key for git.bioconductor.org, I followed the instructions and went to the [BiocCredentials application](https://git.bioconductor.org/BiocCredentials/). However, as I try to activate, it says:

> m.gierlinski@dundee.ac.uk is not associated with a maintainer of a Bioconductor package. 

I believe this is the same problem I reported at the beginning, with BiocCheck reporting that I'm not registered on the support site - see my post from the 4 August. `lshep` replied to it that they'd investigate this with the support site. But the problem still persists.

**Comment by lshep** [comment] 2023-09-18 11:23
The support site issue and the BiocCredentials are separate issues and not related.  Please also remember Bioconductor and Bioconductor resources, like R, are case sensitive too.  You must activate your account before you can modify.  Please try activating the account `M.Gierlinski@dundee.ac.uk` at  https://git.bioconductor.org/BiocCredentials/account_activation/

**Comment by MarekGierlinski** [comment] 2023-09-18 11:30
As I said above, this does not work. I type "M.Gierlinski@dundee.ac.uk" (with capital letters) and get the message:

m.gierlinski@dundee.ac.uk is not associated with a maintainer of a Bioconductor package.

**Comment by lshep** [comment] 2023-09-18 11:33
I will reset the BiocCredentials account, activate it and set a temporary password for you to your email.

**Comment by lshep** [comment] 2023-09-18 11:38
You should have an email from me.

**Comment by MarekGierlinski** [comment] 2023-09-18 11:46
Got it. When I tried to log in with the temp password, I got the message

> Your email and password didn't match. Have you activated your account? If yes, please check the spelling and try again.

I did check the spelling!

**Comment by MarekGierlinski** [comment] 2023-09-18 11:47
Just to be sure, is the the site I should be using?

https://git.bioconductor.org/BiocCredentials/login/

**Comment by lshep** [comment] 2023-09-18 11:48
Try on :  https://git.bioconductor.org/BiocCredentials/account_activation/

**Comment by MarekGierlinski** [comment] 2023-09-18 11:50
Nope, the same as before:

> m.gierlinski@dundee.ac.auk is not associated with a maintainer of a Bioconductor package.

I tried both "M.Gierlinski" and "m.gierlinski", the error message always uses lower case.

**Comment by lshep** [comment] 2023-09-18 11:58
I activated your account manually -- see if you can use the change password --  and to be clear the above has an extra 'a' in the extension:  `m.gierlinski@dundee.ac.uk`

**Comment by MarekGierlinski** [comment] 2023-09-18 12:08
Oh, sorry. My eyes must be failing me, there was an extra "a" indeed. But I used the correct email earlier, I promise!

Thank you for your help.

**Comment by lshep** [comment] 2023-09-18 12:38
We are still investigating the email validation on the support site -- so this error if it occurs can be ignored.

**Comment by MarekGierlinski** [comment] 2023-09-18 12:53
`R CMD CHECK` passed on MacOS, but failed with a timeout on Linux at 

```
biomaRt::useEnsembl(biomart = "ensembl", dataset = "scerevisiae_gene_ensembl")
```

I'm afraid this can happen from time to time when Biomart is busy. I'm not sure how to prevent similar failures in the future.

`BiocCheck` failed both times on the "Maintainer must register at the support site", which is the issue you trying to resolve. Otherwise, not errors, no warnings.

**Comment by PeteHaitch** [comment] 2023-09-28 03:16
Hi @MarekGierlinski,

Thank you for making the required changes and carefully considering the recommended changes.
There are just a couple of minor points to address before I mark the package as accepted:

- [ ] Please use `donttest{}` rather than `dontrun{}` in your `.Rd` files (as advised by `BiocCheck::BiocCheck()`). I guess you might also consider wrapping in a `donttest{}` the examples that rely on Biomart connectivity if that continues to be an intermittent problem, although @lshep may clarify if that's the correct/preferred way to deal with this issue.
- [ ] I didn't understand at first the point you were making in the 'Comparison to other functional enrichment packages' section of the vignette. From what you write, **topGO** takes 0.6x the time for setup (6 vs. 10 seconds) but 4x the time for testing (200 vs. 50 ms), and therefore **topGO** takes 0.62x the time overall compared to **fenr** (6.2 vs. 10.05 seconds). However, if you then wanted to test a new gene set (`gene_selection`/`expl_sel`) then you'd have to repeat the setup for **topGO** whereas for **fenr** you wouldn't because the setup only depends on the background (`all_genes`/`exmpl_all`). Is this correct?

As an aside, you might be interested in **gesel.js**, which is a JavaScript package for performing client-side gene set enrichment analysis, which I imagine could also be incorporated into a Shiny app:
- Software: https://github.com/LTLA/gesel.js
- Preprint/paper: https://github.com/openjournals/joss-reviews/issues/5777

**Comment by PeteHaitch** [comment] 2023-09-28 03:19
I'll be on leave (and offline) from today until October 9.
The deadline for new packages to be accepted is October 18 (see https://www.bioconductor.org/developers/release-schedule/).
I'm sure it won't take you long to address the comments in https://github.com/Bioconductor/Contributions/issues/3017#issuecomment-1738375910,  but I will not be able to formally accept the package until after returning from leave.

If while I'm away you do have any urgent concerns or questions, please post to this issue and tag @vjcitn or @lshep to bring it to their attention, but if it's not urgent then there's no need to tag them and I'll respond when I'm back.

**Comment by MarekGierlinski** [comment] 2023-10-09 06:41
Hi,

We have a problem. There is a bug in the new version of *vroom* 1.6.4 (see https://github.com/tidyverse/vroom/issues/519), which, unfortunately, causes *fenr* to fail to build. I can confirm I can build it on my Mac with *vroom* 1.6.3, but not with 1.6.4. We might have to wait until the bug is fixed. Alternatively, if this is not happening soon, I can replace all the *readr* calls (`read_tsv` etc., internally they use *vroom*) with base R, but *readr* is about twice as fast as base functions, so I'd be reluctant to do this.

Apart from that, I have done a few updates, see `NEWS.md`. There is one `donttest{}` left in the interactive example that calls a Shiny app (function `enrichment_interactive()`). Without `donttest{}` it causes `devtools::check()` to stall indefinitely while checking examples. I don't know if it is possible to run tests on interactive code.

**Comment by PeteHaitch** [comment] 2023-10-10 21:38
The timing of that bug is unfortunate, but I don't think it need hold up submission and ultimate acceptance of **fenr**.

An alternative interim workaround (while still using the latest version of **vroom**) is to add `readr::local_edition(1)` to the top of all **fenr** functions that call `readr::read_*()` functions, which which will then cause these to use the original, non-vroom versions of these functions ([see **vroom** release notes for version 2.0.0](https://cran.r-project.org/web/packages/readr/news/news.html)).
You can then remove `readr::local_edition(1)` once the bug is fixed in **vroom**.
I made such a change to my local checkout of the BioC git repo and it allowed **fenr** to build and check on my machine.

I'll continue my review using this locally-modified version and post feedback, shortly.

**Comment by PeteHaitch** [comment] 2023-10-10 22:12
I think you can remove the `donttest{}`/`dontrun{}` entirely from the Shiny example by changing it to the following:

```r
data(yeast_de)
term_data <- fetch_terms_for_example(yeast_de)
if (interactive()) {
  enrichment_interactive(yeast_de, term_data)
}
```

This way the testable bits of the example are still tested but the Shiny app isn't launched because `interactive()` returns `FALSE` when packages are checked from the command line.

Could you please reply to my [earlier comment/question](https://github.com/Bioconductor/Contributions/issues/3017#issuecomment-1738375910):

> I didn't understand at first the point you were making in the 'Comparison to other functional enrichment packages' section of the vignette. From what you write, topGO takes 0.6x the time for setup (6 vs. 10 seconds) but 4x the time for testing (200 vs. 50 ms), and therefore topGO takes 0.62x the time overall compared to fenr (6.2 vs. 10.05 seconds). However, if you then wanted to test a new gene set (gene_selection/expl_sel) then you'd have to repeat the setup for topGO whereas for fenr you wouldn't because the setup only depends on the background (all_genes/exmpl_all). Is this correct?

Final minor thing, `R/iterative_example` should be `R/interative_example`.

**Comment by MarekGierlinski** [comment] 2023-10-11 07:39
I have added `readr::local_edition(1)`, as suggested and now *fenr* builds with no issues. I have added `if(interactive())` to the interactive example and it works fine (it is such a simple solution!). I changed the name of the file.

To answer your question - yes, this is correct. In the followup to this question I have rewritten parts of the vignette and package description in `DESCRIPTION` file to make this point come through.

@lshep: Any results from investigation of the email validation issue on the support site?

**Comment by lshep** [comment] 2023-10-11 20:35
We have identified the issue and are in process of pushing up a fix; likely next week.  I can verify the email is valid and this ERROR can still be ignored for now and not prevent acceptance if everything else is ok.

**Comment by PeteHaitch** [comment] 2023-10-12 02:01
I'm happy to mark **fenr** as accepted.
Thank you for your engaging constructively in the review process, @MarekGierlinski, and for your contribution to Bioconductor!

**Comment by MarekGierlinski** [comment] 2023-10-12 06:46
Hi Peter, thank you very much for you time and effort.

**Comment by lshep** [comment] 2023-10-13 17:09
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MarekGierlinski.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("fenr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/fenr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-10-13 17:09 UTC
Labels: ERROR, 3a. accepted

**Comment by MarekGierlinski** [comment] 2023-11-13 08:56
> We have identified the issue and are in process of pushing up a fix; likely next week. I can verify the email is valid and this ERROR can still be ignored for now and not prevent acceptance if everything else is ok.

Hi @lshep the issue still persists.

**Comment by lshep** [comment] 2023-11-13 14:01
Yes we have a fix waiting we have been waiting to see if the base code where the issue occurs wants to make the change or if we should do it locally.  Sorry for the delay.
