### ISSUE TITLE
(inactive) MMAPPR2

### ISSUE THREAD

**Issue by kjohnsen** [Bioconductor/Contributions#902] opened 2018-10-04 23:15 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kjohnsen/MMAPPR2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kjohnsen** [comment] 2018-10-04 23:15
AdditionalPackage: https://github.com/kjohnsen/MMAPPR2data

**Comment by lshep** [comment] 2018-10-11 15:07
Thank you for your submission to Bioconductor. Please see the technical review
below. Please also ensure you have your [webhook enabled](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) for _both_ packages to
ensure that valid version bumps kick off new builds.  Please comment back here
with updates on changes and when you are ready for a re-review. 

**MMAPPR2data**

**description:**

- [ ] you shouldn't need to explicit depend on AnnotationHub or ExperimentHubData so
these can be removed. AnnotationHub gets installed as a dependency of
ExperimentHub. I don't believe you should be calling anything from
ExperimentHubData so this can also be removed
- [ ] We added a new biocViews term for ExperimentHub please add. 


**namespace:**
- [ ]If packages are listed in DESCRIPTION as depends, then they should be imported
in the namespace. So add the following:
```
import(ExperimentHub)
import(Rsamtools)
```

**man:**
- [ ] To get rid of the windows Rd warning use 
```
\code{\link[Rsamtools:BamFile-class]{BamFile}} 
```
Similar situation as
https://stat.ethz.ch/pipermail/bioc-devel/2018-October/014137.html

**report example error**
- [ ] You export zy13mutBam  and zy13wtBam which are the name of your functions
but in your examples you call zy13wt().  I think you mean zy13wtBam? 
- [ ] Please subscribe to the mailing list
`https://stat.ethz.ch/mailman/listinfo/bioc-devel` If you have done so already
there is normally a verification step so please check spam or junk folder in
case it was redirected there. 




**MMAPPR2**

**build report**
- [ ] Is this package not meant to be run on windows? 
- [ ] Now that the data package is available, please do a version bump to get a
R CMD check report. 
- [ ] You have included large data files in the software package - normally the
goal of an accompanied data package is so this data is not in the software
package keeping the software package tiny and lightweight.  Why  is the data not
in the MMAPPR2data package? 
- [ ] Your package needs a vignette with executable code chunks. The package
will not be accepted without this requirement.
- [ ] Please fix the coding practices NOTES and WARNINGS
- [ ] Fix Namespace and Description inconsistencies
- [ ] Fix man page error
- [ ] Fix runnable example error
- [ ] Please subscribe to the mailing list
`https://stat.ethz.ch/mailman/listinfo/bioc-devel` If you have done so already
there is normally a verification step so please check spam or junk folder in
case it was redirected there. 


**description**
- [ ] remove LazyData: true.  We rarely see this to be useful and actually found this to slow down the
installation of the package
 
**vignette**
- [ ] Your package needs a vignette with executable code chunks. The package
will not be accepted without this requirement. 

Once the above is corrected I will look more closely at man files and R
code. Thank you.I look forward to working with you to get your packages accepted
to Bioconductor.

Cheers!

**Comment by kjohnsen** [comment] 2018-10-11 22:43
Thanks Lori! I'll get to work on fixing these. As for the data--the data included is pre-computed `MmapprData` objects at various points in the pipeline--it seemed unwise to me to put these in the data package, since that would introduce a circular dependency. I need these large objects for runnable examples--they are already the minimum amount of data to show meaningful functionality. I _could_ strip them down to the point of having trivial examples though. What do you recommend?

**Comment by lshep** [comment] 2018-10-12 17:22
And I can only assume that means that generating the data interactively is too time consuming?

**Comment by lshep** [comment] 2018-10-12 17:33
Do you introduce a new class?  If not, I'm unsure why you would need a circular dependency? If your data is in standard formats which it looks like .rda and doesn't require a specialized class from your package to properly display or load you shouldn't need to depend, import, or suggest the software package. 
I can only assume as you say they are various points in the pipeline that running interactively is too time consuming?

**Comment by kjohnsen** [comment] 2018-10-15 23:35
Yes, I introduce a new class to store data as the pipeline progresses.

And running interactively is fairly time-consuming--it takes a couple of minutes to get through the whole thing with this trimmed demo data.

**Comment by kjohnsen** [comment] 2018-10-16 23:18
The package doesn't run on Windows because gmapR is a dependency (we use GmapGenome for variant calling with VariantTools). That's not the only kind of genome you can use with VariantTools, so we could fix that, but that would be a longer-term priority.

The pipeline would probably finish under 5 minutes, but there's a problem. One step of the pipeline (variant calling and effect prediction) has some heavy dependencies, so I thought it would be better not to run it at all in the vignette and examples. It would require access to reference genome files, constructing a GmapGenome, and installing VEP (which itself can introduce a nightmare of Perl dependencies). 

So assuming we don't want to run that part of the pipeline, I need some way to store the results of variant calling and effect prediction to pick up with the rest of the pipeline. I could cut the number of those objects from 5 down to just the one I need to skip that step--the package might make the size requirement then. 

I can see why it would be preferable to have that data in the MMAPPR2data package, but how could I store it there when it's an instance of a class defined in MMAPPR2?

That's right, my PI is listed as the maintainer--I will make sure he gets on the bioc-devel list.

**Comment by lshep** [comment] 2018-10-17 17:54
Yes - as long as the ability to run the examples in the man pages is there for users (so feasibly the code in the dontrun works -  I would let it slide provided all the steps and full pipeline is run in the vignette -  I would move forward with the proposal above.  
In the top most directory please create a file  `.BBSoptions`  -  in that file please include the line `UnsupportedPlatforms: win`  .  This will signal to both the SPB and when you get on the daily builder that it is not supported on this platform.

**Comment by kjohnsen** [comment] 2018-10-18 15:35
All right, I implemented the restructured data/vignette/examples and it should all be working. I'll be doing the minor fixes and adding the .BBSoptions file soon.

**Comment by kjohnsen** [comment] 2018-10-18 21:39
It looks like the data package hasn't been getting built, which is necessary for the vignette to build correctly. I added the webhook and it got built the first time, so I don't know why it hasn't been working for [recent version bumps](https://github.com/kjohnsen/MMAPPR2data/blob/master/DESCRIPTION)

**Comment by lshep** [comment] 2018-10-18 23:43
Can you please try doing the `AdditionalPackage: https://github.com/kjohnsen/MMAPPR2data`  again?  The issue is that this line is normally done after the first package is completed the checks and after the package is out of awaiting review so it never registered in the queue.

**Comment by kjohnsen** [comment] 2018-10-19 04:45
AdditionalPackage: https://github.com/kjohnsen/MMAPPR2data

**Comment by lshep** [comment] 2018-10-22 11:53
We do not have a Jonathan Hill or the listed email registered on the bioc-devel mailing list.  I just checked the membership listing.  Please have him register with the jhill@byu.edu again. Maybe he inadvertently unsubscribed.  

You can ignore the @ note then 

No you don't have to fix  the line spacing.  

The time constraint is close enough that I will be lenient on the 5 min warning. 

**Data Package**
Please fix the other ERROR and WARNING in the MMAPPR2data package build report as well.  Most notably about the import and NAMESPACE

**Main Package**
To get rid of the 80% warnings man documentation error and also for completion - please put all necessary code to run the example (in the dontrun if necessary) but right now for example in generateCandidates.Rd  I don't know what postPeakRefMD is in the example given.  Show the steps to make this object even if it isn't run -  and if there is a single line that could be run place that outside the don't run -  even it it is identifying the data file


Please start with these comment -  I will look over the package R code later today and comment with anything further.

**Comment by kjohnsen** [comment] 2018-10-22 19:32
I know you advised not importing AnnotationHub in the data package, but my functions rely on the `hubCache()` function, so I put it back in the imports.

**Comment by kjohnsen** [comment] 2018-10-22 20:30
I made all the examples runnable and did some style fixes. I didn't fix shorten all of the lines over 80 characters, mainly for verbose, uninteresting lines like logging and setting generics. Let me know if you want me to clean those up more.

There might be a problem with GitHub at the moment--I'm not getting builds triggered either on Travis or through here.

**Comment by lshep** [comment] 2018-10-23 15:36
Data package is good to go now. 
Please see the following comments regarding the software package:

**Running the Vignette:**

```
{r hidden-hacks, echo=FALSE}
# hide from users, allows VEPFlags to be constructed without complaining
MMAPPR2:::.insertFakeVEPintoPath()
gmapR::GmapGenomeDirectory(create=TRUE)
BiocParallel::register(BiocParallel::SerialParam())
```
- [ ] Generally we don't like hidden hacks - I think if the above specification that ensembl vep has to be installed (and include that addition of vep in the path) then you shouldn't need a hidden hack for insertFakeVEPintoPATH - generally we don't like random hacks on users systems especially if its changing a system environment variable 
- [ ]  why is gmapR::GmapGenomeDirectory necessary? If ensemble vep is set up correctly is this also already available and not needed? 
- [ ] exposing that you can run the pipe in parallel and for the vignette and testing you are using Serial is not necessarily bad to expose to the user. Then point to your customize BiocParallel backend section you included below if users wanted to use a different back-end

```
{r candidates-step, eval=FALSE}
postCandidatesMD <- generateCandidates(postPeakRefMD)
```
```
{r prep-for-output, echo=FALSE}
postCandidatesMD <- postPeakRefMD
## I don't know why data isn't being exported right and I have to do this...
data("zy13candidates")
postCandidatesMD@candidates <- zy13candidates # tack on from MMAPPR2data
dir.create(outputFolder(param(postCandidatesMD)), showWarnings = FALSE)
```
```{r output-step}
outputMmapprData(postCandidatesMD)
```

- [ ] generateCandidates throws and ERROR and isn't evaluated - why? If this isn't working that isn't acceptable. And this is why we require each function and step to be evaluated somewhere to ensure that it is running correctly. `## I don't know why data isn't being exported right and I have to do this ` Its better to fix it. 
- [ ] Should candidates not be a list and be a GRangesList object instead. 
- [ ] Output of vignette should be written to a temp directory. dir.create(outputFolder(param(postCandidatesMD)), showWarnings = FALSE)
- [ ] Also in your echo=FALSE hidden chunk above - you  manually create a directory - Shouldn't this be taken care of automatically when calling the `outputMmapprData` function. rather than relying on the user to create it 
```
> outputMmapprData(postCandidatesMD)
Error in pdf(file.path(mmapprData@param@outputFolder, "genome_plots.pdf"),  : 
  cannot open file 'DEFAULT/genome_plots.pdf'
```


**MMAPPR2 R code**
all_classes.R
- [ ] candidates sounds like it should be a GRangeList instead of a list of GRange objects. 


main.R
- [ ] .insertFakeVEPintoPath -  is this necessary - The builders will have VEP installed and I think its reasonable to assume if you say at the top that the vignette requires ensembl vep to be installed and paths to be set that this function should not be necessary.

- [ ] this seems like it could be reduced to an apply and/or parallelized bpiterate.  If you already implemented BiocParallel it would probably be a good candidate to also parallelize.
```
.indexBamFileList <- function(bfl) {
    for (i in seq_along(bfl)) {
        bamFile <- bfl[[i]]
        if (is.na(Rsamtools::index(bamFile)))
            Rsamtools::indexBam(bamFile)
    }
}
```


peaks.R  and other R files 
- [ ] use get/set methods over @ if they are implemented 
ex. `distance(mmapprData)[[i]]` rather than `mmapprData@distance[[i]]`  Use getters and setters; thats why they are defined!


As before please comment back here with updates and comments and when ready kick off a new build of the package for rereview

**Comment by kjohnsen** [comment] 2018-10-24 00:54
Ok, thank you for the comments!

I can work on the smaller stuff, but most of what you mentioned comes down to this: should `generateCandidates()` be runnable in the vignette? I assure you it works, but like I mentioned before, I thought its dependencies were just too much to want to try and install them in the vignette. Building a `GmapGenome` takes a long time, and would require access to a large fasta file. Installing VEP is much more complicated still, introducing a world of perl dependencies. These are both necessary for `generateCandidates()`, which calls variants then runs VEP on them, so what do you suggest?

(`.insertFakeVEPintoPath` is only necessary for examples when VEP isn't installed; without it, a VEPFlags object can't be created. The user would not use this.)

**Comment by lshep** [comment] 2018-10-24 11:04
`(.insertFakeVEPintoPath is only necessary for examples when VEP isn't installed; without it, a VEPFlags object can't be created. The user would not use this.) - `  If you are making VEP a requirement of your package which you do, then it is expected that the user will have this installed to run the vignette. The builders have this installed already.  so remove the helper file that would place misc. dummy paths on a users system environment.  writing something to a users directory other than a temporary directory or changing environment variables is really never a good idea and we would always discourage this.  

There needs to be a way to run and test your functions in a timely and efficient manner.  Even if this means using a more paired down and dummy example set.   You `ensuring` me that it works isn't very assuring when I try to run the code provided and get an error.  At the very least the code that is shown should be able to be run and not ERROR (even if it is currently eval=FALSE) so that I could replicated it if I so choose to take the time.  However,  any function that is exported should have some way to test or run the function to ensure that it is running correctly.  Nor was it very confident to have a comment like `## I don't know why data isn't being exported right and I have to do this...`

@mtmorgan  would you agree/disagree or any further comments?

**Comment by kjohnsen** [comment] 2018-10-24 12:06
Okay, if I can count on VEP being installed, I think all we'll need to run `generateCandidates()` in the vignette is the reference genome. My first idea to implement this would be to add a fasta file with just the chromosome we're interested in (73 MB) to the data package. What do you think?

Do you mean the vignette should be able to build on the user's machine? If we assume VEP is already installed, should the code blocks instructing the user on how to install it remain as `eval=FALSE`?

I created the vignette assuming that its primary purpose was to teach the user how to use the package; I tried to arrange it so that a user could follow it from installation of dependencies through running the program seamlessly, despite the ugly stuff going on in the `echo=FALSE` blocks (which could definitely be refactored, true). That is, my idea was to use these `echo=FALSE` blocks to maintain the illusion of the dependencies (VEP and genome) being set up already, which should be true if the user follows the vignette. The built vignette does not display these blocks.

**Comment by mtmorgan** [comment] 2018-10-24 12:29
Code blocks with installation instructions may legitimately have an `eval = FALSE` flag.

Definitely `.insertFakeVEPintoPath()` should not be used (even if it were, one would rather `dir <- tempfile(); dir.create(dir)` instead of unlinking a directory...). because as Lori mentions the user (and build system) will have VEP installed...

Is it really the case that one needs a full chromosome to run the vignette / examples? I realize there's a tension between demonstrating the software and performing an analysis, but a carefully chosen example may be sufficient to illustrate functionality with very modest resources.

Certainly I can believe that `generateCandidates()` works now, but that is no guarantee that it will be robust to changes in R or dependent packages in the future. Any test at all would be better than none, and again this test needs to be balanced against the need to build and test your package in a timely manner.

**Comment by kjohnsen** [comment] 2018-10-24 12:52
The sample data covers most of the chromosome, but not all, so a reference genome could be cut down slightly. In preparing the data, I could only narrow the range so much before functionality started suffering.

The issue basically is this--the reads and genome need to cover a wide enough range to detect linkage between two pools of a genetic screen. If we're using real data, I might be able to find another case where we could cut it down to half a chromosome, but not much more.

The only other way I see would be to simulate the aligned sequencing data. I haven't done that before, so I don't know how feasible that is or how realistic the results could be.

**Comment by lshep** [comment] 2018-11-13 15:58
Hello @kjohnsen ,  I wanted to check in if there has been any progress?

**Comment by kjohnsen** [comment] 2018-11-13 17:47
No, not too much recently--since missing the deadline for the October release I have had other priorities. I should be back to focusing on MMAPPR in a couple of weeks.

**Comment by lshep** [comment] 2018-11-20 13:52
Please also note that the data in the hubs has been updated to work with the current 3.9  biocversion -  please update your metadata in the data package to reflect biocversion 3.9 and use the devel version of bioconductor to have access to these values in the hub.

**Comment by kjohnsen** [comment] 2019-01-16 01:13
Hi @lshep, I'm getting back to work on this. I'm looking at how to test `generateCandidates()`, and since the check is already taking over 5 minutes without that part, I figure I'm left with no choice but to come up with a tiny toy dataset and reference genome. Let me know if I'm wrong.

**Comment by lshep** [comment] 2019-01-16 11:46
That seems reasonable.  Tiny toy sets often display the functionality of the package well enough and you can always reference the fuller set if user want a more thorough experience.

**Comment by kjohnsen** [comment] 2019-01-16 23:41
Ok. I have a couple ideas to handle the reference genome. Maybe you can spare me some of the trial and error if you know one of these is preferable, or if there's a better way.
1. Include the raw fasta file in the data package and build a GmapGenome
2. Get Ensembl's most recent version of the zebrafish genome (which I need for this project) on Bioconductor as a BSgenome, to then use a small piece of it in examples [like gmapR does with `TP53genome()`](https://github.com/lawremi/gmapR/blob/99ba020fe5f5567409efff6e4373a14ff88e4022/R/TP53Genome.R)

**Comment by lshep** [comment] 2019-01-17 12:03
We generally prefer using existing data so 2 would be preferred.

**Comment by lshep** [comment] 2019-02-01 17:43
Can we expect some updates soon?

**Comment by lshep** [comment] 2019-02-13 18:00
Please continue to fix the ERROR/Warnings/NOTES in the build report and since I know you have been actively updating - please comment back here when you are ready for a re-review of the packages

**Comment by kjohnsen** [comment] 2019-02-13 19:19
Will do. The synthetic data is almost done.

**Comment by kjohnsen** [comment] 2019-02-19 23:45
@lshep I've run into problems setting up my synthetic data for use with the vignette, that is, making a small reference genome with a single gene. I figure the best way to solve the problem is to create a BSgenome package for the GRCz11 zebrafish genome. I don't see in the vignette much in the way of submitting a BSgenome package to Bioconductor after creating it--is that something I need to talk with Herve Pages about?

**Comment by lshep** [comment] 2019-02-20 17:42
Is there a reason why one of the current BSGenome's could not be used?  

http://bioconductor.org/packages/release/data/annotation/html/BSgenome.Drerio.UCSC.danRer10.html

**Comment by kjohnsen** [comment] 2019-02-20 19:46
The biggest reason is that names for the UCSC version don't match with Ensembl, which they need to for VEP. Also, we would need to figure out how to use a previous version of Ensembl/VEP (with GRCz10) on the Bioconductor pipeline for it to work right.

**Comment by lshep** [comment] 2019-02-21 11:49
I would check in with Herve Pages @hpages  on when/if a new version of the package will be created before submitting a new one.  
If he doesn't plan on making it and you would like to submit one it would follow the guidelines of ExperimentHub like packages but for AnnotationHub.

**Comment by kjohnsen** [comment] 2019-02-27 23:33
I thought of an easier way: instead of relying on the standard zebrafish VEP cache, I can just run VEP using the small fasta file and a GTF file for just this gene. It seems like all I'll have to do is configure the `VEPFlags` object. Let me know if this wouldn't work--I'll try it out.

**Comment by lshep** [comment] 2019-02-28 12:56
I'm not that familiar with using VEP but that sounds reasonable if you can get it to work.

**Comment by lshep** [comment] 2019-03-28 11:48
I just wanted to check it on progess as the deadline for accepting packages for this release has been announced as Wed April 24.

**Comment by kjohnsen** [comment] 2019-04-01 15:55
I think I'll be able to make it. The toy dataset is now working on the vignette, so soon I'll be able to merge the branch and keep polishing things up.

**Comment by lshep** [comment] 2019-04-08 13:07
Keep in mind the last day to be accepted is April 24th.  Once you push changes I will still have to review the packages and accept by this date to be included in the release

**Comment by kjohnsen** [comment] 2019-04-08 21:00
Ok, thanks. Hopefully I can get it done in time.

**Comment by kjohnsen** [comment] 2019-04-08 23:46
I'm not quite sure why the build failed...I looked through [R source code ](https://github.com/wch/r-source/blob/trunk/src/main/eval.c#L2070) to see it's a result of a zero-length conditional statement, but I don't know where that code would be called from. If you happen to have seen this error before I'd appreciate the help.

**Comment by lshep** [comment] 2019-04-09 15:17
`R CMD Stangle MMAPPR2.Rmd` will give you an MMAPPR2.R command with all the executed R in your vignette to run.  Doing this and running the code in the vignette 
```
> md <- new('MmapprData', param=param) ## calculateDistance() takes a MmapprData object
> postCalcDistMD <- calculateDistance(md)
  |======================================================================| 100%
Error in if (cuid %in% names(env)) rm(list = cuid, envir = env) : 
  argument is of length zero
> traceback()
6: .ClusterManager$drop(x$.uid)
5: .bpstop_impl(x)
4: BiocParallel::bpstop(bpParam)
3: BiocParallel::bpstop(bpParam)
2: .runFunctionInParallel(chrList, .calcDistForChr, param = mmapprData@param)
1: calculateDistance(md)
```

**Comment by lshep** [comment] 2019-04-09 17:18
Am i also correct that you still have an ExperimentData package but that it no longer uses the ExperimentHub?  May I remove the resources from the ExperimentHub?

**Comment by kjohnsen** [comment] 2019-04-10 03:58
Ok, thanks. I'll look into that. And yes, go ahead and remove the ExperimentHub resources.

**Comment by kjohnsen** [comment] 2019-04-15 22:56
The vignette was running fine until I updated to the latest version of BiocParallel (from 1.16.6 to 1.17.18). I'll try and figure out what's happening, but could I get some help from the BiocParallel developers?

**Comment by lshep** [comment] 2019-04-16 11:27
Sure,  I recommend reaching out either by opening an issue on the BiocParallel github or on the bioc-devel@r-project.org

**Comment by lshep** [comment] 2019-04-23 14:25
The deadline for acceptance in the 3.9 release is tomorrow;  packages accepted after this date will remain in bioc devel and be released under 3.10 in the fall.

**Comment by kjohnsen** [comment] 2019-04-23 22:30
Yeah, we'll have to do the next release. Sorry I've been so slow; I've had very limited time to work on this.

**Comment by kjohnsen** [comment] 2019-04-30 23:40
It looks like there's a problem on the server: `There is no package called rtracklayer`

**Comment by kjohnsen** [comment] 2019-05-07 13:56
All right @lshep, it's passing! I updated the R dependency, which should fix the last warning. As for the notes, there's line length--all of those are boilerplate lines like `setGeneric` or strings in logging messages and such which would be awkward to break up. Indentation: I only depart from the 4-space rule to match with parentheses when splitting a line. There are 3 long functions, the most egregious of which I'm working on fixing. Let me know what you want me to change.

**Comment by lshep** [comment] 2019-05-14 14:12
Do you still have a data package and software package?   The software package is still referencing the data package in the DESCRIPTION and the data package is still referencing the hubs in the DESCRIPTION... if any of this needs to be updated please do so.

**Comment by kjohnsen** [comment] 2019-05-14 21:08
All right. I removed the ExperimentHub BiocView in [MMAPPR2data](https://github.com/kjohnsen/MMAPPR2data) .

**Comment by lshep** [comment] 2019-05-15 13:38
A few minor things but the packages look in good shape.  Nice documentation

# Data Package

See notes and warnings in build report
http://bioconductor.org/spb_reports/MMAPPR2data_buildreport_20190514171241.html


# Software Package

**Build Report**

- [ ] This seems like a legit and real warning that should be addressed
```
* Checking coding practice...
Warning in res[i] <- withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),  :
  number of items to replace is not a multiple of replacement length
Warning in res[i] <- withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),  :
  number of items to replace is not a multiple of replacement length

```

**Vignette**
- [ ] Files/output of vignette should be written to a temporary directory and
not to the home/working directory.  Please use `tempdir()` The same should be
true for an examples in man files and tests.

**Comment by lshep** [comment] 2019-05-28 16:06
I wanted to follow up on the changes suggested to the software package as well?

**Comment by kjohnsen** [comment] 2019-05-29 00:55
I’ll have the tempdir() fix done soon, and I’ll take a look at the build warning, though it looks like it’s in the check code, not my package. Thanks again for being so patient—I’ve been working on this on top of a full-time job, so progress has been slow

**Comment by kjohnsen** [comment] 2019-05-30 00:25
Looks like someone else ran into this problem last year: https://github.com/Bioconductor/Contributions/issues/749#issuecomment-390259592

**Comment by kjohnsen** [comment] 2019-06-04 00:23
Hi Lori, it looks like the build is failing because a Perl module is missing the VEP needs. Is there a way we could get that installed?

**Comment by lshep** [comment] 2019-06-04 18:24
I'll look into it, Thanks for pointing it out.

**Comment by lshep** [comment] 2019-06-07 14:41
The ensembl-vep error has been fixed.  Please now correct the ERROR in the package code.

**Comment by kjohnsen** [comment] 2019-06-12 01:30
No errors! Are we ready? What else can I do?

**Comment by lshep** [comment] 2019-06-12 11:21
For what its worth if you have specified the NAMESPACE/DESCRIPTION properly you shouldn't explicitly need to put the package name in front of the function call ie.  `IRanges::IRanges`  and `Biobase::sampleNames`  etc...  This really only needs to be done if there is a namespace conflict (where two packages have functions of the same name).   But there is nothing really wrong with being explicit either; just pointing it out.  
Everything else looks okay... Cheers

**Comment by lshep** [comment] 2019-06-12 11:22
@mtmorgan   Please note there is a data package and a software package for addition

**Comment by kjohnsen** [comment] 2019-06-13 00:44
Ok, I did the package::function thing after someone suggested it somewhere over doing imports. Might have been in Hadley Wickham's ebook.

Thanks for everything! Thanks for being so patient--it's taken a while. And thanks for insisting on testability--putting together that synthetic toy data has really made the package a lot more maintainable.

**Comment by lshep** [comment] 2019-06-13 02:23
I glad you found it useful.  Many are initially discouraged and find the testing/active running tedious but many also discover that it does help improve the code and makes it easier to maintain and spot bugs.  Some even start developing testing before writing code to ensure robustness. 
We appreciate you sticking through the process. 
Welcome to Bioconductor!!

**Comment by mtmorgan** [comment] 2019-06-13 20:14
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kjohnsen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MMAPPR2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MMAPPR2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2019-06-13 20:14
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kjohnsen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MMAPPR2data")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MMAPPR2data

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-06-13 20:14 UTC
Labels: 3a. accepted, OK
