### ISSUE TITLE
rat2302frmavecs

### ISSUE THREAD

**Issue by vbelcastPM** [Bioconductor/Contributions#750] opened 2018-05-03 09:27 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pmpsa-hpc/rat2302frmavecs

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment] 2018-05-18 16:58
Hi Vincenzo, @vbelcastPM 

Thank you for your submission. Your package looks ready to go. 

## vignettes

I would suggest that you provide runnable examples using the dataset within the
package and importing/depending the `frmaTools` package as well.

This would enhance the vignette and make it easier for users that want to
make use of the dataset.

Thank you.

Regards,
Marcel

**Comment by LiNk-NY** [comment] 2018-05-24 18:26
Hi Vincenzo, @vbelcastPM 
Any updates, comments? 

Regards,
Marcel

**Comment by vbelcastPM** [comment] 2018-05-25 07:07
Hi Marcel,

Thank you for the good news and your reminder.

I’ll be working on the runnable example to add to the Vignettes.

Best,
VIncenzo

**Comment by LiNk-NY** [comment] 2018-05-29 16:24
Hi Vincenzo, @vbelcastPM 
Please provide some updates on the status of this.
Thanks,
Marcel

**Comment by vbelcastPM** [comment] 2018-05-31 09:54
Dear Marcel,

The question I have is whether to add mock CEL files to the package.
Anyway, I did add the following to vignette that illustrate the basic usage of the data package.

Best,
Vincenzo

# library('affy')
# library('rat2302frmavecs')
# library('frma')
# affybatch = ReadAffy(filenames = <CEL files>, cdfname = 'rat2302rnentrezg')
# eset = frma(affybatch)

**Comment by LiNk-NY** [comment] 2018-05-31 17:20
Hi Vincenzo, @vbelcastPM 

Please use appropriate Rmarkdown syntax in the vignette for the code chunks.
You can add a small CEL file to the package in `inst/extdata` for example purposes. 

Best regards,
Marcel

**Comment by LiNk-NY** [comment] 2018-06-05 15:52
Hi Vincenzo, @vbelcastPM 
Please resolve the issues in the vignette. 
Thank you. 
-Marcel

**Comment by LiNk-NY** [comment] 2018-06-13 16:29
Hi Vincenzo, @vbelcastPM 
Can you provide an update on the status of your package? 
Otherwise, I will have to close the issue next week.
Thank you.

**Comment by LiNk-NY** [comment] 2018-06-22 15:12
Hi Vincenzo,
I've closed the issue due to inactivity. 
You may re-open the issue when you are ready to make updates to the vignette.
Best regards,
Marcel

**Comment by vbelcastPM** [comment] 2018-06-29 12:13
Dear Marcel,

Sorry for my very late reply. I took over this package and realized that another one is required to be submitted along.

Sorry to make you wasting time.

Best,
Vincenzo

**Comment by LiNk-NY** [comment] 2018-07-05 18:20
Hi Vincenzo, 

No problem! We're happy to help you improve your package. 
We will be waiting for your future submission. Thank you!

Regards,
Marcel

**Comment by vbelcastPM** [comment] 2019-01-25 09:50
Dear Marcel,

I finally found the time to work on the pending package. I have now updated the git repository with the new code.
https://github.com/pmpsa-hpc/rat2302frmavecs

Once the issue is re-opened I’ll bump the version.

Best,
Vincenzo

**Comment by LiNk-NY** [comment] 2019-01-25 17:37
Hi Vincenzo, @vbelcastPM 

AFAIK, you can bump the version even if the issue is closed and
you should get a build of the package. 

Please bump the version now. Thanks!

Best, 
Marcel

**Comment by vbelcastPM** [comment] 2019-01-28 08:22
Hi Marcel,

Thank you for the info.
I just bumped the version but no action seem to be triggered. Did I miss something?

Best,
Vincenzo

**Comment by LiNk-NY** [comment] 2019-01-28 16:38
Hi Vincenzo, @vbelcastPM 

Please check that your webhooks are set up properly. 
Also, the SPB has been under maintenance recently. 

Lori, @lshep, any hints as to why the package is not building? Thanks!

-MR

**Comment by lshep** [comment] 2019-01-28 17:16
A few things: 
1.  The issue has to be open and with a label of review in progress in order to trigger a build   
2. You can't change the repo location without telling us -  The repository location in the  initial commit seems different from the location you are trying now -  Which location is the correct location?  If the location has changed,  it needs to be changed manually by us in our database and in the repository link at the top of the page in order for the issue to build correctly.

**Comment by LiNk-NY** [comment] 2019-01-28 18:41
Thanks for looking into it Lori. 

Vincenzo, @vbelcastPM 
It looks like the repository has changed ownership and is now under the @pmpsa-hpc
account.
Please update the link at the top of the page and confirm that this is the correct location:
`pmpsa-hpc/rat2302frmavecs` 

Best regards,
Marcel

**Comment by lshep** [comment] 2019-01-29 11:58
I have updated the issue in our database.  You should be able to do a version bump and kick off a new build now.   Please let me know if  you do another version bump and it does not appear to be building .

**Comment by vbelcastPM** [comment] 2019-02-04 08:33
Hello Marcel,

Was wondering if you has time to check the email below.

Best,
Vincenzo

From: Belcastro, Vincenzo (contracted)
Sent: 29 January 2019 13:49
To: 'Bioconductor/Contributions' <reply@reply.github.com>
Subject: RE: [Bioconductor/Contributions] rat2302frmavecs (#750)

Hi Marcel,

The push correctly trigger the build.
I see errors that may related to the build and check system itself. Could you have a look?

Thank you,
Vincenzo

**Comment by LiNk-NY** [comment] 2019-02-04 19:22
Thanks Lori for kicking off another build. 

Vincenzo, @vbelcastPM 
It looks like you have a warning about imports:

```
* Checking DESCRIPTION/NAMESPACE consistency...
    * WARNING: Import affy, frma in NAMESPACE as well as DESCRIPTION.
    This is not a software package, skipping vignette checks...
```
* Provide Import directives in the `NAMESPACE` file as well.

**Comment by vbelcastPM** [comment] 2019-02-05 09:36
Done. Now I get an ERROR on the Linux check. I’m not sure is related to the code itself.

**Comment by lshep** [comment] 2019-02-05 12:04
This will happen occasionally - there is an issue with one of the Bioconductor mirrors we are trying to get resolved.  You can ignore this ERROR for now.

**Comment by LiNk-NY** [comment] 2019-02-05 20:39
Hi Vincenzo, @vbelcastPM 

Please fix the typos in the vignette (line no. 68).
It looks ready to go. 

Thanks, 
Marcel

**Comment by vbelcastPM** [comment] 2019-02-06 10:19
Hi Marcel,

Typos fixed. You want me to bump the version?

Best,
Vincenzo

**Comment by LiNk-NY** [comment] 2019-02-06 16:23
Yes, thanks!
@vbelcastPM

**Comment by LiNk-NY** [comment] 2019-02-07 16:08
Hi Vincenzo, @vbelcastPM 
Thank you for your submission! 

Best regards,
Marcel

**Comment by vbelcastPM** [comment] 2019-02-07 16:14
Thank you for your help Marcel.

Best,
Vincenzo

**Comment by dvantwisk** [comment] 2019-02-12 16:05
Your package has been added to bioc 3.9 devel. It should propagate within a day or so.

**Closed** 2019-02-14 19:25 UTC
Labels: 3a. accepted, OK

**Comment by vbelcastPM** [comment] 2019-02-15 07:54
Thank you very much for the information
