### ISSUE TITLE
csdR

### ISSUE THREAD

**Issue by yaccos** [Bioconductor/Contributions#2141] opened 2021-06-08 15:39 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/AlmaasLab/csdR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by Kayla-Morrell** [comment] 2021-06-22 16:55
@yaccos - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: What is the purpose of the 'docs/' directory and 'scratch.r'
  file. These aren't usually things we allow in our packages.

## DESCRIPTION

- [ ] REQUIRED: Since you are using a standard license, it is not necessary to
  include '+ file LICENSE' in the 'License:' field. You also don't need to
include the LICENSE file in your package.

## Data

- [ ] REQUIRED: There should be an 'inst/extdata' directory that contains the
  two txt files mentioned in DATASET.R file since these are the raw data files
to make the 'data/' files.

- [ ] REQUIRED: The 'data-raw' directory should be moved/renamed an
  'inst/script/' directory since this documents the data in some way.

- [ ] REQUIRED: There also needs to be documentation in the 'inst/script/'
  directory that documents the two txt files in the 'inst/extdata' directory.
The script could very but should clearly document how the data was genereated.
It should include source urls and any important information regarding filtering
or processing. It can be executable code, sudo code, or a text description. A
user should be able to download and roughly reproduce the file or object that is
present as data.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to download / load the package from Bioconductor. The code
should look like the following and should include `eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("csdR")
```

- [ ] SUGGESTION: I would move the setup section of the code to after the
  installation or have it be part of the same section.

Best,
Kayla

**Comment by yaccos** [comment] 2021-06-25 08:59
@Kayla-Morrell, Thank you for your feedback. I have done the following revisions to the package:

> REQUIRED: What is the purpose of the 'docs/' directory and 'scratch.r'
file. These aren't usually things we allow in our packages.

The purpose of the `docs/` directory was to contain the following website (https://almaaslab.github.io/csdR/). I have now moved it to another branch of the project as it is irrelevant for Bioconductor. The `scratch.R` file served a purpose during development for prototyping, but is no longer needed and is therefore deleted.

> REQUIRED: Since you are using a standard license, it is not necessary to
include '+ file LICENSE' in the 'License:' field. You also don't need to
include the LICENSE file in your package.

I have removed the part '+ file LICENSE' in the 'License' field and removed the LICENSE file. Even though you did not ask for it, I added my ORCID as well.

> REQUIRED: There should be an 'inst/extdata' directory that contains the
two txt files mentioned in DATASET.R file since these are the raw data files
to make the 'data/' files.

The two txt files are 154 MB and 181 MB in size. Do you really want me to include them regardless of their size? What DATASET.R essentially does is to reduce the size the data down to a managable size for a package by randomly selecting a subset of 1000 genes.

> REQUIRED: The 'data-raw' directory should be moved/renamed an
'inst/script/' directory since this documents the data in some way.

Deleted the 'data-raw' directory and moved the contents to 'inst/script.

> REQUIRED: There also needs to be documentation in the 'inst/script/'
directory that documents the two txt files in the 'inst/extdata' directory.
The script could very but should clearly document how the data was genereated.
It should include source urls and any important information regarding filtering
or processing. It can be executable code, sudo code, or a text description. A
user should be able to download and roughly reproduce the file or object that is
present as data.

Added `inst/script/download_preprocess.md` with a brief textual description of the procedure of obtaining and preprocessing the data.

>  REQUIRED: There should be an 'Installation' section that demonstrates to
the user how to download / load the package from Bioconductor. The code
should look like the following and should include eval = FALSE.

Added an 'Installation' section to the vignette.

> SUGGESTION: I would move the setup section of the code to after the
installation or have it be part of the same section.

Moved the setup code at the end of the 'Installation' section.

With best regards,
Jakob

**Comment by yaccos** [comment] 2021-06-25 09:40
Dear @bioc-issue-bot:

The fact that the build fails on riesling1 (and no other of the machines) has nothing to do with the package. It seems like riesling1 cannot access the R makevars 
> make: D:/biocbuild/bbs-3.14-bioc/R/etc/x64/Makeconf: Permission denied

and hence fails to compile the package

> g++    -c -o RcppExports.o RcppExports.cpp
RcppExports.cpp:4:10: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
          ^~~~~~~~
compilation terminated.

**Comment by Kayla-Morrell** [comment] 2021-06-29 12:18
@yaccos - We recently added the Windows builder to the build report, so there may have been some initial issues with it. I will review the changes based on the other two builders and hopefully the issues on Windows will resolve themselves. If not, we can investigate further on our end. I should have a re-review of the package posted within the next couple of days.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-07-09 17:13
@yaccos - I've reviewed the changes and everything looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by vjcitn** [comment] 2021-07-21 03:22
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/yaccos.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("csdR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/csdR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-07-21 03:22 UTC
Labels: 3a. accepted, OK
