### ISSUE TITLE
tradeSeq

### ISSUE THREAD

**Issue by koenvandenberge** [Bioconductor/Contributions#1157] opened 2019-06-22 09:35 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/statOmics/tradeSeq

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment] 2019-08-05 14:14
Hello @koenvandenberge - Just checking in to see if you've made any further progress since the last build 20 days ago?

**Comment by koenvandenberge** [comment] 2019-08-05 14:45
Hi @Kayla-Morrell thank you for looking into our submission.

No, we have not made any progress since the last build 20 days ago.

**Comment by Kayla-Morrell** [comment] 2019-08-05 17:26
When submitting a package to _Bioconductor_ we like to have the review process be as active as possible. We generally like to see activity within a 2 week window. If there is no progress on the package development within the next 2 weeks then we will close the issue for inactivity.

**Comment by koenvandenberge** [comment] 2019-08-05 18:02
I was on holidays until today, but I assure you that the package is still under active development.

**Comment by koenvandenberge** [comment] 2019-09-04 18:05
Hi @Kayla-Morrell 

We have just finished a major overhaul of the package.
It would be great to get your feedback.
Our only remaining ERROR label relates to the size of the tarball of the package.

Thank you in advance,
Best,
Koen

**Comment by Kayla-Morrell** [comment] 2019-09-05 17:20
Hello @koenvandenberge,

You must address WARNINGS as well. One suggestion I can make for the size of the tarball has to do with the vignette directory. This directory should only include the vignette file, the bib file, and any necessary static images. The html file is taking up 8.26MB worth of space in the repository, please remove this file as it is not needed.

Best,
Kayla

**Comment by koenvandenberge** [comment] 2019-10-02 13:41
Dear @Kayla-Morrell 

We have now fixed all errors and warnings, except for one warning, which is related to our usage of `set.seed` in the code. We require this for reproducibility purposes, since we perform a multinomial sampling to assign cells to lineages in a trajectory. Note, that the seed can be passed as an argument to the `fitGAM` function, hence it is not hard coded in the package.

It would be great to get feedback concerning the submission of tradeSeq to Bioconductor.

Best,
Koen

**Comment by Kayla-Morrell** [comment] 2019-10-11 18:20
@koenvandenberge - Please let me know when you have finished making changes to the package so I can start the initial review. 

Thanks,
Kayla

**Comment by koenvandenberge** [comment] 2019-10-14 08:00
@Kayla-Morrell We will limit our commits this week to allow for time to review the package. cc @HectorRDB

**Comment by Kayla-Morrell** [comment] 2019-10-15 17:32
Hello @koenvandenberge,

Thank you for submitting to _Bioconductor_. Please see the review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review. Please keep in mind the deadline for new packages to be accepted for the 3.10 release is October 23rd.

## General package development

- [ ] REQUIRED: The LICENSE.md file is not needed. Since the MIT licese is 
distributed by R, the only file that is needed is the LICENSE file.

- [ ] REQUIRED: What is the purpose of the '_pkgdown.yml' file in the top 
directory?

- [ ] REQUIRED: What is the purpose of the 'docs/' directory?

## DESCRIPTION

- [ ] REQUIRED: Ellaborate a bit more in the 'Description:' of the package, like 
what types of questions of interest?

- [ ] REQUIRED: 'LazyData:' should be set to false. This field being set to true 
can slow down the loading of packages with data.

- [ ] REQUIRED: The package 'methods' is used but not declared.

## NAMESPACE

- [ ] REQUIRED: You have both `import()` as well as `importFrom()` for the 
package slingshot. We would prefer `importFrom()` over importing the whole 
package but please pick one or the other, not both.

## Data

- [ ] REQUIRED: Is the sds data used somewhere? If so there needs to be a man 
page that documents the data.

## Vignettes

- [ ] REQUIRED: There should be an 'Introduction' section that explains a bit 
about the package. I see you point people to the pre-print, but you should still 
provide a little detail here. Maybe direct users to the paper for additional 
details.

- [ ] REQUIRED: Add an 'Installation' section that should show the users how to 
download and load the package from _Bioconductor_. The code should look 
something like this and should include `eval = FALSE`:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("tradeSeq")
```

- [ ] REQUIRED: Line 22-32, it is not necessary to load all of these packages, 
especially those that are listed as imports in the DESCRIPTION file. Only load 
in tradeSeq here. Then when you need certain functions in the vignette load the 
packages in that code chunk (like you do in line 60 with slingshot).

- [ ] REQUIRED: Like 36, this should be set as a global option in the vignette 
code. `knitr::opts_chunk$set(dpi = 58)` could be added within an R code chunk 
before the text at line 15.

- [ ] REQUIRED: We don't want people accessing data from GitHub for many
reasons but the major one being the possibility of relocation and not updating
the documentation. If you would like to utilize this data for the vignette it
should be included as part of the package, or could you just use the data used 
with the vignettes?

- [ ] REQUIRED: Line 88-95, it is understandable to not have a computationally 
demanding command evaluate (eval = FALSE), however, the alternative should be 
evaluated. When I evaluate it I get an error, which isn't shown in checks 
because it's not evalutated. Please fix the following error and have this code 
evaluate,

```
> icMat <- evaluateK(counts = counts, knots=3:20, nGenes = 200,
+                    pseudotime = slingPseudotime(crv, na = FALSE),
+                    cellWeights = slingCurveWeights(crv))
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘evaluateK’ for signature ‘"standardGeneric"’
```

- [ ] REQUIRED: In order for lines 97 and 98 to show, the user needs the 
package 'magick' to be installed which means they also need ImageMagick. A 
work around for all this would be to just insert the picture in the text with 
`knitr::include_graphics("temp.png")`.

- [ ] REQUIRED: Lines 379-382, the lines don't have to be evaluated but they 
should be shown so the user knows how to utilize the functions.

- [ ] REQUIRED: Same comment as above with the images, I would just insert the 
image instead of trying to use `draw_image()`.

- [ ] REQUIRED: Lines 412-414, this code won't be needed once the data is 
supplied within the package.

## Man pages

- [ ] REQUIRED: I think the documentation for 'clusterExpressionPatterns' needs 
to be similar to 'associationTest' where you actually document the methods and 
not the function. Because the way it looks now, the man page shows 
'.clusterExpressionPatterns' which may confuse users.

- [ ] REQUIRED: In 'earlyDETest', there is repeated text for the Description.

- [ ] REQUIRED: In 'evaluateK', there are two lines of text for Description and 
they seem generally the same.

- [ ] REQUIRED: There needs to be some code that is tested for `evaluateK()`, 
whether it be in example code of the man page or in the vignette. Without the 
code evaluating somewhere we will have no knowledge if it breaks in the future.

- [ ] REQUIRED: In 'fitGAM', the data for the example should not come from 
GitHub.

- [ ] REQUIRED: In 'plotGeneCount', the data for the example should not come 
from GitHub.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: sceMethods.R is empty and should be removed if you don't intend
on using it.

- [ ] REQUIRED: From R CMD check:
        - .associationTest: no visible global function definition for 'metadata'
        - .earlyDETest: no visible global function definition for 'metadata'
        - .earlyDETest: no visible binding for global variable 'X1'
        - .earlyDETest: no visible binding for global variable 'X2'
        - .fitGAM: no visible binding for global variable 't1'
        - .fitGAM: no visible binding for global variable 'l1'
        - .fitGAM: counts_to_Gam: no visible binding for '<<-' assignment to 'X'
        - .fitGAM: counts_to_Gam: no visible binding for '<<-' assignment to 'dm'
        - .fitGAM: counts_to_Gam: no visible binding for '<<-' assignment to
        'knotPoints'
        - .fitGAM: no visible binding for global variable 'X'
        - .fitGAM: no visible binding for global variable 'dm'
        - .fitGAM: no visible binding for global variable 'knotPoints'
        - .plotSmoothers: no visible binding for global variable 'gene_count'
        - .plotSmoothers: no visible binding for global variable 'lineage'
        - .plotSmoothers_sce: no visible binding for global variable 'gene_count'
        - .plotSmoothers_sce: no visible binding for global variable 'lineage'
        - plotGeneCount: no visible binding for global variable 'dim1'
        - plotGeneCount: no visible binding for global variable 'dim2'
        - plotGeneCount: no visible global function definition for 'metadata'
        - fitGAM,matrix: no visible global function definition for 'colData<-'
        - fitGAM,matrix: no visible global function definition for 'DataFrame'
        - fitGAM,matrix: no visible global function definition for 'rowData<-'
        - fitGAM,matrix: no visible binding for global variable 'X'
        - fitGAM,matrix: no visible binding for global variable 'dm'
        - fitGAM,matrix: no visible global function definition for 'metadata'
        - fitGAM,matrix: no visible global function definition for 'metadata<-'
        Undefined global functions or variables:
        DataFrame X X1 X2 colData<- dim1 dim2 dm gene_count knotPoints l1
        lineage metadata metadata<- rowData<- t1

- [ ] REQUIRED: Avoid sapply(); use vapply() instead. Found in files:
        associationTest, line 131 and 141
        deffEndTest, line 102 and 110
        fitGAM, lines 158, 175, and 190
        startVsEndTest, line 126 and 134

- [ ] REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. Found in
files:
        associationTest, line 111 and 138
        diffEndTest, lines 79, 107, and 128
        earlyDETest, lines 94, 122, 144, and 150
        evaluateK, line 17, 21, 38, and 41
        plotGeneCount, line 67
        startVsEndTest, lines 104, 131, and 150
        utils, line 251

- [ ] REQUIRED: We require that set.seed() not be included inside functions. 
The user should set the seed outside the function if they choose to do so. 
Please make the necessary changes.

- [ ] REQUIRED: Avoid the use of '<<-'.

- [ ] REQUIRED: Line 196 of fitGAM uses ':::' which should be '::'. Is this line 
needed?

- [ ] SUGGESTION: For formating reasons, consider shorter lines; 90 lines 
are > 80 characters long.

- [ ] SUGESTION: For formating reason, consider multiples of 4 spaces for line 
indents, 1107 lines are not.

Best,
Kayla

**Comment by koenvandenberge** [comment] 2019-10-18 12:52
Dear @Kayla-Morrell 

Many thanks for your detailed review of our package.
We have now gone over your review. While we fixed most issues, a few remain, and for those we answer below why we consider it crucial that the package remains as is. The issues that have not been answered have been addressed in the updated version of the package.

We would also like to discuss how we would best include the dataset that we process in our vignette. As you noted above, we used to download it from GitHub, which was found to be problematic since it could be relocated. We had then decided to move to Zenodo to archive the dataset, since these links are permanent, and this is included in the current version of the package. However, it seems like this is problematic for Windows machines, since they seem to be having trouble reading in the file, as shown in our build report. Alternatively, we can include the dataset in the package, but note that then we will exceed the 5MB file limit. It would be great if you could let us know the preferred way of dealing with this, such that we can fix the situation before the deadline.

Best,
Koen



> Hello @koenvandenberge,
> 
> Thank you for submitting to _Bioconductor_. Please see the review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review. Please keep in mind the deadline for new packages to be accepted for the 3.10 release is October 23rd.
> 
> ## General package development
> * [ ]  REQUIRED: The LICENSE.md file is not needed. Since the MIT licese is
>   distributed by R, the only file that is needed is the LICENSE file.
> * [ ]  REQUIRED: What is the purpose of the '_pkgdown.yml' file in the top
>   directory?
> * [ ]  REQUIRED: What is the purpose of the 'docs/' directory?

**Answer**:Those files are produced by the pkgdown package (https://pkgdown.r-lib.org/) and are used to produce a website for the package (https://statomics.github.io/tradeSeq/index.html). It is especially helpful for users for the time being since we do not have a bioconductor page. Note that the file and the folder are both ignored when building the package.

> 
> ## DESCRIPTION
> * [ ]  REQUIRED: Ellaborate a bit more in the 'Description:' of the package, like
>   what types of questions of interest?
> * [ ]  REQUIRED: 'LazyData:' should be set to false. This field being set to true
>   can slow down the loading of packages with data.
> * [ ]  REQUIRED: The package 'methods' is used but not declared.
> 
> ## NAMESPACE
> * [ ]  REQUIRED: You have both `import()` as well as `importFrom()` for the
>   package slingshot. We would prefer `importFrom()` over importing the whole
>   package but please pick one or the other, not both.
> 
> ## Data
> * [ ]  REQUIRED: Is the sds data used somewhere? If so there needs to be a man
>   page that documents the data.
> 
> ## Vignettes
> * [ ]  REQUIRED: There should be an 'Introduction' section that explains a bit
>   about the package. I see you point people to the pre-print, but you should still
>   provide a little detail here. Maybe direct users to the paper for additional
>   details.
> * [ ]  REQUIRED: Add an 'Installation' section that should show the users how to
>   download and load the package from _Bioconductor_. The code should look
>   something like this and should include `eval = FALSE`:
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("tradeSeq")
> ```
> 
> * [ ]  REQUIRED: Line 22-32, it is not necessary to load all of these packages,
>   especially those that are listed as imports in the DESCRIPTION file. Only load
>   in tradeSeq here. Then when you need certain functions in the vignette load the
>   packages in that code chunk (like you do in line 60 with slingshot).
> * [ ]  REQUIRED: Like 36, this should be set as a global option in the vignette
>   code. `knitr::opts_chunk$set(dpi = 58)` could be added within an R code chunk
>   before the text at line 15.
> * [ ]  REQUIRED: We don't want people accessing data from GitHub for many
>   reasons but the major one being the possibility of relocation and not updating
>   the documentation. If you would like to utilize this data for the vignette it
>   should be included as part of the package, or could you just use the data used
>   with the vignettes?

**Answer**: We have now relocated the dataset to Zenodo, and have included this link in the vignette, which should obviate these issues. The other solution would be to include the data as part of the package, but then we are exceeding the 5MB file limit of the package.


> * [ ]  REQUIRED: Line 88-95, it is understandable to not have a computationally
>   demanding command evaluate (eval = FALSE), however, the alternative should be
>   evaluated. When I evaluate it I get an error, which isn't shown in checks
>   because it's not evalutated. Please fix the following error and have this code
>   evaluate,
> 
> ```
> > icMat <- evaluateK(counts = counts, knots=3:20, nGenes = 200,
> +                    pseudotime = slingPseudotime(crv, na = FALSE),
> +                    cellWeights = slingCurveWeights(crv))
> Error in (function (classes, fdef, mtable)  :
>   unable to find an inherited method for function ‘evaluateK’ for signature ‘"standardGeneric"’
> ```
> 
> * [ ]  REQUIRED: In order for lines 97 and 98 to show, the user needs the
>   package 'magick' to be installed which means they also need ImageMagick. A
>   work around for all this would be to just insert the picture in the text with
>   `knitr::include_graphics("temp.png")`.
> * [ ]  REQUIRED: Lines 379-382, the lines don't have to be evaluated but they
>   should be shown so the user knows how to utilize the functions.
> * [ ]  REQUIRED: Same comment as above with the images, I would just insert the
>   image instead of trying to use `draw_image()`.
> * [ ]  REQUIRED: Lines 412-414, this code won't be needed once the data is
>   supplied within the package.

**Answer**: We have now stored the data on Zenodo and download it from there. As mentioned above, we can also store the data in the package, but then we will exceed the file limit of our package.

> 
> ## Man pages
> * [ ]  REQUIRED: I think the documentation for 'clusterExpressionPatterns' needs
>   to be similar to 'associationTest' where you actually document the methods and
>   not the function. Because the way it looks now, the man page shows
>   '.clusterExpressionPatterns' which may confuse users.
> * [ ]  REQUIRED: In 'earlyDETest', there is repeated text for the Description.
> * [ ]  REQUIRED: In 'evaluateK', there are two lines of text for Description and
>   they seem generally the same.

**Answer**: This might be a misunderstanding, since we do not observe this.


> * [ ]  REQUIRED: There needs to be some code that is tested for `evaluateK()`,
>   whether it be in example code of the man page or in the vignette. Without the
>   code evaluating somewhere we will have no knowledge if it breaks in the future.
> * [ ]  REQUIRED: In 'fitGAM', the data for the example should not come from
>   GitHub.
> * [ ]  REQUIRED: In 'plotGeneCount', the data for the example should not come
>   from GitHub.
> 
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encourage them. See
>   http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
> 
> ## R code
> * [ ]  REQUIRED: sceMethods.R is empty and should be removed if you don't intend
>   on using it.

Many of the R CMD check issues below are the result of R CMD check not being compatible with the tidyverse syntax or the output of the assign function.
Below, we show which ones are due to the `assign` function and which ones due to `tidyverse`. All others have been fixed.


 - `Assign` function incompatibility
 
    - .earlyDETest: no visible binding for global variable 'X1'
    - .earlyDETest: no visible binding for global variable 'X2'
    - .fitGAM: no visible binding for global variable 't1'
    - .fitGAM: no visible binding for global variable 'l1'
    - .fitGAM: no visible binding for global variable 'X'
    - .fitGAM: no visible binding for global variable 'dm'
    - .fitGAM: no visible binding for global variable 'knotPoints'
    - fitGAM,matrix: no visible binding for global variable 'X'
    - fitGAM,matrix: no visible binding for global variable 'dm'
    
 - `tidyverse` incompatibility
 
    - .plotSmoothers: no visible binding for global variable 'gene_count'
    - .plotSmoothers: no visible binding for global variable 'lineage'
    - .plotSmoothers_sce: no visible binding for global variable 'gene_count'
    - .plotSmoothers_sce: no visible binding for global variable 'lineage'
    - plotGeneCount: no visible binding for global variable 'dim1'
    - plotGeneCount: no visible binding for global variable 'dim2'


 

> * [ ]  REQUIRED: From R CMD check:
>   - .associationTest: no visible global function definition for 'metadata'
>   - .earlyDETest: no visible global function definition for 'metadata'
>   - .earlyDETest: no visible binding for global variable 'X1'
>   - .earlyDETest: no visible binding for global variable 'X2'
>   - .fitGAM: no visible binding for global variable 't1'
>   - .fitGAM: no visible binding for global variable 'l1'
>   - .fitGAM: counts_to_Gam: no visible binding for '<<-' assignment to 'X'
>   - .fitGAM: counts_to_Gam: no visible binding for '<<-' assignment to 'dm'
>   - .fitGAM: counts_to_Gam: no visible binding for '<<-' assignment to
>   'knotPoints'
>   - .fitGAM: no visible binding for global variable 'X'
>   - .fitGAM: no visible binding for global variable 'dm'
>   - .fitGAM: no visible binding for global variable 'knotPoints'
>   - .plotSmoothers: no visible binding for global variable 'gene_count'
>   - .plotSmoothers: no visible binding for global variable 'lineage'
>   - .plotSmoothers_sce: no visible binding for global variable 'gene_count'
>   - .plotSmoothers_sce: no visible binding for global variable 'lineage'
>   - plotGeneCount: no visible binding for global variable 'dim1'
>   - plotGeneCount: no visible binding for global variable 'dim2'
>   - plotGeneCount: no visible global function definition for 'metadata'
>   - fitGAM,matrix: no visible global function definition for 'colData<-'
>   - fitGAM,matrix: no visible global function definition for 'DataFrame'
>   - fitGAM,matrix: no visible global function definition for 'rowData<-'
>   - fitGAM,matrix: no visible binding for global variable 'X'
>   - fitGAM,matrix: no visible binding for global variable 'dm'
>   - fitGAM,matrix: no visible global function definition for 'metadata'
>   - fitGAM,matrix: no visible global function definition for 'metadata<-'
>   Undefined global functions or variables:
>   DataFrame X X1 X2 colData<- dim1 dim2 dm gene_count knotPoints l1
>   lineage metadata metadata<- rowData<- t1
> * [ ]  REQUIRED: Avoid sapply(); use vapply() instead. Found in files:
>   associationTest, line 131 and 141
>   deffEndTest, line 102 and 110
>   fitGAM, lines 158, 175, and 190
>   startVsEndTest, line 126 and 134
> * [ ]  REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. Found in
>   files:
>   associationTest, line 111 and 138
>   diffEndTest, lines 79, 107, and 128
>   earlyDETest, lines 94, 122, 144, and 150
>   evaluateK, line 17, 21, 38, and 41
>   plotGeneCount, line 67
>   startVsEndTest, lines 104, 131, and 150
>   utils, line 251
> * [ ]  REQUIRED: We require that set.seed() not be included inside functions.
>   The user should set the seed outside the function if they choose to do so.
>   Please make the necessary changes.

**Answer**: our algorithm is by nature stochastic. We require this for reproducibility purposes, since we perform a multinomial sampling to assign cells to lineages in a trajectory. This must be reproducible, and we do not want to risk the possibility that users forget to set a seed prior to running the function. Note, that the seed can be passed as an argument to the fitGAM function, hence it is not hard coded in the package. Exceptions have been made for some similar packages such as SC3 (https://bioconductor.org/packages/release/bioc/html/SC3.html).


> * [ ]  REQUIRED: Avoid the use of '<<-'.
> * [ ]  REQUIRED: Line 196 of fitGAM uses ':::' which should be '::'. Is this line
>   needed?

**Answer**: We build a formula which we then pass to the gam function of the mgcv package. This formula uses the s function from mgcv that is not exported. We can build the formula on the stop (i.e when we call the gam function), which would allow us to not use :::, but it would make for a much harder to understand code. 


> * [ ]  SUGGESTION: For formating reasons, consider shorter lines; 90 lines
>   are > 80 characters long.
> * [ ]  SUGESTION: For formating reason, consider multiples of 4 spaces for line
>   indents, 1107 lines are not.
> 
> Best,
> Kayla

**Comment by koenvandenberge** [comment] 2019-10-21 15:43
Hi @Kayla-Morrell 

We have now updated the package to contain the data used in the vignette and hence do no longer download it from GitHub (or Zenodo). The only remaining warning would be the usage of `set.seed`, which we have argumented in our response above.

Although not labelled here, the build report has an error that may be unrelated to the package (cc @lshep ). The only reason I can think of is the version number of the package; we got to version `0.99.99` in the previous commit, and I have now incremented it to `0.99.9901`.

Please let us know if you require any further changes for the submission deadline.

Best,
Koen

**Comment by mtmorgan** [comment] 2019-10-23 13:14
Please remove the call to `set.seed()` from your code. While the user seeking reproducibility must call `set.seed()` explicitly, they will see immediately what the problem is, whereas a user incorporating your package into their workflow will wonder why their calls to `set.seed()` are apparently being ignored / over-ridden by some mystery function. This is standard practice in Bioconductor and in the R community in general.

**Comment by koenvandenberge** [comment] 2019-10-23 19:26
@Kayla-Morrell @mtmorgan 

We've now removed the `set.seed()` code from the package and recommended to call it prior to running `tradeSeq` in the vignette.
Thank you for your review.

Best,
Koen

**Comment by koenvandenberge** [comment] 2019-10-23 19:58
Awesome!!

**Comment by mtmorgan** [comment] 2019-10-24 15:35
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/koenvandenberge.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tradeSeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tradeSeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-10-24 15:35 UTC
Labels: 3a. accepted, OK
