### ISSUE TITLE
PloGO2

### ISSUE THREAD

**Issue by APAFbioinformatics** [Bioconductor/Contributions#1352] opened 2020-01-29 02:11 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/APAFbioinformatics/PloGO2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-01-29 07:37
please remove the vignettes/*pdf file from your github repository; this file is generated automatically when your package is built.

**Comment by APAFbioinformatics** [comment] 2020-01-31 00:13
Hi,
We would greatly appreciate some help with the following problem: the package build seems to fail on Linux with the error below, which we cannot reproduce in our local environment.  Could you please offer any suggestion?  Since Category and genefilter are pretty core Bioconductor packages, we would assume there would be no problem loading them?

Many thanks!
Dana

R CMD check error:
=============
Error: package or namespace load failed for Category in loadNamespace(j <- imp[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called genefilter
Error: package Category could not be loaded
Execution halted

**Comment by lshep** [comment] 2020-02-06 13:13
That ERROR was on our end.  I can look further into the tokay ERROR.  @dvantwisk  you can review based on the linux review.

**Comment by APAFbioinformatics** [comment] 2020-02-18 04:16
Thank you for the clarification that the build ERROR was not on our end - if there is anything we can do please let us know, otherwise we look forward to hearing any comments from the review.
Many thanks!

**Comment by dvantwisk** [comment] 2020-03-12 12:29
I apologize for the wait. Here is a review of your package. The [REQUIRED] tag indicates changes that need to be made or addressed. The [CONSIDER] tag indicates changes that are advisable but not necessary. Please message me back when you are done making changes.

DESCRIPTION
- [ ] [REQUIRED] `Depends:` is only used for packages that are vital to running
this package (e.g. R). It you are simply importing symbols for a packages, use
`Imports:`.

NAMESPACE
- [ ] [REQUIRED] You are using `exportPattern("^[[:alpha:]]+")` to export all
symbols in your package. Are all symbols in your package meant to be available
to the user?  I ask that you explicitly state which symbols are being exported
in your NAMESPACE.

vignettes/PloGO2_vignette.Rnw
- [ ] [REQUIRED] We generally don't want to see `eval=FALSE`s in vignettes since
we want user facing code to be run on the build machines to verify this
functionality is working. Is there a reason why you've included these?

GENERAL
- [ ] [REQUIRED] Use `seq_len()` and `seq_along()` instead of `1:...`. This is
slightly more efficient and avoids the unexpected case where `1:0` is `1 0`.

- [ ] [REQUIRED] In functions about creating plots, these functions create the
file to display the plot.  This is troublesome because it may cause the user to
unknowingly flood their directory with plots that they didn't name themselves
and doesn't give the user the ability to modify the plots as they see fit.
It would be better to instead simply return the plot from these functions and
allow the user to save it to a file themselves.

- [ ] [REQUIRED] You use a function called `Error()` several times, but this
function doesn't seem to exist. It would be better to use `stop()`.

- [ ] [REQUIRED] When saving a file, it is best to have the save location's
default location be a  `tempfile()` or to not have a default and exhort the user
to save the file to a location that they choose.

- [ ] [CONSIDER] Using `match.arg()`. For example in `processAnnotation.R:L3`,
the function processAnnotation's `format` argument has two possible values.
To display these values to your user in the function, you can say 
`format = c("compact", "long")` in the function declaration. The default
value will be the first value in the vector. The value that the user enters can
then be obtained using `format <- match.arg(format)`. If the value is not in the
vector of accepted values, an error will be thrown. This can be done extensively
throughout this package.

R/getUniprotBatch.R
- [ ] [REQUIRED] L6: When trying to access a web resource, it's best to create
a default argument in your function for the `hostname`.
`"https://www.uniprot.org/uniprot/?query="` is a good default but you should
allow the users to change the value just in case the web resource were to move.

R/sysdata.rda
- [ ] [REQUIRED] Is this file needed? Consider removing it.

tests
- [ ] [CONSIDER] Creating tests using the `testthat` package.

**Comment by dvantwisk** [comment] 2020-04-07 14:01
Hello,

I just want to check in with the progress of your package submission. I need to remind you that the deadline for your package to be included in the next Bioconductor release is April 21st.

**Comment by APAFbioinformatics** [comment] 2020-04-07 20:46
Thank you @dvantwisk for the review, and sorry about the delay - strange times for all.  We have made good progress with implementing the required changes and hope to be able to make the deadline. Many thanks!

**Comment by APAFbioinformatics** [comment] 2020-04-08 04:30
Dear @dvantwisk, we have submitted the package again, with all the [REQUIRED] modifications implemented.  However, we are getting ERROR on the Windows build again; we have tried the package build and check on 3 different machines and cannot reproduce the error - is it possibly again on the build side?
Many thanks for your help.

**Comment by lshep** [comment] 2020-04-10 16:25
It looks like there are two code chunks with the label genFile.  Could you try and rename one to see if the windows latex ERROR goes away.

**Comment by APAFbioinformatics** [comment] 2020-04-14 01:29
Many thanks @lshep for your suggestion, we changed the code chunks name and the build passes now on both platforms.  But now the check issues errors related to the NEWS package, which a few days ago were just warnings.
We'll keep trying...

**Comment by lshep** [comment] 2020-04-14 01:40
The NEWS file is on our end. Sorry for the confusion on that.  I made a fix in the BiocCheck code that should propagate fully tomorrow.

**Comment by lshep** [comment] 2020-04-14 01:49
I'll rerun the issue -- it should be clear on malbec but won't clear up on windows until tomorrow afternoon -- until then you can ignore it.

**Comment by APAFbioinformatics** [comment] 2020-04-14 01:56
No worries, thanks @lshep, really appreciate the help!

**Comment by APAFbioinformatics** [comment] 2020-04-14 23:50
Dear @lshep, we noticed that the only warning message in the overnight built was about the existence of the vignette pdf files in the inst/doc. We then removed them from the inst/doc and committed. In the new built report, we can see that the Linux platform was built OK but not the Windows which now generated an error when creating the vignette. Could you please suggest what we need to do in order for it to pass? Your help is greatly appreciated!

**Comment by lshep** [comment] 2020-04-16 12:58
I'll look into the windows ERROR today;  we were updating the R on windows yesterday so I was unable to test.  It seems based on [this comment](https://github.com/Bioconductor/Contributions/issues/1352#issuecomment-610745098)  you are ready for a re-review from @dvantwisk based on the linux build.

**Comment by APAFbioinformatics** [comment] 2020-04-16 22:47
Thanks @lshep, really appreciate your help!
We are ready for re-review whenever @dvantwisk is able to.

**Comment by lshep** [comment] 2020-04-17 20:10
I'm not able to reproduce the ERROR when I go on the builder and try to build manually.  I would say ignore this for now.  If it continues we can investigate some other ways.

**Comment by dvantwisk** [comment] 2020-04-17 20:22
I think the changes that were made to the package look fine. @lshep are we able to accept the package now despite the windows issues?

**Comment by lshep** [comment] 2020-04-17 20:28
Yes. Go ahead.  If it continues on the daily builder let me know and I'll look into it more.

**Comment by APAFbioinformatics** [comment] 2020-04-18 04:38
Dear @dvantwisk and @lshep, that's brilliant! Thank you so much for all the help you guys provided, really appreciate!

**Comment by mtmorgan** [comment] 2020-04-21 08:40
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/APAFbioinformatics.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PloGO2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PloGO2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-21 08:40 UTC
Labels: 3a. accepted, ERROR
