### ISSUE TITLE
PDATK

### ISSUE THREAD

**Issue by ChristopherEeles** [Bioconductor/Contributions#1881] opened 2021-02-05 23:50 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/PDATK

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LiNk-NY** [comment] 2021-02-17 17:26
Hi Christopher, @ChristopherEeles 

Thank you for your submission. 
Please see the review below. 
Feel free to ask any questions. 

Best regards,
Marcel

---

# PDATK #1881

## DESCRIPTION

* Looks good.

## NAMESPACE

* Is there a reason for exporting class unions (e.g.,
`PCOSP_or_ClinicalModel`)? These should be internal to the
package for easier method dispatch.

## vignettes

* Include an `Installation` section in the vignette
* Include the PCOSP paper reference.
* It may be better to use the `assays` argument instead of a `sumExp` one in
the constructor function of `SurvivalExperiment` for ease-of-use and simplicity
you can test for class membership inside your constructor function.
* Add references to both vignettes

Minor:
* Use `grep` with `value = TRUE` instead of `x[grepl(..., x)]`

## R

* We do not recommend setting a `randomSeed` inside functions. This should
be done outside the function by the user (in `trainModel` and others).
See: http://bioconductor.org/developers/package-guidelines/#rcode
* Avoid using inprecise comparisons when merging data such as `colData` in
`!all(colDTL[[1]] == colDTL[[2]], na.rm=TRUE)` if there are NA values in
different cells the two datasets may still pass this test even though they are
not equal. I would suggest merging using a `key` identifier and with
`all = TRUE`.

## tests

* We highly recommend adding tests to the package for maintaining robustness
of the code.

**Comment by ChristopherEeles** [comment] 2021-02-18 21:12
Hi @LiNk-NY,

I am having a hard time fixing the timeout issues on Windows Server. The problem arises because I have to redo model training, prediction and validation for any of the downstream functions like plotting or model comparison. I am already pushing package size limits so I can't just save a pre-validated model to use for those examples. I have done some searching to see if it is possible to cache the results of one example to be loaded in another, but haven't found anything about this. Do you have any recommendations?

NAMESPACE

    Is there a reason for exporting class unions (e.g.,
    PCOSP_or_ClinicalModel)? These should be internal to the
    package for easier method dispatch.
    - This is fixed

vignettes

    Include an Installation section in the vignette
    - Done
   
    Include the PCOSP paper reference.
    - Done

    It may be better to use the assays argument instead of a sumExp one in
    the constructor function of SurvivalExperiment for ease-of-use and simplicity
    you can test for class membership inside your constructor function.

    - I am not sure what you mean by this. I originally tried just passing an existing SummarizedExperiment through to the dots
      of the SummarizedExperiment constructor, but found that this stripped off existing metadata and thus didn't achieve 
      the result I was looking for (which is to allow users to easily convert a SummarizedExperiment to a SurvivalExperiment.

    Add references to both vignettes
    - Done

Minor:

    Use grep with value = TRUE instead of x[grepl(..., x)]
    - I can update this but I am curious why it's important?

R

    We do not recommend setting a randomSeed inside functions. This should
    be done outside the function by the user (in trainModel and others).
    See: http://bioconductor.org/developers/package-guidelines/#rcode
    - I am aware of this guideline, but couldn't think of another way to achieve the goal of a completely reproducible 
      self-contained model object without setting the seed internally. I originally wanted to capture the existing seed, 
      but as far as I can tell it isn't possible to reconstruct the original set.seed call from .Random.seed. The issue with 
      setting the seed outside of the method is that I then have no way to record all of the model configuration 
      parameters needed to reproduce a specific run. Setting the seed outside of the method also has the drawback of depending   
      on the number of ticks to the random seed since it was set, so the samples will depend not only on the seed, but also 
      how many random  samples were taken before the function was called.
    - I guess my question is, is this a HARD rule? I agree that in most cases it is not a good idea to set.seed inside of a function 
      call, but in this case it is a feature to ensure that a model produces the same results regardless of where it is called. 
      We actually had an issue with reproducing the original PCOSP publication in the package because of that exact issue.
    - If we can compromise, maybe I can set the default random seed to NA, so no seed it set, then if a user specifies a 
      randomSeed when building the model object I can throw a warning that I modified the seed locally inside the fuction call?

    Avoid using inprecise comparisons when merging data such as colData in
    !all(colDTL[[1]] == colDTL[[2]], na.rm=TRUE) if there are NA values in
    different cells the two datasets may still pass this test even though they are
    not equal. I would suggest merging using a key identifier and with
    all = TRUE.
   - I will look into this, haven't had a chance yet but will

tests

    We highly recommend adding tests to the package for maintaining robustness
    of the code.
    - I added tests; ~50% coverage, ~80% if you include the examples in the covr run; I will add more but am working on a 
       number of project right now.

**Comment by LiNk-NY** [comment] 2021-02-19 17:33
Hi Christopher, @ChristopherEeles 

> I am having a hard time fixing the timeout issues on Windows Server. The problem arises because I have to redo model training, prediction and validation for any of the downstream functions like plotting or model comparison. I am already pushing package size limits so I can't just save a pre-validated model to use for those examples. I have done some searching to see if it is possible to cache the results of one example to be loaded in another, but haven't found anything about this. Do you have any recommendations?

My recommendation would be to reduce the size of the data that you have in the package. Your examples should demonstrate the package functionality rather than a real-world workflow. Large computations are often the cause of timeouts. By reducing the size of the data, you'll lower the timings. Windows takes longer because of the two architectures. 

> It may be better to use the assays argument instead of a sumExp one in
> the constructor function of SurvivalExperiment for ease-of-use and simplicity
> you can test for class membership inside your constructor function.
> 
> - I am not sure what you mean by this. I originally tried just passing an existing SummarizedExperiment through to the dots
>   of the SummarizedExperiment constructor, but found that this stripped off existing metadata and thus didn't achieve 
>   the result I was looking for (which is to allow users to easily convert a SummarizedExperiment to a SurvivalExperiment.
> 

Your constructor function should be able to find and recognize `SummarizedExperiment` inputs in the `...` argument. Take the list and go through it with: 
```
inputs <- list(...)
is(inputs[[1]], "SummarizedExperiment")
```

> Add references to both vignettes
> - Done
> ```
> 
> Minor:
> 
> ```
> Use grep with value = TRUE instead of x[grepl(..., x)]
> - I can update this but I am curious why it's important?
> ```

This is a minor point but in general, it's good to reduce the number of operations
for readability and performance. 

> 
> R
> 
> ```
> We do not recommend setting a randomSeed inside functions. This should
> be done outside the function by the user (in trainModel and others).
> See: http://bioconductor.org/developers/package-guidelines/#rcode
> - I am aware of this guideline, but couldn't think of another way to achieve the goal of a completely reproducible 
>   self-contained model object without setting the seed internally. I originally wanted to capture the existing seed, 
>   but as far as I can tell it isn't possible to reconstruct the original set.seed call from .Random.seed. The issue with 
>   setting the seed outside of the method is that I then have no way to record all of the model configuration 
>   parameters needed to reproduce a specific run. Setting the seed outside of the method also has the drawback of depending   
>   on the number of ticks to the random seed since it was set, so the samples will depend not only on the seed, but also 
>   how many random  samples were taken before the function was called.
> - I guess my question is, is this a HARD rule? I agree that in most cases it is not a good idea to set.seed inside of a function 
>   call, but in this case it is a feature to ensure that a model produces the same results regardless of where it is called. 
>   We actually had an issue with reproducing the original PCOSP publication in the package because of that exact issue.
> - If we can compromise, maybe I can set the default random seed to NA, so no seed it set, then if a user specifies a 
>   randomSeed when building the model object I can throw a warning that I modified the seed locally inside the fuction call?
> 

The seed should be recorded by the user and not the function. You can record the seed _without_ a call to `set.seed` inside the function and at the same time record it in the metadata. This will be up to the user to document. 

```{r}
set.seed(1)
trainModel(..., seed.used = 1) {
    metadata(object)$randomSeed <- seed.used
}
```

Best,
Marcel

**Comment by LiNk-NY** [comment] 2021-02-23 19:05
Hi Chris, @ChristopherEeles 
Can you bump the version of the package and push? 
Thanks,
Marcel

**Comment by ChristopherEeles** [comment] 2021-02-24 19:54
Hi Marcel @LiNk-NY,

I fixed my TIMEOUT issues. Turns out the example size was fine, but `BiocParallel` was using `SnowParam` with a SOCK cluster on Windows and that was slowing down my examples and tests ~8x. Any idea why the overhead is so high?

I register `SerialParam` before running the parallelized examples in the package now, but wondered if there is a more 'elegant' way to accomplish the same result, such as setting global settings for examples in a package?

The remaining warning on Windows seems like a false positive due to bad file names in the auto-generated docs:
```
Found the following significant warnings:
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/models<-,SurvivalModel,SimpleList-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/models<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationData<-,SurvivalModel,CohortList-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationData<-.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationStats<-,SurvivalModel,data.frame-method.html': Invalid argument
  Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationStats<-.html': Invalid argument
See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.Rcheck/00install.out' for details.
```
Regarding the rest of the review:

> The seed should be recorded by the user and not the function. You can record the seed without a call to set.seed inside the function and at the same time record it in the metadata. This will be up to the user to document.

- This is now fixed, no more seeds are set inside function calls. Instead, randomSeed is now a mandatory parameter to the constructor of the model objects in PDATK

> This is a minor point but in general, it's good to reduce the number of operations
for readability and performance.
- I can't find the call to x[grepl(..., x)] anymore. I deleted a bunch of unused utility code from a previous refactor, so I think this snippet was probably in there.

> Your constructor function should be able to find and recognize SummarizedExperiment inputs in the ... argument. Take the list and go through it with:
- This is fixed and I now check the first item of dots instead of adding the sumExp parameter.

I believe that should address all of your concerns. If you require further changes please let me know.

Thanks for you assistance.

Best,
Chris

**Comment by ChristopherEeles** [comment] 2021-02-24 20:00
Missed a review comment:
>Avoid using inprecise comparisons when merging data such as colData in
!all(colDTL[[1]] == colDTL[[2]], na.rm=TRUE) if there are NA values in
different cells the two datasets may still pass this test even though they are
not equal. I would suggest merging using a key identifier and with
all = TRUE.
- I fixed this by doing my comparison with all.equal instead

**Comment by LiNk-NY** [comment] 2021-03-02 14:24
Hi Christopher, @ChristopherEeles 

> I fixed my TIMEOUT issues. Turns out the example size was fine, but `BiocParallel` was using `SnowParam` with a SOCK cluster on Windows and that was slowing down my examples and tests ~8x. Any idea why the overhead is so high?
> 
> I register `SerialParam` before running the parallelized examples in the package now, but wondered if there is a more 'elegant' way to accomplish the same result, such as setting global settings for examples in a package?
 
I would avoid running parallel computations in the examples. Please keep it to one core. The examples are not supposed to be resource intensive. They're meant to demonstrate the use of the function with a small dataset. Remember that the package will be checked along with a number of packages. If all other packages are using multiple CPUs, they will significantly strain the build system. 

> The remaining warning on Windows seems like a false positive due to bad file names in the auto-generated docs:
> 
> ```
> Found the following significant warnings:
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/models<-,SurvivalModel,SimpleList-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/models<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationData<-,SurvivalModel,CohortList-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationData<-.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationStats<-,SurvivalModel,data.frame-method.html': Invalid argument
>   Rd warning: cannot open file 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.buildbin-libdir/00LOCK-PDATK/00new/PDATK/help/validationStats<-.html': Invalid argument
> See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1881/PDATK_20210224192007/PDATK.Rcheck/00install.out' for details.
> ```

Yes, you can ignore those warnings on Windows. They're related to how the package is checked by the BBS / SPB.  

BTW, I'm not sure how the package is building and checking without pushing to `git.biocoductor.org`. Can you update the package there? 
cc: @lshep

**Comment by ChristopherEeles** [comment] 2021-03-05 16:11
Hi Marcel @LiNk-NY,

I added the Bioconductor upstream and pushed there. I was also confused when I didn't have to push to Bioconductor for the build to start.

Let me know if you need anything further. For the submission.

I also have a suggestion/request. For my parallel examples, I actually just used `BiocParallel` with the default settings, so I never explicitly parallelized any of the code, I just pass dots to my `bplapply` calls so the user can use `BPPARAM.` Given this fact, it seems that the default backend on Windows server is `SnowParam` with a SOCK cluster. Maybe it is worthwhile for you guys to register `SerialParam` as the back-end by default to prevent the issues you mentioned above?

Best,
Chris

**Comment by ChristopherEeles** [comment] 2021-03-09 15:58
Hi Marcel @LiNk-NY,

I have responded to all review comments.

Please let me know if you need anything further for the submission.

Best,
Chris

**Comment by LiNk-NY** [comment] 2021-03-09 18:07
Hi Christopher, @ChristopherEeles 

Sorry for the delay in getting back to you. Thanks for making those changes.

> I added the Bioconductor upstream and pushed there. I was also confused when I didn't have to push to Bioconductor for the build to start.

Perhaps you had set up a webhook? We are phasing out this functionality and it should not work in the future. 

> I also have a suggestion/request. For my parallel examples, I actually just used `BiocParallel` with the default settings, so I never explicitly parallelized any of the code, I just pass dots to my `bplapply` calls so the user can use `BPPARAM.` Given this fact, it seems that the default backend on Windows server is `SnowParam` with a SOCK cluster. Maybe it is worthwhile for you guys to register `SerialParam` as the back-end by default to prevent the issues you mentioned above?

Perhaps @mtmorgan can comment on this but I would recommend that you make `SerialParam` default in your code to
avoid greedy computations (which you have done already). 

Best regards,
Marcel

**Comment by vjcitn** [comment] 2021-03-17 14:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ChristopherEeles.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PDATK")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PDATK

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-03-17 14:02 UTC
Labels: 3a. accepted, WARNINGS
