### ISSUE TITLE
RLHub

### ISSUE THREAD

**Issue by millerh1** [Bioconductor/Contributions#2350] opened 2021-09-29 22:16 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bishop-Laboratory/RLHub

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2021-09-29 22:21
Please enhance the description by mentioning R-loop genomics in the DESCRIPTION for
the poor soul who does not know what RLBase is.

**Comment by millerh1** [comment] 2021-09-29 22:39
@vjcitn Thank you for pointing this out! I have now updated the `DESCRIPTION` to be more informative.

**Comment by millerh1** [comment] 2021-09-30 22:32
I have also just updated the `man/` pages with significantly more detail and bumped the version.

**Comment by millerh1** [comment] 2021-10-01 17:22
Currently waiting on an `awaiting moderation` tag.

Also, I am submitting an adjoining software package: https://github.com/Bishop-Laboratory/RLSeq

**Comment by millerh1** [comment] 2021-10-04 16:45
AdditionalPackage: https://github.com/Bishop-Laboratory/RLSeq

**Comment by millerh1** [comment] 2021-10-05 19:04
@lshep it appears that the MacOS runner threw an error on `RLSeq` because it couldn't find the adjoining ExperimentHub package. 

```shell
ERROR: dependency RLHub is not available for package RLSeq
```

Do you have any suggestion about how I should go about resolving this?

**Comment by lshep** [comment] 2021-10-06 11:41
If you look at the build report for RLHub it also failed to build. Once the RLHub package builds RLSeq would be able to find it. Let me try to kick off a manual build the mac builders were having some issues this week and I think the original RLHub ERROR was on us.

**Comment by lshep** [comment] 2021-10-06 12:02
Manually kicking off RLSeq since RLHub was now successful

**Comment by millerh1** [comment] 2021-10-06 12:28
@lshep Thank you! I am a bit confused now at the TIMEOUT error -- it only happens on MacOS. Looking at the logs, it looks like MacOS is take 2X as long as run the examples as the other builders.

**Comment by lshep** [comment] 2021-10-06 12:30
I'll look more and review based on the other platforms for now.  In the meantime please try to clean up as many NOTES as possible.  Cheers

**Comment by millerh1** [comment] 2021-10-07 05:46
Hi @lshep I've made some of the requested changes (tackled most of the NOTEs), but I'm now struggling to clean the pack files since I now have a warning about them. I have no problem removing the problematic files locally (and even no issues pushing these changes to GitHub), but when I try to push to the bioconductor git repo I'm getting permission denied errors.

Here's what I'm trying (using the [instructions](https://rtyley.github.io/bfg-repo-cleaner/) from BFG):

```shell
git clone --mirror git@git.bioconductor.org:packages/RLSeq.git
cd RLSeq.git
java -jar ../../bfg-1.14.0.jar --strip-blobs-bigger-than 10K
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```

This should have worked, as per the [instructions](https://rtyley.github.io/bfg-repo-cleaner/) from BFG. However, this is the error I am getting:

```shell
Enumerating objects: 2073, done.
Writing objects: 100% (2073/2073), 2.01 MiB | 85.60 MiB/s, done.
Total 2073 (delta 0), reused 0 (delta 0)
remote: Resolving deltas: 100% (1280/1280), done.
remote: FATAL: + refs/heads/master packages/RLSeq millerh1 DENIED by fallthru
remote: error: hook declined to update refs/heads/master
To git.bioconductor.org:packages/RLSeq.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/RLSeq.git'
```

Trying with `git push -f` produces the same issue. And even using the full tree instead of just `--mirror` I still see the same problem. I have no problem pushing new changes, but I can't seem to rewrite previously-committed files without elevated permissions.

Would you mind nuking the repository so I can start afresh? Or if you have any other ideas or suggestions, please let me know!

**Comment by lshep** [comment] 2021-10-07 11:42
We don't allow force pushes from maintainer and will need assistance from us.  @nturaga could you help?

**Comment by nturaga** [comment] 2021-10-07 17:29
I'm reset the package on git.bioconductor. You should be good to go.

I've noticed your default branch is 'main' on github, it's 'master' at the moment on git.bioconductor. Please take note.

**Comment by millerh1** [comment] 2021-10-07 19:59
Thank you @lshep and @nturaga. I have just pushed the clean repo!

**Comment by millerh1** [comment] 2021-10-07 20:31
I am unsure of what the new error is -- I am not seeing it locally, and I am unable to view the check logs. I have a suspicion that I may have needed to push the ExperimentHub package again first since RLSeq depends on it... so I've now bumped the version and done that.

**Comment by millerh1** [comment] 2021-10-07 20:42
RLHub has built successfully so I'm going to retry RLSeq.

**Comment by millerh1** [comment] 2021-10-07 23:11
Updated the RLSeq package so that tests and examples will take less time. This should remove the `Warning` tag.

**Comment by lshep** [comment] 2021-10-12 12:46
Please see review of packages below: 


**RLHub**


**README**

- [ ] Pleae include Bioconductor installation instructions of the package

**vignette**

- [ ] Include Bioconductor package installation instructions.

- [ ] verifying  `{.r}` is the same as a `eval=FALSE` code chunk?


------------------------------

**RLSeq**

**LICENSE**

- [ ] Just wanted to verify as the authors are listed as `RSeqR` not `RLSeq`

**inst**

- [ ] Please explain the use case and definition of the directories in
  `inst`. These are not typical names (ie. ext-data, int-data, Rmd). Are the
  files in these directories accesse by your code, vignette examples. etc?
  At the very least `ext-data` should take the classic `extdata` form and there
  should be an accompanied `inst/scripts` directory that gives sources and how
  the data was generated. `Rmd` if this is documentation it should be in the
  vignette directory not an ad-hoc directory so it is compiled and checked with
  R CMD build/R CMD check. etc....

**vignette**

- [ ] Link of `RLBase` does not work. 

_Quick-start_

- [ ] `RLBase` link does not work 

- [ ] The vignette should not be referencing your s3 buckets directly. Use the
  ExperimentHub interface to download the data for your vignette.

Until the vignette is updated appropriatly I will not continue to review in
detail.


**R code / man pages**

Again also where appropriate please update to access data through the
ExperimentHub so caching of data is implemented. 


When ready please perform version bumps to trigger new builds and comment back here with what has been updated/changed or make comments addressing issues.  When ready please request a re-review

Cheers

**Comment by millerh1** [comment] 2021-10-15 03:48
@lshep I am not sure what is going on, but it appears the build system may be stalled. Hopefully it was go through soon... In the meantime, here is my response to the points which you raised:

Hi @lshep,

Thank you for the review of the packages! I have done my best to address your comments -- please let me know if I have misunderstood any of them.

# RLHub

## README

**Comment**

>Please include Bioconductor installation instructions of the package

**Response**

Thank you for the suggestion! I have now updated the `README` to include these.


## vignette

**Comment**

> * [x]  Include Bioconductor package installation instructions.

**Response**

I have now updated this as well. 

**Comment**

> * [x]  verifying  `{.r}` is the same as a `eval=FALSE` code chunk?

**Response**

Yep! That prevents code evaluation since it just makes a code block with R syntax highlighting. 

# RLSeq

## LICENSE

**Comment**
 
> * [x]  Just wanted to verify as the authors are listed as `RSeqR` not `RLSeq`

**Response**

Yes! Thank you for pointing this out -- I have now changed it everywhere to reflect the correct name. 

## inst

**Comment**

> * [x]  Please explain the use case and definition of the directories in
>   `inst`. These are not typical names (ie. ext-data, int-data, Rmd). Are the
>   files in these directories accesse by your code, vignette examples. etc?
>   At the very least `ext-data` should take the classic `extdata` form and there
>   should be an accompanied `inst/scripts` directory that gives sources and how
>   the data was generated. `Rmd` if this is documentation it should be in the
>   vignette directory not an ad-hoc directory so it is compiled and checked with
>   R CMD build/R CMD check. etc....

**Response**

Thank you for pointing this out! I have now updated the `ext-data` folder to be called `extdata`. The `Rmd` folder is where the RMarkdown templates required for the `report` function are located. I have included a `README.md` in `inst/` now which explains this. 

The `int-data/` folder contained data used internally by functions in the package. I have now refactored the package such that all data is in the `data/` folder and the scripts used to build the data objects are in `data-raw/`. I have also added `data.R` in the `R/` folder, which provides documentation of each dataset.


## vignette

**Comment**

> * [x]  Link of `RLBase` does not work.

**Response**
 
Thank you for pointing this out! It now works. 

### _Quick-start_

**Comment**

> * [x]  `RLBase` link does not work

**Response**

I have now updated this as well.

**Comment**

> * [ ]  The vignette should not be referencing your s3 buckets directly. Use the
>   ExperimentHub interface to download the data for your vignette.

**Response**

These data are not provided in ExperimentHub at this time. They are processed files (there are over 1000 in total - ~ 60GB in total) which are generated by *RLPipes* (the upstream processing component of our software suite). The real-world data used in the vignette is unfortunately rather large (15MB for the peaks and ~150MB for the coverage). However, I feel that, without it, the user will not have a realistic example to observe -- which I think is important since a primary purpose of RLSeq is quality assessment. I also do not think it would be possible to store this data locally within the package due to size issues. In particular, I think that the bigWig (coverage) file does not need to be downloaded or cached since there are efficient methods via `rtracklayer` (which RLSeq uses) to pull the coverage within specific genomic intervals without the need for downloading the whole file.

## R code / man pages

**Comment**

> Again also where appropriate please update to access data through the ExperimentHub so caching of data is implemented.

**Response**

Please see my previous response above.


# Other changes

Here is a short summary of additional changes made in version `0.99.7`:

1. Documentation. I have written more detailed documentation of each function and data object in RLSeq.
2. Runnable code in RLSeq vignette. The only remaining non-evaluated R code is the installation instructions and the "Quick Start" as this takes quite some time to run as it is a realistic example.
3. Minor changes. I have added some minor changes to a few functions and updated some of the language / links in the report `.Rmd` files. 
4. Removal of tests. In order to allow all parts of the vignette to run, I had to remove the `tests/` so that it would all run within the allotted 10 minute window. I think that the tests were largely redundant, however, as they cover the same functions tested by the runnable examples during CRAN checks.

**Comment by millerh1** [comment] 2021-10-15 15:34
I'm going to go ahead and add back in the automated test suite since I think it will probably still build in time and I want to remove the NOTE I'm now getting because of it.

**Comment by lshep** [comment] 2021-10-20 13:32
Thank you.  Here are some additional comments: 

**RLSeq**


**vignette**

- [ ] Might want to show `library(dplyr)` as when I got to 4.3 I couldn't run
  code if just following the shown coding chunks. 

- [ ] Do you use parallelization in your code? Interesting after running the
  vignette when I went to exit my R terminal I got the following message:
```
  > q()
Save workspace image? [y/n/c]: n
Error while shutting down parallel: unable to terminate some child processes
```
I was able to reproduce this twice. 

**R code**

**general**

- [ ] getFromNamespace is documented as not to be used in production code and
  should be avoided. What was the reasoning as its normal use case is to avoid
  warnings about using non exported functions but the RLHub package exports
  these functions already. 

- [ ] Your using a lot of functions from packages that are not specified in the
  NAMESPACE. Please import the package or select function appropriately in the
  namespace from dplyr, valr, genomeinfodb, etc. If you find you are using many
  functions from a package, the package should be in the namespace. I still
  recommend keeping all of the `::` for completeness and to avoid conflicts of
  functions names but having a more complete NAMESPACE is advisable.


**featureEnrich**

- [ ] Setting seeds without users knowledge is generally discourages if there is
  a random component that could effect reproducibility. It would be better
  practice to have the seed as an argument to the function so a user is
  aware. Also this entire section is concerning considering there is an issue
  with the function in valr that needs this "workaround". Is there a different
  package or function that could be utilized that does not have bugs?



Please fix and respond to the above concerns.  When ready please kick off a new build and request a re-review.  Thank you

**Comment by millerh1** [comment] 2021-10-21 06:06
Hi @lshep,

Thank you for the review! I will do my best to address these issues in my response 
below:

**RLSeq**

**vignette**


> * [x]  Might want to show `library(dplyr)` as when I got to 4.3 I couldn't run
>   code if just following the shown coding chunks.

Thank you for pointing this out! I have now added `library(dplyr)`.

> * [x]  Do you use parallelization in your code? Interesting after running the
>   vignette when I went to exit my R terminal I got the following message:
> 
> ```
>   > q()
> Save workspace image? [y/n/c]: n
> Error while shutting down parallel: unable to terminate some child processes
> ```
> 
> I was able to reproduce this twice.

I had not previously noticed this, but it appears that regioneR uses 
parallelization by default with > 1000 peaks. I have now updated the code to 
prevent this behavior.

**R code**
 
**general**
 
> * [x]  getFromNamespace is documented as not to be used in production code and
>   should be avoided. What was the reasoning as its normal use case is to avoid
>   warnings about using non exported functions but the RLHub package exports
>   these functions already.

Thank you for pointing this out! I have removed all uses of `getFromNamespace`.

> * [x]  Your using a lot of functions from packages that are not specified in the
>   NAMESPACE. Please import the package or select function appropriately in the
>   namespace from dplyr, valr, genomeinfodb, etc. If you find you are using many
>   functions from a package, the package should be in the namespace. I still
>   recommend keeping all of the `::` for completeness and to avoid conflicts of
>   functions names but having a more complete NAMESPACE is advisable.

I have now updated this! 


**featureEnrich**
 
> * [x]  Setting seeds without users knowledge is generally discourages if there is
>   a random component that could effect reproducibility. It would be better
>   practice to have the seed as an argument to the function so a user is
>   aware. Also this entire section is concerning considering there is an issue
>   with the function in valr that needs this "workaround". Is there a different
>   package or function that could be utilized that does not have bugs?

I have now removed the use of the `bed_shuffle` function! There are no other instances 
where seeds are used.

> Please fix and respond to the above concerns. When ready please kick off a new build and request a re-review. Thank you

**Comment by lshep** [comment] 2021-10-22 17:16
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/millerh1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RLHub")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RLHub

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment] 2021-10-22 17:16
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/millerh1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RLSeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RLSeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-10-22 17:16 UTC
Labels: OK, 3a. accepted

**Comment by millerh1** [comment] 2021-10-22 18:13
@lshep Thank you so much!!
