### ISSUE TITLE
PhosR

### ISSUE THREAD

**Issue by taiyunkim** [Bioconductor/Contributions#1538] opened 2020-06-30 01:42 UTC
- Repository: https://github.com/PYangLab/PhosR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

**Comment by mtmorgan** [comment] 2020-06-30 17:08
Consider using [SummarizedExperiment][1] for data representation; this increases robustness and interoperability of your package; the data set "phospho.cells.Ins.sample" fits directly into a SummarizedExperiment

[1]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by taiyunkim** [comment] 2020-07-08 12:23
I have updated the repository and fixed the version.

**Comment by mtmorgan** [comment] 2020-07-13 15:42
We are updating the way new packages are processed, and I am temporarily changing the status of your package.

**Comment by mtmorgan** [comment] 2020-07-13 15:46
To continue processing, your DESCRIPTION file needs to be valid. Please change https://github.com/PYangLab/PhosR/blob/master/DESCRIPTION#L5 to read `Authors@R: ` (plural Author**s**)

**Comment by taiyunkim** [comment] 2020-07-16 00:04
I have made the changes. Thank you

**Comment by lshep** [comment] 2020-07-16 14:00
I kicked off a manual build of your package which you should receive shortly.  Please see the following documentation about pushing changes to the repository to trigger new build reports.  [new package workflow](https://bioconductor.org/developers/how-to/git/new-package-workflow/).

**Comment by taiyunkim** [comment] 2020-07-16 22:52
I have checked the build report and they are with regards to the subscription mailing list and a registering to Bioconductor  support site.

```
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .
```

However, I have already subscribed to the mailing list and I am already registered to the support site.

**Comment by lshep** [comment] 2020-07-17 12:03
Is it the same email registered that is in the maintainer of the DESCRIPTION?

**Comment by taiyunkim** [comment] 2020-08-02 23:51
I am having trouble with the command line `git push upstream master`.
I get the following error.

```
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have set the public keys and I cannot manage credentials for Bioconductor git repository as this is my first Bioconductor package and I cannot activate my account at Bioconductor Gir Credentials. Would you be able to guide how to resolve this?

Thank you in advance

**Comment by nturaga** [comment] 2020-08-03 14:04
Hi, 

You first have to activate your account on BiocCredentials to be able to add SSH keys. You will receive an email from BiocCredentials (maybe it got filtered into Spam / Junk). 

Otherwise, your account seems to be set up just fine. 

Best,

Nitesh

**Comment by mtmorgan** [comment] 2020-08-03 14:41
I think though that there is a key already, from https://github.com/taiyunkim.keys. Are you using the corresponding private key when trying to reach git@git.bioconductor.org?

**Comment by LiNk-NY** [comment] 2020-08-07 21:26
Hi Taiyun, @taiyunkim 

Thank you for your submission. Please see the review below.
If you have any questions, add them in the comment box below. 

Best,
Marcel

---

# PhosR #1538

## DESCRIPTION

* Is there a proteomics `biocViews`?
* Looks good

## NAMESPACE

* Looks good

## vignettes

* I'd suggest that you keep your vignette within the 80 character width limit.
* Add an `Installation` section that shows users how to install the package using
`BiocManager`
* It looks good and thorough

## R

* Can you get the KEGG and reactome data from the internet? I am not sure you
need a serialized dataset in the package.
* Avoid copy and append methods in `selectTimes`. Although this has been
improved in R, you could use pre-allocate and fill. See the Bioconductor
guidelines https://bioconductor.org/developers/how-to/efficient-code/.
* Where possible, avoid nested `for` loops and use vectorized operations
* Avoid using `print` or `cat` in package code, use `message` for easier
suppression, consider adding a `verbose` argument to your function as well.
* It seems to me like `ptImpute` should accept something like
`SummarizedExperiment` with an annotation like `treatment` in the `colData` to
separate columns
* Should the general representation for your data be `SummarizedExperiment`
rather than a plain matrix?
* Allow users to modify parameters for plotting with `...` in plotting
functions
* It seems like functionality such as ORA is already available in Bioconductor.
Have you looked at the `EnrichmentBrowser`?
* Use more descriptive options for the `panel` argument in `plotQC`. The name
of the function would be more helpful IMO.
* Avoid using `tidyr::spread` since it is 'retired' in its lifecycle:
https://tidyr.tidyverse.org/reference/spread.html
* Provide friendlier examples to your users. This code does not seem very
new-user friendly:
```
tmp <- do.call(cbind, lapply(split(1:ncol(phospho.L6.ratio), gsub('_exp\\d+',
                            '', colnames(phospho.L6.ratio))),
                            function(i){rowMeans(phospho.L6.ratio[,i])}))
```
* Try to avoid using `1:x` sequence generation.

Minor:
* Similarly to `sapply`, `mapply` automatically reduces the output into a
simpler format, use the more robust `Map` function to obtain a predictable
result (e.g., in `createFrequencyMat`)
* Avoid evaluating to logical twice (e.g., `if (reorder == FALSE)`,
`if (scale == TRUE)` in `medianScaling`; simply use `if (reorder)`)

**Comment by LiNk-NY** [comment] 2020-08-28 22:29
Hi Taiyun, @taiyunkim 

If there is no response, we would have to close the issue for inactivity.

Best regards,
Marcel

**Comment by taiyunkim** [comment] 2020-08-29 00:52
Hi Marcel. @LiNk-NY 

Sorry for the late response. I will have the repository updated and update you with the response over the weekend.

Best regards,
Taiyun

**Comment by LiNk-NY** [comment] 2020-08-31 20:27
Hi Taiyun, @taiyunkim 
Can you bump the package `z` version? 
Thanks.

**Comment by LiNk-NY** [comment] 2020-08-31 20:31
Also, make sure to respond to the review line by line.

**Comment by taiyunkim** [comment] 2020-09-01 17:15
Hi Marcel, @LiNk-NY 

Thank you for your detailed reviews and suggestions for our package.  I have bump the package version and we have revised the package and made changes to meet your suggestions as detailed below.

## DESCRIPTION

* **Is there a proteomics biocViews?**

 Yes, we have added Proteomics to the biocViews.

## vignettes

* **I'd suggest that you keep your vignette within the 80 character width limit.**

We have kept the vignette files within the 80 character width limit except for the URL links and the YAML section which we cannot break to the next line.

* Add an Installation section that shows users how to install the package using BiocManager

We have included the `Installation` section after the `Introduction` section in the vignette.

## R

* **Can you get the KEGG and reactome data from the internet? I am not sure you need a serialized dataset in the package.**

Yes, we have included the KEGG and reactome data for purposes of reproducibility of our analysis. These data and the demonstration in our tutorials in the vignette would be used to introduce our function to the new users with reproducible results. For example, as we provide phosphosite-level over-representation analysis (ORA) using site-level annotation, we provide KEGG and reactome pathways in a similar structure to our site-level annotation data as a demonstration of the flexibility of our function.

* **Avoid copy and append methods in selectTimes. Although this has been improved in R, you could use pre-allocate and fill. See the Bioconductor guidelines https://bioconductor.org/developers/how-to/efficient-code/.**

We have corrected this `selectTimes` function to pre-allocate and fill method.

* **Where possible, avoid nested for loops and use vectorized operations**

We have changed our nested for loops to utilise vectorized operations.

* **Avoid using print or cat in package code, use message for easier suppression, consider adding a verbose argument to your function as well.**

We have changed all our `print` or `cat` functions to `message`. We also added verbose argument to those functions as suggested.

* **It seems to me like ptImpute should accept something like SummarizedExperiment with an annotation like treatment in the colData to separate columns**
    
We have allowed `ptImpute` to accept `SummarizedExperiment` object but it does not utilise `colData` to separate the columns within the function as it can be very complex and confusing when there are more than 2 treatment groups to pair. We, therefore, need the users to input two subset matrices.

* **Should the general representation for your data be SummarizedExperiment rather than a plain matrix?**

We have allowed some functions to accept `SummarizedExperiment` objects where it is possible and appropriate with examples.

* **Allow users to modify parameters for plotting with ... in plotting functions**

We have include `...` argument to allow users to modify parameters for plotting.

* **It seems like functionality such as ORA is already available in Bioconductor. Have you looked at the EnrichmentBrowser?**
    
Yes, `EnrichmentBrowser` is a package that has ORA function for gene-level of analysis. Our `pathwayOverrepresent` function is however primarily developed for phosphosite-level overrepresentation analysis. It can also be used for gene-level ORA by user-defined annotations to perform ORA. We have clarified this in the function documentation.

* **Use more descriptive options for the panel argument in plotQC. The name of the function would be more helpful IMO.**

Yes, this has been updated in the `plotQC` function.

* **Avoid using tidyr::spread since it is 'retired' in its lifecycle: https://tidyr.tidyverse.org/reference/spread.html**

Yes, we have changed all codes using `tidyr::spread` to `tidyr::pivot_wider`

* **Provide friendlier examples to your users. This code does not seem very new-user friendly:**

```r
tmp <- do.call(cbind, lapply(split(1:ncol(phospho.L6.ratio), gsub('_exp\\d+',
                            '', colnames(phospho.L6.ratio))),
                            function(i){rowMeans(phospho.L6.ratio[,i])}))
```

We have split this line down to be more new-user friendly.


* **Try to avoid using 1:x sequence generation.**

We have changed all the lines using `1:x` sequence to `seq(x)`

Minor:

* **Similarly to sapply, mapply automatically reduces the output into a simpler format, use the more robust Map function to obtain a predictable result (e.g., in createFrequencyMat)**
    
We have changed `mapply` function to the `Map` function as suggested.

* **Avoid evaluating to logical twice (e.g., if (reorder == FALSE), if (scale == TRUE) in medianScaling; simply use if (reorder))**

We have corrected all the lines that evaluate logical twice.

**Comment by LiNk-NY** [comment] 2020-09-03 23:09
Hi Taiyun, @taiyunkim 
Thank you for making those changes. 

> * Can you get the KEGG and reactome data from the internet? I am not sure you need a serialized dataset in the package.
>> Yes, we have included the KEGG and reactome data for purposes of reproducibility of our analysis. These data and the demonstration in our tutorials in the vignette would be used to introduce our function to the new users with reproducible results. For example, as we provide phosphosite-level over-representation analysis (ORA) using site-level annotation, we also provide KEGG and reactome pathways in a similar structure to our site-level annotation data as a demonstration of the flexibility and applicability of our function in gene-level ORA.

I was referring to a function that you can call to download the data from the internet _rather_ than saving a serialized version of it in your package. The serialized data may become stale without constant maintenance. Also, if you have a formal analysis that you'd like to be able to reproduce, please include that in a separate GitHub repository / package. 
Please use either `BiocSet::kegg_sets` or `KEGGREST` to download the data.

**Comment by taiyunkim** [comment] 2020-09-20 22:59
> Hi Taiyun, @taiyunkim
> Thank you for making those changes.
> 
> > * Can you get the KEGG and reactome data from the internet? I am not sure you need a serialized dataset in the package.
> > 
> > > Yes, we have included the KEGG and reactome data for purposes of reproducibility of our analysis. These data and the demonstration in our tutorials in the vignette would be used to introduce our function to the new users with reproducible results. For example, as we provide phosphosite-level over-representation analysis (ORA) using site-level annotation, we also provide KEGG and reactome pathways in a similar structure to our site-level annotation data as a demonstration of the flexibility and applicability of our function in gene-level ORA.
> 
> I was referring to a function that you can call to download the data from the internet _rather_ than saving a serialized version of it in your package. The serialized data may become stale without constant maintenance. Also, if you have a formal analysis that you'd like to be able to reproduce, please include that in a separate GitHub repository / package.
> Please use either `BiocSet::kegg_sets` or `KEGGREST` to download the data.

Hi Marcel, @LiNk-NY 
Thank you for your suggestions. I have removed the serialized pathway data and utilised the database in the Bioc for demonstrations in the vignette and the examples documentations.

**Comment by LiNk-NY** [comment] 2020-09-21 18:38
Hi Taiyun, @taiyunkim 
Please review the requirements for the `Suggests:` field. This would help in deciding whether to keep `org.Rn.eg.db` and `reactome.db` in the `Imports:` field. It appears to me that you only use these packages in the function examples; therefore, these packages should be included in the `Suggests` field.

**Comment by taiyunkim** [comment] 2020-09-22 12:08
> Hi Taiyun, @taiyunkim
> Please review the requirements for the `Suggests:` field. This would help in deciding whether to keep `org.Rn.eg.db` and `reactome.db` in the `Imports:` field. It appears to me that you only use these packages in the function examples; therefore, these packages should be included in the `Suggests` field.
> 
> https://www.bioconductor.org/developers/package-guidelines/#description

Hi Marcel, @LiNk-NY 
I have moved `org.Rn.eg.db` and `reactome.db` to the `Suggests` field as suggested.

**Comment by LiNk-NY** [comment] 2020-09-22 13:30
Looks great! Thank you for your contribution to Bioconductor!

**Comment by mtmorgan** [comment] 2020-09-25 19:33
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/taiyunkim.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PhosR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PhosR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-09-25 19:33 UTC
Labels: 3a. accepted, OK
