### ISSUE TITLE
SpatialExperiment

### ISSUE THREAD

**Issue by drighelli** [Bioconductor/Contributions#1544] opened 2020-07-07 15:18 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/drighelli/SpatialExperiment

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LTLA** [comment] 2020-07-07 17:23
Some comments from my end:

- Adding or removing "top-level" fields from `int_colData()` is dangerous; instead, use nested DFs in [Section 2.3](https://bioconductor.org/packages/devel/bioc/vignettes/SingleCellExperiment/inst/doc/devel.html#23_Using_%E2%80%9CInception-style%E2%80%9D_nesting). 
- Does `x@int_cellID` really need to exist? Why can't you just use the column names? Visium data isn't even cells, anyway.
- `spatialCoords<-` seems way more complicated than it needs to be, it should just be setting `int_colData(x)$SpatialExperiment`. What's the rationale behind the code for already-present coordinates?

**Comment by drighelli** [comment] 2020-07-09 18:11
Hi @LTLA thanks for your comments,

> Adding or removing "top-level" fields from int_colData() is dangerous; instead, use nested DFs in Section 2.3.
Thanks for pointing this out! I'll work on this!

> Does x@int_cellID really need to exist? Why can't you just use the column names? Visium data isn't even cells, anyway.
I wanted to give the possibility to the user to provide rownames or a specific column for the identifier.
I know that Visium is not "cell-centered", but it's just a variable name, I could rename it sampleID if you prefer... 

> spatialCoords<- seems way more complicated than it needs to be, it should just be setting
That's because of the int_colData "top-level" handling, once that I use your suggestion it'll be easier.

> int_colData(x)$SpatialExperiment. What's the rationale behind the code for already-present coordinates?
I just want to be sure to assign the coordinates to the right samples, what happens if some not expert user shuffles the samples? (it's just one possible situation)

**Comment by LTLA** [comment] 2020-07-10 16:28
> I know that Visium is not "cell-centered", but it's just a variable name, I could rename it sampleID if you prefer...

The exact name isn't so much the problem, the issue is that you'll have to keep it synchronized with the column names. Otherwise people could rename the columns of the SPE and wonder why their IDs are also not updated. (Normally this would not be too bad but it seems that you are treating the IDs as a special identifier field.) 

So, you would have to overwrite `colnames<-` to guarantee the column names and IDs are synchronized. You would probably also have to prohibit setting `colnames` to `NULL` as this would wipe out the ID field.

> I just want to be sure to assign the coordinates to the right samples, what happens if some not expert user shuffles the samples? (it's just one possible situation)

You might consider looking at how the base SE handles mismatches in the value's dimnames during `assay<-`. It does a check for whether the SE's dimnames are identical to the value's dimnames, and if they're not the same, it throws an error. (I can't remember whether it is more forgiving if one or the other is `NULL`.) It will not rearrange the value to fit.

I would say that it is unwise to be too intelligent in these getter/setter functions, mostly because a mismatch in the sample identities is often symptomatic of a deeper problem in the synchronization of the (meta)data. You would also be obliged to deal with duplicated sample names in an "expected" way, and I don't know what that might be.

**Comment by drighelli** [comment] 2020-07-14 09:00
Hi @Kayla-Morrell,

I think that the points discussed by @LTLA are all good points, so I was thinking to implement them before to proceed.

What do you think is best for the reviewing process?

Thanks!
Dario

**Comment by Kayla-Morrell** [comment] 2020-07-14 12:28
Hello @drighelli - 

If you think it will be a quick implementation (within a couple of weeks) then we can keep the issue open. If you want to take some time I can always tag the issue as 'Inactive' then when you are ready to start up the review process you can comment on this issue and I'll reopen it. Let me know which option works best for you.

Best,
Kayla

**Comment by drighelli** [comment] 2020-07-14 13:16
Thanks @Kayla-Morrell,

I'd be able to do the implementations in a couple of weeks, so the first choice should work!

dario

**Comment by drighelli** [comment] 2020-07-20 07:41
Hi @Kayla-Morrell ,

I updated the package and it passed all the checks :)

**Comment by Kayla-Morrell** [comment] 2020-07-23 17:35
Hello @drighelli - 

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up of less 
than 3 sentences. Please consider expanding this field, and structure it as a 
full paragraph.

- [ ] SUGGESTION: It is strongly encouraged to include the 'BugReports:' field 
with a relevant link to Github for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: Exported functions should not include '.' but use camel case or 
underscoring instead. 

## inst/script

- [ ] REQUIRED: The scripts in this directory can vary. Since data was included 
in 'inst/extdata/', a related script must be present in this directory 
documenting very clearly how the data was generated. It should include source 
urls and any important information regarding filtering or processing. It can be 
executible code, sudo code, or a text description. A user should be able to 
download the data and roughly reproduce the file or object that is present as 
data.

## Vignettes

- [ ] REQUIRED: Each vignette should have an 'Introduction' section that serves 
as an abstract to introduce the objective, models, unique functions, key points, 
etc that distinguish the package/workflow from other packages of similar type.

- [ ] REQUIRED: Each vignette should have an 'Installation' section that shows 
to users how to download and load the package from Bioconductor. The code should 
looking something like the following and inclue `eval = FALSE`,

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("SpatialExperiment")
```

*MouseCoronalVisiumAnalysis*

- [ ] REQUIRED: Line 22, you mention VisualExperiment and not SpatialExperiment.

## Man pages

- [ ] REQUIRED: For the `scaleFactors` man page, the example code doesn't 
utilize the function anywhere.

Best,
Kayla

**Comment by drighelli** [comment] 2020-07-24 13:56
Hi @Kayla-Morrell,

thanks for your revisions!

I implemented them all, but I've a point about the "inst/scripts" section.
It'd necessary in case I processed the data in some way, but I just downloaded them and stored in the package.
That's why I put a inst/extdata/README file with descriptions and links to the data sources. 

I hope this could work!

Thanks!
Dario

> ## DESCRIPTION
> * [x]  SUGGESTION: The Description field in the DESCRIPTION is made up of less
>   than 3 sentences. Please consider expanding this field, and structure it as a
>   full paragraph.
> * [x]  SUGGESTION: It is strongly encouraged to include the 'BugReports:' field
>   with a relevant link to Github for reporting Issues.
> 
> ## NAMESPACE
> * [x]  REQUIRED: Exported functions should not include '.' but use camel case or
>   underscoring instead.
> 
> ## inst/script
> * [x]  REQUIRED: The scripts in this directory can vary. Since data was included
>   in 'inst/extdata/', a related script must be present in this directory
>   documenting very clearly how the data was generated. It should include source
>   urls and any important information regarding filtering or processing. It can be
>   executible code, sudo code, or a text description. A user should be able to
>   download the data and roughly reproduce the file or object that is present as
>   data.
> 
> ## Vignettes
> * [x]  REQUIRED: Each vignette should have an 'Introduction' section that serves
>   as an abstract to introduce the objective, models, unique functions, key points,
>   etc that distinguish the package/workflow from other packages of similar type.
> * [x]  REQUIRED: Each vignette should have an 'Installation' section that shows
>   to users how to download and load the package from Bioconductor. The code should
>   looking something like the following and inclue `eval = FALSE`,
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("SpatialExperiment")
> ```
> 
> _MouseCoronalVisiumAnalysis_
> 
> * [x]  REQUIRED: Line 22, you mention VisualExperiment and not SpatialExperiment.
> 
> ## Man pages
> * [x]  REQUIRED: For the `scaleFactors` man page, the example code doesn't
>   utilize the function anywhere.
> 
> Best,
> Kayla

**Comment by Kayla-Morrell** [comment] 2020-08-03 17:20
Hello @drighelli - Thank you for making the necessary changes. The `inst/script` note was an oversight on my part. The README file should be just fine since you mention where the data is coming from. Everything looks great and I'd be more than happy to accept the package.

Best,
Kayla

**Comment by drighelli** [comment] 2020-08-03 17:38
Thanks @Kayla-Morrell !!!

**Comment by mtmorgan** [comment] 2020-08-03 20:14
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/drighelli.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpatialExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpatialExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-08-03 20:14 UTC
Labels: 3a. accepted, OK
