### ISSUE TITLE
ODER

### ISSUE THREAD

**Issue by eolagbaju** [Bioconductor/Contributions#2270] opened 2021-09-03 17:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/eolagbaju/ODER

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2] 
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment] 2021-09-16 19:13
Hi @eolagbaju 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# ODER #2270

## DESCRIPTION

* update or remove field version in `Depends: R (>= 2.10)`

## NAMESPACE

* Internal functions should not be exported (`.file_cache`) or remove the
leading period.

## vignettes

* Provide a more descriptive title. Note that keyword, "workflows", are for
workflow packages.
* Consider wrapping text to a limit of 80 column width.
* Do not provide code that does not work. `ODER` is not in Bioconductor so
`BiocManager::install("ODER")` will fail.
* Use `GenomeInfoDb::genome` instead of the one in `rtracklayer::genome`.
* Why reference the `dasper` package? Wrong package?
* Please move the code for your reference out of the main vignette ("Code for
creating the vignette"). If you'd like to keep it, perhaps include it in
`inst/scripts` or on your computer.

## R

* Keep the code within the 80 column width limit.
* Remove `dontshow` section from `R/annotatER.R`. Examples run in sequence so
you can run that code in a previous/current example and use the created object.
* Avoid using `exists` and ensure that the object exists based on above
comment.
* Some datasets need more descriptive names, "*_example" is not very helpful.
It is good practice to include study origin in the name, if possible.
* Use `message` instead of `print`.
* Avoid `1:n` sequence generation use `seq_len`/ `seq_along`
* Address `NOTE`s in `BiocCheck::BiocCheck()`
* Avoid nested `for` loops if possible.
* Do not use hardcoded values in code, e.g., `mcols(gtf)[["type"]]`. Add an
argument that lets the user specify the relevant column in the gtf file.
* Consider using the native R pipe operator `|>`.
* `ODER:::` (with triple colons) in same package code is rarely needed see
`R/ODER.R`.
* `file.exists` does not make sense for a URL in `.file_cache`. The use of
`BiocFileCache` is a bit awkward. It seems to only work for URLs and errors
out for non-existent files.

## dev/

* These files are mostly for the developer's reference and are not meant
to be part of the package.

## tests/ `covr::package_coverage`

* Please provide more coverage for your main function (`ODER`).
```
    > package_coverage()
    ODER Coverage: 66.38%
    R/ODER.R: 0.00%
    R/optimise-ERs.R: 33.12%
    R/get_expressed_genes.R: 85.29%
    R/refine-ERs.R: 85.71%
    R/annotatER.R: 86.61%
    R/rutils.R: 92.16%
    R/get_count_matrix.R: 93.75%
    R/get-coverage.R: 97.22%
    R/get-ers.R: 100.00%
    R/plot-ERs.R: 100.00%
```

**Comment by eolagbaju** [comment] 2021-10-01 16:53
Thanks very much Marcel, for taking the time to review our package ODER. We appreciate your helpful points and have attempted to address them all - see responses below: 
 
**DESCRIPTION**

- update or remove field version in Depends: R (>= 2.10)

We tried removing the field entirely but unfortunately this generated the error below. Checking, it looks as though `usethis::use_data()` [automatically adds the dependency of R (>= 2.1.0)](https://github.com/r-lib/usethis/issues/631). Furthermore, we would like `ODER` to be compatible with R (<= 4.0) as internally, our lab is still using R 4.0. In this case, we have left the dependency as R (>=2.10), would this be acceptable/what would you advise?
```bash
checking data for ASCII and uncompressed saves (482ms)
Warning: package needs dependence on R (>= 2.10)
WARNING
```
**NAMESPACE**

-  Internal functions should not be exported (.file_cache) or remove the leading period.

That is a good point, we have changed it to `file_cache` (without the “.”) now.

**vignettes**

-  Provide a more descriptive title. Note that keyword, "workflows", are for workflow packages.

We have changed the vignette title to “ODER: Optimising the Definition of Expressed Regions” and the name of the vignette file to "ODER_overview.Rmd".

-  Consider wrapping text to a limit of 80 column width.

We have done so where possible (reducing the number of problem lines from 254 to 6) but we were unable to find a solution for some of the long URLs in the vignette - e.g. line 90 includes http://master.bioconductor.org/help/course-materials/2019/BSS2019/04_Practical_CoreApproachesInBioconductor.html in the vignette. Do you have advice on how to handle situations like this? 

- Do not provide code that does not work. ODER is not in Bioconductor so BiocManager::install("ODER") will fail.

Apologies, we have now changed this to BiocManager::install(“eolagbaju/ODER”)

- Use GenomeInfoDb::genome instead of the one in rtracklayer::genome.

Done. 

- Why reference the dasper package? Wrong package?

Thanks for highlighting this, we have now changed it referencing ODER.

- Please move the code for your reference out of the main vignette ("Code for creating the vignette"). If you'd like to keep it, perhaps include it in inst/scripts or on your computer.

This code has now been removed.

**R**

- Keep the code within the 80 column width limit.

Done for all R functions

- Remove dontshow section from R/annotatER.R. Examples run in sequence so you can run that code in a previous/current example and use the created object.

Done

- Avoid using exists and ensure that the object exists based on above comment.

Through testing, the examples looked to run in alphabetical order. We tried to remove the duplicate `exists`/creation of object code for objects that were generated in the previous examples. However, this didn’t work and led to errors stating the object could not be found (can provide a minimal example of this if needed). 
 
Following this, we tried to use `describeIn` to minimize the usage of `exists`. This removed the majority of `exists` calls but some remain, as we did not want to house all function documentation in a single place. 

We would appreciate any advice on how best to resolve this.

- Some datasets need more descriptive names, "*_example" is not very helpful. It is good practice to include study origin in the name, if possible.

We have now included a more informative description of the origin within the example name e.g. gtex_SRP012682_SRX222703_lung_auc_1 so tha they include study origin and experiment identifier (derived from the `recount` R package) where appropriate. 

- Use message instead of print.

Done

- Avoid 1:n sequence generation use seq_len/ seq_along

Done

- Address NOTEs in BiocCheck::BiocCheck()

We have reduced the number of notes from 7 to 3. Of the 3 remaining; 
`NOTE: Consider shorter lines` - The character width exceeding 80 is due to the URLs in the vignette, described above. 

`NOTE: Consider multiples of 4 spaces for line indents, 44 lines(1%) are not.`. - The remaining lines that do not conform seem to be the function arguments within the `.Rd` files. When we try to manually modify these in the function definitions, calling `styler::style_pkg(transformers = biocthis::bioc_style())` reverted this back to the 2-space indent style. 

`NOTE: Update R version dependency from 2.10 to 4.1.0.` - We would really like to preserve the compatibility of `ODER` with R (<= 4.0) as this is the predominant version used by members of our lab. 
We hope that these remaining notes can be acceptable. Or please could you advise us on how you would address the issues above, thank you. 

- Avoid nested for loops if possible.

We have removed some of the nested loops in `get_ers()`. 

- Do not use hardcoded values in code, e.g., mcols(gtf)[["type"]]. Add an argument that lets the user specify the relevant column in the gtf file.

We have added a `type_col_name` argument for users to specify the gtf column name. 

- Consider using the native R pipe operator |>.

Similar to above points, we would really like to keep ODER compatible with R (<= 4.0) for internal use. 

- ODER::: (with triple colons) in same package code is rarely needed see R/ODER.R.

We have removed all instances of `ODER:::` 

- file.exists does not make sense for a URL in .file_cache. The use of BiocFileCache is a bit awkward. It seems to only work for URLs and errors out for non-existent files.

The intended use of `file_cache` is to cache URLs for faster repeated or return a path to a local file (no need to cache) if it exists. It was not designed for files that do not exist. Though we agree that this was not clear previously. With this in mind, we have now modified `file_cache` to return an informative error message when the file does not exist or is not a URL. Let us know if this is acceptable or could you please advise on how you would change this, thanks.

**dev/**

- These files are mostly for the developer's reference and are not meant to be part of the package.

These files have been removed.

**tests/**

- Please provide more coverage for your main function (ODER).

Done. The package coverage now stands at 93%. 

```
ODER Coverage: 94.07%
R/get_expressed_genes.R: 77.78%
R/annotatER.R: 80.85%
R/refine-ERs.R: 86.36%
R/rutils.R: 90.48%
R/get_count_matrix.R: 95.00%
R/get-coverage.R: 97.50%
R/get-ers.R: 100.00%
R/ODER.R: 100.00%
R/optimise-ERs.R: 100.00%
R/plot-ERs.R: 100.00%
```

Let us know if the changes we have made are sufficient. We are happy to go back and make any further edits if you think they are needed. 

Thanks again!

**Comment by dzhang32** [comment] 2021-10-04 10:03
Hi @LiNk-NY, 

I am an co-author of ODER and had a couple of questions regarding the package submission:

- @eolagbaju is moving on from our lab and the responsibility of maintaining ODER will fall to me. In this case, would it be possible to also allow me commit/push permissions for ODER on the BBS? 
- We have pushed some changes to ODER last Friday (commit id: 9a969a6da7a3754222d5f9c514aa60710a42fee9). I can see the trigger of a new build, but the build report still hasn't become available. I was wondering we have missed something here? 

Thanks, 

David

**Comment by LiNk-NY** [comment] 2021-10-05 20:00
Hi David, @dzhang32 
The first step is to update the `DESCRIPTION` file so that you are listed as the maintainer. 
I will check with Lori @lshep  and see what needs to be done on the backend for this change to
proceed. 

Note. Updates coming tomorrow.
Best,
Marcel

**Comment by lshep** [comment] 2021-10-06 11:53
@dzhang32  you should now have push access. Let us know if there are any issues.

**Comment by LiNk-NY** [comment] 2021-10-07 03:18
Thanks Lori!

@dzhang32 Please bump the version of the package for another build.

**Comment by dzhang32** [comment] 2021-10-07 11:18
Thanks a lot @LiNk-NY and @lshep! I have just made a successful push to the BBS. 

I have been trying to replicate the Windows-specific `R CMD Check ERROR` on the previous BBS build using GHA, so far without success - will check back to see the build report for this current push and try to address any ERRORs/WARNINGs that arise.

**Comment by LiNk-NY** [comment] 2021-10-07 16:05
Hi David, @dzhang32 

Thank you for making those changes. See some responses below. 

Best,
Marcel

---

> **DESCRIPTION**
> 
> * update or remove field version in Depends: R (>= 2.10)
> 
> We tried removing the field entirely but unfortunately this generated the error below. Checking, it looks as though `usethis::use_data()` [automatically adds the dependency of R (>= 2.1.0)](https://github.com/r-lib/usethis/issues/631). Furthermore, we would like `ODER` to be compatible with R (<= 4.0) as internally, our lab is still using R 4.0. In this case, we have left the dependency as R (>=2.10), would this be acceptable/what would you advise?
> 
> ```shell
> checking data for ASCII and uncompressed saves (482ms)
> Warning: package needs dependence on R (>= 2.10)
> WARNING
> ```

This field is a bit cosmetic. The package won't be available for versions < 4.1 when published in Bioconductor due to the natural restrictions imposed by `BiocManager`. I would suggest that your lab members update their version of R to the latest release to stay up to date. 

> * Consider wrapping text to a limit of 80 column width.
> 
> We have done so where possible (reducing the number of problem lines from 254 to 6) but we were unable to find a solution for some of the long URLs in the vignette - e.g. line 90 includes http://master.bioconductor.org/help/course-materials/2019/BSS2019/04_Practical_CoreApproachesInBioconductor.html in the vignette. Do you have advice on how to handle situations like this?
> 

You can leave the long URL as is. 

> * Do not provide code that does not work. ODER is not in Bioconductor so BiocManager::install("ODER") will fail.
> 
> Apologies, we have now changed this to BiocManager::install(“eolagbaju/ODER”)
> 

Thank you. It seems a bit nitpicky but the reasoning is that users looking for help with your package should always get code that is runnable. 

> * Avoid using exists and ensure that the object exists based on above comment.
> 
> Through testing, the examples looked to run in alphabetical order. We tried to remove the duplicate `exists`/creation of object code for objects that were generated in the previous examples. However, this didn’t work and led to errors stating the object could not be found (can provide a minimal example of this if needed).
>

You may need to modify the collation order. In roxygen you can use `@include R/<filename>.R`.
 
> Following this, we tried to use `describeIn` to minimize the usage of `exists`. This removed the majority of `exists` calls but some remain, as we did not want to house all function documentation in a single place.
> 
> We would appreciate any advice on how best to resolve this.

Creating a collation order would help with this. 

> * Some datasets need more descriptive names, "*_example" is not very helpful. It is good practice to include study origin in the name, if possible.
> 
> We have now included a more informative description of the origin within the example name e.g. gtex_SRP012682_SRX222703_lung_auc_1 so tha they include study origin and experiment identifier (derived from the `recount` R package) where appropriate.
> 

This is helpful. Thanks!

> `NOTE: Consider multiples of 4 spaces for line indents, 44 lines(1%) are not.`. - The remaining lines that do not conform seem to be the function arguments within the `.Rd` files. When we try to manually modify these in the function definitions, calling `styler::style_pkg(transformers = biocthis::bioc_style())` reverted this back to the 2-space indent style.
> 

I think `styler` does not allow you to change it to 4 spaces, IIRC. If you are using roxygen, those changes will be overwritten when running `devtools::document()` or similar.

**Comment by dzhang32** [comment] 2021-10-07 16:26
Thanks a lot for your feedback Marcel! All of your points make sense to me and in particular, I hadn't thought of and like the idea of using a collation order - will aim to get these changes implemented and respond in more detail within the next 1-2 days.

**Comment by dzhang32** [comment] 2021-10-08 10:30
Hi Marcel @LiNk-NY, 

I am working on using collation to permit the sharing of objects between roxygen examples. However, I am finding that it doesn't seem to work as expected. 

I have created a minimal test package to illustrate (https://github.com/dzhang32/testpackage). This creates object `a` in the `a_test.R` `@examples`, which is called by the `b_test.R` `@examples`. `b_test.R` contains an `@include a_test.R` call. However, as shown in the GHA workflow, I get the error `object 'a' not found` when running the `b_test.R` `@examples` (I can reproduce this issue locally too). 

Through googling, I can't seem find a direct answer, but it does not look like the environment is shared between roxygen examples. If this is the case, the `exists` calls in `ODER` are redundant anyway and I will remove them. However I wanted to check your thoughts first - have I missed something or understood incorrectly? 

Thanks a lot in advance, 

David

**Comment by dzhang32** [comment] 2021-10-08 11:15
With some digging, it looks like R removes the created variables between examples: https://community-bioc.slack.com/archives/C34NC134G/p1623835649094700. 

In this case, I will proceed with removing the `exists` calls.

**Comment by LiNk-NY** [comment] 2021-10-08 14:53
> I am working on using collation to permit the sharing of objects between roxygen examples. However, I am finding that it doesn't seem to work as expected.
> 
> I have created a minimal test package to illustrate (https://github.com/dzhang32/testpackage). This creates object `a` in the `a_test.R` `@examples`, which is called by the `b_test.R` `@examples`. `b_test.R` contains an `@include a_test.R` call. However, as shown in the GHA workflow, I get the error `object 'a' not found` when running the `b_test.R` `@examples` (I can reproduce this issue locally too).
> 
> Through googling, I can't seem find a direct answer, but it does not look like the environment is shared between roxygen examples. If this is the case, the `exists` calls in `ODER` are redundant anyway and I will remove them. However I wanted to check your thoughts first - have I missed something or understood incorrectly?

Hi David, @dzhang32 

After the collation order is correct, you can include `example(a_test)` in `b_test.R` to make `a` available. 
It's a bit of a hack but `R CMD check` appropriately runs the checks. 
You may get an error with `devtools::run_examples()`. 
If `a` is not too complicated, you can create `a` at the beginning of the examples for `b_test` otherwise
the `example(a_test)` should work (so long as the examples are within the time limit). 

Best, 
Marcel

**Comment by dzhang32** [comment] 2021-10-08 16:32
Hi Marcel @LiNk-NY, 

Thanks again for your advice, it's very helpful! Responses below: 

--- 

> This field is a bit cosmetic. The package won't be available for versions < 4.1 when published in Bioconductor due to the natural restrictions imposed by BiocManager. I would suggest that your lab members update their version of R to the latest release to stay up to date.

I agree with you, and have modified `ODER` to depend on R (>= 4.1) (https://github.com/eolagbaju/ODER/commit/616980ed1d741cb5cace86725414da79ef50aebb).

> After the collation order is correct, you can include example(a_test) in b_test.R to make a available.
It's a bit of a hack but R CMD check appropriately runs the checks.
You may get an error with devtools::run_examples().
If a is not too complicated, you can create a at the beginning of the examples for b_test otherwise
the example(a_test) should work (so long as the examples are within the time limit).

In the end, I removed all of the `exists` calls from the roxygen examples. These changes look to pass the BBS time limit, so have stuck with that solution (https://github.com/eolagbaju/ODER/commit/cf68a2f6617fc0b232c518f4fc3f1d1ec81c0c19 & https://github.com/eolagbaju/ODER/commit/9fa97b594b411bd52dcdd4429d10aace2b0096b0). 

I really appreciate you pointing out the `example(a_test)` hack, it's a good one to know and I'll keep it in mind for future packages, thank you! 

> I think styler does not allow you to change it to 4 spaces, IIRC. If you are using roxygen, those changes will be overwritten when running devtools::document() or similar.

Checking, it seems `devtools::document()` is the culprit, producing lines with 2-space indents (https://github.com/eolagbaju/ODER/blob/c5d3346d0701e1c028aabfe8b3ce7aace9c6a4af/man/add_expressed_genes.Rd#L8-L13) which are flagged by `BiocCheck()` as a NOTE. I am not sure how to get around this NOTE, without manually editing the `.Rd` files. If you know of any workarounds for this, I'd be happy to implement. 

In the last BBS build, the remaining 2 NOTEs are those related to the long URLs in the vignette and the `.Rd` 2-space indents. Let me know if there is anything else that you would like improved in `ODER` before it can be accepted. 

All the very best, 

David

**Comment by LiNk-NY** [comment] 2021-10-08 17:26
Hi David, @dzhang32 

Thank you for making those changes. Yes, the objects that you need in the examples
are easy to recreate so it is not worth the trouble of running the example. 

There may be an option to customize the `roxygen2` indentation but I wasn't able to
find it after a quick look. I don't think the developers allow you to make a choice.
The code that generates the usage is here: 
https://github.com/r-lib/roxygen2/blob/9ea5dd9ef9853511639bd9cdc47f0191280191b6/R/rd-usage.R#L129-L149

Thank you for your contribution. Your package has been accepted. 

Best regards,
Marcel

**Comment by dzhang32** [comment] 2021-10-08 18:19
Thanks a lot for your time and advice throughout the review process Marcel @LiNk-NY!

**Comment by lshep** [comment] 2021-10-12 17:54
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/eolagbaju.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ODER")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ODER

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-10-12 17:54 UTC
Labels: OK, 3a. accepted
