### ISSUE TITLE
MicrobiomeBenchmarkData

### ISSUE THREAD

**Issue by sdgamboa** [Bioconductor/Contributions#2791] opened 2022-10-03 19:19 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/waldronlab/MicrobiomeBenchmarkData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by Kayla-Morrell** [comment] 2022-10-18 15:40
@sdgamboa - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] REQUIRED: For packages that include data, we recommend not including
  `LazyData: TRUE`. In our experience it only slows down the loading of packages
with large data. If necessary, please provide reasoning.
- [ ] SUGGESTION: Consider adding automatically suggested biocViews:
  SequencingData.

## Data

- [ ] REQUIRED: To accompany the 'inst/extdata/' directory there needs to be an
  'inst/script/' directory that contains the documentation. The script present
in 'inst/script/' must clearly document how the data was generated and contain
source information. It should include source URLS and any key information
regarding filtering or processing. It can be executable code, sudo code, or a
text description. Users should be able to download and roughly reproduce the
file or object that is present as data in 'inst/extdata/'.
- [ ] SUGGESTION: The 'data-raw/' directory seems like it might do better in the
  'inst/script/' directory. If not please explain what these scripts are used
for since we normally don't allow this type of directory in our packages.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 6
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 6 lines that are not.

Best,
Kayla

**Comment by sdgamboa** [comment] 2022-10-26 16:46
@Kayla-Morrell, thank you! I've made the requested updates to the package. Please see below:

Updates:

+ LazyData was set to false in the DESCRIPTION file. This required the addition of a [helper function](https://github.com/waldronlab/MicrobiomeBenchmarkData/blob/df9ba8daaf7735976ea7cd5ee33de1f754efd317/R/MicrobiomeBenchmarkData.R#L234-L247)
+ Added sequencingData to BiocViews in the DESCRIPTION file.

+ Added [inst/scripts](https://github.com/waldronlab/MicrobiomeBenchmarkData/tree/main/inst/scripts) for [inst/extdata](https://github.com/waldronlab/MicrobiomeBenchmarkData/tree/main/inst/extdata).
+ data-raw directory has been removed.

+ Lines are all below 80 characters long.
+ All indents are multiples of four now.

**Comment by Kayla-Morrell** [comment] 2022-10-26 16:52
@sdgamboa - Please push a version bump to the git version of the package to trigger a new build report. See [here](https://github.com/Bioconductor/Contributions/issues/2791#issuecomment-1266933739) on how this can be done.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2022-10-26 18:25
@sdgamboa - Thank you for making those changes. I've looked them over and everything looks good. I am more than happy to accept the package.

Best,
Kayla

**Comment by sdgamboa** [comment] 2022-10-26 18:40
@Kayla-Morrell, thank you!

**Comment by lshep** [comment] 2022-10-28 15:50
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sdgamboa.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MicrobiomeBenchmarkData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MicrobiomeBenchmarkData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-10-28 15:50 UTC
Labels: OK, 3a. accepted
