### ISSUE TITLE
DeProViR

### ISSUE THREAD

**Issue by mrbakhsh** [Bioconductor/Contributions#3148] opened 2023-09-12 18:51 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mrbakhsh/DeProViR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2023-09-15 12:47
If https://nlp.stanford.edu/projects/glove/glove.6B.zip is needed,  would it make sense to [cache](https://bioconductor.org/packages/release/bioc/html/BiocFileCache.html) this file rather than redownload each time its needed?

**Comment by mrbakhsh** [comment] 2023-09-15 19:50
Hi @lshep, 
Thank you very much for the suggestion, I have already cached a file using BiocFileCache and incorporated it into my code. However, I am not sure what the issue is with the build since, on my own platform, I am able to build the package successfully without any errors or warnings. I would greatly appreciate your help in resolving this.

**Comment by lshep** [comment] 2023-09-18 12:26
My guess would be a timeout issue.  As when I try to run the code I get a timeout reached.  The default timeout for download.file is 60 seconds.
```
> zip_url <- "https://nlp.stanford.edu/data/glove.6B.zip"
>  dest_folder = tempdir()
> download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),mode = "wb")
trying URL 'https://nlp.stanford.edu/data/glove.6B.zip'
Content type 'application/zip' length 862182613 bytes (822.2 MB)
===================
downloaded 315.9 MB

Error in download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),  : 
  download from 'https://nlp.stanford.edu/data/glove.6B.zip' failed
In addition: Warning messages:
1: In download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),  :
  downloaded length 0 != reported length 0
2: In download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),  :
  URL 'https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip': Timeout of 60 seconds was reached

```
You should make note of this is the documentation. Both man pages and vignette.  You can set a timeout with `options(timeout=120)` .  Before you run your function to download, add this with appropriate note that a user should increase this to a reasonable, expected time (in seconds) for the file download to complete. 

```
> options(timeout=120)
> download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),mode = "wb")
trying URL 'https://nlp.stanford.edu/data/glove.6B.zip'
Content type 'application/zip' length 862182613 bytes (822.2 MB)
=====================================
downloaded 620.2 MB

Error in download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),  : 
  download from 'https://nlp.stanford.edu/data/glove.6B.zip' failed
In addition: Warning messages:
1: In download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),  :
  downloaded length 0 != reported length 0
2: In download.file(zip_url, destfile = file.path(dest_folder, "glove.6B.zip"),  :
  URL 'https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip': Timeout of 120 seconds was reached

```

**Comment by mrbakhsh** [comment] 2023-09-18 17:36
Hi @lshep, thank you once more for your suggestion. I included the timeout option in both the vignettes and the man files. However, I am getting a new error stating that 'con' is not recognized as a connection. I still can't reproduce this error on my own system, and the package continues to pass without any errors or warnings during the R CMD check and R CMD build.

**Comment by lshep** [comment] 2023-09-18 17:53
```
> model_training <- ModelTraining(
+       url_path = "https://nlp.stanford.edu/data",
+       training_dir = system.file("extdata/training_Set",
+                               package = "DeProViR"),
+       input_dim = 20,
+       output_dim = 100,
+       filters_layer1CNN = 32,
+       kernel_size_layer1CNN = 16,
+       filters_layer2CNN = 64,
+       kernel_size_layer2CNN = 7,
+       pool_size = 30,
+       layer_lstm = 64,
+       units = 8,
+       metrics = "AUC",
+       cv_fold = 5,
+       epochs = 100,
+       batch_size = 128,
+       plots = FALSE,
+       tpath = tempdir(),
+       save_model_weights = FALSE,
+       filepath = tempdir()) 
Error in readLines(unzip(zipfile = bfcinfo(bfc["BFC1"])$rpath, files = "glove.6B.100d.txt",  : 
  'con' is not a connection
In addition: Warning message:
In unzip(zipfile = bfcinfo(bfc["BFC1"])$rpath, files = "glove.6B.100d.txt",  :
  error 1 in extracting from zip file
```

**Comment by lshep** [comment] 2023-09-18 17:54
You also shouldn't assume that your resources is "BFC1" .  If you are using the default cache which on quick glance seems true, a user could have cached something before your file.  You will need to bfcquery to file the id that is associated with your package.

**Comment by vjcitn** [comment] 2023-09-18 22:42
This is what I am seeing in a clean environment on ubuntu with all deps satisfied, rendering the vignette:
```
> render("DeProViR_tutorial.Rmd", html_document())


processing file: DeProViR_tutorial.Rmd
  |......................                              |  43% [unnamed-chunk-2]
Would you like to create a default python environment for the reticulate package? (Yes/no/cancel) yes
  |..............................                      |  57% [unnamed-chunk-3]
Would you like to create a default python environment for the reticulate package? (Yes/no/cancel) yes
  |.....................................               |  71% [unnamed-chunk-4]
Would you like to create a default python environment for the reticulate package? (Yes/no/cancel) yes
  |.............................................       |  86% [unnamed-chunk-5]
Would you like to create a default python environment for the reticulate package?
```
This makes no sense.  Please use basilisk to manage your python usage.

**Comment by mrbakhsh** [comment] 2023-09-19 15:30
@lshep , thank you for the help; now the issue has been resolved.
@vjcitn, thanks a lot for the suggestion. But, the package has been built successfully on the macOS environment. 
I did not use any specific Python modules here to use the basilisk. Before running the package on my system, I use reticulate::use_python("~/miniforge3/envs/tf-2.6/bin/python") to specify the Python path for running DL algorithms.

**Comment by mrbakhsh** [comment] 2023-09-21 21:23
Hi @vjcitn and @lshep, can you please help me with resolving an error in the Linux environment? The package ran successfully on the macOS system. Essentially, I followed the same steps as the GenProSeq Bioconductor package.

**Comment by lshep** [comment] 2023-09-25 17:24
It looks like there is an ERROR because the path is incorrect? should be `test_Set` not `test_set`.  Linux is case sensitive (as is R code)

**Comment by hpages** [comment] 2023-09-25 17:29
Also proper use of `system.file()` is:
```
system.file("extdata", "test_Set", "test_set_unknownInteraction.csv", package = "DeProViR")
```

**Comment by mrbakhsh** [comment] 2023-09-27 21:45
Hi @lshep @hpages, thanks for the help; the package is now built with no error.

**Comment by hpages** [comment] 2023-10-11 19:43
Thanks for submitting **DeProViR** to Bioconductor.

Please name your functions consistently:
```
> ls('package:DeProViR')
[1] "encode_HostSeq"             "encode_ViralSeq"           
[3] "gloveEmb_import"            "Load_PreTrainedModel"      
[5] "load_TrainingSet"           "ModelPerformance_evalPlots"
[7] "ModelTraining"              "predInteractions"          
```
Some multipart names use the underscore (`encode_ViralSeq`), others don't (e.g. `predInteractions`). Casing is also inconsistent like in `load_TrainingSet` vs `Load_PreTrainedModel`. Please choose a style and stick to it. Bioconductor recommends the camelCase style for function names. 

The man page for one of the 2 main functions in the package (`ModelTraining()`) has no example, and the code chunk in the vignette where the function is used is not evaluated. Plus the package has no unit tests. This means that the function is never evaluated during `R CMD build` or `R CMD check`. This in turn means that we have no way to automatically detect whether the `ModelTraining()` function is working as expected or not. Note that the reason Bioconductor insists on having all user-facing functions in a package used in the examples or vignette is to allow automated quality control on the package.

Use `<-` consistently everywhere for assignment. For example, in the example below (from `?ModelPerformance_evalPlots`) you're sometimes using `=` and sometimes `<-`:
```
pred_label = seq(0,1, length.out = 100)
truth_label = rep(c(0,1), each = 50)
perf <- ModelPerformance_evalPlots(pred_label, truth_label,
tpath = tempdir())
```
Also please use proper indentation for multiple-line expressions, to make the code easier to read.

So the above code should look something like this:
```
pred_label <- seq(0,1, length.out = 100)
truth_label <- rep(c(0,1), each = 50)
perf <- ModelPerformance_evalPlots(pred_label,
                                   truth_label,
                                   tpath = tempdir())
```
Make sure to apply the same changes to all the examples and code in the package.

The Details sections in your man pages look like this:
```
Details:

     ModelPerformance_evalPlots
```
or
```
Details:

     predInteractions
```
or
```
Details:

     ModelTraining
```
etc... That is, they just repeat the name of the function! They should of course provide details about what the function does. However note that, for some of your functions, the Description section _already_ provides some of the details. So either move the details to the Details section and keep the Description section short, or remove the Details section. What you choose to do exactly will depend on each function and the amount of details that you provide.

Thanks,
H.

**Comment by lshep** [comment] 2023-11-20 14:33
@mrbakhsh Do you plan on updating the package to follow the suggestions from @hpages ?

**Comment by matineh-procogia** [comment] 2023-11-20 15:20
Hi @lshep, Yes, of course. I've already implemented all the necessary changes and plan to submit the updates by the end of this week.

**Comment by mrbakhsh** [comment] 2023-11-20 15:22
Hi @lshep. Yes, of course. I've already implemented all the necessary changes and plan to submit the updates by the end of this week.

**Comment by mrbakhsh** [comment] 2023-11-24 18:11
Hi @hpages, I have pushed the following updates.  Thank you!

# R code
- [X] Please consistently use camelCase style when naming your functions
**Answer**:
```
[1] "encodeHostSeq"             "encodeViralSeq"           
[3] "gloveImport"                  "loadPreTrainedModel"      
[5] "loadTrainingSet"            "performancePlots"
[7] "modelTraining"               "predInteractions"       
```
- [X] The man page for one of the 2 main functions in the package (ModelTraining()) has no example, and the code chunk in the vignette where the function is used is not evaluated.
**Answer**: I have included eval=TRUE for the modelTraining() function in the vignette to enable the evaluation of the code chunk in the vignette. 

# Man page
- [X] Use `<-` consistently everywhere for assignment.
**Answer:**
```
pred_label <- seq(0,1, length.out = 100)
truth_label <- rep(c(0,1), each = 50)
perf <- performancePlots(pred_label,
                         truth_label,
                         tpath = tempdir())  


```

- [X] Use proper indentation for multiple-line expressions, to make the code easier to read.
**Answer:** I have modified the examples in the man page to include correct indentation.

- [X] Either move the details to the Details section and keep the Description section short, or remove the Details section
**Answer:** I removed the @details section from the man page.

**Comment by mrbakhsh** [comment] 2023-12-14 18:23
Hi @hpages, I pushed the requested changes last month and would appreciate your feedback. Thank you, and I am looking forward to hearing from you.

**Comment by lshep** [comment] 2024-01-03 13:13
I'm very sorry for the delay; it should not be taking this long. I will check in with @hpages if he plans to revisit this review soon or reassign the reviewer if necessary

**Comment by mrbakhsh** [comment] 2024-01-03 14:58
Hi @lshep, thanks a lot for your help and for the follow-up.

**Comment by hpages** [comment] 2024-01-03 17:00
Hi @mrbakhsh, sorry for the delay. I'll take another look at the package in the next couple of days. Thanks for your patience.

**Comment by mrbakhsh** [comment] 2024-01-09 17:56
Hi @hpages, sure, that would be great. Thank you

**Comment by hpages** [comment] 2024-01-17 03:30
Hi @mrbakhsh,

Thanks for all the changes and improvements and sorry again for the delay. Package looks good and is almost ready for acceptance. Note that you still have a few places where the code is not properly indented, e.g. here:

    testing_set <- data.table::fread(
    system.file("extdata", "test_Set", "test_set_unknownInteraction.csv",
    package = "DeProViR"))

As mentioned before, this makes your code unnecessarily hard to read.

Please make sure to format/indent all your code properly.

Thanks again,
H.

**Comment by hpages** [comment] 2024-01-23 21:05
@mrbakhsh I get clean `R CMD check` and `BiocCheck()` results on my Linux laptop (Ubuntu 23.10) so I'm not sure what's happening with the SPB. Can you bump the version one more time? I know you already bumped twice in the last couple of days, sorry for that. Hopefully third time's the charm... :crossed_fingers: Thanks!

**Comment by hpages** [comment] 2024-01-24 02:57
Thank you. So at least now the package is all green on nebbiolo1. I'm investigating the vignette error on merida1. I'll let you know what I find.

**Comment by matineh-procogia** [comment] 2024-01-24 03:01
@hpages Thanks much for following up. There was a small issue with my author list names in the description, but after fixing that, I'm not encountering any errors in my Mac environment using R cmd build or R cmd check.

**Comment by hpages** [comment] 2024-01-24 03:59
I can't reproduce the vignette error on merida1. Let's ignore it.

This has not changed:
```
testing_set <- data.table::fread(
system.file("extdata", "test_Set", "test_set_unknownInteraction.csv",
package = "DeProViR"))
```
Still not properly indented/formatted! :confused: 

Again please check all your code and make sure it is properly indented/formatted.

Note that things like this are not properly indented/formatted either:
```
embeddings_index <-
gloveImport(url_path = "https://nlp.stanford.edu/data")
```

Finally: any reason why `gloveImport()` reprocess the cached file each time it's called? This processing is expensive and takes a significant amount of time. Why not process `glove.6B.zip` once for all and cache the result instead (the result is an environment that you can save to disk with `saveRDS()`).

Thanks,
H.

**Comment by mrbakhsh** [comment] 2024-02-04 21:07
Hi @hpages, apologies for the delay. I have already fixed the indentation in the man files. Thank you.

**Comment by hpages** [comment] 2024-02-07 00:39
Thanks for formatting the code. That makes it a lot easier to read and understand.

The package is good to go. Hopefully you will consider revisiting the caching approach in `gloveImport()` at some point (see my previous comment about this). It is not great software design to recompute the same thing over and over again, especially when this computation is expensive.

Thanks for your contribution to Bioconductor.

Best,
H.

**Comment by lshep** [comment] 2024-02-14 16:09
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mrbakhsh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DeProViR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DeProViR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-02-14 16:09 UTC
Labels: ERROR, 3a. accepted
