### ISSUE TITLE
MTseeker

### ISSUE THREAD

**Issue by ttriche** [Bioconductor/Contributions#911] opened 2018-10-06 00:23 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/trichelab/MTseeker

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ttriche** [comment] 2018-10-06 02:11
AdditionalPackage: https://github.com/trichelab/MTseeker

**Comment by ttriche** [comment] 2018-10-07 19:36
Reversed order of softwarePackage-dataPackage dependencies per @vobencha and @lawremi  suggestions on bioc-devel.

**Comment by lshep** [comment] 2018-10-09 13:31
Sorry -  There was an issue on our build server -  I reran the software instead of the data package -  the data package is rerunning now -

**Comment by hpages** [comment] 2018-10-23 10:32
Hi Tim,

Thanks for your submission. See my feedback below.

H.

1. As discussed previously gmapR would need to move from Imports to Suggests if you want the package to build and check on Windows once we add it to the daily builds. Also examples that require gmapR should be inside `if (.Platform$OS.type != "windows")` statements instead of being turned off on all platforms with a \donttest directive. Alternatively, you can leave gmapR in the Imports field in which case we'll mark the package as unsupported on Windows. In any case the examples making use of gmapR (like `callMT()`) should be evaluated by `R CMD check` at least on one platform (typically Linux). This is the only way to guarantee that these functions work.

2. Not sure why this problem doesn't show up on the SPB report but `R CMD build` fails to build the vignette for me:
    ```
    hpages@spectre:~/MTseeker.review$ time bdevbuild MTseeker
    * checking for file ‘MTseeker/DESCRIPTION’ ... OK
    * preparing ‘MTseeker’:
    * checking DESCRIPTION meta-information ... OK
    * installing the package to build vignettes
    * creating vignettes ... ERROR
    Quitting from lines 120-121 (oncocytomas.Rmd) 
    Error: processing vignette 'oncocytomas.Rmd' failed with diagnostics:
    could not find function "filt"
    Execution halted
    ```
    It looks like this is because the vignette actually doesn't load MTseeker (`library(MTseeker)` is in a non-evaluated code chunk).

3. After replacing `eval=FALSE` with `eval=TRUE` for the first code chunk, `R CMD build MTseeker` still gives me the following error:
    ```
    * creating vignettes ... ERROR
    Quitting from lines 120-121 (oncocytomas.Rmd) 
    Error: processing vignette 'oncocytomas.Rmd' failed with diagnostics:
    not enough space for cells at track index '5'.
    Execution halted
    ```
    Strangely I can't reproduce this error if I `R CMD Stangle` the oncocytomas.Rmd vignette and then do `source(oncocytomas.R, echo=TRUE)`. Also the SPB doesn't seem to get that error either.

4. `R CMD check` produces many "no visible binding for global variable" notes. Are you sure they can safely be ignored?

5. The man page for the MAlignments methods doesn't tell me anything about what `runLength(x)` or `runValue(x)` are about. The \value section doesn't help either:
    ```
    various things, as appropriate to the methods
    ```
    However when I call `runLength()` on the `RONKSreads` data set it seems to return the read length (as displayed by `Summary(RONKSreads))` so I wonder why this is not called `readLength()` instead of `runLength()`. The `runLength` slot of a MAlignments object should also probably be called `readLength`.

6. `runValue()` is even more mysterious:
    ```
    runValue(RONKSreads[[1]])
    [1] 16569
    ```
    This looks like the length of chrMT:
    ```
    seqlengths(RONKSreads)
    #  chrM 
    # 16569 
    ```
    Why introduce the `runValue()` getter for this? And why is it called "runValue"?

7. The examples in the man pages for the `MAlignments()`, `MAlignmentsList()`, `MVRanges()`, and `MVRangesList()` constructors should show how to use these constructors rather than showing pre-made objects of the classes returned by these constructors.

8. I notice that the classes corresponding to the 4 constructors above have their own separate man pages (with a 1-liner description of the class in them). It would make sense to merge the man page of the class with the man page of the corresponding constructor . So 4 man pages instead of 8.

9. The man page for the MVRanges methods provides very little examples. In particular it would be nice to see `locateVariants()`, `predictCoding()`, `tallyVariants()`, and `summarizeVariants()` examples.

10. It is not a good idea to override the `coverage()` method for GAlignments objects with a method for MAlignments objects that does something different. This means that all the existing code in Bioconductor that accepts a GAlignments as input (this is normally checked with `is(x, "GAlignments")`, which will also be TRUE on an MAlignments object), and that expects `coverage()` to behave the way it currently behaves on a GAlignments object, will break on an MAlignments object. Same problem with the `coverage()` method for MVRanges objects: it overrides and changes the semantic of the method for VRanges objects. An important principle in class and method design in general is to not override an existing method with a method that changes the semantic of the original method. This is easily avoided by choosing a different verb. For example in your case, it seems that what your `coverage()` methods return is the sequencing depth a.k.a. read depth. How about using `depth()` or `readDepth()` for this instead of `coverage()`? (`readDepth()` would pair nicely with `readLength()`.)

11. The Description section in `?getMT` is cluttered with occurrences of "nb." and is very cryptic:
    ```
     nb. this could probably be done faster for a list of BAMs but it's
     not nb. nb. this returns NuMT-depleted mitochondrial
     GenomicAlignments nb. nb. nb. for the time being, this function
     ONLY supports rCRS/GRCh/hg38! nb. nb. nb. nb. both chrM and
     mtGenome are now autodetected from BAM headers nb. nb. nb. nb. nb.
     in the process of converting to rCRS, chrM becomes "chrM"
    ```
    Also the example has 2 problems:
    ```
     library(MTseekerData)
     data(RONKSreads)
     
       RONKSreads <- getMT(BAMs)
      
     RONKSreads
    ```
    The call to `getMT()` is in a \donttest statement but the end-user doesn't know that so will be confused when s/he tries to run this code (e.g. with `example(getMT)`) and gets the error:
    ```
    Error in is(bam, "SummarizedExperiment") : object 'BAMs' not found
    ```

12. Overall the man page for `getMT` tells me very little about what this function does and how to use it. So I tried a shot in the dark:
    ```
    ex1_file <- system.file("extdata", "ex1.bam", package="Rsamtools")
    getMT(ex1_file)
    # Error in if (mtGenome == "other") { : 
    #  missing value where TRUE/FALSE needed
    ```
    No luck!

13. `example(callMT)` fails with the error:
    ```
    BAM file NKS_1.merged.hg19_rCRSchrm.bam does not exist
    ```

14. `?callTNMT()` has no example.

15. `?indexMtGenome` has no example.

16. Please provide more details about the `RONKSreads` and `RONKSvariants` data sets in their respective man pages. In particular explain how these objects were created. This is important for reproducibility purposes but also to give the users an example of how to proceed to generate similar objects from _their_ data.

17. The MAlignments class adds the `bam` and `runLength` slots to the GAlignments class to store the path to the orginal BAM file and the read length, respectively. Maybe a plain GAlignments object could have been used for this, with the path to the BAM file stored in the `metadata()` of the object and the read length calculated on-the-fly by the `readLength()` getter (this is fast).

18. Please avoid mixing naming styles like in `callMtVars()` and `filterMTvars()`. Use `callMTvars()` and `filterMTvars()`, or `callMtVars()` and `filterMtVars()`. Once you pick up a style, stick to it e.g. if you decide to go for `MT` (like in the name of your package) then `callTnMtVars()` should become `callTnMTvars()`, `callTNMT()` should become `callTnMT()`, etc...

19. Typo: should be "fiesty" not "feisty"

20. Would be great to add unit tests to the package.

**Comment by ttriche** [comment] 2018-10-23 12:31
These are terrific. I'll get on them. Thanks much for your effort in putting together this review, and for pointing out pileup().

I've been doubting whether overriding coverage() was the right choice ever since I did it. In fact mtCoverage() ends up doing what coverage() should do, and vice versa. So that one's a quick fix :-)

Thanks again for taking the time to create such a thorough review.

Timothy J. Triche, Jr., PhD
Assistant Professor of Bioinformatics
Van Andel Research Institute
333 Bostwick Avenue NE
Grand Rapids, MI, 49503
(616) 234-5316 (office)
(626) 375-9663 (mobile)
(616) 234-5377 (administrative, courtesy of Christie Preston)
trichelab.vai.org

________________________________________

**Comment by hpages** [comment] 2018-10-26 18:07
Hi Tim, any progress on this? Monday would be the last day for adding the package to BioC 3.8.

Thanks,
H.

**Comment by hpages** [comment] 2018-10-27 17:19
Great, thanks!

**Comment by ttriche** [comment] 2018-10-29 20:24
re: readLength getter:

R> ??readLength
No vignettes or demos or help files found with alias or concept or
title matching 'readLength' using fuzzy matching.

Google doesn't find anything either.  I may just create another helper function :-/

**Comment by ttriche** [comment] 2018-10-30 04:20
All review comments should now be addressed.  callTNMT was flaky and has been retired for now.  Windows support will have to wait for 3.9.  Examples and renaming are all done now. 
Bumping version, pushing, and hopefully moving into production.

**Comment by hpages** [comment] 2018-10-30 10:05
Great. Just in time :-)

For some reason the SPB only produced a report for the data package (MTseekerData). No report for MTseeker!

Thanks for the improvements. The vignette still fails to build for me (see item 3 in my original report). Would be nice to rename the runLength slot of the MAlignments class. Curious users that do `showClass("MAlignments")` will probably be quite confused to see a runLength slot there like for Rle objects. The error I reported in item 12 persists.

But hey we don't have time for another round of fixes so let's add the package to Bioconductor first and you'll take care of those things later.

Thanks for this new contrib.

H.

**Comment by ttriche** [comment] 2018-10-30 11:55
Thanks so much @hpages !

--t

**Comment by mtmorgan** [comment] 2018-10-30 14:38
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ttriche.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MTseeker")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MTseeker

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2018-10-30 14:38
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ttriche.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MTseekerData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MTseekerData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-10-30 14:38 UTC
Labels: 3a. accepted, ERROR
