### ISSUE TITLE
multicrispr

### ISSUE THREAD

**Issue by bhagwataditya** [Bioconductor/Contributions#1486] opened 2020-04-24 11:16 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/loosolab/multicrispr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-04-24 13:32
As preliminary comments

- Can you please expand the Description: field of the DESCRIPITION file to provide a more comprehensive abstract of your package?

- The large number of dependencies seemed surprising given the focused nature of your package. Please examine these very carefully to evaluate the trade-off between features enabled and maintenance cost.

- It never seems like a good idea to run anything as admin, so I was surprised to see the instructions to do so in the vignette. Also consider using [basilisk][] as a 'Bioconductor standard' way of enabling use of python dependencies @lgatto 
[basilisk]: https://bioconductor.org/packages/devel/bioc/html/basilisk.html

**Comment by LTLA** [comment] 2020-04-25 06:59
By and large, **basilisk** should be able to handle the Python dependencies that I can see (2.7, **azimuth**, **scikit-learn**). The main issues occur on Windows, as they typically do. The success of installation of Python 2.7 on Windows is unpredictable, and installation of Python packages via `pip` is dependent on whether non-system DLLs have found their way into the system directories.

**Comment by bhagwataditya** [comment] 2020-04-25 11:19
Thankyou Martin & Aaron,
Looking into how to integrate your recommendations. Will get back with an update soon.

**Comment by bhagwataditya** [comment] 2020-04-26 18:08
> As preliminary comments
> 
> * Can you please expand the Description: field of the DESCRIPITION file to provide a more comprehensive abstract of your package?
> * The large number of dependencies seemed surprising given the focused nature of your package. Please examine these very carefully to evaluate the trade-off between features enabled and maintenance cost.
> * It never seems like a good idea to run anything as admin, so I was surprised to see the instructions to do so in the vignette. Also consider using [basilisk][] as a 'Bioconductor standard' way of enabling use of python dependencies @LTLA
>   [basilisk]: https://bioconductor.org/packages/devel/bioc/html/basilisk.html

**Comment by bhagwataditya** [comment] 2020-04-26 18:26
Thankyou @mtmorgan and @LTLA 

I followed your recommendations and:
- updated DESCRIPTION with a more comprehensive abstract
- removed dependencies that were not strictly required
- removed the admin rights requirement (is actually only required if conda is installed under admin rights)

Regarding the failure to build: this is puzzling to me. I can successfully build it in a **win R-devel** as well as a **linux R-devel** environment, without getting the errors of the BioC machines.

Regarding basilisk: thank you for letting me know - looks interesting! That should be unrelated to the current issue of non-building, however. I have taken care in the (current) vignette to not run the python code (it's anyways only an optional last step in the whole gRNA design process). So I would prefer to first get the current vignette and package building.

Thank you for your feedback!

Aditya

@LTLA and @mtmorgan 

- basilisk looks interesting, but it should not be currently the reason why the latest build is failing. In the latest vignette, I make sure to call python only

**Comment by mtmorgan** [comment] 2020-04-26 20:50
Since the vignette is failing, I installed the package
```
multicrispr master$ bioc-devel CMD INSTALL .
```
(using R 4.0.0 and BiocManager::install(version = "devel")`, making sure `BiocManager::valid()` returns (something close to) TRUE).

I noticed that the git repository contains 'build products', i.e., the file vignettes/designing_grna_libraries.R. This file should not be present, because it will be created when the package is built. Nonetheless, I then ran 'Stangle' on the vignette to get the R code
```
multicrispr master$ cd vignettes
multicrispr/vignettes master$ bioc-devel CMD Stangle designing_grna_libraries.Rmd
```
This gave me an up-to-date version of designing_grna_libraries.R. So I started _R_ and sourced that file
```
multicrispr/vignettes master$ bioc-devel
> source("designing_grna_libraries.R", echo=TRUE)
...
> tfbs0 <- bed_to_granges(bedfile, genome = 'mm10')
	Read SRF.bed into GRanges
Error in bed$thickStart : $ operator is invalid for atomic vectors
> traceback()
12: .local(con, format, text, ...)
11: import(FileForFormat(con, format), ...)
10: import(FileForFormat(con, format), ...)
9: import(con, format = "bed", ...)
8: import(con, format = "bed", ...)
7: rtracklayer::import.bed(bedfile, genome = genome)
6: rtracklayer::import.bed(bedfile, genome = genome)
5: bed_to_granges(bedfile, genome = "mm10") at designing_grna_libraries.R#52
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("designing_grna_libraries.R", echo = TRUE)
```
digging a little more
```
> bedfile
[1] "/Users/ma38727/Library/R/4.0/Bioc/3.11/library/multicrispr/extdata/SRF.bed"
> rtracklayer::import(bedfile)
Error: $ operator is invalid for atomic vectors
```
a little more digging after `methods("import")`
```
> debug(import, signature = c("BEDFile", "ANY", "ANY"))
> rtracklayer::import(bedfile)
...
Browse[3]> next
debug: if (!is.null(bed$thickStart)) {
    thickEnd <- bed$thickEnd
    if (is.null(thickEnd))
        thickEnd <- bed$end
    bed$thick <- IRanges(bed$thickStart + 1L, thickEnd)
    bed$thickStart <- bed$thickEnd <- NULL
}
Browse[3]> next
Error in bed$thickStart : $ operator is invalid for atomic vectors
```
and the next time round
```
Browse[2]>
debug: bed <- DataFrame(read.table(con, colClasses = bedClasses, as.is = TRUE,
    na.strings = c(".", na.strings), comment.char = "", sep = sep,
    quote = ""))
Browse[2]>
debug: colnames(bed) <- bedNames[bedNames %in% colnames]
Browse[2]> class(bed)
[1] "DFrame"
attr(,"package")
[1] "S4Vectors"
Browse[2]> dim(bed)
[1] 3 1
Browse[2]> bed
DataFrame with 3 rows and 1 column
                                                                           V1
                                                                  <character>
1                                  version https://git-lfs.github.com/spec/v1
2 oid sha256:2e5c03b513ea39388a19c7b7aa3118320d644bfc81085d51a7170e2e155744a6
3                                                                  size 91414
```
which is looking kind of strange -- column is advertised as `V1` but actually
```
Browse[2]> names(bed)
[1] "chrom"
Browse[2]> bed$chrom
[1] "version https://git-lfs.github.com/spec/v1"
[2] "oid sha256:2e5c03b513ea39388a19c7b7aa3118320d644bfc81085d51a7170e2e155744a6"
[3] "size 91414"
```
and there's no `thickStart` column...
```
Browse[2]> bed$thickStart
Error in bed$thickStart : $ operator is invalid for atomic vectors
```
This seems very funky. So I confirmed that
```
BiocManager::valid()
```
returns TRUE, turned off debugging
```
> undebug(import, signature = c("BEDFile", "ANY", "ANY"))
```
and checked whether the examples on the `import.bed` help page ran...
```
example(import.bed)
```
They did run successfully. 

A first guess is that SRF.bed is malformed. Other than that, I'm at a loss, and call on @lawremi or perhaps @hpages for advice... The simple reproducible example is, in a new R session,
```
$ bioc-devel
> rtracklayer::import("multicrispr/inst/extdata/SRF.bed")
Error in bed$thickStart : $ operator is invalid for atomic vectors
```

**Comment by bhagwataditya** [comment] 2020-04-27 05:40
Thankyou Martin!

Is there a way for me to connect interactively with the BioC build machines, so that I can try to look what is failing in the bed file import and whether fixing anything in the format of SRF.bed fixes it?

Aditya
________________________________________

**Comment by bhagwataditya** [comment] 2020-04-27 05:42
Asking because I cannot reproduce the issue on rocker-devel...
________________________________________
From: Bhagwat, Aditya
Sent: Monday, April 27, 2020 7:40 AM
To: Bioconductor/Contributions; Bioconductor/Contributions
Cc: State change; Graumann, Johannes; Looso, Mario
Subject: RE: [Bioconductor/Contributions] multicrispr (#1486)

Thankyou Martin!

Is there a way for me to connect interactively with the BioC build machines, so that I can try to look what is failing in the bed file import and whether fixing anything in the format of SRF.bed fixes it?

Aditya
________________________________________

**Comment by bhagwataditya** [comment] 2020-04-27 08:26
Thankyou @mtmorgan!

Is there a way for me to connect interactively with the BioC build machines, so that I can try to look what is failing in the bed file import and whether fixing anything in the format of SRF.bed fixes it? I haven't been able to reproduce this on rocker-devel, so I could test it interactively on the Bioc machines, that would be useful.

Aditya

**Comment by bhagwataditya** [comment] 2020-04-27 09:06
Oh, this seems to be a git-lfs issue. when I vim the installed file, I get: 

    version https://git-lfs.github.com/spec/v1
    oid sha256:2e5c03b513ea39388a19c7b7aa3118320d644bfc81085d51a7170e2e155744a6
    size 91414

**Comment by mtmorgan** [comment] 2020-04-27 09:20
If these are large files then probably you should either (a) identify a (much) more modest subset for demonstrating your software or (b) make the files available via [ExperimentHub][1] as a [package][2]

[1]: https://bioconductor.org/packages/devel/ExperimentHub
[2]: https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html

**Comment by nturaga** [comment] 2020-05-14 17:10
# Review

## R CMD build

* ok 

## R CMD INSTALL

* ok

## DESCRIPTION

* ok

## NAMESPACE

* ok

## NEWS

* ok

## R

* Remove commented out code.

* Use `BiocParallel` instead of `parallel::mclapply()`.

* Are you sure you have cut down dependencies enough? There are still quite a few.

* Well written code! 

## vignette

* ok

## man

* ok

## extdata

* Just saw a .pptx file in the folder, and are you sure you want this?

**Comment by bhagwataditya** [comment] 2020-05-14 18:22
Hi Nitesh, thank you for your nice feedback :-), which I followed up on:

**R**
- I removed commented out code
- There is reason why I am using parallel::mclapply rather than BiocParallel: 
    + I first used BiocParallel::bplapply().
     That works great on linux, but it fails on windows.
    support.bioconductor.org/p/92587/ explains likely why
Windows doensn't allow forking (where a child process inherits parent env)
Instead bplapply defaults to multithreading.
In that scenario, the reticulation env is not correctly passed.
mclapply seems like best choice: fork on linux - execute serially on win
- package dependencies: I am actually really using functionality from each of these. Cutting down on dependencies would also mean cutting down on functionality. I can do this if it is really required, but it would be a pity.

**extdata**
-  :-) This ppt is not a real presentation, it's just a single slide with the "source" of the overview figure in my vignette. 

Okay then, let me push my updates

**Comment by mtmorgan** [comment] 2020-06-01 21:56
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bhagwataditya.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("multicrispr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/multicrispr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-06-01 21:56 UTC
Labels: 3a. accepted, OK
