### ISSUE TITLE
GrafGen

### ISSUE THREAD

**Issue by wheelerb** [Bioconductor/Contributions#3324] opened 2024-02-29 14:09 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wheelerb/GrafGen

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2024-03-11 15:04
thanks for this submission.  please don't put python script in exec.  you can use [basilisk](https://bioconductor.org/packages/basilisk) with `reticulate::import_from_path` to get the symbols you need with inst/python used to store your python code.  basilisk will allow you to specify all non-builtins with versions to be acquired either from pip or conda channels.  thanks

**Comment by wheelerb** [comment] 2024-03-12 19:30
Thanks for looking at the package.
Using basilisk seems very complicated, and the python script is a minor, non-essential component of the R package. I may have to remove the python script.

**Comment by wheelerb** [comment] 2024-03-13 20:41
I have updated the package by removing the python script.

**Comment by lshep** [comment] 2024-03-20 17:06
It looks like you change a users `config` with the command `config(showTips = FALSE) ` .  It is not recommended to change a users configuration. Is there a reason this is necessary?

**Comment by wheelerb** [comment] 2024-03-20 18:03
The config(showTips = FALSE) is in the code to produce interactive plots. I will try leaving it out and see if the plots are any different. Thanks.

**Comment by wheelerb** [comment] 2024-03-20 18:57
There was no change in the plots. The config(showTips = FALSE) statement has been removed.

**Comment by hpages** [comment] 2024-03-21 23:01
Thanks for this submission.

Only a few minor things that should be easy to address:

1. It's not clear how dataset `grafGen_example_results` was obtained. According to its man page it's "The returned object from `grafGen` in the analysis of a subset of the reference data." Please clarify which subset you're referring to exactly. If it's the one included in the package (in the `data.vcf.gz` file), then the problem is that calling `grafGen()` on it produces different results:
    ```
    > genoFile  <- system.file("extdata", "data.vcf.gz", package="GrafGen")
    > results <- grafGen(genoFile, print=0)
    > results$table[1:3, ]
            Sample N_SNPs    GD1_x    GD2_y     GD3_z F_percent E_percent A_percent
    1 HpGP-ALG-002  35528 1.325330 1.246303 -0.008719     27.79     72.21         0
    2 HpGP-ALG-004  35528 1.355911 1.264769  0.004511     19.76     80.24         0
    3 HpGP-ALG-005  35528 1.350071 1.267337 -0.003531     19.70     80.30         0
      hpgpAfrica hpgpAfrica-distant hpgpAfroamerica hpgpEuroamerica
    1   0.398096           0.661930        0.324232        0.276226
    2   0.429534           0.660384        0.336875        0.279032
    3   0.420432           0.655047        0.331030        0.275570
      hpgpMediterranea hpgpEurope hpgpEurasia hpgpAsia hpgpAklavik86-like
    1         0.277100   0.305868    0.395434 0.577032           0.597266
    2         0.260454   0.289007    0.380532 0.564095           0.587367
    3         0.256573   0.284675    0.379566 0.565708           0.589778
                Refpop Nearest_neighbor Separation_percent
    1  hpgpEuroamerica hpgpMediterranea               0.32
    2 hpgpMediterranea  hpgpEuroamerica               7.13
    3 hpgpMediterranea  hpgpEuroamerica               7.40
    
    > data(grafGen_example_results)
    > grafGen_example_results$table[1:3, ]
            Sample N_SNPs    GD1_x    GD2_y    GD3_z E_percent F_percent A_percent
    2 HpGP-ALG-002 143705 1.314069 1.246175 0.000711     71.12     28.88         0
    4 HpGP-ALG-004 143705 1.342173 1.262621 0.005026     78.29     21.71         0
    5 HpGP-ALG-005 143705 1.343746 1.266677 0.000658     79.49     20.51         0
      hpgpEurope hpgpAfrica hpgpAsia hpgpAfroamerica hpgpEuroamerica
    2   0.310315   0.397851 0.593879        0.325261        0.278219
    4   0.292363   0.420089 0.577689        0.333375        0.279396
    5   0.286959   0.418200 0.575399        0.330121        0.275956
      hpgpMediterranea hpgpEurasia hpgpAklavik86-like hpgpAfrica-distant
    2         0.279297    0.403331           0.608942           0.668793
    4         0.259688    0.386691           0.599314           0.660547
    5         0.255563    0.384445           0.599825           0.659308
                Refpop Nearest_neighbor Separation_percent
    2  hpgpEuroamerica hpgpMediterranea               0.39
    4 hpgpMediterranea  hpgpEuroamerica               7.59
    5 hpgpMediterranea  hpgpEuroamerica               7.98
    ```
   Please make sure that the other included datasets (`grafGen_reference_results` and `grafGen_reference_dataframe`) also match the actual results produced by **GrafGen** when running it on the full reference data (1011 genomes).

2. Would actually be nice to provide the link to the full reference data in the man page for `grafGen_reference_results` so that people can try to run **GrafGen** on it if they want.

3. Use `file.path(dir, "data.vcf.gz")` instead of `paste0(dir, .Platform$file.sep, "data.vcf.gz")` to construct a file path.

4. Use `inherits(f, "try-error")` or `!inherits(x, "grafpop")` instead of `"try-error" %in% class(f)` or `!("grafpop" %in% class(x))`.

5. Do not include the word "error" or "ERROR" in your error messages. The `stop()` function already does that for you so the message displayed to the end user contains twice the word "error":
    ```
    > stop("ERROR: invalid input")
    Error: ERROR: invalid input
    ```

6. No need to use `paste()` or `paste0()` to put together an error message because `stop()` also takes care of that for you. So instead of:
    ```
    stop(paste0("ERROR: id must be a column in ", nm))
    ```
   just do:
    ```
    stop("id must be a column in ", nm)
    ```


7. Lots of internal functions that are not used anywhere (dead code): `checkFiles`, `check_out.file`, `checkForSep`, `check.dir`, `check.list`, `check_options`, `default.list`, `pgo_interactive`, etc... A package is easier to maintain in the long run if it only contains what's actually needed and used.

8. You also have internal utilities that are defined more than once (e.g. `check_numVec`) so you might want to spend a little bit of time cleaning your R code.

Thanks,
H.

**Comment by hpages** [comment] 2024-03-21 23:14
and also:

9. The Shiny app doesn't work for me. Trying to run the code in the vignette:
    ```
    ...
    tmp <- createApp(ret)
    reference_results <- tmp$reference_results
    user_results      <- tmp$user_results
    user_metadata     <- tmp$user_metadata
    shiny::runApp(tmp$app)
    ```
   produces the following error:
    ```
    Listening on http://127.0.0.1:7828
    Warning: Error in get: object 'grafGen_reference_dataframe' not found
      39: get
      38: server
       1: shiny::runApp
    Error in get("grafGen_reference_dataframe") : 
      object 'grafGen_reference_dataframe' not found
    ```

Best,
H.

**Comment by wheelerb** [comment] 2024-03-22 11:57
Thank you for the review. I will take care of these issues.

**Comment by wheelerb** [comment] 2024-03-26 12:57
I believe all of the issues have now been taken care of. Thank you.
Bill

**Comment by hpages** [comment] 2024-03-27 00:36
Thanks! :rocket:

**Comment by lshep** [comment] 2024-03-27 13:26
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wheelerb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GrafGen")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GrafGen

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-03-27 13:26 UTC
Labels: OK, 3a. accepted
