### ISSUE TITLE
metaseqR2

### ISSUE THREAD

**Issue by pmoulos** [Bioconductor/Contributions#1435] opened 2020-03-26 16:03 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pmoulos/metaseqR2

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-03-26 17:23
@pmoulos can you explain the relationship between this package and metaseqR ? Usually it is counter-productive to have two versions of a package available. Why not just increment your existing package to version 1.99.0, 1.99.1, ... until the release, when it will become version 2.0.0 ?

**Comment by pmoulos** [comment] 2020-03-27 17:03
@mtmorgan, there is a relationship between the two packages similarly with the case of DESeq and DESeq2. metaseqR2 has some similar logic to metaseqR but it has major and breaking additions, different calculation models and severe refactoring, including changes in argument naming, exported functions and many other aspects. Therefore, it would be easier for users to educate themselves on a new, simpler in terms of usage, but at the same time richer in functionalities package, than breaking many functionalities of the previous one.

In addition to the above, here is a summary of severe changes which to my opinion justify a new package:

* The addition of normalization and statistical testing from DESeq2, ABSSeq and DSS
* A self-contained, versioned and designed for efficient integration with metaseqR2 gene annotation system, which also allows for the usage of custom annotations via GTF files (using wrappers over Bioconductor facilities)
* Support for the analysis of RNA-Seq protocols based on 3’ UTR sequencing (e.g. the Lexogen Quant-Seq kit)
* A new mode that allows for simple differential expression analysis at the transcript level
* Significant additions of diagnostic plots
* Complete redesign and rewrite of its final report using RMarkdown
* Full interactive diagnostic and explorative plots through the usage of Javascript libraries and related R packages (e.g. heatmaply)
* Generation of normalized RNA signal visualization tracks and trackhubs (suitable for visualizing stranded RNA-Seq data) for viewing in genome browsers (e.g. UCSC, IGV) and links to the UCSC Genome Browser

Therefore, my logic is to maintain both packages:
* metaseqR2 will be in active development
* metaseqR will remain stable but frozen in terms of functionality additions for users preferring this one over the new version

**Comment by mtmorgan** [comment] 2020-03-27 17:14
I suggest that you deprecate metaseqR in the devel branch immediately after the next release. See for instance the problems with DESeq in the thread here: https://support.bioconductor.org/p/129152

**Comment by pmoulos** [comment] 2020-03-27 17:25
@mtmorgan, yes this can be done. In the meanwhile, would it be a problem for the two packages to co-exist in a release? Would it pose a problem for the current submission? Thanks.

**Comment by mtmorgan** [comment] 2020-03-27 17:29
we can continue  with the current submission.

**Comment by pmoulos** [comment] 2020-04-20 14:24
Hi @Kayla-Morrell thanks for looking at the package. Is there anything else required from my side given that the upcoming release package inclusion deadline is approaching?

**Comment by Kayla-Morrell** [comment] 2020-04-20 14:28
@pmoulos - Thanks for checking in, I'm working on getting the initial review posted by the end of today. Hopefully that will be enough time for you to work on the changes and we can get it in by the deadline.

**Comment by Kayla-Morrell** [comment] 2020-04-20 22:37
Hello @pmoulos,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review. Keep in mind that the deadline for accepting new packages into the Bioconductor 3.11 release is 4/22.

## DESCRIPTION

- [ ] REQUIRED: 'LazyLoad' isn't a needed field and should be removed.

- [ ] REQUIRED: 'LazyData' should be set to false. It's out experience that when 
this is set to true it can slow down the loading of packages, especially those 
with data.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        - ATACSeq, Microarray, Metabolomics, Proteomics, Epigenetics,
        Cheminformatics, Regression, ExonArray, ChIPSeq, OneChannel,
        TwoChannel, MicroRNAArray, mRNAMicroarray, ProprietaryPlatforms,
        GeneSetEnrichment, BatchEffect

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with a 
relevant link to GitHub for reporting Issues.

## NAMESPACE

Well organized.

## CITATION

- [ ] REQUIRED: The 'mheader' for the CITATION file explains how to cite 
metaseqR. This should be changed to metaseqR2.

## Vignettes

- [ ] REQUIRED: Inline code should have single backticks \` \`, yours currently 
have three which indicates blocks of code to be run. Please change all inline 
code to single backticks.

*metaseqr2-annotation*

- [ ] REQUIRED: There should be an installation section that demonstrates to the 
user how to install the package from Bioconductor. The code should look like the 
following and should include `eval=FALSE`:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("metaseqR2")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: The last section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

- [ ] REQUIRED: I'm not able to get this vignette building locally. I hope that 
once you change the inline coding the builders will pick up the issues I'm 
experiencing. But until then I'll work more on my side to see if I can debug 
some more. (It seems to error out from line 180-238).

*metaseqr2-statistics*

- [ ] REQUIRED: There should be an installation section that demonstrates to the 
user how to install the package from Bioconductor. The code should look like the 
following and should include `eval = FALSE`:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("metaseqR2")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: Line 350, data should not be downloaded from Google Drive. The 
data should be part of the package, be coming from one of our Hubs, or from 
reliable sources.

- [ ] REQUIRED: There should not be `eval=FALSE` sections in the vignette, this 
defeats the purpose of having executable code.

- [ ] REQUIRED: The last section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

## Man pages

- [ ] REQUIRED: There needs to be runnable examples in the following man pages
which document exported object. If the example is not feasible the function 
needs to be tested somehow, where that be in a code chunk in a vignette or 
by using tests.
        - createSignalTracks.Rd
        - metaTest.Rd
        - read2count.Rd
        - readTargets.Rd
        - statBayseq.Rd

## R code

- [ ] REQUIRED: While trying to run the vignette code locally I ran into a few 
warnings that weren't shown in the vignettes themselves because you set 
`warnings=FALSE`. Please investigate the use of these functions 
`GenomeInfoDb::fetchExtendedChromInfoFromUCSC is deprecated` and 
`Specifying width/height in layout() in now deprecated`.

- [ ] REQUIRED: Unexported object imported by ':::' calls. You are not allowed 
to access non-exported functions from other packages. Either ask the maintainer 
to export the function or write your own version of it using exported functions.
        - 'GenomicFeatures:::GFF_FEATURE_TYPES'
        - 'biomaRt:::generateFilterXML'
        - 'biomaRt:::.setResultColNames'
        - 'biomaRt:::martCheck'
        - 'biomaRt:::martDataset'
        - 'biomaRt:::martHost'
        - 'biomaRt:::martVSchema'

- [ ] REQUIRED: There are ':::' calls to the package's namespace in its code. A
package almost never needs to use ':::' for its own objects:
        - '.chromInforFromBAM'
        - '.chromInfroToSeqInfoDf'
        - 'cmclapply'
        - 'getUcscOrganism'
        - 'getValidChrs'

- [ ] REQUIRED: install, biocLite, install.packages, or update.packages found in
R files. Generally you shouldn't be making a call to these functions in your code.
        - annotation.R, line 1907

- [ ] REQUIRED: Avoid sapply(); use vapply() if possible. Found in files:
        - annotation.R, lines 1240, 1298, and 1357
        - json.R, line 2189
        - main.R, lines 946, 950, 1075, and 1079
        - meta.R, lines 350 and 358
        - plot.R, lines 2057 and 2766
        - sim.R, lines 361, 388, 389, 390, 416, 416, and 418
        - stat.R, lines 14, 307, and 653
        - tracks.R, lines 99 and 222
        - util.R, lines 2968 and 2969

- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along() instead, if possible. 
Found in files:
        - annotation.R, lines 154, 215, 268, 341, 716, 738, 1162, 1222, 1279,
        1339, 1538, 1587, 1595, 1612, 1616, 1656, 1922, 2773, 2805, 2837,
        2852, 2902, 2953, 2968, 2998, 3030, 3045, 3102, 3154, 3172, and 3203
        - argcheck.R, line 6
        - count.R, lines 218, 515, 551, and 583
        - export.R, line 25
        - json.R, lines 149, 232, 407, 441, 629, 835, 867, 868, 989, 1097,
        1117, 1123, 1245, 1489, 1502, 1526, 2036, 2152, 2178, 2629, 2888,
        3242, 3245, and 3257
        - main.R, lines 788, 879, 1011, 1124, 1753, 1756, and 2095
        - meta.R, lines 94, 126, 160, 271, 312, 341, 348, and 356
        - norm.R, lines 12, 139, 166, 200, and 277
        - plot.R, lines 9, 47, 57, 192, 266, 285, 365, 366, 461, 483, 484, 522
        593, 594, 647, 649, 673, 675, 855, 904, 1257, 1275, 1317, 1318, 1457,
        1582, 1805, 1810, 1860, 1865, 1875, 2093, 2158, 2206, 2231, 2639,
        2658, 2677, 2791, 2806, 2814, 2815, 2828, 2829, 2837, 2838, 2851,
        2852, 2952, 3116, 3118, 3126, 3143, 3159, and 3160
        - reportdb.R, lines 422, 521, 538, 548, 563, 573, 601, 610, 720, 721,
        731, 732, 810, 839, 864, 873, 912, 1001, and 1017
        - sim.R, lines 12, 19, 28, 29, 56, 57, 102, 103, 125, 162, 164, 168,
        170, 183, 188, 194, 201, 207, 210, 212, 238, 249, 250, 295, 323, 329,
        346, 349, 354, 357, 359, 362, 378, and 406
        - stat.R, lines 5, 113, 265, 437, 515, 524, 556, 566, 579, 592, 603,
        613, 623, 642, 699, 781, 968, and 1284
        - tracks.R, lines 245, 262, and 274
        - util.R, lines 1588, 1613, 1621, 1638, 1647, 1670, 1738, 1832, 2805,
        2810, 2819, 2829, 2839, and 2969

- [ ] REQUIRED: We do not allow for `set.seed()` to be used in code. This 
includes using setting it as a global variable. Please remove this.

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 23 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line 
indents. There are 417 lines that are not.

Best,
Kayla

**Comment by pmoulos** [comment] 2020-04-22 12:42
Hello @Kayla-Morrell, thank you for the review. Below, points addressed, answers and some comments:

> ## DESCRIPTION
> * [X]  REQUIRED: 'LazyLoad' isn't a needed field and should be removed.
> * [X]  REQUIRED: 'LazyData' should be set to false. It's out experience that when
>   this is set to true it can slow down the loading of packages, especially those
>   with data.
> * [X]  SUGGESTION: Consider adding these automatically suggested biocViews:
>   - ATACSeq, Microarray, Metabolomics, Proteomics, Epigenetics,
>   Cheminformatics, Regression, ExonArray, ChIPSeq, OneChannel,
>   TwoChannel, MicroRNAArray, mRNAMicroarray, ProprietaryPlatforms,
>   GeneSetEnrichment, BatchEffect
> * [X]  SUGGESTION: It is encouraged to include the 'BugReports:' field with a
>   relevant link to GitHub for reporting Issues.


### Comments on DESCRIPTION
- Not all biocViews were added as the package clearly does not address them and may be misleading, specifically, Microarray, Metabolomics, Proteomics, Cheminformatics, ExonArray, OneChannel, TwoChannel, MicroRNAArray, mRNAMicroarray

> ## CITATION
> * [X]  REQUIRED: The 'mheader' for the CITATION file explains how to cite
>   metaseqR. This should be changed to metaseqR2.

### Comments on CITATION
- An article describing metaseqR2 will be submitted this week. Should I change the reference now or wait until it gets published and then update the citation in dev?

> ## Vignettes
> * [X]  REQUIRED: Inline code should have single backticks ` `, yours currently
>   have three which indicates blocks of code to be run. Please change all inline
>   code to single backticks.
> 
> _metaseqr2-annotation_
> 
> * [X]  REQUIRED: There should be an installation section that demonstrates to the
>   user how to install the package from Bioconductor. The code should look like the
>   following and should include `eval=FALSE`:
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("metaseqR2")
> ```
> 
> * [ ]  SUGGESTION: We strongly encourage the use of table of contents.
> * [X]  REQUIRED: The last section of the vignette should be 'Session Info' and
>   should include `sessionInfo()`.
> * [ ]  REQUIRED: I'm not able to get this vignette building locally. I hope that
>   once you change the inline coding the builders will pick up the issues I'm
>   experiencing. But until then I'll work more on my side to see if I can debug
>   some more. (It seems to error out from line 180-238).
> 
> _metaseqr2-statistics_
> 
> * [X]  REQUIRED: There should be an installation section that demonstrates to the
>   user how to install the package from Bioconductor. The code should look like the
>   following and should include `eval = FALSE`:
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("metaseqR2")
> ```
> 
> * [ ]  SUGGESTION: We strongly encourage the use of table of contents.
> * [X]  REQUIRED: Line 350, data should not be downloaded from Google Drive. The
>   data should be part of the package, be coming from one of our Hubs, or from
>   reliable sources.
> * [X]  REQUIRED: There should not be `eval=FALSE` sections in the vignette, this
>   defeats the purpose of having executable code.
> * [X]  REQUIRED: The last section of the vignette should be 'Session Info' and
>   should include `sessionInfo()`.


### Comments on Vignettes
- Regarding the TOC, for each vignette, a TOC is generated by the `BiocStyle`. Do you mean a TOC linking to all vignettes? How can I do that?
- I removed the example requiring to download data from Google Drive and replaced with additional external resources (GitHub wiki) for additional help on using the package.
- Regarding the vignette that you cannot build locally, the code in that particular chunk is platform-dependent. It will not run on Windows machines (but the code checks for that). Other than that, I can build it locally and it seems that the Bioconductor build system does not face an issue.


> ## Man pages
> * [X]  REQUIRED: There needs to be runnable examples in the following man pages
>   which document exported object. If the example is not feasible the function
>   needs to be tested somehow, where that be in a code chunk in a vignette or
>   by using tests.
>   - createSignalTracks.Rd
>   - metaTest.Rd
>   - read2count.Rd
>   - readTargets.Rd
>   - statBayseq.Rd


### Comments on Man pages
- A small subset of 2 real BAM files was added in `inst/extdata`. These files were the basis for creating runnable examples for createSignalTracks.Rd, read2count.Rd, readTargets.Rd.
- Runnable examples were added in metaTest.Rd and statBayseq.Rd



> ## R code
> * [X]  REQUIRED: While trying to run the vignette code locally I ran into a few
>   warnings that weren't shown in the vignettes themselves because you set
>   `warnings=FALSE`. Please investigate the use of these functions
>   `GenomeInfoDb::fetchExtendedChromInfoFromUCSC is deprecated` and
>   `Specifying width/height in layout() in now deprecated`.
> * [X]  REQUIRED: Unexported object imported by ':::' calls. You are not allowed
>   to access non-exported functions from other packages. Either ask the maintainer
>   to export the function or write your own version of it using exported functions.
>   - 'GenomicFeatures:::GFF_FEATURE_TYPES'
>   - 'biomaRt:::generateFilterXML'
>   - 'biomaRt:::.setResultColNames'
>   - 'biomaRt:::martCheck'
>   - 'biomaRt:::martDataset'
>   - 'biomaRt:::martHost'
>   - 'biomaRt:::martVSchema'
> * [X]  REQUIRED: There are ':::' calls to the package's namespace in its code. A
>   package almost never needs to use ':::' for its own objects:
>   - '.chromInfoFromBAM'
>   - '.chromInfroToSeqInfoDf'
>   - 'cmclapply'
>   - 'getUcscOrganism'
>   - 'getValidChrs'
> * [ ]  REQUIRED: install, biocLite, install.packages, or update.packages found in
>   R files. Generally you shouldn't be making a call to these functions in your code.
>   - annotation.R, line 1907
> * [X]  REQUIRED: Avoid sapply(); use vapply() if possible. Found in files: 
>   - annotation.R, lines 1240, 1298, and 1357
>   - json.R, line 2189
>   - main.R, lines 946, 950, 1075, and 1079
>   - meta.R, lines 350 and 358
>   - plot.R, lines 2057 and 2766
>   - sim.R, lines 361, 388, 389, 390, 416, 416, and 418
>   - stat.R, lines 14, 307, and 653
>   - tracks.R, lines 99 and 222
>   - util.R, lines 2968 and 2969
> * [X]  REQUIRED: Avoid 1:...; use seq_len() or seq_along() instead, if possible.
>   Found in files:
>   - annotation.R, lines 154, 215, 268, 341, 716, 738, 1162, 1222, 1279,
>   1339, 1538, 1587, 1595, 1612, 1616, 1656, 1922, 2773, 2805, 2837,
>   2852, 2902, 2953, 2968, 2998, 3030, 3045, 3102, 3154, 3172, and 3203
>   - argcheck.R, line 6
>   - count.R, lines 218, 515, 551, and 583
>   - export.R, line 25
>   - json.R, lines 149, 232, 407, 441, 629, 835, 867, 868, 989, 1097,
>   1117, 1123, 1245, 1489, 1502, 1526, 2036, 2152, 2178, 2629, 2888,
>   3242, 3245, and 3257
>   - main.R, lines 788, 879, 1011, 1124, 1753, 1756, and 2095
>   - meta.R, lines 94, 126, 160, 271, 312, 341, 348, and 356
>   - norm.R, lines 12, 139, 166, 200, and 277
>   - plot.R, lines 9, 47, 57, 192, 266, 285, 365, 366, 461, 483, 484, 522
>   593, 594, 647, 649, 673, 675, 855, 904, 1257, 1275, 1317, 1318, 1457,
>   1582, 1805, 1810, 1860, 1865, 1875, 2093, 2158, 2206, 2231, 2639,
>   2658, 2677, 2791, 2806, 2814, 2815, 2828, 2829, 2837, 2838, 2851,
>   2852, 2952, 3116, 3118, 3126, 3143, 3159, and 3160
>   - reportdb.R, lines 422, 521, 538, 548, 563, 573, 601, 610, 720, 721,
>   731, 732, 810, 839, 864, 873, 912, 1001, and 1017
>   - sim.R, lines 12, 19, 28, 29, 56, 57, 102, 103, 125, 162, 164, 168,
>   170, 183, 188, 194, 201, 207, 210, 212, 238, 249, 250, 295, 323, 329,
>   346, 349, 354, 357, 359, 362, 378, and 406
>   - stat.R, lines 5, 113, 265, 437, 515, 524, 556, 566, 579, 592, 603,
>   613, 623, 642, 699, 781, 968, and 1284
>   - tracks.R, lines 245, 262, and 274
>   - util.R, lines 1588, 1613, 1621, 1638, 1647, 1670, 1738, 1832, 2805,
>   2810, 2819, 2829, 2839, and 2969
> * [X]  REQUIRED: We do not allow for `set.seed()` to be used in code. This
>   includes using setting it as a global variable. Please remove this.
> * [X]  SUGGESTION: For formating reasons, consider shorter lines. There are 23
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
>   indents. There are 417 lines that are not.

### Comments on R code
- Regarding the warning ` GenomeInfoDb::fetchExtendedChromInfoFromUCSC is deprecated`, this is dependent on the version of Bioconductor and `GenomeInfoDb` library on a system. Given that I would prefer the package to also run on older versions of R, I wrote a non-exported wrapper functions that checks the `GenomeInfoDb` version and calls the most current function or the deprecated one in case of older versions of `GenomeInfoDb`. This wrapper is expected to go away in future releases, e.g. when `GenomeInfoDb::fetchExtendedChromInfoFromUCSC ` becomes defunct.
- Regarding the `Specifying width/height in layout() in now deprecated` warning, this comes from the `heatmaply` package and its relation to plotly (see also [here](https://github.com/talgalili/heatmaply/issues/86). At this point I cannot do much about this other than removing the offending lines (e.g. 1902 at `inst/metaseqr2_report.Rmd`) but then I can't control the size of my heatmaps which is not desired both for functional and aesthetic reasons.
- Regarding a call to `BiocManager::install()` (annotation.R, line 1907), I would like to keep this as an automation offered to the user. If a BSgenome package is missing, then instead of crashing/stopping, the function is trying to download and install it. I understand the good practices though. Would this be a particular problem in keeping it?
- Regarding the usage of `set.seed()`, I need this for some plots in the report generated by the package. I removed it from ```zzz.R``` and placed an advice in the main functionality vignette.

**Comment by pmoulos** [comment] 2020-04-22 18:03
Hi @Kayla-Morrell, any hope to look at this :-)

**Comment by Kayla-Morrell** [comment] 2020-04-22 18:24
@pmoulos - Thank you for making the necessary changes. I have just a couple follow up comments and then I should be ready to accept the package. Let me know when you are ready for me to look over these points.

> ### Comments on DESCRIPTION
> * Not all biocViews were added as the package clearly does not address them and may be misleading, specifically, Microarray, Metabolomics, Proteomics, Cheminformatics, ExonArray, OneChannel, TwoChannel, MicroRNAArray, mRNAMicroarray
> 
That's fine that you've left some out from the list. These are automatically generated from BiocCheck based on the other biocViews that are listed.
>
> ### Comments on CITATION
> * An article describing metaseqR2 will be submitted this week. Should I change the reference now or wait until it gets published and then update the citation in dev?
>
As shown in our package guidelines, the [citation](https://bioconductor.org/developers/package-guidelines/#citation) is more so for how the package should be cited. I'll let you be the judge of if you want to leave it as is or not.
> 
> ### Comments on Vignettes
> * Regarding the TOC, for each vignette, a TOC is generated by the `BiocStyle`. Do you mean a TOC linking to all vignettes? How can I do that?
> * I removed the example requiring to download data from Google Drive and replaced with additional external resources (GitHub wiki) for additional help on using the package.
> * Regarding the vignette that you cannot build locally, the code in that particular chunk is platform-dependent. It will not run on Windows machines (but the code checks for that). Other than that, I can build it locally and it seems that the Bioconductor build system does not face an issue.
> 
By adding the 'toc' in the top of the vignette code then TOC's will be put at the top of the individual vignettes (see the code below).
```output:
    BiocStyle::html_document:
        toc: true
        toc_float: true
```
>
> ### Comments on Man pages
> * A small subset of 2 real BAM files was added in `inst/extdata`. These files were the basis for creating runnable examples for createSignalTracks.Rd, read2count.Rd, readTargets.Rd.
> * Runnable examples were added in metaTest.Rd and statBayseq.Rd
> 
Thank you for adding the BAM files, there needs to be some documentation about these files. There needs to be documentation for the 'inst/extdata/' files in an 'inst/script/'. Please see our package guidelines [here](https://bioconductor.org/developers/package-guidelines/#manpages) for what to include for the documentation.

Best,
Kayla

**Comment by pmoulos** [comment] 2020-04-22 19:47
Hi @Kayla-Morrell, 
I added a `README.txt` file in `inst/script` with a description on the source of these files and addressed the TOC issue.
Hope this is OK.
Thank you for all the help.

**Comment by Kayla-Morrell** [comment] 2020-04-22 20:13
@pmoulos - Those look fine. Just one last last change that I can see. In the vignettes, line 11 (should be the same in the both files) should be:

```
%\VignetteEngine{knitr::rmarkdown}
``` 
this will help render the vignettes properly.

**Comment by pmoulos** [comment] 2020-04-22 20:27
Hi @Kayla-Morrell,
I changed the line in the vignettes.
There was an error in the last built in Linux, however I suspect that this is related to Ensembl and its reduced functionality over the past few weeks... Let's see how this built goes.
Thanks.

**Comment by mtmorgan** [comment] 2020-04-22 21:24
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pmoulos.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("metaseqR2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/metaseqR2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-22 21:24 UTC
Labels: 3a. accepted, OK
