### ISSUE TITLE
CONSTANd

### ISSUE THREAD

**Issue by PDiracDelta** [Bioconductor/Contributions#1724] opened 2020-10-20 12:11 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/PDiracDelta/CONSTANd

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by mtmorgan** [comment] 2020-10-20 13:33
I believe (from https://tldrlegal.com/license/non-profit-open-software-license-3.0-(nposl-3.0)) that your license restricts use to non-profits? Generally that is strongly discouraged; is this a requirement of your submission? If so, I would be very reluctant to consider it in Bioconductor.

**Comment by PDiracDelta** [comment] 2020-10-21 11:14
> I believe (from https://tldrlegal.com/license/non-profit-open-software-license-3.0-(nposl-3.0)) that your license restricts use to non-profits? Generally licenses that restrict usage to particular groups are strongly discouraged in Bioconductor; is this a requirement of your submission? If so, I would be very reluctant to consider it in Bioconductor.

Hi, I believe this would indeed be a requirement: we want researchers/educators to be able to conduct their research/education freely, but not allow for commercial entities to profit off of the work we did without asking us. However, I need to double-check this with 'my superiors' ...
Could you help me out a little? What aspects of such a license would make you decide to not consider our package, and what aspects would solve the issue?

**Comment by mtmorgan** [comment] 2020-10-21 12:35
Restricting use to particular groups is problematic, both practically and philosophically.

FWIW, you are profiting, academically, off the work commercial companies have provided, for instance the SummarizedExperiment infrastructure has benefitted greatly from input from commercial entities.

**Comment by Kayla-Morrell** [comment] 2020-11-02 14:58
@PDiracDelta - I will begin reviewing this package, but keep in mind I won't accept the package until all errors are cleaned up. It seems that the only ERROR currently is subscribing to the bioc-devel mailing list, once this is done this ERROR should be resolved.

Best,
Kayla

**Comment by PDiracDelta** [comment] 2020-11-02 16:52
Dear Kayla,

Perfect, thanks. I contacted the lng term maintainer, who should be
subscribed by 9 nov at the latest.

**Comment by PDiracDelta** [comment] 2020-11-10 09:36
> @PDiracDelta - I will begin reviewing this package, but keep in mind I won't accept the package until all errors are cleaned up. It seems that the only ERROR currently is subscribing to the bioc-devel mailing list, once this is done this ERROR should be resolved.
> 
> Best,
> Kayla

Hi @Kayla-Morrell , the maintainer should now be subscribed to the mailing list as well. Please let me know if there's anything else we need to do.

**Comment by Kayla-Morrell** [comment] 2020-11-20 18:48
Hello @PDiracDelta, 

Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] REQUIRED: The empty fields are not needed and should be removed, i.e.
  'Enhances'.

- [ ] REQUIRED: Update the R version dependency from 4.0 to 4.1.

- [ ] REQUIRED: It seems odd that this package doesn't depend/import any other
  Bioconductor packages. The 'Imports:' is for any packages that provide
functions, methods, or classes that are used inside the package namespace.
The 'Suggests:' are for packages used in vignettes, examples, and in
conditional code. Might some of these suggested packages belong in imports?
Just making sure this package works with our idea of interoperablity with
existing  Bioconductor classes.

- [ ] REQUIRED: The 'BugReports:' link should be a relevant link to GitHub
  Issues.

## Vignette

- [ ] REQUIRED: We don't allow anything besides the vignette files and any
  static images to be in the vignette directory. The other files in here seem
like they belong in a 'data/' or 'inst/extdata' directory. For any data that
should be exported to the user and readily available should be in the 'data/'
directory. The files in this directory require documentation in the form of man
pages. Any raw data files belong in the 'inst/extdata' directory. The
documentation for these files can go in an 'inst/script' directory. I could see
the functions file going in the 'inst/script' directory since it demonstrates
how to clean up the data. The idea is that a user should be able to download
the raw data and be able to roughly reproduce the file or object present as
data.

- [ ] SUGGESTION: I would make the library calls visible to the user so they
  know what packages to load in order to run your vignette.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

Best,
Kayla

**Comment by PDiracDelta** [comment] 2020-11-20 20:59
Thanks for reviewing, this all seems reasonable and doable. I'm a bit busy, but I will surely make the changes by december 20th.
As for this comment:
> It seems odd that this package doesn't depend/import any other Bioconductor packages.
It may sound odd but this is the case. We are happy that our method can be this 'simple' :) All you need is a matrix with numbers.

**Comment by PDiracDelta** [comment] 2020-12-16 14:27
@Kayla-Morrell  apologies, can't look it this week, but by the end of next week should be feasible.

**Comment by PDiracDelta** [comment] 2020-12-27 09:57
Hi @Kayla-Morrell I just raelized ther eis no R4.1 yet... is there? I assumed you maent R4.0.1, but apparently that isn't allowed by the R builder (non-zero patch level). Also: why can't it be R4.0? I can run it fine with that version.

**Comment by Kayla-Morrell** [comment] 2020-12-28 16:10
@PDiracDelta - New packages should be developed on the devel version of Bioconductor (which is currently 3.13). As our installation instructions state [here](https://www.bioconductor.org/install/) in order to use the devel version of Bioconductor you must also have the R version 4.1.0 which is considered the devel version of R.

**Comment by PDiracDelta** [comment] 2020-12-29 13:15
Hi again @Kayla-Morrell , installing and using R-devel was trickier than I thought but we got there :) 
I believe all necessary things are now in order - please let me know if anything's wrong.

**Comment by Kayla-Morrell** [comment] 2021-01-06 18:00
@PDiracDelta - Thank you for making the necessary changes. Everything looks good and I'm more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment] 2021-01-09 11:37
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/PDiracDelta.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CONSTANd")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CONSTANd

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2021-01-09 11:37 UTC
Labels: 3a. accepted, OK
