### ISSUE TITLE
New package `hermes`

### ISSUE THREAD

**Issue by danielinteractive** [Bioconductor/Contributions#2412] opened 2021-10-29 06:55 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/insightsengineering/hermes

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by danielinteractive** [comment] 2021-11-02 20:26
@jianhong Hi Jianhong, thx in advance for reviewing `hermes`. Do you have any tips what I can do about the build errors - they seem to come from the build system? (checks run all fine)

**Comment by lshep** [comment] 2021-11-03 11:31
The ERROR for BiocCheck is on our end and you may ignore for now. we are investigating and when it is resolved we will kick off a manual build of your package with a new report.  Cheers

**Comment by jianhong** [comment] 2021-11-03 13:01
Thank you @lshep. @danielinteractive I will start review process now and keep you updated soon.

Jianhong.

**Comment by danielinteractive** [comment] 2021-11-03 18:36
Thanks both @lshep and @jianhong ! Much appreciated :-)

**Comment by jianhong** [comment] 2021-11-14 12:52
# Package `hermes` Review

This package is in good shape but there are some issues need to be fixed.

## General package development

- [ ] `R CMD build` without errors, warnings and notes.
── Failure (test-differential.R:130:3): autoplot for HermesDataDiffExpr works as expected with custom options ──
- [ ]  Update R version dependency from 4.0 to 4.1.0. 
- [ ] unknown macro '\insertRef' found in h_diff_expr_deseq2.Rd:42, h_diff_expr_voom.Rd:43, and h_diff_expr_voom.Rd:45.
- [ ] Avoid 'suppressWarnings'/'*Messages' if possible in R/pca_cor_samplevar.R (line 52,
      column 3)
- [ ] README file contain non-ASCII characters.
- [ ] Consider to add `BiocManager::install` in README `installation` section.

## The DESCRIPTION file

- [ ] 'LazyData:' in the 'DESCRIPTION' should be set to false or removed

## The NAMESPACE file

- [ ] Function names use `camelCase` or `snake_case` and do not include `.`.

## Documentation

- [ ] Consider `BiocStyle` package for vignette formatting.
- [ ] Vignette should have an *Installation* section. Please include Bioconductor installation instructions using BiocManager.
- [ ] Table of contents in vignette is missing.
- [ ] Vignette should include `sessionInfo()`.

## R code

- [ ] `::` is not suggested in source code.
- [ ] `tryCatch` will not catch the error when non-interactive mode. Consider replace `tryCatch` with `try`

## Unacceptable files

- [ ] Please move `design` and `data-raw` to `inst` folder.
- [ ] Consider to remove _pkgdown.yml, .gitlab-ci.yml and staged_dependencies.yaml.

**Comment by danielinteractive** [comment] 2021-11-15 20:50
Thanks a lot @jianhong for your review. Please see below some questions and comments on the reported issues.

> # Package `hermes` Review
> This package is in good shape but there are some issues need to be fixed.
> 
> ## General package development
> * [ ]  `R CMD build` without errors, warnings and notes.
>   ── Failure (test-differential.R:130:3): autoplot for HermesDataDiffExpr works as expected with custom options ──

Do you have more details on the failure here? E.g. is there a log file somewhere to have a look at?

> * [ ]   Update R version dependency from 4.0 to 4.1.0.

No problem, we will do that.

> * [ ]  unknown macro '\insertRef' found in h_diff_expr_deseq2.Rd:42, h_diff_expr_voom.Rd:43, and h_diff_expr_voom.Rd:45.

Same question here re: more details.

> * [ ]  Avoid 'suppressWarnings'/'*Messages' if possible in R/pca_cor_samplevar.R (line 52,
>   column 3)

The problem here is that we want to handle fit problems in a nicer way for the user - specifically we set results
to `NA`. But we will check again if there is another way.

> * [ ]  README file contain non-ASCII characters.

No problem, we will remove them.

> * [ ]  Consider to add `BiocManager::install` in README `installation` section.

Just to confirm: This will be to say to install `hermes` from `BioConductor`, correct?

> ## The DESCRIPTION file
> * [ ]  'LazyData:' in the 'DESCRIPTION' should be set to false or removed

We have seen this note in the `BiocCheck` before already and tried to set to false or remove it. Unfortunately it did not work out in both cases. The reason is probably that we would like to supply the oackage example data directly upon package loading to the user (e.g. `hermes_data` etc.) Therefore we would like to keep as is.

> ## The NAMESPACE file
> * [ ]  Function names use `camelCase` or `snake_case` and do not include `.`.

We follow this convention actually. Note that the single `.` occurrence is `.row_data_annotation_cols` which is a constant that is exported to be able to interface with other packages with it. We chose here the `.` prefix for the constants in the package.

> ## Documentation
> * [ ]  Consider `BiocStyle` package for vignette formatting.
> * [ ]  Vignette should have an _Installation_ section. Please include Bioconductor installation instructions using BiocManager.
> * [ ]  Table of contents in vignette is missing.
> * [ ]  Vignette should include `sessionInfo()`.

No problem, we will take care of these as much as possible.

> ## R code
> * [ ]  `::` is not suggested in source code.

We had a lengthy discussion within our development team regarding this. The final conclusion was that it is more elegant and readable to access required functions etc. from other namespaces with `::` while importing those packages - the reason is that we 1) don't need to copy these functions to our namespace and 2) that the origin is clearly visible when reading the code. Also, this is permissible as per `R CMD check` and `BiocCheck` and has worked for us well also in other, complex, packages. Therefore we would ask to keep the code as is. 

> * [ ]  `tryCatch` will not catch the error when non-interactive mode. Consider replace `tryCatch` with `try`

Thanks we will look into this.

> 
> ## Unacceptable files
> * [ ]  Please move `design` and `data-raw` to `inst` folder.

We would like to not move them to the `inst` folder as these should not be installed together with the R-package. As indicated by `.Rbuildignore` these should not be part of the built package and thus not installed. They are only relevant for developers working on the package code itself.

> * [ ]  Consider to remove _pkgdown.yml, .gitlab-ci.yml and staged_dependencies.yaml.

Unfortunately this is not possible as it would break our upstream automation setup, i.e., we would need to completely fork this repository which would not be ideal.

Thanks again for your time and thanks in advance for your response.

**Comment by jianhong** [comment] 2021-11-15 21:52
> > # Package `hermes` Review
> > This package is in good shape but there are some issues need to be fixed.
> > ## General package development
> > 
> > * [ ]   `R CMD build` without errors, warnings and notes.
> >   ── Failure (test-differential.R:130:3): autoplot for HermesDataDiffExpr works as expected with custom options ──
> 
> Do you have more details on the failure here? E.g. is there a log file somewhere to have a look at?
This is the output I got:
  * Run `testthat::snapshot_review('differential')` to review changes
  Backtrace:
      █
   1. └─vdiffr::expect_doppelganger(...) test-differential.R:130:2
   2.   ├─base::withCallingHandlers(...)
   3.   └─testthat::expect_snapshot_file(...)

This maybe caused by my environment. If the package can pass the building system, you can leave it.

> > * [ ]   unknown macro '\insertRef' found in h_diff_expr_deseq2.Rd:42, h_diff_expr_voom.Rd:43, and h_diff_expr_voom.Rd:45.
> 
> Same question here re: more details.

No worry in current stage. This may be the issue of BiocCheck.

> > * [ ]   Consider to add `BiocManager::install` in README `installation` section.
> 
> Just to confirm: This will be to say to install `hermes` from `BioConductor`, correct?

Yes

> > ## R code
> > 
> > * [ ]   `::` is not suggested in source code.
> 
> We had a lengthy discussion within our development team regarding this. The final conclusion was that it is more elegant and readable to access required functions etc. from other namespaces with `::` while importing those packages - the reason is that we 1) don't need to copy these functions to our namespace and 2) that the origin is clearly visible when reading the code. Also, this is permissible as per `R CMD check` and `BiocCheck` and has worked for us well also in other, complex, packages. Therefore we would ask to keep the code as is.

I agree with you that keeping it will make it readable and I am just following the review guideline. You can keep the `::` and make sure the packages are imported.

> > ## Unacceptable files
> > 
> > * [ ]   Please move `design` and `data-raw` to `inst` folder.
> 
> We would like to not move them to the `inst` folder as these should not be installed together with the R-package. As indicated by `.Rbuildignore` these should not be part of the built package and thus not installed. They are only relevant for developers working on the package code itself.
> 
> > * [ ]   Consider to remove _pkgdown.yml, .gitlab-ci.yml and staged_dependencies.yaml.
> 
> Unfortunately this is not possible as it would break our upstream automation setup, i.e., we would need to completely fork this repository which would not be ideal.

I suggest you to create a new branch to hold those files and make the package clean.

**Comment by danielinteractive** [comment] 2021-11-16 10:39
Thanks @jianhong for your quick reply, I now pushed an update which resolves all issues as we aligned above.

**Comment by danielinteractive** [comment] 2021-11-17 08:22
@jianhong not sure why I cannot join the bioc-devel mailing list. I applied now twice already for it.
This is the only error in the build logs.

**Comment by jianhong** [comment] 2021-11-18 13:17
@danielinteractive no worry about the mailing list. This happened many times. I will ignore it in current stage. But make sure you will get email from the bioc-devel mailing list and also sign up in the [support site](https://support.bioconductor.org/)

**Comment by danielinteractive** [comment] 2021-11-18 13:21
thx @jianhong - I am not sure, it seems so far I did not receive any mails from the bioc-devel mailing list. 
I signed up already on the support site though.

**Comment by danielinteractive** [comment] 2021-11-23 19:58
@jianhong what would be the next step? is anything remaining in terms of review? thx!

**Comment by jianhong** [comment] 2021-11-23 20:03
Sorry for the delay. I am a little busy recently. I will submit the review soon.

**Comment by jianhong** [comment] 2021-11-23 20:21
@danielinteractive great progress. Only one thing left. Please consider to fix the `tryCatch` in `normalization.R` line 241. Once you got fixed, it is ready to accept.

**Comment by danielinteractive** [comment] 2021-11-23 20:26
@jianhong thx for having a look - I actually tested that separately, by running a script non-interactively (with `Rscript`) and it actually did work as in interactive mode. So I don't think this is a problem. (Also I looked up and understand that `try` is using `tryCatch` internally - so seems any deficiency `tryCatch` would potentially have also is inherited by `try`.) Or did I miss something?

**Comment by jianhong** [comment] 2021-11-23 21:10
@danielinteractive Oh, R already fixed this issue. Thank you for the message.

**Comment by danielinteractive** [comment] 2021-11-24 08:31
Great, thanks @jianhong - as this is my first Bioconductor package, naive question: will `hermes` then appear soon at http://bioconductor.org/packages/devel/bioc/ ?

**Comment by lshep** [comment] 2021-11-24 11:39
I'll process the packages later today. Once that happens it should appear within 48 hours

**Comment by lshep** [comment] 2021-11-24 12:20
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/danielinteractive.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("hermes")`. The package 'landing page' will be created at

https://bioconductor.org/packages/hermes

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-11-24 12:20 UTC
Labels: ERROR, 3a. accepted
