### ISSUE TITLE
MBECS

### ISSUE THREAD

**Issue by rmolbrich** [Bioconductor/Contributions#2497] opened 2022-01-14 19:10 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rmolbrich/MBECS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

**Comment by vjcitn** [comment] 2022-01-18 12:28
Vignette has no content.  Please revise and comment here when repo is appropriately populated and passes R CMD check.

**Comment by vjcitn** [comment] 2022-01-22 11:54
Please respond.

**Comment by rmolbrich** [comment] 2022-01-24 10:41
Hello,

the vignette escaped me, I am sorry for that. I spend time writing it and had a colleague do some more testing of the functionality of the package. 

- It just passed CMD build and check with the subsequent status messages. 
- BiocCheckGitClone passed
- BiocCheck produces the error "Maintainer must register at the support site; visit https://support.bioconductor.org/accounts/signup/ ." which seems to be some artefact, since I am registered.

Terminal output:
(base) Michaels-MBP:packagespace.new molbrich$ R CMD build MBECS
* checking for file ‘MBECS/DESCRIPTION’ ... OK
* preparing ‘MBECS’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘MBECS_0.99.5.tar.gz’

(base) Michaels-MBP:packagespace.new molbrich$ R CMD check MBECS_0.99.5.tar.gz
* using log directory ‘/MBECS.Rcheck’
* using R version 4.1.2 (2021-11-01)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘MBECS/DESCRIPTION’ ... OK
* this is package ‘MBECS’ version ‘0.99.5’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘MBECS’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
mbecMixedVariance: no visible binding for global variable ‘.’
mbecModelVariancePVCA: no visible binding for global variable ‘.’
mbecMosaic: no visible binding for global variable ‘Freq’
mbecMosaicPlot: no visible binding for global variable ‘Var1’
mbecMosaicPlot: no visible binding for global variable ‘Freq.scaled’
mbecMosaicPlot: no visible binding for global variable ‘Var2’
mbecPVCAStatsPlot: no visible binding for global variable ‘type’
mbecPVCAStatsPlot: no visible binding for global variable ‘covariate’
mbecPVCAStatsPlot: no visible binding for global variable ‘variance’
mbecPVCAStatsPlot: no visible binding for global variable ‘variance.p’
mbecRDAStatsPlot: no visible binding for global variable ‘type’
mbecRDAStatsPlot: no visible binding for global variable ‘variance’
mbecRDAStatsPlot: no visible binding for global variable ‘covariate’
mbecRDAStatsPlot: no visible binding for global variable ‘variance.r’
mbecRLE: no visible binding for global variable ‘.’
mbecRLE: no visible global function definition for ‘everything’
mbecRLE: no visible binding for global variable ‘plot.order’
mbecRLE: no visible binding for global variable ‘specimen’
mbecRLEPlot: no visible binding for global variable ‘specimen’
mbecRLEPlot: no visible binding for global variable ‘values’
mbecSCOEFStatsPlot: no visible binding for global variable ‘variable’
mbecSCOEFStatsPlot: no visible binding for global variable ‘type’
mbecSCOEFStatsPlot: no visible binding for global variable
  ‘sil.coefficient’
mbecSCOEFStatsPlot: no visible binding for global variable ‘cluster’
mbecVarianceStatsLM: no visible binding for global variable ‘.’
mbecVarianceStatsPlot: no visible binding for global variable ‘type’
mbecVarianceStatsPlot: no visible binding for global variable
  ‘variance’
mbecVarianceStatsPlot: no visible binding for global variable
  ‘covariate’
Undefined global functions or variables:
  . Freq Freq.scaled Var1 Var2 cluster covariate everything plot.order
  sil.coefficient specimen type values variable variance variance.p
  variance.r
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking LazyData ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘mbecs_vignette.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
See
  ‘/MBECS.Rcheck/00check.log’
for details.


Best,
Michael

**Comment by rmolbrich** [comment] 2022-02-08 16:42
Hi,

I would like to request some help at this point. I fixed the errors that produced the timeout, but the issue of not being recognized as registered at the support forum remains. I have been registered for three months now. I attached a screenshot of my profile at support.bioconductor.org. I also included the name of my package in the watched tags. It is not obvious to me what else I am supposed to do.

Best
<img width="1039" alt="BiocSupportProfile" src="https://user-images.githubusercontent.com/83829168/153023451-23e5b7d6-b925-4486-9ec6-8b7666817cab.png">

**Comment by lshep** [comment] 2022-02-08 16:45
I will look into the support site error for you.  @HelenaLC  ignore this ERROR for now and proceed with review; I will post when I know more.

**Comment by HelenaLC** [comment] 2022-02-09 06:34
Here's a first round of comments to consider... Note that many of these are suggestions and not strictly required (e.g., "consider..."). Please comment back here with what has been addressed or any comments regarding any needed clarification or questions you might have. Cheers!

# README

- [ ] Please include Bioconductor installation instructions using `BiocManager`.

# NEWS

- [ ] Missing; consider adding a NEWS files.

# DESCRIPTION

- [ ] We would encourage an R dependency of >= 4.2.

- [ ] We recommend `lazyData: false` as setting it to `true`  
is rarely useful and could slow package installation.

- [ ] Consider adding a `URL:` field pointing to the code repo,  
and a `BugReports:` field for reporting issues (e.g., to Github)

- [ ] Nearly all packages used are currently under `suggests:`  
but are required by many exported functions. This means that  
most functions will break down when users install `MBECS`  
(without manually installing all suggested packages).  
Any packages required for key functionality should go in `depends:`,  
while those that aren't "key" or only used in the vignette can go in `suggests`.  
If you feel that some of the package's functionality aren't relevant  
in the majority of cases, another option would be to check in the  
corresponding functions if all dependencies are available, stop execution,  
and to given an informative warning when they are not. Otherwise, functions  
might start running and fail at some point due to a missing dependency.

# documentation

- [ ] Consider adding a package *.man* page (i.e., `?MBECS`)  
so users would be directed to the main functions of the package.

- [ ] In the corresponding man pages (in `data.R`), please add details    
on how the toy data were generated (perhaps the code for this?),  
or on the source information for data that is not synthetic.

# R/

- [ ] consider having a look at some of coding style guidelines [here](https://bioconductor.org/developers/how-to/coding-style/)  
While these are *recommendations*, it's nice to be consistent.  
E.g., we recommend 4 space tab indentation (instead of vertical alignment)  
and keeping to a 80 character limit. Some code is currently difficult to read  
mostly because indentation is inconsistent and produces a lot of white space.

- [ ] Both functions in `mbecs_reports.R` currently create outputs  
in the current working directory with a fixed file name.  
Would it be possible to expose arguments to the user to specify both?  
(I.e., `output_dir/file` with default `getwd()/NULL`, respectively.)

- [ ] (Found this by running the unevaluated chunks in the vignette...)  
`mbecReportPost` in `mbecs_reports` will currently fail due to a typo;  
`input.ob <- mbecProcessInput(input.ob, model.vars)` should be `input.obj`.  

- [ ] Avoid the use of `sapply` (use `vapply` instead) in `mbecs_plots.R`,  
and of `1:...` (use `seq_len/along` instead) in `mbecs_analyses.R`;  
see the corresponding build report NOTEs.

# vignette

- [ ] To highlight / distinguish code from normal text,  
you can use back-ticks instead of single quotation. E.g.,  
"[...] the 'library' function" with \`s gives `library`

- [ ] Type in the "Usage_mosaic" chunk comment: distrubuted > distributed

- [ ] Especially in the vignette, try to keep to an 80 character limit  
as the code will otherwise be difficult to read when displayed online.  
E.g., could add linebreaks after function arguments when they are very long.

# tests/

- [ ] Coverage looks pretty good; nice job! Would it be possible  
to add some for the function in `mbecs_reports.R` (currently 0%)?  
Both `mbecReportPrelim` and `mbecReportPost` provide the option  
to return the generated plot list (when `return.data = TRUE`);  
could these be used to test that they work as intended?

```
# devtools::test_coverage()
MBECS Coverage: 82.09%
R/mbecs_reports.R: 0.00%
R/mbecs_corrections.R: 59.60%
R/mbecs_classes.R: 79.11%
R/mbecs_helper.R: 89.25%
R/mbecs_analyses.R: 90.16%
R/mbecs_plots.R: 99.53%
```

**Comment by rmolbrich** [comment] 2022-02-10 16:03
Thank you, I am working on it.

**Comment by rmolbrich** [comment] 2022-02-17 17:13
I aimed to address all the mentioned points and think that the package is better for it now. 

I hope that the following points are acceptable.
- There are still 9 lines longer than 80 characters, which are 0% of the code so I assume this is negligible.
- 667 lines don't adhere to 4 space indentation rule due to line-breaks in between function parameters
- And I kept the dependence on R >= 4.1 partly because it would be inconvenient for my colleagues to install the devel version of R in order to test/use the package, but honestly mostly because I gave up on trying to make vegan compile on my machine.

The error in compiling the package occurs due to the misperception of my support site registration. 

Best,

Michael

**Comment by HelenaLC** [comment] 2022-02-21 09:14
Jup, the character limits, indentation and your preference to keep R >= 4.1 as a dependency are all acceptable. Here some more comments with special apologies for the 1st point - my mistake...

# DESCRIPTION

- I am *very* sorry, but made an accidental mistake in writing my earlier comment regarding `Suggests/Depends/Imports`... There's a NOTE by `R CMD check` stating `Depends: includes the non-default packages:`. In fact, `Depends:` should (in your case), only list `R (>= 4.1)`; all else should go under `Imports:`; if you'd like to make some functionality optional, related packages go under `Suggests:` (e.g., `knitr`, `(r)markdown` for generating reports could be made optional).  
The difference is that anything in `Depends:` will be loaded *in full* when `MBECS` is loaded; we don't want this. Instead, it is advisable to do *selective* importing of the functions you use (e.g., using `roxygen2`'s `@importFrom`). Please have a look at the guidelines [here](http://contributions.bioconductor.org/description.html#depends-imports-suggests-enhances).

- Related to the above, by using selective imports, it is rarely necessary to use `package::function`. E.g., in `mbecRUV2`, one could do `@importFrmo ruv RUV2` in the `roxygen2` header, and use `tmp.ruv2 <- RUV2(...)` in the function definition. Especially for `ggplot` this would cut down on 100s of characters and greatly improve readability.

- Consider expanding on your `biocViews:` to increase the package's findability; some suggestions are given in the `BiocCheck` report. 

# code 

- You can get rid of all the `no visible binding for global variable` NOTEs related to plotting functions by using `aes_string` instead of `aes`. E.g., `ggplot(..., aes(x, y)) -> ggplot(..., aes_string("x", "y"))`.

- In `mbecCorrection()`, could you move the `choices` of `match.arg` to the `method` argument in the function definition? I.e., `mbecCorrection <- function(..., method = c("lm", ...))`. That way, users can more easily see available methods in the usage section of the documentation, and `match.arg` will automatically do the job, i.e., you can use `method <- match.arg(method)` inside the function. Same for anywhere else where there's a fixed character vector of choices, e.g. `mbecSVA`.

- The plots are all really nice! Just wondering - are the gray boxes produced by `mbecBoxPlot` in the bottom-left & -right corners intentional? 

<img width="463" alt="image" src="https://user-images.githubusercontent.com/14542264/154924390-ce5ac059-dc28-45c3-bf2e-5bf2f1775391.png">

- Regarding plot-arrangement in general, have you considered using `patchwork` or `cowplot`? These provide options to automatically "collect" legends at the bottom or right of multi-panel figures, and would elevate the pain of extracting, removing, adding back & arranging legends manually.

# documentation

- As mentioned previously, on the corresponding man pages (in `data.R`), please add details on how the toy data were generated (perhaps the code for this?), or on the source information for data that is not synthetic. This is a requirement, no suggestion ;) 

- I don't see why you need the `utils-pipe.R` script. If you selectively import the pipe-operator, users would be directed to `magrittr`'s help page for it. You don't need to provide one (as you also don't for every other "foreign" function you use). This would also clear part of the `BiocCheck` `NOTE: Consider adding runnable examples...`

# vignette

- There are still some cases where code is not highlighted / distinguishable from normal text... no strict requirement, but would aid readability (e.g., lines 129, 140-153, 292, 301, possibly others).

**Comment by HelenaLC** [comment] 2022-02-23 09:20
Thanks for using `aes_string`, getting rid of `utils-pipe.R`, proper usage of `match.arg`, expanding on `BiocViews`, prettifying `mbecBoxPlot`, highlighting code in the vignette, and (most importantly) moving dependencies to `Depends`; looks all good now & the report looks much cleaner! Few minor comments left (I think)...

- Please include Bioconductor installation (using `BiocManager::install()`) instructions in `README.md`. See [here](https://github.com/drighelli/SpatialExperiment) for an example.

- While there's now a help page for `mbecDummy` (because there's a function definition after the `roxygen2` header), the documentation for the mock data used in the examples (`dummy.x`) cannot be navigated to by the user (for example, `?dummy.mbec` gives an error).  
There are many ways of documenting data. One approach would be to write one piece of documentation (e.g., with `@rdname dummy.data`), and include aliases for all objects (via `@aliases dummy.list dummy.mbec dummy.ps`). Within that document, there could be different sections explaining what `dummy.list` is, and how `dummy.mbec/.ps` were generated from it (reusing what you already wrote). Does that make sense?

- There's seems to be a lot of "clutter" in the repo that is listed under `.git/Rbuildignore`. Ideally, only absolutely necessary files should be put on GitHub (e.g., source code), and deprecated or intermediate files should be removed (e.g., there are 2 licenses, a `README_file` directory, lots of local files not being pushed). In the long term, I'd recommend cleaning this up; putting lots of things in `.xignore` files is not a good habit to get into ;)

**Comment by rmolbrich** [comment] 2022-02-23 15:35
Thank you for the comments.

- I decided not to use cowplot, when I started. Since I already went through the trouble of rearranging plots myself, I want to stick to it for the time being. 
- I updated the Readme to include installation instructions as proposed as well as an abridged version of the tutorial. 
- Worked on cleaning up the clutter. 
- Reduced the size of the data-sets for tests in the hope that this will fix the timeout issues.
- Report-function documentation comes with examples now.

As for the data documentation. I understand the proposed workaround, but I failed to reproduce the issue on two machines. Did I accidentally fix something or is it just a fluke that this works for me now? 

<img width="819" alt="Screenshot 2022-02-23 at 15 08 12" src="https://user-images.githubusercontent.com/83829168/155335599-babb62ca-d8a8-4b23-916d-dba547742609.png">

**Comment by HelenaLC** [comment] 2022-02-24 08:42
Great, thanks. I can see the docs for `dummy.x` now - not sure if I had just missed it earlier. Also the timeout is fixed & README looks good. @lshep any news regarding the support site error? Other than that should be good to accept.

**Comment by lshep** [comment] 2022-03-14 14:50
I'm sorry for the delay in response; I missed this message.  Please ignore the support site error for now.  We have identified the issue on the support site and should have a fix pushed up over the next 2 weeks.

**Comment by lshep** [comment] 2022-03-21 18:19
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rmolbrich.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MBECS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MBECS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-03-21 18:19 UTC
Labels: ERROR, 3a. accepted
