### ISSUE TITLE
sigFeature: an R-package for significant feature selection using SVM-RFE & t-statistic

### ISSUE THREAD

**Issue by pijush1285** [Bioconductor/Contributions#713] opened 2018-04-04 11:11 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pijush1285/sigFeature

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2018-04-04 11:24
@hpages will review this package but it looks like it needs to support [SummarizedExperiment][1] as inputs instead of (or in addition to) matrices of gene expression.

[1]:  https://bioconductor.org/packages/SummarizedExperiment

**Comment by pijush1285** [comment] 2018-04-07 10:15
I have found that the only WARNING detected by the three OS in your report is,
* WARNING: Update R version dependency from 3.4.3 to 3.5.
I have checked the package in windows and Ubuntu after changing the R version 3.5.0 alpha and found that the package check is fine. Initially a WARNING was there says that "*checking PDF version of manual ... WARNING" but this warning coming due to some problem related to LaTeX. After following some instruction given by the link (https://tex.stackexchange.com/questions/125274/error-font-ts1-zi4r-at-540-not-found) I able to solve the problem.

I have change the Depends: R (>= 3.4.3) to Depends: R (>= 3.5.0) in the DESCRIPTION page also.
Please check the package again. If another problem is found please let me know.

**Comment by pijush1285** [comment] 2018-04-09 06:49
Dear Sir,


I have change the Depends: R (>= 3.4.3) to Depends: R (>= 3.5.0) in the
DESCRIPTION page.
I have got R CMD and BiocCheck check massage successful without any error
and without any WARNING.

Please inform me the present status of the "sigFeature" package.



Thank you


regards
Pijush Das

**Comment by pijush1285** [comment] 2018-04-10 11:05
Please give me any update about the present status of the "sigFeature" package.
If any further modification is required please inform me.

regards
Pijush das

**Comment by grimbough** [comment] 2018-04-13 08:08
When you make a change to your package on Github, you also need to bump the version number in DESCRIPTION, so in your case it should now be 0.99.1.  

Normally if you forget to do this the issue will be tagged with VERSION BUMP REQUIRED.  The fact that your post is not labelled like this makes me wonder if you have added the web hook to your repository.  Please look at https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook and make sure you've done this for your package.

Ther are also a number of NOTEs in the output of **BiocCheck** that I'm sure you will be asked to address e.g. `sapply()` vs `vapply()` and using `seq_along()` etc so I would suggest pro-actively looking at those.

**Comment by mtmorgan** [comment] 2018-04-13 17:19
Please address the following and provide a short summary of your changes.

DESCRIPTION

- remove Author: and Maintainer: field (redundant when Authors@R: present.

vignettes

- Structure data so that it is interoperable with Bioconductor conventions. 'ExampleDataRaw' should be a features x samples (not samples x features) [SummarizedExperiment][1] (not plain matrix). All user-facing functions should work with SummarizedExperiment and other [standard Bioconductor classes][2].

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

R

- start all user-facing functions by validating (e.g., using `stopifnot()`) user inputs.
- PlotErrors.R:31 and elsewhere avoid `1:xxx`; use `seq_len(xxx)` instead (avoids surprises when xxx = 0)
- favor legible formatting over compact representation, e.g., predict.R:96
    ```
    for (i in 1:(object$nclasses - 1))
        for (j in (i + 1):object$nclasses) 
            colns <- c(
                colns, 
                paste(
                    object$levels[object$labels[i]], 
                    "/", 
                    object$levels[object$labels[j]],
                    sep = ""
                )
            )
    attr(ret2, "decision.values") <- 
        napredict(
            act, 
            matrix(
                ret$dec, nrow = nrow(newdata), 
                byrow = TRUE, dimnames = list(rowns,colns)
            )
        )
    ```
- vectorize instead of iterate whereever possible, for instance in the above code
    ```
    for (i in 1:(object$nclasses - 1)) {
        j <- seq(i + 1, object$nclasses)
        label <- paste0(
            object$levels[object$labels[i]], 
            "/",
            object$levels[object$labels[j]],
        )
    }
    ```
  and actually further vectorize to remove the outer loop
- avoid the 'copy and append' pattern `x <- c(x, ...)` as in the above code; this scales poorly. See
- use `message()` rather than `print()` to provide diagnostics to the user, e.g., svmrfeFeatureRanking.R:51
- structure, manipulate, and return data to the user in a 'tidy' way. E.g., featsweepSigFe is a list-of-list-of-data.frame, but could be a data.frame with an additional column indicating fold.

man pages

- Please spell-check, e.g., featsweepSigFe.Rd:8 'standered' -> 'standard'

**Comment by grimbough** [comment] 2018-04-24 16:36
It looks like you still need to follow the instructions for adding a web hook (https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) in order to trigger a new build of your updated package

**Comment by mtmorgan** [comment] 2018-04-26 09:10
please clarify why you have made a copy of `predict()` here; it would be normal to import the relevant method, or to write your own method.

**Comment by pijush1285** [comment] 2018-04-26 09:38
You are absolutely right Sir. I actually do not want to copy the predict() function as a member function in the sigFeaure package. Rather I would like to import the predict() function here. But I got some error when I try to import that function in this package.  If you please give me some reference to import the predict() function with out any error or warning, I will submit the updated package again.

Thank you 

regards
Pijush

**Comment by mtmorgan** [comment] 2018-04-26 09:39
provide a simple reproducible example that exercises this part of your code.

**Comment by pijush1285** [comment] 2018-04-26 10:40
Here is the code given below. In that code I am using the predict function.

library(SummarizedExperiment)
library(e1071)
data(ExampleRawData, package="sigFeature")
x  <- t(assays(ExampleRawData)$counts)
y  <- colData(ExampleRawData)$sampleLabels

#Train the data on the basis of top 1000 ranked fratures
#which were computed by svmrfeFeatureRanking() function.
data("featureRankedList")
RFE.model = svm(x[ , featureRankedList[1:1000]], y, type="C-classification", kernel="linear")
summary(RFE.model)
#Testing or predicting the same dataset.
pred <- predict(RFE.model, x[ , featureRankedList[1:1000]])
table(pred,y)



Please suggest me If it is better to remove the predict() function, I can remove that also.

**Comment by mtmorgan** [comment] 2018-04-26 13:12
The code above does not use `sigFeature:::predict.sigFeature()`; if you only want your user to have access to `e1071::predict()` for examples or in your vignette, then remove it from `Imports:` and include it as `Suggests:` in the DESCRIPTION file.

**Comment by pijush1285** [comment] 2018-04-26 18:10
Dear Sir,

I have done the modification as it was suggested by you. But if remove the package e1071 from Imports: and include it in Suggests: then some error massage shows that no need to import the e1071 package in the NAMESPACE page. When I remove the e1071 package from NAMESPACE page then some error massage is there as I am using the svm() function from that package.

Finally I have decided to remove the predict() function as it is already inside e1071 package and expecting that the user can use the predict() function from that package.

**Comment by pijush1285** [comment] 2018-04-28 07:00
Dear Martin Morgan,

I have done the necessary changes as it was suggested.
If any further modification is required please let me know

Thank you

Pijush

**Comment by mtmorgan** [comment] 2018-05-05 17:28
@pijush1285 usually I would add your package to the bioconductor repository and nightly builds after it has been accepted. There is a problem on our end, though, and it will take an extra day or two to work this out. I will post here when your package has been added.

**Comment by pijush1285** [comment] 2018-05-06 09:39
Thank you mtmorgan. This is a great news for me. This is the first time that I have submitted a package in bioconductor repository. Thank you so much for your guidance and help.

**Comment by mtmorgan** [comment] 2018-05-09 14:58
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pijush1285.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"sigFeature\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sigFeature

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-05-09 14:58 UTC
Labels: 3a. accepted, OK
