### ISSUE TITLE
protGear

### ISSUE THREAD

**Issue by Keniajin** [Bioconductor/Contributions#2460] opened 2021-12-15 12:34 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Keniajin/protGear

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2021-12-16 16:58
Thanks for this submission.  This is a very interesting package and I hope we can review it favorably.  At present, we cannot review it for a few reasons.  First, my own attempt to install the package failed because of pacman misbehavior.  Please do not use pacman functions in your package.  Package installation activities are to be governed by the DESCRIPTION file as it will be processed by BiocManager::install().   All dependencies and imported packages that are in CRAN or Bioconductor will be resolved by the build system to ensure your vignettes and examples can be tested.  Second there are references in the vignette to a file that does not exist.  I dug around and found it under inst/extdata, and you need to change
```
header_gpr <- readLines("data/array_data/machine1/KK2-06.txt",
                        n=40)
```
to 
```
header_gpr <- readLines(system.file("extdata/array_data/machine1/KK2-06.txt", package="protGear"),
                        n=40)
```
.. a number of other file references need to be changed in the same way.  Please add more comments to this issue if you have additional questions.  Once these changes are made I will reevaluate for review.

**Comment by Keniajin** [comment] 2021-12-21 13:41
Hi @vjcitn, thanks. I have updated and removed the pacman functions in my package. The updates on the files have also been done. 
I am getting an error after running `Biocheck::Biocheck() `of `"Maintainer must register at the support site; visit https://support.bioconductor.org/accounts/signup/ ."`. Could have an idea why this is happening.

**Comment by lshep** [comment] 2021-12-21 13:45
Did you register the email:  `keniajn@gmail.com` at the support site as requested? It is not showing as a valid registered support site email address to any user on the support site

**Comment by Keniajin** [comment] 2021-12-21 14:03
Thanks @lshep , I was missing an i in the email.

**Comment by vjcitn** [comment] 2021-12-21 15:19
In your vignette you have 
```
```{r setup, include=FALSE}
ploads <- c('tidyverse','ggpubr','gtools','purrr','scales','pheatmap', 'data.table','kableExtra','gridExtra', 'png','knitr' ,'grid','styler',  'factoextra','FactoMineR','magick','rlang','GGally','ggplotify', 'remotes')
sapply(ploads, require, character.only = TRUE)
```
Please do not do this.  Use library() in the vignette when needed.  You can use library() within suppressPackageStartupMessages in a hidden chunk to get packages loaded early on.  Also your vignette wants tidyverse but it is not mentioned in DESCRIPTION.

**Comment by vjcitn** [comment] 2021-12-21 15:20
Does your package pass R CMD check locally?  I can't even build on linux:
```
 --- function search by body ---
Function .onLoad in namespace kableExtra has this body.
 ----------- END OF FAILURE REPORT -------------- 
Quitting from lines 88-89 (vignette.Rmd) 
Error: processing vignette 'vignette.Rmd' failed with diagnostics:
package or namespace load failed for 'protGear':
 .onLoad failed in loadNamespace() for 'kableExtra', details:
  call: !is.null(rmarkdown::metadata$output) && rmarkdown::metadata$output %in% 
  error: 'length(x) = 2 > 1' in coercion to 'logical(1)'
--- failed re-building ‘vignette.Rmd’

```

**Comment by Keniajin** [comment] 2021-12-22 09:41
The package builds well on R CMD 

```
During startup - Warning messages:
1: Setting LC_COLLATE=en_GB.UTF-8 failed
2: Setting LC_CTYPE=en_GB.UTF-8 failed
3: Setting LC_MONETARY=en_GB.UTF-8 failed
4: Setting LC_TIME=en_GB.UTF-8 failed
* checking for file 'protGear/DESCRIPTION' ... OK
* preparing 'protGear':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory 'protGear/data/raw_BG'
Removed empty directory 'protGear/data/raw_MFI_BG'
Removed empty directory 'protGear/data/sample_folder'
Removed empty directory 'protGear/data'
Removed empty directory 'protGear/inst/shiny-examples/protGear_interactive/load_data_dashboard/processed_data'
Removed empty directory 'protGear/vignettes/data/array_sampleID'
Omitted 'LazyData' from DESCRIPTION
* building 'protGear_0.99.1.tar.gz'
```

**Comment by vjcitn** [comment] 2021-12-22 12:14
Please provide the sessionInfo() after doing rcmdcheck::rcmdcheck() on your tarball along with the output of the rcmdcheck.  Thanks!

**Comment by vjcitn** [comment] 2021-12-22 12:18
Also please make the changes necessary to avoid 
```
Removed empty directory 'protGear/data/raw_BG'
Removed empty directory 'protGear/data/raw_MFI_BG'
Removed empty directory 'protGear/data/sample_folder'
Removed empty directory 'protGear/data'
Removed empty directory 'protGear/inst/shiny-examples/protGear_interactive/load_data_dashboard/processed_data'
Removed empty directory 'protGear/vignettes/data/array_sampleID'
```

**Comment by vjcitn** [comment] 2021-12-31 14:12
I hope you will be finding some time to address some of the concerns in the review.  A new submission needs to be tested in the devel branch of R (version 4.2).  You might want to take advantage of the mentoring program, see https://docs.google.com/forms/d/e/1FAIpQLSf_xEOQU6Ye78qF0o0tcUhmMHWui-QVX8R-53KQE8c13qQMqA/viewform ... I hope you have a pleasant new year and that we will hear back from you soon.

**Comment by Keniajin** [comment] 2022-01-07 09:58
> Please provide the sessionInfo() after doing rcmdcheck::rcmdcheck() on your tarball along with the output of the rcmdcheck. Thanks!

Here is the `sessionInfo()`
```
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.5.2    compiler_4.1.1    R6_2.5.1          rprojroot_2.0.2   cli_3.0.1         tools_4.1.1       prettyunits_1.1.1 withr_2.4.2      
 [9] crayon_1.4.1      xopen_1.0.0       rcmdcheck_1.3.3   desc_1.3.0        callr_3.7.0       digest_0.6.27     pkgbuild_1.2.0    ps_1.6.0  
```

**Comment by Keniajin** [comment] 2022-01-07 09:59
> I hope you will be finding some time to address some of the concerns in the review. A new submission needs to be tested in the devel branch of R (version 4.2). You might want to take advantage of the mentoring program, see https://docs.google.com/forms/d/e/1FAIpQLSf_xEOQU6Ye78qF0o0tcUhmMHWui-QVX8R-53KQE8c13qQMqA/viewform ... I hope you have a pleasant new year and that we will hear back from you soon.

Unfortunately I missed this since I was on break, is there another chance available?

**Comment by vjcitn** [comment] 2022-01-07 11:33
Hi, I am surprised about the mentorship form closure.  I will check with the head of that program.  In
any case, please install R 4.2 (devel branch) and test your package with that.  That is obligatory for
submissions in this part of the year.

**Comment by vjcitn** [comment] 2022-01-08 11:22
Well, the mentorship program is indeed closed for the first cycle.  Please install R 4.2, run your package through R CMD check and if there are no errors we will proceed with the review.  But do comment here when you complete this check.

**Comment by vjcitn** [comment] 2022-01-08 11:24
Please try to run R CMD check on a "clean" deployment of R, so that system peculiarities do not affect the check.  There should be no references to local files except as mediated by system.file() to refer to relatively small files that are installed with the package.

**Comment by Keniajin** [comment] 2022-01-08 18:25
I have testes using the R 4.2 (devel branch) and the package builds well

```
`0 errors ✔ | 1 warning ✖ | 7 notes ✖
> sessionInfo()
R Under development (unstable) (2022-01-05 r81453 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] remotes_2.4.2        ggplotify_0.1.0      FactoMineR_2.4       factoextra_1.0.7     styler_1.6.2         png_0.1-7            pheatmap_1.0.12      GGally_2.1.2        
 [9] kableExtra_1.3.4     shinydashboard_0.7.2 flexdashboard_0.5.2  htmltools_0.5.2      plotly_4.10.0        purrr_0.3.4          trend_1.1.4          shiny_1.7.1         
[17] dplyr_1.0.7          plyr_1.8.6           readr_2.1.1          rmarkdown_2.11       rlang_0.4.12         tibble_3.1.6         gridExtra_2.3        gtools_3.9.2        
[25] ggpubr_0.4.0         data.table_1.14.2    tidyr_1.1.4          ggplot2_3.3.5        pacman_0.5.1        

loaded via a namespace (and not attached):
 [1] colorspace_2.0-2     ggsignif_0.6.3       ellipsis_0.3.2       rprojroot_2.0.2      rstudioapi_0.13      ggrepel_0.9.1        DT_0.20              fansi_0.5.0         
 [9] xml2_1.3.3           R.methodsS3_1.8.1    leaps_3.1            knitr_1.37           jsonlite_1.7.2       broom_0.7.11         cluster_2.1.2        R.oo_1.24.0         
[17] BiocManager_1.30.16  compiler_4.2.0       httr_1.4.2           backports_1.4.1      fastmap_1.1.0        lazyeval_0.2.2       cli_3.1.0            later_1.3.0         
[25] prettyunits_1.1.1    tools_4.2.0          gtable_0.3.0         glue_1.6.0           Rcpp_1.0.7           carData_3.0-5        xopen_1.0.0          vctrs_0.3.8         
[33] svglite_2.0.0        xfun_0.29            stringr_1.4.0        ps_1.6.0             rvest_1.0.2          mime_0.12            lifecycle_1.0.1      rstatix_0.7.0       
[41] MASS_7.3-54          scales_1.1.1         hms_1.1.1            promises_1.2.0.1     RColorBrewer_1.1-2   curl_4.3.2           rcmdcheck_1.4.0      yulab.utils_0.0.4   
[49] reshape_0.8.8        stringi_1.7.6        desc_1.4.0           pkgbuild_1.3.1       pkgconfig_2.0.3      systemfonts_1.0.3    evaluate_0.14        lattice_0.20-45     
[57] htmlwidgets_1.5.4    processx_3.5.2       tidyselect_1.1.1     magrittr_2.0.1       R6_2.5.1             generics_0.1.1       pillar_1.6.4         withr_2.4.3         
[65] scatterplot3d_0.3-41 abind_1.4-5          crayon_1.4.2         car_3.0-12           utf8_1.2.2           tzdb_0.2.0           grid_4.2.0           callr_3.7.0         
[73] digest_0.6.29        flashClust_1.01-2    webshot_0.5.2        xtable_1.8-4         R.cache_0.15.0       httpuv_1.6.5         extraDistr_1.9.1     gridGraphics_0.5-1  
[81] R.utils_2.11.0       munsell_0.5.0        viridisLite_0.4.0 `
```

**Comment by vjcitn** [comment] 2022-01-08 19:13
Confirmed.  Package will proceed to review next week.

**Comment by Keniajin** [comment] 2022-01-20 09:30
I am trying to `git fetch` from upstream but I am getting access rights error
```
Fetching upstream
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream
```

**Comment by lshep** [comment] 2022-01-20 12:15
Please make sure you have activated and added ssh-keys to your GitCredentials account as mentioned above:  https://git.bioconductor.org/BiocCredentials

**Comment by Keniajin** [comment] 2022-01-21 14:10
![access_credentials](https://user-images.githubusercontent.com/2590865/150540603-985a8a93-f2a5-4092-8c0f-dc8201717777.PNG)

![access_credentials2](https://user-images.githubusercontent.com/2590865/150541100-ed21839b-1a33-4942-adbe-c49f2ced081b.PNG)
I have added  the keys but seems not to be going through

**Comment by lshep** [comment] 2022-01-21 14:17
Please show the full commands you are trying with output

**Comment by Keniajin** [comment] 2022-01-24 08:02
Hi @lshep below are the commands. I have updated the repository on my Github to remove the errors.

```
$  git remote add upstream git@git.bioconductor.org:packages/protGear.git
$ git remote -v
origin  https://github.com/Keniajin/protGear.git (fetch)
origin  https://github.com/Keniajin/protGear.git (push)
upstream        git@git.bioconductor.org:packages/protGear.git (fetch)
upstream        git@git.bioconductor.org:packages/protGear.git (push)

$ git fetch --all
Fetching origin
Fetching upstream
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream
```

**Comment by lshep** [comment] 2022-01-24 12:24
Have you added ssh-keys?  Please check out the [FAQ page](http://bioconductor.org/developers/how-to/git/faq/) specifically 14-16

**Comment by Keniajin** [comment] 2022-01-24 21:03
Thanks @lshep, I had to add a new public key to work. Just to ‘Bump’ the package version to build again?

**Comment by vjcitn** [comment] 2022-01-24 21:13
Yes.  Bump the version and commit and push.

**Comment by Kayla-Morrell** [comment] 2022-02-10 16:59
Hello @Keniajin - In order for a formal review of the package to be done, all ERRORS and WARNINGS need to be addressed from the build report. Please clean up these issues and then I will begin my review.

Best,
Kayla

**Comment by Keniajin** [comment] 2022-02-11 16:08
> Hello @Keniajin - In order for a formal review of the package to be done, all ERRORS and WARNINGS need to be addressed from the build report. Please clean up these issues and then I will begin my review.
> 
> Best, Kayla

Hi Kayla, I am addressing the package Source tarball size. I cannot pick why there is a difference in size from my local computer.

**Comment by Kayla-Morrell** [comment] 2022-02-22 18:37
@Keniajin,

Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: There seem to be a few files/directories present in your package
  that aren't normally included in Bioconductor packages. Please justify their
use or remove:
	- docs/
	- help.csv
	- intro_test.html
	- www/

## DESCRIPTION

- [ ] REQUIRED: There are far too many packages listed as depends. This field is
  intended for packages that provide essential functionality for the package.
There shouldn't be more than 3 packages listed her. If the packages provide
functions, methods, or classes that are used inside your package name space they
should be listed under Imports.
- [ ] REQUIRED: The package rlang is listed under both Depends and Imports. This
  is not allowed. Please pick one or the other.
- [ ] REQUIRED: The package factoextra is listed twice under Imports. Please
  remove one so it is only listed once.
- [ ] REQUIRED: There are package listed in Depends that are not imported from
  in the NAMESPACE file. These packages should be imported from in the NAMESPACE 
file:
	Biobase, gridExtra, knitr, magrittr, vsn
- [ ] REQUIRED: Update R version from 4.1 to 4.2.
- [ ] REQUIRED: There is a call to scales in the vignette but this package is
  not listed under depends/imports/suggests. If this is something used only in
the vignette example code then I would list it under Suggests.
- [ ] SUGGESTION: There are many suggested biocViews listed in the BiocCheck results 
of the build report. Please look them over and add any that seem applicable to your package.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing the entire
  package. However, if there are many functions from a single package, this is
when the use of `import()` is acceptable. Also there are some packages that are
imported and then you import individual functions from the package using
importFrom. These should be simplified if possible.

## NEWS

- [ ] REQUIRED: Including a NEWS file is great, but it seems that yours is not
  formatted properly. Please see our documentation
[here](https://contributions.bioconductor.org/news.html) to see the correct way
to format this file.

## Package data

- [ ] REQUIRED: We require documentation for data in the `inst/extdata/`
  directory to be present in the `inst/scripts/` directory. The scripts in this
directory can vary. They should very clearly state how the data was generated.
It should include source URLs and any key information regarding filtering or
processing. It can be executable code, sudo code, or a text description. The
idea is users should be able to download the data and roughly reproduce the file
or object that is present as data.

## Vignette

- [ ] REQUIRED: For reproducability you should not be hiding the libraries being
  loaded. Also, you should not install a bunch at the beginning but only load
the libraries where needed in your code. This will help prevent unneeded
libraries from being loaded.
- [ ] REQUIRED: Line 375, when running through your vignette I got an error
  'could not find function "kable_styling"' because I didn't load the libraries
you loaded because they were hidden. Please add the proper library call to this
code chunk so that the code can be executed.
- [ ] REQUIRED: Line 620, when trying to run the shiny app I got the error that
  there is no package called 'shinythemes', 'shinyjs', 'shinyWidgets',
'shinycssloaders', 'shinyFeedback', 'shinyalert', or 'shinyFiles'.
- [ ] SUGGESTION: We strongly encourage the use of BiocStyle for formatting.
- [ ] REQUIRED: The Installation section should demonstrate to the user how to
  install the package from Bioconductor, not github.
- [ ] REQUIRED: The final section of the vignette should be Session Info and
  should include `sessionInfo()`.
- [ ] REQUIRED: Only source vignette files (.Rnw or .Rmd) and any necessary
  static images should be present in the vignette directory. Please remove the
.csv and .R files.

## Man pages

- [ ] SUGGESTION: There is a man page for error_replicates but this does not
  seem to be exported. If this is an internal function I would suggest adding
the `@keywords internal` tag to the documentation.
- [ ] SUGGESTION: We suggest having a package man page with an overview of the
  package and links to the main functions.
- [ ] REQUIRED: Runnable examples should be added to the following man pages
  which document exported functions:
	- launch_protGear_interactive
	- launch_select
	- remove_batch_effect
	- rlm_normalise_matrix
	- rlm_normalise
-  [ ] REQUIRED: There should not be a figures subdirectory in the man directory.
  Only man page files should be present here. If the figures are needed they
should go in an inst/figures directory and be referenced from that location.

## Unit tests

- [ ] SUGGESTION: We strongly encourage the use of unit tests.

## R code

- [ ] SUGGESTION: There are many undefined global functions or variables. I
  would suggest defining as many of these as possible. 
- [ ] REQUIRED: Avoid `1:...`; instead use `seq_len()` or `seq_along()` were
  possible.
- [ ] REQUIRED: `cat` and `print` should not be used outside of `show` methods.
  Use `message`, `warning`, or `stop` instead. Found `print` in files:
	R/cv_estimation_tag_function.R, line 68
	R/global_functions.R, line 165
	R/normalisation_functions.R, line 152
	R/read_files_functions.R, lines 128 and 603
- [ ] REQUIRED: Avoid the use of `paste` in condition signals. Found in files:
	R/cv_estimation_tag_functions.R, lines 41 and 66
	R/global_functions.R, line 128
	R/read_files_functions.R, lines 57, 112, and 590
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 411
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider 4 spaces instead of tabs.
  There are 4 lines that contain tabs.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
  indents. There are 862 lines that are not.


Best,
Kayla

**Comment by Keniajin** [comment] 2022-03-23 10:28
###  General package development
- Removed the files/directories aren't normally included in Bioconductor package

### DESCRIPTION
- Removed the many packages listed on depends
- Removed `rlang` in depends
- Removed one of the `factoextra` files
- Updated the required packages in the NAMESPACE
- Updated the R version to 4.2
- Added Suggests in Description
-  Added some of the suggested biocViews

### NEWS
- Updated the NEWS format

### Package data
- Added a data.R file under inst/scripts/ for data documentation

### Vignette
- Packages shown at the top of vignette
- Added the Bioconductor installation
- Removed .csv and .R files. in vignette directory

### Man pages
- Runnable examples were added to 
  - launch_protGear_interactive
  - launch_select
  - remove_batch_effect
  - rlm_normalise_matrix
  - rlm_normalise
- The figures subdirectory in the man directory removed

### R code
- Avoided using 1:....; where possible however I could not avoid it in `1:n()` 
- Removed cat and print outside of show methods
- Avoided the use of paste in condition signals

Regards,
Ken Mwai

**Comment by Keniajin** [comment] 2022-04-01 12:31
@Kayla-Morrell the package is ready for re-review

**Comment by Kayla-Morrell** [comment] 2022-04-07 14:48
@Keniajin - Thank you for making the necessary changes. You mentioned that you removed the R and csv file from the vignette directory but I find them still present. Please be sure these files are removed. Once this is done I'll be able to accept the package.

Best,
Kayla

**Comment by Keniajin** [comment] 2022-04-08 17:18
> @Keniajin - Thank you for making the necessary changes. You mentioned that you removed the R and csv file from the vignette directory but I find them still present. Please be sure these files are removed. Once this is done I'll be able to accept the package.
> 
> Best, Kayla

@Kayla-Morrell thanks for the update. I have confirmed the files are removed now.

**Comment by lshep** [comment] 2022-04-08 18:17
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Keniajin.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("protGear")`. The package 'landing page' will be created at

https://bioconductor.org/packages/protGear

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-04-08 18:17 UTC
Labels: OK, 3a. accepted
