### ISSUE TITLE
VERSO

### ISSUE THREAD

**Issue by DavideMaspero** [Bioconductor/Contributions#1689] opened 2020-10-02 15:10 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BIMIB-DISCo/VERSO

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by DavideMaspero** [comment] 2020-10-15 17:01
Dear @nturaga, 

we are wondering if you have updates regarding the review process of our package VERSO, as the deadline is quickly approaching.

Thanks,
Davide Maspero

**Comment by nturaga** [comment] 2020-10-19 15:33
Hi @DavideMaspero 

I echo Kasper's concern. Please take a look at your build report. http://bioconductor.org/spb_reports/VERSO_buildreport_20201019051058.html#merida1_buildsrc_anchor 

It's full of WARNINGS / NOTES. Please fix those if you want your package to be accepted before the new release. 

## DESCRIPTION 

The description field is too short. It has to be like an abstract of a paper. 

## NAMESPACE

ok

## R

- Use the package 'BiocParallel' instead of the `parallel` package. 

- Follow the coding style http://bioconductor.org/developers/how-to/coding-style/. 

- For rowSum and colSum you seem to not be using the `Rfast` package implementation. Since you are importing this package already, you might as well see if using these operations will give you a speed up. 

- Do not use the `1:ncol(data)` etc (1:len(..)) type of loop structures. Use `seq_len` or `seq_along` instead. Please check the NOTE sections in your build report. 

- You seem to be "over" casting some objects which are really not needed. When you add additional calls to functions which are basically not doing anything you will waste computational time. 

```
  for(i in 1:num_rs) {

	if(verbose) {
            cat(paste0("Performing restart number ",as.character(as.integer(i))," out of ",as.character(\
as.integer(num_rs))),"\n")
	}

```

this can be written as: (or something very close to this) 

```
for(i in seq_len(num_rs)) {
     if (verbose) {
           message("performing restart number ", i, "out of ", num_rs)
}} 
``` 

- You use the `1:something` paradigm a lot in your code, when it seems to be not needed at all. Revisit these and test them if they are needed.

- I've never seen this style before, but can you tell me why your function name is in "quotes"?

```
"learn.VERSO.phylogenetic.tree" <- function(
```

## General

- There is also an interoperability issue here. You do not allow standard Bioconductor objects to be passed into your exported functions( unless I'm missing something here). 

- See #8 http://bioconductor.org/developers/package-guidelines/#description 

## NEWS

- Your news file has to be parsable by `utils::news()`.

## Vignette

- The naming convention is not very obvious. I'm not sure why you have an Rmd and an Rnw style vignette. 

- It also seems very brief for the package. Please try and elaborate.

- You don't use BiocStyle in the Rmd files, even though your DESCRIPTION file has it in the Suggests section. Please use BiocStyle in both the Rnw and Rmd 

- Follow a clear naming convention for the vignette names. I would strongly urge merging all of them into the same file.

**Comment by danro9685** [comment] 2020-10-19 20:33
Dear @nturaga, 

thank you for your detailed feedbacks. Me and @DavideMaspero have been working hard to implement all the necessary changes. 

In the latest build, we have included most of your suggestions, please have a look and let us know what you think. 

Also, regarding vignette, the .Rmd files are for the GitHub Pages; do you have suggestions on what (if anything) to expand? We think we have already covered the package main functions. 

Looking forward to having your feedback. 

Thanks, 
Daniele & Davide

**Comment by nturaga** [comment] 2020-10-21 15:55
Have you looked at your build report?? http://bioconductor.org/spb_reports/VERSO_buildreport_20201020132638.html#merida1_buildsrc_anchor 

Please fix the warnings.

**Comment by danro9685** [comment] 2020-10-21 16:15
Dear @nturaga, 

we have only 1 warning (functions VERSO and learn.VERSO.phylogenetic.tree third line) as we pass a seed parameter to the function and do set.seed(seed). This is for reproducibility. What do you want us to do? 

Best, 
Daniele

**Comment by nturaga** [comment] 2020-10-21 16:23
Take a look at this and see if you can avoid the set.seed function warning.

https://support.bioconductor.org/p/110439/

**Comment by danro9685** [comment] 2020-10-21 16:32
Dear @nturaga, 

thanks for this great reference. We have taken a look at the discussion there and we think that we have already clearly documented the usage of the seed in our package to make it clear to the user as suggested. 

Thanks, 
Daniele & Davide

**Comment by nturaga** [comment] 2020-10-21 18:43
Hi, 

What you are doing now (below), doesn't provide that much convenience over not having the `seed` argument at all. 

```
foo <- function(x, seed=NULL)
{
    ## I've added this because at the very least you need to check if seed is NULL.
    if (!is.null(seed))
        set.seed(seed)
    ...
}
```

You can just let the user know that they have to set the seed before calling the function `foo()` in your case `learn.VERSO.phylogenetic.tree()` or `VERSO()`. 

As a user, I can just call,

```
set.seed(123)
foo(x) ## No seed argument required.
```

This will allow you to get rid of the warnings as well. 

You call `set.seed(seed)` unconditionally, which is not good, because this re-initializes the RNG when `seed` is NULL. If the user doesn't supply the seed arg, the RNG should not be touched.

I'm cc-ing @hpages as well here, who has more experience with this. But we also point this out in https://www.bioconductor.org/developers/package-guidelines/#rcode , point #2 `Do not use set.seed in any internal R code.`.

**Comment by danro9685** [comment] 2020-10-21 20:35
Dear @nturaga, 

this latest push should fix it. We have removed the set.seed from within the two functions and documented it for the user outside. 

Thanks for your feedbacks, 
Daniele

**Comment by nturaga** [comment] 2020-10-22 13:02
I can't see a new build. Please issue a new version bump.

**Comment by danro9685** [comment] 2020-10-22 13:07
See previous message of 17 hours ago: "Received a valid push on git.bioconductor.org; starting a build for commit id: 177fce1178504de4fa5b9b29585f34d344551ca0". We submitted the push, but for some reason it is not building it.

**Comment by nturaga** [comment] 2020-10-22 13:11
It looks like something is off on our end on the Mac builder. We'll
investigate.

**Comment by danro9685** [comment] 2020-10-22 13:13
Ok, thank you.

**Comment by nturaga** [comment] 2020-10-22 13:15
Can you also ignore the directory `.github` and not just the files inside of it ( `^.github/.*$` ) in your `.RbuildIgnore`?

This will remove that last warning which you've been getting. The `seed` warning is gone now.

**Comment by danro9685** [comment] 2020-10-22 13:32
Dear @nturaga, 

done. But it does not seem to be building. 

Best, 
Daniele

**Comment by nturaga** [comment] 2020-10-22 14:05
Hi @danro9685 

I've accepted your package. One thing I'd like you to consider is, the way your Github repo is organized. 

The `master` branch is not your `default` branch. So when package users what to leave an issue with the code and click on your github link, they are taken to the `VERSO` branch. The naive user and bug reporter won't know why this is the case.

I suggest you make a slight modification in the way your Github repo is displayed. If it helps, add the README.md which the `VERSO` branch has to the `master` branch. 

Does this argument sound reasonable to you? 

Nitesh

**Comment by danro9685** [comment] 2020-10-22 14:07
Yes, sounds good idea. Thanks!

**Comment by mtmorgan** [comment] 2020-10-22 19:48
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/DavideMaspero.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("VERSO")`. The package 'landing page' will be created at

https://bioconductor.org/packages/VERSO

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-10-22 19:48 UTC
Labels: 3a. accepted
