### ISSUE TITLE
Trendy

### ISSUE THREAD

**Issue by rhondabacher** [Bioconductor/Contributions#605] opened 2018-01-08 17:41 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rhondabacher/Trendy

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment] 2018-01-16 16:25
Hi, 

Thanks for your contribution to Bioconductor. Your package is under review now and you can expect an official technical review within this week. Thanks!

Best, 
Qian

**Comment by Liubuntu** [comment] 2018-01-17 22:46
Hi @rhondabacher , 

Your package looks really nice in the functions and output figures with shiny interface. There are some minor issues to address. Please do the version bump to trigger a valid build when you are ready for a second review. Cheers! 

## DESCRIPTION
- Add `Depends` field and depend on the development version of R for the newly submitted R packages. i.e., `Depends: R (>= 3.5)`.
- use a specific version of license in the `License` field. i.e., `License: GPL-2`
- A general rule for writing R package is to keep <=80 characters per line and use multiples of 4 spaces for indentation. Do this in your `Description` field and generalize to the R scripts.

## NAMESPACE
- Seems that you have imported many functions from `shiny`, so you could consider importing the whole package if there is no conflict of functions with other packages.

## MAN
- Looks good.

## R
- extractPattern.R:L68, use `seq_along(genes.pass)` instead of `1:length(genes.pass)`. Do the same for L80: `for(i in 1:length(patstart))`. The use of `seq_len` and `seq_along` is better and safer for marginal case, i.e., if the length of `genes.pass` equals to 0, the loop will not break. Generalize to other R scripts.

- Try to write smaller unexported functions started with "." in the function name, and write the final function as a wrapper for smaller unexported functions. e.g., in "fitSegBIC.R:L41", write the function used in lapply as a unexported function called `.break_point(fit)` and call this function `fit.bp.all <- lapply(whichFit, .break_point)`.  

- fitSegRsq.R:L148-169. use `if (forceRsq)` instead of `if (forceRsq == TRUE)`, and use `else{` for the opposite case.

- Format and indent with multiples of 4 spaces through R script, and keep each lines to be <=80 characters. Use `enter` properly and `tab` for automatic alignmentindentation. e.g., in `fitSegBIC.R` and `fitSegRsq.R`. Check other R scripts for indentation.

## VIGNETTE

The vignette looks really good and easy-reading with proper data and figures. Only a very minor thing:

- You don't need to use `print()` to show the R object. E.g., the last line of R code could be just `SessionInfo()` instead of `print(SessionInfo)`. There are 6 instances of `print()` in your vignette.

**Comment by rhondabacher** [comment] 2018-01-18 16:02
Hi Qian,

Thanks! I've taken care of the things you note.

Best,
Rhonda

**Comment by Liubuntu** [comment] 2018-01-23 17:32
2nd review. Please fix the following issues or comment back for any questions.

## vignettes
- a new folder of `figure` should be removed.

## R

- `fitSegRsq.R` and `fitSegBIC.R`.
These 2 functions calculate different statistics but the process of calculation is similar, which results in a lot of repeated code (even with almost same arguments and default values). -- generalize the calculation process into a separate function, and use wrappers for the calculation function and specify which statistic you want to calculate.

- avoid using `sapply` and use `vapply` instead, which is more stable.
```
helperFunctions.R:    getL <- sapply(IN, length)
topTrendy.R:    seg.all.radj <- sapply(trendyOutData, function(i) i$AdjustedR2)
```

- Vectorize rather than using loop.
```
trendHeatmap.R:    bks.first <- sapply(bks.all, function(i) i[1])
```
Seems that the `bks.all` is just a matrix, could you use `[,1]` for the subsetting for first break point?

- `TrendyExampleData.R` and `data(TrendyExampleData)`
use lower case initial for each function name to be consistent with all functions R data names. "camel case" it is, lower case initial for the first word inside function name, and capital initial for each word after. i.e., `trendyExampleData`.

## unit tests.
Consider adding unit tests. We strongly encourage them. See http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

**Comment by rhondabacher** [comment] 2018-01-31 16:17
> vignettes
> a new folder of figure should be removed.

Thanks! I have fixed this.

> fitSegRsq.R and fitSegBIC.R.
> These 2 functions calculate different statistics but the process of calculation is similar, which results in a lot of repeated code (even with almost same arguments and default values). -- generalize the calculation process into a separate function, and use wrappers for the calculation function and specify which statistic you want to calculate.

Good point, the only reason I had both was for some compatibility to a very early version. After more testing, I decided to remove and discontinue the Rsq option completely.

> avoid using sapply and use vapply instead, which is more stable.
I have changed all use of sapply to vapply.

> Vectorize rather than using loop.
For extractPattern.R, I vectorized the loops. There are no remaining loops in the major functions.

> trendHeatmap.R:    bks.first <- sapply(bks.all, function(i) i[1])
> Seems that the bks.all is just a matrix, could you use [,1] for the subsetting for first break point?
Yes, thanks! I've changed this to your suggestion.

> TrendyExampleData.R and data(TrendyExampleData)
> use lower case initial for each function name to be consistent with all functions R data names. "camel case" it is, lower case initial for the first word inside function name, and capital initial for each word after. i.e., trendyExampleData.
> unit tests.
Done.

> Consider adding unit tests. We strongly encourage them. See http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
Thanks for this suggestion. I will implement unit tests in future package development.

Thank you,
Rhonda

**Comment by Liubuntu** [comment] 2018-01-31 19:48
Hi @rhondabacher ,

Thank you for the quick fix. Just a little 2 minor issues and we should be ready to accept. 

## DESCRIPTION
Since your package is doing segmented (or breakpoint) regression models, we suggest you to add this automatically suggested biocViews: Regression to the `biocViews` field. 

## R/TrendyExampleData.R
To be consistent, Could you rename the script name to be "trendyExampleData.R".

Cheers, 
Qian

**Comment by rhondabacher** [comment] 2018-01-31 20:08
I've just updated the description and renamed the script.

Thanks Qian for your time and suggestions!

**Comment by Liubuntu** [comment] 2018-01-31 21:06
Thanks for your contribution to Bioconductor. I would say Trendy is a very good Bioconductor package, and I have really enjoyed reading your vignette!

**Comment by mtmorgan** [comment] 2018-02-03 17:24
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rhondabacher.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"Trendy\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Trendy

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Closed by mtmorgan** 2018-02-03 17:24 UTC
Labels: 3a. accepted
