### ISSUE TITLE
ALPS

### ISSUE THREAD

**Issue by itsvenu** [Bioconductor/Contributions#1215] opened 2019-08-21 22:40 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/itsvenu/ALPS

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by itsvenu** [comment] 2019-08-23 10:35
Hi @nturaga, the error seems to be from vignette which requires another package: [https://github.com/itsvenu/ALPSdata](https://github.com/itsvenu/ALPSdata). This package contains example data (>5MB). That's why I didn't provide it with `ALPS` package. The data is coming from a published study.

R CMD build, check and BiocCheck are clean if I had it instalIed. I uncommented the code to install `ALPSdata` in the vignette. 

Do you suggest I should also submit ALPSdata package to bioconductor? or should I host files somewhere and include code to download them within vignette?

Thank you.

**Comment by nturaga** [comment] 2019-08-23 14:50
If you want to build the package again on the Single package builder, you have to bump the version. 

You should submit ALPSdata as an Experiment hub package. https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html.

Your software package cannot exceed 5MB in size.

Best,

Nitesh

**Comment by itsvenu** [comment] 2019-08-25 18:13
Hi @nturaga, I don't really get what the error in current build is related to? I ran build, check, bioccheck in windows, linux, macOS from my side. All are clear. Is it possible to provide more information about the error from your side, so that I can look into it? 

Thanks.

**Comment by itsvenu** [comment] 2019-08-27 15:11
hi @nturaga, I bumped the version number but the ERROR in windows is still present. It's very smooth when I run on windows system from my side. Also, there are other examples which utilizes the same code snippet, they didn't throw any error. 

Is there any chance you can take a look into more details why is it happening on your windows server? So that I can move onto next steps?

Thank you!

**Comment by itsvenu** [comment] 2019-09-02 08:50
Hi @nturaga, any update on this issue? Thanks.

**Comment by lshep** [comment] 2019-09-05 11:40
So we have determined the windows is the 32bit specific ERROR as per the discussion on the mailing list.  Please review despite the windows ERROR  @itsvenu  its up to you if you want to add the .BBSOption file for unsupporting 32bit for the time being or wait it out to see what rtracklayer says after submitting an issue report about it.

**Comment by itsvenu** [comment] 2019-09-05 12:23
Hi @lshep, I will include the .BBSOption file for this release. As such I don't need to modify any code in the package, unless rtracklayer changes a lot to support win32 system. Once the issue is fixed, I will remove the BBS file in the next release. This would be best IMO. Should I add BBS file and update the package git repo?

**Comment by lshep** [comment] 2019-09-05 12:52
Yes please git add the `.BBSOptions` file sorry please use this exact caps and plural form for our system to recognize it with the line `UnsupportedPlatforms: win32`  this should prevent building on the 32 bit version of windows only.   Then do a version bump in the DESCRIPTION to hopefully get a full build report.  Thank you

**Comment by lshep** [comment] 2019-09-05 12:54
My mistake on the wrong caps early please use `.BBSoptions`

**Comment by itsvenu** [comment] 2019-09-05 13:48
@lshep aw, finally seems like clean build report. Thanks for helping me out.

**Comment by nturaga** [comment] 2019-09-30 15:10
##  R CMD build

ok

## R CMD check

ok

## DESCRIPTION

- [ ] Description should be like a paper abstract. Please give more details.

## LICENSE

ok

## NAMESPACE

- ok 

## R

- [ ] There are no official guidelines but using %>% makes reading code
  that much harder from the reviewers stand point. The use of the pipe
  is not consistent in your package as well. I'm not suggesting
  removing them, but for a future package use them only if
  necessary. Using pipe operators within software will make it harder
  to debug as well if there is an error.
  
- [ ] Avoid using slot accessors `@` directly. Make a getter function if needed and use that in `x@annotStat`.

- [ ] Use BiocParallel package and find the appropriate function to fit
  your needs, instead of `parallel::mclapply`. 

- [ ] Is it worth declaring a new function with a confusing pipe operation
  `%||%` when you are using it exactly 2 times?
  
  R/geom_flat_violin.R
  45:                     data$width <- data$width %||%
  46:                       params$width %||% (resolution(data$x, FALSE) * 0.9)


## tests

* ok 

## man

- [ ] There is a `figures` folder in the man pages, but the figures
  themselves don't seem to be used.
  
## README_files

- [ ] Please explain what this is for?

## vignette

- [ ] Add the bioconductor way of installing packages with
  `BiocManager::install()`
  
- [ ] Don't supressMessages at library loading. 

Once you fix these issues, i'll do a second review.

**Comment by itsvenu** [comment] 2019-10-01 12:29
Hi @nturaga, thanks for the review and comments. I addressed all the comments mentioned above

# DESCRIPTION

- [x] extended the package abstract

# R

- [x] I see what you mean. I will take care of it for my future package submissions.
- [x] Replaced slot accessor `@` with getter function with `attr`
- [x] Replaced `parallel` with `BiocParallel`
- [x] Yes, you are right. I removed this code completely and used a function from a CRAN package and added it to the `depends` in `DESCRIPTION` file

# man

- [x] figures from `man/figures` are used in the github `README.md` manual file.

# README_files

- [x] This directory contains figures embedded in github `README.md` manual file and is generated with `README.Rmd`

# vignette

- [x] added `BiocManager::install()`
- [x] removed `supressMessages `

Thanks.

**Comment by Kayla-Morrell** [comment] 2019-10-09 18:27
Hello @itsvenu - 

I'll be taking over the review of your package for the time being. Thank you for making the changes mentioned above. I do have some additional points that should be addressed before accepting the package. Please see my review points below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: There is some reorganization of the repo that should be done.
	- [ ] LICENSE.md file is not needed. Since the MIT license is 
	distributed by R the only additional file that is needed in your repo 
	is the LICENSE file.
	- [ ] The README_files/ should be moved to an inst/figures/ directory.
	- [ ] The man/figures/ directory should also go in the inst/figures/ 
	directory.
	- [ ] The directory data-raw/ should be removed and the file DATASET.R 
	should be moved to an inst/script/ directory.
	- [ ] There only needs to be one copy of ALPS-ref.bib, the one in the 
	vignettes/ directory should stay but the one in the top directory should 
	be removed.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to false. When this is true it can 
slow down the loading of packages with data.

- [ ] REQUIRED: 'RoxygenNote:' should be 6.1.1 not 6.1.1.9000.

- [ ] SUGGESTION: Consider adding automatically suggested biocViews:
        - Transcription
        - HistoneModification

## Data

- [ ] REQUIRED: There are many files in the inst/extdata/ directories that 
aren't utilized in the package (from what I could tell at least). Please make 
sure you are only including files that are used within the code, vignette, or 
examples.

## Vignette

The 'README-ALPS-overview' image is a very good overview of the package, well 
done!

## Man pages

- [ ] SUGGESTION: check Rd line widths. 9 files \examples lines wider than 100
characters. These lines will be truncated in the PDF manual.

*pipe*

- [ ] REQUIRED: Almost got the internal keyword tag correct, it should be 
`@keywords internal`.

## inst/script

- [ ] REQUIRED: This is where DATARAW.R belongs. However, the code needs to be 
worked on so that other users can use the code and produce the same resuls you 
did. The paths are specific to your library which if someone else ran this code 
right now, it would error out.

- [ ] REQUIRED: The scripts in this directory can vary. Most importantly if data 
was included in the inst/extdata/, a related script must be present in this 
directory documenting very clearly how the data was generated. It should include 
source urls and any important information regarding filtering or processing. It 
can be executible code, sudo code, or a text description. A user should be able 
to download and roughly reproduce the file or object that is present as data.

## Unit tests

*test-plot_correlation*

- [ ] REQUIRED: There is nothing being tested in this file. Either add test(s) 
or remove the file.

*test-plot_enrichment*

- [ ] REQUIRED: Same for this file, there isn't anything being tested.

*test-plot_motif_logo*

- [ ] REQUIRED: Again, nothing is being tested here.


## R code

- [ ] REQUIRED: It doesn't seem right to have your input data for most of your 
functions be set to NULL. In some of the functions you use 
`assertthat::assert_that()` to kind of test if the data being read in is NULL 
and would throw an error if it was, but in some you don't. A better approach 
would be not to set a default value for the input data and then use 
`assertthat::assert_that()` to test if the input data is the format you require. 
Something like `assertthat::assert_that(is.data.frame(data))`.

- [ ] REQUIRED: Is there a reason why you redefined `%>%` and then export it? 
You end up importing the pipe from magrittr, why not just use this in your code/

- [ ] REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()`. Found in files:
        - get_variable_regions, line 55
        - multiBigwig_summary, line 93
        - plot_browser_tracks, line 89
        - plot_correlation, line 58
        - plot_motif_logo, line 45

- [ ] SUGGESTION: Consider shorter lines, 176 lines are >80 characters long.

- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents, 327 lines 
are not.

Best,
Kayla

**Comment by itsvenu** [comment] 2019-10-14 12:57
Hi @Kayla-Morrell, thanks for the comments. I addressed above raised points. For some I added comments. 

-----------------------------
- [x] REQUIRED: There is some reorganization of the repo that should be done.
 LICENSE.md file is not needed. Since the MIT license is
distributed by R the only additional file that is needed in your repo
is the LICENSE file.
- [x] The README_files/ should be moved to an inst/figures/ directory.
 The man/figures/ directory should also go in the inst/figures/
directory.
- [x] The directory data-raw/ should be removed and the file DATASET.R
should be moved to an inst/script/ directory.
- [x] There only needs to be one copy of ALPS-ref.bib, the one in the
vignettes/ directory should stay but the one in the top directory should
be removed.
-----------------------------
#### DESCRIPTION
 
- [x] REQUIRED: 'LazyData:' should be set to false. When this is true it can
slow down the loading of packages with data.
 
I changed this to `false`. However,  from [this resource](http://r-pkgs.had.co.nz/data.html), seems we better off keeping `lazydata: true`, so the example datasets within the package does not occupy any memory, unless used. If a user wants to use only functions without running the examples given in the package's vignette, loading package doesn't occupy any memory. Or did I miss some additional details? 
 
(Although, ALPS package doesn't have any such datasets. All examples need the data to be read from `extdata` directory)
 
- [x] REQUIRED: 'RoxygenNote:' should be 6.1.1 not 6.1.1.9000.
 
- [x] SUGGESTION: Consider adding automatically suggested biocViews:
- Transcription
- HistoneModification
------------------------
#### Data
- [x] REQUIRED: There are many files in the inst/extdata/ directories that
aren't utilized in the package (from what I could tell at least). Please make
sure you are only including files that are used within the code, vignette, or
examples.
 
All files are used in vignette's examples.
 
------------------------
#### Man pages
- [ ] REQUIRED: Almost got the internal keyword tag correct, it should be
@keywords internal.
 
`devtools::document()` is generating the Rd file with `keyword`, although the `utils-pipe.R` contains `@keywords`. If I edit the `pipe.Rd` file by hand to change keyword -> keywords, CMD build is raising a warning that `keywords` is unknown. Could you please provide the source on which the `keywords` suggestion is based on?
 
------------------------
#### inst/script
 
- [x] REQUIRED: This is where DATARAW.R belongs. However, the code needs to be
worked on so that other users can use the code and produce the same results you
did. The paths are specific to your library which if someone else ran this code
right now, it would error out.
 
- [x] REQUIRED: The scripts in this directory can vary. Most importantly if data
was included in the inst/extdata/, a related script must be present in this
directory documenting very clearly how the data was generated. It should include
source urls and any important information regarding filtering or processing. It
can be executible code, sudo code, or a text description. A user should be able
to download and roughly reproduce the file or object that is present as data.
 
#### Unit tests
test-plot_correlation
 
- [x] REQUIRED: There is nothing being tested in this file. Either add test(s)
or remove the file.
 
test-plot_enrichment
 
- [x] REQUIRED: Same for this file, there isn't anything being tested.
 
test-plot_motif_logo
 
- [x] REQUIRED: Again, nothing is being tested here.
 
Removed these test files.

-------------------
#### R code
- [x] REQUIRED: It doesn't seem right to have your input data for most of your
functions be set to NULL. In some of the functions you use
assertthat::assert_that() to kind of test if the data being read in is NULL
and would throw an error if it was, but in some you don't. A better approach
would be not to set a default value for the input data and then use
assertthat::assert_that() to test if the input data is the format you require.
Something like assertthat::assert_that(is.data.frame(data)).
 
Changed functions according to suggestions where appropriate.

- [x] REQUIRED: Is there a reason why you redefined %>% and then export it?
You end up importing the pipe from magrittr, why not just use this in your code/

Instead of importing pipe for every function, [this thread](https://github.com/sckott/analogsea/issues/32) suggests to define pipe in separate file and export it.

- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along(). Found in files:
 -get_variable_regions, line 55
 -multiBigwig_summary, line 93
 -plot_browser_tracks, line 89
 -plot_correlation, line 58
 -plot_motif_logo, line 45
 
`...` are not present in functions (not sure why BiocCheck throwing this NOTE)
- `get_variable_regions`
- `multiBigwig_summary`
- `plot_motif_logo`
 
and in function `plot_correlation ` & `plot_browser_tracks `, `...` was used in the context of [ellipsis](https://github.com/r-lib/ellipsis). I couldn't find any resource that ellipsis can be replaced by `seq_len` or `seq_along` (I doubt that these 2 functions can replace ellipsis?). Further discussion would be appreciated! 

Thank you. Please let me know if there are additional comments.

**Comment by Kayla-Morrell** [comment] 2019-10-15 19:08
Hello @itsvenu,

Thank you for making the necessary changes. I have just a few more requirements as well as some responses to your comments. Please see the re-review below.

- [ ] REQUIRED: Thank you for cleaning up the repo, however you did not move the README_files/ into an inst/figures/ directory. Also, the man/figures/ directory is still present and not in the inst/figures/ directory. We do not like to have anything besides man pages in the man/ directory. Please make this change.

#### DESCRIPTION
> * [x]  REQUIRED: 'LazyData:' should be set to false. When this is true it can
>   slow down the loading of packages with data.
> 
> I changed this to `false`. However, from [this resource](http://r-pkgs.had.co.nz/data.html), seems we better off keeping `lazydata: true`, so the example datasets within the package does not occupy any memory, unless used. If a user wants to use only functions without running the examples given in the package's vignette, loading package doesn't occupy any memory. Or did I miss some additional details?

_Bioconductor_ preferes to have this set to false, see notes about [DESCRIPTION](https://bioconductor.org/developers/package-guidelines/#description) and [data](https://bioconductor.org/developers/package-guidelines/#data).

- [ ] REQUIRED: 'RoxygenNote:' should be 6.1.1 not 6.1.1.900, this change was not made. Please do so.

#### Man pages
> * [ ]  REQUIRED: Almost got the internal keyword tag correct, it should be
>   @Keywords internal.
> 
> `devtools::document()` is generating the Rd file with `keyword`, although the `utils-pipe.R` contains `@keywords`. If I edit the `pipe.Rd` file by hand to change keyword -> keywords, CMD build is raising a warning that `keywords` is unknown. Could you please provide the source on which the `keywords` suggestion is based on?

Correct, this was my mistake. I didn't realize when you add `@keywords` to the roxygen documentation it gets turned into `\keyword` in the man page. This comment can be ignored.

##### R code
> * [ ]  REQUIRED: Avoid 1:...; use seq_len() or seq_along(). Found in files:
>   -get_variable_regions, line 55
>   -multiBigwig_summary, line 93
>   -plot_browser_tracks, line 89
>   -plot_correlation, line 58
>   -plot_motif_logo, line 45
> 
> `...` are not present in functions (not sure why BiocCheck throwing this NOTE)
> 
> * `get_variable_regions`
> * `multiBigwig_summary`
> * `plot_motif_logo`
> 
> and in function `plot_correlation ` & `plot_browser_tracks `, `...` was used in the context of [ellipsis](https://github.com/r-lib/ellipsis). I couldn't find any resource that ellipsis can be replaced by `seq_len` or `seq_along` (I doubt that these 2 functions can replace ellipsis?). Further discussion would be appreciated!

Here are my proposed solutions...correct me if I'm wrong.

- For `get_variable_regions`: `idx <- order(-rv)[seq_long(num_regions)]`
- For `multiBigwig_summary`: `for (i in seq_len(bwL)) {`
- For `plot_browser_tracks`: `for (i in seq_len(all_sample_ids)) {`
- For `plot_motif_logo`: `for (i in seq_len(x_rd2)) {`

`plot_correlation` doesn't have a fix and is fine as is.

Best,
Kayla

**Comment by itsvenu** [comment] 2019-10-16 13:02
Hi @Kayla-Morrell,

Thanks a lot for the quick response.

> - [x]  REQUIRED: Thank you for cleaning up the repo, however you did not move the README_files/ into an inst/figures/ directory. Also, the man/figures/ directory is still present and not in the inst/figures/ directory. We do not like to have anything besides man pages in the man/ directory. Please make this change.

README_files were used in github README.md file. The contents are same as package's vignette. I thought it's becoming redundant and completely removed this directory. I moved man/figures to inst/figures (sorry, I missed it somehow from previous commit).

> - [x] REQUIRED: 'RoxygenNote:' should be 6.1.1 not 6.1.1.900, this change was not made. Please do so

This was automatically changed back to 6.1.1.900 when I ran `devtools::document()`. Now fixed it.

> Regarding ... 

Thanks for suggesting the solutions. I implemented these changes and used either `seq_along` or `seq_len` depending on the context. 

However, I can't use `seq_*` in `multiBigwig_summary ` function. The `bwL` is a `BigWigFileList` class (from `rtracklayer`) object and using `seq_len` is producing an error (argument must be coercible to non-negative integer). Looks like it has to be `for(i in 1:length(BwL))`.

Please let me know if there are additional comments/suggestions.

Thank you.

**Comment by Kayla-Morrell** [comment] 2019-10-16 13:39
@itsvenu - Perfect, as soon as I see a commit and push, as well as a clean build I'll be happy to accept the package.

**Comment by mtmorgan** [comment] 2019-10-16 17:26
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/itsvenu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ALPS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ALPS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-10-16 17:26 UTC
Labels: 3a. accepted, OK
