### ISSUE TITLE
sketchR

### ISSUE THREAD

**Issue by csoneson** [Bioconductor/Contributions#3284] opened 2024-02-01 20:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fmicompbio/sketchR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by csoneson** [comment] 2024-02-05 17:45
I think the timeout here (on macOS only) comes from building the `conda` environment, which I'm not sure how to do much about - this should only have to be done once, and then things should be much faster. Is there anything that can be done to retrigger the build and let it run through (I guess that if I bump the version it will try to create a new environment)?

**Comment by hpages** [comment] 2024-02-08 20:23
Hi Charlotte,

We've made some changes to how **basilisk**'s cache is set up on nebbiolo1 and merida1. Now it's shared between the daily builds (BBS) and SPB. This should help a little bit with `R CMD build` and `R CMD check` timings of **sketchR** because the SPB will now benefit from things that are already installed by the daily builds.

Can you bump the version of the package? We'll see how it goes.

Note that there will still be a substantial amount of stuff that needs to be reinstalled over and over each time you bump the version of the package (this is how **basilisk** was designed, I can't think of an easy way to avoid that), but the cache also contains a significant amount of stuff that is version-independent. That part won't be reinstalled.

Best

**Comment by hpages** [comment] 2024-02-08 21:13
hmm... :disappointed: I'll take a look...

**Comment by csoneson** [comment] 2024-02-08 21:15
Thanks Hervé! Let me know if there's something else I should try (I can probably reduce the run time of the vignette a little by using a smaller data set to start with, but I'm not sure that has a big impact compared to the time spent building the environment).

**Comment by hpages** [comment] 2024-02-08 23:57
Turns out that the SPB was still using the old cache location (`~/Library/Caches/org.R-project.R/R/basilisk`). Looks like the SPB server needs to be restarted for the new cache location (`/var/cache/basilisk`) to become effective, so I just did that.

Can you please try again? :crossed_fingers:

**Comment by hpages** [comment] 2024-02-09 17:37
Bummer! :disappointed:

FWIW I was able to manually build **sketchR** in an interactive session on merida1 in 9m32s (see https://github.com/Bioconductor/BBS/issues/400), but that was when the daily builds were not running so I guess that gave me a small advantage.

Anyways, even though sharing the cache seems to help a little bit, it's not enough.

Let me think about what else we can do about this.

**Comment by csoneson** [comment] 2024-02-09 19:34
Thanks again - just let me know if there's something I can do! 
I am also able build the package locally in less than 10 minutes, but of course there's not really anything else running on my laptop at the same time.

**Comment by vjcitn** [comment] 2024-02-09 20:12
Hi -- when you say "build the package locally in 10 min" does that include all the miniconda activities for a version bump?

**Comment by hpages** [comment] 2024-02-09 20:15
> when you say "build the package locally in 10 min" does that include all the miniconda activities for a version bump?

For me when I did it on merida1 it did include all the miniconda activities, yes.

Anyways, it doesn't seem fair to take into account the time it takes to set up the **basilisk** environment. This is just a one-time overhead and doesn't reflect the efficiency of the code in the package itself.

One way to ignore the overhead would be to have the SPB (and BBS) run `R CMD build` twice on the package. The first time would be behind the scene and with more time allowed, and only the second time would "count" and be reported. This would be done only for a small subset of packages that are manually enrolled via some flag that they add to their `.BBSoptions` file. However, this would require some substantial changes to the SPB and BBS code base (unfortunately the two build systems don't share as much code as they could). So this is something that we _might_ consider doing in the future.

In the meantime, I'm going to manually restart a build. If it passes `R CMD build` on merida1 in time, hopefully we can give it the green light for ingestion.

**Comment by hpages** [comment] 2024-02-09 20:25
Build and check each took about 2 min on nebbiolo1 and merida1. Yeah!

**Comment by csoneson** [comment] 2024-02-09 20:44
> Hi -- when you say "build the package locally in 10 min" does that include all the miniconda activities for a version bump?

Yes, I think so (at least as far as I can tell), and it was rebuilding the environment (but may potentially have used some previously downloaded and cached packages rather than re-downloading them, I didn't actually check that in detail). 

> Build and check each took about 2 min on nebbiolo1 and merida1. Yeah!

Yay!!

**Comment by hpages** [comment] 2024-02-09 21:46
Can we clear **sketchR** for ingestion @vjcitn @lshep?

**Comment by lshep** [comment] 2024-02-12 12:34
A reviewer hasn't looked at the package yet.  I can take a more in depth look this week.

**Comment by lshep** [comment] 2024-02-15 16:31
When I'm trying to build locally I'm getting the following ERROR is there something I should do to resolve?
```
lorikern@jbcj433:~/PkgReview$ R CMD build sketchR 
* checking for file 'sketchR/DESCRIPTION' ... OK
* preparing 'sketchR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘sketchR.Rmd’ using rmarkdown

Quitting from lines 60-89 [unnamed-chunk-2] (sketchR.Rmd)
Error: processing vignette 'sketchR.Rmd' failed with diagnostics:
function 'as_cholmod_sparse' not provided by package 'Matrix'
--- failed re-building ‘sketchR.Rmd’

SUMMARY: processing the following file failed:
  ‘sketchR.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by csoneson** [comment] 2024-02-15 16:35
I've seen this happening when some packages needed to be reinstalled (from source) since `Matrix` changed their ABI in v1.6-2. For me, reinstalling the packages mentioned in https://stat.ethz.ch/pipermail/r-package-devel/2023q4/010051.html (plus `TFBSTools`, but that's not used here) has been enough.

**Comment by lshep** [comment] 2024-02-15 16:49
hmm... I just tried re-instaling Matrix from source but it still didnt work. Maybe I'll try re-installing R ...

**Comment by csoneson** [comment] 2024-02-15 16:56
I think reinstalling Matrix itself is not enough, also the packages linking to it must be reinstalled (the ones in the linked post).

**Comment by lshep** [comment] 2024-02-15 17:01
tried both Matrix and TFBSTools and still same...

**Comment by csoneson** [comment] 2024-02-15 17:06
What about irlba and/or lme4?

**Comment by lshep** [comment] 2024-02-15 18:20
I deleted out and re-installed Matrix, TFBSTools, lme4, and irlba .... and that seemed to work. I'll try to have a review by tomorrow

**Comment by lshep** [comment] 2024-02-22 18:18
A few quick comments: 
**LICENSE**

- [ ] Is it meant to be 2022?

**vignette**

- [ ] Can the abstract more distinctly describe the "main functionalities" of
  sketchR? Why its important to add to bioconductor/what is novel about the
  package.

**man**

- [ ] Can you provide a package level man page so when a naive user tries
  `?sketchR` it suggests functionality or where to start with the package.

**Comment by csoneson** [comment] 2024-02-23 07:52
Thanks! We've addressed the comments here: https://github.com/fmicompbio/sketchR/pull/13/files

> Is it meant to be 2022? 

Actually yes - from what we understand the copyright year should be when the software was first made available to the public, and in this case the package has been on GitHub since 2022. 

> Can the abstract more distinctly describe the "main functionalities" of sketchR?

We've expanded the introduction to cover these aspects. 

> Can you provide a package level man page?

Yep, good catch, I forgot that - added.

**Comment by lshep** [comment] 2024-03-04 13:12
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/csoneson.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sketchR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sketchR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-03-04 13:12 UTC
Labels: OK, 3a. accepted
