### ISSUE TITLE
epihet

### ISSUE THREAD

**Issue by xiaowenchenjax** [Bioconductor/Contributions#739] opened 2018-04-23 21:39 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/TheJacksonLaboratory/epihet

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment] 2018-04-24 18:28
HI @xiaowenchenjax , 

Please try to fix all the ERRORs in the build report, and a technical review will be given shortly after the building is successfully. Let us know for any questions by commenting here. Thanks for your contribution to Bioconductor. 

cheers,
Qian

**Comment by Liubuntu** [comment] 2018-05-07 14:56
Hi @xiaowenchenjax , 

Please fix any error and warnings that shows in the build report. You can comment back here with any questions. Be sure to make efforts in fixing them by making commits and version bumps, which will trigger new build and shows here. Because the Bioconductor core team usually have a rule of 2 weeks for any new issue here, if no fixes, responses, or any efforts showing that you are working on it, the issue would be closed. But if you feel like you would not be available recently for the new package, you can let us know also, we'll close the issue, and you can always open it once have time. 

Regards,
Qian

**Comment by Liubuntu** [comment] 2018-05-08 18:46
Hi @xiaowenchenjax , 

I am closing this issue since no response within 2 weeks and the last notice. Please feel free to reopen it when you are more available. Thanks for your contribution to Bioconductor. 

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-10-02 21:14
I fixed the error in epihet package, please reopen it and check it. Thanks.

**Comment by xiaowenchenjax** [comment] 2018-10-03 13:15
Hi @mtmorgan,
I fixed the error in epihet package, please reopen it and check it. Thanks.

**Comment by xiaowenchenjax** [comment] 2018-10-03 13:37
Hi @mtmorgan ,
I fixed the error in epihet package, please reopen it and check it. Thanks.

**Comment by mtmorgan** [comment] 2018-10-03 16:33
Please ensure that the [web hook is active][1] and then increment the version number of your package in the DESCRIPTION file to 0.99.1, and push the commit to github.

[1]: https://github.com/Bioconductor/Contributions/#adding-a-web-hook

**Comment by xiaowenchenjax** [comment] 2018-10-05 20:13
HI @bioc-issue-bot ,
I change the R dependency from 3.4 to 3.5, git ignore '.gitattributes', and delete set.seed function in diffHet() and epiTSNE() funtion.

**Comment by mtmorgan** [comment] 2018-10-05 20:17
did you remember to increment the version of your package, to 0.99.2? That is what the 'VERSION BUMP REQUIRED' tag means.

**Comment by xiaowenchenjax** [comment] 2018-10-05 20:50
Hi @bioc-issue-bot ,
i already add ".gitattributes" to the .gitignore file this time, why build report also complain it. 
Could you give me some clue? THANK YOU VERY MUCH.

**Comment by mtmorgan** [comment] 2018-10-05 21:01
You can see, in a new clone, that .gitattributes is present in the repository
```
c02xd1anjgh6:NewPackages ma38727$ git clone https://github.com/TheJacksonLaboratory/epihet
Cloning into 'epihet'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 385 (delta 5), reused 6 (delta 2), pack-reused 367
Receiving objects: 100% (385/385), 4.47 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (113/113), done.
c02xd1anjgh6:NewPackages ma38727$ cd epihet/
c02xd1anjgh6:epihet ma38727$ ls -a
.		.git		DESCRIPTION	R		inst
..		.gitattributes	NAMESPACE	README.md	man
.Rbuildignore	.gitignore	NEWS		data		vignettes
```
By adding it to .gitignore you've told git to ignore any revisions to it, but not to remove it. So
```
git rm .gitattributes
```
and then version bump & push.

**Comment by xiaowenchenjax** [comment] 2018-10-05 22:00
Hi @bioc-issue-bot ,
All set . Please build and check it. Thank you!

**Comment by xiaowenchenjax** [comment] 2018-10-08 15:33
Hi @bioc-issue-bot ,
I have a question: after the package built without errors or warnings on all platforms, when i can find my package in Bioconductor? and what else i should do? Thank you.

**Comment by mtmorgan** [comment] 2018-10-09 02:38
please review the material in the link 'what to expect' appearing in an earlier comment.

**Comment by xiaowenchenjax** [comment] 2018-10-09 21:28
Hi @Liubuntu ,
It is great, thanks.

**Comment by Liubuntu** [comment] 2018-10-22 15:31
Hi @xiaowenchenjax , 

I have posted this review last Friday, but didn't know why it disappeared. So I am posting again. Sorry for the delay in my end. Please seek to address the below issues ASAP so that we can make the release. I'm glad to work together with you on that! Thank you!

Best,
Qian

## DESCRIPTION 

Refer [here](http://bioconductor.org/developers/package-guidelines/)

- Please remove the `Date` field.
- Please remove `LazyData = true`. This rarely proves to be a good
  thing. In our experience it only slows down the loading of packages
  with large data.
- “Authors@R” is duplicate of "Author + Maintainer" field. Remove one
  if all exist.
- Please add `URL: ` field for the relevant links to the GitHub
  repository.
- Please add `BugReport: `. It is encouraged to include this field for
  the relevant links to Github for reporting Issues.


## NAMESPACE

- Seems this package heavily depends on ggplot2, so maybe you just
  import the whole package instead of a long list of specific
  functions?

## vignette

- After the Introduction, please add a section for "Installation" to
  show to users how to install the package as if it has been included
  in Bioconductor. Because new packages is going to be in Bioc devel
  (Bioc 3.8), they are required to use `BiocManager` instead of
  `BiocInstaller` for downing the package. You should include
  something like this:

```
1. Download the package from Bioconductor.

{r getPackage, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("pkgName")

Or install the development version of the package from Github.
{r, eval = FALSE}
BiocManager::install(“githubUserName/pkgname”)

2. Load the package into R session.
 {r Load, message=FALSE}
library(pkgName)
```

- Please add a table of contents for better organization. This could
  be easily specified in the header. check here:
  https://rmarkdown.rstudio.com/html_document_format.html.

- Please add in the end of the vignette a section of `SessionInfo` for your
vignette running environment. e.g.,
```
{r}
sessionInfo()
```
## R/

- Function naming: Use camelCaps: initial lowercase, then alternate
  case between words.. Refer
  [here](https://bioconductor.org/developers/how-to/coding-style/). for
  "moduleanno", "modulesim", "modulevisual"...

- Add some basic checks for the function arguments, since some are required
to be specific class or having specific information as explained in "@param",
e.g., "compMatrix(epi.gr, ...)", add something like:
```
stopifnot( is(epi.gr, "GRanges") )
```

Also check other scripts for similar issue. e.g., "diffHet(subtype,
...)", "epiBox(type, ...)", "epiMa(pval.matrix, )", "epiMap(annotate,
)", "epiPCA(type, )", "epiTSNE(type, )", "modulevisual(value.matrix,
)", "summarize(gr1, gr2, )", "userobj(data)", ...

- vectorize your code. The following could be rewritten (diffHet.R:L53):
```
    mean1.v = apply(val1.r, 1, mean)
    mean2.v = apply(val2.r, 1, mean)
```
as:
```
    mean1.v = rowMeans(val1.r)
    mean2.v = rowMeans(val2.r)
```

- Do not need to test twice for logical values (diffHet.R:L58): `if
(length(loci.filter)>0)` could be only: `if
(length(loci.filter))`. Also in "epinetwork.R":L166.

- Avoid using of `1:...`, use `seq_len()` or `seq_along` instead.

- Avoid `sapply()`, use `vapply()` instead.

- Please use " <- " for assignment instead of "=".

- typo: summarize.R: L4-5, should be "GenomicRanges".


## man/

- Put the "@rdname data" in "data.R" for each dataset so that documentations
for all data goes into one Rd file.
```
#' background
#'
#' A data frame containing 31995 elements as background used for pathway
#' enrichment analysis:
#' @docType data
#' @keywords datasets
#' @name background
#' @rdname data

"background"


#' datTraits
#'
#' clinical traits containing OS,EFS,age
#'
#' @docType data
#' @keywords datasets
#' @name datTraits
#' @rdname data

"datTraits"

```

## NEWS
- Looks good!

**Comment by Liubuntu** [comment] 2018-10-24 15:13
Hi @xiaowenchenjax , 

The final date to include new packages would be 10/24/2018, which is today. Since we are having some delay in the review, we can extend the date to be 10/26/2018, Friday. Please let me know if you have any questions about the review issues. Thanks!

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-10-29 13:37
Hi @Liubuntu,
I am sorry. i did not check it on time. i am working on it today. So I think i miss this release.

**Comment by xiaowenchenjax** [comment] 2018-10-29 13:39
Hi @Liubuntu 
Could you tell me what time the next release?

**Comment by Liubuntu** [comment] 2018-10-29 14:42
The next release (Bioc 3.9) would be end of April, 2019. But anyway, when this package is accepted, it will be in the Bioc devel (https://www.bioconductor.org/developers/how-to/useDevel/), which is meant to have your package go through users' tests and easy to make updates during this period. This is usually encouraged for the new packages. After 6 months, the stable version of package will be included in the new release.

**Comment by xiaowenchenjax** [comment] 2018-10-31 14:16
Hi @Liubuntu 
Ok, Thanks. i am working on it now.

**Comment by Liubuntu** [comment] 2018-11-05 15:10
HI @xiaowenchenjax , 

Please make sure to respond with any updates or fixes or questions within 2 weeks since your last comment, so that this issue will remain active. Thanks!

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-11-06 13:22
Hi @Liubuntu ,
The updates already done. I want to build and check the modified package. But some dependencies fail to install in my R/3.5.1. It almost close. I will finish it as soon as possible. Thanks.
Best,
Xiaowen

**Comment by xiaowenchenjax** [comment] 2018-11-08 23:15
Hi @Liubuntu 
I have updated my package, but i could check it using R/3.5.1 on our helix. it complain 
">library(ggplot2)
Error: package or namespace load failed for ‘ggplot2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/gpfs/ctgs0/software/helix/R/3.5.1/lib64/R/library/Rcpp/libs/Rcpp.so':
  /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /gpfs/ctgs0/software/helix/R/3.5.1/lib64/R/library/Rcpp/libs/Rcpp.so)"
because our package use ggplot2 package a lot. 
So could you help me check this package?
Thanks a lot!
Best,
Xiaowen

**Comment by Liubuntu** [comment] 2018-11-09 15:47
Hi @xiaowenchenjax , 

I'll see if I can reproduce this error on my linux system and let you updated. Thanks!

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-11-09 18:59
Hi @Liubuntu ,
Thanks. i can library ggplot2 on other versions of R.
Best,
Xiaowen

**Comment by Liubuntu** [comment] 2018-11-13 18:43
Hi @xiaowenchenjax , 

I have tried to build your package (before I do the check) but there are several issues you need to fix first: 

1. NAMESPACE seems to be having some flaws, It should be `GenomicRanges` instead of `GenomicRaes`. Source code is in `R/summarize.R`.
```
importFrom(GenomicRaes,findOverlaps)
importFrom(GenomicRaes,values)
```
2. Also on vignette/epihet.Rnw, L58, It should be `BiocManager` instead of `BioManager`. 
```
BioManager::install("EpiHet") 
```
3. DESCRIPTION. Please depend on the development version of R. 
```Depends: R(>= 3.5.1)```

For your question, could you try to first `update.packages()` in your R session, and redo the `library(ggplot2)`? And you can also check your package using `devtools::check()` inside R, or `R CMD build epihet` => `R CMD CHECK epihet_0.99.3.tar.gz`. 

Let me know if this could be of any help. 

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-11-14 12:56
Hi @Liubuntu ,
thank you for your suggestion. i will try it.
Best,
Xiaowen

**Comment by xiaowenchenjax** [comment] 2018-11-14 16:04
Hi @Liubuntu ,
i had updated my package. 
Best,
Xiaowen

**Comment by Liubuntu** [comment] 2018-11-15 21:13
HI @xiaowenchenjax , 

You need to bump version in `DESCRIPTION` so that the changes could be caught and trigger a new build. 

Please read [the instructions][1] for setting
up a push hook on your repository, or further changes to your
repository will NOT trigger a new build.

[1]: https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-11-16 01:31
Hi @Liubuntu 
Sorry about that. I am done

**Comment by xiaowenchenjax** [comment] 2018-11-16 12:59
Hi @Liubuntu ,
I would like to change my package name "epihet" to "EpiHet", to keep same with the manuscript which i want to submit some journal. Is it easy to change it?
Thanks.
Best,
Xiaowen

**Comment by Liubuntu** [comment] 2018-11-16 15:44
Hi @xiaowenchenjax , 

Yes it is possible to change the name of the package while under review.  

1. Change your github repository first.  
2. Update the github link (in first comment of this issue) 
3. Update the **issue name** on the review.  

After that, We will need to also make the change on our database of new issues.  When the issue is renamed please ask @lshep on the issue number to rename the issue before making any additional version bumps to the package.

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-11-16 18:42
Hi @Liubuntu,
I see, it is too complex, it is easier to keep "epihet" this name. Thank you very much.
Best,
Xiaowen

**Comment by lshep** [comment] 2018-11-16 18:45
It really is no trouble on our end to change the database if you wish to pursue the name change -  entirely up to you.

**Comment by Liubuntu** [comment] 2018-11-16 19:18
Hi @xiaowenchenjax , 

The steps only include updating the package name for 1) your own github repository, 2) the link to your updated github repository in the first comment of this issue and 3) this issue name. 

If you want to keep the current name of "epihet", you will need to make the names consistent in your `DESCRIPTION` "Package" field, so that the current building error could be removed. A second review will be give only when you get a clean and successful building report. Thanks!

Best,
Qian

**Comment by xiaowenchenjax** [comment] 2018-11-18 02:07
Hi @Liubuntu ,
OK, thanks. i will update my package as soon as possible.
Best,
Xiaowen

**Comment by xiaowenchenjax** [comment] 2018-11-26 18:17
Hi @Liubuntu ,
I update my package. i think this time should be OK. thanks

**Comment by xiaowenchenjax** [comment] 2018-11-27 15:16
Hi @Liubuntu ,
I check the warnings and error in the build report. 
for BiocCheck, WARNING: Update R version dependency from 3.5.1 to 3.6.
In MACS, ERROR: dependency ReactomePA is not available for package epihet.
Could you give me some suggestion how to fix it? 
Thank you very much
Best,
Xiaowen

**Comment by Liubuntu** [comment] 2018-11-27 15:50
Hi @xiaowenchenjax , 

You can ignore the MAC dependency error for now. Please do ```for BiocCheck, WARNING: Update R version dependency from 3.5.1 to 3.6.``` as suggested, so that I could give another look at your updates. Thanks!

Best,
qian

**Comment by Liubuntu** [comment] 2018-11-27 20:47
Yes. You need to bump version whenever you make any changes/updates so that it could trigger the building.

**Comment by xiaowenchenjax** [comment] 2018-11-28 00:15
Hi @Liubuntu ,
Thanks.
Best.
Xiaowen

**Comment by Liubuntu** [comment] 2018-11-28 17:58
Hi @xiaowenchenjax , 

Please see below for the 2nd review. Please address the issues or comment back to explain why they are not addressed. Let me know for any question. Thanks!

## R
> Also check other scripts for similar issue. e.g., "diffHet(subtype,
> ...)", "epiBox(type, ...)", "epiMa(pval.matrix, )",
> "epiMap(annotate,)", "epiPCA(type, )", "epiTSNE(type, )",
> "modulevisual(value.matrix, )", "summarize(gr1, gr2, )",
> "userobj(data)", ...

The above argument checks, I mean the specific information that are
required for the argument. E.g., in epiMA.R, check the column names /
column contents would make more sense than checking the data class
`is(pval.matrix, "data.frame")`. Same as the other functions above.

```
@param pval.matrix The data frame returned from the
#' diffHet() function that contains means, p-values,
#' adjusted p-values, and heterogeneity difference
#'
```

The following issues about coding style / best practices were from
initial review and was not addressed with no explaination. These are
strongly encouraged by Bioconductor, If making the modifications are
too hard or causing unexpected delay in time with coordinating or
anything else, please explain here.

- Do not need to test twice for logical values (diffHet.R:L58):
`if (length(loci.filter)>0)` could be only: `if (length(loci.filter))`.
Also in "epinetwork.R":L167.

- Avoid using of `1:...`, use `seq_len()` or `seq_along()` instead.

- Please use " <- " for assignment instead of "=".

## man/

Since all data are documented inside one "data.md" file, so in
"R/data.R", there is no need for the duplicated `@return A data
frame`. One would be enough.

Also for `@format` and `@description`, add a label before hand each
description line with the data name, so the merged "data.md" file is
more organized and easy to read. e.g.,

```
...
#' @description A data frame containing 31995 elements as background
used for pathway enrichment analysis:
#' @format background: A data frame with 31995 rows and 1 variables: ...
#' @return
#' A data frame
"background"

#' datTraits
#'
#' @description datTraits: clinical traits containing OS,EFS,age
#' @format datTraits: A data frame with 6 rows and 3 variables: ...
#' @return A data frame
      ## COMMENT: remove this section from "datTrait" and all duplicate sections from the documentation of other datasets. One "@return A data frame" from "background" would be enough.
"datTraits"

**Comment by xiaowenchenjax** [comment] 2018-11-30 02:09
Hi @Liubuntu ,
I will look at it. Thanks.
Xiaowen

**Comment by xiaowenchenjax** [comment] 2018-11-30 16:43
Hi @Liubuntu,
In my data.R file, It looks like this:
#' Example data
#' @docType data
#' @keywords datasets
#' @name background
#' @rdname data
#' @usage data(background)
#' background
#' @description background: A data frame containing 31995 elements as background used for pathway
#' enrichment analysis
#' @format background: A data frame with 31995 rows and 1 variables:
#' \describe{
#'   \item{gene}{background gene list}
#' }
#' @return
#' A data frame
"background"

#' datTraits
#' @docType data
#' @keywords datasets
#' @name datTraits
#' @rdname data
#' @usage data(datTraits)
#' datTraits
#' @description datTraits: Clinical traits containing OS,EFS,age
#' @format datTraits: A data frame with 6 rows and 3 variables:
#' \describe{
#'   \item{OS}{overall survival time}
#'   \item{EFS}{survival time}
#'   \item{age}{ages of patients}
#' }
"datTraits"
**But in the data.Rd file, i can only see the format and describe information for data frame "background" . Could you tell me how to fix it?*
\docType{data}
\name{background}
\alias{background}
\alias{datTraits}
\alias{DEG}
\alias{DEH}
\alias{diffhetmatrix}
\alias{moduledm}
\alias{modulesil}
\alias{promoter}
\alias{sharedmatrix}
\title{background}
\format{background: A data frame with 31995 rows and 1 variables:
\describe{
  \item{gene}{background gene list}
}}
\usage{
data(background)
......

**Comment by Liubuntu** [comment] 2018-12-05 19:45
Hi @xiaowenchenjax , 

Thanks for making updates.  However, for coding styles, I would recommend you to check out [here](https://bioconductor.org/developers/how-to/coding-style/) and [here](https://bioconductor.org/developers/how-to/efficient-code/) for any further development. It's highly recommended to use ` <- ` for R variable assignment instead of `=`, all through the code. 

I'm accepting the package now. Thanks for your contribution to Bioconductor. 

Cheers,
Qian

**Comment by xiaowenchenjax** [comment] 2018-12-06 03:15
Hi @Liubuntu,
Thank you! I learn from you a lot. i will check the link you send me and keep this coding style for further development.
Best,
Xiaowen

**Comment by mtmorgan** [comment] 2018-12-11 23:17
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xiaowenchenjax.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("epihet")`. The package 'landing page' will be created at

https://bioconductor.org/packages/epihet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-12-11 23:17 UTC
Labels: 3a. accepted
