### ISSUE TITLE
netboxr

### ISSUE THREAD

**Issue by mil2041** [Bioconductor/Contributions#1272] opened 2019-10-01 19:37 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mil2041/netboxr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment] 2019-10-09 15:57
Hi Eric, @mil2041 

Thank you for your submission. 

Please review your dependencies and modify the `DESCRIPTION` file accordingly. 
Please run `R CMD check` and `R CMD BiocCheck` on the package  to see the
points of improvement. After this is done, bump the version and I will review
your package. Thank you.

-Marcel

**Comment by mil2041** [comment] 2019-10-11 18:33
> Hi Eric, @mil2041
> 
> Thank you for your submission.
> 
> Please review your dependencies and modify the `DESCRIPTION` file accordingly.
> Please run `R CMD check` and `R CMD BiocCheck` on the package to see the
> points of improvement. After this is done, bump the version and I will review
> your package. Thank you.
> 
> -Marcel

Hi Marcel, 

We have checked the package dependency again and the package also has passed the 
`R CMD check` and `R CMD BiocCheck` checks now. The version numbering also has been changed. 

Many thanks,
Eric

**Comment by mil2041** [comment] 2019-10-11 18:37
> Hi Eric, @mil2041
> 
> Thank you for your submission.
> 
> Please review your dependencies and modify the `DESCRIPTION` file accordingly.
> Please run `R CMD check` and `R CMD BiocCheck` on the package to see the
> points of improvement. After this is done, bump the version and I will review
> your package. Thank you.
> 
> -Marcel

Hi Marcel, @LiNk-NY 

We have checked the package dependency again and the package also has passed the
R CMD check and R CMD BiocCheck checks now. The version numbering also has been changed.

Many thanks,
Eric

**Comment by LiNk-NY** [comment] 2019-10-18 00:42
Hi Eric, @mil2041 
Thank you for your submission. 
Please see the review below. 
If you have any questions, post them here. 
Best, 
Marcel 

---

# netboxr #1272

## DESCRIPTION

* There are a lot of packages in the `Depends` field. Please reduce this to
a minimal set of packages. Move packages to `Imports` and avoid duplicate
package entries (e.g., `c('data.table', 'jsonlite', 'parallel', 'gplots',
'plyr')`).
* Include the suggested biocViews terms from BiocCheck
* See also:
```
   * NOTE: Consider clarifying how 4 object(s) are initialized. Maybe
      they are part of a data set loaded with data(), or perhaps part
      of an object referenced in with() or within().
    function (object)
      geneConnector (phyper)
      geneConnector (p.adjust)
      localNullModel (sd)
      localNullModel (pnorm)
```
* Remove `org*db` package from the `Depends` field and put it in `Suggests`.
* Load it conditionally if the package is installed by using `requireNamespace`

## NAMESPACE

* Looks good.
* Imports should be `Imports` only and not `Depends`

## vignettes

* Remove the `remotes::install_github` command and use `BiocManager::install`
* Use `help(package = "netboxr")` to display the installed vignettes.
* Looks good. Please keep the 80 column width for readability
* Make sure commented code is either removed or un-commented

## R

* As in `BiocCheck`, avoid using `1:n` sequence generation, use `seq_len(n)`
or `seq_along`.
* Do not use `cat` to print messages to the user, use `message`.
* It doesn't make sense to calculate both `pValue` corrections. Provide only
the correction requested.  You can use `match.arg` on the `pValueAdj` argument.
Set the default to `pValueAdj = c("BH", "Bonferroni")` in the function
definition.d
* Remove all the commented code and code such as `write.table`
* Avoid using `dontrun` tags in examples. Static code leads to errors as
package development progresses
* A list representation is not very helpful. Please find a more compact and
meaningful data structure for representing your data.

**Comment by mil2041** [comment] 2019-10-23 20:46
Hi Marcel, @LiNk-NY

We really appreciate the suggestions on the netboxr package. We have modified the package to comply with the suggestions in the previous comments. The output of netboxr is still in the list format so far, because we think the output can be readily used for other packages. 

Many thanks,
Eric

**Comment by LiNk-NY** [comment] 2019-10-23 22:58
Hi Eric, @mil2041 

Thank you for making those changes. 
Please respond item by item. 

_Note_. There is a stray `*.R` file in the vignettes folder. Please remove it
and clean up the `inst/tmp` folder. This directory is mostly for 
experiment data packages that want to provide some form of 
reproducibility. Delete any code that has a comment and code
that is not needed for the functionality of the package. 

Thank you. 

Best, 
Marcel

**Comment by mil2041** [comment] 2019-10-25 20:48
Hi Marcel, @LiNk-NY 

> Hi Eric, @mil2041
> 
> Thank you for making those changes.
> Please respond item by item.
Sorry for not replying to the previous comments item by item. 

> _Note_. There is a stray `*.R` file in the vignettes folder. 
We have checked the files in the vignettes folder and only keep the necessary file.  

> Please remove it and clean up the `inst/tmp` folder. This directory is mostly for
> experiment data packages that want to provide some form of
> reproducibility. 
We also have removed the 'inst' folder. Those files are legacy codes, they are not required for this release. 

> Delete any code that has a comment and code
> that is not needed for the functionality of the package.
We have gone through the code thoroughly again. Only the necessary functionalities of the package are kept. 

> Thank you.
> 
> Best,
> Marcel

Many thanks again,
Eric

**Comment by LiNk-NY** [comment] 2019-10-28 14:24
Hi Eric, @mil2041 

It looks like you should move `paxtoolsr` to the `Imports` field as you're selectively
importing `readGmt` from that package.
Your package looks ready to go. 

Best,
Marcel

**Comment by mil2041** [comment] 2019-10-28 21:22
Hi Marcel, @LiNk-NY

> Hi Eric, @mil2041
> 
> It looks like you should move `paxtoolsr` to the `Imports` field as you're selectively
> importing `readGmt` from that package.
We have changed the DESCRIPTION file and moved the pxtoolsr into imports section now.

> Your package looks ready to go.
> 
> Best,
> Marcel

Many thanks,
Eric

**Comment by LiNk-NY** [comment] 2019-10-31 17:56
Hi Eric, @mil2041 
Thanks for making those changes. 
Your package has been accepted. 

Best,
Marcel

**Comment by mtmorgan** [comment] 2019-11-02 20:00
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mil2041.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("netboxr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/netboxr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-11-02 20:00 UTC
Labels: 3a. accepted, OK
