### ISSUE TITLE
AnVILWorkflow

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/Contributions#2832] opened 2022-10-08 02:23 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shbrief/AnVILWorkflow

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by shbrief** [comment] 2022-10-12 18:21
Hi @Kayla-Morrell ,

I updated my email address to the one used for the bioc-devel mailing list.
But I'm unsure how to resolve the other error (`* ERROR: At least 80% of man pages documenting exported objects must have runnable examples.`), because more than 80% of functions in this package are a wrapper around API calls. Is there any suggestion on this case? Thanks!

Sehyun

**Comment by Kayla-Morrell** [comment] 2022-10-18 16:54
Hello @shbrief 

There do need to be examples in the man pages for exported objects. Would utilizing something like the following work?

```{r}
if (AnVIL::gcould_exists()) {
    ## run example code
}
``` 

You could also look into `donttest{}` as a last resort (we prefer runnable, testable code over using `donttest{}`/`dontrun{}`). If you must use one of these options we prefer `donttest{}` because it requires valid R code.

Best,
Kayla

**Comment by shbrief** [comment] 2022-10-25 03:43
Hi @Kayla-Morrell 
I fixed all the errors. Could you look at whether it's ready for the next step in review? Thanks!

**Comment by Kayla-Morrell** [comment] 2022-10-25 15:06
@shbrief - You need to push a version bump to the git version of the package to kick of a new build report. Without a clean build report I can't continue with my portion of the review. Please see [here](https://github.com/Bioconductor/Contributions/issues/2832#issuecomment-1275051428) for how to get this set up.

Best,
Kayla

**Comment by shbrief** [comment] 2022-10-25 15:10
I have some permission issues accessing upstream. I'll push the new version as soon as I figure this out. Thanks!

**Comment by shbrief** [comment] 2022-10-25 20:18
Hi @Kayla-Morrell 
I cleared all the errors/warnings. Please let me know what else needs to be done. Thanks!

**Comment by Kayla-Morrell** [comment] 2022-10-26 18:38
@shbrief - When trying to build the package locally I get the following error:

```{r}
* creating vignettes ... ERROR
--- re-building ‘salmon.Rmd’ using rmarkdown
Loading required package: dplyr

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Quitting from lines 193-195 (salmon.Rmd)
Error: processing vignette 'salmon.Rmd' failed with diagnostics:
'gcloud auth print-access-token' failed:
  ERROR: (gcloud.auth.print-access-token) Your current active account [shbrief@gmail.com] does not have any valid credentials
    Please run:

      $ gcloud auth login

    to obtain new credentials.

    For service account, please activate it first:

      $ gcloud auth activate-service-account ACCOUNT
  exit status: 1
--- failed re-building ‘salmon.Rmd’

SUMMARY: processing the following file failed:
  ‘salmon.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by shbrief** [comment] 2022-10-26 20:28
Hi @Kayla-Morrell, I think it should work now.

**Comment by shbrief** [comment] 2022-10-28 00:04
Will it be possible to include this package in the BioC 3.16 release? @vjcitn @lshep

**Comment by vjcitn** [comment] 2022-10-28 02:52
Hi Sehyun -- it may be possible.  But I am looking at the vignette as produced on my machine.  A key point is 
```
knitr::knit_exit(fully=FALSE)
```
So most of the vignette is not produced.  Is this what you want?

**Comment by shbrief** [comment] 2022-10-28 02:55
Oh sorry, I was experimenting with something and accidentally pushed it. I'll fix it now.

**Comment by shbrief** [comment] 2022-10-28 03:07
@vjcitn Fixed. Let me know if you find any other issues. Thanks!

**Comment by lshep** [comment] 2022-10-28 14:55
@Kayla-Morrell is the assigned reviewer and will still have to review and accept

**Comment by Kayla-Morrell** [comment] 2022-10-28 15:07
@shbrief - I still need to do a full initial review of this package (besides just a clean build report) which takes time and reviews are not the only thing that I currently work on. This is an especially busy time with the release so please be patient. I will try to get to the review by the end of the day but I do not foresee it being a part of the 3.16 release since the deadline was Wednesday.

Best,
Kayla

**Comment by shbrief** [comment] 2022-11-09 21:13
@Kayla-Morrell Do you know when you would have time to review this package? I haven't heard anything for a while and just want to make sure I didn't miss any communication. Thanks! - Sehyun

**Comment by Kayla-Morrell** [comment] 2022-11-14 15:13
@shbrief - Sorry for the delay, with the release and being out sick last week I'm a bit behind. I will work on getting a review posted early this week.

**Comment by Kayla-Morrell** [comment] 2022-11-15 16:31
@shbrief - I still cannot build the package locally in order to do a review. This is the error I get when trying to run R CMD build:

```{r error}
* creating vignettes ... ERROR
--- re-building ‘salmon.Rmd’ using rmarkdown
Loading required package: dplyr

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Warning in rm(resp) : object 'resp' not found
Warning in rm(resp) : object 'resp' not found
Quitting from lines 219-221 (salmon.Rmd)
Error: processing vignette 'salmon.Rmd' failed with diagnostics:
'gcloud auth print-access-token' failed:
  ERROR: (gcloud.auth.print-access-token) Your current active account [shbrief@gmail.com] does not have any valid credentials
    Please run:

      $ gcloud auth login

    to obtain new credentials.

    For service account, please activate it first:

      $ gcloud auth activate-service-account ACCOUNT
  exit status: 1
--- failed re-building ‘salmon.Rmd’

SUMMARY: processing the following file failed:
  ‘salmon.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by shbrief** [comment] 2022-11-22 17:54
It seems like the gcloud enviroment of your local machine is misconfigured - the package is building on the build system and because the build system does not have gcloud installed so no code chunks will be evaluated. Is there a reason you try to build this locally? Could you use the build system instead? Also, just to confirm the configuration issue, could you tell me the output for the following code in your local machine? Thanks!

```
AnVIL::gcloud_account()
AnVIL::gcloud_project()
```

**Comment by Kayla-Morrell** [comment] 2022-11-28 15:20
@shbrief - Part of the review process is for the reviewer to be able to build and check the package locally. The build system may not have gcloud installed but my local system does and this may be the case for other users. This was my initial result of the code you posted:
```{r}
> gcloud_exists()
[1] TRUE
> gcloud_account()
[1] "shbrief@gmail.com"
```
My cloud environment must have been overwritten from an early attempt at building your package. I reset my cloud environment to my account and project and was still unable to build the package. The new error is:
```{r}
* creating vignettes ... ERROR
--- re-building ‘salmon.Rmd’ using rmarkdown
Loading required package: dplyr

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Warning in rm(resp) : object 'resp' not found
Warning in rm(resp) : object 'resp' not found
Quitting from lines 219-221 (salmon.Rmd)
Error: processing vignette 'salmon.Rmd' failed with diagnostics:
Workspace doesn't exit or you don't have access to it.
--- failed re-building ‘salmon.Rmd’

SUMMARY: processing the following file failed:
  ‘salmon.Rmd’

Error: Vignette re-building failed.
Execution halted
```
Best,
Kayla

**Comment by shbrief** [comment] 2022-11-28 21:35
@Kayla-Morrell Thanks for trying it out again. Martin could successfully build it locally, so I'm not completely sure what causes the error in your local machine. I updated a few things that can potentially solve the problem. Could you take a look at it now? Thanks!

**Comment by Kayla-Morrell** [comment] 2022-11-29 14:15
@shbrief - There is one minor change that I had to make to the vignette code in order to get the package to build. On line 302 of the vignette I had to change `tibble::tibble` to `tibble::tibble()` so that it was an actual function call. Now that the package builds locally I can move forward with the review. I'll have it posted in the next couple of days.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2022-12-02 17:11
@shbrief - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.1 to 4.3.0.
- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field which
  includes a relevant link to GitHub for reporting issues.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: We require documentation of files in the `inst/extdata/`
  directory in an `inst/script/` directory. The script(s) in this directory can
vary. Most importantly there needs to be documentation vary clearly stating how
the data was generated and source information. It should include source URLs and
any key information regarding filtering or processing. It can be executable
code, sudo code, or a text description. Users should be able to download and
roughly reproduce the file or object that is present as data.
- [ ] REQUIRED: Looking at the data files within 'inst/extdata/' I don't see
  where Table1.pdf is used within the package. If it is not needed it should be
removed.

## Vignette

- [ ] REQUIRED: There should be an Installation section (besides the load
  package section) that demonstrates to the user how to install the package from
Bioconductor. The code chunk should include `eval = FALSE`.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?AnVILWorkflow`.
- [ ] REQUIRED: Should the example for `availableAnalysis()` have the code to
  check if gcloud is available?
- [ ] REQUIRED: There should be a runnable example in the `setCloudEnv()` man
  page.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html

## R code

- [ ] SUGGESTION: checking R code for possible problems.
    getOutput: no visible binding for global variable 'workflowName'
    Undefined global functions or variables:
        workflowName
- [ ] REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods
- [ ] REQUIRED: Avoid the use of 'paste' in condition signals
- [ ] REQUIRED: Avoid 'suppressWarnings'/'Messages' if possible (found 1 times)
- [ ] SUGGESTION: Consider shorter lines. There are 14 lines that are > 80
characters long.
- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents. There are 84
lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2022-12-29 14:44
Hello @shbrief - Checking in to see if there has been any progress made on addressing the points from my review. We like to see changes within 2-3 weeks to be sure the package is actively being worked on. Let me know if you have any questions or need any further clarification.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2023-01-25 17:11
@shbrief - I have not heard back from you in some time. If no changes from the review are made in the next week I'll be closing the issue due to inactivity.

Best,
Kayla

**Comment by shbrief** [comment] 2023-01-25 17:31
@Kayla-Morrell Hi Kayla, I'll make updates by the end of next week. Thanks for keeping track of it. - Sehyun

**Comment by shbrief** [comment] 2023-02-03 21:48
Hey Kayla, I need a little more time to update (~a week). Could you wait? Or would it better to close this and resubmit? Let me know. Thanks!

**Comment by Kayla-Morrell** [comment] 2023-02-06 15:56
@shbrief - That's fine, I can wait.

**Comment by shbrief** [comment] 2023-02-10 21:03
@kayla Here are the updates. Let me know what you think. Thanks!

## DESCRIPTION

- [x] REQUIRED: Update R version dependency from 4.1 to 4.3.0. 
*--> It seems like the latest version of R is 4.2.2 now. I updated the dependency to 4.2.0. Let me know if this is not ok.*
- [x] SUGGESTION: We strongly encourage including the 'BugReports:' field which
  includes a relevant link to GitHub for reporting issues.
*--> `BugReports: https://github.com/shbrief/AnVILWorkflow/issues` is added*

## NEWS

- [x] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.
*--> NEWS file is added*

## Data

- [x] REQUIRED: We require documentation of files in the `inst/extdata/`
  directory in an `inst/script/` directory. The script(s) in this directory can
vary. Most importantly there needs to be documentation vary clearly stating how
the data was generated and source information. It should include source URLs and
any key information regarding filtering or processing. It can be executable
code, sudo code, or a text description. Users should be able to download and
roughly reproduce the file or object that is present as data. 
*--> Delete some unnecessary files and move the `map` file under `data` folder.*
- [x] REQUIRED: Looking at the data files within 'inst/extdata/' I don't see
  where Table1.pdf is used within the package. If it is not needed it should be
removed.
*--> Removed*

## Vignette

- [x] REQUIRED: There should be an Installation section (besides the load
  package section) that demonstrates to the user how to install the package from
Bioconductor. The code chunk should include `eval = FALSE`.
*--> The installation section (with `eval=FALSE`) is added*

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?AnVILWorkflow`.
- [x] REQUIRED: Should the example for `availableAnalysis()` have the code to
  check if gcloud is available? 
*--> This function is supposed to print out workspaces manually curated by this package, which is saved as a data file within the package (`data/map.rda`). So there is no need to check gcloud availability.*
- [x] REQUIRED: There should be a runnable example in the `setCloudEnv()` man
  page.
*--> An example is added*

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html

## R code

- [x] SUGGESTION: checking R code for possible problems.
    getOutput: no visible binding for global variable 'workflowName'
    Undefined global functions or variables:
        workflowName
    *--> This variable is removed.*
- [x] REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods
- [x] REQUIRED: Avoid the use of 'paste' in condition signals
- [x] REQUIRED: Avoid 'suppressWarnings'/'Messages' if possible (found 1 times)
- [ ] SUGGESTION: Consider shorter lines. There are 14 lines that are > 80
characters long. 
*--> Shorten several lines that I think are proper.*
- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents. There are 84
lines that are not.

**Comment by shbrief** [comment] 2023-02-14 18:13
@kayla Here are the updates. Let me know what you think. Thanks!

## DESCRIPTION

- [x] REQUIRED: Update R version dependency from 4.1 to 4.3.0. 
*--> It seems like the latest version of R is 4.2.2 now. I updated the dependency to 4.2.0. Let me know if this is not ok.*
- [x] SUGGESTION: We strongly encourage including the 'BugReports:' field which
  includes a relevant link to GitHub for reporting issues.
*--> `BugReports: https://github.com/shbrief/AnVILWorkflow/issues` is added*

## NEWS

- [x] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.
*--> NEWS file is added*

## Data

- [x] REQUIRED: We require documentation of files in the `inst/extdata/`
  directory in an `inst/script/` directory. The script(s) in this directory can
vary. Most importantly there needs to be documentation vary clearly stating how
the data was generated and source information. It should include source URLs and
any key information regarding filtering or processing. It can be executable
code, sudo code, or a text description. Users should be able to download and
roughly reproduce the file or object that is present as data. 
*--> Delete some unnecessary files and add the description on `map.tsv` file under `inst/script/` folder.*
- [x] REQUIRED: Looking at the data files within 'inst/extdata/' I don't see
  where Table1.pdf is used within the package. If it is not needed it should be
removed.
*--> Removed*

## Vignette

- [x] REQUIRED: There should be an Installation section (besides the load
  package section) that demonstrates to the user how to install the package from
Bioconductor. The code chunk should include `eval = FALSE`.
*--> The installation section (with `eval=FALSE`) is added*

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to the main functions. Users should be able to have a
relevant page display with `?AnVILWorkflow`.
- [x] REQUIRED: Should the example for `availableAnalysis()` have the code to
  check if gcloud is available? 
*--> This function is supposed to print out workspaces manually curated by this package, which is saved in the package (`inst/extdata/map.tsv`). So there is no need to check gcloud availability.*
- [x] REQUIRED: There should be a runnable example in the `setCloudEnv()` man
  page.
*--> An example is added*

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html

## R code

- [x] SUGGESTION: checking R code for possible problems.
    getOutput: no visible binding for global variable 'workflowName'
    Undefined global functions or variables:
        workflowName
    *--> This variable is removed.*
- [x] REQUIRED: Avoid 'cat' and 'print' outside of 'show' methods
- [x] REQUIRED: Avoid the use of 'paste' in condition signals
- [x] REQUIRED: Avoid 'suppressWarnings'/'Messages' if possible (found 1 times)
- [x] SUGGESTION: Consider shorter lines. There are 14 lines that are > 80
characters long. 
*--> Shorten several lines that I think are proper.*
- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents. There are 84
lines that are not.

**Comment by Kayla-Morrell** [comment] 2023-02-24 15:47
@shbrief - Thank you for making the necessary changes. There is just one change that needs to be made and then I'll be able to accept the package.

## DESCRIPTION

- [ ] REQUIRED: The R version should be set to 4.3.0, this is the devel version of R and is the version that will work with Bioconductor 3.17 when it is released.

Best,
Kayla

**Comment by shbrief** [comment] 2023-02-24 18:11
@Kayla-Morrell R dependence version is updated. Thanks!

**Comment by lshep** [comment] 2023-03-03 14:25
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shbrief.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AnVILWorkflow")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AnVILWorkflow

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-03-03 14:25 UTC
Labels: OK, 3a. accepted
