### ISSUE TITLE
(inactive) cellmigRation

### ISSUE THREAD

**Issue by wleoncio** [Bioconductor/Contributions#1618] opened 2020-09-02 14:22 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ocbe-uio/cellmigRation

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-09-03 18:06
Please follow package guidelines by removing large files; it may be necessary to follow [additional steps](http://bioconductor.org/developers/how-to/git/remove-large-data/) to remove the files from the git repository.
```
files larger than 5Mb:
  /inst/extdata/A6dCon-short.tif
```
Please be sure to run `BiocCheck::BiocCheck()` on your package after removing the large files.

Please post a comment here when your package has been updated, so the review process can start.

**Comment by wleoncio** [comment] 2020-09-04 15:03
Dear reviewer,

The package has been updated with the requested change. Please proceed with the review process.

**Comment by wleoncio** [comment] 2020-09-18 07:25
Dear reviewers,

We have rechecked the package on our usual OSs (Linux and Windows) plus the offending OS (mac) and were unable to replicate the warning. According to [a 2016 bioc-devel thread](https://stat.ethz.ch/pipermail/bioc-devel/2016-February/008743.html), that particular rgl.init warning is safe to ignore. Is that still the case?

Thank you,
Waldir

**Comment by Kayla-Morrell** [comment] 2020-09-18 18:11
@wleoncio - I would say it's safe to ignore (for the time being). I'm currently working on the initial review of the package and should have it posted in the next couple of days.

Thanks for your patience,
Kayla

**Comment by Kayla-Morrell** [comment] 2020-09-21 17:28
@wleoncio - 

Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## General package development

*R CMD check*

- [ ] NOTE: checking installed package size. Installed size is 8.2Mb, data 
directory is 6.6Mb.

- [ ] REQUIRED: Since you are using a standard license you do not need to 
include the LICENSE file in your package.

## DESCRIPTION

- [ ] REQUIRED: The biocViews tags for this package (I believe) are wrong. This 
package would be considered a Software package since there functionality within 
it. Please take a look at our Software biocViews terms and pick the ones that 
would apply to your package. https://bioconductor.org/packages/release/BiocViews.html#___Software

## NAMESPACE

- [ ] REQUIRED: Exported functions should use camel case or underscoring, not 
"." which indicates S3 dispatch.

## NEWS

- [ ] REQUIRED: It's good practice to include a NEWS file, so thank you for that. 
However, the content and the file format don't match. If you want to use a 
NEWS.md file, the content must be in mark down. The content you have belongs in 
a NEWS file. I think the easiest change would to just rename the file from 
'NEWS.md' to just 'NEWS'. You can check if the file is formatted properly by 
installing your package and then running 
`utils::news(package="<name of your package>")`.

## Data

- [ ] REQUIRED: Can you provide any source information for the datasets?

## Vignette

- [ ] REQUIRED: The Installation section should demonstrate to the user how to 
install the package from Bioconductor, not github. The code should look like 
the following:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("cellmigRation")
```

- [ ] SUGGESTION: We strongly encourage a table of contents.

- [ ] REQUIRED: Lines 114-126, we discourage the use of downloading data from 
online resources and would much rather have the data as part of the package. If 
you want to demonstrate `LoadTiff()` I would suggest including these data files 
as part of an `inst/extdata/` directory and include the download process as a 
script in an `inst/script/` directory.

- [ ] REQUIRED: You need to show the loading of the LS data 
(`data("VignBuilderDataset")`). I would suggest explaining that the loading in 
the tiff data is optional (and can be done with the users own data) but the 
data can be loaded for the vignette using `data(VignBuilderDataset)`. That way 
if the user just wants to walk through the vignette they won't have to download 
the data themselves, they can just load yours and be on their way.

- [ ] REQUIRED: Code chunks need to be evaluated (eval = TRUE) and visible to 
the user (echo = TRUE), unless there is some justification as to why they 
shouldn't be. The idea behind a vignette is to have reproducibility and if 
chunks of code aren't evaluated or shown it can result in code that either 
won't work for the user or different results. 

- [ ] REQUIRED: Line 387, there seems to be an extra ` before CellMig(). 

## Man pages

- [ ] REQUIRED: There need to be runnable examples in the man pages which 
document exported objects.

- [ ] REQUIRED: There is usage of dontrun{} / donttest{} found in man page 
examples. 22% of man pages use one of these cases. This is not good practice and 
all exmaples should be runnable for exported objects.

## Unit tests

- [ ] SUGGESTION: We like to see more than one test being performed, you might 
give some thought to adding more tests.

## R code

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` where possible.

- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` where possible.

- [ ] REQUIRED: Avoid use of direct slot access with `@` or `slot()`. Accessor 
methods should be created and utilized

- [ ] REQUIRED: Recommended function length <= 50 lines. There are 27 functions >
50 lines. They don't have to be precisely 50 lines, but 1167 lines for a 
function is way too long. Your code would benefit from being broken into more 
R files as well. It will make the code easier to read and debug.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 
983 lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 3261 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2020-10-06 14:22
Hello @wleoncio - With the Bioconductor release taking place this month, I wanted to make you aware that the last day for accepting new packages into the 3.12 release is 10/21. If you would like your package included in the release please be sure changes are made with enough time for me to re-review and accept by that date. If this doesn't seem attainable then the package will be apart of the next release.

Best,
Kayla

**Comment by wleoncio** [comment] 2020-10-06 14:29
Thank you for the heads up, @Kayla-Morrell. As you can see from the references above, we're still working on addressing all the issues from [your review](https://github.com/Bioconductor/Contributions/issues/1618#issuecomment-696258765). I think It's more probable we'll make it to the next release, but I'd love to be proven wrong!

**Comment by Kayla-Morrell** [comment] 2020-11-20 15:30
Hello @wleoncio - I am closing this package for inactivity. We normally like to see changes to a package within a few weeks to know they are actively being worked on (no changes have been committed in over a month). When you have implemented changes and are ready for a re-review, please comment back here to ask that the issue be reopened.

Best,
Kayla

**Comment by wleoncio** [comment] 2020-11-23 05:54
Relaying to PI (@systemsbiologist) to keep him in the loop of the [action above](https://github.com/Bioconductor/Contributions/issues/1618#issuecomment-731236876).

**Comment by wleoncio** [comment] 2021-03-05 09:29
Dear @Kayla-Morrell,

We have prepared a new package version for review. I am, however, having trouble triggering a reopening of this issue. We have already done the following:

- Addressed all issues raised in https://github.com/Bioconductor/Contributions/issues/1618#issuecomment-696258765 (notes, requirements and suggestions);
- Bumped version from 0.99.1 to 0.99.2 (and then 0.99.3 as a retry) in the package `DESCRIPTION`;
- Got the package passing `R CMD check`, `R CMD check --as-cran`, `BiocCheck()` and `BiocCheckGitClone()`;
- Pushed the latest commit to `git.bioconductor.org:packages/cellmigRation.git` and `github.com/ocbe-uio/cellmigRation.git`;
- Read the guidelines on [this repository's README file](https://github.com/Bioconductor/Contributions) as well as the [new package workflow](https://bioconductor.org/developers/how-to/git/new-package-workflow/) page on Bioconductor.org.

The new workflow page states that "[i]f your push to git.bioconductor.org included a version bump, you’ll receive an email directing you to visit your issue on github.com, https://github.com/Bioconductor/Contributions/issues/; a comment is also posted on the issue indicating that a build has started", but none of this has happened so far. Please advise.

**Comment by Kayla-Morrell** [comment] 2021-03-05 12:13
@wleoncio - The tag needs to be changed from 'inactive' to 'review in progress'. I have done this now. Please try pushing another version bump and this should trigger a new build.

Best,
Kayla

**Comment by wleoncio** [comment] 2021-03-08 10:15
Dear @Kayla-Morrell,

Thank you for the help and the availability to review our package.

Version 0.99.6 is building fine on Linux and Windows. The macOS build is failing to install the `kableExtra` package, which seems to be a problem with the dependency itself (judging by how [kableExtra's CRAN check report](https://cran.r-project.org/web/checks/check_results_kableExtra.html) also fails for that OS at the moment).

Would you consider proceeding with the package review or should we try to redo the vignette not to use that package?

Best,
Waldir

**Comment by Kayla-Morrell** [comment] 2021-03-08 13:05
Hello @wleoncio - If the package is building fine on the other builders I'm more than happy to proceed. Hopefully in the mean time the issue will get cleared up on CRAN. I will look over the changes in the next couple days and let you know if there are any additional changes that need to be made. Thanks!

**Comment by SystemsBiologist** [comment] 2021-03-18 08:53
Hello @Kayla-Morrell,
We are wondering if the changes we made are satisfactory!
Looking forward to hearing from you.
Best,
Salim

**Comment by Kayla-Morrell** [comment] 2021-03-18 14:27
@SystemsBiologist - Sorry for the delay, I will look over the changes today and let you know if there are further changes that need to be made.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-03-18 18:02
@wleoncio - Thank you for making all the necessary changes. I've looked them over and have just a few more requirements that need to be met and then I'll be happy to accept the package. Please see these additional requirements below.

## General package development

- [ ] REQUIRED: This was a previous requirement that was not met, since you are
  using a standard license you do not need to include the LICENSE file in your
package. This file should be removed. 

## DESCRIPTION

- [ ] REQUIRED: 'LazyData' should be set to 'false'. It is our experience when
  this field is set to 'true' it can slow down the loading of the package
especially if it includes data.

## Vignette

- [ ] REQUIRED: In order for the vignette to be reproducable to users (meaning
  if they want to get the same results you did) you should put the `set.seed()`
command into a code chunk that is visable to the user so they can set the seed
themselves.

- [ ] SUGGESTION: I would change the installation code to something like the
  following and include `eval=FALSE`

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("cellmigRation")
```

Best,
Kayla

**Comment by wleoncio** [comment] 2021-03-19 11:39
Dear @Kayla-Morrell,

Thank you for your suggestions, they are surely improving the quality of our package. I believe we have implemented all of them on version 0.99.7, but please let us know if anything is amiss.

Best,
Waldir

**Comment by Kayla-Morrell** [comment] 2021-03-19 18:21
@wleoncio - Great! Thank you for making those changes. I've looked everything over and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by SystemsBiologist** [comment] 2021-03-19 18:36
Dear @Kayla-Morrell,

Thanks a lot!

Have a nice weekend,

Salim

**Comment by wleoncio** [comment] 2021-04-22 04:24
Dear @Kayla-Morrell,

Considering the [approaching deadlines for Bioconductor 3.13](https://www.bioconductor.org/developers/release-schedule/) and the last message from the bioc-issue-bot on this thread saying our software package was going to be added to the nightly builds, we were wondering if there are any actions to be taken by our part for this to happen, since we can't seem to find cellmigRation listed anywhere on [the check results page](https://www.bioconductor.org/checkResults/).

Thank you for the clarification,
Waldir

**Comment by Kayla-Morrell** [comment] 2021-04-22 16:14
@wleoncio - Sorry for the confusion, something must have gone wrong on our end. We are working on resolving the issue.

**Comment by vjcitn** [comment] 2021-04-24 03:38
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wleoncio.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("cellmigRation")`. The package 'landing page' will be created at

https://bioconductor.org/packages/cellmigRation

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-04-24 03:38 UTC
Labels: 3a. accepted, WARNINGS
