### ISSUE TITLE
AltWrapper

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/Contributions#1222] opened 2019-08-30 16:44 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Jiefei-Wang/AltWrapper

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment] 2019-08-30 17:08
@gmbecker and @ltierney are probably interested in this. Btw, are you guys aware of https://github.com/fstpackage/lazyvec?

**Comment by Jiefei-Wang** [comment] 2019-08-30 17:57
Hi @lawremi, thanks for your comment. Martin has told me about the lazyvec package while I was developing this package. Glad to see someone has the same idea. I read his package and feel we have different thought on the implementation. If I understand it correctly, his implementation is closed to procedure-oriented, you can create an ALTREP given the data and functions. Mine is more like R's S4 class, after defining a class and its functions you can make an ALTREP via the class name. Therefore, two packages are supposed to be used differently. Besides that, I also like to provide a well documented ALTREP APIs in my package for pure R user to use ALTREP since there is not too much documentation about ALTREP. Our package certainly have some overlaps but I think we have different use cases.

**Comment by gmbecker** [comment] 2019-08-30 18:19
I will find some time to look at and comment more deeply on this sometime soon. Thanks for the tag @lawremi. 

@Jiefei-Wang One thing I do know off the top of my head is that from discussions with @ltierney is that he has serious concerns about R-implemented altrep classes.

I think this is due to the fact that parts of the ALTREP framework temporarily turn off garbage collection (specifically, from a quick glance, the dataptr retrieval methods, see comments in , e.g., `ALTVEC_DATAPTR_EX` within altrep.c) and it isn't really ok to be evaluating arbitrary R-level code with GC turned off, because quite literally anything could happen. 

I will look more closely when I can (hopefully soon).

**Comment by Jiefei-Wang** [comment] 2019-09-04 18:29
Hi @gmbecker , Martin and I had a meeting and we took a look at the code in altrep.c, we knew that GC is suspended when calling dataptr method, but we could not find a good reason for it. We must overlook some potential problem so I would like to ask your thought here. Mainly there are two questions in my mind:

1. Why is GC suspended when calling dataptr method?

2. what is the problem if we call an R function while GC is off? 

I will appreciate it if you can elaborate on this topic.

Best,
Jiefei

**Comment by lawremi** [comment] 2019-09-06 16:28
For one thing, If `DATAPTR()` could cause garbage collection (via an allocating ALTREP implementation) then we and every R package using native code would need to `PROTECT()` everything passed to it (and there are _a lot_ of things passed to `DATAPTR()`). Calling any code, but particularly user R code, with the garbage collector turned off, can exhaust the heap.

**Comment by Jiefei-Wang** [comment] 2019-09-06 18:17
Thank you @lawremi , I can see the problem now. I appreciate your help here.

**Comment by Jiefei-Wang** [comment] 2019-09-11 15:08
Hi @hpages , the package is up-to-date and ready for review.

**Comment by Jiefei-Wang** [comment] 2019-09-23 16:40
Hi @hpages , I have finished the updates, it is ready for review.

**Comment by hpages** [comment] 2019-10-02 17:25
Hi @Jiefei-Wang ,

I took a quick first look and have some feedback, see below. I'll need to take a closer look but it'd be great if you could address the points below. Thanks!

H.

- In the Description field of the DESCRIPTION file. Instead of:

    > It provides a set of functions to define and manage an ALTREP class in purely R level.

    How about "It provides a set of functions to manage user-defined ALTREP classes at the R level."

- Note that you only use BiocStyle to build the vignette so you don't need to import it. It should be listed in Suggests instead.

- Depending on DescTools only to use `StrAlign()` seems unnecessary. Use base function `format()` instead. Note that with these 2 changes (i.e. removal of BiocStyle and DescTools from the Imports field), `library(AltWrapper)` is now 8x faster (takes 0.111s instead of 0.923s on my laptop) and you end up with 2 packages in `sessionInfo()$loadedOnly` instead of 20.

- In `setAltClass()`, `classType` can be `"raw"`, `"logical"`, `"integer"`, or `"real"`. Why not use `"numeric"` or `"double"` instead of `"real"` for consistency with the names of the atomic types in base R?

- More generally speaking you should try to be more consistent with the terminology and the spelling. For example in your documentation sometimes you write "altwrapper object" and sometimes "altWrapper object". Choose a spelling (all lower case of camelCaps) and stick to it.

- Overall the naming of your functions lack consistency. Here are some suggestions for improving this:
    altClassStatus -> showAltClass
    makeAltrep -> newAltrep
    getClassType -> getAltClassType
    deleteClass -> deleteAltClass
    isAltClassExist -> isAltClassDefined or altClassExists
    isAltMethodExist -> isAltMethodDefined or altMethodExists
    removeWrapper -> removeAltWrapper

- I'm confused by this example in `?removeWrapper`, especially by the comment that "`A` does not have a wrapper":
    ```
    ## Define an altWrapper class
    length_func<-function(x) length(x)
    setAltClass(className = "example", classType = "integer")
    setAltMethod(className = "example", getLength = length_func)
    A = makeAltrep(className = "example", x = 1L:10L)
     
    ## Since A is a new object and does not have a wrapper,
    ## calling `removeWrapper` does not have any effect.
    A = removeWrapper(A)
    ```
  But when I call `is.altWrapper()` on `A` before or after the call to `removeWrapper()`, I always get TRUE.

- The vignette says: "Note that there is an extra argument `.self` in `sumFunc` function." However I don't see this argument.

- My impression is that `deleteClass()` doesn't clean as much as it should because the following code seems to slowly eat the memory of my system (as reported by running `top` in a terminal to monitor memory usage):
    ```
    library(AltWrapper)
    for (i in 1:1e6) {
       className <- paste0("test", i)
       setAltClass(className, classType="integer")
       deleteClass(className)
    }
    ```

- Please use `<-` instead of `=` for assignment. Also always place a white space before and after `<-`.

**Comment by Jiefei-Wang** [comment] 2019-10-07 19:03
Hi Herve,

Thanks for your comments, I have made the changes and it is ready for review. Here are some thoughts on your question:

1. 
> I'm confused by this example in ?removeWrapper, especially by the comment that "A does not have a wrapper"

The function removeWrapper is not for removing the altWrapper and exposing the internal data(This can be achieved by calling getAltWrapperData), the function is for removing the wrapper created by the function R_tryWrap in RInternal.h header. R_tryWrap is used internally by some R functions so removeWrapper is designed to make sure a variable is an altWrapper object, not a wrapper. Otherwise if a wrapper presents, the C level function getAltData1 and getAltData2 will get the data from the wrapper, not the altWrapper object. I have updated its document to clarify your concern. I think it is better to use removeWrapper rather than removeAltWrapper to avoid confusion.

2.
> The vignette says: "Note that there is an extra argument .self in sumFunc function." However I don't see this argument.

I decided to delete the extra argument before return the result and forgot to update the vignette accordingly. Thanks for pointing it out. Now the vignette should be fine.

3. 

> My impression is that deleteClass() doesn't clean as much as it should

This is a very interesting observation, and actually the memory is not eaten by the class definition. It is R's string caching that is using the memory. To confirm that
```
a=new.env()
for (i in 1:1e6) {
    className <- paste0("test", i)
    exists(className, envir = a, inherits = F)
}
```

This simple code will consume about 200MB memory and they are not refundable when calling `gc()`. I guess the caching is managed by R and we don't have control over it.

**Comment by hpages** [comment] 2019-10-08 08:59
Hi Jiefei,

Good catch with your conclusion that it's R's CHARSXP caching that is using the memory! That makes a lot of sense.

Thanks for taking the time to explain what `removeWrapper()` does. Please make sure that the explanation in the man page is as clear/complete as the one you gave me above. In particular please make sure to explain why one would want to remove the wrapper. Right now it's not really clear. Overall the man page doesn't provide as much details as it could. A few more things about `removeWrapper()`:

- I still find the name of the function confusing. I get that we're talking about removing a mysterious wrapper that has nothing to do with your AltWrapper objects. Would it make sense to use a more specific term for the wrapper removed by `removeWrapper()` e.g. something like "automatic wrapper" or "caching wrapper" and to rename `removeWrapper()` accordingly? (e.g. `removeAutoWrapper()` or `removeCachingWrapper()`). It's ok to give long names to ultra-specialized functions like that.

- The only example you show for `removeWrapper()` is an example where the function doesn't actually remove anything. This is not illustrative at all and also it doesn't help the reader understand the usefulness of the function. Do you think you could show an example where calling `removeWrapper()` actually removes something?

- How does the user know whether an altWrapper object has an "automatic/caching wrapper" or not?

- In the man page you write: "it can be silently made in some R functions and behaves exactly the same as the object it wraps". How about: "It can be silently added by some R functions and behaves exactly the same as the object it wraps". I guess this is an _in-place_ modification e.g. calling `sum(x)` will silently add the wrapper to `x`. Wouldn't it then make sense to also have `removeWrapper(x)` perform an _in-place_ modification? If that makes sense, then `removeWrapper(x)` would no longer need to return the modified object and maybe it could instead return a single logical indicating whether a wrapper was actually removed or not.

Thanks!

**Comment by ltierney** [comment] 2019-10-08 17:15
On Tue, 8 Oct 2019, Hervé Pagès wrote:

> 
> Hi Jiefei,
> 
> Good catch with your conclusion that it's R's CHARSXP caching that is using
> the memory! That makes a lot of sense.

This is incorrect. The CHARSXP cache has nothing to do with this.

The issue is that the _symbol table_ is not garbage collected. This is
well known and could be fixed but hasn't been high enough on anyone's
priority list to get done. It does create issues from time to time in
artificial examples and in some uses of environments as hash tables.

Fixing this is a little tricky because the assumption in C code in
many, many places is that the symbols returned by `install()` will
never be garbage collected. Ones created by R calls to things like
`assign()` or by the parser and that are have never been returned by
`install()` could be. So there would need to be a bit on symbols
indicating whether they have ever been returned by `install()` and a
version of `install()`, maybe `install_temp()`, for use in the parser
and the C side of `assign()` that returns symbols with this bit not
set. Then the GC can collect any unreachable symbols with the bit
unset.

**Comment by ltierney** [comment] 2019-10-08 17:30
I am fairly dubious about going down this road. The assumption of `ALTREP` is that code for methods will be written very carefully. In particular many methods should not run the GC or transfer control (i.e. execute a `LONGJMP`) because the C code where these methods get called may assume these things will not happen.
It is possible to suspend the GC (and this is done around calls to `DATAPTR` and a few `altstring` methods but not for others) though doing that for long periods around R code is risky. It is also possible to suspend interrupts, though again risky. Preventing jumps from errors and such is also possible but has significant issues as well.

**Comment by hpages** [comment] 2019-10-08 19:33
Thanks @ltierney  for the feedback.

Interesting to know about the symbol table not being collected. AFAICS it has never been a problem in practice. The apparent memory usage inflation I observed was in the context of running very simple/naive code forged for the sole purpose of detecting a potential memory leak in Jiefei's code.  The code I came up with for that was indeed artificial/unrealistic.

**Comment by ltierney** [comment] 2019-10-08 20:22
It does come up from time to time in the hash table context; there was an [SO question](https://stackoverflow.com/questions/31907459/remove-a-temporary-environment-variable-and-release-memory-in-r/31908506#31908506) a few years back, for example. It would  be nice to fix but never seems to make it to the top of the pile. Might have to wait until someone who needs it fixed works on it and contributes a patch.

The CHARSXP cache is in pretty good shape thanks to Seth Falcon's great work on it.

**Comment by Jiefei-Wang** [comment] 2019-10-09 16:38
Thanks @ltierney for giving us the developer's thought on ALTREP.  

I agree that an ALTREP class should not be too complicated. This package is just for fast development of a simple ALTREP class. Since we do not have control over user's code, I will add a section in vignette to highlight the things that you've pointed out to make sure users know them.

**Comment by Jiefei-Wang** [comment] 2019-10-10 15:40
Hi @hpages ,

I have changed the function `removeWrapper` to `removeCachingWrapper` and add a concrete example to show the usage of the function. Also I added a new section in vignette to talk about the concerns that we have discussed here.

**Comment by hpages** [comment] 2019-10-11 16:34
Excellent! Thank you.

**Comment by gmbecker** [comment] 2019-10-12 00:04
> Thanks @ltierney for giving us the developer's thought on ALTREP.
> 
> I agree that an ALTREP class should not be too complicated. This package is just for fast development of a simple ALTREP class. Since we do not have control over user's code, I will add a section in vignette to highlight the things that you've pointed out to make sure users know them.

Hi ,  @Jiefei-Wang, without wanting to put words in @ltierney's mouth I'm not sure that was what he meant. Things can be extremely simple in terms of R code and still do the things that Luke was saying that altrep methods shouldn't do.  Generally, R code can trigger the garbage collector, because genereally R code gets to allocate whenever it wants/needs to, can throw errors (ie LONGJMP), etc. Luke is saying that means that means that this makes R code unsafe for use in methods. Generally. 

For example, off the top of my head, I would be hard pressed to write R code that did much of anything that I could guarantee would NEVER error or trigger garbage collection. I **_might_** be able to figure out a couple of things if I sat down and thought about it really hard, but there are likely plenty of things that cant b done via R code in a way that is safe for an ALTREP method under the requirements Luke pointed out. See below, which tells R to do a gc any (or only nearly any?) time a gc could possibly be triggered. Very basic stuff. Stuff you'd need to implement, e.g., Get_element, Get_region, etc. And all of it, each tiny piece, has  _**many**_  oppportunities to trigger gc. 

```
> gcinfo(TRUE)
[1] FALSE
> gctorture(TRUE)
> x = 1:100
Garbage collection 3 = 2+0+1 (level 0) ... 
15.8 Mbytes of cons cells used (47%)
4.6 Mbytes of vectors used (7%)
Garbage collection 4 = 3+0+1 (level 0) ... 
15.8 Mbytes of cons cells used (47%)
4.6 Mbytes of vectors used (7%)
<snip a couple dozen more>
> x[3]
Garbage collection 24 = 22+1+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 25 = 23+1+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 26 = 24+1+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
<snip>
[1] 3
> c(2, 5)
Garbage collection 42 = 40+1+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 43 = 40+2+1 (level 1) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
<snip>
[1] 2 5
> 5
Garbage collection 64 = 60+3+1 (level 1) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 65 = 61+3+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 66 = 62+3+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 67 = 63+3+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 68 = 64+3+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 69 = 65+3+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
Garbage collection 70 = 66+3+1 (level 0) ... 
15.6 Mbytes of cons cells used (46%)
4.5 Mbytes of vectors used (7%)
[1] 5

```

I know that's really frustrating, after you put all this work in. And I totally get the desire to do this. It was actually in my original proposal for ALTREP as an example, you can see it in the slides, but I didn't end up doing it because Luke felt that is unsafe/a bad idea. 

The issue isn't one of letting the users know that they need to be careful, its that, from what I see, its IMPOSSIBLE (or at least so close as to be effectively the same thing) for them to actually be careful enough.

Sorry. I know it's a bummer :(
~G

**Comment by mtmorgan** [comment] 2019-10-15 21:44
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Jiefei-Wang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("AltWrapper")`. The package 'landing page' will be created at

https://bioconductor.org/packages/AltWrapper

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-10-15 21:44 UTC
Labels: 3a. accepted, OK

**Comment by mtmorgan** [comment] 2019-10-15 23:12
Just to chime in my two cents. First it's been really great to see @gmbecker and @ltierney contribute to this discussion; obviously they are the experts on ALTREP. Second, I definitely appreciate the issues and limitations of an R-based interface that both Gabe and Luke express. But third I'm really impressed with the understanding that @Jiefei-Wang has developed, the emphasis he has place on documenting the ALTREP interface, and the creative way in which this experimental package has developed -- there are only a handful of people (mostly in this thread!) with a similar level of understanding.

In the end I pressed the key that accepted this package and added it to the devel branch of Bioconductor. My secret hope is that this motivates a more robust implementation of ALTREP, perhaps one that Jiefei, Gabe, and others contribute to. Another aspect is that, since a C-level implementation is already possible, and since a C implementation can call R (as evidenced by this package!) the cat is already out of the bag. I also tried to put myself in the role of a researcher interested in exploring ALTREP, toying with new ideas for data representation and probing the limits of R's native support for ALTREP. In this role I would much rather work at the R level, and live with consequences of life on the edge, than at the C level. I also respected @hpages's interest in this package -- ALTREP provides new ideas and approaches that can change the landscape of R package development, and this package exposes those ideas to a wider audience.

I hope @gmbecker and @ltierney, especially , do not feel as though their comments have been ignored.

**Comment by gmbecker** [comment] 2019-10-16 08:12
@mtmorgan at the end of the day my views on on your reasoning for accepting the package are moot so I won't belabor any of them here.

One thing I will say is that I do hope you will seriously consider special casing the AltWrapperer package so that it remains devel only across releases of bioconductor. The reason for that is that no package which utilizes AltWrapper can ever be production-quality code as ALTREP stands now for the reasons Luke mentioned and I later elaborated on. 

It remaining devel only would allow the early experimentation you desire while still requiring a package to be converted away from the unsafe experimental framework AltWrapper provides before being published in the release branch. A safer but still permissive middle ground, so to speak.

**Comment by mtmorgan** [comment] 2019-10-16 13:53
@gmbecker one part that I was unclear on was whether the garbage collector was _always_ off during user-facing ALTREP (in which case the worst-case scenario is memory exhaustion?) or only off on specific calls?

**Comment by ltierney** [comment] 2019-10-16 15:02
On Wed, 16 Oct 2019, Martin Morgan wrote:

> 
> @gmbecker one part that I was unclear on was whether the garbage collector
> was always off during user-facing ALTREP (in which case the worst-case
> scenario is memory exhaustion?) or only off on specific calls?

I don't know what user-facing means.

At the moment the ALTREP infrastructure disables GC around calls to
Dataptr and STRSXP Elt and Set_elt methods as these are quite likely
to need to allocate. GC is re-enabled after the method returns or is
left by a jump. The infrastructure does not disable GC around others
method calls as doing so can impact performance. Some methods do not
need it, like Duplicate, since those will only be called in a context
where GC is expected. For others, like integer and real Elt methods
calling code may not have protected things, so GC need to be disabled
by a method implementer for a method that wants to allocate.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AA55UVCHYIVGL5CIIQ6TGLDQO4MHFA5CNFSM4ISPGXAKYY3PNVWWK3TUL52HS4
> DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBMSD4Q.gif]
> 
> 
>

-- 
Luke Tierney
Ralph E. Wareham Professor of Mathematical Sciences
University of Iowa                  Phone:             319-335-3386
Department of Statistics and        Fax:               319-335-3017
    Actuarial Science
241 Schaeffer Hall                  email:   luke-tierney@uiowa.edu
Iowa City, IA 52242                 WWW:  http://www.stat.uiowa.edu

**Comment by Jiefei-Wang** [comment] 2019-10-16 15:06
Hi @gmbecker and @ltierney , Thanks for your comment. It is good to know the problem and limitations of ALTREP. even though it is kind of frustrating but I believe it will benefit all the ALTREP users. Given the current status of the ALTREP, it is not a good idea to make the AltWrapper package public available and encourage people to write the `wrong` code, so Martin and I will remove the package from the repository and keep it as a GitHub project. People can still try and taste the R-level ALTREP and hopefully the package can still serve as a learning tool.
