### ISSUE TITLE
bayNorm

### ISSUE THREAD

**Issue by WT215** [Bioconductor/Contributions#878] opened 2018-09-20 08:09 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/WT215/bayNorm

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by WT215** [comment] 2018-09-26 19:19
@lshep Hello, thank you for your review, it is very helpful! I have done the following changes:

1.  I use `seq_len()` instead of `1:...`.
2.  I added bioconductor installation instructions in both README.md and vignettes:
```
source("https://bioconductor.org/biocLite.R")
biocLite("bayNorm")
``` 
Is this correct?

3.   Removed `Maintainer` in `DESCRIPTION`.
4.   Removed `LazyData: true`.
5.   The formatting of Imports, Suggests fields has been fixed.
6.   I removed `not run`  and set `eval=FALSE` for the examples in `bayNorm` function and vignette respectively.
7.  In man page, for the object `Data`, I specified that the assays slot contains the expression matrix and is named "Counts".
8.  The code has been simplified in both noisygene_detection.r and bayNorm.r. Furthermore, I further simplified the code in PRIOR_FUNCTIONS.r.
9. For the examples in vignette, I created a `SummarizedExperiment` object and then input it in the main functions.

Thank you very much!

Cheers,
Wenhao

**Comment by lshep** [comment] 2018-09-27 11:08
The installation should use BiocManager and BiocInstaller is being deprecated
```
library(BiocManager)
BiocManager::install("bayNorm")
```

Thank you for the other corrections.  I will re-review and comment back soon.

**Comment by WT215** [comment] 2018-10-03 08:16
Hi @lshep, may I ask how is the re-review going? Is it possible for bayNorm to be included in the next release? Thank you very much!

**Comment by lshep** [comment] 2018-10-04 17:08
I apologize for the delay I will have a review for you tomorrow morning EST.

**Comment by WT215** [comment] 2018-10-04 17:13
Hi @lshep No problem! In the meantime I am also fixing some small errors in the code. Thank you for your help!

**Comment by lshep** [comment] 2018-10-05 15:02
Please see comments below.

**General**
- [ ] From your description this is for single-cell RNA-seq data. The code should therefore be updated to work with SingleCellExperiment Class as well since that is the Bioconductor class structure for SingleCell. Since your code was adapted for SummarizedExperiment this shouldn't be a large task since SingleCellExperiment extends rangedSummarizedExperiment - in fact it may already
(you should test) but then the package should make note of this 

- [ ] I don't see any indication of what your algorithm is for normalization -    please provide more
  detail in the vignette and main pages on what/how the normalization is   performed. I can assume from the package name it is some sort of Bayesian   method but more details need to be provided

- [ ] There are a number of packages that analyze/normalized  single cell  data. You will   need to provide a comparison that makes your normalization method different   from existing. Doing a search of Bioconductor biocViews for normalization and   single cell the following packages are listed
AUCell, BASiCS, cellity, scater, SCnorm, scone, scran, slalom.  Especially since  some of these indicate Bayesian methods for normalization. 

**vignette:**
- [ ] For the SummarizedExperiment call,  please put SummarizedExperiment::SummarizedExperiment if you choose to hide the library load.  Else people blindly running the code will get SummarizedExperiment not found error. You might consider looking at some of the other packages above and seeing if a SingleCellExperiment object can be passed into your functions as this would be the largest audience based on your package DESCRIPTION

- [ ] The vignette seems very shallow.  It describes very briefly the main   function but there is no indication of when or what use would be benefited   from running any of the other exported functions, and you export quite a few.  If some of these are not meant to be exported and used directly that please make them internal and don't export or document.  Some description of the use and functionality of the other functions should be included as well as runnable examples - it is okay to either have them run in   the vignette or the man page but export functions need to be executed at least   once somewhere.  Since this is a normalization package some indication of   your normalization algorithm should also be included. 


Thank you.  I look forward to your comments.

**Comment by WT215** [comment] 2018-10-05 15:37
Hi @lshep, thank you for your re-review. 

Regard to your **General** opinions:

1. `bayNorm` is adapted with `SummarizedExperiment`, so do I still incorporated `SingleCellExperiment` class?
2. The algorithms and comparison between `bayNorm` and other normalization methods (like `SCnorm`) have been posted in `bioRxiv`: <a href="https://www.biorxiv.org/content/early/2018/08/03/384586">Tang <em>et al.</em> (2018). bioRxiv. </a>. We cited the paper in `README`. The vignette could be too verbose if we discussed details of algorithms there.

I will updated the `vignette` as soon as possible.

Thank you very much!

Best wishes,
Wenhao

**Comment by lshep** [comment] 2018-10-05 16:12
I would see if it is already accounted for by your support for SummarizedExperiment - since SingleCellExperiment extended SummarizedExperiment there may be nothing to be done on your part but to update the documentation saying that this class is also supported -  but if your package is designed specifically for SingleCell Data than yes making sure it works with SingleCellExperiment would be  the recommendation

If there is no way to briefly summarized the algorithms used -  I would at minimum also reference the paper in the vignette and package man page

When ready with updates don't forget to version bump for the new build report and comment back here 

Cheers!

**Comment by WT215** [comment] 2018-10-05 16:16
Hi @lshep, no problem! I will reference the paper in both vignette and package man page. I just tested the `SingleCellExperiment`, it works fine. I will also included that class as you suggested.

I will let you know once it has been ready.

Thank you for your help!

Best wishes,
Wenhao

**Comment by WT215** [comment] 2018-10-05 17:52
@lshep  Hi, may I ask how to fix this warning please?
`Warning: replacing previous import 'SingleCellExperiment::weights' by 'stats::weights' when loading 'bayNorm`

I do not have `SingleCellExperiment::weights` in my code.

Thanks a lot!

**Comment by lshep** [comment] 2018-10-05 17:58
You can ignore that warning for now -  it has to do with the naming conflict of the function -

**Comment by WT215** [comment] 2018-10-05 18:02
Hi @lshep Ok I see. Then do I just leave it for you to have another review? 

I have done the following changes:

1. Including support of `SingleCellExperiment class`
2. In `vignette` and man pages of `bayNorm.R`, I added the reference to the paper: <a href="https://www.biorxiv.org/content/early/2018/08/03/384586">Tang <em>et al.</em> (2018). bioRxiv. </a>
3. All examples are runnable except for some functions written in Rcpp. Because most of them need to be exported so that they can be included in the wrapper functions. However, for some main Rcpp functions, I also let the examples to be runnable.

Thanks a lot!

Best wishes,
Wenhao

**Comment by WT215** [comment] 2018-10-08 13:17
Hi @lshep , I have added Methods of bayNorm at the end of the vignettes. The only warning it reports is:
```
* checking whether package bayNorm can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import SingleCellExperiment::weights by stats::weights when loading bayNorm
See /Users/pkgbuild/packagebuilder/workers/jobs/878/40f8973/bayNorm.Rcheck/00install.out for details.
```

Please have a check.

Thanks a lot!

**Comment by lshep** [comment] 2018-10-11 16:35
Looking good a few more comments:

- [ ] That warning comes from importing both SingleCellExperiment and stats packages
that have a weights function.  You could either selectively import functions
from one or we will allow this warning


- [ ] The vignette only shows BetaFun, bayNorm, bayNorm_sup yet you export 15 other
functions - I would have a package man package or a section in the vignette that
briefy describes what your other functions are for. If they are not meant to be
used by the user, you can mark the documentation with the @keywords internal and
remove @export so they are not included in the NAMESPACE. 

- [ ] We recommend BiocParallel over parallel. 


**R Files**

PRIOR_FUNCTIONS.R
- [ ] You don't need to convert the SingleCellExperiment object into a
SummarizedExperiment object. **Apply this to all R functions** The functions will work the same so for example
```
library(SingleCellExperiment)
counts <- matrix(rpois(100, lambda = 10), ncol=10, nrow=10)
sce <- SingleCellExperiment(assays = list(counts = counts))
assayNames(sce)
```


- [ ] We generally like to minimize repeat code as much as possible and opt for
simplification. Something like the following could be reordered to make only one
call to AdjustSIZE_fun setting appropriate variables 
```
if (FIX_MU) {

            BB_prior <- cbind(MME_prior$MME_MU, BB_size)
            rownames(BB_prior) <- rownames(Data)
            colnames(BB_prior) <- c("MME_MU", "BB_SIZE")

            MME_SIZE_adjust <- AdjustSIZE_fun(
                BB_prior[, 2],
                MME_prior$MME_MU,
                MME_prior$MME_SIZE)
        } else {
            BB_prior <- BB_size
            rownames(BB_prior) <- rownames(Data)
            colnames(BB_prior) <- c("BB_SIZE", "BB_MU")
            MME_SIZE_adjust <- AdjustSIZE_fun(
                BB_prior[, 1],
                MME_prior$MME_MU,
                MME_prior$MME_SIZE)
        }
```
So somthing like the following
```
BB_prior <- BB_size
colnames(BB_prior) <- c("BB_SIZE", "BB_MU")
rownames(BB_prior) <- rownames(Data)
if (FIX_MU){
    BB_prior <- cbind(BB_prior, MME_prior$MME_MU)
    colnames(BB_prior) <- c("BB_SIZE", "MME_MU")
    vec <- BB_prior[,2]
}else{
   vec <- BB_prior[,1]
}
MME_SIZE_adjust <- AdjustSIZE_fun(vec,MME_prior$MME_MU,MME_prior$MME_SIZE)

```
**Apply this concept throughout all R code**  
Like there seems to be similar structure in BB_Fun too - when possible mimize
code redundency



- [ ] bayNorm and bayNorm_sup have a lot of repeated code. It would be better to
  have all similar code in one function with a wrapper for the two different
  scenerios. Again standing behind limiting the amound of repeated code in
  packages. 


When ready with updates don't forget to version bump for the new build report and comment back here

Cheers!

**Comment by lshep** [comment] 2018-10-16 14:04
I would still look at using BiocParallel eventually bu tI will not enforce its use at this time.  Cheers and welcome to Bioconductor.

**Comment by WT215** [comment] 2018-10-16 14:06
Hi @lshep , ok I will try to incorporate `BiocParallel`, thank you very much!

**Comment by WT215** [comment] 2018-10-17 08:35
Hi @lshep, I have replaced `foreach` with `BiocParallel`. Can I continue bumping the version and git push as before?

Thanks a lot!

**Comment by lshep** [comment] 2018-10-17 11:14
You could if you like.  Since the package hasn't offiically moved into our git.bioconductor.org repository yet you could and only have to push to your github repository.   
Once the issue is closed (we will do this) and added you will have to set up your remotes to point to the git.bioconductor.org server and also push there.  (instructions will be given when the package is added) and can always be found on the [git help pages](http://bioconductor.org/developers/how-to/git/).

**Comment by WT215** [comment] 2018-10-17 11:30
@lshep Great! I have done that. 

Cheers,
Wenhao

**Comment by mtmorgan** [comment] 2018-10-18 13:31
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/WT215.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"bayNorm\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bayNorm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-10-18 13:31 UTC
Labels: 3a. accepted, OK
