### ISSUE TITLE
pathwayPCA

### ISSUE THREAD

**Issue by gabrielodom** [Bioconductor/Contributions#1000] opened 2019-02-07 20:47 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gabrielodom/pathwayPCA
This is my first package submission to Bioconductor. I apologize in advance for my lack of experience.

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

Comments:
- Package size: we are cleaning up the .git/ directory now, in order to reduce the overall size of the package. We have one data file in `inst/extdata` that is 5.6Mb.
- `library()` calls within functions: because we use parallel computing architecture that is compatible across platforms, we use `clusterEvalQ(cl, library(package))`. 

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2019-02-07 20:56
Please update your package to interoperate with (accept as inputs / return as outputs) standard Bioconductor data representations][1], especially [SummarizedExperiment][2]

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses
[2]: https://bioconductor.org/packages/SummarizedExperiment

**Comment by gabrielodom** [comment] 2019-02-14 14:19
@mtmorgan Thank you for the comment. We have added a function to interface the SummarizedExperiment class with our pathway-based -Omics class.

To the reviewer: The two ERRORs I cannot fix are:
1. System Files found that should not be git tracked: pathwayPCA.Rproj
2. ERROR: Maintainer must subscribe to the bioc-devel mailing list. Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

For ERROR 1, the pathwayPCA.Rproj file is listed in .gitignore. I have used the [BFG](https://rtyley.github.io/bfg-repo-cleaner/) to remove the pathwayPCA.Rproj file from .git/. When I search for it in the .git folder, I am unable to find it.

**Comment by lshep** [comment] 2019-02-14 17:06
Thank you - 
For the remaining ERRORS:

1.  It seems like this is remedied in the last build report. 
2.  We require all package maintainers to sign up for the mailing list.  The `gabriel.odom@med.miami.edu`  must register on the mailing list.  Please check spam folders for the final confirmation as sometimes it gets marked as spam. 

I will perform a more thorough review of the package within the next week but It will be recommended to fix all WARNINGS/NOTES in the build report.

**Comment by gabrielodom** [comment] 2019-02-14 17:11
Thank you @lshep. We are still working on the package install size. Our issue thread is 
https://github.com/gabrielodom/pathwayPCA/issues/64

**Comment by lshep** [comment] 2019-03-05 15:12
**General**

- [ ] We encourage the use of  BiocParallel over parallel for parallelization
  implementation. Please explain why this was not used if not updating
- [ ] Standard Biconductor objects and classes for data should be utilized
  whereever possible instead of creating new.  Please explain why no existing
  structure could be used or extended. 
- [ ] Can this be integrated with other Bioconductor packages/input/output


**Build report**

- [ ] Normally require/library calls are not necessary in code if the proper
  packages (or select functions from packages) were imported in the
  NAMESPACE. Please investigate this WARNING 

- [ ] We strongly encourage [units tests](http://bioconductor.org/developers/how-to/unitTesting-guidelines/).  They can be helpful in debugging code
  and to ensure the code is working as intended. 

**readme**

- [ ] Add Bioconductor installation instructions as well 

**Description**

- [ ] User Authors@R (recommended) or Author:/Maintiner:  not both. 


**Namespace**

- [ ] You have exported a lot of functions. Are all these functions intended to
  be used directly by the user or are some used internally only and be removed
  as an export? 


**news**

- [ ] Should have only one news file please remove NEWS (suggested removal) or
  NEWS.md (suggested keep) 

**inst/vignette_drafts/vignette_docx**

- [ ] Does not seem like this should be included here and exposed to
  users. Please remove. Move any relevant vignettes to the vignette directory

**inst/misc_scripts**
- [ ] What are these scripts?  Again are these relevant that they should be
exposed to the user. Else remove

**inst/extdata**
- [ ] Only include data files in extdata.  Create a new `inst/scripts` directory
to contain scripts for generating the data. These scripts (either R/sudo code/or
paragraph) should indicate the source of the data and how to replicate
creation. 


**data**
- [ ] In the man pages for colonSurv_df.Rd please include the source information
for data where this subset was taken from. 


**docs/testing_files**

- [ ] What are the purpose of these directories?  They probably should not be
  git tracked?  These directories will be 'ignored' by R CMD build but still
  cloned over. The desired state is closer to only package relevant files on the
  master/git repository.  

**pathwayPCA.pdf**
- [ ] Remove this from the top level directory (git rm)


**vignette**
**Introduction_to_pathwayPCA**
- [ ] Include Bioconductor installation instructions
- [ ] If you created your own class, you show have accessor methods for common
slots of interest to avoid direct access
eg. 
```> class(ovarian_aespcOut)
[1] "aespcOut"   "pathwayPCA" "list"      
ovarian_aespcOut$pVals_df

```
Could perhaps benefit from an accessor method for pVals? 

- [ ] You perform a modification 
```
ovOutGather_df <-
  # Take in the results data frame,
  ovarian_aespcOut$pVals_df %>%
  # add the score variable,
  mutate(score = -log(rawp)) %>%
  # subset the top 20 pathways, and
  slice(1:20) %>% 
  # remove the columns we don't need
  select(-pathways, -n_tested, -rawp, -FDR_BH)
``` 
But it is unclear to me why?  Also couldn't this  be automated for the user
instead of manually run? 

**R code**

While there is a lot of it - generally seems well organized and well written.

**Comment by gabrielodom** [comment] 2019-03-06 17:43
@lshep, thank you. We are working to address these points.

**Comment by lshep** [comment] 2019-03-28 11:52
Just wanted to check in regarding progress.  The deadline for accepting new packages for this release has been announced as Wed. April 24th.

**Comment by gabrielodom** [comment] 2019-03-28 19:46
Hi @lshep, we are in the process of re-submitting this afternoon or tomorrow morning. Thank you for checking up on us!

**Comment by gabrielodom** [comment] 2019-03-28 20:53
---
title: "Response to Bioconductor Review"
author: "Gabriel Odom, Lizhong Liu, James Ban, Lily Wang, and Steven Chen"
date: "March 28, 2019"
output: html_document
---

## Introduction
We thank the Bioconductor review team, in particular Lori Shepherd, for their valuable time spent reviewing our package and for their insightful feedback. We have carefully thought about all comments and made many revisions accordingly in the revised package and documentations. We hope this resubmission address the reviewer’s concerns well.

</br>

## General Comments
**Comment**:

> We encourage the use of BiocParallel over parallel for parallelization implementation. Please explain why this was not used if not updating

**Response**: We appreciate your comment. During our package design phase, we did consider using the `BiocParallel` package due to its superb multi-machine/supercluster functionality and flexibility. However, after considerable thought, we chose to implement Snow-style parallel computing. We felt that the base `parallel` package was quite sufficient for our needs. Given that many of our package’s current users work in Windows environments, and that the pathwayPCA algorithm is not overly complex, we decided to use a simple single-machine Snow cluster. We have extensively tested our parallel computing setup on Windows, Macintosh, and Linux systems. 

**Comment**:

> Standard Biconductor objects and classes for data should be utilized whereever possible instead of creating new. Please explain why no existing structure could be used or extended.

**Response**: Thanks for your comment. In response, to make our package compatible with `SummarizedExperiment` objects, we have now added a function `SE2Tidy()` that can import a `SummarizedExperiment` object. 

**Comment**:

> Can this be integrated with other Bioconductor packages/input/output

**Response**: Yes. Our package now interfaces with the `SummarizedExperiment` package for assay data and the `rWikiPathways` package for pathway collections. 

</br>

## Build Report
**Comment**: 

> Normally require/library calls are not necessary in code if the proper packages (or select functions from packages) were imported in the NAMESPACE. Please investigate this WARNING

**Response**: This WARNING is triggered by loading a necessary package onto the Snow-style cluster suite. Per the [Introduction to `BiocParallel`](https://bioconductor.org/packages/devel/bioc/vignettes/BiocParallel/inst/doc/Introduction_To_BiocParallel.pdf) section 4.1.2 on clusters, this `library()` call would be required even with the `BiocParallel` package. I don't see a way around this.

**Comment**: 

> We strongly encourage units tests. They can be helpful in debugging code and to ensure the code is working as intended.

Response: This is an excellent suggestion. In response, we have added unit tests in the `/tests/testthat/` directory, as suggested in the Bioconductor [Unit Testing](https://bioconductor.org/developers/how-to/unitTesting-guidelines/) guidelines.

</br>

## Top-Level Files
### README.md
**Comment**:

> Add Bioconductor installation instructions as well

**Response**: We have updated the README.md file, the GitHub README, and the package home page with Bioconductor installation instructions.

### DESCRIPTION
**Comment**: 

> User Authors@R (recommended) or Author:/Maintiner: not both.

**Response**: We have removed the redundant "Maintainer" field.

### NAMESPACE
**Comment**: 

> You have exported a lot of functions. Are all these functions intended to be used directly by the user or are some used internally only and be removed as an export?

**Response**: As you suggested, we have removed a few dozen internal functions from the NAMESPACE of our package. However, in order to keep the examples we wrote for these functions (to aid in future development), we have wrapped them in a `\dontrun{}` environment. This creates a new NOTE. Please disregard this NOTE.

### NEWS.md
**Comment**:

> Should have only one news file please remove NEWS (suggested removal) or NEWS.md (suggested keep)

**Response**: As you suggested, we have removed the NEWS file and kept the NEWS.md file.

</br>

## inst/ Files
### vignette_drafts/
**Comment**:

> Does not seem like this should be included here and exposed to users. Please remove. Move any relevant vignettes to the vignette directory

**Response**: This directory has been removed.

### vignette_docx/
**Comment**:

> Does not seem like this should be included here and exposed to users. Please remove. Move any relevant vignettes to the vignette directory

**Response**: This directory has been removed.

### misc_scripts/
**Comment**:

> What are these scripts? Again are these relevant that they should be exposed to the user. Else remove

**Response**: This directory has been removed.

### extdata/
**Comment**:

> Only include data files in extdata. Create a new inst/scripts directory to contain scripts for generating the data. These scripts (either R/sudo code/or paragraph) should indicate the source of the data and how to replicate creation.

**Response**: As you suggested, we have moved all `*.R` files relevant to data generation to `inst/scripts`.

</br>

## Top-Level Directories
### docs/
**Comment**:

> What are the purpose of these directories? They probably should not be git tracked? These directories will be 'ignored' by R CMD build but still cloned over. The desired state is closer to only package relevant files on the master/git repository.

**Response**: To clarify, the `pkgdown` website-builder utility package builds [our package website](https://gabrielodom.github.io/pathwayPCA/) and stores the files for this website in the `docs/` directory.

### testing_files/
**Comment**:

> What are the purpose of these directories? They probably should not be git tracked? These directories will be 'ignored' by R CMD build but still cloned over. The desired state is closer to only package relevant files on the master/git repository.

Response (from Gabriel Odom): To clarify, I changed the directory from `tests/` to `testing_files/` so that R wouldn't run my tests every time I checked the package. I have now removed this directory from the package as you suggested. 

</br>

## Vignette Comments
**Comment**:

> Include Bioconductor installation instructions

**Response**: We have added Bioconductor installation instructions to the "Introduction to PathwayPCA" and "Supplement 1 - Quickstart Guide" vignettes.

**Comment**:

> If you created your own class, you show have accessor methods for common slots of interest to avoid direct access. eg. [1] "aespcOut" "pathwayPCA" "list" and ovarian_aespcOut$pVals_df. Could perhaps benefit from an accessor method for pVals?

**Response**: This is an excellent suggestion. As you suggested, we have added `getPathpVals()` as an accessor function for the table of $p$-values returned in objects of class `aespcOut` and `superpcOut`. The vignettes "Introduction to PathwayPCA", "Supplement 1 - Quickstart Guide", and "Supplement 4 - Methods Walkthrough" now all make use of this new accessor function.

**Comment**:

> You perform a modification
```
  ovOutGather_df <-
  ovarian_aespcOut$pVals_df %>%
  mutate(score = -log(rawp)) %>%
  slice(1:20) %>% 
  select(-pathways, -n_tested, -rawp, -FDR_BH)
```
> But it is unclear to me why? Also couldn't this be automated for the user instead of manually run?

**Response**: As you suggested, we have implemented a new function that automates this modification. The new accessor function `getPathpVals()` has functionality to select the most significant $k$ pathways, transform the $p$-values, and remove the `pathways` and `n_tested` columns.

</br>

## Miscellaneous

### Data Documentation
**Comment**: 

> In the man pages for colonSurv_df.Rd please include the source information for data where this subset was taken from.

**Response**: We have included a citation of GEO GSE17538 in the documentation for the `colonSurv_df` data object.

### PDF Manual
**Comment**:

> Remove this from the top level directory (git rm)

**Response**: The file `pathwayPCA.pdf` has been removed from the package and from git.

**Comment by lshep** [comment] 2019-04-01 14:13
Thank you. The changes look good.  Thank you for such detailed documentation and vignette sections and adding the additional sections showing its interaction with other Bioconductor packages.

**Comment by mtmorgan** [comment] 2019-04-01 15:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gabrielodom.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pathwayPCA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pathwayPCA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-04-01 15:02 UTC
Labels: 3a. accepted, VERSION BUMP REQUIRED, WARNINGS
