### ISSUE TITLE
rsemmed

### ISSUE THREAD

**Issue by lmyint** [Bioconductor/Contributions#1594] opened 2020-08-16 21:02 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lmyint/rsemmed

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment] 2020-08-24 18:58
Hello @lmyint ,

Thank you for submitting to _Bioconductor_. Overall, this was a very well written package, I only have a few minor points to make. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: Found the following hidden files and directories, they should
be removed or added to .gitignore file:
        - .travis.yml

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        - SequenceMatching

- [ ] SUGGESTION: I would almost argue that 'methods' and 'magrittr' should be
'Imports:'. Depends are usually for packages that provide essential
functionality for users of your package. There seem to be, unless I'm mistaken,
just a couple functions that are used from these packages.

## Data

- [ ] REQUIRED: The content in the 'data-raw' directory should be moved to an
'inst/script/' directory since these are scripts to obtain the 'data' files.

- [ ] REQUIRED: You should not be accessing data from the internet. There is no
guarantee that the data will always be present at this location, that users will
have access to this data, etc. You could include this 'g.rda' data file in the
'inst/extdata/' directory and have it be part of the package (as long as it
doesn't exceed 5MB in size).

## R code

- [ ] REQUIRED: 'temp.R' should be removed.

- [ ] SUGGESTION: Consider shorter lines; 74 lines are > 80 characters long.

Best,
Kayla

**Comment by lmyint** [comment] 2020-08-25 18:21
Hi @Kayla-Morrell,
Thank you for your review!

## General package development
* [x]  REQUIRED: Found the following hidden files and directories, they should
  be removed or added to .gitignore file:
  - .travis.yml
    - The travis file is now ignored with .Rbuildignore.

## DESCRIPTION
* [ ]  SUGGESTION: Consider adding these automatically suggested biocViews:
  - SequenceMatching
    - This package doesn't really fit the SequenceMatching view because it doesn't perform biological sequence alignment or matching.
* [x]  SUGGESTION: I would almost argue that 'methods' and 'magrittr' should be
  'Imports:'. Depends are usually for packages that provide essential
  functionality for users of your package. There seem to be, unless I'm mistaken,
  just a couple functions that are used from these packages.

## Data
* [x]  REQUIRED: The content in the 'data-raw' directory should be moved to an
  'inst/script/' directory since these are scripts to obtain the 'data' files.
* [ ]  REQUIRED: You should not be accessing data from the internet. There is no
  guarantee that the data will always be present at this location, that users will
  have access to this data, etc. You could include this 'g.rda' data file in the
  'inst/extdata/' directory and have it be part of the package (as long as it
  doesn't exceed 5MB in size).
    - Unfortunately the `g.rda` file is about 380MB. I'm not quite sure the best way to go about making this data available to users. I processed the original data into this form for users and want to make it available to them because this full data is the only reason they would use the package. I don't want them to have to recreate it themselves. I've looked into the [drat](https://journal.r-project.org/archive/2017/RJ-2017-026/index.html) package for hosting data packages, but it doesn't seem to fit this situation. The file is too large to host on GitHub.

## R code
* [x]  REQUIRED: 'temp.R' should be removed.
* [ ]  SUGGESTION: Consider shorter lines; 74 lines are > 80 characters long.
  - I believe that all of these longer lines are lines of text in the vignette, so is it ok to keep these lines long?

Best,
Leslie

**Comment by Kayla-Morrell** [comment] 2020-08-26 14:00
@lmyint - In order to produce a build report that reflects these changes, you need to bump the version in the DESCRIPTION file.

**Comment by lmyint** [comment] 2020-08-26 14:57
Just bumped it!

**Comment by Kayla-Morrell** [comment] 2020-08-26 16:43
@lmyint - I see the version bump pushed to the github, but since a build wasn't triggered I assume you forgot to also push to `git@git.bioconductor.org:packages/rsemmed`. Please look at the documentation [here](https://bioconductor.org/developers/how-to/git/new-package-workflow/) about setting up the upstream remote and pushing there as well.

**Comment by Kayla-Morrell** [comment] 2020-09-08 17:17
Hello @lmyint - Thank you for making the necessary changes. I have just one area that needs to be addressed in order for me to accept the package.

## inst/script

The idea behind this directory is to document very clearly how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executable code, sudo code, or a text description. A user should be able to download and roughly reproduce the file or object that is present as data.

- [ ] REQUIRED: Looking at the graph_semmed.R file, there is no indication as to where the PREDICTION.csv.gz file comes from. If you provide some source information this will be acceptable.

- [ ] REQUIRED: Looking at the g_mini.R and g_small.R files, you should not be telling users to load the g.rda data from your Google Drive. Instead, you can instruct the users to run the script in graph_semmed.R to get the g.rda file (since this is what the result of the script is). 

Best,
Kayla

**Comment by lmyint** [comment] 2020-09-12 03:40
Hi @Kayla-Morrell - I updated the description of the data availability in the vignette (in the Full data availability section) to indicate source information for the raw data (a National Library of Medicine URL). I also removed the link to Google Drive. I included an additional processing script in `inst/script` so that users can fully recreate the complete data object from the National Library of Medicine raw data.

Thank you so much for your review!

Best,
Leslie

**Comment by Kayla-Morrell** [comment] 2020-09-21 19:33
@lmyint - Thank you for making the necessary changes, I'm more than happy to accept the package now.

Best,
Kayla

**Comment by mtmorgan** [comment] 2020-09-21 20:52
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lmyint.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rsemmed")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rsemmed

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-09-21 20:52 UTC
Labels: 3a. accepted, OK
