### ISSUE TITLE
A package written for mass-spec data with abundance-dependent missing and censored values

### ISSUE THREAD

**Issue by ireneslzeng** [Bioconductor/Contributions#689] opened 2018-03-26 05:31 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/superOmics/mlm4omics

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Liubuntu** [comment] 2018-03-27 18:40
Hi @ireneslzeng , 

Thanks for your contribution to Bioconductor. Please see the build report to address all ERROR messages about:  
- package versioning. 
``` 
ERROR: Maintainer must subscribe to the bioc-devel mailing list.
Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```
- to register on the Bioc-devel mailing list.
```
ERROR: Maintainer must subscribe to the bioc-devel mailing list.
Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```

 Please also seek to address most of the NOTE messages in the report. 
- if you have your own LICENCE file on the top directory, please include it in the DESCRIPTION file. E.g., `License: GPL-2 | LICENCE`. 
- package size. Check carefully for all your data or files inside your package. The installed size of your package is 39.1Mb, which is pretty big! Make sure all files are needed and used. 
- other note messages like using "vapply" instead of "sapply", line indentation, and line length could be addressed now or in later technical review. 

Cheers, 
Qian

**Comment by ireneslzeng** [comment] 2018-04-01 10:05
Thank you for the reviewing. 
I have registered on Bioc-devel mailing list and changed the version number accordingly. 
The files are all needed , I have used the r console window to edit all documents and reduce the length. There remains a small % of lines > 80 characters. I hope to have some technical reviews regarding to these notes.

**Comment by Liubuntu** [comment] 2018-04-02 17:50
IMPORTANT: Please read the [instructions](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) for setting
up a push hook on your repository, or further changes to your
repository will NOT trigger a new build.

**Comment by ireneslzeng** [comment] 2018-04-03 03:40
Thank you. I have added another push hook on the repository. Here is the link: 
https://github.com/ireneslzeng/mlmm/settings/hooks/25504212

**Comment by Liubuntu** [comment] 2018-04-03 16:27
If you have done that already, please try bump your package version, and see if it could trigger an automatic build here. Otherwise, I couldn't get noticed with your commits. Thanks!

**Comment by ireneslzeng** [comment] 2018-04-04 02:33
I read the report, it states okay for the first platform. The other two indicate "Git clones failed"., 
Please advise any solution, thank you.

**Comment by Liubuntu** [comment] 2018-04-04 18:28
Hi @ireneslzeng , 

We have rebuilt your package manually. And it could build successfully. An Initial review will be given shortly. Thanks!

Cheers,
Qian

**Comment by ireneslzeng** [comment] 2018-04-05 02:11
Many thanks for your help and patience. 
Irene

**Comment by Liubuntu** [comment] 2018-04-12 16:41
Hi @ireneslzeng , 

Thank for your contribution to Bioconductor. Here are some issues from the initial technical review. Please seek to address all/most of them. Comment back here with any questions or if you are ready for a second review, where some additional issues could be added.

## DESCRIPTION

- Remove the `date` field (not needed).
- `License`: should usually just refer to one particular version (e.g., GPL-2)
- Add the relevant links to the GitHub repository or bug report links. e.g., under`bugReport: https://github.com/ireneslzeng/mlmm/issues` field.

## NAMESPACE

- look good.

## Vignette
- Please add a table of contents for better organization. This could be easily specified in the header. check here: https://rmarkdown.rstudio.com/html_document_format.html.
- Please add a `Introduction` section in the beginning which serves as an abstract of a research paper. e.g., to introduce the objective, models, unique functions, key points \
that distinguish it from other similar packages of your package...

- IMPORTANT: please add a section called `Installation` after `Introduction`, and show to users how to download and library this package as it is already available in Biocondu\
ctor. E.g., to use `BiocInstaller` function for downloading. ``` BiocInstaller::biocLite("mlmm")``` You can also choose to add a subsection for installing the developmental ve\
rsion from github, e.g.,```devtools::install_github("ireneslzeng/mlmm") ```

- Please add in the end of the vignette a section of `SessionInfo` for your vignette running environment. `sessionInfo()`

- Add more descriptive contents for each section.  

## MAN/
- look good.

## R/

- Please use ` <- ` instead of `=` for assignment.
- `setinitialvalues.R`. the arguments within the function definition could be only taking default values, as you used in `mlmc.R` and `mlmm.R`. `npred`, `np`... are not pred-d\
efined values here, right?

```
setinitvalues=function(npred=npred, np=np, npred_miss=npred_miss,                                                                                                               
npred_sub=npred_sub, nmiss=nmiss, nsid=nsid)                                                                                                                                    
```

### coding practices
- NOTE: Avoid sapply(); use vapply() found in files:
  stanmodels.R (line 25, column 14)
-  NOTE: Consider shorter lines; 33 lines (3%) are > 80 characters
   long.  try use `Alt+q` shortcut in your emacs session for automatic
   indentation of correct length.
- NOTE: Consider multiples of 4 spaces for line indents, 38 lines(3%)

cheers,
Qian

**Comment by Liubuntu** [comment] 2018-04-24 18:25
Hi @ireneslzeng ,

Please be aware that Bioconductor usually suggest package maintainers to reply with the technical review within ~2 weeks. Or at least show your efforts in addressing the review issues, e.g., make appropriate git commits, and bump package version to trigger the new build. Otherwise, if you feel that you are not available for a period of time to work further on your package, we will close the issue and you can open it later when you have more time for it. Thanks!

Best,
Qian

**Comment by ireneslzeng** [comment] 2018-04-25 01:05
Hi,@Liubuntu, 
Sorry about the lack of responses because I did not know if I can ask questions frequently in the issue list when all the review points are clear. Thank you for the reminding.
I have been working on all the revisions according to your comments.
I have been working through the notes on a daily basis and one of which I have discussed with rstan building team in the rstan forum.  Now, I only need to have the vignette finalized today, and one note which is created after revision of the R program that I am not sure  :grinning:  
 "Consider multiples of 4 spaces for line indents" in the .RD file , I can only change this in the roxygendised  mlmc.R program, but the R program has been edited via emac and have the right format.

notes are like these:
Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source, and vignette source...
    * NOTE: Consider multiples of 4 spaces for line indents, 13 lines(1%) are not.
    First 6 lines:
      man/mlmc.Rd:8   formula_subject, pdata, respond_dep_missing = TRUE,
      man/mlmc.Rd:9   response_censorlim = NULL, pidname, sidname, prec_prior = NULL,
      man/mlmc.Rd:10   alpha_prior = NULL, iterno = 100, chains = 3, thin = 1, seed = 125,

And the vignette dose not show the number even when I have used the number_sections: true statement
for output Pdf_document. 
Could you please advise? 
Thank you! 
Irene

**Comment by Liubuntu** [comment] 2018-04-25 20:49
Hi @ireneslzeng , 

Thanks for the update. So for the indentation, if you are using emacs, put cursor in the line which needs reformatting, simply hit the `alt+q` shortcut for a correct formatting with automatic indentations.

For the other question, try `number_sections: true` instead of `number_section: `, while these are not required. A table of content with `toc: true` is good enough. 

Best,
Qian

**Comment by ireneslzeng** [comment] 2018-04-26 04:49
@Liubuntu 
Thank you for the responses. I have revised the .RMD file, 
Please let me know if the latest version is okay, 
Irene

**Comment by Liubuntu** [comment] 2018-04-26 15:40
Hi @ireneslzeng , 

Your package is not building correctly because of the vignette. There should be 4 spaces before each entry under `Vignettes: >`. Please correct it, bump version, and see if it could build successfully. 

```
vignette: >
    %\VignetteIndexEntry{"Introduction of mlmm"}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
```

Qian

**Comment by ireneslzeng** [comment] 2018-04-27 01:14
@Liubuntu 
I have changed the .RMD file, and can successfully output the html. I am not sure why the package can not be built in the platform. 
thank you, 
Irene

**Comment by ireneslzeng** [comment] 2018-04-29 22:57
Hi, @Liubuntu 
The building reports show a similar message : Git clone Failed, but on different platforms this time. 
The successful platform has 0 error, warning or note. 
Could you please advise a solution or suggestion? Do I need to email to the bioconductor developer group?

**Comment by Liubuntu** [comment] 2018-05-01 18:29
HI @ireneslzeng , 

We kicked off a manual build of you package, and it build successfully. It seems some problem with the github for the error. And it happens now and then. I will look at your package with the new updates very soon (you could expect a 2nd review within 2 weeks at most). Thanks. 

Best,
Qian

**Comment by Liubuntu** [comment] 2018-05-07 17:42
Hi @ireneslzeng ,

Please see the 2nd review of your package. Let me know for any question. Thanks.

## Vignette

- generally, please add a white space after using "#..." for initiating sections and subsections. And consider adding a new line before R code chunk. The following sections are not showing section header or R code trunks correctly. Please go through the whole vignette and manually check if everything is working.
- Section 3, Installation. The code are not showing correctly.
- Section 4, header is not full, remove the new line after `...regression, `.
- section 4.1.1, 4.1.2 is not showing correctly.
- section 4.2.1.2, R code is not showing correctly.
- section 4.2.2.2, R code is not showing correctly.

## R

- Please use "<-" instead of "=" for assignment.
- Since you have imported "stats", so there is no need to use "stats::" whenever calling stats functions. Same as the other imported packages.
- Can you explain the argument default values that you have used inside "setinitialvalues.R"?
```
setinitvalues=function(npred=npred, np=np, npred_miss=npred_miss,
    npred_sub=npred_sub, nmiss=nmiss,nsid=nsid,
```

Regards,
Qian

**Comment by ireneslzeng** [comment] 2018-05-08 04:25
@Liubuntu ,
Thank you for the review, I will change the vignette and add info for the default values in setinitialvalue.R
Best, 

Irene

**Comment by ireneslzeng** [comment] 2018-05-15 02:29
Hi, @Liubuntu
I have revised the vignette, I built it from Rstudio and it looks okay. I have not uploaded the .html file in Git, only the .rmd file. 
The R files have changed, but the column sign needs to be there. I have tried different ways to set the library "stats", i.e. only includes stats in import , but it have some warnings messages. The current setting have no problems.  I consider it safe if I specify the library for these functions, because it will not overlap with functions having the same name from different packages, or from the global environment.

Please let me know if there are any issues, 
Thank you , 
    

Irene

**Comment by Liubuntu** [comment] 2018-05-17 15:26
Hi @ireneslzeng , 

Thanks for making the modifications. I will review it very soon. Thanks!

Best,
Qian

**Comment by Liubuntu** [comment] 2018-05-25 20:26
Hi @ireneslzeng 

All the following issues are carried over from last review. PLEASE address all of these issue before you comment back for another review. You will have a week to do that, because for the original issues, that has been almost 3 weeks. If you could not be able comply with the Bioconductor requirements as you have agreed when you created this issue, the package would not be able to go to Bioconductor. Thanks! 

## R/
- Seems that you were not able to replace the "=" with " <- " for function name assignment... 
- "setinitialvalues.R", if you do not have default values for the argument of `npred, np, npred_miss, npred_sub, mniss, nsid` as the other arguments, just leave the argument blank without trying to assign any R variables. e.g., 

```
setinitvalues=function(npred, np, npred_miss,
     npred_sub, nmiss, nsid,
    censor_lim_upp=0.008, ita_a=1, ita_b=1/10, ...
```
## vignette
This is a carry over from last review, the whole section 4 is not showing correctly!
- Section 4, header is not full, remove the new line after ...regression,.     
- section 4.1.1, 4.1.2 is not showing correctly.
- section 4.2.1.2, R code is not showing correctly.
section 4.2.2.2, R code is not showing correctly.

## import packages

Only use `stats::` when there is a function name conflict with other packages. Otherwise, just call the function name because you have already imported `stats` in your NAMESPACE!

-- Bioconductor

**Comment by ireneslzeng** [comment] 2018-05-28 07:05
Hi, @Liubuntu 
I have now addressed all the listed issues: 
"
R/
Seems that you were not able to replace the "=" with " <- " for function name assignment...
"
I overlooked one imported function, now I changed the "<-" to "=" in it. 

"setinitialvalues.R", if you do not have default values for the argument of npred, np, npred_miss, npred_sub, mniss, nsid as the other arguments, just leave the argument blank without trying to assign 
"
Thank you, I have changed the setinitialvalues. R accordingly. 

"vignette
This is a carry over from last review, the whole section 4 is not showing correctly!
"
Yes, the section 4 was section 5 in the last vignette. Now , I have changed it and upload the built vignette in the inst/doc folder as well. 

"import packages
Only use stats:: when there is a function name conflict with other packages. Otherwise, just call the function name because you have already imported stats in your NAMESPACE!"

Thanks, I have changed it as well, by using importFrom functions. 

With respects, I believe I have addressed all the issues listed.  If I have a new grand repository for our group and include this package as one component in the future, could you please advise how to process it?  

Thanks you for your patience. 

Irene

**Comment by ireneslzeng** [comment] 2018-05-31 10:21
@mtmorgan we have updated the repository. please check.

**Comment by lshep** [comment] 2018-05-31 12:17
Changing the package name prevented the above build -  I have made the appropriate adjustments on our end and you should be able to trigger builds on version bump again.  Your reviewer should have a new review for you soon.

**Comment by buddalasunil999** [comment] 2018-05-31 22:13
@Liubuntu could you please tell us why the build is failing? is it because we changed the package name or something else?

**Comment by buddalasunil999** [comment] 2018-06-01 09:00
@Liubuntu @bioc-issue-bot we fixed the error.

**Comment by buddalasunil999** [comment] 2018-06-01 09:18
@lshep @Liubuntu  we created version bump. it seems the build is not triggered. how long does it take to pick-up the changes?

**Comment by lshep** [comment] 2018-06-01 10:58
Is the webhook still initialized?  I would try re setting the webhook.

**Comment by buddalasunil999** [comment] 2018-06-01 11:06
@lshep ok, I have reset it. do I need to push version bump again to trigger the build?

**Comment by lshep** [comment] 2018-06-01 11:08
Yes please -  so we know if it is working or not -  if it is not triggered I will investigate more.

**Comment by lshep** [comment] 2018-06-01 11:13
I'll look into this.  sorry for the delay -  I will manually kick off a build of your package for now.

**Comment by ireneslzeng** [comment] 2018-06-01 11:44
The new package will delete one option in the function, others remain the
same. The new version does base on the latest version after the last review
we had from Qian.

**Comment by lshep** [comment] 2018-06-01 11:44
Sorry for the Miscellaneous version bumps -  Could you please trying doing one more?

**Comment by ireneslzeng** [comment] 2018-06-02 01:57
@lshep Thank you for that, 
Sorry about the changes. Now, the revision has made accordingly. The new version from the new repository seems to trigger.

**Comment by Liubuntu** [comment] 2018-06-06 15:59
Hi @ireneslzeng , 

Thanks for your modifications. But seems that you have misunderstood this: ``` replace the "=" with " <- " for function name assignment``` I mean to change all "=" into " <- " (make sure the two blank spaces before and after "<-")  for function or R variable assignment! See [here](http://bioconductor.org/developers/how-to/coding-style/) for some useful package coding styles (last line indicates the assignment). Which is the best practice and should be not hard to modify. 

E.g., 
```
mlmc=function(formula_completed, formula_missing, formula_censor=NULL,... 
```

should be: 
```
mlmc <- function(formula_completed, formula_missing, formula_censor=NULL,...
```
Also inside you function "mlmc.R", change this: 
```
t=terms(formula_completed)
mf=model.frame(t,pdata,na.action='na.pass')
mm=model.matrix(mf,pdata)
...
``` 
into this: 
```
t <- terms(formula_completed)
mf <- model.frame(t,pdata,na.action='na.pass')
mm <- model.matrix(mf,pdata)
...
``` 
If you can modify this, it would be ready for inclusion to Bioconductor. Thanks!

Best,
Qian

**Comment by ireneslzeng** [comment] 2018-06-08 08:56
@Liubuntu ,thank you for the comments. I modified the function name assignment symbol, please check, 
Thanks, 

Irene

**Comment by Liubuntu** [comment] 2018-06-12 14:16
Hi @ireneslzeng , 

Can you check your "setinitialvalues.R" script and do the replacement of "=" into " <- " for the value assignment inside the function? As Bioconductor core team members insist on these points as best practice, you should really do the checking manually and make sure all applicable places are modified. Otherwise, it's getting very inefficient to check back and forth for the review points I have posted.  

Qian

**Comment by ireneslzeng** [comment] 2018-06-12 23:38
@Liubuntu , I did not meant to ignore the function assignment inside the list() for initializing values using the random number generator. I have used the <- version and it caused problems in rstan , so I have to change them back to "=".  I think I will have to modify the program and not having <- in the list() and reassign them in the list. 
Thank you for the patience, is there any example of bioconductor package using rstan platform, so I can follow it as an example? I maintained our progress opening so others will know as well, 
We will maintain our package, and have registered in rstan, R project and bioconductor developer list. 
 
Irene

**Comment by superOmics** [comment] 2018-06-13 04:12
Hi, @Liubuntu, I modified the setinitialvalue function. Yes, the maintenances of the package will be our on-going efforts. 
Irene

**Comment by Liubuntu** [comment] 2018-06-15 19:05
Hi @ireneslzeng , 

It's weird that the " <- " sign would affect the use of rstan. But glad that it works now. Seems that there has been quite some misunderstandings during our communication. When you say you have modified your package and have addressed **all** the review points, I didn't expect to see those quite obvious exceptions in your package without any explanation, which has influenced the work efficiency greatly. I apologize if I have passed any unclear points also.

The package is accepted now. Please keep on your maintenance according to Bioconductor's guidelines. 

Cheers,
Qian

**Comment by ireneslzeng** [comment] 2018-06-17 08:05
@Liubuntu , thank you for your helps along the submission. It is a learning curve for us, not only about the submission but also about using rstan for making a package. 
I was confused about the symbol, because in stan, the latest version language using "=" to replace "<-". I think I mixed up the symbol when I red  the comments.  
We hope the R package will be useful for the others. 
Irene

**Comment by mtmorgan** [comment] 2018-06-19 21:45
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ireneslzeng.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"mlm4omics\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mlm4omics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-06-19 21:45 UTC
Labels: 3a. accepted
