### ISSUE TITLE
Banksy

### ISSUE THREAD

**Issue by prabhakarlab** [Bioconductor/Contributions#3201] opened 2023-10-03 21:08 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/prabhakarlab/Banksy

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by jleechung** [comment] 2023-11-11 03:21
Hi @HelenaLC, 

Thank you for helping to review our package!

I am trying to push an update to address the error raised by BiocCheck. I've followed the steps [here](https://contributions.bioconductor.org/git-version-control.html#new-package-workflow). Here are the remotes:

```
(base) ➜  Banksy git:(bioc) git remote -v
origin	git@github.com:prabhakarlab/Banksy.git (fetch)
origin	git@github.com:prabhakarlab/Banksy.git (push)
upstream	git@git.bioconductor.org:packages/Banksy.git (fetch)
upstream	git@git.bioconductor.org:packages/Banksy.git (push)
```

When trying to push to upstream, I get this error:

```
(base) ➜  Banksy git:(bioc) git push upstream
Enter passphrase for key '/Users/jlee/.ssh/id_rsa': 
FATAL: W any packages/Banksy jleechung DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

My guess is that `jleechung` does not have access rights, and that only `prabhakarlab` has access. The repository was previously under `jleechung` and then transferred to `prabhakarlab`. Do you know how to resolve this? 

Best,
Joseph

**Comment by HelenaLC** [comment] 2023-11-13 09:07
@lshep can you help?

**Comment by lshep** [comment] 2023-11-13 14:00
This should be fixed now.

**Comment by jleechung** [comment] 2023-11-13 14:23
Thanks @lshep . I have access now, but there's a hook that's rejecting the push.

```
(base) ➜  Banksy git:(bioc) git push upstream
Enter passphrase for key '/Users/jlee/.ssh/id_rsa': 
Enumerating objects: 93, done.
Counting objects: 100% (93/93), done.
Delta compression using up to 8 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (51/51), 2.13 MiB | 4.27 MiB/s, done.
Total 51 (delta 34), reused 51 (delta 34), pack-reused 0
remote: FATAL: W refs/heads/bioc packages/Banksy jleechung DENIED by fallthru
remote: error: hook declined to update refs/heads/bioc
To git.bioconductor.org:packages/Banksy.git
 ! [remote rejected] bioc -> bioc (hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/Banksy.git'
```

**Comment by lshep** [comment] 2023-11-13 14:47
If I'm reading correctly,  you are on a branch called bioc?   We do not have a branch called bioc.  You should push to the `devel` branch.  `git push upstream devel`  or in this case if you are on a different branch you would have to map bioc to devel  `git push upstream bioc:devel`  See http://contributions.bioconductor.org/git-version-control.html  item 5  which shows the concept with the generally used default of main rather than bioc.

**Comment by jleechung** [comment] 2023-11-13 14:57
Thanks for the clarification @lshep !

**Comment by HelenaLC** [comment] 2023-11-13 15:01
Thank you @lshep!!

**Comment by jleechung** [comment] 2023-11-23 17:36
Hi @HelenaLC, the build report shows one warning for `set.seed` usage. We're wondering if an exception can be made for our package. We're aware of the dangers of calling `set.seed` within a function (as discussed [here](https://support.bioconductor.org/p/110439/#:~:text=seed%20inside%20functions%20can%20quietly,BiocCheck%20to%20not%20put%20set)). However, several of the functions in `Banksy` loop over a set of parameters and run other functions which are non-deterministic - for instance, the [runBanksyPCA](https://github.com/prabhakarlab/Banksy/blob/b1a2c8bb2af06346f303637b9bba18faa1a1fe32/R/reduction.R#L50) function iterates over two parameters and runs PCA with each combination of them. To ensure that the results of each iteration can be replicated without running the entire loop, we provide an option for the user to set the seed to be used for each iteration - when the seed is set, a [message](https://github.com/prabhakarlab/Banksy/blob/b1a2c8bb2af06346f303637b9bba18faa1a1fe32/R/misc.R#L70C1-L75C1) is displayed indicating usage of a seed. **By default, no seed is set.**

**Comment by HelenaLC** [comment] 2023-11-23 19:13
If I understand correctly, I agree that a scenario like this would be a reasonable exception (granted results from each iteration are in fact returned vs. only for a set of parameters that have been selected based on said iterations), however, I am confused by the example here - to the best of my knowledge, PCA is not stochastic? Or did you perhaps mean the parameters iterated over are chosen at random?

**Comment by jleechung** [comment] 2023-11-23 23:04
Yes, the results from each iteration are returned. The parameters iterated over are fixed. Each combination of the parameters (`m` and `lambda` [here](https://github.com/prabhakarlab/Banksy/blob/b1a2c8bb2af06346f303637b9bba18faa1a1fe32/R/reduction.R#L50)) basically corresponds to a different data matrix (obtained using the `getBanksyMatrix` function [here](https://github.com/prabhakarlab/Banksy/blob/b1a2c8bb2af06346f303637b9bba18faa1a1fe32/R/reduction.R#L51)) which we then process for downstream analysis (PCA, clustering). 

The example is indeed confusing! You are right that PCA is indeed deterministic, but the `irlba` implementation has some randomness. In particular the signs of the PC scores are arbitrary (see the example below). 

For clustering, we use the leiden algorithm, which also has some randomness. The option to set the seed ensures that the cluster labels corresponding to each parameter combination can be reproduced without re-running everything else.

<details>
<summary>A minimal example</summary>

```r
> # Generate a random matrix
> set.seed(0)
> nrow = 100
> ncol = 100
> x = matrix(rnorm(nrow * ncol), nrow=nrow, ncol=ncol)
> 
> library(irlba)
> 
> # 1st seed
> set.seed(0)
> pca1 = prcomp_irlba(x)
> pca1$sdev
[1] 1.962165 1.880813 1.829245
> head(pca1$x)
           PC1         PC2         PC3
[1,]  1.030909  0.91192811 -0.95235086
[2,]  3.695931  0.21370964 -0.01640296
[3,] -1.999539 -0.08252353 -3.09563458
[4,] -2.227486  2.24713378  0.82003709
[5,] -3.267269  1.23008979 -1.26974827
[6,]  1.485216  2.34388876 -1.50597179
> 
> # 2nd seed
> set.seed(1)
> pca2 = prcomp_irlba(x)
> pca2$sdev
[1] 1.962165 1.880813 1.829245
> head(pca2$x)
           PC1         PC2         PC3
[1,] -1.030909 -0.91192811  0.95234265
[2,] -3.695931 -0.21370964  0.01641001
[3,]  1.999539  0.08252353  3.09564828
[4,]  2.227486 -2.24713378 -0.82003191
[5,]  3.267269 -1.23008979  1.26973306
[6,] -1.485216 -2.34388876  1.50595649
> 
```

</details>

**Comment by HelenaLC** [comment] 2023-11-27 08:48
# other 

- [ ] in the README, please include Bioc installation instructions using `BiocManager::install()`

# DESCRIPTION

- [ ] consider adding a `BugReports:` fields pointing to https://github.com/prabhakarlab/Banksy/issues

- [ ] please update R version dependency to >= 4.3.0; Bioc 3.19, and thus the package, will not be installable with older software

# vignette

- [ ] `eval=FALSE` flags, or equivalent tricks in markdown) undermine the benefit of vignettes and are generally not allowed (see [here](https://contributions.bioconductor.org/docs.html?q=eval=f#vignettes)); `BiocCheck()` currently warns that 36/54 = 65% of chunks or unevaluated

- [ ] we encourage the use of `BiocStyle` for formatting with `html_document` as rendering target (see [here](https://contributions.bioconductor.org/docs.html?q=biocst#vignettes))

# documention

- [ ] please provide provenance information for any example data; specifically, a reference/online source for `hippocampus` and a script under `inst/script` for how the synthetic `rings` data were generated (see [here](https://contributions.bioconductor.org/docs.html?q=script#doc-inst-script))

- [ ] consider adding a package *.man*/help page (`?Banksy`), e.g., listing key resources/references, summarizing the packages key purpose/functionality, demonstrating a quick workflow, hyperlinking to corresponding functions etc.

- [ ] I would appreciate some detail on methodology, a reference etc. in the corresponding functions' documentation. For example, "return BANKSY matrix" and "compute component neighborhood matrices" does not give much of an idea what is being done here; I vaguely recall seeing the preprint (I think?), and it would be nice to get a brief `@details` section saying i) how, for example, spatial coordinates are incorporated in the embedding, or anything else a given function might do (in terms of methodology), and ii) the effect different parameters might have on this. All that can be very brief with a link to an external resource, but it would be nice to have it in the function documentation where most will look.

# code

- [ ] when functions expect a specific data structure (e.g., a `SpatialExperiment` is expected, `computeBanksy()` has been run etc.), I'd encourage implementing some basic validity checks (at the very top of a function's body). Currently, there is no checks at all (e.g., whether or not the input is a SE/SCE/SPE), which may result in hard-to-interpret errors, especially for less programmatically inclined users. For `Banksy`-specific things, you'd might also like to check all needed slots exists.

- [ ] related to the above: it would be sensible to implement some minimal argument checks in order to prevent (potentially heavy) computations from being carrier out, only for the function to fail downstream for stupid reasons (like a typo, misinterpretation of an argument etc.); e.g., `verbose` is a length-one logical value, an argument is a scalar numeric or integer etc.

- [ ] `clusterBanksy()` lists 4 choices for `algo`, but only Leiden is implemented.

- [ ] nothing wrong, just if that's useful: consecutive `if-else-` statements on character strings such as *computation.R* lines 293+ can nicely written using `switch()`, e.g.,
```
switch(spatial_mode,
    rNN_gauss={...},
    kNN_rank={...},
    ...)
```
- [ ] related to the above: when a function argument expects a  character string that matches a list of predefined choices, this is typically done using `match.arg()` early on (defaults to the first) and listing choices in the function definition; this i) lists possible choices directly in the function doc/argument auto-complete, ii) automatically gives an informative error when an invalid values is given, and iii) prevents part of the function running when it will eventually fail, e.g., ...
```
computeNeighbors <- \(...,
    spatial_mode=c("kNN_median", "rNN_gauss", "kNN_rank", ...))
{
    spatial_mode <- match.arg(spatial_mode)
    ...
}
```

**Comment by lshep** [comment] 2023-12-27 14:35
@prabhakarlab may we expect changes addressing the review comments above soon?

**Comment by jleechung** [comment] 2023-12-27 14:39
Yes, we will do so latest by the first week of January. Thank you!

**Comment by jleechung** [comment] 2024-01-03 18:45
Thank you for the review, @HelenaLC. We have made the necessary changes; the remaining warning comes from `set.seed` usage. Please see below for responses to points of significance.

## Other

- [x] _in the README, please include Bioc installation instructions using_ `BiocManager::install()`

## DESCRIPTION
- [x] _consider adding a BugReports: fields pointing to_ https://github.com/prabhakarlab/Banksy/issues

- [x] _please update R version dependency to >= 4.3.0; Bioc 3.19, and thus the package, will not be installable with older software_
- Updated to >= 4.4.0. 

## Vignette
 - [x] _eval=FALSE flags, or equivalent tricks in markdown) undermine the benefit of vignettes and are generally not allowed (see [here](https://contributions.bioconductor.org/docs.html?q=eval=f#vignettes)); BiocCheck() currently warns that 36/54 = 65% of chunks or unevaluated_

- Three of the four vignettes now evaluate all their chunks. The last vignette (`domain-segment.Rmd`) utilises a large, external dataset - due to size / runtime (for R CMD check time limit for vignettes) constraints we use `eval=FALSE` and stash only the clustering results. 

- [x] _we encourage the use of BiocStyle for formatting with html_document as rendering target (see [here](https://contributions.bioconductor.org/docs.html?q=biocst#vignettes))_

## Documention
- [x] _please provide provenance information for any example data; specifically, a reference/online source for hippocampus and a script under inst/script for how the synthetic rings data were generated (see [here](https://contributions.bioconductor.org/docs.html?q=script#doc-inst-script))_

- We have added provenance information for the example datasets; these are documented at the respective help pages, `?rings` and `?hippocampus`. For `rings`, a script is provided at `inst/script`. For `hippocampus`, we refer users to our preprint - we will update this link once the paper is out.  

- [x] _consider adding a package .man/help page (?Banksy), e.g., listing key resources/references, summarizing the packages key purpose/functionality, demonstrating a quick workflow, hyperlinking to corresponding functions etc._
- We have now added a main package [help page](https://github.com/prabhakarlab/Banksy/blob/9f71260088ea1e80a7a23f82f7b49a3efd18a0c9/man/Banksy-package.Rd#L3).

- [x] _I would appreciate some detail on methodology, a reference etc. in the corresponding functions' documentation. For example, "return BANKSY matrix" and "compute component neighborhood matrices" does not give much of an idea what is being done here; I vaguely recall seeing the preprint (I think?), and it would be nice to get a brief @details section saying i) how, for example, spatial coordinates are incorporated in the embedding, or anything else a given function might do (in terms of methodology), and ii) the effect different parameters might have on this. All that can be very brief with a link to an external resource, but it would be nice to have it in the function documentation where most will look._

- We have added `@details` sections in the documentation for the 'main' functions (`computeBanksy`, `getBanksyMatrix`, `runBanksyPCA|UMAP` and `clusterBanksy`), and added more detail to the argument descriptions. See for instance [here](https://github.com/prabhakarlab/Banksy/blob/9f71260088ea1e80a7a23f82f7b49a3efd18a0c9/R/computation.R#L4). 

## Code

- [x] _when functions expect a specific data structure (e.g., a SpatialExperiment is expected, computeBanksy() has been run etc.), I'd encourage implementing some basic validity checks (at the very top of a function's body). Currently, there is no checks at all (e.g., whether or not the input is a SE/SCE/SPE), which may result in hard-to-interpret errors, especially for less programmatically inclined users. For Banksy-specific things, you'd might also like to check all needed slots exists._

- The code should be relatively robust to SE/SCE/SPE classes; the function where this is most relevant is the `computeBanksy` function, where the spatial coordinates need to be retrieved. We do this in the [`getLocs` helper](https://github.com/prabhakarlab/Banksy/blob/9f71260088ea1e80a7a23f82f7b49a3efd18a0c9/R/computation.R#L315), which extracts the spatial coordinates given the input data class. This helper is called near the [top of the function](https://github.com/prabhakarlab/Banksy/blob/9f71260088ea1e80a7a23f82f7b49a3efd18a0c9/R/computation.R#L108) before any heavy computation. 

- As for other functions, we also implement checks that throw error messages detailing what is expected of the input, and what commands should be run to rectify the error (for instance, [here](https://github.com/prabhakarlab/Banksy/blob/9f71260088ea1e80a7a23f82f7b49a3efd18a0c9/R/computation.R#L231) and [here](https://github.com/prabhakarlab/Banksy/blob/9f71260088ea1e80a7a23f82f7b49a3efd18a0c9/R/cluster.R#L297)). 

- [x] related to the above: it would be sensible to implement some minimal argument checks in order to prevent (potentially heavy) computations from being carrier out, only for the function to fail downstream for stupid reasons (like a typo, misinterpretation of an argument etc.); e.g., verbose is a length-one logical value, an argument is a scalar numeric or integer etc.

- We have now implemented argument checks for the main functions (with `stopifnot`, for instance, [here](https://github.com/prabhakarlab/Banksy/blob/9f71260088ea1e80a7a23f82f7b49a3efd18a0c9/R/computation.R#L145)). 

- [x] clusterBanksy() lists 4 choices for algo, but only Leiden is implemented.

- Thank you for catching this, we have now implemented the other algos. 

- [x] nothing wrong, just if that's useful: consecutive if-else- statements on character strings such as computation.R lines 293+ can nicely written using switch(), e.g.,
```
switch(spatial_mode,
    rNN_gauss={...},
    kNN_rank={...},
    ...)
```

- We have now implemented `switch` where applicable (with the `spatial_mode` argument in `computeBanksy`, and the `algo` argument in `clusterBanksy`). 

- [x] related to the above: when a function argument expects a character string that matches a list of predefined choices, this is typically done using match.arg() early on (defaults to the first) and listing choices in the function definition; this i) lists possible choices directly in the function doc/argument auto-complete, ii) automatically gives an informative error when an invalid values is given, and iii) prevents part of the function running when it will eventually fail, e.g., ...
```
computeNeighbors <- \(...,
    spatial_mode=c("kNN_median", "rNN_gauss", "kNN_rank", ...))
{
    spatial_mode <- match.arg(spatial_mode)
    ...
}
```

- Similarly, we have implemented `match.arg` where applicable.

**Comment by HelenaLC** [comment] 2024-01-09 11:44
Apologies for the (holiday-)delay... Fantastic, thank you for addressing these thoroughly! Two minor comments or, rather, room for improvement/learning in the future. But happy to accept as is and you can address these later, perhaps once the package builds on the Bioc devel server.

- pre-allocating and filling (unless really necessary, e.g., because there are side-effects), e.g., `for (i in ...) x[i] <-`, should preferably written using `apply`, `vapply` or `lapply`; e.g., *cluster.R* lines 630+ (see [here](https://contributions.bioconductor.org/r-code.html?q=vect#pre-allocate-and-fill-if-iterations-are-necessary))

- nothing 'wrong', but note that `match.arg` does not require specifying `choices` when they are already listed in the function definition; e.g., `compareClusters` function in *cluster.R* (`clusterBanksy` does this already)

**Comment by jleechung** [comment] 2024-01-09 12:48
Thank you @HelenaLC, we will address those points down the road. Appreciate your time and effort in the reviews!

**Comment by lshep** [comment] 2024-01-09 12:50
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/prabhakarlab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Banksy")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Banksy

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-01-09 12:50 UTC
Labels: 3a. accepted, WARNINGS
