### ISSUE TITLE
weitrix

### ISSUE THREAD

**Issue by pfh** [Bioconductor/Contributions#1421] opened 2020-03-17 04:49 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pfh/weitrix

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by pfh** [comment] 2020-03-24 22:43
Hello @hpages ,

There's a question about data representation in this package that I'd really like your advice on. One of the things I want to do with this package is define how to store a matrix with precision weights, using the modern SummarizedExperiment representation. Since there are several possible meanings of "weights", I want the user to have to explicitly mark the weights as having a particular interpretation (compatible with limma and lm). [Some discussion of this on the support site.](https://support.bioconductor.org/p/117018/)

The way I've currently done this is by setting some metadata within a SummarizedExperiment. A downside is the result does not print itself in way that makes it obvious that it's a special type of SummarizedExperiment. An alternative would be to define a new subclass, but then this package couldn't be used with existing subclasses of SummarizedExperiment such as SingleCellExperiment. What do you think?

**Comment by hpages** [comment] 2020-04-16 04:08
Sorry for the late answer on this.

I don't have a good answer. A compromise between using a SummarizedExperiment object tagged with metadata and defining a new SummarizedExperiment subclass would be to define a SingleCellExperiment subclass. From a purely technical point of view it doesn't hurt to derive a more specialized class like SingleCellExperiment, instead of deriving SummarizedExperiment, since an SingleCellExperiment derivative _is_ still a SummarizedExperiment object in the sense that it will be accepted everywhere a SummarizedExperiment object is expected (`is(sce, "SummarizedExperiment")` is TRUE on a SingleCellExperiment). The only thing is that the additional functionality available for SingleCellExperiment objects won't be used in your most generic workflow. So it's not a super clean design choice either and it could confuse those of your users who have data not related to single-cell experiments.

Anyway, I wish you had sorted this earlier by asking on the bioc-devel mailing list (the primary place for questions about package development) before submitting.

**Comment by pfh** [comment] 2020-04-18 01:05
My apologies.

Deriving from SingleCellExperiment would rule out using it with any other classes derived from SummarizedExperiment. Also SingleCellExperiment has a lot of features I'm not using (assays with expected meanings, size factors, dimensionality reductions of a particular format), and I wouldn't want to set up an expectation that they would be supported. This package is meant to be agnostic about what sort of data it is.

How about we proceed with the existing design?

**Comment by hpages** [comment] 2020-04-21 09:53
Your objections to the solution that would consist in deriving a new class from SingleCellExperiment make a lot of sense. I think that your current approach based on a plain SummarizedExperiment object is actually the best way to go. It's true that the object does not print itself in way that makes it obvious that it's a special type of SummarizedExperiment but that's a minor issue.

I took a quick look at the package. It is well documented and the implementation is very clean. Thanks for this contribution to the project!

Cheers,
H.

**Comment by hpages** [comment] 2020-04-21 10:06
oops, I went too fast, sorry. `R CMD check` actually gives me an error (not sure why this was not caught by the Single Package Builder):
```
* checking examples ... ERROR
Running examples in ‘weitrix-Ex.R’ failed
The error most likely occurred in:

> ### Name: components_seq_scree
> ### Title: Proportion more variance explained by adding components one at a
> ###   time
> ### Aliases: components_seq_scree components_seq_screeplot
> 
> ### ** Examples
> 
> comp_seq <- weitrix_components_seq(simwei, 4, verbose=FALSE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘bplapply’ for signature ‘"list", "NULL"’
Calls: weitrix_components_seq ... weitrix_components -> fit_all_rows -> bplapply -> <Anonymous>
Execution halted
```
A quicker/easier way to reproduce is by starting R, loading the package, then:
```
> example(components_seq_scree)

cmpn__> comp_seq <- weitrix_components_seq(simwei, 4, verbose=FALSE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘bplapply’ for signature ‘"list", "NULL"’
```
Please address and bump the version so we'll get a new build from the SPB.

Thanks,
H.

**Comment by pfh** [comment] 2020-04-22 11:47
Ah, I see what's happened. You made DelayedArray no longer parallel by default. That does seem sensible given how flaky parallel processing can be, but I wasn't expecting `getAutoBPPARAM()` to return `NULL`.

I do want weitrix to be parallel by default, as the `weitrix_components()` function is rather slow otherwise, so it now uses `BiocParallel::bpparam()`.

**Comment by hpages** [comment] 2020-04-23 17:28
I see. Thanks for the quick fix!

**Comment by mtmorgan** [comment] 2020-04-23 23:00
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pfh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("weitrix")`. The package 'landing page' will be created at

https://bioconductor.org/packages/weitrix

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-23 23:00 UTC
Labels: 3a. accepted, OK
