### ISSUE TITLE
syntenet

### ISSUE THREAD

**Issue by almeidasilvaf** [Bioconductor/Contributions#2682] opened 2022-05-31 06:53 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/almeidasilvaf/syntenet

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by HelenaLC** [comment] 2022-06-17 04:59
Hi! Here a first round of comments - overall, I believe the package is already in good shape. Please post back with how/if/why different points have/not been addressed. I will try to get another reviewer to cover the cpp portion. 

**data**

- (Picking one example, but this applied to various data)  
The doc for `edges` states that *"The object was created using*  
*the example code, exactly as described in the vignette."*  
But this is not a real data description nor intuitive to understand  
(at least for me): searching for "edge" in the vignette leads to `net`,  
which turns out to match `edges`, but variable names are different.
  - You might consider including the code to generate  
    the object inside the respective documentation examples  
    (perhaps *as is*, if it is fast, and commented out otherwise?)
  - In any case, please give a more thorough description of the object  
  (i.e., similar to what is described in the vignette, but on the man page)

**vignette**

- Rather than using cursive, you can highlight / hyperlink package names using  
\`r BiocStyle::Biocpkg('...')\` (similar commands exist for GitHub, CRAN etc.)

- Would be nice to fix some missing function/package name syntax highlighting  
(e.g., line 109: AAStringSet; 111: GRangesList or CompressedGRangesList;  
263: CliquePercolation; 283: hclust; 444: treeio; 445: ggtree; others?)

- Sorry, super minor, but the code in line 351 isn't so  
pleasing to read. Perhaps this could be formatted as:

```r
idx <- rownames(pgs$profile_matrix) %in% gs_clusters$Cluster
pgs$profile_matrix <- pgs$profile_matrix[idx, ]
```

- I understand the plot generated by `plot_network()` in line 383 is interactive,  
however, it is initially cut off at the borders as clusters are very far apart  
(unless I zoom out, which took me a moment to realize). Could this be fixed  
somehow, either using .Rmd chunk options or function arguments?

**R**

- In `binarize_and_transpose()` (*microsynteny-based_phylogeny.R*):  
Might be worth adding basic argument validity checks  
in order to avoid unexpected behavior downstream, e.g.,  

```r
M <- profile_matrix
if (!is.null(M)) {
  # not sure if NAs should/n't not be valid,
  # so that might be something else to include here
  stopifnot(
    # should be a numeric matrix
    is.matrix(M), is.numeric(M), 
    # with non-negative integer values
    M >= 0, M == round(M))
}
```

Currently, anything can go in and come out:

```r
# you're setting > 1 to 1,  but this doesn't
# guarantee there'll be only 0s and 1s
> binarize_and_transpose(0.9)
     [,1]
[1,]  0.9
> binarize_and_transpose(-1)
     [,1]
[1,]   -1
# any letter > 1 will give TRUE
# b/c 1 is converted to character
> binarize_and_transpose("x")
     [,1]
[1,] "1" 
```

This, in fact, applied to various functions/arguments, where random inputs  
(and sometimes even the default arguments) give unintelligible errors.  
The key motivation (I think) to have argument validity checks in place  
is that you (the developer) can control the message users receive,  
ideally giving instructions what's wrong/what to do.  

- In the example of `find_GS_clusters()` (*phylogenomic_profiling.R*),  
there seems to be an annotation missing? This currently passes silently.  
Perhaps the function could give a `message()` to make users aware of this?

```r
> dim(profile_matrix)
[1] 2551   25
> dim(species_annotation)
[1] 24  2
> setdiff(
    colnames(profile_matrix), 
    species_annotation$Species)
[1] "hlu"
```

- The code reads well overall, however, there are some inconsistencies  
here and there that would be nice to consolidate (e.g., 4-space/tab  
indentation vs. vertical alignment; some missing spaces after commas;  
perhaps some additional linebreaks when characters exceed 80 in a line etc.)

- In `species_id_length()` (*utils.R*), the triplicated code could be written as:

```r
# could easily increase to higher length here
# if that could be relevant in certain cases
for (n in seq(3, 5)) { 
    abbrev <- lapply(nam, substr, 1, n)
    count <- table(unlist(abbrev))
    if (!any(count > 1)) break
}
return(n)
```

- In line 114 of `interspecies_synteny()` (*utils_synteny.R*):  
  - Why the `suppressWarnings()`? This gives a NOTE in the build report,  
and I think is not required as you're just creating a vector, no?
  - Again, some argument checks would help avoid uninformative errors.  
  The function's default `blast_inter = annot_list = NULL`, which fails.  
  In general: If there are required arguments, the function definition  
  should not provide default values (that result in an error)  
  as to make clear these must be provided by the user.

**unit test coverage**

Looks very good overall! Perhaps some tests could be added for  
`infer_microsynteny_phylogeny()` in *microsynteny-based_phylogeny.R* and  
`run_diamond()` in *synteny_detection.R*; these currently have zero coverage.

```r
> devtools::test_coverage()
syntenet Coverage: 85.29%
R/microsynteny-based_phylogeny.R: 40.62%
R/synteny_detection.R: 50.00%
R/dataviz.R: 71.88%
R/utils.R: 81.36%
src/mcscanxr.cpp: 89.34%
R/data_preprocessing.R: 97.30%
R/phylogenomic_profiling.R: 100.00%
R/utils_synteny.R: 100.00%
src/mcscanxr.h: 100.00%
```

**Comment by almeidasilvaf** [comment] 2022-06-19 10:49
Hi, @HelenaLC. Thank you very much for the detailed review. I really appreciate your time. Here are my replies to each of your points:

- data

> (Picking one example, but this applied to various data)
The doc for edges states that "The object was created using
the example code, exactly as described in the vignette."
But this is not a real data description nor intuitive to understand
(at least for me): searching for "edge" in the vignette leads to net,
which turns out to match edges, but variable names are different.
You might consider including the code to generate
the object inside the respective documentation examples
(perhaps as is, if it is fast, and commented out otherwise?)
In any case, please give a more thorough description of the object
(i.e., similar to what is described in the vignette, but on the man page)

Agreed. I added more details to the man page for these objects that were created using the vignette code. I have also included the code to create `edges` in inst/script. The code to recreate all other objects were already there.

- vignette

> Rather than using cursive, you can highlight / hyperlink package names using
`r BiocStyle::Biocpkg('...')` (similar commands exist for GitHub, CRAN etc.)

Done. For references to syntenet itself, I included `BiocStyle::Githubpkg()`. As soon as the package is on Bioc, I will change it to `BiocStyle::Biocpkg()`.

> Would be nice to fix some missing function/package name syntax highlighting
(e.g., line 109: AAStringSet; 111: GRangesList or CompressedGRangesList;
263: CliquePercolation; 283: hclust; 444: treeio; 445: ggtree; others?)

Done. For package names, I included `BiocStyle::<repo>pkg`. For classes names (e.g., AAStringSet, GRangesList), I included highlights with backticks (e.g., `AAStringSet`).

> Sorry, super minor, but the code in line 351 isn't so
pleasing to read. Perhaps this could be formatted as:

Done. Thank you for the suggestion. I changed the code accordingly.

> I understand the plot generated by plot_network() in line 383 is interactive,
however, it is initially cut off at the borders as clusters are very far apart
(unless I zoom out, which took me a moment to realize). Could this be fixed
somehow, either using .Rmd chunk options or function arguments?

Done. I made it look better by changing the repulsion of the nodes, so that clusters do not repel each other too much. The optimal solution would be to increase the window size, but then the vignette gets too big and the package exceeds the size limit.

- R

> In binarize_and_transpose() (microsynteny-based_phylogeny.R):
Might be worth adding basic argument validity checks
in order to avoid unexpected behavior downstream, e.g.,

Done. Thank you for the suggestion. I included your code with some modifications. `stopifnot()` should be avoided, as its error messages are not actually helpful. I replaced it with `if()` and `stop()` with more clear error messages. However, I must mention that this check was a bit silly, as the only way users can get the profile matrix is by running `syntenet::phylogenomic_profile()`. I basically added a check for an object that was created by another function from the same package.

> This, in fact, applied to various functions/arguments, where random inputs
(and sometimes even the default arguments) give unintelligible errors.
The key motivation (I think) to have argument validity checks in place
is that you (the developer) can control the message users receive,
ideally giving instructions what's wrong/what to do.

Done. I included three helpers in utils.R to check if some arguments match the expected class. 

> In the example of find_GS_clusters() (phylogenomic_profiling.R),
there seems to be an annotation missing? This currently passes silently.
Perhaps the function could give a message() to make users aware of this?

Done. I included the message, but users are not actually required to input annotations for each species. For instance, if users have the families for each species, but a particular family has only 1 species, I wouldn't call a cluster that only appers in this 1 species as "group-specific". I would skip this species in the annotation data frame, as it is not very informative.

> The code reads well overall, however, there are some inconsistencies
here and there that would be nice to consolidate (e.g., 4-space/tab
indentation vs. vertical alignment; some missing spaces after commas;
perhaps some additional linebreaks when characters exceed 80 in a line etc.)

Done. I tried my best to fix them, but that's a hot topic. If I could choose, I would always use tab indentation vs vertical alignment, fill my functions with comments, leave empty lines (what people call "letting the code breathe"), etc. However, BiocCheck throws a note for functions longer than 50 lines (if I am not mistaken). I think that should be abolished. Because of this NOTE, what many Bioc developers do (myself included) is to use vertical alignment sometimes to avoid making the function longer, and not use spaces after commas in some lines to avoid exceeding the 80 limit (another NOTE in BiocCheck). At the end of the day, these NOTES in BiocCheck make developers write less readable code. That's food for thought for the Bioc core team. Perhaps increasing the function size limit to 100 lines?

> In species_id_length() (utils.R), the triplicated code could be written as:

Done. Thank you very much for the suggestion. 

> In line 114 of interspecies_synteny() (utils_synteny.R): Why the suppressWarnings()? This gives a NOTE in the build report,
and I think is not required as you're just creating a vector, no?

No. That's odd. When I was developing this package, GenomicRanges threw a WARNING saying that we cannot combine GRanges objects with different seqlevels. However, I updated GenomicRanges recently and it doesn't throw the WARNING anymore. Anyway, a NOTE doesn't prevent the package from passing the build report. If I remove suppressWarnings() and the developers of GenomicRanges decide to include that WARNING again, the package would fail. Better not to count on them.

> Again, some argument checks would help avoid uninformative errors.
The function's default blast_inter = annot_list = NULL, which fails.
In general: If there are required arguments, the function definition
should not provide default values (that result in an error)
as to make clear these must be provided by the user.

Done. See my answer to the similar request above.

> Looks very good overall! Perhaps some tests could be added for
infer_microsynteny_phylogeny() in microsynteny-based_phylogeny.R and
run_diamond() in synteny_detection.R; these currently have zero coverage.

Thank you. These wrapper functions that call external software have unit tests, but they are only executed if the softwares are installed.

**Comment by HelenaLC** [comment] 2022-06-20 09:58
Nice. Thanks for your prompt addressing of these points! Regarding your comments/thoughts on `BiocCheck`: I feel you in a way. However, 

I think that the 80-character limit should seldom pose an issue and be addressed by additional linebreaks after arguments vs. omitting spaces. And, I'd rather live with NOTEs on exceeding the 50-line limit vs. omitting empty lines and thorough commenting. 

In the end, there's a reason these are NOTEs (not WARNINGs) that, I'd argue, aim at bringing developers' attention to something they might *consider* changing according to their own judgement. As you mentioned: If a function is 100 lines long as a result of "room to breathe" and comments - go ahead! But if it is for a lack of factorisation - maybe rethink its design. 

As you rightly pointed out: it's a hot topic; there are probably good arguments both ways! I think you'd be most welcomed to bring your thoughts to the Bioc community Slack channel - even just briefly pitching an informal discussion - to perhaps hear some more "convincing" arguments for / reasoning behind the current check choices (from both core team and the user/developer community).

In any case, happy to accept `syntenet`. *Though package `treeio` is still missing syntax highlighting in line 449 of the vignette ;)

**Comment by lshep** [comment] 2022-06-28 12:21
@HelenaLC  Please don't close packages that are accepted.  We need the packages open with the accepted label to find them to add to the daily builder manifest.

**Comment by lshep** [comment] 2022-06-28 12:27
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/almeidasilvaf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("syntenet")`. The package 'landing page' will be created at

https://bioconductor.org/packages/syntenet

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-06-28 12:27 UTC
Labels: OK, 3a. accepted
