### ISSUE TITLE
animalcules

### ISSUE THREAD

**Issue by anfederico** [Bioconductor/Contributions#1052] opened 2019-03-21 18:39 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/compbiomed/animalcules

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2019-03-21 18:54
please provide a decent Description: of your package in the DESCRIPTION file, and in the vignette a proper abstract (if you're going to have one) and text in addition to code chunks to provide a literate exposition on your package use. Post a comment here when you have addressed these basic Bioconductor requirements.

**Comment by anfederico** [comment] 2019-03-22 00:14
Sorry about that, should be all set now.

**Comment by jasonzhao0307** [comment] 2019-03-22 15:20
@Kayla-Morrell Hey Kayla, we need your help on this error ("appending gaps is not supported") here. So we run this function in the vignette normally in our system, but it keeps failing in the test, I'm wondering if this is related to the unstable R 3.6?

**Comment by Kayla-Morrell** [comment] 2019-03-22 17:56
@jasonzhao0307 We seem to be seeing this error with many of our packages due to a recent modification to S4Vectors (version 0.21.3). We are working on this issue and it's our hope to have it fixed soon.

**Comment by jasonzhao0307** [comment] 2019-03-24 03:21
@Kayla-Morrell Would you please tell us when this could be fixed? Thank you!

**Comment by jasonzhao0307** [comment] 2019-03-26 16:28
@Kayla-Morrell Hi Kayla, we've tried to commit again, so the previous error disappeared, but another DEseq2 related error showed up: "logical subscript contains NAs"

**Comment by anfederico** [comment] 2019-04-03 17:47
@Kayla-Morrell Could you help us with this? We'd like to reopen the submission.

**Comment by Kayla-Morrell** [comment] 2019-04-03 17:50
@anfederico Please version bump to be sure a new build is initiated.

**Comment by anfederico** [comment] 2019-04-03 17:50
@Kayla-Morrell Thanks

**Comment by Kayla-Morrell** [comment] 2019-04-10 15:38
Hello @anfederico,

Thank you for submitting to _Bioconductor_. Please see the initial review of your package below. Comment back here with updates that have been made and when the package is ready for a re-review. Please keep in mind the deadline to accept packages into this release cycle is 4/24, therefore changes should be made in a timely manner so as to give enough time for a re-revew and any additional changes.

# General package development #

*R CMD BiocCheck*

Incomplete final line in inst/shiny/utils/ui_util.R

Consider shorter lines, 157 lines are > 80 characters

Consider 4 spaces instead of tabs, 1 line contains tabs

Consider multiples of 4 spaces for line indents, 666 lines are not (FormatR for help)

- [ ] REQUIRED: Clean up repository to only include files that are required to build the package ('doc', '.travis.yml', etc. are not needed).

# DESCRIPTION #

- [ ] REQUIRED: 'LazyData' should be set to 'FALSE'. Having it set to 'TRUE' only slows down the loading of packages with data.

- [ ] CLARIFICATION: Make sure the following packages should be imported since they aren't listed in NAMESPACE
	- shiny
	- tibble
	- ape
	- vegan
	- S4Vectors
	- scales

- [ ] REQUIRED: Add 'methods' and 'stats' to 'Imports'.

- [ ] REQUIRED: 'BiocCheck' and 'devtools' do not have to be suggested unless they are used in examples/vignettes.

- [ ] REQUIRED: 'Software' related biocViews need to be included in this package. Right now you are using 'ExperimentData' tags.

# NAMESPACE # 

- [ ] REQUIRED: Exported functions should use camel case or underscoring, not '.' since this indicates S3 dispatch.

- [ ] SUGGESTION: Be sure that you are only using `import()` if many function are used from the package. If only a few functions are used than import them using `importFrom()`.

# NEWS #

- [ ] REQUIRED: If you intend to use a NEWS file then please fill it in. See https://bioconductor.org/developers/package-guidelines/#news for how to format properly.

# Data #

- [ ] REQUIRED: Data in '/data' needs to be documented.

- [ ] CLARIFICATION: What is the purpose of the file in the 'data-raw' directory.

- [ ] REQUIRED: Documentation for the 'inst/extdata' should be included in the 'inst/script' directory. This should be a script that clearly present how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executable code, sudo code, or text description. The user should be able to download and be able to roughly reproduce the file or object that is present.

# vignette #

- [ ] REQUIRED: We prefer to have an 'Introduction' section that serves as an abstract. Remove the 'abstract:' tag from the metadata of the vignette and create an 'Introduction' section with it. Also be sure to include \` \` around the package name so it will be formated as code instead of regular text.

- [ ] REQUIRED: Include an 'Installation' section that shows the users how to download and load the package from _Bioconductor_.

- [ ] REQUIRED: The knit options does not have to be a section in your vignette that displays to the user. Add `include = FALSE` inside the `{r}` so that the code is run but will not be shown in the vignette output.

- [ ] SUGGESTION: It can be up to you what you include in the knit options but I would suggest not including `message = FALSE` for all code. Messages can be helpful to users as they work through the vignette. Instead I would add this option to the specific chunks of R code that you won't want the message to show. I would suggest adding in the knit options things like `collapse = TRUE` and `comment = "#>"`.

- [ ] REQUIRED: You do not need to load in all of the libraries for your package in your vignette. They will be loaded when they install your package. Please remove this chunk (lines 47-69). The only libraries that should be loaded are the ones that aren't imported and used strictly in your vignette. Then I would load them as needed in the code.

- [ ] REQUIRED: Line 88-90, this code should not be commented out. Instead, add the tag `eval = FALSE` to {r} so that the code is shown but not evaluated when building the vignette.

- [ ] CLARIFICATION: After running the `run_animalcules()` function I noticed on the opening page of the shiny app there is no information for the 'Annotation table'. Both 'Counts Table' and 'Taxonomy Table' have descriptive information about them but 'Annotation' does not. I'm not sure if this was intended but it might be something to consider adding.

- [ ] SUGGESTION: Line 132, I would do `head(result$sam_table)` so that instead of all 50 subjects being shown just the first 6 subjects.

- [ ] SUGGESTION: I wouldn't comment out line 259.

- [ ] SUGGESTION: I wouldn't comment out line 275.

- [ ] SUGGESTION: Line 276, I would also do `head(result$table)` here so all subjects aren't printed out.

- [ ] CLARIFICATION: For line 324, when I run the code myself is it expected to get a different list of biomarkers than the ones you show? This will then change the plots following. If so, this might be something you point out to the user so they don't think they messed something up.

- [ ] REQUIRED: Section 11 - Toy Dataset, this section is not needed and is what should be included in the 'inst/script' directory. This demonstrates how you went from 'animalcules.rds' to 'MAE.rds.

# man pages #

*MAE*

- [ ] REQUIRED: This needs to be documentation needs to be more complete. Take a look at http://r-pkgs.had.co.nz/data.html#data-data for help with this.

*animalcules-package*

- [ ] SUGGESTION: You might consider adding some links to the main function in this page.

*diversities*

- [ ] REQUIRED: For arguments, the description of 'zeroes' seems incomplete. Not sure if there needs to be a 'TRUE' or 'FALSE' somewhere in the sentence.

*diversities_help*

- [ ] CLARIFICATION: How is this different from 'diversities'?

*filter_summary_top*

- [ ] REQUIRED: Could you change the variable being plotted in the example to show a pie chart and not a boxplot? 

*find_taxon_mat*

- [ ] REQUIRED: Add runnable examples since it is an exported function.

*read_pathoscope_data*

- [ ] REQUIRED: Add runnable examples since it is an exported function.

*animalcules*

- [ ] CLARIFICATION: Is the title/description correct for this file?

- [ ] REQUIRED: Add runnable example since it is an exported function (it will most likely be the same as 'Usage' but it's good practice to have since some users just go right to examples).

*upsample_counts*

- [ ] REQUIRED: Add runnable examples since it is an exported function.

# R code #

- [ ] REQUIRED: Use `vapply()` instead of `sapply()`.

- [ ] REQUIRED: Use various apply functions instead of `for` loops.

- [ ] REQUIRED: Use `seq_len()` or `seq_along()` instead of `1:...`.

- [ ] SUGGESTION: If using `import` or `importFrom` then you don't need to use `package::function` in the R code, you can just use the function normally. This will help simplify your code a bit.

- [ ] REQUIRED: The functions in 'utils.R' don't need to be exported to the user. Since they are documented already you can add the `@keywords interal` which will remove them from the package index.

Best,
Kayla

**Comment by anfederico** [comment] 2019-04-21 15:10
Hi @Kayla-Morrell 

Thank you for the feedback. We have addressed the following issues. Please see our responses and clarifications in bold/italics. One note, we are receiving one warning on the build report but we can't figure out what's causing it. Both devtools::check() and BioCheck() are running on our machines with no errors.

 # General package development
 _R CMD BiocCheck_
 
 * [x] Incomplete final line in inst/shiny/utils/ui_util.R
 
 * [x]  Consider shorter lines, 157 lines are  80 characters
 
 * [x]  Consider 4 spaces instead of tabs, 1 line contains tabs
 
 * [x] Consider multiples of 4 spaces for line indents, 666 lines are not (FormatR for help)
 
 * [x]  REQUIRED: Clean up repository to only include files that are required to build the package ('doc', '.travis.yml', etc. are not needed).
 
 # DESCRIPTION
 * [x]  REQUIRED: 'LazyData' should be set to 'FALSE'. Having it set to 'TRUE' only slows down the loading of packages with data.
 * [x]  CLARIFICATION: Make sure the following packages should be imported since they aren't listed in NAMESPACE
   
   * shiny
   * tibble
   * ape
   * vegan
   * S4Vectors
   * scales
 * [x]  REQUIRED: Add 'methods' and 'stats' to 'Imports'.
 * [x]  REQUIRED: 'BiocCheck' and 'devtools' do not have to be suggested unless they are used in examples/vignettes.
 * [x]  REQUIRED: 'Software' related biocViews need to be included in this package. Right now you are using 'ExperimentData' tags.
 
 # NAMESPACE
 * [x]  REQUIRED: Exported functions should use camel case or underscoring, not '.' since this indicates S3 dispatch.
 * [x]  SUGGESTION: Be sure that you are only using `import()` if many function are used from the package. If only a few functions are used than import them using `importFrom()`.
 
 # NEWS
 * [x]  REQUIRED: If you intend to use a NEWS file then please fill it in. See https://bioconductor.org/developers/package-guidelines/#news for how to format properly.
 
 # Data
 * [x]  REQUIRED: Data in '/data' needs to be documented.
 * [x]  CLARIFICATION: What is the purpose of the file in the 'data-raw' directory. _**The script in this directory is now the script used to create MAE.rda in the data directory**_
 * [X]  REQUIRED: Documentation for the 'inst/extdata' should be included in the 'inst/script' directory. This should be a script that clearly present how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executable code, sudo code, or text description. The user should be able to download and be able to roughly reproduce the file or object that is present.
 
 # vignette
 * [X]  REQUIRED: We prefer to have an 'Introduction' section that serves as an abstract. Remove the 'abstract:' tag from the metadata of the vignette and create an 'Introduction' section with it. Also be sure to include ` ` around the package name so it will be formated as code instead of regular text.
 * [X]  REQUIRED: Include an 'Installation' section that shows the users how to download and load the package from _Bioconductor_.
 * [X]  REQUIRED: The knit options does not have to be a section in your vignette that displays to the user. Add `include = FALSE` inside the `{r}` so that the code is run but will not be shown in the vignette output.
 * [X]  SUGGESTION: It can be up to you what you include in the knit options but I would suggest not including `message = FALSE` for all code. Messages can be helpful to users as they work through the vignette. Instead I would add this option to the specific chunks of R code that you won't want the message to show. I would suggest adding in the knit options things like `collapse = TRUE` and `comment = "#"`.  _**We added comments but we actually don't want to show messages on any code blocks.**_
 * [X]  REQUIRED: You do not need to load in all of the libraries for your package in your vignette. They will be loaded when they install your package. Please remove this chunk (lines 47-69). The only libraries that should be loaded are the ones that aren't imported and used strictly in your vignette. Then I would load them as needed in the code.
 * [X]  REQUIRED: Line 88-90, this code should not be commented out. Instead, add the tag `eval = FALSE` to {r} so that the code is shown but not evaluated when building the vignette.
 * [X]  CLARIFICATION: After running the `run_animalcules()` function I noticed on the opening page of the shiny app there is no information for the 'Annotation table'. Both 'Counts Table' and 'Taxonomy Table' have descriptive information about them but 'Annotation' does not. I'm not sure if this was intended but it might be something to consider adding. **_Added relevant information._**
 * [X]  SUGGESTION: Line 132, I would do `head(result$sam_table)` so that instead of all 50 subjects being shown just the first 6 subjects.
 * [X]  SUGGESTION: I wouldn't comment out line 259.
 * [X]  SUGGESTION: I wouldn't comment out line 275.
 * [X]  SUGGESTION: Line 276, I would also do `head(result$table)` here so all subjects aren't printed out.
 * [X]  CLARIFICATION: For line 324, when I run the code myself is it expected to get a different list of biomarkers than the ones you show? This will then change the plots following. If so, this might be something you point out to the user so they don't think they messed something up.
 * [X]  REQUIRED: Section 11 - Toy Dataset, this section is not needed and is what should be included in the 'inst/script' directory. This demonstrates how you went from 'animalcules.rds' to 'MAE.rds.
 
 # man pages
 _MAE_
 
 * [x]  REQUIRED: This needs to be documentation needs to be more complete. Take a look at http://r-pkgs.had.co.nz/data.html#data-data for help with this. **_See R/data.R_**
 
 _animalcules-package_
 
 * [X]  SUGGESTION: You might consider adding some links to the main function in this page.
 
 _diversities_
 
 * [x]  REQUIRED: For arguments, the description of 'zeroes' seems incomplete. Not sure if there needs to be a 'TRUE' or 'FALSE' somewhere in the sentence.
 
 _diversities_help_
 
 * [x]  CLARIFICATION: How is this different from 'diversities'? **_Diversities is the general function that will check user conditions from the Shiny application and then decide if it should call diversities_help, which will calculate the diversity._**
 
 _filter_summary_top_
 
 * [x]  REQUIRED: Could you change the variable being plotted in the example to show a pie chart and not a boxplot?
 
 _find_taxon_mat_
 
 * [x]  REQUIRED: Add runnable examples since it is an exported function.
 
 _read_pathoscope_data_
 
 * [X]  REQUIRED: Add runnable examples since it is an exported function.
 
 _animalcules_
 
 * [x]  CLARIFICATION: Is the title/description correct for this file?
 * [x]  REQUIRED: Add runnable example since it is an exported function (it will most likely be the same as 'Usage' but it's good practice to have since some users just go right to examples).
 
 _upsample_counts_
 
 * [x]  REQUIRED: Add runnable examples since it is an exported function.
 
 # R code
 * [x]  REQUIRED: Use `vapply()` instead of `sapply()`. **_The benefit of using vapply over sapply is not apparent to me, and we would have to change a lot of code, for seemingly no improvement to the code base_**
 * [x]  REQUIRED: Use various apply functions instead of `for` loops. **_Sometimes for loops are a better choice than apply functions. For example when adding many traces to plotly objects._**
 * [x]  REQUIRED: Use `seq_len()` or `seq_along()` instead of `1:...`.
 * [x]  SUGGESTION: If using `import` or `importFrom` then you don't need to use `package::function` in the R code, you can just use the function normally. This will help simplify your code a bit.
 * [x]  REQUIRED: The functions in 'utils.R' don't need to be exported to the user. Since they are documented already you can add the `@keywords interal` which will remove them from the package index. **_Some of these functions are useful for microbiome transcriptomics data analysis and therefore should be accessible to users._**

**Comment by Kayla-Morrell** [comment] 2019-04-22 16:29
Hello @anfederico,

Thank you for all the work done on this package. I have looked over the changes made and have just a few additional notes before accepting your package. See the secondary review below and comment back here when you are ready for me to look it over again.

# General package development #

*R CMD check*

- [ ] SUGGESTION: Fix the global variable and function NOTES.

*R CMD BiocCheck*

- [ ] SUGGESTION: Fix the initialization NOTE.

# DESCRIPTION #

- [ ] REQUIRED: I asked that you clarify that certain packages should be listed as an 'Import' even though they were not listed in NAMESPACE. I was able to locate instances of 'S4Vectors', 'shiny' and 'vegan' within the Shiny R code but I still cannot locate where 'tibble', 'ape', or 'scales' are used. Please indicate where they are used or remove them from 'Imports'.

- [ ] REQUIRED: 'methods' and 'stats' where not added to 'Imports:' though you marked that they were. Please add them.

- [ ] SUGGESTION: Consider adding 'Coverage' to 'biocViews:' if applicable.

# NAMESPACE #

- [ ] REQUIRED: Once 'methods' and 'stats' are added to 'Imports:' in DESCRIPTION file then `importFrom("methods", "as")` and `importFrom("stats", "as.formula", "cor.test", "density", "kruskal.test", "model.matrix", "quantile", "t.test", "wilcox.test")` should be added to NAMESPACE file.

# data #

- [ ] REQUIRED: Thank you for including documentation for the data in 'inst/script'. There needs to be documentation though for where 'animalcules.rds' and 'TB_example_dataset.rds' come from.

- [ ] REQUIRED: Where is 'toy_data.rds' actually used?

# vignette #

- [ ] REQUIRED: Line 36, 'animalcules' should be lowercase even if it is at the beginning of a sentence.

- [ ] REQUIRED: Line 31, 'devtools::load_all(".")' is not needed and should be removed.

# man pages #

- [ ] REQUIRED: You mentioned that the 'MAE.Rd' documentation was moved to 'R/data.R' but this file is not present. Is it located some place else?

*read_pathoscope_data*

- [ ] REQUIRED: No runnable examples were added to this file.

 # R code #

- [ ] CLARIFICATION: We recommend that `vapply()` be used instead of `sapply()` because problems arixe when the 'X' argument to `sapply()` has length 0. The return type is then a `list()` rather than a vector or array. There are only 3 instances of `sapply()` in your code:
	- grep_tid.R, line 11
	- utils.R, line 45
	- utils.R, line 64

- [ ] REQUIRED: I see you made the `seq_along()` or `seq_len()` changes to your R code but this also needs to be reflected in the shiny R code. Please make the necessary changes.

Best,
Kayla

**Comment by anfederico** [comment] 2019-04-23 21:05
Hi @Kayla-Morrell 

Thank you again for the feedback. We have addressed the following concerns.

# General package development #

*R CMD check*

- [x] SUGGESTION: Fix the global variable and function NOTES.

*R CMD BiocCheck*

- [x] SUGGESTION: Fix the initialization NOTE.

**_We fixed as many as we could!_**

# DESCRIPTION #

- [x] REQUIRED: I asked that you clarify that certain packages should be listed as an 'Import' even though they were not listed in NAMESPACE. I was able to locate instances of 'S4Vectors', 'shiny' and 'vegan' within the Shiny R code but I still cannot locate where 'tibble', 'ape', or 'scales' are used. Please indicate where they are used or remove them from 'Imports'. **_The tibble package is used in find_biomarker.R and has been added to its imports. The ape package is used in dimred_pcoa.R and has been added to its imports. The scales packaged is used in dimred_pca.R and dimred_pcoa.R and has been added to its imports._** 

- [x] REQUIRED: 'methods' and 'stats' where not added to 'Imports:' though you marked that they were. Please add them. _**Added**_

- [x] SUGGESTION: Consider adding 'Coverage' to 'biocViews:' if applicable. **_Thanks for the suggestion. Added_**

# NAMESPACE #

- [x] REQUIRED: Once 'methods' and 'stats' are added to 'Imports:' in DESCRIPTION file then `importFrom("methods", "as")` and `importFrom("stats", "as.formula", "cor.test", "density", "kruskal.test", "model.matrix", "quantile", "t.test", "wilcox.test")` should be added to NAMESPACE file.

# data #

- [x] REQUIRED: Thank you for including documentation for the data in 'inst/script'. There needs to be documentation though for where 'animalcules.rds' and 'TB_example_dataset.rds' come from. _**Added**_

- [x] REQUIRED: Where is 'toy_data.rds' actually used? _**It is currently being used in the examples for R/upsample_counts.**_

# vignette #

- [x] REQUIRED: Line 36, 'animalcules' should be lowercase even if it is at the beginning of a sentence.  _**Fixed.**_

- [x] REQUIRED: Line 31, 'devtools::load_all(".")' is not needed and should be removed.  _**Fixed.**_

# man pages #

- [x] REQUIRED: You mentioned that the 'MAE.Rd' documentation was moved to 'R/data.R' but this file is not present. Is it located some place else? **_We decided to remove MAE.rda from the package because it was redundant. This resulted in no need for the /data and /data-raw directories as well. We do use MAE.rds however, which resides in /inst/extdata/MAE.rds and is documented in /inst/script/extdata.R (along with toy_data.rds)._**

*read_pathoscope_data*

- [x] REQUIRED: No runnable examples were added to this file. **_This function shouldn't have been exported, we have changed it to internal instead. It will eventually be integrated into and run only from the Shiny application._**

 # R code #

- [x] CLARIFICATION: We recommend that `vapply()` be used instead of `sapply()` because problems arixe when the 'X' argument to `sapply()` has length 0. The return type is then a `list()` rather than a vector or array. There are only 3 instances of `sapply()` in your code: _**Fixed.**_
	- grep_tid.R, line 11
	- utils.R, line 45
	- utils.R, line 64

- [x] REQUIRED: I see you made the `seq_along()` or `seq_len()` changes to your R code but this also needs to be reflected in the shiny R code. Please make the necessary changes. _**Fixed.**_

**Comment by Kayla-Morrell** [comment] 2019-04-24 14:34
@anfederico - Thank you again for making the necessary changes. I will be able to accept the package once the ERROR is cleaned (and ideally the WARNINGS as well).

Best, 
Kayla

**Comment by anfederico** [comment] 2019-04-24 16:28
@Kayla-Morrell 

The error message seems to be an http request issue from using the rentrez package. My best guess is it is specific to the linux machine being used by Bioconductor to check the examples. I'm not sure what I could change on our end to solve this error (besides adding skip example to the roxygen), as it should work on most machines (ours included).

> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Error in the HTTP2 framing layer
> Calls: find_taxonomy ... request_fetch -> request_fetch.write_memory -> <Anonymous>

The warnings are from this. I saw a few users mentioning the same warning on the Bioconductor mailing list, and responses saying that it was an internal issue of Bioconductor. And to ignore it.

> Found the following significant warnings:
>   Warning: multiple methods tables found for 'rowSums'
>   Warning: multiple methods tables found for 'colSums'
>   Warning: multiple methods tables found for 'rowMeans'
>   Warning: multiple methods tables found for 'colMeans'

**Comment by Kayla-Morrell** [comment] 2019-04-24 19:02
@anfederico - After talking over with my colleagues we are going to go ahead and accept the package.  It seems to be a recent ERROR and a possible server issue that we hope will fix itself. We would rather see the code run in the example to be sure things aren't broken in the future then not have it run/test. Thank you for all of your work on this package.

Best,
Kayla

**Comment by anfederico** [comment] 2019-04-24 19:05
@Kayla-Morrell Thank you!

**Comment by mtmorgan** [comment] 2019-04-24 21:28
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/anfederico.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("animalcules")`. The package 'landing page' will be created at

https://bioconductor.org/packages/animalcules

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-04-24 21:28 UTC
Labels: 3a. accepted, ERROR, WARNINGS
