### ISSUE TITLE
Please add package mbQTL

### ISSUE THREAD

**Issue by Mercedeh66** [Bioconductor/Contributions#2899] opened 2023-01-16 01:59 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Mercedeh66/mbQTL

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2023-01-19 11:09
Please run R CMD check on your package
```
Running examples in 'mbQTL-Ex.R' failed
The error most likely occurred in:

> ### Name: allToAllProduct
> ### Title: allToAllProduct creates a dataframe of snp and taxa correlations
> ### Aliases: allToAllProduct
> ### Keywords: Correlation snptaxa
> 
> ### ** Examples
> 
> x <- allToAllProduct(SnpFile, microbeAbund, "chr1.171282963_T")
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rownames': object 'microbeAbund' not found
Calls: allToAllProduct -> RegSnp -> rownames -> .handleSimpleError -> h
Execution halted
* checking for unstated dependencies in vignettes ... OK

```

**Comment by Mercedeh66** [comment] 2023-01-20 01:06
Hi thank you for spotting this. I have corrected the errors. Please try again. Thank you!

**Comment by Mercedeh66** [comment] 2023-01-30 13:55
@HelenaLC should be good to go! Thanks.

**Comment by HelenaLC** [comment] 2023-01-31 16:01
Some (mostly minor) comments below! Note that many are suggestions and not strictly required (e.g., "consider..."). Please comment back here with what has/not been addressed how/why not, or any comments regarding any needed clarification or questions you might have; happy to help/discuss. Cheers!

# `DESCRIPTION`

- [ ] Would be nice to add a brief but descriptive `Title:` for the package. This will show up on the Bioconductor website ([here](https://www.bioconductor.org/packages/release/bioc/html/BayesSpace.html)'s an example of what I mean).

- [ ] As mentioned in the [build report](http://bioconductor.org/spb_reports/mbQTL_buildreport_20230130081404.html), please update `Depends:` from R v4.2 to 4.3 (since anyways Bioc 3.17 won't be installable under older versions of R).

# code

- [ ] I'd strongly suggest adding some argument validity checks with informative messages to the user. For example, say your function expects a `data.frame` with `rownames` set an 2 non-zero dimensions and numeric values (e.g., `coringTaxa()`), users might get obstruct errors if this it not the case.

- [ ] I understand using `dplyr` and `tidyr` is nice on a daily basis, but it adds dozens of dependencies for functionality that can often be achieved using base R. If at all possible, I'd try working around these. Of course, that's left to your personal judgement; but it it's just about `mutate`, `filter`, `select` and friends, I'd argue the cost (in terms of dependencies) is not worth the benefit. 

# data

- [ ] All that's in `data-raw` at the moment should go in an `inst/extdata` directory, and be read into R with `system.file()` (see [here](http://contributions.bioconductor.org/data.html?q=extdata#raw-data-and-the-instextdata-directory) for details). Accordingly, the `mydataset.R` script would go in `inst/script` as described [here](http://contributions.bioconductor.org/docs.html?q=inst#doc-inst-script).

- [ ] Please properly document all example data in the corresponding `man` pages, and provide source information and/or code (in `inst/script`) on how the example data were generated. There's virtually no description of the data at the moment.

# documentation

- (more of a question than a comment ;) The `NEWS` states v0.99.1, but the `DESCRIPTION` is at v0.99.0. Make sure to update the latter and push version bumps to the local (origin) as well as to Bioc (upstream) branch when making updates.

- Nothing to complain about really, but did you know you can write `data(one, two, three)` rather than having multiple `data()` calls? Perhaps something worth considering to keep examples more compact.

- [ ] Please including Bioconductor installation instructions using `BiocManager::install()` in the `READEME`.

- [ ] (optional) We would highly encourage having a package man page so users would be directed to the main functions of the package with `?mbQTL`.

- [ ] I'd recommend against importing dependencies in their entirety with `@import <package>`, and rather use selection imports via `@importForm <package> <function>`. Ideally, these go in the roxygen chunk preceding the corresponding function that uses them. This makes it clear which namespace functions are being called from and avoid namespace conflicts (say, two packages exporting functions of the same name).

- [ ] We don't allow `\dontrun` in examples unless there is a strong justification for this (?) Currently in *Logistic_Regression.R* (lines 27,62) and *Correlation_Regression.R* (line 67)

- [ ] For all functions, I feel that the documentation could be a little more extensive (according to your own judgement). E.g., when there's a statistical test/modeling step, pointers to the underlying methods would be nice (e.g., function hyperlinks). Or a brief `@details` section that describes what is being done. Similarly, under `@return`, it'd be nice to briefly describe the different columns (with their explicit name).  
To give a simple example, rather than saying "`MatrixeQR` core functions are utilized to achieve this", it would be nice to be explicit about which function (e.g., `Matrix_eQTL_engine()`) is used and for what. Note than, I can see this in the code but 'normal' users cannot without direct pointers.

# vignette

- [ ] We encourage the use of `r BiocStyle::Biocpkg("BiocStyle")` for formatting with `html_document` as rendering target; see [here](http://contributions.bioconductor.org/docs.html) for instructions. You have it under `Suggests:` in the `DESCRIPTION`, but it's currently not being used?

- [ ] To highlight/distinguish code (e.g., package/function/variable/class names) from normal text, I'd highly recommend consistently using back-ticks. Makes it a lot easier to read/follow things.

- [ ] Especially in the vignette, please stick to a 80-character limit as code might be otherwise hard to read when displayed online (which it typically is when accessing the HTML of the vignette on the Bioc website).

- [ ] Besides the intro giving some background, the vignette currently gives few details on the methods being run and outputs produced. For example, rather than just running through the examples, briefly explain the underlying methods; perhaps display chunks of the output and explain what they mean/how they should be interpreted; point to relevant outside packages/functions (e.g., using `BiocStyle` functions for hyperlinks) etc. Overall, the vignette is a little sparse right now.

**Comment by Mercedeh66** [comment] 2023-02-06 00:30
Hi @HelenaLC. Tried to address almost all of the comments. Many thanks for the guidance.

Best,

-M

DESCRIPTION
Would be nice to add a brief but descriptive Title: for the package. This will show up on the Bioconductor website ([here](https://www.bioconductor.org/packages/release/bioc/html/BayesSpace.html)'s an example of what I mean). - Done

 As mentioned in the [build report](http://bioconductor.org/spb_reports/mbQTL_buildreport_20230130081404.html), please update Depends: from R v4.2 to 4.3 (since anyways Bioc 3.17 won't be installable under older versions of R).
-Done

code
 I'd strongly suggest adding some argument validity checks with informative messages to the user. For example, say your function expects a data.frame with rownames set an 2 non-zero dimensions and numeric values (e.g., coringTaxa()), users might get obstruct errors if this it not the case.
-Done
 I understand using dplyr and tidyr is nice on a daily basis, but it adds dozens of dependencies for functionality that can often be achieved using base R. If at all possible, I'd try working around these. Of course, that's left to your personal judgement; but it it's just about mutate, filter, select and friends, I'd argue the cost (in terms of dependencies) is not worth the benefit.
-I agree, in this particular case we will be dealing with very large snp files and taxa files and processing is easier with dplyr so I am going to stick with it. Thanks for the valuable advice though.

data
 All that's in data-raw at the moment should go in an inst/extdata directory, and be read into R with system.file() (see [here](http://contributions.bioconductor.org/data.html?q=extdata#raw-data-and-the-instextdata-directory) for details). Accordingly, the mydataset.R script would go in inst/script as described [here](http://contributions.bioconductor.org/docs.html?q=inst#doc-inst-script).
-Done
 Please properly document all example data in the corresponding man pages, and provide source information and/or code (in inst/script) on how the example data were generated. There's virtually no description of the data at the moment.
-Improved-Done

documentation
(more of a question than a comment ;) The NEWS states v0.99.1, but the DESCRIPTION is at v0.99.0. Make sure to update the latter and push version bumps to the local (origin) as well as to Bioc (upstream) branch when making updates.
-Done
Nothing to complain about really, but did you know you can write data(one, two, three) rather than having multiple data() calls? Perhaps something worth considering to keep examples more compact.
-Thanks
 Please including Bioconductor installation instructions using BiocManager::install() in the READEME.
-Done
 (optional) We would highly encourage having a package man page so users would be directed to the main functions of the package with ?mbQTL.
 I'd recommend against importing dependencies in their entirety with @import <package>, and rather use selection imports via @importForm <package> <function>. Ideally, these go in the roxygen chunk preceding the corresponding function that uses them. This makes it clear which namespace functions are being called from and avoid namespace conflicts (say, two packages exporting functions of the same name).

 We don't allow \dontrun in examples unless there is a strong justification for this (?) Currently in Logistic_Regression.R (lines 27,62) and Correlation_Regression.R (line 67)
-Done
 For all functions, I feel that the documentation could be a little more extensive (according to your own judgement). E.g., when there's a statistical test/modeling step, pointers to the underlying methods would be nice (e.g., function hyperlinks). Or a brief @details section that describes what is being done. Similarly, under @return, it'd be nice to briefly describe the different columns (with their explicit name).
To give a simple example, rather than saying "MatrixeQR core functions are utilized to achieve this", it would be nice to be explicit about which function (e.g., Matrix_eQTL_engine()) is used and for what. Note than, I can see this in the code but 'normal' users cannot without direct pointers.
-Done
vignette
 We encourage the use of r BiocStyle::Biocpkg("BiocStyle") for formatting with html_document as rendering target; see [here](http://contributions.bioconductor.org/docs.html) for instructions. You have it under Suggests: in the DESCRIPTION, but it's currently not being used?
-Done
 To highlight/distinguish code (e.g., package/function/variable/class names) from normal text, I'd highly recommend consistently using back-ticks. Makes it a lot easier to read/follow things.
-Changed format.
 Especially in the vignette, please stick to a 80-character limit as code might be otherwise hard to read when displayed online (which it typically is when accessing the HTML of the vignette on the Bioc website).
-Done
 Besides the intro giving some background, the vignette currently gives few details on the methods being run and outputs produced. For example, rather than just running through the examples, briefly explain the underlying methods; perhaps display chunks of the output and explain what they mean/how they should be interpreted; point to relevant outside packages/functions (e.g., using BiocStyle functions for hyperlinks) etc. Overall, the vignette is a little sparse right now.
-Improved it.

**Comment by HelenaLC** [comment] 2023-02-07 09:55
So, looks like your origin branch DESCRIPTION [here](https://github.com/Mercedeh66/mbQTL/blob/master/DESCRIPTION) is at v0.99.2, but the Bioc one is still at 0.99.0. You need to (now and for all time to come as a Bioc maintainer) push to both the local (origin) and bioc branch (upstream) to trigger a new build. Also note that this will trigger the Bioc bot to post a message here that a "new build has been triggered".

Also, would be nice if you could edit the above (ideally, edit, not repost, to keep the thread clean) to keep the .md formatting and code highlighting from my original comments. E.g., you can do a "Quote reply" on GitHub to reply to the original post.

**Comment by Mercedeh66** [comment] 2023-02-19 21:21
> So, looks like your origin branch DESCRIPTION [here](https://github.com/Mercedeh66/mbQTL/blob/master/DESCRIPTION) is at v0.99.2, but the Bioc one is still at 0.99.0. You need to (now and for all time to come as a Bioc maintainer) push to both the local (origin) and bioc branch (upstream) to trigger a new build. Also note that this will trigger the Bioc bot to post a message here that a "new build has been triggered".
> 
> Also, would be nice if you could edit the above (ideally, edit, not repost, to keep the thread clean) to keep the .md formatting and code highlighting from my original comments. E.g., you can do a "Quote reply" on GitHub to reply to the original post.

Just wanted to let you know, all is done and it is passing the check now.

**Comment by HelenaLC** [comment] 2023-02-22 15:38
Hey Mercedeh, see my comments below.

Kindly, could you respond using .md syntax (or a quoted response) this time?
It's quite painful to read unformatted plain text bullet lists and code on GH...

- in the `LICENSE`: Copyright (c) 2022 mirTarRnaSeq authors -> ...2023 mbQTL...
- in the `DESCRIPTION`: consider adding a `URL:` and `BugReports:` field  
pointing to "https://github.com/Mercedeh66/mbQTL" and ".../issues", respectively
- perhaps add a space in the `DESCRIPTION`s `Title: mbQTL:A package` before the "A"?
- some typos I found in the vignette (perhaps worth giving everything another read...):
  - line 95: vigette -> vignette
  - 100: add space b/w "formats.The"
  - 113: aggreagate -> aggregated, taxanomic -> taxonomic (I think?), 
  - 114: formated -> formatted
  - 131: hetrozygous -> heterozygous
  - 166: abundancefile -> abundance file
- also in the vignette: across all code chunks, I'd recommend  
not exceeding the 80-char limit, even with comments  
(this might look messy when displayed online...)
- have you considered this...? "having a package man page so users  
would be directed to the main functions of the package with ?mbQTL."  
(double checking because you didn't comment on / implement this)
- in the vignette, re "to highlight/distinguish code [...]":  
you said "Done", but everything is still in plain text.  
I find this very difficult to read / follow; especially  
when referring to variable/function/package names,  
code-style would improve readability a lot  
(potentially adding hyperlinks via `BiocStyle` commands  
when referring to external software)
- perhaps I'm missing something, but I can still not find  
information on data source/reproducibility.  
I can see that there are comments in `inst/script/mydataset.R`,  
but these will not be visible to regular users.  
Instead, there should be a man page containing these information  
(accessible via `?mbQTL::data` or, e.g., `?CovFile` etc.).  
All that is to say: data documentation should go  
in the roxygen chunks of your `code/data.R` script.

**Comment by Mercedeh66** [comment] 2023-02-26 02:42
> Hey Mercedeh, see my comments below.
> 
> Kindly, could you respond using .md syntax (or a quoted response) this time? It's quite painful to read unformatted plain text bullet lists and code on GH...
> 
> * in the `LICENSE`: Copyright (c) 2022 mirTarRnaSeq authors -> ...2023 mbQTL...
>_DONE_
> * in the `DESCRIPTION`: consider adding a `URL:` and `BugReports:` field
>   pointing to "https://github.com/Mercedeh66/mbQTL" and ".../issues", respectively
>_DONE_
> * perhaps add a space in the `DESCRIPTION`s `Title: mbQTL:A package` before the "A"?
>_DONE_
> * some typos I found in the vignette (perhaps worth giving everything another read...):
>   
>   * line 95: vigette -> vignette
>_DONE_
>   * 100: add space b/w "formats.The"
>_DONE_
>   * 113: aggreagate -> aggregated, taxanomic -> taxonomic (I think?),
>_DONE_
>   * 114: formated -> formatted
>_DONE_
>   * 131: hetrozygous -> heterozygous
>_DONE_
>   * 166: abundancefile -> abundance file
>_DONE_
> * also in the vignette: across all code chunks, I'd recommend
>   not exceeding the 80-char limit, even with comments
>   (this might look messy when displayed online...)
> _I am assuming you mean per line limit. Altered the best I could._
> * have you considered this...? "having a package man page so users
>   would be directed to the main functions of the package with ?mbQTL."
>   (double checking because you didn't comment on / implement this)
> _Added Done_
> * in the vignette, re "to highlight/distinguish code [...]":
>   you said "Done", but everything is still in plain text.
>   I find this very difficult to read / follow; especially
>   when referring to variable/function/package names,
>   code-style would improve readability a lot
>   (potentially adding hyperlinks via `BiocStyle` commands
>   when referring to external software)
>  _Done_
> * perhaps I'm missing something, but I can still not find
>   information on data source/reproducibility.
>   I can see that there are comments in `inst/script/mydataset.R`,
>   but these will not be visible to regular users.
>   Instead, there should be a man page containing these information
>   (accessible via `?mbQTL::data` or, e.g., `?CovFile` etc.).
>   All that is to say: data documentation should go
>   in the roxygen chunks of your `code/data.R` script.
> _This is strange I thought I updated this in the data.R file and it should now be there please try again. If I am missing something please let me know._

> _Thanks so much Helena for such an in depth and detailed review and the great comments/suggestions. I really appreciate it. I hope all is good now._

**Comment by lshep** [comment] 2023-03-03 14:25
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Mercedeh66.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mbQTL")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mbQTL

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-03-03 14:25 UTC
Labels: OK, 3a. accepted
