### ISSUE TITLE
Xeva : XEnograft Visualization & Analysis

### ISSUE THREAD

**Issue by gangeshberiuhn** [Bioconductor/Contributions#968] opened 2019-01-08 22:58 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bhklab/Xeva

Confirm the following by editing each checkbox to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by gangeshberiuhn** [comment] 2019-01-09 16:52
I have changed the version to 0.99.0 and the Github repository has the webhook installed and it seems to have triggered. But still, I am getting the same response "version bump required" from bioc-issue-bot.

**Comment by mtmorgan** [comment] 2019-01-09 17:19
The version number at submission should have been 0.99.0. the next version 0.99.1, the next 0.99.2.

I think that you have used 0.99.0, but not 0.99.1, so I suggest that you change the version to that number.

That you have used a larger version number already MAY cause problems, and if so @lshep will provide assistance.

**Comment by gangeshberiuhn** [comment] 2019-01-10 19:24
@mtmorgan We have pushed some changes to our Github repository and we were waiting to see the build report generated but it's been a while and still we haven't got anything.

**Comment by mtmorgan** [comment] 2019-01-10 19:54
You request a version (3.4.4) of R that is not supported -- usually, it is not necessary to specify a particular R version, as Bioconductor releases are tied to specific R versions. You are contributing a package the 'devel' branch of Bioconductor, which currently uses 'R-devel', which has version 3.6.

Remove R from the Depends: field and increment the version.

@lshep probably the Single Package Builder choked on the bad version but did not report this?

**Comment by gangeshberiuhn** [comment] 2019-01-10 20:06
@mtmorgan If the build fails it keeps on checking again and again. is there any issue with the bot?

**Comment by lshep** [comment] 2019-01-11 02:31
Could you please check your webhook for this issue and make sure this is only one registered for issues.bioconductor.org  -  Please also check the settings and makes sure under `Which events would you like to trigger this webhook`  is `Just the push event`   - It is very odd that every push event is triggering multiple builds and we don't see this on any other issues at this time.

**Comment by gangeshberiuhn** [comment] 2019-01-11 03:50
@lshep I have deleted the old webhook and created a new one. I have checked and it's Just the push event checkbox which has been selected and only one webhook has been registered for issues.bioconductor.org. Yes, it's pretty strange that multiple builds are getting triggered.

**Comment by lshep** [comment] 2019-01-17 12:58
I kicked off a manual build given the situation from before -  The previous `git clone` ERROR was on our end because of the multiple triggers but it seem like there were more ERROR's that needed to be corrected before @dvantwisk started a formal review 

If the ComplexHeatmap version needs to be a more recent version you need to reach out to that maintainer to push the changes into Bioconductor.  We will only use the version in CRAN/Bioconductor.

**Comment by lshep** [comment] 2019-01-18 18:51
Your repository has somehow managed to break our build system - as we do not see this with any other package -  We think we have implemented a  fixed to filter only one trigger and produce only one valid report for your issue

Please reset your webhook one more time following these instructions (https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook)   most notable ignore my previous comment about changing the `Which events would you like to trigger this webhook`   and just leave the default settings as is 

After that we would appreciate if you tried a version bump as we cannot reproduce this when we trigger a manual build

**Comment by gangeshberiuhn** [comment] 2019-01-23 18:45
For sure. I will reset the webhook.

**Comment by dvantwisk** [comment] 2019-01-28 14:35
Are you still having an issue with your pushes building on our build machines?

**Comment by gangeshberiuhn** [comment] 2019-01-28 15:40
We haven't pushed anything new yet, we are currently working on resolving the issues with our package.

**Comment by dvantwisk** [comment] 2019-02-13 17:25
Hello,

Since I haven't seen activity on this package for over two weeks, I am going to close the issue for now. Feel free to reopen it when you are ready to push more changes.

**Comment by gangeshberiuhn** [comment] 2019-02-20 21:04
Hey, Could you please re-open the Issue as we have to push changes.

**Comment by lshep** [comment] 2019-02-21 17:07
Hey -  It looks like you guys are actively pushing commits and there is still something going very very wrong - Would you be interesting in video chatting/sharing so we can see what you are doing and how your repository settings are set up so we can try to figure out the root of the problem?

**Comment by spocks** [comment] 2019-02-21 17:17
Hi @lshep Once I had version error in build report. But now the last report it says "Git clone Failed". @gangeshberiuhn could you look into it?

**Comment by lshep** [comment] 2019-02-21 17:18
@gangeshberiuhn   see above would you be willing to video chat with us now

**Comment by lshep** [comment] 2019-02-21 17:19
We can do a video meeting at this location now to try to help:   https://bluejeans.com/2024711962

**Closed** 2019-02-21 18:08 UTC
Labels: 2. review in progress, ERROR, WARNINGS

**Comment by lshep** [comment] 2019-02-21 18:15
Okay I think we are set on our end for you to try and create a new issue for this.  Thank you again for being so understanding

**Comment by gangeshberiuhn** [comment] 2019-02-21 18:17
Thanks. I will create a new for this.

**Comment by gangeshberiuhn** [comment] 2019-02-21 18:28
Hey, Will it be creating any conflict if we open a new issue with the same name as of a closed Issue?

**Comment by lshep** [comment] 2019-02-21 18:29
It shouldn't because I deleted it from the database of issues -  but if there is let me know

**Comment by gangeshberiuhn** [comment] 2019-02-21 18:31
Cool. Thanks.

**Comment by gangeshberiuhn** [comment] 2019-02-21 18:36
I have created a new Issue.

**Comment by spocks** [comment] 2019-02-21 19:13
@lshep we have created a new issue at https://github.com/Bioconductor/Contributions/issues/1022

**Comment by lshep** [comment] 2019-02-21 19:16
Yes,  thank you -  once @mtmorgan  puts it into a queue we can monitor what happens when you push changes -  If it is still problematic when you guys try to push versions, I'll take over reviewing the package as I can push a manual build when necessary so you can get accurate build reports -
