### ISSUE TITLE
pwrEWAS

### ISSUE THREAD

**Issue by stefangraw** [Bioconductor/Contributions#1009] opened 2019-02-13 20:07 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stefangraw/pwrEWAS

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by stefangraw** [comment] 2019-02-14 18:53
So I have addressed the issue, but I am struggling to push the updated github repository to bioconductor. 
I have created the webhook. Is there anything else I need to do?

Thanks,
Stefan

**Comment by stefangraw** [comment] 2019-02-14 18:56
Oh, just I missed the part where I need to increase the version number to trigger it.

**Comment by stefangraw** [comment] 2019-02-15 14:54
There was a valid push, that was started to be built about 17 hours ago. But I have not received any results. Does that mean I was built without an error, or does is commonly take this long?

**Comment by lshep** [comment] 2019-02-19 12:38
There was an issue with the Single Package Builder - I will manually kick off a build of your package but it should behave as normal and build upon the version bumps now.

**Comment by stefangraw** [comment] 2019-02-19 19:59
I am left with 2 error messages, that can not exactly be address:

    * ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 104.0243 MB
        Size Requirement: 5.0000 MB

pwrEWAS depends on internal reference data, that is specific to tissue types. These reference data sets are critical for pwrEWAS and can not be excluded.  I could make pwrEWAS download each reference data set from github (about 9mb) everytime needed, but this would make pwrEWAS not work without internet connection. Are there any other alternatives?
		
	* ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      pwrEWAS_shiny.Rd

pwrEWAS_shiny is initialtes a shiny user interface that requires user input and does not execute anything by itself and therefore will results in a timeout.

**Comment by stefangraw** [comment] 2019-02-22 18:18
Dear @lshep or @hpages,
Do you have any suggestions/recommendations how to address these issues?

Thanks,
Stefan

**Comment by lshep** [comment] 2019-02-22 18:26
@hpages  will be primarily responsible for reviewing and making comments on this package but since he is currently on a short vacation:  we do not allow software packages this large in Bioconductor.  There are two options: providing the data in a separate [experiment data package](http://bioconductor.org/developers/package-submission/#experPackage)  that accompanies the software package which would use [ExperimentHub](https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html) to cache the data.

**Comment by stefangraw** [comment] 2019-02-22 19:12
@lshep , thank you for your recommendation. I will try to split the software and required data sets. 
Is there anything I can do about the runnable examples?

Thanks,
Stefan

**Comment by lshep** [comment] 2019-02-22 19:32
For now you can ignore the runnable examples and it can be addressed later on in the review process.

**Comment by stefangraw** [comment] 2019-02-24 22:57
The rData files are not experimental data, they contain parameters that are used to simulate data. I have removed these files and (for now) they are downloaded when needed. However, I am still getting the following error message:

    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      pwrEWAS_shiny.Rd

pwrEWAS_shiny.Rd opens up an R-Shiny user interface, that requires the user to interact with it. Including an example would run into timeouts.

**Comment by stefangraw** [comment] 2019-02-25 19:19
The rData files are not experimental data, they contain parameters that are used to simulate data. I have removed these files and (for now) they are downloaded when needed. However, I am still getting the following error message:

```
* ERROR: At least 80% of man pages documenting exported objects
  must have runnable examples. The following pages do not:
  pwrEWAS_shiny.Rd
```
pwrEWAS_shiny.Rd opens up an R-Shiny user interface, that requires the user to interact with it. Including an example would run into timeouts.

**Comment by hpages** [comment] 2019-03-21 19:53
Hi @stefangraw ,

Thanks for submitting pwrEWAS. Note that the package has many problems. Some of them are causing the WARNINGs and ERROR reported by our Single Package Builder. Also the man page for `loadDataset` looks very broken (when I open it with `?loadDataset`). But why would you provide a man page for an unexported symbol in the first place?

Please address these issues before I can proceed with the review. A simple workaround for the `R CMD BiocCheck` ERROR is to put the call to `pwrEWAS_shiny()` in an `if (interactive()) { ... }` statement:
```
if (interactive()) {
  pwrEWAS_shiny()
}
```
Also please take a close look at all the `R CMD check` and `R CMD BiocCheck` NOTEs as most of them are pointing at real problems so should not be ignored.

Thanks,
H.

**Comment by stefangraw** [comment] 2019-03-24 03:50
Hey @hpages 

I apologize, this is my first bioconductor submission. 
For the function loadDataset I did not mean to provide a manual. Some old code got compiled as manual. I am sorry for the confusion. 

Thank you for the suggestion about using "interactive()", that was very helpful. I have update the submission and resolved all ERRORS. Currently I am still loading all required data sets from github repository, I still need to resolve this issue. 

What are the next steps beside resolving the issue with the data sets?

Thank you for you help and time!
Stefan

**Comment by hpages** [comment] 2019-04-04 17:33
Hi @stefangraw ,

Thanks for making these changes. Note that `R CMD check` and `R CMD BiocCheck` are still issuing  many NOTEs. Plus now they are also issuing some warnings (this is new). As I mentioned earlier, most of them are pointing at real problems and should not be ignored.

2 more things:

- Remove vignette.pdf. The PDF vignette does not belong to the package source tree as it will automatically be built and added to the package source tarball by `R CMD build`.

- Do not tell your readers to install a Bioconductor package from GitHub. The proper way to install a Bioconductor package is explained here: https://bioconductor.org/install/ Either provide that link, or show the following code in your vignette:
    ```
    if (!requireNamespace("BiocManager"))
        install.packages("BiocManager")
    BiocManager::install("pwrEWAS")
    ```
    Or both. Note that the above code should not get evaluated when the vignette gets built (e.g. with `R CMD build`) which means that `eval=FALSE` should be used in the opening line of the code chunk.

Thanks,
H.

**Comment by hpages** [comment] 2019-04-19 23:52
Hi @stefangraw , are you planning to follow up with this submission? Thanks.   H.

**Comment by stefangraw** [comment] 2019-04-20 22:27
Hey @hpages  , I will follow up and address the issues sometime next week. I apologize for delay, I had my dissertation defense this week and it kept me quite busy.
Thanks,
Stefan

**Comment by hpages** [comment] 2019-04-22 18:35
No worries. Just so you know that it will be too late to include pwrEWAS in our upcoming release (BioC 3.9). On acceptance it will be included in the next release (BioC 3.10, scheduled for Fall).
Cheers,
H.

**Comment by stefangraw** [comment] 2019-04-25 18:58
Hey @hpages ,

I have addressed some warnings and I am down to 2 warnings (I wanted to address warnings first and then focus on notes). However, I do not understand the first warning and I am uncertain on how to address the second warning:

First warning:
"Found the following notes/warnings:
  Non-staged installation was used
See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1009/2c731fe/pwrEWAS.Rcheck/00install.out' for details."

I am uncertain what is causing this issue and how I can address it. I would appreciate any assistance with this issue.

Second warning:
"This is a software package
    * WARNING: Evaluate more vignette chunks.
        # of code chunks: 15
        # of eval=FALSE: 8
        # of nonexecutable code chunks by syntax: 0
        # total unevaluated 8 (53%)"

This warning is caused by the run time of pwrEWAS. If I evaluate all steps I run into a timeout error. What should I do about this?

Thank you for your help,
Stefan

**Comment by stefangraw** [comment] 2019-05-06 18:37
I have addressed some warnings and notes and I am down to 2 warnings. However, I do not understand the first warning and I am uncertain on how to address the second warning:

First warning:
"Found the following notes/warnings:
Non-staged installation was used
See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1009/2c731fe/pwrEWAS.Rcheck/00install.out' for details."

I am uncertain what is causing this issue and how I can address it. I would appreciate any assistance with this issue.

Second warning:
"This is a software package
* WARNING: Evaluate more vignette chunks.
# of code chunks: 15
# of eval=FALSE: 8
# of nonexecutable code chunks by syntax: 0
# total unevaluated 8 (53%)"

This warning is caused by the run time of pwrEWAS. If I evaluate all steps I run into a timeout error. What should I do about this?

Thank you for your help,
Stefan

**Comment by stefangraw** [comment] 2019-05-06 18:39
I have addressed some warnings and I am down to 2 warnings. However, I do not understand the first warning and I am uncertain on how to address the second warning:

First warning:
"Found the following notes/warnings:
Non-staged installation was used
See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1009/2c731fe/pwrEWAS.Rcheck/00install.out' for details."

I am uncertain what is causing this issue and how I can address it. I would appreciate any assistance with this issue.

Second warning:
"This is a software package
* WARNING: Evaluate more vignette chunks.
# of code chunks: 15
# of eval=FALSE: 8
# of nonexecutable code chunks by syntax: 0
# total unevaluated 8 (53%)"

This warning is caused by the run time of pwrEWAS. If I evaluate all steps I run into a timeout error. What should I do about this?

Thank you for your help,
Stefan

**Comment by stefangraw** [comment] 2019-05-06 21:15
Hey @hpages 

I have addressed some warnings and I am down to 2 warnings. However, I do not understand the first warning and I am uncertain on how to address the second warning:

First warning:
"Found the following notes/warnings:
Non-staged installation was used
See 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1009/2c731fe/pwrEWAS.Rcheck/00install.out' for details."

I am uncertain what is causing this issue and how I can address it. I would appreciate any assistance with this issue.

Second warning:
"This is a software package

WARNING: Evaluate more vignette chunks.
\# of code chunks: 15
\# of eval=FALSE: 8
\# of nonexecutable code chunks by syntax: 0
\# total unevaluated 8 (53%)"
This warning is caused by the run time of pwrEWAS. If I evaluate all steps I run into a timeout error. What should I do about this?

Thank you for your help,
Stefan

**Comment by hpages** [comment] 2019-05-09 18:59
Hi @stefangraw ,

The "Non-staged installation was used" message is a NOTE, not a WARNING, and is on Windows only. It can be ignored.

You're using `eval=FALSE` for all the code chunks in the vignette that call `pwrEWAS()`. These code chunks use the central and most important function in your package so using `eval=FALSE` for them is not an option. The 2 calls to `pwrEWAS()` in the first code chunk each take < 20s to complete on my laptop so I don't really understand how you could run into a TIMEOUT when allowing evaluation of this code chunk. Also note that we've recently increased the time limit for `R CMD check` from 5 to 10 min. This should help you get more things evaluated in your vignette.

Note that the `pwrEWAS()` function relies on datasets hosted on GitHub (at `https://github.com/stefangraw/pwrEWAS_data`). This is not the Bioconductor's way to handle data sets. Among other problems, this approach is not compatible with Bioconductor's commitment to reproducible research. Please make these data sets available as AnnotationHub or ExperimentHub resources. Alternatively, if these data sets are annotations, you can make them available via one or several data annotation packages.

Found in the man page for `pwrEWAS()`:
```
Detailed description of in-/outputs, instructions and an example, as well as
interpretations of the example results are provided in the following vignette:
```
but there is nothing after that i.e. no pointer to the vignette is following the colon (`:`).

Best,
H.

**Comment by stefangraw** [comment] 2019-05-13 19:23
Hey @hpages ,

First, I want to thank you for your help and time! 

For the run time and TIMEOUT of the vignette: I could run the two commands under usage (with short run time), however, all results of the vignette are based on the code under "Example - Running pwrEWAS". Each command in this section runs 80min. And I would need all the results of on of these function for most subsequent code chunks. This example is based on the example in the paper and without this more elaborate example it would be very difficult to demonstrate all functions of pwrEWAS. I am uncertain on how to address this issue. Only three ideas come to my mind:
1. I could keep it the way it is.
2. I include all code chunks but I would require a greater time limit.
3. I modify the example, but then it would not coincide with the published paper and the functionality of pwrEWAS would not be demonstrated in full.
What do you think would be the best way to address this issue? 

About the data issue: accessing the data from github is a temporary fix. This is my first bioconductor submission and I wanted address any (major) issues regarding the pwrEWAS package first and than handle the submission of the data sets, rather than having several submissions in parallel. 

Good catch on the missing link of the man page, I have included the link.

I will start the submission of the data sets in the near future and modify the pwrEWAS package accordingly once the data is available though AnnotationHub or ExperimentHub.

Please let me know how to proceed with the run time issue.

Thank you!
Stefan

**Comment by hpages** [comment] 2019-05-30 09:49
I'm sorry but we don't accept packages that rely on datasets hosted on GitHub, for the reasons I explained earlier. This will need to be addressed before package acceptance. Thanks for your understanding.

H.

**Comment by stefangraw** [comment] 2019-07-08 19:47
Dear @hpages ,

Are there guides that could assist me in uploading the data to ExperimentHub? I started using https://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html , but I am not certain if I am doing the correct thing. I seemed like I am creating a complete new submission including vignette, R code, etc. 

Or do I need to follow the steps on submitting a related package as described at: https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages

Thank you for your help!
Stefan

**Comment by hpages** [comment] 2019-07-09 09:24
Hi @stefangraw,

We normally recommend hosting the data (the 10 `.rdata` files at https://github.com/stefangraw/pwrEWAS_data in your case) on ExperimentHub. The "Creating An ExperimentHub Package" vignette should explain how to do this. Yes this also requires making a data experiment package and to submit that package. Because the data is on ExperimentHub, the data experiment package won't actually contain the data so will be very light. You can ask on the bioc-devel mailing list for help about how to do this. Don't hesitate to ask for clarifications if the instructions in the "Creating An ExperimentHub Package" vignette are not clear.

Alternatively you can make a data experiment package that actually contains the data. In this case, you don't need to host the data on ExperimentHub. Just make a data package that contains the 10 `.rdata` files at https://github.com/stefangraw/pwrEWAS_data (the files should go in the `data/` folder of the package). Note that this will make the package significantly bigger. This package will also need to be submitted.

Hope this helps.

H.

**Comment by stefangraw** [comment] 2019-08-09 19:37
AdditionalPackages: https://github.com/stefangraw/pwrEWAS_data

**Comment by stefangraw** [comment] 2019-08-09 19:41
Hey @hpages 
I have created and uploaded an ExerimentHubData package. I am still somewhat uncertain if I need to have any documentation in the "man" folder, because I am not exporting any functions. What is the next step?

Thanks,
Stefan

**Comment by stefangraw** [comment] 2019-08-09 20:22
PS: I currently still have the data files in the data packages, but I will delete them in the next couple of dates and change the code in the actual packages to load them from ExperimentHubData. The data is currently available in the devel version.

**Comment by stefangraw** [comment] 2019-08-12 16:44
Hey @hpages 
I have created and uploaded an ExerimentHubData package containing my data files. I am still somewhat uncertain if I need to have any documentation in the "man" folder, because I am not exporting any functions. I tried to connect the two packages with the following command: AdditionalPackages: https://github.com/stefangraw/pwrEWAS_data
But I am not sure if the worked, because I did not get any bot response. 

I am now loading the data for pwrEWAS through ExperimentHub (still load the ExperimentHub  package within "function.R" to set the devel option, but once pwrEWAS_data makes it out of devel, I can remove these steps).

What are the next steps?

Thanks,
Stefan

**Comment by lshep** [comment] 2019-08-15 11:37
It doesn't look like it ran.  I think its singular  `AdditionalPackage`  not `AdditionalPackages` -  could you please repost the follow (`AdditionalPackage: https://github.com/stefangraw/pwrEWAS_data`)  it should trigger a build.  @hpages  can chime in about the man page but I would have at least a package man page that references your software package.

**Comment by stefangraw** [comment] 2019-08-15 13:24
AdditionalPackage: https://github.com/stefangraw/pwrEWAS_data

**Comment by stefangraw** [comment] 2019-08-15 15:27
AdditionalPackage: https://github.com/stefangraw/pwrEWAS_data

**Comment by lshep** [comment] 2019-08-15 15:30
Ah ... sorry for the confusion.   The data package is now already associated with teh issue_number.  Please add the webhook like you did for the software package.   Then version bumps to the data package will trigger the new build

**Comment by stefangraw** [comment] 2019-08-15 15:41
@lshep no that was my bad. I was wondering why I didn't trigger a new build with a version bump and thought I needed to add the package again. I totally forgot about the webhook. 

However, I was confused about the following error:
PostProcessing: Accessing git_info complete. ERROR: Repository name: 'pwrEWAS' and DESCRIPTION Package: 'pwrEWAS_data' do not match.

Does the package containing the data (here pwrEWAS_data) need to have the package name of the as the package it is associated with (here pwrEWAS)? 

I have edited my description file of the pwrEWAS_data package from pwrEWAS_data to pwrEWAS, which seemed to have fixed the error.

Thanks,
Stefan

**Comment by lshep** [comment] 2019-08-15 15:43
@mtmorgan @hpages   can packages not have an underscore in the name?

**Comment by stefangraw** [comment] 2019-08-15 15:46
@lshep should I rename pwrEWAS_data to pwrEWAS.data?

Do you know why the package is marked as timeout, even though I don't get any errors?

**Comment by lshep** [comment] 2019-08-15 15:48
I think it has to do with the mismatch of DESCRIPTION to package name.   Please wait for feedback from @mtmorgan / @hpages  before renaming.

**Comment by lshep** [comment] 2019-08-15 17:04
So after discussing it appears R does not let a package have an underscore in the name.  Please change to either a "."  or simply `pwrEWASdata`.   You will need to change the github package directory and the DESCRIPTION . When you decide please let me know and I will change in our database so that it will still be able to build.

**Comment by lshep** [comment] 2019-08-15 17:04
The timeouts occur because R cannot pull the package correctly because of this naming issue.

**Comment by stefangraw** [comment] 2019-08-15 17:50
AdditionalPackage: https://github.com/stefangraw/pwrEWAS.data

**Comment by stefangraw** [comment] 2019-08-15 17:52
@lshep No problem, I have changed the name from pwrEWAS_data to pwrEWAS.data

Do I need to unlink the previous package (pwrEWAS_data)? I link pwrEWAS.data to this package now. Could you change in the database to pwrEWAS.data?

Thanks,
Stefan

**Comment by lshep** [comment] 2019-08-15 18:13
It looks like you are all set and have both building now.  Let me know if you have any other issues with the builders else I'll leave it to @hpages  to review

**Comment by stefangraw** [comment] 2019-08-15 18:14
@lshep Excellent! Thank you for your help!
Stefan

**Comment by stefangraw** [comment] 2019-08-15 18:16
AdditionalPackage: https://github.com/stefangraw/pwrEWAS.data

**Comment by stefangraw** [comment] 2019-08-15 18:49
@hpages 
I am getting the following warnings I don't know how to address:

Warning: replacing previous import 'Biobase::cache' by 'ExperimentHub::cache' when loading 'pwrEWAS.data'
I don't believe I am using Biobase::cache

WARNING: directory pwrEWAS.data/man is empty
I still need to fill this, but I don't know what information need to be provided.

* checking for unstated dependencies in examples ... WARNING
no parsed files found
Is this caused by reading in files from GEO, that I manually downloaded, because getGEO did not work?

Thanks,
Stefan

**Comment by stefangraw** [comment] 2019-08-15 19:57
Hey @hpages 

I am getting the following warnings I don't know how to address:

WARNING: directory 'pwrEWAS.data/man' is empty
- I don't know what information in what format need to be provided in man

\* checking whether package 'pwrEWAS.data' can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import 'Biobase::cache' by 'ExperimentHub::cache' when loading 'pwrEWAS.data'
- Biobase and ExperimentHub both seem to be containing a function cache, however I am not using this function.

\* checking for unstated dependencies in examples ... WARNING
no parsed files found
- I don't know what is causing this issue or how to fix it.

If you could get me some help with these warning, I would appreciate it!
Thanks,
Stefan

**Comment by hpages** [comment] 2019-08-30 18:58
Hi @stefangraw 

Note that pwrEWAS.data doesn't need to import any package because it contains no proper R code (the package doesn't have an `R/` folder to start with). One only needs to import packages that are used **internally** in the package code itself i.e. in the functions _implemented_ in the package but the pwrEWAS.data package does not implement anything. It's basically a wrapper around a vignette. 

More precisely:
- The Biobase, GEOquery, and utils packages are only used in your `inst/scripts/make-data.R` script, which is a standalone script that is only intended to be run by you. `R CMD build` and `R CMD check` will completely ignore the script and the script is not needed during the normal use of the package. All this to say that the requirements for the script should not be reflected in the DESCRIPTION file of the package. What you should do instead is add `library()` statements at the beginning of the script to explicitly load Biobase, GEOquery, and utils. Note that this will make the `Biobase::cache` vs `ExperimentHub::cache` conflict go away.
- I see that you also import ExperimentHub but I can't see where you use it. If you intend to use it in the vignette, then you will need to put it in the `Suggests` field. Otherwise just remove it from the `Imports` field.

So you don't need to import or export anything at the moment, which means that you could get rid of the `Imports` field and your `NAMESPACE` file could be empty. Also this means that you have no symbol to document at the moment (you're not exporting anything) so you could in theory remove the `man/` folder. However, as @lshep pointed out, it's still a good idea to provide a short man page for the package (`man/pwrEWAS.data-package.Rd`).

That being said I would strongly recommend that you define and export some simple utility functions to get the datasets for the various tissue types. You could provide one no-argument function per dataset (e.g. `load_Saliva_data()`, `load_Lymphoma_data()`, etc...), or a single 1-argument function that loads the dataset specified via its argument (in the same fashion as `pwrEWAS:::loadDataset()` but you would need to choose a less generic name for the function). These functions would need to be exported and documented (the man pages are a good place to provide details about the datasets). With this approach, the vignette becomes somewhat redundant with the man page so can be removed.

Once pwrEWAS.data is ready, pwrEWAS will need to be modified to get the datasets thru pwrEWAS.data.

Hope this helps,

H.

**Comment by hpages** [comment] 2019-08-30 19:50
Actually instead of defining functions to load the datasets, a better approach is to make the datasets available via `data()`. Note that the datasets can be stored in the `data/` folder (in which case you don't need to use ExperimentHub), or, if they are hosted on ExperimentHub, you can actually put small `.R` scripts in `data/` that will fetch the datasets when the user tries to load them with `data()`. In the former case the datasets are pre-computed or static, and in the latter they are computed on-the-fly or dynamic. For example if you put the following `abc.R` file in `data/`:
```
a <- 1:15
b <- letters
c <- foo()
```
then doing `data(abc)` will compute the 3 datasets on-the-fly.

The `data()` approach allows you to hide the details of where the datasets are actually stored (i.e. in the package or on ExperimentHub). And you can change the location of the datasets without affecting the user (s/he will still get them with `data()`). So for example you could start with static datasets (i.e. pre-computed datasets stored in the package) and you would always be able to move them to ExperimentHub in the future without breaking `data(Saliva, package="pwrEWAS.data")`.

Note that providing your own utility functions to get the datasets (like I suggested earlier) also hides the details of where the datasets are actually stored. However, making the datasets available via `data()` is better because it's the standard way to access datasets so there is no need to come up with your own functions for that. Another advantage of relying on `data()` is that the datasets are discoverable with `data(package="pwrEWAS.data")` and are also documented like any other dataset i.e. via a dataset-specific man page (man pages for datasets are organized in a special way). 

One more thing: I suspect using `LazyData: true` would cause problems with dynamic datasets but I didn't test that. Anyway, generally speaking we discourage the use of `LazyData: true`.

H.

**Comment by stefangraw** [comment] 2019-09-03 19:03
@hpages 

- I have removed imports from DECRIPTION file
- I have cleared the NAMESPACE
- I have removed man/ folder (for now; possibly include later with man/pwrEWAS.data-packag./Rd)

**Regarding simple utility function to load the tissue types:**
The user will not require access to the data, s/he will only need to specify what tissue s/he is interested. However, if you still recommend to provide such functions, I can implement these. 

**Regarding having pwrEWAS load the datasets thru prwEWAS.data:**
I have modified the code of pwrEWAS to load the data from ExperimentHub. Is that incorrect?

**Regarding the storage of the data in data/:**
The data files are to big to be stored in data/ and you told me to store them at ExerimentHub.

If you still recommend to provide the user to load the data sets, do I understand correctly, that the best way would be to have tissue-specific R scripts in data/, that load the data from ExperimentHub?

Thanks,
Stefan

**Comment by stefangraw** [comment] 2019-09-14 03:22
Dear @hpages 

I have addressed the issues you mentioned (I really liked your suggestion to use switch, it feels very elegant). Focusing on pwrEWAS.data for now, I reduced the NOTES down to three and I have questions about these:

* The lines highlighted to be longer than 80 characters were either text or part of a table. Should I still reduce the characters per line here, because I feel it would it harder too read.
* The NOTE suggests to consider multiples of 4 spaces for line indents. I am using RStudio, which provides a function to auto-indent. Does this issue need to be addressed, and if so, are there any more elegant ways than doing it per hand?

Thanks,
Stefan


NOTES:
\* Checking unit tests...
    \* NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
\* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    \* NOTE: Consider shorter lines; 14 lines (18%) are > 80 characters
      long.
    First 6 lines:
      vignettes/vignette.Rmd:27 The following data sets were used to create t...
      vignettes/vignette.Rmd:32 Tissue Type              & Accession Number &...
      vignettes/vignette.Rmd:33 Saliva                   & GSE92767         &...
      vignettes/vignette.Rmd:34 Lymphoma                 & GSE42372         &...
      vignettes/vignette.Rmd:35 Placenta                 & GSE62733         &...
      vignettes/vignette.Rmd:36 Liver                    & GSE61258         &...
    * NOTE: Consider multiples of 4 spaces for line indents, 24
      lines(30%) are not.

**Comment by stefangraw** [comment] 2019-09-24 20:01
Dear @hpages

I have addressed the issues you mentioned (I really liked your suggestion to use switch, it feels very elegant). I reduced the NOTES down the following 3 types:

* functions with too many lines
* lines with too many characters
* multiples of 4 spaces for line indents

Do all of these NOTES need to be addressed? 
* The functions with >50 lines are the main functions.
* Some of the lines with > 80 characters are either text or part of a table. 
*  I am using RStudio, which provides a function to auto-indent. Does this issue need to be addressed, and if so, are there any more elegant ways than doing it per hand?

Thanks,
Stefan

**Comment by stefangraw** [comment] 2019-09-24 21:01
Dear @hpages 

I have addressed the issues you mentioned (I really liked your suggestion to use switch, it feels very elegant). I reduced the NOTES down the following 3 types:

* functions with too many lines
* lines with too many characters
* multiples of 4 spaces for line indents

Do all of these NOTES need to be addressed?

* The functions with >50 lines are the main functions.
* Some of the lines with > 80 characters are either text or part of a table.
* I am using RStudio, which provides a function to auto-indent. Does this issue need to be addressed, and if so, are there any more elegant ways than doing it per hand?

Thanks,
Stefan

**Comment by stefangraw** [comment] 2019-09-25 19:13
Dear @hpages

I have addressed the issues you mentioned (I really liked your suggestion to use switch, it feels very elegant). I reduced the NOTES down the following 2 types:

*functions with too many lines
*lines with too many characters
Do these NOTES need to be addressed?

The functions with >50 lines are the main functions.
Some of the lines with > 80 characters are either text or part of a table and indents seem to count toward this limit too.

Thanks,
Stefan

**Comment by hpages** [comment] 2019-09-27 09:21
Hi Stefan,

Thanks for these changes. Let's ignore the remaining NOTEs about functions with too many lines, lines longer than 80 characters, and indents not being multiples of 4 spaces.

Glad that you like `switch()`. Then you should also use it instead of the other chained `if-else` statement you have in the `pwrEWAS()` function.

### In the pwrEWAS.data package

- You still have many occurences of `pwrEWAS_data` in many places. They need to be replaced with `pwrEWAS.data`. Note that replacing those in your `pwrEWAS.data/inst/extdata/metadata.csv` file will also require that you change the name of the directory on the Bioconductor AWS S3 bucket where you uploaded the data if you've not done so already.

- Please add your name to the `Maintainer` field of the `metadata.csv` file (like you've done for the `Maintainer` field in your `DESCRIPTION` files).

- In the `DESCRIPTION` file of pwrEWAS.data the `Title` and `Description` fields are exactly the same as in the pwrEWAS package. This doesn't make sense. How about using the same `Title` and `Description` as in the pwrEWAS.data vignette? That is: "Reference data accompanying pwrEWAS" for `Title`, and the abstract field for `Description`.

- In your unit tests, you call `pwrEWAS.data:::loadDataset("Saliva")` 4 times in a raw in the same function (then you do the same with `pwrEWAS.data:::loadDataset("Cord-blood (whole blood)")`). As I mentioned previously, repeating the same code again and again is not good practice. In addition, it often leads to inefficient code like in this particular case. Your code will look better and be more efficient if you do `methPara <- pwrEWAS.data:::loadDataset("Saliva")` and then do all your checks on `methPara`.

### In the pwrEWAS package

- In the man page for `pwrEWAS` you still provide a link to an old static vignette on GitHub (https://github.com/stefangraw/pwrEWAS/blob/master/vignettes/vignette.pdf) that no longer exists. What you should tell the reader of your man page instead is to open the vignette with `vignette("vignette", package="pwrEWAS")`. This will open the vignette that is included in the package. Unlike a static vignette on GitHub, this one is guaranteed to be in sync with the package. Note that if you had called your vignette `pwrEWAS` then the user could open it with just `vignette("pwrEWAS")`. Same thing for the vignette in pwrEWAS.data. And BTW why not also show the command to use to open the vignette in the pwrEWAS.data man page? It's about making it easy for your users to find things. They will appreciate.

- Move the `library("pwrEWAS")` statement from the Installation to Usage section of the vignette.

### In both packages

- Always use `<-` instead of `=` for assignments.

We're almost there.

Thanks again,
H.

**Comment by stefangraw** [comment] 2019-09-27 15:35
Hey @hpages 

I believe I have addressed all the issue you listed. Is there anything else that I need to address?

Thank you,
Stefan

**Comment by hpages** [comment] 2019-09-27 16:58
Thx. One last thing: you still need to use `<-` instead of `=` for the assignments in your vignette.

H.

**Comment by stefangraw** [comment] 2019-09-27 17:33
Hey @hpages 

I have changed the assignment in the vignette. Is there anything else?

Thanks,
Stefan

**Comment by hpages** [comment] 2019-09-27 18:03
Nope. We're good. After a long and bumpy road, we're finally there. Thanks for your patience and efforts during this long review process.

Cheers,
H.

**Comment by stefangraw** [comment] 2019-09-27 18:07
@hpages Thank you for all your help, guidance and patience with me!

**Comment by hpages** [comment] 2019-09-27 18:12
No problem, you're welcome. I appreciate the fact that you were very responsive to my feedback and I believe that you've learned a few useful things along the away.

Best,
H.

**Comment by mtmorgan** [comment] 2019-09-27 19:42
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stefangraw.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pwrEWAS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pwrEWAS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2019-10-01 20:56
Re-opening to process data package.

**Comment by mtmorgan** [comment] 2019-10-01 21:08
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/stefangraw.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pwrEWAS.data")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pwrEWAS.data

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-10-01 21:08 UTC
Labels: 3a. accepted, OK
