### ISSUE TITLE
Rarr

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/Contributions#2925] opened 2023-02-09 15:30 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/grimbough/Rarr

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2023-02-09 21:00
The vignette throws
```
> s3_address <- "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0 ..." ... [TRUNCATED] 

> zarr_overview(s3_address)
List of 3
 $ Code     : chr "InvalidAccessKeyId"
```
Temporary?  Can this be made more resilient?

**Comment by grimbough** [comment] 2023-02-09 21:38
That's not an issue I've encountered in testing.  The Zarr file is an exemplar OME-NGFF image stack, specifically made available for testing, and shouldn't require any authentication to access it. 

I doubt it's temporary, seems more likely to be a setup issue I haven't encountered.  I use the `aws.s3` package to access S3, which has quite a number of ways to provide AWS credentials.  Perhaps something on the system you're using is conflicting in a way I've not seen on my own setup.  Do you have anything set for the `AWS_ACCESS_KEY_ID` environment variable?

Does the example further on in the vignette, in the section "Using credentials to access private S3 buckets" work any better?  That's on a different host and does require authentication to be set.

**Comment by LiNk-NY** [comment] 2023-02-09 23:51
FWIW I am also getting this 403 hang up:

``` r
library(Rarr)
s3_address <- "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0076A/10501752.zarr/0"
zarr_overview(s3_address)
#> Client error: (403) Forbidden
#> List of 3
#>  $ Code     : chr "InvalidAccessKeyId"
#>  $ RequestId: chr "tx00000000000000301d714-0063e57bcf-16699797-default"
#>  $ HostId   : chr "16699797-default-default"
#>  - attr(*, "headers")=List of 6
#>   ..$ content-length  : chr "199"
#>   ..$ x-amz-request-id: chr "tx00000000000000301d714-0063e57bcf-16699797-default"
#>   ..$ accept-ranges   : chr "bytes"
#>   ..$ content-type    : chr "application/xml"
#>   ..$ date            : chr "Thu, 09 Feb 2023 23:03:43 GMT"
#>   ..$ connection      : chr "Keep-Alive"
#>   ..- attr(*, "class")= chr [1:2] "insensitive" "list"
#>  - attr(*, "class")= chr "aws_error"
#>  - attr(*, "request_canonical")= chr "GET\n/idr/zarr/v0.4/idr0076A/10501752.zarr/0/.zarray\n\nhost:uk1s3.embassy.ebi.ac.uk\nx-amz-date:20230209T23034"| __truncated__
#>  - attr(*, "request_string_to_sign")= chr "[removed]"| __truncated__
#>  - attr(*, "request_signature")= chr "[removed]"| __truncated__
#> NULL
#> Error in parse_aws_s3_response(r, Sig, verbose = verbose): Forbidden (HTTP 403).
```

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Even with the OSN resource located at: 

```r
s3_address <- "https://mghp.osn.xsede.org/bir190004-bucket01/TMA11/zarr/1.zarr/0.0.0"
zarr_overview(s3_address)
```

**Comment by grimbough** [comment] 2023-02-10 13:40
Thanks for confirming. I'm able to replicate this behaviour if I set some AWS credentials, and then try to access a public bucket.  It seems that there's no easy way to temporarily override them.  Passing empty strings for the `key` and `secret` to the `aws.s3` functions has no effect - in fact the code explicitly ignores them and continues to look for credentials in other places.

A solution that works for me is to unset the enviroment variables:

```r
Sys.setenv(
  "AWS_ACCESS_KEY_ID" = "",
  "AWS_SECRET_ACCESS_KEY" = ""
)
```

However, if you have AWS credentials stored elsewhere e.g. in `~/.aws/credentials` then that will still take precedence and it'll fail.

I believe a solution to this was requested a long time ago at https://github.com/cloudyr/aws.signature/issues/61 and it doesn't look like it got any traction.  I'll have a think about how to proceed.  If anyone is aware of a different package for managing AWS authentication then happy to switch.

**Comment by vjcitn** [comment] 2023-03-03 04:19
A comment about naming came up.  Rarr and rawrr are very close.  I am not concerned about a risk of confusion but wanted to be sure this was surfaced.

**Comment by grimbough** [comment] 2023-03-10 10:54
Hi @Kayla-Morrell 

I've managed to get rid of the errors and warnings, and also successfully made the package compatible with other Zarr implementations (https://github.com/joshmoore/zarr_implementations/pull/2).  I'll stop making changes for now until you've managed to do a review.

Looking forward to your feedback!

**Comment by Kayla-Morrell** [comment] 2023-04-04 18:19
@grimbough - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review. Also, keep in mind that the deadline for packages to be accepted for the upcoming release is April 19th.

## DESCRIPTION

- [ ] SUGGESTION: We encourage including the 'BugReports:' field with the
  relevant link to GitHub for reporting Issues.

## Data 

- [ ] REQUIRED: There needs to be documentation of some kind for the data in the
  `inst/extdata/` directory. The documentation should be in an `inst/script/`
directory and the scripts can vary. They must clearly state how the data was
generated and source information. It should include source URLs and any key
information regarding filtering or processing. It can be executable code, sudo
code, or a text description. Ideally users should be able to download and
roughly reproduce the file or object that is present as data.

## Man pages

- [ ] REQUIRED: There should be runnable examples in man pages that document
  exported objects. None of the `use_*` functions have runnable examples.

## R code

- [ ] SUGGESTION: Avoid 'cat' and 'print' outside of 'show' methods
- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 68
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
  indents. There are 524 lines that are not.

Best,
Kayla

**Comment by grimbough** [comment] 2023-04-05 14:26
Hi @Kayla-Morrell thanks a lot for the review, that really helpful.  I've made the following changes.
 
> ## DESCRIPTION
> * [x]  SUGGESTION: We encourage including the 'BugReports:' field with the
>   relevant link to GitHub for reporting Issues.

I've added both a 'URL' and 'BugReports' filed to the description which link to the package's GitHub page.

> ## Data
> * [x]  REQUIRED: There needs to be documentation of some kind for the data in the
>   `inst/extdata/` directory. The documentation should be in an `inst/script/`
>   directory and the scripts can vary. They must clearly state how the data was
>   generated and source information. It should include source URLs and any key
>   information regarding filtering or processing. It can be executable code, sudo
>   code, or a text description. Ideally users should be able to download and
>   roughly reproduce the file or object that is present as data.

The data generation script existed in `inst/docker` but it wasn't documented.  I've now mode the script and Dockerfile to `inst/scripts` and added a README with a description of the example files and details of how someone could generate on their own system.

> ## Man pages
> * [x]  REQUIRED: There should be runnable examples in man pages that document
>   exported objects. None of the `use_*` functions have runnable examples.

I've added some example code to the man pages for the `use_*` functions.

> ## R code
> * [x]  SUGGESTION: Avoid 'cat' and 'print' outside of 'show' methods

I've replaced the calls to `cat` with `message`.

> * [ ]  SUGGESTION: For formating reasons, consider shorter lines. There are 68
>   lines that are > 80 characters long.

I've made an effort to reduce some of the line lengths.  Not everything has changed, but it's down to 44 lines.  In some cases I thought it made readability worse by forcing line breaks, and some of the long lines are in Rd files that are automatically generated by Roxygen.

> * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
>   indents. There are 524 lines that are not.

I'm happy with the indentation provided by Rstudio, which aligns against brackets rather than multiples of 4, and so haven't changed this.

I'll chase down why there's now a warning from a man page.  I don't see this on my local system.

**Comment by grimbough** [comment] 2023-04-05 15:26
I think the current warning is a false positive introduced by some recent changes to BiocCheck (https://github.com/Bioconductor/BiocCheck/issues/189).  I'd appreciate if you could look at the package updates assuming the warning will go away, and I'll make changes to the package if @LiNk-NY points out I'm mistaken.

**Comment by Kayla-Morrell** [comment] 2023-04-06 14:39
@grimbough - Thank you for making the necessary changes. I've looked everything over and I'm more than happy to accept the package. I don't see the WARNING as an issue because I assume it's on our end.

Best,
Kayla

**Comment by grimbough** [comment] 2023-04-06 16:36
That's awesome.  Thanks @Kayla-Morrell  for taking the time to do the review.

**Comment by lshep** [comment] 2023-04-10 14:57
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/grimbough.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Rarr")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Rarr

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-04-10 14:57 UTC
Labels: 3a. accepted, WARNINGS
