### ISSUE TITLE
ISAnalytics

### ISSUE THREAD

**Issue by GiuliaPais** [Bioconductor/Contributions#1585] opened 2020-08-10 14:53 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/calabrialab/ISAnalytics

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment] 2020-08-24 17:32
Hello @GiuliaPais - 

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        - Sequencing, SingleCell, CellBiology, DataImport

- [ ] REQUIRED: The 'BugReports:' field should link the issues on the GitHub. 

## NAMESPACE

- [ ] REQUIRED: Exported functions should use camel case or underscoring and not 
include '.' which indicates S3 dispatch.

## NEWS

- [ ] REQUIRED: The version in the NEWS.md file should be corrected.

## Vignettes

The two points below apply to both vignettes.

- [ ] REQUIRED: Before loading in the package with `library(ISAnalytics)` you 
should demonstrate to the user how to download the package using Biconductor. 
The code should look like the following and include `eval = FALSE`,

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ISAnalytics")
```

- [ ] SUGGESTION: Under the reproducibility section, a lot of the code isn't 
needed. For instance, the user will most likely access the vignette of the 
package by using `vignette(XXX)` in R, not using `render()` and `knit()`. The 
date and time aren't really needed either, we normally just ask for a session 
info section which is enough for reproducibility.

*how_to_import_functions*

- [ ] REQUIRED: The example at line 181, these code chunks should not be set 
to `eval = FALSE`. This defeats the purpose of a having a reproducable vignette.

## Man pages

- [ ] REQUIRED: Any function that isn't exported should include 
`@keywords internal` so that the function is removed from the documentation 
index. Usually man pages are only used for functions that are exported to the 
user.

- [ ] REQUIRED: Unknown package 'import_parallel_vispa2Matrices' in Rd xrefs

- [ ] REQUIRED: Consider adding runnable examples to the following man pages 
which document exported objects:
        - pipe.Rd
        - tidyeval.Rd
        - vec_restore.ISADataFrame.Rd

- [ ] REQUIRED: Usage of dontrun{} / donttest{} found in man page examples. All 
exported functions should have runnable examples. 
Found in the following file:
        - import_parallel_Vispa2Marices.Rd

## R code

- [ ] REQUIRED: 'sysdata.rdata' should be removed.

- [ ] REQUIRED: What is the purpose of 'utils-pipe' and 'utils-tidy-eval'? You 
can just import these functions from the packages.

- [ ] REQUIRED: We prefer classes to be S4 as opposed to S3, is there a reason 
you chose to go with S3 for 'ISADataFrame'? Especially since 'DataFrame' is an 
S4 class (the naming is confusing).

- [ ] REQUIRED: While running R CMD build/check and BiocCheck on this package, 
there were 100 tabs that were opened on my browser. These popups should be an 
option in the function so that the user can chose whether they want these 
reports or not.

- [ ] REQUIRED: Avoid `sapply()`, use `vapply()`. Found in file:
        - internal-functions.R line 430 and 560

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 146 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 121 lines that are not.

Best,
Kayla

**Comment by GiuliaPais** [comment] 2020-08-24 18:41
Hello @Kayla-Morrell, thanks for reviewing our package. Can I ask a few questions before we commit for changes?

> REQUIRED: We prefer classes to be S4 as opposed to S3, is there a reason
you chose to go with S3 for 'ISADataFrame'? Especially since 'DataFrame' is an
S4 class (the naming is confusing).

ISADataFrame needs to be an S3 object because it extends and uses tibble (aka tbl_df), which is an S3 object and all generics working for tibbles must work for our structure too. We can't really change this I'm afraid.

> REQUIRED: 'sysdata.rdata' should be removed.

Is this mandatory? Sysdata contains very useful internal variables for us. Should we convert them into functions instead?

>  REQUIRED: Exported functions should use camel case or underscoring and not
include '.' which indicates S3 dispatch.

Also related to the previous point, all functions containing a dot are in fact implementations of S3 generics.

>  REQUIRED: What is the purpose of 'utils-pipe' and 'utils-tidy-eval'? You
can just import these functions from the packages.

These were added automatically by devtools::use_pipe and devtools::use_tidy_eval. It allows our package to use the pipe operator %>% and tidy evaluation automatically. Since we're extensively using function from the tidyverse these steps were reccomended, should we change it anyway?

>  REQUIRED: Usage of dontrun{} / donttest{} found in man page examples. All
exported functions should have runnable examples.
Found in the following file:

> - import_parallel_Vispa2Marices.Rd

>  REQUIRED: The example at line 181, these code chunks should not be set
to eval = FALSE. This defeats the purpose of a having a reproducable vignette.

These two problems are related to the fact that the function in question is interactive, meaning it requires input from the user in the console, therefore it's not possible to run examples for this function.

Please let us know what to do with the above, in the meantime we're going to work on the other problems. Thank you in advance

**Comment by GiuliaPais** [comment] 2020-09-01 20:22
Hi @Kayla-Morrell, our package has been modified and is ready to be reviewed again. Here are our comments on changes:

# DESCRIPTION

- [X] SUGGESTION: Consider adding these automatically suggested biocViews:
     - Sequencing, SingleCell, CellBiology, DataImport
     
     We added "Sequencing" and "SingleCell" to the DESCRIPTION file, we don't find appropriate the other biocViews for our package

- [X] REQUIRED: The 'BugReports:' field should link the issues on the GitHub.

# NAMESPACE

- [X] REQUIRED: Exported functions should use camel case or underscoring and not
include '.' which indicates S3 dispatch.

The only function that include dots are now only unexported functions

# NEWS

- [X] REQUIRED: The version in the NEWS.md file should be corrected.

# Vignettes

- [X] REQUIRED: Before loading in the package with library(ISAnalytics) you
should demonstrate to the user how to download the package using Biconductor.
The code should look like the following and include eval = FALSE

Now all vignettes include an "Installation" section and also a section referencing package options and settings.

- [X] SUGGESTION: Under the reproducibility section, a lot of the code isn't
needed. For instance, the user will most likely access the vignette of the
package by using vignette(XXX) in R, not using render() and knit(). The
date and time aren't really needed either, we normally just ask for a session
info section which is enough for reproducibility.

- [ ] REQUIRED: The example at line 181, these code chunks should not be set
to eval = FALSE. This defeats the purpose of a having a reproducable vignette.

**As stated in my previous post, these chunks refer to interactive functions, meaning they require input from the user in the console, therefore it is impossible to execute those chunks of code. Despite this we think it might be actually helpful for the user to have this code in the vignette even if it's not automatically executed. Please let us know your feedback on this.**

# Man pages

- [X] REQUIRED: Any function that isn't exported should include
@keywords internal so that the function is removed from the documentation
index. Usually man pages are only used for functions that are exported to the
user.

- [X] REQUIRED: Unknown package 'import_parallel_vispa2Matrices' in Rd xrefs

This was removed

- [X] REQUIRED: Consider adding runnable examples to the following man pages
which document exported objects:
    - pipe.Rd
    - tidyeval.Rd
    - vec_restore.ISADataFrame.Rd

All of these files were removed

- [ ] REQUIRED: Usage of dontrun{} / donttest{} found in man page examples. All
exported functions should have runnable examples.
Found in the following file:
- import_parallel_Vispa2Marices.Rd

**As stated before this example refers to an interactive function and can not be run**

# R code

- [X] REQUIRED: 'sysdata.rdata' should be removed.

- [X] REQUIRED: What is the purpose of 'utils-pipe' and 'utils-tidy-eval'? You
can just import these functions from the packages.

These files were removed

- [X] REQUIRED: We prefer classes to be S4 as opposed to S3, is there a reason
you chose to go with S3 for 'ISADataFrame'? Especially since 'DataFrame' is an
S4 class (the naming is confusing).

We decided to drop this structure entirely and use tibble directly

- [X] REQUIRED: While running R CMD build/check and BiocCheck on this package,
there were 100 tabs that were opened on my browser. These popups should be an
option in the function so that the user can chose whether they want these
reports or not.

This should be fixed now, please let us know if more problems arise

- [X] REQUIRED: Avoid sapply(), use vapply(). Found in file:
- internal-functions.R line 430 and 560

- [X] SUGGESTION: For formatting reasons, consider shorter lines. There are 146
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
line indents. There are 121 lines that are not.

We actually styled every file in the package now but BiocCheck is still giving us this note for man files (these files are generated automatically by roxygen2 and we can't modify them)

Please let us know if all of the changes were sufficent, hope to hear from you soon,
Giulia

**Comment by mtmorgan** [comment] 2020-09-11 18:43
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/GiuliaPais.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ISAnalytics")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ISAnalytics

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-09-11 18:43 UTC
Labels: 3a. accepted, OK
