### ISSUE TITLE
pipeFrame and enrichTF

### ISSUE THREAD

**Issue by wzthu** [Bioconductor/Contributions#1051] opened 2019-03-21 16:48 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wzthu/pipeFrame

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by wzthu** [comment] 2019-03-22 05:11
AdditionalPackage: https://github.com/wzthu/enrichTF

**Comment by wzthu** [comment] 2019-03-27 22:52
Hi, @nturaga ! 

I think we are ready for package review now.

Thank you for taking up your time!

**Comment by wzthu** [comment] 2019-04-12 17:39
Hi @nturaga @Kayla-Morrell ,
Sorry to disturb you again.
How long will it take to review the package generally?
Is it still possible for our package to be included in Bioc 3.9 release version before May 1st?
We are looking forward to your suggestions and we are ready to revise the package ASAP.
Thank you!

**Comment by Kayla-Morrell** [comment] 2019-04-12 17:45
Hi @wzthu,

Thank you for checking in. I began reviewing your package(s) yesterday and it is my goal to get an initial review to you by Monday or Tuesday. We have until April 24th to accept packages for the release. It may be close but we should be able to make the deadline. I will comment back here as soon as the review is ready.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2019-04-17 02:35
Hello @wzthu,

Thank you for submitting to _Bioconductor_. Please see the initial review of your package below. Comment back here with updates that have been made and when the package is ready for a re-review. Please keep in mind the deadline to accept packages into this release cycle is 4/24, therefore changes should be made in a timely manner so as to give enough time for a re-review and any additional changes.

# pipeFrame review

# General package development #

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be included in _Bioconductor_ release announcements

- [ ] SUGGESTION: Consider adding unit tests, we strongly encourage them.

- [ ] SUGGESTION: Consider shorter lines, 266 lines are > 80 characters long

- [ ] SUGGESTION: Consider multiples of 4 spaces for line indents, 666 lines are not

# DESCRIPTION #

- [ ] SUGGESTION: For the 'Title:', capitalize 'pipeline'.

- [ ] SUGGESTION: For 'License:' the file is not needed since you are using a standard license.

- [ ] REQUIRED: Move `BiocManager` to 'Suggests:' since nothing is imported from it

- [ ] REQUIRED: 'LazyData:' should be set to 'FALSE', this being set to 'TRUE' can slow down the loading of packages with data.

# inst/extdata #

- [ ] REQUIRED: We require documentation on this file in an 'inst/script' directory. Must clearly document how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executible code, sudo code, or a text description. A user should be able to download and be able to roughly reproduce the file/object that is present in the data.

- [ ] CLARIFICATION: Where is this data used in this package?

# vignette #

- [ ] SUGGESTION: Change name of vignette to just 'pipeFrame' just so it's more intuitive for the user to type `vignette("pipeFrame")`. Currently the user would have to use `vignette("pipeFrame-introduction")`.

- [ ] REQUIRED: Line 67-75, I would not include this section because it's an internal function of your package. Treat this vignette as if a general user is the one working through the vignette, because this is most likely who is using it.

- [ ] CLARIFICATION: Line 140-143, when I evaluate this code I get a different output than what is shown. My output is `"hg19" "hg38" "mm9" "mm10"`.

- [ ] REQUIRED: Line 155, "prompt" is misspelled.

- [ ] REQUIRED: Line 163, there should be a space between "." and "2)".

- [ ] SUGGESTION: At the end of line 163, I would elaborate on "There are two steps". It's not very clear what the two steps apply to.

- [ ] CLARIFICATION: Line 175-181, is there a reason why this chunk of code is `eval = FALSE`?

- [ ] REQUIRED: Line 301-303, when evaluating this code I get an error and can't produce the graph. The error is below. This section is set to `eval = FALSE` so the error is not picked up when building. Fix accordingly and be sure the code is evaluated.

``` 
Error in alpha(coords$colour, coords$alpha) :
  could not find function "alpha"
```

- [ ] REQUIRED: Line 374-382, this section of code throws an error. Please fix this, the error is below. This section is set to `eval = FALSE` so the error is not picked up when building. Be sure code can be evaluated.

```
Error in getClass(Class, where = topenv(parent.frame())) :
  “RandomRegionOnGenome” is not a defined class
>
```

- [ ] REQUIRED: Line 386-391, this section of code does not evaluate properly. An error is thrown (which is below) and the section is `eval = FALSE`. Fix this code and be sure the code can be evaluated.

```
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘runOverlappedRandomRegion’ for signature ‘"missing"’
```

- [ ] REQUIRED: Line 416-506, avoid the use of direct slot access with '@'. An accessor method should be created and used instead.

# man pages #

*Step-class*

- [ ] REQUIRED: Avoid the use of direct slot access with '@' in examples. An accessor method should be created and used instead.

- [ ] REQUIRED: When running through the examples, line 350 produces an error so then the rest of the example won't execute:

```
setGenome("hg19")
Error in dir.exists(refdir) : invalid filename argument
```

*Utils*

- [ ] CLARIFICATION: Line 64, when I run through this code I do not get an error. The directory that was created was 'testdir' and you are checking for 'testdir1'. Is this correct?

*graphMng*

- [ ] REQUIRED: There should be runnable examples for this man page since the functions are exported.

*runWithFinishCheck*

- [ ] REQUIRED: The example code runs fine until the last line `setGenome("hg19")`, the error I get is below.

```
> setGenome("hg19")
Error in dir.exists(refdir) : invalid filename argument
```

*setGenome*

- [ ] REQUIRED: I am having a problem with running the examples. `getValidGenome()` works and outputs `"hg19" "hg38" "mm9" "mm10"` but I get an error for the next two lines.

```
>      setGenome("hg19")
Error in dir.exists(refdir) : invalid filename argument
>      getGenome()
Error in getGenome() : please call `setGenome` to set genome first
```

# R code #

- [ ] REQUIRED: Use various apply functions instead of `for` loops.

- [ ] REQUIRED: Avoid the use of direct slot access with '@'. Accessor methods should be created and used instead.

- [ ] REQUIRED: 'bsgenomename', 'curOrgDb', and 'curTxDb' should be listed in DESCRIPTION file not loaded in like you have in 'StepBase.R'.

- [ ] REQUIRED: Use `seq_len()` or `seq_along()` instead of `1:...`.

# enrichTF

# General package development #

- [ ] SUGGESTION: Consider adding the 'Transcription' biocView.

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be included in _Bioconductor_ release annoucements.

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. 237 lines are > 80 characters.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. 2 lines contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. 144 lines are not. 

# DESCRIPTION #

- [ ] SUGGESTION: For 'License:' the file is not needed since you are using a standard license.

- [ ] REQUIRED: 'LazyData:' should be set to 'FALSE', this being set to 'TRUE' can slow down the loading of packages with data. 

# inst/extdata #

- [ ] REQUIRED: We require documentation for all of these files in an 'inst/script' directory. Must clearly document how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executible code, sudo code, or a text description. A user should be able to download and be able to roughly reproduce the file and/or object that is present in the data.

# vignette #

- [ ] REQUIRED: Put \` \` around function names so they are formated correctly.

- [ ] SUGGESTION: Change name of vignette to 'enrichTF' just so it's more intuitive for the user to type `vignette("enrichTF")`. Currently the user would have to use `vignette("introduction")`.

- [ ] REQUIRED: Line 26, Bioc 3.9 builds on R 3.6, not 3.5.

- [ ] CLARIFICATION: Line 41-43, why is this chunk `echo=FALSE`?

- [ ] CLARIFICATION: Line 53-58, why is this chunk of code `eval=FALSE`?

- [ ] CLARIFICATION: Line 57, the comment indicates that 'testgenome' should be changed to one of 'hg19', 'hg20', 'mm9', or 'mm10'. Does this apply to the vignette as well or just in general usage?

- [ ] SUGGESTION: I would move the 'Introduction' section to before the 'Quick Start' section.

- [ ] CLARIFICATION: If the user runs like 53-58, will the rest of the output look like yours? When I ran that section of code and then start running through the vignette I got a message about the step was finished, nothing to do, `clearStepCache()`. Be sure that what ever code is present should be runable by the user and get the same output that is shown.

- [ ] CLARIFICATION: Line 161-163, why is this chynk of code `eval=FALSE`. Also, I get a warning when I run this code. See the warning below and be sure it is nothing major.

```
Warning message:
In matrix(unlist(allpValue), nrow = length(tfName), ncol = 4, byrow = TRUE) :
  data length [32] is not a sub-multiple or multiple of the number of rows [81]
>
```

- [ ] SUGGESTION: Is there anyway to show the output/results of the functions? What is the reason to run these functions? All of the code works but I'm not sure it is clear what the end goal is.

# man pages #

*MotifsInRegions*

- [ ] REQUIRED: Uncomment the final line of code in the example section.

*PECA_TF_enrich*

- [ ] REQUIRED: Uncomment the final line of code in the example section.

*TFsEnrichInRegions*

- [ ] REQUIRED: Consider adding runnable examples to the 'TFsEnrichInRegions' man page since there are exported objects.

- [ ] SUGGESTION: Be sure `dontrun{}` or `donttest{}` are run somewhere (in 'TFsEnrichInRegions').

# R code #

- [ ] REQUIRED: Avoid the use of direct slot acess with '@'. Accessor methods should be created and used instead.

- [ ] REQUIRED: Avoid the use of `sapply()`, use `vapply()` instead.

- [ ] REQUIRED: Use various apply functions instead of `for` loops.

- [ ] REQUIRED: Avoid `1:...`, use `seq_len()` or `seq_along()` instead.

Best,
Kayla

**Comment by wzthu** [comment] 2019-04-17 02:46
Thank you so much, @Kayla-Morrell ! 

We are revising the package ASAP. 

Best,
Zheng

**Comment by wzthu** [comment] 2019-04-20 12:09
Hi @Kayla-Morrell ,
We have already revised the two packages. The changes we made are listed below.
If you have any more suggestions, we can improve them at once.
Thank you again for your valuable comments. 



# pipeFrame review

## General package development


- [x]   SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements

- [x]  SUGGESTION: Consider adding unit tests, we strongly encourage them.

- [x]  SUGGESTION: Consider shorter lines, 266 lines are > 80 characters long

- Almost all lines are shorter than 80 characters long.

- [x]  SUGGESTION: Consider multiples of 4 spaces for line indents, 666 lines are not

- The line started with non multiples of 4 spaces are adjusted but some long lines are not because they need to be shorter than 80 characters long.

## DESCRIPTION
- [x]  SUGGESTION: For the 'Title:', capitalize 'pipeline'.

- [x]  SUGGESTION: For 'License:' the file is not needed since you are using a standard license.

- [x]  REQUIRED: Move BiocManager to 'Suggests:' since nothing is imported from it

- [x]  REQUIRED: 'LazyData:' should be set to 'FALSE', this being set to 'TRUE' can slow down the loading of packages with data.

## inst/extdata
- [x]  REQUIRED: We require documentation on this file in an 'inst/script' directory. Must clearly document how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executible code, sudo code, or a text description. A user should be able to download and be able to roughly reproduce the file/object that is present in the data.

- [x]  CLARIFICATION: Where is this data used in this package?

We removed the data because we can randomly generate them in the example code. So no description is added.

## vignette
- [x]  SUGGESTION: Change name of vignette to just 'pipeFrame' just so it's more intuitive for the user to type vignette("pipeFrame"). Currently the user would have to use vignette("pipeFrame-introduction").

- [x]  REQUIRED: Line 67-75, I would not include this section because it's an internal function of your package. Treat this vignette as if a general user is the one working through the vignette, because this is most likely who is using it.

We have removed them.

- [x]  CLARIFICATION: Line 140-143, when I evaluate this code I get a different output than what is shown. My output is "hg19" "hg38" "mm9" "mm10".

Because you execute the code set with eval=FALSE  before you execute `getValidGenome()`
```{r eval=FALSE}
initPipeFrame(availableGenome = c("hg19", "hg38", "mm9", "mm10"),
              defaultJobName = "test-pipeline"
)

```


- [x]  REQUIRED: Line 155, "prompt" is misspelled.

- [x]  REQUIRED: Line 163, there should be a space between "." and "2)".

- [x]  SUGGESTION: At the end of line 163, I would elaborate on "There are two steps". It's not very clear what the two steps apply to.

We add some detail description.

- [x]  CLARIFICATION: Line 175-181, is there a reason why this chunk of code is eval = FALSE?

If it is set TRUE, it will be very time consuming in the later chunk. It will build genome FASTA file from BSgenome object, which will waste a lot of time.

```{r}
setGenome("hg19")
#display the current configured genome
getGenome()
```

- [x]  REQUIRED: Line 301-303, when evaluating this code I get an error and can't produce the graph. The error is below. This section is set to eval = FALSE so the error is not picked up when building. Fix accordingly and be sure the code is evaluated.

Error in alpha(coords$colour, coords$alpha) :
  could not find function "alpha"

The bug comes from package ggDAG. The author did not fix it yet so we replace it with another package visNetwork. Now it works well.


- [x]  REQUIRED: Line 374-382, this section of code throws an error. Please fix this, the error is below. This section is set to eval = FALSE so the error is not picked up when building. Be sure code can be evaluated.
Error in getClass(Class, where = topenv(parent.frame())) :
  “RandomRegionOnGenome” is not a defined class
>

We move this section backward and set eval = TRUE. Then there is no error now.


- [x]  REQUIRED: Line 386-391, this section of code does not evaluate properly. An error is thrown (which is below) and the section is eval = FALSE. Fix this code and be sure the code can be evaluated.
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘runOverlappedRandomRegion’ for signature ‘"missing"’

We have fixed this problem and set eval = TRUE

- [x]  REQUIRED: Line 416-506, avoid the use of direct slot access with '@'. An accessor method should be created and used instead.
## man pages
Step-class


All of them are replaced with function or $


- [x]  REQUIRED: Avoid the use of direct slot access with '@' in examples. An accessor method should be created and used instead.

All of them are replaced with function or $

- [x]  REQUIRED: When running through the examples, line 350 produces an error so then the rest of the example won't execute:

setGenome("hg19")
Error in dir.exists(refdir) : invalid filename argument
Utils

We have fixed this bug now.

- [x]  CLARIFICATION: Line 64, when I run through this code I do not get an error. The directory that was created was 'testdir' and you are checking for 'testdir1'. Is this correct?

Yes, we expect it will raise an error when checking  'testdir1'.

graphMng

- [x]  REQUIRED: There should be runnable examples for this man page since the functions are exported.
runWithFinishCheck


- [x]  REQUIRED: The example code runs fine until the last line setGenome("hg19"), the error I get is below.
> setGenome("hg19")
Error in dir.exists(refdir) : invalid filename argument

We have fixed this bug.

setGenome

- [x]  REQUIRED: I am having a problem with running the examples. getValidGenome() works and outputs "hg19" "hg38" "mm9" "mm10" but I get an error for the next two lines.
>      setGenome("hg19")
Error in dir.exists(refdir) : invalid filename argument
>      getGenome()
Error in getGenome() : please call `setGenome` to set genome first

We have fixed this bug.

## R code
- [x]  REQUIRED: Use various apply functions instead of for loops.

All of them are replaced.

- [x]  REQUIRED: Avoid the use of direct slot access with '@'. Accessor methods should be created and used instead.

Necessary interfaces for user are implemented.

- [ ]  REQUIRED: 'bsgenomename', 'curOrgDb', and 'curTxDb' should be listed in DESCRIPTION file not loaded in like you have in 'StepBase.R'.

Most of user do not need to install more than one kind of gene set when they are running the pipeline. And installing all of the BSgenome OrgDb and TxDb will consume a lot of time and space. So we have to provide these functions for user to install one group of them like BSgenom OrgDb and TxDb related to genome  "hg19" when user `setGenome("hg19")`

- [x]  REQUIRED: Use seq_len() or seq_along() instead of 1:....

# enrichTF
## General package development
- [x]  SUGGESTION: Consider adding the 'Transcription' biocView.

- [x]  SUGGESTION: Consider adding a NEWS file, so your package news will be included in Bioconductor release annoucements.

- [x]  SUGGESTION: Consider adding unit tests. We strongly encourage them.

- [x]  SUGGESTION: For formatting reasons, consider shorter lines. 237 lines are > 80 characters.

- [x]  SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. 2 lines contain tabs.- [x]

- [x]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. 144 lines are not.

## DESCRIPTION
- [x]  SUGGESTION: For 'License:' the file is not needed since you are using a standard license.

- [x]  REQUIRED: 'LazyData:' should be set to 'FALSE', this being set to 'TRUE' can slow down the loading of packages with data.

## inst/extdata
- [x]  REQUIRED: We require documentation for all of these files in an 'inst/script' directory. Must clearly document how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executible code, sudo code, or a text description. A user should be able to download and be able to roughly reproduce the file and/or object that is present in the data.
## vignette
- [x]  REQUIRED: Put ` ` around function names so they are formated correctly.

- [x]  SUGGESTION: Change name of vignette to 'enrichTF' just so it's more intuitive for the user to type vignette("enrichTF"). Currently the user would have to use vignette("introduction").

- [x]  REQUIRED: Line 26, Bioc 3.9 builds on R 3.6, not 3.5.

- [x]  CLARIFICATION: Line 41-43, why is this chunk echo=FALSE?

We forget to remove this test chunk so have we removed it.

- [x]  CLARIFICATION: Line 53-58, why is this chunk of code eval=FALSE?

We set it TRUE now. We reduce test data size so it can run within the limited time.

- [x]  CLARIFICATION: Line 57, the comment indicates that 'testgenome' should be changed to one of 'hg19', 'hg20', 'mm9', or 'mm10'. Does this apply to the vignette as well or just in general usage?

They are for general usage. 'testgenome' is used for package example and vignette only.

- [x]  SUGGESTION: I would move the 'Introduction' section to before the 'Quick Start' section.

- [x]  CLARIFICATION: If the user runs like 53-58, will the rest of the output look like yours? When I ran that section of code and then start running through the vignette I got a message about the step was finished, nothing to do, clearStepCache(). Be sure that what ever code is present should be runable by the user and get the same output that is shown.

This is one of the function of pipeline framework. When the steps of pipeline are finished and user rerun the whole or part of the pipeline, it will not run again and show message that it is done. It will only run those step that is not finished.

- [x]  CLARIFICATION: Line 161-163, why is this chynk of code eval=FALSE. Also, I get a warning when I run this code. See the warning below and be sure it is nothing major.

Warning message:
In matrix(unlist(allpValue), nrow = length(tfName), ncol = 4, byrow = TRUE) :
  data length [32] is not a sub-multiple or multiple of the number of rows [81]
>

We fix this bug and set eval=TRUE with smaller test data size.

- [x]  SUGGESTION: Is there anyway to show the output/results of the functions? What is the reason to run these functions? All of the code works but I'm not sure it is clear what the end goal is.
man pages

Yes, we have shown an example result file on a  vignette table.

MotifsInRegions

- [x]  REQUIRED: Uncomment the final line of code in the example section.
PECA_TF_enrich

- [x]  REQUIRED: Uncomment the final line of code in the example section.
TFsEnrichInRegions

- [x]  REQUIRED: Consider adding runnable examples to the 'TFsEnrichInRegions' man page since there are exported objects.

- [x]  SUGGESTION: Be sure dontrun{} or donttest{} are run somewhere (in 'TFsEnrichInRegions').

We have removed dontrun.

## R code
- [x]  REQUIRED: Avoid the use of direct slot acess with '@'. Accessor methods should be created and used instead.

- [x]  REQUIRED: Avoid the use of sapply(), use vapply() instead.

- [x]  REQUIRED: Use various apply functions instead of for loops.

- [x]  REQUIRED: Avoid 1:..., use seq_len() or seq_along() instead.

**Comment by Kayla-Morrell** [comment] 2019-04-22 18:43
Hello @wzthu, 

Thank you for all the work done on these packages. I have looked over the changes made and have just a few additional notes before accepting the packages. See the secondary review below and comment back here when you are ready for me to look it over again.

# pipeFrame #

# General package development #

- [ ] Recommend cleaning up the global function 'reportList' NOTE.

# inst/NEWS #

- [ ] REQUIRED: Thank you for adding a NEWS file. The information within the NEWS file is fine but the formatting is not exactly correct. See https://bioconductor.org/developers/package-guidelines/#news for proper formatting.

# vignette #

- [ ] REQUIRED: With regards to line 153-156, I now understand why I get a different output than what is shown (because I evaluate the code with eval = FALSE) but this is what the user will do. So either run the vignette as if the user ran that chunk of code (by removing the eval = FALSE) or remove the code so the user doesn't evaluate it themself.

- [ ] REQUIRED: Line 168, 'prompt' is still misspelled (it is currently 'prumpt'), this was marked as done but it's not.

- [ ] REQUIRED: Line 177, there needs to be a space between the period and 1 ". 1)".

- [ ] REQUIRED: Line 182, there needs to be a space between the period and 2 ". 2)". This was marked as done but is not changed.

# enrichTF #

# inst/NEWS #

- [ ] REQUIRED: Thank you for adding a NEWS file. The content is fine but the formatting is not correct. See https://bioconductor.org/developers/package-guidelines/#news for formatting help.

# inst/script #

- [ ] REQUIRED: Thank you for adding documentation for the data. Please add to line 9 the name of the file in paranthesis like the rest of the entries.


Best,
Kayla

**Comment by wzthu** [comment] 2019-04-22 21:39
Hi @Kayla-Morrell ,
Thank you for fast reply!  We have fixed all of problems you mentioned.
The changes we made are listed below. 
Please tell us if there is anything else need to be changed. 
We will fixed them at once.

Best,
Zheng




# pipeFrame
## General package development
 

- [x]  Recommend cleaning up the global function 'reportList' NOTE.

- This is a bug we have fixed it.

## inst/NEWS
- [x]  REQUIRED: Thank you for adding a NEWS file. The information within the NEWS file is fine but the formatting is not exactly correct. See https://bioconductor.org/developers/package-guidelines/#news for proper formatting.

# vignette
- [x]  REQUIRED: With regards to line 153-156, I now understand why I get a different output than what is shown (because I evaluate the code with eval = FALSE) but this is what the user will do. So either run the vignette as if the user ran that chunk of code (by removing the eval = FALSE) or remove the code so the user doesn't evaluate it themself.

- In order to show the full workflow, we change the value and set it with default value including all of genomes. So it has been set eval = TRUE  now and the result is consistent with later chunk's result.

- Sorry, we forgot to save vignette file  when these three problem below had been fixed. We have re-fixed them now:

- [x]  REQUIRED: Line 168, 'prompt' is still misspelled (it is currently 'prumpt'), this was marked as done but it's not.


- [x]  REQUIRED: Line 177, there needs to be a space between the period and 1 ". 1)".

- [x]  REQUIRED: Line 182, there needs to be a space between the period and 2 ". 2)". This was marked as done but is not changed.

# enrichTF
## inst/NEWS
- [x]   REQUIRED: Thank you for adding a NEWS file. The content is fine but the formatting is not correct. See https://bioconductor.org/developers/package-guidelines/#news for formatting help.
# inst/script
- [x]   REQUIRED: Thank you for adding documentation for the data. Please add to line 9 the name of the file in paranthesis like the rest of the entries.

**Comment by mtmorgan** [comment] 2019-04-23 21:41
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wzthu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("pipeFrame")`. The package 'landing page' will be created at

https://bioconductor.org/packages/pipeFrame

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2019-04-23 21:41
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wzthu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("enrichTF")`. The package 'landing page' will be created at

https://bioconductor.org/packages/enrichTF

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-04-23 21:41 UTC
Labels: 3a. accepted, OK
