### ISSUE TITLE
panelcn.mops

### ISSUE THREAD

**Issue by gpovysil** [Bioconductor/Contributions#481] opened 2017-09-14 10:42 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bioinf-jku/panelcn.mops

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lshep** [comment] 2017-09-22 13:12
Hello, 
Thank you for your interest in submitting to Bioconductor.  Some comments and questions to be addressed: 

**Build report:** 
- [ ] Please add unit tests

**Vignette:** 
- [ ] I can't run the code to reproduce this vignette? Provide example files and actually run the code.  
i.e testbam SAMPLE1.bam is not a real file so test is NULL is the section that you are evaluating things? You then load data and have a test already generated? perhaps you meant to load the data earlier to provide pregenerated data objects? 
- [ ] please define acronyms at first occurrence (RC, ROI, etc.)
- [ ] In resultstable example you haven't defined selectedGenes to show the output you give
- [ ] resultlist used XandCB and countWindows - why not store this information so you don't have to have the user reinput it in createResultTable? 
- [ ] Can more than one result from resultlist be passed into intergerCopyNumber? Can more than one be passed into plotBoxplot? I feel like the index of interest should be passed as an argument instead of
forcing the user to subset before use? 
- [ ] In running the code it appears a file newBed.bed gets created. For vignettes, if this is part of the code that is executed, we encourage writing any output created to a temporary directory to keep user directories clean. 

**MAN:** 
- [ ] For data man pages, give more information on how it was generated. And show the data(panelcn.mops) call in an example. 
- [ ] panelcn.mops.Rd / runPanelcnMopds better description, its too generic. Describe more about what is being done
- [ ] Why have the overly complicated structure when you currently only have one file 
```
 bed <- list.files(system.file("extdata", package = "panelcn.mops"),
                         pattern = ".bed$", full.names = TRUE)
```
**INST/EXTDATA**
- [ ] What is this? document it with a man page on where it came from. 

**R CODE:** 
- [ ] we don't encourage the . in function name as it indicates S3 object implementation. change panelcn.mops function to camelcase or underscore. 
- [ ] Please see: [efficient coding](http://bioconductor.org/developers/how-to/efficient-code/)
a. Write seq_len(n) or seq_along(x) rather than 1:n or 1:length(x). This protects against the case when n or length(x) is 0 (which often occurs as an unexpected ‘edge case’ in real code) or negative.
b. There are some for loops where you could better pre-allocate and fill. 


Please update the package, ensure you have your webhook set up to get new build reports on version bumps, and comment back here with how the above have been addressed or clarification to questions.  We look forward to getting your package accepted into Bioconductor. 

Cheers, 
Lori

**Comment by gpovysil** [comment] 2017-09-25 14:06
Dear Lori,

thanks for your comments. I included most of your suggestions in the new version of the package as you can see below:

Build report:
1) unit test were added
Vignette:
1) I removed the bam file prior to submitting to Bioconductor because it was too large. I included now a statement in the vignette that this code should not be run and also adapted the example in the man page. Additionally I moved the loading of the data to the beginning of the vignette.
2) All acronyms are now defined at first occurrence.
3) selectedGenes is now defined in chapter 4 with the rest of the object used for the resulttable example.
4) Since both XandCB and countWindows can be fairly large objects and are reused for different resultlist objects I would prefer not to store them in the resultlist objects.
5) intergerCopyNumber is a function of the cn.mops package and only takes individual objects of the S4 class CNVDetectionResult as input. To make everything analogous to cn.mops I would prefer to use plotBoxplot the same way. Additionally the subsetting only has to be done once and plots for different genes can be created, otherwise the user would always have to input 2 parameters.
6) Thank you for pointing out that a new file gets created when compiling the vignette. I set the evaluation of the code to false because in my opinion using a temporary directory might confuse the user. I hope that’s ok.

MAN:
1) I included detailed descriptions and examples for the data man pages
2) Thanks for pointing out that the descriptions were missing for panelcn.mops and runPanelcnMops, I added them.
3) Originally I had more than one file in the extdata folder. I changed it now to system.file("extdata/Genes_part.bed", package = "panelcn.mops")

INST/EXTDATA
1) This is the BED file that defines the windows. I do not understand how I should create a man page for it since I could not find any package that has created man pages for data stored in extdata. Could you point me to an existing package with such a man page?

R CODE:
1) I totally understand your concern. However, the analogous function in the cn.mops package is called cn.mops, therefore I’m afraid users of cn.mops would be confused if we changed it to camelcase or underscore for panelcn.mops.
2) a) Thanks for pointing that out, I was not aware of the functions. I changed everything accordingly.
b) Which for loops do you mean?

Again thanks for your efforts!

**Comment by lshep** [comment] 2017-09-26 17:41
Thank you for your updates and comments.  I recognize the desire to be consistent with cn.mops and in this case will allow. 

A few minor things: 
**Vignette:** 
There is a small typo where you define ROI resion -> region 
Thank you for including the BAM file not included this section isn't run. Could you also just add that you provided the test object as part of the data. 
**inst/extdata:** 
We like to ensure that data provided is freely available and reproducible with generally some information on how it was generated.  Since this file is used as more of a generalized example and depicts proper format, I agree documentation isn't necessary. (although still encouraged to include a brief note on how it was generated in vignette or man page but not necessary)
**R code**
Any of the for loops.  I'm not completely familiar with your code so I don't know off hand if it is possible to predetermine the lengths of the vectors that are being populated rather than the 'copy-and-append" approach. If it is possible, it is more efficient and saved memory.  See section [‘Pre-allocate and fill’ if iterations are necessary](http://bioconductor.org/developers/how-to/efficient-code/). It may not be possible with your code but I wanted to mention it for review and as good practice. 

Please do another version bump and comment when the typos are corrected.  

Cheers, 
Lori

**Comment by gpovysil** [comment] 2017-09-28 05:57
I fixed the typo and added statements about the test object and BED file to the vignette.

Thanks again for your suggestions, I will keep them in mind for future projects.

**Comment by mtmorgan** [comment] 2017-10-04 15:53
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/gpovysil.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"panelcn.mops\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/panelcn.mops

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Closed by mtmorgan** 2017-10-04 15:53 UTC
Labels: 3a. accepted, OK
