### ISSUE TITLE
MultiRNAflow

### ISSUE THREAD

**Issue by loubator** [Bioconductor/Contributions#2934] opened 2023-02-15 10:09 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/loubator/MultiRNAflow

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2023-03-03 04:00
I noticed that you have two vignettes, one in Rmd and one in Rnw format.  There has been a project to reduce complexity by converting Rnw to Rmd.  See https://bioconductor.github.io/biocblog/posts/2023-01-22-OutreachyInternship/#sweave2rmd-project and be in touch with @BerylKanali if you would like to try project  tooling for conversion.

**Comment by HelenaLC** [comment] 2023-03-21 08:07
Hi, just checking in... Are you working on a fix? Except for special cases, in-depth review doesn't occur until the package yields a clean installation and build report.

**Comment by loubator** [comment] 2023-03-26 20:52
Hi,

I am working on a fix.
I used the functions check() and bio check() and they both return no error and warning on my computer and two others computers.
I think I will do a second submission by Friday.

**Comment by HelenaLC** [comment] 2023-04-05 12:36
First round of comments below. The most important on being unit tests, given the package's overall complexity... Note that many are suggestions and not strictly required. Please comment back here with what has/not been addressed how/why not, or any comments regarding any needed clarification or questions you might have.

# DESCRIPTION

- [ ] Please bump `Depends: R (>= 4.2)` to 4.3 (Bioc 3.17 will in any case not be installable under the most current R version)

- [ ] Consider adding a `BugReports:` field that point to https://github.com/loubator/MultiRNAflow/issues.

- [ ] `Title:` "A R package" should be "An R package"

# documentation

- [ ] Consider adding a package *.man* page so users would get an overview of the package's basic workflow and key functions with `?MultiRNAflow`.

# vignette

- [ ] To distinguish code (e.g., function, variable, package names) from plain text, please consider consistently using code-style to highlight it (i.e., back-ticks). This currently done for some (e.g., `?function`), but not all R code (e.g., `function()`).

- [ ] Besides the introduction, the vignette currently contains only a "quick workflow". Please expand on this, e.g., providing details on each step, description of relevant argument settings, overview and interpretation of function outputs and visualizations etc. From the vignette, users should ideally be able to understand and possibly adjust the workflow rather than blindly execute a series of functions.

- [ ] There's a comment that "Bioconductor recommends and checks" (from the template I assume...). Please remove this.

- [ ] `eval=FALSE` flags and similar undermine the benefit of vignettes and are generally not allowed (see [here](http://contributions.bioconductor.org/docs.html?q=eval=FALSE#vignettes) for details).

- [ ] I'm not sure if the table of contents title "INDICE" is perhaps French, but it's unknown to me... Perhaps sticking to the default "Contents" would be clearer.

# other

- [ ] The LICENSE is a template. It contains instructions how to apply it to your software, but these have not been followed... e.g., there are placeholders like <program>, <year>, <name of author>. Please provide a proper licence specification, or have a look at how other packages do this if it helps.

- [ ] The script in `data-raw` should go in `inst/script` (see [here](http://contributions.bioconductor.org/docs.html?q=extdata#doc-inst-script) for details).

- [ ] The NEWS file is still at v.0.99.0 - please remember to track changes here.

# code

- [ ] Some functions expect a specific type and/or structure of input, e.g., extracting bits of data by name from specific locations. I'd recommend including some validity check for function inputs early on as to avoid users from encountering confusing/uninformative failures (e.g., which type of object is expected? which type of slots need to be present? etc.).

- [ ] We strongly encourage unit tests... there is currently only one. Especially given the packages size, it would be highly beneficial to put some work into this - you'll be grateful in the long run (see [here](https://contributions.bioconductor.org/tests.html?q=unit%20te#tests) for some motivation and guidelines).

- [ ] You should refrain from using `@` for accession, and instead use designated accessor/replacement methods. E.g., `DEanalysisGroup.R` line 108.

- [ ] There coding style is quite inconsistent, and there are many places without a single space... please consider having a look at the coding style guidelines outlined [here](http://contributions.bioconductor.org/r-code.html?q=style#coding-style).

- [ ] The recommended line-width is 80 characters, with 4 spaces for indentation (see [15.2.7.1 Indendation](http://contributions.bioconductor.org/r-code.html?q=style#indentation)). The current vertical code alignment produces a lot of white space that expands the code much wider than need be, making it quite hard to read.

- [ ] Path construction via `paste(..., "/", ..., sep="")` is not OS-agnostic; please use `file.path(..., ...)` instead.

- `if (is.null(...) == FALSE)` can be written as `if (!is.null(...))` (which can be read as "if *not* is *null*")
- similarly, `if (... == FALSE)` is equivalent to `if (!...)`
- `paste(..., sep = "")` is equivalent to `paste0(...)`

**Comment by loubator** [comment] 2023-04-06 14:31
Hello @HelenaLC  , many thanks for your review and suggestions.
I just need one clarification about

> Consider adding a package .man page so users would get an overview of the package's basic workflow and key functions with ?MultiRNAflow.

I think I do not understand because I already put a folder called "man" in the MultiRNAflow package. Is it related?

Can you give me more information about this suggestion (example, links, ...)?

I will do a new push on push on git.bioconductor.org by the end of the next week (maximum) in order to make sure to take into account all your suggestions. 

Thanks, and regards,

Rodolphe

**Comment by HelenaLC** [comment] 2023-04-06 15:00
As long as a general help page on what the package is about, maybe links to key functions, or info on where to post issues pops up in R when someone does ?MultiRNAflow, you are good - that’s all I meant. You can check out what other people do there by just trying it locally for e.g. ?scater. If you already got this and I missed it, then there’s nothing to do. 
Re pushing updates - remember the release is approaching soon & there might be outstanding changes. So the sooner the better…

**Comment by HelenaLC** [comment] 2023-04-14 13:46
I see that you pushed an update, however, you didn't respond to the comments raised above, and I can see that many have not been addressed (e.g., no package man page making it hard to digest/browse functionality; you are still using `@` for accession; there is still virtually no unit tests, which is quite worrisome given the overall package size/complexity...). Please provide a response in the future summarizing changes / lack of changes etc., to facilitate the review process and get additional input on anything that isn't clear during development.
Also, there are 2 vignettes (as mentioned previously by Vince), though the .Rmd one does not contain any visualizations. These are rendered via `\includegraphics` in the .Rnw one, which defeats the purpose of dynamically generated, reproducible content as produced by running the code as it is. 

Finally, you are importing the `SummarizedExperiment` (SE) class now, however, it is still not being used to it's potential in many places. To given an example, `DATAnormalization` operates on and returns a `data.frame`, requiring additional arguments to specify columns for gene names and sample metadata. In a SE, all such information would be stored in a standardized way, such that users wouldn't have to handle multiple (potentially out of synch) objects. And, there is already vast infrastructure including PCA and visualizations, which `MultiRNAflow` seems to provide a standalone pipeline without "interacting" with the ecosystem in any way...
Core and community members been creating code used by all bioinformaticians worldwide for 20 years now. The value of 
self-describing, coherently linked data structures for `assay` + sample metadata (`colData`) + feature metadata (`rowData`) is attested to by this history. The value of an ecosystem with highly self-descriptive data structures is definitely compromised when packages come in that don't participate in the framework. So please consider how you and your users can take advantage of Bioconductor infrastructure, if you want to be reviewed and distributed in Bioconductor.

**Comment by loubator** [comment] 2023-04-14 15:01
Hello @HelenaLC,

I think I made a mistake in the update because in the new version I deleted all the '@' for accession and I have 21 unit tests.
Sorry to have bothered you.
I will make sure to follow more carefully all steps of the update process and to take account all remarks.

**Comment by HelenaLC** [comment] 2023-07-18 05:42
Any updates on this?

**Comment by loubator** [comment] 2023-07-18 18:57
> Any updates on this?

Hi @HelenaLC,

Yes an update is coming. I just need a little more time because I am writing my manuscript thesis with an upcoming deadline.
Based on my deadlines (thesis), I should upload a new update in maximum two weeks.

Regards,

Rodolphe

**Comment by loubator** [comment] 2023-08-11 22:24
Hi @HelenaLC,
I have done all necessary updates based on your remarks.

However, I am struggling to push updates with the different terminal code.
I tried the codes given in the web page https://contributions.bioconductor.org/git-version-control.html
There are no errors, but I think no updates have been pushed on git@git.bioconductor.org

As I am very new to git and GitHub, I still do not understand where I am wrong.
I hope to figure out soon my problem.

Regards,

Rodolphe

**Comment by loubator** [comment] 2023-08-11 23:04
> First round of comments below. The most important on being unit tests, given the package's overall complexity... Note that many are suggestions and not strictly required. Please comment back here with what has/not been addressed how/why not, or any comments regarding any needed clarification or questions you might have.
> 
> # DESCRIPTION
> * [x]  Please bump `Depends: R (>= 4.2)` to 4.3 (Bioc 3.17 will in any case not be installable under the most current R version)
> * [x]  Consider adding a `BugReports:` field that point to https://github.com/loubator/MultiRNAflow/issues.
> * [x]  `Title:` "A R package" should be "An R package"
> 
> # documentation
> * [x]  Consider adding a package _.man_ page so users would get an overview of the package's basic workflow and key functions with `?MultiRNAflow`.

As in the package scater you suggested, I add a R function (so a .man page) "MultiRNAflow-package.R"

> 
> # vignette
> * [x]  To distinguish code (e.g., function, variable, package names) from plain text, please consider consistently using code-style to highlight it (i.e., back-ticks). This currently done for some (e.g., `?function`), but not all R code (e.g., `function()`).
> * [x]  Besides the introduction, the vignette currently contains only a "quick workflow". Please expand on this, e.g., providing details on each step, description of relevant argument settings, overview and interpretation of function outputs and visualizations etc. From the vignette, users should ideally be able to understand and possibly adjust the workflow rather than blindly execute a series of functions.
> * [x]  There's a comment that "Bioconductor recommends and checks" (from the template I assume...). Please remove this.
> * [x]  `eval=FALSE` flags and similar undermine the benefit of vignettes and are generally not allowed (see [here](http://contributions.bioconductor.org/docs.html?q=eval=FALSE#vignettes) for details).

I only use `eval=FALSE` at the beginning of the Rnw file in section "Preamble" in order to give help installing CRAN and Bioconductor packages

> * [x]  I'm not sure if the table of contents title "INDICE" is perhaps French, but it's unknown to me... Perhaps sticking to the default "Contents" would be clearer.
> 
> # other
> * [x]  The LICENSE is a template. It contains instructions how to apply it to your software, but these have not been followed... e.g., there are placeholders like , , . Please provide a proper licence specification, or have a look at how other packages do this if it helps.
> * [x]  The script in `data-raw` should go in `inst/script` (see [here](http://contributions.bioconductor.org/docs.html?q=extdata#doc-inst-script) for details).
> * [x]  The NEWS file is still at v.0.99.0 - please remember to track changes here.


> 
> # code
> * [x]  Some functions expect a specific type and/or structure of input, e.g., extracting bits of data by name from specific locations. I'd recommend including some validity check for function inputs early on as to avoid users from encountering confusing/uninformative failures (e.g., which type of object is expected? which type of slots need to be present? etc.).
> * [x]  We strongly encourage unit tests... there is currently only one. Especially given the packages size, it would be highly beneficial to put some work into this - you'll be grateful in the long run (see [here](https://contributions.bioconductor.org/tests.html?q=unit%20te#tests) for some motivation and guidelines).

There are 45 unit tests distributed in 25 files in the folder testthat



> * [x]  You should refrain from using `@` for accession, and instead use designated accessor/replacement methods. E.g., `DEanalysisGroup.R` line 108.
> * [x]  There coding style is quite inconsistent, and there are many places without a single space... please consider having a look at the coding style guidelines outlined [here](http://contributions.bioconductor.org/r-code.html?q=style#coding-style).
> * [ ]  The recommended line-width is 80 characters, with 4 spaces for indentation (see [15.2.7.1 Indendation](http://contributions.bioconductor.org/r-code.html?q=style#indentation)). The current vertical code alignment produces a lot of white space that expands the code much wider than need be, making it quite hard to read.

I improved it but not completely

> * [x]  Path construction via `paste(..., "/", ..., sep="")` is not OS-agnostic; please use `file.path(..., ...)` instead.
> * `if (is.null(...) == FALSE)` can be written as `if (!is.null(...))` (which can be read as "if _not_ is _null_")
> * similarly, `if (... == FALSE)` is equivalent to `if (!...)`
> * `paste(..., sep = "")` is equivalent to `paste0(...)`

Done

I also used SummarizedExperiment class in a better way (I hope) and that helped me to improve inputs of other functions.
Inputs of several functions have been changed.

I hope I pushed everything correctly this time (for instance I hope you can now see all unit tests).

Regards,

Rodolphe

**Comment by HelenaLC** [comment] 2023-08-14 08:59
Thanks for addressing most of the raised points, most of which look good to me now! There are 2 outstanding "issues" I see... 
1. I see that many functions now return a list with, e.g., a plot and `SummarizedExperiment`(SE) element. However, the point of using the SE-class in the first place is for functions to take a SE as input and output *directly*, and add/alter bits of data along the way. E.g., `PCAAnalysis()` should store results in the object, and anything that "doesn't fit" could be stored as `metadata()`, or returned independently (e.g., just plotting something). Having a heterogeneous list as output is rarely a good nor necessary option.
For example, the `SingleCellExperiment` class, which extends the `SummarizedExperiment`, can also stored `reducedDims` such as PCA. Similarly, `HCPCanalysis()` clustering results should be stored as `colData` and not be returned as an independent `data.frame`.
I'd encourage you to have a look at other RNA-seq workflow packages (there are many!!) to see what things could look like. Ideally, there's 1 object flowing through the analysis (taking and returing a S(C)E object, but no plots), with independent functions to visualization parts of the results (returning plots, but no objects), such as `DATAplotExpressionGenes()` to give one example.

2. While there are some unit tests now, coverage is very minimal (6%), with 1000s of untested lines. I strongly encourage you to improve this; an overall coverage of >90% would be desirable, especially with a package of this size (in terms of code). However, because unit tests are a recommendation and not requirement by Bioc at the moment, this will not keep the package from being accepted...

```r
# devtools::devtools::test_coverage()
MultiRNAflow Coverage: 6.24%
R/DEanalysisGlobal.R: 0.00%
R/DEplotAlluvial.R: 0.00%
R/DEplotBarplot.R: 0.00%
R/DEplotBarplotFacetGrid.R: 0.00%
R/DEplotVennBarplotGroup.R: 0.00%
R/DEplotVennBarplotTime.R: 0.00%
R/DEanalysisTimeAndGroup.R: 0.38%
R/GSEApreprocessing.R: 0.50%
R/DEresultGroupPerTime.R: 0.76%
R/PCAgraphics.R: 0.89%
R/DEplotVolcanoMA.R: 0.94%
R/DEplotHeatmaps.R: 1.04%
R/DEanalysisTime.R: 1.09%
R/DEresultGroup.R: 1.19%
R/DATAplotExpression1Gene.R: 1.85%
R/DATAplotBoxplotSamples.R: 2.04%
R/HCPCanalysis.R: 2.29%
R/DEanalysisGroup.R: 3.08%
R/DEplotBarplotTime.R: 3.77%
R/PCAanalysis.R: 4.62%
R/GSEAQuickAnalysis.R: 5.17%
R/PCArealization.R: 5.71%
R/DATAnormalization.R: 5.81%
R/DATAplotExpressionGenes.R: 10.53%
R/PCApreprocessing.R: 12.50%
R/MFUZZclustersNumber.R: 12.99%
R/DEanalysisSubData.R: 23.29%
R/MFUZZanalysis.R: 24.36%
R/DATAprepSE.R: 67.39%
R/ColnamesToFactors.R: 76.14%
R/RawCountsSimulation.R: 80.00%
R/CharacterNumbers.R: 100.00%
```

**Comment by loubator** [comment] 2023-08-21 14:56
> Thanks for addressing most of the raised points, most of which look good to me now! There are 2 outstanding "issues" I see...
> 
> 1. I see that many functions now return a list with, e.g., a plot and `SummarizedExperiment`(SE) element. However, the point of using the SE-class in the first place is for functions to take a SE as input and output _directly_, and add/alter bits of data along the way. E.g., `PCAAnalysis()` should store results in the object, and anything that "doesn't fit" could be stored as `metadata()`, or returned independently (e.g., just plotting something). Having a heterogeneous list as output is rarely a good nor necessary option.

Done, I hope to have correct this issue correctly.

> 2. While there are some unit tests now, coverage is very minimal (6%), with 1000s of untested lines. I strongly encourage you to improve this; an overall coverage of >90% would be desirable, especially with a package of this size (in terms of code). However, because unit tests are a recommendation and not requirement by Bioc at the moment, this will not keep the package from being accepted...

I add a lot of unit tests, now there are 197 unit tests in 31 files. So now, the coverage comes from 6% to 60%

**Comment by loubator** [comment] 2023-08-21 14:57
I forgot to add @HelenaLC 

Regards,

Rodolphe

**Comment by loubator** [comment] 2023-09-03 16:23
Hi @HelenaLC,

Is this version of the package good enough to be accepted ?

Regards,

Rodolphe

**Comment by lshep** [comment] 2023-09-12 17:31
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/loubator.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MultiRNAflow")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MultiRNAflow

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-09-12 17:31 UTC
Labels: OK, 3a. accepted
