### ISSUE TITLE
Discordant R Package Try #2

### ISSUE THREAD

**Issue by siskac** [Bioconductor/Contributions#178] opened 2016-10-23 17:59 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/siskac/discordant

Confirm the following by editing each check box to '[x]'
- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [ x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.
- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by vobencha** [comment] 2016-11-03 20:38
Hi,
Please fix these issues raised in the Single Package Builder:
* Checking native routine registration...
    * WARNING: Register native routines! see
      http://cran.r-project.org/doc/manuals/R-exts.html#Registering-native-routines

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

* Checking man pages...
    * WARNING: Add non-empty \value sections to the following man
      pages:
      fishersTrans.Rd, TCGA_Breast_miRNASeq.Rd,
      TCGA_Breast_miRNASeq_voom.Rd, TCGA_Breast_RNASeq.Rd,
      TCGA_Breast_RNASeq_voom.Rd, TCGA_GBM_miRNA_microarray.Rd,
      TCGA_GBM_transcript_microarray.Rd

Please remove Discordant_vignette.pdf and discordant_0.99.0.tar.gz from the top level of the package. 

Once that's done I'll do a full review.

Valerie

**Comment by vobencha** [comment] 2016-11-16 03:33
Checking in. Are you planning to submit an updated version of the package?

Valerie

**Comment by siskac** [comment] 2016-11-16 03:35
I’m so sorry, I keep getting hit with deadlines every time I make time to deal with this. I will try to get it done by the end of this week.

Charlotte Siska

**Comment by siskac** [comment] 2016-11-21 21:48
Hello Valerie, I’ve made the updates. I did check with Bioccheck, and the same errors are coming up. I registered to Bioconductor, fixed the man pages and pretty sure I registered my C code. Could you please look at it and tell me what to fix? Thanks.

Charlotte Siska

**Comment by vobencha** [comment] 2016-11-21 22:35
All of the errors are exactly the same as the last build report?

**Comment by siskac** [comment] 2016-11-21 23:55
I see what I did wrong - I got confused where to register, and did it on the mailing list but not the support. Still getting errors about registering native routines, which I thought I did. I followed the instructions given in the link you sent. I had to take out the description of datatypes (REALSXP, INTSXP) because it was causing an error while compiling. Do you have any advice?

Thanks,
Charlotte Siska

**Comment by vobencha** [comment] 2016-11-22 01:09
No, without seeing the error I can't help. Please bump the version and commit to the master branch. The single package builder will produce another build and I'll see the remaining errors in that output.

For an example of a package that uses C code and registers routines look at GenomicAlignments:
svn co https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/GenomicAlignments

Valerie

**Comment by siskac** [comment] 2016-11-22 19:00
I figured out how to register native routines. Thank you for the help. I just pushed the updated version onto github. Please let me know if you need anything else.

Charlotte Siska

**Comment by vobencha** [comment] 2016-11-23 21:54
You need to bump the version in your master github branch. This is the trigger for the single package builder. Once that's done we should see a new build report.
Valerie

**Comment by vobencha** [comment] 2016-11-29 14:32
Can you please bump the version?

**Comment by siskac** [comment] 2016-11-29 17:46
I think I just bumped the version. I apologize, I’m new to this and I thought updating the version in the DESCRIPTION file did they trick. Please let me know if it works.

Charlotte Siska

**Comment by siskac** [comment] 2016-12-07 20:48
so, I am really confused. I bumped the version, but a new build report was not created? I bumped it on git, was I supposed to do it on svn as well? Any insights would be appreciated.

Charlotte Siska

**Comment by vobencha** [comment] 2016-12-07 20:58
It should have been. I'll ask Lori for a forced build.

**Comment by siskac** [comment] 2016-12-08 21:22
I searched the errors on the internet, and I found on the forum this error can happen at random. http://thread.gmane.org/gmane.science.biology.informatics.conductor.devel/9264

Should I do another build? Or is there something I can do to prevent this error in the future?

**Comment by vobencha** [comment] 2016-12-08 21:44
You can ignore the MiKTeK errors for now. We see this warning on linux:

* creating vignettes ... OK
Warning: inst/doc files
    Discordant_vignette.Rnw, Discordant_vignette.pdf
  ignored as vignettes have been rebuilt.

You need to remove the inst/doc directory and the build/ directory. Bump the version and resubmit.
Valerie

**Comment by siskac** [comment] 2016-12-08 23:35
ok I just removed the directories and bumped the version but not seeing any build. is there another step that I am missing? Thanks.

**Comment by vobencha** [comment] 2016-12-09 23:31
I'm able to reproduce this error on my linux system so it is real, not a problem with the builders:

* creating vignettes ... ERROR
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'Discordant_vignette.tex' failed.
BibTeX errors:
The top-level auxiliary file: Discordant_vignette.aux
The style file: ieeetr.bst
I couldn't open database file Discordant_bib_v3.bib
---line 46 of file Discordant_vignette.aux
 : \bibdata{Discordant_bib_v3
 :                           }
I'm skipping whatever remains of this command
I found no database files---while reading file Discordant_vignette.aux
Calls: <Anonymous> -> texi2pdf -> texi2dvi
Execution halted

**Comment by siskac** [comment] 2016-12-09 23:32
I realized what happened, i accidentally deleted my .bib file for the vignette. Attempting to fix it now.

charlotte

**Comment by siskac** [comment] 2016-12-11 20:47
It seems with latest version 0.99.5 there are no errors in  malbec2, but still getting errors about the vignette for tokay2 and oaxaca. Please let me know how I should proceed.

**Comment by vobencha** [comment] 2016-12-12 15:03
Hi,

We can ignore the MiKTeK errors on windows and mac for now. I've done the full review and below are some comments and suggestions.

1) Add Depends R (>= 3.4) in DESCRIPTION; all new packages are developed against the devel branch.

2) inputs

Biocondcutor encourages interoperability between packages. If methods in your package support (as input) the base infrastructure classes it's easier for a user to apply your method to their data.

Please have a look at the ExpressionSet, SummarizedExperiment or MultiAssayExperiment classes.

  http://www.bioconductor.org/packages/3.5/bioc/html/Biobase.html

  http://www.bioconductor.org/packages/3.5/bioc/html/SummarizedExperiment.html

  http://www.bioconductor.org/packages/3.5/bioc/html/MultiAssayExperiment.html

One of those should be appropriate as inputs, e.g., please support one of these classes as the

- 'mat' argument in split.MADOutlier()

- 'x' and 'y' arguments in createVectores() and discordantRun()

3) \details in man pages

Please add a \details section to these man pages: createVectors.Rd, discordantRun.Rd, fishersTrans.Rd and splitMADOutlier.Rd. Explain a bit about what they do and how they are unique to the package, e.g., a fisher transformation is

4) \value in man pages

The \value section should describe the output object in general and then list specifics. Using split.MADOutlier() as an example,

\value{
  \item{mat.filtered}{Input matrix where features with outliers filtered out.}
  \item{index}{Index of features that have no outliers.}
}

If I run the example at the bottom of the page I get a 'mat.filtered' variable. There is no guarantee the use will name this result 'mat.filtered' so it doesn't make sense to document that name in as output in \value. The actual output is a matirx:

> class(mat.filtered)

With these dimnames (what do they mean?):

> dimnames(mat.filtered)
[[1]]
[1] "hsa-mir-574"

[[2]]
 [1] "1"    "1.1"  "1.2"  "1.3"  "1.4"  "1.5"  "1.6"  "1.7"  "1.8"  "1.9"
[11] "1.10" "1.11" "1.12" "1.13" "1.14" "2"    "2.1"  "2.2"  "2.3"  "2.4"
[21] "2.5"  "2.6"  "2.7"  "2.8"  "2.9"  "2.10" "2.11" "2.12" "2.13" "2.14"
[31] "2.15" "2.16" "2.17" "2.18" "2.19" "2.20" "2.21" "2.22" "2.23" "2.24"
[41] "2.25" "2.26" "2.27" "2.28" "2.29" "2.30" "2.31" "2.32" "2.33" "2.34"
[51] "2.35" "2.36" "2.37" "2.38" "2.39" "2.40" "2.41"

I don't see an 'index' as part of the output so I'm not sure why it's documented in \value. This needs to be fixed in all function man pages not just split.MADOutlier().

5) \arguments section on man pages

On fisherTrans.Rd the 'rhoV' input is described as a integer or numeric list. It's not a list but a vector:

> class(rhoV)
[1] "numeric"
> is(rhoV, "list")
[1] FALSE

Please double check the object types you've listed for the inputs.

6) dependencies

i) Please remove this from the vignette:

\section{Required packages}
R packages WGCNA, gtools, MASS and tools are required.

When the DESCRIPTION and NAMESPACE are properly specificed you don't need to tell the use what packages discordant depends on. When biocLite("discordant") is called, all depedencies are automatically loaded.

ii) You load MASS in the fisherTrans() example for mvrnorm(). This is fine but if you expect the user to need this and other functions from MASS you could put it in 'Depends' in DESCRIPTION. I don't think the MASS package is heavy to load and it may be a good idea to make all those functions available to the user by just loading discordant.

7) Please format your code to a max of 80 characters wide.

8) evaluate vignette code chunks

None of your code chunks are evaluated. Instead they are wrapped in \begin{verbatim}, \end{verbatim}. Please remove the verbatim statements and evaluate the code.

We recommend the use of the BiocStyle pacakge:

  http://www.bioconductor.org/packages/3.5/bioc/html/BiocStyle.html

There are vignettes on the package landing page that show how to create a pdf or html vignette.

9) add checks for input values

I would recommend adding some checks in your code to confirm the inputs are what you expect. For example, if I give a 'groups' vector of length 2 to createVectors() no warning or error is thrown and yet the NAs are probably not what was intended. If it's expected that 'groups' is recycled that should be in the documentation.

> vectors1 <- createVectors(TCGA_GBM_transcript_microarray, TCGA_GBM_miRNA_microarray, groups = groups)

> sapply(vectors1, function(xx) sum(is.na(xx)))
v1 v2
 0  0

> vectors2 <- createVectors(TCGA_GBM_transcript_microarray, TCGA_GBM_miRNA_microarray, groups = groups[1:2])

> sapply(vectors2, function(xx) sum(is.na(xx)))
 v1  v2
  0 200

Let me know if you have questions.

Valerie

**Comment by vobencha** [comment] 2016-12-29 14:07
Checking in. I'd like to finalize the package next week if at all possible.
Let me know if you have questions.
Valerie

**Comment by siskac** [comment] 2016-12-29 14:31
I am just about done with edits you gave, but I am having issues with biocstyle in the vignette. Could you direct me to a r package that has a vignette I could reference? Thanks.

**Comment by vobencha** [comment] 2016-12-29 16:36
Both GenomicTuples and genoset use BiocStyle,

http://www.bioconductor.org/packages/3.5/bioc/html/GenomicTuples.html
http://www.bioconductor.org/packages/3.5/bioc/html/genoset.html

**Comment by siskac** [comment] 2017-01-09 16:19
Hey, could we please get this evaluated by the end of this week? Thanks!

**Comment by vobencha** [comment] 2017-01-09 16:44
Sorry for the delay. I think all of the SPB issues have been fixed and it would be best to get a clean build before approval.

@lshep can you please kick off a new SPB for this issue?

**Comment by lshep** [comment] 2017-01-09 16:54
Rerunning now, there should be a new build report posted shortly.

**Comment by vobencha** [comment] 2017-01-09 17:07
Thanks @lshep !

@siskac , the last warning to address is updating the R version,
* Checking R Version dependency...
    * WARNING: Update R version dependency from 3.3 to 3.4.

Once that's done we are good to go.
Valerie

**Comment by siskac** [comment] 2017-01-10 18:19
How soon will the R package be on the website? We have a paper that was just accepted on the extensions and would like to include the link to discordant on bioconductor. Thanks!

**Comment by vobencha** [comment] 2017-01-10 18:30
It will probably take a week to post on the web site. In the next few days you'll get an email with svn credentials and instructions.

The package will only be available in devel until the next release in April 2017 at which time it's available in both. For your publication you can use this link which will take you to the release page unless the package is only available in devel:
http://bioconductor.org/packages/discordant

Valerie

**Closed** 2017-01-12 16:40 UTC
Labels: 3a. accepted, OK
