### ISSUE TITLE
combi

### ISSUE THREAD

**Issue by sthawinke** [Bioconductor/Contributions#1377] opened 2020-02-19 09:28 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CenterForStatistics-UGent/combi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-02-19 10:45
Please update the Description: field of the DESCRIPTION file to clearly indicate what the package does, much like a paper abstract. 'Data integration' is too general.

**Comment by lshep** [comment] 2020-03-10 18:39
Thank you for your submission. Please see comments below: 

**Build Report**

- [ ] See NOTE about clarification of objects

**README**

- [ ] Include Bioconductor installation instructions

**DESCRIPTION**

- [ ] Please remove `LazyData: true` we have rarely found this useful and can actually slow package installation.

**NAMESPACE**

- [X] Okay

**INST**

- [ ] Rdata should be in `extdata` not `fits`. Please change the name of the directory
- [ ] There should be an inst/scripts/ directory that contains a file showing how the data in extdata/ was generated. This can be R code, sudo-code, or text indicating source of data and any preprocessing.

- [ ] Citation file is mal-formed. We need to be able to call `readCitationFile()` on the standalone CITATION file. 
```
> readCitationFile("CITATION")
Error in tools:::.parse_CITATION_file(file, meta$Encoding) : 
  non-ASCII input in a CITATION file without a declared encoding
```
- [ ] Only have one NEWS format. If both are present, you would need to update both when making changes/updates/fixes to the package. Only one is read for Bioconductor. Currently in the order of
```
inst/NEWS.Rd
inst/NEWS
inst/NEWS.md
NEWS.md
NEWS
```
NEWS.Rmd is currently ignored as it does not have the proper extension and it would be considered after inst/NEWS. inst/NEWS has been tested and is currently formated correctly. 

**TESTS**

- [X] Okay

**Data**

- [X] Okay
- [ ] For man pages you should probably show in the usage data(Zhang) along with the reference to the object
- [ ] Expand on the details of how the object was created from the source 
https://www.ibdmdb.org/. 


**Vignette**

- [ ] Optional: shorten to `combi.Rmd`. Its much more intuitive for a user to do `vignette("combi")`  than `vignette("combivignette")`
- [ ] Functions need to be evaluated either in the man pages or the vignette (probably preferably the vignette).
- [ ] If you took the time to create your own class, please also provide a show method or summary method so a user knows what is in the object. 


**R code / man page**

- [ ] Functions need to be evaluated either in the man pages or the vignette (probably preferably the vignette).  If they are not run here please use donttest instead of dontrun. donttest ensures valid R code
- [ ] Why do all the files start with `F_`. We would prefer the files remove this prefix.   

_addLink_

- [ ] Is the Views check suppose to be a stop, warning, or message? 
- [ ] In the man page links can be two columns but in the checks it seems 2 or 4? 
- [ ] Seems like the man page needs clarification on constraints


**Bigger issues**

- [ ] All of your main function calls in the vignette and man pages are in  `eval=FALSE` or `dontrun`. This is very problematic. We require that your functions are evaluated at least once in either the vignette or the man pages to show they can run without ERROR. Try using a smaller example set to minimize the time it takes to run.

- [ ] It seems like between zhangoMetabo and zhangMetavars, the function should be able to use the common Bioconductor structure SummarizedExperiment.To play into the Bioconductor ecosystem I would also check out the formats used by MSnbase which is the currently recommend way to read in MS data.

Thank you for your submission. Please address the above issues.  When ready please ensure a version bump to kick off a new build and comment back here that you are ready for a re-review and comment on what has been addressed.  

Cheers

**Comment by sthawinke** [comment] 2020-03-16 16:47
Thanks for your feedback. I think I can address these issues, although it will take some time as I am currently on a break. You will hear from me on a couple of months if that's ok.

**Comment by sthawinke** [comment] 2020-03-18 19:41
I addressed most of your comments, the code is now evaluated in the vignette. The new version has been pushed. Still, I had the following doubts:

- _See NOTE about clarification of objects_: This is because of the use of with/within, it just avoids the use of too many dollar signs
- _Seems like the man page needs clarification on constraints_: Could you clarify? For adding the link there are no real constraints. A paper is to appear with more details about the algorithm, e.g. the difference between unconstrained and constrained ordination.
- _It seems like between zhangoMetabo and zhangMetavars, the function should be able to use the common Bioconductor structure SummarizedExperiment.To play into the Bioconductor ecosystem I would also check out the formats used by MSnbase which is the currently recommend way to read in MS data._ I understand the concern from the BioConductor viewpoint. Yet the aim of the algorithm is to integrate many different datasets, contained in objects that may also contain metadata. Yet the metadata provided in e.g. a phyloseq and a SummarizedExperiment object may not be identical, and not all variables may need to be included in a constrained integration. Therefore we require the user to explicitly and separately provide the data frame with covariates. For the supply of views indeed any BioConductor class might be used.

**Comment by sthawinke** [comment] 2020-03-19 17:39
@Ishep what is the problem here? Why does it take so long to build the vignette on Windows? Also, I could not find the results for Mac

**Comment by lshep** [comment] 2020-03-19 17:53
We hope to have the mac builder back soon but it is temporarily unavailable:
https://stat.ethz.ch/pipermail/bioc-devel/2020-January/016057.html

I'm not sure what is causing the windows slow down; I will try to investigate this when re-reviewing your package.

**Comment by lshep** [comment] 2020-03-25 12:48
Got a little side track with the switch to work from home from the virus.  Here are a few last comments while I investigate the windows ERROR.  I will be investigating this today so hopefully will have some comment about it today or tomorrow.

**Comment by lshep** [comment] 2020-03-25 15:59
It does seem that running the combi function on windows is significantly slower.  I am trying to run it interactively and indeed I'm going on about 30 minutes without it completing.  I have yet to identify what in the function is causing the problem but you should look at addressing this as it does seem like a real issue.

**Comment by lshep** [comment] 2020-03-25 16:14
It seems like you are doing some paralyzation at some point.  The ERROR that ends up displaying and probably causing the problem is 
```
Error in serialize(data, node$con) : error writing to connection
```
I believe the solution is to limit the number of cores used (try 2 or 1) .  Or to check the type of parallelization specified as I believe there are limitations on which can be utilized on windows.

**Comment by sthawinke** [comment] 2020-03-26 08:06
Thanks for your feedback. Please find below the answers to your concerns:

- Constraints in exported functions: The documentation has been improved, and checks have been added for the arguments of all exported functions. 
- Also SummarizedExperiment datasets are now accepted. The metabolomics data (zhangMetabo) has been converted to a SummarizedExperiment object as an example. 
- NEWS.Rmd has been removed
- A print methods has been added for the combi class
- At most 2 views at once are used in the examples, but with bplapply the specification of the backend is left to the user, and should work on all platforms. I modified the package to use a serial backend by default. Yet the problem seemed to come from BiocParallel or the Windows server rather than the examples, which are really light and do work in Linux. Now there is another problem with the binary package builder in Windows which I do not understand, could you shed some light on this?

**Comment by sthawinke** [comment] 2020-03-26 13:00
I removed the BiocParallel functionality to make it work. It is acceptable for me this way, although it would be better with multithreading options. Yet from my side I cannot solve this problem.

**Comment by sthawinke** [comment] 2020-04-04 07:44
@lshep another problem has popped up that I did not experience before. I removed the R-version dependency but the problem remains. Can you give any hints how to solve this?

**Comment by lshep** [comment] 2020-04-06 11:40
You can ignore this warning.  We changed our check and realized it was too aggressive and have since reverted it. You should not see it on future builds.

**Comment by mtmorgan** [comment] 2020-04-06 22:10
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/sthawinke.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("combi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/combi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-06 22:10 UTC
Labels: 3a. accepted, WARNINGS
