### ISSUE TITLE
iNETgrate

### ISSUE THREAD

**Issue by habilzare** [Bioconductor/Contributions#2979] opened 2023-03-25 00:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/habilzare/iNETgrate

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2023-03-26 12:35
I am passing this for review but I think there are a couple of issues you might want to get a jump on.  I could not build the whole vignette, I am not sure why.  You should use R markdown instead of Sweave markup.  I saw 
```
Keeping only 71 entities in dnam because ratio is set to 1 . 
The correlation plots are saved at: 
 /home/stvjc/SUBMISSIONS/MAR22/iNETgrate/vignettes/iNETgrateRes/plots 
Combining filtered data...
unionGenes set size: 77 
Warning messages:
1: In filter.low.cor(Data = genExpr, survival = survival, whichData = "expression",  :
  Both minCor and ratio are passed as inputs!! Function will use both thresholds.
2: In stats::cor(t(Data[, common]), as.numeric(deathTime[common]),  :
  the standard deviation is zero
3: In stats::cor(t(Data[, names(sample2vital)]), sample2vital, method = "spearman",  :
  the standard deviation is zero
```
and those warnings will need to be repaired.  Please run R CMD check on your package and get it to zero errors and zero warnings.  Finally, why are plots being written to disk?  Thank you

**Comment by habilzare** [comment] 2023-03-27 00:27
Thanks vjcitn,
> You should use R markdown instead of Sweave markup.
Is this a Bioconductor requirement?

During the analysis, plots are written to disk for the user to look at after the analysis is done. There are too many plots to look at during the analysis.

**Comment by nilseling** [comment] 2023-03-31 19:21
Hi @habilzare,

Thanks for submitting the package. Could you please address the issues of the build report while I'll take a couple of days to review the package?

**Comment by habilzare** [comment] 2023-03-31 21:02
Hi Nils,
Thanks for accepting to review our package. I'll address the issues and give you updates.

**Comment by habilzare** [comment] 2023-03-31 22:41
Nils, 
I get the following error when I try to push changes to Bioconductor repository. Can you help with this?

`G1100154022:iNETgrate habil$  git push upstream devel`
FATAL: W any packages/iNETgrate h.zare DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I get the same error with:
`G1100154022:iNETgrate habil$  git push upstream main:devel`


I am using SSH as shown below:

`G1100154022:iNETgrate habil$ git remote -v`
origin	git@github.com:habilzare/iNETgrate.git (fetch)
origin	git@github.com:habilzare/iNETgrate.git (push)
upstream	git@git.bioconductor.org:packages/iNETgrate.git (fetch)
upstream	git@git.bioconductor.org:packages/iNETgrate.git (push)

**Comment by nilseling** [comment] 2023-04-03 06:53
Hi @lshep 
Could you potentially help with this? Thanks in advance!

**Comment by lshep** [comment] 2023-04-03 11:45
There was a mismatch on the username for access. Could you please try again.

**Comment by habilzare** [comment] 2023-04-03 13:29
My push worked fine, thanks Ishep!

**Comment by habilzare** [comment] 2023-04-04 22:40
Hi @lshep

I cannot reproduce the check error on my macOS. Maybe it is due to older or different versions of  TCGAbiolinks or dplyr on the Bioconductor servers. How can I figure out which versions of these packages are used during the check?

Also, I looked in CRAN but couldn't find  "R Under development (unstable) (2023-03-16 r83996)", which was used to check my package.

**Comment by lshep** [comment] 2023-04-05 12:23
The Bioconductor build system will always use whatever is available for download from Biocondcutor and CRAN repositories.  Please make sure you are using R 4.3 and Bioc 3.17 to test.  You can do a BiocManager::install / BiocManager::valid to make sure you have a valid installation and packages match what should be expected (and would be on the build system)

**Comment by nilseling** [comment] 2023-04-05 17:43
Hi @habilzare 

I was able to reproduce the errors on R 4.3 and Bioc 3.17, could you please test the package locally and address these issues. As Vince previously suggested, I would recommend to use R markdown to create the vignette. At the moment I'm still having issued building the vignette.

**Comment by habilzare** [comment] 2023-04-05 21:42
@nilseling and @lshep,

How can I install the dependency TCGAbiolinks package on Bioc 3.17? I have now R 4.3 (i.e., "R version 4.3.0 alpha (2023-04-04 r84161)"), and Bioc 3.17. I got the following warning when I tried to install TCGAbiolinks. I tried both devel and release.

`> BiocManager::install("TCGAbiolinks")`
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirrors.nics.utk.edu/cran
Bioconductor version 3.17 (BiocManager 1.30.20), R 4.3.0 alpha (2023-04-04
  r84161)
Installing package(s) 'TCGAbiolinks'
Warning message:
**package ‘TCGAbiolinks’ is not available for Bioconductor version '3.17'**

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by habilzare** [comment] 2023-04-05 21:47
The error should be reproduced using the following commands, which has nothing to do with my package. I can run this fine on Bioc 16, but not Bioc 17:

query <- TCGAbiolinks::GDCquery(project="TCGA-LAML", data.category="Clinical", file.type="xml")
TCGAbiolinks::GDCdownload(query, directory=".")
clinical <- TCGAbiolinks::GDCprepare_clinic(query,directory=".",clinical.info="patient")

**Comment by nilseling** [comment] 2023-04-06 14:35
Hi @habilzare 

I can't tell why `TCGAbiolinks` is not available on Bioc 3.17 or where the differences in functionality are coming from. You could reach out on the Bioc mailing list and ask for help.
For debugging you can install the development version from [Github](https://github.com/BioinformaticsFMRP/TCGAbiolinks) which seems to be the same version as the one on [Bioc devel](https://bioconductor.org/packages/devel/bioc/html/TCGAbiolinks.html).

**Comment by lshep** [comment] 2023-04-06 17:56
We updated R on the build system a few days ago and it looks like TCGAbiolinks has yet to build/check cleaning so likely the reason it might have not been available. I expect that will resolve in a day or two

**Comment by habilzare** [comment] 2023-04-07 22:48
It takes only 12 minutes on my Macbook to check. One difference is that I do not use --no-resave-data when I build the package. Could it be the reason of the significantly higher check time on Bioconductor (it does not give me this warning at the check time: * checking data for ASCII and uncompressed saves ... WARNING)?

**Comment by nilseling** [comment] 2023-04-11 07:54
Hi @habilzare 

I had the first pass through the package. Please have a look at my comments below and let me know how you address them.
The biggest issue at the moment is that I can't build the vignette. The package installs but I can't find the vignette in the package and can't build it due to `knit` and `LaTeX` issues. It would be a huge help if you could use `Rmarkdown` ([as recommended](https://contributions.bioconductor.org/docs.html#vignettes)) so that I better understand the functionality of the package.

## General package development

- [ ] I would not recommend to write files into the current working directory (`getwd()`) but (if needed) use a temporary directory (`tempdir()`). 
- [ ] Please address the following `BiocCheck` NOTEs and WARNINGs:

```
    * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
    * NOTE: Avoid the use of 'paste' in condition signals
    * WARNING: Remove browser() statements (found 2 times)
    * NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found 1 times)
    * NOTE: Usage of dontrun{} / donttest{} tags found in man page examples. 9% of man
      pages use at least one of these tags.
    * NOTE: Use donttest{} instead of dontrun{}.
```

## The DESCRIPTION file

- [ ] It won't be necessary to fix the package versions for `BiocStyle`, `GenomicRanges` and `Pigengene` as the latest versions will be used as dependencies. 
- [ ] Either remove R as dependency or set it to `4.3`.
- [ ] I believe you can move `BiocStyle` from `Depends` to `Suggests`.

## The NAMESPACE file

- [ ] Please avoid function names in the form of `function.name` as these indicate S3 generics and use `functionName` or `function_name` instead.
	  
## Package data

- [ ] Please check the example for `toyCleanedAml` - the variable `savePath` is not defined.

```
checking examples with --run-donttest ... [309s/306s] ERROR
  Running examples in ‘iNETgrate-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: toyCleanedAml
  > ### Title: A subset of cleaned TCGA-LAML data
  > ### Aliases: toyCleanedAml
  > ### Keywords: datasets
  > 
  > ### ** Examples
  > 
  > 
  > 
  > ## This dataset can be regenerated using the following commands,
  > ##which can take some time to run.
  > ## No test: 
  > dataProject <- "TCGA-LAML"
  > dataPath <- file.path(getwd(), "data", dataProject)
  > dir.create(savePath)
  Error: object 'savePath' not found
  Execution halted
```

## Documentation

- [ ] I was not able to access the vignette as `knit` gave me the following warning.

```
Writing to file iNETgrate_inference.tex
Processing code chunks with options ...
Error in match.arg(options$results, c("verbatim", "tex", "hide")) : 
  'arg' should be one of “verbatim”, “tex”, “hide”
Calls: <Anonymous> -> SweaveParseOptions -> check -> match.arg
Execution halted
```

Please consider using a `.Rmd` vignette instead so that I can understand the functionality of the package.

- [ ] Please add examples for `best.inetgrator`, `compute.inetgrator`, `infer.eigengenes`, 

## Unit tests

- [ ] It is highly recommended to add unit tests covering the main funtionality of the package.

**Comment by habilzare** [comment] 2023-04-11 16:29
Hi @nilseling ,
Thanks for reviewing my package and your comments. I'll let you know when I am done with addressing them. 

The vignette is built well on the Bioconductor server. It will take some time for me to learn R markdown and I am not sure the mathematical formulas will be shown as good as the current Sweave vignette. So, I prefer to continue using Sweave.

Are you using RStudio? It is buggy. You should be able to make the vignette using the following command:

`R CMD Sweave --pdf iNETgrate/vignettes/iNETgrate_inference.Rnw
`

[https://tex.stackexchange.com/a/125328](https://tex.stackexchange.com/a/125328)

**Comment by nilseling** [comment] 2023-04-13 09:45
Hi @habilzare 

thanks, that worked. Here are the last comments on the vignette:

- [ ] I would replace the devel installation with `BiocManager::install("habilzare/iNETgrate")`
- [ ] Can a warning such as:

```
## Warning in stats::cor(t(Data[, common]), as.numeric(deathTime[common]),
: the standard deviation is zero
```

be avoided by properly pre-processing the data?

- [ ] All code chunks in the vignette (except for the installation instructions) should be executed. I would recommend to exclude the `download.data` chunk. Please also make sure the `oneStep`, `inetgrator` and `pathway_analysis` chunks are executed.

Please also keep in mind that the package should be accepted until April 19th.

**Comment by nilseling** [comment] 2023-04-17 15:16
Hi @habilzare 

just a reminder that if the package should be released in the next round, it should be accepted on Wednesday. No rush with the revisions, the package can always be included in the next release.

**Comment by habilzare** [comment] 2023-04-18 23:13
Hi @nilseling ,
I am working hard for this package to be accepted by April 19. I addressed most of your comments in Version 0.99.50. I'll respond to your comments and explain what I did for each in a few hours. Thanks!

**Comment by habilzare** [comment] 2023-04-19 02:46
Hi @nilseling,

**Please see my responses to the comments you send me on April 11th below in bold.**
 
> ## General package development
> * [ ]  I would not recommend to write files into the current working directory (`getwd()`) but (if needed) use a temporary directory (`tempdir()`).

**Done.**

> * [ ]  Please address the following `BiocCheck` NOTEs and WARNINGs:
> 
> ```
>     * NOTE: Avoid 'cat' and 'print' outside of 'show' methods

 **I removed most of them. I believe the few that are left are legitimate e.g., at high levels of verbosity,  I use ‘print’ to give information about the output of the ‘table’ command to the user. It cannot be easily replaced with ‘message’**

>     * NOTE: Avoid the use of 'paste' in condition signals
**Done.**
>     * WARNING: Remove browser() statements (found 2 times)
**These two browsers will be turned only on the debug mode so that the developer can look into the situation. Please let me know if there is a better way to do this.**
>     * NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found 1 times)
**The AnnotationDbi::select() function prints a message per each query. There are thousands of queries in an iNETgrate run and these messages would make the standard output too busy. Unfortunately, there is no other way to silence this function.**
>     * NOTE: Usage of dontrun{} / donttest{} tags found in man page examples. 9% of man
>       pages use at least one of these tags.
**a) In toyRawAml.Rd and toyCleanedAml.Rd, I have code in the example section to document how these toy data can be reproduced. I used \donttest{} for this code because running them takes a long time and it is unnecessary to test this process in every check.   
b) I used \donttest{} in download.data.Rd because new TCGAbiolinks is buggy (2.24.3 < Version  <= 2.27.2). This function is not a major part of the iNETgrate pipeline and data can be provided in other ways.**
>     * NOTE: Use donttest{} instead of dontrun{}.
**Done.**

> ```
> ## The DESCRIPTION file
> * [ ]  It won't be necessary to fix the package versions for `BiocStyle`, `GenomicRanges` and `Pigengene` as the latest versions will be used as dependencies.
**Users may build and install iNETgrate in some other ways than Bioc. Lower versions of these packages would cause issues.**

> * [ ]  Either remove R as dependency or set it to `4.3`.
**Done**.

> * [ ]  I believe you can move `BiocStyle` from `Depends` to `Suggests`.
**With an old version of BiocStyle, building iNETgrate will be problematic and that is very difficult to debug. So, I prefer not to allow building without a proper version of BiocStyle.**

> ## The NAMESPACE file
> * [ ]  Please avoid function names in the form of `function.name` as these indicate S3 generics and use `functionName` or `function_name` instead.
**Changed to camelCase.**

> 
> ## Package data
> * [ ]  Please check the example for `toyCleanedAml` - the variable `savePath` is not defined.
> ```
> checking examples with --run-donttest ... [309s/306s] ERROR
>   Running examples in ‘iNETgrate-Ex.R’ failed
>   The error most likely occurred in:
>   
>   > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
>   > ### Name: toyCleanedAml
>   > ### Title: A subset of cleaned TCGA-LAML data
>   > ### Aliases: toyCleanedAml
>   > ### Keywords: datasets
>   > 
>   > ### ** Examples
>   > 
>   > 
>   > 
>   > ## This dataset can be regenerated using the following commands,
>   > ##which can take some time to run.
>   > ## No test: 
>   > dataProject <- "TCGA-LAML"
>   > dataPath <- file.path(getwd(), "data", dataProject)
>   > dir.create(savePath)
>   Error: object 'savePath' not found
>   Execution halted
> ```
> 
**Fixed.**

> ## Documentation
> 
> * [ ]  Please add examples for `best.inetgrator`, `compute.inetgrator`, `infer.eigengenes`,
> 
**As mentioned in the docs, examples are included in analyzeSurvival, . Running this example takes a long time and repeating them would result in timeout at check time.**

> ## Unit tests
> * [ ]  It is highly recommended to add unit tests covering the main funtionality of the package.
**All functions have examples, which can be used as tests.**

**Comment by nilseling** [comment] 2023-04-19 06:29
Hi @habilzare 

could you please update your Github repository so that I can have a look at the changes? For now, please make sure that all code chunks in the vignette are run and please remove the `browser()` statements in the code. For debugging you would use the `debug` function.

**Comment by habilzare** [comment] 2023-04-19 14:30
Hi @nilseling,
I pushed Version 0.99.52 to Bioc and GitHub. 

The last two examples in the vignette are run. The first one, iNETgrate(), is just a wrapper for the whole pipeline and running it would take 2 minutes. Therefore, I did not run it to save time. The example is the same in the docs, which is run at check time.

I'll update again later today to remove `browser()` and some other things.

**Comment by habilzare** [comment] 2023-04-19 17:09
Hi @nilseling ,
I think I responded all of your comments now. Please let me know if I missed anything that does not allow the acceptance of the package today. See some of my latest changes in bold below.

> * [ ] ...please remove the browser() statements in the code.

**Done.**

> * [ ]  I would replace the devel installation with `BiocManager::install("habilzare/iNETgrate")`

**Done.**

> * [ ]  Can a warning such as:
> 
> ```
> ## Warning in stats::cor(t(Data[, common]), as.numeric(deathTime[common]),
> : the standard deviation is zero
> ```
> 
> be avoided by properly pre-processing the data?

**This is actually the pre-processing code. I used `suppressWarnings()` on this line if you agree with me that these warnings are extra.**

> * [] Please also make sure the `oneStep`, `inetgrator` and `pathway_analysis` chunks are executed.

**I explained about the `oneStep` (`iNETgrator()`) above. Running `inetgrator` and `pathway_analysis` added 1 minute to the check time resulting in a warning. Do you think I should leave it as is, or skip running them?
.
Thanks for helping me improving the package. Hopefully, it will be accepted in this Bioconductor release.**

**Comment by nilseling** [comment] 2023-04-19 19:12
Hi @habilzare 

Unfortunately I won't be able to review the changes in the next hours (already being quite late in Europe) but I'll look at them in the next days.

**Comment by habilzare** [comment] 2023-05-01 21:03
Hi @nilseling ,
Do you have an update on the iNETgrate package? I have responded to all of your comments. Please let me know if I missed anything.

**Comment by nilseling** [comment] 2023-05-01 21:13
Hi @habilzare 
Really sorry for the delay, I will get back to it on Wednesday.

**Comment by nilseling** [comment] 2023-05-03 07:27
Hi @habilzare 

I went through the changes again and there are still three things that need to be addressed:

- [ ] In the vignette, please replace the `R CMD INSTALL iNETgrate_x.y.z.tar.gz` line with the devel installation `BiocManager::install("habilzare/iNETgrate")`. In general the package should be installed via `BiocManager::install("iNETgrate")`.
- [ ] I'm not quite sure if the warnings regarding the standard deviation should be suppressed. In the vignette there is another warning:

```
## Warning in stats::cor(balancedData, as.matrix(eigengenes[rownames(balancedData),
: the standard deviation is zero
```

Could this be avoided by filtering out features with sd == 0? If not, you could add instructions to the vignette if the user can ignore this but also the other warnings that occur during analysis.

- [ ] In general all chunks of the vignette except the installation instructions need to be executed. To reach this aim, you can remove the `downloadData` chunk and please evaluate the `oneStep` chunk.

**Comment by nilseling** [comment] 2023-05-16 12:12
Hi @habilzare 
are there any updates on this? Otherwise we can temporarily close the issue due to inactivity.

**Comment by habilzare** [comment] 2023-05-16 21:28
Hi @nilseling ,
I am almost done with addressing your comments. Please do not close the issue. I'll send an update soon.

**Comment by habilzare** [comment] 2023-05-17 05:13
Hi @nilseling,
I address all your comments below:


> * [ ]  In the vignette, please replace the `R CMD INSTALL iNETgrate_x.y.z.tar.gz` line with the devel installation `BiocManager::install("habilzare/iNETgrate")`. In general the package should be installed via `BiocManager::install("iNETgrate")`.

Updated to only `BiocManager::install("iNETgrate")`.

> * [ ]  I'm not quite sure if the warnings regarding the standard deviation should be suppressed. In the vignette there is another warning:
> 
> ```
> ## Warning in stats::cor(balancedData, as.matrix(eigengenes[rownames(balancedData),
> : the standard deviation is zero
> ```
> 
> Could this be avoided by filtering out features with sd == 0? If not, you could add instructions to the vignette if the user can ignore this but also the other warnings that occur during analysis.

I removed warnings as much as I could. The remaining warnings are beyond the scope of this package:

1- `read_block` is caused by loading loading `SummarizedExperiment` and `HDF5Array` packages.
2- `dopar` is caused by `WGCNA`.
3- `stats::cor(balancedData,..)` and `get.enriched.pw` are caused by `Pigengene` (hopefully,  will be addressed in the next release of `Pigengene`). 


> * [ ]  In general all chunks of the vignette except the installation instructions need to be executed. To reach this aim, you can remove the `downloadData` chunk and please evaluate the `oneStep` chunk.

Done.


Please let me know if you have any other suggestion.

**Comment by nilseling** [comment] 2023-05-17 12:34
Thanks @habilzare. Is there any way you could reduce the `R CMD check` time to less than 10 minutes?

**Comment by habilzare** [comment] 2023-05-18 03:53
> Thanks @habilzare. Is there any way you could reduce the `R CMD check` time to less than 10 minutes?

Yes, if you allow me to refer to the one step iNETgrate() documents instead of running it in the vignette like what I did in version 0.99.68. Is this OK?

**Comment by habilzare** [comment] 2023-05-19 18:41
Hi @nilseling ,
Is the current package acceptable?
Thanks!

**Comment by nilseling** [comment] 2023-05-19 19:57
It still gets a timeout when checking. Is there any way to reduce the check time?

**Comment by habilzare** [comment] 2023-05-24 00:56
@nilseling 

It is very difficult to make the toy data smaller because it may not lead to a reasonable network. With the new updated on the TCGAbiolonks package, I cannot even make the toy data again. I have asked the authors for help in this post:

https://support.bioconductor.org/p/9152425/#9152427

**Comment by habilzare** [comment] 2023-05-24 03:33
Hi @nilseling ,
I tried with a smaller toy data, which is 2/3 of the current data. A network cannot be made using this smaller toy data because there won't be enough genes to form clusters (modules). Is there any possibility the package be accepted as is?

**Comment by lshep** [comment] 2023-05-24 11:27
The R CMD check call didn't even start checking examples and tests; It timeouts after 16 min which is still pretty significant. Is it possible to use a different toy example set that is smaller and has enough genes?   Also please fix the data files suggestion for compression `R CMD build --resave-data`  and update your R version dependency.

**Comment by habilzare** [comment] 2023-05-24 13:11
Hi @lshep ,

> The R CMD check call didn't even start checking examples and tests; It timeouts after 16 min which is still pretty significant. 

The check on Bioc stops after `checking for missing documentation entries`. It takes only 5 minutes to reach this on my laptop and the whole check takes 12 minutes for me. I do not know why it takes so long on the Bioc server. Could the server be busy with multiple tasks?

> Also please fix the data files suggestion for compression `R CMD build --resave-data` 

The build command on the Bioc server uses the `--no-resave-data` option and I have control over it.

`BuildCommand: /home/biocbuild/bbs-3.18-bioc/R/bin/R CMD build --keep-empty-dirs --no-resave-data iNETgrate
`--

> and update your R version dependency.

@nilseling told me to remove dependency to R (see above).

**Comment by lshep** [comment] 2023-05-24 13:19
Re: the data save.  save the data either by using `tools::resaveRdaFiles()` or `save(something, file = "something.rda", compress = "xz")` .   We have now implemented the SPB to check on both linux and mac builders -- when you make the above change with appropriate version bump we can see if it is platform specific and/or gets better.

**Comment by habilzare** [comment] 2023-05-24 23:47
I used `save(compress = "xz", ....)` and the total data folder size decreased by 20% in Version 0.99.74. However, the check time increased from 12 minutes to 15 minutes on my laptop probably because it takes longer to load xz-compressed files.

**Comment by habilzare** [comment] 2023-05-25 02:59
The R version and file compression issues were resolved in Version 0.99.80.

**Comment by nilseling** [comment] 2023-06-05 07:33
Hi @habilzare 

is there any attempt to decrease the check time by using a smaller toy dataset?

**Comment by habilzare** [comment] 2023-06-06 16:03
Yes @nilseling , 
I tried, but with smaller data, a network cannot be made using the smaller toy data because there won't be enough genes to form clusters (modules) unfortunately.

**Comment by lshep** [comment] 2023-06-07 13:20
The core team has discussed and will allow the exception on the timeout.  Please understand that exceptions are not granted lightly and if you develop future packages they should meet the time requirements.

**Comment by lshep** [comment] 2023-06-07 13:20
@nilseling please add any other comments but ignore the timeout

**Comment by nilseling** [comment] 2023-06-07 13:40
With this we can then accept the package.

**Comment by habilzare** [comment] 2023-06-07 14:30
Thank you @nilseling and @nilseling for accepting our package! We appreciate the the core team's flexibility. 

When we started this package, I was careful to have a toy dataset to limit the check time below 4 minutes. However, as we added more functions and examples, the check time increased. Also, I did not expect the check time on the Bioc server to be significantly higher than our laptop. In future packages, I'll be more careful about the check time.

**Comment by habilzare** [comment] 2023-06-12 13:31
It is not on the Bioc 3.18 list yet. Does it take more for this to happen?

[https://www.bioconductor.org/checkResults/3.18/bioc-LATEST/](https://www.bioconductor.org/checkResults/3.18/bioc-LATEST/)

**Comment by lshep** [comment] 2023-06-13 10:48
I am away at a conference this week and will process al packages when I get back. Thank you for your patience

**Comment by lshep** [comment] 2023-06-20 14:39
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/habilzare.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("iNETgrate")`. The package 'landing page' will be created at

https://bioconductor.org/packages/iNETgrate

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-06-20 14:39 UTC
Labels: 3a. accepted, TIMEOUT, WARNINGS

**Comment by habilzare** [comment] 2023-06-20 15:01
Thanks @lshep for adding iNETgrate to the build list. I already have an 'ssh' key associated with my github username. 

Can I keep the package updated only on the Bioconductor repository and remove it from my github? I think updating and synchronizing two remotes is extra, unnecessary work.

**Comment by lshep** [comment] 2023-06-20 15:04
Yes if you like.  the location Bioconductor will use will always be the git.bioconductor.org location so if you only wish to maintain that location that is up to you.

**Comment by habilzare** [comment] 2023-06-20 19:19
Thanks @lshep for the confirmation! I'll remove the iNETgrate repository from my GitHub after I review nightly builds.

**Comment by jarcasariego** [comment] 2024-10-28 14:49
Hi @habilzare, I was attempting to install the package but it's not available in Bioconductor 3.20. Is there another way of installing it or could this issue in Bioconductor be solved?

**Comment by lshep** [comment] 2024-10-28 14:53
Its not this package's issue;  a dependency they rely on is failing and we flushed the repo in prep for release.  We have reached out to GEOquery (a requirement of minfi that this package requires) and hopefully should be resolved quickly

**Comment by jarcasariego** [comment] 2024-10-28 15:00
Great! Thanks @lshep for the fast reply

**Comment by lshep** [comment] 2024-10-28 15:06
In the meantime, while it is not recommended to mix package versions,  you can either download the source code for devel with `git clone https://git.bioconductor.org/packages/iNETgrate` and R cmd build/install locally  or you can download a release version pre built package from the [release landing page](https://bioconductor.org/packages/release/bioc/html/iNETgrate.html) and install locally
