### ISSUE TITLE
iCellR bioconductor

### ISSUE THREAD

**Issue by rezakj** [Bioconductor/Contributions#1112] opened 2019-05-03 21:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rezakj/iCellR

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2019-05-04 16:47
Your package MUST interoperate with Bioconductor, for instance accepting [SingleCellExperiment][1] and other [standard data representations][2] -- no point in being in Bioconductor otherwise!

[1]: https://bioconductor.org/packages/SingleCellExperiment
[2]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by dvantwisk** [comment] 2019-05-16 17:59
Hello,

Just checking in. Are you making progress on Martin's suggestion and fixing the warnings/errors ?

**Comment by rezakj** [comment] 2019-05-16 19:33
Hi, I have been very busy lately but I will check them out soon.

Reza
--
Alireza Khodadadi-Jamayran,
Senior Bioinformatics Programmer at
Applied Bioinformatics Laboratories (ABL) and
Genome Technology Center (GTC),
Division of Advanced Research Technologies (DART),
NYU Langone Medical Center
550 1st Ave, SB-604/MSB-304, New York, NY 10016
E-mail: alireza.khodadadi-jamayran@nyumc.org<mailto:alireza.khodadadi-jamayran@nyumc.org>
Phone: (212) 263-8132

**Comment by dvantwisk** [comment] 2019-05-29 17:23
Just checking in again since it's been about two weeks. We require that packages that are up for review are actively being worked on. We will need to see activity within the next two weeks of we will need to close the issue. If the issue is closed, it an be reopened at a later time when the developer is ready to work on it again.

**Comment by rezakj** [comment] 2019-05-29 17:28
Sorry about this, we decided to keep it on github for the time being.
Thank you so much,
Reza
--
Alireza Khodadadi-Jamayran,
Senior Bioinformatics Programmer at
Applied Bioinformatics Laboratories (ABL) and
Genome Technology Center (GTC),
Division of Advanced Research Technologies (DART),
NYU Langone Medical Center
550 1st Ave, SB-604/MSB-304, New York, NY 10016
E-mail: alireza.khodadadi-jamayran@nyumc.org<mailto:alireza.khodadadi-jamayran@nyumc.org>
Phone: (212) 263-8132

**Comment by dvantwisk** [comment] 2019-06-04 15:19
Just to clarify, you are saying that you currently do not want the package on Bioconductor? If so, is it okay to close this issue?

**Closed** 2019-06-06 11:34 UTC
Labels: 2. review in progress, ERROR, WARNINGS
