### ISSUE TITLE
ctgGEM

### ISSUE THREAD

**Issue by bicbioeng1** [Bioconductor/Contributions#1334] opened 2020-01-09 00:16 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bicbioeng/ctgGEM
Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-01-09 02:58
Please update your package to use the more modern [SummarizedExperiment][1] rather than ExpressionSet, or perhaps given the nature of your package [TreeSummarizedExperiment][2]

[1]: https://bioconductor.org/packages/SummarizedExperiment
[2]: https://bioconductor.org/packages/TreeSummarizedExperiment

**Comment by mtmorgan** [comment] 2020-01-23 14:00
Please let me know when you will provide an update to your package.

**Comment by bicbioeng1** [comment] 2020-01-27 06:23
Dear Mr. Morgan,

I apologize for the delay, some issues on our end prevented us from
resolving the package problems sooner. We should have our updates in early
this week.

If you don't mind me asking: is Bioconductor moving away from the use of
the ExpressionSet class? We're fine switching over to using
SummarizedExperiment classes, but the ExpressionSet has proven to be a very
useful data structure for handling our gene expression data, so out of
curiosity we would like to know why the former is preferred in this case.
Thank you, and have a great day!

**Comment by mtmorgan** [comment] 2020-01-27 15:34
Yes, SummarizedExperiment was introduced more than 4 years ago as a replacement for ExpressionSet.

**Comment by bicbioeng1** [comment] 2020-01-30 09:01
Mr. Morgan,

We should have the updated code in today, I'll let you know when it
happens.

Quick question: while we have changed our core structure to use the
SummarizedExperiment class, would it be reasonable to leave the
ExpressionSet implementation for our destiny-related methods? The destiny
package makes extensive use of the ExpressionSet class in their
documentation and their methods seem to favor ExpressionSet objects. Thanks!

**Comment by mtmorgan** [comment] 2020-01-31 14:05
yes supporting both SummarizedExperiment and ExpressionSet is appropriate.

**Comment by mtmorgan** [comment] 2020-02-05 22:23
is your package ready for review?

**Comment by bicbioeng1** [comment] 2020-02-07 07:42
My apologies, the package is technically ready but I can't seem to figure
out how to fix the warning generated during the build process. The issue is
in the html code for the vignette in the inst/doc subdirectory after the
package is built, and I can't seem to find anyone else reporting this
problem. At this point I should probably raise the question to the public
and see if anyone has any insight because I'm not sure where the warning is
coming from. I can't reproduce it locally...

**Comment by mtmorgan** [comment] 2020-02-07 14:47
The warning I see is
```
* Checking coding practice...
    * WARNING: Avoid class() == or class() != ; use is() or !is()
      Found in files:
        inst/doc/ctgGEM-Vignette.html (line 906)
```
which as you say is in an HTML file; this looks like a red herring to me. I'll review your package and look into the cause of this...

**Comment by mtmorgan** [comment] 2020-02-10 18:25
Please review the following comments, update your package, and post a comment with a brief summary of your response. The issue about the warning from HTML files seems like a false positive and BiocCheck will be updated.

DESCRIPTION

- please provide a more comprehensive Description: field, like a paper abstract, outling what specific analysis your package enables.

vignettes

- good

R (comments on specific lines of code may apply to other parts of the pacakge)

- ctgGEMset-class.R: 84 The convention is to name the 'constructor' after the class, so `ctgGEMset()` rather than `newctgGEMset()`.

- ctgGEMset-class.R:87 `stop()` prefixes "Error:" to the message, so no need to include "Error:" in the message

- ctgGEMset-methods.R: 81 break `stop()` messages into separate character vectors to avoid unusual indentation; compare
  ```
  > stop("foo
  +    bar")
  Error: foo
     bar
  > stop("foo ",
  +     "bar")
  Error: foo bar
  ```

- ctgGEMset-methods.R:106 No need to `paste()` separately from `stop()`; `stop()` calls an implicit `paste0()` on it's arguments

- ctgGEMset-methods:217 I don't think it's a good idea to implement `exprs()` / `pData()` etc on SummarizedExperiment or in general to provide a compatiblity layer between SummarizedExperiment and ExpressionSet -- ExpressionSet should be viewed as 'legacy' and supported for backward compatibility only. For instance, `colData()` of a SummarizedExperiment can contain data that are not well-represented as `data.frame()`, e.g., `DataFrame(x = GRanges())`. It should not be / is not necessary to use accessors when accessing these objects, e.g., `colData(object)@listData` should be simply `colData(object)`.

- generate_tree.R:46 functions should not write to the current working directory, but instead provide the option for user to provide a directory, defaulting to `tempfile()` or perhaps `tempdir()`. The command `dir.exists()` is more transparent than `file_test("-d", ...)`

- makeMonocle.R:74 use `format(Sys.time(), "%Y-%m-%d_...")` instead of this transformation; see `?format.POSIXct` for the format string.

- makeMonocle.R:174 use `message()` rather than `print()` to communicate messages to users.

man

- good

**Comment by bicbioeng1** [comment] 2020-02-12 04:35
Thank you, will get those updates in as soon as possible!

**Comment by bicbioeng1** [comment] 2020-02-27 07:30
Here is a list of the most recent updates:

- More comprehensive Description field and Introduction section in the
vignette
- Changed constructor name to ctgGEMset()
- Removed "Error" from stop messages and changed print() calls to message()
calls where appropriate
- Removed Biobase function extensions from 'ctgGEMset-methods" file
- Functions now default to temporary directory, otherwise taking the
directory provided by the user to store output in
- Switched to format(Sys.time()...) for filenames in all functions

**Comment by mtmorgan** [comment] 2020-03-08 19:49
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bicbioeng1.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ctgGEM")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ctgGEM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-03-08 19:49 UTC
Labels: 3a. accepted, OK
