### ISSUE TITLE
easyreporting

### ISSUE THREAD

**Issue by drighelli** [Bioconductor/Contributions#1299] opened 2019-10-31 11:14 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/drighelli/easyreporting

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by drighelli** [comment] 2019-11-18 10:45
Hi, 

Is there anything else to do?

**Comment by Kayla-Morrell** [comment] 2019-11-19 17:58
Hello @drighelli - Sorry for my late reply. I have a couple notes about your package before I can start the official review. 

The first major point is that we prefer the use of S4 classes. You can see a previous discussion about this matter on our mailing list [here](https://stat.ethz.ch/pipermail/bioc-devel/2017-May/011013.html). In summary, using R6 class requires the user to know/utilize yet another syntax and semantics. If you would like to use R6 within your package that is fine but we discourage exposing/exporting it to the user. 

The second is that you currently use a biocView term 'ReproducibleResearch' which tags the package as an ExperimentData package instead of a Software package. Generally ExperimentData  packages accompany Software packages for use in the examples and vignettes. I would suggest picking a different biocView term for your package, perhaps 'ReportWriting'. The categories can be viewed under Software [here](https://bioconductor.org/packages/release/BiocViews.html).

Please let me know if you have any questions or need any clarification for the points above.

Best,
Kayla

**Comment by drighelli** [comment] 2019-11-20 11:23
Hi @Kayla-Morrell - Thanks for replying!

1. I understand, what do you suggest about this? Do I have to entirely reshape the class in S4 or is there a way to just reshape the vignettes? (when you talk about "exporting it to the user" is it referred to the vignettes?)
1.1 May I leave the actual vignettes as they are (to provide examples about R6 usage) and simultaneously write a new vignette by using the class in "S4 format usage style"?

2. ok, I understand... There is no problem at all for me in changing the biocView in "ReportWriting"!!
But maybe the ReproducibleResearch term should be thought in a more general way including also software and not just data. Just because it is a more general aspect of the research, which includes both aspects, there is "no ReproducibleResearch if there is no code using that data".

Thanks for your points!
Looking forward to your reply :)
Dario

**Comment by Kayla-Morrell** [comment] 2019-11-22 16:50
Hello @drighelli,

1. We suggest reshaping the class into S4. When I talk about exporting it to the user, I mean all the functions that are declared as `export()` in your NAMESPACE file. The use of these functions are demonstrated in the examples of the man pages as well as in the vignettes. I would advise against having 2 vignettes.

2. Thank you for the suggestion, something for us to think about for the future. Just be sure you change the package so the terms only come from the software hierarchy and you'll be all set :)

Let me know if you need more clarification or have any follow up questions.
Best,
Kayla

**Comment by drighelli** [comment] 2019-11-26 14:10
Hi @Kayla-Morrell,

thanks for your reply and suggestions.

I think that I'm going to reshape the package as an S4 Class, if this can be useful for the Bioconductor project.

Thanks,
Dario

**Comment by drighelli** [comment] 2019-11-28 19:45
hi @Kayla-Morrell,

I just re-shaped the class as S4, please let me know if there is something else to do.

Thanks,
dario

**Comment by drighelli** [comment] 2019-12-02 10:43
Hi @Kayla-Morrell,

sorry for these two last versions bumping, I found some missing suggestions in the DESCRIPTION file.

Looking forward to your revision.

Dario

**Comment by drighelli** [comment] 2019-12-11 20:02
Hi @Kayla-Morrell,

any updates?

dario

**Comment by Kayla-Morrell** [comment] 2019-12-12 16:52
Hello @drighelli - I am currently working on the review and should have it posted by tomorrow.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2019-12-13 16:13
@drighelli - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

-[ ] REQUIRED: The 'inst/' directory needs some work. What is the purpose of the 
'code_example/' and 'example/' directories? The data needs to be in a different 
directory, more on that in the 'data' section below.

## DESCRIPTION

- [ ] REQUIRED: Use either the 'Author@R' field OR the 'Author/Maintainer' 
field, but not both. We prefer the 'Author@R' field.

- [ ] REQUIRED: 'LazyData' should be set to 'false'. When this field is true it 
can slow down the loading of packages, especially those that contain data.

- [ ] SUGGESTION: The packages you have listed in 'Depends:' might be a better 
fit if they were listed as 'Imports:'. It seems these packages provide fuctions 
that are used inside the package name space, which is the idea of imported 
packages. Depends are more for packages that provide functionality for users of 
the package, which might be a bit expreme for these packages listed.

- [ ] SUGGESTION: It is encouraged to include 'BugReports:' field with a 
relevant link to Github Issues.

## NEWS

- [ ] REQUIRED: Thank you for including a NEWS file, however it isn't correctly 
formatted. I would suggest moving the NEWS file to the top directory, but 
regardless of where it is located please look at the following link for help 
with the format, https://bioconductor.org/developers/package-guidelines/#news.

## Data

- [ ] REQUIRED: The data for this package should be located in either an 
'inst/extdata' directory or a 'data/' directory, depending on the purpose of the 
data. Please see our write up about including data for further help with this, 
https://bioconductor.org/developers/package-guidelines/#data. Also be sure that 
there is documentation somewhere for this data. 

## Vignette

*bio_usage*

- [ ] REQUIRED: There should be an 'Installation' section before 'Requirements' 
that demonstrates to the user how to download the package from Bioconductor. The 
code should look something like this:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("easyreporting")
```

- [ ] REQUIRED: Line 66, the link for the data is not correct. In the markdown 
code, the phrase for the link should be in the square brackets [ ] , and the 
link should be in the parentheses ( ).

- [ ] REQUIRED: Line 127, compiling should be capitalized (Compiling).

- [ ] REQUIRED: When running line 131, it quits compiling from lines 35-42 with 
the error message:

```
Error in fitFDistRobustly(var, df1 = df, covariate = covariate, winsor.tail.p = winsor.tail.p) :
  statmod package required but is not installed
```

Once I installed this package it worked fine, this should be listed in the 
DESCRIPTION file somewhere (most likely under Suggests).

- [ ] REQUIRED: The final section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

*standard_usage*

- [ ] REQUIRED: There should be some sort of an 'Introduction' section that 
serves as an abstract to introduce the objective, models, unique functions, key 
points, etc. of the package. 

- [ ] REQUIRED: There should be an 'Installation' section before 'Requirements' 
that demonstrates to the user how to download the package from Bioconductor. The 
code should look something like this:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("easyreporting")
```

- [ ] REQUIRED: This chunk of code should not be `eval = FALSE`, this undermines 
the benefit of vignettes having executable code.

- [ ] REQUIRED: The final section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

## Man pages

*compile*

- [ ] REQUIRED: There should be more information for 'Description:'.

- [ ] REQUIRED: The argument 'object:' should be an 'easyreporting class object' 
not just 'a general object'.

*easyreporting*

- [ ] REQUIRED: Under 'Usage:' the 2 lines of code look identical, remove 1 of 
them.

- [ ] REQUIRED: For 'Value:' the 2 lines seem to be saying the same thing. Have 
just 1 line.

*getOptionsList*

- [ ] REQUIRED: There should be more information for 'Description:'.

- [ ] REQUIRED: The argument 'object:' should be an 'easyreporting class object' 
not just 'a general object'.

*getReportFilename*

- [ ] REQUIRED: There should be more information for 'Description:'.

- [ ] REQUIRED: The argument 'object:' should be an 'easyreporting class object' 
not just 'a general object'.

*mkdCodeChunkEnd*

- [ ] REQUIRED: If you use this function in the vignettes and you want the users 
to use it then it should be exported.

- [ ] REQUIRED: If it is being exported then you should add runnable exampels to 
the man page.

*mkdCodeChunkSt*

- [ ] REQUIRED: IF you use this function in the vignettes and you want the users 
to use it then it should be exported.

- [ ] REQUIRED: If it is being exported then you should add runnable examples to 
the man page.

*mkdGeneralMsg*

- [ ] REQUIRED: There should be more information for 'Description:'.

*mkdTitle*

- [ ] REQUIRED: There should be more information for 'Description:'.

*setOptionsList*

- [ ] REQUIRED: There should be more information for 'Description:'.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests, they are strongly encouraged. See 
this link for more information, https://bioconductor.org/developers/package-guidelines/#unittest.

## R code

- [ ] REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. This
is found in 'easyreportingM.R', line 416.

- [ ] REQUIRED: Avoid use of direct slot access with `@` or `slot()`, seen in 
'easyreportingM.R'. Accessor methods should be created and utilized instead.

- [ ] SUGGESTION: For formating purposes, consider shorter lines. There are 7 
lines that are >80 characters long.

- [ ] SUGGESTION: For formating purposes, consider multiples of 4 spaces for 
line indents. There are 102 lines that are not.

Best,
Kayla

**Comment by drighelli** [comment] 2019-12-15 16:44
I'm gonna write my answers only for those aspects I didn't implement.
All the other reviews have been already done.
For tomorrow I'll bump a new version with the revised changes.

General package development
-[ ] REQUIRED: The 'inst/' directory needs some work. What is the purpose of the
'code_example/' and 'example/' directories? The data needs to be in a different
directory, more on that in the 'data' section below.

The example directory contains an execution example, while the code_example directory contains some code used in the vignettes.x

NEWS
 REQUIRED: Thank you for including a NEWS file, however, it isn't correctly
formatted. I would suggest moving the NEWS file to the top directory, but
regardless of where it is located please look at the following link for help
with the format, https://bioconductor.org/developers/package-guidelines/#news.

Your link plays: "A NEWS file should be included to keep track of changes to the code from one version to the next. It can be a top-level file or in the inst/ directory.", I always used to put files to be installed in the INST directory, I find it cleaner, btw thanks for pointing up that I can move it also on the top dir.
For the format: I just changed it! 

 REQUIRED: When running line 131, it quits compiling from lines 35-42 with
the error message:

Error in fitFDistRobustly(var, df1 = df, covariate = covariate, winsor.tail.p = winsor.tail.p) :
  statmod package required but is not installed
Once I installed this package it worked fine, this should be listed in the
DESCRIPTION file somewhere (most likely under Suggests).

That's pretty weird, I don't use that function. I think it's a dependence of limma or edgeR, that are already included in the suggestions.

Unit tests
 SUGGESTION: Consider adding unit tests, they are strongly encouraged. See
this link for more information, https://bioconductor.org/developers/package-guidelines/#unittest.

You're right, but at the moment writing unit tests for all the parts of the code it's a little bit time demanding, I'm gonna slowly account that in the future.

 REQUIRED: Avoid use of direct slot access with @ or slot(), seen in
'easyreportingM.R'. Accessor methods should be created and utilized instead.

That's an internal function. Is it so fundamental to do that even in an internal function?

thanks,
dario

**Comment by drighelli** [comment] 2019-12-18 16:52
Hi @Kayla-Morrell,

Finally, I made it, passing all the checks! ^^'

Respect to my previous comments I also fixed the "Error in fitFDistRobustly" problem.

Dario

**Comment by Kayla-Morrell** [comment] 2020-01-02 17:00
Hello @drighelli,

My apologies for the late response, I was away for the holidays. Thank you for making the necessary changes. I have just a few more points that need to be addressed and then I can accept the package. Please see these points below and let me know when you are ready for me to look things over again.

## General package development

- [ ] SUGGESTION: Thank you for explaining what the purpose of the files are in
`inst/code_example/` and `inst/example/`. I would highly suggest putting all
these scripts into an `inst/script/` directory to help simplify.

## Vignettes

*bio_usage*

- [ ] REQUIRED: Thank you for including the code for downloading the package
from _Bioconductor_. However, lines 38-40 should be included in a code chunk
that uses `eval = FALSE` (i.e. \{r, eval = FALSE\}). Then line 42 should be in
a code chunk that gets evaluated. This will help eliminate the warning shown
in the vignette.

*standard_usage*

- [ ] REQUIRED: The same comment as with *bioc_usage*, the lines 38-40 should
be included in a chunk that is `eval = FALSE`, and then line 42 should be in
a code chunk that gets evaluated.

## man pages

*easyreporting*

- [ ] REQUIRED: For 'Description', 'Usage', 'Value', and 'Examples' there are 2
lines for each that are identical to each other. Please change it so that there
is 1 line for each.

Best,
Kayla

**Comment by drighelli** [comment] 2020-01-05 14:23
HI @Kayla-Morrell ,

I just made all the revisions, exception made for the examples scripts because the final aim of the folder is different.

Now everything should be ok.

dario

**Comment by Kayla-Morrell** [comment] 2020-01-07 13:41
@drighelli - Thank you for making those changes. I have looked everything over and I am more than happy to accept the package.

Best,
Kayla

**Comment by drighelli** [comment] 2020-01-10 09:51
@Kayla-Morrell thanks! :)

Best,
Dario

**Comment by drighelli** [comment] 2020-01-13 13:40
Hi @Kayla-Morrell,

sorry for asking, how it works now? :)

dario

**Comment by Kayla-Morrell** [comment] 2020-01-13 18:56
Hello @drighelli - There will be some additional instructions/details posted here once your package gets added to our Bioconductor git repository. Until then there is nothing else you need to do.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2020-01-14 14:12
Hello @drighelli - I was advised that there is an additional change that needs to be made to your package in order for it to be accepted. In the vignettes you are writing to the home directory, so then there are arbitrary files that are found on our build system every time your package is built. To avoid contaminating our home directory on the builders we suggest that you have these files written to a temporary directory. For example, in `bio_usage.rmd` at line 63 you have:

```
proj.path <- file.path("~", "bioinfo_report")
bioEr <- easyreporting(filenamePath=proj.path, title="bioinfo_report",
                        author=c("Dario Righelli"))
```

we would suggest you change this to:

```
proj.path <- tempdir()
bioEr <- easyreporting(filenamePath=proj.path, title="bioinfo_report",
                        author=c("Dario Righelli"))
```

Please make this change where ever you may write files. Thank you.

**Comment by drighelli** [comment] 2020-01-14 14:19
hi @Kayla-Morrell,

sorry for the inconvenience and thanks for the suggestion.
Indeed, I didn't know where to save these files.

Just changed!

Dario

**Comment by drighelli** [comment] 2020-01-14 14:28
dear @Kayla-Morrell,

unfortunately, the changes you suggested seem to not work properly for your bot.

Any other suggestion?

Thanks,
Dario

**Comment by Kayla-Morrell** [comment] 2020-01-14 14:38
@drighelli - It seems that is somewhere in your code since it is erroring out at the function call `easyreporting()`. Be sure that the user is able to set any arbitrary directory to save these files. I found one instance of `getwd()` in `easyreportingM.R` (line 45) that may contribute to this.

**Comment by drighelli** [comment] 2020-01-14 17:09
@Kayla-Morrell now everything should be ok.
dario

**Comment by Kayla-Morrell** [comment] 2020-01-14 17:11
@drighelli - Perfect, I'll go ahead and accept the package again. Thanks for making those changes.

**Comment by mtmorgan** [comment] 2020-01-15 10:11
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/drighelli.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("easyreporting")`. The package 'landing page' will be created at

https://bioconductor.org/packages/easyreporting

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-01-15 10:11 UTC
Labels: 3a. accepted, OK
