### ISSUE TITLE
chimeraviz

### ISSUE THREAD

**Issue by stianlagstad** [Bioconductor/Contributions#206] opened 2016-11-25 21:36 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stianlagstad/chimeraviz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by stianlagstad** [comment] 2016-11-27 09:32
Hi,

Is there a problem with BiocCheck? I'm registered at both the bioc-devel mailing list and the support site. (https://support.bioconductor.org/u/9723/). I'm using the same email address as in the DESCRIPTION file here.

**Comment by vobencha** [comment] 2016-11-27 15:04
Hi,
I'll have to look into the 'not registered' mailing list issue. In the mean time please address these points in the single package builder output:

* checking for missing documentation entries ... WARNING
Undocumented code objects:
  'addFusionReadsAlignment' 'createFusionReport'
  'decideTranscriptCategory' 'fetchReadsFromFastq' 'fusionToDataFrame'
  'getEnsemblIds' 'getFusionByChromosome' 'getFusionByGeneName'
  'getFusionById' 'getTranscriptsEnsembldb' 'importDefuse'
  'importEricscript' 'importFusioncatcher' 'importFusionmap'
  'importInfusion' 'importJaffa' 'importPrada' 'importSoapfuse'
  'importStarfusion' 'plotCircle' 'plotFusion' 'plotFusionReads'
  'plotFusionSeparate' 'plotFusionTogether' 'plotFusionTranscript'
  'plotFusionTranscriptsGraph' 'plotTranscripts' 'selectTranscript'
  'splitOnUtrAndAddFeature' 'writeFusionReference'
Undocumented S4 classes:
  'PartnerGene' 'Fusion'
All user-level objects in a package (including S4 classes and methods)
should have documentation entries.
See chapter Writing R documentation files in the Writing R
Extensions manual.

Adding more views is up to you but the more you have the easier it is for others to find your package:
* Checking for recommended biocViews...
    * NOTE: Consider adding these automatically suggested biocViews:
      Sequencing, Microarray, Coverage, Alignment, SequenceMatching,
      DataImport

* Checking for direct slot access...
    Found @ in vignettes/chimeraviz-vignette.Rmd
    * NOTE: Use accessors; don't access S4 class slots via '@' in
      examples/vignettes.

Once those are cleaned up I'll do a full review.
Valerie

**Comment by stianlagstad** [comment] 2016-11-27 16:15
Are roxygen2 generated documentation not accepted? I believe everything in the package has been documented with roxygen2.

I can fix the note about using accessors, but for the sake of my curiosity: Why are they not allowed in vignettes?

**Comment by vobencha** [comment] 2016-11-29 15:23
When I run R CMD build locally (which I assume you've done?) I see these problems:
* installing *source* package ‘chimeraviz’ ...
Warning in .write_description(db, file.path(outDir, "DESCRIPTION")) :
  Unknown encoding with non-ASCII data: converting to ASCII

You need to add Encoding: UTF-8 to the DESCRIPTION file.

We also see this:
** help
No man pages found in package  'chimeraviz'

When I load the package and look for help I get nothing:
> ?getFusionById
No documentation for 'getFusionById' in specified packages and libraries:
you could try '??getFusionById'

The problem is not with roxygen2 but your package structure. You  need a man/ directory and a few other things. Here is a primer:
http://kbroman.org/pkg_primer/pages/docs.html

You could use the source of roxygen2 as an example of how to make a package with roxygen2:
https://cran.r-project.org/web/packages/roxygen2/index.html
https://github.com/klutometis/roxygen

Valerie

**Comment by vobencha** [comment] 2016-11-29 15:31
The use of '@' is discouraged in all code not just vignettes. In general '@' is used in the getter/setter functions only and in the rest of the code the accessors are used. The rational is that direct slot access can corrupt / invalidate an object with no complaints from R. A getter/setter function can check for correct data type, length etc. and throw an error if the wrong thing is put in the slot on purpose or by mistake.

**Comment by stianlagstad** [comment] 2016-11-30 22:41
Thank you for the pointers, @vobencha. Could you advice on my recent error? I'm unable to reproduce it on my end.

**Comment by vobencha** [comment] 2016-12-07 15:47
Hi Stian,
Sorry I didn't see this message until you posted on the support site. Looks like Leo answered it. I've checked your package locally and on malbec2 (linux builder) and all looks good. I'll take another quick look at the package and get back to you today with final comments. 
Valerie

**Comment by vobencha** [comment] 2016-12-07 15:58
Thanks for making the changes. One last change for the vignette -

There are many calls to system.file() in your vignette. Several load the same file and assign it to different variable names. You only need to load a file once in the vignette and then just reuse it -no need to load separately for each example. Please reduce the system.file() calls, bump the version and we should get a clean SPB build.

Thanks.
Valerie

**Comment by stianlagstad** [comment] 2016-12-07 16:01
Thank you, I will fix that. I only did it so that each example would be runnable on its own.

**Comment by stianlagstad** [comment] 2016-12-07 20:24
Could you advice on what I should do with the `there is no package called 'webshot'` error?

**Comment by vobencha** [comment] 2016-12-07 20:50
Not sure, I'll have to look into it.

**Comment by vobencha** [comment] 2016-12-08 22:01
I'm going to approve this. I'm not sure what's going on with the mac builder. Please keep an eye on the  package once it's added to the build report 

  http://www.bioconductor.org/checkResults/devel/bioc-LATEST/

If you see errors on mac post back to the mailing list as you have been doing. Thanks for making the changes and for the effort you put into the package.
Valerie

**Comment by stianlagstad** [comment] 2016-12-09 11:57
I added the webshot package in an attempt to remedy the error, but I should not need it. Can I remove it from Suggests now?

**Comment by vobencha** [comment] 2016-12-09 13:26
Yes, please do. Also bump the version again.

**Comment by stianlagstad** [comment] 2016-12-12 19:44
Is there anything else I have to do for the package to be added to the devel branch? :)

**Comment by vobencha** [comment] 2016-12-12 20:06
No, the rest is done on our side. In the next week you should get an email with svn credentials and instructions for next steps.

**Comment by stianlagstad** [comment] 2016-12-12 20:16
Thank you again!

**Closed** 2016-12-12 22:17 UTC
Labels: 3a. accepted, ERROR
