### ISSUE TITLE
PhenoGeneRanker

### ISSUE THREAD

**Issue by JakeP627** [Bioconductor/Contributions#1576] opened 2020-07-30 16:10 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bozdaglab/PhenoGeneRanker

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment] 2020-09-15 09:14
Hi @JakeP627,

Thanks for your submission. Note that there are no examples that I can run in the man pages or in the vignette so I can't review the package. This is software so it's important that for the review process we can try your functions and make sure that they work as advertised. Without running examples, we can't do that. Please provide runnable examples. Note that this is a requirement per our guidelines. Thanks!

Best,
H.

**Comment by hpages** [comment] 2020-10-06 16:05
Hi @JakeP627, are you planning to follow up with this submission? Thanks

**Comment by lshep** [comment] 2020-11-17 14:20
Is there an update on this package?  We like to see responses and updates in a 3-4 weeks; This issue has seen no updates since September.  If you need more time to work on the issue we can temporarily close until you are ready to continue with the review.

**Comment by serdarbozdag** [comment] 2020-11-17 15:16
Thanks for reaching out. We have our update almost ready. We will submit the updated version this week.

Serdar

On Nov 17, 2020, at 8:20 AM, lshep <notifications@github.com> wrote:

﻿

Is there an update on this package? We like to see responses and updates in a 3-4 weeks; This issue has seen no updates since September. If you need more time to work on the issue we can temporarily close until you are ready to continue with the review.

**Comment by serdarbozdag** [comment] 2020-11-20 04:20
> Is there an update on this package? We like to see responses and updates in a 3-4 weeks; This issue has seen no updates since September. If you need more time to work on the issue we can temporarily close until you are ready to continue with the review.

Hello, we would like to submit a new version, but the initial maintainer is no longer in the project so we need to change the maintainer. I just sent an email to bioc-devel@r-project.org <bioc-devel@r-project.org> to request to associate @cdursun as the maintainer. Is there anything you could help with this? 
thanks

**Comment by lshep** [comment] 2020-11-20 15:14
@serdarbozdag  @cdursun has been updated in our system as maintainer.  Please make sure to make the appropriate change in the DESCRIPTION of the package as well when you push changes.   @cdursun you will have to activate your Bioconductor Git Credentials account using your email cagataydursun@gmail.com .  I will be sending your temporary password to that email momentarily.

**Comment by lshep** [comment] 2020-11-20 15:17
The Git Credentials account can be found here:  https://git.bioconductor.org/BiocCredentials

**Comment by serdarbozdag** [comment] 2020-11-20 17:32
Great, thanks.

**Comment by hpages** [comment] 2020-12-11 05:29
Hi @serdarbozdag, is the package ready for review? Thanks.  H.

**Comment by serdarbozdag** [comment] 2020-12-11 06:00
Yes, the latest submission we had a couple of weeks ago is ready for your review. Let me know if you need us to submit it again.

Thanks
Serdar

On Dec 10, 2020, at 11:29 PM, Hervé Pagès <notifications@github.com> wrote:

﻿

Hi @serdarbozdag<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_serdarbozdag&d=DwMCaQ&c=S1d2Gs1Y1NQV8Lx35_Qi5FnTH2uYWyh_OhOS94IqYCo&r=hA-XTKcE0pHLi8qKA6Dq1o8P8ckUkKd0p5cTStqyOwY&m=G7gKc7w9562OwjNlbOVKJIYkj8F21sadPvJdjBBJlUM&s=iKfstkt1V_FgKRPf-PtGr4GNas1PbY3Qy7y6vvLsxZs&e=>, is the package ready for review? Thanks. H.

**Comment by hpages** [comment] 2021-01-15 18:23
Hi @serdarbozdag ,

I'll take a look at the package ASAP. Sorry for the delay.

H.

**Comment by serdarbozdag** [comment] 2021-01-18 01:20
Thanks. We are looking forward to hearing your comments. We will be submitting the revised version of our paper very soon. If the bioconductor package is approved, we would be able to put the link to the manuscript. 

Best,

Serdar

**Comment by hpages** [comment] 2021-01-26 09:37
Hi @serdarbozdag ,

I get 1 ERROR and 1 WARNING when I run `R CMD check` on the package:
```
hpages@spectre:~$ R CMD check PhenoGeneRanker_0.99.6.tar.gz 
* using log directory ‘/home/hpages/pkgreviews/PhenoGeneRanker.review/PhenoGeneRanker.Rcheck’
* using R Under development (unstable) (2020-11-18 r79449)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘PhenoGeneRanker/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘PhenoGeneRanker’ version ‘0.99.6’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘PhenoGeneRanker’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... WARNING
Warning: parse error in file 'lines':
40: unexpected ','
43: ranksWithPval <- RandomWalkRestart(CreateWalkMatrix('myFile.txt'),c('gene1'), 
44:        c(), TRUE, 12, 0.7, 0.6, tau =(1,
                                           ^
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... ERROR
Running examples in ‘PhenoGeneRanker-Ex.R’ failed
The error most likely occurred in:

> ### Name: CreateWalkMatrix
> ### Title: Create Walk Matrix
> ### Aliases: CreateWalkMatrix
> 
> ### ** Examples
> 
> CreateWalkMatrix('myInput.txt')
Warning in file(file, "rt") :
  cannot open file 'myInput.txt': No such file or directory
Error in file(file, "rt") : cannot open the connection
Calls: CreateWalkMatrix -> ReadSettings -> read.table -> file
Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘PhenoGeneRanker.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR, 1 WARNING
See
  ‘/home/hpages/pkgreviews/PhenoGeneRanker.review/PhenoGeneRanker.Rcheck/00check.log’
for details.
```
I'm on Ubuntu 20.10 (see my `sessionInfo()` below).

Hopefully you can reproduce and address. Make sure you are using R 4.1 + BioC 3.13, and that all your packages are up-to-date (you can check this with `BiocManager::valid()`).

Thanks,
H.

**sessionInfo():**
```
> library(BiocManager)
Bioconductor version 3.13 (BiocManager 1.30.10), ?BiocManager::install for help
> BiocManager::valid()
[1] TRUE
> library(PhenoGeneRanker)
> sessionInfo()
R Under development (unstable) (2020-11-18 r79449)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Matrix products: default
BLAS:   /home/hpages/R/R-4.1.r79449/lib/libRblas.so
LAPACK: /home/hpages/R/R-4.1.r79449/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocManager_1.30.10    PhenoGeneRanker_0.99.6

loaded via a namespace (and not attached):
 [1] igraph_1.2.6      magrittr_2.0.1    tidyselect_1.1.0  doParallel_1.0.16
 [5] lattice_0.20-41   R6_2.5.0          rlang_0.4.10      foreach_1.5.1    
 [9] dplyr_1.0.3       tools_4.1.0       parallel_4.1.0    grid_4.1.0       
[13] DBI_1.1.1         iterators_1.0.13  ellipsis_0.3.1    assertthat_0.2.1 
[17] tibble_3.0.5      lifecycle_0.2.0   crayon_1.3.4      Matrix_1.3-2     
[21] purrr_0.3.4       vctrs_0.3.6       codetools_0.2-18  glue_1.4.2       
[25] compiler_4.1.0    pillar_1.4.7      generics_0.1.0    pkgconfig_2.0.3  
```

**Comment by cdursun** [comment] 2021-02-01 23:24
Hi @hpages,
I am the author and maintainer for the package. When you address only @serdarbozdag I don't get any email. We have just seen your comment, I will check the problem soon.
Thanks,
Cagatay

**Comment by cdursun** [comment] 2021-02-09 23:00
Hi @hpages,
The version for PhenoGeneRanker should be 0.99.13. Could you please check it again?
Thanks,
Cagatay

**Comment by hpages** [comment] 2021-02-17 01:41
@cdursun You didn't submit the package and you never commented in this issue so I'm not sure how I was supposed to know that I needed to address you. I will do it from now.

Ok so it seems that last time I checked the package I picked up the wrong version, sorry for that. I'm cloning the package repo again, but now from https://git.bioconductor.org/packages/PhenoGeneRanker instead of https://github.com/bozdaglab/PhenoGeneRanker, and I'm indeed seeing version 0.99.13.

Checking this version of the package now...

**Comment by hpages** [comment] 2021-02-18 08:16
@cdursun PhenoGeneRanker passes `R CMD check` and `R CMD BiocCheck` cleanly. Only one minor thing before we can add the package to Bioconductor: the description of the `inputFileName` argument in the man page for `CreateWalkMatrix()` seems truncated:

> inputFileName: The name of the text file that contains the names of

Please address. Note that a complete description of this argument would also require describing the format of the input file, which is something you already do with great details in the vignette, so you could point to the vignette for that in order to avoid repetition.

Thanks

**Comment by cdursun** [comment] 2021-02-18 14:31
Thank you for your feedback @hpages, we will address it soon.

**Comment by cdursun** [comment] 2021-02-18 18:32
Hi @hpages, the package is ready for review, thanks!

**Comment by hpages** [comment] 2021-03-05 02:47
Package is good to go. Thanks!

**Comment by cdursun** [comment] 2021-03-05 14:54
Great, thanks @hpages!

**Comment by mtmorgan** [comment] 2021-03-08 22:30
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/JakeP627.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PhenoGeneRanker")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PhenoGeneRanker

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2021-03-08 22:30 UTC
Labels: 3a. accepted, OK

**Comment by serdarbozdag** [comment] 2021-03-08 23:21
Thanks. I added SSH key to my account https://github.com/serdarbozdag. I tried to submit it to Bioconductor, but it failed. JakeP627 is no longer in this project.
I’m the PI of this project. Can you make my account affiliated with the package? I updated my email address on my Github account to my email address at my new institution (serdar.bozdag@unt.edu<mailto:serdar.bozdag@unt.edu>).

Thanks,
Serdar

Serdar Bozdag, Ph.D.
Associate Professor of Computer Science
Dept. of Computer Science and Engineering
Dept. of Mathematics
BioDiscovery Institute

Discovery Park F295
University of North Texas
Denton, TX 76203-5017
Web: https://biocomp.engineering.unt.edu/
Twitter: @bozdags<https://twitter.com/bozdags>

**Comment by mtmorgan** [comment] 2021-03-08 23:43
Maintainership of this package is very confusing. @cdursun can you please clarify that you no longer wish to maintain this package, and that you wish @serdarbozdag to take on this responsibility?

**Comment by serdarbozdag** [comment] 2021-03-08 23:54
Sorry for the confusion. Please keep @cdursun as maintainer of the package, too. I’m assuming assigning >1 maintainer is possible.

Serdar

On Mar 8, 2021, at 5:43 PM, Martin Morgan <notifications@github.com> wrote:

﻿

Maintainership of this package is very confusing. @cdursun<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcdursun&data=04%7C01%7Cserdar.bozdag%40unt.edu%7C99b5608246e5492cc8c708d8e28bfb95%7C70de199207c6480fa318a1afcba03983%7C0%7C0%7C637508438137622115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=or0qxHcKrwSIkBgoaTvJMvMVFxNlkrXPVw6ro8VC0sk%3D&reserved=0> can you please clarify that you no longer wish to maintain this package, and that you wish @serdarbozdag<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fserdarbozdag&data=04%7C01%7Cserdar.bozdag%40unt.edu%7C99b5608246e5492cc8c708d8e28bfb95%7C70de199207c6480fa318a1afcba03983%7C0%7C0%7C637508438137622115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QppDMx3oxZCjwnfY1FDIBLPIQ%2Bhk52sk%2B4oG6cbnwd0%3D&reserved=0> to take on this responsibility?

**Comment by cdursun** [comment] 2021-03-09 00:52
> The master branch of your GitHub repository has been added to Bioconductor's git repository.
> 
> To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/JakeP627.keys is not empty), then no further steps are required. Otherwise, do the following:
> 
>     1. [Add an SSH key to your github account](https://help.github.com/articles/connecting-to-github-with-ssh/)
> 
>     2. [Submit your SSH key to Bioconductor](https://git.bioconductor.org/BiocCredentials/)
> 
> 
> See further instructions at
> 
> https://bioconductor.org/developers/how-to/git/
> 
> for working with this repository. See especially
> 
> https://bioconductor.org/developers/how-to/git/new-package-workflow/
> https://bioconductor.org/developers/how-to/git/sync-existing-repositories/
> 
> to keep your GitHub and Bioconductor repositories in sync.
> 
> Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at
> 
> https://bioconductor.org/checkResults/
> 
> (Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PhenoGeneRanker")`. The package 'landing page' will be created at
> 
> https://bioconductor.org/packages/PhenoGeneRanker
> 
> If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

> Maintainership of this package is very confusing. @cdursun can you please clarify that you no longer wish to maintain this package, and that you wish @serdarbozdag to take on this responsibility?

Hi @mtmorgan, I will continue to be the maintainer for the package.
