### ISSUE TITLE
zellkonverter

### ISSUE THREAD

**Issue by lazappi** [Bioconductor/Contributions#1549] opened 2020-07-10 13:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/theislab/zellkonverter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LTLA** [comment] 2020-07-13 23:21
Linux and Windows look like Latex errors, dropping the `\Figure{}` should fix them.

Don't know why Windows fails on identity but not equality. Oh well, we might as well just flip to `expect_equal`.

Mac is an unknown reason. Don't know why it's borking out, as things are functioning fine on the BBS. 

I wonder if we can reproduce the error more simply if @lshep runs:

```sh
. '/Users/pkgbuild/Library/Caches/basilisk/1.1.8/0/etc/profile.d/conda.sh' 
conda activate
```

I can only imagine that it's an obtrusive `PYTHONPATH`, despite the fact that I actually unset the `$PYTHONPATH` for that subshell.

**Comment by lazappi** [comment] 2020-07-14 08:03
I will have a look at the LaTeX error and the test. Any extra info on the conda problem would be helpful.

There's also an error from `BiocCheckGitClone` about the `.Rproj` file. Do I need to fix that?

I have updated my email for the mailing list to match my maintainer email (I was already subscribed, just with a different email).

**Comment by lazappi** [comment] 2020-07-15 13:46
@lshep I'm having trouble pushing to the Bioconductor git. I checked the BiocCredentials app and I don't have access to the **zellkonverter** repository. Can you please take a look at that?

**Comment by lshep** [comment] 2020-07-15 17:27
Can you show the commands you are trying with output and git remote -v?

**Comment by lazappi** [comment] 2020-07-16 07:47
Sorry, I should have posted that the first time.

**git remotes**

```bash
$ git remote -v
origin  git@github.com:theislab/zellkonverter.git (fetch)
origin  git@github.com:theislab/zellkonverter.git (push)
upstream        git@git.bioconductor.org:packages/zellkonverter.git (fetch)
upstream        git@git.bioconductor.org:packages/zellkonverter.git (push)
```

**git push**

```bash
$ git push upstream master
FATAL: W any packages/zellkonverter l.zappia DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**SSH check (truncated output)**

```bash
$ ssh -T git@git.bioconductor.org
hello l.zappia, this is git@ip-172-30-0-33 running gitolite3 v3.6.6-6-g7c8f0ab on git 2.24.1

 R    	admin/..*
 R    	packages/..*
 R  	admin/BiocManager
 R  	admin/bioconductor.org
...
 R      packages/spikeLI
 R      packages/spkTools
 R W    packages/splatter
 R      packages/spliceR
 R      packages/spliceSites
...
 R      packages/zFPKM
 R      packages/zebrafishRNASeq
 R      packages/zellkonverter
 R      packages/zinbwave
 R      packages/zlibbioc

**Comment by lshep** [comment] 2020-07-16 11:43
@nturaga  could you investigate?

**Comment by nturaga** [comment] 2020-07-16 15:02
@lazappi I have identified the problem with this. I'll get back to you on when you can push successfully. 

Thank you for your patience.

**Comment by nturaga** [comment] 2020-07-21 14:25
Hi @lazappi , The problem has been fixed. You can commit now.

**Comment by lshep** [comment] 2020-08-20 17:37
I apologize for the delay.  I will review the package tonight and have a review tomorrow.  In the meantime could you correct the sys file ERROR by adding `zellkonverter.Rproj`  into your `.gitignore` 
Thank you

**Comment by LTLA** [comment] 2020-08-25 16:01
It looks like we're in a pretty good state now; are there any further comments?

**Comment by mtmorgan** [comment] 2020-08-27 18:16
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lazappi.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("zellkonverter")`. The package 'landing page' will be created at

https://bioconductor.org/packages/zellkonverter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-08-27 18:16 UTC
Labels: 3a. accepted, WARNINGS
