### ISSUE TITLE
HPiP

### ISSUE THREAD

**Issue by mrbakhsh** [Bioconductor/Contributions#2230] opened 2021-08-13 22:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/mrbakhsh/HPiP

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by mrbakhsh** [comment] 2021-08-15 20:18
Hi, may I please know how long time should I wait for the assigned reviewer to my package? thank you

**Comment by mrbakhsh** [comment] 2021-08-17 03:15
Thank you for reopening the issue.

**Comment by mrbakhsh** [comment] 2021-08-20 03:58
Dear @vjcitn 
I have submitted the package a few days ago, and I have updated the manual again. I would appreciate it if you review the package at a time convenient for you.
Thank you

**Comment by lshep** [comment] 2021-09-01 16:05
Thank you for your submission.  Please see initial review: 



**Build Report/General**

- [ ] The License in the DESCRIPTION and the LICENSE file provided in the
  package do not match.  Please choose one LICENSE type. It must be an open
  source LICENSE. We recommend one of the LICENSE distributed with R
  https://www.r-project.org/Licenses/

- [ ] Please address the coding practice NOTES in the build report.

- [ ] Please try to keep to an 80 character limit as the code will otherwise be
difficult to read when displayed online. One suggested alternative is to
include linebreaks after function arguments.

**DESCRIPTION**

- [ ] We recommend having a BugReport and Url field in the package description.

**README**

- [ ] Please also include Bioconductor installation instructions.


**NEWS**

- [ ] We highly recommend adding a NEWS file so package updates will be included
  in the bi-annual release announcements.  See example release announcement
  http://bioconductor.org/news/bioc_3_13_release/.  Without a NEWS file the
  package will not be included. See
  https://contributions.bioconductor.org/news.html for formatting.

**Unit Tests**

- [ ] We highly recommend unit test to test basic functionality of package

**inst**

- [ ] Please see https://cran.r-project.org/doc/manuals/r-release/R-exts.html
  for naming conventions. Generally data to be called by system.file are in a
  directory `inst/extdata` and internal system data is store in the R directory
  as a sysdata.rda file.  This also explains it nicely
  https://r-pkgs.org/data.html
  
- [ ] All data provided in the inst directory, regardless of subdirectory,
  should have a `inst/script` file associated with how the data was
  generated. This should include source information, licensing if necessary, and
  any preprocessing to generate the data. It can be code, sudo-code, or text.

**vignette**

- [ ] There is no reuse of existing Bioconductor class structure. It seems like
  structures like BiocSet, SummarizedExpeirment,  or at the very least
  BioStrings should be utilized.
  Biostrings seems highly approrpiate to be able to be used throughout the
  vignette as input option to all functions. And as FASTA import method.
  If you utilized SummarizedExperiment or an extention of SummarizedExperiment,
  you could potentially store the results of each of these processes in one
  object. Bioconductor standard object for rectangular feature x sample data is
  a SummarizedExperiment. 

- [ ] Do not use deprecated functions. Please update as recommended by the dplyr
  warnings

```
> x_df <- calculateCTDD(x)
Warning messages:
1: `summarise_each_()` was deprecated in dplyr 0.7.0.
Please use `across()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: Expected 2 pieces. Additional pieces discarded in 273 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
3: `funs()` was deprecated in dplyr 0.8.0.
Please use a list of either functions or lambdas: 

  # Simple named list: 
  list(mean = mean, median = median)

  # Auto named with `tibble::lst()`: 
  tibble::lst(mean, median)

  # Using lambdas
  list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
> 
```

A deprecated function is intended to be removed and the functionality in your
package will then be broken 

- [ ] Syntex errors in Summary of descriptors in the HPiP package

```
the Gold_ReferenceSet.csv data set.

**1. Load the gold-standard data:**

``` 
data is a dead link and this seems like it is wanted as a list header but does
not format properly.

Step 4 is also not displaying properly
```
**4.Map the amino acid composition (AAC) descriptor to the gold-standard data:**

```

- [ ] Because there are multiple filter methods loaded, I originally got an
  error trying to run your code but if you specify the package it should come
  from it works:

```
> pred_interactions <- filter(pred_interactions, ensemble_score > 0.6)
Error in filter(pred_interactions, ensemble_score > 0.6) : 
  object 'ensemble_score' not found

## but if you specify the correct filter it works
> pred_interactions <- dplyr::filter(pred_interactions, ensemble_score > 0.6)

```

- [ ] For plotting results with plots=TRUE in pred_ensemel, I don't get to see
  all three plots interactively as they are overwritten in the same device
  window. I only end up with a ROC plot. 

- [ ] I get more errors trying to run the code
```
> S_interc <- filter(pred_interactions, 
+                            str_detect(Pathogen_protein, "^E:"))
Error in str_detect(Pathogen_protein, "^E:") : 
  could not find function "str_detect"

```
- [ ] All the ERROR trying to mimic your vignette is why we never recommend
  eval=FALSE in the vignettes. If possible run the code as much as possible.


**R code**


- [ ] Large sections of repeated code should be avoided and moved into a single
  function. For example calculateCTDD and CalculateCTDT share most of the same
  code base.  These easily could be merged into one function and have sections
  specific to which method is being called. Same with calculateF1 and
  calculateF2.  The main functions are the exact same except which function to
  call in the lapply at the end. This should be one function with an argument
  for F1 or F2. These are only two examples but all functions that have high
  overlapped should be merged or the sections of code that are the same should
  be its own internal function that each of the main functions call.
  

- [ ] Remove inefficiencies.  For example calculatedCTDD have two fastaSplitted. Please
evaluate in all R files. 

- [ ] Results of webqueries should be cached so users may reproduce
  results. See BiocFileCache. webqueries occur in both get_FASTA and
  get_positivePPI
  

- [ ] It seems very bad practice to share an access key?  I assume this key was
  assigned to you or your group for access; is access to this website restricted
  use with an account?  If so then users should register on their own and the
  function should take an argument of their own assigned access key.

Thank you for your submission.  Please address the above issues.  When ready please make sure there is a version bump to trigger a new build report and comment back here on the above issues and requesting a re-review.  

Cheers,

**Comment by mrbakhsh** [comment] 2021-09-11 03:46
Hi @lshep - I have pushed the following updates. Thank you!
# Build report 
- [X] The License in the DESCRIPTION and the LICENSE file provided in the
package do not match. Please choose one LICENSE type. It must be an open
source LICENSE. We recommend one of the LICENSE distributed with R
https://www.r-project.org/Licenses/.
**Answer:** I have changed the LICENSE to MIT + file LICENSE.
- [X]  Please address the coding practice NOTES in the build report.
**Answer:**  I have addressed almost all the notes as suggested.
- [X]  Please try to keep to an 80-character limit as the code will otherwise be
difficult to read when displayed online. One suggested alternative is to
include linebreaks after function arguments.
**Answer:**  Thank you for the suggestion. Line breaks have been added to keep an 80-character limit.
# Description
- [X]  We recommend having a BugReport and Url field in the package description.
**Answer:** Thank you for the suggestion. They added to the package description. 
# README
 - [X] Please also include Bioconductor installation instructions.
**Answer:**  Bioconductor installation instructions is added to the README file. 
# NEWS
- [X]  We highly recommend adding a NEWS file so package updates will be included in the bi-annual release announcements. See example release announcement http://bioconductor.org/news/bioc_3_13_release/. Without a NEWS file the package will not be included. See https://contributions.bioconductor.org/news.html for formatting.
**Answer:**  NEWS file included in the package.
# Unit Tests
- [X]  We highly recommend unit test to test basic functionality of package.
**Answer:** Done. 
# inst
- [X]  Please see https://cran.r-project.org/doc/manuals/r-release/R-exts.html for naming conventions. Generally, data to be called by system.file are in a directory inst/extdata and internal system data is store in the R directory as a sysdata.rda file. This also explains it nicely https://r-pkgs.org/data.html. 
**Answer:**  Thank you for the suggestion. Raw data now stored in `inst/extdata`, while package data are stored in `data/` directory. In addition, scripts that generate package data in are now available in `data-raw` directory.
- [X] All data provided in the inst directory, regardless of subdirectory, should have an inst/script file associated with how the data was generated. This should include source information, licensing if necessary, and any preprocessing to generate the data. It can be code, sudo-code, or text.
**Answer:**  Done.
# vignette
- [X] There is no reuse of existing Bioconductor class structure. It seems like structures like BiocSet, SummarizedExpeirment, or at the very least BioStrings should be utilized. Biostrings seems highly approrpiate to be able to be used throughout the vignette as input option to all functions. And as FASTA import method.If you utilized SummarizedExperiment or an extention of SummarizedExperiment,
you could potentially store the results of each of these processes in one object. Bioconductor standard object for rectangular feature x sample data is a SummarizedExperiment.
**Answer:** Thank you for the suggestion. Both objects are added to the vignette. 
- [X] Do not use deprecated functions. Please update as recommended by the dplyr warnings
**Answer:** I updated the function.
- [X]  Syntex errors in Summary of descriptors in the HPiP package. Step 4 is also not displaying properly.
**Answer:**  fixed the errors.
- [X]  Because there are multiple filter methods loaded, I originally got an error trying to run your code but if you specify the package it should come from it works.
**Answer:**  Thank you for the suggestion. All the required packages for data manipulation or data handling are loaded in the beginning of the vignette.
- [X]  For plotting results with plots=TRUE in pred_ensembel, I don't get to see all three plots interactively as they are overwritten in the same device window. I only end up with a ROC plot.
**Answer:**  I already fixed the issue, and if argument `plots` set to TRUE, the `pred_ensembel` function will create three plots and save them as pdf file in a sub directory of the working directory. 
- [X]  I get more errors trying to run the code.
**Answer:**  Thank you for the suggestion. All the required packages for data manipulation or data handling are loaded in the beginning of the vignette.
- [X]  All the ERROR trying to mimic your vignette is why we never recommend eval=FALSE in the vignettes. If possible run the code as much as possible.
**Answer:**  All eval arguments are now set to TRUE.

# R code
- [X]  Large sections of repeated code should be avoided and moved into a single function. For example calculateCTDD and CalculateCTDT share most of the same code base. These easily could be merged into one function and have sections specific to which method is being called. Same with calculateF1 and calculateF2. The main functions are the exact same except which function to call in the lapply at the end. This should be one function with an argument for F1 or F2. These are only two examples but all functions that have high overlapped should be merged or the sections of code that are the same should be its own internal function that each of the main functions call.
**Answer:** Thank you for the suggestions. F1 and F2 are merged into one function. Also, Autocorrelation descriptors (moran, geary  and moreau_broto) are now merged into one function. For `calculateCTDD` and `calculateCTDT`, the section of the codes that were similar are now merged.
- [X]  Remove inefficiencies. For example calculatedCTDD have two fastaSplitted. Please evaluate in all R files.
**Answer:**  Done. 
- [X]  Results of webqueries should be cached so users may reproduce results. See BiocFileCache. webqueries occur in both get_FASTA and get_positivePPI.
**Answer:** Thank you for the suggestion. Changed the functions as suggested.
- [X]  It seems very bad practice to share an access key? I assume this key was assigned to you or your group for access; is access to this website restricted use with an account? If so then users should register on their own and the function should take an argument of their own assigned access key.
**Answer:** Thank you for the suggestion. Changed the function as suggested.

**Comment by mrbakhsh** [comment] 2021-09-15 23:20
Hi @lshep - Sorry to push new updates as I found some issues in the `pred_ensembel ( )` function. Looking forward to hearing from you soon, thank you.

**Comment by mrbakhsh** [comment] 2021-09-16 01:37
Hi @lshep - Sorry to push new updates as I found some issues in the `pred_ensembel ( )` function. Looking forward to hearing from you soon, thank you.

**Comment by lshep** [comment] 2021-09-16 17:08
Thank you for the changes.  A few more minor comments: 

- [ ] In vignette, when plot.pdf is saved in pred_ensemel call
```
set.seed(102)
ppi <- pred_ensembel(ind_data,
                     gd,
                     classifier = c("svmRadial", "glm", "ranger"),
                     resampling.method = "cv",
                     ncross = 5,
                     verboseIter = TRUE,
                     plots = TRUE,
                     filename = "plots.pdf")
```
Please show using a `tempdir()`. `filename=file.path(tempdir(), "plots.pdf")`


- [ ] You are still technically sharing your access key with users by providing it as default argument to get_positivePPI. How necessary is it to show the example and usage in the vignette?  This would be an appropriate place to use an `eval=FALSE` in vignette and `donttest` in man examples.  If it is necessary to have the results of this function for subsequent examples in the vignette, I would suggest saving the necessary intermediate object in extdata and then in the vignette after an eval=FALSE (with dummy access.key value), load the object that performed the task with a code chunk in an echo=FALSE. 

Cheers

**Comment by mrbakhsh** [comment] 2021-09-17 02:00
Hi @lshep, thanks a lot for all the help.  I have pushed the following updates. Thank you!

- [X] In the vignette, when plot.pdf is saved in pred_ensemel call `filename=file.path(tempdir(), "plots.pdf")`
**Answer:** Thank you for the suggestion, changed the vignette as suggested. 

- [X]  You are still technically sharing your access key with users by providing it as a default argument to get_positivePPI. How necessary is it to show the example and usage in the vignette? This would be an appropriate place to use an eval=FALSE in vignette and donttest in man examples. If it is necessary to have the results of this function for subsequent examples in the vignette, I would suggest saving the necessary intermediate object in extdata and then in the vignette after an eval=FALSE (with dummy access.key-value), load the object that performed the task with a code chunk in an echo=FALSE.
**Answer:** Thank you for the suggestion. Changed both vignette and the man file as suggested.

**Comment by mrbakhsh** [comment] 2021-09-22 21:05
Hi @lshep, I have addressed the minor comments. Please let me know if you need anything further for the submission.

Thank you

**Comment by lshep** [comment] 2021-09-24 14:41
Thank you.

**Comment by vjcitn** [comment] 2021-10-02 00:46
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mrbakhsh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HPiP")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HPiP

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by vjcitn** 2021-10-02 00:46 UTC
Labels: OK, 3a. accepted
