### ISSUE TITLE
frenchFISH: Poisson models for quantifying DNA copy-number from fluorescence in situ hybridisation of tissue sections

### ISSUE THREAD

**Issue by agberman** [Bioconductor/Contributions#1340] opened 2020-01-15 17:02 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/markowetzlab/frenchFISH

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by agberman** [comment] 2020-01-18 13:59
Hi @lshep , I pushed some changes to the repository dealing with the BiocCheck errors and warnings. Could the tests be re-run now?

Apologies for the probably basic questions. This is my first time submitting to Bioconductor.

**Comment by lshep** [comment] 2020-01-18 14:03
Please make sure your webhook is enabled.  
https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook
Once this is set up a new build should happen when you do a version bump

**Comment by agberman** [comment] 2020-01-20 13:52
Hi @lshep, thank you for your help. I have submitted my changes along with a version bump, and I think I am passing all the BiocCheck tests now. Is there another step that I need to take to move forward with the submission process?

Thanks again for your time,
Adam

**Comment by lshep** [comment] 2020-01-21 13:16
No other steps at this time.  We try to review all packages within 2 weeks of a clean build.  Cheers

**Comment by lshep** [comment] 2020-02-05 15:24
**Build Report:**

- [ ] Could you please look into the NOTE from the tokay2? I don't have much
background in this so if you run into issues maybe it would be worth posting on
the bioc-devel@r-project.org? 
```
* checking compiled code ... NOTE
Note: information on .o files for i386 is not available
Note: information on .o files for x64 is not available
File 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1333/810cf08/tscR.buildbin-libdir/tscR/libs/i386/tscR.dll':
  Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
File 'C:/Users/pkgbuild/packagebuilder/workers/jobs/1333/810cf08/tscR.buildbin-libdir/tscR/libs/x64/tscR.dll':
  Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
File 'tscR/libs/i386/tscR.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
File 'tscR/libs/x64/tscR.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.
It is good practice to register native routines and to disable symbol
search.

```

- [ ] We strongly recommend unit tests.  While most are initially hestitant,
  many find that it helps with debugging and sometimes even development. 



**NEW**

- [ ] Don't add an empty news file. Either have valid entires or remove. We
  collect all package news files to put together the [release announcement](http://bioconductor.org/news/bioc_3_10_release/) at
  every bioconductor release.  we strongly encourage you to utilize it to notify
  users of any changes or bug corrections but is optional. See `?news` in R for
  formatting or
  [news](http://bioconductor.org/developers/package-guidelines/#news)


**DESCRIPTION**

- [ ] Please remove `lazyData: true` we have rarely found it useful and actually
  can slow down package installation. 


**vignette**

- [x] Nice background section and I appreciate the comparisons to other
  Bioconductor packages. 

- [ ] Please include Bioconductor installation instructions as default. You can
  include the github installation as 'development' version

- [ ] When I try to run your vignette manually with only the code shown, I get an ERROR 
```
> data(tscR)
> time <- c(1,2,3)
> sDist <- slopeDist(df, time)
Error in if (dim(x)[1] > 1000) { : argument is of length zero
```
I believe this is because whereever you defined the `df` it is actually not
shown in the vignette (perhaps you did echo=FALSE for that code chunk?)

**Comment by lshep** [comment] 2020-02-05 16:54
Thank you for your submission. Please see comment below: 

**readme**

- [ ] include bioconductor installation instructions

**NEWS**

- [ ] Please include at least one news item not an empty file. We
  collect all package news files to put together the [release announcement](http://bioconductor.org/news/bioc_3_10_release/) at
  every bioconductor release.  we strongly encourage you to utilize it to notify
  users of any changes or bug corrections but is optional. Suggestion: many use
  submission to bioconductor as the first item. 

**DESCRIPTION**

- [ ] Please remove `lazyData: true` we have rarely found this useful and it can
  actually slow the installation of a package. 

**vignette**

- [ ] recommend shortening name to simply `frenchfish.Rmd`. Its much more
  intuitive for the user to do `vignette("frenchfish")` than
  `vignette(frenchfish-vignette")`.  (Or even frenchFISH to match the
  capitalization of your package since R is case sensitive.

- [ ] If you are setting a seed for reproducible results we recommend exposing
  to the user with this explanation. Else it could be confusing when they try
  running your vignette and get different results. 

- [ ] I assume `cell_radius` and `section_height` are values that are given by
  instrumentation at the time the experiment is run? The same actually with the
  counts matrix correct?  Is everything provided from instrumentation? 

**R**

- [ ] remove `paste` in `stop` and `warning` calls. stop and warning
  automatically concatenate multiple argumnents. 
```
> vl = 3
> warning("I have a value:", vl)
Warning message:
I have a value:3 
```
- [ ] Is a data.frame necessary? It seems like you would only ever have numeric values to analyze in which case a matrix would be a better base structure since there is no mixing of different types of data (numeric, character, etc) 

**Overall question**

- [ ] Since you ran the functions on real datasets for your paper, I'm curious
  at why you wouldn't include the raw data and show the actaully analysis
  instead of using random simulated data? It would be a stronger presentation
  and proof of reproducibility to use the data you presented in your paper.

Please address the above comments and when you are ready for a re-review please kick off a new build with a version bump and summarize changes or respond to questions here. 

cheers

**Comment by agberman** [comment] 2020-02-05 20:35
Hi @Ishep, thank you very much for the review and helpful comments. Please see my response to each of your comments below:

readme
 include bioconductor installation instructions

done!

NEWS
 Please include at least one news item not an empty file. We
collect all package news files to put together the release announcement at
every bioconductor release. we strongly encourage you to utilize it to notify
users of any changes or bug corrections but is optional. Suggestion: many use
submission to bioconductor as the first item.

done!

DESCRIPTION
 Please remove lazyData: true we have rarely found this useful and it can
actually slow the installation of a package.

done!

vignette
 recommend shortening name to simply frenchfish.Rmd. Its much more
intuitive for the user to do vignette("frenchfish") than
vignette(frenchfish-vignette"). (Or even frenchFISH to match the
capitalization of your package since R is case sensitive.

done!

 If you are setting a seed for reproducible results we recommend exposing
to the user with this explanation. Else it could be confusing when they try
running your vignette and get different results.

I added an explanation regarding setting the seed.

 I assume cell_radius and section_height are values that are given by
instrumentation at the time the experiment is run? The same actually with the
counts matrix correct? Is everything provided from instrumentation?

Yes, these are both measurements which will be know by the user as a prerequisite (cell radius will be known based on the cell type being imaged, and section height from the instrumentation).

R
 remove paste in stop and warning calls. stop and warning
automatically concatenate multiple arguments.

done!

 Is a data.frame necessary? It seems like you would only ever have numeric values to analyze in which case a matrix would be a better base structure since there is no mixing of different types of data (numeric, character, etc)

Good point, I've changed the input data structures from dataframes to matrices.

Overall question
 Since you ran the functions on real datasets for your paper, I'm curious
at why you wouldn't include the raw data and show the actaully analysis
instead of using random simulated data? It would be a stronger presentation
and proof of reproducibility to use the data you presented in your paper.
Please address the above comments and when you are ready for a re-review please kick off a new build with a version bump and summarize changes or respond to questions here.

The answer to this is slightly complicated. The paper was written something like a year and a half ago by someone else, and he is working now to reproduce the exact counts shown in the paper from FISHalyseR (the automatic spot-counting software he used before applying the corrections this package does). So we're working out that issue first before we adjust the vignette to include the paper's input (which might change slightly for the automatic counting side of things once we re-run FISHalyseR). The short answer is that we fully intend to use the paper's data in the vignette, but due to some minor issues in reproducing the raw counts to feed into the package, it may be a bit before the vignette can be updated with those exact numbers. Would it be okay if for now we used these simulated data in the vignette?

Thanks again,
Adam

**Comment by lshep** [comment] 2020-02-05 20:45
So is this run in addition to FISHalyseR? Is it meant to be a compliment or additional analysis step afterwards?

**Comment by agberman** [comment] 2020-02-05 20:50
It's meant to be an additional analysis step afterward. There are basically two main ways people get spot counts from FISH: either they count them manually, or they use a computer vision-based software (e.g. FISHalyseR) to automatically count the spots for each probe in the image. FrenchFISH takes these raw spot counts (either manually counted or automatic), then corrects those spot counts using Poisson models (they need to be corrected because in a FISH image, not all cells will be visible in a given section, or a cell might be cut in such a way so that not all of the probes in it will be visible) - so the model is for adjusting for this noise to give a more accurate count.

**Comment by lshep** [comment] 2020-02-05 20:54
Excellent.  And even better now that I know it links in with the other Bioconductor package.  It might be nice to make better mention of this somewhere in the vignette?  It might also be nice to show a continued analysis with the data the FISHalyseR makes use of until your data is ready - would this be an option?

**Comment by agberman** [comment] 2020-02-05 21:10
I can absolutely explain more about that in the vignette (it could be added as a prelude to the automatic spot counting section). Regarding your second point, do you mean to use the old FISHalyseR counts in the current version of the paper as an input for the vignette? If so, I can do this (assume those data are still around), then change the input data later once we re-run FISHalyseR. Is this what you mean?

**Comment by lshep** [comment] 2020-02-05 21:17
Yes  thats what I mean -  I know there are still extdata in the FISHalyseR package that I assumed they used to demonstrate their package use - if you could use that to run the FISHalyseR (if its too timely to run directly in the vignette, you could always save the output from that analysis in your package to use for demonstration and just reference it was generated with the sample data in FISHalyseR)  and show the full pipeline and use case I think that might be useful -

**Comment by agberman** [comment] 2020-02-11 14:08
Hi @lshep, sorry for the delay in my response. That should be possible. I will work on it and push a version update once it's done. Thanks again for your help.

**Comment by agberman** [comment] 2020-02-17 20:16
Hi @lshep, I've added a new function for parsing the CSVs of automated probe counts that FISHalyseR outputs into count matrices for input into frenchFISH's getAutomaticCountsEstimates function. I've also updated the automated count correction portion of the vignette to account for this. I use the CSV that FISHalyseR's vignette produces of real count data and use frenchFISH to correct them. Are there any further steps I should take?

Thanks you for your help,
Adam

**Comment by mtmorgan** [comment] 2020-03-08 19:49
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/agberman.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("frenchFISH")`. The package 'landing page' will be created at

https://bioconductor.org/packages/frenchFISH

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-03-08 19:49 UTC
Labels: 3a. accepted, OK
