### ISSUE TITLE
MAI

### ISSUE THREAD

**Issue by Dekermanjian** [Bioconductor/Contributions#2203] opened 2021-07-21 01:34 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/KechrisLab/MAI

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment] 2021-07-21 16:40
Hi Jonathan, @Dekermanjian 

Thank you for your submission. 
Unfortunately, at this time, we cannot accept a package that does not use existing Bioconductor infrastructure. 
See below.

Best regards,
Marcel

---

# MAI #2203

* `MAI` does not make use of the existing Bioconductor infrastructure in the
field of metabolomics and therefore is not a candidate for acceptance.
* If you would like to revise your package please state how you will integrate
the package to existing Bioconductor classes and methods.

**Comment by Dekermanjian** [comment] 2021-07-21 18:15
Hi Marcel, @LiNk-NY 

I would like to revise MAI to be able to provide imputation functionality on summarized experiment classes.

**Comment by Dekermanjian** [comment] 2021-07-27 16:17
Hi Marcel, @LiNk-NY 
I just wanted to let you know that I have added the functionality to impute data included as assay in the SummarizedExperiment class.

**Comment by LiNk-NY** [comment] 2021-07-27 20:05
Hi Jonathan, @Dekermanjian 

Thanks for making those changes. 
Please see the review below. 

Best regards,
Marcel

---

# MAI #2203

## DESCRIPTION

* Add `BugReports` and `URL` fields pointing to GitHub.
* Looks good.

## NAMESPACE

* Avoid using `exportPattern` in the `NAMESPACE`.
* Export only the functions that are relevant to end users.

## vignettes

* Use a more descriptive name than `data_miss`. Usually the names are relevant
to the technology from which the data is collected. If it is generated data,
use the technology name that the data emulates.
* The extraction of data looks cumbersome with `[[x]][[y]]`.
* Rename `data_miss` to `se` or something similar so that the user knows the
object is a `SummarizedExperiment`.
* Minor: Use `<-` instead of `=` for assignment.

## R

* Avoid the use of `1:n` sequence generation and use the more robust,
`seq_len(length(x))` and / or `seq_along(x)`
* Include the character vector of algorithms (in `R/MAI.R:MAI()`) in the
function arguments and use `match.arg` within the function body to match to
one.
* Avoid using `print` within the function and use `message` also allow users
to turn off the messages with a `verbose` argument in the function (`MAI()`).
* Either only take the first assay in `data_miss` when it is a
`SummarizedExperiment` or allow users to specify the assay with an `i`
argument in the function that has a default of 1. This allows users to select
which assays to impute missing data for (more flexible).
* The use of `exists` is awkward and not encouraged. You can add `stopCluster`
to `on.exit`.
* Minor: Use `<-` instead of `=` for assignment.
* Minor: `seq_along(1:10)` is the same as `1:10`

## man

* Properly document the `data_miss` argument so that it includes the use
of `SummarizedExperiment`.
* Note that the MAI function returns a list in the `value` section.

## tests

* We strongly encourage that you add more tests to ensure that the code
is robust to all types of inputs.

**Comment by Dekermanjian** [comment] 2021-07-27 20:11
Thank you @LiNk-NY 

I will make the changes you have listed. 

Marcel, for the 1:n portion, in the code I have seq_along for all of them but the BiocCheck is still saying that they are 1:n. Am I missing something?

**Comment by LiNk-NY** [comment] 2021-07-27 20:37
Hi Jonathan, @Dekermanjian 

Please see the output of `BiocCheck::BiocCheck(".")`

```
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        Altered_mm_algorithm.R (line 17, column 46)
        Altered_mm_algorithm.R (line 18, column 41)
        Altered_mm_algorithm.R (line 23, column 53)
        Altered_mm_algorithm.R (line 41, column 32)
        Altered_mm_algorithm.R (line 50, column 16)
        Altered_mm_algorithm.R (line 82, column 32)
        Altered_mm_algorithm.R (line 90, column 26)
        Altered_mm_algorithm.R (line 132, column 55)
        Altered_mm_algorithm.R (line 160, column 25)
        Altered_mm_algorithm.R (line 172, column 25)
        MAI.R (line 71, column 23)
        nsKNN.R (line 16, column 43)
        nsKNN.R (line 18, column 24)
        nsKNN.R (line 29, column 55)
        nsKNN.R (line 32, column 55)
        nsKNN.R (line 40, column 25)
        nsKNN.R (line 78, column 25)
        nsKNN.R (line 80, column 36)
        nsKNN.R (line 83, column 29)
        nsKNN.R (line 91, column 38)
        nsKNN.R (line 94, column 59)
        nsKNN.R (line 94, column 100)
        NSKNNMissingData.R (line 16, column 46)
        NSKNNMissingData.R (line 17, column 41)
        NSKNNMissingData.R (line 22, column 53)
        NSKNNMissingData.R (line 40, column 32)
        NSKNNMissingData.R (line 49, column 26)
        NSKNNMissingData.R (line 79, column 32)
        NSKNNMissingData.R (line 87, column 26)
        NSKNNMissingData.R (line 128, column 55)
        NSKNNMissingData.R (line 154, column 25)
        NSKNNMissingData.R (line 164, column 25)
        singleImputationFunctions.R (line 37, column 15)
        utils.R (line 30, column 23)
        utils.R (line 94, column 35)
        utils.R (line 129, column 23)
        utils.R (line 130, column 25)
        utils.R (line 167, column 30)
        utils.R (line 167, column 71)
```

**Comment by Dekermanjian** [comment] 2021-07-27 21:22
@LiNk-NY 
Yes, but if you look at the code I have seq_along() for all of those lines. Am I doing something wrong?

**Comment by Dekermanjian** [comment] 2021-07-28 15:46
Hi Marcel, @LiNk-NY 

Here is what I have done in the latest push

# DESCRIPTION
- added BugReports and URL

# NAMESPACE
- removed exportPattern

# vignettes
- changed name of data from data_miss to untargeted_LCMS_data
- renamed data_miss to se for Summarized Experiment case

# R
- included vector of algorithms and match.arg
- replaced print with message and added a verbose argument
- added assay_ix to allow designated assay imputation by assay index
- removed exists for stopCluster

# Man
- properly documented data_miss, added new argument documentation, and documented values returned

**Comment by LiNk-NY** [comment] 2021-07-28 18:48
> @LiNk-NY
> Yes, but if you look at the code I have seq_along() for all of those lines. Am I doing something wrong?

Hi Jonathan, @Dekermanjian 

Pulling the first two examples: 

```r
  belowThreshMet = data[sortAvgIdx[seq_along(1:numMetBelowThresh)],]
  belowThreshIdx = sortAvgIdx[seq_along(1:numMetBelowThresh)]
```

The issue is that `1:n` is still being used despite it being wrapped by `seq_along`. 
Consider this scenario where `n` or `numMetBelowThresh` is zero: 

```r
seq_along(1:0)
# [1] 1 2
```

and now 

```r
seq_len(0)
# integer(0)
```

These are not the same. The latter is more robust and the former is possibly wrong.

**Comment by LiNk-NY** [comment] 2021-07-28 18:52
> # vignettes
> * changed name of data from data_miss to untargeted_LCMS_data
> * renamed data_miss to se for Summarized Experiment case
>
> # R
> * included vector of algorithms and match.arg
> * replaced print with message and added a verbose argument
> * added assay_ix to allow designated assay imputation by assay index
> * removed exists for stopCluster
> 
>
> # Man
> * properly documented data_miss, added new argument documentation, and documented values returned

These are great changes! Thanks for adding them. 

Best,
Marcel

**Comment by Dekermanjian** [comment] 2021-07-28 18:54
@LiNk-NY 
Okay, I understand now. I will fix all the seq_alongs ASAP.

**Comment by Dekermanjian** [comment] 2021-07-28 19:32
Marcel, @LiNk-NY 
I have removed all `seq_along(1:n)` and replaced them with `seq_len(n)`. Let me know if there are other changes/additions you would like me to make to MAI. 

Thank you for you review of our package.

**Comment by LiNk-NY** [comment] 2021-07-28 19:50
Hi Jonathan, @Dekermanjian 

Thank you for making those changes and for your contribution.
Your package has been accepted to Bioconductor.

Best,
Marcel

**Comment by Dekermanjian** [comment] 2021-07-28 20:00
@LiNk-NY 

Thank you very much!

**Comment by vjcitn** [comment] 2021-08-17 11:49
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Dekermanjian.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MAI")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MAI

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by vjcitn** 2021-08-17 11:49 UTC
Labels: OK, 3a. accepted
