### ISSUE TITLE
SINCE

### ISSUE THREAD

**Issue by XZouProjects** [Bioconductor/Contributions#1087] opened 2019-04-10 08:08 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/XZouProjects/SINCE

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2019-04-10 19:41
Looks like your package doesn't use [standard bioconductor packages][1] for robustness and interoperability, and does not have fully evaluated code chunks in the vignette to illustrate / test package functionality!

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by hpages** [comment] 2019-04-15 16:06
The vignette hangs on malbec2 on the call to `SINCE()`. `SINCE()` uses snow/doSNOW internally to do the following:
```
cl <- makeCluster(paralSize, type = getClusterOption("type"))
registerDoSNOW(cl)
... some computations ...
stopCluster(cl)
```
This code works on my laptop where `getClusterOption("type")` returns `"SOCK"`. However, on malbec2, where Rmpi is installed, `getClusterOption("type")` returns `"MPI"`, which seems to cause the call to `stopClusters()` to hang. This can be reproduced with:
```
library(snow)
library(doSNOW)
cl <- makeCluster(4, type="MPI")
registerDoSNOW(cl)
stopCluster(cl)  # hangs!
```
The problem will go away if you explicitly specify `type="SOCK"` in your call to `makeCluster()`.

However, I would encourage you to consider a BiocParallel-based solution for your parallelization needs, instead of the current snow/doSNOW-based solution. BiocParallel experts @mtmorgan and @nturaga might be able to provide some guidance.

H.

**Comment by XZouProjects** [comment] 2019-04-17 05:24
what is the next step?

**Comment by Liubuntu** [comment] 2019-05-03 21:06
Hi @XZouProjects , 

Thanks for submitting your package to Bioconductor. However, as @mtmorgan and @hpages has commented earlier, your package is stand-alone without interoperating with any Bioconductor data structures while you are actually working with single cell expression data, and you don't have any runnable code chunks in the vignette. Your example data included hard-coded weblink which could be broken very easily. 

So please respond for the `IMPORTANT` issues as soon as possible. If this package doesn't comply
with the Bioconductor guidelines, it would not be reviewed.

Check [here](https://bioconductor.org/developers/package-guidelines/)
for the Bioconductor package guidelines. 

## DESCRIPTION
- **IMPORTANT:** You should interoperate with existing Bioconductor
  packages for the robustness. See Martin's comment
  [here](https://github.com/Bioconductor/Contributions/issues/1087#issuecomment-481833927).
- You should `Depends: R(>= 3.6)` and `Imports: ` other packages if
  you don't want to load them with `SINCE`.

## Namespace

## R/ 

### data structures (reusing Bioc?)
- **IMPORTANT**: Since your package is designed to work with single
  cell expression data, it should at least be interoperable with the
  `SummarizedExperiment`, `SingleCellExperiment`, etc. With these data
  structures, you could not only save the expression data, but also
  the `rowData` for the gene annotations, and `colData` for sample
  annotation. You may also save your results inside the
  `SummarizedExperiment` container.

### Other issues: 
- add default values in the argument documentation.
- add runnable examples, without the hard-coded weblink.
- `cluster_res_list` contains the file names and then called
  `read.table(cluster_res_list)`, however, the file was not contained
  in the package...
- use `nrow()` instead of dim()[1].
- Prefix non-exported functions with a ‘.’, e.g. the `Binarization`, etc.

## man
- need documentation for package itself.

## vignette
- Need runnable code chunks. See Herve's comments
  [here](https://github.com/Bioconductor/Contributions/issues/1087#issuecomment-483315908).

## unit tests
- Unit tests are strongly recommended. See
  [here](https://bioconductor.org/developers/package-guidelines/#unittest).

## NEWS 
- A NEWS file should be added in the top directory. See
  [here](https://bioconductor.org/developers/package-guidelines/#news).

Best,
Qian

**Comment by Liubuntu** [comment] 2019-05-16 18:25
Hi @XZouProjects , 

We normally expect responses (direct comments / explanations / commits, etc.) from the package maintainer to the reviewer within 2 weeks. If you think the package is not ready for further evaluation, or you need additional time to implement the fixes, kindly let us know, so we can deactivate this issue and re-open whenever you are ready. 

Thanks!
Qian

**Comment by Liubuntu** [comment] 2019-05-21 16:24
Hi @XZouProjects , 

Since we didn't receive any response both here and through email. I'll close the issue temporarily and re-open upon request. 

Thanks,
Qian

**Closed** 2019-05-21 16:24 UTC
Labels: 2. review in progress, OK
