### ISSUE TITLE
DropletTestFiles

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1597] opened 2020-08-20 06:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/DropletTestFiles

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LTLA** [comment] 2020-08-20 06:27
As suggested by @lshep. I've already uploaded the first round of files to S3, and I'll add some actual tests once those files become available on **ExperimentHub**.

**Comment by lshep** [comment] 2020-08-20 14:42
Done! 
```
snapshotDate(): 2020-08-20
> query(eh, "DropletTestFiles")
ExperimentHub with 13 records
# snapshotDate(): 2020-08-20
# $dataprovider: 10X Genomics
# $species: Homo sapiens
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH3646"]]' 

           title                                
  EH3646 | 10X ATAC PBMC 1k peak count matrix   
  EH3647 | 10X ATAC PBMC 1k peak HDF5 matrix    
  EH3648 | 10X ATAC PBMC 1k motif count matrix  
  EH3649 | 10X ATAC PBMC 1k motif HDF5 matrix   
  EH3650 | 10X PBMC 5k molecule information file
  ...      ...                                  
  EH3654 | 10X PBMC 5k raw count matrix         
  EH3655 | 10X PBMC 4k raw count matrix         
  EH3656 | 10X PBMC 4k filtered count matrix    
  EH3657 | 10X PBMC 4k raw HDF5 matrix          
  EH3658 | 10X PBMC 4k molecule information file
```

**Comment by LTLA** [comment] 2020-08-21 05:31
Thanks @lshep, I've added tests and functional examples now. 

I just realized that one of my dataset's names was not quite specific enough. Could you rename all files with `DropletTestFiles/tenx-3.1.0-pbmc5k` to `DropletTestFiles/tenx-3.1.0-pbmc5k_protein`? For context: I recently found out that there is another PBMC 5K dataset that does _not_ have protein, so I need something to distinguish them. I've already updated the relevant metadata file in `inst/extdata` correspondingly in my GitHub repository. (I tried to push it to the BioC git but it seems that a repository has not been set up there yet.)

Also, to give you a heads up: there will be another round of files for this package, probably early next week - just waiting on someone else to do an upload for me. I'll let you know here when it's ready.

**Comment by lshep** [comment] 2020-08-24 15:44
@LTLA  Deleted the old files out - working on add the updated.  I noticed the RDataPath in the csv file has tenx-3.1.0-5k_pbmc_protein_v3  but the directory structure uploaded does not have the _v3 - I assume this should be updated in the metadata file and that you don't want the extra extension but wanted to verify

**Comment by lshep** [comment] 2020-08-24 15:48
I missed [this comment](https://github.com/Bioconductor/Contributions/issues/1597#issuecomment-678721268) about deleting all files from EHub -- Is this metadata entries and s3 files?

**Comment by LTLA** [comment] 2020-08-24 16:17
Yes: I'll upload the files with the fixed names to S3 this evening.

**Comment by lshep** [comment] 2020-08-24 16:20
Ok. I'll delete everything out and we can start fresh.  Cheers

**Comment by LTLA** [comment] 2020-08-25 04:38
Files have been uploaded again. To be precise, there are five sets of files in `DropletTestFiles/` on the EHub S3:

```
tenx-2.0.1-nuclei_900
tenx-3.1.0-5k_pbmc_protein_v3
tenx-atac-1.2.0-atac_pbmc_1k_nextgem
tenx-3.0.0-pbmc_10k_protein_v3
tenx-4.0.0-SC3_v3_NextGem_DI_Neuron_10K
```

There is still one set that has not been uploaded yet (`tenx-2.1.0-pbmc4k`) as I am waiting for 10X to reply to me about a missing file. If they don't respond in a timely manner, I will just upload what I have, but in the meantime, the set of files that we do have should be sufficient to proceed with the review.

**Comment by lshep** [comment] 2020-08-26 12:33
Added.  I didn't fine tooth check each file so let me know if there are any issues.   

```
snapshotDate(): 2020-08-26
> query(eh, "DropletTest")
ExperimentHub with 48 records
# snapshotDate(): 2020-08-26
# $dataprovider: Jonathan Griffiths, 10X Genomics
# $species: Mus musculus, Homo sapiens
# $rdataclass: character
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["EH3685"]]' 

           title                                                             
  EH3685 | 10X brain nuclei 1k molecule information file                     
  EH3686 | 10X brain nuclei 1k filtered HDF5 matrix                          
  EH3687 | 10X brain nuclei 1k raw HDF5 matrix                               
  EH3688 | 10X brain nuclei 1k filtered count matrix                         
  EH3689 | 10X brain nuclei 1k raw count matrix                              
  ...      ...                                                               
  EH3728 | HiSeq 4000-sequenced mammary epithelial cells (expt. 1 barcode D1)
  EH3729 | HiSeq 4000-sequenced mammary epithelial cells (expt. 1 barcode E1)
  EH3730 | HiSeq 4000-sequenced mammary epithelial cells (expt. 1 barcode F1)
  EH3731 | HiSeq 4000-sequenced mammary epithelial cells (expt. 1 barcode G1)
  EH3732 | HiSeq 4000-sequenced mammary epithelial cells (expt. 1 barcode H1)
```

**Comment by LTLA** [comment] 2020-08-28 00:50
Looking at them, the Windows and Linux errors don't seem like they're my fault.

**Comment by hpages** [comment] 2020-08-28 15:25
Hi Aaron,

Let's ignore them.

W.r.t. the BUILD error on malbec1: I was not able to reproduce on malbec1 or on my laptop. Looks like an ExperimentHub hiccup (I see a lot of them these days on the build machines).

W.r.t. the CHECK error on tokay1: Looks like vctrs was missing when DropletTestFiles got checked. Our current set is to use the same R instance on the build machines for the BBS and SPB. Maybe BBS was running the daily builds and in the process of reinstalling vctrs? This kind of collision is unfortunately a risk with this setup.

I see this when running the examples:
```
> getTestFile(out$rdatapath[1])
snapshotDate(): 2020-08-26
see ?DropletTestFiles and browseVignettes('DropletTestFiles') for documentation
loading from cache
                                               EH3690 
"/home/hpages/.cache/ExperimentHub/2d935858b517_3726" 
```
but:
```
> ?DropletTestFiles
No documentation for ‘DropletTestFiles’ in specified packages and libraries:
you could try ‘??DropletTestFiles’
```
Other than that package is good to go.

H.

**Comment by mtmorgan** [comment] 2020-09-03 18:31
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DropletTestFiles")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DropletTestFiles

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-09-03 18:31 UTC
Labels: 3a. accepted, OK
