### ISSUE TITLE
curatedTBData

### ISSUE THREAD

**Issue by xutao-wang** [Bioconductor/Contributions#2292] opened 2021-09-16 19:18 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/compbiomed/curatedTBData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment] 2021-09-25 00:23
Hi Xutao, @xutao-wang 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

--- 

# curatedTBData #2292

* Please reduce the size of the repository. Currently it sits at 3.6 Gb. Use
the BFG repo cleaner and notify us after to re-clone.

## DESCRIPTION

* Consider using the native pipe `|>` to avoid the `magrittr` dependency.
* Looks good.

## NAMESPACE

* Looks concise.
* Use either 'camelCase' or 'snake_case' exclusively.
* Consider using the `subset` generic rather than `subset_curatedTBData`.

## vignettes

* Remove GitHub installation and after acceptance.
* Avoid using `devtools::load_all()` anywhere in package code.
* Please keep the text to a 80 character width limit.
* Consider naming logical argument consistently, e.g., `curated.only` and
`dry.run`
* Fix typos in the results and add a `\n` carriage return at the end of the
output:
```r
Will download the following resources for GSE19439 from the ExperiementHub:
GSE19439_assay_raw
GSE19439_assay_curated
GSE19439_column_data
GSE19439_row_data
GSE19439_meta_data>
```
* "Now" keyword in the output is probably not needed.
* Consider adding a progress bar so that the user knows it is working.
* Avoid installing packages for the user. The `curatedTBData` function
consistently asks the user to update packages, please remove this.
* The function returns a list with a single `MultiAssayExperiment`. Perhaps the
function should return only a `MultiAssayExperiment` object.
* Do not use `cat` in the vignette.

## R

* The use of `base::*` is not needed.
* Consider separating analytical / graphical functions into a different
package to potentially avoid namespace collisions and keep the focus of the
package.
* Use `is.*` for S3 classes.
* Avoid copy and append method inside of `for` loops in `R/curatedTBData.R`.
* Do not use `cat` inside a function unless you are creating a `show` method.
* Consider using the `metadata` before querying rather than operating on the
result of the `Hub` query.
* You might don't need to create a `sampleMap` when `primary` and `colname`
names are the same, simply use the constructor function.
* Avoid creating methods for classes outside of the package (e.g.,
`subset_curatedTBData` for `SummarizedExperiment` and `MultiAssayExperiment`).
You can create a plain function that uses the expected names
(`annotationColName`) inside the downloaded data object in the package.
* 'AUC' case should be consistent in both `combine_auc` and `get_mean_AUC`.

## tests

* Looks good.
* Consider adding more tests to `combine_auc`, `get_mean_AUC`.
```r
> covr::package_coverage()
curatedTBData Coverage: 35.52%
R/combine_auc.R: 0.00%
R/get_mean_AUC.R: 0.00%
R/heatmap_auc.R: 4.80%
R/boxplotTBSig.R: 8.33%
R/combineObjects.R: 76.71%
R/subset_curatedTBData.R: 77.78%
R/curatedTBData.R: 80.46%
```

**Comment by xutao-wang** [comment] 2021-10-03 02:40
Dear Marcel, @LiNk-NY 

Thank you for your helpful suggestions!
I have reduced the package size and modified package based on your comments. Can you help me to re-clone the repository? 

Thanks,
Xutao

**Comment by lshep** [comment] 2021-10-05 16:40
@nturaga  I think this needs a reclone on git.bioconductor.org

**Comment by LiNk-NY** [comment] 2021-10-05 21:10
Thanks Nitesh and Lori for taking care of this! 

I can confirm a reduction of repo size from 3.6 Gb to 1.60 MiB. :heavy_check_mark: 

Xutao, @xutao-wang 
Please make sure to respond to the review line by line. 

Best regards,
Marcel

**Comment by xutao-wang** [comment] 2021-10-06 00:10
Thank you folks for the help!

Marcel @LiNk-NY, please see below for the respond. I really appreciate your time on reviewing the package, let me know if you have any comments or thoughts!

# curatedTBData

- [x] Please reduce the size of the repository. Currently it sits at 3.6 Gb. Use
the BFG repo cleaner and notify us after to re-clone.
**Answer**: Repository size has been reduced.

# DESCRIPTION

- [x] Consider using the native pipe |> to avoid the magrittr dependency.
**Answer**: replace `%>%` with `|>`. magrittr dependency has been removed.

# NAMESPACE 

- [x] Use either 'camelCase' or 'snake_case' exclusively.
**Answer**: All exproted function names have been changed to snake_case.
- [x] Consider using the subset generic rather than subset_curatedTBData. 
**Answer**: Methods for subset_curatedTBData has been removed.

# vignettes

- [x] Remove GitHub installation and after acceptance.
**Answer**: Github installation code has been removed.
- [x] Avoid using `devtools::load_all()` anywhere in package code.
**Answer**: `devtools::load_all()` hase been removed.
- [x] Please keep the text to a 80 character width limit.
**Answer**: The text in the vignette has been edited to a 80 characters.
- [x] Consider naming logical argument consistently, e.g., `curated.only` and
`dry.run`
**Answer**: Change to `dry.run`.
- [x] Fix typos in the results and add a `\n` carriage return at the end of the
output: 

```R
Will download the following resources for GSE19439 from the ExperiementHub:
GSE19439_assay_raw
GSE19439_assay_curated
GSE19439_column_data
GSE19439_row_data
GSE19439_meta_data>
```
**Answer**: Add `\n` at the end of the output, and fix typo in the vignette:
```r
Will download the following resources for GSE19439 from the ExperiementHub:
GSE19439_assay_raw
GSE19439_assay_curated
GSE19439_column_data
GSE19439_row_data
GSE19439_meta_data

> 
```
- [x] "Now" keyword in the output is probably not needed.
**Answer**: Remove "Now" in the output.
- [x] Consider adding a progress bar so that the user knows it is working.
**Answer**: Add progressbar when downloading the data.
```r
> curatedTBData("GSE19439", dry.run = FALSE, curated.only = FALSE)
snapshotDate(): 2021-09-24
Downloading: GSE19439
  |=========================================================================| 100%
Finished!
```
- [ ] Avoid installing packages for the user. The curatedTBData function
consistently asks the user to update packages, please remove this.
**Answer**: This is probably due to `eh[[id]]` tries to install `curatedTBData` package when it has not been installed in the user's library. \
The message should be gone after the package has been installed. Could you let me know if there is a better way to handle this? Thanks!
- [ ] The function returns a list with a single `MultiAssayExperiment`. Perhaps the
function should return only a `MultiAssayExperiment` object.
**Answer**: To keep the independence of each study, I maintain a list of `MultiAssayExperiment` as output for now. 
- [x] Do not use `cat` in the vignette.
**Answer**: `cat` in the vignette has been removed.

# R
- [x] The use of `base::*` is not needed.
**Answer**: Remove all `base::`
- [ ] Consider separating analytical / graphical functions into a different
package to potentially avoid namespace collisions and keep the focus of the
package.
**Answer**: Thank you for pointing this out! The main focus of the package is the data. The analytical/graphical functions are used for example analysis in the vignette. These functions can be removed from package uppn discussion. I keep them in the package for now. 
- [x] Use `is.*` for S3 classes.
**Answer**: Change to `is.*` for S3 classes. 
- [x] Avoid copy and append method inside of `for` loops in `R/curatedTBData.R`.
**Answer**: Remove `for` loops in `R/curatedTBData.R`.
- [x] Do not use `cat` inside a function unless you are creating a show method.
**Answer**: Remove `cat` from `curatedTBData()`
- [x] Consider using the `metadata` before querying rather than operating on the
result of the `Hub` query.
**Answer**: Use `metadata` to select appropriate query names.
- [x] You might don't need to create a `sampleMap` when `primary` and `colname`
names are the same, simply use the constructor function.
**Answer**: Remove `sampleMap`.
- [x] Avoid creating methods for classes outside of the package (e.g.,
`subset_curatedTBData` for `SummarizedExperiment` and `MultiAssayExperiment`).
You can create a plain function that uses the expected names
(`annotationColName`) inside the downloaded data object in the package.
**Answer**: Change `subset_curatedTBData()` into plain functions.
- [x] 'AUC' case should be consistent in both `combine_auc` and `get_mean_AUC`.
**Answer**: Change to `get_mean_auc`.

# tests

- [x] Consider adding more tests to `combine_auc`, `get_mean_AUC`. 

```r
> covr::package_coverage()
curatedTBData Coverage: 35.52%
R/combine_auc.R: 0.00%
R/get_mean_AUC.R: 0.00%
R/heatmap_auc.R: 4.80%
R/boxplotTBSig.R: 8.33%
R/combineObjects.R: 76.71%
R/subset_curatedTBData.R: 77.78%
R/curatedTBData.R: 80.46%
```
**Answer**: Add more tests to `combine_auc` and `get_mean_auc`.
```r
> covr::package_coverage()
curatedTBData Coverage: 78.59%
R/combine_auc.R: 58.90%
R/combine_objects.R: 76.55%
R/subset_curatedTBData.R: 80.23%
R/curatedTBData.R: 80.56%
R/heatmap_auc.R: 87.31%
R/get_mean_auc.R: 88.46%
R/boxplotTBSig.R: 92.45%
```

**Comment by LiNk-NY** [comment] 2021-10-06 02:35
Hi Xutao, @xutao-wang 

Thank you for making those changes. The package is looking better!
Please see some responses below. 

Best,
Marcel

---

> * [x]  Fix typos in the results and add a `\n` carriage return at the end of the
>   output:
> **Answer**: Add `\n` at the end of the output, and fix typo in the vignette:
> 
> ```r
> Will download the following resources for GSE19439 from the ExperiementHub:
> GSE19439_assay_raw
> GSE19439_assay_curated
> GSE19439_column_data
> GSE19439_row_data
> GSE19439_meta_data
> 
> > 
> ```

It looks like 'ExperiementHub' is still present. Please change this to 'ExperimentHub'. 

> * [ ]  Avoid installing packages for the user. The curatedTBData function
>   consistently asks the user to update packages, please remove this.
>   **Answer**: This is probably due to `eh[[id]]` tries to install `curatedTBData` package when it has not been installed in the user's library. 
>   The message should be gone after the package has been installed. Could you let me know if there is a better way to handle this? Thanks!

This seems to be the case. Thanks for clearing that up. 

> * [ ]  Consider separating analytical / graphical functions into a different
>   package to potentially avoid namespace collisions and keep the focus of the
>   package.
>   **Answer**: Thank you for pointing this out! The main focus of the package is the data. The analytical/graphical functions are used for example analysis in the vignette. These functions can be removed from package uppn discussion. I keep them in the package for now.

To keep packages modular, I would recommend that you put your analysis and even graphical functions in separate packages if they are substantial. This makes it easier for users looking for the data to only download the package that will access it. For those looking to analyze the data, they would use both.

**Comment by xutao-wang** [comment] 2021-10-06 20:58
Hi Marcel @LiNk-NY,

Thank you for the prompt response! 

The typo has been fixed:
```R
> curatedTBData("GSE19439", dry.run = TRUE, curated.only = FALSE)
snapshotDate(): 2021-10-06
dry.run = TRUE, listing dataset(s) to be downloaded
Set dry.run = FALSE to download dataset(s).
Will download the following resources for GSE19439 from the ExperimentHub:
GSE19439_assay_raw
GSE19439_assay_curated
GSE19439_column_data
GSE19439_row_data
GSE19439_meta_data

> 
```

I think you are right for putting the analysis in a separate place. The analytical functions and examples have been removed from the package. 

Please kindly let me know if there is anything else I need to edit.

Best,
Xutao

**Comment by LiNk-NY** [comment] 2021-10-07 15:03
Hi Xutao, @xutao-wang 
Thanks for making those changes! Your package has been accepted. 
Don't forget to submit your analysis and graphing package when ready!
Best regards,
Marcel

**Comment by xutao-wang** [comment] 2021-10-07 17:46
Thank you for your help, Marcel! @LiNk-NY 

Best,
Xutao

**Comment by lshep** [comment] 2021-10-08 13:07
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/xutao-wang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("curatedTBData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/curatedTBData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-10-08 13:07 UTC
Labels: OK, 3a. accepted
