### ISSUE TITLE
netSmooth: A Network smoothing based method for Single Cell RNA-seq

### ISSUE THREAD

**Issue by jonathanronen** [Bioconductor/Contributions#603] opened 2018-01-08 14:56 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BIMSBbioinfo/netSmooth

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2018-01-08 15:06
Before your package can be added to the review queue, the vignette code chunks need to be 'live' (i.e., no `eval = FALSE`). Please update your repository, bump the package version (to 0.99.1) and confirm that the updated package conforms to Bioconductor guidelines for time and space. Please post a comment here when your package has been updated.

**Comment by jonathanronen** [comment] 2018-01-08 16:17
Thanks for the quick look, @mtmorgan. We made the vignette like this in order to speed up the check. This must be somewhat common in the bioconductor universe, as many packages have extensive vignettes which I find hard to imagine run in under 5 minutes. For instance, the DESeq2 vignette has a bunch of them [1], as does the methylKit vignette [2].

In this package as well, dealing with single cell rnaseq means the data matrices will be of certain size. Our vignette already uses a reduced size dataset, and reducing it further might make demonstrating some of the concepts of the package more challenging.

Would it be possible to reconsider this request?

[1]: https://raw.githubusercontent.com/Bioconductor-mirror/DESeq2/master/vignettes/DESeq2.Rmd
[2]: https://raw.githubusercontent.com/al2na/methylKit/master/vignettes/methylKit.Rmd

**Comment by mtmorgan** [comment] 2018-01-08 18:05
Your package must have the majority of code chunks (e.g., 80%) evaluated. Usually this involves identifying a realistic but trimmed data set that illustrates functionality in a timely fashion. That other packages no longer meet this requirement isn't justification for starting off on the wrong foot.

**Comment by jonathanronen** [comment] 2018-01-31 13:57
@mtmorgan Appologies for the hiatus. Requested changes have been made. Please have a look.
Thanks! J.

**Comment by mtmorgan** [comment] 2018-03-02 21:15
Please add a version bump and I'll review the package promptly.

**Comment by mtmorgan** [comment] 2018-03-19 20:57
DESCRIPTION

- Use Authors@R, rather than Author and Maintainer fields

NAMESPACE

- looks good

vignettes

- remove buildingPPIsFromStringDB.html and netSmoothIntro.html; these
  are created during the build process.
- Please spell-check, e.g., buildingPPIsFromStringDB.Rmd:21 'databse'
  --> database
  
R

- To make your code more robust, use `stopifnot()` or similar to check
  that each incoming argument matches expectation, e.g., netSmooth.R
  assert that `adjMatrix` is a matrix, of numeric value, with
  appropriate dimensions.
- use `message()` rather than `cat()` to communicate with users
  (everywhere but `show()` methods). No need to `message(paste(...))`,
  usually `message(...)` is sufficient (also for `stop()`, `warning()`).
- use `BiocParallel::bplapply()` rather the `mclapply()`, making sure
  your code works when using `SnowParam()` (separate processes, rather
  than processes sharing memory).
- Adopt a code formatting style that allows for longer lines and
  greater readability, e.g., using a consistent indent of 4 spaces

    ```
    scores <- unlist(mclapply(seq_len(length(smoothed.expression.matrices)),
                                      function(i) {
                                          x.sm <-
                                              smoothed.expression.matrices[[i]]
                  scoreSmoothing(x=x.sm,
                                 method=autoAlphaMethod,
                                 is.counts=is.counts,
                                 dimReduceFlavor=autoAlphaDimReduceFlavor, ...)
                                      },
                                      mc.cores=numcores))
    ```
    
  might become

    ```
    scores <- unlist(mclapply(
        seq_len(length(smoothed.expression.matrices)),
        function(i) {
            x.sm <- smoothed.expression.matrices[[i]]
            scoreSmoothing(
                x=x.sm, method=autoAlphaMethod, is.counts=is.counts,
                dimReduceFlavor=autoAlphaDimReduceFlavor, ...
            )
        }, mc.cores=numcores
    ))
    ```
    
- structure your code to test and fail early, reducing the need for complicated `if ()` statements deeper into the code, e.g.,

    ```
    stopifnot(is.numeric(alpha) || alpha == "auto")
    ```
- use the `@keyword internal` to mark functions that are not ment for end users.
- prefer vectorized functions over iterations wherever possible, e.g.,
  clusterExperimentWorkflow.R:58 can be constructed in vectorized
  calls outside the loop.
  
man

- provide more detail on how each data set (e.g., `human.ppi`) is
  obtained -- enough so that the curious user could reproduce the data
  themselves. I realize there are scripts in ./data-raw; the
  Bioconductor convention would have these as scripts in the
  `./inst/data-raw` directory, so that the scripts are available to
  the end user in the installed package; refer to these scripts in the
  man page, e.g., `system.file(package="netSmooth", "data-raw")`

**Comment by mtmorgan** [comment] 2018-04-03 19:47
Please respond within two weeks.

**Comment by jonathanronen** [comment] 2018-04-11 09:37
@mtmorgan thanks for the input! i've done the changes you suggested.

right now it seems the windows build is failing - this is following your request that I use `BiocParallel::bplapply` instead of `mclapply`.  Is this a problem with the windows build machine, or is there some other windows-specific configuration which is not well documented in BiocParallel?

**Comment by mtmorgan** [comment] 2018-04-11 11:58
Windows uses separate, completely independent, processes that do not share memory etc., whereas Linux / Mac do share memory. Likely what happens (I have not investigated closely) is that your function references symbols or data that are not available in the new process. You can likely see the problem on Linux / Mac by using a 'SnowParam()', e.g., `register(SnowParam())`. The solution is to write the bplapply functions so that they are provided, through arguments, with all the relevant data. If you point me to a simple reproducible example I can provide more concrete help.

**Comment by jonathanronen** [comment] 2018-04-12 11:37
That can't be it right now. The test that fails on the windows machine passes the linux/mac machines, and uses a SnowParam.
Here's the default parameter: https://github.com/BIMSBbioinfo/netSmooth/blob/master/R/netSmooth.R#L59

And the test which fails calls this function.

Any ideas?

**Comment by mtmorgan** [comment] 2018-04-14 16:25
I looked at your code a little bit.

Three things about BiocParallel. You need to either `register()` the BPPARAM or pass BPPARAM as an argument to bplapply. For single thread execution, its more efficient to use `SerialParam()`, otherwise, you'll pay the cost of loading your package on each worker, and of transmitting large data via socket connections to the workers.  If you're going to run multiple `bplappy()` in a single function call, then it's better to start the cluster at the top of the function, instead of (implicitly) on each call to `bplappy()`. So for your code

```
bpparam = BiocParallel::SerialParam()
...
if (!BiocParallel::bpisup(bpparam)) {
    bpstart(bpparam)
    on.exit(bpstop(bpparam), add=TRUE
}
...
smoothed.expression.matrices <- BiocParallel::bplapply(
                autoAlphaRange,
                function(a) {
                    smoothAndRecombine(x, adjMatrix, a,
                        normalizeAdjMatrix=normalizeAdjMatrix)
                }
            , BPPARAM = bpparam)
```

**Comment by jonathanronen** [comment] 2018-04-16 18:14
Thanks for the tip, @mtmorgan !
Are we all set?

**Comment by mtmorgan** [comment] 2018-04-16 18:40
Looks like there are addressable warnings

```
* checking dependencies in R code ... NOTE
package 'methods' is used but not declared
```
Use `Imports: methods` in the DESCRIPTION file, importing all or part of it in the NAMESPACE.

```
* checking R code for possible problems ... [17s] NOTE
netSmooth,matrix: no visible global function definition for 'bpstart'
netSmooth,matrix: no visible global function definition for 'bpstop'
Undefined global functions or variables:
  bpstart bpstop
```
These should be resolved `BiocParallel::bpstart()` or `importFrom(BiocParallel, bpstart, bpstop)` in the NAMESPACE. BiocParallel should be in the Suggests: field of the DESCRIPTION file (for BiocParallel:: solution) or `Imports:` (for `importFrom(...)` soluion).

**Comment by mtmorgan** [comment] 2018-04-22 16:55
Still seem like there are warnings that can be addressed
```
* checking DESCRIPTION meta-information ... NOTE
Package listed in more than one of Depends, Imports, Suggests, Enhances:
  knitr
A package should be listed in only one of these fields.
```
List it only in Suggests: 
```
* checking top-level files ... NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.
```
The DESCRIPTION file says that the package is licensed under Artistic-2.0. The included LICENSE file is GPL-3. Please choose a single license. Either way, R contains copies of the Artistic-2.0 and GPL-3 license, so a LICENSE file is not required.
```
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: methods
  All declared Imports should be used.
```
The DESCRIPTION file has `Imports: methods` but the NAMESPACE does not mention the methods package. If you use functions from the methods package, add `import(methods)` to the NAMESPACE file.

**Comment by jonathanronen** [comment] 2018-04-25 13:41
thanks again, @mtmorgan . hope that was OK to meet the deadline!

**Comment by mtmorgan** [comment] 2018-04-25 13:56
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jonathanronen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"netSmooth\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/netSmooth

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-04-25 13:56 UTC
Labels: 3a. accepted, WARNINGS
