### ISSUE TITLE
rawDiag

### ISSUE THREAD

**Issue by cpanse** [Bioconductor/Contributions#3251] opened 2023-12-06 15:11 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to Bioconductor

-    Repository: https://github.com/cpanse/rawDiag

Confirm the following by editing each check box to '[x]'

    [x] I understand that by submitting my package to Bioconductor,
    the package source and all review commentary are visible to the
    general public.

    [x] I have read the Bioconductor [Package Submission](https://bioconductor.org/developers/package-submission/)
    instructions. My package is consistent with the Bioconductor
    [Package Guidelines](https://contributions.bioconductor.org/).

    [x] I understand Bioconductor [Package Naming Policy](https://bioconductor.org/developers/package-submission/#naming) and acknowledge
    Bioconductor may retain use of package name.

    [x ] I understand that a minimum requirement for package acceptance
    is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS.
    Passing these checks does not result in automatic acceptance. The
    package will then undergo a formal review and recommendations for
    acceptance regarding other Bioconductor standards will be addressed.

    [ x] My package addresses statistical or bioinformatic issues related
    to the analysis and comprehension of high throughput omics data.

    [ x] I am committed to the long-term maintenance of my package. This
    includes monitoring the [support site](https://support.bioconductor.org/) for issues that users may
    have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
    of developments in the Bioconductor community, responding promptly
    to requests for updates from the Core team in response to changes in
    R or underlying software.

    [x ] I am familiar with the [Bioconductor code of conduct](https://bioconductor.org/about/code-of-conduct/) and
    agree to abide by it.

I am familiar with the essential aspects of Bioconductor software
management, including:

    [x] The 'devel' branch for new packages and features.
    [x] The stable 'release' branch, made available every six
    months, for bug fixes.
    [x] Bioconductor version control using [Git](http://bioconductor.org/developers/how-to/git/)
    (optionally [via GitHub](http://bioconductor.org/developers/how-to/git/sync-existing-repositories/)).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website](https://bioconductor.org/) to sign up.

**Comment by lshep** [comment] 2023-12-11 13:56
It looks like the set up for the rawrr package needs to be run in order to use your package.  I highly suggest referencing the `https://github.com/fgcz/rawrr/blob/devel/INSTALL`  in an INSTALL file of your own and making note of it perhaps in the package level man page?

**Comment by lshep** [comment] 2023-12-11 14:03
I ran 
```
rawrr::installRawFileReaderDLLs()
rawrr::installRawrrExe()
```
and when I still try to build your package locally I am getting an ERROR

```
lorikern@jbcj433:~/PkgReview$ R CMD build rawDiag 
* checking for file 'rawDiag/DESCRIPTION' ... OK
* preparing 'rawDiag':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘rawDiag.Rmd’ using rmarkdown
trying URL 'https://bioconductor.org/packages/3.19/data/experiment/src/contrib/tartare_1.17.0.tar.gz'
Content type 'application/x-gzip' length 314914 bytes (307 KB)
==================================================
downloaded 307 KB

* installing *source* package ‘tartare’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tartare)

The downloaded source packages are in
	'/tmp/RtmpzC3q1y/downloaded_packages'

Quitting from lines 65-68 [readOrbitrap] (rawDiag.Rmd)
Error: processing vignette 'rawDiag.Rmd' failed with diagnostics:
no lines available in input
--- failed re-building ‘rawDiag.Rmd’

SUMMARY: processing the following file failed:
  ‘rawDiag.Rmd’

Error: Vignette re-building failed.
Execution halted
```

**Comment by cpanse** [comment] 2023-12-11 15:34
Dear @lshep,

I added an INSTALL file; SystemRequirements @DESCRIPTION and a note in the ?rawDiag man page.
https://github.com/cpanse/rawDiag/commit/7db172841ef420168ced14f48578bfdca8825ebd
C

**Comment by lshep** [comment] 2023-12-11 16:17
I still get an ERROR when I try to build locally but I'll pass it into the build system for now and see if it reproduces there.

**Comment by cpanse** [comment] 2023-12-11 16:58
@lshep OK;  I copied the part from the MsBackendRawFileReader vignette. Thanks, Christian

**Comment by lshep** [comment] 2023-12-27 14:52
Please fix all ERROR, Warning, Notes before a reviewer is assigned for an in depth review. thank you

**Comment by cpanse** [comment] 2023-12-27 15:01
@lshep; I don’t know how to fix the error. One way is that rawrr is working (meaning having all the libraries installed) or I need to fetch the proprietary vendor libraries when rendering the vignette. Thanks and best wishes, C

**Comment by cpanse** [comment] 2024-01-09 06:56
`ERROR: Subscribe to the Bioc-devel mailing list by going to`  I get emails sent to bioc-devel@r-project.org

**Comment by lshep** [comment] 2024-01-09 13:10
We can ignore this error for now as there seems to be an issue with the BiocCheck for the bioc-devel mailing list.  I did confirm you are registered.  Is there a way to reduce the package size as there is still a warning concerning package size?

**Comment by cpanse** [comment] 2024-01-09 15:05
Dear @lshep; I could reduce the output of the vignette. Thanks, Christian

**Comment by lazappi** [comment] 2024-02-09 16:56
Hi @cpanse

Thanks for submitting **rawDiag** :tada:! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: Please address notes from `R CMD build`
- [ ] :warning: Please address notes and warnings from `BiocCheck::BiocCheck()`
  - Specifically the `WARNING` about using `.Deprecated`
- [ ] :warning: Please address notes from `R CMD check`
  - The check failed for me locally. If it passes on the build system it's probably fine though.

## NAMESPACE file

- [ ] :rotating_light: Please rename `read.raw` to be consistent with the other functions

## The NEWS file

- [ ] :green_circle: Remember to update the NEWS file when you make changes to the package

## Documentation

### Vignette

- [ ] :rotating_light: Please add an *Introduction* section. This should:
  - [ ] Introduce your package
  - [ ] Include motivation for inclusion in Bioconductor
  - [ ] Include comparison to similar packages (if applicable)
- [ ] :rotating_light: Please add an *Installation* section that includes:
  - [ ] Bioconductor installation instructions (not evaluated)
  - [ ] Instructions for installing additional system dependencies
- [ ] :warning: The vignette is very brief, I think it can be expanded to better explain the package and its functionality
- [ ] :warning: In general `echo = TRUE` is preferred in vignettes to show the code that is being run
- [ ] :rotating_light: Please remove commented code that isn't run
- [ ] :green_circle: I got an error when I tried to run the plotting chunk:

  ```r
  Error in `ggplot()`:
  ! `mapping` should be created with `aes()`.
  ✖ You've supplied a <character> object
  ```

### Man pages

- [ ] :warning: It is recommended to add a package man page
- [ ] :green_circle: I noticed some unrendered code in the documentation, you might want to check what the rendered output looks like

## Unit tests

- [ ] :warning: The `context()` function is superseded in recent **{testthat}** versions
- [ ] :warning: The tests can be better organised into files for different parts of the package, usually they match the structure of the `R/` directory
- [ ] :warning: The current tests are minimal, please consider adding more tests

## Code

### R

- [ ] :rotating_light: Using `paste` in `message()`, `warning()`, `stop()` is not needed
- [ ] :warning: Consider adding checks that function arguments are valid
  - For several of the function you could easily use `match.arg`
- [ ] :rotating_light: Parallelisation should use the `BiocParallel` package
- [ ] :rotating_light: Please remove commented code that isn't used
- [ ] :warning: The name of the `shiny()` function is very generation, I would recommend changing it to something more specific to the package
- [ ] :warning: I'm not sure about the need for the `appDir` argument in the `shiny()` function, I don't think a user would ever need to set this
- [ ] :warning: It might be better not to have a default value for the `rawDir` argument in the `shiny()` function. The default value is unlikely to work for most users and making it required would be clearer.
- [ ] :rotating_light: Please give the `.f()` function a more descriptive name

### Third-party code

- [ ] :rotating_light: Please check the inclusion of third-party code follows the [guidelines](https://contributions.bioconductor.org/third-party-code.html)

**Comment by cpanse** [comment] 2024-02-15 14:28
Dear @lazappi; thanks for your work. I really appreciate it.

Please find my comments (Version: 0.99.23) below:

> Hi @cpanse
> 
> Thanks for submitting **rawDiag** 🎉! Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.
> 
> **What next?**
> 
> Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses. You can use the "Quote reply" option in the `...` menu on this comment to reply directly to my points below.
> 
> Luke
> # Review
> 
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> ## General package development
> 
>     * [X]  ⚠️ Please address notes from `R CMD build`
seems to be fine
> 
>     * [X]  ⚠️ Please address notes and warnings from `BiocCheck::BiocCheck()`
Zero warnings; notes are in progress. BiocCheck::BiocCheck() is very sensitive
>       
>       * Specifically the `WARNING` about using `.Deprecated`
The package has been used for a while (2017) see github.com/fgcz/rawDiag
so I have to deal with the situation. 
> 
>     * [X]  ⚠️ Please address notes from `R CMD check`
fix that
>       
>       * The check failed for me locally. If it passes on the build system it's probably fine though.
> 
> 
> ## NAMESPACE file
> 
>     * [X]  🚨 Please rename `read.raw` to be consistent with the other functions
done. its renamed to `readRaw`
> 
> 
> ## The NEWS file
> 
>     * [X]  🟢 Remember to update the NEWS file when you make changes to the package
done
> 
> 
> ## Documentation
> ### Vignette
> 
>     * [X]  🚨 Please add an _Introduction_ section. This should:
>       
>       * [X]  Introduce your package
>       * [x]  Include motivation for inclusion in Bioconductor
>       * [x]  Include comparison to similar packages (if applicable)
> 
>     * [X]  🚨 Please add an _Installation_ section that includes:
>       
>       * [x]  Bioconductor installation instructions (not evaluated)
>       * [x]  Instructions for installing additional system dependencies
> 
>     * [ ]  ⚠️ The vignette is very brief, I think it can be expanded to better explain the package and its functionality
> 
>     * [x]  ⚠️ In general `echo = TRUE` is preferred in vignettes to show the code that is being run
> 
>     * [x]  🚨 Please remove commented code that isn't run
> 
>     * [ ]  🟢 I got an error when I tried to run the plotting chunk:
>       ```r
>       Error in `ggplot()`:
>       ! `mapping` should be created with `aes()`.
>       ✖ You've supplied a <character> object
>       ```

I can not reproduce the error.

> 
> 
> ### Man pages
> 
>     * [ ]  ⚠️ It is recommended to add a package man page

It is a great idea; I am worried that I duplicate my vignette text. I am happy to write a package man page if you have a good package as a template example.

> 
>     * [ ]  🟢 I noticed some unrendered code in the documentation, you might want to check what the rendered output looks like
> 
> 
> ## Unit tests
> 
>     * [x]  ⚠️ The `context()` function is superseded in recent **{testthat}** versions
> 
>     * [x]  ⚠️ The tests can be better organised into files for different parts of the package, usually they match the structure of the `R/` directory
> 
>     * [ ]  ⚠️ The current tests are minimal, please consider adding more tests
work in progress.
> 
> ## Code
> ### R
> 
>     * [x]  🚨 Using `paste` in `message()`, `warning()`, `stop()` is not needed
done as much as possible
> 
>     * [ ]  ⚠️ Consider adding checks that function arguments are valid
I added issue: https://github.com/cpanse/rawDiag/issues/1 
will follow up later
>       
>       * For several of the function you could easily use `match.arg`
> 
>     * [x]  🚨 Parallelisation should use the `BiocParallel` package

done

>     * [x]  🚨 Please remove commented code that isn't used

should be done

>     * [x]  ⚠️ The name of the `shiny()` function is very generation, I would recommend changing it to something more specific to the package

I refactored the shiny application as documented here https://contributions.bioconductor.org/shiny.html

> 
>     * [x]  ⚠️ I'm not sure about the need for the `appDir` argument in the `shiny()` function, I don't think a user would ever need to set this

I removed the parameter appDir. Good point.

> 
>     * [ ]  ⚠️ It might be better not to have a default value for the `rawDir` argument in the `shiny()` function. The default value is unlikely to work for most users and making it required would be clearer.

I have to think about it. 

> 
>     * [x]  🚨 Please give the `.f()` function a more descriptive name
removed the code 
> 
> 
> ### Third-party code
> 
>     * [x]  🚨 Please check the inclusion of third-party code follows the [guidelines](https://contributions.bioconductor.org/third-party-code.html)

This is a crucial point. Luckily, it is solved and handled by the https://bioconductor.org/packages/rawrr/ package.

C

**Comment by lazappi** [comment] 2024-02-23 08:58
> > ```
> > * [X]  ⚠️ Please address notes and warnings from `BiocCheck::BiocCheck()`
> > ```
> 
> Zero warnings; notes are in progress. BiocCheck::BiocCheck() is very sensitive

You are right, it is quite sensitive and some things about line lengths etc. are ok to ignore but there are others that would be easy to address.

> > ```
> >   * Specifically the `WARNING` about using `.Deprecated`
> > ```
> 
> The package has been used for a while (2017) see github.com/fgcz/rawDiag so I have to deal with the situation.

It looks like this warning is gone now so I guess you addressed it somehow?
 
> > ## Documentation
> > ### Vignette
> > ```
> > * [X]  🚨 Please add an _Introduction_ section. This should:
> >   
> >   * [X]  Introduce your package
> >   * [x]  Include motivation for inclusion in Bioconductor
> >   * [x]  Include comparison to similar packages (if applicable)

This is great, thanks!

> > * [X]  🚨 Please add an _Installation_ section that includes:
> >   
> >   * [x]  Bioconductor installation instructions (not evaluated)
> >   * [x]  Instructions for installing additional system dependencies

The instructions for the dependencies are great but you are still missing the instructions for installing the package itself with **{BiocManager}**.

> > * [ ]  ⚠️ The vignette is very brief, I think it can be expanded to better explain the package and its functionality

The vignette still needs more description of the functionality. The rendered vignette shows all the plots but there isn't any information about how to use/interpret them. It would also be good to describe the Shiny app.

Also, I think at least one plot gave a message about a dependency not being installed. Please make sure all the required packages are listed somewhere in `DESCRIPTION`.

> > * [x]  ⚠️ In general `echo = TRUE` is preferred in vignettes to show the code that is being run

`echo = FALSE` is still set on some chunks

> > * [x]  🚨 Please remove commented code that isn't run

There is still commented code in the vignette

> > * [ ]  🟢 I got an error when I tried to run the plotting chunk:
> >   ```r
> >   Error in `ggplot()`:
> >   ! `mapping` should be created with `aes()`.
> >   ✖ You've supplied a <character> object
> >   ```
> > ```
> 
> I can not reproduce the error.

This worked fine now, not sure what the issue was

> > ### Man pages
> > ```
> > * [ ]  ⚠️ It is recommended to add a package man page
> > ```
> 
> It is a great idea; I am worried that I duplicate my vignette text. I am happy to write a package man page if you have a good package as a template example.

You can use [`usethis::use_package_doc()`](https://usethis.r-lib.org/reference/use_package_doc.html) to create an automatically generated one but it's not a big deal so up to you.

> > ```
> > * [ ]  🟢 I noticed some unrendered code in the documentation, you might want to check what the rendered output looks like
> > ```

This is still there in the references section for `readRaw()`

> > * [ ]  ⚠️ The current tests are minimal, please consider adding more tests
> > ```
> 
> work in progress.

👍🏻 It would be great if you could add more

> > ## Code
> > ### R
> > ```
> > * [x]  🚨 Using `paste` in `message()`, `warning()`, `stop()` is not needed
> > ```
> 
> done as much as possible

I think this could be removed in the the message in the vignette

> > * [x]  🚨 Parallelisation should use the `BiocParallel` package
> > ```
> 
> done

Thanks! Usually I would say there should be a `BPPARAM` argument that lets the user specify how parallel processing is done but I'm not sure how that would work inside a Shiny app.

> > ```
> > * [ ]  ⚠️ It might be better not to have a default value for the `rawDir` argument in the `shiny()` function. The default value is unlikely to work for most users and making it required would be clearer.
> > ```
> 
> I have to think about it.

Up to you but I do think it would avoid issues for uses and it's not much extra work for people to need to set the directory

**Comment by cpanse** [comment] 2024-02-28 10:55
Dear @lazappi ; 

thanks again for you feedback.

> > > ```
> > > * [X]  ⚠️ Please address notes and warnings from `BiocCheck::BiocCheck()`
> > > ```
> > 
> > 
> > Zero warnings; notes are in progress. BiocCheck::BiocCheck() is very sensitive
> 
> You are right, it is quite sensitive and some things about line lengths etc. are ok to ignore but there are others that would be easy to address.
> 
> > > ```
> > >   * Specifically the `WARNING` about using `.Deprecated`
> > > ```
> > 
> > 
> > The package has been used for a while (2017) see github.com/fgcz/rawDiag so I have to deal with the situation.
> 
> It looks like this warning is gone now so I guess you addressed it somehow?
I added .Deprecated to Rbuildignore.
> 
> > > ## Documentation
> > > ### Vignette
> > > ```
> > > * [X]  🚨 Please add an _Introduction_ section. This should:
> > >   
> > >   * [X]  Introduce your package
> > >   * [x]  Include motivation for inclusion in Bioconductor
> > >   * [x]  Include comparison to similar packages (if applicable)
> > > ```
> 
> This is great, thanks!
> 
> > > * [x]   🚨 Please add an _Installation_ section that includes:
> > >   
> > >   * [x]   Bioconductor installation instructions (not evaluated)
> > >   * [x]   Instructions for installing additional system dependencies
> 
> The instructions for the dependencies are great but you are still missing the instructions for installing the package itself with **{BiocManager}**.

Added a paragraph (assuming it is going to be on Bioconductor).

> 
> > > * [ ]   ⚠️ The vignette is very brief, I think it can be expanded to better explain the package and its functionality
> 
> The vignette still needs more description of the functionality. The rendered vignette shows all the plots but there isn't any information about how to use/interpret them. It would also be good to describe the Shiny app.

I added an more text and an other example data set.

> 
> Also, I think at least one plot gave a message about a dependency not being installed. Please make sure all the required packages are listed somewhere in `DESCRIPTION`.

should be the case. 

> 
> > > * [x]   ⚠️ In general `echo = TRUE` is preferred in vignettes to show the code that is being run
> 
> `echo = FALSE` is still set on some chunks
> 
> > > * [x]   🚨 Please remove commented code that isn't run
> 
> There is still commented code in the vignette

OK; found and removed it. I double checked. I hope it is fixed.

> 
> > > * [ ]   🟢 I got an error when I tried to run the plotting chunk:
> > >   ```r
> > >   Error in `ggplot()`:
> > >   ! `mapping` should be created with `aes()`.
> > >   ✖ You've supplied a <character> object
> > >   ```
> > 
> > 
> > I can not reproduce the error.
ack.
> 
> This worked fine now, not sure what the issue was
> 
> > > ### Man pages
> > > ```
> > > * [ ]  ⚠️ It is recommended to add a package man page
> > > ```
> > 
> > 
> > It is a great idea; I am worried that I duplicate my vignette text. I am happy to write a package man page if you have a good package as a template example.
> 
> You can use [`usethis::use_package_doc()`](https://usethis.r-lib.org/reference/use_package_doc.html) to create an automatically generated one but it's not a big deal so up to you.

OK;  I know how to technical do that but it needs to be filled with content easy to maintain.

> 
> > > ```
> > > * [ ]  🟢 I noticed some unrendered code in the documentation, you might want to check what the rendered output looks like
> > > ```
> 
> This is still there in the references section for `readRaw()`
> 
> > > * [ ]   ⚠️ The current tests are minimal, please consider adding more tests

This seems to be a bug in RStudio. It looks great in my Linux|Mac terminal. However, using the latest roxygen2 (7.3.1), RStudio renders the reference the right way.

> > 
> > 
> > work in progress.
> 
> 👍🏻 It would be great if you could add more

I added some shinyModule test cases.  Testing the visual output failed. 

> 
> > > ## Code
> > > ### R
> > > ```
> > > * [x]  🚨 Using `paste` in `message()`, `warning()`, `stop()` is not needed
> > > ```
> > 
> > 
> > done as much as possible
> 
> I think this could be removed in the the message in the vignette

I found it and removed it. tnx.

> 
> > > * [x]   🚨 Parallelisation should use the `BiocParallel` package
> > 
> > 
> > done
> 
> Thanks! Usually I would say there should be a `BPPARAM` argument that lets the user specify how parallel processing is done but I'm not sure how that would work inside a Shiny app.

Yes; I have the same thoughts.

> 
> > > ```
> > > * [ ]  ⚠️ It might be better not to have a default value for the `rawDir` argument in the `shiny()` function. The default value is unlikely to work for most users and making it required would be clearer.
> > > ```
> > 
> > 
> > I have to think about it.
> 
> Up to you but I do think it would avoid issues for uses and it's not much extra work for people to need to set the directory

Now I got it. Good point; I changed the default to the rawrr sample directory, which should always work for every user.
Also, I added the `~/Download` folder example to the man page. 

Thanks again and best wishes, 
Christian

**Comment by lazappi** [comment] 2024-03-01 08:42
> > Also, I think at least one plot gave a message about a dependency not being installed. Please make sure all the required packages are listed somewhere in `DESCRIPTION`.
> 
> should be the case.

I still see this warning in the vignette:

```r
## Warning: Computation failed in `stat_binhex()`.
## Caused by error in `compute_group()`:
## ! The package "hexbin" is required for `stat_bin_hex()`.
```

> > > > * [ ]  ⚠️ It is recommended to add a package man page
> > > > ```
> > > 
> > > 
> > > It is a great idea; I am worried that I duplicate my vignette text. I am happy to write a package man page if you have a good package as a template example.
> > 
> > 
> > You can use [`usethis::use_package_doc()`](https://usethis.r-lib.org/reference/use_package_doc.html) to create an automatically generated one but it's not a big deal so up to you.
> 
> OK; I know how to technical do that but it needs to be filled with content easy to maintain.

The function I suggested creates a special file that automatically generates the package man page when the documentation is built (mostly from the `DESCRIPTION`). So other than running the function once you don't have to do/maintain anything. Just wanted to clarify, but still totally up to you.

> > > > ```
> > > > * [ ]  🟢 I noticed some unrendered code in the documentation, you might want to check what the rendered output looks like
> > > > ```
> > 
> > 
> > This is still there in the references section for `readRaw()`
> > > > * [ ]    ⚠️ The current tests are minimal, please consider adding more tests
> 
> This seems to be a bug in RStudio. It looks great in my Linux|Mac terminal. However, using the latest roxygen2 (7.3.1), RStudio renders the reference the right way.

Uh, ok. That's fine then.

> > > > * [x]    🚨 Parallelisation should use the `BiocParallel` package
> > > 
> > > 
> > > done
> > 
> > 
> > Thanks! Usually I would say there should be a `BPPARAM` argument that lets the user specify how parallel processing is done but I'm not sure how that would work inside a Shiny app.
> 
> Yes; I have the same thoughts.

I guess maybe the user could pass it to the function that creates the app? Or maybe it is worth pointing to the **{BiocParallel}** docs which explain how to register a backend that you then use in the app?

I think it would be great if you can follow up on these last points but I don't think any of them are important enough to hold up the package so I will approve what you have now.

**Comment by lazappi** [comment] 2024-03-01 08:43
Congratulations on getting **{rawDiag}** into Bioconductor :tada:! It can take a few days to be picked up by the build system but then it should be available in Bioconductor devel and the next release.

**Comment by lshep** [comment] 2024-03-04 13:12
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cpanse.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("rawDiag")`. The package 'landing page' will be created at

https://bioconductor.org/packages/rawDiag

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-03-04 13:12 UTC
Labels: OK, 3a. accepted
