### ISSUE TITLE
gep2pep

### ISSUE THREAD

**Issue by franapoli** [Bioconductor/Contributions#528] opened 2017-10-11 10:32 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/franapoli/gep2pep

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2017-10-11 11:03
Make sure your package interfaces with (accepts as arguments / returns as values) relevant Bioconductor objects, including those from the GSEABase and SummarizedExperiment packages. Can you re-use our existing infrastructure for annotation, especially Organism.dplyr?

**Comment by franapoli** [comment] 2017-10-11 13:50
@mtmorgan thanks for the comment, I'm now working on it. The package does not use standard assays so I did not include Bioconductor classes I knew of, but I should be able to support some of the GSEABase and Organism.dplyr classes as inputs and SummarizedExperiment as outputs in the next commit.

**Comment by lshep** [comment] 2017-10-11 13:54
Also Please make sure your webhook is initialized as described in the link above.  Before your next version bump, please also sign up for the mailing list: 

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by lawremi** [comment] 2017-10-11 17:31
I'm pretty sure you could use SummarizedExperiment for the input gene expression profiles. There is nothing that says that SE must contain sample-level data.

**Comment by franapoli** [comment] 2017-10-11 17:40
@lawremi thanks, I will look into that too.

**Comment by franapoli** [comment] 2017-10-18 14:54
Hi,

as suggested, this version improved integration with Bioconductor existing packages.

In particular, this version supports GeneSet objects from the GSEABase throughout the package functionalities. The user can provide GeneSetCollection objects and the data are also internally stored in that format. This was quite an effort and I even derived a new class from GeneSetCollection in order to support BroadCollection-like objects without naming constraints (I use categories and subcategories, but I need to freely choose their names). I think this was a nice improvement overall.

Concerning the SummarizedExperiment class, I considered it thoroughly, and even wrote the code to convert some gep2pep matrices to SE, but in the end I commented it out and dropped the idea. Gep2pep takes a gene expression profiles matrix and converts it to pathway-based data using different databases of pathways. This means that, using for example MSigDB, the tool builds 24 different versions of the transcriptional data, that can not be modeled as assays of the same SE (they have same columns but different rows). Attaching same meta-data to all columns would be quite a waste. On the other hand, metadata for the rows are gene sets. To attach them as rowData I should first convert them back to data.frame-s, which is actually the original format that I just moved from to support GSEABase objects. In the end, I could get an SE in input, but I would just extract the data matrix and strip all the rest, giving the false impression of supporting something that in practice I'm not. Analogous reasons made me drop the class as an output format. My idea is that since our package implements rather non-standard pipelines it would require more generic classes than SE as it is now.

Finally, I looked into Organism.dplyr, but I'm not using any of its functionalities. It could be useful to build gene sets, but the package expects gene sets to have been defined in advance.

Thanks again for the comments.

**Comment by lawremi** [comment] 2017-10-18 15:29
I think MultiAssayExperiment would handle the multiple feature set problem. To hold gene set features you could extend SE like RangedSummarizedExperiment did, adding a gene set object instead of ranges. That would be a very useful contribution but maybe @mtmorgan should weigh-in as the GSEABase guy.

**Comment by franapoli** [comment] 2017-10-19 09:25
Thank you @lawremi, I'm looking into MAE and it seems it could theoretically cover my case. However, I have been looking for a lazy-loading feature, but it seems it is not supported, meaning that one has to load all assay data matrices at ones. In our case that would be impossible, this is why we are storing each data matrix into a separate file going through the hassle of managing that. BTW, if I'm correct that this feature does not exist, it would be great to work on it (I mean, not for this package, it would take too long!).

**Comment by vjcitn** [comment] 2017-10-19 10:51
MultiAssayExperiment can be defined for constituent experiments satisfying
fairly simple APIs.  If numerical data matrices are the issue, HDF5Array
representations
could help achieve the desired laziness (and more).  For other data types,
rhdf5 or ff may be used.

**Comment by lawremi** [comment] 2017-10-19 10:56
As Vince just mentioned, the MultiAssayExperiment vignettes should make mention somewhere of using the DelayedArray package to achieve lazy loading. Currently, there is a backend for HDF5. You probably have a different format, but implementing new DelayedArray backends is supposed to be easy. Or, you might just want to switch to HDF5.

**Comment by franapoli** [comment] 2017-10-19 11:20
[Here](http://bioconductor.org/packages/release/bioc/vignettes/MultiAssayExperiment/inst/doc/UsingHDF5Array.html) is the dedicated vignette, this is exactly what I was talking about. I will look into it, thanks.

**Comment by lshep** [comment] 2017-11-10 19:40
Just checking in, were you making any more updates or should I review the package?

**Comment by franapoli** [comment] 2017-11-10 19:58
Hi Ishep,

I'm trying to follow the suggestions I received, but that about using the
SummarizedExperiment class proved to be quite a challenge for my case. I've
been asking to the bioc-devel mailing list and it seems I should model my
data as a rather complex MultiAssayExperiment also using a custom
DelayedMatrix backend, with the available documentation about this last
step being rather fragmented. Since I don't work full time on this, it is
taking long.

Maybe a more affordable solution could be to stick with the current version
and add SE support in subsequent releases, which would not break
compatibility anyway.

What do you think?

Thank you for checking,
Francesco

Il 10 nov 2017 20:40, "lshep" <notifications@github.com> ha scritto:

Just checking in, were you making any more updates or should I review the
package?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Bioconductor/Contributions/issues/528#issuecomment-343567073>,
or mute the thread

**Comment by LiNk-NY** [comment] 2017-11-10 20:58
Ciao Francesco, @franapoli 

I am interested in hearing how the documentation for this last step is "fragmented."
If something is not clear or lacking in the documentation, I invite you to open an 
issue at https://github.com/waldronlab/MultiAssayExperiment/issues. Thanks.

Regards,
Marcel

**Comment by franapoli** [comment] 2017-11-10 21:06
Hi Marcel,

By "last step" I was referring to the creation of a custom backend for DelayedArray, as discussed on the mailing list with the author.

My best,
Francesco

Il giorno 10 nov 2017, alle ore 21:58, Marcel Ramos <notifications@github.com> ha scritto:

Ciao Francesco, @franapoli

I am interested in hearing how the documentation for this last step is "fragmented."
If something is not clear or lacking in the documentation, I invite you to open an
issue at https://github.com/waldronlab/MultiAssayExperiment/issues. Thanks.

Regards,
Marcel

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

Il giorno 10 nov 2017, 21:58, alle ore 21:58, Marcel Ramos <notifications@github.com> ha scritto:

**Comment by vjcitn** [comment] 2017-11-10 21:14
I don't know what aspect of your package is being held up by DelayedArray
deployability
for backends other than RAM/HDF5 on disk, but we should try to make
progress on some examples.
@petehaitch has made some progress, if I understand correctly.
 Independently, when I last looked I felt
there was a little progress in the vjcitn/RemoteArray code ... but I have
been swamped with
course preparations.  What is the backend you need to handle through this
interface?

**Comment by franapoli** [comment] 2017-11-11 19:02
Actually I just need to make an RDS backend: when the user accesses the matrix, the whole matrix is loaded from an RDS file. I just need to avoid to load all the matrices (assays) together. We use the [repo package](https://cran.r-project.org/package=repo) to manage files (I need to maintain this compatibility), but once I have an RDS backend it should be easy to go through the repo's layer (which uses RDS).

For additional details about what I'm doing, find below an excerpt from the mailing list.

----------
>> On Oct 24, 2017 6:14 AM, "Francesco Napolitano" <franapoli@gmail.com> wrote:
>>
>> I'm converting gene expression profiles to "pathway expression
>> profiles" (https://doi.org/10.1093/bioinformatics/btv536), so for each
>> pathway I have an enrichment score and a p-value. I guess it would be
>> like modeling gene expression data where limma-like preprocessing was
>> performed, so you have a fold change - p-value pair for each gene.
>> Isn't there a data model for that?

> Nice paper, thanks for the link! Could you explain the problem a little more
> using the terminology of your paper? I see your enrichment values matrix
> (fig 1c ESij) of pathways x cell lines, and imagine additional associated
> matrices of p-values and ranks, but where do assays with different rows come
> in?

Fig 1 shows the pipeline for a single database of pathways, but we
used 10 different databases (GO, KEGG, Reactome...). Currently we use
all of MSigDB, which includes 24 subcategories, and we have a matrix
of ES and a matrix of pvalues for each. You always have the same drugs
over columns, but different pathways over rows. Keeping them separated
is necessary (you don't want to rank pathways across unrelated
databases). On the other hand, if I build one SummarizedExperiment for
each database, I have to replicate the common metadata across all of
them, and also lose most of the features that going through the burden
of modeling my data with SE were all about :-/.

**Comment by vjcitn** [comment] 2017-11-11 21:54
I have just had a look through your vignette, along with the "repo"
vignette, which is very interesting.

I think one basic question is how to establish a relationship between your
repo
concept and other integrative containers in Bioconductor.  If you already
have sufficient control over memory footprint
through the "repo" design, the DelayedArray concept does not seem too
critical to adopt.  The scope of
the repo container is broad -- managing gene set collections, results of
pathway analyses, and, in practice, likely
much more as the analysis proceeds.  There are no analogs to this in
Bioconductor infrastructure that I know of.

One place where Bioc design would likely be useful is in the entity called
'geps' in the vignette, which is a naked
matrix of ranks for different conditions.  A SummarizedExperiment makes
sense there, and if you have many conditions
(thousands?) the HDF5-backed SummarizedExperiment could be useful.
buildPEPs could then be defined for
a SummarizedExperiment and could propagate metadata that are usefully bound
into the SummarizedExperiment.

One other question I have is whether it could make sense to define an
interface to the repo that implements the
endomorphism idiom X[G, S], where G is some feature selection and S is some
condition selection.  We often use
this; I noted that CondSEA asks for a vector of conditions as its second
argument.

In the end I think the package should be reviewed without requiring an
attack on the DelayedArray extension.
You could likely use HDF5 through the repo when needed.

**Comment by lawremi** [comment] 2017-11-12 00:11
RDS is not a suitable file format for DelayedArray, because there is no random access, at least not when compressed. I fail to see how this repo package has anything to do with out of core implementation of large matrices.

**Comment by vjcitn** [comment] 2017-11-12 01:33
I would agree.  To the extent that any out-of-memory representation is
needed, it is available from existing infrastructure.
There is an as yet unaddressed role for SummarizedExperiment structures,
for which out-of-memory assay management
is straightforward, and other matrix structures of the package should be
able to use DelayedArray as needed.

**Comment by lawremi** [comment] 2017-11-12 05:50
If there are multiple feature sets sharing the same set of samples, then it makes sense to use an MAE. A DelayedArray backend on top of RDS (a single, delayed complete read) might actually make sense in circumstances like this.

**Comment by lshep** [comment] 2017-11-20 14:58
Hi @franapoli 

I agree that we can move on with the intention of adding SE or MAE support in subsequent releases. Please see other comments to address. 


**VIGNETTE**

It seems like the user would benefit from having some accessor methods. 
e.g `description(rp$get("c3_TFT_sets")[["E47_01"]])`
This seems a little messy. As stated rp$get is a repo command so can you create some helpers and a wrapper around it? perhaps something to list options for potential arguments to rp$get() and [[ and then a wrapper that would plug these arguments into that statement? 
Similarly:
`rp$get("c3_TFT")$ES[1:3, 1:3]`
If you know that there are ES and PV matricies, create an accessor method for the output if they would be of potential use to the user. 
And also:
Accessors for CondSEA and details matricies for condition-set enrichment analysis and PathSEA and details for pathway-set enrichment. 

REAL world example : (while not eval i ran for reproducibility) 
Change in untar and openRepository: Cmap_MsigDB_v6.1_PEPs.tar.gz  (capitalization of s)

Side: 
Well done on output produced. I like the status messages for steps throughout running the functions. 
Thank you for the real world example. 

**INST:** 
We encourage data to be organized into an inst/extdata directory. Please move the RDS files into extdata subdirectory (and update system.file calls in vignette or man appropriately). 


**R CODE:** 

throughout code: 
Write seq_len(n) or seq_along(x) rather than 1:n or 1:length(x). This protects against the case when n or length(x) is 0 (which often occurs as an unexpected ‘edge case’ in real code) or negative.

dummyFunction
If this is needed maybe mark as keyword(internal) or remove the man file since it will not be referenced by the user (similarly for any other internal functions)

Please comment back here when updates are pushed with what has been addressed. 
Thank you for your interest in Bioconductor.

**Comment by franapoli** [comment] 2017-11-21 00:09
Hi @lshep 

I just pushed a new version following your comments, as follows:

> VIGNETTE
> It seems like the user would benefit from having some accessor
> methods.
> e.g description(rp$get("c3_TFT_sets")[["E47_01"]])

Done, the accessor is `loadCollection` and returns a `GeneSetCollection` object.

> Similarly:
> rp$get("c3_TFT")$ES[1:3, 1:3]

Done, the new accessors are `loadESmatrix` and `loadPVmatrix`.

> Accessors for CondSEA and details matricies for condition-set
> enrichment analysis and PathSEA and details for pathway-set
> enrichment.

Done, there is now a `getResults` and a `getDetails` that can be used both for `CondSEA` output and for `PathSEA` output.

> REAL world example : (while not eval i ran for reproducibility)
> Change in untar and openRepository: Cmap_MsigDB_v6.1_PEPs.tar.gz
> (capitalization of s)

Fixed. I tested the whole code of the example.

> Side:
> Well done on output produced. I like the status messages for steps
> throughout running the functions.
> Thank you for the real world example.

Thank you!

> INST:
> Please move the RDS files into extdata subdirectory (and update
> system.file calls in vignette or man appropriately).

Done.

> R CODE:
> throughout code:
> Write seq_len(n) or seq_along(x) rather than 1:n or 1:length(x). This

Done.

> dummyFunction
> If this is needed maybe mark as keyword(internal) or remove the man
> file since it will not be referenced by the user (similarly for any
> other internal functions)

I set keyword(internal). The `dummyFunction` just collects in a single place the documentation of common parameters for other functions to inherit from. I put it in .Rbuildignore just in case.

**Comment by mtmorgan** [comment] 2017-11-22 21:34
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/franapoli.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"gep2pep\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gep2pep

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Closed by mtmorgan** 2017-11-22 21:34 UTC
Labels: 3a. accepted, OK
