### ISSUE TITLE
bambu

### ISSUE THREAD

**Issue by cying111** [Bioconductor/Contributions#1596] opened 2020-08-18 02:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/GoekeLab/bambu

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-08-19 17:31
The version number of new packages must be '0.99.0'. Also please ensure that your package meets Bioconductor file size requirements
```
BiocManager::install("BiocCheck")
BiocCheck::BiocCheck("path/to/bambu")
```
If there are large files in your git repository history, it may be necessary to remove these following instructions at https://bioconductor.org/developers/how-to/git/remove-large-data/

Post a comment here when your package has been revised.

**Comment by cying111** [comment] 2020-08-20 03:50
Thank you for the feedback! 

We have addressed the two comments in the master branch:
1. Updated the version number in description
2. Removed large history files using BFG repo cleaner.

Please let us know if there are further questions!

**Comment by cying111** [comment] 2020-08-24 02:54
AdditionalPackage: https://github.com/GoekeLab/NanoporeRNASeq

**Comment by mtmorgan** [comment] 2020-08-24 18:24
The version of NanoporeRNASeq must also have 'y' of 'x.y.z' be '99', so '0.99.0'. The package must also satisfy Bioconductor size requirements; has it passed `BiocCheck::BiocCheck("NanoporeRNASeq")` on your own system?

**Comment by cying111** [comment] 2020-08-25 02:39
Hi @mtmorgan , the version number has been updated now. The additional package is created as an experimental data package and we have made sure that big history files are all removed. We have also tested the biocheck for NanoporeRNASeq and it passed. 

Let us know if you have further questions!! Thanks!!

**Comment by lshep** [comment] 2020-08-25 15:40
@cying111 and @LiNk-NY  Just to let you know what is going on and why bambu is marked as unsupported across all platforms.  The SPB had an implementation of recognizing a Dockerfile in the top level directory as indicating a Docker submission for Bioconductor.  We realize this is a poor implementation and are working on a correction that uses the DESCRIPTION file instead but it may take a few days.  Until then @LiNk-NY  you would have to build/check the package locally for review.  Once the changes are implemented I will do a manual rebuild and leave a message here.  Cheers and sorry for the inconvenience.

**Comment by lshep** [comment] 2020-08-26 14:03
The docker file recognition issue has been addressed. I kicked off a manual build of bambu and the report should post shortly.  Cheers

**Comment by cying111** [comment] 2020-08-27 06:33
Hi, changes are pushed to both the Bioconductor and github repositories.

**Comment by cying111** [comment] 2020-08-27 08:52
hi @LiNk-NY @lshep , sorry about this, I have a technical question here. I have updated the package, however, the first commit was pushed without updating the version number (sorry for my stupidity) and then I pushed anotehr commit with updating the version number. In this case, I am not sure is the new build using the first commit as well?

**Comment by lshep** [comment] 2020-08-27 11:50
The build with the version bump should contain all the changes from the first push.  Cheers

**Comment by LiNk-NY** [comment] 2020-08-27 15:00
@lshep 
It looks like the build report didn't post? 
Thanks.

**Comment by mtmorgan** [comment] 2020-08-27 17:29
For NanoporeRNASeq we still have
```
files larger than 5Mb:
  /inst/extdata/Homo_sapiens.GRCh38.dna_sm.primary_assembly_chr22_1_25409234.fa
  /inst/extdata/K562_directcDNA_replicate1.bam
  /inst/extdata/K562_directcDNA_replicate4.bam
  /inst/extdata/K562_directRNA_replicate6.bam
  /inst/extdata/MCF7_directcDNA_replicate3.bam
  /inst/extdata/MCF7_directRNA_replicate4.bam
```
Either reduce the size of these files (presumably used to illustrate your package) or re-implement the package so that the data are hosted on ExperimentHub (http://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html)

**Comment by cying111** [comment] 2020-08-28 02:37
hi @mtmorgan, for NanoporeRNASeq, we probably cannot reduce the file size any more so we will need to host the data to the ExperimentHub. We have modified the package dependencies to meet the requirements for ExperimentHub,  for the next steps, could you provide further guidance on how to upload data to ExperimentHub? Thank you

**Comment by cying111** [comment] 2020-08-28 10:34
hi @lshep @LiNk-NY @mtmorgan , regarding the new build report, 
1. it looks like the remaining error is mostly due to the test time  being too long, do you have any suggestions or advices on how to fix this error? 
2. For the other build bin error on Mac, it looks like there is a system file missing, should we be concerned of that as well? If so, do you guys have any suggestions on how to resolve it? 
3. Other than errors, do we need to fix all the warnings as well? Thanks!

**Comment by mtmorgan** [comment] 2020-08-28 11:16
@lshep  or @Kayla-Morrell can help with https://github.com/Bioconductor/Contributions/issues/1596#issuecomment-682291681

**Comment by mtmorgan** [comment] 2020-08-28 11:22
1. The time is likely due to the vignette or examples trying to do a complete analysis, rather than performing an illustrative analysis on a subset of the data.

2. I can't see the missing system file on the macOS builds, but maybe after cleaning up the other issues it will be more apparent

3. Yes, generally you should tackle the warnings. You should also address the notes, expect if they do not make sense in your situation. In particular the 'undefined global variables' should be addressed. If you're using dplyr syntax, note that `select()` variables can be quoted `mtcars %>% select("cyl")` and `filter()` variables can use rlang::.data `mtcars %>% filter(.data$cyl == 6)`.

**Comment by lshep** [comment] 2020-08-28 12:56
@cying111   Please send an email to hubs@bioconductor.org  and we will give you the credentials to upload the data to S3 where the data will be hosted.  We will examine the metadata file more closely when the data is uploaded to make sure everything looks correct but on quick glance please update the BiocVersion to 3.12.  Cheers

**Comment by LiNk-NY** [comment] 2020-08-31 23:14
Hi Chen, @CYing111 
Please provide any updates here so that we can keep the review going. 
Thank you!
-Marcel

**Comment by cying111** [comment] 2020-09-01 01:10
Hi, @LiNk-NY sorry about this, we are still making edits to the package, we will update it soon later this week. Thank you.

**Comment by LiNk-NY** [comment] 2020-09-01 14:37
Thank you Chen! @cying111

**Comment by mtmorgan** [comment] 2020-09-08 19:18
I'll close this issue until NanoporeRNASeq has been updated to pass BiocCheck; post a comment here when the issue is ready to be re-opened.

**Comment by cying111** [comment] 2020-09-09 09:02
Sorry about this, we are still working on the packages. We will post a comment once we are ready. Thank you!!

**Comment by cying111** [comment] 2020-10-01 09:33
@lshep, hi, I have recently uploaded the data to S3 experiment hub, could you help to check if that's uploaded correctly and help to make it live, so that we can try to call the files within the package. Thanks for a lot for your help.

**Comment by lshep** [comment] 2020-10-01 11:52
I do not see the data uploaded to S3.  Please try again.  When ready or if you have any further questions,  please send an email to hubs@bioconductor.org.

**Comment by Kayla-Morrell** [comment] 2020-10-01 12:19
Hello @cying111 - Did you create an accompanying data package `NanoporeRNASeq`? If so I will be uploading the data this morning and should be available soon.

**Comment by cying111** [comment] 2020-10-02 00:59
Hello @Kayla-Morrell , yes, the data is uploaded for the accompany data package NanoporeRNASeq. Thank you.

**Comment by cying111** [comment] 2020-10-08 13:18
Hi @mtmorgan , sorry for the late updates. I have pushed a new version for bambu. I have also updated the accompanying package NanoporeRNASeq. Please help reopen the issue!! Thank you very much!!

**Comment by mtmorgan** [comment] 2020-10-08 22:12
OK, I think your additional package should be building and the review process can continue.

**Comment by cying111** [comment] 2020-10-09 01:06
Hi, just to check, is there any build report for bambu?

**Comment by LiNk-NY** [comment] 2020-10-09 03:36
Hi Chen, @cying111 
Can you trigger a new build of bambu by doing a version bump? 
Thanks.

**Comment by cying111** [comment] 2020-10-09 04:01
hi @LiNk-NY , I just retried to update the version again and do the push, still not triggering a new build:

This is the command that I do:
## fetch and merge 
git remote -v
git fetch --all
git merge upstream/master
git merge origin/master
## I changed the version number to 0.99.7
git add DESCRIPTION
git commit -m "version update to 0.99.7"
## push to upstream and origin
git push upstream master
git push origin master

**Comment by LiNk-NY** [comment] 2020-10-09 04:17
Hi Chen, @cying111 
What does your `git remote -v` say when you're in the `bambu` directory?

@lshep @Kayla-Morrell Any ideas why `bambu` version bump is not triggering a build? 

Thanks.

**Comment by cying111** [comment] 2020-10-09 04:21
This is the printout from `git remote -v `
origin  https://github.com/GoekeLab/bambu.git (fetch)
origin  https://github.com/GoekeLab/bambu.git (push)
upstream        git@git.bioconductor.org:packages/bambu.git (fetch)
upstream        git@git.bioconductor.org:packages/bambu.git (push)

**Comment by LiNk-NY** [comment] 2020-10-09 04:34
It looks good to me. Let's see what the others in the team say. Thanks.

**Comment by lshep** [comment] 2020-10-09 12:09
The label `review in progress` needed to be added in order for a build to proceed. Please try again.

**Comment by LiNk-NY** [comment] 2020-10-09 15:29
Chen @cying111, please bump the version of `bambu` and try again. Thank you.

**Comment by cying111** [comment] 2020-10-10 02:31
Thank you all @LiNk-NY @lshep ! It now worked. As NanoporeRNASeq depends on bambu, I will push a version bump for NanoporeRNASeq when a new build is done for bambu.

**Comment by cying111** [comment] 2020-10-10 05:06
Hi @LiNk-NY , regarding the warnings for both packages, I am not sure I can do anything with it for now. I think I changed the requirement of R version to the latest because I need to use the most recent ExperrimentHub snapshot which requires the latest R version. Could you advise on what I should do?

**Comment by cying111** [comment] 2020-10-12 02:25
> Hi @LiNk-NY , regarding the warnings for both packages, I am not sure I can do anything with it for now. I think I changed the requirement of R version to the latest because I need to use the most recent ExperrimentHub snapshot which requires the latest R version. Could you advise on what I should do?

Thanks @LiNk-NY, I think I figured out this warning and resolved it by reseting the R requirement to 4.0.0 Thanks.

**Comment by LiNk-NY** [comment] 2020-10-13 00:04
Hi Chen, @cying111 

Thank you for your submission to Bioconductor.
Please see the review below. If you have any questions,
feel free to post them as comments below. 
Be sure to respond to the review line by line. 

Best regards,
Marcel

---

# bambu #1596

* Overall, the package looks good.
* Because of the number of unexported helper functions in the package,
consider creating a utility package with exported helpers for users
looking to use the same operations.
* See the comments for `NanoporeRNASeq` below.

# NanoporeRNASeq

* Was there no existing package that could provide this example data on
`ExperimentHub`?
* If not, please use more descriptive names for the data. 'annotation' and
'sample_info' are too broad and can apply to any dataset.
* Avoid installing packages for the user, remove the chunk where the `ipak`
function is created and used (vignette lines#55-67)
* Add any packages in 'packages' L#65 to the `Suggests:` field in the
`DESCRIPTION` file.
* Add `sessionInfo` and remove `devtools::load_all`.
* Provide installation instructions using `BiocManager::install` as seen
on package landing pages.

## DESCRIPTION

* Avoid adding `devtools` in the `Suggests` field.
* Avoid depending on `BiocManager`.
* Generally, the package is really heavy in terms of dependencies. If possible,
avoid using packages where you only have a few number of functions that are
imported. Perhaps, there are ways around the importing of `data.table` and
`dplyr`.

## NAMESPACE

* Are there other packages that provide read and write GTF functionality? It
may be better to not re-invent the wheel.

## vignettes

* Remove the `ipak` code chunk similar to that in `NanoporeRNASeq`.
* Include an `Installation` section that uses `BiocManager` instead of
`devtools`.
* Is `Content` necessary when `BiocStyle` provides a `toc: true` option?
* Can you provide a small files to show how the functionality of `bambu`?
* Or, can you find a package that does provide example files for the vignette?
* The previous bulletpoints raise the question whether you need
`NanoporeRNASeq` at all.
* Avoid using `eval=FALSE` where possible. If need be, write to the `tempdir()`
directory. It's better to test code this way than to not test at all.

## R

* Combine non-exported functions into a single R script rather than having
separate files.
* Avoid unneccesary clean up (using `rm` and `gc` functions). R does this
internally already.
* If possible, reduce the length of argument names in the main `bambu`
function.
* If you must save a file, set `readClass.outputDir` to `tempdir()` in the
top-level function arguments rather than down in the code.
* It may be better to drop the `fs` dependency by using either your own
mechanism or `BiocFileCache` if `fs::path` is the only import from the
package.
* Avoid nesting `*apply` function calls. Use `lapply(..., tail, 1L)` instead
(in line#484 of `R/isore.R`).
* Perhaps you can combine conditions using the `%in%` operator for operations
like `x$strand %in% c("+", "-")` (L#487-497 of `R/isore.R`).
* Consider creating a separate package for providing the helper functions
as utilities for other users (with proper documentation).
* Consider creating an `import` & `export` method for a particular file
subclass (e.g., `GTF`; where an alternative import function is not available;
see generic in `BiocIO`)
* If reasonable, create a feature request for `GenomicAlignments` to allow
the behaviour that you would like to use instead of copying the function
body from `GenomicAlignments`.

Minor:
* Use `on.exit` calls for clean up such as `on.exit(close(bf))`.
* `if (length(x) > 1)` is equivalent to `if (length(x))`

**Comment by cying111** [comment] 2020-10-14 07:27
Thank you, Marcel @LiNk-NY , for reviewing the package. We have learned many things from this review and bioconductor submission process. We have addressed your comments below:
## Overall for NanoporeRNSeq

> Was there no existing package that could provide this example data on ExperimentHub?

We have explored this, and there seems to be no existing package for long read RNA-Seq examples. The aim of this package is to provide simple examples researchers can use for long read RNA-Seq package development. To facilitate this, we have specifically created a small annotation file that exactly matches to the  example bam files that we use. We hope that this will be useful to many others as well.

>  If not, please use more descriptive names for the data. 'annotation' and 'sample_info' are too broad and can apply to any dataset.

We have renamed the two objects in this package. Please check.

> Avoid installing packages for the user, remove the chunk where the ipak function is created and used (vignette lines#55-67)

We have removed  this chunk. Thank you for the suggestions.

> Add any packages in 'packages' L#65 to the Suggests: field in the DESCRIPTION file.
  
Packages that are previously in the ipak chunks are now all in the suggested field.

> Add sessionInfo and remove devtools::load_all.

We added sessionInfo() in the end of the vignette and removed devtools::load_all()

> Provide installation instructions using BiocManager::install as seen on package landing pages.

 Installation of bambu now is through BiocManager::install
## Description

> Avoid adding devtools in the Suggests field.

Devtools was removed from the Suggests field for both packages.

> Avoid depending on BiocManager.

Imports from BiocManager is removed for both packages.

> Generally, the package is really heavy in terms of dependencies. If possible, avoid using packages where you only have a few number of functions that are imported. Perhaps, there are ways around the importing of data.table and Dplyr.

We have followed your suggestions to remove most of the dependencies, for cases where only  a few functions are used, we have moved to suggests and call these functions with :: instead. Please check.
Namespace for bambu

> Are there other packages that provide read and write GTF functionality? It may be better to not re-invent the wheel.

We are aware of the existence of functionality that can read and write GTF. However, the object output from our package is rather specific and customized. To keep all the information in, we believe it is better to provide our own functions which are adapted but can better suit our package output.

## Vignettes for bambu

> Remove the ipak code chunk similar to that in NanoporeRNASeq.

We have removed this code chunk.

> Include an Installation section that uses BiocManager instead of devtools.

We have replaced devtools with BiocManager in the installation section

> Is Content necessary when BiocStyle provides a toc: true option?

We have removed the content section

> Can you provide a small file to show the functionality of bambu?
Or, can you find a package that does provide example files for the vignette?
The previous bulletpoints raise the question whether you need NanoporeRNASeq at all.

These points can be addressed together. We have tried to see if there exist any small example data for bambu, but unfortunately, we can’t find any. Therefore, we created NanoporeRNASeq and generated small data examples for long reads that can be used by bambu and other packages specifically for long reads. 

> Avoid using eval=FALSE where possible. If need be, write to the tempdir()  directory. It's better to test code this way than to not test at all.

We have removed eval = FALSE for those with chunks with illustration purposes. However, we kept eval = FALSE for those sections where it was only meant for description rather than illustration. 

## R code 

> Combine non-exported functions into a single R script rather than having separate files.

We agree that this might be a good idea. To accommodate for it while still keeping the functions that used for different steps in separate files to facilitate future maintenance, we have renamed the Rscripts to name as utility_XXX_functions so to distinguish from those that are to be exported. 

> Avoid unnecessary clean up (using rm and gc functions). R does this internally already.

We have removed all unnecessary clean up,.i.e., all rm() and gc() used within functions.

> If possible, reduce the length of argument names in the main bambu Function.

We have renamed the argument names in the main bambu function. 

> If you must save a file, set readClass.outputDir to tempdir() in the top-level function arguments rather than down in the code.

We have set readClass.outputDir to tempdir() in the top-level function

> It may be better to drop the fs dependency by using either your own mechanism or BiocFileCache if fs::path is the only import from the Package.

We have dropped the dependency on fs to use BiocFileCache to create files

> Avoid nesting *apply function calls. Use lapply(..., tail, 1L) instead (in line#484 of R/isore.R)

We have avoided the nested *apply call and replaced endoapply with lapply

> Perhaps you can combine conditions using the %in% operator for operations like x$strand %in% c("+", "-") (L#487-497 of R/isore.R).

We have updated the code in updateWIntronMatches function to combine the conditions respectively. 

> Consider creating a separate package for providing the helper functions as utilities for other users (with proper documentation).

We agree that it would be great to have such a package for others to use. However, most of the functions written for internal use are rather specific to objects used within this package and may need quite a bit of work to make them generalizable to other users. Therefore, we prefer to have this implementation in a future release. 

> Consider creating an import & export method for a particular file subclass (e.g., GTF; where an alternative import function is not available; see generic in BiocIO)

Thank you for this suggestion. This is indeed a very good suggestion. However, similar as above, to be able to do this, the functions written for this might need some work to be done. We may consider it as an added feature for the next release.

> If reasonable, create a feature request for GenomicAlignments to allow the behaviour that you would like to use instead of copying the function body from GenomicAlignments.

Thank you for the suggestions. For most of the functions we have added a few more functionalities to the original code. However, we agree that for functions which could be useful to others it will be helpful to make a feature request for GenomicAlignments. We will consider it for the next release as it might take some time to have the feature we needed to be ready in GenomicAlignments.
## Minor:
> Use on.exit calls for clean up such as on.exit(close(bf)).

We have used on.exit when calls for cleaning up.

> if (length(x) > 1) is equivalent to if (length(x))

It looks like it should rather be if (length(x) > 0) being equivalent to if(length(x)). Therefore, we have changed if(length(x) > 0) to if(length(x)). For if ( length(x) > 1 ) case, we did not do the change as we found out that if(length(x)-1) is not the same as if(length(x)>1) when length(x) == 0.

**Comment by LiNk-NY** [comment] 2020-10-15 15:01
Hi Chen, @cying111 

Thanks for making those changes. 

Please re-read http://bioconductor.org/developers/package-guidelines/#description and make sure that the packages in the `Suggests` field are non-essential for the code in the package. If they are, these packages should go in the `Imports` field.

Please bump the version and push upstream after you make this change. 

Best,
Marcel

**Comment by cying111** [comment] 2020-10-16 06:55
Hi Marcel, @LiNk-NY 
Thanks for the suggestions. I have followed your suggestions to move packages essential to the package back to imports and keep the others in suggests. Please check, Thank you!

**Comment by cying111** [comment] 2020-10-20 07:45
Hi @LiNk-NY , please let us know if there are any problems with this new version! Thank you!

**Comment by LiNk-NY** [comment] 2020-10-20 13:10
Hi Chen, @cying111 
Thank you for making that change. Your package has been accepted. 
Best regards,
Marcel

**Comment by mtmorgan** [comment] 2020-10-20 21:49
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cying111.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("bambu")`. The package 'landing page' will be created at

https://bioconductor.org/packages/bambu

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2020-10-20 21:49
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cying111.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NanoporeRNASeq")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NanoporeRNASeq

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-10-20 21:49 UTC
Labels: 3a. accepted, OK
