### ISSUE TITLE
immunotation

### ISSUE THREAD

**Issue by imkeller** [Bioconductor/Contributions#2032] opened 2021-04-06 21:41 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/imkeller/immunotation

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x ] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by imkeller** [comment] 2021-04-13 15:46
Hi @Kayla-Morrell ,

this package uses external reference annotations, for example a list of [G groups](http://hla.alleles.org/alleles/p_groups.html) for nomenclature conversion. The complete reference list is read from here: [https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/hla_nom_g.txt](https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/hla_nom_g.txt)

As far as I understand this causes an ERROR in the checks.
> ERROR: Avoid references to external hosting platforms
>       Found in files:
>         external_resources_input.R (line 105, column 18)
>         external_resources_input.R (line 115, column 18)

What should I do to circumvent the problem? Should I copy the reference file into the data folder of the package (ideally I would like to avoid this), or is there another option you can recommend? I could include checks for the version of the list.
Many thanks!

**Comment by Kayla-Morrell** [comment] 2021-04-20 19:50
@imkeller - We do not allow for data to be hosted on external platforms such as github or dropbox. You have a couple of options.

1) You could include the file as data in the package - this can be done if the package stays within the size limit for Bioconductor (the built package tarball cannot exceed 5MB).
2) You could host the file in either our AnnotationHub or ExperimentHub then reference the resource in your package from there.
3) The final (probably less ideal option) would be to create a separate, accompanying annotation or experiment data package that will be used by your package. Since there is only one file, this might be over kill.

Let me know if you have follow up questions or need more guidance. We do have some guidelines [here](https://bioconductor.org/developers/package-guidelines/#data) for including data with your package.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-04-29 17:15
@imkeller - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.0 to 4.1.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with the
  relevant link to GitHub for reporting Issues.

## NEWS

- [ ] REQUIRED: Thank your for including a NEWS file, but this file should have
  content within it. See our documentation
[here](https://bioconductor.org/developers/package-guidelines/#news) to make
sure the file is formated correctly.

## Data

- [ ] REQUIRED: We required that data in the 'inst/extdata' directory requires
  documentation in an 'inst/script' directory. The scripts in this directory can
vary. Related scripts must be present in this directory documenting very clearly
how the data was generated. It should include source urls and any important
information regarding filtering or processing. It can be executable code, sudo
code, or a text description. A user should be able to download and roughly
reproduce the file or object that is present as data.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section (maybe in the Scope
  of the package section) that demonstrates to the user how to download the
package from Bioconductor. The code should look like the following and include
`eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("immunotation")
```

- [ ] REQUIRED: The final section of the vignette should be 'Session
  Information' and should include `sessionInfo()`.

## Man pages

- [ ] SUGGESTION: For any function that is not being exported but has been
  documented I would add the `@keywords internal` tag. This will remove the
function from the documentation index of the package.

- [ ] REQUIRED: Add runnable examples to the following man pages which document 
exported objects:
        human_protein_complex_table.Rd

## R code

- [ ] REQUIRED: Since you make queries to web resources be sure you are
  following our guildesline
[here](http://bioconductor.org/developers/how-to/web-query/).

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 22 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reaons, consider multiples of 4 spaces for line 
indents. There are 40 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-05-03 18:49
@imkeller - I should have mentioned in my review above to keep in mind that the deadline to accept new packages into the Bioconductor 3.13 release is May 12th.  Any packages accepted after this date will be included in the next realse.

Best,
Kayla

**Comment by imkeller** [comment] 2021-05-04 18:30
@Kayla-Morrell thank you for your comments and suggestions. I updated the package to address your points as follows:

> ## DESCRIPTION
> 
>     * [x]  REQUIRED: Update R version dependency from 4.0 to 4.1.
The change was implemented.
>     * [x]  SUGGESTION: It is encouraged to include the 'BugReports:' field with the
>       relevant link to GitHub for reporting Issues.
- The change was implemented.
> 
> ## NEWS
> 
>     * [x]  REQUIRED: Thank your for including a NEWS file, but this file should have
>       content within it. See our documentation
>       [here](https://bioconductor.org/developers/package-guidelines/#news) to make
>       sure the file is formated correctly.
I included version history in the NEWS file and respected the formatting guidelines.
> 
> ## Data
> 
>     * [x]  REQUIRED: We required that data in the 'inst/extdata' directory requires
>       documentation in an 'inst/script' directory. The scripts in this directory can
>       vary. Related scripts must be present in this directory documenting very clearly
>       how the data was generated. It should include source urls and any important
>       information regarding filtering or processing. It can be executable code, sudo
>       code, or a text description. A user should be able to download and roughly
>       reproduce the file or object that is present as data.
> 
I included external_resources.Rmd in inst/scripts/. It allows users to reproduce the data files contained in inst/extdata.
> 
> ## Vignette
> 
>     * [x]  REQUIRED: There should be an 'Installation' section (maybe in the Scope
>       of the package section) that demonstrates to the user how to download the
>       package from Bioconductor. The code should look like the following and include
>       `eval = FALSE`.
> 
The 'Installation' section is included below the scope of the package section.
> 
>     * [x]  REQUIRED: The final section of the vignette should be 'Session
>       Information' and should include `sessionInfo()`.
> 
'Session Information' is included at the end of the vignette.
> 
> ## Man pages
> 
>     * [x]  SUGGESTION: For any function that is not being exported but has been
>       documented I would add the `@keywords internal` tag. This will remove the
>       function from the documentation index of the package.
I added @keywords internal to non-exported documented functions.
> 
>     * [x]  REQUIRED: Add runnable examples to the following man pages which document
>       exported objects:
>       human_protein_complex_table.Rd
I added a runnable example to human_protein_complex_table.Rd.
> 
> 
> ## R code
> 
>     * [x]  REQUIRED: Since you make queries to web resources be sure you are
>       following our guildesline
>       [here](http://bioconductor.org/developers/how-to/web-query/).
Most of the functions querying web resources use the getURL function in external_resources_input.R, which is in accordance with the guidelines.
I updated the queries in MACUI_interface.R and made sure they return meaningful error messages/warnings.
> 
>     * [x]  SUGGESTION: For formating reasons, consider shorter lines. There are 22
>       lines that are > 80 characters long.
The remaining lines > 80 characters are mostly in the vignette concerning hyperlinks or tables, which I would like to avoid to change, because I think it is easier to read as is.
> 
>     * [x]  SUGGESTION: For formating reaons, consider multiples of 4 spaces for line
>       indents. There are 40 lines that are not.
The lines where the indents are not 4 spaces seem to be mainly in the man/ documentation files and thus caused by roxygen. Not sure if it makes sense to change this manually.

**Comment by Kayla-Morrell** [comment] 2021-05-06 20:51
@imkeller - Thank you for making the necessary changes. Everything looks great and I'm more than happy to accept the package.

Best,
Kayla

**Comment by vjcitn** [comment] 2021-05-07 10:05
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/imkeller.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("immunotation")`. The package 'landing page' will be created at

https://bioconductor.org/packages/immunotation

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-05-07 10:05 UTC
Labels: 3a. accepted, OK
