### ISSUE TITLE
progeny: pathway activity inference from gene expression data

### ISSUE THREAD

**Issue by mschubert** [Bioconductor/Contributions#477] opened 2017-09-09 10:55 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/saezlab/progeny

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment] 2017-09-23 08:15
@mschubert will you be addressing the build error on windows?

**Comment by mschubert** [comment] 2017-09-23 08:21
Apologies for the delay, it's on my list. - Having difficulty finding a Windows machine to test on.

**Comment by mschubert** [comment] 2017-09-27 16:48
@mtmorgan This is fixed now. Thank you for the patience.

**Comment by mtmorgan** [comment] 2017-10-04 16:40
It seem like your package is to replicate a highly speciifc analysis, rather than to help others do similar analyses. Can you clarify, both for me and for your users via the DESCRIPTION file and vignette, how you anticipate the package will be used in novel analysis? For instance, what constraints apply to data sets for which one might wish to apply your fitted model?

DESCRIPTION

- good

NAMESPACE

- good

vignettes

- progeny.Rmd:52 Use BiocFileCache to download the data; this will mean that the build system downloads only once rather than nightly, making results more reproducible.

- is there value in downloading an Excel file, instead of exporting the xlsx file (and then importing from) to csv? It seems like the file format needs to be highly idiosyncratic anyway, so might as well make it in a globally readable format.

- provide some narrative interpretation of input and results, so that the reader has some additional guidance on package use.

- Can you incorporate this into existing work flows, e.g., from the 'airway' experiment data package?

- Include the output of `sessionInfo()` as a final code chunk, to aid reproducibility and provide context.

R

- progeny.r:27 This looks like it woud not work; there is no 'exprs' method for AnnotatedDataFrame. Maybe you mean ExpressionSet. Also, many modern analyses use SummarizedExperiment.

- progeny.r:32 it is never appropriate to rely on the global environment for reading or writing variables; 'model' should be an argument, or ??? what is it's role here? it would be appropriate to discover it's path (save as RDS instead of rda) and input it

    ```
    model_path = system.file(package="progeny", "data", "model.rds")
    model = readRDS(model_path)
    ```

- Since Bioconductor makes extensive use of S4, it is appropriate here, and not too much more cumbersome, to use S4 methods

    ```
    setGeneric(
        "progeny",
        function(expr, scale = TRUE) standardGeneric("progeny"),
        signature = "expr"
    )

    setMethod("progeny", "matrix", function(expr, scale = TRUE) {
        ...
    })
    
    etc
    ```

man

- The model.Rd man page is insufficient. Describe in more detail structure of the matrix. E.g., why there are 1059 rows and 11 columns? What do the values in the matrix represent?

- Similarly, provide additional detail, especially about the `expr` argument, to `progeny()`, e.g., are these normalized values from microarray experiments?

**Comment by mschubert** [comment] 2017-10-09 16:00
I have now uploaded a revised version of the package.

Please find some more detailed comments to your requests below.

The remaining error has got nothing to do with the package (I think):

> 'BiocCheck' is not recognized as an internal or external command,
operable program or batch file.

### vignettes

> progeny.Rmd:52 Use BiocFileCache to download the data; this will mean that the build system downloads only once rather than nightly, making results more reproducible.

I now make use of `BiocFileCache` in the vignette.

> is there value in downloading an Excel file, instead of exporting the xlsx file (and then importing from) to csv? It seems like the file format needs to be highly idiosyncratic anyway, so might as well make it in a globally readable format.

I am not maintaining these files, and I can not guarantee continued hosting of a csv version (although I can request it with the maintainers). What I can do is add an additional matrix to the package, but this would increase size and not benefit from updates of the data source.

> provide some narrative interpretation of input and results, so that the reader has some additional guidance on package use.

I added `sessionInfo()` to the vignette.

> Can you incorporate this into existing work flows, e.g., from the 'airway' experiment data package?

I now also added an example on how to process the `airway` data set in the vignette.

> Include the output of `sessionInfo()` as a final code chunk, to aid reproducibility and provide context.

I added this in the vignette.

### R

> progeny.r:27 This looks like it woud not work; there is no 'exprs' method for AnnotatedDataFrame. Maybe you mean ExpressionSet. Also, many modern analyses use SummarizedExperiment.

I have fixed the code to include the appropriate classes.

> progeny.r:32 it is never appropriate to rely on the global environment for reading or writing variables; 'model' should be an argument, or ??? what is it's role here? it would be appropriate to discover it's path (save as RDS instead of rda) and input it

The function does not rely on the global environment but rather the package environment, which provides this object. This is [recommended here](http://r-pkgs.had.co.nz/data.html#data-sysdata).

> Since Bioconductor makes extensive use of S4, it is appropriate here, and not too much more cumbersome, to use S4 methods

Can you explain what S4 offers over S3 in this case?

### man

> The model.Rd man page is insufficient. Describe in more detail structure of the matrix. E.g., why there are 1059 rows and 11 columns? What do the values in the matrix represent?

I added additional information to the documentation.

> Similarly, provide additional detail, especially about the expr argument, to progeny(), e.g., are these normalized values from microarray experiments?

I added additional information to the documentation.

**Comment by mtmorgan** [comment] 2017-10-22 17:09
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mschubert.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"progeny\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/progeny

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Closed by mtmorgan** 2017-10-22 17:09 UTC
Labels: 3a. accepted
