### ISSUE TITLE
CTexploreR

### ISSUE THREAD

**Issue by aloriot** [Bioconductor/Contributions#3138] opened 2023-09-08 10:53 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/UCLouvain-CBIO/CTexploreR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lgatto** [comment] 2023-09-25 19:21
Hi there - we are addressing the issues, but I had a question regarding the timing. The examples currently take so long because of the first time data download (data from [CTdata](https://bioconductor.org/packages/release/bioc/html/CTdata.html) via ExperimentHub). Next time, the data will be loaded from cache and the example will be much faster to execute - we didn't hit such long timings when checking locally before submission. Should we still limit our examples? We can't really reduce the data size here, except for creating completely new datasets.

**Comment by lshep** [comment] 2023-09-26 11:07
If they are cached then on the next build it would be resolved. Perhaps just trying doing a version bump to see if things have resolved on their own?

**Comment by lgatto** [comment] 2023-10-05 12:38
@lshep - would it be possible to give me access to the Bioconductor CTexploreR github repo?

**Comment by lshep** [comment] 2023-10-05 12:49
you mean maintainer access at git.bioconductor.org? We dont have a github.  You have been added

**Comment by lgatto** [comment] 2023-10-11 14:51
- On lconway (macOS), the warning complains about package files exceding the 5MB size limit (in BiocCheck)
- On nebbiolo2 (linux), the warning complains about the check exceeding 10 min requirement (in check)

Do these two not cancel each other out? ;-) 

I'll check (on linux) what I can do, but was wondering if, in the meantime, a reviewer could already have a look.

**Comment by lgatto** [comment] 2023-10-12 13:55
Hi @lshep - I am in a bit of a pickle here. 

- If I want to reduce the check time to < 10 minutes (currently at  11m 7.3s locally), I'll need to either further reduce the unit tests, of add `\dontrun` to some examples (code that is anyway explained in the vignette). What should I sacrifice? 

- As for the size, it's entirely due to figures in the vignette, that is 5.3 Mb. Not sure how to easily fix this for only 0.3 Mb.

**Comment by lshep** [comment] 2023-10-13 13:11
We can move it forward for now.  I would say as long as the examples/functions are run somewhere then it would be okay to add a dontrun (ie.  if it is run in the vignette, than it can be in a dontrun in the example man page)  I would try and leave the tests untouched as much as possible.   Me personally I would rather see a complete vignette and complete tests over run in the examples.   
Is there a way to reduce the resolution slightly at all for the figures? that might help? 

In the meantime I'll assign a reviewer.

**Comment by lgatto** [comment] 2023-10-13 16:34
The errors complain about less than 80% of man pages documenting exported objects must have runnable examples. This is on purpose, to cut the check timing - see above. And all these functions are executed and illustrated in the vignette anyway.

**Comment by LiNk-NY** [comment] 2023-10-17 20:20
Hi Laurent, @lgatto 

I am getting an error when attempting to `INSTALL` the package: 

```r
* installing to library 
* installing *source* package 'CTexploreR' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
see ?CTdata and browseVignettes('CTdata') for documentation
downloading 1 resources
retrieving 1 resource
Warning: download failed
  web resource path: 'https://experimenthub.bioconductor.org/fetch/8368'
  local file path: '/home/user/.cache/R/ExperimentHub/667b6f452f79_8368'
  reason: Conflict (HTTP 409).
Warning: bfcadd() failed; resource removed
  rid: BFC7
  fpath: 'https://experimenthub.bioconductor.org/fetch/8368'
  reason: download failed
Warning: download failed
  hub path: 'https://experimenthub.bioconductor.org/fetch/8368'
  cache resource: 'EH8309 : 8368'
  reason: bfcadd() failed; see warnings()
Error : failed to load resource
  name: EH8309
  title: CT_genes
  reason: 1 resources failed to download
Error: unable to load R code in package 'CTexploreR'
Execution halted
ERROR: lazy loading failed for package 'CTexploreR'
```

It seems like the `leukemiaAtlas` package is not available. Do you know where this package is coming from? I do not see it in Bioconductor or CRAN.

Best,
Marcel

**Comment by LiNk-NY** [comment] 2023-10-17 21:49
Hi Laurent and Axelle, @lgatto @aloriot 

Thank you for your submission. 
The package looks to be in good shape. There are some errors to resolve. 
Please see the review below.

Best regards,
Marcel

---

# CTexploreR #3138

## DESCRIPTION

* Looks good.
* Include `leukemiaAtlas` and other packages that are required to load
`ExperimentHub` resources in `Suggests`.

## NAMESPACE

* Consider using `MatrixGenerics::rowMaxs` instead of `Biobase::rowMax`.

## R

* Use `match.arg` in `CCLE_expression` and others to select default arguments
and to show the user the entire list of possibilities as the default argument.
For example, `match.arg` will select the first option by default:

```r
test <- function(units = c("TMP", "log_TPM")) {
    match.arg(units)
}
```

* Functions like `CTdata::CCLE_data()` should work. Currently, there is an
error `Conflict (HTTP 409)` when running the function.
* Use default values in arguments e.g., `nt_up = 1000` in
`normal_tissues_methylation`
* Minor. Consider using `values.only` instead of `return` to avoid clashing
symbols in `CCLE_expression()` and other functions.
* Minor. Reduce logic `ifelse(condition, TRUE, FALSE)` to `condition` in
`CT_correlated_genes()`.
* Minor. The `cells` argument in `testis_expression` can use
`match.arg(several.ok = TRUE, ...)` to allow the selection of multiple
`germ_cells` and/or `somatic_cells`. There could also be a `switch` call to
resolve the choices of `germ_cells` and `somatic_cells` that would return the
appropriate group vector.

## tests

* Unable to run `covr::package_coverage()` due to installation errors.

**Comment by LiNk-NY** [comment] 2023-11-01 13:23
Hi Axelle, @aloriot 
Any updates on this?

**Comment by lgatto** [comment] 2023-11-01 13:46
Thank you for getting back to us, @LiNk-NY . 

We experienced some weird issues on our RStudio server (that @aloriot makes use of), which is why it took some extra time. It checked fine on my computer, but wanted to double check before pushing. Also, I guess we should move to R-devel and Bioc 3.19 now, right?

**Comment by LiNk-NY** [comment] 2023-11-01 15:05
Hi Laurent, @lgatto 
Thank you for your response. 
Yes, ideally you should check on Bioc devel 3.19. 
Note that the `bioconductor/bioconductor_docker:devel-amd64` image is now available. 
Best,
Marcel

**Comment by lgatto** [comment] 2023-11-10 15:15
## Addressed

- Used `MatrixGenerics::rowMaxs` instead of` Biobase::rowMax`.

- `match.arg()` was used to select the default unit parameter in
  `CCLE_Expression()`, `GTEX_expression()`, `TCGA_expression()` and
  `HPA_cell_type_expression()`

- Set default values of nt_up and nt_down to 1000 and 200 in
  `normal_tissues_methylation()`

- Used `values_only` instead of `return` in all functions.

- Changed the `if (values_only) ...` by `ifelse(values_only,
  return(x), return(y))` in all fucntions

- `match.arg()` was used to select "all" cells by default in
  `testis_expression()`, and `switch()` was added to resolve
  germ_cells and somatic_cells choices.

- Functions like `CTdata::CCLE_data()` should work - @lgatto tested it
  locally with Bioc 3.19.

- The package coverage is shown below

```
> library(covr)
> pc <- covr::package_coverage("../dev/CTexploreR/")
> pc
CTexploreR Coverage: 96.03%
R/TCGA_expression.R: 83.02%
R/normal_tissues_methylation.R: 89.71%
R/TCGA_methylation_expression_correlation.R: 93.10%
R/CCLE_expression.R: 95.65%
R/HPA_cell_type_expression.R: 97.67%
R/testis_expression.R: 98.48%
R/CT_correlated_genes.R: 100.00%
R/DAC_induction.R: 100.00%
R/GTEX_expression.R: 100.00%
R/normal_tissue_expression_multimapping.R: 100.00%
R/normal_tissues_mean_methylation.R: 100.00%
R/utils.R: 100.00%
> 
```

## Not addressed

- Include `leukemiaAtlas` and other packages that are required to load
  `ExperimentHub` resources in Suggests.

Not sure to understand the question, could you clarify what is the `leukemiaAtlas` 
and why we should include it?

**Comment by lgatto** [comment] 2023-11-10 15:38
The error

* ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples.

is expected - we removed some examples from the man pages because they were redundant with the vignette and were time consuming because on data retrieval.

**Comment by LiNk-NY** [comment] 2023-11-20 16:06
Thank you Laurent!
Is the data for the examples and vignettes cached? 

> Not sure to understand the question, could you clarify what is the leukemiaAtlas
and why we should include it?

It looks like some of the resources are annotated with a dependency on the non-existent `leukemiaAtlas` package. The error that I linked [above](https://github.com/Bioconductor/Contributions/issues/3138#issuecomment-1767109932) may have been caused by connectivity issues. Also, the data retrieved is a simple `data.frame` so the dependency is not critical (though the maintainers of the data should fix their package). Disregard the `Suggests` comment. 

```r
> ExperimentHub::ExperimentHub()["EH8368"]
snapshotDate(): 2023-11-14
ExperimentHub with 1 record
# snapshotDate(): 2023-11-14
# names(): EH8368
# package(): leukemiaAtlas
# $dataprovider: GEO
# $species: Homo sapiens
# $rdataclass: DataFrame
# $rdatadateadded: 2023-08-02
# $title: rosell2011_healthy_colData
# $description: per-sample metadata bulk expression data of healthy samples ...
# $taxonomyid: 9606
# $genome: hg38
# $sourcetype: tar.gz
# $sourceurl: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE25414
# $sourcesize: NA
# $tags: c("ExpressionData", "RNASeqData", "SingleCellData") 
# retrieve record with 'object[["EH8368"]]' 
```

cc: @ywhsiao

**Comment by lgatto** [comment] 2023-11-21 06:20
Hi @LiNk-NY - I'm not sure about `leukemiaAtlas`, to be honest. It is cached on my computer, yes, but I don't think CTexploreR requires it, at least explicitly. I can't find any reference to it in our package, at least, and @aloriot didn't know about it either.

**Comment by LiNk-NY** [comment] 2023-11-21 14:24
Thanks Laurent. It looks like it is completely unrelated to `CTdata`. I will chalk up the error to technical issues on our end.
The package has been accepted. Thanks again for all your contributions!
Best,
Marcel

**Comment by lgatto** [comment] 2023-11-21 14:57
Fantastic, thank you very much!

**Comment by lshep** [comment] 2023-11-27 17:13
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/aloriot.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CTexploreR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CTexploreR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-11-27 17:13 UTC
Labels: ERROR, 3a. accepted
