### ISSUE TITLE
msgbsR

### ISSUE THREAD

**Issue by BenjaminAdelaide** [Bioconductor/Contributions#203] opened 2016-11-22 01:54 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/BenjaminAdelaide/msgbsR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by hpages** [comment] 2016-12-02 08:00
Hi Benjamin,

Thanks for your submission. See below for some feedback. I'll take a 2nd look at the package once these issues are addressed.

Thanks,
H.

1) Except for `msgbsR_Vignette.Rnw`, all the files in the `msgbsR/vignettes/` folder are LaTeX/pdflatex products. These files don't belong to the git tree. Please remove them.

2) After loading msgbsR, `sessionInfo()` reports 98 packages loaded via a namespace. Please try to reduce the amount of package dependencies.

3) Please add BSgenome.Rnorvegicus.UCSC.rn6 to the Suggests field of the DESCRIPTION file. The vignette uses this package.

4) Make sure that the \usage sections of the man pages show the default values of the function arguments. For example args `fastaPath` and `BSgenome` of the `checkCuts()` function both have a default value set to NULL:
```
args(checkCuts)
# function (cutSites, cutIDs, fastaPath = NULL, BSgenome = NULL, 
#     seq) 
# NULL
```
but the man page doesn't show that:
```
  Usage:

     checkCuts(cutSites, cutIDs, fastaPath, BSgenome, seq)
```
I would have expected `R CMD check` to report this but apparently it doesn't. This looks like a bug in `R CMD check` that would be worth reporting to the R people.

5) Serialized datasets like `datCounts.Rdata` are better placed in the `data/` folder, rather than in the `inst/extdata/` folder. One of the advantages of placing them in `data/` is that they can then be loaded with `data(datCounts)` which is easier than
```
load(system.file("extdata", "datCounts.Rdata", package = 'msgbsR'))
```
Also datasets in the `data/` folder are discoverable with `data(package="msgbsR")` and need to be documented.

6) 2 issues with the `datCounts` matrix:
  6-a) These are counts so please use an integer matrix instead of numeric matrix. Integer matrices use twice less memory than double matrices.
  6-b) The rownames are of the form `chr20:1:57125`. Please adopt widely used format `chr20:1-57125` instead. One advantage of this format is that it's recognize by the `GRanges()` constructor so the user easily turn these genomic ranges into a GRanges object with:
```
library(GenomicRanges)
GRanges(rownames(datCounts))
```
The idea is to facilitate interaction with the ecosystem of Bioconductor packages.

7) A general problem across the package is the use of character matrices to represent things that should not be represented as a character matrix. For example the man page for `checkCuts()` contains the following description for the `cutSites` argument:
```
     cutSites: A matrix where the first column is the chromosome ID, the
               second column is the starting position and the third column
               is the ending position of the cut site sequence.
```
Please use a GRanges object instead of a character matrix for this. This is exactly what GRanges objects are for.

Note that after you've addressed 5), 6) and 7), the example in the man page for checkCuts() will simply be:
```
load(datCounts)
cutSites <- GRanges(rownames(datCounts))
chr20 <- system.file("extdata", "chr20.fa.gz", package="msgbsR")
correctCuts <- checkCuts(cutSite, cutIDs=row.names(datCounts),
                         fastaPath=chr20, seq="CCGG")
```
Also please simplify the code in the vignette accordingly.

8) The `plotCircos()` function has a `genome` argument that is described as follow in the man page:
```
  genome: A matrix with the lengths of the chromosomes. The first
          column is the chromosome ID and the second is the length of
          each chromosome.
```
This is another misuse of character matrix. For consistency with other Bioconductor packages, it would be preferable to use a named integer vector for this. See the value returned by the `seqlengths()` getter for an example of such named integer vector:
```
library(BSgenome.Rnorvegicus.UCSC.rn6)
head(seqlengths(BSgenome.Rnorvegicus.UCSC.rn6))
#      chr1      chr2      chr3      chr4      chr5      chr6 
# 282763074 266435125 177699992 184226339 173707219 147991367 
```
Also for consistency with other Bioconductor packages, please rename the `genome` argument -> `seqlengths`.

9) For consistency with other Bioconductor packages, please rename the `BSgenome` argument of the `checkCuts()` function -> `genome`. Inside the function, do
```
  if (!is.null(genome)) {
    genome <- getBSgenome(genome). In the man page, describe this argument as follow:
    sequences <- data.frame(getSeq(BSgenome, cuts.gr))
 }
```

10) Any reason why the example in the man page for `plotCircos()` is inside a `\dontrun` directive?

11) Your code use a lot of if statements like
```
if (is.null(fastaPath) == FALSE) ...
```
or
```
if (fastaExt == "TRUE") ...
```
or
```
if (cutIDsClass == "FALSE") ...
```
etc...
This is considered poor coding style. Please use
```
if (!is.null(fastaPath)) ...
```
or
```
if (fastaExt) ...
```
or
```
if (!cutIDsClass) ...
```
Of course `fastaExt` and `cutIDsClass` should be logical variables and not strings.

12) The recommended way to check that an object is of a certain class is to do `if (is(x, "a certain class"))` instead of `if (class(x) == "a certain class")`.

**Comment by BenjaminAdelaide** [comment] 2016-12-05 10:16
Hi  @hpages ,

Thank you for your comments and suggestions to my R package. I have to my knowledge now made all of your recommendations. Below are your comments again and how I have made your changes. 
However, I am currently getting a 'texi2pdf' error, I am unsure what to do here, it appears to be looking for the pdf version of the msgbsR_vignette but it should be making itself during the build process.

Thanks for your input,

From Benjamin.


1. Except for msgbsR_Vignette.Rnw, all the files in the msgbsR/vignettes/ folder are LaTeX/pdflatex products. These files don't belong to the git tree. Please remove them.
All other files excluding msgbsR_Vignette.Rnw have now been removed.

2. After loading msgbsR, sessionInfo() reports 98 packages loaded via a namespace. Please try to reduce the amount of package dependencies.
I am unsure on reducing the package dependencies without affecting the use of the functions. Is it possible to reduce them any further.

3. Please add BSgenome.Rnorvegicus.UCSC.rn6 to the Suggests field of the DESCRIPTION file. The vignette uses this package.
BSgenome.Rnorvegicus.UCSC.rn6 has now been added to the Suggest field of the DECRIPTION file.

4. Make sure that the \usage sections of the man pages show the default values of the function arguments. For example args fastaPath and BSgenome of the checkCuts() function both have a default value set to NULL:
All functions now have a \usage section and default values are shown. I have removed both fastaPath and BSgenome inputs and replaced both with a simplified genome input instead.

5. Serialized datasets like datCounts.Rdata are better placed in the data/ folder, rather than in the inst/extdata/ folder. 
datCounts.rda, datCounts_filtered.rda, ratChr.rda, cuts.rda have now been placed into the data/ folder and can been used as examples.

6. 2 issues with the datCounts matrix:
6-a) These are counts so please use an integer matrix instead of numeric matrix. Integer matrices use twice less memory than double matrices.
6-b) The rownames are of the form chr20:1:57125. Please adopt widely used format chr20:1-57125 instead. One advantage of this format is that it's recognize by the GRanges() constructor so the user easily turn these genomic ranges into a GRanges object with:
The supplied datCounts.rda is to my knowledge now an integer matrix. I have also converted the row names to be recognised by GRanges (example: chr20:123-123).

7. A general problem across the package is the use of character matrices to represent things that should not be represented as a character matrix. 
I have now converted the use of a character matrix into a GRanges object for all functions.

8. The plotCircos() function has a genome argument that is described as follow in the man page:
The input for the genome argument is now an integer object.

9. For consistency with other Bioconductor packages, please rename the BSgenome argument of the checkCuts() function -> genome.
The input for the genome in checkCuts() is now genome and BSgenome has now been removed.

10. Any reason why the example in the man page for plotCircos() is inside a \dontrun directive?
At the time of submission I believe there was an error with ggplot2 on the servers. Since it has been fixed I have removed the \dontrun directive and added a new example.

11. Your code use a lot of if statements like
I have converted all old code unit tests to  if(!is(x, "object class")) in all functions.

12. The recommended way to check that an object is of a certain class is to do if (is(x, "a certain class")) instead of if (class(x) == "a certain class").
I have converted my code to this method in all of the functions.

**Comment by hpages** [comment] 2016-12-08 06:46
Hi Benjamin,

Thanks for all the changes to msgbsR. The errors reported by the single package builder look like false positives -- I can build and check the package successfully on my laptop -- so let's ignore them.

Still many issues with the package. Several of them previously reported but not properly addressed:

6. Using integers instead of doubles applies to matrices of counts *in general*. And in particular to the matrix returned by `rawCounts()`.

7. You need to update the description of the `cutSites` argument to reflect its new nature.

8. Please rename the `genome` argument -> `seqlengths`.

11. You still have many clumsy `if` statements like:
```
if(fasta == TRUE) ...
```
or even worse:
```
if(fastaExt == 'TRUE') ...
```
And also clumsy `if else` statements like:
```
if(fasta == TRUE){
    ...
} else if(fasta == FALSE) { # <--- why test fasta again if you already now it's not TRUE?
    ...
}
```
Please take the time to learn the basics of good programming practices. The submission process is not really the place to discuss the topic but there are many resources available for that. The effort is totally worth it in the long run, especially if you're planning to contribute code to the Bioinformatics community in general, not just Bioconductor. Even for the code you use internally in your lab because it will be easier to read/understand/maintain/share.

Some new issues:

13. The man pages for your data sets are too minimalist. For example, the man page for the `cuts` data set is:
```
A GRanges object of MspI cut sites.

Description:

     A data set containing the following data:

Usage:

     data(cuts)
     
Format:

     A GRanges object

Details:

        • cuts a GRanges object of MspI cut sites

Value:

     A GRanges object
```
The Details and Value sections couldn't be more minimalist. Please tell a little bit more about these Mspi cut sites in the Details section e.g. how they were generated/obtained, for which reference reference genome, if they are for the full genome or only a subset of the genome, how the GRanges object was constructed, etc... In the Value section specify the length of the object e.g.
```
A GRanges object of length 363.
```
Also, `seqinfo(cuts)` should contain seqlength, circularity flag, and genome information.

14. A few tweaks to your DESCRIPTION/NAMESPACE files: (a) Please add the methods package to the Depends field and add `import(methods)` to the NAMESPACE file. (b) Move GRanges from Imports to Depends. (c) Remove BiocGenerics from Suggests.

15. There are a couple of problems with the following code (used in the man pages and in the vignette):
```
cutSites@ranges@start <- as.integer(cutSites@ranges@start -1)
cutSites@ranges@width <- as.integer(cutSites@ranges@width + 3)
```
When working with S4 objects (e.g. GRanges objects) we should never try to access directly the content of their slots with the `@` operator. Instead we should use accessors.  Accessors are divided in 2 groups: getters and setters. See the GRanges man page (`?GRanges`) for how to get/set the start/width/end of GRanges objects using the `start()`/`width()`/`end()` getters and setters. Using a combination of getters and setters, the above code can be replaced with:
```
start(cutSites) <- start(cutSites) - 1
end(cutSites) <- end(cutSites) + 2
```
Also please note that this extends the ranges by 1 nucleotide position to the left and 2 nucleotides to the right. Any reason for this dissymmetry?
Finally note that you might consider using `resize()` for resizing the ranges with a single function call. See `?resize` in the GenomicRanges package for more information.

16. `checkCuts()` should of course return a GRanges object.

17. Please always use double quotes (`"`) instead of single quotes (`'`) around string literals. The later tend to cause problems when copy/pasted from the PDF of the vignette with some PDF readers.

18. It's hard to understand how the following code (found in the man pages and the vignette) could make any sense:
```
my_path <- system.file("extdata", "Control_1.bam", package = "msgbsR")
my_path <- gsub("Control_1.bam", "" , my_path)
```
Why would you construct a path by explicitly adding the Control_1.bam part to it and then immediately remove that part?

19. In the man page for rawCounts():
```
Value:

     Produces a data frame where the rows correspond to cut sites and
     columns are the samples. Cut sites are given a unique ID
     (chromosome:strand:position).
```
No, not a data frame. And no, the cut sites IDs are not in the `chromosome:strand:position` format.

20. I get the following warning when running the example for `plotCircos()`:
```
Warning message:
In BioC 3.5, the 'force' argument was replaced by the more flexible
  'pruning.mode' argument, and is deprecated. See ?seqinfo for the
  supported pruning modes. Note that 'force=TRUE' is equivalent to
  'pruning.mode="coarse"'. 
```
Please address.

21. Finally note that the standard way to represent read counts in Bioconductor is with a SummarizedExperiment object instead of a matrix. See the SummarizedExperiment package for more information. Please consider using this in your package. Make sure that the `rawCounts()` function propagates the `seqinfo` from the BAM files to the returned SummarizedExperiment object. You can use `seqinfo(BamFile(my_path))` to extract the `seqinfo` but if you use `readGAlignments()` internally (instead of `scanBam()`), you'll get the seqinfo on the returned GAlignments object. Once you have this in place, getting the cut sites from the SummarizedExperiment object will be a matter of calling `rowRanges()` on it. Note that the plotCircos() function won't need the `seqlengths` argument anymore because it will be able to get this information from the GRanges object.

Don't hesitate to ask on the bioc-devel mailing list if you need help or have any concern with this.

Thanks,
H.

**Comment by BenjaminAdelaide** [comment] 2016-12-09 05:05
Hi @hpages ,

Thankyou for your suggestions and your comments regarding my R package. Below is what I have done to my package in response to your suggestions and comments.

Thankyou again for your import,

From Benjamin.

6. Using integers instead of doubles applies to matrices of counts in general. And in particular to the matrix returned by rawCounts().
I have added extra code to rawCounts such that it returns an integer matrix.

7. You need to update the description of the cutSites argument to reflect its new nature.
The description to cutSites has been updated since it is now a GRanges input.

8. Please rename the genome argument -> seqlengths.
The genome argument has now been renamed to seqlengths.

9. You still have many clumsy if statements like:
To my knowledge I have converted all remaining if statements to the desired format.

13. The man pages for your data sets are too minimalist. For example, the man page for the cuts data set is:
I apologise for the minimal input. I have now updated the data set to contain more descriptive information.

14. A few tweaks to your DESCRIPTION/NAMESPACE files: 
The methods and GenomicRanges packages have been added to the Depends field and BioGenerics has been removed.

15. There are a couple of problems with the following code (used in the man pages and in the vignette):
Thankyou for your comment, I have now convert the code in the manual page to your suggestion. Also regarding the dissymmetry, it is to cover the sequence of the recognition site. The restriction enzyme MspI used in the example cuts at C/CGG. Therefore to check if the cut sites are correct the postion must move 1 to the left and 2 to the right.

16. checkCuts() should of course return a GRanges object.
The aim of checkCuts() was to return a vector of IDs of the cut sites that did match the desired input sequence (seq). The user then uses this vector to filter out the incorrect cut sites from datCounts. To my knowledge, I do not know of a way to remove the incorrect cut sites from a matrix using a GRanges object. 

17. Please always use double quotes (") instead of single quotes (') around string literals. The later tend to cause problems when copy/pasted from the PDF of the vignette with some PDF readers.
All single quotes have been removed and replaced with double quotes.

18. It's hard to understand how the following code (found in the man pages and the vignette) could make any sense:
The following code has been adjusted such that it reads:
my_path <- system.file("extdata", "", package = "msgbsR")
datCounts <- rawCounts(bamFilepath = my_path, threads = 1)

19. In the man page for rawCounts():
The man page for rawCounts() has been updated such that it reads:
Produces an integer matrix where the columns are samples and the rows are cut sites. The cut site IDs are in the format chr:position-position.

20. I get the following warning when running the example for plotCircos():
I have now removed the force argument and it should now remove the warning.

21. Finally note that the standard way to represent read counts in Bioconductor is with a SummarizedExperiment object instead of a matrix. 
Thank you for your suggestion regarding using SummarizedExperiment with my package. Since my package depends on edgeR, for differential methylation analyses, which to my knowledege does not use SummarizedExperiment objects, I do not think it would be necessary to use with my package. Furthermore, edgeR starts with a matrix of read counts as well. Is it a requirement to use SummarizedExperiment in order to submit a package to Bioconductor?

**Comment by BenjaminAdelaide** [comment] 2017-01-29 22:28
Hi @hpages 

Do the current changes meet your requirements?

Thanks

**Comment by hpages** [comment] 2017-02-14 08:13
Hi Benjamin,

Please don't change the issue numbers in your answers. For example in your last list of answers, item #12 is about an issue I originally reported as issue #15. Doing this is making things unnecessarily hard to track. I'm using my *original* issue numbers below.

- Related to issue #9 from my original feedback. Please replace
```
    if(!is(genome, "BSgenome")){
        stop('genome must be a BSgenome if fasta = FALSE')
    }
```
with
```
    genome <- getBSgenome(genome)
```
in the `checkCuts()` function. This means that msgbsR needs to import the BSgenome package (i.e. have BSgenome in the Imports field and import(BSgenome) in the NAMESPACE file). Trying to pass `genome` thru `getBSgenome()` has many benefits e.g. it will also work if `genome` is the name of a BSgenome data package. It will even work if the user specifies the BSgenome data package with something like `"rn6"`. And it will fail gracefully with a useful error message if the specified BSgenome data package is not installed.

- Related to issue #11 from my original feedback. Please understand that doing things like
```
    isTRUE(x)
```
or
```
    ifelse(x, yes=TRUE, no=FALSE)
```
on a logical value `x` is not needed and hurts readability. More generally speaking, there is no point in calling an expression on `x` that is a no-op i.e. that is guaranteed to return the same `x`. Unfortunately that's something I see a lot in your code e.g.
```
    if(isTRUE(fasta)) ...
```
or
```
    gffExt <- ifelse(extenstion(gff) == "gff" | extenstion(gff) == "gff3" , yes=TRUE, no=FALSE)
```
Instead of this please do:
```
    if (fasta) ...
```
  or
```
    gffExt <- extenstion(gff) == "gff" | extenstion(gff) == "gff3"
```
Note that I already sent you feedback before on the proper way to write `if` and `if else` statements and gave you precise instructions so please follow them.

- Generally speaking you need to pay a lot more attention to the quality of your code. For example your vignette contains the following 2 lines:
```
    ratChr <- seqlengths(BSgenome.Rnorvegicus.UCSC.rn6)
    ratChr <- ratChr[which(names(seqlengths(BSgenome.Rnorvegicus.UCSC.rn6)) == "chr20")]
```
This is so obfuscated! It is basic knowledge that a named vector can be subsetted by name so please replace with:
```
    ratChr <- seqlengths(BSgenome.Rnorvegicus.UCSC.rn6)["chr20"]
```
Using such obfuscated code for realizing such simple tasks gives a poor image of your package.
  
- Related to issue #13 from my previous feedback. You're still not telling how the GRanges object `cuts` was obtained. My guess is that you used `diffMeth()` for that but I don't know exactly how the function was called and on what. So please be as explicit as possible about how `cuts` was obtained by showing the exact code that you used to generate this dataset. It's all about being transparent and not have your users trying to guess what you did.

- Related to issue #15 from my previous feedback. Thanks for clarifying the reason for the dissymmetry in
```
    start(cutSites) <- start(cutSites) - 1
    end(cutSites) <- end(cutSites) + 2
```
but this dissymmetry reveals a deeper problem with your approach. With this approach you're only selecting the sites where the restriction enzyme did a cut at C/CGG on the plus strand. This is why your `checkCuts()` function returns less than half of the sites (it returns 7178 sites out of 16977). Because `checkCuts()` takes an unstranded GRanges object, the internal calls to `scanFa()` or `getSeq()` will extract the sequence from the plus strand, so in order to select sites where the restriction enzyme did a cut at C/CGG on the *minus* strand, one needs to pass the reverse complement of the sequence. Even though the reverse complement is the same sequence (because the sequence is a palyndrome), now the cut should be considered to happen on the other side i.e. to cut at CCG/G. So to select the sites from the minus strand, one needs to do:
```
    cutSites <- GRanges(rownames(datCounts))
    start(cutSites) <- start(cutSites) - 2
    end(cutSites) <- end(cutSites) + 1
```
and call checkCuts(cutSites, ..., seq="CCGG"). This returns 6487 sites out of 16977. The fact that all these cut sites are currently omitted from your analysis questions the scientific validity of your results.

- Related to issue #18 from my previous feedback. No need to pass the empty string (`""`) in your calls to `system.file()`:
```
    system.file("extdata", "", package = "msgbsR")
```
It's important that you show code in the vignettes and examples that follows good practices, and is concise and as simple as possible.

- About issue #21 from my previous feedback. Yes please use SummarizedExperiment objects to represent read counts. It doesn't matter that you use edgeR behind the scene for differential methylation analyses. You're doing this via your own function, `diffMeth()`, so you have the freedom to support SummarizedExperiment objects. More precisely, you should use a RangedSummarizedExperiment object to represent the counts and store the cut sites in a GPos object that you store as the rowRanges of the RangedSummarizedExperiment object. This implies a redesign of some of your functions e.g. `rawCounts()` should return a RangedSummarizedExperiment object that can be used as input of `plotCounts()` and `diffMeth()`.

Other issues:

(22) Your internal helper `readCounts()` uses the following expression to compute `readStart`:
```
    readStart <- ifelse(df$strand == 2, df$pos + df$qwidth - 1, df$pos)
```
This produces incorrect results in general for reads on the minus strand because the qwidth ("query width") is the width of the query *before* alignment. Once aligned to the reference genome, the query can be longer or shorter depending on whether there were indels and/or skipped regions. In order to compute the width of the query *after* alignment you would need to take into account the CIGAR strings where the details about indels and/or skipped regions are reported. This can be done by loading your BAM files with the `readGAlignments()` function from the GenomicAlignments package instead of using low-level `scanBam()`. It will return a GAlignments object `gal` from which you can compute `readStart` with:
```
   readStart <- ifelse(strand(gal) == "-", end(gal), start(gal))
```

(23) The `rawCounts()` function contains the following code:
```
    dat <- readCounts(bamFilepath = bamFiles[1])
    anyDuplicated(dat$id)
    dat <- mclapply(bamFiles, FUN = readCounts, mc.cores = threads)
```
So `bamFiles[1]` is loaded twice! The 1st time it's loaded in the `dat` variable which you don't use and replace by another `dat` variable.

(24) Several problems with `closestFeat()`. Inside the function you re-implement your own GFF reading function (`gffRead`) instead of using `import()` from the rtracklayer package. This implementation has several problems e.g. it's based on `read.table()` and so will be inefficient on big GFF files. Also it won't parse the "attributes" column. So please take the time to familiarize yourself with what's already available in Bioconductor and use it instead of trying to re-invent the wheel. Also the GRanges container is the container of choice for representing genomic features in Bioconductor so `closestFeat()` should return that. In the end your `closestFeat()` function can be implemented in 2 lines with someting like this:
```
    closestFeat <- function(gff, cutSites)
    {
        gff <- import(gff)
        gff[nearest(cutSites, gff)]
    }
```
Note that the function provides very little value as most Bioconductor users know how to do this "by hand" and don't really need a dedicated function for this.

(25) Not sure it's a good idea to use randomly generated data in the examples section of `diffMeth()` man page when you have real data at hand.

(26) You need to `import(methods)` in your NAMESPACE file. 

(27) No need to specify `threads=1` in your calls to `rawCounts()` since this is actually the default.

Cheers,
H.

**Comment by BenjaminAdelaide** [comment] 2017-02-27 22:58
Hi @hpages 

Thanks for your comments. To the best of my knowledge I have now made your corrections.

Thanks for your time

**Comment by hpages** [comment] 2017-03-31 06:28
Hi Benjamin,

The red VERSION BUMP REQUIRED label indicates that you need to bump the version of your package in order to trigger a new build/check of the package. Thanks!

H.

**Comment by hpages** [comment] 2017-04-14 17:25
Hi Benjamin,

The error we see in the last build/check of your package was caused by some recent changes in other Bioconductor packages that msgbsR depends on. See here for the details:

  https://stat.ethz.ch/pipermail/bioc-devel/2017-April/010737.html

These problems should have been addressed now. Can you please bump the version of your package again in order to trigger a new build/check of the package? Thanks and sorry for the inconvenience!

H.

**Comment by hpages** [comment] 2017-04-21 08:11
Hi Benjamin,

Thanks for addressing all the issues I reported!

All the changes you made look good and greatly improve the overall quality and usability of your package. There is only one little thing left: the package is too big (33 Mb). Note that you could reduce its size by half by not including the `chr20.fa.gz` file (Rat chr20 sequence). The size of this file alone is 17 Mb and you only use it to illustrate the fact that `checkCuts()` can also be used directly on a FASTA file (in addition to a BSgenome object). While this is a nice feature, that's something you could just mention in the vignette but you don't actually need to show how to do that.

The next Bioconductor release is in 5 days so we don't have much time left. Hopefully you can do something about the size of the package. I would need to hear back from you before Saturday night.

Thanks again for all your hard work on the package.

Cheers,
H.

**Comment by hpages** [comment] 2017-04-23 23:36
Hi Benjamin,
Any chance you can take care of the size issue before tomorrow?
Thanks,
H.

**Comment by BenjaminAdelaide** [comment] 2017-04-23 23:47
Hi @hpages ,

Thanks for your comments and your help, it's been greatly appreciated. 

As you've suggested I have now removed the chr20.fa.gz from the package and the respective code from the vignette.

Thankyou again,

From Ben

**Comment by hpages** [comment] 2017-04-24 00:02
OK. Thanks for the change. As you know, the single package builder is still reporting a build failure on Windows. However we're too short of time before the BioC release for troubleshooting this issue now. So I'm accepting the package as-is but the Windows issue is something that will need to be investigated and addressed after the release. Otherwise we'll have to mark the package as unsupported on Windows.

We will make sure to add the package to our Subversion repository and build system ASAP. Also we'll send you an email very soon with a follow-up on this. Thanks for your contribution to Bioconductor!

Regards,
H.

**Closed** 2017-04-24 18:31 UTC
Labels: 3a. accepted, ERROR, WARNINGS
