### ISSUE TITLE
visiumStitched

### ISSUE THREAD

**Issue by Nick-Eagles** [Bioconductor/Contributions#3501] opened 2024-07-29 18:52 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LieberInstitute/visiumStitched

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lcolladotor** [comment] 2024-07-30 17:32
PS This will be a package where both Nick and I will ultimately need Git push permissions on BioC. Thanks in advance!

**Comment by lshep** [comment] 2024-08-12 14:31
I just tried to build locally and I get 
```
Quitting from lines 383-399 [precast_k2] (visiumStitched.Rmd)
Error: processing vignette 'visiumStitched.Rmd' failed with diagnostics:
undefined columns selected
--- failed re-building ‘visiumStitched.Rmd’

SUMMARY: processing the following file failed:
  ‘visiumStitched.Rmd’

Error: Vignette re-building failed.
Execution halted

```

**Comment by lcolladotor** [comment] 2024-08-12 15:12
Hi Lori,

Hmm, that's weird. It seems like you have access to an older version since https://github.com/LieberInstitute/visiumStitched/actions/runs/10290020036/job/28479030122 did complete `R CMD build` and other steps. Note that since Nick made this issue, we did have to make some updates.

Another tell sign is that the code chunk name you listed, changed from `precast_k2` to `precast_k2_stitched` at https://github.com/LieberInstitute/visiumStitched/commit/15e19a4fe9dec99f29ba6bd193c64953cd246aa7#diff-875fd975531b65ba1343b24ad76faffbcc69d119601a74ac0734833a6bb07326L382.

Note that we haven't bumped the version number from 0.99.0 since the SBP hasn't been run yet and from previous experience, @bioc-issue-bot will complain that the version number is not 0.99.0 for the first run.  Maybe we should bump the version number though (say 0.99.1)?

Best,
Leo

**Comment by lshep** [comment] 2024-08-12 16:09
indeed. I shall try again.

**Comment by lcolladotor** [comment] 2024-08-15 02:53
Hi @Nick-Eagles,

Have you had a chance to look into resolving the issue(s) with your Bioconductor Support account (watched tags) + Bioconductor email support subscription?

Remember that once you have done so, you have to bump the package version, and push to both https://github.com/LieberInstitute/visiumStitched as well as the Bioconductor git server (git.bioconductor.org). See the notes on how to do this from the last link in the automated message above my comment. Doing this, will trigger a new SBP (Single Package Builder) run, which if successful, will remove the `ERROR` tag on this issue, which is needed for the review to keep moving.

Best,
Leo

**Comment by lcolladotor** [comment] 2024-08-23 14:03
Hi @lshep,

Right now the SBP at http://bioconductor.org/spb_reports/visiumStitched_buildreport_20240820163605.html reported a warning since R CMD check took longer than 10 min to run. 

```
* checking examples ... [237s/243s] OK
Examples with CPU (user + system) or elapsed time > 5s
                      user system elapsed
build_spe           76.262  7.230  85.155
spe_to_seurat       32.023  3.932  36.406
add_array_coords    23.551  6.906  30.879
prep_fiji_image     17.799  4.825  23.568
rescale_fiji_inputs 14.105  1.492  16.684
prep_fiji_coords    12.416  2.478  15.925
* checking for unstated dependencies in tests ... OK
* checking tests ...
  Running testthat.R [209s/213s]
 [209s/214s] OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* checking PDF version of manual ... [3s/3s] OK
* DONE

Status: 1 NOTE
See
  /home/pkgbuild/packagebuilder/workers/jobs/3501/04736b337ce9ed8dae3c08b4a72baec88fda8e97/visiumStitched.Rcheck/00check.log
for details.

 WARNING: R CMD check exceeded 10 min requirement
```


However, at GitHub actions also on Linux we see a different story at https://github.com/LieberInstitute/visiumStitched/actions/runs/10478583431/job/29022282328#step:21:95 

```
* checking examples ... OK
Examples with CPU (user + system) or elapsed time > 5s
                      user system elapsed
build_spe           48.161  1.715  50.384
add_array_coords    16.248  1.449  18.476
spe_to_seurat       15.939  0.388  20.562
prep_fiji_image      9.854  0.888  11.251
prep_fiji_coords     9.105  0.773  10.613
rescale_fiji_inputs  9.006  0.739  10.682
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: 2 NOTEs
See
  ‘/__w/visiumStitched/visiumStitched/check/visiumStitched.Rcheck/00check.log’
for details.
── R CMD check results ────────────────────────────── visiumStitched 0.[99](https://github.com/LieberInstitute/visiumStitched/actions/runs/10478583431/job/29022282328#step:21:100).5 ────
Duration: 8m 36.9s
```

On GHA the total run time is less than 10 min, but also, examples such as `build_spe()` took 50 seconds whereas on SBP it took 85 seconds (70% higher). 


https://contributions.bioconductor.org/long-tests.html doesn't seem like it'd be helpful for this scenario. 

Do you have any suggestions on how to proceed? We could put some examples, say, the ones for `build_spe()` under a `dontrun`, as they are similar in nature to the tests for that function. 

Thanks,
Leo

**Comment by lshep** [comment] 2024-08-23 14:09
Its less than 10 min but not by much at 8 min 37 sec .  Finding ways to reduce the time would be beneficial.  As long as any exported function is run in either test or examples so that it can be run/checked at least once.

**Comment by lcolladotor** [comment] 2024-08-23 14:10
Ok! Thanks Lori!

**Comment by lcolladotor** [comment] 2024-08-23 21:29
Hi,

I see that on version 0.99.7 @Nick-Eagles was able to bring down R CMD check by nearly 1 minute (to 7 min 47 secs) based on numbers from GitHub actions, though it still triggers the 10 min warning on SBP.

```
* checking examples ... OK
Examples with CPU (user + system) or elapsed time > 5s
                      user system elapsed
build_spe           39.727  0.528  40.249
add_array_coords    16.870  1.490  20.709
rescale_fiji_inputs  8.256  0.664  10.272
spe_to_seurat        8.032  0.294  16.307
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: 2 NOTEs
See
  ‘/__w/visiumStitched/visiumStitched/check/visiumStitched.Rcheck/00check.log’
for details.
── R CMD check results ────────────────────────────── visiumStitched 0.99.7 ────
Duration: 7m 46.4s
```

The above was taken from https://github.com/LieberInstitute/visiumStitched/actions/runs/10532150505/job/29185703583#step:21:116.

I see at https://github.com/LieberInstitute/visiumStitched/compare/04736b3..edda4cb that Nick mostly used `exists()` and a file to save data that is re-used across multiple examples. He also deleted one test and in another use uses a smaller subset of data (100 genes).

Does this seem enough @lshep? Hm... we could delete https://github.com/LieberInstitute/visiumStitched/blob/devel/tests/testthat/test-build_spe.R since most of that code seems to be used on the example for `build_spe()`.

Best,
Leo

**Comment by LiNk-NY** [comment] 2024-10-11 20:28
Hi Nick @Nick-Eagles 

Thank you for your submission. Please see the review below. 

Best regards,
Marcel

---

# visiumStitched #3501

* Overall the package is well put together. Increase robustness by using
named indices rather than numeric ones. Consider migrating the code to
other readers as this `SpatialExperiment` might change in the future.

## DESCRIPTION

* Looks good.
* Consider removing the `LazyData: true` line. Any data should be loaded with
`data(...)`.

## NAMESPACE

* Use more common names for functions, e.g., `spe_to_seurat` can `as.Seurat()`.
* Consider renaming `build_spe` and avoid abbreviations.
* Add `Seurat` to the `Suggests` field instead.

## vignettes

* Consider wrapping text to 80 characters for readability and ease of
maintenance.
* Remove `Sys.time()` calls from vignette. The BBS will provide this
information in the report.
* Remove installation instructions that use `remotes`. You should be using
`BiocManager::install()` instead.
* The interface is a bit awkward `build_spe`. It seems like `sample_info`
requires a lot of user intervention.
* Consider using other import tools as `read10xVisium` may be deprecated soon,
e.g., `VisiumIO`, `SpatialExperimentIO` and others. Disclaimer: I maintain
`VisiumIO`. Feel free to ask on the \#spatial Bioc slack channel.
* Remove extra code in the Reproducibility section of the vignette e.g.,
"extract R code", "wallclock" etc. Keep the session information.

## R

* Perhaps reduce the complexity of the exampels so that they are easier to
read and run.
* Avoid saving `Rds` files from the examples. Use cached data in conjunction
with `BiocFileCache`, if possible e.g., in `build_spe` and others.
* Avoid using index subsetting where possible and use names instead, e.g.,
`coords_xy[, 1]`.
* Avoid creating folders for the user and assume that they are already
available; error when not e.g., in `rescale_fiji_inputs`.
* Add a package check to the `spe_to_seurat` function e.g., with
`BiocBaseUtils::checkInstalled()`. Consider re-using previously written
`spe_to_seurat` functions.

## tests

* Consider improving some unit test coverage:

```r
> covr::package_coverage(type = 'all')
visiumStitched Coverage: 80.04%
R/array_error_metrics.R: 0.00%
R/build_spe.R: 78.08%
R/add_array_coords.R: 79.31%
R/prep_fiji_coords.R: 84.21%
R/prep_fiji_image.R: 85.19%
R/spe_to_seurat.R: 86.44%
R/add_overlap_info.R: 89.29%
R/rescale_fiji_inputs.R: 90.48%
R/array_coord_utils.R: 94.29%
```

**Comment by Nick-Eagles** [comment] 2024-10-18 14:15
Thanks Marcel for the constructive comments! I've addressed most of the points as suggested, with a couple exceptions. In the numeric index case you referenced ([here](https://github.com/LieberInstitute/visiumStitched/blob/7676df4e9ccdb99aeffee68ac964bd73fb68af41/R/prep_fiji.R#L314)), there aren't named columns to use, but I believe it should be robust against grabbing the wrong column, since the column order is guaranteed [here](https://github.com/LieberInstitute/visiumStitched/blob/7676df4e9ccdb99aeffee68ac964bd73fb68af41/R/prep_fiji.R#L301). I was unable to find other numeric index cases where using names was possible.

Regarding the saving of RDS files in examples, `BiocFileCache` seems difficult to use, as the `sample_info` data frame to cache has columns that point to a large number of local file paths (a spaceranger output directory, an image, and XML file). My specific concerns are that it seems I can either use `BiocFileCache` to individually cache the huge number of files (which may excessively complicate the example), or attempt to simply cache `sample_info`, which feels like a false/ incorrect use of caching (it caches paths to files but not the files themselves). The original motivation was to shorten the otherwise computationally lengthy examples. Given that we want to avoid writing unexpected files on users' machines when running examples, I wrote the RDS files to a temporary directory (see [here](https://github.com/LieberInstitute/visiumStitched/blob/7676df4e9ccdb99aeffee68ac964bd73fb68af41/R/add_array_coords.R#L67)). Please let me know if this is satisfactory or if you have a particular solution in mind for me to implement.

Finally, Leo and I are unable to replicate the error in the single package builder; the package builds locally with the same R and Bioc versions, and builds on [GHA](https://github.com/LieberInstitute/visiumStitched) as well. Do you have any insight into what could be wrong?

Best,
-Nick

**Comment by lcolladotor** [comment] 2024-10-18 14:51
Hi,

We tried replicating the error as part of today's _LIBD rstats club_ session. The video at https://youtu.be/YAeUsKGUmtM starts with this and at 23:52 you can see the R session info for where we tried to reproduce the error. I'm not sure what environment variable in the SBP could be driving the differences between our R 4.4.1 (from today October 18) bioc 3.20 installation at [JHPCE](https://jhpce.jhu.edu/) and the one used by SBP. Note that in GHA we are using the Bioconductor docker devel image also with bioc 3.20, so hmm, we are a bit stumped on how to reproduce the SBP error.

Best,
Leo

**Comment by LiNk-NY** [comment] 2024-10-23 16:03
Hi Nick @Nick-Eagles 

> individually cache the huge number of files (which may excessively complicate the example), or attempt to simply cache `sample_info`, which feels like a false/ incorrect use of caching (it caches paths to files but not the files themselves). The original motivation was to shorten the otherwise computationally lengthy examples. Given that we want to avoid writing unexpected files on users' machines when running examples, I wrote the RDS files to a temporary directory (see [here](https://github.com/LieberInstitute/visiumStitched/blob/7676df4e9ccdb99aeffee68ac964bd73fb68af41/R/add_array_coords.R#L67)). Please let me know if this is satisfactory or if you have a particular solution in mind for me to implement.

Caching a zipped file may be more manageable than multiple files. In either case, avoid saving Rds files in the examples. It is not the expected behavior of the `example` function. The function that downloads files should be using some caching mechanism e.g., `BiocFileCache` to avoid re-downloads which can save you some time. You can also consider creating small example datasets and putting them in `inst/extdata/`. The examples should not be computationally intensive as they're there to demonstrate the usage of the function. 

> R session info for where we tried to reproduce the error.  I'm not sure what environment variable in the SBP could be driving the differences

AFAIK the SPB environment variables are the same as those in the BBS : https://github.com/Bioconductor/BBS/blob/devel/3.20/Renviron.bioc 

I wasn't able to reproduce the error locally or with the Bioc devel container. You can ignore the error for now. 
Thanks!

**Comment by Nick-Eagles** [comment] 2024-10-25 14:06
Thanks Marcel! After more experimentation, I noticed it's lines like [this](https://github.com/LieberInstitute/visiumStitched/blob/15b6708a28f6bbcce62d634522eae441367d4fb7/R/add_array_coords.R#L91) that are the main contributors to the example and test length, and the [data I use](https://github.com/LieberInstitute/visiumStitched/blob/15b6708a28f6bbcce62d634522eae441367d4fb7/R/add_array_coords.R#L84) already uses `BiocFileCache` under the hood. Therefore, I simply removed the problematic saving of RDS files. Due to the SPB build error, I'm not sure how long R CMD BUILD will take on SPB now, but it takes 8 min, 4 seconds on [GHA currently](https://github.com/LieberInstitute/visiumStitched/actions/runs/11506339184/job/32030048704#step:21:122). Please let me know if there's more I can do from my end.

Best,
-Nick

**Comment by Nick-Eagles** [comment] 2024-10-28 19:01
Hi @LiNk-NY, just tagging as I forgot to in my original message (not sure if you get notifications for this thread)

**Comment by LiNk-NY** [comment] 2024-10-28 21:06
Hi @Nick-Eagles 
Thanks for tagging me. 
I looked a bit closer into the issue and I was able to reproduce this error on Ubuntu 24.04.1 LTS: 

```r
2024-10-28 17:05:24.249652 rtracklayer::import: reading the reference GTF file
Error in while (grepl("^#", line)) { : argument is of length zero
Calls: build_SpatialExperiment ... import -> import -> import -> .local -> .sniffGFFVersion
Execution halted
```

which indicates a bug in `rtracklayer:::.sniffGFFVersion`

**Comment by LiNk-NY** [comment] 2024-10-28 21:17
> but it takes 8 min, 4 seconds on [GHA currently](https://github.com/LieberInstitute/visiumStitched/actions/runs/11506339184/job/32030048704#step:21:122).

That should be within the BBS time limit. Thanks!

**Comment by Nick-Eagles** [comment] 2024-11-04 19:55
Thanks @LiNk-NY for tracking down the issue and confirming the `R CMD BUILD` time is okay! Let me know if there's anything else you need from my end.

Best,
-Nick

**Comment by lcolladotor** [comment] 2024-11-18 16:54
As an FYI the paper is now published at https://doi.org/10.1186/s12864-024-10991-y ^^

**Comment by vjcitn** [comment] 2024-11-18 17:07
Congratulations on the paper!

**Comment by lcolladotor** [comment] 2024-11-18 17:49
Thanks Vince!

**Comment by LiNk-NY** [comment] 2024-11-18 18:09
Please update the package to resolve the `NOTE`:

```r
* checking R code for possible problems ... NOTE
merge_overlapping: no visible global function definition for ‘assays<-’
merge_overlapping: no visible global function definition for
  ‘reducedDims’
merge_overlapping: no visible global function definition for
  ‘reducedDims<-’
Undefined global functions or variables:
  assays<- reducedDims reducedDims<-
```

and note that the package is close to the timing limit of 15 minutes for `R CMD check`.

Thank you for your submission!

**Comment by lcolladotor** [comment] 2024-11-18 18:25
Will do @LiNk-NY! Thanks again!

cc @Nick-Eagles: check  👀 Marcel's comment above

**Comment by lshep** [comment] 2024-11-21 17:50
You can ignore this message.  I will be processing accepted packages tomorrow to the daily builder. This is a message to notify reviewers/bioc that changes were made after acceptance.  And that on-demand building is suspended after a package is accepted so not to expect a build report from the changes.

**Comment by Nick-Eagles** [comment] 2024-11-21 17:51
Thanks so much for the prompt explanation! That makes sense.

**Comment by lcolladotor** [comment] 2024-11-21 18:48
Thanks Lori!

I had asked Nick to address Marcel's comments above (https://github.com/Bioconductor/Contributions/issues/3501#issuecomment-2483775277).

**Comment by lshep** [comment] 2024-11-22 12:18
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Nick-Eagles.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("visiumStitched")`. The package 'landing page' will be created at

https://bioconductor.org/packages/visiumStitched

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-11-22 12:18 UTC
Labels: ERROR, 3a. accepted
