### ISSUE TITLE
MetaCyto: an R package for the meta-analysis of cytometry data.

### ISSUE THREAD

**Issue by hzc363** [Bioconductor/Contributions#375] opened 2017-05-22 21:56 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hzc363/MetaCyto

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by hzc363** [comment] 2017-05-22 22:17
Hi, It seems that the error is caused by failing to load a dependency package "flowCore".  Is it because "flowCore" is available on Bioconductor rather than CRAN? How can I solve this problem?

**Comment by vobencha** [comment] 2017-05-24 17:48
Hi,
flowCore is available on the veracruz1 mac builder, you can see it here:
http://www.bioconductor.org/checkResults/devel/bioc-LATEST/
I'm not sure why we are seeing that error - we'll run it again and see if the error persists.

First you need to address the errors for linux and windows:

Errors in linux build:
```
* Checking whether vignette is built with 'R CMD build'...
    * ERROR: Vignette must be built by 'R CMD build'. Please see the
      `Vignette Checks` section of the BiocCheck vignette.

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
```
Errors in Windows build:
```
ERROR: dependency 'metafor' is not available for package 'MetaCyto'
```
Valerie

**Comment by hzc363** [comment] 2017-06-01 03:55
Hi， 

I fixed the dependency requirements. I checked the updated package on Mac, PC and Linux, no errors. Could you please run the check again on your machine?

Thanks!
Zicheng

**Comment by vobencha** [comment] 2017-06-01 15:06
You need to bump the version to trigger a new build, e.g., 0.99.1, 0.99.2, etc ...

**Comment by hzc363** [comment] 2017-06-04 02:20
Hi, I have changed the version number to 0.99.1 2 days ago. No new build seems to be triggered. Are there more things I need to do? Thanks!

**Comment by vobencha** [comment] 2017-06-08 13:19
@lshep , can you please trigger another build for this issue?

**Comment by lshep** [comment] 2017-06-08 13:20
Yes but please ensure the webhook is set up correctly https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook

**Comment by hzc363** [comment] 2017-06-08 17:37
I need some help here. 

The re-check report from Bioconductor showed that there is an error in all three platforms:

> Summary:
> ERROR count: 1
> WARNING count: 1
> NOTE count: 6

However, when I run the biocheck on my own machine, no error is reported.

> Summary:
> ERROR count: 0
> WARNING count: 1
> NOTE count: 6

Without being able to reproduce the error on my own machine, it is difficult for me to debug. I just updated all the dependencies, as wells as the biocheck package on my local machine 2 days ago. So it doesn't seem to be a version issue.

**Comment by vobencha** [comment] 2017-06-11 13:14
This is not a full review, just some preliminary comments to get this on the right track. Most of these are taken directly from the Single Package Builder output.

1) Please read new package requirements here, especially the sections on NAMESPACE and vignettes.
http://www.bioconductor.org/developers/package-guidelines/
2) You do not have a functional vignette. 
During R CMD build you would see a line that says 'building vignettes'. We don't see that with your package which means the vignette is not being built real-time:
```
~/repos/git/software >R-dev CMD build MetaCyto/
* checking for file ‘MetaCyto/DESCRIPTION’ ... OK
* preparing ‘MetaCyto’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘MetaCyto_0.99.1.tar.gz’
```
3) Please fix the title field:
* checking DESCRIPTION meta-information ... NOTE
Malformed Title field: should not end in a period.
License components which are templates and need '+ file LICENSE':
  MIT
4) Fix these global variable issues that are under your control (i.e., the variables that come from your package):
```
* checking R code for possible problems ... NOTE
HC.assign: no visible global function definition for ‘cutree’
autoCluster.batch: no visible global function definition for ‘read.csv’
baselineCut: no visible global function definition for ‘hist’
clusterStats: no visible binding for global variable ‘median’
```
5) Follow this advice:
```
Consider adding
  importFrom("grDevices", "dev.off", "pdf", "rgb")
  importFrom("graphics", "abline", "axis", "box", "hist", "image", "par")
  importFrom("stats", "as.dist", "confint", "cor", "cutree", "dist",
             "lm", "median", "na.omit", "quantile")
  importFrom("utils", "combn", "read.csv", "write.csv")
to your NAMESPACE file.
```
6) Here is the very clear note about the package not having an evaluated vignette:
```
* checking files in ‘vignettes’ ... NOTE
Package has no Sweave vignette sources and no VignetteBuilder field.
```
7) error in MetaCyto-Ex.R
I can reproduce this error on my machine when running R CMD check:
```
* checking examples ... ERROR
Running examples in ‘MetaCyto-Ex.R’ failed
The error most likely occurred in:
> ### Name: autoCluster.batch
...
> cluster_label=autoCluster.batch(preprocessOutputFolder="Example_Result/preprocess_output",
+                                 excludeClusterParameters=excludeClusterParameters,
+                                 labelQuantile=0.95,
+                                 clusterFunction=flowHC)
Clustering , study ID =  SDY736_FCM-1 
Error in readFCSgetPar(x, paste("$P", 1:nrpar, "B", sep = "")) : 
  Parameter(s) $P1B not contained in 'x'
```
The error message is pretty clear. You need to run R CMD build and R CMD check in addition to BiocCheck; they check different things.

Please fix the problems listed above, run R CMD build and check locally and then bump the version. If the Single Package builder does not automatically run a new build, my guess is something is wrong with your webhook as Lori mentioned above. Please re-read the instructions and be sure that is set up properly.

Valerie

**Comment by vobencha** [comment] 2017-06-26 03:07
Just checking in. Are you planning to submit a new version?
Valerie

**Comment by hzc363** [comment] 2017-06-26 04:16
Yes，still working on it. Thanks for checking.

**Comment by vobencha** [comment] 2017-07-13 04:36
If we don't have a new version by July 21 I'll close this issue. You can always open a new issue if you decide to resubmit.
Valerie

**Comment by vobencha** [comment] 2017-07-24 12:17
Closing this issue due to inactivity.
Valerie

**Comment by hzc363** [comment] 2017-09-05 18:54
Hi, Valerie @vobencha 
I submitted my package (MetaCyto) a few months ago. At that time, the package was not accepted and the issue was closed. I would like to re-submit my package. 

I can't find a way to re-open this issue. Could you please re-open it?

Thank you very much. 
ZIcheng

**Comment by vobencha** [comment] 2017-09-05 19:30
I've reopened the issue.

**Comment by hzc363** [comment] 2017-09-06 00:00
Dear Bioconductor reviewer,

I pushed a new version of my package for check and get this error message:

> Error: processing vignette 'MetaCyto_Vignette.Rmd' failed with diagnostics:
> Parameter(s) $P1B not contained in 'x'

I have encountered similar error messages in my previous pushes. However, I could not reproduce this error on my own computer. I updated all the dependencies to the current version and checked my package on Mac, Linux, and windows. In all cases, my package and vignette were built with no error.  

I have struggled with this error for some time and really need your help.  To help me learn more about the error,  could you please run this short script on the Bioconductor machine and let me know if you encounter any error? Also, can you tell me the version of the "flowCore" package installed on the Bioconductor machine? I really appreciate your help. 

```
library(flowCore)
dat = as.matrix(iris[,1:4])
dat = flowFrame(dat)
write.FCS(dat,"dat.fcs")
dat = read.FCS("dat.fcs")
```
Thanks
Zicheng

**Comment by hzc363** [comment] 2017-09-11 16:28
Hi, Valerie @vobencha

I pushed a new version of my manuscript 4 days ago. The bioc-issue-bot received it and started a build. I did not get results back. Just wondering if anything is wrong with my push?

Thank you
Zicheng

**Comment by lshep** [comment] 2017-09-11 16:34
Sorry. We were making updates at that time which might have interrupted your build.  I will manually create a build, you should receive a report shortly.

**Comment by vobencha** [comment] 2017-09-11 16:38
Thanks @lshep .

**Comment by vobencha** [comment] 2017-09-11 16:45
@hzc363 , here is the output your requested.
```
> library(flowcore)
Error in library(flowcore) : there is no package called ‘flowcore’
> library(flowCore)
> library(flowCore)
> dat = as.matrix(iris[,1:4])
> dat = flowFrame(dat)
> write.FCS(dat,"dat.fcs")
[1] "dat.fcs"
Warning message:
In write.FCS(dat, "dat.fcs") :
  'write.FCS' is not fully tested and should be considered as experimental.
> dat = read.FCS("dat.fcs")
Error in readFCSgetPar(x, paste("$P", 1:nrpar, "B", sep = "")) : 
  Parameter(s) $P1B not contained in 'x'
Parameter(s) $P2B not contained in 'x'
Parameter(s) $P3B not contained in 'x'
Parameter(s) $P4B not contained in 'x'
```

Here is my sessionInfo():
```
> sessionInfo()
R version 3.4.1 Patched (2017-07-24 r72962)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Fedora 24 (Workstation Edition)

Matrix products: default
BLAS: /home/vobencha/R/R-dev/R-3-4-branch/lib/libRblas.so
LAPACK: /home/vobencha/R/R-dev/R-3-4-branch/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flowCore_1.43.6

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12        lattice_0.20-35     matrixStats_0.52.2 
 [4] mvtnorm_1.0-6       corpcor_1.6.9       rrcov_1.4-3        
 [7] grid_3.4.1          stats4_3.4.1        pcaPP_1.9-72       
[10] graph_1.55.0        robustbase_0.92-7   Biobase_2.37.2     
[13] DEoptimR_1.0-8      parallel_3.4.1      compiler_3.4.1     
[16] BiocGenerics_0.23.0 cluster_2.0.6    
```

**Comment by vobencha** [comment] 2017-09-11 16:47
You can see what package versions are installed on the devel build machine here:
http://www.bioconductor.org/checkResults/devel/bioc-LATEST/

**Comment by hzc363** [comment] 2017-09-11 16:53
Thank you! @vobencha  Now I know where the error comes from. Although I can't reproduce the error, I will try to fix so that it can pass the check.

**Comment by hzc363** [comment] 2017-09-26 15:58
@vobencha 

Hi, the check returned OK for my package. Just wondering what I need to do to move things forward.

Thank you
Zicheng

**Comment by vobencha** [comment] 2017-09-26 19:10
Please explain how you've addressed all issues raised in https://github.com/Bioconductor/Contributions/issues/375#issuecomment-328588402

**Comment by hzc363** [comment] 2017-09-29 20:56
Dear @vobencha , 

I have modified my package MetaCyto to address the following issues:

**1. MetaCyto did not have a functional vignette.**

I have added “VignetteBuilder: knitr” in the Description file to enable vignette building. 

**2.  MetaCyto’s title should not end in a period.**

I have removed the period.

**3. No visible global definition for several functions, such as “cutree” and “hist”.**

These functions are defined in the “stats” package. I have added it to my NAMESPACE

**4. Several functions need to be added into namespace (similar problem as in 3).** 

I have imported these functions in NAMESPACE.

**5. package not having an evaluated vignette**
I have added “VignetteBuilder: knitr” in the Description file to enable vignette building. 

**6. An error occurred  when evaluating the examples.** 
The error happens when reading fcs files from disc. I added a line of code to ensure the files can be read by the “read.FCS” function. The error is eliminated in the current version of MetaCyto.

**Comment by hzc363** [comment] 2017-10-09 17:31
Dear @vobencha,

I explained how all issues were addressed in my previous comment.  Please let me know what I need to do to move forward. 

Thank you
Zicheng

**Comment by vobencha** [comment] 2017-10-10 02:57
Hi,

Nice job with your man pages - thanks for including examples on all pages. Just a few comments/suggestions below.

1) Please remove LazyData = true. In our experience this has only caused problems - it makes packages with large data very slow to load.

2) What is the inst/extdata/NEWS.rtf file for?

3) The built tarball must be <= 4MG on disk. See http://www.bioconductor.org/developers/package-guidelines/#correctness.
```
biocbuild@malbec1:~/sandbox$ du -sh MetaCyto
14M    MetaCyto
```
Valerie

**Comment by hzc363** [comment] 2017-10-10 22:53
Hi, @vobencha 

Thank you for the comments. I removed the LazyData = true in the DESCRIPTION file and the NEWS.rtf file. 

The MetaCyto folder from GitHub is larger than 4MB because it has all the commit histories.  The tarball after built is about 1MB. 

```
PEDS-7TPG8WP-LT:Local_Projects zichenghu$ ls -lh MetaCyto_0.99.7.tar.gz
-rw-r--r--  1 zichenghu  staff   1.0M Oct 10 15:21 MetaCyto_0.99.7.tar.gz
```

**Comment by hzc363** [comment] 2017-10-25 16:39
Hi, @vobencha,

Please see my last comment for responses to your review comments.  Let me know how to move things forward. 

Thank you. 
Zicheng

**Comment by vobencha** [comment] 2017-10-25 17:33
Thanks for making the changes. And yes, you're right, the built tarball is only ~1MB. Thanks for pointing that out. The package looks good and is approved.

**Comment by vobencha** [comment] 2017-10-25 20:48
I'm not sure why this issue got closed. Maybe I did that accidentally. We should get an autoresponse from the bot when I marked the package as accepted.

**Comment by vobencha** [comment] 2017-10-25 20:50
My mistake. Looks like we got the appropriate response and Martin closed the issue.

**Comment by vobencha** [comment] 2017-10-25 20:52
Nope. Wrong again. Leaving this as is until Martin or Lori look at it.

**Comment by mtmorgan** [comment] 2017-10-25 21:50
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hzc363.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"MetaCyto\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MetaCyto

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

**Closed by mtmorgan** 2017-10-25 21:50 UTC
Labels: 3a. accepted, OK
