### ISSUE TITLE
sarks

### ISSUE THREAD

**Issue by denniscwylie** [Bioconductor/Contributions#1373] opened 2020-02-14 15:26 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/denniscwylie/sarks

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-02-14 18:08
Please provide an informative Title: and Description: (like a paper title and abstract) so that users know exactly what your package does, how it can be, used, perhaps how it differs from other available solutions, and how it integrates into typical Bioconductor data modalities / work flows.

@Kayla-Morrell will provide a review after this issue and any others generated by the automatic builder are addressed.

**Comment by denniscwylie** [comment] 2020-02-15 17:32
Is there any way to get a better sense of what might be causing the windows-only failure to build the Sweave vignette pdf? I'm able to build this on my own Windows 10 machine from the github repo and it has not trouble on linux, while the error message seems...less than helpful:

* creating vignettes ... ERROR
--- re-building 'sarks-vignette.Rnw' using Sweave
Warning in system(paste(shQuote(texi2dvi), if (quiet) "--quiet" else "",  :
  running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\texify.exe" --quiet --pdf "sarks-vignette.tex" --max-iterations=20 -I "C:/Users/biocbuild/bbs-3.11-bioc/R/share/texmf/tex/latex" -I "C:/Users/biocbuild/bbs-3.11-bioc/R/share/texmf/bibtex/bst"' had status 1
Error: processing vignette 'sarks-vignette.Rnw' failed with diagnostics:
Failed to locate 'texi2pdf' output file 'sarks-vignette.pdf' for vignette with name 'sarks-vignette' and engine 'utils::Sweave'. The following files exist in working directory 'C:\Users\pkgbuild\AppData\Local\Temp\RtmpSKmUHv\Rbuild25146a662fca\sarks\vignettes': 'sarks-vignette-block-info.pdf' (18810 bytes), 'sarks-vignette-yhat-plot.pdf' (25484 bytes), 'sarks-vignette.Rnw' (56885 bytes), 'sarks-vignette.tex' (67114 bytes), 'sarks.bib' (974 bytes)
--- failed re-building 'sarks-vignette.Rnw'

**Comment by denniscwylie** [comment] 2020-02-17 15:19
Given that I'm not having any trouble building this package on either windows or latex on my end (and that it builds fine on malbec2 as well), I just wanted to check if it might be possible that there is a problem in the windows (tokay2) MiKTeX texify process? Based on the build report, it appears that the files:

sarks-vignette-block-info.pdf' (18810 bytes), 'sarks-vignette-yhat-plot.pdf' (25484 bytes), 'sarks-vignette.Rnw' (56570 bytes), 'sarks-vignette.tex' (66979 bytes), 'sarks.bib' (974 bytes)

are all the correct size, indicating to me that the Sweave process has executed correctly but that there is some problem building the pdf from the latex document on tokay2.

Thank you again!
--Dennis

**Comment by Kayla-Morrell** [comment] 2020-02-19 16:48
@denniscwylie - I'm looking into this issue and hope to have an answer for you soon.

Best,
Kayla

**Comment by denniscwylie** [comment] 2020-02-26 15:03
Hi @Kayla-Morrell, just checking in to see if there is any update.

Thanks again!
--Dennis

**Comment by Kayla-Morrell** [comment] 2020-02-26 18:37
@denniscwylie - Sorry for the delayed response, I had to ask some others on the team about this issue. We seem to think this is something on our side, so we will continue to work on the issue. But in the mean time, since you get a clean build on the Linux builder I will go a head and review your package. I should have a review posted here in the next few days.

Best, 
Kayla

**Comment by denniscwylie** [comment] 2020-02-27 00:56
@Kayla-Morrell - Thank you! I'll keep an eye out for the review.

Hope you're doing well,
--Dennis

**Comment by Kayla-Morrell** [comment] 2020-03-02 15:29
Hello @denniscwylie,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The organization of the repo could use some work.
	- What is the purpose of the 'examples/' directory?
	- There should be a single top README.md file that explains the extra 
	details, including installation instructions. There are a few other top 
	level .md files (INSTAlL.md, sarks_vignette.md, and user_guide.md) that 
	should be condensed into one file and/or removed.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to 'false'. We find that when this is 
'true' it can slow down the loading of packages, especially those with large 
data.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
	- DifferentialExpression, DifferentialPeakCalling

- [ ] SUGGESTION: We strongly encourage using the 'BugReports:' tag which 
includes the relevant link to Github for reporting Issues.

## NAMESPACE

- [ ] SUGGESTION: Since you are using roxygen2 in your function documentation, 
I would suggest looking into `@importFrom` and even `@import` to help simplify 
the `package::function()` calls in your code. Once you import the functions, 
you wouldn't have to necessarily preface the function call with the pacakage 
name.

## Vignette

- [ ] REQUIRED: Before calling `library(sarks)`, there should be some code that 
shows how to download the package from Bioconductor. The code should look 
something like the following, and should include `eval = FALSE`,

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("sarks")
```

- [ ] REQUIRED: At line 362, you include a section of code that is not echoed 
and the results are hidden. This isn't best practice because if this is 
something the user needs to run the same results you did in the vignette, they 
won't know to run this command. Either make this visible or remove it from the 
code.

- [ ] REQUIRED: There should be final section named 'Session Info' that includes 
`sessionInfo()`.

## Man pages

- [ ] REQUIRED: The data man pages need a bit more detail about the format of 
the data, such as length or dimensions.

## R code

- [ ] REQUIRED: There should be no use of 'seed' within the R functions. 
Regardless if it is an optional argument, if the user requires reproducability 
they can call `set.seed()` before using the function. 

- [ ] REQUIRED: Lines 476 and 477, avoid the use of direct slot access with `@`, 
instead an accessor method should be used.

- [ ] SUGGESTION: Consider shorter lines. There are 33 lines that are > 80 characters 
long.

Best,
Kayla

**Comment by denniscwylie** [comment] 2020-03-02 17:38
Hi @Kayla-Morrell,

Thank you for the rapid review! I'm planning to work on the changes and to have the updates made as quickly as possible, but I did want to check back regarding a couple of the required changes first:

- **Regarding the optional seed arguments in the R functions:** these are included because the random permutations are generated and analyzed in the underlying java implementation of the fundamental sarks algorithm and data structures for efficiency. I don't believe running set.seed in R would work to establish reproducibility in this case, so I would request that these seed arguments be allowed in this case if at all possible!
- **Regarding the organization of the repo as far as the examples directory:** this contains a few slightly larger data files relevant to the published sarks paper which I'd like to keep up on github; these are omitted from the R package using .Rbuildignore so as to keep the package from getting cluttered with unnecessary large files.
  - Additionally both the user_guide.md and some of the files in the examples directory are focused on direct command-line usage of the underlying java code; these are all excluded from the R package in .Rbuildignore, but I'd like to leave them on github for those who would like to use the java code directly.
  - I'm happy to merge the INSTALL.md file into the README.md file as suggested and will do this when I submit the updated version.
  - If necessary I can remove the sarks-vignette.md file (which is again excluded from the R package in .Rbuildignore), though I thought it might be convenient for some users to refer to directly from the github page especially while waiting for the bioconductor version of the package to be available.

Thank you again, and I hope you're doing well!
--Dennis

**Comment by Kayla-Morrell** [comment] 2020-03-05 14:35
@denniscwylie - Thank you for clarifying on the two points above. I'll have to investigate a bit about the optional seed argument, so you can keep as is for now while I figure that out. The explanation you provide for the repo organization is fine. I look forward to re-reviewing the changes once they are made.

Best,
Kayla

**Comment by denniscwylie** [comment] 2020-03-06 17:15
Hi @Kayla-Morrell 

I just pushed the updates to sarks; looks like it still builds fine on the linux system but has the same weird latex to pdf conversion hiccup on the windows system.

Summarizing the updates:

- **General package development**
  - REQUIRED: INSTALL.md file merged with README.md
- **DESCRIPTION**
  - REQUIRED: 'LazyData:' now set to 'false'.
  - SUGGESTION: Added DifferentialExpression to biocViews; I don't think the standard usage of DifferentialPeakCalling covers the type of peak calling done in sarks, so have not added it here.
  - SUGGESTION: added 'BugReports:' tag.
- **NAMESPACE**
  - SUGGESTION: now using @importFrom to simplify package::function() calls.
- **Vignette**
  - REQUIRED: added installation section to vignette
  - REQUIRED: all code chunks now visible in vignette (removed echo=FALSE chunk)
  - REQUIRED: added 'Session Info' section including sessionInfo() call.
- **Man pages**
  - REQUIRED: added detail about the format of data (length, nchar, etc.).
- **R code**
  - REQUIRED: replaced use of direct slot access using @ with accessor method.
  - SUGGESTION: only lines remaining > 80 characters long are the vignette title line and lines in documentation including a long URL string.

Thank you again!
--Dennis

**Comment by Kayla-Morrell** [comment] 2020-03-06 18:48
@denniscwylie - Perfect, I'll take a look at the updates and get back to you early next week with any further requirements.

Thank you!
Kayla

**Comment by denniscwylie** [comment] 2020-03-13 12:52
Hi @Kayla-Morrell, just checking in to see if there is any update.

Thanks again!
--Dennis

**Comment by Kayla-Morrell** [comment] 2020-03-13 18:02
@denniscwylie - I've reviewed your changes, everything looks good so I'm more than happy to accept the package. I've also checked with others on the team and your argument to keep the seed option is valid, so nothing needs to be changed for that. We are still looking into the Windows error, but it seems to be something on our end that we need to debug. 
Best,
Kayla

**Comment by denniscwylie** [comment] 2020-03-13 18:10
@Kayla-Morrell Thank you again!

Hope you are doing well,
--Dennis

**Comment by mtmorgan** [comment] 2020-03-24 13:51
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/denniscwylie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sarks")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sarks

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2020-03-24 18:56
oops, this needs to be opened because of https://github.com/Bioconductor/Contributions/issues/1382#issuecomment-603443619

**Comment by denniscwylie** [comment] 2020-03-24 19:05
Hi @mtmorgan,

Just updated the repo---let me know if anything else needs to be done!

Thanks,
Dennis

**Comment by mtmorgan** [comment] 2020-03-24 19:18
Thanks (also for catching my mistake with TAPseq -- I don't know how you did that!) Unfortunately examples/mo2015_upstream_seqs.fa.gz (and maybe others?) is also too large...

**Comment by denniscwylie** [comment] 2020-03-24 19:36
Hi again @mtmorgan,

Just removed that file as well---I don't believe there are any other files which should surpass 5 MB.

Cheers,
Dennis

**Comment by mtmorgan** [comment] 2020-03-24 19:54
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/denniscwylie.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sarks")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sarks

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-03-24 19:54 UTC
Labels: 3a. accepted, ERROR

**Comment by mtmorgan** [comment] 2020-03-24 19:58
Thanks for your help! As a reward you get to be the first (in a while) new package to be tweeted! https://twitter.com/Bioconductor/status/1242540488814714886

**Comment by denniscwylie** [comment] 2020-03-24 20:04
Thanks! Hope you're doing well,

Cheers,
Dennis
