### ISSUE TITLE
Submission of package exomePeak2 to bioconductor

### ISSUE THREAD

**Issue by ZW-xjtlu** [Bioconductor/Contributions#1310] opened 2019-11-27 06:03 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/ZW-xjtlu/exomePeak2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2019-11-27 14:00
What's the relationship between this package and the defunct package exomePeak?

**Comment by ZhenWei10** [comment] 2019-11-28 01:34
Hi Martin, 
exomePeak2 is a new package that is independent of the package exomePeak.

**Comment by mtmorgan** [comment] 2019-11-28 20:47
I'm concerned that exomePeak and its users were abandoned, and that the same fate waits users of exomePeak2. Is there a reason why exomePeak is not being updated?

**Comment by ZhenWei10** [comment] 2019-11-29 00:32
Hi Martin,

We have made substantial changes in almost every data processing steps for exomePeak2, and the entire package is recreated. We think it will be good to create 2 different packages to document 2 different methods. I will update the exomPeak package soon and make it available for the users again.

**Comment by Kayla-Morrell** [comment] 2019-12-12 16:55
Hello @ZhenWei10 - In order to properly review the package there needs to be a clean build report (no ERROR, WARNING, or TIMEOUT, as well as limited NOTE). Please work on making the necessary changes to your package.

Best,
Kayla

**Comment by ZW-xjtlu** [comment] 2019-12-23 09:43
Hi Kayla,

Sorry for the incorrect building report, the package is now cleared with no errors and warnings. Please help me generate the build and check report on the Bioconductor server again.

Sincerely,
Zhen

**Comment by ZW-xjtlu** [comment] 2019-12-23 09:46
Hi Kayla,

The errors and warnings in the report are now fixed, would you please help me to review the package again.
Please inform me if you have encountered any other issue.

Best wishes,
Zhen

**Comment by Kayla-Morrell** [comment] 2019-12-24 12:41
@ZW-xjtlu - Please be sure you have your web hook set up as per the instructions [here](https://github.com/Bioconductor/Contributions/issues/1310#issuecomment-559867707). If the web hook is set up properly then be sure you commit and push a bump in the version number of the package in the DESCRIPTION, this is what our builder looks for to trigger a new build. Please try these two solutions, if for some reason you do not get a build report after then I can investigate further.

Best,
Kayla

**Comment by ZW-xjtlu** [comment] 2019-12-25 06:50
Dear Kayla,

Thanks for your detailed instructions. I fixed the issue by changing the version number in DESCRIPTION.
Let’s check the build report for this time.

Best wishes,
Zhen

**Comment by ZW-xjtlu** [comment] 2019-12-26 04:44
@Kayla-Morrell  It seems that the build report is not automatically triggered by my version bump. Could it due to my user name on Github is changed from ZhenWei10 to ZW-xjtlu? Therefore, the new package repository should be: https://github.com/ZW-xjtlu/exomePeak2 

Best,
Zhen

**Comment by Kayla-Morrell** [comment] 2020-01-02 13:47
@ZW-xjtlu - The change to the Github user name is most likely what is causing this issue since the SPB is trying to grab changes from the ZhenWei10/exomePeak2 repo. I will work on making the change on our side so that you can get a proper build report.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2020-01-06 13:24
Hey @ZW-xjtlu,

We have changed the repository name in our database but you will need to update the repository link [here](https://github.com/Bioconductor/Contributions/issues/1310#issue-529136099). After that, build should be triggered.

Best,
Kayla

**Comment by ZW-xjtlu** [comment] 2020-01-06 13:44
Hi @Kayla-Morrell 

I have updated the repository link, thanks for helping me with this issue.

Best wishes,
Zhen

**Comment by Kayla-Morrell** [comment] 2020-01-06 13:56
@ZW-xjtlu - Please try bumping the version number to see if a build is triggered.

**Comment by ZW-xjtlu** [comment] 2020-01-06 14:00
@Kayla-Morrell The build is now triggered by version bump. Thanks, the issue is fixed

**Comment by Kayla-Morrell** [comment] 2020-01-23 15:49
Hello @ZW-xjtlu, 

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: Please remove the top level file 'exomePeak2_0.99.pdf'.

- [ ] REQUIRED: There should only be 'README.md' (the 'README.Rmd' file should 
be removed), and the figures in README_files belong in an 'inst/figures/' 
directory to be sure they included in the package.

## DESCRIPTION

- [ ] REQUIRED: The 'Title:' field is malformed, it should not end in a period.

- [ ] REQUIRED: 'LazyData:' should be set to 'false'. When this field is 'true' 
we find it can slow down the loading of a package, especially if it includes 
data.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        ExomeSeq, Coverage, Normalization, Preprocessing, ImmunoOncology,
        DifferentialExpression

- [ ] REQUIRED: The package 'methods' is used but not declared.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with a
relevant link to Github Issues.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an 
entire package, as this can slow down the loading of your package. However if 
there are many functions from a single package, `import()` is okay but please 
make the number of these as minimal as possible. It is also not necessary to 
have both `import()` and `importFrom()` for the same package.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: All the data files in 'inst/extdata/' need to be documented. 
This is done with an 'inst/script/' directory and it will be explained in more 
detail in a later point.

## Vignettes

- [ ] REQUIRED: The author information doesn't look formatted correctly. Try 
this in the metadata instead:

```
author:
- name: First Author
  affiliation:
  - First affiliation
  - Second affiliation
  email: first@author.com
- name: Second Author
  affiliation:
  - First affiliation
  - Second affiliation
  email: second@author.com
```

- [ ] REQUIRED: Line 21 is not needed since you indicated in line 15 that the 
vignette engine is rmarkdown.

- [ ] REQUIRED: For the users to reproduce the same results you have in the 
vignette I would suggest not hiding the `set.seed()` from the user (line 25). 
Instead I would set the seed in your first visible code chunk, for instance in 
the chunk of code starting at line 36. This way the user can set the same seed
as you did and get similar results.

- [ ] REQUIRED: There should be an 'Introduction' section that introduces the 
package.

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to 
the user how to install the package from _Bioconductor_. The code should look 
something like the following and include `eval = FALSE` in the code chunk:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("exomePeak2")
```

## Man pages

- [ ] SUGGESTION: For any function that is documented but isn't exported I 
suggest adding the tag `@keywords internal` so that they are removed from the
documenation index.

*MeripBamFileList*

- [ ] REQUIRED: Man pages describing new classes must be very detailed on the 
structure and what type of information is stored.

## inst/script

- [ ] REQUIRED: The scripts in this directory can vary. Most importantly if data 
was included in the `inst/extdata/` directory, a related script must be present 
in this directory documenting very clearly how the data was generated. It should 
include source urls and any important information regarding filtering or 
processing. It can be executible code, sudo code, or a text description. A user 
should be able to download and roughly reproduce the file or object that is 
present as data.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

## R code

- [ ] REQUIRED: Consider clarifying how 25 objects are initialized. Maybe they are
part of a data set loaded with data(), or perhaps part of an object referenced
in with() or within().
        function (object)
        call_peaks_with_GLM (relevel)
        consDESeq2_DM (qbinom)
        consDESeq2_M (qbinom)
        convertTxDb (seqlengths)
        ctest (pbinom)
        decision_deseq (P_cut)
        exome_bins_from_txdb (seqlengths<-)
        exome_bins_from_txdb (seqlengths)
        exomePeak2 (is)
        exomePeak2 (capture.output)
        exonPlot (log2_exon_lengths)
        exonPlot (region)
        flank_on_exons (seqlengths<-)
        flank_on_exons (seqlengths)
        format_argg (package.version)
        GC_content_over_grl (is)
        GC_content_over_grl (startIndex)
        GC_content_over_grl (DNAStringSet)
        GC_content_over_grl (Hsapiens)
        reads_five_POS (is)
        reads_five_POS (as)
        reads_five_POS_rev (is)
        reads_five_POS_rev (as)
        scanMeripBAM (new)
        SummarizedExomePeak (new)

Adding these `importFrom` for the effected function should help to clear some of 
these issues up (they will also add them to the NAMESPACE file, just be sure 
the DESCRIPTION Imports field contains these packages).
        importFrom("methods", "as", "is", "new")
        importFrom("stats", "pbinom", "qbinom", "relevel")
        importFrom("utils", "capture.output", "read.table", "write.csv")

- [ ] SUGGESTION: For formatting purposes, consider shorter lines. There are 
1093 lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting purposes, consider multiples of 4 spaces for 
line indents. There are 1806 lines are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2020-02-12 03:22
@ZW-xjtlu - Just checking in to see if there has been any progress made on the review I posted.

**Comment by Kayla-Morrell** [comment] 2020-03-02 16:28
@ZW-xjtlu - If there is no progress on the package development in the next two weeks we will be closing for inactivity.

**Comment by ZW-xjtlu** [comment] 2020-03-05 00:48
@Kayla-Morrell Dear Kayla, sorry for the late reply. I couldn't be able to update the package at GitHub until now, I think it might due to the internet connection problem from my home in China.  I will implement the review comment as soon as possible.

**Comment by ZW-xjtlu** [comment] 2020-03-13 03:49
@Kayla-Morrell Hi, I have encountered a build error on the Bioconductor server that does not occur before. 

Below is the error message:
```
Quitting from lines 57-79 (Vignette_V_0.99.Rmd) 
Error: processing vignette 'Vignette_V_0.99.Rmd' failed with diagnostics:
BSgenome.Hsapiens.UCSC.hg19 package is not currently installed.
  You first need to install it, which you can do with:
      library(BiocManager)
      install("BSgenome.Hsapiens.UCSC.hg19")
--- failed re-building 'Vignette_V_0.99.Rmd'

SUMMARY: processing the following file failed:
  'Vignette_V_0.99.Rmd'

Error: Vignette re-building failed.
Execution halted
```
I don't have an error on the Linux server, and I have passed the check and build.
But for the windows server, it reports the error above because its has not installed the package BSgenome.Hsapiens.UCSC.hg19.

The BSgenome package is essential for a standard analysis in exomePeak2, 
and it is by default retrieved by getBSgenome(), and the default input is "hg19".
In the past, this function will trigger automatic download if the server haven't installed the queried BSgenome package.  But this function will report errors since the last update if it does not install package "hg19".

This setting will make it very difficult to demonstrate functions in exomePeak2 which rely on the genome sequences.

Do you have any suggestions on how to overcome this issue?

**Comment by Kayla-Morrell** [comment] 2020-03-13 14:10
@ZW-xjtlu - We were doing some updating to the windows builder yesterday and you might have caught it during a down time. You can try doing a version bump to trigger another build. If it isn't cleared up on the next build then I will investigate further.

**Comment by ZW-xjtlu** [comment] 2020-03-14 09:26
> @ZW-xjtlu - We were doing some updating to the windows builder yesterday and you might have caught it during a down time. You can try doing a version bump to trigger another build. If it isn't cleared up on the next build then I will investigate further.

@Kayla-Morrell  Dear Kayla, the error message is resolved,  thanks for helping me with it. You could now check my package implemented with the previous comments.

**Comment by Kayla-Morrell** [comment] 2020-03-16 15:15
@ZW-xjtlu - Thank you for make the necessary changes. I have just one more requirement before I can accept the package. Please see the note below and let me know when you are ready for me to review the change.

## NEWS

- [ ] REQUIRED: Thank you for including the NEWS file unfortunately it isn't
formated properly. See the following link for help with formating,
https://bioconductor.org/developers/package-guidelines/#news

Best,
Kayla

**Comment by ZW-xjtlu** [comment] 2020-03-18 03:27
@Kayla-Morrell 
Hi Kayla, I have changed the format of the NEWS file. 
Please tell me if more adjustment is required.
Best regards,
Zhen

**Comment by Kayla-Morrell** [comment] 2020-03-19 16:13
@ZW-xjtlu - Thank you for formatting the NEWS file. I just need you to do a version bump to get rid of the 'Version Bump Required' tag. 
Best,
Kayla

**Comment by mtmorgan** [comment] 2020-03-24 13:51
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ZW-xjtlu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("exomePeak2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/exomePeak2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-03-24 13:51 UTC
Labels: 3a. accepted, OK
