### ISSUE TITLE
immunogenViewer

### ISSUE THREAD

**Issue by kathiwaury** [Bioconductor/Contributions#3446] opened 2024-05-31 16:10 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kathiwaury/immunogenViewer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2024-06-07 13:10
I don't think your current custom citation file will display right on our
  landing pages as general a citation file must be parsable by
  `readCitationFile` in R.  There is also the warning in R CMD check

```
Found the following CITATION file in a non-standard place:
  CITATION.cff
Most likely 'inst/CITATION' should be used instead.

```

**Comment by hpages** [comment] 2024-07-18 23:34
Hi @kathiwaury,

The package and vignette look good. Only one minor cosmetic detail.

Functions print unnecessary success messages. For example:

    > proteinDF <- getProteinFeatures("P55087")
    [1] "Successfully created protein dataframe for UniProt P55087."
    
    > proteinDF <- addImmunogen(proteinDF, start=10, end=30, name="A12")
    [1] "Successfully added immunogen 'A12' to the protein dataframe."
    
    > proteinDF <- addImmunogen(proteinDF, seq="RFKEAFSKAAQQTKGSYMEVEDNRSQVETDD", name="HPA")
    [1] "Successfully added immunogen 'HPA' to the protein dataframe."

This is not really useful. The conventional approach is to raise errors with informative error messages (which you do), but to not print any message in case of success. Exceptions can be made to the "no message on success" rule when one wants to display progress of a long multi-step task. However note that in this case the messages should be displayed with `message()` instead of `print()` so that the user can silence the code by wrapping it in `suppressMessages()`.

That will be all! :smiley: 

Let me know if you have questions.

Best,
H.

**Comment by kathiwaury** [comment] 2024-07-22 18:09
Hi @hpages,

Thanks a lot for reviewing! 

I have removed the success messages as you suggested. I have also fixed an issue with one of the features and changed names to be more informative in the plot. 

All checks ran fine on my side but I get this warning from the Bioconductor Package Builder now:

`* Checking vignette directory...`
    `* WARNING: Package listed as VignetteEngine or VignetteBuilder but
      not currently Suggested.`

I have both `knitr` and `rmarkdown` listed in the Suggest field, so not really sure how to solve this warning. Could you help with this?

Many thanks,

Kathi

**Comment by hpages** [comment] 2024-07-30 18:29
Hi @kathiwaury,

Thanks for making these changes.

I can't reproduce this warning on my laptop where I have the latest version of **BiocCheck** (1.41.9). Note that the SPB was using **BiocCheck** 1.41.6 at the time the report was generated, so this strongly suggests that the warning was a false positive that has since been addressed in **BiocCheck**.

Please remove the `LazyData: false` line from your `DESCRIPTION` file.

Once you've done this, the package will be good to go.

Best,
H.

**Comment by kathiwaury** [comment] 2024-07-31 13:12
Hi @hpages,

the `LazyData` line is deleted. Happy to hear that the package is good to go. Thanks again!

Best,

Kathi

**Comment by hpages** [comment] 2024-08-05 01:02
Thanks!

**Comment by lshep** [comment] 2024-08-05 14:03
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kathiwaury.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("immunogenViewer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/immunogenViewer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-08-05 14:03 UTC
Labels: OK, 3a. accepted
