### ISSUE TITLE
SFEData, SpatialFeatureExperiment, and Voyager

### ISSUE THREAD

**Issue by lambdamoses** [Bioconductor/Contributions#2719] opened 2022-07-15 17:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pachterlab/SFEData

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-07-22 13:59
Will you be following the https://github.com/Bioconductor/Contributions#submitting-related-packages so that SpatialFeatureExperiment is in place for checking SFEData?

**Comment by vjcitn** [comment] 2022-07-22 14:02
I installed SpatialFeatureExperiment from pachterlab repo to check this package and it seemed fine.  You will need to submit SpatialFeatureExperiment too, as a related package.

**Comment by lshep** [comment] 2022-07-22 14:04
@vjcitn to have the interface for submitting related packages work correctly they can't submit it until the data package is already in review with a 'review in progress' tag (and therefore already initialized in the review process).  If it is good please proceed with the 'pre-check passed'

**Comment by lambdamoses** [comment] 2022-07-23 02:22
AdditionalPackage: https://github.com/pachterlab/SpatialFeatureExperiment

**Comment by lambdamoses** [comment] 2022-07-23 02:22
AdditionalPackage: https://github.com/pachterlab/Voyager

**Comment by vjcitn** [comment] 2022-08-04 17:36
Hi, bump your version numbers/commit/push to get a new build.

**Comment by Kayla-Morrell** [comment] 2022-09-06 18:18
Hello @lambdamoses - I'm working through the initial reviews of these packages. I wanted to check in and see how you wanted to handle the review process. Would you prefer working through one package at a time or would you rather I post all three reviews at the same time?

Best,
Kayla

**Comment by lambdamoses** [comment] 2022-09-06 18:29
I suppose one package at a time.

**Comment by Kayla-Morrell** [comment] 2022-09-06 20:04
@lambdamoses - Great, then below is the initial review of SFEData. The required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] SUGGESTION: We encourage using the 'BugReports' field and including the
  relevant link to GitHub for reporting issues.

## Vignette

- [ ] SUGGESTION: We encourage the use of `BiocStyle` for formatting. 
- [ ] REQUIRED: Add an 'Installation' section that demonstrates to the user how
  to download and load the package from Bioconductor. This code can be included
in an `eval = FALSE` code chunk.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 2 lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 14 lines that are not.

Best,
Kayla

**Comment by lambdamoses** [comment] 2022-09-06 22:36
> ## DESCRIPTION
> * [x]  SUGGESTION: We encourage using the 'BugReports' field and including the
>   relevant link to GitHub for reporting issues. (I also added URL in the DESCRIPTION file.)
> 
> ## Vignette
> * [x]  SUGGESTION: We encourage the use of `BiocStyle` for formatting.
> * [x]  REQUIRED: Add an 'Installation' section that demonstrates to the user how
>   to download and load the package from Bioconductor. This code can be included
>   in an `eval = FALSE` code chunk.
> 
> ## R code
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 2 lines that are > 80 characters long. (I can't locate those lines in the R code files. It's probably referring to the plain text in the vignette, which I think is fine since RStudio wraps the plain text.)
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 14 lines that are not. (I'm accustomed to indenting by 2 spaces.)

**Comment by Kayla-Morrell** [comment] 2022-09-07 16:09
@lambdamoses - Great, thank you for making those changes. I've looked them over and `SFEData` now looks good. Below is the initial review of SpatialFeatureExperiment. Again, the required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: In the README file the installation instructions should also
  include Bioconductor installation instructions.

## DESCRIPTION

- [ ] SUGGESTION: 'SpatialExperiment' is misspelled in the `Title` field.
- [ ] SUGGESTION: It is encouraged to include the `BugReports` field with
  relevant links to GitHub for reporting issues.

## Data

- [ ] REQUIRED: Raw data files should be included in the 'inst/extdata'
  directory. We also require documentation on these files in an 'inst/script/'
directory.
- [ ] REQUIRED: Documentation of the raw data is needed in the 'inst/script/'
  directory. The scripts in this directory vary. It's most important to include
how the data was generated and source information. It should include source URLs
and any key information regarding filtering or processing. It can be executable
code, sudo code, or a text description. Users should be able to download and
roughly reproduce the file or object that is present as data.
- [ ] REQUIRED: The 'data-raw' and 'inst/testdata' are not acceptable locations
  for data. I believe that the 'inst/testdata' belongs in the 'inst/extdata'
directory and the 'data-raw' belongs in the 'inst/script' directory. When moving
data to 'inst/extdata' you will access it using `system.file()` instead of
`readRDS()`.

## Vignette

- [ ] REQUIRED: Add an 'Installation' section that show to users how to download
  and load the package from Bioconductor. The instructions should be in an `eval
= FALSE` code chunk.

## Man pages

- [ ] SUGGESTION: The use of dontrun{} / donttest{} is discouraged and generally
  not allowed. However, if this is necessary than we prefer donttest{} over
dontrun{} since donttest{} requires valid R code while dontrun{} does not.

## R code

- [ ] REQUIRED: Unexported object imported by a ':::' call:
  'S4Vectors:::disableValidity'. See the note in ?':::' about the use of this
operator.
- [ ] REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` instead.
- [ ] REQUIRED: Avoid the use of `paste` in condition signals.
- [ ] REQUIRED: Avoid `supressWarnings`/`*Messages` if possible (found 1 times)
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 312 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 1240 lines that are not. 

Best,
Kayla

**Comment by lambdamoses** [comment] 2022-09-07 22:11
Question about using `:::`: I used `S4Vectors:::disableValidity` because I found `SingleCellExperiment` and `SpatialExperiment` using it, so I thought it's allowed. I also used some internal functions of `SingleCellExperiment` that I find useful. If it's not allowed, then what alternative do you suggest? Like copying and pasting the code for the internal functions?

**Comment by hpages** [comment] 2022-09-08 00:57
I'd say it's ok to ignore the `R CMD check` NOTE about `S4Vectors:::disableValidity`. In some rare situations one actually needs to temporarily disable validation of S4 objects but unfortunately the **methods** package doesn't provide a mechanism for that. A few Bioconductor packages use `S4Vectors:::disableValidity` already: **InteractionSet**, **miloR**, **NxtIRFcore**, **PhosR**, **SingleCellExperiment**, **SpatialExperiment**, **SpliceWiz**, and **TreeSummarizedExperiment**. Of course `S4Vectors:::disableValidity` should be exported and documented but that's on me.

**Comment by lambdamoses** [comment] 2022-09-08 01:21
I also used some internal functions of `SingleCellExperiment` though, like `SingleCellExperiment:::.get_internal_character`, which is used in the implementation of `reducedDims` in `SingleCellExperiment`, because the new field `colGeometries` in `int_colData` is implemented in a similar way as `reducedDims`. I just don't want to reinvent the wheel. But then if the internals of `SingleCellExperiment` change, my package will break. Then I suppose I'd better copy and paste the code from `SingleCellExperiment`? Suggestions?

`Voyager` uses some internal functions in `SpatialFeatureExperiment`; I suppose I can export them even though they're not meant for users.

**Comment by LiNk-NY** [comment] 2022-09-08 14:02
Hervé @hpages 
I could move it and document it in `BiocBaseUtils` as we did with `replaceSlots` > `setSlots`. 
Best,
Marcel

**Comment by hpages** [comment] 2022-09-08 23:28
@lambdamoses,

> But then if the internals of SingleCellExperiment change, my package will break.

You can also look at it the other way around: if they improve `SingleCellExperiment:::.get_internal_character`, or fix a bug in it, then your package will immediately benefit. Also note that if they break your package, it'll be in Bioc devel only, so it won't affect regular users and you'll have time to fix. That being said, `SingleCellExperiment:::.get_internal_character` is such a simple/small function that maybe it's not a big deal to just have your own copy in your package? It's a trade-off.

@LiNk-NY Sounds good. Almost everything in `S4Vectors/R/S4-utils.R` should probably make it to **BiocBaseUtils**. Plus all the stuff in `S4Vectors/R/show-utils.R` and most of the stuff in `S4Vectors/vector-utils.R`, `S4Vectors/integer-utils.R`, `S4Vectors/character-utils.R`, `S4Vectors/raw-utils.R`, and `S4Vectors/eval-utils.R`. But let's not discuss this here.

**Comment by lambdamoses** [comment] 2022-09-10 03:09
> ## General package development
> * [x]  REQUIRED: In the README file the installation instructions should also
>   include Bioconductor installation instructions.
> 
> ## DESCRIPTION
> * [x]  SUGGESTION: 'SpatialExperiment' is misspelled in the `Title` field.
> * [x]  SUGGESTION: It is encouraged to include the `BugReports` field with
>   relevant links to GitHub for reporting issues.
> 
> ## Data
> * [x]  REQUIRED: Raw data files should be included in the 'inst/extdata'
>   directory. We also require documentation on these files in an 'inst/script/'
>   directory.
> * [x]  REQUIRED: Documentation of the raw data is needed in the 'inst/script/'
>   directory. The scripts in this directory vary. It's most important to include
>   how the data was generated and source information. It should include source URLs
>   and any key information regarding filtering or processing. It can be executable
>   code, sudo code, or a text description. Users should be able to download and
>   roughly reproduce the file or object that is present as data.
> * [x]  REQUIRED: The 'data-raw' and 'inst/testdata' are not acceptable locations
>   for data. I believe that the 'inst/testdata' belongs in the 'inst/extdata'
>   directory and the 'data-raw' belongs in the 'inst/script' directory. When moving
>   data to 'inst/extdata' you will access it using `system.file()` instead of
>   `readRDS()`.
> 
> ## Vignette
> * [x]  REQUIRED: Add an 'Installation' section that show to users how to download
>   and load the package from Bioconductor. The instructions should be in an `eval = FALSE` code chunk.
> 
> ## Man pages
> * [x]  SUGGESTION: The use of dontrun{} / donttest{} is discouraged and generally
>   not allowed. However, if this is necessary than we prefer donttest{} over
>   dontrun{} since donttest{} requires valid R code while dontrun{} does not.
> 
> ## R code
> * [ ]  REQUIRED: Unexported object imported by a ':::' call:
>   'S4Vectors:::disableValidity'. See the note in ?':::' about the use of this
>   operator.
> * [x]  REQUIRED: Avoid `1:...`; use `seq_len()` or `seq_along()` instead.

Question: I did get rid of `1:...` and replaced them with `seq_len`. While I understand that `1:n` and `1:length(x)` may be dangerous as `n` and `length(x)` may be 0, all cases when I used `1:...` did not involve variables, only fixed numbers, for subsetting, like `1:3`. So is something like `1:3` still discouraged?
> * [ ]  REQUIRED: Avoid the use of `paste` in condition signals.

All cases when I used `paste` in `warning` or `stop` is to collapse multiple items to show, which is allowed per https://contributions.bioconductor.org/r-code.html?q=paste#end-user-messages
> * [ ]  REQUIRED: Avoid `supressWarnings`/`*Messages` if possible (found 1 times)

`suppressWarnings` is used in the `[` method for `SpatialFeatureExperiment`: `suppressWarnings(x <- callNextMethod())`, which calls the `[` method for `SpatialExperiment`. I need to suppress the warning here because the SFE method uses the `drop` argument in its unique way that does not apply to `SpatialExperiment` and `SingleCellExperiment`. I get this warning if the `drop` argument is used. The warning comes from `callNextMethod`, and the `drop` argument is used in the code after `callNextMethod`.
```
sfe_subset <- sfe[1:10, 1:10, drop = TRUE]
Node indices in the graphs are no longer valid after subsetting. Dropping all row and col graphs.
Warning message:
In .nextMethod(x = x, i = i, j = j, drop = drop) :
  'drop' ignored '[,SpatialFeatureExperiment,ANY,ANY-method'
```
> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 312
>   lines that are > 80 characters long.

I did some reformatting to shorten some lines, and the remaining ones over 80 characters long aren't that much longer than 80 characters.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 1240 lines that are not.

I usually and consistently indent by 2 spaces as in RStudio's default.

**Comment by Kayla-Morrell** [comment] 2022-09-21 15:37
@lambdamoses - Thank you for making the necessary changes to SpatialFeatureExperiment. Everything looks good. I wanted to check in to let you know that I'm finishing up my initial review of Voyager and should have it posted by the end of the week. Thank you for your patience during the review process.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2022-09-29 14:54
@lambdamoses - Below is my initial review of Voyager. Again, the required changes must be made while the suggested changes do not have to be (though we strongly encourage them). Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: In the README file the installation instructions should also
  include Bioconductor installation instructions.

## DESCRIPTION

- [ ] SUGGESTION: It is encouraged to include the `BugReports:` field with a
  relevant link to GitHub for reporting Issues.

## Data

- [ ] REQUIRED: The `inst/testdata` should be changed to `inst/extdata` and the
  `data-raw` directory should become `inst/script` since it seems that this file
documents the creation of the data file.

## Vignette

- [ ] SUGGESTION: I would rename the vignette file to something more meaningful
  then 'overview'.
- [ ] REQUIRED: There needs to be a vignette present within the package. Perhaps
  you have a subset of the larger vignette within the package and direct users
to the more indepth one if they want to learn more. 

## Man pages

- [ ] SUGGESTION: It is encouraged to include a package man page with an
  overview of the package and links to the main functions. Users should be able
to have a relevant page display with `?Voyager`.

## Unit tests

- [ ] REQUIRED: What is the purpose of the `_snaps/plot` directory?

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 87 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider mulitples of 4 spaces for 
line indents. There are 1225 lines that are not.

Best,
Kayla

**Comment by lambdamoses** [comment] 2022-10-04 18:36
I have written some new functionalities for both SFE and Voyager in addition to addressing the reviews.

> ## General package development
> * [x]  REQUIRED: In the README file the installation instructions should also
>   include Bioconductor installation instructions.
> 
> ## DESCRIPTION
> * [x]  SUGGESTION: It is encouraged to include the `BugReports:` field with a
>   relevant link to GitHub for reporting Issues.
> 
> ## Data
> * [x]  REQUIRED: The `inst/testdata` should be changed to `inst/extdata` and the
>   `data-raw` directory should become `inst/script` since it seems that this file
>   documents the creation of the data file.
> 
> ## Vignette
> * [ ]  SUGGESTION: I would rename the vignette file to something more meaningful
>   then 'overview'.
> * [x]  REQUIRED: There needs to be a vignette present within the package. Perhaps
>   you have a subset of the larger vignette within the package and direct users
>   to the more indepth one if they want to learn more.

I have written a shorter vignette, though I no longer link to SFEWorkshop because the user interface has changed. I'll link to a new website later.

> ## Man pages
> * [ ]  SUGGESTION: It is encouraged to include a package man page with an
>   overview of the package and links to the main functions. Users should be able
>   to have a relevant page display with `?Voyager`.

I don't really find that necessary since I myself rarely look at package man pages and go straight to the vignette or package website instead for overviews of packages I use.

> ## Unit tests
> * [x]  REQUIRED: What is the purpose of the `_snaps/plot` directory?

To unit test plotting functions. This directory contains SVG snapshots of plots as how they should look like, and the unit tests, using `vdiffr::expect_doppelganger`, compare the plot generated when the unit tests are run to the snapshots. If they don't match, then I can check the differences with a shiny app to see if the plotting functions have really been broken. However, `expect_doppelganger` tests are skipped on CRAN style checks by default since they're fragile as there may be inconsequential differences unnoticeable by eye from different systems, especially the ones involving `geom_sf` which depend on the system dependencies like GEOS. These tests are helpful locally.

> ## R code
> * [x]  SUGGESTION: For formatting reasons, consider shorter lines. There are 87
>   lines that are > 80 characters long.
> * [x]  SUGGESTION: For formatting reasons, consider mulitples of 4 spaces for
>   line indents. There are 1225 lines that are not.
> 
> Best, Kayla

**Comment by Kayla-Morrell** [comment] 2022-10-11 14:30
@lambdamoses - Thank you for making the necessary changes. I have reviewed them and everything looks good. I am more than happy to accept the packages. 

Best,
Kayla

**Comment by lshep** [comment] 2022-10-11 16:03
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lambdamoses.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SFEData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SFEData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment] 2022-10-11 16:03
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lambdamoses.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SpatialFeatureExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SpatialFeatureExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment] 2022-10-11 16:03
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lambdamoses.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Voyager")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Voyager

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-10-11 16:03 UTC
Labels: OK, 3a. accepted
