### ISSUE TITLE
IntEREst

### ISSUE THREAD

**Issue by gacatag** [Bioconductor/Contributions#217] opened 2016-12-15 18:20 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/gacatag/IntEREst

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment] 2016-12-15 18:49
Glanced at this. The interestResult class (should be capitalized) has slots (which should be of type integer) that are subscripts into the columns of another data.frame slot. Why not just store those columns directly as slots? Is it so important that they can be moved around? Btw, the `representation` arg to `setClass()` has been deprecated in favor of the `slots` arg.

**Comment by gacatag** [comment] 2016-12-15 20:44
AdditionalPackage: https://github.com/gacatag/MDS.Chr22.U12Genes

**Comment by vobencha** [comment] 2016-12-29 17:13
Hi,
I see you've uploaded a data package. Have you incorporated the comments Michael made for the software package? If yes, I'll go ahead and do a full review.

Please subscribe to the bioc-devel mailing list:

* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

Valerie

**Comment by gacatag** [comment] 2017-01-03 12:45
Hi Valerie!
No sorry! haven't incorporated Michael's ("lawremi" I assume) comments yet. His suggestion regarding the class is actually very good. I'm working on it now and will incorporate it soon, and commit the changes.

**Comment by gacatag** [comment] 2017-01-03 12:48
Hi Valerie  ( @vobencha )!
No sorry! haven't incorporated Michael's  ( @lawremi I assume) comments yet. His suggestion regarding the class was actually very good. I'm working on it now and will incorporate it soon, and commit the changes.

**Comment by gacatag** [comment] 2017-01-05 17:17
Dear Valerie ( @vobencha )
Hi!
I have now incorporated Michael's comments. Feel free to proceed with the review.
Cheers!
Ali

**Comment by vobencha** [comment] 2017-01-09 17:48
Hi,

1) Please fix these issues raised on the single package build report:

Shorten the run time for this example:

** running examples for arch 'i386' ... [220s] OK
Examples with CPU or elapsed time > 5s
                user system elapsed
getRepeatTable 34.02   1.44  211.95

Why so many unevaluated code chunks?

* Checking vignette directory...
    This is a software package
    # of chunks: 13, # of eval=FALSE: 3 (23%)

* Checking for recommended biocViews...
    * NOTE: Consider adding these automatically suggested biocViews:
      Transcription, Sequencing, Alignment, Normalization, Bayesian,
      Clustering, Regression, GeneExpression, RNASeq, ChIPSeq,
      DifferentialExpression, GeneSetEnrichment, BatchEffect,
      MultipleComparison, QualityControl, TimeCourse, DataImport

All exported functions / man pages need runnable examples:

* Checking exported objects have runnable examples...
    * NOTE: Consider adding runnable examples to the following man
      pages which document exported objects:
      annotateU12.Rd, buildSsTypePwms.Rd, interest.Rd,

Please format your code to max 80 characters wide:

* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 762 lines (14%) are > 80 characters
      long.

2) Remove the build/ and inst/doc/ directories. Both are generated automatically by R CMD build/check and are not needed in the source.

Valerie

**Comment by gacatag** [comment] 2017-01-11 16:08
gacatag:
Dear Valerie ( @vobencha )
Hi,
Thank you for your review and comments.

I have modified the codes and here are the main changes to the package together with my response to your comments:

1.
> Shorten the run time for this example: ... getRepeatTable

I changed the example into a `\dontrun`. The `getRepeatTable()` function connects to UCSC and builds a data.frame that includes information regarding repetitive DNA sequences in the human genome. Connecting to UCSC, downloading and accessing the repeats file (rmsk) from UCSC takes most of the time time in this function. Even requesting a small family repetitive elements (e.g. "Merlin" with only 57 reported cases) did not decrease the running time significantly. 

> Why so many unevaluated code chunks?
>* Checking vignette directory...
>    This is a software package
>    # of chunks: 13, # of eval=FALSE: 3 (23%)
The first 3 chunks in the vignette include codes that are time consuming to run (~ 15 minutes). Out of these chunks, the first 2 `interest()` and `interest.sequential()` results are exactly the same, however the `interest()` is run in parallel, hence it is provided as an example, demonstrating how to run the process on multiple cores, in parallel. Due to the large size of a lot of studied binary sequence reads mapped (.bam) files I think a lot of users would want to run in parallel mode, hence an example would be helpful to them. Please note that the object which is the result of running the first 3 chunks, i.e. `mdsChr22Obj`, is provided as a data inside the package and the remaining (and runnable) chunks inside the vignette document use the data for various downstream analysis and plots.    

> Optionally add more biocViews so users can find your package more easily:

>* Checking for recommended biocViews...
>    * NOTE: Consider adding these automatically suggested biocViews:
>      Transcription, Sequencing, Alignment, Normalization, Bayesian,
>      Clustering, Regression, GeneExpression, RNASeq, ChIPSeq,
>      DifferentialExpression, GeneSetEnrichment, BatchEffect,
>      MultipleComparison, QualityControl, TimeCourse, DataImport

These biocViews were added: Sequencing, RNASeq, Alignment, Normalization, and DifferentialExpression

> All exported functions / man pages need runnable examples:
>
> * Checking exported objects have runnable examples...
>    * NOTE: Consider adding runnable examples to the following man
>      pages which document exported objects:
>      annotateU12.Rd, buildSsTypePwms.Rd, interest.Rd,

I added a runnable example to the annotateU12.Rd manual which runs in a reasonable time. However, `interest()` and `interest.sequential()` are wrapper functions (that run several other functions) and are relatively time-demanding to run. They read a .bam file N lines at a time (N can be set by the user) and divide it to several smaller files (that can be fully managed by the memory), then the functions continue with counting the number of the reads in the individual files that hit each region (intron or exon), and in the end they sum the results from the smaller files and normalize the read counts. The `buildSsTypePwms()` and (as mentioned previously in my comments) `getRepeatTable()` functions are relatively time demanding, they connect to other sources for building data (`buildSsTypePwms()` connects and downloads data from U12DB or SpliceRack and `getRepeatTable()` connects to UCSC ). The tables generated by these functions can be used in various functions in the `IntEREst` package e.g. `interes()` and `interest.sequential()`.

> Please format your code to max 80 characters wide:
>
> * Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
>   and vignette source...
>    * NOTE: Consider shorter lines; 762 lines (14%) are > 80 characters
>      long.

All lines in the source files were shorten to (<80 characters) except for 10 lines in the vignettes/IntEREst.Rmd file. These lines are longer due to chunk parameters and apparently the parameters have to be defined in a single line.

2.
>  Remove the build/ and inst/doc/ directories. Both are generated automatically by R CMD build/check and are not needed in the source.

I removed the build/ and inst/doc/ directories as you suggested.

Thank you again!

Ali

**Comment by gacatag** [comment] 2017-01-24 09:19
Dear Valerie ( @vobencha ),
Hi!
In addition to the changes I mentioned in my previous response I also made a small correction to the R/u12Boxplot.R, hence the latest version bump.
Cheers!

**Comment by vobencha** [comment] 2017-01-24 14:10
Thanks. I'll have a look at this today.
Valerie

**Comment by vobencha** [comment] 2017-01-24 17:26
(1) parallel

I would recommend using the BiocParallel or doParallel packages instead of Rmpi. These 2 are much more recent packages and have been developed to be cross-platform compatible. Rmpi has some historical system requirements/issues that are best avoided. Additionally, the code attempts to specify exactly what to sent to each worker and mange the details of communication. This approach is no longer necessary with newer implementations in BiocParallel (build on the paralle and snow packages) and doParallel.

(2) zzz.R

It is not good practice to set global variables. Please explain why you think you need this and I will suggest an alternative.

(3) Smaller data for examples.

The functions need to be evaluated in either the man pages or vignette. The idea is to test the function at least once in the nightly builds. You will need to use smaller subsets of data and specify smaller subsets in the ScanBamParam object. Here are some small bam files you could use in your examples if you need ideas:
http://www.bioconductor.org/packages/release/data/experiment/html/pasillaBamSubset.html
http://www.bioconductor.org/packages/release/data/experiment/html/RNAseqData.HNRNPC.bam.chr14.html
http://www.bioconductor.org/packages/release/data/experiment/html/SCLCBam.html
http://www.bioconductor.org/packages/release/data/experiment/html/leeBamViews.html

(4) Code inefficiencies

The code needs to be streamlined and in many cases it looks like you are reinventing the wheel by not reusing the existing infrastructure as it is intended. I will walk through interest() as an example but it is necessary to make these changes in all functions.

## interest():

This function is trying to do too much. bamPreprocess() should read in the data but I don't understand why it needs to write out files. If it does, it should write to a location specified by the user. A reasonably clear workflow would consists of these steps:

- the user provides bam files to bamPreprocess(); bam Preprocess returns a GAlignmentsList or similar that can be saved as a .Rda file
- the user calls interestAnalyse with (a) their own GAlignmentsList (or similar) object or (b) the GAlignments object created by reading in the file created by bamPreprocess(); the output of interestAnalyse is a SummarizedExperiment
- is it necessary that interestSummarise be a separate step or could it be combined with interestAnalyse?

## bamPreprocess():

(i) reassignment
This reassignment of functions in Rsamtools to variables of the exactly same name is poor practice (NAMESPACE clash) and not necessary. Please remove the reassignments and use the functions/objects directly from Rsamtools.

    BamFile<- Rsamtools::BamFile
    ScanBamParam<- Rsamtools::ScanBamParam   
    scanBam<- Rsamtools::scanBam   
    scanBamFlag<- Rsamtools::scanBamFlag
    scanBamWhat<- Rsamtools::scanBamWhat

(ii) hard coded paths
This hard-coded approach to writing files is not cross-platform compatible and must be removed. Use a path specified by the user (default) or tmpdir() and tmpfile().
   dir.create(paste(outFolder,"read1/", sep="/"))   
   dir.create(paste(outFolder,"read2/", sep="/"))
   dir.create(paste(outFolder,"single/", sep="/"))

All references to 'read1', 'read2' and 'single' directories need to be removed, e.g,

    paste(outFolder, "/read2/tmpSam_", count, sep=""),

(iii) scanBam vs readGAlignment* functions
Why are you using scanBam() instead of readGAlighments(), readGAlignmentPairs() or readGAlignmentsList()? You are re-inventing the wheel in many aspects here.

It looks as though you expect both paired and unpaired data in one file ... ? The readGAlignmentsList() reads in all records with a metadata column on the object ('mate_status') indicating if a read is paired or not. Please look at ?readGAlignments man page. I think you should reuse one of these functions and not scanBam().

(iv) create param once
Create the ScanBamParam once, outside the while() loop.
```
scParam=ScanBamParam(
       what=scanBamWhat()[c(1,3,5,8,13,9, 10, 6, 4, 14, 15)],
       flag=scanBamFlag(isPaired=TRUE,
       isDuplicate=includePairedDuplicate))
```

## interestAnalyse()):

(i) Please use BiocParallel or doParallel instead of Rmpi.

(ii) Remove these reassignments:
```
subjectHits<-  S4Vectors::subjectHits
queryHits<- S4Vectors::queryHits
GRanges<- GenomicRanges::GRanges
findOverlaps<- GenomicRanges::findOverlaps
IRanges<- IRanges::IRanges
```

(ii) Many of your lapply's don't need to be loops. Operations on the CIGAR can be vectorized as described here:
http://www.bioconductor.org/developers/how-to/efficient-code/

## InterestResult object

(i)  Please use the SummarizedExperiment class as the output instead of creating your own S4 InterestResult.

Valerie

**Comment by gacatag** [comment] 2017-01-25 17:32
Dear Valerie ( @vobencha ),
Hi!
Thank you for your insightful comments and hints. I'll try to go through them and implement the changes you suggested. For now I would like to mention the following:

*Regarding _BiocParallel_ or _doParallel_ over _Rmpi_, I will try to use these new packages that are supported by Bioconductor.

*I'll remove the zzz.R file and not define global variables. I added that initially to get rid of a warning during the test but now I didn't get the warning when I removed zzz.R and ran the tests.

*I will replace scanBam() with _readGAlignmentPairs()_ and _readGAlignments_ but regarding the parallel coding in interest():  
My goal is to read a single large input .bam file, _N_ mapped-reads at a time and run analysis (Mapped reads summarization or counting in introns and exons) in parallel over _n_ computing cores. In other words, I would like to parallelize over several read chunks from a single .bam file rather than over several .bam files. Because, I would need to speed up the analysis of a single large .bam file and analyze it without loading the whole file into the memory. I would also need to know which reads are paired-mapped (both pair of reads are mapped) and which are single-mapped. To my knowledge, to implement this I either should 
_I)_ read from the .bam file _n_ mapped-reads at a time (first reading paired mapped reads and then the single mapped), write them in temporary files and finally run the same analysis on these temp files while passing a value to the nodes that tells whether the analyzed temp file includes single or pair mapped reads., or 
_II)_ I should provide index numbers, and implement such that the first node reads the first _n_ mapped reads from the .bam file, and the rest of the nodes read from the same .bam file but skip 1 to _k_ chunks of reads to read a chunk of reads that would be analyzed uniquely by that node. 
The _interest()_ function right now uses the policy _I_ but now I am planning to change it to _II_. Feel free to recommend if you know a better solution.

Cheers!

Ali

**Comment by vobencha** [comment] 2017-01-31 21:50
Hi,
Responding to comments in https://github.com/Bioconductor/Contributions/issues/217#issuecomment-275175414.

I do not think either option I or II you describe are good approaches. Once you modify the code to use BiocParallel or doParallel you won't need to manage jobs at the node/worker level. I strongly advise against doing that - it is error prone and likely not platform independent. This is what I think needs to happen:
- modify the code to use BiocParallel or doParallel
- distribute the bam files as BamFile objects to the workers in bplapply()
In the BamFile object specify if the bam file is single or paired end.
- each worker should call readGAlignmentsList() because it can read pairs or single-end; once a chunk is read in do the analysis on the chunk; do not write out the raw records from the bam files to temp files before doing the analysis.

Why do you want parallel workers to operate on chunks of the same bam file instead of having each working work through the file in chunks? You will incur much less time/memory overhead if you just let one worker move through one bam file in chunks; the code in GenomicAlignments/Rsamtools has been optimized to do this. You don't want to manage opening a bam file, give one chunk to worker A, save your place in the file, close the file, then worker B opens the file and tries to find where worker A left off.

Valerie

**Comment by gacatag** [comment] 2017-02-07 16:58
Dear Valerie ( @vobencha  ),
Hi!
Thank you for your insightful comments and hints.
I have addressed all of them in the newest version _IntEREst 0.99.16_.

>(1) parallel
>
>I would recommend using the BiocParallel or doParallel packages instead of Rmpi... 

The package now uses  `bpiterate` (togetehr with `SerialParam` and `MulticoreParam`) from the _BiocParallel_ package.

>(2) zzz.R
>
>It is not good practice to set global variables. Please explain why you think you need this and I will suggest an alternative.

The global variables are removed.

>(3) Smaller data for examples.
>
>The functions need to be evaluated in either the man pages or vignette... 

A new small bam file is added to /inst/extdata that is used in the examples in manuals (man/interest.Rd and man/interest.sequential.Rd). They run in a reasonable time.   

>(4) Code inefficiencies
>
>The code needs to be streamlined and in many cases it looks like you are reinventing the wheel by not reusing the existing infrastructure as it is intended. I will walk through interest() as an example but it is necessary to make these changes in all functions.
>interest():
>
>This function is trying to do too much. bamPreprocess() should read in the data but I don't understand why it needs to write out files. If it does, it should write to a location specified by the user. A reasonably clear workflow would consists of these steps...
>is it necessary that interestSummarise be a separate step or could it be combined with interestAnalyse?

The `bamPreprocess()` is removed. The system is now based on `bpiterate()` function from the _BiocParallel_ package. No temp files are written anymore and manual controls are no longer performed to determine what parallel core takes care of which chunk of the reads in the input .bam file. The parallel process iterates through various read chunks from the input bam file automatically and analyzes them. The output of the `interest` and `interest.sequential` functions are written in a user defined text file and they can be returned as objects of `SummarizedExperiment` too. Please note that the user only runs `interest()` or `interest.sequential()`; the other functions used in these 2 functions, e.g.` interestSummarise()` and `interestAnalyse()` are invisible to the user (they are not exported)  and they are only used for modular and more organized coding and modifying of the codes.

 

>bamPreprocess():
>
>(i) reassignment
>This reassignment of functions in Rsamtools to variables of the exactly same name is poor practice (NAMESPACE clash) and not necessary. Please remove the reassignments and use the functions/objects directly from Rsamtools.
>
>BamFile<- Rsamtools::BamFile
>ScanBamParam<- Rsamtools::ScanBamParam ... 


The reassignments are removed.

>(ii) hard coded paths
>This hard-coded approach to writing files is not cross-platform compatible and must be removed. Use a path specified by the user (default) or tmpdir() and tmpfile().
>dir.create(paste(outFolder,"read1/", sep="/")) ...

Hard codes for writing files are removed and no temproray file is written any more.


>(iii) scanBam vs readGAlignment* functions
>Why are you using scanBam() instead of readGAlighments(), readGAlignmentPairs() or readGAlignmentsList()? You are re-inventing the wheel in many aspects here.
>
>It looks as though you expect both paired and unpaired data in one file ... ? The readGAlignmentsList() reads in all records with a metadata column on the object ('mate_status') indicating if a read is paired or not. Please look at ?readGAlignments man page. I think you should reuse one of these functions and not scanBam().

The `scanBam()` is not used any more; the `readGAlignmentsList()` is used for reading single mapped reads and `readGAlignmentPairs()` for reading paired reads together. The analysis on the single mapped reads is a bit different from the analysis on the paired reads (e.g. the paired reads mapped to an exon should be counted only once).

>(iv) create param once
>Create the ScanBamParam once, outside the while() loop...

`ScanBamParam()` is called outside the iteration and loop.

>interestAnalyse()):
>
>(i) Please use BiocParallel or doParallel instead of Rmpi.

_BiocParallel_ is used instead of _Rmpi_.

>(ii) Remove these reassignments:
>
>subjectHits<-  S4Vectors::subjectHits...

Reassignments are removed.

>(ii) Many of your lapply's don't need to be loops. Operations on the CIGAR can be vectorized as described here:
>http://www.bioconductor.org/developers/how-to/efficient-code/

Loops are removed and the process are vectorized using the `cumsum()` function in base R.

>InterestResult object
>
>(i) Please use the SummarizedExperiment class as the output instead of creating your own S4 InterestResult.

The S4 class `InterestResult` is removed and `SummarizedExperiment` is used instead.

Finally, please also note that I have now also suggested the data package used in the vignettes, i.e. _MDS.Chr22.U12Genes_ . I added it as an AdditionalPackage on 15 Dec, 2016 https://github.com/gacatag/MDS.Chr22.U12Genes .

Thank you again!

Ali

**Comment by gacatag** [comment] 2017-02-08 13:05
Dear Valerie ( @vobencha ),
Hi!
In the newest version bump IntEREst 0.99.17 I added an isPaired parameter that by setting it as FALSE the analysis would be adaptable to single read (not paired!) sequencing .bam files. It would read and analyze the single/unpaired read .bam file correctly.

**Comment by gacatag** [comment] 2017-02-08 13:13
Dear Valerie ( @vobencha ),
Hi again!
In the newest version bump IntEREst 0.99.17 I added an isPaired parameter that by setting it as FALSE the analysis would be adaptable to single read (not paired!) sequencing .bam files. It would read and analyze the single/unpaired read .bam file correctly.

Cheers!

**Comment by vobencha** [comment] 2017-02-21 20:27
Thanks for your patience. I'll take a look at this tomorrow.
Valerie

**Comment by vobencha** [comment] 2017-02-22 14:02
Hi,

Thank you for working on the package. It's looking much better.

I'm not clear on what your intentions are with the MDS.Chr22.U12Genes data package. Currently the software package is self contained and does not use it. The data package has 15 bam files which is excessive for an experimental data package. I would recommend you proceed with the software package and not the experimental data package.

Valerie

**Comment by gacatag** [comment] 2017-02-23 15:54
Hi Valerie ( @vobencha ).
Thank you for your response. I removed the MDS.Chr22.U12Genes dependency (suggestion) and also updated the vignette document accordingly; instead of the large data package, I included all the scripts needed to generate the test data `mdsChr22Obj` in /inst/scripts/. I included the scripts in case a user wished to generate the test data `mdsChr22Obj` manually using the `interest()` and the `readInterestResults()` functions, or if a user wanted to see how the test data is generated.

The reason that I was initially  planing to include the data package MDS.Chr22.U12Genes is that, although I already had included the test data `mdsChr22Obj` in the package, that could be used as a demo to test plotting and other DOWNSTREAM analysis, I also wanted to include the source .bam files as an attached package (suggsted by IntEREst) to also show a demo on running the intron-retention estimation functions, _i.e._ `interest()` and `interest.sequential()`  which lead to building `mdsChr22Obj`. As I mentioned, based on your comment, in the latest version bump I added the scripts that one can use to make the test data `mdsChr22Obj` to the package and I also provided the path to the readme.txt file and the scripts in the vignette.

Cheers,

Ali

**Comment by gacatag** [comment] 2017-02-23 15:59
Hi Valerie ( @vobencha ).
Thank you for your response. I removed the MDS.Chr22.U12Genes dependency (suggestion) and also updated the vignette document accordingly; instead of the large data package, I included all the scripts needed to generate the test data `mdsChr22Obj` in /inst/scripts/. I included the scripts in case a user wished to generate the test data `mdsChr22Obj` manually using the `interest()` and the `readInterestResults()` functions, or if a user wanted to see how the test data is generated.

The reason that I was initially  planing to include the data package MDS.Chr22.U12Genes is that, although I already had included the test data `mdsChr22Obj` in the package, that could be used as a demo to test plotting and other DOWNSTREAM analysis, I also wanted to include the source .bam files as an attached package (suggsted by IntEREst) to also show a demo on running the intron-retention estimation functions, _i.e._ `interest()` and `interest.sequential()`  which lead to building `mdsChr22Obj`. As I mentioned, based on your comment, in the latest version bump I added the scripts that one can use to make the test data `mdsChr22Obj` to the package and I also provided the path to the readme.txt file and the scripts in the vignette.

Cheers,

Ali

**Comment by vobencha** [comment] 2017-03-02 15:46
Thanks for making the changes. The package looks good and I'm approving it. The RMySQL on the mac is expected and won't be fixed anytime soon since the binaries aren't available from CRAN.

Valerie

**Comment by vobencha** [comment] 2017-03-02 15:47
You'll get an email in the next few days with svn credentials and instructions for working on the package in svn.

Valerie

**Comment by gacatag** [comment] 2017-03-03 08:35
Great!
Thank you for your comments.

Cheers!
Ali

**Closed** 2017-03-04 09:42 UTC
Labels: 3a. accepted, ERROR
