### ISSUE TITLE
MPO.db

### ISSUE THREAD

**Issue by huerqiang** [Bioconductor/Contributions#2985] opened 2023-03-26 21:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuLab-SMU/MPO.db

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x]The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2023-03-31 14:57
When I try to install I get
```
1/11 packages newly attached/loaded, see sessionInfo() for details.
Error: package or namespace load failed for 'MPO.db':
 .onLoad failed in loadNamespace() for 'MPO.db', details:
  call: dbFileConnect(dbfile)
  error: DB file '' not found
```
please try your package on a completely clean system.  Be sure it passes R CMD check.

**Comment by huerqiang** [comment] 2023-04-03 17:36
@vjcitn Hi, I have update this package and it passes devtools::check(cran = FALSE) and BiocCheck::BiocCheck('new-package'=TRUE)  now.

**Comment by huerqiang** [comment] 2023-04-09 08:18
@vjcitn Hi, I would like to ask if there are other modifications needed for this package.

**Comment by huerqiang** [comment] 2023-04-16 10:09
@vjcitn Hi, since Wednesday April 19 is the deadline to add new packages to the Bioc 3.17 manifest, I would like to ask if MPO.db has passed the review? Thanks.

**Comment by vjcitn** [comment] 2023-04-16 10:39
I wonder why this is happening:
```
❯ checking whether the namespace can be unloaded cleanly ... WARNING
  ---- unloading
  Loading required package: MPO.db
  Error: package or namespace load failed for ‘MPO.db’:
   .onLoad failed in loadNamespace() for 'MPO.db', details:
    call: value[[3L]](cond)
    error: failed to create index
    hubCache(): /home/stvjc/.cache/R/AnnotationHub
    reason: replacement has 70032 rows, data has 0
  Error in .requirePackage(package) : 
    unable to find required package ‘MPO.db’
  Calls: <Anonymous> ... .findInheritedMethods -> getClass -> getClassDef -> .requirePackage

0 errors ✔ | 1 warning ✖ | 0 notes ✔
> sessionInfo()
R Under development (unstable) (2023-03-18 r84003)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /home/stvjc/R-43dev-dist/lib/R/lib/libRblas.so 
LAPACK: /home/stvjc/R-43dev-dist/lib/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_2.21

loaded via a namespace (and not attached):
 [1] desc_1.4.2        digest_0.6.31     R6_2.5.1          fastmap_1.1.1    
 [5] xfun_0.38         rcmdcheck_1.4.0   knitr_1.42        htmltools_0.5.5  
 [9] ps_1.7.4          cli_3.6.1         xopen_1.0.0       processx_3.8.0   
[13] callr_3.7.3       withr_2.5.0       compiler_4.3.0    prettyunits_1.1.1
[17] rprojroot_2.0.3   tools_4.3.0       pkgbuild_1.4.0    curl_5.0.0       
[21] evaluate_0.20     startup_0.20.0    crayon_1.5.2      rlang_1.1.0   
```
Also the vignette should use BiocStyle for rendering.  I will pass the check and see how the build system does.

**Comment by huerqiang** [comment] 2023-04-16 12:20
@vjcitn I have update the vignette.  
The check result was OK 2 weeks ago, but I also encountered this error "replacement has 70032 rows, data has 0" when I recheck it just now, and I don't know what caused it for the time being.

**Comment by LiNk-NY** [comment] 2023-04-17 22:09
> ```
> ❯ checking whether the namespace can be unloaded cleanly ... WARNING
>   ---- unloading
>   Loading required package: MPO.db
>   Error: package or namespace load failed for ‘MPO.db’:
>    .onLoad failed in loadNamespace() for 'MPO.db', details:
>     call: value[[3L]](cond)
>     error: failed to create index
>     hubCache(): /home/stvjc/.cache/R/AnnotationHub
>     reason: replacement has 70032 rows, data has 0
>   Error in .requirePackage(package) : 
>     unable to find required package ‘MPO.db’
>   Calls: <Anonymous> ... .findInheritedMethods -> getClass -> getClassDef -> .requirePackage
> 

Hi Vince, @vjcitn 
This means that you should install the package first before checking it.

**Comment by LiNk-NY** [comment] 2023-04-17 22:13
Hi ErQiang, @huerqiang 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# MPO.db #2985

## DESCRIPTION

* Consider adding a `URL` field pointing to the GitHub repository.
* Looks good

## NAMESPACE

* Imports and exports look minimal.
* Consider adding `AnnotationDbi` to the Depends field rather than rexporting
'columns', 'keytypes', 'select', 'keys' functions.

## vignettes

* Consider adding author and affiliation in the yaml header of the vignette.
* Include an installation section using the usual commands i.e., with
`BiocManager`

## R

* Since you are creating methods for `MPODb`, you should `Depends` on
`AnnotationDbi` and avoid using `getFromNamespace` function
* Add default keytypes in the `select` MPODb method.
* Consider using BiocFileCache to cache the connections.
* Consider defining an official `MPODb` class in the package.
* Avoid saving `txdb.Rdata` file to the user's directory

## tests

* We strongly recommend adding unit tests to the package

```r
covr::package_coverage()
snapshotDate(): 2023-04-06
MPO.db Coverage: 0.00%
R/AllClasses.R: 0.00%
R/objects.R: 0.00%
R/zzz.R: 0.00%
```

**Comment by LiNk-NY** [comment] 2023-04-17 22:15
Can you bump the 'z' version of the package and rebuild? 
Thanks!
-MR

**Comment by huerqiang** [comment] 2023-04-18 15:25
@LiNk-NY 
I have done the following modifications:
(1) add a URL field pointing to the GitHub repository in DESCRIPTION
(2) add author and affiliation in the yaml header of the vignette.
(3)  add installation section in vignette
(4) delete some functions which using getFromNamespace
(5) add default keytypes "mpid" in the select MPODb method
(6) avoid saving txdb.Rdata file to the user's directory
(6) add test
MPO.db Coverage: 27.91%
R/objects.R: 0.00%
R/zzz.R: 0.00%
R/AllClasses.R: 43.64%

Others I'm not sure how to modify:
### NAMESPACE
(1) Imports and exports look minimal.
(2) Consider adding AnnotationDbi to the Depends field rather than rexporting
'columns', 'keytypes', 'select', 'keys' functions.
### R
(3) Consider using BiocFileCache to cache the connections.
(4) Consider defining an official MPODb class in the package.

And when I pushed it to git@git.bioconductor.org:packages/MPO.db, I got the errors:
```r
git push upstream
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 16 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 1.60 KiB | 1.60 MiB/s, done.
Total 11 (delta 5), reused 0 (delta 0), pack-reused 0
remote: FATAL: W refs/heads/main packages/MPO.db huerqiang DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/MPO.db.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git.bioconductor.org:packages/MPO.db.git'
```
This is my remote:
```r
git remote -v
origin  git@github.com:huerqiang/MPO.db.git (fetch)
origin  git@github.com:huerqiang/MPO.db.git (push)
upstream        git@git.bioconductor.org:packages/MPO.db.git (fetch)
upstream        git@git.bioconductor.org:packages/MPO.db.git (push)
yulab   git@github.com:YuLab-SMU/MPO.db.git (fetch)
yulab   git@github.com:YuLab-SMU/MPO.db.git (push)
```
Hope to get your help, thank you very much.

**Comment by lshep** [comment] 2023-04-21 13:28
There is no "main" branch on Bioconductor.  You would need to do something like `git push upstream main:devel`

**Comment by huerqiang** [comment] 2023-04-21 13:30
Thanks, it works!

**Comment by huerqiang** [comment] 2023-04-22 21:39
@lshep @LiNk-NY  Hi, I found that the check result still has the warning: 
```r
 .onLoad failed in loadNamespace() for 'MPO.db', details:
  call: value[[3L]](cond)
  error: failed to create index
  hubCache(): /home/pkgbuild/.cache/R/AnnotationHub
  reason: replacement has 70032 rows, data has 0
```
Does this require me to make any changes? Thanks.

**Comment by LiNk-NY** [comment] 2023-04-24 17:23
Hi ErQiang, @huerqiang 

I am unable to reproduce the above error locally. 

I did notice that the [zzz.R file](https://github.com/YuLab-SMU/MPO.db/blob/main/R/zzz.R) is unchanged. 
I don't think it is a good idea to assign within the package's namespace and 
it looks like you are exporting functions in `zzz.R` that should be methods for your `MPODb` class. 
I am not sure why the above is needed. Consider creating a proper reference class with methods. 

See here for an example: https://code.bioconductor.org/browse/BiocParallel/blob/master/R/BatchtoolsParam-class.R#L128

-Marcel

**Comment by huerqiang** [comment] 2023-05-16 14:49
@LiNk-NY Hi, I have updated the zzz.R and it passed the RMD check with 0 errors ✔ | 0 warnings ✔ | 0 notes ✔.

**Comment by LiNk-NY** [comment] 2023-05-16 22:17
Hi HuerQiang, @huerqiang 
Thank you for making those changes. 
Please make sure that all the items in the checklist (in the first comment) are ticked off i.e., [x]. 
Your package has been accepted.
Best regards,
Marcel

**Comment by huerqiang** [comment] 2023-05-16 22:30
Thanks, I have updated the first comment and all the items in the checklist are ticked off.

**Comment by huerqiang** [comment] 2023-05-19 19:07
@LiNk-NY Hi, the MPO.db package has been accepted for three days, but it has yet to be built in Bioconductor devel. I would like to ask if this is a normal situation?

**Comment by lshep** [comment] 2023-05-22 11:49
Please be patient. I ingest all accepted packages generally once a week.  It will be processed later today and should show up in devel within the next 48 hours or so.

**Comment by lshep** [comment] 2023-05-22 14:28
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/huerqiang.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MPO.db")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MPO.db

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-05-22 14:28 UTC
Labels: OK, 3a. accepted
