### ISSUE TITLE
mitoClone2

### ISSUE THREAD

**Issue by benstory** [Bioconductor/Contributions#2158] opened 2021-06-20 22:54 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/benstory/mitoClone2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/

**Comment by benstory** [comment] 2021-07-06 12:03
The package builds on the Mac/Linux machines but not the BioC Windows machine. However, it does build successfully on https://win-builder.r-project.org/.

The only Warning for the Linux/Mac build is related to the included source code from an external program (https://github.com/cbg-ethz/SCITE) and I would prefer not to edit any of their code as a matter of principle. Hervé suggested I include the software since it was so easy to compile - which is a great idea - rather than have the end-user download it on their own. Hopefully this is OK. Please let me know how I can move this process forward.

**Comment by hpages** [comment] 2021-07-06 19:46
There was a file permission issue on our Windows builder. It should be addressed now. Please bump the version of the package to trigger a new build by the SPB. Thanks!

**Comment by benstory** [comment] 2021-07-08 12:56
Hi Hérve thanks for looking into this, I was worried it was something on my end. Either way it was a good learning experience :)

@LiNk-NY, at this point I think the package is ready for review. The "WARNING" is related to an external software package included in the package (https://github.com/cbg-ethz/SCITE) and I am hesitant to edit their source code out of principle. Outside of that I'm ready to make any changes that deem necessary to the package for acceptance to Bioconductor. I'm always easily available on the bioC slack if needed. Thanks. -Ben

**Comment by LiNk-NY** [comment] 2021-07-09 16:43
Hi Ben, @benstory 

Thank you for your submission. 
Please see the review below. 

Regards,
Marcel

---

# mitoClone2 #2158

## README

* Please don't advertise your package as install-able from Bioconductor
when it hasn't been accepted.

## DESCRIPTION

* Update the R version to >= 4.1.0 which corresponds to the current devel
version.
* Include `BugReports` and `URL` fields that point to GitHub
* Use whole sentences in the `Description` field. `BiocCheck` will flag short
`Description` fields by checking for `.`.
* Remove the `LazyData: true` or set to `false`.

## NAMESPACE

* Looks good.

## R

* Use character indices rather than numeric ones for more robust code.
* Include all options in the argument, e.g.,
`what = c("alleleRatio", "ternary")`, and then use `match.arg()` inside the
function to obtain one.
* Avoid using `@` in the package code. You should have formal extractor
functions for your class.
* Avoid using system calls in `plotTree`. That code may not be portable to all
platforms. Separate the plotting and saving functionality. Do not save files
for the user by default.
* Consider using `reticulate` or `basilisk` rather than system calls to python.
* Does `Rsamtools` have the functionality that you are looking for? This is
preferred over `system("which samtools")`
* Reduce repetitive coding by using conditional inputs in `ggplot`, e.g.,
`legend.pos <- if (showLegend) "top" else "none"`
* Please follow up with the Notes from `BiocCheck::BiocCheck()`, current count:
15.

* Minor: the `new("mutationsCalls", ...)` should be the last call in the
constructor
* Save the output of `GRanges(sites)` and re-use it in
`mutationCallsFromCohort`.

## vignettes

* Restrict text to an 80-character width limit. It makes it easier to review
and maintain.
* Avoid using `@` access and provide formal accessor and replacement functions.
* Your example datasets in the vignette should be minimal enough to allow
the demonstration of function use. Avoid providing code that takes more
than 1 minute to run in the vignette.
* Provide a `sessionInfo` section at the end of the vignette.
* Avoid downloading data from a link.
* Keep examples from publications (Ludwig et. al) in a separate repository.
The main focus of the vignettes should be to demonstrate the functionality of
the package rather than reproducing a real-world analysis. If you wish,
you can create a workflow package to that end.

## src

* We would prefer that you do not include external software with your package.
Perhaps you can instruct users to use that software independently of yours and
your package can optionally work with the output of the `SCITE` software?
For the time being we can't accept your package with the `SCITEpkg` code
inside of it.

## tests

* We strongly recommend that you add unit tests to your functions to make
them more robust and reliable.

**Comment by benstory** [comment] 2021-07-13 16:37
Dear Marcel (@LiNk-NY),

Thank you for taking the time to review my submission. I have responded point-by-point to your concerns. Please let me know if everything is acceptable to you.

Best,
Ben

> Hi Ben, @benstory
> 
> Thank you for your submission.
> Please see the review below.
> 
> Regards,
> Marcel
> 
> # mitoClone2 #2158
> ## README
> * Please don't advertise your package as install-able from Bioconductor
>   when it hasn't been accepted. 

**FIXED**

> 
> ## DESCRIPTION
> * Update the R version to >= 4.1.0 which corresponds to the current devel
>   version. 

**FIXED**


> * Include `BugReports` and `URL` fields that point to GitHub 

**FIXED**


> * Use whole sentences in the `Description` field. `BiocCheck` will flag short
>   `Description` fields by checking for `.`. 

**FIXED**


> * Remove the `LazyData: true` or set to `false`. 

**FIXED**

 _I had to move all the objects from the ‘data’ folder to ‘extdata’ and now load them explicitly. This results in a warning on build but ultimately I do really not want those objects facing the user. Happy to hear any suggestions._
> 
> ## NAMESPACE
> * Looks good. 

**THANK YOU**

> 
> ## R
> * Use character indices rather than numeric ones for more robust code. 

**KINDA FIXED**

 _In all reasonable cases, in some cases the numeric index makes sense._
> * Include all options in the argument, e.g.,
>   `what = c("alleleRatio", "ternary")`, and then use `match.arg()` inside the
>   function to obtain one. 

**FIXED**


> * Avoid using `@` in the package code. You should have formal extractor
>   functions for your class. 

**KINDA FIXED**

 _Add a few more accessors functions for use in the vignettes and examples. Within the internal code certain slots don’t necessarily need to be available to the end user. This is especially true for the recursive code chunks within functions_tree.R. I removed all ‘@’ usage in vignettes and examples and also replaced those within the code (when accessor was available)._
> * Avoid using system calls in `plotTree`. That code may not be portable to all
>   platforms. Separate the plotting and saving functionality. Do not save files
>   for the user by default. 

**FIXED**

 _(removed entire function)_
> * Consider using `reticulate` or `basilisk` rather than system calls to python. 

**FIXED**

 _(removed it)_
> * Does `Rsamtools` have the functionality that you are looking for? This is
>   preferred over `system("which samtools")` 

**FIXED**

 _(removed samtools call and added instructions for user to run python code externally and import through R)_
> * Reduce repetitive coding by using conditional inputs in `ggplot`, e.g.,
>   `legend.pos <- if (showLegend) "top" else "none"` 

**FIXED**


> * Please follow up with the Notes from `BiocCheck::BiocCheck()`, current count:
> 

**KINDA FIXED**

 _I dropped the number of notes down to 8. At least 3 of them are not correct. The major thing has to do with line numbers for functions etc… I used RStudio to clean up how the actual code looks... and it looks a bit better. Not sure how to wrap the lines for the manual pages, maybe I need to do that manually?_
> 
> * Minor: the `new("mutationsCalls", ...)` should be the last call in the
>   constructor 

**FIXED**


> * Save the output of `GRanges(sites)` and re-use it in
>   `mutationCallsFromCohort`. 

**FIXED**

 _This parameter is not necessarily supposed to be reused across functions (e.g. user wants to investigate a subset of their data). Also, it is now clarified that the parameter can take both a character or GRanges object as input._
> 
> ## vignettes
> * Restrict text to an 80-character width limit. It makes it easier to review
>   and maintain. 

**FIXED**

 _I added a knitr option to force wrapping at 70-characters. Hopefully this solves the issue._
> * Avoid using `@` access and provide formal accessor and replacement functions. 

**FIXED**


> * Your example datasets in the vignette should be minimal enough to allow
>   the demonstration of function use. Avoid providing code that takes more
>   than 1 minute to run in the vignette. 

**KINDA FIXED**

 _See below discussion of SCITE. I limited it to one experimental example but the run itself still takes about 2 minutes._
> * Provide a `sessionInfo` section at the end of the vignette. 

**FIXED**


> * Avoid downloading data from a link. 

**FIXED**

 _Removed all external links to data_
> * Keep examples from publications (Ludwig et. al) in a separate repository.
>   The main focus of the vignettes should be to demonstrate the functionality of
>   the package rather than reproducing a real-world analysis. If you wish,
>   you can create a workflow package to that end. 

**FIXED**

 _I tried to cut down the size of everything in the vignette. The recreation of the Ludwig data is just an ideal dataset used to showcase the package. The type of data analysis done in this example is exactly what the package was designed to do. Anyway I removed all the repetitive exact figure creation at the end. I trimmed the vignette down to be shorter, faster, and more for focused on demonstrating functional aspects of the package._
> 
> ## src
> * We would prefer that you do not include external software with your package.
>   Perhaps you can instruct users to use that software independently of yours and
>   your package can optionally work with the output of the `SCITE` software?
>   For the time being we can't accept your package with the `SCITEpkg` code
>   inside of it. 

**NOT FIXED**

 _I think that including the SCITE code as part of this R package is extremely valuable. I would imagine that the vast majority of Windows R users would be severely hamstrung when it comes to installing/compiling external software on their own and thus by having it pre-bundled and compiled with the R package – we make it extremely accessible to all. **The SCITE software is step 3 in a very important 4-step process that is the raison d’être of this package.** Before including it, I originally asked what to do about external dependencies on the Bioconductor Slack and was advised by Hérve Pagès to include the software to be compiled when the package is installed and then Mike Smith helped me create the Makefile to do just that. Then others had to [fix the build server](https://community-bioc.slack.com/archives/C0207H5QC3X/p1625240733057500) in order to help further. It is a bit confusing at this point to hear that this is not acceptable. In the [package guidelines (#11) ](https://www.bioconductor.org/developers/package-guidelines) it is suggested that including external code is possible. In this case the code is raw C++ compiled at install with **zero** additional dependencies. I also agree to assume “…responsibility for maintenance of that code. Part of the maintenance responsibility includes keeping the code up to date as bug fixes and updates are released for the mainline third-party project.“ Anyway hopefully this is more of a recommendation than a firm barrier. Let me know otherwise._
> 
> ## tests
> * We strongly recommend that you add unit tests to your functions to make
>   them more robust and reliable. 

**FIXED**

 _Added a couple tests._

Thanks again for your time. Looking forward to your reply. -Ben

**Comment by LiNk-NY** [comment] 2021-07-14 16:53
Hi Ben, @benstory 

Thank you for your response. You are right, external C code is allowed in packages and perhaps the GPL-3 license should be respected. We suggest that you add the authors of the `SCITE` software to your packages `DESCRIPTION` file. Usually packages containing external C code are kept separate e.g., `Rhtslib` so that they are more modular and other packages can make use of that library without having to import `mitoClone2` for example. 
Hervé pointed out that it is strange that you provide a standalone executable in `${R_PACKAGE_DIR}/libs/` and perhaps the ~source~ executable should be moved to a more appropriate location, perhaps `mitoClone2/inst/exec` or `mitoClone2/inst/bin` but more investigation is needed. 

> Not sure how to wrap the lines for the manual pages, maybe I need to do that manually?

We don't encourage this if you are using `roxygen2` because those changes will be overwritten AFAIK when you "roxygenize"

> This parameter is not necessarily supposed to be reused across functions (e.g. user wants to investigate a subset of their data). Also, it is now clarified that the parameter can take both a character or GRanges object as input.

I meant this within the function (see line 21). It looks like you ran it but didn't assign the output to a variable. 

> I added a knitr option to force wrapping at 70-characters. Hopefully this solves the issue.

I meant this for the source document and not the output. 


> I tried to cut down the size of everything in the vignette. The recreation of the Ludwig data is just an ideal dataset used to showcase the package. The type of data analysis done in this example is exactly what the package was designed to do. Anyway I removed all the repetitive exact figure creation at the end. I trimmed the vignette down to be shorter, faster, and more for focused on demonstrating functional aspects of the package.

Yes, this is an excellent use case but it is best reserved for a workflow type of package. 

Best regards,
Marcel

**Comment by hpages** [comment] 2021-07-14 22:49
Hi @LiNk-NY @benstory,
Just to clarify, I was suggesting `${R_PACKAGE_DIR}/exec/` or `${R_PACKAGE_DIR}/bin/` for the SCITE executable, not for the source code. But now that I think more about it, maybe everything could go in `mitoClone2/inst/SCITE`, source and executable (this means the executable gets installed in `${R_PACKAGE_DIR}/SCITE/`). Would be cleaner than the current layout. Hopefully the changes to the current `Makevars` are relatively straightforward.
Best,
H.

**Comment by benstory** [comment] 2021-07-15 00:47
Hi @LiNk-NY @hpages ,

Thank you guys for the suggestions I'm perfectly OK with putting the files anywhere. Also, I originally changed the /src folder name from SCITE to SCITEpkg because I was getting a warning at a some point about having a file named 'scite' and a directory named 'SCITE'. I will try to fiddle around with it tomorrow morning (late in Germany). I'm fine with whatever route you think is ideal for including the software.

-

@LiNk-NY
>those changes will be overwritten AFAIK when you "roxygenize"
>source document

Sorry I was referring to the manually changing the `#'@examples`/`#'@name` etc... lines in the  .R src files, for some reason those lines didn't wrap automatically using **formatR** I think everything else wrapped successfully. If those `#'@` lines need to be wrapped I will try to make some Emacs macros for it.

> see line 21

Oops embarrassing  - fixed it - will be changed in next push ...

> best reserved for a workflow type of package.

I shrunk that whole **Overview** vignette section drastically and removed all major mentions of the Ludwig source data... should I shrink it even more? I could make the heatmaps very small maybe even 20x20 if needed. It now highlights the two different options for (step 2/4 of the 4 steps). The **Clustering** vignette now runs in half the time but still runs one instance of SCITE (step 3/4 - two min process) and then step 4/4. If vignette build time is an issue I can just completely remove the **Clustering** vignette and add an extra to panel to the end of **Overview** with pre-computed data showcasing the functionality of step 3 and step 4.

Thanks again for helping me with this process! Very excited that we are making good progress.

Best,
Ben

**Comment by benstory** [comment] 2021-07-15 14:22
@LiNk-NY 

Everything should be fixed now. The SCITE source code is present in the `'mitoClone2/inst/SCITEpkg'` and when compiled on install, the executable ends up in `${R_PACKAGE_DIR}/SCITE/`. The vast majority of the code sits at less than 80 chars per line... some very deep loops seem to still add to the 80 char and 4 space tabs **warnings** but overall the total percentages are drastically reduced.

I cut the vignettes down a lot although they still aren't crazy fast.

One warning is related to some .RData files I moved out of the `data` folder to `inst/extdata` after setting LazyLoading to `false`. And they are documented in `/inst/script/README`... but the warning persists.

Let me know if you think anything else needs to be changed.

Best,
Ben

**Comment by LiNk-NY** [comment] 2021-07-15 15:22
Hi Ben, @benstory 

Thanks for making those changes. 

I currently only see two warnings:

```r
* checking whether package 'mitoClone2' can be installed ... WARNING
Found the following significant warnings:
  ../inst/SCITEpkg/mcmcBinTreeMove.cpp:75:1: warning: control reaches end of non-void function [-Wreturn-type]
  bam2R_10x.cpp:145:9: warning: ISO C++ forbids variable length array ‘counts’ [-Wvla]
See '/home/mr148/bioc/mitoClone2.Rcheck/00install.out' for details.

* checking R code for possible problems ... NOTE
mitoPlot: no visible binding for global variable ‘type’
mitoPlot: no visible binding for global variable ‘gene’
Undefined global functions or variables:
  gene type

* checking for missing documentation entries ... WARNING
Undocumented data sets:
  ‘M_P1’ ‘M_P2’ ‘N_P1’ ‘N_P2’
```

It seems like those datasets should be documented.
Perhaps you can put them in a list so that you only have to document a single object. 

Can you also address the `NOTE`?

**Comment by benstory** [comment] 2021-07-15 21:06
@LiNk-NY 

Hi Marcel,

After much trial and tribulation all of those issues have been solved phew. The 'type' and 'gene' error were related to plotting with ggplot2. Hope everything is good. 

Thanks again for your time,
Ben

**Comment by benstory** [comment] 2021-07-16 15:46
Also feel free to reach out on Slack if anything else needs to be changed - I check it more regularly than github.

**Comment by LiNk-NY** [comment] 2021-07-19 17:22
Hi Ben, @benstory 

Can anything be done about this warning? 

```r
* checking whether package 'mitoClone2' can be installed ... WARNING
Found the following significant warnings:
  ../inst/SCITEpkg/mcmcBinTreeMove.cpp:75:1: warning: control reaches end of non-void function [-Wreturn-type]
  bam2R_10x.cpp:145:9: warning: ISO C++ forbids variable length array ‘counts’ [-Wvla]
See '/home/user/bioc/mitoClone2.Rcheck/00install.out' for details.
```

Everything else looks good. Thanks for making those updates!

Best,
Marcel

**Comment by benstory** [comment] 2021-07-19 18:23
Hello Marcel @LiNk-NY,

The bam2R_10x warning should be fixed (although I'm not seeing it in the previous build report). The other warning is caused by the SCITE source code - I think it is very much **negligible**. I would prefer not to modify any of the source code from the external software package -  in order to be able to confidently tell the end-user that they are using a clone of the existing SCITE program (https://github.com/cbg-ethz/SCITE) that has not been modified in any way.

Hope that is alright with you. Thanks again for your help in this process.

Best,
Ben

**Comment by benstory** [comment] 2021-07-19 18:38
Looking into it a little further - I think it just depends on the compiler. `g++ -std=c++11` seems to not give any warnings whereas `clang++` does.

**Comment by benstory** [comment] 2021-07-20 22:37
@LiNk-NY 
Hi Marcel,

So looking at the SCITE code itself, I can randomly add a `return 0;` command to the end of the function causing the warning to suppress it. I'm not totally sure whether it will affect any functionality but I'm happy to make the change if it's required to move the package forward. Let me know your thoughts and I can push the commit, if necessary.

Thanks for your time,
Ben

**Comment by LiNk-NY** [comment] 2021-07-21 15:05
Hi Ben, @benstory 

Thank you for making those changes. 

Given that you include the `SCITE` software in your package it is appropriate to include the authors of that software as contributors in the `DESCRIPTION` file.

I am accepting your package. Thank you for your contribution. 
Please make sure to follow up with any feedback from `BiocCheck::BiocCheck()`. 

Best regards,
Marcel

**Comment by benstory** [comment] 2021-07-21 18:26
Awesome thanks for all the help Marcel @LiNk-NY !

**Comment by vjcitn** [comment] 2021-07-28 09:19
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/benstory.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mitoClone2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mitoClone2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-07-28 09:19 UTC
Labels: 3a. accepted, WARNINGS
