### ISSUE TITLE
vasp

### ISSUE THREAD

**Issue by yuhuihui2011** [Bioconductor/Contributions#1397] opened 2020-03-02 21:48 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yuhuihui2011/vasp

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by yuhuihui2011** [comment] 2020-03-02 22:11
> A reviewer has been assigned to your package. Learn [what to expect](https://github.com/Bioconductor/Contributions#what-to-expect)
> during the review process.
> 
> **IMPORTANT**: Please read [the instructions](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) for setting
> up a push hook on your repository, or further changes to your
> repository will NOT trigger a new build.

 A push hook has been added.

**Comment by yuhuihui2011** [comment] 2020-03-03 21:16
> Dear Package contributor,
> 
> This is the automated single package builder at bioconductor.org.
> 
> Your package has been built on Linux, Mac, and Windows.
> 
> On one or more platforms, the build results were: "skipped, ERROR".
> This may mean there is a problem with the package that you need to fix.
> Or it may mean that there is a problem with the build system itself.
> 
> Please see the [build report](http://bioconductor.org/spb_reports/vasp_buildreport_20200302165752.html) for more details.

I have updated a new version, could you please check it again?

**Comment by mtmorgan** [comment] 2020-03-03 21:36
@yuhuihui2011 you don't need to create a new repository, just increment the version number. It looks like you've done that, but it didn't trigger a new build, so check that the [web hook][1] is established correctly, and increment the version number again.

[1]: https://github.com/Bioconductor/Contributions#adding-a-web-hook

**Comment by yuhuihui2011** [comment] 2020-03-03 21:55
> @yuhuihui2011 you don't need to create a new repository, just increment the version number. It looks like you've done that, but it didn't trigger a new build, so check that the [web hook](https://github.com/Bioconductor/Contributions#adding-a-web-hook) is established correctly, and increment the version number again.

I have done that and the  VERSION BUMP REQUIRED has been removed. But the error has also exited.

**Comment by mtmorgan** [comment] 2020-03-03 22:24
Follow the 'build report' link to see the ERRORs for your package; make changes and then increment the version again.

**Comment by yuhuihui2011** [comment] 2020-03-06 18:44
Dear @Kayla-Morrell,
It looks like that the package built without errors or warnings on all platforms. Let me know if there are additional enhances you can suggest.
Thanks!
Huihui

**Comment by Kayla-Morrell** [comment] 2020-03-06 18:49
@yuhuihui2011 - Perfect, I'll begin my initial review of the package. I will comment back here with any necessary changes by the end of next week.

Thank you!
Kayla

**Comment by Kayla-Morrell** [comment] 2020-03-16 14:22
Hello @yuhuihui2011,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The 'figures' directory and content should be removed, it 
doesn't seem necessary.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to 'false'. It is our experience that 
when this field is 'true' it can slow down the loading of a packages, especially 
if it contains data.

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field which 
should include the relevant links to GitHub for reporting Issues.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an 
entire package. Unless you use many functions from the packages, I would suggest i
using `importFrom()`.

## NEWS

- [ ] REQUIRED: Thank you for including a NEWS file, we highly suggest them and 
find them very useful during release time. However, your news file isn't 
formated properly. Please see the following link to help format the file:
https://bioconductor.org/developers/package-guidelines/#news.

## Data

*data/*

- [ ] REQUIRED: There needs to be some more information documented for 
'rice.bg'. There needs to be information about the creation of the object (any 
filtering or processing that needed to be done) and the source of the data (is
there a source url for the data). 

*extdata/*

- [ ] REQUIRED: There needs to be an 'inst/script/' directory created. Since 
there was data included in 'inst/extdata/', a related script must be present in 
this directory documenting very clearly how the data was generated. It should 
include source urls and any important information regarding filtering or 
processing. It can be executible code, sudo code, or a text description. A user 
should be able to download and roughly reproduce the file or object that is 
present as data.

## Vignette

- [ ] REQUIRED: There should only the 'vasp.Rmd' file in this directory, the 
others are not necessary.

- [ ] SUGGESTION: We strongly encourage the use of a table of contents.

- [ ] SUGGESTION: Lines 48-51, you explain that the user needs to follow the 
manual for Ballgown to create a ballgown object and then you show code to make 
the ballgown object. I would mention that the user could create a ballgown 
object using files provided in your package and the code you provide, or that 
you provide a ballgown object with the package ('rice.bg').

- [ ] SUGGESTION: Once you use `data(rice.bg)` in line 68, you don't have to 
keep using it in each chunk of code.

- [ ] SUGGESTION: Once you use `library(Sushi)` in line 114, you don't have to 
keep using it in each chunk of code.

- [ ] SUGGESTION: For formating and reading purposes I would remove the extra 
spaces between the variable name and the definition in lines 138-141. 

## Man pages

- [ ] SUGGESTION: You might consider having a package man page with an overview 
of the package and links to the main functions.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them.

## R code

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 82 lines that are not.

Best,
Kayla

**Comment by yuhuihui2011** [comment] 2020-03-17 20:07
Hi @Kayla-Morrell,

Thank you for your review and comment. I have carefully check all your comments 
and updated the package. Please see the answers in _**bold and italic**_ as follows:
    
General package development

REQUIRED: The 'figures' directory and content should be removed, it
doesn't seem necessary.

_**A: I have changed the 'figures' directory to "README_files" since there are some 
files in the directory linking to README.md**_

DESCRIPTION

REQUIRED: 'LazyData:' should be set to 'false'. It is our experience that
when this field is 'true' it can slow down the loading of a packages, especially
if it contains data.

_**A: 'LazyData' has been set to 'false'**_

SUGGESTION: We strongly encourage the use of the 'BugReports:' field which
should include the relevant links to GitHub for reporting Issues.

_**A: 'BugReports' field added**_

NAMESPACE

SUGGESTION: Generally importFrom() is encouraged over importing an
entire package. Unless you use many functions from the packages, I would suggest i
using importFrom().

_**A: I have changed some functions to be imported by importFrom()**_

NEWS

REQUIRED: Thank you for including a NEWS file, we highly suggest them and
find them very useful during release time. However, your news file isn't
formated properly. Please see the following link to help format the file:
https://bioconductor.org/developers/package-guidelines/#news.
    
_**A: The format has been changed to as the link**_
    
Data

data/
    
REQUIRED: There needs to be some more information documented for
'rice.bg'. There needs to be information about the creation of the object (any
filtering or processing that needed to be done) and the source of the data (is
there a source url for the data).

_**A: Add more information about rice.bg, e.g. source, detail process and reference 
in the data.R and rice.bg.Rd**_

extdata/
    
REQUIRED: There needs to be an 'inst/script/' directory created. Since
there was data included in 'inst/extdata/', a related script must be present in
this directory documenting very clearly how the data was generated. It should
include source urls and any important information regarding filtering or
processing. It can be executible code, sudo code, or a text description. A user
should be able to download and roughly reproduce the file or object that is
present as data.

_**A: Add readme.txt file to the 'inst/script/' directory**_

Vignette

REQUIRED: There should only the 'vasp.Rmd' file in this directory, the
others are not necessary.

_**A: The other files were removed from the directory**_

SUGGESTION: We strongly encourage the use of a table of contents.

SUGGESTION: Lines 48-51, you explain that the user needs to follow the
manual for Ballgown to create a ballgown object and then you show code to make
the ballgown object. I would mention that the user could create a ballgown
object using files provided in your package and the code you provide, or that
you provide a ballgown object with the package ('rice.bg').

_**A: Add "Here is an example of constructing rice.bg object from 
HISAT2+StringTie output" to the end of the sentence to explain**_

SUGGESTION: Once you use data(rice.bg) in line 68, you don't have to
keep using it in each chunk of code.

_**A: only keep one**_

SUGGESTION: Once you use library(Sushi) in line 114, you don't have to
keep using it in each chunk of code.

_**A: only keep one**_

SUGGESTION: For formating and reading purposes I would remove the extra
spaces between the variable name and the definition in lines 138-141.

_**A: The extra spaces have been removed**_

Man pages

SUGGESTION: You might consider having a package man page with an overview
of the package and links to the main functions.

_**A: Add manuel file manual.pdf into inst/doc/ directory**_

Unit tests

SUGGESTION: Consider adding unit tests. We strongly encourage them.
R code

_**A: It says that "Unit tests, however, are best written as you develop code, 
rather than after your package is written" 
(http://bioconductor.org/developers/how-to/unitTesting-guidelines/). It is hard
for me to rewrite the package using unit tests**_

SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
line indents. There are 82 lines that are not.

_**A: All line indents are multiples of 4 spaces now**_


Please review it again!

Thanks,
Huihui

**Comment by Kayla-Morrell** [comment] 2020-03-19 16:43
@yuhuihui2011 - Thank you for making the necessary changes, I've looked over them over and everything looks good. I'd be more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment] 2020-03-24 13:51
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/yuhuihui2011.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("vasp")`. The package 'landing page' will be created at

https://bioconductor.org/packages/vasp

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-03-24 13:51 UTC
Labels: 3a. accepted, OK
