### ISSUE TITLE
New package for the alignment of mass-spectrometer runs

### ISSUE THREAD

**Issue by shubham1637** [Bioconductor/Contributions#1328] opened 2019-12-18 22:50 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shubham1637/DIAlignR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by shubham1637** [comment] 2019-12-29 18:31
@Kayla-Morrell I do not see any message if the previous build was successful.
Do you know why is it so?

**Comment by Kayla-Morrell** [comment] 2020-01-02 15:05
@shubham1637 - It seems that your last build on 12/23 got stuck at the building stage on the Windows builder and never completed. Therefore I kicked off a manual build, but there is still an ERROR on the Windows builder. This is something that needs to be fixed on our end and I will let you know when the problem is fixed.

Thanks for your patience,
Kayla

**Comment by Kayla-Morrell** [comment] 2020-01-06 14:34
@shubham1637 - Everything should be all set and you should get build messages now.

Best,
Kayla

**Comment by shubham1637** [comment] 2020-01-06 14:35
@Kayla-Morrell Thanks

**Comment by Kayla-Morrell** [comment] 2020-01-21 18:06
Hello @shubham1637 -  Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: The `doc/` directory is not needed and should be removed.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to 'false'. Whe have found when 
this tag is set to 'true' it can slow down the loading of the package, 
especially those that include data.

- [ ] SUGGESTION: Consider adding the automatically suggested biocViews tag
'Coverage'.

- [ ] SUGGESTION: It is encouraged to include 'BugReports:' field with a
relevant link to Github Issues.

## Data

- [ ] REQUIRED: The `data-raw/` files belong in an `inst/extdata/` directory.

## NEWS

- [ ] REQUIRED: A NEWS file is important for keeping track of changes to the 
code from one version to the next, so thank you for including it. However, the 
formatting is incorrect and doesn't render properly. Please take a look at our 
guidelines for NEWS files and change accordingly, 
https://bioconductor.org/developers/package-guidelines/#news.

## Vignette

- [ ] REQUIRED: The installation section should demonstrate to the user how to 
download the package from _Bioconductor_, not GitHub. The code provided should 
look something along the lines of the following and should remain `eval = FALSE`:

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DIAlignR")
```

Then the package can be loaded using `library()` like you have.

- [ ] SUGGESTION: We highly suggest the use of table of contents.

- [ ] REQUIRED: You should let the user know that there are example files for 
alignment in the package and that the steps starting at line 40 aren't 
manditory for them to complete. Either do this at line 36 before explaining the 
steps or at line 62 after explaining the steps.

- [ ] SUGGESTION: For all code chunks, I suggest making the code fit within the 
80 character window. That way it is easier for the user to read the code 
without having to use the scroll bar.

- [ ] REQUIRED: You only have to assign `dataPath` and `runs` once in the 
vignette, they will be remembered throughout the whole vignette. Please remove 
the multiple instances of them.

- [ ] REQUIRED: The last compilation section is not needed since it is included 
in the header information of the vignette.

- [ ] REQUIRED: The final section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

## Man pages

- [ ] REQUIRED: For any function that is documented but isn't exported you 
should add the tag `@keywords internal` so that they are removed from the 
documenation index.

- [ ] REQUIRED: In man pages under 'Author(s)' for 'License' I see the use of 
MIT but in your DESCRIPTION file you are using GPL-3. Should the license be the 
same without?

- [ ] REQUIRED: Examples of exported functions should contain runnable code, 
this means not using `dontrun` or `donttest`. Please fix the examples in the 
following man pages:
	- extractXIC_group
	- fetchAnalytesInfo
	- filenamesFromMZML
	- filenamesFromOSW
	- getAnalytesName
	- getLOESSfit
	- getLinearfit
	- getRefRun
	- mappedRTfromAlignObj
	- pickNearestFeature
	- readChromatogramHeader
	- selectChromIndices

- [ ] REQUIRED: The man pages describing new classes must be more detailed about 
the structure and what type of information is stored.

- [ ] REQUIRED: Use accessors; do not access S4 class slots via '@' in
examples/vignettes. Found in:
        man/doAffineAlignmentCpp.Rd
        man/doAlignmentCpp.Rd

*XIC_QFNNTDIVLLEDFQK_3_DIAlignR*

- [ ] REQUIRED: When the `data-raw/` files are moved, the source information 
needs to be changed.

*areaIntegrator*

- [ ] REQUIRED: Add a runnable example since this man page documents exported 
objects.

*getAlignedFigs*

- [ ] REQUIRED: The description for this function does not make sense, 
'AlignObjOutput' is mentioned but I see 'AlignObj' used in the function call.

## inst/script

- [ ] REQUIRED: The scripts in this directory can vary. Most importantly if data 
was included in the `inst/extdata/` directory, a related script must be present 
in this directory documenting very clearly how the data was generated. It should 
include source urls and any important information regarding filtering or 
processing. It can be executible code, sudo code, or a text description. A user 
should be able to download the data and roughly reproduce the file or object 
that is present as data. I also believe this is a good place to have the scripts 
in your 'data-raw/' directory since they describe how the data was generated 
in 'data'. This will ensure all code is distributed with your package.

## R code

- [ ] SUGGESTION: For the functions 'getAlignObj' and 'getAlignObjs' I believe 
one of them should be renamed because it isn't clear from the names on how they 
might be different. 

- [ ] REQUIRED: Avoid `1:...`, instead use `seq_len()` or `seq_along()`. Found 
in files:
        merge_osw_mzml.R, line 100
        read_osw.R, line 99
        visualise_chromatograms.R, lines 35 and 119

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 785 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 714 lines that are not.

Best,
Kayla

**Comment by shubham1637** [comment] 2020-01-22 20:10
@Kayla-Morrell I get a REQUIRED change "The `data-raw/` files belong in an `inst/extdata/` directory."

The `data-raw/` files are text files used to generate data rather than data itself. Therefore, I don't think these should be in `inst/extdata/` directory. For example this package https://github.com/hadley/usdanutrients

**Comment by shubham1637** [comment] 2020-01-23 06:05
Hi @Kayla-Morrell I have made most of the changes as suggested, checked in the boxes. Few REQUIRED suggestions I have not followed and provided an explanation for them.

> Hello @shubham1637 - Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.
> 
> ## General package development
> * [x]  REQUIRED: The `doc/` directory is not needed and should be removed.
> 
> ## DESCRIPTION
> * [x]  REQUIRED: 'LazyData:' should be set to 'false'. Whe have found when
>   this tag is set to 'true' it can slow down the loading of the package,
>   especially those that include data.
> * [ ]  SUGGESTION: Consider adding the automatically suggested biocViews tag
>   'Coverage'.
> * [x]  SUGGESTION: It is encouraged to include 'BugReports:' field with a
>   relevant link to Github Issues.
> 
> ## Data
> * [ ]  REQUIRED: The `data-raw/` files belong in an `inst/extdata/` directory.

The data-raw/ files are text files used to generate data rather than data itself. Therefore, I don't think these should be in inst/extdata/ directory. For example this package https://github.com/hadley/usdanutrients

> 
> ## NEWS
> * [x]  REQUIRED: A NEWS file is important for keeping track of changes to the
>   code from one version to the next, so thank you for including it. However, the
>   formatting is incorrect and doesn't render properly. Please take a look at our
>   guidelines for NEWS files and change accordingly,
>   https://bioconductor.org/developers/package-guidelines/#news.
> 
> ## Vignette
> * [x]  REQUIRED: The installation section should demonstrate to the user how to
>   download the package from _Bioconductor_, not GitHub. The code provided should
>   look something along the lines of the following and should remain `eval = FALSE`:
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("DIAlignR")
> ```
> 
> Then the package can be loaded using `library()` like you have.
> 
> * [x]  SUGGESTION: We highly suggest the use of table of contents.
> * [x]  REQUIRED: You should let the user know that there are example files for
>   alignment in the package and that the steps starting at line 40 aren't
>   manditory for them to complete. Either do this at line 36 before explaining the
>   steps or at line 62 after explaining the steps.
> * [x]  SUGGESTION: For all code chunks, I suggest making the code fit within the
>   80 character window. That way it is easier for the user to read the code
>   without having to use the scroll bar.
> * [x]  REQUIRED: You only have to assign `dataPath` and `runs` once in the
>   vignette, they will be remembered throughout the whole vignette. Please remove
>   the multiple instances of them.
> * [x]  REQUIRED: The last compilation section is not needed since it is included
>   in the header information of the vignette.
> * [x]  REQUIRED: The final section of the vignette should be 'Session Info' and
>   should include `sessionInfo()`.
> 
> ## Man pages
> * [x]  REQUIRED: For any function that is documented but isn't exported you
>   should add the tag `@keywords internal` so that they are removed from the
>   documenation index.
> * [x]  REQUIRED: In man pages under 'Author(s)' for 'License' I see the use of
>   MIT but in your DESCRIPTION file you are using GPL-3. Should the license be the
>   same without?
> * [ ]  REQUIRED: Examples of exported functions should contain runnable code,
>   this means not using `dontrun` or `donttest`. Please fix the examples in the
>   following man pages:
>   * extractXIC_group
>   * fetchAnalytesInfo
>   * filenamesFromMZML
>   * filenamesFromOSW
>   * getAnalytesName
>   * getLOESSfit
>   * getLinearfit
>   * getRefRun
>   * mappedRTfromAlignObj
>   * pickNearestFeature
>   * readChromatogramHeader
>   * selectChromIndices

These are the internal functions that are not exported. These examples will throw an error if run. After having the tag `@keywords internal`, these functions should not be in the documentation index.

> * [x]  REQUIRED: The man pages describing new classes must be more detailed about
>   the structure and what type of information is stored.
> * [x]  REQUIRED: Use accessors; do not access S4 class slots via '@' in
>   examples/vignettes. Found in:
>   man/doAffineAlignmentCpp.Rd
>   man/doAlignmentCpp.Rd
> 
> _XIC_QFNNTDIVLLEDFQK_3_DIAlignR_
> 
> * [ ]  REQUIRED: When the `data-raw/` files are moved, the source information
>   needs to be changed.
> 
> _areaIntegrator_
> 
> * [x]  REQUIRED: Add a runnable example since this man page documents exported
>   objects.
> 
> _getAlignedFigs_
> 
> * [x]  REQUIRED: The description for this function does not make sense,
>   'AlignObjOutput' is mentioned but I see 'AlignObj' used in the function call.
> 
> ## inst/script
> * [ ]  REQUIRED: The scripts in this directory can vary. Most importantly if data
>   was included in the `inst/extdata/` directory, a related script must be present
>   in this directory documenting very clearly how the data was generated. It should
>   include source urls and any important information regarding filtering or
>   processing. It can be executible code, sudo code, or a text description. A user
>   should be able to download the data and roughly reproduce the file or object
>   that is present as data. I also believe this is a good place to have the scripts
>   in your 'data-raw/' directory since they describe how the data was generated
>   in 'data'. This will ensure all code is distributed with your package.
> 

I think your explanation is reasonable that the user will get the script if it is in the `inst/extdata/` directory. We generally access this data using `system.file` that is meant for the data rather than the script. The script is only useful for developer, therefore, should be hidden from the user. I think the script should be in `data-raw`. Let me know if you think otherwise.

> ## R code
> * [ ]  SUGGESTION: For the functions 'getAlignObj' and 'getAlignObjs' I believe
>   one of them should be renamed because it isn't clear from the names on how they
>   might be different.
> * [ ]  REQUIRED: Avoid `1:...`, instead use `seq_len()` or `seq_along()`. Found
>   in files:
>   merge_osw_mzml.R, line 100
>   read_osw.R, line 99
>   visualise_chromatograms.R, lines 35 and 119

In these files, I am not interating throguh a vector rather a data-frame or matrix, therefore, `seq_len()` and `seq_along()` can't provide the necessary behavior.

> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 785
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 714 lines that are not.
> 
> Best,
> Kayla

Thanks very much for taking the time and evaluating the package.

Best,
Shubham

**Comment by Kayla-Morrell** [comment] 2020-02-03 16:22
@shubham1637 - Thank you for making those changes. I have just a few final requirements and then I can accept the package. Please see the notes below.

## Data

- [ ] REQUIRED: Thank you for clarifying about the `data-raw/` directory. If
you do not want to move the scripts to the `inst/extdata/` directory then I ask
for some minor modifications. You claim that these scripts are only useful for
the developer, but then in the man pages for the rdata files in `data/` you
point the user to this directory for source information. This forces the user
to look to the `data-raw/` directory if they want more information. My
suggestion would be to add the source to the raw data in the man page, whether
that be stating the data came from NCBI and providing a url, explaining it was        generated from your lab using a specific machine or technique, what ever it may
be. Then state if they want more information they can look to the scripts in
`data-raw/` and point them to github. This way the user isn't forced to the
directory unless they want more thorough details about the data and they can get
a general understanding of the source just from the man pages.

## Man pages

- [ ] REQUIRED: About changing the licenses in the man pages from MIT to GPL-3,
I see the changes made in the documentation in the R files but the changes
aren't reflected in the man pages. I see the addition of `\keyword{internal}` to
the man pages, perhaps you forgot to run a document command after making the
license change and never commited these changes? There also seems to still be
MIT listed in the RcppExports.R file, should they be changed here as well?

- [ ] REQUIRED: The same goes for the more detail in the class man pages. I see
the changes in the documentation of the R files, but the man pages remain
unchanged.

- [ ] REQUIRED: The same also for changing to use `slot()` instead of `@` in
the examples of the man pages. I see the change in the documentation in the R
file but I don't see the changes reflected in the man pages.

- [ ] REQUIRED: The same as above for the example added to the areaIntegrator
man page.

- [ ] REQUIRED: The same as above for update to the description of the
getAlignedFigs man page.

Best,
Kayla

**Comment by shubham1637** [comment] 2020-02-04 16:57
Dear @Kayla-Morrell , I have made the required changes as you have mentioned. Thanks for going through this package.
> ## Data
> * [X]  REQUIRED: Thank you for clarifying about the `data-raw/` directory. If
>   you do not want to move the scripts to the `inst/extdata/` directory then I ask
>   for some minor modifications. You claim that these scripts are only useful for
>   the developer, but then in the man pages for the rdata files in `data/` you
>   point the user to this directory for source information. This forces the user
>   to look to the `data-raw/` directory if they want more information. My
>   suggestion would be to add the source to the raw data in the man page, whether
>   that be stating the data came from NCBI and providing a url, explaining it was generated from your lab using a specific machine or technique, what ever it may
>   be. Then state if they want more information they can look to the scripts in
>   `data-raw/` and point them to github. This way the user isn't forced to the
>   directory unless they want more thorough details about the data and they can get
>   a general understanding of the source just from the man pages.
> 
Thanks very much for pointing this out. I have added a web-link in the `data/` documentation. The data is downloaded from an online repository Peptide-Atlas. I have attached a link to it. The repository has all metadata associated with the data.

> ## Man pages
> * [X]  REQUIRED: About changing the licenses in the man pages from MIT to GPL-3,
>   I see the changes made in the documentation in the R files but the changes
>   aren't reflected in the man pages. I see the addition of `\keyword{internal}` to
>   the man pages, perhaps you forgot to run a document command after making the
>   license change and never commited these changes? There also seems to still be
>   MIT listed in the RcppExports.R file, should they be changed here as well?
> * [X]  REQUIRED: The same goes for the more detail in the class man pages. I see
>   the changes in the documentation of the R files, but the man pages remain
>   unchanged.
> * [X]  REQUIRED: The same also for changing to use `slot()` instead of `@` in
>   the examples of the man pages. I see the change in the documentation in the R
>   file but I don't see the changes reflected in the man pages.
> * [X]  REQUIRED: The same as above for the example added to the areaIntegrator
>   man page.
> * [X]  REQUIRED: The same as above for update to the description of the
>   getAlignedFigs man page.

I have run `devtools::document()` to modify the `man/` pages. I want to keep C++ code under the MIT license so that it can be freely used. Therefore, I have not changed licensing for RcppExports.R as well.

Thanks again.
Best,
Shubham

**Comment by Kayla-Morrell** [comment] 2020-02-06 17:27
@shubham1637  - Perfect, thank you for making those last few changes. Everything looks good now and I'd be happy to accept the package. Thank you again for your contribution.

Best,
Kayla

**Comment by mtmorgan** [comment] 2020-02-14 20:30
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/shubham1637.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DIAlignR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DIAlignR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-02-14 20:30 UTC
Labels: 3a. accepted, OK
