### ISSUE TITLE
HubPub

### ISSUE THREAD

**Issue by Kayla-Morrell** [Bioconductor/Contributions#2090] opened 2021-04-23 19:11 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor/HubPub

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment] 2021-04-28 17:25
Hi Kayla,

HubPub sounds like a nice place to hang around with friends ;-)

(They actually have a building here on UW campus in Seattle called "The Hub" that is the center of student life. Unfortunately no pub there.)

I'll check the package later today.

H.

**Comment by Kayla-Morrell** [comment] 2021-04-28 20:22
Thanks Herve, I'll try to get to cleaning up the examples ERROR later today. 

Best,
Kayla

**Comment by hpages** [comment] 2021-04-29 01:20
Ok, I'm actually going to wait for you to do that before I take a look at the package. Thanks!

**Comment by hpages** [comment] 2021-05-07 05:59
Hi Kayla,

I'm getting this error today when I run `R CMD build` on the latest **HubPub** (0.99.1):
```
hpages@spectre:~$ R CMD build HubPub
* checking for file ‘HubPub/DESCRIPTION’ ... OK
* preparing ‘HubPub’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘HubPub.Rmd’ using rmarkdown
Quitting from lines 96-117 (HubPub.Rmd) 
Error: processing vignette 'HubPub.Rmd' failed with diagnostics:
identical(colnames(taxdb), c("tax_id", "genus", "species")) is not TRUE
--- failed re-building ‘HubPub.Rmd’

SUMMARY: processing the following file failed:
  ‘HubPub.Rmd’

Error: Vignette re-building failed.
Execution halted
```
If I `R CMD Stangle HubPub.Rmd` and source `HubPub.R`, I get:
```
> source("HubPub.R", echo=TRUE)

> ## ----setup, include = FALSE---------------------------------------------------
> knitr::opts_chunk$set(
+     collapse = TRUE,
+     comment = "#> ..." ... [TRUNCATED] 

> ## ----bioconductor, eval = FALSE-----------------------------------------------
> ## if(!requireNamespace("BiocManager", quietly = TRUE))
> ##      .... [TRUNCATED] 
Bioconductor version 3.13 (BiocManager 1.30.12.2), ?BiocManager::install for
  help

> ## ----create-------------------------------------------------------------------
> fl <- tempdir()

> create_pkg(file.path(fl, "/examplePkg"), "ExperimentHub")
✔ Creating '/tmp/RtmpgNkxr2/examplePkg/'
✔ Setting active project to '/tmp/RtmpgNkxr2/examplePkg'
✔ Creating 'R/'
✔ Writing 'DESCRIPTION'
Package: examplePkg
Title: What the Package Does (One Line, Title Case)
Version: 0.99.0
Date: 2021-05-06
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
Description: What the package does (one paragraph).
License: Artistic-2.0
BugReports: https://support.bioconductor.org/t/examplePkg
Imports:
    ExperimentHub
biocViews: ExperimentHub
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
✔ Writing 'NAMESPACE'
✔ Setting active project to '<no active project>'
✔ Setting active project to '/tmp/RtmpgNkxr2/examplePkg'
✔ Initialising Git repo
✔ Adding '.Rproj.user', '.Rhistory', '.Rdata', '.httr-oauth', '.DS_Store' to '.gitignore'
✔ Writing 'R/examplePkg-package.R'
✔ Writing 'NEWS.md'
✔ Creating 'man/'
✔ Creating 'inst/scripts/'
✔ Writing 'inst/scripts/make-data.R'
✔ Writing 'inst/scripts/make-metadata.R'
✔ Writing 'R/zzz.R'
✔ Creating 'inst/extdata/'
✔ Adding 'testthat' to Suggests field in DESCRIPTION
✔ Setting Config/testthat/edition field in DESCRIPTION to '3'
✔ Creating 'tests/testthat/'
✔ Writing 'tests/testthat.R'
• Call `use_test()` to initialize a basic test file and open it for editing.
✔ Writing 'tests/testthat/test_metadata.R'
[1] "/tmp/RtmpgNkxr2//examplePkg"

> ## ----resource-----------------------------------------------------------------
> metadata <- metadata(
+     Title = "ENCODE",
+     Description = .... [TRUNCATED] 

> add_resource(file.path(fl, "/examplePkg"), metadata)
Error in loadTaxonomyDb() : 
  identical(colnames(taxdb), c("tax_id", "genus", "species")) is not TRUE
```
Can you reproduce this?

The fact that the package was passing `R CMD build` 7 days ago (and has not changed since then) suggests a change in some dependency.

Thanks,
H.

**sessionInfo():**
```
R Under development (unstable) (2021-03-08 r80083)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Matrix products: default
BLAS:   /home/hpages/R/R-4.1.r80083/lib/libRblas.so
LAPACK: /home/hpages/R/R-4.1.r80083/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB              LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] futile.logger_1.4.3 HubPub_0.99.1      

loaded via a namespace (and not attached):
  [1] rjson_0.2.20                  ellipsis_0.3.2               
  [3] rprojroot_2.0.2               XVector_0.31.1               
  [5] GenomicRanges_1.43.4          base64enc_0.1-3              
  [7] fs_1.5.0                      rstudioapi_0.13              
  [9] roxygen2_7.1.1                getopt_1.20.3                
 [11] bit64_4.0.5                   interactiveDisplayBase_1.29.0
 [13] AnnotationDbi_1.53.1          fansi_0.4.2                  
 [15] xml2_1.3.2                    codetools_0.2-18             
 [17] biocthis_1.1.10               cachem_1.0.4                 
 [19] knitr_1.33                    jsonlite_1.7.2               
 [21] Rsamtools_2.7.2               dbplyr_2.1.1                 
 [23] png_0.1-7                     graph_1.69.0                 
 [25] shiny_1.6.0                   BiocManager_1.30.12.2        
 [27] compiler_4.1.0                httr_1.4.2                   
 [29] backports_1.2.1               assertthat_0.2.1             
 [31] Matrix_1.3-3                  fastmap_1.1.0                
 [33] cli_2.5.0                     formatR_1.9                  
 [35] later_1.2.0                   htmltools_0.5.1.1            
 [37] prettyunits_1.1.1             tools_4.1.0                  
 [39] glue_1.4.2                    GenomeInfoDbData_1.2.5       
 [41] dplyr_1.0.6                   rappdirs_0.3.3               
 [43] Rcpp_1.0.6                    Biobase_2.51.0               
 [45] styler_1.4.1                  vctrs_0.3.8                  
 [47] Biostrings_2.59.2             ExperimentHub_1.99.5         
 [49] rtracklayer_1.51.5            optparse_1.6.6               
 [51] xfun_0.22                     stringr_1.4.0                
 [53] testthat_3.0.2                mime_0.10                    
 [55] lifecycle_1.0.0               restfulr_0.0.13              
 [57] sys_3.4                       XML_3.99-0.6                 
 [59] stringdist_0.9.6.3            AnnotationHub_2.99.5         
 [61] zlibbioc_1.37.0               BiocCheck_1.27.16            
 [63] hms_1.0.0                     promises_1.2.0.1             
 [65] credentials_1.3.0             MatrixGenerics_1.3.1         
 [67] parallel_4.1.0                SummarizedExperiment_1.21.3  
 [69] RBGL_1.67.0                   lambda.r_1.2.4               
 [71] gert_1.3.0                    yaml_2.2.1                   
 [73] curl_4.3.1                    memoise_2.0.0                
 [75] aws.signature_0.6.0           biomaRt_2.47.9               
 [77] stringi_1.5.3                 RSQLite_2.2.7                
 [79] BiocVersion_3.13.1            S4Vectors_0.29.19            
 [81] BiocIO_1.1.2                  desc_1.3.0                   
 [83] GenomicFeatures_1.43.8        BiocGenerics_0.37.5          
 [85] filelock_1.0.2                BiocParallel_1.25.5          
 [87] GenomeInfoDb_1.27.11          rlang_0.4.11                 
 [89] pkgconfig_2.0.3               bitops_1.0-7                 
 [91] matrixStats_0.58.0            lattice_0.20-44              
 [93] purrr_0.3.4                   GenomicAlignments_1.27.2     
 [95] bit_4.0.4                     tidyselect_1.1.1             
 [97] AnnotationForge_1.33.3        magrittr_2.0.1               
 [99] R6_2.5.0                      IRanges_2.25.11              
[101] generics_0.1.0                RUnit_0.4.32                 
[103] available_1.0.4               DelayedArray_0.17.13         
[105] DBI_1.1.1                     pillar_1.6.0                 
[107] whisker_0.4                   withr_2.4.2                  
[109] biocViews_1.59.3              KEGGREST_1.31.2              
[111] RCurl_1.98-1.3                tibble_3.1.1                 
[113] crayon_1.4.1                  futile.options_1.0.1         
[115] utf8_1.2.1                    OrganismDbi_1.33.0           
[117] BiocFileCache_1.99.7          aws.s3_0.3.21                
[119] progress_1.2.2                usethis_2.0.1                
[121] grid_4.1.0                    ExperimentHubData_1.17.4     
[123] blob_1.2.1                    digest_0.6.27                
[125] xtable_1.8-4                  httpuv_1.6.0                 
[127] openssl_1.4.4                 stats4_4.1.0                 
[129] AnnotationHubData_1.21.9      askpass_1.1                  
```

**Comment by Kayla-Morrell** [comment] 2021-05-11 12:46
@hpages - This should be fixed now with GenomeInfoDbData v1.2.6.

**Comment by hpages** [comment] 2021-05-12 08:39
Hi Kayla, can you bump the version and push so that we get a new build? Thanks.  H.

**Comment by hpages** [comment] 2021-05-12 16:34
Thanks for the version bump. Unfortunately it seems that **GenomeInfoDbData** didn't get updated on malbec2 yet, sorry for that.

I spotted a few minor things in the package:

1. The `metadata()` function in **HubPub** conflicts with the `metadata()` function in **S4Vectors**.

2. You should never make explicit use of `/` in things like `file.path()` or `system.file()`. The only reason a function like `file.path()` exists in the first place is to build file paths without the need to explicitly use `/`, which is not portable. Note that other programming languages provide something equivalent to build file paths in a portable way e.g. `os.path.join` in Python:
    ```
    >>> import os
    >>> os.path.join("path", "to", "my", "file")
    'path/to/my/file'
    ```

3. It's not clear to me why the `biocViews` field contains the term `GUI`. Does the package provide some sort of Graphical User Interface?

4. In the vignette:

    > The create_pkg() function creates the skeleton of a package that follows the guidelines for a Bioconductor Hub type package.

   Would be nice if the link to these guidelines was provided here instead of at the end of the section. Furthermore it seems that ideally the "Creating A Hub Package: ExperimentHub or AnnotationHub" vignette that is currently in **AnnotationHub** would be in a better place in **HubPub**. Maybe something to consider once the package is in Bioconductor. Then **ExperimentHub**'s and **AnnotationHub**'s documentation would only need to have quick references to the document in **HubPub**, and the 2 packages would `Suggests` **HubPub**.

    > will not be benefit the developer

    Remove "be".

Other than that, the package looks good.

Thanks,
H.

**Comment by Kayla-Morrell** [comment] 2021-05-12 19:57
@hpages - Thanks for the notes and taking a look through the package, hopefully the build report posts soon. I just wanted to summarize the changes that I made.

1. I renamed the `metadata()` function to `hub_metadata()` and changed in all code/documentation/tests.
2. I removed any `/` in `file.path()`, sorry I over looked these originally when I was changing from `paste0()` to `file.path()`.
3. I removed `GUI` `from biocviews`, this was a copied over term from AH and EH but I agree it didn't fit here.
4. I moved up the link to the "Creating a Hub Package" vignette as you suggested and removed "be" in the text you pointed out. I'll keep your note in mind about moving "Creating A Hub Package: ExperimentHub or AnnotationHub" vignette to HubPub in the future, this is something that I'll have to run by Lori.

Best,
Kayla

**Comment by hpages** [comment] 2021-05-12 23:10
Thanks Kayla.

We've updated R on all the build machines today so maybe that's causing some delays with the SPB, I don't know. It could also be that the SPB tried to start the build while we were in the middle of updating R on the builders in which case the SPB wouldn't be able to start anything.

Anyways I ran `R CMD build` + `R CMD check` + `BiocCheck` on **HubPub** on my laptop and everything is clean.

Thanks again,
H.

**Comment by vjcitn** [comment] 2021-05-13 16:55
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Kayla-Morrell.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HubPub")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HubPub

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-05-13 16:55 UTC
Labels: 3a. accepted, ERROR
