### ISSUE TITLE
methylGSA

### ISSUE THREAD

**Issue by reese3928** [Bioconductor/Contributions#758] opened 2018-05-22 16:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/reese3928/methylGSA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by reese3928** [comment] 2018-05-25 03:07
Hi Marcel @LiNk-NY ,

My package kept suffering from time out error when building on OS X and Linux. I really couldn't figure out why. I built my package on other OS X and Linux systems and it works well. Could you give some hint on the time out error? Thanks!

**Comment by reese3928** [comment] 2018-05-29 17:23
Hi, Marcel @LiNk-NY 

Thanks much for your response. My name is Xu Ren.

Indeed, I imported a large dataset package. My package is used to perform gene set testing with length bias adjustment for DNA methylation data. One important step is to get gene symbol and their corresponding CpG IDs on Illumina 450K array. I get the CpG IDs from IlluminaHumanMethylation450kanno.ilmn12.hg19 package using getAnnotation function in minfi package. But this process takes some time, which makes R CMD check exceed 5 min time limit. However, getting the annotation is an essential step and it cannot be avoided.

Thanks again,
Xu Ren

**Comment by LiNk-NY** [comment] 2018-05-29 18:45
Hi Xu Ren, @reese3928 
Thank you for your submission to Bioconductor.
Please find your review below. 
I have asked a collaborator (@lgeistlinger) with expertise in GSEA to
provide comments on the contents of the package. 

If you have any questions or comments, please feel free to include them below. 

Best regards,
Marcel

---

# methylGO #758

* `methylGO` does not only provide access to GO resources but also KEGG
and Reactome databases. Consider renaming the package to reflect its
utility.

## DESCRIPTION

* Please format `Imports:` field so that the listed packages are clearly
legible.
* Update your `Depends:` field to R version >= 3.5.0.
* Consider using `Authors@R` field to combine `Author` and `Maintainer` fields.

## NAMESPACE

* Looks good.

## R

* Consider combining toy dataset roxygen blocks into a single file
(e.g., GSlisttoy.R, cpgtoy.R > toydatasets.R)
* Include how you generated these datasets in a script under `/inst/scripts` or
`/data-raw`; if datasets are subsets of actual data please include a source.
* Avoid using `sapply` and use the more robust `vapply`
* The code for the options in `getGS` is quite similar. Consider using a helper
function to avoid repetitive code.
* Use `vapply` instead of `unlist(lapply())` if the `lapply` output is
consistent.
* Reference subsetting values using names rather than numbers
(e.g., `GSEAres[, "variable"]` instead of `GSEAres[, 1]`)
* Reuse `getAnnot` functionality within `methylgometh` to avoid repetitive
code.

Minor:
* `return()` is unnecessary within an `lapply` loop as the last evaluated
piece of code is returned

## vignettes

* It's good that you added example datasets. The procedure looks straight
forward.
* Please include your `sessionInfo` at the end of the vignette.

## tests

* Please add tests to your package to keep the code robust and maintenance
low.

## inst/NEWS

* Please add a NEWS file for providing updates on user facing,
internal improvements, and bug fixes.

**Comment by reese3928** [comment] 2018-05-29 19:36
Hi Marcel @LiNk-NY and @lgeistlinger,

Thanks much for your detailed review and comments. We will update the package according to your review. 

Xu Ren

**Comment by reese3928** [comment] 2018-05-30 18:33
Hi Marcel @LiNk-NY,

We have updated the package and addressed each item in your review. However, there are a couple of things that I'd like to confirm with you before we push the update to Github.

1. We have added tests to our package, but as you know, we have the timeout issue because of importing a large annotation dataset. If we include these tests, R CMD check is going to take longer and the timeout issue is more likely to be triggered. Is this going to be a problem?

2. If we change the package name and repository name on Github, is this issue #758 still going to work well? e.g. Is the webhook going to be affected?

Thanks,
Xu Ren

**Comment by lgeistlinger** [comment] 2018-06-03 21:16
Hi @reese3928 and @LiNk-NY 

The vignette sufficiently describes methodological details and provides literature for readers interested in more background.

I have only minor comments:

- Agreed with @LiNk-NY : package name should be more general such as `methylGSA` or `methylEnrich` given that you provide a selection of enrichment methods and a range of gene set definitions

- Consider using Bioconductor core data structures for representing gene sets as implemented in `GSEABase` - that's not ultimately necessary given the common representation as a list of character vectors; however, benefits of using the classes `GeneSet` and `GeneSetCollection` from `GSEABase` include interoperability with other Bioconductor packages and, in particular, straightforwad mapping between various gene ID types

- Note that you are actually applying here a version of [`GSEApreranked`](http://software.broadinstitute.org/cancer/software/genepattern/modules/docs/GSEAPreranked/1) (which is a gene-sampling procedure) and not the original GSEA procedure (which is a subject-sampling procedure)

**Comment by reese3928** [comment] 2018-06-04 03:11
Hi @lgeistlinger,

Thanks very much for your comments. We will address these issues and update the package. 

Xu Ren

**Comment by LiNk-NY** [comment] 2018-06-05 16:14
Hi Xu Ren, @reese3928 

1. If possible, import a smaller subset of the annotation dataset for your examples. If this is an actual dataset that you need in the package code, I suggest you increase the timeout limit. Perhaps @lshep or @mtmorgan can comment further on this. 

2. You'd have to create another issue under [Bioconductor/Contributions](https://github.com/Bioconductor/Contributions) after renaming your repository. 

Thank you Ludwig @lgeistlinger for the insightful comments!

Regards,
Marcel

**Comment by LiNk-NY** [comment] 2018-06-05 16:17
Please bump your package version for a more recent build.

**Comment by reese3928** [comment] 2018-06-06 16:39
Hi Marcel @LiNk-NY,

We have pushed the latest build. Please check, thanks.

**Comment by LiNk-NY** [comment] 2018-06-06 21:12
Hi Xu Ren, @reese3928

Hervé took a deeper look into why your package is taking a long time to check.
Here is his feedback:

> Couldn't this mapping be obtained in a more efficient way? [The data] is still too big (91Mb) to be stored in the package. Did they talk with the `IlluminaHumanMethylationEPICanno.ilm10b2.hg19` folks (Kasper group) for the best way to get this mapping? The `IlluminaHumanMethylationEPICanno.ilm10b2.hg19` package should be designed in a way that makes this kind of query easy and fast.

Could you respond to these questions? 
Thanks! 

-Marcel 


cc: @kasperdanielhansen

**Comment by kasperdanielhansen** [comment] 2018-06-07 08:41
I have not looked at the code in the package, and the build reports seems to have expired so I cannot see timings on individual examples.

In principle, the author is doing it correctly, with the following caveat: you want to use `getAnnotation()` directly on the minfi object like `getAnnotation(gmSet)` to get a 1-1 mapping between rows of the minfi object and the output. 

I am aware that this is not exactly _super_ fast but I am surprised to learn that it should take a _really_ long time to do.  A brief, clear pointer to the offending code and some idea of time would be useful to me. Nevertheless, for other reasons, we are currently strongly contemplating a redesign of the annotation packages which should make this faster and more memory efficient.

A final comment: mapping CpG loci to genes is non-trivial. The `getAnnotation()` function uses a mapping supplied by Illumina.  I strongly suggest that a package doing GO annotation analysis for methylation arrays (which would be nice) allows for a custom (aka user-supplied) link between CpGs and genes. Perhaps this is already supported; I have not looked at the package code.

**Comment by lshep** [comment] 2018-06-07 11:37
@kasperdanielhansen  Sorry about this.  We seem to have something going on on our end with the build reports.  I'm investigating this.

**Comment by lshep** [comment] 2018-06-07 11:45
Actaully @lgeistlinger   I realized the issue is not with our builder -  You have named your package differently in the DESCRIPTION than you have as the repository.  This is not allowed.

**Comment by lshep** [comment] 2018-06-07 12:44
@reese3928 You don't have to create a new issue.  If you rename your repository and update the link at the top of the page,  I can take the necessary steps on our end to utilize this same issue.  Its not advertised as it takes some extra effort on our end but it is possible.  Let me know when the renaming has happened and I'll proceed on our end -  Please don't push any version bumps to the package until I respond that we are all set as they will not work.

**Comment by reese3928** [comment] 2018-06-07 23:57
Hi @lshep, I have renamed the repository and updated the link at the top of this page. Please check. Thanks.

**Comment by lshep** [comment] 2018-06-08 11:44
Please try bumping the version of your package to see if it will build.

**Comment by reese3928** [comment] 2018-06-08 12:15
@lshep Version bump works, thanks.

**Comment by reese3928** [comment] 2018-06-08 14:01
Hi Marcel, @LiNk-NY, 

The package is renamed, and all the issues in your previous review are addressed. Please check, thanks.

**Comment by reese3928** [comment] 2018-06-10 05:43
"methylGO does not only provide access to GO resources but also KEGG
and Reactome databases. Consider renaming the package to reflect its
utility."
- Package is renamed to methylGSA.
# **DESCRIPTION**
"Please format Imports: field so that the listed packages are clearly
legible."
- `Imports:`field is formatted. 

"Update your Depends: field to R version >= 3.5.0."
- `Depends` field is updated to R version 3.5.

"Consider using Authors@R field to combine Author and Maintainer fields."
- `Author` and `Maintainer` fields are changed to `Authors@R`.

# **R**

"Consider combining toy dataset roxygen blocks into a single file
(e.g., GSlisttoy.R, cpgtoy.R > toydatasets.R)"
- GSlisttoy.R and cpgtoy.R are combined to toydatasets.R.

"Include how you generated these datasets in a script under /inst/scripts or
/data-raw; if datasets are subsets of actual data please include a source."
- The code generated these datasets are included in scripts under `inst/scripts`.

"Avoid using sapply and use the more robust vapply
The code for the options in getGS is quite similar. Consider using a helper
function to avoid repetitive code."
- `sapply` are changed to `vapply`.

"The code for the options in getGS is quite similar. Consider using a helper
function to avoid repetitive code."
- The code in `getGS` is reorganized to avoid repetitive code. 

"Use vapply instead of unlist(lapply()) if the lapply output is
consistent."
- Used `vapply` instead of `unlist(lapply())`.

"Reference subsetting values using names rather than numbers
(e.g., GSEAres[, "variable"] instead of GSEAres[, 1])"
- Changes made.

"Reuse getAnnot functionality within methylgometh to avoid repetitive
code."
- Code in `methylgometh` is reorganized to avoid repetitive code. 

"return() is unnecessary within an lapply loop as the last evaluated
piece of code is returned"
- `return` is removed. 

# **vignettes**
"Please include your sessionInfo at the end of the vignette.
tests"
- `sessionInfo` is included.

# **tests**
"Please add tests to your package to keep the code robust and maintenance
low."
- tests are included in `tests/`

# **NEWS**
"Please add a NEWS file for providing updates on user facing,
internal improvements, and bug fixes."
- NEWS.md file is included.

**Comment by LiNk-NY** [comment] 2018-06-13 16:57
Hi Xu Ren, @reese3928 

Thanks for making those changes.
Can you respond to the comment left by Kasper? 

Regards, 
Marcel

**Comment by reese3928** [comment] 2018-06-13 17:32
Hi Marcel @LiNk-NY,

1. For the caveat, I tried using getAnnotation(object) directly, but R CMD build failed. The object name is  illuminahumanmethylation450kanno.ilmn12.hg19, which is the same as the package name. So I think there is name space issue if we use getAnnotation(object) directly in a package.

2. Unfortunately, user supplied link between CpG and gene is not supported in our package at this time. I think if we can use existing mapping, it will make the user easier to use the package because the users don't have to create mapping themselves. But we will consider adding this option in the future.

Thanks,
Xu Ren

**Comment by reese3928** [comment] 2018-06-23 22:44
Dear Marcel @LiNk-NY ,

We have modified the package to make it support user-supplied mapping between CpGs and gene names, which is suggested by Kasper. By using user supplied mapping in the examples, we are able to make R CMD check time within 5 minutes on Linux and Mac. But it exceeds 5 minutes on Windows. As you can see in the build report, only one example is >5s, but the total check time is ~7 minutes. This means most of the time is spent on checking the stuff other than examples. I really have no idea of how to make R CMD check even faster. Could you please check the report and let me know what to do next? Thank you.

Xu Ren

**Comment by LiNk-NY** [comment] 2018-06-25 19:20
Hi Xu Ren, @reese3928 
Thanks for making this change. I will review these shortly. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment] 2018-07-02 16:51
Hi Xu Ren, @reese3928 
Apologies for the delay. Your package has been accepted. 
Thank you for submitting to Bioconductor. 

Best regards,
Marcel

**Comment by mtmorgan** [comment] 2018-07-05 14:18
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/reese3928.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"methylGSA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/methylGSA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-07-05 14:18 UTC
Labels: 3a. accepted, WARNINGS
