### ISSUE TITLE
MaAsLin2 package submission

### ISSUE THREAD

**Issue by ljmciver** [Bioconductor/Contributions#1126] opened 2019-05-20 22:00 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/biobakery/Maaslin2

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2019-05-21 13:05
The vignette requires code chunks that are evaluated
<pre>
```{r}
...
```
</pre>
rather than static 'pictures'
<pre>
```
...
```
</pre>
Please update accordingly. The reviewer will have additional comments.

**Comment by ljmciver** [comment] 2019-06-06 17:34
Hello @hpages - I think you are assigned to the maaslin2 package submission review. It looks like everything is building ok with the package and I tried to capture all of the bioconductor guidelines for the submission. Please let me know if you have any questions/issues/suggestions for the package!

Thanks!
Lauren

**Comment by ljmciver** [comment] 2019-06-26 18:38
Hello @mtmorgan and @hpages , I think our package is currently under review by one of you. Please let me know if you need any changes to the package or if you have any questions.

Thank you,
Lauren

**Comment by Kayla-Morrell** [comment] 2019-07-12 17:10
Hello @ljmciver,

Thank you for submitting to _Bioconductor_, I'm sorry for the delay. Please see the initial review of your package below. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: In the 'Description:' field, you only mention details about 
MaAsLin but don't talk about how MaAsLin2 differs from this package. Please add
 a bit more details.

- [ ] REQUIRED: For 'License:', since you are using one of the 'offical' 
licenses than you do not need to include '+ file LICENSE' or the LICENSE file in
 your repo.

- [ ] REQUIRED: 'LazyData:' should be set to 'false'. Having this field set to 
true can slow down the loading of the package.

- [ ] SUGGESTION: We highly encourage adding a 'BugReports:' field that includes
 a relevant link to the GitHub repo where they can report Issues.

## NAMESPACE

- [ ] SUGGESTION: We highly suggest using the package roxygen2 for documentation
 of functions. This package makes makes documentation and importing/exporting 
much easier. Though it is not a requirement I figured I would mention it for 
potential help with the namespace file, R files, and man pages. 

- [ ] REQUIRED: If you chose to keep editing the NAMESPACE file by hand, be sure
 that all functions that are to be exported are. Also be sure to include as many
 importFrom as possible. I see in the DESCRIPTION file you have many packages 
listed for 'Imports:' but only a handful of functions are actually listed in 
your NAMESPACE file. Importing the functions in the NAMESPACE can help simplify
 the use of '::' in your R code.

## Data

- [ ] REQUIRED: There needs to be documentation for the files in `inst/extdata`
in a `inst/script` directory.

## Vignettes

- [ ] SUGGESTION: Since your package can be used from command line or within R,
 I think it would be a good idea to have 2 vignettes. One vignette would show 
the user how to use your package from command line and the other would how the 
user how to use your package from within R. The content can be similar to each 
other but that way you have only one type of code in each vignette (either 
command line commands or R commands).

- [ ] REQUIRED: Be sure to add the proper authors in the vignette information.

- [ ] SUGGESTION: We highly suggest the use of BiocStyle for formatting.

- [ ] REQUIRED: Line 15, you should be talking about Maaslin2 not MaAsLin.

- [ ] REQUIRED: The 'Installation' section for R should explain to users the 
proper way to download the package from _Bioconductor_.
 This can be done with the following code:

```{r, eval=FALSE}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Maaslin2")
``` 

- [ ] REQUIRED: Lines 104-112, this section is repetative with lines 180-188. My
 suggestion would be to remove the first chunk (lines 104-112), explain what 
files it requires, run the example, and then explain what the output files are.

- [ ] REQUIRED: Line 248, these two functions should have examples code shown. 
If the user can use these functions outside of `Maaslin2()` then they should be
 exported and these arguments should be explained in a man page, not here.

- [ ] REQUIRED: The last section of the vignette should be 'Session Info' and 
include `SessionInfo()`.

## inst/script

- [ ] REQUIRED: The scripts in this directory can vary. Most importantly if data 
was included in the inst/extdata/, a related script must be present in this 
directory documenting very clearly how the data was generated. It should include 
source urls and any important information regarding filtering or processing. It 
can be executible code, sudo code, or a text description. A user should be able 
to download and be able to roughly reproduce the file or object that is present 
as data.

## Unit tests

- [ ] REQUIRED: You should be using the RUnit or testthat packages for unit 
testing. Since you already have a 'test_Maaslin2.R' file in the inst/unitTests 
directory I suggest using the testthat package. What you will have to do is add
 testthat to the 'Suggests:' of your DESCRIPTION file. Then when you use 
testthat, a testthat directory will be added to your tests directory. In the 
test/testthat directory is where you will place the 'test_Maaslin2.R' file. Then
 you will get rid of the inst/unitTests directory and the 2 files you have in 
the tests/ directory (RunTests.R and expected_results.tsv). See this url for 
more info on how to utilize testthat:
http://bioconductor.org/developers/how-to/unitTesting-guidelines/#testthatUsage.

## R code

- [ ] SUGGESTION: A general suggestion for the R files, you don't have to test 
whether the required libraries are loaded. When the user installs/loads your
 package they will get a message from R if the required libraries aren't 
installed/loaded.

- [ ] REQUIRED: Be sure to use various apply functions instead of for loops were
 possible.

*fit*

- [ ] REQUIRED: Line 192, avoid `1:...`, use `seq_len()` or `seq_along()` 
instead. 

*viz*

- [ ] REQUIRED: Line 169, avoid `1:...`, use `seq_len()` or `seq_along()` 
instead.

- [ ] REQUIRED: Line 410, avoid `sapply()`, use `vapply()` instead. 

Best,
Kayla

**Comment by ljmciver** [comment] 2019-07-17 21:14
Hello @Kayla-Morrell , Thank you for the feedback! I have made all of the required changes except for one which I wanted to check in with you. Would it be ok if we did not import all of the packages in the NAMESPACE file. I prefer to use the double colon approach for external packages because I think it is easier to see where functions are coming from which makes modifications and debugging a bit easier. For this approach I was using the suggestion from the O'Reilly R Packages book that recommends this practice of explicit namespaces with double colons. Here is the reference: https://r-pkgs.org/namespace.html . Would it be ok to keep the code this way?

Thanks for the suggestion about splitting up the vignettes. If it sounds ok to you I would like to keep them as one because then I can also use this file as the readme which we link to in the repository as our user manual. This helps us from duplicating documentation. 

Thank you again for the review and the feedback! Please let me know if there is anything else you think needs to be changed.

Thanks!
Lauren

**Comment by ljmciver** [comment] 2019-07-24 21:27
Hi @Kayla-Morrell , I obtained some real data sets and options from one of the MaAsLin2 authors (Himel Mallick) for the vignette. I have updated the package to include these data files and descriptions. Please let me know if you think anything else needs to be changed.

Thanks!
Lauren

**Comment by Kayla-Morrell** [comment] 2019-07-30 14:54
Hello @ljmciver -

Thank you for all the work done on this package. I have looked over the changes made as well as the justifications you gave regarding the NAMESPACE and vignette. There are just a few additional requirements before accepting the package. Please see the secondary review below and comment back here when you are ready for me to look it over again.

## DESCRIPTION

- [ ] REQUIRED: Thank you for making the change for the license, however, you 
will need to add the `+ file LICENSE` back in with the LICENSE file in your repo.
 This was my mistake, I didn't realize that the LICENSE file is a requirement 
by the MIT license.

- [ ] CLARIFICATION: Thank you for adding in a 'BugReport:' field. If you would
 like issues to be reported to your bitbucket page that's fine but please keep 
an eye on the github repo issues as well. Since Bioconductor uses github, most 
users will look to that repo for reporting issues. Also, if most of your work is
 done on your bitbucket account just be sure the github repo stays current.

## vignette

- [ ] REQUIRED: Line 84-86, this code needs to be actual R code. Be sure there 
is `\{r, eval = false\}` and \`\`\` \`\`\` around this code so that it shows up
 as R code.

- [ ] REQUIRED: Line 188-219, all of this text is not needed. The information 
will be printed from just from the command `SessionInfo()`.  


Best,
Kayla

**Comment by ljmciver** [comment] 2019-08-01 19:00
Hi @Kayla-Morrell , Thanks for the review and feedback. I have made all of the suggested changes. I noticed in the automated build process for the MacOS platform it seems to change what dependencies are required even though the package has the same dependencies. Do you know if this might be some unexpected behavior with the bioconductor MacOS build/test system? I will also post a issue about this to follow up as I have ended up having to add four dependencies to the package plus importing them into the namespace to get the automated build on MacOS to pass.

Please let me know if there is anything else that you think needs to be modified.

Thanks!
Lauren

**Comment by Kayla-Morrell** [comment] 2019-08-05 14:31
Hello @ljmciver - It just looks like you need to do a version bump, then if the build is clean I'll be more than happy to accept the package.

**Comment by ljmciver** [comment] 2019-08-05 17:54
Hi @Kayla-Morrell , Thanks for the ping about the version bump required. I have tagged a new version and the automated build did not have any errors or warnings. Please let me know if you need anything else from me to proceed with our package submission.

Thanks!
Lauren

**Comment by mtmorgan** [comment] 2019-08-07 21:19
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ljmciver.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("Maaslin2")`. The package 'landing page' will be created at

https://bioconductor.org/packages/Maaslin2

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-08-07 21:19 UTC
Labels: 3a. accepted, OK
