### ISSUE TITLE
scDesign3

### ISSUE THREAD

**Issue by SONGDONGYUAN1994** [Bioconductor/Contributions#2903] opened 2023-01-20 23:01 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/SONGDONGYUAN1994/scDesign3

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by hpages** [comment] 2023-02-24 19:41
Hi @SONGDONGYUAN1994 ,

Thanks for submitting **scDesign3** to Bioconductor.

The package contains 13 vignettes and they take too long to build. I started `R CMD build scDesign3` on my laptop half an hour ago and it's still running the "creating vignettes ..." step! Hence the TIMEOUT reported by the SPB (Single Package Builder) 2 days ago. See above.

Per our guidelines, the vignettes in a Bioconductor package should take less than 5 min to build. So you need to work on making the code in the vignette faster. Please read our guidelines carefully. We expect package developers to read them and have their package satisfy them _before_ submitting their package.

Alternatively, you could move all these vignettes to a separate "workflow package", and keep a small vignette in **scDesign3**. See [here](https://bioconductor.org/packages/release/BiocViews.html#___Workflow) for the list of workflow packages currently available in Bioconductor. The advantage of this separation is that the vignette in a workflow package is not required to build in less than 5 min like for a software package. Note however that a workflow package can only contain 1 vignette (the document showing the workflow), so all the vignettes that you put there would need to be merged into a single vignette.

Also:

- You have 40 packages listed in the `Suggests` field! Are you sure you need them all? For example why would you have packages like **magrittr**, **tidyselect** or **gamlss.add** in `Suggests`? You don't seem to use them anywhere in **scDesign3**. These are just 3 examples but it looks like there are plenty of other packages that you have listed there but don't use at all!

- The way your code handles suggested packages is not going to lead to a user-friendly experience. For example it seems that packages **matrixcalc** and **spcov** are used by `fit_copula()`, but there's no word about this in the man page. Furthermore, `fit_copula()` is going to fail in the middle of a possibly long calculation if the user doesn't have these packages installed. This is not good practice. The function should fail early and with a friendly error message that asks the user to install these packages.

- Note that the dependency on **Rfast** is a quite heavy one: the package has a lot of C++17 code that takes forever to compile. So you shoud use it only if you _really_ need it. It's not clear to me why you need things like `Rfast::rowVars()` or `Rfast::colVars()`, when these functions are available in lighter and more mainstream package **matrixStats**. The **matrixStats** versions are also _much_ faster:
    ```
    > library(matrixStats)
    > library(Rfast)
    > library(microbenchmark)
    > m <- matrix(rnorm(1000 * 500), ncol=500)
    > microbenchmark(matrixStats::colVars(m), Rfast::colVars(m))
    Unit: milliseconds
                        expr      min        lq      mean    median        uq
     matrixStats::colVars(m)  2.25559  2.364918  2.430568  2.404364  2.479315
           Rfast::colVars(m) 13.81729 17.398497 44.981375 29.246507 52.716935
            max neval
       2.820306   100
     106.514653   100
    ```
    So please make sure you have a really good reason for introducing a dependency like **Rfast**.

Please note that this is not a review yet, just things that will need to be addressed before I actually start the review.

Thanks,
H.

**Comment by SONGDONGYUAN1994** [comment] 2023-02-24 20:49
Hi Hervé,
Thank you so much for your help, and I apologize for all the inconvenience. I will address the problems ASAP. May I ask a few questions about those issues?

1. Too long vignettes: sorry that this is an annoying problem. I still want to keep all vignettes in `scDesign3` since I used the `pkgdown` to build its website. I am afraid that the code itself cannot be faster. My current idea is to pre-save the intermediate data somewhere and set `eval = FALSE` for those time-consuming code chunks. Would you think this is appropriate for Bioconductor?
2. For `Rfast`, what I really need is : [Rfast::cora](https://rdrr.io/cran/Rfast/man/cova.html). for the calculation of correlation matrix of large matrices (thousands of genes and tens of thousands of cells). Would you mind suggesting a more mainstream alternative for it?

I will check the dependencies and refine them soon. Again, thanks for your support!

Best,
Dongyuan

**Comment by hpages** [comment] 2023-03-08 06:00
Hi Dongyuan,

My bad, when I said that a workflow package can only contain 1 vignette (the document showing the workflow), that's not true. A workflow package can actually contain several Rmd documents. See for example the [RNAseq123](https://bioconductor.org/packages/RNAseq123), the [chipseqDB](https://bioconductor.org/packages/chipseqDB), or the [simpleSingleCell](https://bioconductor.org/packages/simpleSingleCell) workflow.

Sorry for the confusion.

> I still want to keep all vignettes in `scDesign3` since I used the `pkgdown` to build its website.

I don't see why you couldn't achieve the same thing with a workflow package. Keep all the R code and datasets in **scDesign3**, and move the vignettes to the workflow package.

For **Rfast** and your need for `Rfast::cora()`, are your matrices sparse? (this is typical for single cell data). If so, have you considered using a sparse matrix representation like the dgCMatrix container from the **Matrix** package? Then I believe that you should be able to use functions from the **sparseMatrixStats** package to efficiently compute your correlation matrices. If your matrices are so big that they don't fit in memory, please consider using an on-disk representation like HDF5Matrix from the **HDF5Array** package, or TileDBMatrix from the **TileDBArray** package. Then use functions from the **DelayedMatrixStats** package to compute your correlation matrices for your HDF5Matrix or TileDBMatrix objects.

Hope this helps,

H.

**Comment by SONGDONGYUAN1994** [comment] 2023-04-15 01:08
Hi Hervé,
Sorry for the delay, and thank you so much for your suggestion! Unfortunately, our correlation matrix is an intermediate step and is dense, so the sparse matrix does not work for us. Instead, we apply a faster version of correlation calculation from `Rfast`. We do remove the `Rfast` completely, and now the dependencies are much lighter than before. We also remove most vignettes. We would appreciate your further instructions. Thanks again!

Best regards,
Dongyuan

**Comment by hpages** [comment] 2023-04-19 19:34
Hi Dongyuan,

If you think that the package is ready for me to take another look, please bump its version so we get a new build report. In the event that the new report reveals new issues, please make sure to address them (and bump the version again).

Thanks,
H.

**Comment by hpages** [comment] 2023-05-22 14:23
@SONGDONGYUAN1994 Are you planning to follow up with this submission?

**Comment by SONGDONGYUAN1994** [comment] 2023-05-22 15:59
Hi Hervé,
I apologize for the delay, and we now bump the version number and push it to Bioconductor. I would response to your suggestions and modify our package timely. Thank you so much!

Best regards,
Dongyuan

**Comment by hpages** [comment] 2023-06-07 00:21
Hi Dongyuan,

Ok so with all the vignettes (except one) now renamed by adding the `.orig` suffix to them, `R CMD build` is able to complete in less than 5 mins. That's one way to address the issue but is not a satisfying one. Why would you disable all the vignettes when you can keep them all in a workflow package as mentioned previously? This is not hard to do so I would strongly encourage you to consider that option.

Also instead of downloading the dozen or so datasets used in the vignettes each time with things like:

    MOBSC_sce <- readRDS((url("https://figshare.com/ndownloader/files/40581983")))

I'd suggest that you download them to the user cache (i.e. to `tools::R_user_dir("scDesign3", which="cache")`) so they are downloaded once only to the user machine (and to our build machines). This will not only save bandwidth but will also speedup further executions of the code in the vignettes, and so will make further runs of `R CMD build` faster. See https://contributions.bioconductor.org/data.html#other-data and https://contributions.bioconductor.org/r-code.html#web-querying-and-file-caching for our guidelines with respect to data download.

Note that some of your datasets (e.g. `SCGEMMETH_sce` and `SCGEMRNA_sce`) are on dropbox.com in addition to figshare.com, and you sometimes dowload them from one place and sometimes from the other place. Please download everything from figshare.com and avoid using dropbox.com to host scientific datasets.

Thanks,
H.

**Comment by SONGDONGYUAN1994** [comment] 2023-06-07 21:50
Hi Hervé,
Thank you for your suggestions! We would move the vignettes to a new workflow package and re-write them to avoid repeated downloading. The files from Dropbox should have been changed to figShare and we will fix them this time.

Best regards,
Dongyuan

**Comment by lshep** [comment] 2023-07-28 13:57
@SONGDONGYUAN1994  is there an update on this issue?  We like to see progress in a 2-3 week time frame to keep packages moving through the review process and add to Bioconductor as soon as possible.  If there were changes they should have been pushed to the git.bioconductor.org repo to produce a new build report.  See the information provided in https://github.com/Bioconductor/Contributions/issues/2903#issuecomment-1440527950

**Comment by SONGDONGYUAN1994** [comment] 2023-07-28 15:42
Hi lshep,
Sorry for the delay, since we kept receiving issues on our GitHub in the past month. We will push our new version today. Thanks!

Best,
Dongyuan

**Comment by SONGDONGYUAN1994** [comment] 2023-07-29 18:51
AdditionalPackage: https://github.com/SONGDONGYUAN1994/scDesign3Workflow

**Comment by SONGDONGYUAN1994** [comment] 2023-07-30 00:15
Hi,
I have bumped the scDesign3 and created a new workflow package scDesign3Workflow. Thank you so much!

Best,
Dongyuan

**Comment by hpages** [comment] 2023-09-06 16:53
Thanks @SONGDONGYUAN1994 for submitting **scDesign3Workflow** as an additional package.

I'm not sure the package got properly ingested to git.bioconductor.org or to the SPB though, as I'm not able to clone https://git.bioconductor.org/packages/scDesign3Workflow and it doesn't seem like we got a build/check report from the SPB yet.

Maybe some manual intervention is required on our end? @vjcitn @lshep Any thoughts? Thx

**Comment by lshep** [comment] 2023-09-06 16:56
Give me a minute or two.  Adding it now and kicking off the build.

**Comment by JSB-UCLA** [comment] 2023-09-06 17:07
Thanks for your help! Please let me know if I need to update anything.

Best,
Dongyuan

**Comment by hpages** [comment] 2023-09-12 00:27
Thanks @lshep!

@SONGDONGYUAN1994 @JSB-UCLA Please address the BUILD error (and any other remaining issues) reported by the SPB. Thanks!

**Comment by SONGDONGYUAN1994** [comment] 2023-09-19 02:24
Hi,
I have bumped `scDesign3Workflow` from v0.99.0 to 0.99.1. However, I got the error when I push it:
dongyuan@lambda-server:~/package_development/scDesign3Workflow$ git push upstream main:devel
error: src refspec main does not match any
error: failed to push some refs to 'git@git.bioconductor.org:packages/scDesign3Workflow.git'

Did I miss anything? Sorry for the trouble!

Best,
Dongyuan

**Comment by lshep** [comment] 2023-09-19 11:17
The set up is the same as the other package.  Have you set your remotes and done a `git fetch --all` ? Just to be clear your local branch you are working on is defaulted to main and you are currently checked out on a branch called main?

**Comment by SONGDONGYUAN1994** [comment] 2023-09-20 02:38
Hi,
Since I need to fix the error in `scDesign3Workflow`, I updated `scDesign3`, bumped the version to 0.99.7, but I got the error this time (weird, this error seems to be nothing related to the package but the download link):

lconway BUILD SRC output
===============================

 R CMD BUILD

===============================

* checking for file scDesign3/DESCRIPTION ... OK
* preparing scDesign3:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building scDesign3.Rmd using rmarkdown

Quitting from lines 58-60 [unnamed-chunk-3] (scDesign3.Rmd)
Error: processing vignette 'scDesign3.Rmd' failed with diagnostics:
cannot read from connection
--- failed re-building scDesign3.Rmd

SUMMARY: processing the following file failed:
  scDesign3.Rmd

Error: Vignette re-building failed.
Execution halted

58-60 is this chunk:
```{r}
example_sce <- readRDS((url("https://figshare.com/ndownloader/files/40581992")))
print(example_sce)
```

Thank you so much!

Best,
Dongyuan

**Comment by hpages** [comment] 2023-09-29 00:03
Hi Dongyuan,

I cannot reproduce this error on lconway:
```
lconway:sandbox biocbuild$ time R CMD build --keep-empty-dirs --no-resave-data scDesign3
* checking for file ‘scDesign3/DESCRIPTION’ ... OK
* preparing ‘scDesign3’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘scDesign3_0.99.7.tar.gz’


real	1m13.594s
user	0m56.509s
sys	0m8.905s
```
so the error we see on the SPB report was probably because of lconway having some intermittent internet access issue. Let's ignore it.

However, the **scDesign3Workflow** package fails for real (see SPB report from last week), apparently because it suggests the following packages which are not available in Bioconductor or CRAN: **monocle3**, **PseudotimeDE**, **SPARK**. Please note that we don't allow this.

Thanks,
H.

**Comment by SONGDONGYUAN1994** [comment] 2023-10-03 18:41
@hpages Thank you so much! For scDesign3Workflow, my question is how should I deal with this:
it suggests the following packages which are not available in Bioconductor or CRAN: monocle3, PseudotimeDE, SPARK

These packages are only on their Github repo. I used them in one vignittee for benchmarking their performance thus they must be used. Thank you!

Best,
Dongyuan

**Comment by hpages** [comment] 2023-10-03 23:29
You can either:
- convince the authors of these packages to submit them to CRAN or Bioconductor,
- find CRAN or Bioconductor alternatives for these packages,
- revisit your workflows to eliminate the need for these packages.

The problem is that, generally speaking, R packages that exist only on GitHub offer no guarantee of stability and don't have any formal commitment to fixing bugs or perform any sort of QA. Also most of them won't bother to ensure that the package can be installed on Windows or Mac, and they won't provide binaries for these platforms either. This doesn't play well with the mission of Bioconductor which is to distribute robust and stable software that is easy to install on Linux, Windows, and Mac.

Thanks,
H.

**Comment by SONGDONGYUAN1994** [comment] 2023-10-03 23:38
Thanks! I got it now. I will update scDesign3WorkFlow ASAP; it seems like I have to eliminate them.

Best,
Dongyuan

**Comment by hpages** [comment] 2023-10-17 19:45
@lshep Looks like we never got the report for the latest build (started 5 days ago).

@SONGDONGYUAN1994 Can you try to bump the version of the package again and push? Thanks

**Comment by SONGDONGYUAN1994** [comment] 2023-10-17 19:49
Thanks! Let me try this right now.

**Comment by hpages** [comment] 2023-10-18 01:24
Hmm... still not working.

Any thought @lshep?

**Comment by lshep** [comment] 2023-10-18 12:54
Its timing out in the build stage and is having trouble when the report is not available at all for posting.  I can look into this bug but it is because it is timing out after 2 hours `ERROR\\nTIMEOUT: R CMD build exceeded 120 mins`

**Comment by SONGDONGYUAN1994** [comment] 2023-10-18 14:58
@hpages @lshep Oh I got it. I think we took more than two hours to compile it locally. Are there any solutions? I thought there was no time limit for workflow package since we created it to solve the time-consuming issue for a regular Bioconductor package.

**Comment by hpages** [comment] 2023-10-18 17:07
@SONGDONGYUAN1994 There's currently an `R CMD build` time limit of 2 hours for workflow packages. See for example the latest build report for workflows in BioC 3.18: https://bioconductor.org/checkResults/3.18/workflows-LATEST/ The limit was set a long time ago, in a very arbitrary manner. It never really mattered anyways because no workflow package currently in Bioconductor would need anything close to that.

We can increase it to 3 hours. Would that work?

Note that we won't be able to go beyond that though. If you need more time, then you should consider splitting the workflows into more than one package, or turn them into a book package. The time limit for book packages is 5 hours at the moment, but we could increase it if needed. See the latest build report for the books in BioC 3.18: https://bioconductor.org/checkResults/3.18/books-LATEST/

@lshep Would it be possible to increase the time limit for workflows to 3 hours in the SPB? I'll do it in the BBS. Thanks

**Comment by lshep** [comment] 2023-10-18 18:59
I believe the SPB should now have a 3 hour timeout limit . I'll manually kick off a build now to see if that will complete

**Comment by hpages** [comment] 2023-10-18 19:33
Awesome. Thanks @lshep!

**Comment by hpages** [comment] 2023-10-19 16:46
Didn't seem to complete. No report. @lshep can you take a look?

**Comment by lshep** [comment] 2023-10-19 16:50
Here is the partial report;  I'd have to go onto lconway to see why it didnt seem to complete at all.   http://staging.bioconductor.org:8000/job/19748/

**Comment by SONGDONGYUAN1994** [comment] 2023-10-19 17:24
Thank you all! Looks like there are still some errors. In the worst case, can we first publish scDesign3? Sorry for all the inconvenience.

**Comment by hpages** [comment] 2023-10-19 17:50
ok let's do that

**Comment by hpages** [comment] 2023-10-19 17:53
@lshep This is acceptance of the software package only (**scDesign3**). The workflow package (**scDesign3Workflow**) is not accepted yet. @SONGDONGYUAN1994 will resubmit it separately.

@SONGDONGYUAN1994 Please resubmit **scDesign3Workflow** in a new issue. Thank you!

**Comment by lshep** [comment] 2023-10-19 17:54
@SONGDONGYUAN1994  wait to resubmit until after this issue is closed and I can delete it from the SPB tracker otherwise it will close the new submission and associate it with this issue

**Comment by SONGDONGYUAN1994** [comment] 2023-10-19 18:01
Thank you all! I will wait for it. Thanks again for your help!

**Comment by lshep** [comment] 2023-10-21 14:25
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/SONGDONGYUAN1994.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scDesign3")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scDesign3

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-10-21 14:25 UTC
Labels: ERROR, 3a. accepted

**Comment by hpages** [comment] 2023-10-21 20:52
Thanks @lshep 

@SONGDONGYUAN1994 Please go ahead and submit **scDesign3Workflow** in a new issue. Thanks
