### ISSUE TITLE
ceRNAnetsim

### ISSUE THREAD

**Issue by selcenari** [Bioconductor/Contributions#1287] opened 2019-10-11 09:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/selcenari/ceRNAnetsim

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by selcenari** [comment] 2019-10-14 12:53
Hi @Kayla-Morrell ,

I  have built and checked the package with no build vignette option. But doesn't the Bioconductor do this in the background? In this case, what should we do?

**Comment by Kayla-Morrell** [comment] 2019-10-15 19:31
@selcenari - could have possibly been the same time of day when our daily builders were trying to post. I kicked off a manual build and everything seemed to build alright. Just work on cleaning up the ERRORs and WARNINGs and then I'll be able to do the review of the package.

Best,
Kayla

**Comment by selcenari** [comment] 2019-10-21 11:55
Hi, i have committed last changes 4 day before. But the bioc-devel -issue-bot could not detect automatically. How can i handle it?

**Comment by Kayla-Morrell** [comment] 2019-10-21 12:05
@selcenari - Have you set up your push [hook](https://github.com/Bioconductor/Contributions/issues/1287#issuecomment-541178101) for your repo?

**Comment by selcenari** [comment] 2019-10-21 12:48
@Kayla-Morrell  oh sorry. Thank you!!!

**Comment by Kayla-Morrell** [comment] 2019-10-21 18:09
@selcenari - We seem to be having some issues with the single package builder at the moment. I will be fixing them and then kicking off a manual build of your package. Please don't make any commits until then. Thanks!

**Comment by selcenari** [comment] 2019-10-21 18:20
@Kayla-Morrell  i am sorry about i did not see your comment. I have tried to solve this fail. Thank you

**Comment by Kayla-Morrell** [comment] 2019-10-21 18:40
@selcenari - Not a problem. Everything should be all set now.

**Comment by selcenari** [comment] 2019-10-21 18:46
@Kayla-Morrell  Thank you!!!

**Comment by Kayla-Morrell** [comment] 2019-11-06 19:39
Hello @selcenari,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## General package development

- [ ] REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. It is not 
needed and should be removed.

- [ ] REQUIRED: The raw package directory should not contain unnecessary files, 
system files, or hidden files. These files may be present in your local 
directory but should not be commited to git. What is the purpose of the 
'Dockerfile' file, the '_pkgdown.yaml' file, and the 'codecov.yml' file?

## DESCRIPTION

- [ ] REQUIRED: 'LazyData' should be set to false. When this field is true it 
can slow down the loading of packages with data.

- [ ] REQUIRED: Now that we have a different devel version of Bioconductor, 
please update the R version dependency from 3.6 to 4.0. 

- [ ] REQUIRED: 'tibble' is being imported but I don't see it listed as an 
`import()` or `importFrom()` in the NAMESPACE file. Please determine if this 
package should be listed here or not.

## NEWS

- [ ] REQUIRED: Thank you for including a NEWS file, however this file should 
just be a NEWS file, not NEWS.md. 

## Vignettes

- [ ] REQUIRED: All vignettes should minimially include these sections:
	- Introduction
	- Installation
	- Session Info.

The 'Introduction' section serves as an abstract to introduce the objective, 
models, unique functions, key points, etc that distinguish the package from 
other packages of similar type.

The 'Installation' section should show to users how to download and load the 
package from _Bioconductor_. It should include code similar to the following and 
be `eval = FALSE`,

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ceRNAnetsim")
```

The last section of the vignette should be 'Session Info' and should include 
`sessionInfo()`.

- [ ] SUGGESTION: Especially if you have lengthy vignettes, we highly suggest 
the use of table of contents. 

- [ ] REQUIRED: Some of your vignettes should be combined and/or simplified. The 
idea of a vignette is to demonstrate how to accomplish non-trivial tasks 
embodying the core functionality of your package. You can have more than one 
vignette but I would suggest doing one that demonstrates the package as a whole 
(functions and such) and then one that walks through a real life examples (or 
how the user might use this in their research).

- [ ] REQUIRED: A vignette provides reproducability: the vignette produces the 
same results as copying the corresponding commands into an R session. It is 
therefore essential that the vignette embed executed R code. short-cuts (e.g., 
using the Sweave eval=FALSE flag) undermine the benefit of vignettes and are 
generally not allowed; exceptions can be made with proper justification.

## Man pages

- [ ] REQUIRED: Data man pages must include source information and data 
structure information. All of them need more information included in them.

- [ ] SUGGESTION: For any function that isn't exported (e.g., `gene_knowndown`) 
you can add `@keywords internal` to the roxygen documentation in the R code for 
that function. That way the function won't be listed in the documentation index.

## R code

- [ ] REQUIRED: Undefined global functions or variables:
        find_node_perturbation: no visible binding for global variable 'len'
        priming_graph: no visible global function definition for 'na.omit'.
        Consider adding `importFrom("stats", "na.omit") to your NAMESPACE file.

- [ ] REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. Found in
files:
        find_iteration.R, line 30
        simulate_vis.R, line 45 (still using 1:..., this should be avoided)
        simulate.R, line 39 and 59 (still using 1:..., this should be avoided)

- [ ] SUGGESTION: In 'simulate_vis.R', I think there should be an argument that 
the user can indicate if they want the plots saved or not. After running through 
the vignette I had a number of plot files that I didn't need. Default could be 
that they are always saved, but the user can chose to not have them saved. 

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 291 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. 
There are 13 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 456 lines that are not.

Best,
Kayla

**Comment by selcenari** [comment] 2019-11-14 06:33
Hi @Kayla-Morrell 

Firstly, Thanks for your review. We figured out problems except a few.  I've listed changes in package following:
 
 ## General package development
* [x]  REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. It is not
   needed and should be removed.
 * [x]  REQUIRED: The raw package directory should not contain unnecessary files,
   system files, or hidden files. These files may be present in your local
   directory but should not be commited to git. What is the purpose of the
   'Dockerfile' file, the '_pkgdown.yaml' file, and the 'codecov.yml' file?
 
 ## DESCRIPTION

 * [x]  REQUIRED: 'LazyData' should be set to false. When this field is true it
  can slow down the loading of packages with data.
 * [??]  REQUIRED: Now that we have a different devel version of Bioconductor,
   please update the R version dependency from 3.6 to 4.0.

 * [!!!]  I've upgraded version of package. **But it gave error as you can see in build report. Rversion is 3.6 in Bioconductor package builder although BiocVersion is 3.10. How can that be figure out?**

 * [x]  REQUIRED: 'tibble' is being imported but I don't see it listed as an
   `import()` or `importFrom()` in the NAMESPACE file. Please determine if this
   package should be listed here or not.
 
 ## NEWS
 * [x]  REQUIRED: Thank you for including a NEWS file, however this file should
   just be a NEWS file, not NEWS.md.
 
 ## Vignettes
 * [x]  REQUIRED: All vignettes should minimially include these sections:
   
   * Introduction
   * Installation
   * Session Info.
 
> The 'Introduction' section serves as an abstract to introduce the objective,
> models, unique functions, key points, etc that distinguish the package from
> other packages of similar type.
> 
> The 'Installation' section should show to users how to download and load the
> package from _Bioconductor_. It should include code similar to the following and
> be `eval = FALSE`,
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("ceRNAnetsim")
> ```
> 
> The last section of the vignette should be 'Session Info' and should include
> `sessionInfo()`.
> 
 * [x]  SUGGESTION: Especially if you have lengthy vignettes, we highly suggest
   the use of table of contents.

 * [x]  REQUIRED: Some of your vignettes should be combined and/or simplified. The
   idea of a vignette is to demonstrate how to accomplish non-trivial tasks
   embodying the core functionality of your package. You can have more than one
   vignette but I would suggest doing one that demonstrates the package as a whole
   (functions and such) and then one that walks through a real life examples (or
   how the user might use this in their research).

 * [??]  REQUIRED: A vignette provides reproducability: the vignette produces the
   same results as copying the corresponding commands into an R session. It is
   therefore essential that the vignette embed executed R code. short-cuts (e.g.,
   using the Sweave eval=FALSE flag) undermine the benefit of vignettes and are
   generally not allowed; exceptions can be made with proper justification.
 
* [??] **Actually, i know that entire vignettes must be reproducible. Because some of our functions are 
   time-consuming, so there were time-out problems when running some chunks in vignettes, for 
   example: [in our first submission](https://github.com/Bioconductor/Contributions/issues/1287#issuecomment-541187244). I can 
    choose  `--no-build-vignettes` when performing local build. if we can do this in 
    your package builder, I can rearrange vignettes.**

 ## Man pages
 * [x]  REQUIRED: Data man pages must include source information and data
   structure information. All of them need more information included in them.
 * [x]  SUGGESTION: For any function that isn't exported (e.g., `gene_knowndown`)
   you can add `@keywords internal` to the roxygen documentation in the R code for
   that function. That way the function won't be listed in the documentation index.
 
 ## R code
 * [x]  REQUIRED: Undefined global functions or variables:
   find_node_perturbation: no visible binding for global variable 'len'
   priming_graph: no visible global function definition for 'na.omit'.
   Consider adding `importFrom("stats", "na.omit") to your NAMESPACE file.

 * [x]  REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. Found in
   files:
>   find_iteration.R, line 30
>   simulate_vis.R, line 45 (still using 1:..., this should be avoided)
>   simulate.R, line 39 and 59 (still using 1:..., this should be avoided)

 * [x]  SUGGESTION: In 'simulate_vis.R', I think there should be an argument that
   the user can indicate if they want the plots saved or not. After running through
   the vignette I had a number of plot files that I didn't need. Default could be that they are always 
   saved, but the user can chose to not have them saved.

> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 291
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
>   There are 13 lines that contain tabs.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 456 lines that are not.

 Best

**Comment by Kayla-Morrell** [comment] 2019-11-19 17:00
Hello @selcenari - I guess I was a bit preemptive with my review, we are still working on updating the R version on the single package builder. It should hopefully be resolved by the end of the week. Feel free to change back to R 3.6 for the time being so that you can get a proper build report. I can inform you when to make the change to R 4.0 when it is ready on our builder.

Thank you for you patience and I will re-review you package this week.

Best,
Kayla

**Comment by selcenari** [comment] 2019-11-21 09:18
Hi @Kayla-Morrell,

Thanks for comment. I didn't have any problems when I changed the version. 

As I mentioned in the [comment](https://github.com/Bioconductor/Contributions/issues/1287#issuecomment-553746744), I marked some chunks of vihgnettes as "eval=FALSE". For reproducubility we also added "binder badge" to our project via github (as you see in [here](https://github.com/selcenari/ceRNAnetsim)) . But also If we can arrange them as --no build vignettes, in build process, I can change them to eval=TRUE.

Thanks for your help...

**Comment by Kayla-Morrell** [comment] 2019-11-22 16:23
Hello @selcenari - Thank you for making the necessary changes. I have some additional notes before accepting the package. Please see them below.

- [ ] REQUIRED: For the NEWS file, thank you for changing to the correct file format. However, the information in the file is not formatted correctly so when I render the NEWS file nothing is shown. Please see https://bioconductor.org/developers/package-guidelines/#news for proper formatting.

- [ ] REQUIRED: In the basic_usage vignette, lines 77-82, 88-92, and 100-103 need to be shown to the user (echo = TRUE) or else the user won't be able to reproduce what you have done in lines 111-117.

- [ ] REQUIRED: We have our build systems set up in a specific way, as you can see in the details of the build report. This does not include using --no-build-vignettes. We need as much code as possible to be eval = TRUE to insure vignettes are working properly. The major offender of this is the mirtarbase_example vignette as much of this code is set to eval = FALSE. Upon further investigation of the code in the vignette I may have a potential solution to help speed up the build of this vignette. Starting at line 175, 

```
system.time(TCGA_E9_A1N5_mirnagene %>% 
    priming_graph(competing_count = gene_expression, miRNA_count = total_read))
   user  system elapsed
  3.009   0.410   3.459
```

This part of the function only about 3.5 seconds to run.

```
> system.time(TCGA_E9_A1N5_mirnagene %>% 
    priming_graph(competing_count = gene_expression, miRNA_count = total_read) %>% 
    update_how(node_name = "HIST1H3H", how = 30))
   user  system elapsed
  3.232   0.605   3.874
```

Adding the next part of the code only adds about 0.4 of a second. Then the lengthy part of the code...

```
> system.time(TCGA_E9_A1N5_mirnagene %>% 
    priming_graph(competing_count = gene_expression, miRNA_count = total_read) %>% 
    update_how(node_name = "HIST1H3H", how = 30) %>% 
    simulate(20))
   user  system elapsed
 95.245  10.596 107.258
```

Every time you call this `simulate()` function you are adding about 103 seconds (or almost 2 minutes) of run time. Then in lines 189-193 you repeat the same code. So my thought was to save this chunk of code to a variable so you only do the calculation once, like so:

```
> tst <- TCGA_E9_A1N5_mirnagene %>% 
    priming_graph(competing_count = gene_expression, miRNA_count = total_read) %>%
    update_how(node_name = "HIST1H3H", how = 30) %>% 
    simulate(20)
Warning message:
In priming_graph(., competing_count = gene_expression, miRNA_count = total_read) :
  First column is processed as competing and the second as miRNA.

> tst %>% find_iteration(plot=TRUE)
> system.time(tst %>% find_iteration(plot=TRUE))
   user  system elapsed
 15.815   0.381  16.402
```

I would suggest avoid repeating the same code over and over, especially if it takes time to run. Try simplifying code where you can and it may save you some time in the build step (this can be used in any of the vignettes to help speed up the build time as much as possible).

Let me know if you need clarification in any way.

Best,
Kayla

**Comment by selcenari** [comment] 2019-11-26 19:45
Hi @Kayla-Morrell ,

Thanks for your review, the changes are shown following:

 * [ ]  REQUIRED: For the NEWS file, thank you for changing to the correct file format. However, the information in the file is not formatted correctly so when I render the NEWS file nothing is shown. Please see https://bioconductor.org/developers/package-guidelines/#news for proper formatting.

I have looked at formating of NEWS file. But actually there was nothing wrong in package’s NEWS file. At the same time, i have tried to solve this problem. I have noticed that it could be an Rstudio bug. Because, i encountered Error below, when i ran `utils::news(package="example_package")`

*Error in UseMethod("toHTML") : no applicable method for 'toHTML' applied to an object of class "NULL"*.

[Here](https://stackoverflow.com/questions/56270933/package-specific-utilsnews-not-working-in-rstudio) you can see the similar problem. I have tried some other methods to solve this problem, but it is non-effective to show news without local changes. 

 * [x]  REQUIRED: In the basic_usage vignette, lines 77-82, 88-92, and 100-103 need to be shown to the user (echo = TRUE) or else the user won't be able to reproduce what you have done in lines 111-117.
 * [x]  REQUIRED: We have our build systems set up in a specific way, as you can see in the details of the build report. This does not include using --no-build-vignettes. We need as much code as possible to be eval = TRUE to insure vignettes are working properly. The major offender of this is the mirtarbase_example vignette as much of this code is set to eval = FALSE. Upon further investigation of the code in the vignette I may have a potential solution to help speed up the build of this vignette. Starting at line 175.

Thanks for the suggestions, it worked great. Two chunks (in auxiliary_commands vignette) includes eval=FALSE, but i shown this as it is only helper command not used as basic steps of the workflow.
If you have a suggestion about NEWS file,i can work on it.

Best…
Selcen

**Comment by Kayla-Morrell** [comment] 2019-11-27 16:21
@selcenari - I rechecked the NEWS file and it seems to be rendering fine now. Thank you for making those changes, everything looks good now and I'd be more than happy to accept the package.

Best,
Kayla

**Comment by mtmorgan** [comment] 2019-11-27 22:33
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/selcenari.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ceRNAnetsim")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ceRNAnetsim

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-11-27 22:33 UTC
Labels: 3a. accepted, OK
