### ISSUE TITLE
MSstatsConvert package

### ISSUE THREAD

**Issue by mstaniak** [Bioconductor/Contributions#1664] opened 2020-10-01 15:04 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Vitek-Lab/MSstatsConvert

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hpages** [comment] 2020-10-16 07:27
Hi @mstaniak ,

Thanks for the submission.

I get the following error when running `R CMD check` on MSstatsConvert:
```
biocbuild@malbec1:~/sandbox$ R CMD check MSstatsConvert_0.99.6.tar.gz 
* using log directory ‘/home/biocbuild/sandbox/MSstatsConvert.Rcheck’
* using R version 4.0.3 (2020-10-10)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘MSstatsConvert/DESCRIPTION’ ... OK
* this is package ‘MSstatsConvert’ version ‘0.99.6’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘MSstatsConvert’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘tinytest.R’
 ERROR
Running the tests in ‘tests/tinytest.R’ failed.
Last 13 lines of output:
   > test_MSstatsConvert.R#018: tinytest::expect_true
   > test_MSstatsConvert.R#019: tinytest::expect_true
   > test_MSstatsConvert.R#020: tinytest::expect_true
   > test_MSstatsConvert.R#022: tinytest::expect_true
   > test_MSstatsConvert.R#023: tinytest::expect_true
   > test_MSstatsConvert.R#024: tinytest::expect_true 
   Remove the 'tinytest::' prefix to register the test results.FALSE
  
  Running test_MSstatsConvert.R.........    0 tests    
  Running test_MSstatsConvert.R.........    0 tests    
  Running test_MSstatsConvert.R.........    0 tests    
  Running test_MSstatsConvert.R.........    0 tests    Error in `[.data.table`(input, , `:=`(c("ProteinName", "PeptideSequence",  : 
    Some items of .SDcols are not column names: [PrecursorCharge, PSM, Mixture, TechRepMixture, Run, BioReplicate]
  Calls: <Anonymous> ... <Anonymous> -> .selectMSstatsColumns -> [ -> [.data.table
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘msstats_data_format.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR
See
  ‘/home/biocbuild/sandbox/MSstatsConvert.Rcheck/00check.log’
for details.
```
I get this on our Linux builder malbec1 (Ubuntu 18.04 + R 4.0.3) and on my laptop (Ubuntu 16.04 + R version 4.0.2 Patched (2020-06-24 r78746)).

Not sure why the automatic build by the SPB (Single Package Builder) didn't pick this up. Could this be a change in tinytest? I'm using the latest version -- 1.2.3 -- which was published on CRAN last week.

Please try to reproduce this on your machine and address. Make sure you're using tinytest 1.2.3 and the latest version of data.table. Also tinytest 1.2.3 should have made its way to all the build machines now so if you bump the version of the package to trigger a new automatic build by the SPB, this error should get reported.

Oh, I just see now that you've made changes to the package since the last automatic build by the SPB (`git log` reports 5 commits since Oct 2, the last one 2 days ago). That must be why. Please address and bump the version so we get a new build report. Thanks!

Best,
H.

**Comment by mstaniak** [comment] 2020-10-16 10:34
Hi,

thanks for letting me know about the tinytest update. Indeed, some tests needed to be updated.
The latest commit should fix the issue.


Best
Mateusz

**Comment by hpages** [comment] 2020-10-20 05:45
Please bump the version of the package so we get a new build. Thanks!

**Comment by mstaniak** [comment] 2020-10-20 08:45
The bot indicated that a build started, but there is no comment with a build report - what went wrong?
I'll bump the version again, hopefully this time we'll get a report

**Comment by hpages** [comment] 2020-10-23 04:28
Thanks @mstaniak for the quick fix. The package is good to go.

Cheers,
H.

**Comment by mtmorgan** [comment] 2020-10-23 17:18
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mstaniak.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MSstatsConvert")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MSstatsConvert

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-10-23 17:18 UTC
Labels: 3a. accepted, OK
