### ISSUE TITLE
tidySpatialExperiment

### ISSUE THREAD

**Issue by william-hutchison** [Bioconductor/Contributions#3130] opened 2023-09-01 01:51 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/william-hutchison/tidySpatialExperiment

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2023-09-13 02:46
you need DropletUtils in Suggests, or _R_CHECK_SUGGESTS_ONLY_ will lead to error

**Comment by william-hutchison** [comment] 2023-09-19 06:22
Hello, thank you for your feedback. I have addressed all warnings and errors produced during the automated test process. Let me know if you have any further suggestions

**Comment by hpages** [comment] 2023-09-28 23:17
Thanks @william-hutchison. Please consider addressing the following NOTEs:

**`R CMD check` NOTEs:**

1. ```
    * checking dependencies in R code ... NOTE
    Packages in Depends field not imported from:
      ‘SpatialExperiment’ ‘tidySingleCellExperiment’
      These packages need to be imported from (in the NAMESPACE file)
      for when this namespace is loaded but not attached.
    ```

2. ```
    Consider adding
      importFrom("methods", "callNextMethod", "getMethod", "is")
    to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
    contains 'methods').
    ```
    Note that for the above note we actually recommend to import the full **methods** namespace with `import(methods)` instead of the suggested selective import.

    Fixing the imports should get rid of most "no visible binding for global variable" and "no visible global function definition" messages. Any remaining one will need to be assessed to determine whether it's a false positive or not.

3. ```
    * checking Rd files ... NOTE
    prepare_Rd: group_by.Rd:70-72: Dropping empty section \seealso
    ```

**`BiocCheck()` NOTEs:**

4. ```
    * Checking for recommended biocViews...
        * NOTE: Consider adding these automatically suggested biocViews:
          Spatial, Transcriptomics, SingleCell, ImmunoOncology, DataImport
    ```
    Maybe not all the terms above are relevant but maybe some of them are?

5. ```
    * Checking vignette directory...
        * NOTE: 'sessionInfo' not found in vignette(s)
    ```

6. ```
    * Checking coding practice...
        * NOTE: Avoid using '=' for assignment and use '<-' instead
    ```

Let me know if you have any questions.

Thanks,
H.

**Comment by william-hutchison** [comment] 2023-10-01 00:26
Thanks @hpages.

I have addressed most of these notes.

I am not sure if I will be able to silence:
`Package in Depends field not imported from: tidySingleCellExperiment
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.`

The exported functions in `tidySingleCellExperiment` which I import are themselves imported from other packages within `tidySingleCellExperiment`, and maintain their original namespace (e.g dplyr), leading to the error `Error: object arrange is not exported by 'namespace:tidySingleCellExperiment'`.

I am also unable to import the whole of `tidySingleCellExperiment` as it causes conflicts with `ttservice`. The other functions I import from `tidySingleCellExperiment` are not exported. 

There are also a few remaining `BiocCheck()` notes on style, which I will continue to work towards fixing.

Let me know if you have any further suggestions.

William

**Comment by william-hutchison** [comment] 2023-10-04 00:24
Although to clarify, I could of course import something which is not needed from `tidySingleCellExperiment` to silence the note. But that seems like a worse outcome than leaving the note as is.

**Comment by hpages** [comment] 2023-10-04 01:25
> I am also unable to import the whole of **tidySingleCellExperiment** as it causes conflicts with **ttservice**. 

I don't see any conflict with **ttservice** when importing the whole **tidySingleCellExperiment**. However, I do see a conflict with `plotly::plot_ly`:
```
Warning: replacing previous import ‘tidySingleCellExperiment::plot_ly’ by ‘plotly::plot_ly’ when loading ‘tidySpatialExperiment’
```
At the root of the problem is how **tidySummarizedExperiment**, **tidySingleCellExperiment**, and **tidySpatialCellExperiment** handle the `plot_ly` generic and methods:
- It looks like **tidySummarizedExperiment** overrides the original `plotly::plot_ly` function with its own `plot_ly` S3 generic. Then it defines the `plot_ly.default` and `plot_ly.SummarizedExperiment` methods.
- Then **tidySingleCellExperiment** does it again i.e. it overrides the original `plotly::plot_ly` function again, as well as the `plot_ly` S3 generic defined in **tidySummarizedExperiment**, with another `plot_ly` S3 generic. Then it defines the `plot_ly.default` method (again) and the new `plot_ly.SingleCellExperiment` method.
- Finally **tidySpatialExperiment** is again doing it: it overrides the original `plotly::plot_ly` function again, as well as the `plot_ly` S3 generics defined in **tidySummarizedExperiment** and **tidySingleCellExperiment**, with a 3rd `plot_ly` S3 generic. Then it defines the `plot_ly.default` method (again) and the `plot_ly.SpatialExperiment` method.

Note that every time a generic is masked by a new generic of the same name, all the methods defined for the masked generic also get masked.

This approach has a lot of problems, too many to discuss them in detail here. Best practice is to define the generic function _in one place_, and also to define each method only once. Also the default method should just be an alias to the original non-generic function (in this case it should be the `plot_ly` function defined in the **plotly** package).

This is easy to do with S4 generics and classes (note that Bioconductor recommends the use of S4 over S3):

1. Define and export the `plot_ly` S4 generic and default method:
    ```
    setGeneric("plot_ly", signature="data")
    ```
    Note that this statement automatically takes care of defining the default method (see it with `selectMethod(plot_ly, "ANY")`). This should probably go at the bottom of the tidy*Experiment stack, that is, in the **tidySummarizedExperiment** package. Also **tidySummarizedExperiment** will still need to import the `plot_ly` function from the **plotly** package like it does already. 

2. Each package that wants to define a `plot_ly()` method must import the `plot_ly` generic _from **tidySummarizedExperiment**_ (with `importFrom(tidySummarizedExperiment, plot_ly)`), then use `setMethod()` to define the S4 method. E.g. **tidySingleCellExperiment** will need to do something like:
    ```
    setMethod("plot_ly", "SingleCellExperiment",
        function(data = data.frame(), ..., type = NULL, name, color, 
                 colors = NULL, alpha = NULL, stroke, strokes = NULL, alpha_stroke = 1, 
                 size, sizes = c(10, 100), span, spans = c(1, 20), symbol, 
                 symbols = NULL, linetype, linetypes = NULL, split, frame, 
                 width = NULL, height = NULL, source = "A")
        {
            ...
            ...
        }
    )
    ```
    Note that the S4 method for SummarizedExperiment objects will (of course) need to be defined in **tidySummarizedExperiment**, where the S4 generic is defined. So in this case no additional import is needed.

3. About exports: **tidySummarizedExperiment** will need to export the `plot_ly` generic (with `export(plot_ly)`) and methods (with `exportMethods(plot_ly)`). Other packages that only define `plot_ly` S4 methods will need to export these methods (in particular they don't need and should not do `export(plot_ly)`).

4. Finally man pages will need to have the corresponding `\alias` and `\usage` lines.
 
Hope this helps,
H.

**Comment by william-hutchison** [comment] 2023-10-04 05:58
Thank you for your detailed response. I will discuss making these changes in **tidySingleCellExperiment** and **tidySpatialExperiment** with @stemangiola, the maintainer of the packages.

**Comment by stemangiola** [comment] 2023-10-04 15:51
Thanks @hpages, for the feedback. @william-hutchison we can use for plotly the same strategy that we used for any other methods in `tidySCE`. If that satisfies the feedback, we can apply it to the other tidy* packages.

**Comment by william-hutchison** [comment] 2023-10-05 05:36
I have prevented the overwriting of `plot_ly` methods in **tidySpatialExperiment**. The generic method is now imported from **tidySummarizedExperiment**. I found that in this instance the **tidySingleCellExperiment** version of plot_ly is suitable for use with a `SpatialExperiment` object, so to reduce code duplication I have removed the `plot_ly` function definition in **tidySpatialExperiment**.

I have submitted pull requests to **tidySingleCellExperiment** and **tidySummarizedExperiment** switching to S4 and preventing the `plot_ly` methods from being overwritten.

I initially tried to fix these dependencies using S3 to be consistent with the rest of the tidy* packages but was not successful. I think `plot_ly` is likely an issue because it does not include a generic method, while **ggplot** ect do. This forces more complicated dependencies, which were difficult to overcome using S3 and may be why the methods were coded to overwrite each other in this way to begin with.

Regardless, I think the changes I submitted to **tidySingleCellExperiment** and **tidySummarizedExperiment** have improved the way `plot_ly` is handled across the tidy* packages. Also I believe they will silence the warning which just popped up once merged.

**Comment by hpages** [comment] 2023-10-06 05:15
Thanks for these changes. For your comments about S3 vs S4, I appreciate your point about trying to handle the `plot_ly` situation in S3, for consistency with the rest of the tidy* packages. And maybe there's an elegant way to do it with S3, I don't know, I'm not familiar enough with S3 to tell. I just know that S4 handles this nicely using the approach I suggested above, which is standard routine in Bioconductor. Thanks again for trying that. We'll see how it goes when the changes in **tidySingleCellExperiment** and **tidySummarizedExperiment** get merged and propagate, hopefully soon.

**Comment by hpages** [comment] 2023-10-17 19:38
Hi @william-hutchison Any progress on this? The 3.18 release is coming soon and we only have a few days left to add new packages to the 3.18 manifest. Thanks

**Comment by william-hutchison** [comment] 2023-10-18 07:11
Hi @hpages, sorry about the delay. A different project has taken my attention over the past week. I will try to get this finished in the next few days, all good if it doesn't get included in the 3.18 release though.

**Comment by william-hutchison** [comment] 2023-11-02 04:01
I believe I have addressed the issues related to `ploy_ly`. **ttservice** now contains a S3 generic for `plot_ly` and a default S3 method. Both are imported by **tidySpatialExperiment**. 

When the user uses `plot_ly` with the `SpatialExperiment` class they will be calling the generic in **ttservice**, which then calls the `SpatialExperiment` `plot_ly` method in **tidySpatialExperiment**, which then extracts the cell data and calls the default `plot_ly` method in **ttservice**. 

I have also applied this strategy to `plot_ly` in **tidySIngleCellExperiment** https://github.com/stemangiola/tidySingleCellExperiment/pull/100 and **tidySummarizedExperiment** https://github.com/stemangiola/tidySummarizedExperiment/pull/86. If the user has multiple tidy* packages loaded the single generic in **ttservice** will direct the user's call of `plot_ly` to the correct method given the class. 

In my testing the warning:

`Warning: replacing previous import tidySingleCellExperiment::plot_ly by ttservice::plot_ly when loading tidySpatialExperiment`

is solved with the newly merged changes to **tidySIngleCellExperiment** V1.11.8. 

I abandoned my previously mentioned implementation of S4 `plot_ly` sharing between tidy* packages to better match the structure of the ecosystem. 

Thanks for your help with this @hpages and let me know if you have any further suggestions.

Kind regards,
William

**Comment by william-hutchison** [comment] 2023-11-28 01:15
Hi @hpages, the last remaining warning was solved by the updated **tidySingleCellExperiment** being used in the test build.

I will continue to work on tidySpatialExperiment as on ongoing project, but I believe it is now in quite a polished state.

Let me know if you would like to see any more changes before acceptance into Bioconductor and thanks again for your help.

**Comment by lshep** [comment] 2024-01-03 13:13
I'm very sorry for the delay; it should not be taking this long. I will check in with @hpages if he plans to revisit this review soon or reassign the reviewer if necessary

**Comment by hpages** [comment] 2024-01-03 17:10
Hi @william-hutchison, taking a look now...

**Comment by hpages** [comment] 2024-01-05 01:54
@william-hutchison I don't see that the `plot_ly` situation has been addressed properly e.g. I still see the `plot_ly()` generic being defined in at least 2 different places, one in **ttservice**:
```
library(ttservice)
plot_ly
# function (data = data.frame(), ..., type = NULL, name = NULL, 
#     color = NULL, colors = NULL, alpha = NULL, stroke = NULL, 
#     strokes = NULL, alpha_stroke = 1, size = NULL, sizes = c(10, 
#         100), span = NULL, spans = c(1, 20), symbol = NULL, symbols = NULL, 
#     linetype = NULL, linetypes = NULL, split = NULL, frame = NULL, 
#     width = NULL, height = NULL, source = "A") 
# {
#     UseMethod("plot_ly")
# }
# <bytecode: 0x564201dde750>
# <environment: namespace:ttservice>
```
and one in **tidySummarizedExperiment**:
```
library(tidySummarizedExperiment)
plot_ly
# function (data = data.frame(), ..., type = NULL, name = NULL, 
#     color = NULL, colors = NULL, alpha = NULL, stroke = NULL, 
#     strokes = NULL, alpha_stroke = 1, size = NULL, sizes = c(10, 
#         100), span = NULL, spans = c(1, 20), symbol = NULL, symbols = NULL, 
#     linetype = NULL, linetypes = NULL, split = NULL, frame = NULL, 
#     width = NULL, height = NULL, source = "A") 
# {
#     UseMethod("plot_ly")
# }
# <bytecode: 0x564211f42048>
# <environment: namespace:tidySummarizedExperiment>
```

FWIW here is what your package stack looks like:
```
  tidySpatialExperiment
           |
           v
 tidySingleCellExperiment
           |
           v
 tidySummarizedExperiment
           |
           v
       ttservice
           |                           packages that you control
 - - - - - | - - - - - - - - - - - - - - - - - - - - - - - - - - - 
           |                           package that you do not control
           v 
         plotly
```
As I explained earlier there should be one `plot_ly()` generic only, defined at the lowest level (i.e. in your **ttservice** package), and all other packages in your package stack should only define `plot_ly()` _methods_.

Best,
H.

**sessionInfo():**
```
R Under development (unstable) (2024-01-02 r85764)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 23.10

Matrix products: default
BLAS:   /home/hpages/R/R-4.4.r85764/lib/libRblas.so 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Los_Angeles
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] ggplot2_3.4.4                   tidyr_1.3.0                    
 [3] dplyr_1.1.4                     tidySummarizedExperiment_1.13.0
 [5] SummarizedExperiment_1.33.1     Biobase_2.63.0                 
 [7] GenomicRanges_1.55.1            GenomeInfoDb_1.39.5            
 [9] IRanges_2.37.0                  S4Vectors_0.41.3               
[11] BiocGenerics_0.49.1             MatrixGenerics_1.15.0          
[13] matrixStats_1.2.0               ttservice_0.4.0                

loaded via a namespace (and not attached):
 [1] plotly_4.10.3           utf8_1.2.4              generics_0.1.3         
 [4] SparseArray_1.3.2       bitops_1.0-7            stringi_1.8.3          
 [7] lattice_0.22-5          digest_0.6.33           magrittr_2.0.3         
[10] grid_4.4.0              fastmap_1.1.1           jsonlite_1.8.8         
[13] Matrix_1.6-4            httr_1.4.7              purrr_1.0.2            
[16] fansi_1.0.6             viridisLite_0.4.2       scales_1.3.0           
[19] lazyeval_0.2.2          abind_1.4-5             cli_3.6.2              
[22] rlang_1.1.2             crayon_1.5.2            XVector_0.43.0         
[25] ellipsis_0.3.2          munsell_0.5.0           withr_2.5.2            
[28] DelayedArray_0.29.0     S4Arrays_1.3.1          tools_4.4.0            
[31] colorspace_2.1-0        GenomeInfoDbData_1.2.11 vctrs_0.6.5            
[34] R6_2.5.1                lifecycle_1.0.4         stringr_1.5.1          
[37] zlibbioc_1.49.0         htmlwidgets_1.6.4       pkgconfig_2.0.3        
[40] pillar_1.9.0            gtable_0.3.4            data.table_1.14.10     
[43] glue_1.6.2              tibble_3.2.1            tidyselect_1.2.0       
[46] htmltools_0.5.7         compiler_4.4.0          RCurl_1.98-1.13        
```

**Comment by william-hutchison** [comment] 2024-01-05 02:12
Hi @hpages, thank you for your feedback. 

I had removed the `plot_ly()` generic from **tidySummarizedExperiment** in our [development version](https://github.com/stemangiola/tidySummarizedExperiment/blob/master/R/plotly_methods.R) but did not push these changes to Bioconductor. Sorry about that, I will address this now. 

Kind regards, 
William

**Comment by william-hutchison** [comment] 2024-01-09 23:12
Hi @hpages. The updated **tidySummarizedExperiment** has been pushed the devel branch of Bioconductor. Thanks again.

**Comment by hpages** [comment] 2024-01-17 03:56
Great, thanks!

Last thing on the list: since in the end the `plot_ly()` generic is defined in the **ttservice** package, do you really need to list **tidySummarizedExperiment** in `Depends`? What is **tidySummarizedExperiment** used for in **tidySpatialExperiment**?

If you do need to depend on **tidySummarizedExperiment**, then make sure to import the package in your `NAMESPACE` like you did for **tidySingleCellExperiment**. This issue is actually reported by `R CMD check`:
```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘tidySummarizedExperiment’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```
If you don't need to depend on **tidySummarizedExperiment** then remove it from `Depends`.

Maybe the same applies to **tidySingleCellExperiment**? Do you really need to depend on it?

Thanks again,
H.

**Comment by william-hutchison** [comment] 2024-01-18 02:12
Hi @hpages, thank you for your suggestions. 

I have moved **tidySummarizedExperiment** to `Suggests`. I believe **tidySingleCellExperiment** should remain in `Depends` to attach functions which are not exported by **tidySpatialExperiment** and are instead called directly from **tidySingleCellExperiment** e.g `count()`.

Unfortunately I am now encountering an error with the macOS build:

`ERROR: dependency SpatialExperiment is not available for package tidySpatialExperiment`

All works well on Ubuntu and I am not sure what could be causing this, as SpatialExperiment has always been listed in `Depends`. I will continue to investigate, but let me know if you have any ideas. Maybe it could be a problem with the build process?

Thanks again

**Comment by hpages** [comment] 2024-01-19 18:42
Maybe it was just bad timing. We updated R to the latest R-devel on all our devel build machines a couple of days ago. It could be that the SPB got triggered before all the BioC packages got reinstalled on merida1. Can you please trigger a new build by bumping the version again? Thanks

**Comment by hpages** [comment] 2024-01-20 03:49
Thanks. Let's ignore the warning on merida1.` R CMD check` took a little bit more than 10 min there (11 minutes 43.62 seconds), not a big deal.

3 minor things left and the package will be good to go:

1. This `R CMD build` note:
```
* checking for empty or unneeded directories
Omitted LazyData from DESCRIPTION
```
(just remove the `LazyData: false` line)

2. This `R CMD check` note:
```
* checking Rd line widths ... NOTE
Rd file 'rectangle.Rd':
  \examples lines wider than 100 characters:
         mutate(in_rectangle = rectangle(array_col, array_row, center = c(50, 50), height = 20, width = 10))
```

3. This `R CMD BiocCheck` note:
```
* Checking coding practice...
    * NOTE: Avoid using '=' for assignment and use '<-' instead
```

Almost there.

Thanks again.

**Comment by william-hutchison** [comment] 2024-01-22 00:03
Hi @hpages, I have addressed the three notes you raised. Thank you for helping me improve **tidySpatialExperiment**.

**Comment by hpages** [comment] 2024-01-22 14:37
Great, thanks!

**Comment by lshep** [comment] 2024-01-26 12:40
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/william-hutchison.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("tidySpatialExperiment")`. The package 'landing page' will be created at

https://bioconductor.org/packages/tidySpatialExperiment

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-01-26 12:40 UTC
Labels: 3a. accepted
