### ISSUE TITLE
CuratedAtlasQueryR

### ISSUE THREAD

**Issue by multimeric** [Bioconductor/Contributions#2991] opened 2023-03-29 01:08 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/stemangiola/CuratedAtlasQueryR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by multimeric** [comment] 2023-04-04 03:47
Is there any way to access the logs of the bioc build? Also, are there any known issues relating to network accesses or filesystem usage on the build machine? Because when I run a build locally it finishes in just under 2 minutes, and therefore shouldn't be hitting the 15 minute timeout:

```bash
$ gh repo clone stemangiola/CuratedAtlasQueryR
Cloning into 'CuratedAtlasQueryR'...
remote: Enumerating objects: 2078, done.
remote: Counting objects: 100% (817/817), done.
remote: Compressing objects: 100% (355/355), done.
remote: Total 2078 (delta 524), reused 676 (delta 444), pack-reused 1261
Receiving objects: 100% (2078/2078), 1.86 MiB | 1.30 MiB/s, done.
Resolving deltas: 100% (1256/1256), done.
$ /usr/bin/time R CMD build CuratedAtlasQueryR
* checking for file ‘CuratedAtlasQueryR/DESCRIPTION’ ... OK
* preparing ‘CuratedAtlasQueryR’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyDataCompression’ from DESCRIPTION
* building ‘CuratedAtlasQueryR_0.99.1.tar.gz’

86.92user 13.00system 1:45.13elapsed 95%CPU (0avgtext+0avgdata 1515732maxresident)k
2192328inputs+16920outputs (1010major+3387858minor)pagefaults 0swaps
```

**Comment by multimeric** [comment] 2023-04-05 00:12
`R CMD build` also only takes 216.70 seconds, ie < 4 minutes on my own Mac, using my home internet connection which isn't even that fast. So I'm not sure what is happening here.

**Comment by lshep** [comment] 2023-04-05 12:40
Are you using the latest versions of all packages and R 4.3 Bioc 3.17 to test?  BiocManager::valid to make sure that you have the expected versions of packages.  I just tried locally on my linux box and it is at  15 minutes and it still has not finished building.  Is there large amounts of data being downloaded? Are you using caching mechanisms?

**Comment by multimeric** [comment] 2023-04-05 12:48
Yes, it downloads a decent amount of data to run the vignette. Maybe 500mb at a guess? Is that likely to be an issue? Is the time to install dependencies included in the build time? I thought not.

**Comment by lshep** [comment] 2023-04-05 12:50
package dependency installation no.  but data download and actively building the vignette yet.

**Comment by vjcitn** [comment] 2023-04-05 13:20
If the downloaded data are properly cached then once the build system has the resources cached, it will not need to download them again and event times will be reduced.  Are we talking about the metadata resource or illustrative SCE?

**Comment by lshep** [comment] 2023-04-05 13:29
Also 500 mb seems like a lot of data.  Could a smaller subset be used?  Many times a smaller example is enough for proof of principle.

**Comment by multimeric** [comment] 2023-04-05 13:37
> Also 500 mb seems like a lot of data. Could a smaller subset be used? Many times a smaller example is enough for proof of principle.

It would be possible, just annoying. The metadata file is a bit of a monolith and I'd rather not have to maintain a separate "demo metadata" file that would also complicate the vignette with advanced parameters.

> If the downloaded data are properly cached then once the build system has the resources cached, it will not need to download them again and event times will be reduced. Are we talking about the metadata resource or illustrative SCE?

Yes, downloaded data is cached, and I'm fairly certain that is working properly. The largest download is probably the metadata file itself, which is ~450 Mb.

My best guess right now about what is happening is that the data is located in Australia and all of my testing has been in Australia, but the BioC build machine is presumably not. The slower download might be caused by that geographic distance.

**Comment by lshep** [comment] 2023-04-05 13:51
Annoying maybe but please keep in mind we have thousands of packages we are building and providing support for.  And users might not always have access to 500 mb of space of a system. Is the full metadata file required for full functionality of the package?   Where are you hosting the data currently?

**Comment by LiNk-NY** [comment] 2023-04-05 18:01
The check took quite a bit of time for me too

```r
real	10m7.507s
user	11m3.190s
sys	0m12.881s
```

FWIW, the installation of `duckdb` takes quite a bit of time but this is separate from the `R CMD check`.

**Comment by LiNk-NY** [comment] 2023-04-05 18:03
Hi Michael, @multimeric 
Thank you for your submission. 
Please see the review below. 
Best,
Marcel 

--- 

# CuratedAtlasQueryR #2991

## DESCRIPTION

* Consider checking for typos (Should "agnency" be "agency"?)
* Consider including an ORCiD identifier at least for the maintainer.
* Looks good

## NAMESPACE

* Consider combining `get_*metadata` into a single function with an
`unharmonized = TRUE/FALSE` option.
* Looks good.
* Minor: Consider using camelCase vs snake_case for exported functions.

## vignettes

* Remove GitHub installation section after acceptance.
* Provide a short explain with regards to how the data is hosted and from what
project it originates.
* Is it possible to avoid the `eval=FALSE` in the metadata chunk and others?
* Is realized data cached?
* Include a `sessionInfo()` section

## R

* Consider using a single `assert_that` call and separate expressions with
commas `,`.
* Perhaps use `force(data)` in `get_SingleCellExperiment`?
* Looks good.

## tests

* Coverage looks good

## dev

* Consider moving this folder into the `inst` directory

## /

* `tissue_label.csv` seems out of place, perhaps move it into `inst/extdata`?

**Comment by multimeric** [comment] 2023-04-06 06:11
Hi @LiNk-NY, thanks for the review.

> Is it possible to avoid the eval=FALSE in the metadata chunk and others?

Would you mind clarifying which chunk(s) you are referring to?

> Is realized data cached?

Also which data to you mean here?

**Comment by LiNk-NY** [comment] 2023-04-06 20:59
> Would you mind clarifying which chunk(s) you are referring to?

I mean these and a chunk above the linked section: 

https://github.com/stemangiola/CuratedAtlasQueryR/blob/d2bf12e09f18ed6e4331214b03e1a11e4d40e997/vignettes/Introduction.Rmd#L171-L293

> > Is realized data cached?
> 
> Also which data to you mean here?

The assay and metadata data. It looks like `get_default_cache_dir()` is used to cache and it is possible to cache the connection.

**Comment by LiNk-NY** [comment] 2023-04-14 20:58
BTW you can knit the vignette into the `README.md` with code like in: 
https://github.com/waldronlab/TENxIO/blob/devel/inst/scripts/README.Rmd
There are ways to do this automatically via GitHub Actions as well.

**Comment by LiNk-NY** [comment] 2023-04-14 21:49
https://github.com/stemangiola/CuratedAtlasQueryR/blob/d2bf12e09f18ed6e4331214b03e1a11e4d40e997/vignettes/Introduction.Rmd#L165-L174

AFAIU, saving an object with an HDF5 backend only serializes the seed links within the `SingleCellExperiment` `assay`. This is the reason it is fast. If the path to the H5 files are altered (e.g., shared) the `Rds` file no longer works. The recommended way of saving an object with an HDF5 backend is to use `saveHDF5SummarizedExperiment` in `HDF5Array`. 
Perhaps @hpages can confirm.

**Comment by multimeric** [comment] 2023-04-15 05:24
> AFAIU, saving an object with an HDF5 backend only serializes the seed links within the SingleCellExperiment assay. This is the reason it is fast. If the path to the H5 files are altered (e.g., shared) the Rds file no longer works. The recommended way of saving an object with an HDF5 backend is to use saveHDF5SummarizedExperiment in HDF5Array.

Yes, that is the point being made in the vignette. That saving the unrealised DelayedArray is fast because the computation hasn't happened yet. `saveHDF5SummarizedExperiment` is explained in the next section.

**Comment by LiNk-NY** [comment] 2023-04-15 19:50
It wasn't clear in the vignette and it should probably be discouraged because the `Rds` file is not portable. 
For example, if you share the `Rds` file, the collaborator will get this error because they do not have the original `h5` file.

```r
> library(SingleCellExperiment)
> test <- readRDS("/home/rstudio/data/single_cell_counts.rds")
> assay(test)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'type': file '/home/user/.cache/R/CuratedAtlasQueryR/0.2.1/original/bc380dae8b14313a870973697842878b/assays.h5' does not exist
```

**Comment by stemangiola** [comment] 2023-05-08 06:26
Hello @LiNk-NY, I am trying to push to bioc with

`git push upstream devel`

but I get

```
FATAL: W any packages/CuratedAtlasQueryR stemangiola DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Could you please advise

**Comment by lshep** [comment] 2023-05-08 11:35
Please try again; I believe we have fixed the issue.

**Comment by stemangiola** [comment] 2023-05-09 00:09
Thanks @lshep ,

now I get a different error

```
(base) [mangiola.s@rstudio-2 CuratedAtlasQueryR]$ git push upstream devel
error: src refspec devel does not match any.
error: failed to push some refs to 'git@git.bioconductor.org:packages/CuratedAtlasQueryR.git'
```

**Comment by multimeric** [comment] 2023-05-09 07:08
@stemangiola That's because our main branch isn't called `devel`.

**Comment by multimeric** [comment] 2023-05-09 07:25
@LiNk-NY 

While we wait for the build report, here is my response to your feedback.

> Consider checking for typos (Should "agnency" be "agency"?)

This typo has been fixed. Also I've added a spell checker to our test suite which will detect much such issues: https://github.com/stemangiola/CuratedAtlasQueryR/blob/master/tests/spelling.R. The one you identified was in the name field of the DESCRIPTION so couldn't be automatically detected anyway.

> Consider including an ORCiD identifier at least for the maintainer.

Done. Stefano and I have our ORCiDs listed

> Consider combining get_*metadata into a single function with an unharmonized = TRUE/FALSE option.

This is something we considered earlier, before submitting. The API is designed this way because the harmonised vs unharmonised metadata are completely different in structure, and we hope the average user will not have to think about `get_unharmonised()` at all. The API is designed this way to encourage the user to use `get_metadata()` instead.

> Minor: Consider using camelCase vs snake_case for exported functions.

The package has been standardised to use snake_case. This only involved changing one function: `getSingleCellExperiment` to `get_single_cell_experiment`.

> Provide a short explain with regards to how the data is hosted and from what project it originates.

This is now mentioned in the README.

> Is it possible to avoid the eval=FALSE in the metadata chunk and others?

I've created a minimal metadata file that means the entire vignette is now evaluated.

> Is realized data cached?

Still not entirely sure what this refers to, but yes we cache the assay data and metadata. We don't cache user-transformed versions of either, and we leave that up to the user.

> Include a sessionInfo() section

This is now in the vignette

> Consider using a single assert_that call and separate expressions with commas ,

This is done where possible, but it isn't possible in all cases because each `assert_that` can only have one error message per function call.

> Perhaps use force(data) in get_SingleCellExperiment?

Done, this is clearer in intention.

> dev
> Consider moving this folder into the inst directory

This isn't installed in the package (it's in the `.Rbuildignore`), so hopefully it's location in the repo doesn't matter

> BTW you can knit the vignette into the README.md with code like in:

The vignette and the readme have now been unified

> It wasn't clear in the vignette and it should probably be discouraged because the Rds file is not portable.
> For example, if you share the Rds file, the collaborator will get this error because they do not have the original h5 file.

I have added more detail about the tradeoffs of each serialization method.

**Comment by multimeric** [comment] 2023-05-15 01:14
I'm a bit perplexed by the build failure though. I added a much smaller metadata file as suggested, and it still seems to be timing out. Any input would be appreciated.

**Comment by LiNk-NY** [comment] 2023-05-17 22:23
I have tried building the package locally and it is taking quite a bit of time.

**Comment by LiNk-NY** [comment] 2023-05-22 20:49
Hi Michael, @multimeric 
Thank you for making those changes. 
A couple of minor points: 

* Consider using `BiocStyle` to style the vignette. 
* Resolve this warning: 
```r
* checking S3 generic/method consistency ... WARNING
as.sparse:
  function(x, ...)
as.sparse.DelayedMatrix:
  function(x)
See section 'Generic functions and methods' in the 'Writing R
Extensions' manual.
```

Your package has been accepted on the condition that the above will be considered. 
Best,
Marcel

**Comment by multimeric** [comment] 2023-05-22 22:45
Thanks for the feedback, will implement those two points. Can you explain why it was accepted despite the build time issue?

**Comment by lshep** [comment] 2023-05-23 11:32
@LiNk-NY I would also like verification on this point? It has not built once on the SPB without a timeout?  We don't even have a R CMD check and BiocCheck for it?

**Comment by LiNk-NY** [comment] 2023-05-23 14:34
Hi Michael and Lori, @multimeric @lshep 

I ran it on my machine and it passed though it took about 10 minutes. 
It seemed to me to be an SPB issue but please create a commit and have the SPB give it another go. 

Best,
Marcel

**Comment by multimeric** [comment] 2023-05-24 00:57
Does the build machine have a persistent cache? Because I changed the metadata file used in the vignette into a smaller sample one, which made the build much faster. However if the old metadata file were still cached I could see the build taking a while.

**Comment by lshep** [comment] 2023-05-24 11:30
@multimeric if you utilized caching mechanisms then yes the cache should be persistent.  What would I be looking for to delete out/reset?

**Comment by multimeric** [comment] 2023-05-24 11:38
`CuratedAtlasQueryR:::get_default_cache_dir() |> unlink(TRUE, TRUE, TRUE)` should do it, I think.

**Comment by lshep** [comment] 2023-05-24 11:43
Could you bump the version and try again.  I reset the cache.

**Comment by stemangiola** [comment] 2023-06-14 10:39
Hello @LiNk-NY , and All,

thanks a lot for reviewing this package.

Could we please accept the package, as the timeout is due to the long installation of DuckDB, which is not our fault, and there is nothing we can do about it.

thanks a lot.

**Comment by LiNk-NY** [comment] 2023-06-14 13:59
Hi Stefano, @stemangiola 

Thank you for your patience. 

The package should not install any packages and I don't think it installs `duckdb` while running `R CMD build`?

Building the package locally takes less than 2 minutes on my end.  
I am not sure what the issue is. 

Do you have any ideas Lori? @lshep

**Comment by lshep** [comment] 2023-06-23 14:56
I also got a build in a few minutes when I manually attempted.  I'm going to manually trigger another build to see what happens and see if it has corrected itself.

**Comment by multimeric** [comment] 2023-06-24 01:04
Okay the build seems to be making progress now.

>  ERROR: Maintainer must add package name to Watched Tags on the support site; Edit your Support Site User Profile to add Watched Tags.

I'm not really sure what this means, considering the package isn't yet in BioC, but maybe @stemangiola you can do something here?

**Comment by stemangiola** [comment] 2023-06-24 07:42
I tried, but I cannot. I think first we accept it on Bioconductor, and then I will add the Watched Tags

<img width="1134" alt="image" src="https://github.com/Bioconductor/Contributions/assets/7232890/4718d832-2598-4854-a6bf-a22deb0c099d">

**Comment by vjcitn** [comment] 2023-06-24 10:22
I guess tag adding and the error message could be clarified.  Edit your profile at support.bioconductor.org.  Go to "My tags" field and add any string.  It becomes a watched tag.  @LiNk-NY am I right?  Should we provide more doc on this in BiocCheck?

![tags](https://github.com/Bioconductor/Contributions/assets/4624066/19e8c897-bb07-4616-bc05-fc2f5cf302d1)

**Comment by LiNk-NY** [comment] 2023-06-24 11:46
The package doesn't have to be in Bioconductor to be able to add a Watched Tag. The maintainer email must agree in both the package `DESCRIPTION` and support site. It looks like @stemangiola has added the tag in the screenshot. It should work with a version bump.

**Comment by LiNk-NY** [comment] 2023-06-30 20:19
Hi Stefano, @stemangiola 
Any updates on this? 

@multimeric 
In the meantime, please resolve this warning for formals consistency: 

```r
* checking S3 generic/method consistency ... WARNING
as.sparse:
  function(x, ...)
as.sparse.DelayedMatrix:
  function(x)
See section 'Generic functions and methods' in the 'Writing R
Extensions' manual.
```

Once ready, please bump the version and `push` for another build. 

-Marcel

**Comment by stemangiola** [comment] 2023-07-03 09:49
@multimeric I had a look but I'm not sure about the logics of as.sparse. Would you mind fix and push to bioconductor.

We might be on the edge of acceptance.

Thanks a lot.

**Comment by multimeric** [comment] 2023-07-06 03:39
Hi all, the above warning has been fixed, the version bumped and it seems to have resolved the Watched Tags error as well. However I'm not sure abut the last remaining warning:
> WARNING: Empty or missing \value sections found in man pages.

I had a look through all our man pages just now and none of them have empty `\value` sections. Could this relate to a dependency?

**Comment by LiNk-NY** [comment] 2023-07-06 14:16
Hi Michael @multimeric 
Have you checked the `CuratedAtlasQueryR.BiocCheck` folder? (Note you have to run `BiocCheck::BiocCheck()` locally)
I see this: 
```r
* WARNING: Empty or missing \value sections found in man pages.
Found in files:
man/cache.Rd, man/COUNTS_URL.Rd, man/COUNTS_VERSION.Rd, man/DATABASE_URL.Rd, man/downsample_metadata.Rd, man/SAMPLE_DATABASE_URL.Rd, man/UNHARMONISED_URL.Rd
```
Best,
Marcel

**Comment by multimeric** [comment] 2023-07-07 00:39
I see, so we have missing `@return` fields in some of the docs. Although some of these objects are not functions so I'm not sure why they're being checked or what to set their `@return` to.

**Comment by LiNk-NY** [comment] 2023-07-07 23:51
Hi Michael, @multimeric 
It looks like some of them are package constants. They probably do not need to be exported (e.g., `SAMPLE_DATABASE_URL`). Otherwise, you would have to include a `@return` entry indicating "a single string for ...". 
Note that package constants are often written as `.SAMPLE_DATABASE_URL` with a leading dot indicating that they are not exported. 
Best,
Marcel

**Comment by multimeric** [comment] 2023-07-11 06:04
> It looks like some of them are package constants. They probably do not need to be exported (e.g., SAMPLE_DATABASE_URL).

Sadly they do need to be exported. I had to add them to the package to work around the package test runtime limitation. I will document them as you have described.

**Comment by multimeric** [comment] 2023-07-11 06:35
And actually it seems to be checking non-exported objects too, like `cache`, which has a man page for internal use which it seems like I will have to remove

**Comment by stemangiola** [comment] 2023-07-12 04:08
Thanks @multimeric, for your tenancy!

This is a good time to mention that we received some funds for a further 12-month development of the package to incorporate disease-specific data sets and enhance the database and interface with biological analysis results read delete available to researchers.

**Comment by LiNk-NY** [comment] 2023-07-12 17:22
Hi @multimeric 
Thank you for making the changes. It looks good to me. 
Your package has been accepted. 

FWIW, please follow the latest recommendations for resolving: 

```
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
```
@lshep Do you have resources for resolving this issue?

It may be coming from a package dependency.

Thank you.
-Marcel

**Comment by lshep** [comment] 2023-07-12 20:01
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/multimeric.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CuratedAtlasQueryR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CuratedAtlasQueryR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-07-12 20:01 UTC
Labels: OK, 3a. accepted
