### ISSUE TITLE
ProteoMM: Model-Based Peptide-Level Analysis Platform for Combined Analysis of Multiple Omics Datasets

### ISSUE THREAD

**Issue by YuliyaLab** [Bioconductor/Contributions#792] opened 2018-06-30 01:50 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/YuliyaLab/ProteoMM
Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2018-06-30 10:54
@nturaga will review this package. Please consider adopt [standard Biocondcutor data representations][1] for interfacing with your user. For instance, in the 'Human' section of the vignette it sounds as though your have a matrix of 635 peptides from 6 samples, with additional metadata describing the peptides. This can be represented as a SummarizedExperiment, where the 635 x 6 matrix of intensities represent the 'assay', the additional metadata are 'rowData()'.

[1]: http://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by YuliyaLab** [comment] 2018-06-30 13:07
Hi, I eliminated one of the warnings (now using is.factor()) but for reproducibility, we must have set.seed() in our code. We are imputing missing values with randomly generated ones. For someone to reproduce the results the users must be able to set the random seed. Can you please let me know how I can get around this warning? 
I am going to make another push shortly with version 99.2 where I updated the NAMESPACE file. 
Thank you!

**Comment by YuliyaLab** [comment] 2018-07-04 16:37
Hi, my code requires the ability to set the random number generator seed for Reproducibility. The software generates imputed values and thus it is essential to be able to reproduce the results to set the seed. Can you please let me know how to avoid the Warning due to the presence of set.seed() in my code. 

* Checking coding practice...
    * WARNING: Remove set.seed usage in R code
      Found in R/ directory functions:
        MBimpute()
        sva.id()

Many thanks!

**Comment by nturaga** [comment] 2018-07-05 21:50
Hi @YuliyaLab 

You can just let the user do the `set.seed(123)` themselves before running your `MBimpute()` function. You can choose to throw a warning to the user saying that, setting a seed is important. 

You can also give an example in your man page where you set a seed. 

Thanks

**Comment by YuliyaLab** [comment] 2018-07-08 03:49
Hi, yes, that is an option, but requiring the user to specify the parameter would assure that they do set ti. I will reorganize to warn the users to set the seed. Thank you,
Yuliya

**Comment by nturaga** [comment] 2018-07-12 16:53
# Review ProteoMM

## R CMD build

ok

## R CMD INSTALL 

* Fix these INSTALL artifacts, `R CMD INSTALL ProteoMM_0.99.4.tar.gz`

```
Bioconductor version 3.8 (BiocInstaller 1.31.1), ?biocLite for help
* installing to library '/Users/ni41435_ca/R-stuff/bin/R-3-5-branch/library'
* installing *source* package 'ProteoMM' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
* Adding gdata to Imports

Next:
Refer to functions with gdata::fun()
* Adding ggplot2 to Imports

Next:
Refer to functions with ggplot2::fun()
* Adding ggrepel to Imports

Next:
Refer to functions with ggrepel::fun()
* Adding gtools to Imports

Next:
Refer to functions with gtools::fun()
* Adding multtest to Imports

Next:
Refer to functions with multtest::fun()
* Adding readr to Imports

Next:
Refer to functions with readr::fun()

** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Bioconductor version 3.8 (BiocInstaller 1.31.1), ?biocLite for help
* DONE (ProteoMM)
```

## DESCRIPTION

* ok

## NAMESPACE

* ok

## vignettes

* Give your vignette a more appropriate name. 

* No need to have the `html` file, as the build system will run
  the vignette and generate the html file.

* Vignette is looks unstructured, use BiocStyle for better
  formatting
  https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html.

http://bioconductor.org/developers/package-guidelines/#vignettes

## man

ok

## NEWS 

* Empty NEWS file.

## R

### `EigenMS.R`

* You don't need to use `which` here, it creates a logical vector
  which can be used as indices.
  
  
		present = prot.info[which(!prot.info[,1] %in% rownames(pmiss)), ] #rownames OK
		pres = m[which(!prot.info[,1] %in% rownames(pmiss)), ]
		rownames(pres) = prot.info[which(!prot.info[,1] %in% rownames(pmiss)),1]
		
		
* You can use `rowMins` or `colMins` (from` library(matrixStats)`)
  instead of

		present.min = apply(nobs, 1, min) # number present in each group
		
		
	Try:
	
		x <- matrix( rnorm(1000 * 2000), ncol = 2000 )

		system.time( s1 <- rowMins(x) )
		system.time( s1 <- apply(x, 1, min) )

		system.time( s1 <- rowMaxs(x) )
		system.time( s1 <- apply(x, 1, max) )


It's always good practice to see if there are vectorized functions
available for wherever a loop or an `apply` function is being used.

http://bioconductor.org/developers/how-to/efficient-code/

Pay close attention to the places where nested loops are used.

* You can use `seq_len(numiter)` instead of just `seq`. Change this
  whereever you have used it in your `for` loops, or similar
  constructs.
  
* Never set options directly like this because it's hard to know what
  the users initial option was in the workspace. Instead, save the old
  option and reset it to the old option on exit.

	
		options(warn = -1)
        ...
		options(warn = 0)

 vs

		oopt <- options(warn = -1)
		on.exit(options(oopt))
  

* Instead of `print` if you want to print to stdout, please use
  `message`. When using `message` you don't have to use `paste` within
  it anymore unless you want to recycle the message with a vector. Do
  this everywhere.
  
  http://bioconductor.org/developers/how-to/coding-style/
  
```
**End-User messages**

message() communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.

warning() communicates unusual situations handled by your code.

stop() indicates an error condition.

cat() or print() are used only when displaying an object to the user, e.g., in a show method.
```
  
  Follow the instructions in the coding style
  
### `MBImpute.R`

* Similar to `rowMins`, look at `rowMeans` as well in matrixStats or other packages.

* In this loop, you can reduce the number of times `unique` is being
  called on `treatment` by taking it out of the nested for-loop. I'm
  not convinced this nested loop is needed and this whole operation
  can be vectorized.


  l360-l366
  
		colnames(n.present) = unique(treatment)
		for(i in seq(1,n.peptide)) {
		  for(j in seq(1,n.u.treatment)) {
			  n.present[i,j] = sum(!is.na(y[peptide==i &
                                          treatment==unique(treatment)[j]]))
									  }
		}
  

Vectorize your code as much as possible to make it run faster. This
particular format of using nested loops happens through out.

* Consider also reindenting your code to follow the `coding-style` document.


* Similar issues, as above, in `gtest.R` which can be vectorized. Take
  a look at all the `apply` and for-loops throughout your code base
  and vectorize.
  

* This is not required, `loadRequiredLibs.R`. You can add them to your
  DESCRIPTION file and have your package import them in the NAMESPACE
  as needed.
  
* Please check out the `@import` and `@importFrom` in in roxygen2. You
   can take advantage of this and clear up your code of all the
   `<package_name>::<function_name>` calls. Just use `<function_name>`
   unless there is a conflict.
   
Once you have fixed the issues highlighted here, please post a detailed response of all the fixes. I'll do a secondary review once the you have posted your response.

**Comment by YuliyaLab** [comment] 2018-07-23 22:08
Hi, 
many thanks for the suggestions, all very good ones! 
Both developers are currently on the 2-week leave, is it OK if we submit the updates as soon as we return? It will take a bit over 2 weeks of turn around time. 
Thank you!

**Comment by nturaga** [comment] 2018-08-09 13:55
Hi @YuliyaLab ,

Please let me know any updates, if your colleagues are back for development or you need more time?

Best,

Nitesh

**Comment by YuliyaLab** [comment] 2018-08-10 13:17
Hi, yes, we will be working on the package this upcoming week!

**Comment by lshep** [comment] 2018-08-23 11:38
Is there another update on when we might expect changes?  If updates are not pushed soon we will temporarily close the issue for inactivity until you have time to work on it.

**Comment by YuliyaLab** [comment] 2018-08-30 07:01
Hi, yes! Will be doing an update in a few days! Thank you for checking!

**Comment by YuliyaLab** [comment] 2018-08-30 07:12
Hi,
I do have a question, one of the suggestions for the code you made is to
use rowMins() from a library

"You can use rowMins or colMins (fromlibrary(matrixStats))"

This gets into introducing additional dependencies vs using a built-in
function. Do you strongly prefer to include an additional library
dependency over the use of apply?

Thank you,
Yuliya

**Comment by lshep** [comment] 2018-08-31 11:03
It depends on how big of a matrix you are performing the action over.  matrixStats is a very stable package and while it would be an added dependency would greatly improve the performance over an apply if the matrix is medium to extremely large.  If you don't care about performance or speed up than maybe it isn't necessary.   Keep in mind to while the package needs to be available as a dependency you can use the importFrom to only import the functions you need when utilizing your package.  We would still recommend using the built in functions but it is your call.

**Comment by lshep** [comment] 2018-09-07 12:45
If there are no changes by monday we will close the issue for inactivity. We require maintainers to be an active part of the process. Our review with suggested changes occurred on July 12 and there has been no updates since.  We generally close issues after a 2-3 week period of activity but have left it open with promises of updates -  if the issue is closed you may request the issue be reopened when you have time to actively participate in the process.

**Comment by nturaga** [comment] 2018-09-12 12:14
Hi @YuliyaLab Once you are ready for a review. Please leave a detailed response with the changes you have made so it is easier for me to go through.

Best,

Nitesh

**Comment by YuliyaLab** [comment] 2018-09-12 12:30
Hi Nitesh,
we have gone over the suggested changes and addressed all of them.
Vectorization suggestions were very useful!
Thank you,
Yuliya

**Comment by nturaga** [comment] 2018-09-28 16:13
## Update

* Format the DESCRIPTION file properly.

* Remove commented out lines of code.

* The way you handle options is still not correctly done in EigenMS.R,
  please fix it as per the solution given in the previous review.

* The set of optimizations I've recommended in EigenMS.R in my first
  review apply to all your code. After reviewing your code again, I've
  noticed that in MBImpute.R, there are `apply` functions instead of
  using optimized functions from `matrixStats`. Please make sure all
  these corrections are done across all of the code.

* In TwoPart_MultiMS.R, I don't think importing `dplyr` for one mutate
  call is necessary. It will limit your package.

        plotdata = dplyr::mutate(plotdata, log_PV=-log10(PV))

    to

        plotdata$log_PV = -log10(plotdata$PV)


   Don't introduce package dependencies for functions which can be
   done easily in base R. If you intend to use dplyr for all the
   tibble, data.frame etc manipulations, then you should go ahead an
   import dplyr. But that is not the case at the moment.

* `print` statment is used to display a diagnostic message in
  TwoPart_MultiMS.R. Please check my earlier review about "End user
  messages" and make sure the format is followed thorugh out all of
  you code files.

* `g.test.R` has no optimizations made. The review suggestions were
  not implemented from earlier. Please remove the apply statments, and
  use the `matrixStats` package across all your codebase, not just
  this one file.

Please respond to each point individually in the previous review and
in the current updated review. If there is a point in the review you
do not agree with you must justify it. Once the point-by-point update
is submitted, i'll review the package again. The review previously given was not fully implemented.

**Comment by YuliyaLab** [comment] 2018-09-29 03:47
Hi, thank you,
we thought we fixed the 'options' problem, but will go over the code to
make sure all instances of us using it are taken care off.
Thank you,
Yuliya

**Comment by YuliyaLab** [comment] 2018-10-18 01:03
Hi, yes, ready for the review!
We included our point-by-point response into the commit changes description
as we were not clear where you wanted them.
Below is a copy of the response we did for each of the comments.
Thank you,
Yuliya

------------------------------
September update:
------------------------------
(1) Format the DESCRIPTION file properly.
Rearranged the filed order and removed:
Type: Package
Arranged as per the Bioconductor guidelines.

(2) Remove commented out lines of code.
Removed commented non-vectorised code

EigenMS:
# vectorized option, use instead of the for-loop bellow
nobs = matrixStats::rowSums2(!is.na(pres))
# for (ii in seq_len(numiter) ) {
#  nobs[ii] = sum(!is.na(pres[ii,]))
# }

MBImpute
g.test

# for (i in seq_len(nrows)) { row.tot <- row.tot + 1/(sum(x[i,])) }
      row.tot = sum( 1 / (rowSums(x) ) )

g = 0
    # for (i in seq_len(length(x)) ) {
    #  if (x[i] != 0) g <- g + x[i] * log(x[i]/E[i])
    # } # vectorized code for the above loop!
    ppos = x != 0
    g = sum(x[ppos] * log(x[ppos]/E[ppos]))

peptideLevel_DE:
# graphics::par(mar=c(3,3,3,3))

TwoPart_MultiMat.R:
# graphics::par(mar=c(3,3,3,3))
Also all other commented out code and examples outside of the MAN


(3) The way you handle options is still not correctly done in EigenMS.R,
please fix it as per the solution given in the previous review.
Replaced the incorrect lines using options below
## oopt = options(warn = -1)    # lines 374, 375 & 558, 559
## on.exit(options(oopt)) # on exit will return to the use set parameters
 with:
oopt <- options()
on.exit(options(oopt)) # on exit will return to the use set parameters
options(warn = -1)


(4) The set of optimizations I've recommended in EigenMS.R in my first
review apply to all your code. After reviewing your code again, I've
noticed that in MBImpute.R, there are apply functions instead of
using optimized functions from matrixStats. Please make sure all
these corrections are done across all of the code.

Replaced the use of apply() in min and mean computations in MBImpute.R


(5) In TwoPart_MultiMS.R, I don't think importing dplyr for one mutate
call is necessary. It will limit your package.
  plotdata = dplyr::mutate(plotdata, log_PV=-log10(PV))
to
  plotdata$log_PV = -log10(plotdata$PV)
Don't introduce package dependencies for functions which can be
done easily in base R. If you intend to use dplyr for all the
tibble, data.frame etc manipulations, then you should go ahead an
import dplyr. But that is not the case at the moment.

Good point, eliminated the dependancy on for the dplyr package only to use
1 function!
removed dplyr from the list if imported packages in DESCRIPTION.
Removed from NAMESPACE:
importFrom(dplyr,filter)
importFrom(dplyr,mutate)

(6)  print statment is used to display a diagnostic message in
TwoPart_MultiMS.R. Please check my earlier review about "End user
messages" and make sure the format is followed thorugh out all of
you code files.

Replaced all print() statements with message() statements.


(7) g.test.R has no optimizations made. The review suggestions were
not implemented from earlier. Please remove the apply statments, and
use the matrixStats package across all your codebase, not just
this one file.

Replaces apply with rowSums2() and colSums2().


------------------------------
Previous review - *response*
------------------------------
(1) Fix these INSTALL artifacts, R CMD INSTALL ProteoMM_0.99.4.tar.gz
Fixed

Removed use_package statements that were giving issues from
loadRequiredLibs.R:
# devtools::use_package("gdata")
# devtools::use_package("ggplot2")
# devtools::use_package("multtest")
# devtools::use_package("readr")
# devtools::use_package("ggrepel")
# devtools::use_package("gtools")


vignettes

   - Give your vignette a more appropriate name.
   - No need to have the html file, as the build system will run
   the vignette and generate the html file.
   - Vignette is looks unstructured, use BiocStyle for better
   formatting
   https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html.

http://bioconductor.org/developers/package-guidelines/#vignettes

Updated to use BiocStyle, changed the name.

We include some of the tutorial style output in our Vignette, we would like
those sections to remain such that users can reproduce the findings.

REigenMS.R — ignoring item 2 for matrixStats library!! Avoid dependance!

   - You don't need to use which here, it creates a logical vector
   which can be used as indices.
     present = prot.info[which(!prot.info[,1] %in% rownames(pmiss)), ]
   #rownames OK
     pres = m[which(!prot.info[,1] %in% rownames(pmiss)), ]
     rownames(pres) = prot.info[which(!prot.info[,1] %in%
   rownames(pmiss)),1]

Changed to not use which.


   - You can use rowMins or colMins (fromlibrary(matrixStats))
   instead of
     present.min = apply(nobs, 1, min) # number present in each group


Changed to use matrixStats package.

Pay close attention to the places where nested loops are used.

   - You can use seq_len(numiter) instead of just seq. Change this
   whereever you have used it in your for loops, or similar
   constructs.

Changed to use seq_len().


   - Never set options directly like this because it's hard to know what

the users initial option was in the workspace. Instead, save the old
option and reset it to the old option on exit.
  options(warn = -1)
  ...
  options(warn = 0)
vs
    oopt <- options(warn = -1)
       on.exit(options(oopt))

Updated code to use options correctly.


   - Instead of print if you want to print to stdout, please use
   message. When using message you don't have to use paste within
   it anymore unless you want to recycle the message with a vector. Do
   this everywhere.
   http://bioconductor.org/developers/how-to/coding-style/


Made changes to how we use:
- matrixStats - we replaced our apply's with functions from matrixStats
- options()
- message() instead of print() in all functions.

MBImpute.R — Do matrixStats!!! in 2 functions!!

   - Similar to rowMins, look at rowMeans as well in matrixStats or other
   packages.
   - In this loop, you can reduce the number of times unique is being

called on treatment by taking it out of the nested for-loop. I'm
not convinced this nested loop is needed and this whole operation
can be vectorized.
l360-l366
  colnames(n.present) = unique(treatment)
  for(i in seq(1,n.peptide)) {
   for(j in seq(1,n.u.treatment)) {
         n.present[i,j] = sum(!is.na(y[peptide==i &
                                   treatment==unique(treatment)[j]]))
                                                         }
  }
Vectorize your code as much as possible to make it run faster. This
particular format of using nested loops happens through out.

We now use matrixStats and vectorised the code as suggested in 2 bulleted
items above.


   - Consider also reindenting your code to follow the coding-style
   document.


Sadly, we failed to identify a way in RStudio to automatically indent
lines.
Our RStudio setting are exactly what is required by the tabs are not
replaced
by RStudio with 2 spaces. Please advice if we can have the spacing as it
is.



   - Similar issues, as above, in gtest.R which can be vectorized. Take
   a look at all the apply and for-loops throughout your code base
   and vectorized.


           Vectorized!

   - This is not required, loadRequiredLibs.R. You can add them to your
   DESCRIPTION file and have your package import them in the NAMESPACE
   as needed.


          Updated our current DESCRIPTION file, eliminated
loadRequiredLibs.R file.


   - Please check out the @import and @importFrom in in roxygen2. You

can take advantage of this and clear up your code of all the
<package_name>::<function_name> calls. Just use <function_name>
unless there is a conflict.
Once you have fixed the issues highlighted here, please post a detailed
response of all the fixes. I'll do a secondary review once the you have
posted your response.

We have updated our code as per Bioconductor’s advice to
use <package_name>::<function_name>. To eliminate any issues we updated all
functions we use for clarity. We decided to always use
<package_name>::<function_name>
unless we are using base R functions to eliminate any future conflicts as
we will be developing the package further.

**Comment by nturaga** [comment] 2018-10-22 15:21
@YuliyaLab 

Package looks good, but there seems to be one lagging NOTE in the build report.


```
* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 1 object(s) are initialized. Maybe
      it is part of a data set loaded with data(), or perhaps part of
      an object referenced in with() or within().
    function (object)
      plot_volcano_wLab (log_PV)
```

You can fix your code, and check the same on your local machine with CRAN checks

```
R CMD build ProteoMM

R CMD check ProteoMM_version.tar.gz
```

and then, use `BiocCheck`

try 

```
> BiocCheck::BiocCheck("ProteoMM")
```

```
This is BiocCheck version 1.17.24. BiocCheck is a work in progress.
Output and severity of issues may change. Installing package...
* Checking if other packages can import this one...
* Checking to see if we understand object initialization...
    * NOTE: Consider clarifying how 1 object(s) are initialized. Maybe
      it is part of a data set loaded with data(), or perhaps part of
      an object referenced in with() or within().
    function (object)
      plot_volcano_wLab (log_PV)
```

Please fix this, and I can go forward and accept the package. 

Thanks,

Nitesh

**Comment by YuliyaLab** [comment] 2018-10-23 13:32
Hi Nitesh,
we fixed the log_PV initialization note/issue and pushed changed to GitHub
with the bumped version. Please let us know if there are any other issues.
Thank you,
Yuliya

**Comment by mtmorgan** [comment] 2018-10-23 16:08
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/YuliyaLab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install(\"ProteoMM\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ProteoMM

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-10-23 16:08 UTC
Labels: 3a. accepted, OK
