### ISSUE TITLE
scry

### ISSUE THREAD

**Issue by kstreet13** [Bioconductor/Contributions#1422] opened 2020-03-17 19:05 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kstreet13/scry

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kstreet13** [comment] 2020-03-18 16:14
Hi @lshep,

Sorry if this is common problem, but I've pushed a few new updates today (along with version bumps) and they seem to be getting picked up by the webhook (which shows several new, successful deliveries), but not triggering any new builds. Am I missing something? One of them did fail on TravisCI, if that has any impact on the webhook or single package builder.

Thanks,
Kelly

**Comment by lshep** [comment] 2020-03-19 12:54
Sorry for the delay.  That is odd and the single package builder does seem to be running as normal.  For now I'll kick off a manual build which should post shortly.   I might suggest deleting and re-establishing the webhook just to make sure it is linking properly.  If  you continue to have issues then please reach out and we can investigate more.

**Comment by lshep** [comment] 2020-03-20 14:35
Please subscribe to the mailing list.  I will have a review of your package in the next week or so.

**Comment by kstreet13** [comment] 2020-03-20 15:06
As far as I know, @willtownes signed up for the mailing list on Tuesday, but has yet to receive a confirmation.

**Comment by willtownes** [comment] 2020-03-20 15:36
Sorry to all, I just found the confirmation email in my spam box. I am now confirmed!

**Comment by kstreet13** [comment] 2020-03-20 16:17
Ok, I pushed a new update and it looks like we're still having issues with the webhook (I deleted and re-added as suggeted).

**Comment by kstreet13** [comment] 2020-03-24 15:10
@lshep, it seems like the webhook is working (at least from my end), but it's still not triggering new builds... I did as you suggested and deleted and re-established the webhook. Is there something else we should try?
<img width="768" alt="Screen Shot 2020-03-24 at 11 07 30 AM" src="https://user-images.githubusercontent.com/11052277/77441421-cc2e7800-6dbf-11ea-8ab8-7bbcb7d9a8bd.png">

**Comment by lshep** [comment] 2020-03-24 17:57
The automatic hook is working for everyone else so it has to be a specialized case.  In the meantime let me know when you want a manual rebuild (I handle this too so luckily it works out as your reviewer too).  I'll try to investigate more and see if i can find anything in the logs to try and get it straightened out. I just kicked off a manual build so you should have a report shortly

**Comment by lshep** [comment] 2020-03-24 18:03
How are you making the commits to your repository?  I see things like "Kelly Street authored and Kelly Street committed"  on your repository where on others its the "<github id> committed"

**Comment by kstreet13** [comment] 2020-03-26 14:24
I'm not sure what the other options are (sorry, I'm definitely not a git expert), but I use the terminal for all git commands. We've been making changes on the `develop` branch, pushing, and testing those before merging them into `master`.

And there is one other webhook set up for code coverage (codecov.io) and it seems to be functioning properly.

**Comment by lshep** [comment] 2020-03-26 16:46
Could you try do a version bump directly on the master branch instead of merging one in to see if that triggers a build report? Regardless -- I'm in the process of reviewing your package now and should have more feedback later today - tomorrow at the latest. 
Cheers

**Comment by lshep** [comment] 2020-03-26 19:17
So that seems to be the key

**Comment by kstreet13** [comment] 2020-03-26 19:27
ok, cool! Any idea why that works but merging doesn't?

**Comment by lshep** [comment] 2020-03-26 19:33
Not off hand;  but thank you this is helpful for me to look into our backend to see if its an issue with webhooks in general or our underlying code.   Still working on the review so most likely tomorrow morning. 
Cheers

**Comment by lshep** [comment] 2020-03-27 15:49
**General**

- [ ] Find a biological relevant real example dataset; See Experiment Data
  packages or ExperimentHub. 

- [ ] It seems like you recode already existing statistical methods. Why not import from existing packages? 


**DESCRIPTION**
- [ ] The Description in the Description should be like an abstract. The current
one is too short and potential users will not understand what "Irizarry lab"
is.  Describe what type of methods and for what type of data. 

**vignette**

- [ ] I suggest including another vignette "scry.Rmd" as it is intuitive for a
user to do `vignette(scry)`.  This vignette could simply summarize what
inforamtion would be covered in the other two vigenttes. 

- [ ] In both vignettes there is a large amount of setup and definition even
  before a user would utilize your function.  How is this saving the user any
  amount of time? 

_dimensionReduction_

- [ ] Why is there a random function defined at the start of the vignette?
  Shoud this not be encoded and included for distribution? 

- [ ] Why not find example data of biological signficance? I'm sure there might
  be relevant data or datasets in an exisitng Experiment Data package or the
  ExperimentHub to demonstrate with real data.



**R code / man pages**

_AllHelperFunctions_

- [ ] fam can only be two options.  This information should be included in the
  description of the argument. 

- [ ] Misleading if you say AllHelperfunctions and then the first thing I see
  when I open featureSelection is the top section of helper functions. 


_featureSelection_

- [ ] Why do you re-event statistical methods that are already implemented? poisson
  and bionomial evaluation are pretty well known and standard methods, I would
  assume these functions exist in a basic stat package. 


Please address the above issue and when ready do a version bump (on the master branch) to trigger a new build report. Please comment you are ready for a re-review and summarize changes or respond to questions above.  

Cheers,

**Comment by lshep** [comment] 2020-04-13 15:00
Hello.  Any updates and comments from the above review?

**Comment by lshep** [comment] 2020-04-16 13:52
Please remember the package must be re-reviewed and accepted by April 22 to be included in the 3.11 release. Else it will remain in devel until the Fall release of bioc 3.12

**Comment by kstreet13** [comment] 2020-04-16 14:25
Hey, sorry! We've been busy with other things lately, but we are working on updates and will hopefully have a new version for review soon.

**Comment by willtownes** [comment] 2020-04-22 00:18
@lshep thanks for the helpful suggestions and we apologize for the delay. We now have an updated version on master branch that should address all of your concerns. 

### General

- [x] Find a biological relevant real example dataset; See Experiment Data
packages or ExperimentHub. *We now include real data from DuoClustering2018.*

- [x] It seems like you recode already existing statistical methods. Why not import from existing packages? *We had to recode these methods because the computation in the original implementation was too slow.*

### DESCRIPTION

- [x] The Description in the Description should be like an abstract. The current
one is too short and potential users will not understand what "Irizarry lab"
is. Describe what type of methods and for what type of data. *We have now updated the description to be more informative. We also modified the title of the package to no longer refer to "Rafalab".*

### vignette

- [x] I suggest including another vignette "scry.Rmd" as it is intuitive for a
user to do vignette(scry). This vignette could simply summarize what
inforamtion would be covered in the other two vigenttes. *This vignette is now included.*

- [x] In both vignettes there is a large amount of setup and definition even
before a user would utilize your function. How is this saving the user any
amount of time? *We have now replaced these two vignettes with the simplified scry vignette.*

#### dimensionReduction

- [x] Why is there a random function defined at the start of the vignette?
Shoud this not be encoded and included for distribution? *We have now removed this vignette and replaced with the simplified scry one.*

- [x] Why not find example data of biological signficance? I'm sure there might
be relevant data or datasets in an exisitng Experiment Data package or the
ExperimentHub to demonstrate with real data. *We now include data from DuoClustering2018 in the scry vignette.*

### R code / man pages

#### AllHelperFunctions

- [x] fam can only be two options. This information should be included in the
description of the argument. *We have now updated the documentation to include this.*

- [x] Misleading if you say AllHelperfunctions and then the first thing I see
when I open featureSelection is the top section of helper functions. *We have now renamed AllHelperfunctions to utils.R, to emphasize that it doesn't include all of the helper functions.*

#### featureSelection

- [x] Why do you re-event statistical methods that are already implemented? poisson
and bionomial evaluation are pretty well known and standard methods, I would
assume these functions exist in a basic stat package. *It's true that the deviance can be computed using eg the glm function from base stats. However, this function always runs iterative Fisher scoring which is unnecessary computation given that our estimators are a special case that has a closed-form solution. We couldn't find an existing package with these estimators implemented in the computationally efficient form, so we just went ahead and did our own implementation.*

**Comment by lshep** [comment] 2020-04-22 12:24
This looks good. Thank you for updating the vignette especially. I think it reads much easier and now shows the strong connection with the Bioconductor SCE class.   

One minor note that you should try and fix before the release.  The news.md is still formatted slightly incorrect.  You can not have any plain text.  You will need to have a list element identifier (either + or -) in front of `Intiail release of the ...`  or since it is in markdown you might also be able to use subheaders (###) but I would recommend the + or - .   

I'll accept despite the news formatting issue since this is minor.  

Cheers,

**Comment by kstreet13** [comment] 2020-04-22 16:08
Thanks very much! I have made the change to the NEWS file that you requested. Sorry again for the delay, we appreciate all your help!

**Comment by mtmorgan** [comment] 2020-04-22 19:04
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kstreet13.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scry")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scry

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-22 19:04 UTC
Labels: 3a. accepted, OK
