### ISSUE TITLE
CoSIAdata

### ISSUE THREAD

**Issue by adc0032** [Bioconductor/Contributions#2951] opened 2023-03-13 20:00 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/lasseignelab/CoSIAdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by adc0032** [comment] 2023-03-27 22:50
AdditionalPackage: https://github.com/lasseignelab/CoSIA

**Comment by Kayla-Morrell** [comment] 2023-04-10 14:19
Hello @adc0032 - Thank you for submitting to _Bioconductor_. Please see the initial review of
**CoSIAdata** below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.
Keep in mind that the deadline to accept new packages into the Bioconductor 3.17
release is 4/19. Any packages accepted after this date will be included in the
next release.

## DESCRIPTION

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field that
  includes the relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an
  entire package. 
- [ ] REQUIRED: `.onLoad` is an internal function and should not be exported.
  Generally data packages do not export any functions.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section that demonstrates to
  the user how to download and load the package from Bioconductor. These
instructions should be included in an `eval = FALSE` code chunk.

## Man pages

- [ ] REQUIRED: Since `.onLoad()` is an internal function you do not need a man
  page for it. If you want to keep it I would suggest adding an internal tag to
the documentation.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  https://contributions.bioconductor.org/tests.html

## R code

- [ ] SUGGESITON: For formating reasons, consider shorter lines. There are 7 
lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for 
line indents. There are  4 lines that are not.

Best,
Kayla

**Comment by adc0032** [comment] 2023-04-11 16:01
Hi @Kayla-Morrell,
Could I get some guidance with updating the package on the Bioc end?
I am getting access issues when trying to push to upstream:devel

```{bash}
rstudio@37cae6206cbf:~/CoSIAdata$ git remote -v
origin  https://github.com/lasseignelab/CoSIAdata.git (fetch)
origin  https://github.com/lasseignelab/CoSIAdata.git (push)
upstream        git@git.bioconductor.org:packages/CoSIAdata.git (fetch)
upstream        git@git.bioconductor.org:packages/CoSIAdata.git (push)
```

```{bash}
rstudio@37cae6206cbf:~/CoSIAdata$ git fetch --all
Fetching origin
Fetching upstream
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream
```

I checked my SSH keys on credentials and everything looks fine.

**Comment by Kayla-Morrell** [comment] 2023-04-11 16:09
@lshep - Would you be able to help with this issue?

**Comment by lshep** [comment] 2023-04-11 16:26
Everything looks correct on our end too. 
I would work through some of the scenarios at http://contributions.bioconductor.org/git-version-control.html#faq
Perhaps try    ssh -T -v git@git.bioconductor.org  to make sure its using the ssh key expected. 
If not I would try generating/adding a new key.

**Comment by adc0032** [comment] 2023-04-11 17:14
> Everything looks correct on our end too. I would work through some of the scenarios at http://contributions.bioconductor.org/git-version-control.html#faq Perhaps try ssh -T -v [git@git.bioconductor.org](mailto:git@git.bioconductor.org) to make sure its using the ssh key expected. If not I would try generating/adding a new key.

Thank you, @lshep !

**Comment by adc0032** [comment] 2023-04-11 18:52
Hi @Kayla-Morrell, thank you for your review. 
We have addressed Bioc package submission comments as follows:

> ## DESCRIPTION
> * [x]  SUGGESTION: We strongly encourage the use of the 'BugReports:' field that
>   includes the relevant link to GitHub for reporting Issues.
> *We have included a 'BugReport' field*
>
> ## NAMESPACE
> * [x]  SUGGESTION: Generally `importFrom()` is encouraged over importing an
>   entire package.
>  *We have update `import()` to `importFrom()`*
> * [x]  REQUIRED: `.onLoad` is an internal function and should not be exported.
>   Generally data packages do not export any functions.
>   *We are no longer exporting `.onLoad`* 
>
> ## Vignette
> * [x]  REQUIRED: There should be an 'Installation' section that demonstrates to
>   the user how to download and load the package from Bioconductor. These
>   instructions should be included in an `eval = FALSE` code chunk.
>  *We have updated our vignette with installation steps* 
>
> ## Man pages
> * [x]  REQUIRED: Since `.onLoad()` is an internal function you do not need a man
>   page for it. If you want to keep it I would suggest adding an internal tag to
>   the documentation.
>  *We have added an internal tag to `.onLoad()`*
>
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encourage them. See
>   https://contributions.bioconductor.org/tests.html
>  *we will add unit testing in a minor update and announce via NEWS*
>
> ## R code
> * [ ]  SUGGESITON: For formating reasons, consider shorter lines. There are 7
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for
>   line indents. There are  4 lines that are not.
> *We attempted to format all .R files to account for `roxygen` formatting during .Rd creation, however these lines did not meet the style suggestion once roxygenized. Please let us know if there are ways to configure `roxygen` to address this.*

**Comment by adc0032** [comment] 2023-04-12 16:16
Hi @lshep @Kayla-Morrell,
our file size issue is due to the CoSIA vignette htmls that includes large plotly output. All of the examples are non-trivial  (we think). Do you have a compromise on file size and demonstrating package utility?
[Reference build](https://github.com/Bioconductor/Contributions/issues/2951#issuecomment-1503799210)

**Comment by Kayla-Morrell** [comment] 2023-04-17 13:48
@adc0032 - I've reviewed the changes to CoSIAdata and everything looks good. As far as CoSIA goes, individual files must be under 5MB in size. I have a couple suggestions for decreasing the file size:

1. If you are working with a large dataset and that's what is causing the large plot, perhaps just plotting a subset of the data would help with the file size.
2. If you are demonstrating the use of a function that is tested else where (i.e., else where in the vignette, a runnable man page example, and/or a unit test) than perhaps you can include the large plot code in an `eval = FALSE` and include a static image of the plot. I'm not sure this would help a ton if the static image ends up being quite large.

Let me know if you need further help and I can see if the rest of the review team or the core team has any suggestions.

Best,
Kayla

**Comment by adc0032** [comment] 2023-04-17 20:28
@Kayla-Morrell  Thank you so much!
@lshep 
We've gotten things down to where it should be, but it required a history rewrite. Will you need to "re-clone" on your end for us to push upstream?

**Comment by adc0032** [comment] 2023-04-18 00:21
We're going to keep trying to get the R CMD check under 10 min, but it already is on our end using:
`devtools::check(vignette=FALSE)`
<img width="1227" alt="Screen Shot 2023-04-17 at 7 11 30 PM" src="https://user-images.githubusercontent.com/18667790/232637743-87ac9c0f-a11a-4d26-b4ea-1c6d6e009d1d.png">

**Comment by Kayla-Morrell** [comment] 2023-04-18 14:07
@adc0032 - Great work getting the build report cleaned up! I'll work on getting the review posted within the next couple hours.

**Comment by Kayla-Morrell** [comment] 2023-04-18 16:15
@adc0032 - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: The installation instructions in the README should also include
  Bioconductor installation instructions. See Bioconductor installation
instructions on any current Bioconductor package landing page. 
- [ ] REQUIRED: The 'Meta/' and 'doc/' directories are not usually things
  included in Bioconductor packages. Please remove them.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
	ThirdPartyClient, DataImport, GUI
- [ ] REQUIRED: If you plan to include the 'URL:' field than please provide a
  valid URL.

## Data

- [ ] REQUIRED: We require data present in `inst/extdata/` to be documented in
 an `inst/script/` directory. The script(s) in this directory can vary, but most
importantly it must clearly document how the data was generated and source
information. It should include source URLs and any key information regarding
filtering or processing. It can be executable code, sudo code, or a text
description. Users should be able to download and roughly reproduce the file or
object that is present as data.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encouarge them. See
  https://contributions.bioconductor.org/tests.html.

## R code

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 61
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
  indents. There are 68 lines that are not.

Best,
Kayla

**Comment by adc0032** [comment] 2023-04-18 20:13
@Kayla-Morrell Thank you so very much for helping us push through! We have addressed Bioc package submission comments as follows (Build in progress):
> 
> ## General package development
> * [x]  REQUIRED: The installation instructions in the README should also include
>   Bioconductor installation instructions. See Bioconductor installation
>   instructions on any current Bioconductor package landing page.
> *We have updated the instructions in the README for installing from Bioconductor*
>
> * [x]  REQUIRED: The 'Meta/' and 'doc/' directories are not usually things
>   included in Bioconductor packages. Please remove them.
>  *We have removed these two directories*
>
> ## DESCRIPTION
> * [x]  SUGGESTION: Consider adding these automatically suggested biocViews:
>   ThirdPartyClient, DataImport, GUI
> *We have added these suggested biocViews*
>
> * [x]  REQUIRED: If you plan to include the 'URL:' field than please provide a
>   valid URL.
>  *We have updated the URL*
>
> ## Data
> * [x]  REQUIRED: We require data present in `inst/extdata/` to be documented in
>   an `inst/script/` directory. The script(s) in this directory can vary, but most
>   importantly it must clearly document how the data was generated and source
>   information. It should include source URLs and any key information regarding
>   filtering or processing. It can be executable code, sudo code, or a text
>   description. Users should be able to download and roughly reproduce the file or
>   object that is present as data.
>  *We have moved the data download and formatting script from `R/` to `inst/script/`. We have updated the script to include how the data was obtained, including link.*
>
> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encouarge them. See
>   https://contributions.bioconductor.org/tests.html.
>  *We will add unit testing as a minor release and update in NEWS*
>
> ## R code
> * [ ]  SUGGESTION: For formating reasons, consider shorter lines. There are 61
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for line
>   indents. There are 68 lines that are not.
> *We have attempted to get the last 2% of these style formatting completed, however with roxygen modifications we cannot rid of these last few lines. Please let us know if reviewers have suggestions on configuring roxygen output.*

**Comment by Kayla-Morrell** [comment] 2023-04-19 17:08
@adc0032 - Thank you for making those necessary changes. I've looked everything over and all looks good. I'm more than happy to accept the packages.

Best,
Kayla

**Comment by adc0032** [comment] 2023-04-19 18:26
@Kayla-Morrell thank you so very much for your help to get CoSIA ready for Bioconductor. We appreciate you!

**Comment by lshep** [comment] 2023-04-20 13:59
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adc0032.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CoSIAdata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CoSIAdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment] 2023-04-20 13:59
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adc0032.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CoSIA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CoSIA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-04-20 13:59 UTC
Labels: OK, 3a. accepted

**Comment by adc0032** [comment] 2023-04-21 18:36
@lshep when I click the link for CoSIAdata, it sends me to the removed package page.
It also does not show up on the build list

**Comment by lshep** [comment] 2023-04-23 21:35
The schedule for the daily builds can be found on the [check results page](https://bioconductor.org/checkResults/). ExperimentData builds are built on Tue and Thur.  Likely the package was added to the manifest to late and miss the Thur build.  It would be available and found after a success run on the builder.
