### ISSUE TITLE
NewWave

### ISSUE THREAD

**Issue by fedeago** [Bioconductor/Contributions#1629] opened 2020-09-08 08:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository:  https://github.com/fedeago/NewWave

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Kayla-Morrell** [comment] 2020-09-25 17:41
Hello @fedeago -

Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: What is the purpose of the 'inst/function.R' file?

## DESCRIPTION

- [ ] REQUIRED: The 'Description:' field is made up by less than 3 sentences. 
Expand this field and structure it as a full paragraph.

- [ ] REQUIRED: The 'Depends:' field should be edited. This field is for 
packages that provide essential functionality. It is unusual for more than 3 
packages to be listed here. If they don't provide essential functionality, they 
should be moved to 'Imports:'.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
	- Sequencing, Coverage

## NEWS

- [ ] REQUIRED: The formating of the NEWS file is not correct. Please see the 
following link for help with this:
https://bioconductor.org/developers/package-guidelines/#news.

## Vignette

- [ ] REQUIRED: The vignette 'title:' field should be more informative.

- [ ] REQUIRED: I would remove lines 17-24 since you repeat the code immediately 
after and echo it to the user. 

- [ ] REQUIRED: There should be an 'Introduction' section that serves as an 
abstract to introduce the objective, models, unique fuctions, key points, etc. 
that distinguish the package from other packages of similar type. 

- [ ] REQUIRED: There should be an 'Installation' section that shows the user 
how to download the package from Bioconductor. The code should look like the 
following and include `eval = FALSE`.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("NewWave")
```

- [ ] SUGGESTION: We strongly encourage a table of contents.

- [ ] REQUIRED: The final section should be 'Session Information' and should 
include `sessionInfo()`.

## Man pages

- [ ] REQUIRED: Man pages are only needed for functions that are exported. For 
any function that is documented but not being exported you can add the 
`@keywords internal` tag to the documentation. This will remove the function 
from the documentation index.

## R code

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 27 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for 
line indents. There are 363 lines that are not.

Best,
Kayla

**Comment by fedeago** [comment] 2020-09-29 07:42
Hello @Kayla-Morrell 

Thank you for your precious observation.
In inst/function.R there are all the function needed by the cluster for the estimation. This is the only way we found to be sure that no other useless variable and library present in the global environment were duplicated across all cluster's nodes causing an increasing in memory consumption, this increase is especially visible foe small and medium data set.
 ## General package development
 
     * [x]  REQUIRED: What is the purpose of the 'inst/function.R' file?
 
 
 ## DESCRIPTION
 
     * [x]  REQUIRED: The 'Description:' field is made up by less than 3 sentences.
       Expand this field and structure it as a full paragraph.
 
     * [x]  REQUIRED: The 'Depends:' field should be edited. This field is for
       packages that provide essential functionality. It is unusual for more than 3
       packages to be listed here. If they don't provide essential functionality, they
       should be moved to 'Imports:'.
 
     * [x]  SUGGESTION: Consider adding these automatically suggested biocViews:
       
       * Sequencing, Coverage
 
 
 ## NEWS
 
     * [x]  REQUIRED: The formating of the NEWS file is not correct. Please see the
       following link for help with this:
       https://bioconductor.org/developers/package-guidelines/#news.
 
 
 ## Vignette
 
     * [x]  REQUIRED: The vignette 'title:' field should be more informative.
 
     * [x]  REQUIRED: I would remove lines 17-24 since you repeat the code immediately
       after and echo it to the user.
 
     * [x]  REQUIRED: There should be an 'Introduction' section that serves as an
       abstract to introduce the objective, models, unique functions, key points, etc.
       that distinguish the package from other packages of similar type.
 
     * [x]  REQUIRED: There should be an 'Installation' section that shows the user
       how to download the package from Bioconductor. The code should look like the
       following and include `eval = FALSE`.
 
 
 ```
 if(!requireNamespace("BiocManager", quietly = TRUE))
     install.packages("BiocManager")
 BiocManager::install("NewWave")
 ```
 
     * [x]  SUGGESTION: We strongly encourage a table of contents.
 
     * [x]  REQUIRED: The final section should be 'Session Information' and should
       include `sessionInfo()`.
 
 
 ## Man pages
 
     * [x]  REQUIRED: Man pages are only needed for functions that are exported. For
       any function that is documented but not being exported you can add the
       `@keywords internal` tag to the documentation. This will remove the function
       from the documentation index.
 
 
 ## R code
 
     * [ ]  SUGGESTION: For formating reasons, consider shorter lines. There are 27
       lines that are > 80 characters long.
 
     * [ ]  SUGGESTION: For formating reasons, consider multiples of 4 spaces for
       line indents. There are 363 lines that are not.

Best 
Federico

**Comment by mtmorgan** [comment] 2020-10-09 20:36
I don't think your analysis is correct with respect to serialization of objects in the global environment -- these are in general not serialized; instead you are seeing the cost of loading your package & dependencies on the workers. Have you investigated ways to reduce the dependency burden of your package? When you start the cluster, you could pay the one-time cost of loading your package, and then the overhead on subsequent calls would be minimal. Also, have you thought about choosing a more 'granular' parallelization strategy, where more work is done in each parallel call? This will be more efficient in general.

The basic problem with inst/script/*R files is that they are not checked at all, so that 'bit rot' can (and will!!) quickly set in.

**Comment by fedeago** [comment] 2020-10-12 15:05
Hi @mtmorgan ,

in my repository I created another branch called "BioconductorIssue" in which function.R is inside R folder and the functions are called by clusterApply using `NewWave:::`. Running this script:
```
library(splatter)
library(NewWave)

params <- newSplatParams()
N=1000
set.seed(1234)
data <- splatSimulateGroups(params,batchCells=c(N/2,N/2),
                            group.prob = rep(0.1,10),
                            de.prob = 0.2,
                            verbose = FALSE) 
set.seed(12359)
hvg <- rowVars(counts(data))
names(hvg) <- rownames(counts(data))
data <- data[names(sort(hvg,decreasing=TRUE))[1:1000],]
res2 <- newWave(data,X = "~Batch", K=10, children=10)
```
 with both version in my computer the new version without `inst/function.R` use near 500MB of memory for each job while the version with `inst/function.R` uses only 150MB for each job. I think that this is a big difference and this reduction of memory consumption make that file worth to be in that folder. Another option could be create a two package, one for the main job and one for the children jobs. In this case the child package depends only on base package while the main package depends on all actual packages plus this child package.

R and Bioconductor checks `inst/function.R` indirectly becouse the vignette could not run if one of these functions is broken.

Best,
Federico

**Comment by drisso** [comment] 2020-10-15 09:54
@mtmorgan @Kayla-Morrell,

we're experimenting with two solutions:

1. Creating a minimal package (to be submitted to CRAN) with just the heavy-lifting optimization functions and minimal dependencies. NewWave would depend on this new package and only the minimal package would be sent to the workers.
2. Creating a minimal environment in which to copy the needed functions from within the package and then exporting that minimal environment to the workers.

We can confirm that 1. works (see branch https://github.com/fedeago/NewWave/tree/TwoPack, new package at https://github.com/fedeago/deepwave), while we still need to implement and test 2.  However, solution 2 has the advantage of not creating an extra package.

We will get back to you once we have explored solution 2.

**Comment by mtmorgan** [comment] 2020-10-15 11:12
I mean to get to this today, but I was thinking that you could do
```
funs <- local({
    var1 <- ...
    list(
        fun1 = function(...) {},
        fun2 = function() {}
    )
}, env = .GlobalEnv)
```
although this is untested. I think a solution like this is better than a separate, minimal package. I think you would not need to export any environment; parallel evaluation of `funs$fun1` would send it's environment (including `var1`) to the worker.

**Comment by fedeago** [comment] 2020-10-19 12:16
@mtmorgan 

we try to use your solution but still uses to much RAM. In order to investigate the behavior of that implementation I created a R package that can be found in the repository `https://github.com/fedeago/RAMinvestigation`. It is a minimal implementation with a single function(`main(number_of_workers)`) that imports the package SummarizedExperiments, creates a cluster and than apply to that cluster a function defined as you suggested. You only need to choose the number of workers. Suddenly each workers use 400 MB of RAM, the weight of SummarizedExperiment. Do you have any other suggestion to overcome this problem?

**Comment by drisso** [comment] 2020-10-22 08:21
Hi @mtmorgan ,

the repo that @fedeago refers to in his post above is a minimal implementation of your suggestion. It still forces all the workers to load the dependency packages. Any chance you can have a look at the code and see if we're doing something obviously wrong? Otherwise, any suggestions on how to get past this?

Thanks!
Davide

**Comment by mtmorgan** [comment] 2020-10-22 20:17
The `local()` function needs to specify an environment outside the package namespace, e.g., 
```
funs <- local({
  list(
    example = function(k) {

      Sys.sleep(10)
    }
  )
}, envir = baseenv())
```

**Comment by fedeago** [comment] 2020-10-23 08:58
Hi @mtmorgan, thank you for these new details.

Suddenly these not change RAM consumption of each single worker, they continue to use 400 MB of RAM, the weight of SummarizedExperiment. 

We have two implementations working, the original one with `inst\functions.R' and the second one with a package in CRAN for those functions. Is possible to have one of these approved? Which one do you consider more worthy?

Thanks
Federico

**Comment by mtmorgan** [comment] 2020-10-23 10:11
Use the original approach in inst/functions.R

**Comment by drisso** [comment] 2020-10-23 10:19
Thanks @mtmorgan 

if you agree to accept the package with the original inst/functions.R approach, we commit to keeping exploring a better solution for a second version of the package.

It looks like this is not a straightforward things to solve, but it may be worth finding a general solution that could be implemented by the large-scale packages to keep the RAM consumption low.

**Comment by mtmorgan** [comment] 2020-10-23 10:24
But how are you measuring memory use? I was installing the package using base R tools (`R CMD INSTALL .`) and base R in a console (`R -e "RAMinvestigation::main(10)"`. I was looking at memory consumption with the Mac's 'Activity Monitor'. I created a pull request to make sure that we are using the same code.

**Comment by fedeago** [comment] 2020-10-23 10:26
I measured it looking at the `htop` of my linux machine. If you need a more detailed measure I can provide it.

**Comment by mtmorgan** [comment] 2020-10-23 10:32
I tweaked my previous comment with a little more detail; I'll run on the bioconductor/bioconductor_docker:devel image to see if we can't get to a consistent interpretation.

**Comment by mtmorgan** [comment] 2020-10-23 11:14
I updated and ran the bioconductor docker image

```
docker pull bioconductor/bioconductor_docker:devel
docker run -it --rm bioconductor/bioconductor_docker:devel bash
```
I started an R session and installed SummarizedExperiment and the repos
```
# R
> BiocManager::install("SummarizedExperiment")
> BiocManager::install("fedeago/RAMinvestigation")
```
From my host system I started another terminal and attached to the running docker image, and started `top`
```
docker ps  # showed the 'names' of the image as happy_nash
docker exec -it happy_nash bash
## root@d0f4b4d8d792:/# top
```
Back in the original terminal and R I ran
```
> RAMinvestigation::main(3)
```
and in top I saw the processes consuming ~ 65 MB rather than 448 MB.

Can you reproduce this?

**Comment by fedeago** [comment] 2020-10-23 11:37
Yes, you are right.

I will investigate why in my machine there is this inflation in RAM consumption using the last version of `RAM investigation` and then I will modify `NewWave` accordingly.
Thank you for yours suggestion and your help in debugging.

Best regards,
Federico

**Comment by Kayla-Morrell** [comment] 2020-10-23 13:18
After discussion with @mtmorgan we are going to go ahead and accept the package. Thank you for your contribution!

Best,
Kayla

**Comment by mtmorgan** [comment] 2020-10-23 17:18
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fedeago.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NewWave")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NewWave

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-10-23 17:18 UTC
Labels: 3a. accepted, OK
