### ISSUE TITLE
FastqCleaner

### ISSUE THREAD

**Issue by leandroroser** [Bioconductor/Contributions#650] opened 2018-02-13 07:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/leandroroser/FastqCleaner

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by leandroroser** [comment] 2018-02-23 22:32
Dear @nturaga,

Do I need to do anything else before the review process?
Thank you!

  Leandro

**Comment by nturaga** [comment] 2018-03-08 18:40
Hi @leandroroser

I will review your package within the next few days and post a review.

**Comment by nturaga** [comment] 2018-04-02 13:55
FastqCleaner review
===================

## R CMD build 

* Ok

## R CMD INSTALL 

* Ok


## DESCRIPTION

* You need more for the Description. Think of this as a paper
  abstract. Add what kind of diagnostics are provided by the tool.

* You don't need Authors@R and Author + Maintainer. Just keep Authors@R.

## NAMESPACE

* ok.

## Vignette

* You suggest using BiocStyle, but don't apply the style to your
  vignette. It seems to be commented out for some reason. Please fix.

* Vignette doesn't load images.

## R 

* Your file should be lowercase zzz.R just to conform to standards.
  It prints out a line "Overview help('FastqCleaner')", which fails.
  You should remove this.
  
  ```
  > help('FastqCleaner')
  No documentation for 'FastqCleaner' in specified packages and libraries:
  you could try '??FastqCleaner'
  ```
  
  This entire zzz.R seems unecessary.

* First look at your build report, there are NOTE sections you need to
  correct, most important is changing the sapply to vapply and then
  correcting the 1:length loops to use seq_len or seq_along

  http://bioconductor.org/spb_reports/FastqCleaner_buildreport_20180223163657.html

	```
	* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply() found in files:
    plotObjects.R (line 145, column 22)
    plotObjects.R (line 169, column 13)
    plotObjects.R (line 171, column 15)
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
    auxiliar.R (line 77, column 42)
    plotObjects.R (line 100, column 13)
    plotObjects.R (line 117, column 43)
    plotObjects.R (line 168, column 12)
    plotObjects.R (line 185, column 20)
    plotObjects.R (line 241, column 14)
    plotObjects.R (line 308, column 51)
    plotObjects.R (line 582, column 34)

	```
	
* More NOTE's 

	```
	 * NOTE: Consider shorter lines; 390 lines (7%) are > 80 characters
      long.
    First 6 lines:
      R/adapter_filter.R:4 #' @param Lpattern 5' pattern (character or \code{...
      R/adapter_filter.R:5 #' @param Rpattern 3' pattern (character or \code{...
      R/adapter_filter.R:15 #' @param with_indels allow indels? This is avail...
      R/adapter_filter.R:16 #' @param anchored Adapter or partial adapter wit...
      R/adapter_filter.R:18 #' @param fixed Parameter passed to \code{\link[B...
      R/adapter_filter.R:19 #' or \code{\link[Biostrings:lowlevel-matching]{i...
    * NOTE: Consider 4 spaces instead of tabs; 1 lines (0%) contain
      tabs.
    First 1 lines:
      R/plotObjects.R:183   names(reldiv) <- 1:length(reldiv)	
    * NOTE: Consider multiples of 4 spaces for line indents, 1003
      lines(18%) are not.
    First 6 lines:
      R/adapter_filter.R:86                            method = c("exact", "e...
      R/adapter_filter.R:87                            first = c("R", "L"), w...
      R/adapter_filter.R:88                            anchored = TRUE, fixed...
      R/adapter_filter.R:89                            checks = TRUE, ...) {
      R/adapter_filter.R:90   
      R/adapter_filter.R:91   method <- match.arg(method)

	```

See http://bioconductor.org/developers/how-to/coding-style/

* Reformat your code, to make it more readable. Use `formatR` package
  if needed, or RStudio's code-indenting.

	example:
	
	```
	-
	-    outFormats <- list(A = list(x = "Sanger", y = 1, q = 33, range = "[33 - 73]"),
	-        B = list(x = "Illumina 1.8+", y = 2, q = 33, range = "[33; 74]"), C = list(x = "Illumina 1.5+",
	-            y = 3, q = 64, range = "[66; 104]"), D = list(x = "Illumina 1.3+", y = 4,
	-            q = 64, range = "[64; 104]"), E = list(x = "Solexa", y = 5, q = 64, range = "[59; 104]"))
	-
	+
	+    outFormats <- list(A = list(x = "Sanger", y = 1, q = 33, range = "[33 - 73]"),
	+                       B = list(x = "Illumina 1.8+", y = 2, q = 33, range = "[33; 74]"),
	+                       C = list(x = "Illumina 1.5+",
	+                                y = 3, q = 64, range = "[66; 104]"),
	+                       D = list(x = "Illumina 1.3+", y = 4, q = 64, range = "[64; 104]"),
	+                       åE = list(x = "Solexa", y = 5, q = 64, range = "[59; 104]"))
	+
	```


* In complex_filter.R, you might want to explain some of the magic
  numbers to your users, why is the referenceEntropy default to that
  number?
  
  ```
  #' @param referenceEntropy reference entropy. Default 3.908135
  ```

* You have loops which are hardcoded, `for(i in 1:11)` in
  plotObjects.R. Even in plotting functions, this is bad practice.
  
  
* remove commented out code.

**Comment by nturaga** [comment] 2018-04-05 13:34
@leandroroser Please issue a version bump, when you make changes to get a new build report.

**Comment by leandroroser** [comment] 2018-04-05 18:29
Thank you for the review @nturaga. I will be working on the improvements.

**Comment by nturaga** [comment] 2018-04-18 21:46
@leandroroser Let me know when you are ready for another review after posting your changes.

**Comment by leandroroser** [comment] 2018-04-20 00:58
Hi @nturaga,

I have made the suggested corrections to the package.

I am having warnings and errors related to git tracked files (compiled .o files of the src folder, which are actually not present when I push my commits). The files are listed in .gitignore, and I do not see them using the command: git ls-tree -r master --name-only. 

How could I fix this issue?

Thanks!
  Leandro

**Comment by leandroroser** [comment] 2018-04-23 04:26
Hi @nturaga, it seems that the issue persists. I think that the files were tracked at some point, but previous versions that were passing without errors already included the files in .gitignore

**Comment by nturaga** [comment] 2018-04-23 13:38
Hi @leandroroser, I am investigating. Please give me some time

**Comment by nturaga** [comment] 2018-04-23 22:38
Please fix the WARNING on the build. The previous issue is now resolved.

**Comment by leandroroser** [comment] 2018-04-24 04:14
Hi @nturaga , thanks.

One of the warnings is related to the size of the package. The vignette has a step-by-step guide with images that explain the use of the application. There is also an html file for the 'help' button of the application (the total size for these elements after compressing the images is ~4.5 Mb). I was wondering if, in this particular case, the size of the package could be justified.

**Comment by nturaga** [comment] 2018-04-25 15:37
Hi @leandroroser,

I understand the need for images in this package. But isn't it possible to make these images lower resolution `PNG` files? 

This will allow for the package to fall under the limit. We have a hard limit of 5MB for software packages. Please give this a try and let me know.

Best,

**Comment by leandroroser** [comment] 2018-05-03 23:02
Hi @nturaga,

I have been working with the images to fit the 4 Mb limit. Using bmp the size increased considerably, and with jpg the size is 4.6 Mb. I used jpg for a size < 5 Mb. Please let me know if you think this is fine to proceed.

Thanks,
 Leandro

**Comment by nturaga** [comment] 2018-05-17 14:42
@leandroroser I'm hoping @mtmorgan might have a suggestion. The only way I was able to reduce image size was using PNGs

**Comment by leandroroser** [comment] 2018-05-19 06:37
Thanks for the suggestions, @nturaga and @mtmorgan. I have fixed the warnings related to the package size (pictures are PNGs now).

There is a new warning:

* WARNING: Remove set.seed usage in R code
      Found in R/ directory functions:
        inject_letter_random()
        random_length()
        random_qual()
        random_seq()

This set of functions provide simulated sequences, qualities, etc. An optional value can be passed as argument to generate reproducible examples (via an internal call to set.seed()). I think that set.seed() in this case is useful. Should I make some modifications to the functions?

Thanks again,
  Leandro

**Comment by mtmorgan** [comment] 2018-05-19 10:58
For reproducibility the usual practice is for the user to `set.seed()` at the top of their script. Indeed the warning that you cite above is to prevent packages from messing with the random number stream.

**Comment by leandroroser** [comment] 2018-05-20 08:41
Hi @nturaga and @mtmorgan. I have fixed the issues.
I am ready to proceed.

Thanks,
  Leandro

**Comment by mtmorgan** [comment] 2018-05-21 17:16
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/leandroroser.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"FastqCleaner\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/FastqCleaner

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-05-21 17:16 UTC
Labels: 3a. accepted, OK
