### ISSUE TITLE
mosbi

### ISSUE THREAD

**Issue by tdrose** [Bioconductor/Contributions#2252] opened 2021-08-24 11:35 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/tdrose/mosbi

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by tdrose** [comment] 2021-08-26 08:51
I have a question concerning a dependency. For convienience I would like to add [runibic](https://bioconductor.org/packages/release/bioc/html/runibic.html) as a suggested dependency and use it in a function, where I check with `requireNamespace` if it is available.

However, the _automated package builder_ raised WARNING, since the package is apparently not available for Windows and an ERROR if I remove the dependency, but still use it in my function.

For now I removed the function to get the OK label. Is there a way around this and where I am still able to include the package for bioconductor?

**Comment by lshep** [comment] 2021-09-10 12:43
I think you mean it isn't available on mac? (http://bioconductor.org/checkResults/devel/bioc-LATEST/runibic/).   If the warning is raised from another package I would ignore the warning and proceed with the hopes that runibic fixes their package; we can make an exception in this case for the warning.

**Comment by tdrose** [comment] 2021-09-16 13:42
Thanks @lshep for answering.

I proceeded as you suggested and added `runibic` again as a suggested dependency.

**Comment by nturaga** [comment] 2021-10-06 03:04
# mosbi review

General comments: Please note the release schedule that is posted here - http://bioconductor.org/developers/release-schedule/.

We'll try to get your package in before that.

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

* ok

## NAMESPACE 

ok

## R

- Use the appropriate messages when throwing errors in your functions or try-catch statements. http://bioconductor.org/developers/how-to/coding-style/

## src

- ok

## tests

- Write test cases

## Vignette

- Use BiocStyle

* Checking vignette directory...
    * NOTE: 'sessionInfo' not found in vignette(s)
      Missing from file(s):
        vignettes/example-workflow.Rmd
        vignettes/similarity-metrics-evaluation.Rmd

**Comment by tdrose** [comment] 2021-10-11 17:17
Dear @nturaga,

I updated the package considering all points from your review:

* *appropriate messages when throwing errors in your functions or try-catch statements* -> I updated most error and try-catch messages to make it clearer
* *tests* -> I added unittest using the `testthat` package for the main functionalities
* *BiocStyle in Vignettes* -> Done
* *sessionInfo in Vignettes* -> Done

The latest build report only showed only `macOS` and no other OS (?), however, @lshep agreed not to take it into account, since one suggested dependency (`runibic`) is not available.

**Comment by nturaga** [comment] 2021-10-11 17:55
Issue a build report tomorrow, please. We are all off today.

**Comment by tdrose** [comment] 2021-10-12 09:20
> Issue a build report tomorrow, please. We are all off today.


Still the same behavior. I only see the `macOS` build report.

**Comment by tdrose** [comment] 2021-10-13 13:45
Again only the `macOS` build report is available.

**Comment by nturaga** [comment] 2021-10-13 15:28
We are having issues with the build system. I'll get back to you as they are fixed

**Comment by lshep** [comment] 2021-10-13 15:39
All three builders should now be up.

**Comment by nturaga** [comment] 2021-10-13 17:19
Hi @tdrose Issue another build

**Comment by tdrose** [comment] 2021-10-14 06:54
Unfortunately same issue.

**Comment by lshep** [comment] 2021-10-14 11:53
not sure why the one set of builders is getting knocked off. I put them back on and I kicked off a manual build of your package. The report should post shortly

**Comment by tdrose** [comment] 2021-10-14 12:36
Thanks @lshep it worked!

**Comment by tdrose** [comment] 2021-10-14 12:36
Here again, are my answers to the review:

I updated the package considering all points from your review:

* appropriate messages when throwing errors in your functions or try-catch statements -> I updated most error and try-catch messages to make it clearer
* tests -> I added unittest using the testthat package for the main functionalities
* BiocStyle in Vignettes -> Done
* sessionInfo in Vignettes -> Done

**Comment by nturaga** [comment] 2021-10-15 01:36
I've accepted your package. Issue another build to see why there is an error on Mac - R CHECK. I couldn't reproduce it locally.

**Comment by tdrose** [comment] 2021-10-15 09:28
I tried to issue new builds (by pushing with a new version number). However no new builds are issued.

**Comment by lshep** [comment] 2021-10-15 12:54
The MAC builder is currently off-line -- please monitor the reports once it gets moved to the daily builder and follow up if it continues there.

**Comment by lshep** [comment] 2021-10-19 15:05
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tdrose.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("mosbi")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mosbi

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-10-19 15:05 UTC
Labels: 3a. accepted
