### ISSUE TITLE
SCArray.sat

### ISSUE THREAD

**Issue by zhengxwen** [Bioconductor/Contributions#2933] opened 2023-02-11 21:30 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/zhengxwen/SCArray.sat

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by zhengxwen** [comment] 2023-02-23 00:03
The only error is
```
ERROR: Maintainer must add package name to Watched Tags on the
      support site; Edit your Support Site User Profile to add Watched
      Tags.
```

To fix this error, I have added "SCArray.sat" to my watched tags, and run "BiocCheck" locally (no error shows).
I just bumped the version to trigger a new build.

**Comment by PeteHaitch** [comment] 2023-02-23 22:17
Thank you for submitting **scArray.sat** to Bioconductor, @zhengxwen.
I hope to begin my review of the package next week, but it may not be until the following that I can get started due to other commitments.
In the meantime, if you have any questions then please post them here.

Cheers,
Pete

**Comment by PeteHaitch** [comment] 2023-02-23 22:29
A few pre-review questions, all rather related:

1. Could you please briefly summarise the differences between **scArray** and **scArray.sat**? I think the figure in the README (https://github.com/zhengxwen/SCArray.sat/blob/main/vignettes/scarray_sat.svg) contains this information, but a text explanation would help me. 
2. Bioconductor's preferred data structure for storing single-cell data is the *SingleCellExperiment* class (from [**SingleCellExperiment**](https://bioconductor.org/packages/SingleCellExperiment/) rather than the *SeuratObject* class from **Seurat**. If my understanding of [the schematic](https://github.com/zhengxwen/SCArray.sat/blob/main/vignettes/scarray_sat.svg) is correct, *SingleCellExperiment*-based workflows are supported by **scArray** and *SeuratObject*-based workflows are supported by **scArray.sat**? 
3. What does the 'sat' in **scArray.sat** mean or stand for? If it's Seurat, it may benefit from being more explicit (e.g., **scArray.Seurat**).

**Comment by zhengxwen** [comment] 2023-02-27 07:35
Thanks for these pre-review questions. They are very helpful.

1)
**SCArray.sat** extends the Seurat classes and functions to support Genomic Data Structure (GDS) files as a DelayedArray backend for data representation. It relies on the implementation of GDS-based DelayedMatrix in the **SCArray** package to represent single cell RNA-seq data. The common optimized algorithms leveraging GDS-based and single cell-specific DelayedMatrix (SC_GDSMatrix) are implemented in the **SCArray** package.

**SCArray.sat** introduces a new SCArrayAssay class (derived from the Seurat Assay), which wraps raw counts, normalized expressions and scaled data matrix based on GDS-specific DelayedMatrix (SC_GDSMatrix). It is designed to integrate seamlessly with the Seurat package to provide common data analysis in the SeuratObject-based workflow. Some of the Seurat-specific methods are re-implemented in **SCArray.sat** to manipulate GDS files.

2)
Yes, the SingleCellExperiment-based workflows are fully supported by the **SCArray** package, while **SCArray.sat** is designed to support and extend the SeuratObject-based workflows. The Seurat object can be converted to a SingleCellExperiment object, via `as.SingleCellExperiment()`.

3)
“**sat**” stands for “**Seurat**”. I feel that “**SCArray.Seurat**” is too long for the package name, and it is longer than 92% of the Bioconductor software packages.


I hope that it is clear now.

**Comment by PeteHaitch** [comment] 2023-03-13 22:21
Hi @zhengxwen,

Thank you for submitting **SCArray.sat** to Bioconductor.

Overall, the package is in good shape and close to being ready for acceptance.

Regarding the package name, I'd recommend going with **SCArray.Seurat** over **SCArray.sat**; I don't know of anyone else who abbreviates 'Seurat' to 'sat', which means people won't know the connection of **SCArray.sat** based on its name.
To me, having 3 extra characters to ensure people know what the package is seems a tiny price to pay.
But of course, the choice of name is yours to make.

In my review below I have separated the issues into Required and Recommended points that I would ask you to address before the package can be accepted.
Would you please provide line-by-line comments to my initial review so that I know what changes I'm looking for in my re-review.

Cheers,
Pete

### Required

- [ ] Is something like `HDF5Array::saveHDF5SummarizedExperiment()` needed? See the section 'Difference between saveHDF5SummarizedExperiment() and saveRDS()' of `?HDF5Array::saveHDF5SummarizedExperiment()` for a full explanation of why it's needed for *HDF5Array*-based *SingleCellExperiment* objects. But briefly, if someone saves a *SC_GDSMatrix*_backed *Seurat* object to disk with `saveRDS()` and then copies that `.rds` file to another computer and tries to open it, then I expect there will be an error because they won't also have copied the necessary `.gds` file (or it might be in a different location even if they do know to copy it). This would also apply to **SCArray** and it's *SC_GDSMatrix*_backed *SingleCellExperiment* objects.
- [ ] In the vignette, please `set.seed()` before steps involving random number generation (e.g., `RunPCA()` and `runUMAP()`) to ensure reproducibility.
- The 'Benchmarking' section of the vignette refers to `D100`, `D250`, `D500`, and `Dfull`, but these aren't defined. Please include the code used to generate these objects.
- [ ] The 'Benchmarking' section of the vignette should describe the system on which it was run (e.g., RAM, CPU, etc.).
- [ ] The 'Save SCArrayAssay' section of the vignette must use `tempdir()`/`tempfile()` when calling `saveRDS()`. You can add a comment that a user running this funtion as part of a 'real' analysis should specify an appropriate location for the file.
- [ ] The example code in `README.md` is broken because `scGetAssayGDS()` doesn't exist. Please fix.

``` r
suppressPackageStartupMessages({
    library(Seurat)
    library(SCArray.sat)
})

# an input GDS file with raw counts
fn <- system.file("extdata", "example.gds", package="SCArray")
fn
#> [1] "/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SCArray/extdata/example.gds"

a <- scGetAssayGDS(fn)
#> Error in scGetAssayGDS(fn): could not find function "scGetAssayGDS"
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R Under development (unstable) (2023-02-13 r83829)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Ventura 13.2.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> time zone: Australia/Melbourne
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats4    stats     graphics  grDevices utils     datasets  methods  
#> [8] base     
#> 
#> other attached packages:
#>  [1] SCArray.sat_0.99.1    SCArray_1.7.14        DelayedArray_0.25.0  
#>  [4] IRanges_2.33.0        S4Vectors_0.37.4      MatrixGenerics_1.11.0
#>  [7] matrixStats_0.63.0    BiocGenerics_0.45.0   Matrix_1.5-3         
#> [10] gdsfmt_1.35.6         SeuratObject_4.1.3    Seurat_4.3.0         
#> 
#> loaded via a namespace (and not attached):
#>   [1] RColorBrewer_1.1-3          rstudioapi_0.14            
#>   [3] jsonlite_1.8.4              magrittr_2.0.3             
#>   [5] spatstat.utils_3.0-2        rmarkdown_2.20             
#>   [7] zlibbioc_1.45.0             fs_1.6.1                   
#>   [9] vctrs_0.5.2                 ROCR_1.0-11                
#>  [11] spatstat.explore_3.0-6      DelayedMatrixStats_1.21.0  
#>  [13] RCurl_1.98-1.10             htmltools_0.5.4            
#>  [15] sctransform_0.3.5           parallelly_1.34.0          
#>  [17] KernSmooth_2.23-20          htmlwidgets_1.6.1          
#>  [19] ica_1.0-3                   plyr_1.8.8                 
#>  [21] plotly_4.10.1               zoo_1.8-11                 
#>  [23] igraph_1.4.1                mime_0.12                  
#>  [25] lifecycle_1.0.3             pkgconfig_2.0.3            
#>  [27] rsvd_1.0.5                  R6_2.5.1                   
#>  [29] fastmap_1.1.1               GenomeInfoDbData_1.2.9     
#>  [31] fitdistrplus_1.1-8          future_1.32.0              
#>  [33] shiny_1.7.4                 digest_0.6.31              
#>  [35] colorspace_2.1-0            patchwork_1.1.2            
#>  [37] tensor_1.5                  irlba_2.3.5.1              
#>  [39] GenomicRanges_1.51.4        beachmat_2.15.0            
#>  [41] progressr_0.13.0            fansi_1.0.4                
#>  [43] spatstat.sparse_3.0-1       httr_1.4.5                 
#>  [45] polyclip_1.10-4             abind_1.4-5                
#>  [47] compiler_4.3.0              withr_2.5.0                
#>  [49] BiocParallel_1.33.9         DBI_1.1.3                  
#>  [51] MASS_7.3-58.3               tools_4.3.0                
#>  [53] lmtest_0.9-40               httpuv_1.6.9               
#>  [55] future.apply_1.10.0         goftest_1.2-3              
#>  [57] glue_1.6.2                  nlme_3.1-162               
#>  [59] promises_1.2.0.1            grid_4.3.0                 
#>  [61] Rtsne_0.16                  cluster_2.1.4              
#>  [63] reshape2_1.4.4              generics_0.1.3             
#>  [65] gtable_0.3.1                spatstat.data_3.0-1        
#>  [67] tidyr_1.3.0                 data.table_1.14.8          
#>  [69] XVector_0.39.0              ScaledMatrix_1.7.0         
#>  [71] BiocSingular_1.15.0         sp_1.6-0                   
#>  [73] utf8_1.2.3                  spatstat.geom_3.1-0        
#>  [75] RcppAnnoy_0.0.20            ggrepel_0.9.3              
#>  [77] RANN_2.6.1                  pillar_1.8.1               
#>  [79] stringr_1.5.0               later_1.3.0                
#>  [81] splines_4.3.0               dplyr_1.1.0                
#>  [83] lattice_0.20-45             survival_3.5-5             
#>  [85] deldir_1.0-6                tidyselect_1.2.0           
#>  [87] SingleCellExperiment_1.21.0 miniUI_0.1.1.1             
#>  [89] pbapply_1.7-0               knitr_1.42                 
#>  [91] gridExtra_2.3               SummarizedExperiment_1.29.1
#>  [93] scattermore_0.8             xfun_0.37                  
#>  [95] Biobase_2.59.0              stringi_1.7.12             
#>  [97] lazyeval_0.2.2              yaml_2.3.7                 
#>  [99] evaluate_0.20               codetools_0.2-19           
#> [101] tibble_3.2.0                cli_3.6.0                  
#> [103] uwot_0.1.14                 xtable_1.8-4               
#> [105] reticulate_1.28             munsell_0.5.0              
#> [107] GenomeInfoDb_1.35.15        Rcpp_1.0.10                
#> [109] globals_0.16.2              spatstat.random_3.1-4      
#> [111] png_0.1-8                   parallel_4.3.0             
#> [113] ellipsis_0.3.2              ggplot2_3.4.1              
#> [115] reprex_2.0.2                bitops_1.0-7               
#> [117] sparseMatrixStats_1.11.1    listenv_0.9.0              
#> [119] viridisLite_0.4.1           scales_1.2.1               
#> [121] ggridges_0.5.4              leiden_0.4.3               
#> [123] purrr_1.0.1                 rlang_1.0.6                
#> [125] cowplot_1.1.1
```

</details>

- [ ] Please add a `BugReports` field to the `DESCRIPTION` (https://contributions.bioconductor.org/description.html#description-bugreport)
- [ ] Please add an 'Installation' section to the vignette (https://contributions.bioconductor.org/docs.html#installation).
- [ ] Please remove `ByteCompile: TRUE` from the `DESCRPTION`; it necessary because it's the default.

### Recommended

- [ ] When running the vignette code in RStudio, I go weird blurry text that's quite hard to read when `show()`-ing a _SCArrayFileClass_. This seems to be from use of `crayon::blurred()` in  `gdsfmt::print.gds.class()`. I guess 'crayon::blurred()` is doing exactly what the function name says, but I'd suggest changing this to a font that can be read clearly on most systems.

![image](https://user-images.githubusercontent.com/1049741/224845688-2ce96327-5f20-45dc-9d94-275d50c43889.png)


- [ ] It is strongly encouraged to use **BiocStyle** for formatting the vignette (https://contributions.bioconductor.org/docs.html?q=biocstyle#vignettes).
- [ ] It would be helpful to have a table summarising which methods from **Seurat** that **SCArray.sat** does and does not support (and whether support is planned, not possible, etc.). For example, running `SCTransform(d)` gives an error that may be confusing to new users. While it may be tricky (if not impossible) to inject a **SCArray.sat**-specific error when a **Seurat** function is applied that **SCArray.sat** does not support, this table featured prominently in the documentation could at least set the expectations for a new user.

``` r
suppressPackageStartupMessages({
  library(Seurat)
  library(SCArray)
  library(SCArray.sat)
})
fn <- system.file("extdata", "example.gds", package="SCArray")
d <- scNewSeuratGDS(fn)
#> Input: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SCArray/extdata/example.gds
#>     counts: 1000 x 850
SCTransform(d)
#> Calculating cell attributes from input UMI matrix: log_umi
#> Error in row_gmean(umi, eps = gmean_eps): matrix x needs to be of class matrix or dgCMatrix
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R Under development (unstable) (2023-02-13 r83829)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Ventura 13.2.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> time zone: Australia/Melbourne
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats4    stats     graphics  grDevices utils     datasets  methods  
#> [8] base     
#> 
#> other attached packages:
#>  [1] SCArray.sat_0.99.1    SCArray_1.7.14        DelayedArray_0.25.0  
#>  [4] IRanges_2.33.0        S4Vectors_0.37.4      MatrixGenerics_1.11.0
#>  [7] matrixStats_0.63.0    BiocGenerics_0.45.0   Matrix_1.5-3         
#> [10] gdsfmt_1.35.6         SeuratObject_4.1.3    Seurat_4.3.0         
#> 
#> loaded via a namespace (and not attached):
#>   [1] RColorBrewer_1.1-3          rstudioapi_0.14            
#>   [3] jsonlite_1.8.4              magrittr_2.0.3             
#>   [5] spatstat.utils_3.0-2        rmarkdown_2.20             
#>   [7] zlibbioc_1.45.0             fs_1.6.1                   
#>   [9] vctrs_0.5.2                 ROCR_1.0-11                
#>  [11] spatstat.explore_3.0-6      DelayedMatrixStats_1.21.0  
#>  [13] RCurl_1.98-1.10             htmltools_0.5.4            
#>  [15] sctransform_0.3.5           parallelly_1.34.0          
#>  [17] KernSmooth_2.23-20          htmlwidgets_1.6.1          
#>  [19] ica_1.0-3                   plyr_1.8.8                 
#>  [21] plotly_4.10.1               zoo_1.8-11                 
#>  [23] igraph_1.4.1                mime_0.12                  
#>  [25] lifecycle_1.0.3             pkgconfig_2.0.3            
#>  [27] rsvd_1.0.5                  R6_2.5.1                   
#>  [29] fastmap_1.1.1               GenomeInfoDbData_1.2.9     
#>  [31] fitdistrplus_1.1-8          future_1.32.0              
#>  [33] shiny_1.7.4                 digest_0.6.31              
#>  [35] colorspace_2.1-0            patchwork_1.1.2            
#>  [37] tensor_1.5                  irlba_2.3.5.1              
#>  [39] GenomicRanges_1.51.4        beachmat_2.15.0            
#>  [41] progressr_0.13.0            fansi_1.0.4                
#>  [43] spatstat.sparse_3.0-1       httr_1.4.5                 
#>  [45] polyclip_1.10-4             abind_1.4-5                
#>  [47] compiler_4.3.0              withr_2.5.0                
#>  [49] BiocParallel_1.33.9         DBI_1.1.3                  
#>  [51] MASS_7.3-58.3               tools_4.3.0                
#>  [53] lmtest_0.9-40               httpuv_1.6.9               
#>  [55] future.apply_1.10.0         goftest_1.2-3              
#>  [57] glue_1.6.2                  nlme_3.1-162               
#>  [59] promises_1.2.0.1            grid_4.3.0                 
#>  [61] Rtsne_0.16                  cluster_2.1.4              
#>  [63] reshape2_1.4.4              generics_0.1.3             
#>  [65] gtable_0.3.1                spatstat.data_3.0-1        
#>  [67] tidyr_1.3.0                 data.table_1.14.8          
#>  [69] XVector_0.39.0              ScaledMatrix_1.7.0         
#>  [71] BiocSingular_1.15.0         sp_1.6-0                   
#>  [73] utf8_1.2.3                  spatstat.geom_3.1-0        
#>  [75] RcppAnnoy_0.0.20            ggrepel_0.9.3              
#>  [77] RANN_2.6.1                  pillar_1.8.1               
#>  [79] stringr_1.5.0               later_1.3.0                
#>  [81] splines_4.3.0               dplyr_1.1.0                
#>  [83] lattice_0.20-45             survival_3.5-5             
#>  [85] deldir_1.0-6                tidyselect_1.2.0           
#>  [87] SingleCellExperiment_1.21.0 miniUI_0.1.1.1             
#>  [89] pbapply_1.7-0               knitr_1.42                 
#>  [91] gridExtra_2.3               SummarizedExperiment_1.29.1
#>  [93] scattermore_0.8             xfun_0.37                  
#>  [95] Biobase_2.59.0              stringi_1.7.12             
#>  [97] lazyeval_0.2.2              yaml_2.3.7                 
#>  [99] evaluate_0.20               codetools_0.2-19           
#> [101] tibble_3.2.0                cli_3.6.0                  
#> [103] uwot_0.1.14                 xtable_1.8-4               
#> [105] reticulate_1.28             munsell_0.5.0              
#> [107] GenomeInfoDb_1.35.15        Rcpp_1.0.10                
#> [109] globals_0.16.2              spatstat.random_3.1-4      
#> [111] png_0.1-8                   parallel_4.3.0             
#> [113] ellipsis_0.3.2              ggplot2_3.4.1              
#> [115] reprex_2.0.2                bitops_1.0-7               
#> [117] sparseMatrixStats_1.11.1    listenv_0.9.0              
#> [119] viridisLite_0.4.1           scales_1.2.1               
#> [121] ggridges_0.5.4              leiden_0.4.3               
#> [123] purrr_1.0.1                 rlang_1.0.6                
#> [125] cowplot_1.1.1
```

</details>

- [ ] Consider a `inst/CITATION` file if applicable (https://contributions.bioconductor.org/citation.html).

**Comment by zhengxwen** [comment] 2023-03-21 04:10
I am not able to fix the WARNING and ERROR in the build (commit id: 38d463bf7e58a3b5c1343e8dee9de10008e5266d):
```
WARNING: R CMD check exceeded 10 min requirement

ERROR:
there is no package called 'BiocGenerics'
package SCArray required by SCArray.sat could not be found
```

**Comment by zhengxwen** [comment] 2023-03-21 04:16
Hi Peter,

Thank you for your detailed comments, and they are very helpful.

I will stick to the package name "SCArray.sat", and thanks for the understanding.

Here are my responses:

### Required

* Is something like HDF5Array::saveHDF5SummarizedExperiment() needed?

It is not necessary. `SCArray::scConvGDS()` can save the count data (or other data matrices) to a GDS file. We usually start from the raw count data, then create a GDS file, load it as a `SingleCellExperiment` object or a `SeuratObject` object. When calling `saveRDS()`, the data of GDS-based DelayedArray are not saved in the RDS file. I explained it in the section "Save SCArrayAssay" of the vignette, and remind users to keep the GDS and RDS files in the same directory or the same relative path. If the corresponing GDS file is not found when manipulating the DelayedArray object in the RDS file, an error will show, like:
```
Error in gdsfmt:::.reopen(x@gds) :
  Can not open file 'example.gds'. No such file or directory
```

* In the vignette, please set.seed() before steps involving random number generation (e.g., RunPCA() and runUMAP()) to ensure reproducibility.

`set.seed(42)` was added to the vignette and README.md.

* The 'Benchmarking' section of the vignette refers to D100, D250, D500, and Dfull, but these aren't defined. Please include the code used to generate these objects.

The following codes were added to the vignett:
```R
library(SCArray)
library(SCArray.sat)

sce <- scExperiment("1M_sc_neurons.gds")  # load the full 1.3M cells

# D100 dataset
scConvGDS(sce[, 1:1e5], "1M_sc_neurons_d100.gds")  # save to a GDS
# in-memory Seurat object
obj <- scMemory(scNewSeuratGDS("1M_sc_neurons_d100.gds"))
saveRDS(obj, "1M_sc_neurons_d100_seuratobj.rds")  # save to a RDS

# D250 dataset
scConvGDS(sce[, 1:2.5e5], "1M_sc_neurons_d250.gds")
obj <- scMemory(scNewSeuratGDS("1M_sc_neurons_d250.gds"))
saveRDS(obj, "1M_sc_neurons_d250_seuratobj.rds")

# D500 dataset
scConvGDS(sce[, 1:5e5], "1M_sc_neurons_d500.gds")
obj <- scMemory(scNewSeuratGDS("1M_sc_neurons_d500.gds"))
saveRDS(obj, "1M_sc_neurons_d500_seuratobj.rds")

# Dfull dataset
scConvGDS(sce, "1M_sc_neurons_dfull.gds")
```

* The 'Benchmarking' section of the vignette should describe the system on which it was run (e.g., RAM, CPU, etc.).

`(CPU: Intel Xeon Gold 6248 @2.50GHz, RAM: 176GB)` is added to the vignette.

* The 'Save SCArrayAssay' section of the vignette must use tempdir()/tempfile() when calling saveRDS(). You can add a comment that a user running this funtion as part of a 'real' analysis should specify an appropriate location for the file.

`"test.rds"` is replaced by `tempfile(fileext=".rds")` in the vignette.

* The example code in README.md is broken because scGetAssayGDS() doesn't exist. Please fix.

It is fixed now.

* Please add a BugReports field to the DESCRIPTION

`BugReports: https://github.com/zhengxwen/SCArray.sat/issues` is added to DESCRIPTION.

* Please add an 'Installation' section to the vignette (https://contributions.bioconductor.org/docs.html#installation).

A section "Installation" is added to the vignette.

* Please remove ByteCompile: TRUE from the DESCRPTION; it necessary because it's the default.

`ByteCompile: TRUE` is removed from DESCRIPTION.


### Recommended

* When running the vignette code in RStudio, I go weird blurry text that's quite hard to read when show()-ing a SCArrayFileClass. This seems to be from use of crayon::blurred() in  gdsfmt::print.gds.class(). I guess 'crayon::blurred()` is doing exactly what the function name says, but I'd suggest changing this to a font that can be read clearly on most systems.

I seldom use RStudio, and I am not sure when RStudio started using the blur effect for `crayon::blurred()`. It is fixed in the most recent gdsfmt_1.35.7. Or users can disable crayon terminal output by `options(gds.crayon=FALSE)`.

* It is strongly encouraged to use BiocStyle for formatting the vignette.

BiocStyle is used in the vignette now.

* It would be helpful to have a table summarising which methods from Seurat that SCArray.sat does and does not support (and whether support is planned, not possible, etc.). For example, running SCTransform(d) gives an error that may be confusing to new users. While it may be tricky (if not impossible) to inject a SCArray.sat-specific error when a Seurat function is applied that SCArray.sat does not support, this table featured prominently in the documentation could at least set the expectations for a new user.

A section "List of supported functions" is add to the vignette. As described in the help file of `SCTransform`, it calls `sctransform::vst` (i.e., the function in another R pacakge rather than Seurat & SeuratObject). Not all of the functions can directly support `SCArrayAssay`. To increase the compatibility of SCArray.sat, contacting with the Seurat package maintainers would be also helpful. Before any additional feature support, SCArray.sat should be deposited in a permanent and public repository. In addition, the `SCArrayAssay` object can be downgraded to the regular `Assay`, see the section "Downgrade SCArrayAssay".

* Consider a inst/CITATION file if applicable.

The file `inst/CITATION` is added.

**Comment by PeteHaitch** [comment] 2023-03-26 21:27
Hi @zhengxwen,

Thank you for your response to the initial review.
I'm now happy to accept **SCArray.sat** into Bioconductor.
Congratulations and thank you for your contribution!

> > Is something like HDF5Array::saveHDF5SummarizedExperiment() needed?

> It is not necessary. ...

What you describe is exactly why something like a function like `HDF5Array::saveHDF5SummarizedExperiment()` (e.g., `SCArray.sat::saveGDSSeuratObejct()`) is necessary or at least very helpful for users.
It can make it easier for a user to share a GDS-backed Seurat object with someone else, or just to move it to a new location.
It's not a requirement for acceptance, but I think it would make a useful addition.

**Comment by PeteHaitch** [comment] 2023-03-26 21:30
Sorry, before I can formally accept **SCArray.sat** could you please bump the version and push to git.bioconductor.org to trigger a new build.
The most recent build on the Single Package Builder (SPB) resulted in an error on the Linux builder (`nebbiolo1`) - I suspect it was a transient error and that a simply re-running it will resolve the issue.
The package builds and checks fine on my system (Mac M1) but it would be good to confirm it passes on other systems using the SPB.

**Comment by PeteHaitch** [comment] 2023-03-27 00:14
Thanks, @zhengxwen!
I'm happy to accept the package despite the `WARNING: check time exceeded 10 min` on `merida1` - the latest build is 49 seconds over the check time there but only takes 5 mins on `nebbiolo1`.
Please keep an eye on builds once it enters the regular BioC builds and see if there's anything you can do to reduce the time taken to check the package.

**Comment by lshep** [comment] 2023-03-31 11:29
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/zhengxwen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SCArray.sat")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SCArray.sat

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-03-31 11:29 UTC
Labels: 3a. accepted, WARNINGS
