### ISSUE TITLE
velociraptor

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/Contributions#1632] opened 2020-09-11 09:34 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kevinrue/velociraptor

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by kevinrue** [comment] 2020-09-11 09:35
Tagging @LTLA and @csoneson to be notified of progress on this submission.

**Comment by LTLA** [comment] 2020-09-12 04:57
Mac and Unix failures seem to be an issue with the SPB, I see green for BiocNeighbors and BiocSingular on the BBS.

Windows, well, who knows what's happening there. Maybe it'll go away in the next release cycle.

**Comment by LTLA** [comment] 2020-09-21 16:07
I don't know that there's all that much we can do about the Windows TIMEOUT. Sometimes it just happens. I don't even know why **basilisk** is failing on tokay, I suspect there is an invalid cached installation that is not getting regenerated. (Fun fact, on Windows I can't even catch invalid installations because any installation failures don't actually trigger any of my errors.)

**Comment by kevinrue** [comment] 2020-09-21 16:22
@mtmorgan 
Windows doesn't look particularly happy about this.
We're looking into it on our side, but feedback and advice are welcome, especially if it's potentially a problem with the build system itself.

All the best
Kevin

**Comment by mtmorgan** [comment] 2020-09-21 18:06
Is this conda-related (and hence above my paygrade ;) ) or ...? If it's a complicated system dependency, then users will also have problems with this -- do you need Qt?

**Comment by LTLA** [comment] 2020-09-21 19:10
I'm not entirely sure myself, we were able to build this [last week](https://github.com/Bioconductor/Contributions/issues/1632#issuecomment-691650956). Too many moving parts to be sure, especially since **basilisk** itself is struggling on tokay (but not riesling, which suggests it's not solely a Windows problem).

I guess I could test this on my Windows VM, though I have found that it hard to reproduce errors on the BBS or SPB.

**Comment by kevinrue** [comment] 2020-09-28 14:24
@mtmorgan @LTLA 
I'm looking into this again now (Windows issue), and I may have some time Thursday and Friday (deadline for new packages)).
Is there still a chance we can get it into this release?
What do we need to do for that to happen? Fix Windows? Declare that Windows isn't supported?

**Comment by kevinrue** [comment] 2020-09-28 14:36
I'm getting the Qt issue on my local Windows machine at the following step in the vignette
```r
embedded <- embedVelocity(reducedDim(sce, "TSNE"), velo.out)
```

![image](https://user-images.githubusercontent.com/5769108/94445917-eb0f2c00-019f-11eb-8274-287eb1e686be.png)

**Comment by LTLA** [comment] 2020-09-28 15:10
Something is probably trying to make a plot in the `embedVelocity` call. Can we see if we can find it and turn it off?

**Comment by csoneson** [comment] 2020-09-28 15:21
Might setting `autoscale=False` in the `embedVelocity` call help? If the problem is https://github.com/theislab/scvelo/blob/1ff51ba53f7fcedadb9ee147aac81383926dd9f6/scvelo/tools/velocity_embedding.py#L15

**Comment by kevinrue** [comment] 2020-09-28 15:51
Politely poking @mtmorgan again 😬

**Comment by LTLA** [comment] 2020-10-01 19:33
This seems pretty solid now.

@kevinrue you want to fill in the section of the trajectory chapter in the OSCA book with this package? Basically it would be the same as the vignette but with the full dataset.

**Comment by mtmorgan** [comment] 2020-10-03 23:41
I don't have any significant problems with this package and am accepting it.

**Comment by mtmorgan** [comment] 2020-10-05 01:44
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kevinrue.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("velociraptor")`. The package 'landing page' will be created at

https://bioconductor.org/packages/velociraptor

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-10-05 01:44 UTC
Labels: 3a. accepted
