### ISSUE TITLE
moanin: An R Package for Time Course RNASeq Data Analysis

### ISSUE THREAD

**Issue by NelleV** [Bioconductor/Contributions#1617] opened 2020-09-02 06:49 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/NelleV/moanin

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-09-03 18:15
Please follow the [Bioconductor versions](http://bioconductor.org/developers/how-to/version-numbering/) standard 'x.y.z', where z is integer valued. Thus update your version to 0.99.1 (and subsequently 0.99.2, 0.99.3, ... during the review process)

**Comment by mtmorgan** [comment] 2020-09-03 18:17
Please also update your biocViews to valid entries -- `microarray` should be `Microarray`.

**Comment by lshep** [comment] 2020-09-04 11:48
Bioconductor dependencies must be active on CRAN or Bioconductor.  The `BiocStyles` was on our end but cover appears to be a legacy CRAN package that was removed in 2017.  See this [CRAN page](https://cran.r-project.org/web/packages/COveR/index.html).  The cover dependency will have to be removed.

**Comment by NelleV** [comment] 2020-09-08 12:50
Hello,
I unfortunately don't seem to be able to do the version bump as I would have expected:

**Comment by lshep** [comment] 2020-09-08 12:52
@nturaga  Can you please assist with this

**Comment by nturaga** [comment] 2020-09-09 11:01
Hi @NelleV ,

The version number you have doesn't follow the numbering scheme we have in place. I'll look into solutions and get back to you.

In the meantime, please take a look at your build rapport and fix the issues which you see (NOTES, WARNINGS, ERRORS). 

Best,

Nitesh

**Comment by NelleV** [comment] 2020-09-14 14:50
Hello,
Any news on how to proceed forward with the git hook? I don't see any solution that I could do on my end, as unlike pre-commit hooks, there is, to the best of my knowledge, no way for me to ignore the hook.
  
I fixed all the errors & warnings build in the package on my laptop.

Thanks,
Nelle

**Comment by nturaga** [comment] 2020-09-14 15:12
I'd have to fix this internally. The issue is arising because your version
number "0.99.0-902" has a'-' within it. It doesn't conform to the
Bioconductor guidelines. Once it is fixed you'd have to sync your package
with the version available on the Bioconductor git server.

I'll get back to later today or early tomorrow.

**Comment by nturaga** [comment] 2020-09-15 01:10
Ok, you need to now sync your package with what is on Bioconductor. Look at version numbering to see the Bioc versioning system.

http://bioconductor.org/developers/how-to/version-numbering/

**Comment by NelleV** [comment] 2020-09-16 16:07
Hello @nturaga 

The last warnings only occurs only on windows during the documentation build: apparently, the topGo functions we are linking to are not found. I'm a bit confused on how to proceed forward with this warning. Any tips?

Many thanks,
Nelle

**Comment by lshep** [comment] 2020-09-16 16:12
See the following on formatting links to other packages https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-formatting.html#links

**Comment by NelleV** [comment] 2020-09-22 08:23
@lshep Looking at the reference you've added on formatting links to other packages, I don't see an issue with the link formatting. 
Not only do they work find on all platform but windows, the issue only arises with topGO. I checked on linux, and the links work fine on the html build of the documentation. From the build warning, the issue is that the functions are not found in the documentation of topGO, yet they do exist (e.g. https://rdrr.io/bioc/topGO/man/topGOdata-class.html).

Unfortunately, I do not have access to a windows machine to attempt to further investigate the issue.

**Comment by lshep** [comment] 2020-09-22 12:05
I think because those functions are listed as alias and not the name you need to do something like   `\code{\link[pkg:filename]{function}}`  for windows to recognize it correctly  where it would be [topGO:dignostic-methods]{GenTable}.  These two links explain better [stackoverflow](https://stackoverflow.com/questions/48430093/how-do-i-resolve-rd-warning-missing-file-link-when-building-packages-in-rstudi) and [cross references](https://cran.r-project.org/doc/manuals/R-exts.html#Cross_002dreferences).  Cheers

**Comment by NelleV** [comment] 2020-09-25 15:43
@lshep Thanks! All warnings and errors have now been fixed!

**Comment by NelleV** [comment] 2020-10-06 09:20
Hello @nturaga 
I was wondering if you had any feedback on the package itself?
Many thanks,
Nelle

**Comment by NelleV** [comment] 2020-10-14 05:26
Hello,
What are the next steps in order to have the package accepted? Is there anything else to do on my end before the review of the package itself?
Many thanks,
Nelle

**Comment by nturaga** [comment] 2020-10-15 15:16
# Review `moanin`

## DESCRIPTION

ok

## NAMESPACE 

ok

## R 

* use `<-` instead of `=` for assignment operation. This is the "R" way.

* Remove commented out code. 

* For rowMeans and other statistics you need to compute check out the package "matrixStats" which optimizes these functions and are faster. Even rowMax and rowMin. 

* Don't use `sapply` in your codebase, use `vapply` instead. 

## vignette

good! 

## man

ok

## Overall

- Well written package. Just needs a few corrections and i'd be happy to accept.

**Comment by NelleV** [comment] 2020-10-22 15:39
Hello,

Thanks @nturaga 

I fixed all of the issues you've underlined!

Unfortunately, the example for the GO term enrichment now fails. The new error comes from topGo currently not running properly on devel (the released version works fine). How should I proceed?

Thanks,
Nelle

**Comment by nturaga** [comment] 2020-10-22 16:19
Hi,

You would need to figure out the issue or wait for topGo to fix the issue. Yesterday was the deadline to accept the packages for this release cycle. So, you now take your time and get this issue fixed and it'll be included in the devel version of Bioconductor. 

Nitesh

**Comment by NelleV** [comment] 2020-10-23 09:11
Hello,

Great. I've opened a PR onto topGO to fix the issue. Hopefully, it will be merged soon and fixed in the devel version of bioconductor. Else, I'll find another solution.

Many thanks,
Nelle

**Comment by NelleV** [comment] 2020-11-02 13:37
Hello @nturaga ,
The build now passes, and in addition to your review, we fixed a couple of small elements here and there that came up while using the package in a new setting.
Many thanks,
Nelle

**Comment by NelleV** [comment] 2020-11-09 08:45
Hi @nturaga ,
I just wanted to check in to see if you had time to do another review of the package!
Many thanks,
Nelle

**Comment by mtmorgan** [comment] 2020-11-11 16:04
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/NelleV.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("moanin")`. The package 'landing page' will be created at

https://bioconductor.org/packages/moanin

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-11-11 16:04 UTC
Labels: 3a. accepted, OK
