### ISSUE TITLE
TMSig

### ISSUE THREAD

**Issue by TylerSagendorf** [Bioconductor/Contributions#3526] opened 2024-08-24 00:18 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/EMSL-Computing/TMSig

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2024-09-04 14:40
Please include an `inst/script/` directory that has a file that can be code,
psuedo code, or text but that describes how the data in `inst/extdata` was
generated. minimally containing source/licensing information. A user should be
able to get an idea of how to recreate the data if necessary.

Given this package seems to be working with geneSets. It will be necessary to
also include functionality to the common Bioconductor classes for gene sets by
also making functions compatible with BiocSet::BiocSet or the GSEABase::GeneSet
or likely more appropriate GSEABase::GetSetCollection.   See 
https://contributions.bioconductor.org/important-bioconductor-package-development-features.html#commonclass

**Comment by TylerSagendorf** [comment] 2024-09-06 22:45
@lshep I will get this taken care of. Since this doesn't have the `pre-review` tag, should I make these changes to the existing TMSig repo under EMSL-Computing?

**Comment by TylerSagendorf** [comment] 2024-09-07 07:33
Functions `sparseIncidence`, `filterSets`, and `invertSets` have been converted to S4 generics to support objects of class `GeneSet` and `GeneSetCollection` from GSEABase. I have also added a .txt file to `inst/script/` that explains how c5.go.v2023.2.Hs.symbols.gmt.gz was generated.

**Comment by lshep** [comment] 2024-09-09 11:07
thank you.  we will take a re-evaluation soon.

**Comment by Kayla-Morrell** [comment] 2024-10-17 11:07
@TylerSagendorf - Thank you for submitting to _Bioconductor_. Please see the initial review of 
the package below. The required changes must be made while the suggested 
changes do not have to be (though we strongly encourage them). Comment back 
here with updates that have been made and when the package is ready for a 
re-review.

## General package development

- [ ] REQUIRED: Package files exceed the 5MB size limit.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
GeneExpression, Transcription, Sequencing, ATACSeq, Microarray, Metabolomics,
Proteomics, Epigenetics, Cheminformatics, Transcriptomics,
DifferentialExpression, ExperimentalDesign, Normalization, Preprocessing,
Bayesian, Regression, ExonArray, RNASeq, OneChannel, TwoChannel, MicroRNAArray,
mRNAMicroarray, ProprietaryPlatforms, CellBiology, BiomedicalInformatics,
FunctionalGenomics, SystemsBiology, ImmunoOncology, AlternativeSplicing,
DifferentialSplicing, BatchEffect, MultipleComparison, QualityControl,
TimeCourse, DataImport

## NAMESPACE

- [ ] REQUIRED: Function names should use camelCase or snake_case and should not include '.'.

## R code

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 4 lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 257 lines that are not.

Best,
Kayla

**Comment by TylerSagendorf** [comment] 2024-10-17 17:06
@Kayla-Morrell Thank you for taking the time to review the package. I have either addressed these points in the latest changes or provided reasoning as to why they weren't addressed below.
1. DESCRIPTION: these biocViews are not strongly related to the TMSig package. My guess is they got suggested because of the `limma` dependency or some packages in the Imports field.
2. NAMESPACE: `cameraPR.matrix` is an S3 method (not S4 only because `limma::cameraPR` is not), so I don't believe I'll be able to remove the '.'
3. Multiples of 4 spaces for line indents: the 257 lines flagged are all cases like those below. If possible, I would like to keep them as-is since the extra blank space at the beginning significantly improves my ability to read the code, and it somewhat reduces the number of lines

<img src="https://github.com/user-attachments/assets/1faaac61-e1de-4258-b372-f57d82140adf" height=60></img>
<img src="https://github.com/user-attachments/assets/fa6353ce-fcc7-49ac-8bbd-4f49d0906d30" height=180></img>

Best,
Tyler

**Comment by Kayla-Morrell** [comment] 2024-10-24 22:04
@TylerSagendorf - Thank you for making the necessary changes and/or providing reasoning. I have looked over everything and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment] 2024-10-25 13:22
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/TylerSagendorf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TMSig")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TMSig

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-10-25 13:22 UTC
Labels: OK, 3a. accepted
