### ISSUE TITLE
PoTRA

### ISSUE THREAD

**Issue by ghost** [Bioconductor/Contributions#1019] opened 2019-02-20 00:37 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Bioconductor-PoTRA/PoTRA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Bioconductor-PoTRA** [comment] 2019-02-21 00:14
I completed the version bump and loaded in the pre-build file for PoTRA. I originally had post-build files loaded into github.

**Comment by Bioconductor-PoTRA** [comment] 2019-02-23 15:01
The BiocCheck states:
* Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    * ERROR: Maintainer must register at the support site; visit
      https://support.bioconductor.org/accounts/signup/ .

**However, I am a subscriber and am registered under the same email, that I used to create the github account for the PoTRA package.**

**Comment by Bioconductor-PoTRA** [comment] 2019-02-23 15:58
The BiocCheck states:

* Checking for bioc-devel mailing list subscription...
  
  * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
    Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
  
  * ERROR: Maintainer must register at the support site; visit
    https://support.bioconductor.org/accounts/signup/ .

**However, I am a subscriber and am registered under the same email, that I used to create the github account for the PoTRA package.**

**Comment by LiNk-NY** [comment] 2019-02-26 15:17
Hi Chaoxing Li, Li Liu, and/or Valentin Dinu, @Bioconductor-PoTRA 

We would prefer that you do not use the `Bioconductor` name in your 
GitHub user name. It makes our users think that you are affiliated with
the Bioconductor core team.

With regards to the error, are you sure you registered those accounts with
the same email? Please verify your registration. I've checked manually
and your email address is not found. 

Best regards,
Marcel

**Comment by Bioconductor-PoTRA** [comment] 2019-02-26 16:02
Hi Marcel,

I’m not listed in the description text.
I am part of the post-development team.
And am working with Dr. Dinu to submit the PoTRA package to Bioconductor.

I can change the github. I added it because the PoTRA github name was already taken.

Thank you,
Margaret

**Comment by LiNk-NY** [comment] 2019-02-26 16:14
Hi Margaret, @Bioconductor-PoTRA 

The maintainer of the package has to be registered on Bioc-devel and
the support site. Please have the owner of the `***** at asu.edu` email
address register for those websites. 

Best,
Marcel

**Comment by LiNk-NY** [comment] 2019-03-05 20:40
Hi Margaret, 
Can you give an update on the status of the warnings/errors?

Thanks,
Marcel

**Comment by LiNk-NY** [comment] 2019-03-05 20:43
DUPLICATE of #1029 
https://github.com/Bioconductor/Contributions/issues/1029

**Closed by LiNk-NY** 2019-03-05 20:43 UTC
Labels: 2. review in progress, ERROR, TIMEOUT, WARNINGS
