### ISSUE TITLE
dominoSignal

### ISSUE THREAD

**Issue by jmitchell81** [Bioconductor/Contributions#3416] opened 2024-05-13 14:13 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/FertigLab/dominoSignal

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2024-05-20 13:22
Please see [previous comments](https://github.com/Bioconductor/Contributions/issues/3259) on initial submission.  In summary:


**vignette**

- [ ] Please show things like options and set.seeds to users so they can
  accurately run and reproduce the code in the vignette.

- [ ] We don't allow data to be on github. can the data retrieved from github
  also be moved to a trusted site like zenodo.

- [ ] Vignette code must be executable. Currently no code is evaluated. 


**General**

- [ ] There is currently no interop with Bioconductor standard classes for
  single cell.  Please adjust package to also account for this and show
  examples. See SingleCellExperiment packages/class.

- [ ] Packages used in vignettes and examples must be on CRAN or Bioconductor.  

It also appears the re-naming is not complete:
```
R CMD build dominoSignal 
* checking for file 'dominoSignal/DESCRIPTION' ... OK
* preparing 'dominoSignal':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘domino2.Rmd’ using rmarkdown

Quitting from lines  at lines 24-32 [libraries] (domino2.Rmd)
Error: processing vignette 'domino2.Rmd' failed with diagnostics:
there is no package called 'domino2'
--- failed re-building ‘domino2.Rmd’
```

**Comment by jmitchell81** [comment] 2024-05-20 14:57
Hello @lshep. My apologies for this issues that were carried over from the last submission. We had an issue with our GitHub action for pushing development changes to this submission branch. I will have these resolved quickly.

To your point about data from GitHub, is this in regards points in the vignettes when data from the cellPhoneDB ligand-receptor database is downloaded from https://github.com/ventolab/cellphonedb-data/archive/refs/tags/v4.0.0.tar.gz ? This is data curated by another laboratory that we do not have permission to re-host on zenodo. We could use a toy data base for vignette examples if need be while directing to this data base resource in the documentation if we are not allowed to directly download from this source in the scripting of the vignette.

**Comment by lshep** [comment] 2024-05-20 15:01
you can leave the github data for now and we can look into further in the review.

**Comment by jmitchell81** [comment] 2024-05-20 19:15
Thank you @lshep. I have corrected our submission branch at HEAD. We're ready for your review.

**Comment by hpages** [comment] 2024-06-19 01:08
Hi @jmitchell81,

Here is some immediate feedback:

1. I still don't see any `set.seed()` calls in the HTML vignettes.

2. You still have at least one occurence of `domino2` in your doc:

   ![image](https://github.com/Bioconductor/Contributions/assets/8810451/7032adf3-b245-4cd4-8f08-cfb6f1b3173d)

   Please make sure to find and correct them all.

3. It doesn't seem that you use standard markdown syntax in your .Rmd files. As a consequence there are many small cosmetic problems with the rendering of the HTML vignettes. See for example `\underline{named} vector` or `{SingleCellExperiment}` here:

   ![image](https://github.com/Bioconductor/Contributions/assets/8810451/2315c446-ada9-4662-9980-da98226ddf90)

4. Four mysterious lines of code right below the title of the vignette and before any text:

   ![image](https://github.com/Bioconductor/Contributions/assets/8810451/b4faf20d-5e99-40ed-be6b-0af7d1f2b012)

   That's quite an unusual and pretty dry way to start a vignette! What is this code? What does it do? Why is it here? Does it work properly without explicitly loading any package first? What package(s)?

5. For example, if I run these four lines of code in a fresh R session and try to display the `dom` object, I get hundreds of screens of output. This is unfortunate because domino objects actually have a `show()` method whose purpose is to prevent that. But that method is defined in the **dominoSignal** package and since the package is not loaded the method is not found. Or maybe it's because the package does not export the method, I'm not sure. In any case you need to export that method.

6. Many of the examples in the man pages use a non-exported non-documented symbol (`dominoSignal:::pbmc_dom_built_tiny`). This is not good practice. You should only expose symbols that are exported and documented to the user.

Please address before I take a closer look at the package.

Thanks,
H.

**Comment by hpages** [comment] 2024-07-18 22:19
Hi @jmitchell81,

Do you intend to follow up on this submission? Let me know if you have any questions.

Best,
H.

**Comment by jmitchell81** [comment] 2024-07-18 22:45
Thank you for checking in @hpages. Coincidentally, our updates addressing your feedback were just finished today. The HEAD branch of our package is ready for your review.

Best regards,
Jacob

**Comment by vjcitn** [comment] 2024-07-18 23:24
plz bump version and push so single package builder processes

**Comment by jmitchell81** [comment] 2024-07-19 15:34
Thank you @vjcitn. I've pushed to the git.bioconductor.org repo. The version number has been bumped to 0.99.3 . The commit id should be f660117. The full id posted by the bio-issue-bot above appears to be correct.

**Comment by hpages** [comment] 2024-07-30 18:13
@jmitchell81 Thanks for these changes.

Two more things and the package should be good to go:

7. You still have many occurences of "domino2" in your source code. Note that there are plenty of tools that let you find all occurences of a given word in your source code (e.g. most GUI provide such a tool). Please take the time to familiarize yourself with these tools. Finding all occurences of a given word in your code is such a common task that it's an essential developer skill.

8. Installation section in the "Get Started with dominoSignal" vignette: Never install a Bioconductor package from Github as this will typically mix-up packages from different Bioconductor versions, leading up to obscure errors, incorrect results, and a lot of confusion and frustration for all parties involved. Please show the proper/safe way, which is to use `BiocManager::install()`. See for example https://bioconductor.org/packages/SummarizedExperiment

Thanks again,

H.

**Comment by jmitchell81** [comment] 2024-07-30 19:31
Thank you for your feedback @hpages . 

For comment 7 on occurrences of "domino2" in our source code, I found 6 occurrences in comments within our tests and one occurrence in the NEWS.md signifying where we changed the package name. Were there other occurrences you found that we need to address?

**Comment by jmitchell81** [comment] 2024-08-05 18:18
Hello @hpages. We proceeded with addressing your comments to remove mentions of the old "domino2" package name and to update the installation instructions to use biocManager. We have, however, left in one instance of "domino2" in NEWS.md that we'd like to keep to signify the version at which the package name was changed to "dominoSignal". We await your further review and appreciate your feedback.

**Comment by hpages** [comment] 2024-09-02 16:05
Thanks for the changes.

Best,
H.

**Comment by lshep** [comment] 2024-09-03 15:59
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jmitchell81.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dominoSignal")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dominoSignal

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-09-03 15:59 UTC
Labels: OK, 3a. accepted
