### ISSUE TITLE
MPAC

### ISSUE THREAD

**Issue by pliu55** [Bioconductor/Contributions#3329] opened 2024-03-11 16:06 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pliu55/MPAC

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2024-03-20 19:54
Thanks for this submission.  I'd suggest that code like 
```
# a matrix of RNA-seq data with rows as genes and columns as tumor samples
rna_tumor_mat = system.file('extdata/TcgaInp/log10fpkmP1_tumor.rds',
                            package='MPAC') %>% readRDS()
```
should be enhanced so that a Bioconductor data structure like SummarizedExperiment
is used to manage the features and samples in an interoperable and self-describing way.

The way you handle the acquisition of PARADIGM is not standard.  It is nice to offer the
user a helper that obtains a binary from github, but in general we do not advocate dependence
on resources lodged only in github because they can disappear at will.  We prefer not to see
github URLs in code in packages in Bioc.

**Comment by pliu55** [comment] 2024-03-20 20:31
Thanks for all the suggestions, @vjcitn. I will utilize SummarizedExperiment as you recommended. 

For PARADIGM, I will remove the github URLs from the code. This will likely lead to reduced coverage for the testing function, but I will put a note in the vignette to describe this. Does this plan sound ok? I would like to have your input first before moving ahead. Thanks.

**Comment by lshep** [comment] 2024-03-27 14:44
That sounds like a good approach

**Comment by pliu55** [comment] 2024-04-03 21:33
Hi @vjcitn and @lshep,

Thanks again for your suggestions. I have improved the [MPAC package](https://github.com/pliu55/MPAC) accordingly. All the changes are listed in the [NEWs.md](https://github.com/pliu55/MPAC/blob/main/NEWS.md). Specifically,

- Use of SummarizedExperiment objects
  - I replaced the matrix objects by SummarizedExperiment objects in the following functions:
    - `ppCnInp()`
    - `ppRnaInp()`
    - `ppPermInp()`
    - `runPrd()`
    - `runPermPrd()`
    - `pltNeiStt()`
  - In addition, the newly added `ppRealInp()` function also uses SummarizedExperiment object.
  - Please note that, for the input of `ppCnInp()`, `ppRnaInp()`, and `ppRealInp()`, I still keep matrix objects. The reason is because I hope this will save user efforts on converting matrix objects to SummarizedExperiment objects, given that most SummarizedExperiment objects are constructed from matrix. 
- Remove PARADIGM GitHub URL
  - The URL has been removed from the R code. A message has been put in place in case user did not supply PARADIGM binary when running the function `runPrd()` and `runPermPrd()`. 
  - The testing function no longer downloads PARADIGM binary automatically.
  - A note has been put in the vignettes to explain the dependence of PARADIGM binary.

**Comment by pliu55** [comment] 2024-04-04 19:17
Hi @vjcitn and @lshep,

The [build report](https://bioconductor.org/spb_reports/MPAC_buildreport_20240404150652.html#nebbiolo1_buildsrc_anchor) above gave an error as 

> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called metapod

I suspect this could be an issue with the testing server, not my package, because __metapod__ is [a valid Bioconductor package](https://www.bioconductor.org/packages/release/bioc/html/metapod.html).  

Could you please give me some suggestions on how to proceed next? I will be appreciated. Thanks.

**Comment by pliu55** [comment] 2024-04-04 22:32
Hi @lshep and @vjcitn,

According to the [build report](http://bioconductor.org/spb_reports/MPAC_buildreport_20240404181910.html) above, my package has pass all the tests except the error below:

>  ERROR: Subscribe to the Bioc-devel mailing list by going to
>      https://stat.ethz.ch/mailman/listinfo/bioc-devel

I have subscribed to the Bioc-devel mailing list using the email (wrk.smnr+bioconductor@gmail.com) listed in [DESCRIPTION](https://github.com/pliu55/MPAC/blob/main/DESCRIPTION) this morning, therefore, I am not sure why the error above is still reported. Please advice how to proceed next. Thank you.

**Comment by lshep** [comment] 2024-04-05 12:19
There is often a confirmation email that gets sent. Can you please check your spam folders to see if it ended up being marked as spam?

**Comment by pliu55** [comment] 2024-04-05 13:48
Hi @lshep,

Thanks for your response. I did receive a confirmation email. I clicked the confirmation link and received a 'Welcome' email as below. In addition, I can visit [the subscriber list](https://stat.ethz.ch/mailman/roster/bioc-devel) by my email (wrk.smnr+bioconductor@gmail.com) and password. Also, I received two Bioc-devel email threads yesterday and this morning, one on 'Important Bioconductor Release Deadlines' and one on "duplicated entries with 'ExperimentHub(localHub=TRUE)'". Therefore, I think my email has subscribed to the Bioc-devel list.  

> Welcome to the [Bioc-devel@r-project.org](mailto:Bioc-devel@r-project.org) mailing list!
>
> To post to this list, send your message to:
>
>  [bioc-devel@r-project.org](mailto:bioc-devel@r-project.org)
>
> General information about the mailing list is at:
>
>  https://stat.ethz.ch/mailman/listinfo/bioc-devel
>
> If you ever want to unsubscribe or change your options (eg, switch to
> or from digest mode, change your password, etc.), visit your
> subscription page at:
>
>  https://stat.ethz.ch/mailman/options/bioc-devel/wrk.smnr%2Bbioconductor%40gmail.com
>
> You can also make such adjustments via email by sending a message to:
>
>  [Bioc-devel-request@r-project.org](mailto:Bioc-devel-request@r-project.org)
>
> [I omitted the rest .... ]

**Comment by lshep** [comment] 2024-04-05 14:01
interesting. I don't see it in the member management section nor am I able to manually enter the email and see it.  We will reach out to the list administrators to try and get more information but for now when you are assigned a reviewer they can ignore this error.

**Comment by Kayla-Morrell** [comment] 2024-05-10 01:43
@pliu55 - Thank you for submitting to _Bioconductor_. The package is in really good shape, I have just one requirement that needs to be addressed before I can accept it. Please see the requirement below. Please let me know when you are ready for a re-review.

## Data

- [ ] REQUIRED: For all the data in `inst/extdata/` there needs to be documentation for in an `inst/scripts/` directory. The scripts in this directory can vary. It's most important to have a related script that documents clearly how the data was generated and source information. It should include any source URLs and any key information regarding filtering or processing. It can be executable code, sudo code, or a text description. Users should be able to download and roughly reproduce the file or object that is present as data.

Best,
Kayla

**Comment by pliu55** [comment] 2024-05-12 16:12
Hi @Kayla-Morrell,

Thank you for reviewing this package and your helpful suggestion. I added documentation in `inst/scripts/` to describe the source and derivation of all the data in `inst/extdata/`. Each Rmd file in `inst/scripts/` corresponds to a folder in `inst/extdata/`. The Rmd files contain text describing where the data was obtained as well as related URLs. It also contains R code showing how files were generated. Hope this documentation is clear.

I pushed a new version of this package as above. For some reason, the build report has an error saying my email address (wrk.smnr+bioconductor@gmail.com) is not subscribed to Bioc-devel. But this email address has been subscribed to Bioc-devel and it keeps receiving emails. Also this email address is in the [subscriber list](https://stat.ethz.ch/mailman/roster/bioc-devel). So, this error is not true.

**Comment by Kayla-Morrell** [comment] 2024-06-02 21:09
@pliu55 - Thank you for making the necessary changes. I have looked them over and everything looks good. I'm more than happy to accept the package.

@lshep - Just wanted to be sure you see that there is still an issue with the mailing list. I'm going to accept the package regardless and hope this issue can be resolved.

Best,
Kayla

**Comment by lshep** [comment] 2024-06-07 15:50
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pliu55.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MPAC")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MPAC

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-06-07 15:50 UTC
Labels: ERROR, 3a. accepted
