### ISSUE TITLE
CellTrails

### ISSUE THREAD

**Issue by dcellwanger** [Bioconductor/Contributions#743] opened 2018-04-30 06:42 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/dcellwanger/CellTrails

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2018-04-30 11:38
@lshep will review this package, but it seems like it does not use the mature [SingleCellExperiment][1] representation or any of the related single cell and [GenomicRanges][2] packages in Bioconductor. Your package would be much more valuable to the community if it interoperated via this mature infrastructure. 

I'm also concerned about the broad and seemingly redundant graphical-related dependencies, including as implied in the vignette on a third party project; are these really necessary for the  core features of your project? Many dependencies make packages very fragile.

Your vignette is currently essentially one large code chunk with words at the beginning and end, but would be much better if the text, code, and output were integrated in a way that explains the operations being performed and the output produced.

Others in the single cell community (e.g., @LTLA @drisso ) might have additional comments.

[1]: https://bioconductor.org/packages/devel/SingleCellExperiment
[2]: https://bioconductor.org/packages/devel/GenomicRanges

**Comment by LTLA** [comment] 2018-04-30 11:44
At least a few of your custom slots can be stored as `int_metadata` or `int_elementMetadata` or `int_rowData`, depending on whether it makes any sense for those slots to respond to subsetting. We are currently revising the developer instructions in _SingleCellExperiment_ for defining new methods that use the internal data slots; this may be a good opportunity to get involved.

If the graph needs to be subsetted as well (not that I think it makes scientific sense to do so), it may also be worth considering the work that @dvantwisk has done for _LoomExperiment_.

**Comment by drisso** [comment] 2018-04-30 18:49
I agree with @LTLA that most if not all the custom slots can be fit naturally into a SingleCellExperiment object. If there is really a need for something special, you should at least extend SingleCellExperiment (or we may consider adding it to the SingleCellExperiment class, if general enough).

**Comment by dcellwanger** [comment] 2018-05-01 05:51
Thank you, Martin Morgan (@mtmorgan), Aaron Lun (@LTLA) and Davide Risso (@drisso), for your initial comments and Lori Ann Shepherd (@Ishep) for taking your time to review our package.
 
Our package accompanies a manuscript that is currently in its final review stage (in Cell Reports, where is has been "accepted in principle"). As soon as it gets formally accepted, we are happy to provide the article to Lori Ann, as it will help to understand the novelties of this package.

Regarding the issue on CellTrails’ dependency on a third-party project: CellTrails reconstructs a branching (developmental) trajectory from gene expression data and stores the trajectory information in a graph structure. Since we did not find a proper implementation of a planar graph embedding within R, we need to make use of a graph layout algorithm provided by third-party software. We implemented a function to export the reconstructed trajectory graph information into the generally accepted _graphml_ graph file format, which can be interpreted by most graph analysis software packages. Please note that CellTrails requires this step only to properly draw the graph. Subsequent analyses and visualizations are computed in R; an import function is provided, respectively. Some of these additional useful but non-essential export/import functionalities were requested by early adopters of our package and these users unanimously agreed that they simplified the analysis of the trajectory graph using this third-party software.

Regarding the issue on the vignette. We would be very pleased if we could provide the detailed tutorial (see our CellTrails project pages site: https://dcellwanger.github.io/CellTrails/), as referenced in the vignette, along with the package. However, the compiled detailed tutorial is about 6MB and therefore triggered a file size warning on our local BiocCheck. Since we intend to extend the functionalities of the package in the future, which eventually will result in an increase of the vignette’s file size, we decided to provide a general overview of the workflow in the package vignette and reference to the project page for the detailed tutorial (similar to the structure of the _monocle_ package [http://10.18129/B9.bioc.monocle]).

**Comment by dcellwanger** [comment] 2018-05-01 06:02
Regarding the SingleCellExperiment class. We truly appreciate Aaron’s and Davide’s valiant effort to implement a unified class for the analysis of single-cell expression data. When we started implementing the package, we decided to extend the ExpressionSet class, as its slots were sufficient to represent single-cell and population-based RT-qPCR and log-normalized RNA-Seq counts, and it nicely stored and printed the experimental meta-information. CellTrails is intended to be used downstream of QC and normalization and therefore, raw counts, spike-ins and size factor information are neglected. On the additional slots of a CellTrailsSet:
* `eigen`: contains information on the learned manifold (list with eigenspace and eigenvalues) from the expression data; we adapted the concept of spectral embedding and therefore, its latent space can be of higher dimension than the original space; we argue that using the slot `reducedDims` would be misleading. Further, `reducedDims` is a list and would potentially enable the storage of multiple lower-dimensional manifolds of the data. Since CellTrails’ subsequent steps operate on only one of those latent spaces, it would important to indicate which manifold was selected (by the user). This would need an additional slot called `reducedDimsMetadata` in the SingleCellExperiment object for listing the name of the selected manifold. Here, we would also store the eigenvalues from the spectral embedding, since this information is required to determine the proper number of latent dimensions and to subsequently truncate the eigenspace.
* spanForest: contains the information on the trajectory backbone graph and can be a forest, i.e., a graph with multiple tree components. It is currently stored as list of `igraph` objects. We assume, that we would need to store the list along with the experimental metadata in the slot `int_metadata` of a `SingleCellExperiment`.
* CellTrails’ subsequent steps are performed on a single user-selected tree of the forest. Therefore, from here on, the analysis is performed on a subset of samples (indicated in the slot `useSample` of a `CellTrailsSet`). We agree, that this information could be naturally stored in the `int_colData` slot of the `SingleCellExperiment` object.
* The `CellTrailsSet` slot `trajectory` contains data on the trajectory fit, i.e. the alignment of single samples onto the trajectory backbone. It is a list with the projection error (numerical vector), the fitted trajectory graph (`igraph` object) and a `data.frame` indicating the type of each sample on the trajectory graph (i.e., branching point, leaf or user-defined terminal end). It makes sense to store this information in one object logically; also the mapping between the `igpraph` nodes and the sample metadata can be better maintained. We assume, that we would need to split this information up in a `SingleCellExperiment` object into the slots `int_metadata` and `int_colData`, which would make code maintenance more difficult.
* The slot `layout` contains the trajectory layout, which is a 2D representation of the trajectory. As aforementioned, it may be composed of a subsample of cells. We cannot store this information in `reducedDims`, as it violates the requirement that the number of rows is equal to the total number of samples.
* The slot `trails` contains information on the user-defined developmental trails on the computed branching trajectory: a list of lists containing the path (`igraph` object) on the trajectory graph, the pseudotime (numerical vector), and the sample names (character vector) per trail. We assume, that we would need to store the list along with the experimental metadata in the slot `int_metadata` of a `SingleCellExperiment`.
 
We also provide an implementation of `show`, which gives a digest of the information contained in a `CellTrailsSet`. Every slot shown can be accessed with a getter method. This is particularly helpful to keep track of each analysis step.
 
To keep the source code well-arranged, we would need to extend the `SingleCellExperiment` class, similarly to our current `ExpressionSet` extension. Additionally, we would need to implement the ExpressionSet getters (e.g., featureNames, exprs, usf.), since our package makes use of these functions. Therefore, we would be very grateful if we could perform this step in a later release of CellTrails. We extended the current package implementation by a function allowing the conversion of a `SingleCellExperiment` into a `CellTrailsSet` and vice versa (similar to `scran::convertTo`).

**Comment by mtmorgan** [comment] 2018-05-01 09:58
Extending ExpressionSet was an (understandable) design mistake; a modern approach would extends SummarizedExperiment, which is what SingleCellExperiment does. It doesn't make sense from a development perspective to release an inappropriate class intending to update it in the future -- the inappropriate class will be saved by various users, and they will be forced to update these and become familiar with your new representation. And of course speaking for myself it is very easy to intend to do something but not actually ever do it. It would be a mistake to implement ExpressionSet accessors (e.g., `featureNames()`, `featureData()`) instead of updating your code to use SummarizedExperiment / SingleCellExperiment accessors (e.g., `rownames()`, `rowData()`).

It might be surprisingly easy to update your class definition and implementation, the underlying conceptual building blocks are the same.

**Comment by mtmorgan** [comment] 2018-05-01 10:05
With respect to your vignette, if the full vignettte processes in a timely manner then I would not worry about the small excess in the final size of your package. On the other hand if the vignette requires excessive computation then I will return to my original comment, which is that you provide a code chunk without context, and the context must be provided.

Your package does not have formal tests, so it is important that the code be evaluated _somehow_ to avoid 'bit rot'. In lieu of tests, evaluated examples and vignettes become a key component of this step in software quality assurance.

I understand that users request features, and that it is very tempting to provide them. The down side of this is that your package becomes very fragile (because it depends on an increasingly large and rapidly changing code base outside your control) and difficult to maintain (because of the increasingly complex logical constraints your earlier design decisions impose on subsequent development). This is the voice of experience speaking, urging you to carefully consider each feature you wish to expose.

**Comment by drisso** [comment] 2018-05-01 13:45
Just to add another voice echoing @LTLA and @mtmorgan comments, I am really convinced that in the long term your package will benefit a lot from using (or inheriting from) SingleCellExperiment (or at least SummarizedExperiment). As Martin said, it is very little effort up-front to make this change now and it will save you a lot of headaches going forward.

I totally understand your point of view of having your own object, but I would strongly suggest that at least it inherits from SingleCellExperiment (or SummarizedExperiment) rather than ExpressionSet.
If your object inherits from SingleCellExperiment, for instance, an user could simply use other packages for QC and normalization (which you said is not the focus of your package) and seamlessly integrate your package into their workflows without the need of any coercion methods.

One more thing about extending SingleCellExperiment vs just using it. As @LTLA said there is really nothing in your object that could not be fit into a SingleCellExperiment, but I acknowledge that with the current documentation of SingleCellExperiment this is not obvious. We are willing to work with you in making that more clear and using your package as a use case to write a "developer guide" on how to use SingleCellExperiment in one's package. For instance by defining methods for specific internal slots etc.

**Comment by dcellwanger** [comment] 2018-05-02 03:44
Thanks, @mtmorgan @LTLA  and @drisso .  We greatly appreciate your time and your comments. 

In my experience, though, it is always worth going the extra mile (within reason) and to add features that improve the usability of software (modules). User-feedback cycles are essential in a good software development process. One should keep in mind, that tools should not only make genomic data accessible to tech-savvy computational biologists, but particularly also to bench scientists. Here, good (rather than `quick-and-dirty`) data visualizations and simple workflows are tremendously helpful to analyze, understand, and interpret the data. In line with that, I think that accessing the genomic feature and sample data with `featureNames`, `featureData`, `sampleNames`, `phenoData`, usf., as implemented in the `ExpressionSet` was much more intuitive for a general user, than the more abstract accessor functions (`rownames`, `elementMetadata`, `colData`, usf.) of the `SingleCellExperiment`. The same holds for the `show` / `print` function of this class. 

I admit that my decision to extend the `ExpressionSet` class was likely also biased, since I was used to store my data in a object of this class from back then, when I was analyzing microarrays. Although it is tempting that I simply extend the `SingleCellExperiment` class by individual slots, if I go ahead and invest the time to change the architecture of the CellTrails package, I will then make the signatures of the relevant exported functions compatible with a `SingleCellExperiment` instance. This will allow a smooth integration of CellTrails into a Bioconductor-based ` SingleCellExperiment` analysis workflow. I am currently performing the requirement analysis of the CellTrails framework and will then determine the required adaptions of the package design and its implementation. Certainly, I will need to implement additional accessors and, unfortunately, need to separate the S3 plot method for a `CellTrailsSet` into single individual functions for a `SingleCellExperiment` to avoid masking. I see the point that keeping the naming of the `assay` slot list elements generic may be of advantage for certain cases, but I do not have a good feeling about the dependency of my functions on an yet undefined element. It should be able to represent log-normalized Log2Ex values / counts / intensities. Unfortunately, it seems that this list element is not strictly required and clearly defined in the class. I will stick to the `logcounts` element, albeit the term _counts_ is not accurate in any case and it is described in the vignette as element containing the log-normalized expression data in _most_ cases.

Please note, that we got word today that the manuscript is accepted. Thus, we need to have a functional package available as soon as the article gets published. I am very excited to implement the required adaptions, as long as they can be finished within a reasonable time frame. I would like to avoid to have two parallel package versions.

**Comment by LTLA** [comment] 2018-05-02 23:58
With respect to making critical changes earlier rather than later; perhaps an anecdote from my past may be helpful. This is in relation to the _diffHic_ package, which I submitted 3-4 years ago. The package reviewer at the time was Nate Hayden, if I recall correctly. He made a number of suggestions that I ignored at the time, because I was hurrying to finish my PhD and just wanted the package to get in. With the benefit of hindsight, I should have listened to him. Here are the consequences:

**Using a home-brewed S4 container:** I was young and foolish, and thought I would show off my coding flair by writing my own container. This was a Bad Idea, leading to all sorts of maintenance nightmares when my users (i.e., myself) tried to do something slightly unusual, e.g., subsetting and combining. In the end I ended up writing another package (_InteractionSet_) to implement the container that I needed - based on a _SummarizedExperiment_, no less. Then I needed to write update methods for my old serialized objects. Then I needed to deprecate my old S4 classes and all of its methods. This work spanned three release cycles (1.5 years), which I could have avoided doing the right thing at the start.

**Irregular unit tests:** I put my unit tests in `inst/tests` where they don't actually get run during the Bioconductor build process. In my defence, this was due to the fact that the tests were really long and would have triggered timeouts (in the age before we had a special build process for long tests). Needless to say, this causes some sleepless nights where I'm not sure that the package is doing as intended on computers other than my own. Another problem was that I wasn't using a formal unit testing system like _testthat_. If none of my tests failed, then it was fine; but if there was a failure, it was a real pain to track down. I lived in fear of those tests failing after a major refactoring - and still do, because I haven't gotten around to re-writing the tests using _testthat_.

**Static vignette:** I have a static PDF vignette, pushed through before it was outlawed on the Bioconductor package guidelines. Again, in my defence, compilation of the vignette takes several hours and involves a number of large data packages, so I couldn't really put it in the package itself. Nonetheless, this means that I need to manually rebuild the vignettes at every release, to check that the contents haven't changed and to ensure that the reported version numbers are up to date. This is a real pain - and now that I've been shut off from my former institute's servers, I can't even do this, because all of the relevant data files are still sitting on those servers.

To put things into perspective; for my popular packages, the number of commits after acceptance into BioC is easily greater than the number of commits before acceptance. Maintenance costs dominate initial development costs, moreso if the initial development was flawed (see my mistakes above). A month's delay to get things right is, quite simply, negligible in the lifetime of a useful package. Of course, for my not-so-popular packages, there's fewer commits involved, but that's not something to boast about: I don't write packages and expect people _not_ to use them.
 
Your package will only get better from switching to a _SummarizedExperiment_. If you need new slots in the _SingleCellExperiment_, talk to @drisso or me. If you play your cards right, you can effectively offload maintenance work to someone else (e.g., see comments in Bioconductor/SummarizedExperiment#10).

Finally, I wouldn't worry about the fact that your manuscript is accepted. You'll be going into BioC-devel, and it'll be 6 months until we get into BioC-release where most of your users will be. There's no rush. In my opinion, for bioinformatics and computational methods, the paper is always easy to write, and is effectively just a description/advertisement for the software package. The real struggle is that of maintaining and streamlining the implementation, especially when people start testing (and breaking) it.

**Comment by lshep** [comment] 2018-05-18 14:18
Hi there.  I wanted to chime in with a few things:

**General:** 
Echoing all the above -  it would be better to transition the code now to SingleCellExperiment rather than roll out the package with a less ideal class. Even if the intention is to update it later, this often is either not done or as mentioned than users will already adopt this old class and make the transition even more difficult and disruptive.  
Which it looks like you are in the process of so wonderful!! 

**LICENSE**
You can remove the LICENSE file as R is distributed with that License it is not
needed

**DESCRIPTION**
- [ ] Please use Author:/Maintainer: or Authors@R not both
- [ ] Remove LazyData: true.  This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large data
- [ ] As @mtmorgan initial commented. "I'm also concerned about the broad and seemingly redundant graphical-related dependencies, including as implied in the vignette on a third party project; are these really necessary for the core features of your project? Many dependencies make packages very fragile."  You gave a nice description of why the third party graphical party was utilized, which is acceptable but could you pair down the other R graphical dependencies to utilize fewer as normally there are very similar functionality and as mentioned graphical packages are very fragile.  

**NAMESPACE**
- [ ] If your package Depends on SummarizedExperiment it will probably be better to import(SummarizedExperiment) rather than singular functions. Users will than have full functionality on objects of this class instead of the limited functions of choice. Also if the main obj is a SingleCellExperiment, it actaully would be ideal to have SingleCellExperiment in Depends and import that as well since it looks like you are adopting this object. 


**Vignette:** 
- [ ] We really would like the vignette to be expanded and not solely redirected.  We will **require** the code to be executed in either vignette, man examples or tests to prove workable code. see @LTLA comments about irregular unit tests and static vignette ; he makes good points. Ideally its probably
better to have the code executed in a vignette or tests as the example data only needs to be generated once rather than regenerated in each of the man examples (which also will help with time).

**R Code**
- [ ] Based on It looks like you still might be making updates and modifying code so please let me know when you are finished and I'll glance at the R code.

**Comment by dcellwanger** [comment] 2018-05-19 02:18
Thanks @Ishep and @LTLA for your time and your comments.
 
**GENERAL**
I agree, that integrating `CellTrails` into a Biconductor-based single-cell analysis pipeline is much more convenient now, albeit multiple packages manipulating the same container and defining functions for the same class may lead to masking issues. I redesigned the package as suggested. It stores all relevant information in an object of class `SingleCellExperiment`.

**LICENSE**
Thank you for noting that. I removed the LICENSE file and updated the DESCRIPTION file.

**DESCRIPTION**
I removed the _Author_/_Maintainer_" and the _LazyData_ entry.

Regarding the dependencies on graphical software and packages. The third-party software is required layout the graph. This is essential for visualization of inferred expression dynamics and to extract single pathways toward a terminal phenotype for further downstream analyses. To our knowledge, there is no proper solution available (in R) for _planar weighted_ embedding of a graph. The procedure within `CellTrails` is straightforward and denotes only a few steps: `write.ygraph` exports the graph structure from the `SingleCellExperiment` object to the common `graphml` file format, which can be interpreted by the third-party software; the user layouts the graph and saves it, and `read.ygraph` enables the re-import into the R session. The function `trajLayout` stores the layout to the `SingleCellExperiment` object; here, `CellTrails` adjusts the layout internally, such that distances between data points (samples) represent the latent (pseudo-)temporal distance between adjacent samples. Frankly, we were testing a lot of alternative options, but did not find an ideal solution to avoid the dependency on this particular third-party software. On these grounds, we are open for alternative suggestions. 

Please note that the `igraph` package is not used for visualization, but for graph operations/manipulations. `CellTrails` imports two (non-standard) packages for visualization:`ggplot2` and `ggrepel`. The former is broadly used and well maintained; it is convenient as it generates `ggplot` objects, which can be adjusted by the user’s personal preference. The latter package is needed to repel overlapping text labels. I would be grateful if you could point out any redundancies I may have overseen.

**NAMESPACE**
I agree. The most recent version(s) of `CellTrails` depend on `SingleCellExperiment`. To avoid the warning triggered by the masking of `stats::start` and `stats::end` by `import(SummarizedExperiment)`, I would prefer to import only those function that are actually used – this was also recently suggested by Martin Morgan (@mtmorgan) on the Bioc-Devel mailing list.

**VIGNETTE**
We agree that referring to an external resource is not optimal. However, we really would like to provide a comprehensive and detailed vignette. A `CellTrails` analysis represents a whole workflow, individual steps of which are dependent on each other (proper checks are implemented). The previous submission/commit v0.99.3 contained the detailed vignette, which caused a server timeout. Building the detailed vignette takes about 2-3 minutes (on my 2015 MacBook) and is about 6.5MB. Not sure whether there is a reasonable solution to overcome the building and file size limitation. Please note that 90% of the code of the detailed vignette is evaluated. Further, the code in the examples is executed and I also added unit tests to prove workable code. 

**R CODE**
There won’t be major changes on the source code. I am looking forward to your feedback.

**Comment by dcellwanger** [comment] 2018-05-22 18:27
Hi @Ishep,
I addressed all your comments. The CRAN and BiocCheck seem to be OK on all OS.
I look forward to your review report.
-Daniel

**Comment by lshep** [comment] 2018-05-22 18:47
@dcellwanger  I'll try and have a review of the code for you within the next day. Cheers

**Comment by lshep** [comment] 2018-05-23 14:47
**NEWS**
- [ ] While very neat - please remove the cell traits at the top of the file (maybe move to README) and the spaces in 
= ==================================== =
essentially your news should become 
```
Version 1.0.0
======================================
+ First public release
```


**VIGNETTE**
Running through vignette at https://dcellwanger.github.io/CellTrails/

- [ ] The function showTrajInfo()  
doesn't end in a new line - add to code
```
  trajResiduals: MSE=NA
  landmarks: none
  trajLayout: none
Trail data: 
  trailNames: none> 
```

- [ ] 3.5 Using Alternative Methods
scran isn't loaded yet 
probably should start with a `library(scran)` else get errors
`Error in loadNamespace(name) : there is no package called 'scran'`

- [ ] 4.4 Altnerative Methods
Add `library(destiny)` for same reason as above with scran.

** inst/exdata ** 
Could you please also provide an inst/scripts/make-data.R that describes how these files were created (could be sudo code but some description of generation)


Please perform a version bump and comment back here when ready for me to look at again.

**Comment by dcellwanger** [comment] 2018-05-25 21:43
@lshep Thank you very much for you comments and the short turnaround time.

**NEWS**
Done.

**VIGNETTE**
•	Thanks for noting that. I extended the returned String of `showTrajInfo` by a new line.
•	I am wondering about your error `there is no package called ‘scran’` - it looks like the package is not installed. I can add the `library` command to the vignette if strictly required, but generally I try to avoid loading packages unnecessarily. If only one or two specific functions of a comprehensive package are needed, I prefer to call the function directly (e.g., via `scran::myFunction`). This lowers the odds of name clashes. Also, (on a Mac OS, at least) the number of loaded DLLs is limited (by default) to 100. The package `scran` loads already 46 DLLs, `destiny` adds another 39 – with those two packages the limit is almost reached (85 DLLs, including the 6 DLLs loaded by the standard packages). Please note that CellTrails can still be loaded (it adds another 7 DLLs), but the potential of loading packages, which might be more relevant for a user in a specific context, to an R session gets very limited.

**inst/exdata**
Done.

**Comment by lshep** [comment] 2018-05-29 11:42
If I was a naive user I may not be aware that all that was needed was a library call but considering you mention scran and destiny in the text section above it, I suppose it is ok. The other option is to use a dontrun{}  section to show the library call but not actually have it loaded.

**Comment by dcellwanger** [comment] 2018-05-30 00:08
@lshep I am sorry for the delay - it looks like the `S4Vectors` implementation was updated. I was not able to reproduce the error thrown on your server on my local test systems (R 3.5 w/ Bioc devel @ Windows and Mac OS). I assumed that an error got triggered by subsetting a `DataFrame` object using `[[x]]` and, indeed, replacing it with `[,x]` resolved the issue. 

The warning which is left indicates a check time exceeding the 5 min requirement (on Windows and OS X). Please let me know if I need to resolve that.

Regarding the vignette. I see your point. The most recent version suggests the `library` call using a 'dontrun' block in the code snippet; also the text was extended, respectively.

**Comment by lshep** [comment] 2018-05-30 11:18
Actually the WARNING is coming from the R version dependency in the DESCRIPTION file:
 * WARNING: Update R version dependency from 3.4 to 3.5.
Which we do recommened updating as this is the version of R that the package will be released under and what we are testing on our systems.

**Comment by lshep** [comment] 2018-05-31 11:44
Ah sorry I was looking at a previous report -  The S4Vectors has been resolved as well I believe -  But I will have a glance at your package again within the next day or two for feedback.

**Comment by dcellwanger** [comment] 2018-06-04 18:38
@lshep We are excited to receive your feedback. Since our package has been adapted as requested to be fully compatible with a `SingleCellExperiment` object, we hope that there won't be additional major design changes needed. The paper will be published tomorrow and we would like to avoid having another major user interface update during the next days/weeks.

**Comment by dcellwanger** [comment] 2018-06-07 15:42
Thank you for your review and for accepting the package. We are excited about `CellTrails` being part of Bioconductor.

**Comment by mtmorgan** [comment] 2018-06-08 17:08
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/dcellwanger.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CellTrails\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CellTrails

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2018-06-08 17:08 UTC
Labels: 3a. accepted, WARNINGS

**Comment by mtmorgan** [comment] 2018-06-08 17:14
Your git repository contained a `doc/` directory. This directory is ignored by R during the build process, and anyway contains files that are larger than the maximum allowed in the Bioconductor git repository. For this reason I removed the directory before cloning to git.bioconductor.org. This may cause problems when synching with your github repository; if so please ask for help on the bioc-devel mailing list.
