### ISSUE TITLE
single

### ISSUE THREAD

**Issue by rocioespci** [Bioconductor/Contributions#2528] opened 2022-02-14 20:09 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/rocioespci/single

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-02-14 21:12
Please see https://contributions.bioconductor.org/docs.html#vignettes ... you should be using BiocStyle for consistency with the majority of submissions, and vignette should end with sessionInfo() invocation/output.

It would be good if some reference to scientific applications/literature would be provided to give context in vignette.  Your preprint should be referenced and vignette updated as it approaches publication status.

**Comment by vjcitn** [comment] 2022-02-14 21:16
You are not using any Bioconductor infrastructure in this package.  Would it not make sense to use a Biostrings DNAString container for your results?  Can you add metadata to the objects manipulated in the package so that they are not freestanding vectors of characters but have more scientific context bound to them?

**Comment by rocioespci** [comment] 2022-02-18 15:34
Hi @vjcitn .  I've updated the package in git-hub to include both suggestions. I've created the vignette with BiocStyle, and I results of consensus computation are now returned as a DNAString from Biostrings.

**Comment by vjcitn** [comment] 2022-02-23 16:09
Thanks, please remove > devtools::install_github("rocioespci/single") from the vignette.  Review can now proceed.  Consider using R markdown instead of Sweave formatting for vignette.

**Comment by rocioespci** [comment] 2022-02-25 09:36
Hi!
I've removed the  devtools::install_github("rocioespci/single") from the vignette. 
I had tried R markdown for the vignette but I keep getting errors when compiling using BiocStyle.

**Comment by lshep** [comment] 2022-02-25 13:48
A reviewer has been assigned to your package. Learn [what to expect][2]
during the review process.

**IMPORTANT**: Please read [this documentation][1] for setting
up remotes to push to git.bioconductor.org. It is required to push a
version bump to git.bioconductor.org to trigger a new build.

Bioconductor utilized your github ssh-keys for git.bioconductor.org
access. To manage keys and future access you may want to active your
[Bioconductor Git Credentials Account][3]

[1]: https://bioconductor.org/developers/how-to/git/new-package-workflow/
[2]: https://github.com/Bioconductor/Contributions#what-to-expect
[3]: https://git.bioconductor.org/BiocCredentials

**Comment by lshep** [comment] 2022-03-03 13:12
Your vignette syntax is still completely in Sweave and the vignette extension is Sweave (Rnw). You would have to update to Rmarkdown syntax and extension (Rmd) in order for BiocStyle/knitr to work properly.

**Comment by rocioespci** [comment] 2022-03-05 09:42
Yes, I know. I meant I had made an rmd file in rmarkdown format and I tried to compile that file with Biocstyle and I obtained errors which I didnt manage to solve. That is why  then I made all the vignette again in Sweave. The markdown file is not on the github package anymore.

**Comment by rocioespci** [comment] 2022-03-11 13:10
Hi @lshep 
I've done the corrections suggested by bioc-issue-bot and push the changes both to git0hub and bioconductor's git, also bumping the version in the description. I did not receive any message of the bot trying to build it again. Is there anything wrong? How should I proceed?

**Comment by lshep** [comment] 2022-03-11 13:17
would you mind trying once more to push a version bump to git.bioconductor.org?  We were having some issues with the SPB earlier in the week; I thought I resolved them but if not I can investigate further

**Comment by rocioespci** [comment] 2022-03-11 13:23
Sure. I changed my version in DESCRIPTION file (to 0.99.2), added,commited,pushed and I didn't get any email from the bot so far. Is this what you meant by "push a version bump" ?

**Comment by lshep** [comment] 2022-03-11 13:24
yes thank you; I'll investigate into why its not triggering.

**Comment by lshep** [comment] 2022-03-11 13:40
in the meantime I will trigger a build manually

**Comment by rocioespci** [comment] 2022-03-11 13:46
Cool, thanks

**Comment by nturaga** [comment] 2022-03-11 14:54
Hi @rocioespci Can you try to push a version bump please? (we'd like to see if the problem is fixed)

**Comment by rocioespci** [comment] 2022-03-11 15:06
Hi @nturaga 
Yes. Done. 
I still don't get any automatic e-mail. :(

**Comment by lshep** [comment] 2022-03-11 18:15
We are trying to track it down. currently all the other packages in the review system are working as normal so it is isolated to your package which is making it difficult

**Comment by lshep** [comment] 2022-03-11 18:47
Okay, I think we finally figured it out and hopefully should be resolved

**Comment by lshep** [comment] 2022-03-29 16:42
Thank you for your submission a few minor comments: 

# Build Report

- [ ] (optional) Consider adding a NEWS file. If a NEWS file is used properly package
  updates will be included in Bioconductor release.  See example release
  announcement: http://bioconductor.org/news/bioc_3_14_release/#new-software-packages

- [ ] (optional - strongly recommended) We always recommend including testing to
  ensure properly functioning packages. Consider adding unit tests. 

# README

- [ ] Update to Bioconductor installation instructions. BiocManager also does
  installation of github libraries and can what is already shown as a development but standard
  Bioconductor installation instructions should also be included
  

# inst

- [ ] Please include an `inst/scripts/` directory that describeds how the data
  in `inst/extdata` was generated including relavent source information.

# vignette

- [ ] Please update the installation section to include Bioconductor
  installation instructions.

# R code

- [ ] please use message instead of cat


Please address the above issues and comment back here when ready for a re-review.  Cheers

**Comment by rocioespci** [comment] 2022-04-05 14:23
Hi @lshep , 
I think I addressed all the comments you made. For the extdata, most of it is experimental data, so there is no script for that. I did add the script for those which are not. 

I think it's now ok for a re-review. 
Let me know :)

**Comment by lshep** [comment] 2022-04-05 15:11
@rocioespci is all the data in extdata simulated?  I was looking for some indication of how the files in extdata were created?  the inst/script describing how the files were generated/created could be code, sudo-code, or text but some indication of how they were created and any relevant source information

**Comment by rocioespci** [comment] 2022-04-05 15:21
It is not exactly simulated, it is experimental data. Fragments of DNA sequences that I measured. I guess that for the purpose of the package it is the same as simulated/invented data. I can add a text saying that.

**Comment by rocioespci** [comment] 2022-04-06 10:06
Hi @lshep !
I have added a txt file explaining that it is experimental/simulated data. Thus ready for re-review :)

**Comment by lshep** [comment] 2022-04-06 12:16
Thank you

**Comment by lshep** [comment] 2022-04-08 18:17
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rocioespci.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("single")`. The package 'landing page' will be created at

https://bioconductor.org/packages/single

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-04-08 18:17 UTC
Labels: OK, 3a. accepted
