### ISSUE TITLE
proBatch submission

### ISSUE THREAD

**Issue by ChloeHJ** [Bioconductor/Contributions#958] opened 2018-12-20 14:51 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/symbioticMe/proBatch/

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2018-12-20 17:49
ouch, that long list of dependencies looks like you've created a very very fragile package; are they all necessary? I strongly recommend you revisit the need for each dependency, trimming the functionality of your package to make it more maintainable and robust.

**Comment by Liubuntu** [comment] 2018-12-20 19:42
Hi @ChloeHJ , 

Please rethink and modify your package according to Martin's comments. (https://github.com/Bioconductor/Contributions/issues/958#issuecomment-449081049). 

Besides, the building report has some ERRORS, including grammar mistakes, tarball size too big and package versioning. Please go through your package and remove any unnecessary files. New package should start from version 0.99.0 at first submission and bump version to 0.99.1 and go on for any changes you made during review process. 

WARNINGS are also present with clear messages, e.g., R dependency version (should be >= 3.6), inconsistency about package imports between DESCRIPTION and NAMESPACE. 

These are important, please make sure to clear all ERROR and WARNINGS so that a technical review will be given later. Comment back here with any questions or concerns. 

Thank you for the contribution to Bioconductor!

Best,
Qian

**Comment by ChloeHJ** [comment] 2018-12-20 20:01
Dear revisions team,

Thank you for your feedbacks on the package, I made the submission by a
branch called "BIoconductor_submission" instead of the master, but I am not
sure if the revision has been done the branch or on the master, as many
comments are already considered in the submitted branch. Would it be
necessary to merge everything to master for an appropriate revision?

Thank you and best regards
Chloe

**Comment by Liubuntu** [comment] 2018-12-21 15:34
Hi @ChloeHJ , 

When you done setting up the web hook https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook, it said 

```Subsequent pushes to the default master branch of your repository will now trigger builds (only if the package version has been bumped), and the build reports will be posted to the issue you created in this repository. Note that pushes to branches that are not master, or non-default branches, are ignored.```

So you should merge all the new commits into master branch so that it triggers new builds. Don't forget the bump version when you need "Bioconductor/Contribution" to catch the updates. 

Best,
Qian

**Comment by ChloeHJ** [comment] 2018-12-21 15:41
Thank you Qian, will do shortly :)

**Comment by ChloeHJ** [comment] 2018-12-27 12:01
All changes have been merged to the master (version 0.99.1). We resolved all ERRORs and WARNINGs from build, check and Bioccheck. Thank you for your time and kind feedback,

Best regards,
Chloe

**Comment by Liubuntu** [comment] 2018-12-27 15:50
HI @ChloeHJ , 

Seems that the Bioconductor/Contribution still did not catch those changes. I could see those commits in "master" branch, but you do need to change the repository in the first comment under this issue to the following:  https://github.com/symbioticMe/proBatch/tree/master

After changing the repository, please remember to bump version again to 0.99.2 and see if the change has gone through. Thanks!

Best,
Qian

**Comment by ChloeHJ** [comment] 2018-12-30 10:10
Hi Qian,

The repository has been modified and version updated!

Thank you and best regards,
Chloe

**Comment by ChloeHJ** [comment] 2019-01-03 01:52
Hi Qian,

Sorry, I misunderstood adding the webhook part, I think we didn't put the URL into payload URL in settings, will do shortly, 

Thank you and best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-01-11 19:00
Hi @ChloeHJ , 

Just a reminder that we would expect update on the issue (with updates/questions/commits/comments...) within 2 weeks. If no response within 2 weeks of last comment, the issue would be closed. 

Thanks!
Qian

**Comment by ChloeHJ** [comment] 2019-01-14 09:13
Hi Qian,

We wanted to add the bioconductor link onto our webhook but the proBatch package is owned by my colleague and she is currently on a holiday and will only be back online in 3-5 days from today. Would there be a way to postpone the issue from being closed?

Thank you and best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-01-15 02:34
HI @ChloeHJ , 

I'll keep the issue open for your colleague comeing back. Thank you for the explanation. 

Best,
Qian

**Comment by ChloeHJ** [comment] 2019-01-15 21:43
Hi Qian,

The webhook was added to our github repository, could you please check if the building machine can catch the version bumps? 

Thank you and best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-01-16 19:34
Hi @ChloeHJ , 

After adding the web hook following [this](), bump the package version in DESCRIPTION in master branch, the building machine would catch it and have some automatic comments under this issue showing it with a new building report if all is set correctly. 

According here: https://github.com/symbioticMe/proBatch/commits/master, The lastest version bump was done on Jan 2nd. So you may want to bump version again to see if it is correct. 

Qian

**Comment by Liubuntu** [comment] 2019-01-22 15:18
Hi @ChloeHJ , 

Yes, the webhook has been set correctly and the building machine could catch commits and version bump right now. You can expect an initial review /comments within 2 weeks since the last successful build. 

Best,
Qian

**Comment by Liubuntu** [comment] 2019-01-31 17:22
Hi @ChloeHJ , 

Here is the initial review of your package. It is quite a big package with many functionalities and well written generally. Some issues to address for each section are summarized here. Please make effort to address all/most of them and comment back here with any questions. The `vignette` would be reviewed shortly and append later here. Thanks!

 ## DESCRIPTION
  
- "Title": add "in/for omic data" in the end to indicate the applicable data type?
- "Description": The description should be a relatively short but detailed overview of what the package functionality entails. It should be one or more complete sentences. The current one looks a bit more detailed, something like the following (or more succinct) would work (do your own modification whenever needed):

    `The proBatch package facilitates batch effects analysis and correction in
    high-thoughput experiments. It was developed primarily for
    mass-spectrometry proteomics (DIA/SWATH), but could also be
    applicable to most omic data with minor adaptations.  The package
    contains functions for diagnostics (proteome/genome-wide and
    feature-level), correction (normalization and batch effects
    correction) and quality control. Non-linear fitting based
    approaches were also included to deal with complex, mass
    spectrometry-specific signal drifts.`

- "Imports": Reminder that too many dependent packages makes your own package fragile. Also it doesn't make sense to import `tidyverse` because it is a collection of other packages but does not provide any specific functions.

## NAMESPACE
- Ok!

## R/
- `colors_for_annotation.R` L51:L69,
vectorize `granularity` value with the conditions and then call the `lapply` function just once to avoid almost duplicate code.
```{r}
if (length(granularity) == 1)
    granularity <- rep(granularity, ncol(annotation_df_numbers)
ann_col_covariate <- lapply(1:ncol(annotation_df_numbers),
                            function(i)
                                generate_colors_for_numeric(
                                    annotation_df_numbers[, i],
                                    i = i,
                                    palette_type = palette_type,
                                    granularity = granularity[i]
                                ))

```
- similar in `proteome_wide_diagnostics.R` L49. Pre-assign argument values (`dendroLabels`, `cex.dendroLabels`...) with conditions and only call `WGCNA::plotDendroAndColors()` once to avoide duplicate code.

- when using checking conditions with `setequal`, use `if (!setequal())` instead of `if(setequal() == FALSE)` to avoid checking twice. Grep `setequal` in your R scripts, this seemed to appear in multiple cases.

- `correlation-based_diagnostics.R` L299,418, avoid functions inside functions, make them as internal functions with prefix of ".", and then call this internal function inside the main exported function for better organization and debugging.

- `fit_non_linear.R` L6: typo? Should be `measurement` instead of `measurment`.

- `normalize.R` L104: Use `normalize_data <- function(..., normalizeFunc = c("quantile", "MedianCentering")...) { normalizeFunc <- match.arg(normalizeFunc); ...` so the default would still be "quantile" and at the same time, it checks the provided values and return error if doesn't match to either "quantile" or "MedianCentering". Go through your scripts and apply to appropriate places.

- `correct_batch_effects.R` L71,86,183,230,233, Seems like you want to use `\code{...}` instead of "`...`". Try to go through other documentations for similar issues if you intend to encompass those words in help page. Some other places with similar situation: include: `correlation-based_diagnostics.R`, L251,254. `fit_non_linear.R` L14. `initial_assessment.R` documentations. `proteome_wide_diagnostics.R` L8,10,17.

- SUGGESTION: Prefix non-exported functions with a ‘.’ for easy reference. Refer [here](https://www.bioconductor.org/developers/how-to/coding-style/) for Biocoductor coding style.
- SUGGESTION: Use ` <- ` instead of " = " for consistent style for variable assignment all through the code.

## man/

- The documentation of functions `center_peptide_batch_medians` and `correct_batch_effects` are using the same `@rdname` and sharing one `man/correct_batch.Rd` file. So for the `@description` and `@return` fields, please specify which corresponds to which, so that the help page doesn't look confusing to uses.

- `man/correct_with_ComBat.Rd`, the "title" is too long. Since you already have everything in "description", you should make a short and descriptive title with 1 sentence. (in `R/correct_batch_effects.R`::L164, put the whole paragraph within `@description`, anda short title in `@name`)

- `man/plot_protein_corrplot.Rd`::L51. Shouldn't it be a ggplot object instead of "nothing"?
- Same issue as in `man/plot_sample_corr_heatmap.Rd`::L43.

Cheers, 
Qian

**Comment by Liubuntu** [comment] 2019-01-31 21:07
Here are some additional comments. Please try to comment back here with any question, or commits, or updates within 2 weeks to keep this issue open. Thanks!

## vignette

- Add affiliations for the authors? 
- L248,275. Do not eval the `library(...)` in the vignette.
- The vignette looks really nice with explanations and details. Only that it looks a bit too long for users to quickly pick up the workflow with key functions. The current version is ok, but would also be nice to have a separate short one with an example data to go through the analysis. You can put both inside the vignette folder, and only include the `Installation` section once. 

## general

- remove the `NAMESPACE.rej` file from top folder.

**Comment by ChloeHJ** [comment] 2019-01-31 22:06
Thank you so much for your comments Qian, I will get back to you as soon as
possible :)

**Comment by ChloeHJ** [comment] 2019-02-01 16:33
Hi Qian,

I have made changes based on your comments but I had a question regarding the "imports". I tried to remove tidyverse from DESCRPTION/ NAMESPACE/ README and replace with smaller functions but the devtools::document() would automatically generate NAMESPACE including the tidyverse, and there will be an error when I go through check() with tidyverse removed. Could you please help me with these problems? 

p.s. I've addressed most of your comments, except the 1) the imports, 2) shorter vignette (we will soon prepare a shorter vignette), and 3) "..." issue where @param was devoted to explain what parameters can be added to "..." and I thought no changes were necessary. 

Thank you so much for your time and comments! 

Best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-02-01 18:48
Thanks for the quick update. I'll take a 2nd look and get back to you soon.

**Comment by ChloeHJ** [comment] 2019-02-06 14:01
Hi Qian, 

We just added a shorter version of vignette to our package. It would be great if you could kindly look at our vignette as well. Thank you so much for your reviews,

Best regards
Chloe

**Comment by ChloeHJ** [comment] 2019-02-07 10:45
Hi Qian,

After adding the second vignette to our package, there have been several issues e.g, exceed size requirements, exceed 5 mins check requirements (below). I am not sure if the settings need to be modified to remove these warnings and errors, or if these errors and warnings would persist by having the shorter vignette to our package, we are also in the process of preparing an Applications note to be submitted to Bioinformatics, we can have a shorter illustrations in this manuscript and remove the shorter vignette from our package. It would be great if you could kindly have a look at the vignettes and let us know what you would recommend, 

* creating vignettes ... OK
Warning: 'inst/doc' file
    'proBatch_vignette_brief.R'
  ignored as vignettes have been rebuilt.
  Run R CMD build with --no-build-vignettes to prevent rebuilding.

WARNING: R CMD check exceeded 5 min requirement

* Checking package size...
    * ERROR: Package Source tarball exceeds Bioconductor size
      requirement.
        Package Size: 5.4069 MB
        Size Requirement: 5.0000 MB

Thank you so much for your time and reviews, 

Best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-02-11 16:19
Hi @ChloeHJ , 

Here is the 2nd review of your package: 

## DESCRIPTION / NAMESPACE
- Did you try removing the `@import tidyverse` from "proBatch.R"? before removing `tidyverse` from DESCRIPTION imports?

## R
- correlation-based_diagnostics.R: L299. The `.corr_distribution` works like an internal function in your script, and you had the keyword internal. So you should remove the `@export` tag.

- correlation-based_diagnostics.R: L480. `corr_distribution_prot` is also nested inside the exported function. Can you also move it out like the above?

## man
- My previous comment about the `\code{...}` and \`...\` was about the different coding style in rmarkdown and roxygen2 to write the in-line documentaton. The "..." means anything you want to encompass or highlight in the help documentations, not the parameters to pass in function definition. I noticed that you are using "\`\`" quite a bit in roxygen2 documentation which should actually be `\code{xxx}`.

Best,
Qian

**Comment by Liubuntu** [comment] 2019-02-11 16:59
One more important thing for developing a new R/Bioconductor package is the interoperability with other existing / established packages in the same area. 

Interoperability is strongly encouraged in Bioconductor and would help with the usage of your own package. Consider interoperability with packages included in `RforProteomics`, and `mzR` which uses CDF (Common Data Format) to represent MS data in R without completely loading data into memory? Check here for other MS related _R / Bioconductor_ packages: http://bioconductor.org/packages/release/BiocViews.html#___MassSpectrometry

**Comment by Liubuntu** [comment] 2019-02-11 17:05
For the error of large size, and exceeding check time, try to make your example dataset (used in examples or vignettes or test functions) minimum but just big enough to show the functionalities. This is usually the case for making them fit into a Bioconductor package.

**Comment by ChloeHJ** [comment] 2019-02-12 11:27
Hi Qian, 

Thank you for your comments! I will look through them and get back to you soon, 

Best regards,
Chloe

**Comment by ChloeHJ** [comment] 2019-02-12 12:31
Hi Qian, 

Regards to the problem of large size, I was wondering if this was due to a wrong setting on the second vignette we produced because the size of data is 1.3Mb but the doc size goes 3.8Mb. Could you please have a closer look onto our second vignette (vignette_brief) and see if it's made correctly? 

Thank you so much! 
Chloe

**Comment by Liubuntu** [comment] 2019-02-15 15:15
Hi @ChloeHJ , 

Sorry for late reply. But I'll look into the short vignette get back to you shortly. 

Thanks,
Qian

**Comment by ChloeHJ** [comment] 2019-02-18 10:18
> One more important thing for developing a new R/Bioconductor package is the interoperability with other existing / established packages in the same area.
> 
> Interoperability is strongly encouraged in Bioconductor and would help with the usage of your own package. Consider interoperability with packages included in `RforProteomics`, and `mzR` which uses CDF (Common Data Format) to represent MS data in R without completely loading data into memory? Check here for other MS related _R / Bioconductor_ packages: http://bioconductor.org/packages/release/BiocViews.html#___MassSpectrometry

Regards to interoperability, the example data is in the same format as the ones in e.g. SWATH2stats, which is the output from openSWATH. However, we needed a data that explicitly shows the presence of batch effects, both continuous mass spectrometry-associated signal drifts and discrete batch effects. The data included in our package was one of the first large-scale proteomics dataset that explicitly showed the batch effects, which raised the notion to develop tools to correct for them. Therefore, we included a reduced openSWATH output of the data to show that the batch effect can be improved by utilizing our proBatch tool.

**Comment by ChloeHJ** [comment] 2019-02-21 16:34
Hi Qian, 

I modified the scripts based on the your comments, and resolved most of them, except for test/ and the vignette problem. I will soon generate tests and get back to you :)  

Best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-02-23 16:01
Hi @ChloeHJ , 

Thanks for those updates and sorry for delaying the review of your short vignette. I'll review them altogether next week. 

Best,
Qian

**Comment by Liubuntu** [comment] 2019-03-01 21:58
HI @ChloeHJ , 

Please see the following comments: 

## vignette
- Remove `proBatch_vignette_brief.R` and only keep the `.Rmd` files and `.png` files. Seems like it is generating one warning from your build report. 
- Rename your vignette as `proBatch.Rmd` and `proBatch_brief.Rmd` so
  it's more spontaneous and easier for users to browse your vignette
  using `vignette("proBatch")`.
- `proBatch_vignette_brief.Rmd`.

## R
- `fit_non_linear.R`:L14, mismatched braces in `(\code[loess_regression})`.

## tests
> test Unit tests are highly recommended. We find them indispensable for
both package development and maintenance. Two of the main frameworks
for testing are RUnit and testthat. Examples and explanations are
provided
[here](http://bioconductor.org/developers/how-to/unitTesting-guidelines/).

I am emphasing the unit test again here. As a large package with many
functionalities and hopefully to be widely used by users, good unit
tests could help you accurately locate issue source for later
maintenance. Otherwise, it's big pain when your package fails in some
day, and you spend huge amount of time trying to figure out where the
bug is. It would greatly enhance your package by adding unit tests (and 
glad to hear that you are working on this).

## Other Suggestions: 
- **Data Structure:** The `Biobase::ExpressionSet` data structure represents
  datasets as `assayData`, `phenoData`, `featureData`, and
  `protocolData`. Note this has been updated into
  `SummarizedExperiment` which has similar representations using
  `Assay`, `colData`, `rowData` and `metadata`. In any case that you
  want to use `Biobase::ExpressionSet`, use
  `SummarizedExperiment::SummarizedExperiment` instead! Modern data
  structures for representing DNA/RNA/MS datasets extends
  `SummarizedExperiment` class, including those I have mentioned in
  the interoperability section.

  Try the following example of a `SummarizedExperiment` object called
  `airway`.

```{r}
library(airway)
data(airway)
airway
is(airway)
assay(airway)[1:5, 1:5]
rowData(airway)
colData(airway)
metadata(airway)
```
Use `methods(class = "SummarizedExperiment")` for more details about
available methods.

- **Interoperability**
> Interoperability is strongly encouraged in Bioconductor and would
> help with the usage of your own package. Consider interoperability
> with packages included in `RforProteomics`, and `mzR` which uses CDF
> (Common Data Format) to represent MS data in R without completely
> loading data into memory? Check here for other MS related _R /
> Bioconductor_ packages:
> http://bioconductor.org/packages/release/BiocViews.html#___MassSpectrometry

It's fine that you are using in-memory loading of the MS datasets for
  now. But as you said, the dataset is "large-scale", and it's common
  that genomic datasets are going out-of-memory large, you should
  consider the above mentioned data structure for representation of
  the big data in a lazy way that you don't actually load the whole
  data into memory for doing analysis using your methods, but you have
  an interface of the data in R that it seems like you are working
  with the whole dataset. It's the trend of lazy data representation
  in R/Bioconductor. For a long-term / next-phase goal of your
  package, your functions should support these kind of data
  structures. In your case, the MS lazy interfaces.

**Comment by Liubuntu** [comment] 2019-03-01 22:07
The short vignette settings looks fine. Two suggestions: 

1. use smaller data (under `data/*.rda`) in examples / tests / vignette. 
2. Do not print twice the figures in the vignettes (seems you are summarizing all figures in the beginning and then separately in lower sections). 

The only error comes from the tarball size. Please try to do the above and let's see if this could be fixed. 

Best,
Qian

**Comment by ChloeHJ** [comment] 2019-03-02 07:13
Hi Qian,

Thank you for your comments, I will go through them and get back to you soon,

Best regards,
Chloe

**Comment by ChloeHJ** [comment] 2019-03-08 14:10
Hi Qian,

Thank you for the suggestions and comments. We tried to improve our package based your comments and please see the descriptions below for details:

- For the vignette, there was still the problem of exceeding time limits and weird generation of vignette_brief.R in the process of building the package. So for now, I have put the shorter vignette into another branch called RELEASE_2.0. If it’s okay for the initial release, is it okay that we handle the problems with the shorter vignette in the next round of release as we would still have one detailed vignette to describe our package?
- I have added tests to our package.
- Thank you for the suggestions on data structure and interoperability. We will aim to let our functions support these data structures for the next phase of release. 

After making these changes, I tried to build/check our package on the machine but it keeps giving me warning about timestamps: 

checking for future file timestamps ...Warning in file(con, "r") :
  cannot open URL 'http://worldclockapi.com/api/json/utc/now': HTTP status was '403 Site Disabled'
 WARNING
unable to verify current time

I was not sure how to handle this problem so may I ask for your suggestion to tackle this warning? 

Thank you and best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-03-11 15:48
HI @ChloeHJ , 

The newly added test functions look awesome. It's fine now to remove the brief vignette also. 

Here are some minor issues to fix: 

## tests
- new test functions look great!

## DESCRIPTION
- ```Maintainer: The package maintainer Chloe H. Lee  <chloe.h.lee94@gmail.com>``` Only keep the name and email here.

## NEWS
- add a `NEWS` file in the top folder. Initial version could be empty. See
  [example](https://github.com/Bioconductor/DelayedArray/blob/master/NEWS) here for later maintenance.

## examples, dontrun tag. 
- Be cautious with the dontrun tag. Make sure they are runnable before
                adding the tag. Since the building time doesn't seem to be an
                issue now, try removing the `dontrun` tag and see if the time
                could be within limit.
- Assign the returned complex values to a new R object. E.g.,
  `adjust_batch_trend()` has very big output. When users run the
  example, it prints everything in the R console but hard to trace
  back. Same as the `correct_batch_effects()` example.

## vignette
- remove the `.html` and `.R` file from the folder.

## Coding issues.
- ```no visible global function defition for ...``` in building
  report. Follow the suggestions in building report to import
  corresponding packages.
- avoid `sapply()`, use `vapply()`.
- avoid `1:...`, use `seq_len()` or `seq_along()`.
- Check your NOTE messages in the building report for details of above
  issues. Fix as much as possible for the NOTEs.

Best,
Qian

**Comment by Liubuntu** [comment] 2019-03-11 15:52
> checking for future file timestamps ...Warning in file(con, "r") :
cannot open URL 'http://worldclockapi.com/api/json/utc/now': HTTP status was '403 Site Disabled'
WARNING
unable to verify current time

Please ignore this warning for now. It's an R-devel issue, we'll update the R-devel and it will go away.

**Comment by ChloeHJ** [comment] 2019-03-13 12:21
Dear Qian,

Thank you so much for your quick review. I revised our packaged based on your comments:
- Added NEWS file 
- Added examples with a smaller example data matrix and removed dontrun tag 
- I tried to remove the most of NOTES 

For the vignette, you commented to remove the .html and .R form the folder but I could not find these files in my local folder. I tried to remove gitignore from vignette folder to see if these folders can be found from elsewhere but I still could not find them. May I ask you for help with this?

Thank you very much for your kind revisions,

Best regards,
Chloe

**Comment by Liubuntu** [comment] 2019-03-25 20:52
Hi @ChloeHJ , 

All you changes are looking great. Just one more note for the NEWS file. I'll accept this package now. Thanks for your contribution to Bioconductor! 

## NEWS
- No need to change. Just updating with you the official guideline for NEWS file:
htttp://bioconductor.org/developers/package-guidelines/#news

Cheers,
Qian

**Comment by ChloeHJ** [comment] 2019-03-25 20:59
> Hi @ChloeHJ ,
> 
> All you changes are looking great. Just one more note for the NEWS file. I'll accept this package now. Thanks for your contribution to Bioconductor!
> 
> ## NEWS
> * No need to change. Just updating with you the official guideline for NEWS file:
>   htttp://bioconductor.org/developers/package-guidelines/#news
> 
> Cheers,
> Qian

Thank you so much for your revisions all the way Qian!!

**Comment by mtmorgan** [comment] 2019-04-01 15:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ChloeHJ.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("proBatch")`. The package 'landing page' will be created at

https://bioconductor.org/packages/proBatch

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-04-01 15:02 UTC
Labels: 3a. accepted

**Comment by symbioticMe** [comment] 2019-08-08 11:50
Dear reviewers, we have made updates to the package & change the maintainer. How to we proceed now to make sure the updates will appear on BioConductor?
