### ISSUE TITLE
netZooR

### ISSUE THREAD

**Issue by marouenbg** [Bioconductor/Contributions#2238] opened 2021-08-17 17:29 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/netZoo/netZooR

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2021-08-24 18:54
Please add valid biocViews to the DESCRIPTION in order to proceed.  All Bioconductor package require biocViews terms.   See http://bioconductor.org/packages/release/BiocViews.html#___Software  and the drop downs on the left for available terms.

**Comment by rohanbiju** [comment] 2021-08-30 23:05
Hi @lshep ! @marouenbg and I have made the required changes. It would be great if you take a look again. Thanks!

**Comment by lshep** [comment] 2021-09-01 18:25
@marouenbg Your biocviews are still incorrect.  You need to update your biocviews to be valid terms (not packages).  We have processed the package anyways but it will need to be corrected in the review process.

**Comment by marouenbg** [comment] 2021-09-01 18:52
Hi @lshep
We fixed biocViews, could you please have a look (https://github.com/netZoo/netZooR)? Thank you 
@rohanbiju

**Comment by lshep** [comment] 2021-09-01 19:00
Thank you. Now the biocViews are valid.  Please correct the ERROR shown in the build report before an indepth review will take place.

**Comment by lshep** [comment] 2021-09-16 11:57
Please resolve the ERROR in the build report before an in-depth review will take place.

**Comment by marouenbg** [comment] 2021-09-17 14:48
Hi @lshep ,
I wasn't able to reproduce the error on my computer. It basically says that it cannot access .txt files in inst/extdata directory, is it ignored by bioconductor? Do you have the set of commands that the server does so I can reproduce them on my computer?

Thank you

**Comment by lshep** [comment] 2021-09-17 15:22
I can reproduce this locally on my computer.  Make sure you are using R 4.1.1 and most updated Bioconductor packages with `BiocManager::valid()`.   There are some environment variables set up on the builders https://github.com/Bioconductor/Contributions#r-cmd-check-environment

**Comment by marouenbg** [comment] 2021-09-17 23:38
HI @lshep ,
Indeed, I was wrong, I installed R4..1.1 and I could reproduce the error. Errors should be fixed now, can you please trigger another run?
Thank you

**Comment by lshep** [comment] 2021-09-22 21:05
Please trigger another run by pushing a version bump to the git.bioconductor.org repository as described https://github.com/Bioconductor/Contributions/issues/2238#issuecomment-910543089

**Comment by marouenbg** [comment] 2021-09-28 22:31
Hi @lshep, sorry for bothering your again. I pushed to bioconductor git (git@git.bioconductor.org:packages/netZooR.git) but I did not receive any feedback from the test server.

**Comment by lshep** [comment] 2021-10-05 13:42
Can you please try again with an updated version bump? we were having some trouble with the auto build scripts last week that should be remedied

**Comment by marouenbg** [comment] 2021-10-07 16:39
It seems that the build was triggered, thank you!

**Comment by lshep** [comment] 2021-10-07 16:40
yep thank you.  it should post shortly.

**Comment by marouenbg** [comment] 2021-10-08 03:07
Hi @lshep ,
I was really trying hard to tidy up the package for bioconductor, the build is ok but I keep getting this error at the Check stage:
* checking PDF version of manual without hyperrefs or index ... ERROR
Do you have any idea where should I look to fix it?
Thank you,
Marouen

**Comment by marouenbg** [comment] 2021-10-08 03:50
OK the previous error was fixed, it was a unicode character hidden in the function description. I still have more errors from the bioconductor check.

**Comment by marouenbg** [comment] 2021-10-08 14:29
Hi @lshep ,
I needed to make significant changes to the master branch to pass the biocoductor tests, therefore I created a new branch called bioc that has the necessary changes while keeping my master branch.
However when I push, I get the following error (my upstream is biocup):

git push biocup bioc

Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 12 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 793 bytes | 198.00 KiB/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: FATAL: W refs/heads/bioc packages/netZooR marouenbg DENIED by fallthru
remote: error: hook declined to update refs/heads/bioc
To git.bioconductor.org:packages/netZooR.git
 ! [remote rejected] bioc -> bioc (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/netZooR.git'

Do you have any idea how to fix this?
Thank you

**Comment by lshep** [comment] 2021-10-08 14:35
Bioconductor does not allow pushing up of other branches and we would really recommended eventually merging into the master branch so not to get out of sync.  I think you can specify a linking see step 5 on https://bioconductor.org/developers/how-to/git/new-package-workflow/  that addresses the new default main/master mismatch

**Comment by marouenbg** [comment] 2021-10-10 00:16
Hi @lshep ,
I fixed all the errors in the build, is there anything else that needs to be done?

**Comment by Kayla-Morrell** [comment] 2021-10-15 18:16
@marouenbg - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: What is the purpose of the 'docs/' directory? This is normally
  not something we allow within Bioconductor packages.

## DESCRIPTION

- [ ] SUGGESTION: Since you are using a standard license, the 'LICENSE' file
  doesn't need to be included in your package.

- [ ] REQUIRED: 'LazyData' should be set to false or removed.

- [ ] REQUIRED: There are packages listed in more than one of Depends, Imports,
Suggests, Enhances:
    viridisLite, pandaR

- [ ] REQUIRED: There are trailing ',' after pandaR in 'Depends', yarn in
  'Imports', and pkgdown in 'Suggests'. These should be removed.

- [ ] REQUIRED: Update R version dependency from 3.3 to 4.1.0.

- [ ] REQUIRED: There is a trailing ',' after the biocView GeneRegulation. This
  should be removed.

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
    GeneExpression, Transcription, Microarray, GraphAndNetwork
See http://bioconductor.org/developers/how-to/biocViews/

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports' field to
  include the relevant link to GitHub for reporting issues.

## NAMESPACE

- [ ] REQUIRED: Exported functions should use camel case or underscoring and not
  include '.', which indicates S3 dispatch.

- [ ] SUGGESTION: Generally 'importFrom()' is encouraged over importing an
  entire package. However, if there are many functions from a single package,
'import()' can be acceptable.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be
  included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: For exon.size, genes, monsterRs, and mut.ucec could you provide
  the actual reference to Kuijjer et al., similar to how you have a reference
for small1976 and yeast.

- [ ] REQUIRED: Data in the 'inst/extdata/' directory need proper documentation
  in an 'inst/script/' directory. The scripts in the directory can vary but most
importantly should clearly state how the data was generated. It should include
source URLs and any key information regarding filtering or processing. It can be
executable code, sudo code, or a text description. Users should be able to
download and roughly reproduce the file or object that is present as data.

## Vignettes

- [ ] REQUIRED: I think there needs to be thought into whether all the vignettes
  are needed in this package. The idea of a vignette is to demonstrate how to
accomplish non-trivial tasks embodying the core functionality of *your* package,
not other established packages. It is fine to explain packages and how they are
relevant to yours but you should really be demonstrating the use of your
package. It also might be better if all code was in one main vignette instead of
many little ones. A user might not know which vignette to browse when looking
for answers to questions or examples to run.

- [ ] REQUIRED: Whether you decide to go with one or many vignette each one must
  minimally include:
    - An Introduction section
    - An Installation section
    - Table of contents (though not necessarly required)
    - Evaluated code chunks - very few (if any) eval = FALSE code chunks
    - Session information section that includes `sessionInfo()`

- [ ] REQUIRED: There is a `library(RColorBrewer)` call in the yarn.Rmd file,
  but RColorBrewer isn't listed as a Suggests in the DESCRIPTION file. Please
add to the DESCRIPTION file if usin in the vignette.

- [ ] REQURIED: All data used in vignette should come from the package itself or
  other CRAN/Bioconductor packages. You should avoid downloading files and
external data from the web.

## Man pages

- [ ] REQUIRED: Data used in examples should come from the package itself or
  other CRAN/Bioconductor packages. You should avoid downloading files and
external data from the web.

- [ ] REQUIRED: Found '@' in man/monster.Rd. Use accessors; don't access S4
  class slots via '@' in examples/vignettes.

- [ ] REQUIRED: All exported objects/functions need valid examples with them.
  For example, the alpaca function just has "a <- 1 # example place holder" as
an example. This is not acceptable.

- [ ] REQUIRED: Add runnable examples to the following man pages which document
  exported objects:
    create.diff.panda.style.Rd
    create.panda.style.Rd
    sambar.convertgmt.Rd
    sambar.corgenelength.Rd
    sambar.desparsify.Rd
    sambar.Rd
    vis.diff.panda.in.cytoscape.Rd
    vis.panda.in.cytoscape.Rd

- [ ] REQUIRED: Usage of dontrun{} / donttest{} found in man page examples. Use
  donttest{} instead of dontrun{} if necessary. Found in the following files:
    vis.diff.panda.in.cytoscape.Rd
    vis.panda.in.cytoscape.Rd

## Unit tests

- [ ] REQUIRED: Data used in tests should come from the package itself or other
  CRAN/Bioconductor packages. You should avoid downloading files and external
data from the web.

## R code

- [ ] REQUIRED: Function names should be camelCase or utilize the underscore and
  not have a dot.

- [ ] SUGGESTION: Consider clarifying how 2 objects are initialized. Maybe they
  are part of a data set loaded with data(), or perhaps part of an object
referenced in with() or within().
    function (object)
    monster.monsterNI (yeast)
    runEgret (NA12878)

- [ ] REQUIRED: Avoid sapply(); use vapply() instead.

- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along() instead.

- [ ] REQUIRED: Avoid use of direct slot access with '@' or slot(). Accessor
  methods should be created and utilized.

- [ ] REQUIRED: Avoid the use of 'paste' in condition signals. Found in files:
    R/panda.to.alpaca.R, line 49
    R/panda.to.condor.object.R, line 72

- [ ] REQUIRED: Avoid redundant 'stop' and 'warn*' in signal conditions. Found
  in files:
    R/CONDOR.R, lines 375 and 581
    R/MONSTER.R, lines 802, 828, and 835

- [ ] REQUIRED: Avoid system(); use system2() instead.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 957
  lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs.
  There are 9 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 1990 lines that are not.

Best,
Kayla

**Comment by marouenbg** [comment] 2021-10-27 18:06
Hi @Kayla-Morrell ,

Thank for the great feedback, I am working on it at the moment.
Regarding this point
- REQUIRED: For exon.size, genes, monsterRs, and mut.ucec could you provide
the actual reference to Kuijjer et al., similar to how you have a reference
for small1976 and yeast.

Where should I provide a reference to Kuijjer et al?

**Comment by marouenbg** [comment] 2021-10-29 02:40
Hi @Kayla-Morrell ,
Thank you so much for the thorough review, I addressed all of the points you raised, please let me know if there is anything else to do.
Marouen

**Comment by Kayla-Morrell** [comment] 2021-11-04 16:26
@marouenbg - Thank you for making the necessary changes. I have looked everything over and there are just a few things that need to be addressed before I can accept the package. Please see the requirements below and comment back here when the changes are ready for re-review.

# Vignette

- [ ] REQUIRED: The installation section should demonstrate to the user how to install and download the package from Bioconductor. The code should look like the following and include `eval = FALSE`.

```{R}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("netZooR")
```

- [ ] REQUIRED: The last section of the vignette should be 'Session Information' and should include `sessionInfo()`.

# Man pages

- [ ] REQUIRED: Add runnable examples to the following man pages which document exported objects:
    createPandaStyle.Rd
    visPandaInCytoscape.Rd

Best,
Kayla

**Comment by marouenbg** [comment] 2021-11-10 03:50
Hi @Kayla-Morrell ,

Thank you for taking the time to review the package! I keep getting this error on the server, however, everything works fine locally.

Thank you


 BiocCheckGitClone('netZooR')

===============================

tar: Unrecognized archive format

**Comment by lshep** [comment] 2021-11-10 12:08
There was a miscommunication on our end and merida1 should no longer be included in the build reports.  This can be ignored and we are removing the builder this morning.

**Comment by marouenbg** [comment] 2021-11-10 14:26
Thank you @lshep .
Hi @Kayla-Morrell ,
I finished addressing the remaining comments, expect the last one. I added examples in createPandaStyle.Rd and
visPandaInCytoscape.Rd using \donttest{} because they call a GUI.

Thank you

**Comment by Kayla-Morrell** [comment] 2021-11-12 15:11
@marouenbg - Thank you for making those changes. I'm more than happy to accept that package now.

Best,
Kayla

**Comment by marouenbg** [comment] 2021-11-12 15:28
Thank you so much @lshep and @Kayla-Morrell for your help making netZooR a better package !

**Comment by lshep** [comment] 2021-11-16 14:16
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/marouenbg.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("netZooR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/netZooR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-11-16 14:16 UTC
Labels: OK, 3a. accepted

**Comment by marouenbg** [comment] 2021-12-01 16:04
Hi @lshep,

@violafanfani and I are trying to deploy netZooR in conda but Bioconductor page says it is compatible with R4.2 which has not been released yet https://bioconductor.org/packages/devel/bioc/html/netZooR.html
Would you have any suggestion for this?

Thank you,

**Comment by vjcitn** [comment] 2021-12-01 16:13
Your package is in the devel branch of Bioconductor which only builds against R4.2 at this time.  To use netZooR with a different version of R, please install netZooR based on a compatible source version of your package that is, for example, in github.  You can use devtools::install_github to accomplish this if working from github; other approaches are available depending on how the source is managed.

**Comment by marouenbg** [comment] 2021-12-01 17:31
Hi @vjcitn ,
When do you think it will be on the base branch and how can I install R4.2 on my computer?
Thank you

**Comment by vjcitn** [comment] 2021-12-01 17:40
I want to make sure it is understood that you can use the package in R 4.1 if you install it from github.  If you want to install it with the Bioconductor devel branch software, which is likely to be unstable, you can install R 4.2 using instructions at the bottom of https://bioconductor.org/developers/how-to/useDevel/

**Comment by violafanfani** [comment] 2021-12-01 18:26
Hi @vjcitn, thanks a lot for helping. We encountered this issue as we are trying to prepare the conda recipe so that we can add netzooR to the bioconda channel as bioconductor-netzoor. If I understand correctly, to have a stable recipe (stable R version + stable version of dependencies) we should wait for netzoor to be on the base branch of bioconductor and In the meantime we could prepare a recipe from the github version. Is that correct?

**Comment by marouenbg** [comment] 2022-07-07 15:46
Hi @lshep , I've been trying to push new commits to git@git.bioconductor.org:packages/netZooR.git but the push does not trigger tests, are there any issues in the testing machines currently?

**Comment by lshep** [comment] 2022-07-07 16:00
Once the package has been accepted it is on the daily builder and does not build  through the SPB submission here.  
You will have to wait for the daily build report found: http://bioconductor.org/checkResults/
This page also list the schedule of each type of package.  
The daily builder does a git pull of all Bioconductor package once a day and performs the install/build/check.  Depending on the time of your push it may take up to 48 hours to appear on the daily build report. 

Please also always remember to do a version bump with changes.  Changes will not propagate if there is not a version bump in the description.

**Comment by marouenbg** [comment] 2022-07-07 16:01
Great, thank you!

**Comment by marouenbg** [comment] 2022-07-07 16:18
@lshep Is there a buildignore for bioconductor? Like a .biocignore, I am running large tests on my self hosted server and I don't want to include them in bioc build.

**Comment by lshep** [comment] 2022-07-07 16:26
bioconductor should respect the traditional  `.buildignore` if its included

**Comment by marouenbg** [comment] 2022-07-21 16:55
Hi @lshep ,
I have updated my package netZooR and the tests ok in http://bioconductor.org/checkResults/
But the develop landing page http://bioconductor.org/packages/3.16/bioc/html/netZooR.html still lists version 1.1 although I bumped the description file to 1.1.15. How often does this page gets updated?

Thank you so much for answering all my questions!

**Comment by lshep** [comment] 2022-07-21 16:58
They regenerate once per day after the builds complete and propagate.  It looks like today's run was just finishing up and the new version is clean and propagating so I expect the landing page to be updated later today over the next few hours.

**Comment by marouenbg** [comment] 2022-07-21 16:58
makes sense, thank you!
