### ISSUE TITLE
CTDquerier

### ISSUE THREAD

**Issue by carleshf** [Bioconductor/Contributions#588] opened 2017-12-21 18:18 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isglobal-brge/CTDquerier

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment] 2017-12-21 19:20
Are you sure you want to couple database access with plotting and analysis? Ideally, there would be a package that downloads the data into common data structures, and then one or more other packages, independent of the downloader, that plot and analyze those data structures, independent of the source. I think Bioconductor already has some data structures for working with interaction networks, like graphs and gene lists (GSEABase). Are those applicable here?

The CTDquery class is confusingly named, because it's the _result_ of the query, not the query itself. 

It looks like the package caches CTD vocabularies in files. Consider using BiocFileCache for that.

Btw, it's not clear why psygenet2r is needed to call `extract()` in the vignette.

**Comment by mtmorgan** [comment] 2018-01-02 21:44
DESCRIPTION

- Good.
- Remember to bump versions (to 0.99.2, ...) to trigger new builds.

vignette

- Vignettes look good!

- `CTD_*` files: should _NOT_ be duplicated in at the root of the package. If they are meant to be available for the vignette, then they should be in inst/extdata (reference in the vignette as `system.file(package=...)`). Consider carefully whether the full files are required, or whether a subset would be sufficient to illustrate package functionality.

- vignette.Rmd: update installation instructions to reflect situation after acceptance, i.e., 

    ```
    source("https://bioconductor.org/biocLite.R")
    biocLite("CTDquerier")
    ```

- CTDQuery-enrich.R:10 and throughout -- use accessors rather than direct slot access. Accessors do not have to be exported. E.g., `.type <- function(x) x@type`. This enables separation of interface from implementation.

- CTDQuery-extract.R:23 consider `switch()` rather than nested `if()`.

- Use [BiocFileCache][] to manage file downloads.

- use functions to avoid copy-paste code, e.g., downlaod_ctd.R

    ```
    .download <- function(url, filename, mode, message, verbose) {
      if( !file.exists( filename ) ) {
        if( verbose ) {
          msg <- sprintf(message, filename)
          message( msg )
        }
        res <- tryCatch( utils::download.file(
          url = fileURL,
          destfile = filename,
          method = mode ),
        error = function(e) { 1 } )
      } else {
        res <- filename
      }
    
      if( res == 1 ) {
        ""
      } else {
        filename
      }
    }
    
    download_ctd_genes <- ... {
      url <- "http://ctdbase.org/reports/CTD_genes.tsv.gz"
      msg <- "Downloading gene vocabulary from CTDbase ('%s')"
      .download(url, filename, mode, msg, verbose)
    }
    ```
    
- For more robust code, validate arguments provided by users, e.g., in the above

    ```
    stopifnot(
        is.character(filename), length(filename) == 1L,
        is.character(mode), mode %in% c("auto" ...),
        is.logical(verbose), length(verbose) == 1L, ...
    )
    ```

- Typo query_ctd_chem.R:79, query_ctd_dise.R:22

man

- ok

[BiocFileCache]: https://bioconductor.org/packages/BiocFileCache

**Comment by carleshf** [comment] 2018-01-02 23:21
Dear @lawremi,


Let me answer your comments:

  * The aim of `CTDquerier` is to provide a way to access and download data from _CTDbase_, not to perform analyses. But I think that is mandatory that `CTDquerier` provides a basic way to visualize that data is able to retrieve.

 * Since `CTDquerier` allows to export all the data it is able to get from _CTDbase_ to `DataFrame` objects I thin that is fully compatible with other packages from Bioconductor for both visualization and analysis.

About your suggestions:

 * I fully agree that the `CTDquery` was not a good choice to be the name of the class containing the data downloaded from _CTDbase_ so I changed it to `CTDdata`.

 * As you suggested the current version of `CTDquerier` uses `BiocFileCache` to manage CTD vocabularies files.

Finally, I participated in the development of `psygenet2r` and the `extract` method from that package does exactly the same than the method `extract` from `CTDuqerier`. Hence I just thought that was unnecessary to create a method with a different name to do the same so I just used the definition of `extract` from `psygenet2r`. Is not the right way to avoid redundancy and to generalize methods? I am totally open to list opinions on this side.


Kind regards,
C.

**Comment by lawremi** [comment] 2018-01-02 23:28
If `extract()` is going to be part of the API for CTDquerier, then you'll need to export it by default. It's a lot to expect the user to load psygenet2r to get access to the generic.

**Comment by carleshf** [comment] 2018-01-02 23:31
Dear @mtmorgan ,

Follows the changes I applied after your suggestions:

  * All `CTD_*` files were removed.
  * Installations istructions were updated.
  * `extract` methods was updated to use `switch`.
  * Current version of the package suses `BiocFileCache`.
  * I updated `query_ctd_*` and `download_ctd_*`.

**Comment by carleshf** [comment] 2018-01-02 23:48
Dear @mtmorgan,

Follows the changes I applied after your suggestions:

  * All `CTD_*` files were removed.
  * Installations instructions were updated.
  * `extract` methods were updated to use `switch`.
  * Current version of the package uses `BiocFileCache`.
  * I updated `query_ctd_*` and `download_ctd_*`.
  * I solved some types.

As suggested by @lawremi I exported the method `extract` as is is part of the API for `CTDquerier` and removed the link to `psygenet2r`. 

I added a new vignette comparing `CTDquerier` with the _CTDbase_ web tool `Batch Query`. If you think it is a good point to cover I will extend it comparing the results obtained using `CTDquerier` versus de the ones obtained from `Batch Query` for the **GALA genes** (Case Study). If you agree I will also compare the usage fo _CTDbase_  web tool `Set Analyzer`.

**Comment by carleshf** [comment] 2018-01-03 08:33
Dear @mtmorgan,

Follows the changes I applied after your suggestions:

  * All `CTD_*` files were removed.
  * Installations instructions were updated.
  * `extract` method was updated to use `switch`.
  * Current version of the package uses `BiocFileCache`.
  * I updated `query_ctd_*` and `download_ctd_*`.
  * I solved some typos.
  * Changed R version to `R 3.5`.

As suggested by @lawremi I exported the method `get_table` (old method `extract`) as it is part of the API for `CTDquerier` and removed the link to `psygenet2r`. 

I added a new vignette comparing `CTDquerier` with the _CTDbase_ web tool `Batch Query`. If you think it is a good point to cover I will extend it comparing the results obtained using `CTDquerier` versus de the ones obtained from `Batch Query` for the **GALA genes** (Case Study). If you agree I will also compare the usage fo _CTDbase_  web tool `Set Analyzer`.

**Comment by mtmorgan** [comment] 2018-01-03 12:47
Can you also address these BiocCheck notes

```
* Checking coding practice...
    * NOTE: Avoid 1:...; use seq_len() or seq_along() found in files:
    R/query_ctd_chem.R (line 77, column 16)
    R/query_ctd_chem.R (line 173, column 42)
    R/query_ctd_chem.R (line 179, column 33)
...
```
? Thanks

**Comment by mtmorgan** [comment] 2018-01-09 22:14
@carleshf Looks like the package just needs a version bump and final build ?

**Comment by carleshf** [comment] 2018-01-09 22:17
@mtmorgan I am finishing an improvement of  `enrich` method to allow users indicate the test they want to perform as well as a specific a given gene universe.

I just need some test and it will be done. Also, I am correcting the BiocCheck notes.

**Comment by carleshf** [comment] 2018-01-12 14:50
I updated the `enrich`  method, as well improved documentation and updated the Case Stuy, adding a description about the resulting tables obtained from querying _CTD_. I corrected several BiocCheck's notes.

Result from R `check`:
```
R CMD check results
0 errors | 0 warnings | 2 notes
R CMD check succeeded
```

Result from Bioconductor `BiocCheck`:
```
Summary:
ERROR count: 0
WARNING count: 1
NOTE count: 6
```

**Comment by carleshf** [comment] 2018-01-15 23:05
Dear @mtmorgan,

I think I need some guidance here. The problem relies on the temporary files created through `BiocFileCache`. 

I have created an internal function to obtain a `BiocFileCache` object that is used by the `download_*` functions, in charge to obtain the *vocabulary files* from CTD.

The first one is:

```
.get_cache <- function() {
    bfc <- BiocFileCache::BiocFileCache()
    return( bfc )
}
```

The `download_*` functions follow this structure:

```
download_ctd_chem <- function( verbose = FALSE ) {
    fileURL <- "http://ctdbase.org/reports/CTD_chemicals.tsv.gz"

    bfc <- .get_cache()
    if( nrow( BiocFileCache::bfcquery(bfc, "CTD_chemicals") ) == 0 ) {
        if( verbose ) message( "Downloading CHEMICAL vocabulary from CTDbase" )
        BiocFileCache::bfcadd(bfc, "CTD_chemicals", fileURL )
    }
}
```

The warning and the consequent error and invalidation of the package appears because the downloaded `.tsv.gz` the file is not stored. I was not able to reproduce this error nor in my Xubuntu laptop, our CentOS servers nor a windows PC. 

So my conclusion is that I am not properly dealing with the `BiocFileCache`, but I do not see what I am doing wrong.

Why of this conclusion?

If I run a basic query given a single gene in my laptop I got:

```
> xkr4 <- query_ctd_gene( terms = "XKR4", verbose = TRUE )
Loading gene vocabulary.
Staring query for gene 'XKR4' ( 114786 )
 . Downloading 'gene-gene interaction' table.
 . Downloading 'disease' table.
 . Downloading 'gene-chemical interaction' table.
 . Downloading 'GO terms' table.
 . Downloading 'KEGG pathways' table.
 . . No 'KEGG pathways' table available for XKR4' ( 114786 )
```

This same query, run on the building system results in:

```
> xkr4 <- query_ctd_gene( terms = "XKR4" )
Error: subscript contains out-of-bounds indices
In addition: Warning messages:
1: In file(file, "rt") :
  cannot open file 'e65329a362d_CTD_genes.tsv.gz': No such file or directory
2: In query_ctd_gene(terms = "XKR4") : 1/1 terms were dropped. 
```

That is because the gene *XKR4* could not be validated into the vocabulary file, that corresponds to 'e65329a362d_CTD_genes.tsv.gz` that is managed by a `BiocFileCache`. I will add some checks to control for this situation, but I don't understand why it is happening.

**Comment by carleshf** [comment] 2018-01-16 13:39
I do not understand... I rolled back to "9184932 Bumped R version to 3.5 (¿?)" and now it does not pass the BiocCheck?

**Comment by carleshf** [comment] 2018-01-16 14:01
So.. I rollback to the beginning of the thread and I will start applying the changes one by one... let's see if in this way I can see where the "subscript out of bounds" appears...

**Comment by carleshf** [comment] 2018-01-16 15:32
Until now, the *corrections* I applied correspond to:

 * Name of the class that stores the results of a query was changed from `CTDquery` to `CTDdata`
 * Enrichment analysis uses a *user* gene universe by default and can use all genes in `CTD` if required.

**Comment by carleshf** [comment] 2018-01-16 22:24
So the problem appears when I add the management of the vocabulary files with `BiocFileCache`.

**Comment by mtmorgan** [comment] 2018-01-16 22:31
Use `bfcrpath()` rather than `bfcquery()$rpath`

 BiocFileCache::bfcrpath(bfc, "CTD_genes")
                                                                  BFC1 
"/tmp/RtmpghXrXq/tempCTDquerierCacheDir/35ec7f5dbe98_CTD_genes.tsv.gz"

**Comment by mtmorgan** [comment] 2018-01-17 09:32
Please use a package-specific cache,
```
.get_cache <- function() {
    #path <- file.path(tempdir(), "tempCTDquerierCacheDir")
    #bfc <- BiocFileCache::BiocFileCache(path)
    cache <- rappdirs::user_cache_dir(appname="CTDQuery")
    bfc <- BiocFileCache::BiocFileCache(cache)
    return( bfc )
}
```

**Comment by mtmorgan** [comment] 2018-01-18 11:23
Please don't make any more changes; we'll investigate what the problem is.

**Comment by lshep** [comment] 2018-01-19 13:26
I believe we have identified and correct the issue. I am kicking off a manual rebuild of the package.

**Comment by mtmorgan** [comment] 2018-01-24 11:53
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carleshf.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"CTDquerier\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CTDquerier

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Closed by mtmorgan** 2018-01-24 11:53 UTC
Labels: 3a. accepted
