### ISSUE TITLE
gemini

### ISSUE THREAD

**Issue by ssj1739** [Bioconductor/Contributions#1148] opened 2019-06-13 18:33 UTC
GEMINI: A variational Bayesian approach to identify genetic interactions from combinatorial CRISPR screens

This package is being submitted to Bioconductor upon conditional acceptance of a corresponding manuscript. The contents of the package are described in detail within the manuscript, as well as with the accompanying documentation.

- Repository: https://github.com/sellerslab/gemini

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by ssj1739** [comment] 2019-06-15 21:18
Hi,

I've pushed to the linked repository, but it seems that there is no build being triggered. Additionally, the warnings in the previous build appear to be from packages not being present or installed on the host machine. Is there any way for me to fix this?

Thanks,
Sidharth Jain

**Comment by Kayla-Morrell** [comment] 2019-06-17 13:03
Hello @ssj1739 - in order for a build to be triggered you need to bump the version in the DESCRIPTION file. Currently it is version 0.99.0 and once you bump it to 0.99.1 and push the change then a build should be triggered. This needs to be done every time you push changes. I'll look into the warnings a bit further on our end.

Best,
Kayla

**Comment by ssj1739** [comment] 2019-06-17 14:00
@Kayla-Morrell Thank you, I'll be sure to do that from now on. 

I think the warnings may have to do with documentation - in the documentation of some functions, I'm linking to packages that aren't in the "Imports", but are instead in "Suggests", and I'm not sure if the machines that install packages are also installing all suggested packages. I can remove this documentation, but I'm wondering what Bioconductor's best practices are regarding linking in documentation.

**Comment by Kayla-Morrell** [comment] 2019-06-19 19:09
Hello @ssj1739 -

Thank you for submitting to _Bioconductor_. Please see the initial review of your package below. Comment back here with updates that have been made and when the package is ready for a re-review.

# DESCRIPTION #

- [ ] REQUIRED: For the 'Description:' there needs to be a proper doi. If not 
available yet please remove this line until it is available.

- [ ] REQUIRED: 'LazyData:' should be set to false. When this is set to true 
we find that it slows down the loading of packages, especially if they have 
large datasets.

- [ ] SUGGESTION: Consider adding the automatically suggested biocView term 
'DataImport'.


- [ ] SUGGESTION: We encourage the use of 'BugReports:' which provides the 
relevant GitHub link for reporting Issues.

# NAMESPACE #

- [ ] REQUIRED: Generally `importFrom()` is encouraged over importing the entire
 package, especially if only a few functions from it are used. Please be sure 
that there is not unneeded importing.

- [ ] REQUIRED: There are some instances where the entire package is imported as
 well as specific functions. For example, 'magrittr' is imported but then '%<>%'
 is imported from 'magrittr' later on. Please be sure you are only using import
 or importFrom and not both. If '%<>%' is the only thing being used from 
'magrittr' I would be sure to remove 'import(magrittr)' and edit your R code 
accordingly. The same happens with 'dplyr' and 'parallel'.

# vignettes #

- [ ] REQUIRED: Only the vignette file (.Rnw or .Rmd) should be in the vignette 
directory. Please remove the R and the .gitingore files.

- [ ] SUGGESTION: Add an “Introduction” section that serves as an abstract to 
introduce the objective, models, unique functions, key points, etc that 
distinguish the package from other packages of similar type. You started a bit 
of an introduction with 'GEMINI follows a basic workflow:...' but I would 
elaborate this section a bit more, if you can, to make it a proper introduction
 section.

- [ ] REQUIRED: Add an “Installation” section that show to users how to download
 and load the package from Bioconductor. It should look something like this:
```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("gemini")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: Please include some text that explains where the Big Papi data 
comes from.

- [ ] SUGGESTION: For the sections using `knitr::kable()`, I would change the 
'echo = FALSE' to true so that the user can see how to achieve the nice table 
you produce. Especially when you start subsetting by A549 (line 111, 117), the 
user may not know how to do this and showing the code would make the code 
reproducable.

- [ ] REQUIRED: Line 122, since 'eval = FALSE' the plot is not produced in the 
vignette. So when you say "We can see that GEMINI..." we can't because the plot
 is not there. Please remove the 'eval = FALSE'. 

- [ ] REQUIRED: Line 137, the same goes for this chunk of code as well. You talk
 about how the boxplot can be re-colored but no boxplot is produced to show it.
 Please remove the 'eval = FALSE'.

- [ ] REQUIRED: Line 98, split this comment onto multiple lines. When the 
vignette is built, the comment is too long for the code box and gets cut off at
 "... is constructed only" 

- [ ] REQUIRED: There should be a final section 'Session Info' that includes 
`SessionInfo()`. 

# man pages #

*Input*

- [ ] REQUIRED: Where does the Big Papi data come from?

*counts*

- [ ] REQUIRED: Is 'Big Papi SynLet' a package that the data comes from? Is 
'Big Papi' the name of the data that comes from the 'SynLet' package? Please be
 more clear with where this data comes from.

*gemini_calculate_lfc*

- [ ] CLARIFICATION: Why is the last line of the example code not run? 

*gemini_parallelization*

- [ ] CLARIFICATION: Can you provide an example for this function since it is 
exported.

*guide.annotation*

- [ ] REQUIRED: Same with counts, please be more clear about where the data 
comes from.

*sample.replicate.annotation*

- [ ] REQUIRED: Same as with counts and guide.annotation, please be more clear 
about where the data comes from.

# R code #

- [ ] NOTE: Consider clarifying how 9 object(s) are initialized.
        function (object)
        - gemini_boxplot (.)
        - gemini_boxplot (.)
        - gemini_boxplot (gi)
        - gemini_boxplot (hj)
        - gemini_boxplot (label)
        - gemini_boxplot (y)
        - gemini_calculate_lfc (.)
        - update_s_pb (.)
        - update_tau_pb (.)

- [ ] SUGGESTION: For formatting purposes, consider shorter lines. 330 lines 
(9%) are > 80 characters long.

- [ ] SUGGETSION: For formatting purposes, consider 4 spaces instead of tabs. 
1528 lines (43%) contain tabs.

- [ ] SUGGESTION: For formatting purposes, consider mulitples of 4 spaces for 
line indents, 139 lines (4%) are not.

- [ ] REQUIRED: There are some functions that need to have their arguments 
spaced better. For example, in 'gemini_calculate_lfc' lines 38-41 need to be 
better in line with the function. This is done correctly in 'gemini_initialize' 
line 49-63. Please be sure these spacing issues are fixed.

Best,
Kayla

**Comment by ssj1739** [comment] 2019-06-24 20:25
# DESCRIPTION
- [X] REQUIRED: For the 'Description:' there needs to be a proper doi. If not
available yet please remove this line until it is available.

- [X] REQUIRED: 'LazyData:' should be set to false. When this is set to true
we find that it slows down the loading of packages, especially if they have
large datasets.

- [X] SUGGESTION: Consider adding the automatically suggested biocView term
'DataImport'.

- [X] SUGGESTION: We encourage the use of 'BugReports:' which provides the
relevant GitHub link for reporting Issues.

# NAMESPACE
- [X] REQUIRED: Generally importFrom() is encouraged over importing the entire
package, especially if only a few functions from it are used. Please be sure
that there is not unneeded importing. 
**SJ: I kept ggplot2 since I'm using several functions from this package**

- [X] REQUIRED: There are some instances where the entire package is imported as
well as specific functions. For example, 'magrittr' is imported but then '%<>%'
is imported from 'magrittr' later on. Please be sure you are only using import
or importFrom and not both. If '%<>%' is the only thing being used from
'magrittr' I would be sure to remove 'import(magrittr)' and edit your R code
accordingly. The same happens with 'dplyr' and 'parallel'.

# vignettes
- [X]  REQUIRED: Only the vignette file (.Rnw or .Rmd) should be in the vignette
directory. Please remove the R and the .gitingore files.

- [X] SUGGESTION: Add an “Introduction” section that serves as an abstract to
introduce the objective, models, unique functions, key points, etc that
distinguish the package from other packages of similar type. You started a bit
of an introduction with 'GEMINI follows a basic workflow:...' but I would
elaborate this section a bit more, if you can, to make it a proper introduction
section.

- [X]  REQUIRED: Add an “Installation” section that shows users how to download
and load the package from Bioconductor. It should look something like this:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("gemini")
```

- [X] SUGGESTION: We strongly encourage the use of table of contents.

- [X] REQUIRED: Please include some text that explains where the Big Papi data
comes from.

 - [X] SUGGESTION: For the sections using knitr::kable(), I would change the
'echo = FALSE' to true so that the user can see how to achieve the nice table
you produce. Especially when you start subsetting by A549 (line 111, 117), the
user may not know how to do this and showing the code would make the code
reproducable.

 - [X] REQUIRED: Line 122, since 'eval = FALSE' the plot is not produced in the
vignette. So when you say "We can see that GEMINI..." we can't because the plot
is not there. Please remove the 'eval = FALSE'.

- [X]  REQUIRED: Line 137, the same goes for this chunk of code as well. You talk
about how the boxplot can be re-colored but no boxplot is produced to show it.
Please remove the 'eval = FALSE'.

- [X]  REQUIRED: Line 98, split this comment onto multiple lines. When the
vignette is built, the comment is too long for the code box and gets cut off at
"... is constructed only"

- [X] REQUIRED: There should be a final section 'Session Info' that includes
SessionInfo().

#man pages
**SJ: I clarified all data as coming from a previous publication (Najm et al, 2018 *Nature Biotechnology*) Details were added in the respective man pages.**

*Input*

- [X] REQUIRED: Where does the Big Papi data come from?
*counts*

- [X] REQUIRED: Is 'Big Papi SynLet' a package that the data comes from? Is
'Big Papi' the name of the data that comes from the 'SynLet' package? Please be
more clear with where this data comes from. **SJ: I clarified all data as coming from a previous publication (Najm et al, 2018 *Nature Biotechnology*) Details were added in the respective man pages.**
gemini_calculate_lfc

- [X] CLARIFICATION: Why is the last line of the example code not run?

gemini_parallelization

- [X] CLARIFICATION: Can you provide an example for this function since it is
exported. **SJ: Removed the \dontrun tag**
guide.annotation

- [X] REQUIRED: Same with counts, please be more clear about where the data
comes from. **SJ: I clarified all data as coming from a previous publication (Najm et al, 2018 *Nature Biotechnology*) Details were added in the respective man pages.**
sample.replicate.annotation

- [X] REQUIRED: Same as with counts and guide.annotation, please be more clear
about where the data comes from. **SJ: I clarified all data as coming from a previous publication (Najm et al, 2018 *Nature Biotechnology*) Details were added in the respective man pages.**

# R code
  NOTE: Consider clarifying how 9 object(s) are initialized.
function (object)
 **SJ: These result from variables used in tidyverse/ggplot2 environments, and are not global or exported.**
- gemini_boxplot (.)
- gemini_boxplot (.)
- gemini_boxplot (gi)
- gemini_boxplot (hj)
- gemini_boxplot (label)
- gemini_boxplot (y)
- gemini_calculate_lfc (.)
- update_s_pb (.)
- update_tau_pb (.)

  SUGGESTION: For formatting purposes, consider shorter lines. 330 lines
(9%) are > 80 characters long.
**SJ: These are primarily in the documentation, and do not affect code readability.**

- [X] SUGGETSION: For formatting purposes, consider 4 spaces instead of tabs.
1528 lines (43%) contain tabs.

- [X] SUGGESTION: For formatting purposes, consider mulitples of 4 spaces for
line indents, 139 lines (4%) are not.

- [X] REQUIRED: There are some functions that need to have their arguments
spaced better. For example, in 'gemini_calculate_lfc' lines 38-41 need to be
better in line with the function. This is done correctly in 'gemini_initialize'
line 49-63. Please be sure these spacing issues are fixed.
**SJ: All lines were reformatted using RStudio reformatting specifications**

**Comment by Kayla-Morrell** [comment] 2019-06-25 13:54
Hi @ssj1739,

Thank you for making the changes, everything looks good and I'm happy to accept the package!

Best,
Kayla

**Comment by mtmorgan** [comment] 2019-07-09 14:52
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ssj1739.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gemini")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gemini

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-07-09 14:52 UTC
Labels: 3a. accepted, OK
