### ISSUE TITLE
RcwlPipelines

### ISSUE THREAD

**Issue by hubentu** [Bioconductor/Contributions#1031] opened 2019-03-01 20:22 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hubentu/RcwlPipelines

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by hubentu** [comment] 2019-03-01 20:27
Hi, this is a data package for [Rcwl][1]. Thanks!

[1]: https://github.com/Bioconductor/Contributions/issues/980

**Comment by hubentu** [comment] 2019-03-15 15:06
Hi @Kayla-Morrell , Any status update? 

Thanks,
Qiang

**Comment by hubentu** [comment] 2019-03-18 21:14
Hi @Kayla-Morrell ,

1. This package is dependent on the package `Rcwl`, which is only compatible with Linux and MacOS, so a file `.BBSoptions` was added to skip the Windows system.
2. There are some build warnings from inst/mc3 and inst/GATK4. These files are from the project MC3 and GATK4 by git-submodules. To keep these files the same as the original project, I didn't clean or rename them.
```
WARNING: directory RcwlPipelines/inst/mc3/backup_templates/utils/backup_templates is empty
...
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  RcwlPipelines/inst/GATK4/gatk4-data-processing/processing-for-variant-discovery-gatk4.b37.wgs.inputs.json
```

Thanks,
Qiang

**Comment by hubentu** [comment] 2019-03-19 14:46
Hi @Kayla-Morrell @mtmorgan ,

I got some build warnings as follows, which are from the git clones of other CWL pipelines. These scripts
are imported and invoked in my package.
Could you give me some suggestion for this warning? Do I need to clean and rename these files?

Thanks,
Qiang

```
* checking for empty or unneeded directories
WARNING: directory RcwlPipelines/inst/mc3/backup_templates/utils/backup_templates is empty
WARNING: directory RcwlPipelines/inst/mc3/tools/indelocator-tool/backup_templates is empty
WARNING: directory RcwlPipelines/inst/mc3/tools/markfiles-tool/backup_templates is empty
WARNING: directory RcwlPipelines/inst/mc3/tools/tcgavcf-tool/backup_templates is empty
WARNING: directory RcwlPipelines/inst/mc3/tools/vcf-tools/backup_templates is empty
WARNING: directory RcwlPipelines/inst/mc3/tools/vcf2maf-tools/backup_templates is empty
WARNING: directory RcwlPipelines/inst/mc3/utils/backup_templates is empty
* looking to see if a data/datalist file should be added
* building RcwlPipelines_0.99.6.tar.gz
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  RcwlPipelines/inst/GATK4/gatk4-data-processing/processing-for-variant-discovery-gatk4.b37.wgs.inputs.json
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  RcwlPipelines/inst/GATK4/gatk4-data-processing/processing-for-variant-discovery-gatk4.hg38.wgs.inputs.json
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  RcwlPipelines/inst/GATK4/gatk4-data-processing/processing-for-variant-discovery-gatk4.hg38.wgs.inputs.local.json
Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
  storing paths of more than 100 bytes is not portable:
  RcwlPipelines/inst/GATK4/gatk4-germline-snps-indels/haplotypecaller-gvcf-gatk4.hg38.inputs.local.json
```

**Comment by Kayla-Morrell** [comment] 2019-03-19 15:05
Hello @hubentu,

I don't have any suggestions for the warnings because I'm not familiar with them. I'm sure Martin will be able to offer some help. Until then, I will ignore these warnings and continue with my initial review. It's my plan to have a review for you by the end of this week. Thank you for your patience.

Best,
Kayla

**Comment by mtmorgan** [comment] 2019-03-19 16:34
For these `WARNING: directory RcwlPipelines/inst/mc3/backup_templates/utils/backup_templates is empty` I guess the problem is that the git repository contains empty directories; you could add these to an .Rbuildignore file in the root of your package if you do not need these directories but they need to be in the git repository; of course removing them from the git repository is also possible...

The second problem is simply that the paths `RcwlPipelines/inst/GATK4/gatk4-germline-snps-indels/haplotypecaller-gvcf-gatk4.hg38.inputs.local.json` have too many characters for some versions of `tar()` (there are 101 characters == bytes in the path above). The solution is to use shorter path names.

**Comment by hubentu** [comment] 2019-03-19 18:12
Hi @mtmorgan ,

Thank you for your help! The .Rbuildignore works perfectly with the empty files.

The files with the long name are from git-submodules of the GATK workflow project.
https://github.com/gatk-workflows/gatk4-data-processing
It would be easier to keep those files consistent with the original git source for future update and maintain. Otherwise, I need to rename the files every time when the project updates. However, if it is necessary, I will rename these files to avoid the warning.

Thanks,
Qiang

**Comment by Kayla-Morrell** [comment] 2019-03-26 13:24
Hi @hubentu ,

Thank you for submitting to _Bioconductor_. Please see the inital review of your package below:

# General Package Development #

*R CMD BiocCheck*

- [ ] SUGGESTION: Recommended biocViews that can be added to the package (if applicable) "DNASeq" and "DataImport".

- [ ] SUGGESTION: Consider adding a NEWS file so your package news will be included in the _Bioconductor_ release announcements.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 4 lines that are > 80 characters long.
	- R/multiqc.R, line 7
	- R/rnaseq_Sf.R, line 6
	- man/multiqc.Rd, line 10
	- man/rnaseq_Sf.Rd, line 9

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces instead of tabs, 5 lines contain tabs.
	- vignettes/RcwlPipelines.Rmd, line 157
	- vignettes/RcwlPipelines.Rmd, line 203
	- vignettes/RcwlPipelines.Rmd, line 204
	- vignettes/RcwlPipelines.Rmd, line 205
	- vignettes/RcwlPipelines.Rmd, line 206
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for line indents. There are 53 lines that are not. See FormatR package (https://cran.r-project.org/web/packages/formatR/index.html) for formatting help.

# Vignettes #

- [ ] SUGGESTION: Line 53 and 54, I would seperate the last r code section into two so that you can use `message=FALSE` when loading the `dplyr` library.

- [ ] CLARIFICATION: Line 73, what is the reason to include `invisible(sapply(scripts, source))`?

- [ ] CLARIFICATION: Line 82, for the "type" should there be a question mark after "File"?

- [ ] REQUIRED: Line 137, "brief" is misspelled.

- [ ] REQUIRED: When going to the url for the DNA alignment pipeline example, the second section should be "Prepare data".

- [ ] REQUIRED: Line 231, remove the \\ at the end of the line so that the bullet points following render correctly. Currently they are not being recognized as bullets.

- [ ] REQUIRED: Line 246, there should not be a space between "GATK" and "4".

Comment back here with updates that have been made and when the package is ready for a re-review.

Best,
Kayla

**Comment by hubentu** [comment] 2019-03-26 18:42
Hi @Kayla-Morrell ,

Thank you very much for your review. I have updated the package based on your comments. Please check.

Thanks,
Qiang

## R CMD BiocCheck
1. DNASeq, RNASeq, DataImport are added to the biocViews.
2. NEWS file added.
3. Formatted.

## Vignettes
1. `message=FALSE` added.
2. The code is to source the Rscript tools to the session, which will be used in the next step for building pipelines.
3. `File?` means this argument is optional, so it can work for both single-end and pair-end reads.
4. Updated all the URLs to the Rcwl book. I will keep updating the draft. Thanks!
5. Removed.
6. Revised.

**Comment by Kayla-Morrell** [comment] 2019-03-27 13:27
Hi @hubentu,

Thank you for the work done on your package. I have looked over the changes made and have just one final requirement before accepting your package. See this requirement below and comment back here when you are ready for me to look over the changes made.

# NEWS file 

- [ ] REQUIRED: See the documentation (https://bioconductor.org/developers/package-guidelines/#news) on how your NEWS file should be formatted. The content is fine, it just needs to be formatted properly.

Best,
Kayla

**Comment by hubentu** [comment] 2019-03-27 14:17
Hi @Kayla-Morrell ,
Updated the NEWS file. Please check.
Thanks,
Qiang

**Comment by mtmorgan** [comment] 2019-04-01 15:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/hubentu.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RcwlPipelines")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RcwlPipelines

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-04-01 15:02 UTC
Labels: 3a. accepted, OK
