### ISSUE TITLE
epidecodeR

### ISSUE THREAD

**Issue by kandarpRJ** [Bioconductor/Contributions#1974] opened 2021-03-17 03:47 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kandarpRJ/epidecodeR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by kandarpRJ** [comment] 2021-03-18 01:49
Hi Kayla-Morrell,

Currently I am pushing changes in repository from my lab system, for which I have added as public key to git. But in few days I am going to lose access to this system after which I will be working using my personal system. I tried pushing changes to bioconductor git using my system and it showed errors. I added public key of my personal system to git but I think its not working. Can you please suggest how to proceed? I have made changes to solve above errors and want to push changes to git and bioconductor.

**Comment by kandarpRJ** [comment] 2021-03-18 02:35
Ok so I added new ssh public key to bioconductor git credential app and made a new push for review. Sorry for the confusion on my side.

**Comment by Kayla-Morrell** [comment] 2021-03-24 17:18
@kandarpRJ - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. Since you
  are using a standard library this file is not necessary and should be removed.

## DESCRIPTION

- [ ] REQUIRED: Set 'LazyData' to 'false' instead of 'true'. It is our
  experience that when this field is set to 'true' it can slow down the loading
of the package, especially if they include data.

- [ ] SUGGESTION: Based on the biocViews tags you have included, consider adding
  the automatically suggest biocViews 'ChipOnChip'.

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field that
  includes the relevant link to GitHub for reporting Issues.

## NAMESPACE

- [ ] REQUIRED: There are packages listed under 'Imports:' in your DESCRIPTION
  file that are not listed in your NAMESPACE file. Please be sure you have all
imports or importFroms listed here.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file so your package news will be
  included in the Bioconductor release announcements.

## Data

- [ ] REQUIRED: Since you include data in the 'inst/extdata' directory there
  needs to be related scripts present in the 'inst/script' directory that very
clearly documents how the data was generated. The scripts can vary but they
should include source urls and any important information regard filtering or
processing. It can be executible code, sudo code, or a text description. A user
should be able to doownload and roughly reproduce the file or object that is
present as data.

## Vignette

- [ ] REQUIRED: The 'Installation' section could use some improvements. First of
  all it isn't necessary to install the packages that are listed as imports in
your package. They will be loaded when the package is. You do not need to
install 'devtools' so this code should be removed. When it comes to installing
the package you should not be installing from GitHub, instead you should be
demonstrating to the user how to install and load from Bioconductor. The code
should look something like the following and include `eval = FALSE`. 

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("epidecodeR")
```

- [ ] SUGGESTION: We strongly encourage the use of table of contents.

- [ ] REQUIRED: Use accessors; do not access S4 class slots via '@'. This is
  used in many of your code chunks in the vignette.

- [ ] REQUIRED: There are sections of code that are included in `echo = FALSE`
  sections. These sections need to be visible to the user so they know how the
variable is created. This is the best practice for reproducible code in your
vignette.

- [ ] REQUIRED: The 'More Examples' section should be removed unless you intend
  to include more examples (this includes line 225).

- [ ] REQUIRED: The final section of the vignette should be 'Session
  Information' and should include `sessionInfo()`.

## Man pages

- [ ] REQUIRED: For functions that are documented but aren't being exported add
  the `@keywords internal` tag to the documentation. This will remove the
function from the documentation index. This will also clear up the BiocCheck
about using dontrun{}/donttest{} in man page examples (for plottingfunc).

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See
  http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

- [ ] REQUIRED: Clarify how 1 obejct is intialized. Maybe it is part of a data
  set loaded with data(), or perhaps part of an object referenced in with() or
withing().
	function (object)
	epidecodeR (IRanges)

- [ ] REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. Found in
  files:
	epidecodeR.R, lines 103, 301, and 361

- [ ] REQUIRED: Avoid the use of direct slot access with `@` or `slot()`.
  Accessor methods should be created and utilized instead.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 138
  lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of using
  tabs. There are 8 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 154 lines that are not.

Best,
Kayla

**Comment by kandarpRJ** [comment] 2021-03-25 07:57
Hi @Kayla-Morrell,

Thank you for reviewing our package. I have made the changes required and suggested by you.

> @kandarpRJ - Thank you for submitting to _Bioconductor_. Please see the initial review of
> the package below. The required changes must be made while the suggested
> changes do not have to be (though we strongly encourage them). Comment back
> here with updates that have been made and when the package is ready for a
> re-review.
> 
> ## General package development
> * [x]  REQUIRED: File LICENSE is not mentioned in the DESCRIPTION file. Since you
>   are using a standard library this file is not necessary and should be removed.

> Removed LICENSE file from git commit

> ## DESCRIPTION
> * [x]  REQUIRED: Set 'LazyData' to 'false' instead of 'true'. It is our
>   experience that when this field is set to 'true' it can slow down the loading
>   of the package, especially if they include data.
 

> Changed LazyData to false

> * [x]  SUGGESTION: Based on the biocViews tags you have included, consider adding
>   the automatically suggest biocViews 'ChipOnChip'.
 

> Added 'ChipOnChip' tag to biocViews

> * [x]  SUGGESTION: We strongly encourage the use of the 'BugReports:' field that
>   includes the relevant link to GitHub for reporting Issues.
 

> Added BugReports: and link to post issues

> ## NAMESPACE
> * [x]  REQUIRED: There are packages listed under 'Imports:' in your DESCRIPTION
>   file that are not listed in your NAMESPACE file. Please be sure you have all
>   imports or importFroms listed here.

>  Added missing imports

> ## NEWS
> * [x]  SUGGESTION: Consider adding a NEWS file so your package news will be
>   included in the Bioconductor release announcements.
 

> Added NEWS file to the package

> ## Data
> * [x]  REQUIRED: Since you include data in the 'inst/extdata' directory there
>   needs to be related scripts present in the 'inst/script' directory that very
>   clearly documents how the data was generated. The scripts can vary but they
>   should include source urls and any important information regard filtering or
>   processing. It can be executible code, sudo code, or a text description. A user
>   should be able to doownload and roughly reproduce the file or object that is
>   present as data.
 

> Included script dir in inst dir. This contains desc.txt file which describes sources of data included as example as well as pseudo code used to generated examples from raw data.

> ## Vignette
> * [x]  REQUIRED: The 'Installation' section could use some improvements. First of
>   all it isn't necessary to install the packages that are listed as imports in
>   your package. They will be loaded when the package is. You do not need to
>   install 'devtools' so this code should be removed. When it comes to installing
>   the package you should not be installing from GitHub, instead you should be
>   demonstrating to the user how to install and load from Bioconductor. The code
>   should look something like the following and include `eval = FALSE`.
> 
> ```
> if(!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("epidecodeR")
> ``` 
 

> Included new instructions of installation of package from bioconductor and removed install_github()

> * [x]  SUGGESTION: We strongly encourage the use of table of contents.

> Added table of content to vignette

> * [x]  REQUIRED: Use accessors; do not access S4 class slots via '@'. This is
>   used in many of your code chunks in the vignette.
 

> Added methods to access slots in S4 class instead of @

> * [x]  REQUIRED: There are sections of code that are included in `echo = FALSE`
>   sections. These sections need to be visible to the user so they know how the
>   variable is created. This is the best practice for reproducible code in your
>   vignette.
 

> Removed echo=FALSE from examples in vignette

> * [x]  REQUIRED: The 'More Examples' section should be removed unless you intend
>   to include more examples (this includes line 225).
 

> Removed line 225 from vignette

> * [x]  REQUIRED: The final section of the vignette should be 'Session
>   Information' and should include `sessionInfo()`.
 

> Added sessionInfo() at the end of vignette

> ## Man pages
> * [x]  REQUIRED: For functions that are documented but aren't being exported add
>   the `@keywords internal` tag to the documentation. This will remove the
>   function from the documentation index. This will also clear up the BiocCheck
>   about using dontrun{}/donttest{} in man page examples (for plottingfunc).
 

> Added @keywords internal to the documentation of plottingfunc function. However when I run biocCheck() locally I still get the note about dontrun(). Is this a problem?

> ## Unit tests
> * [ ]  SUGGESTION: Consider adding unit tests. We strongly encourage them. See
>   http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
 
> ## R code
> * [x]  REQUIRED: Clarify how 1 obejct is intialized. Maybe it is part of a data
>   set loaded with data(), or perhaps part of an object referenced in with() or
>   withing().
>   function (object)
>   epidecodeR (IRanges)
 

> Added initialization for epidecodeR(IRanges)

> * [x]  REQUIRED: Avoid 1:...; use `seq_len()` or `seq_along()` instead. Found in
>   files:
>   epidecodeR.R, lines 103, 301, and 361

>  Added seq_len instead of 1:... at suggested places

> * [x]  REQUIRED: Avoid the use of direct slot access with `@` or `slot()`.
>   Accessor methods should be created and utilized instead.

>  Added methods to access slots in S4 class instead of @

> * [ ]  SUGGESTION: For formatting reasons, consider shorter lines. There are 138
>   lines that are > 80 characters long.
> * [ ]  SUGGESTION: For formatting reasons, consider 4 spaces instead of using
>   tabs. There are 8 lines that contain tabs.
> * [ ]  SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
>   line indents. There are 154 lines that are not.

> Tried to minimize offending formatting

> 
> Best,
> Kayla

Hope the changes are satisfactory. Please tell me if any more changes are required. 

Regards,
Kandarp

**Comment by Kayla-Morrell** [comment] 2021-04-08 16:26
@kandarpRJ - Thank you for making the necessary changes. There are still a few points that need to be addressed before I can accept the package.

## General package development

- [ ] REQUIRED: The LICENSE file is still present in the git repo. Please be sure this gets removed.

## NEWS

- [ ] REQUIRED: Thank you for including a NEWS file but it does not seem to be formatted correctly. Please see our NEWS documentation here - https://bioconductor.org/developers/package-guidelines/#news.

## Vignette
 
- [ ] REQUIRED: The only files that should be present in this directory are the vignette file (.Rmd) and the necessary images (.png). Please remove the .html file.

Best,
Kayla

**Comment by kandarpRJ** [comment] 2021-04-08 22:26
> @kandarpRJ - Thank you for making the necessary changes. There are still a few points that need to be addressed before I can accept the package.
> 
> ## General package development
> * [ ]  REQUIRED: The LICENSE file is still present in the git repo. Please be sure this gets removed.
>  Apologies, I thought I had removed the file but somehow missed it. I have removed the file this time. 
> ## NEWS
> * [ ]  REQUIRED: Thank you for including a NEWS file but it does not seem to be formatted correctly. Please see our NEWS documentation here - https://bioconductor.org/developers/package-guidelines/#news.
>  I have added NEWS.rd file in inst/ dir, I hope this one is in correct format.
> ## Vignette
> * [ ]  REQUIRED: The only files that should be present in this directory are the vignette file (.Rmd) and the necessary images (.png). Please remove the .html file.
>  Removed the html file from vignette folder
> Best,
> Kayla

I pushed to git after making the changes but now build and check is giving me error. 

For windows build it is saying rtracklayer package not found, but I was using this package earlier too and it was building fine then. I dont know how to solve this error.

For linux and mac check error it says "Maintainer must add package name to Watched Tags on the support site; Edit your Support Site User Profile to add Watched Tags.". I dont know what this error means and checking the internet didnt provide any solutions. Can you please help me out in solving these errors?

Regards,
Kandarp

**Comment by kandarpRJ** [comment] 2021-04-09 00:29
Hi @Kayla-Morrell, I figured out that I need to add my package name to watched tag field in profile of support.bioconductor.org and did it (Please see attached screenshot) But after pushing package to git I am still getting error in the checks for linux and mac. Am I doing something wrong here? 

![Screenshot from 2021-04-09 09-22-51](https://user-images.githubusercontent.com/18654381/114111836-ed53ff00-9915-11eb-9fa7-7c190c6be49c.png)

**Comment by Kayla-Morrell** [comment] 2021-04-09 12:10
@kandarpRJ - This is a new check that has been added to BiocCheck. I will check with the devel team to see if I can get you any suggestions to clear up this ERROR.

**Comment by lshep** [comment] 2021-04-09 12:52
@kandarpRJ   When you added the watched tag,  did you remember to go to the bottom of the page and hit "submit" to save the updates to the profile?

**Comment by lshep** [comment] 2021-04-09 12:58
Admittedly this is confusing and we will change the button to say "save" in the future but you must hit "submit" in order for the changes to your profile to actively save.

**Comment by kandarpRJ** [comment] 2021-04-10 01:14
Hi @Kayla-Morrell & @lshep Thank you for helping me out. Sorry it was my bad, I didn't save after adding the tag. I have added the tag and that error has disappeared now.

However, I am still getting error on windows build "ERROR: dependency 'rtracklayer' is not available for package 'epidecodeR'". I used this package previously and the build was successful then. I don't know what to do about this error.

**Comment by lshep** [comment] 2021-04-12 12:16
We Updated R which flushed the available packages.  Currently rtracklayer has an ERROR in windows and is breaking hundreds of package on the builders; the maintainers are aware and in the process of fixing the package but it will be unavailable until they push up a fix.  You can ignore the windows error right now as long as the other two platforms are clean.

**Comment by kandarpRJ** [comment] 2021-04-14 00:30
@lshep Thank you for the clarification and help.

@Kayla-Morrell since we can ignore windows error for now, can we proceed with the review based on build reports of mac and linux to access the changes I made in the latest push?

**Comment by kandarpRJ** [comment] 2021-04-19 21:44
@Kayla-Morrell hi please let me know what more needs to be done to improve the package to get accepted. Awaiting your reply. Thanks

**Comment by Kayla-Morrell** [comment] 2021-04-20 17:09
@kandarpRJ - I have reviewed the required changes and everything looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by vjcitn** [comment] 2021-04-21 13:02
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kandarpRJ.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("epidecodeR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/epidecodeR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-04-21 13:02 UTC
Labels: 3a. accepted, ERROR
