### ISSUE TITLE
TimiRGeN

### ISSUE THREAD

**Issue by Krutik6** [Bioconductor/Contributions#1337] opened 2020-01-14 16:12 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Krutik6/TimiRGeN

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-01-14 18:59
It seems like your package should use SummarizedExperiment or perhaps MultiAssayExperiment as the standard data representation for interoperability and robustness, rather than working with simple data frames / etc.

**Comment by Krutik6** [comment] 2020-01-17 15:48
Thank you for the feedback.

I have looked into SummerisedExperiments and MultiAssayExperiment. It may be worth formulating some of my code to this platform as I do use a lot of data frames. However, since several of my functions rely on lists and fairly complex nested lists, the use of SummerisedExperiments may not entirely appropriate. At this point, I think it is more imperative that I get the package bioconductor ready (passed Build and Checks), and then use the SummerisedExperiments function to tidy my code. 

Fixes which I performed in this version of smiRk:
1) Fixed windows Build error. 
2) Speeded up some of the code. 
3) Fixed unit testing issue. Should work fine on Linux and Mac now.

I predict there may well still be some errors and complications with the windows checks. I would appreciate some guidance on how to resolve these issues when they come up.

**Comment by Krutik6** [comment] 2020-01-29 15:50
Hi there, it has been close to two weeks and was wondering how the review process for the package is going. I imagine there will be quite a bit to change.

**Comment by Krutik6** [comment] 2020-02-12 09:09
Hi @mtmorgan I am currently working on implementing MultiAssayObjects as the standard method of displaying and localising the data in this package, thank you for the advice it does seem very powerful.

@hpages Once I am finished with these updates I may push them on the github. Would this interfere with any review going on with the package? If so I will not push anything until the review is over.

**Comment by hpages** [comment] 2020-02-13 08:16
Hello, I didn't start to review the package yet. If you're going to push important changes to it, I'd rather wait that you do so before I start. Thanks!

**Comment by Krutik6** [comment] 2020-02-14 10:36
@hpages That makes sense. I am aiming to push some major changes soon. One major change is that we have decided to change the package name because we found an old tool with a similar name. Could I ask, what is the best method of changing the name of a submitted package at this point?

**Comment by Krutik6** [comment] 2020-02-19 14:52
@lshep I have followed the instructions to change the package name.

**Comment by lshep** [comment] 2020-02-19 15:14
I have updated in our database.  As long as the webhook is still initialized you should be able to kick off builds on version bumps again.  Please test and let me know if there are any issues.  Cheers

**Comment by Krutik6** [comment] 2020-02-28 14:08
@lshep Thanks for all the help.
@hpages That took a while but it seems that this package is back on track. I do not plan to make anymore major updates unless it is requested.
Changes made:
1) MultiAssayExperiments are now the go to object in the TimiRGeN package.
2) The package has been renamed to TimiRGeN.
3) The checks as a whole have been made faster.
4) Several functions have been edited to remove bugs/ unwanted files. 
5) More data sets have been added to /data folder for vignette building. 
6) Vignettes now build faster because of the added data sets and this avoids bioconductor errors.

Will await any further comments/ review up dates.  All the best. Krutik

**Comment by hpages** [comment] 2020-03-05 18:29
All these changes sound great and like they were worth the wait. Thanks! I'll start reviewing ASAP.

**Comment by hpages** [comment] 2020-03-12 07:40
@Krutik6 ,

Your code needs to adhere to standard practices. E.g.:
```
getIDs_miR_mousetohuman <- function(MAE, miR, mirror = 'useast'){
miR <-cbind(miR, Gene = rownames(miR), name = rownames(miR))
miR$Gene <- gsub(x = miR$Gene, pattern = "-3p", replacement = "")
miR$Gene <- gsub(x = miR$Gene, pattern = "-5p", replacement = "")
human <- biomaRt::useEnsembl("ensembl", dataset="hsapiens_gene_ensembl",
GRCh=37, host = paste0(mirror, ".ensembl.org"))
mouse <- biomaRt::useEnsembl("ensembl", dataset="mmusculus_gene_ensembl",
GRCh=37, host = paste0(mirror, ".ensembl.org"))
bmt <- getLDS(attributes = c("mirbase_id"), filters = "mirbase_id",
values = miR$Gene,mart = mouse,attributesL = c("mirbase_id"), martL = human)
...
```
is **very hard** to read. Please use proper indentation for all your code.

Also in:
```
library(Mfuzz)
mm_miR -> miR
mm_mRNA -> mRNA
StartObject(miR = miR, mRNA = mRNA) -> MAE
e_list -> MAE@metadata$elist
w_list[1:10] -> MAE@metadata$wlist
WikiMatrix(e_list = MAE@metadata$elist, 
wp_list = MAE@metadata$wlist) -> MAE@ExperimentList$Wmat
```
the lack of proper indentation makes it hard for the eye to realize that the last 2 lines are the same command. The fact that you use `->` instead of `<-` makes it even more cryptic. Please always use `<-` for assignment.

This is blocking the review.

Thanks!
H.

**Comment by hpages** [comment] 2020-03-12 07:52
Also you should never use `@` to access the internals of a MultiAssayExperiment object. Always use accessor functions for that. See the documentation of MultiAssayExperiment objects for what accessors are available. Thanks!

H.

**Comment by Krutik6** [comment] 2020-03-12 08:56
Hi @hpages, thank you for the comments, will get on to making these changes right away. Best, Krutik

**Comment by Krutik6** [comment] 2020-03-27 08:51
Hi @hpages the package has undergone the following changes: 
- Now only <- should be found throughout the package
-  Several 'clunky' functions have been removed, may re-introduce in later versions of this package 
- Several tests have been removed to speed up the process of checks
- MAE accessors are now used instead of @, $ symbols
- Indentation is now found throughout the package
- Functions have blank lines in between some lines of code to make them easier to read, and some lines have comments above to help guide reading
- Warnings and messages have been suppressed in a few functions e.g. MultiAssayExperiment, bitr
- dloadmiRTarBase now longer downloads form the server but calls for data found in the TimiRGeN package, this is because the miRTarBase server has been down, most likely due to COVID-19 related reasons. Will restore this function to how it was before, when the servers are back on, most likely in a future version of this package.
- Recreated many of the details in .rd files for internal datasets, this made the package much smaller.
- Vignette shortened greatly
- MAE objects now recur as the primary input and output in most functions 

I hope all these changes make review more accessible. 
Best. Krutik

**Comment by hpages** [comment] 2020-04-17 09:32
Hi @Krutik6,

Thanks for all these changes. Unfortunately the vignette doesn't build for me:
```
hpages@spectre:~$ R CMD build TimiRGeN
* checking for file ‘TimiRGeN/DESCRIPTION’ ... OK
* preparing ‘TimiRGeN’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘TimiRGeN_tutorial.Rmd’ using rmarkdown
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Loading required package: TimiRGeN
.
.
.
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
'select()' returned 1:1 mapping between keys and columns
'select()' returned 1:many mapping between keys and columns
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
Warning in mapply(FUN = FUN, ...) :
  longer argument not a multiple of length of shorter
Warning in base::deparse(e, width) :
  invalid 'cutoff' value for 'deparse', using default
No results
Quitting from lines 311-314 (TimiRGeN_tutorial.Rmd) 
Error: processing vignette 'TimiRGeN_tutorial.Rmd' failed with diagnostics:
subscript out of bounds
--- failed re-building ‘TimiRGeN_tutorial.Rmd’

SUMMARY: processing the following file failed:
  ‘TimiRGeN_tutorial.Rmd’

Error: Vignette re-building failed.
Execution halted
```
Can you please bump the version of the package in order to trigger a new build by the Single Package Builder? So we'll see if it can reproduce this. Thanks!

Best,
H.

**Comment by Krutik6** [comment] 2020-04-17 16:22
Hi @hpages Yes there is a bug that is persisting, odd that this did not come up before on the checks. Will try fixing asap, thank for the feedback. 
Best
Krutik

**Comment by Krutik6** [comment] 2020-04-18 10:36
Hi @hpages, should hopefully be working now. Had to add some extra data files to circumvent a function in the vignette. 
All the best,
Krutik

**Comment by hpages** [comment] 2020-04-21 01:50
Thanks. Right now you use different naming styles for your functions `miRDB_data`, `dloadmiRDB`, `TargetScans_data`, etc... You need to choose a naming style and stick to it. Bioconductor's preference is _camelCaps_. In any case function names should not start with a capital letter except when the function is the constructor function of an S4 class, in which case the function should be named like the class itself (e.g. `MyClass()`).

Thanks again,
H.

**Comment by hpages** [comment] 2020-04-24 19:12
Thanks for renaming the functions. Overall the names look better now.

TimiRGeN is a big package (it defines, exports and documents many functions and datasets) so it will take time to review. It will probably take several iterations before the package is ready for inclusion.

The next thing that is causing problem is that you are not making proper use of the Depends, Imports, and Suggests field. Right now, all your dependencies are listed in Imports. This is not a good idea. Some packages should be moved to Depends (and maybe some should be moved to Suggests). The benefit of putting a package in Depends instead of Imports is that it gets automatically attached to the search path when the user loads your package with `library(TimiRGeN)`. For example, almost everything that TimiRGeN does heavily relies on MultiAssayExperiment objects. So it doesn't really make sense that the user needs to do `library(MultiAssayExperiment)` just to be able to manipulate the object returned by `startObject()`. If they don't do it (and it's easy to forget to do it), they'll get an error:

      library(TimiRGeN)
      MAE <- startObject(miR = mm_miR, mRNA = mm_mRNA)
      assay(MAE)
      # Error in assay(MAE) : could not find function "assay"

This is counter-productive and can be frustrating. In other words, it is not exactly user-firendly that your function returns an object that the user cannot immediately start to manipulate. This can easily be avoided by moving MultiAssayExperiment from Imports to Depends. Then you can remove the dozens of `library(MultiAssayExperiment)` statements that you have in your examples and in the vignette.

Also there is no need to explicitly load all these packages at the beginning of the vignette because you don't use most of them in the vignette. The only packages that you use in the vignette are TimiRGeN, MultiAssayExperiment, org.Hs.eg.db, and org.Mm.eg.db. And once you have MultiAssayExperiment in Depends instead of Imports, the only packages you need to load explicitly are TimiRGeN, org.Hs.eg.db, and org.Mm.eg.db.

Thanks,
H.

**Comment by Krutik6** [comment] 2020-04-28 13:05
Hi @hpages, 
Thank you for the feedback, yes it does make more sense to have most dependencies listed in the depends on section. I have made the requested changes. Also, I do appreciate that TimiRGeN is a large package and that it may take a while before it can be accepted. This is fine, I'm 3/4 years into my PhD, so we have some time :). 
Best,
Krutik

**Comment by hpages** [comment] 2020-05-21 18:16
> yes it does make more sense to have most dependencies listed in the depends on section

Unfortunately that is not what I said. Now I see that you have moved almost everything from Imports  to Depends which is not a good idea either. And the only 2 packages that you didn't move (org.Hs.eg.db and org.Mm.eg.db) are still in the wrong place. Please re-read carefully what I wrote earlier about this and take the time to understand the differences between Depends, Imports, and Suggests. It took me time to write down very detailed explanations and I hope it was not a waste of time. Thanks!

**Comment by Krutik6** [comment] 2020-05-27 17:30
Hi @hpages ,

Sorry I misunderstood the difference between imports and depends. I have read around the subject now.

I have made some corrections and I hope the package now uses imports, suggests and depends more appropriately. I have kept `MultiAssayExperiment` in depends on as most functions use this package. I have also kept `Mfuzz` in depends on, as the `e1071` package and it's `cmeans() ` are not found unless `Mfuzz` is attached to the search path. Keeping `Mfuzz` on depends on seemed appropriate. The two packages which I was on the fence on were `rWikipathways` and `clusterProfiler` because a several main functions in TimiRGeN heavily rely on these packages (`createClusters()`,`dloadGMT()`, `enrichWiki()`, `gmtEnsembl()`, `mirdbData()`, `wikiList()`). They seem to function fine in imports on. I will keep them there unless you suggest otherwise. org.Mm.eg.db and org.Hs.eg.db have been moved to suggests as a user would usually just need one at a time. 

I have also cleaned up quite a lot of code in unit tests and functions, added package::function calls within functions to make importing functions clearer, stopped exporting internal functions and re-introduced `dloadMirtarbase() `and `mirtarbaseData()` functions as the mirtarbase repository server is now back online.  

Hopefully the package is now importing functions and packages more appropriately now. Please do tell me if there are more changes that need to be made on this subject.

All the best,
Krutik

**Comment by Krutik6** [comment] 2020-07-03 09:18
Hi @hpages ,

I haven't heard back from you in a while and was just wondering how the package is doing now?

Hope all is going well.

Best,
Krutik

**Comment by hpages** [comment] 2020-07-21 04:26
Hi @Krutik6 ,

Sorry for the delay. There are still numerous problems with the package. See below.

Best,
H.

1. Your code still uses `->` instead of `<-` in some places.

2. You still have many occurrences of the "retreive" typo.

3. The formatting and numbering of the sections and subsections is broken in the HTML vignette. E.g. the introduction looks like this:
    ```
    #: Introduction Time incorporated microRNA Generation of Networks etc...
    ```
    so is not properly formatted. Also note that it's not numbered but later some sections are and their numbers go from 0.0.1 to 0.0.13 which is a very strange numbering scheme.

4. TimiRGeN exports and documents 55 symbols which is a lot. Are they all relevant for the end user?

5. Please provide more details about your datasets. For example the man pages for `clusterdata`, `clusters`, `c_matrix`, `e_list`, `mfuzzdata`, or `w_list` say very little (and in some cases nothing at all) about what these datasets contain or how the data in them was obtained or generated. Note that if a dataset is not intended to be used or seen by the end user (e.g. `clusters`, `c_matrix`, `Int_data`, and `mfuzzdata`) then there is no need to export or document it.

6. `w_list_human` and `w_list` are datasets for human and mouse, respectively. Why not be a little bit more consistent with how you name your datasets?

7. The Description section in man page for `getIdsMrnaHuman` still contains old name (`getIDs_miR_human`).

8. Also check the Description sections in man pages for `getIdsMirMouse`, `getIdsMrnaHuman`, and `getIdsMrnaMouse`: they all start with the wrong function name.

9. The Description section in man page for `hs_gmt` is just:
    ```
    Description:

         hs_gmt
    ```
    which is not a valid description.

10. Most functions in the package take a MultiAssayExperiment object as first argument but the man page for these functions only says:
    ```
    MAE: MultiAssayExperiment Object.
    ```
    without providing any detail about what the object must contain exactly. For example, it doesn't seem that a function like `diffExpressRes()` will work on an arbitrary MultiAssayExperiment object so the man page should clarify what the expectations are for this object.

11. Note that strictly following the examples in plotting functions `quickBar`, `quickDot`, and `quickNet` won't display anything which could be a little bit confusing for some end users not so familiar with the subtleties of the ggplot2 package.

12. I don't find your error messages particularly helpful e.g.:
    ```
    addIds()
    # Error in addIds() : Check if you are using the correct MAE object.
    addPrefix()
    # Error in addPrefix() : Add MultiAssayExperiment.
    addPrefix(2)
    # Error in addPrefix(2) : Input output from startObject.
    ```
    Really confusing!
    Note that the error message you get by default when the user doesn't supply a mandatory argument is clearer:
    ```
    addPrefix <- function(MAE) return(MAE)
    addPrefix()
    # Error in addPrefix() : argument "MAE" is missing, with no default
    ```
    so there is really not much value in trying to override this. However there is value in checking that the user-supplied arguments are as expected e.g.:
    ```
    addPrefix <- function(MAE) {
        stopifnot(is(MAE, "MultiAssayExperiment"))
        MAE
    }
    addPrefix()
    # Error in is(MAE, "MultiAssayExperiment") : 
    #  argument "MAE" is missing, with no default
    addPrefix(2)
    # Error in addPrefix(2) : is(MAE, "MultiAssayExperiment") is not TRUE
    ```

Thanks!

**Comment by Krutik6** [comment] 2020-07-23 10:06
Hi @hpages 

Thank you for the detailed feedback. Will get on this right away. Will try to have an updated package within 2 weeks time. 

Best,
Krutik

**Comment by Krutik6** [comment] 2020-08-02 10:33
Hi @hpages, 

I have made several changes to the package based on your feedback. Please read below. 

### 1. Your code still uses -> instead of <- in some places.

The `->`'s have all been replaces with `<-` in the functions and tests. 

### 2. Typos and grammar

I have gone through all the functions, the vignette and the tests and corrected for all typos that I found. I also went through the grammar of the vignette, functions and param messages so they are clearer now. 

### 3. Vignette heading formatting and numbering system

The added empty lines between the headings/ subheading and the following text to make the formatting clearer. I also re-numbered the subheadings so the numbering style makes more sense now. Some heading names have also been changed to be more concise.  

### 4. TimiRGeN exports 55 symbols

TimiRGeN now exports 44 symbols, I am not sure if this is still too many, but hopefully this will work better with bioconductor. The 44 symbols include 6 data sets and 38 exported functions. The 38 functions are needed for the end user, and the 6 data sets includes 4 examples data sets for examples : `hs_miR`, `hs_mRNA`, `mm_miR`, `mm_mRNA`, and 2 data sets to speed up running examples : `e_list` and `w_list_mouse`.

       4.1. 7 former data sets are now included in inst/extdata. These are only used in passing vignette building in bioconductor 
               and to speed up the process in vignette building. Also in the vignette code, I have added some text in code blocks with
               `echo=FALSE` to describe why they are needed. 
          
       4.2   The functions `dloadTargetscan`, `dloadMirdb` and `dloadMirtarbase` have been respectfully combined with 
                `targetscanData`, `mirdbData` and `mirtarbaseData`. This helped to reduce the number of exported symbols, and 
                helped with streamlining/ simplifying the package. 

      4.3     `@noRd` added to internal functions `corrTable`, `mirnaFull` and `nonUniuqe` so they are no longer documented.

### 5. Data set details are lacking

I have added more detailed descriptions and details for the remaining data sets which are documented. The other 7 data sets now found in inst/extdata no longer need documentation. Again the other 7 data sets are only used for bioconductor vignette building. 

### 6. Consistent naming of data sets

`w_list` has been re-named to `w_list_mouse`. 

### 7 and 8. Descriptions of getIds functions

I have made the appropriate changes to the getIds man pages and also added to more precise details to the descriptions of all functions.

### 9. Valid descriptions for data sets

A far more detailed approach has been taken for the remaining data sets. 

### 10. Params in man pages lack detail

I have added clear detail on the documentation for each function. Now if a parameter requires extracting data from a MAE, there is very detailed instructions on which particular MAE is needed and where to find the data within the MAE. Furthermore, other params have also had more detail added. I feel any user will now be able to understand the flow of this function much better now and be less likely to be confused. I have tried to keep the English in each param description fairly uniform across the package. 

### 11. Some function will not plot, if the example is followed

I have checked every example and if copied and pasted into a new script, they should all work. 

However, I find a problem in `quickBar` and `quickDot`. 

If plotted in the example and run through CMD check, the following error appears.

`Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  : font family '2' not found in PostScript font database
Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  : invalid font type` 

So keeping this function from plotting is important. But to help users I have added an extra hashed out line 
`q <- quickDot(X = metadata(MAE)[[2]][[1]], Y = metadata(MAE)[[2]][1])
 # to view dot plot enter plot(q)` 

This helps to stop the check CMD error and will help users to see the plot if they wish to. 

###12. If missing messages are poorly detailed

I have added new messages if a parameter is missing. These messages are far more detailed and will help guide a user to understand if any functions are needed to be used prior to the current function. If a data file is missing, the missing message will ask the user to make sure they have used the appropriate functions prior to the current one, but also points out to where the missing file can be found. 

Since this package is very large and used MAE objects to store data, this can be very confusing for users who are more used to data frames/ lists. 

Very clearly, the missing messages will tell the user to look into the assays or metadata of a particular MAE. To point to the right MAE the missing messages will also ask the user to use the MAE which was used in function X. This should help guide users throughout the package. 

I have also made other changes to the package

###13. Made `dataMiningMatrix` more user friendly

If a database server is down, then not all 3 databases can be mined, and none of the down stream analysis can be done. This was a real bottleneck. Now `dataMiningMatrix` can work with any number of downloaded databases. Also this function now only uses base R to work, so `tidyverse` is no longer needed.

        13.1 Removed `tidyverse` from the package and vignette. 

###14.  TimiRGeN now loads `RCy3::cytoscapeping()`

Now RCy3 will not have to be loaded to use `cytoMake`. 

###15. Vignette is now clearer

I changed a lot of the grammar in the vignette making is easier to understand and easier to follow. Also removed some unneeded references. 

I hope the package looks a lot more professional and bioconductor friendly now. 

Best,
Krutik 
```

**Comment by Krutik6** [comment] 2020-08-02 13:31
Hi @hpages,

Just made a small change. `e_list` is now called `e_list_mouse` to stick with the naming style used with `w_list_mouse` and `w_list_human`.

Best,
Krutik

**Comment by hpages** [comment] 2020-09-15 08:57
Hi Krutik,

Thanks for the fixes and improvements, and sorry for the delay.

Note that the section and subsection title still start with `#`'s in the HTML vignette.  I think this is because you're putting a `:` right after the `#`'s. This is not how markdown works. Titles, subtitles, sub-subtitles, etc should start with `# `, `##  `, `### `, etc.  There should be a space after the `#`'s and before the title. No `:`.

Not a show stopper though so I'm letting the package go. You've improved it a lot since the first submission and I'm confident that you'll be able to address the small formatting issue later. Please wait for the package to be added to our git server and to the daily builds before pushing further changes to it. This should take a few days only.

Best,
H.

**Comment by Krutik6** [comment] 2020-09-15 10:35
Thank you so much @hpages for all your help. It has been a journey :) . 

Will update the package to deal with the issues you mentioned above as soon as the package has been added to the git server.

Thanks again, 
Krutik

**Comment by mtmorgan** [comment] 2020-09-15 21:15
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Krutik6.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("TimiRGeN")`. The package 'landing page' will be created at

https://bioconductor.org/packages/TimiRGeN

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-09-15 21:15 UTC
Labels: 3a. accepted, OK
