### ISSUE TITLE
Submit CytoPipeline package (2nd attempt)

### ISSUE THREAD

**Issue by phauchamps** [Bioconductor/Contributions#2838] opened 2022-10-13 12:40 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/UCLouvain-CBIO/CytoPipeline

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-11-12 15:37
```
Quitting from lines 363-365 (CytoPipeline.Rmd) 
Error: processing vignette 'CytoPipeline.Rmd' failed with diagnostics:
'gate_tail' is not an exported object from 'namespace:openCyto'
--- failed re-building ‘CytoPipeline.Rmd’

SUMMARY: processing the following file failed:
```
Please attend to this.

**Comment by phauchamps** [comment] 2022-11-23 13:59
Hi Vince,

The problem above was due to a change in the `openCyto` package, from which the previously exported `gate_tail()` function was removed, without any prior notice :-( Therefore I removed this dependency from the CytoPipeline package, and replaced it by another function.

However, there is still another dependency that prevents my `CytoPipeline` package from checking correctly, in the runExamples and unit test section. This is due to a pending issue in another package from which `CytoPipeline` depends: `ggcyto::scale_x_logicle()` which seems to not converge anymore in the recent Bioc repo commits, and creates build errors in the current Bioc devel build (see http://bioconductor.org/checkResults/release/bioc-LATEST/ggcyto/nebbiolo2-buildsrc.html )

I would have two questions for you:   
1. in your opinion, shall I wait until this build error for ggcyto is solved (it is currently impacting both devel AND release builds in all Bioc technical environments ) or raise myself an issue to ggcyto package's maintainer ? 
2. I have tried to commit my code changes to github repo, but I think that my package has not been incorporated yet in the repo. Could you confirm ? Will it be done when the current issues moves to '2. Review in progress' status ? 

Thanks a lot,

Philippe

**Comment by lshep** [comment] 2022-11-28 12:53
Jumping in here:  I would say feel free to reach out to the maintainer of ggcyto yourself.  We will as well but it is always helpful and sometime knowing someone in the community is waiting on you to fix the issue is an extra motivator to make quick changes. 
you should push changes still to your repo: https://github.com/UCLouvain-CBIO/CytoPipeline  .  the package is still in pre-review phase.  once these issues with dependencies are straightened out, we'll move forward and create the repo on git.bioconductor.org and then you would have to push to both.

**Comment by phauchamps** [comment] 2022-11-28 13:18
Thanks Lori. 
I have posted an issue on ggcyto repo. It is being handled by Mike Jiang. I will let you know when I have pushed a working version again.
Kind regards, Philippe

**Comment by phauchamps** [comment] 2022-12-22 13:57
Hi Lori and Bioc team,
The issues related to dependent package maintenance are now closed. 
Could you please resume the CytoPipeline package submission process, based on the new repo state ? Thanks! Philippe

**Comment by PeteHaitch** [comment] 2023-01-27 03:26
Hi @phauchamps,

Just a heads-up that I won't be able to begin my review of **CytoPipeline** until Friday next week.

Cheers,
Pete

**Comment by PeteHaitch** [comment] 2023-02-07 01:39
Hi @phauchamps,

Thank you for submitting **CytoPipeline** to Bioconductor.
Overall, the package is in great shape, nice work!

In my review below I have separated the issues into **Required** and **Recommended** points that I would ask you to address before the package can be accepted.
Would you please provide line-by-line comments to my initial review so that I know what changes I'm looking for in my re-review.

Cheers,
Pete

## Required

- [ ] The vignette is missing an echoed `library(CytoPipeline)` chunk at the beginning. Without that, a user copy-pasting the code would get an error when they run the first chunk of code.
- [ ] Are **CytoPipelineGUI** and **CytoPipelineUtils** going to be submitted to Bioconductor? The inclusion in the vignette of code related to **CytoPipelineGUI** feels a bit funny given it's only available on GitHub (and Bioconductor aims to restrict dependencies to mainstream repositories such as CRAN and BioC).
- [ ] The [Bioconductor guidelines](https://contributions.bioconductor.org/description.html?q=lazyd#description-lazydata) recommend not include `LazyData: TRUE` unless there are exceptions (and if so to please provide them as part of the review).
  - Aside: you currently use `LazyData: true`; I'm unsure if there is a `true`/`TRUE` distinction.
- [ ] `BiocCheck::BiocCheck()` currently notes `NOTE: License 'GPL (>=3) | file LICENSE' unknown; licenses cannot restrict use`; would you please confirm that the license does not restrict use. I think this is raising a note because it's not a common license that `BiocCheck::BiocCheck()` knows how to handle. We may need someone from @Bioconductor/core to comment on its suitability.
- [ ] Please add an [*Installation* section](https://contributions.bioconductor.org/docs.html#installation) to the vignette.

## Recommended

- [ ] In the vignette, perhaps replace `.scripts/MakeOMIP021Samples` with `r system.file("scripts/MakeOMIP021Samples.R", package = "CytoPipeline")`? I think the user/reader would need to evaluate this code themselves to get the correct path because if the vignette is build on the Bioconductor build system (BBS) then the path would reflect the BBS rather than the user's machine, but I'm not certain.
- [ ] Why `withr::local_tempdir()` and not just `base::tempdir()`?
- [ ] `show(popL_PeacoQC)` has some extraneous whitespace in what's printed by the show()` method, e.g., there appear to be double the intended whitespace in some of this output.

```{r}
> show(pipL_PeacoQC)
Pipeline object for flow cytometry experiment:  OMIP021_PeacoQC 
Sample files: 2  sample file(s)
Scale transformations evaluation queue  has no processing step
Flow frames pre-processing evaluation queue  has no processing step
```

- [ ] Please use `file.path()` instead of `paste0()` to construct file paths (see `?file.path` for reasoning).
  - e.g., in the vignette, `file.path(jsonDir, "OMIP021_flowAI_pipeline.json")` instead of `paste0(jsonDir, "/")`
- [ ] From the vignette, there are a number of warnings when running `execute(pipL_PeacoQC, path = workDir)` and `withr::with_dir(jsonDir, execute(pipL_flowAI, path = workDir))`. For a new user, it can be helpful to add some commentary to the vignette about whether this is typical or whether it is because of some features of the example data and so these can be safely ignored in this case.
- [ ] In the vignette, I recommend additional spacing/separation after output of `execute(pipL_PeacoQC, path = workDir)` and before code chunk starting `# execute flowAI pipeline` because I nearly scrolled past and missed the second chunk.
- [ ] Captions for figures in vignette are strongly recommended.
- [ ] You might write "themself" instead of using the binary "her/himself" (which is still much better than just "himself", so thank you 🏳️‍🌈).
- [ ] Considering adding a [`inst/CITATION` file](https://contributions.bioconductor.org/citation.html).
- [ ] Consider adding a [package man page](https://contributions.bioconductor.org/docs.html#package-level-documentation).
- [ ] Great work with the unit tests! `covr::report()` may help identify any areas for improvement.

**Comment by phauchamps** [comment] 2023-02-08 13:52
Hi @PeteHaitch,

Thanks for reviewing my package and for your comments and suggestions!

Herebelow are my line by line comments.

Cheers,

Philippe

## Required
> * [x]  The vignette is missing an echoed `library(CytoPipeline)` chunk at the beginning. Without that, a user copy-pasting the code would get an error when they run the first chunk of code.  => **ANSWER:** OK, will do!
> * [x]  Are **CytoPipelineGUI** and **CytoPipelineUtils** going to be submitted to Bioconductor? The inclusion in the vignette of code related to **CytoPipelineGUI** feels a bit funny given it's only available on GitHub (and Bioconductor aims to restrict dependencies to mainstream repositories such as CRAN and BioC). => **ANSWER:** regarding **CytoPipelineGUI**, most probably yes, because it contains visualization key functionalities, but the GUI is currently not stable yet is still evolving a lot, so this will be for sometime in the future. Regarding **CytoPipelineUtils**, this package contains a series of wrappers that are meant to be used within a CytoPipeline run. Previously these were included in **CytoPipeline**, but this turned out out to create lots of dependencies in the **CytoPipeline** package, and painful to maintain properly. Now the idea is that **CytoPipelineUtils** gathers all kind of wrappers, including contributions from users. So I don't think I will rush to have it included into Bioconductor, maybe some time in the future, but I am not sure. Note that the vignette itself does not contain any code from **CytoPipelineUtils** (even commented out). 
> * [x]  The [Bioconductor guidelines](https://contributions.bioconductor.org/description.html?q=lazyd#description-lazydata) recommend not include `LazyData: TRUE` unless there are exceptions (and if so to please provide them as part of the review). => **ANSWER**: OK, I will remove it.
>   
>   * Aside: you currently use `LazyData: true`; I'm unsure if there is a `true`/`TRUE` distinction. => **ANSWER** I don't think there is any distinction. I think that `LazyData: true` was generated automatically by `usethis::usedata()`
> * [x]  `BiocCheck::BiocCheck()` currently notes `NOTE: License 'GPL (>=3) | file LICENSE' unknown; licenses cannot restrict use`; would you please confirm that the license does not restrict use. I think this is raising a note because it's not a common license that `BiocCheck::BiocCheck()` knows how to handle. We may need someone from @Bioconductor/core to comment on its suitability. => **ANSWER:** The license terms *are* GPL (>=3), the license file does not add any restriction, it is just made explicit with some template of my institution. I think that the reason I kept it in DESCRIPTION that otherwise BiocCheck was still complaining about a LICENSE file being present, but I'll check and possibly try to amend a bit the DESCRIPTION file. See also the following [blogpost](https://lgatto.github.io/software-licensing/) from my PI, Laurent Gatto.  
> * [x]  Please add an [_Installation_ section](https://contributions.bioconductor.org/docs.html#installation) to the vignette. => **ANSWER:** ok, will do !
> 
> ## Recommended
> * [x]  In the vignette, perhaps replace `.scripts/MakeOMIP021Samples` with `r system.file("scripts/MakeOMIP021Samples.R", package = "CytoPipeline")`? I think the user/reader would need to evaluate this code themselves to get the correct path because if the vignette is build on the Bioconductor build system (BBS) then the path would reflect the BBS rather than the user's machine, but I'm not certain. => **ANSWER:** OK, will make that clearer.
> * [x]  Why `withr::local_tempdir()` and not just `base::tempdir()`? => **ANSWER:** no particular reason, I was just unaware of the `base::tempdir()` version. I will amend it.
> * [x]  `show(popL_PeacoQC)` has some extraneous whitespace in what's printed by the show()` method, e.g., there appear to be double the intended whitespace in some of this output. => **ANSWER:** you are right, I will check.
> 
> ```
> > show(pipL_PeacoQC)
> Pipeline object for flow cytometry experiment:  OMIP021_PeacoQC 
> Sample files: 2  sample file(s)
> Scale transformations evaluation queue  has no processing step
> Flow frames pre-processing evaluation queue  has no processing step
> ```
> 
> * [x]  Please use `file.path()` instead of `paste0()` to construct file paths (see `?file.path` for reasoning).
>   
>   * e.g., in the vignette, `file.path(jsonDir, "OMIP021_flowAI_pipeline.json")` instead of `paste0(jsonDir, "/")` => **ANSWER:** makes sense, will do!
> * [x]  From the vignette, there are a number of warnings when running `execute(pipL_PeacoQC, path = workDir)` and `withr::with_dir(jsonDir, execute(pipL_flowAI, path = workDir))`. For a new user, it can be helpful to add some commentary to the vignette about whether this is typical or whether it is because of some features of the example data and so these can be safely ignored in this case. => **ANSWER:** these warnings come from the packages I am using in my illustrating pipeline (flowAI, peacoQC). I will explicitely comment on these warnings in the vignette, in order to avoid confusing users.
> * [x]  In the vignette, I recommend additional spacing/separation after output of `execute(pipL_PeacoQC, path = workDir)` and before code chunk starting `# execute flowAI pipeline` because I nearly scrolled past and missed the second chunk. => **ANSWER:** ok, will do!
> * [x]  Captions for figures in vignette are strongly recommended. => **ANSWER:** ok, will do !
> * [x]  You might write "themself" instead of using the binary "her/himself" (which is still much better than just "himself", so thank you 🏳️‍🌈). => **ANSWER:** I did not know that, thanks for mentioning this :-) 
> * [x]  Considering adding a [`inst/CITATION` file](https://contributions.bioconductor.org/citation.html). => **ANSWER:** as there is an article in preparation about **CytoPipeline**, I will wait for the manuscript to be issued (e.g. as a pre-print), before customizing the CITATION.
> * [x]  Consider adding a [package man page](https://contributions.bioconductor.org/docs.html#package-level-documentation). => **ANSWER:** ok, will do ! 
> * [x]  Great work with the unit tests! `covr::report()` may help identify any areas for improvement. => **ANSWER:** thank you! Actually, recently I had to deactivate some of my unit tests, due to a [regression bug](https://github.com/tidyverse/ggplot2/issues/5076) in **ggplot2**. I expect to put them back soon, when the bug correction has been released with **ggplot2** version 3.4.1. This should increase the code coverage to 80%+ :-)

**Comment by PeteHaitch** [comment] 2023-02-11 23:57
Thanks, @phauchamps .

Just a reminder to please push the changes to `git@git.bioconductor.org:packages/CytoPipeline` so that the build system can re-build the package as part of the review.
I'll await that before finalising my review.

Thanks,
Pete

**Comment by phauchamps** [comment] 2023-02-13 08:53
Hi @PeteHaitch, just to mention that due to other duties for this week, I will start implementing the agreed changes next week, so you should have a new push by end of next week (at the latest). 

Cheers,

Philippe

**Comment by PeteHaitch** [comment] 2023-02-13 20:50
Hi Philippe,

No problem and thank you for letting me know.

Cheers,
Pete

**Comment by phauchamps** [comment] 2023-02-21 10:31
Hi @PeteHaitch,

Just to let you know that I have commited/pushed all my changes to the repo (version 0.99.5).

Cheers,

Philippe

**Comment by PeteHaitch** [comment] 2023-02-23 21:00
Thank you for making the requested changes, @phauchamps.
I'm happy to accept **CytoPipeline** into Bioconductor.
Congratulations and thank you for your contribution!

**Comment by phauchamps** [comment] 2023-02-23 21:12
Thank you @PeteHaitch ! :-)

**Comment by lshep** [comment] 2023-02-24 13:08
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/phauchamps.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("CytoPipeline")`. The package 'landing page' will be created at

https://bioconductor.org/packages/CytoPipeline

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2023-02-24 13:08 UTC
Labels: OK, 3a. accepted
