### ISSUE TITLE
MesKit

### ISSUE THREAD

**Issue by Wangxin555** [Bioconductor/Contributions#1516] opened 2020-06-13 10:26 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Niinleslie/MesKit

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-06-13 10:29
Please update your package to interoperate with (accept and return) [standard Bioconductor data representations][1] such as GenomicRanges. This increases robustness and interoperability.

[1]: https://bioconductor.org/developers/how-to/commonMethodsAndClasses/

**Comment by Niinleslie** [comment] 2020-06-14 01:37
> Please update your package to interoperate with (accept and return) [standard Bioconductor data representations](https://bioconductor.org/developers/how-to/commonMethodsAndClasses/) such as GenomicRanges. This increases robustness and interoperability.

Hi, we will add a function to coerce objects in MesKit to GRanges objects for additional flexibility.

**Comment by Wangxin555** [comment] 2020-06-17 16:49
@mtmorgan 
@Kayla-Morrell 
Hi, we have updated the dependency of MesKit and have modified some parameters and notifications.

In terms of the build report, although we have tested and passed on all of the three systems, we got three unsupported info and we failed to find a reason. Can you give us a solution or provide us with more information about the buidling process? Thank you so much!

**Comment by Kayla-Morrell** [comment] 2020-06-17 17:08
@Wangxin555 - This is most likely related to the Dockerfile. We don't support Dockerfiles within packages unless you are making an actual contribution to our docker images (which is an entirely different review process). This file can remain in your repository but it will need to be listed in a .gitignore file.
Hope this helps!
-Kayla

**Comment by Wangxin555** [comment] 2020-06-24 09:14
@mtmorgan
@Kayla-Morrell

Hi, we almost fixed all the errors and warnings, but there is one issue that we fail to fix, can you give us some clue? Or, can we know specifically which scripts have this issue?

```
* Checking coding practice...
Warning in tokens[colons, "text"] != c("1", "2") :
  longer object length is not a multiple of shorter object length
Warning in tokens[colons, "text"] != c("1", "2") :
  longer object length is not a multiple of shorter object length
```
Thank you so much!

**Comment by Wangxin555** [comment] 2020-06-24 09:14
@mtmorgan
@Kayla-Morrell

Hi, we almost fixed all the errors and warnings, but there is one issue that we fail to fix, can you give us some clue? Or, can we know specifically which scripts have this issue?

```
* Checking coding practice...
Warning in tokens[colons, "text"] != c("1", "2") :
  longer object length is not a multiple of shorter object length
Warning in tokens[colons, "text"] != c("1", "2") :
  longer object length is not a multiple of shorter object length
```
Thank you so much!

**Comment by Kayla-Morrell** [comment] 2020-06-25 18:54
@Wangxin555 - I've done a little digging into the warnings you mentioned. This doesn't trigger an actual WARNING or ERROR in the build report from BiocCheck so it's safe to ignore them for now. We will be looking into BiocCheck to hopefully clear this up. Thank you for bringing them to our attention.

Best,
Kayla

**Comment by Wangxin555** [comment] 2020-06-30 01:11
@Kayla-Morrell @mtmorgan 

Hi, we have fixed all the errors and warnings, what should we do next?

**Comment by Kayla-Morrell** [comment] 2020-06-30 01:27
@Wangxin555 - I will do a formal review of the package and comment back here with any required/suggested changes to be made before the package can be accepted. This process can take up to two weeks but I will try to have the review posted sooner than that.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2020-07-01 17:19
Hello @Wangxin555,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        - Sequencing
        - GUI

- [ ] REQUIRED: Since you call `library(org.Hs.eg.db)` and `library(clusterProfiler)`
in the vignette, these packages should be listed under 'Suggests:' since they 
aren't needed for functionality in your package but would be needed to run the 
vignette.

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field which
should include the relevant link to GitHub for reporting Issues.

- [ ] SUGGESTION: The 'git_url' and 'git_last_commit_date' fields are
necessarily needed.

## NAMESPACE

- [ ] REQUIRED: Add the following to the NAMESPACE (as well as the DESCRIPTION 
file) to clear up some of the undefined global functions/variables:
	- importFrom("grDevices", "boxplot.stats", "colors")
	- importFrom("stats", "approxfun", "fisher.test", "integrate", "lm", 
	"median", "na.omit", "qnorm")
	- importFrom("utils", "combn")

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an 
entire package. Using `import()` is acceptable if there are many functions 
being used from a single package. Decrease the number of `import()` used, if 
possible.

- [ ] REQUIRED: There are two packages (`tidyr` and `mclust`) that are listed as 
imports in the DESCRIPTION file but are not listed in the NAMESPACE file. This 
should be resolved.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements. See the following for formatting 
help:
https://bioconductor.org/developers/package-guidelines/#news.

## inst/script/

- [ ] REQUIRED: Since you include 'inst/extdata/' in your package, all the files 
need to be documented. This is done in an 'inst/script/' directory. The scripts 
in this directory can vary. Most importantly a related script must be present in 
this directory documenting very clearly how the data was generated. The script 
should include source urls and any important information regarding filtering or 
processing. It can be executible code, sudo code, or a text description. A user 
should be able to download and roughly reproduce the file(s) or object(s) in 
'inst/extdata'.

## Vignettes

- [ ] REQUIRED: All in-line code should use single \` not triple, triple is used 
when creating blocks of code (like like 108). Please make the necessary changes
	- for example, lines 77, 86, 91, 95, 101, etc.

- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how 
to download and load the package from Bioconductor. The code should look 
something like the following and should include `eval=FALSE`:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("MesKit")
```

## Man pages

- [ ] SUGGESTION: We stronly encourage having a package man page with an overview 
of the package and links to the main functions.

- [ ] REQUIRED: Man pages describing new classes must be very detailed on the 
structure and what type of information is stored. All the class man pages need 
more information.

- [ ] REQUIRED: There should be an example for the following man page which 
documents an exported objects, runMesKit.Rd. Since this is a shiny function I 
would suggest including it in `donttest{}`. This way the user can understand how 
to run the function but the shiny code won't be deployed. Using `donttest{}` 
instead of `dontrun{}` will insure that you are using valid R code. 

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See 
the following with unit test help:
https://bioconductor.org/developers/package-guidelines/#unittest.

## R code

- [ ] REQUIRED: There are 269 object are are not initialized (undefined global 
functions or variables). These should be cleaned up as much as possible.

- [ ] REQUIRED: Various apply functions should be used instead of for loops (use 
`vapply()` instead of `sapply()` when possible).

- [ ] REQUIRED: Avoid the use of direct slot access with `@`. Accessor methods 
should be created and utilized instead. Applies mainly to 'compareTree.R' lines 
51 and 52, since this function is exported.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 815 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. 
There are 63 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 2706 lines that are not.

Best,
Kayla

**Comment by Wangxin555** [comment] 2020-07-02 15:37
# Isuues need yo be fixed
## DESCRIPTION

- [ ] SUGGESTION: Consider adding these automatically suggested biocViews:
        - Sequencing
        - GUI

- [ ] REQUIRED: Since you call `library(org.Hs.eg.db)` and `library(clusterProfiler)`
in the vignette, these packages should be listed under 'Suggests:' since they 
aren't needed for functionality in your package but would be needed to run the 
vignette.

- [ ] SUGGESTION: We strongly encourage the use of the 'BugReports:' field which
should include the relevant link to GitHub for reporting Issues.

- [ ] SUGGESTION: The 'git_url' and 'git_last_commit_date' fields are
necessarily needed.

## NAMESPACE

- [ ] REQUIRED: Add the following to the NAMESPACE (as well as the DESCRIPTION 
file) to clear up some of the undefined global functions/variables:
	- importFrom("grDevices", "boxplot.stats", "colors")
	- importFrom("stats", "approxfun", "fisher.test", "integrate", "lm", 
	"median", "na.omit", "qnorm")
	- importFrom("utils", "combn")

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an 
entire package. Using `import()` is acceptable if there are many functions 
being used from a single package. Decrease the number of `import()` used, if 
possible.

- [ ] REQUIRED: There are two packages (`tidyr` and `mclust`) that are listed as 
imports in the DESCRIPTION file but are not listed in the NAMESPACE file. This 
should be resolved.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file, so your package news will be 
included in Bioconductor release announcements. See the following for formatting 
help:
https://bioconductor.org/developers/package-guidelines/#news.

## inst/script/

- [ ] REQUIRED: Since you include 'inst/extdata/' in your package, all the files 
need to be documented. This is done in an 'inst/script/' directory. The scripts 
in this directory can vary. Most importantly a related script must be present in 
this directory documenting very clearly how the data was generated. The script 
should include source urls and any important information regarding filtering or 
processing. It can be executible code, sudo code, or a text description. A user 
should be able to download and roughly reproduce the file(s) or object(s) in 
'inst/extdata'.

## Vignettes

- [ ] REQUIRED: All in-line code should use single \` not triple, triple is used 
when creating blocks of code (like like 108). Please make the necessary changes
	- for example, lines 77, 86, 91, 95, 101, etc.

- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how 
to download and load the package from Bioconductor. The code should look 
something like the following and should include `eval=FALSE`:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("MesKit")
```

## Man pages

- [ ] SUGGESTION: We stronly encourage having a package man page with an overview 
of the package and links to the main functions.

- [ ] REQUIRED: Man pages describing new classes must be very detailed on the 
structure and what type of information is stored. All the class man pages need 
more information.

- [ ] REQUIRED: There should be an example for the following man page which 
documents an exported objects, runMesKit.Rd. Since this is a shiny function I 
would suggest including it in `donttest{}`. This way the user can understand how 
to run the function but the shiny code won't be deployed. Using `donttest{}` 
instead of `dontrun{}` will insure that you are using valid R code. 

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See 
the following with unit test help:
https://bioconductor.org/developers/package-guidelines/#unittest.

## R code

- [ ] REQUIRED: There are 269 object are are not initialized (undefined global 
functions or variables). These should be cleaned up as much as possible.

- [ ] REQUIRED: Various apply functions should be used instead of for loops (use 
`vapply()` instead of `sapply()` when possible).

- [ ] REQUIRED: Avoid the use of direct slot access with `@`. Accessor methods 
should be created and utilized instead. Applies mainly to 'compareTree.R' lines 
51 and 52, since this function is exported.

- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 815 
lines that are > 80 characters long.

- [ ] SUGGESTION: For formatting reasons, consider 4 spaces instead of tabs. 
There are 63 lines that contain tabs.

- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for 
line indents. There are 2706 lines that are not.

**Comment by Wangxin555** [comment] 2020-07-22 15:25
@Kayla-Morrell

Hello, we have almost fixed all the issues listed as 'required' in your checklist, and we are now working on the isssues suggested to be solved. 
Could you please check MesKit again and get us a feedback? Thank you so much!

**Comment by Kayla-Morrell** [comment] 2020-08-03 17:09
Hello @Wangxin555 - Things are looking good. I have one minor point for you to look at. Thank you for adding the `inst/script` directory and including proper documentation. However, there seem to be some data files listed here that aren't included in the `inst/extdata` directory. Once this change is done and all other changes are finished being made I'll be happy to accept the package.

Best,
Kayla

**Comment by Wangxin555** [comment] 2020-08-04 10:11
@Kayla-Morrell 
Hi, thank you so much for your feedback. 
We have fixed the issue you mentioned, now all data files listed under ```inst/script``` are included in the ```inst/extdata``` directory. Besides, we also fixed some tiny bugs.

**Comment by Kayla-Morrell** [comment] 2020-08-04 16:12
@Wangxin555 - Thank you for making that change. Everything looks good now and I'm more than happy to accept the package.

Best,
Kayla

**Comment by Wangxin555** [comment] 2020-08-07 03:13
@Kayla-Morrell
Thank you so much for checking and accepting MesKit. 
In order to better promote the usage of this package, we would appreciate it if you could tell us when can we get an official Bioconductor website for MesKit.

**Comment by Wangxin555** [comment] 2020-08-07 03:13
@Kayla-Morrell
Thank you so much for checking and accepting MesKit. 
In order to better promote the usage of this package, we would appreciate it if you could tell us when can we get an official Bioconductor website for MesKit.

**Comment by Kayla-Morrell** [comment] 2020-08-07 12:44
@Wangxin555 - This part I am not responsible for, but normally it takes about a week from acceptance to be added into the manifest. Then once a clean build is produced on all three of our builders the landing page will be available. There will be more details posted here when this is done.

**Comment by Wangxin555** [comment] 2020-08-07 13:05
Thank you very much!

**Comment by mtmorgan** [comment] 2020-08-10 17:01
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Wangxin555.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MesKit")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MesKit

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-08-10 17:01 UTC
Labels: 3a. accepted, OK
