### ISSUE TITLE
IMAS

### ISSUE THREAD

**Issue by hangost** [Bioconductor/Contributions#310] opened 2017-03-08 23:16 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/hangost/IMAS
Confirm the following by editing each check box to '[x]'

- [ x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ x ] The 'devel' branch for new packages and features.
- [ x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by lawremi** [comment] 2017-03-08 23:38
It seems this could make better use of the GenomicAlignments package. Custom CIGAR parsing code, looping over individual reads, etc, are red flags.

**Comment by lshep** [comment] 2017-03-10 14:44
Thank you for your submission. Please see the following: 

**GENERAL:**
 - [ ] It would help to shorten lines to 80 characters so you could read them when accessing via web browswer on github
 - [ ] Please address @lawremi comments above. There seems to be similar functionality already provided in GenomicAlignments - Either genomicAlignments should be used or please give details on how the functionality differ. 

**VIGNETTE:**
 - [ ] Add installation instructions to vignette also. 
 - [ ] Save output when creating visualization to a tempdir()

**MAN PAGES:** 
 - [ ] perhaps a cleaner way in examples than a  bunch of commented out code is dontrun{} for sections of code that should not be executed
 - [ ] you don't run any of your functions in the examples ... why?
 - [ ] for your sample data more information on how the data was generated and where the data was generated - not just that it is provided with the package.
 - [ ] IMAS-package.Rd - expand on details, suggest or list the main functions for use, give a workflow example 
 - [ ] test - delete

**R code:** 
 - [ ] Avoid use of 1:n; use seq_len(n) or seq_along(x) instead. this is also true for  1:nrow() etc. and problems when nrow() == 0; use seq_len(nrow()) instead.
 - [ ] You also use a lot of applys - preallocate - See:  http://bioconductor.org/developers/how-to/efficient-code/
 - [ ] (Optional) Use BiocParallel rather than foreach; it provides users with a more consistent experience in the Bioconductor universe.


After updates have been made please comment back here with how the above issues have been addressed. Thank you.

**Comment by lshep** [comment] 2017-03-28 12:35
As we are nearing the next release [(release schedule)](http://bioconductor.org/developers/release-schedule/) I wanted to check in to see if you had any questions or comments.  We would love to be able to include your package in the next release if we can get it through the review process.  Please address the above issues and comment back here with how they have been addressed or any questions or concerns you are encountering.

**Comment by hangost** [comment] 2017-03-30 00:22
Dear  reviewers, 
We sincerely appreciate for considering our R package entitled “IMAS: Integrative Analysis of Multi-omics data for Alternative Splicing”. We agreed with and addressed the comments and suggestions from the reviewers. We submitted the point-by-point response to those comments with revised source codes:
GENERAL:
1. It would help to shorten lines to 80 characters so you could read them when accessing via web browswer on github
- We thoroughly modified to shorten lines to 80 characters in source codes, but do I need to do them in NAMESPACE, manual, and etc. as well?
2. Please address @lawremi comments above. There seems to be similar functionality already provided in GenomicAlignments - Either genomicAlignments should be used or please give details on how the functionality differ.
- We modified source codes to use the extractAlignmentRangesOnReference function in the GenomicAlignments package and the cigarParsing.R function was removed. In addition, we used the readGAlignments function in the GenomicAlignments package, instead of the ReadBamToPosition.R function to extract reads from bam files. 

VIGNETTE:
1. Add installation instructions to vignette also.
- We added the installation instructions to vignette.
2. Save output when creating visualization to a tempdir()
- we modified a source code to add the option of save output.

MAN PAGES:
1. perhaps a cleaner way in examples than a bunch of commented out code is dontrun{} for sections of code that should not be executed
- we modified a source code to make an example clear.
2. you don't run any of your functions in the examples ... why?
- The visualization is the last step of the package workflow. Since the function ASvisualization.R for the visualization performs every example in other analysis functions such as, ClinicAnalysis.R, MEsQTLFinder.R, and etc.. The example in other functions without the ASvisualization.R can be redundant.
3. for your sample data more information on how the data was generated and where the data was generated - not just that it is provided with the package.
- We added more information to clearly explain the example data.
4. IMAS-package.Rd - expand on details, suggest or list the main functions for use, give a workflow example
- We added more information for the workflow example.
5. test – delete
- We deleted.

R code:
1. Avoid use of 1:n; use seq_len(n) or seq_along(x) instead. this is also true for 1:nrow() etc. and problems when nrow() == 0; use seq_len(nrow()) instead.
- We thoroughly modified source codes to use seq_along and seq_len, instead of 1:n, 1:nrow(), nrow, and etc.
2. You also use a lot of applys - preallocate - See: http://bioconductor.org/developers/how-to/efficient-code/
- We modified source codes to minimally use applys, and preallocate variables.
3. (Optional) Use BiocParallel rather than foreach; it provides users with a more consistent experience in the Bioconductor universe.
- We modified source codes to use BiocParallel instead of foreach, and this can be applied after this update.

Thanks.

**Comment by lshep** [comment] 2017-03-30 11:26
Could you please make sure your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) is set up properly.  Normallly when the webhook is initialized the automatic build will happen with a version bump.   I'll kick off a manual build this time but please check.  I will review and get back soon with any other feedback

**Comment by lshep** [comment] 2017-03-30 13:32
Could you please look into the windows ERROR that is occurring.

**Comment by hangost** [comment] 2017-03-30 23:34
Thank you very much for your feedbacks!!!
 I will check the error.

Thanks!

**Comment by lshep** [comment] 2017-04-03 11:44
Ignore this ERROR for now.  I will review the package and get back to you shortly with any other comments

**Comment by lshep** [comment] 2017-04-04 11:49
There is still an ERROR on tokay2 that needs to be addressed.  I can reproduce it and it occurs as specified in code chunk number 12: Splicingfinder function   when running ExonsCluster(ASdb, transdb).


Here is the traceback()
```
> traceback()
5: stop(simpleError(msg, call = expr))
4: e$fun(obj, substitute(ex), parent.frame(), e$data)
3: foreach(alt.num = seq_along(alt.gene), .packages = called.packages,
       .combine = rbind) %dopar% {
       over.num <- Alt.mat[, "EnsID"] == alt.gene[alt.num]
       Alt.mat <- rbind(Alt.mat[over.num, ])
       if (alt.type == "ES") {
           each.result <- rbind(ES.Alt.result(Alt.mat))
       }
       else if (alt.type == "ASS") {
           each.result <- rbind(ASS.Alt.result(Alt.mat))
       }
       else if (alt.type == "IR") {
           each.result <- rbind(IR.Alt.result(Alt.mat))
       }
       spl.nums <- grep("Spl|spl", colnames(each.result))
       e.chr <- unique(Alt.mat[, "Nchr"])
       each.result <- rbind(each.result[, -spl.nums])
       each.result <- cbind(EnsID = alt.gene[alt.num], Nchr = e.chr,
           Strand = unique(Alt.mat[, "Strand"]), each.result)
       each.result
   }
2: for.f(each.mat, ES.gene, "ES")
1: ExonsCluster(ASdb, transdb)
```
When I debug a little further is seems to fail:
```
debug: each.mat <- Alt.splice.result$ES
Browse[2]>
debug: each.re <- for.f(each.mat, ES.gene, "ES")
Browse[2]>
Error in { : task 1 failed - "could not find function "ES.Alt.result""
 ```

I hope this helps a little for you to debug the issue.

**Comment by hangost** [comment] 2017-04-05 12:46
Dear lshep,
I very much appreciate for your helps!!

There were some variables with errors because of their environments in only Windows server.
Unfortunately, since I can't see the error in my locals, which are in MAC OS, Linux, and Windows 10, (the package build were successfully finished in all of the locals), I need to modify the codes, uploading in GitHub and pushing to the bioconductor server. So, I'm sorry to push the package and bump versions too much. 

The source codes are completely corrected, but there is an error to be not able to find vignette pdf file in only Windows server. 
I'm not sure why this is occurred.
Any help you can provide would be very much appreciated.

Thanks,
Seonggyun.

**Comment by lshep** [comment] 2017-04-05 13:06
I think this ERROR is something on our build system.  I will review the changes you made thus far.

**Comment by lshep** [comment] 2017-04-05 13:47
Thank you for making the other changes.  I will mark your package as accepted.  Please keep the issue open and you will receive svn instructions via email soon (normally within a week).   
Please note:  If the windows ERROR persists on the daily build system, your attention will be needed immediately to remedy.

**Comment by hangost** [comment] 2017-04-05 15:24
Dear,
I sincerely appreciate for your helps and considering this R package. 
I will check them! Thanks.

Can I change codes a little before or after storing in the svn? I have a plan to change codes with BiocParallel instead of foreach. 
And, could this package release to the next version?

Thanks,
Seonggyun.

**Comment by lshep** [comment] 2017-04-05 15:39
Your code can always be updated and you will have access to make any changes you deem necessary.  @mtmorgan any additional comments on this?

**Comment by mtmorgan** [comment] 2017-04-05 19:46
Yes your package will be added to the nightly builds and svn repository. You'll receive an email in a couple of days with additional instructions, including on how to update the svn repository with your latest revisions. These will be included in the next Bioconductor release.

**Closed** 2017-04-07 20:14 UTC
Labels: 3a. accepted, ERROR
