### ISSUE TITLE
scMET: Bayesian modelling of DNA methylation heterogeneity at single-cell resolution

### ISSUE THREAD

**Issue by andreaskapou** [Bioconductor/Contributions#2585] opened 2022-03-23 18:09 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/andreaskapou/scMET

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-03-24 09:36
This is a very interesting submission.  
```
suppressPackageStartupMessages(library(scMET))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(magrittr))
set.seed(123)
```
magrittr should not be needed insofar as R 4.1 includes `|>`.  Also you have a particular format for single cell data and do not use Bioconductor's SingleCellExperiment class.  This will increase efforts for users to transform the customary representation to your format.  Please introduce converters or adapters or add code to accommodate this representation.

**Comment by andreaskapou** [comment] 2022-03-27 20:18
Hi,

Thanks for the suggestions! I added conversion function going from scmet to SCE objects and vice versa. I also added a section in the vignette file to highlight this functionality!  Bumped package version and pushed it on Github.

Bestm
CAK

**Comment by andreaskapou** [comment] 2022-04-01 08:02
Hi any update on this? Should I do any more changes? Since the deadline for new Bioconductor packages is ending soon. Thanks again!

**Comment by lshep** [comment] 2022-04-01 13:19
The deadline for packages in the queue to make the release is end of April so there is still time.  We will look at the package shortly.

**Comment by vjcitn** [comment] 2022-04-03 11:04
Is this from your code?
```
## Chain 1: ------------------------------------------------------------
## Chain 1: EXPERIMENTAL ALGORITHM:
## Chain 1:   This procedure has not been thoroughly tested and may be unstable
## Chain 1:   or buggy. The interface is subject to change.
## Chain 1: ------------------------------------------------------------
## Chain 1: 
```
Do we want this at this stage?

**Comment by andreaskapou** [comment] 2022-04-04 11:11
Hi, thanks for the update!

No, actually the message comes from `rstan` where my probabilistic model is built. They still consider their Variational inference procedure experimental (see here: https://mc-stan.org/rstan/reference/stanmodel-method-vb.html) and they show this message whenever the function is called. I am happy to keep this message showing to the user, until its removed from `rstan`.

Thanks.

**Comment by andreaskapou** [comment] 2022-04-07 19:16
Hi, 

The package was built and there were no errors only a single warning from the `BiocCheck` build report, which I am not sure what it means:

`* Checking Package Dependencies...
Warning in system2(cmd, args, stdout = TRUE, stderr = FALSE, env = "R_DEFAULT_PACKAGES=NULL") :
  running command 'R_DEFAULT_PACKAGES=NULL '/Library/Frameworks/R.framework/Resources/bin/R' -q --vanilla --slave -f /Library/Frameworks/R.framework/Versions/4.2/Resources/library/BiocCheck/script/checkBadDeps.R --args "/Users/pkgbuild/packagebuilder/workers/jobs/2585/7c83e86ea30a7a4ddce974da0bb582d1ec3d5c6a/scMET_0.99.4.tar.gz" "/var/folders/7y/c__3_48d5y18p1_rhfs_4x9c0000gt/T//RtmpTggVSV/file26656999e55/lib" 2>/dev/null' had status 1`

I saw this error appeared in #2488 and you mentioned this was a bug in BiocCheck and now has been fixed. Could you let me know how should I proceed?

Thanks in advance!

Best,
CAK

**Comment by LiNk-NY** [comment] 2022-04-12 19:06
Hi @andreaskapou 

Yes, this has been fixed in `Bioconductor/BiocCheck@output` which will be merged soon. You can ignore it.
FYI, R has replaced mentions of `--slave` for the `--no-echo` flag.

Pete @PeteHaitch will provide a review in due time. Thanks Pete!

Best,
Marcel

**Comment by PeteHaitch** [comment] 2022-04-20 07:58
Hi @andreaskapou,

Thank you for submitting **scMet** to Bioconductor.
I'm excited to see tools for analysing single-cell methylation data!

That said, I don't think @vjcitn's initial concern about usage of and interoperability with the core Bioconductor class for storing single-cell data (_SingleCellExperiment_) is adequately addressed in the current version.
Before accepting the package, I think that the converter functions need to be re-designed (discussed below).

Longer term, I think having the main **scMET** function(s) accept a _SummarizedExperiment_-derived class (e.g., _SingleCellExperiment_ or _BSseq_ from **bsseq**) would be highly desirable rather than requiring the user to do the interop as separate step(s).
A _SummarizedExperiment_-derived class is a much more natural (and richer, better-supported, more-tested, etc.) data structure than **scmet**'s _ad hoc_ S3 classes. 
Perhaps it is necessary to ultimately create a *data.table*/*data.frame* representation of the data to pass to the **rstan**-based or **ggplot2**-based functionality (that's not clear to me right now), but I really think it would be a big improvement to keep the *data.table*/*data.frame* representation as the internal business of **scMET** (rather than exposing it to the user) and instead exposing a more Bioconductor-familiar interface based on _SummarizedExperiment_-derived objected to users.

For acceptance into Bioconductor, there are a number of Required points, as well as Recommended points, that I would ask you to first please address.
Would you please provide line-by-line comments to my initial review so that I know what changes I'm looking for in my re-review.

Cheers,
Pete

### Required

- [ ] Re-design of converters between the **scmet** format and _SingleCellExperiment_ class. 
  - [ ] The use of a special value (`-1`) to identify CpGs with no coverage is (1) unnecessary and (2) destroys the sparsity of the resulting matrices. Instead, just store a `0` in the corresponding entries of the `met` and `total` matrices; CpGs with no coverage can then be identified by those with a `0` in the `total` entry and there is no loss of sparisty for either the `met` or `total` matrices. 
  - [ ] When constructing the _SummarizedExperiment_-derived representation of the data, I would strongly consider storing the covariates `X` as metadata on the features (CpGs), i.e. as `metadata(rowData(sce))` rather than `metadata(sce)`.
- [ ] Do not use direct slot access with `@`; please use the accessor instead (e.g., instead of `sce@metadata` use `metadata(sce)`).
- [ ] The use of R's S3 object oriented system seems to me a bit non-standard. Bioconductor prefers _S4_ but I don't think it's a strict requirement (see https://contributions.bioconductor.org/r-code.html?q=S4#class-design); pinging @vjcitn for clarification. Admittedly, I mostly use S4 (due to Bioconductor's extensive reliance on it), but I am familiar enough with S3 through everyday R usage and resources such as https://adv-r.hadley.nz/s3.html to notice some things that seem a bit odd and might be refined:
  - In several please you are creating *ad hoc* S3 classes (e.g., *bb_mle* from `bb_mle()`, *scmet_mcmc* and *scmet_vb* from `scmet()`, *scmet_simulate* and *scmet_simulate_diff* from `scmet_simulate()`, and *scmet_differential* from `scmet_differential()`) but there are no methods defined for these classes (E.g., `methods(class = "bb_mle")` returns `no methods found`).
  - Instead, within a general function (e.g., `scmet_plot_efdr_efnr_grid()`) you're using if-else statements based on the class of the object to perform the required functionality. 
  - In S3, this would usually be achieved by defining an S3 generic and associated S3 methods, e.g., the generic `scmet_plot_efdr_efnr_grid()` and associated methods `scmet_plot_efdr_efnr_grid.scmet_mcmc()`, `scmet_plot_efdr_efnr_grid.scmet_vb()`, and `scmet_plot_efdr_efnr_grid.scmet_differential()`.
  - I believe `inherits()` is preferred to `is()` for S3 (https://adv-r.hadley.nz/s3.html#s3-classes and `?class`).
- [ ] Don't call `set.seed()` within a function. Instead, document to the user that they will need to `set.seed()` prior to calling the relevant function in order to get reproducible results.
- [ ] Pinging @vjcitn: I'm not sure what to make of several of the **scMET** functions having a `seed` argument due to their internal use of `rstan::sampling()`; it seems that this is just the done thing with **rstan** (rather than using R's RNG) and any package using it just has to deal with it?
- [ ] How many `iter` are required when running `scmet()`? Because setting it to 20,000 (as advised in vignette) still gave messages about the algorithm potentially not converging:

``` r
suppressPackageStartupMessages(library(scMET))
fit_obj <- scmet(Y = scmet_dt$Y, X = scmet_dt$X, L = 4,
                 iter = 20000, seed = 12)
                 
# A whole bunch of output omitted ...

#> Chain 1: Informational Message: The maximum number of iterations is reached! The algorithm may not have converged.
#> Chain 1: This variational approximation is not guaranteed to be meaningful.
#> Chain 1: 
#> Chain 1: Drawing a sample of size 2000 from the approximate posterior... 
#> Chain 1: COMPLETED.
#> Warning: Pareto k diagnostic value is 3.14. Resampling is disabled. Decreasing
#> tol_rel_obj may help if variational algorithm has terminated prematurely.
#> Otherwise consider using sampling instead.
#> Wed Apr 20 16:13:58 2022 : Posterior inference finished.
```

- [ ] Not clear why the outer `plot()` is required in `plot(scmet_plot_estimated_vs_true(obj = fit_obj, sim_dt = scmet_dt, param = "gamma", mle_fit = bbmle_fit))` from the vignette; it wasn't when I ran the code myself in the console.
- [ ] From the vignette: "Many thanks to John Riddell for the conversion functions.". John should be acknowledged as an author in the `DESCRIPTION`.
- [ ] Please remove the `LICENSE` file (it is not required when using a 'standard' license like GPL-3).
- [ ] `inst/stan/include/license.stan` seems redundant with the top-level license (i.e. `License` field in the `DESCRIPTION`).
- [ ] `inst/include/stan_meta_header.hpp` is essentially empty. Is it required?
- [ ] Please make an effort to address all `WARNINGS` and `NOTES` produced by `BiocCheck::BiocCheck()`. In particular, I would expect these to be remedied as advised (unless there are exceptional reasons):

```
* NOTE: 'LazyData:' in the 'DESCRIPTION' should be set to false or
      removed
* NOTE: Update R version dependency from 4.1.0 to 4.2.0.
* NOTE: Avoid sapply(); use vapply()
* NOTE: Avoid 'cat' and 'print' outside of 'show' methods
* NOTE: Avoid using '=' for assignment and use '<-' instead
* NOTE: Avoid redundant 'stop' and 'warn*' in signal conditions
* WARNING: Remove set.seed usage (found 2 times)
* NOTE: Consider adding runnable examples to the following man pages
  which document exported objects:
  create_design_matrix.Rd, sce_to_scmet.Rd, scmet_to_sce.Rd
```

- [ ] Please upate the installation instructions in the `README` and vignette to the official Bioconductor installation instructions (can be delayed until after acceptance). These will be:

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("scMET")
```


### Recommended

- [ ] It is strongly recommended that you add additional unit tests. Try running `covr::report()` on your package for ideas of where to start.
- [ ] There are a 12 `TODO` comments in code. Are these issues that still need to be addressed or are these outdated?
- [ ] Use `\url{}` in roxygen/`.Rd` markup to get clickable links in the docs.
- [ ] I was initially a bit concerned by the potential need for a non-standard installation of **V8**. However, reading the links it sounds like its largely solved these-days? I'd consider de-emphasising this material, or noting that many (most?) users of **scMet** will not even need to worry about it.
- [ ] Consider using R's native pipe operator, `|>`, instead of depending on **magrittr** for its `%>%` pipe operator.
- [ ] Please run a spellcheck over the documentation and vignette.
- [ ] Some of the **data.table** code would benefit from exposition, e.g. the following code from the vignette is pretty dense:

```r
bbmle_fit <- scmet_dt$Y[, bb_mle(cbind(total_reads, met_reads))
                      [c("mu", "gamma")], by = c("Feature")]
```

- [ ] Please clarify this comment in the vignette: "As we can see, scMET can more accurately estimate the overdispersion parameter γ by shrinking the MLE estimates towards to population average, resulting in more robust estimates." That's not clear to me from the figure (perhaps I'm misunderstanding of figure). E.g, there seem to be a good number of `BB MLE` points are closer to the diagonal than the `scMET` points.
- [ ] Please correct language in vignette: "This will create a new slot named hvf within the fit_obj object."
  - S3 classes don't have 'slots' (this is an S4-specific term, I believe; see https://adv-r.hadley.nz/s4.html). 
- [ ] Output of running `scmet_differential()` refers to 'features' in some places and 'genes' in others. Please clarify.
- [ ] An application to real (rather than simulated) data would be a great addition to the vignette.
- [ ] Please add a `BugReports` field to the `DESCRIPTION` (this is usually the issues page for the GitHub repo: https://github.com/andreaskapou/scMET/issues)
- [ ] Please consider more selective imports using `importFrom` instead of *import all* with `import` in the `NAMESPACE` (probably most relevant for **VGAM** and perhaps **rstantools**; not advised for **methods**).
- [ ] Consider updating `inst/CITATION` to refer to the Genome Biology publication.
- [ ] The vignette should have an *Introduction* section (essentially the current *Background* section)
- [ ] I don't believe the `.datatable.aware` in `R/scMET-package` is necessary
  - Based on my reading of https://cran.r-project.org/web/packages/data.table/vignettes/datatable-importing.html, this isn't necessary because **scMET** lists **data.table** under `Imports` rather than `Suggests`.
  - In its current form, you end up with a strange `.datatable.aware` printed under 'Usage' when a user does `help("scMET-package")`.
- [ ] When running `R CMD check` on **scMET** I get a note saying:

```
  * checking for GNU extensions in Makefiles ... NOTE
    GNU make is a SystemRequirements.
```

I don't understand this, because `GNU make` is already listed in `SystemRequirements`, but it seems like it might be another **rstan**-related thing (https://discourse.mc-stan.org/t/using-rstan-in-an-r-package-generates-r-cmd-check-notes/26628/3), so I think we can ignore it.

**Comment by andreaskapou** [comment] 2022-04-28 23:13
Hi @PeteHaitch 

Thanks for reviewing scMET and the detailed suggestions on making the package better. I agree that using S4 classes and making scMET accept SE derived objects would be optimal. However, in the current circumstances (my current post has shifted from DNA methylation) I do not have the time to refactor the whole package, but would leave it as future work?

Please see my line-by-line answers to your comments. Boxes with ticks are implemented as per your suggestions

## Required 
- [x] Re-design of converters between the scmet format and SingleCellExperiment class.
  -  Thanks for the suggestions. All implemented now.
- [x] Do not use direct slot access with `@`.
- [x] S3 objects: The S3 objects were mostly created to have a certain __structure__ in the generated outputs and was not intended to be 'true' objects, with getter and setter methods.
  - Simplified the code to not require if-else statements for class, hence not requiring S3 generics anymore.
  - Updated to `inherits` rather than `is`
- [x] Don't call `set.seed()` within a function. Instead, document to the user that they will need to `set.seed()` prior to calling the relevant function in order to get reproducible results.
- [x] How many `iter` are required when running `scmet()`
  - This is a tricky one and really depends on the dataset. The STAN implementation of VB relies on `black-box variational inference` and potentially with relatively _small_ sample sizes sometimes tends to 'search' around the local/global minima. We've seen that with larger sample sizes (e.g. working with real data), it tends to converge much faster, e.g. around 5k iterations.
- [x] Not clear why the outer plot() is required. Removed outer plot.
- [x] From the vignette: "Many thanks to John Riddell for the conversion functions.". John should be acknowledged as an author in the DESCRIPTION
- [x] Please remove the LICENSE file (it is not required when using a 'standard' license like GPL-3).
- [x] inst/stan/include/license.stan seems redundant with the top-level license (i.e. License field in the DESCRIPTION).
- [x] Please make an effort to address all `WARNINGS` and `NOTES`.
  - [] NOTE: 'LazyData:' in the 'DESCRIPTION' should be set to false or removed
      -  Added this since I am exporting data (e.g. `scmet_dt`) and make them readily available when calling `library(scMET)`. 
      - Fixed most other NOTES, except the printing messages where I am using `cat` outside show methods.
- [x] Please upate the installation instructions in the README and vignette to the official Bioconductor installation instructions (can be delayed until after acceptance).


## Recommended
- [x] It is strongly recommended that you add additional unit tests. Try running covr::report() on your package for ideas of where to start.
  - Additional tests will be added in the near future, as per your suggestion.
- [x] There are a 12 TODO comments in code. Are these issues that still need to be addressed or are these outdated? They are outdated.
- [x]  Use \url{} in roxygen/.Rd markup to get clickable links in the docs.
- [x] I was initially a bit concerned by the potential need for a non-standard installation of V8. However, reading the links it sounds like its largely solved these-days? I'd consider de-emphasising this material, or noting that many (most?) users of scMet will not even need to worry about it. --> added comment in README.
- [x] Consider using R's native pipe operator, |>, instead of depending on magrittr for its %>% pipe operator. 
- [x] Please run a spellcheck over the documentation and vignette. 
- [x] Some of the data.table code would benefit from exposition
- [x] Please clarify this comment in the vignette: "As we can see, scMET can more accurately estimate the overdispersion parameter γ by shrinking the MLE estimates towards to population average, resulting in more robust estimates." That's not clear to me from the figure (perhaps I'm misunderstanding of figure). E.g, there seem to be a good number of BB MLE points are closer to the diagonal than the scMET points.
  - I agree that for some points MLE might be closer to the diagonal, but overall scMET results in better/ more accurate performance. Actual metrics are shown in the manuscript. One reason you might be seeing relatively large number of MLE points closer compared to scMET is that for efficiency we run scMET with small number of `iter`, hence the model not converging.
- [x] Please correct language in vignette: "This will create a new slot named hvf within the fit_obj object."
- [x] Output of running scmet_differential() refers to 'features' in some places and 'genes' in others. Please clarify.
- [ ] An application to real (rather than simulated) data would be a great addition to the vignette.
  - I agree and this will be added in the near future. A current issue we have is that scMET is relatively slow, hence building the vignette with real data would be prohibitive.
- [x] Please add a BugReports field to the DESCRIPTION
- [x] Please consider more selective imports using importFrom instead of import all with import in the NAMESPACE
- [x] Consider updating inst/CITATION to refer to the Genome Biology publication.
- [x] The vignette should have an Introduction section (essentially the current Background section) 
- [x] I don't believe the .datatable.aware in R/scMET-package is necessary 

Best,
Andreas

**Comment by PeteHaitch** [comment] 2022-04-29 02:51
Thanks, Andreas.
I've got grant deadlines this week but I will take a look next week.

Cheers,
Pete

**Comment by PeteHaitch** [comment] 2022-04-29 02:51
And once it's passing OK on BioC's build machines, please take a look at why it's now timing out there

**Comment by andreaskapou** [comment] 2022-04-29 07:19
Hey Pete, 

No worries at all and good luck with the grant application!

I increased the `iter` so I get a better fit in the vignette examples, which results in timing out. Will revert to old settings and submit again.

Best,
CAK

**Comment by PeteHaitch** [comment] 2022-05-24 03:34
Thanks for your response to the review, @andreaskapou.
The use of S3 is still non-standard, but since it doesn't seem to affect the package functionality and given your current circumstances feel free to leave as-is.
A couple of final points to address, then we'll be ready to accept **scMET**.
FYI I will be on leave until June 9, so there may be a delay in the package being formally accepted once you've made these changes.

### Required

- [ ] In `scmet_to_sce()` you create the sparse assays using e.g., `total <- Matrix::Matrix(as.matrix(tot_Y), sparse = TRUE)`. This is going to be very inefficient because it first creates a dense matrix (`as.matrix()`) and then coerces that to a sparse matrix. Since you can figure out the row and column indices of the non-zero elements in the input (e.g., `tot_Y`), should be able to create the sparse matrix directly (and much more efficiently) through the `sparseMatrix()` constructor.
- [ ] My apologies, I gave slightly incorrect advice in my initial review of, "When constructing the _SummarizedExperiment_-derived representation of the data, I would strongly consider storing the covariates `X` as metadata on the features (CpGs), i.e. as `metadata(rowData(sce))` rather than `metadata(sce)`."
  - In brief, use `mcols(rowData(sce))` rather than `metadata(rowData(sce))`. You could then access, for example, the CpG density of the first 10 CpGs as `rowData(sce)$cpg_density[1:10]`.
  - In more detail, the `metadata()` accessor is intended for the _global_ metadata of an object as a whole whereas the `mcols()` accessor is intended for the _element-wise_ metadata of the individual elements of the object (see `help("Vector-class", "S4Vectors")`).
- [ ] Use `message()` rather than `cat()` when providing informational messages; see https://contributions.bioconductor.org/r-code.html#end-user-messages (flagged by `BiocCheck::BiocCheck("scMET_0.99.10.tar.gz")`; the other NOTEs flagged by it have been explained or, based on my reading, can be treated as recommendations rather than requirements for **scMET**).

### Recommended

- [ ] Suggest documenting your advice on `iter` in `scmet()`, i.e. words to the affect of what you wrote in response to my question: "This is a tricky one and really depends on the dataset. The STAN implementation of VB relies on black-box variational inference and potentially with relatively small sample sizes sometimes tends to 'search' around the local/global minima. We've seen that with larger sample sizes (e.g. working with real data), it tends to converge much faster, e.g. around 5k iterations.". Users will assume the default value is fine.

**Comment by andreaskapou** [comment] 2022-05-30 11:59
Hi @PeteHaitch , please see my line-by-line answers to your comments. Boxes with ticks are implemented as per your suggestions.

- [x] Create the sparse matrix directly (and much more efficiently) through the `sparseMatrix()` constructor.
  -  Thanks for this suggestions. Functions are updated accordingly.
- [x] Use `message()` rather than `cat()` when providing informational messages: Done
- [x] Suggest documenting your advice on `iter` in `scmet()`: Done
- [ ] Use `mcols(rowData(sce))` rather than `metadata(rowData(sce))`. You could then access, for example, the CpG density of the first 10 CpGs as `rowData(sce)$cpg_density[1:10]`. 
  - Thanks for this suggestion, however I believe the current implementation might be better suited for storing covariates `X`. This is because X can have different number of columns and or names, depending on the analysis of the user. Hence it will be less error prone to consider `X` as an independent 'object', rather than deciding which columns to extract from `mcols(rowData(sce))`, and then regenerate the covariate matrix `X`. So I would be inclined to keep things as they are in terms of `X`, if that is OK with you?

Best,
Andreas

**Comment by PeteHaitch** [comment] 2022-07-08 00:33
Thank you for making those changes, @andreaskapou.
I've now accepted the package into Bioconductor.

(Apologies, I thought I had already done this a few weeks ago!)

**Comment by PeteHaitch** [comment] 2022-07-14 05:24
@lshep or @Bioconductor/core: should my changing the tag to '3a. accepted' have automatically triggered the next steps ('The master branch of your GitHub repository has been added to Bioconductor's git repository.' etc.)?

**Comment by nturaga** [comment] 2022-07-14 11:37
Hi Pete

Lori has to do a manual package ingestion for all the packages that have
been accepted. I believe this happens once per week.

It should happen soon.

**Comment by lshep** [comment] 2022-07-18 11:42
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/andreaskapou.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("scMET")`. The package 'landing page' will be created at

https://bioconductor.org/packages/scMET

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-07-18 11:42 UTC
Labels: OK, 3a. accepted
