### ISSUE TITLE
igvR

### ISSUE THREAD

**Issue by paul-shannon** [Bioconductor/Contributions#723] opened 2018-04-13 18:13 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/paul-shannon/igvR

Confirm the following by editing each check box to '[x]'

- [x ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by dvantwisk** [comment] 2018-04-13 18:28
Hello,

I am taking over this package review for Herve.  I will review it promptly once the builds read `OK`.

**Comment by paul-shannon** [comment] 2018-04-13 18:35
Hi Daniel,
Thanks for offering to review my package.
May I offer a little history?   I submitted IGV on April 1st, naively thinking that the old support for web browsers in the build system - which Dan Tenenbaum created and maintained when we were both on the core team - was still in place.   My questions about that to bioc-devel went unanswered for days.  Quite frustrating.    Vince Carey eventually helped out, for which I was grateful.

The package has built clean for several days now.   I just changed the name from IGV to igvR,  created this new issue, added the webhook, and now I get an endless stream of "ABNORMAL build" messages.

I am pretty sure I need your help with this.  It may be my stupid error.  It might even be the build system.  The infinite "ABNORMAL build" loop doesn't seem like it is entirely my fault :}  

If you wait till a green build occurs before trying to help I predict we will never get there!

 - Paul

**Comment by dvantwisk** [comment] 2018-04-13 18:37
I see.  This is bizarre behavior by our build machines.  We will look into it.

**Comment by paul-shannon** [comment] 2018-04-13 18:37
Cool.  Thanks!

**Comment by dvantwisk** [comment] 2018-04-13 18:51
@paul-shannon A reason for this issue may be that you have multiple web-hooks on this issue.  Can you check if you do, and if so, correct this?

**Comment by paul-shannon** [comment] 2018-04-13 18:56
@dvantwisk  Just one now.  My mistake.

**Comment by dvantwisk** [comment] 2018-04-15 03:12
Here's a review for your package.  Please address the following issues and message me back when your are done.  I may have some more thing to say about the file `R/igvR.R` but I'd like to check in on a few things before then.  You are on track for having your package included in the 3.7 release.

.gitignore
- [REQUIRED] add `IGV.Rproj`, `igvR.Rprog`, `build.makefile`, and
`NAMESPACE.oldManuallyCreated` to `.gitignore`.

R/GENERAL
- [CONSIDER] Be specific with what classes are being input and output. For
example, `AnnotationTrack.R`:L15 it seems that the `soureType @param` is asking
for a `character` argument git there are packages like `rtracklayer` that have
specific classes for files. In general, it is advisable to be as specific as
possible regarding input and output for the user.

R/AnnotationTrack.R
- [CONSIDER] L58: Use `match.arg()` to improve style of function declaration.
For example, the parameter `displayMode` can have three values `"COLLAPSED"`,
`"EXPANDED"`, and `"SQUISHED"`. The parameter in the function declaration can be
written as `displayMode=c("SQUISHED", "COLLAPSED", "EXPANDED")`. The value that
the user uses can be obtained with `displayMode <- match.arg(displayMode)`. The
first value (in this case `"SQUISHED"`) is the default argument. Using this
method makes it clear to users what the allowed inputs to a function are and may
also make error catching easier. There are many places in this package that you
could use this.

R/Track.R
- [REQUIRED] this package is trying to set the `getInfo` and get `getSize`.
These names seem rather "general" and it isn't ideal for the structure of the
Bioconductor project to have them implemented here.  I ask that you either:
  - Change the name to be more specific like `trackinfo` and `tracksize`.
  - Find existing Generics in a high level package and `setMethod` for a
    signature consisting of the `Track` class.

R/utils.R
- [REQUIRED] it seems that `printf()` is only being used to display messages
to the user, correct? If so, then replace `print()` in the function with
`message()`, as `message()`'s purpose is to display diagnostic messages and
can be toggled by the user; this isn't the case with `print()`. Also, I don't
see the need to export this small utility function (developers or users probably
aren't coming to the package to use `printf()`), so please remove the `@export`
tag.

**Comment by paul-shannon** [comment] 2018-04-15 16:17
@dvantwisk 
Thank you for your suggestions - they all make sense, all are now implemented but for one, which I think I can explain to your satisfaction:

``` 
[CONSIDER] Be specific with what classes are being input and output. For
example, AnnotationTrack.R:L15 it seems that the @param soureType is asking
for a character argument git there are packages like rtracklayer that have
specific classes for files. In general, it is advisable to be as specific as
possible regarding input and output for the user.
```
The ```sourceType``` parameter to the AnnotationTrack constructor includes these three possibilities from the igv.js ontology (I only support the first one for now):
  - file
 - gcs (Google Cloud Storage)
 - ga4gh  (the Global Alliance API)

I think that Michael's variety of specific file types in rtracklayer do not actually apply here.  The three options listed above are perhaps better understood as protocols with which to obtain data, and a generic file type is, I believe, the proper abstraction.

**Comment by paul-shannon** [comment] 2018-04-15 20:09
@dvantwisk 
The builds fail in a way I find puzzling.   Is this my error?
[build report](http://bioconductor.org/spb_reports/igvR_buildreport_20180415153425.html)

The only diagnostic I could find:

```
accessing git_info failed. Finished Git clone.
Installing dependency status: 0. Package type: Software. 
Installing package status: 0. Build Package status: -9.
```

**Comment by dvantwisk** [comment] 2018-04-15 22:45
I'll look into it.

**Comment by dvantwisk** [comment] 2018-04-16 13:45
Could you make another push with a version bump to see if the issue is cleared up?

**Comment by dvantwisk** [comment] 2018-04-16 14:33
There could be various reasons why the package is failing.  First off, its interesting the report we got on Friday and the current report are essentially the same:
http://bioconductor.org/spb_reports/igvR_buildreport_20180413144215.html
 http://bioconductor.org/spb_reports/igvR_buildreport_20180416101537.html

Just to be sure, are the web-hooks set correctly now?

Secondly, it seems that the timeout is occurring on the vignette.  The vignette opens a browser window and this could take various amounts of time of different machines.  Is it possible to toggle off to browser window?  If not, maybe we could set a few `eval=False`'s in the vignette just to check where the issue is.  (These `eval=FALSE`'s cannot stay, but they could be useful for isolating the issue)

**Comment by paul-shannon** [comment] 2018-04-16 15:02
Hi Daniel,

The vignette uses eval=FALSE throughout.   That change, and the if(interactive()) shield on all man page and examples, and in inst/unitTests/test_igvR.R, were made last week to avoid -any- need for a web browser in the build system.

However…

Somehow, despite a global eval=FALSE, one code chunk still got executed - though why this happens now, I do not know.   That code chunk (“createLoad”) is now explicitly eval=FALSE.  I just ran devtools::document, devtools:build_vignettes, build, install, check, BiocCheck, and no web browser is summoned.  

I have made no changes to the webhoook since deleting the duplicate one yesterday.   I just looked and, indeed, there is just one.

Maybe this will do it?

Thanks for your patience!

 - Paul

**Comment by paul-shannon** [comment] 2018-04-16 15:06
@dvantwisk 

Regarding web browsers in the build system, Martin said the other day:

   The build system will not be modified to support a browser, so the 
   if (interactive()) is unfortunately as good as it will get.

Implying that vignettes, eval=FALSE is appropriate here too.   I modified the vignette to

  - display the code chunks
  - display a screenshot of what one would see in the browser if one were available

 - Paul

**Comment by dvantwisk** [comment] 2018-04-16 16:49
A few things:

- It's good to see we've isolated the problem.  We don't generally allow `eval=False`'s inside of the vignettes because it is important for the builder to verify that the user facing examples are functioning properly.  But for this particular instance with opening a browser window, we may let it through.  I suppose I ask that you isolate the `eval=FALSE` only to the point where the browser window is opened and to let as much of the code in the vignette run as possible (i.e. you should get rid of the global `eval=FALSE` and only use it once in the browser-opening code chunk.)

**Comment by paul-shannon** [comment] 2018-04-16 17:25
All of the chunks in igvR.Rmd, to a first approximation, contact the browser, so nothing is left if I were to do as you suggest!
  
The exceptions are:  2 chunks to initialize knitr, and one chunk to load libraries (igvR, VariantAnnotation, AnnotationHub).  The other 8 chunks each call methods which send messages to the browser.  This reflects the very nature of the package: its only purpose is to connect to javascript in a local web browser.

Once upon a time we (Bioconductor/Seattle) supported, through Dan Tenenbaum’s efforts, a “cytoscape farm”,  and web browsers running on the build system.   Most of my packages (the deprecated RCytoscape, the original RCy3, BrowserViz, RCyjs, now igvR) benefited from that.  Maybe they even provided the motivation for Dan to build that capability.  But these extensions to the build system were a lot of fuss, and Martin’s decision to let them lapse makes a lot of sense.

You will see that the all of fundamental operations of the existing packages BrowerViz, RCyjs (now 2.0.x, to be merged into devel this week) and RCy3 (also in a new version, with new maintainers) - all of these run without tests, without live manpage examples, and without operational vignettes.  We disabled all of those desirable features with the aforementioned lapse of browser & farm support.

We are full true believers in the importance of daily, exhaustive, all-architecture tests.   It’s just that for good reason we cannot run them on the build system.   I am setting up tests on my own machines here at the Insititute for Systems Biology.  I will encourage RCy3 maintainers to do the same.  

The only real tests that survive in igvR are inst/unitTests/test_Tracks.R.   These tests run strictly in R, so they have not been disabled.

Can you see any other approach to this?

 - Paul

**Comment by dvantwisk** [comment] 2018-04-16 18:46
Okay, thank you for explaining this.  The best solution that I can allow is to remove all existing `eval=FALSE`'s in the vignette and in the `knitr::opt_chunk$set` code chunk at L19-27, replace that `eval=FALSE` with `eval=interactive()`.  This will not run the vignettes on build but will allow them to be run interactively.  After that we should be able to accept the package.

**Comment by paul-shannon** [comment] 2018-04-16 20:07
Elegant solution, thanks! 

Looks like 0.99.29 built clean.

**Comment by dvantwisk** [comment] 2018-04-16 20:11
Great!  I'll move to accept the package now.

**Comment by paul-shannon** [comment] 2018-04-17 17:41
@dvantwisk  May I continue to make small changes for a few more days, and have those show up in the release version?   igv.js is within a couple of days of releasing a formal version 2.0 of their library; I'd really like to put that into my build.

**Comment by dvantwisk** [comment] 2018-04-17 19:25
You can make changes in your github repository for the time being.  Once @mtmorgan chimes in and adds your package to the Bioconductor git server, you should be able to push changes there and have it built nightly on our devel builders.  These modifications will appear in the 3.7 Bioconductor release, although I must stress that your package should be building with no errors or warnings by April 25th.  The 3.7 release branch will be created on April 26th.

**Comment by paul-shannon** [comment] 2018-04-17 19:27
Got it, Daniel, thanks.  I’ll be sure to have clean builds well in advance of  4/25.

**Comment by mtmorgan** [comment] 2018-04-18 21:56
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/paul-shannon.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"igvR\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/igvR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Closed by mtmorgan** 2018-04-18 21:56 UTC
Labels: 3a. accepted, OK

**Comment by nturaga** [comment] 2018-04-18 22:33
Please use the following link to [Submit your SSH key to Bioconductor](https://git.bioconductor.org/BiocCredentials/). The link listed in the previous message is deprecated.

**Comment by paul-shannon** [comment] 2018-04-25 15:50
@dvantwisk  @mtmorgan The RStudio folks just made substantial changes (not backwards compatible) to httpuv, upon which BrowserViz, igvR and RCyjs all depend.  I have been scrambling to adapt, having received good support from RStudio.   Some more code changes and lots of testing remain - I hope to have fixes for all three packages in by the end of the day.

**Comment by mtmorgan** [comment] 2018-04-25 20:17
Thanks Paul for being conscientious about this; remember to update the git.bioconductor.org repo.

**Comment by paul-shannon** [comment] 2018-04-25 20:54
Sure thing, Martin.    Other than double checking my command, how can I check to make sure my commits truly get to bioc?   git push origin|upstream ought to do it, but there’s nothing quite so reassuring as seeing changed version numbers on a web page.  Got any tips?

 - Paul

**Comment by mtmorgan** [comment] 2018-04-25 23:55
There's an [rss feed][1] but in practice it has a disconcerting lag; I'd maintain an independent clone that you can pull to.

[1]: http://bioconductor.org/developers/gitlog/
