### ISSUE TITLE
HicAggR

### ISSUE THREAD

**Issue by CuvierLab** [Bioconductor/Contributions#2869] opened 2022-12-09 17:36 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/CuvierLab/HicAggR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2023-01-31 16:26
We apologize for the delay.  I will look over the package in the next week and provide feedback

**Comment by lshep** [comment] 2023-02-14 14:42
I'm having trouble building the package locally 

```
lorikern@jbcj433:~/PkgReviews$ R CMD build HicAggR 
* checking for file 'HicAggR/DESCRIPTION' ... OK
* preparing 'HicAggR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘HicAggR.Rmd’ using rmarkdown
sh: 1: curl: not found
Quitting from lines 69-76 (HicAggR.Rmd) 
Error: processing vignette 'HicAggR.Rmd' failed with diagnostics:
'curl' call had nonzero exit status
--- failed re-building ‘HicAggR.Rmd’

--- re-building ‘InDepth.Rmd’ using rmarkdown
sh: 1: curl: not found
Quitting from lines 80-83 (InDepth.Rmd) 
Error: processing vignette 'InDepth.Rmd' failed with diagnostics:
'curl' call had nonzero exit status
--- failed re-building ‘InDepth.Rmd’

SUMMARY: processing the following files failed:
  ‘HicAggR.Rmd’ ‘InDepth.Rmd’

Error: Vignette re-building failed.
Execution halted

```

I was also wondering the size and nature of the files being downloaded.  Is there a reason a smaller example set of these types of files could not be included with the package to show functionality of the package?

**Comment by lshep** [comment] 2023-03-08 16:16
This is still occurring and there has been no response. Closing this issue for inactivity. If you would like to continue on development and inclusion into Bioconductor please request the issue be reopened.

**Comment by RobTesf** [comment] 2024-03-26 16:25
Hello,
We've addressed the issues on the build you've reported and we've performed some more modifications.
We've checked with `R CMD` and `BiocCheck`, so can you please reopen this issue.
Thanks

**Comment by lshep** [comment] 2024-03-26 16:32
Please push changes to git.bioconductor.org to trigger a new build

**Comment by RobTesf** [comment] 2024-03-26 17:44
I'm having trouble to connect to git.bioconductor.org:packages/HicAggR with a Permission denied (publickey) error.
I've added my ssh key to my github account and I can push to CuvierLab/HicAggR, but not the bioc repo.

**Comment by lshep** [comment] 2024-03-26 17:57
The key should be added to the BiocCredentials account.  Currently the only account that has push permissions is olivier.cuvier@univ-tlse3.fr that is now associated with CuvierLab as the original submitter and listed maintainer.  Only keys at CuvierLab are automatically added for access.  If you should also have permissions it might be beneficial to have a different BiocCredentials account but could we please have Oliver Cuvier confirm this.

**Comment by RobTesf** [comment] 2024-03-26 18:06
Can he confirm that through mail (using that address mail) or does he have to do it through a github account?

**Comment by lshep** [comment] 2024-03-26 18:08
He can leave a message here on the issue or he can reach out via email which ever is easier

**Comment by RobTesf** [comment] 2024-03-26 18:15
Ok thanks. I believe this is the mail address bioc-devel@r-project.org that he can address it to, am I right?

**Comment by lshep** [comment] 2024-03-26 18:16
yes that will be fine.  thank you

**Comment by lshep** [comment] 2024-03-28 11:23
I've sent you an email with information on how to activate your BiocCredentials account

**Comment by RobTesf** [comment] 2024-03-28 16:10
@lshep I'm having an ERROR report with `Subscribe to the Bioc-devel mailing list`, I don't understand this because I'm already subscribed to the bioc-devel list...

**Comment by lshep** [comment] 2024-03-28 16:12
It is the listed maintainers email that must be registered to the bioc-devel mailing list 
```
    person("Olivier", "Cuvier", email = "olivier.cuvier@univ-tlse3.fr", role = c("cre","ctb"))
```
That email is not registered

**Comment by RobTesf** [comment] 2024-03-28 16:42
Correct! thanks

**Comment by lshep** [comment] 2024-04-16 13:28
I apologize for the delay.  Please see comments below:

**vignette**

- [ ] (Optional)  It seems like HicAggR and InDepth are relatively the same but
  InDepth gives more descriptions. Is it worth having the two or should HicAggR
  be removed and InDepth be reanmed HicAggR as the main vignette? This would
  also cut down on run time since then only 1 vignette is compiled/executed.

- [ ] Could you please provide an abstract/intro section in your vignette that
  provides motivation for inclusion in Bioconductor and when appropriate a
  review and comparison to existing Bioconductor packages with similar
  functionality or scope.

- [ ] Update installation instructions with Bioconductor.

- [ ] It might be worth using a
  [BiocFileCache](https://bioconductor.org/packages/release/bioc/html/BiocFileCache.html)
  when downloading test data to ensure against spotting internet
  connection. That way if the test file has already been downloaded it can still
  run. Using the default cache would be fine rather than creating a custom in
  this case.

**tests**

- [ ] I see you run all your functions which is good, but is it actually testing
  against anything for correct values?  It seems like all the functions are just
  run with no actual validation being done.


**R functions**

- [ ]  Function arguments should have validity checking to ensure values going
  in are expected.  Things like listing acceptable values and using  match.args
  or checking for right class type is given.  


Please push changes with a valid version bump and comment back here with what has been addressed above.

**Comment by RobTesf** [comment] 2024-04-26 13:04
@lshep I made the necessary modifications as suggested and I made an R cmd check and my build is failing on windows due to failure to build one of my dependencies (rtracklayer 1.63.2). It built fine with version 1.62.0 on my previous checks. So I was thinking setting the dependency to rtracklayer to version 1.62.0 rather than the latest. This would require resetting the dependency once the issue is resolved at rtracklayer. What do you recommend?

**Comment by lshep** [comment] 2024-04-26 13:08
I would recommend ignoring the failure on windows right now; if its failing from rtracklayer it should eventually clear up.  Please push your changes to git.bioconductor.org with a valid version bump to trigger the new build report

**Comment by RobTesf** [comment] 2024-04-26 13:41
@lshep I used BiocFileCache to do caching in the vignettes and I keep getting this error:
`unable to find an inherited method for function 'bfcpath' for signature 'x = "character"'`
Here is how I tried to use the caching in the vignette.
```
withr::local_options(list(timeout = 3600))
cache.dir <- paste0(tools::R_user_dir("", which="cache"),".HicAggR_HIC_DATA")
bfc <- BiocFileCache::BiocFileCache(cache.dir, ask = FALSE)

Hic.url <- paste0("https://4dn-open-data-public.s3.amazonaws.com/",
"fourfront-webprod/wfoutput/7386f953-8da9-47b0-acb2-931cba810544/",
"4DNFIOTPSS3L.hic")
if(length(BiocFileCache::bfcinfo(bfc)$rname)==0 || 
!"Control_HIC.hic"%in%BiocFileCache::bfcinfo(bfc)$rname){
    if(.Platform$OS.type == "windows"){
        bfc <- BiocFileCache::bfcadd(
            x = bfc,rname = "Control_HIC.hic",
            fpath = Hic.url,
            download = TRUE,
            config = list(method="auto",mode="wb"))
    }else{
        bfc <- BiocFileCache::bfcadd(
            x = bfc,rname = "Control_HIC.hic",
            fpath = Hic.url,
            download = TRUE,
            config = list(method="auto"))
    }
}
HicOutput.pth <- as.character(BiocFileCache::bfcpath(bfc)[
    which(BiocFileCache::bfcinfo(bfc)$rname=="Control_HIC.hic")])
```
I first added BiocFileCache in the description file as Suggested package, then I set the version to the one working fine on my PC (>= 2.6.1) then moved to Imports. But the build fails on github and on bioconductor git R cmd check but works fine on my PC.
Am I not using the caching correctly...

**Comment by lshep** [comment] 2024-04-26 14:04
You overwrote the cache object when you added the resource with bfcadd;  so the first time this runs it fails with the overwrite and then subsequently will pass because the resource is already added. Within your if assign the results to a differently named variable.

**Comment by RobTesf** [comment] 2024-04-26 15:46
@lshep thank for the support. So in this new version I've addressed all your points:

**vignette**

> 
> - [x]  (Optional) It seems like HicAggR and InDepth are relatively the same but
> InDepth gives more descriptions. Is it worth having the two or should HicAggR
> be removed and InDepth be reanmed HicAggR as the main vignette? This would
> also cut down on run time since then only 1 vignette is compiled/executed.

I have removed the Quick start vignette and kept the more detailed one with
less hic resolution, to reduce runtime
> - [x]  Could you please provide an abstract/intro section in your vignette that
> provides motivation for inclusion in Bioconductor and when appropriate a
> review and comparison to existing Bioconductor packages with similar
> functionality or scope.

I've added an introduction to the vignette

> - [x]  Update installation instructions with Bioconductor.

I've added this to the vignette, plus added bioconductor url to the description file
> - [x]  It might be worth using a
> [BiocFileCache](https://bioconductor.org/packages/release/bioc/html/BiocFileCache.html)
> when downloading test data to ensure against spotting internet
> connection. That way if the test file has already been downloaded it can still
> run. Using the default cache would be fine rather than creating a custom in
> this case.

Downloaded files will be cached using BiocFileCache
> **tests**
> 
> - [x]  I see you run all your functions which is good, but is it actually testing
> against anything for correct values?  It seems like all the functions are just
> run with no actual validation being done.

Tests are done now using testthat package...
> 
> **R functions**
> 
> - [x]   Function arguments should have validity checking to ensure values going
>  in are expected.  Things like listing acceptable values and using  match.args
> or checking for right class type is given.

Arguments checks are now performed
> 
> Please push changes with a valid version bump and comment back here with what has been addressed above.

**Comment by lshep** [comment] 2024-04-26 16:16
The default branch of your GitHub repository has been added to Bioconductor's
git repository as branch devel.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/CuvierLab.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("HicAggR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/HicAggR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2024-04-26 16:16 UTC
Labels: OK, 3a. accepted
