### ISSUE TITLE
xcore

### ISSUE THREAD

**Issue by mcjmigdal** [Bioconductor/Contributions#2496] opened 2022-01-14 13:47 UTC
- Repository: https://github.com/bkaczkowski/xcore

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-01-18 12:22
```
* creating vignettes ... ERROR
--- re-building ‘xcore_vignette.Rmd’ using rmarkdown
Quitting from lines 30-31 (xcore_vignette.Rmd) 
Error: processing vignette 'xcore_vignette.Rmd' failed with diagnostics:
object 'rinderpest_mini' not found
```

You have rinderpest_mini.R in a data-raw folder.  Please verify that your package can pass R CMD check, recommit to your github repo, and comment here for me to reevaluate.

**Comment by mcjmigdal** [comment] 2022-01-20 12:30
AdditionalPackage: https://github.com/mcjmigdal/xcoredata

**Comment by mcjmigdal** [comment] 2022-01-20 12:53
@vjcitn I've fixed the `'rinderpest_mini'` issue, however I want to supplement `xcore` with an `xcoredata` data package. For development I was using github LFS, but now I am trying to move to Bioconductor's ExperimentHub. I've tried to reach out to hubs@bioconductor.org, but they did not respond to me since last week. Unfortunately, further down the vignette I am using one of the files from `xcoredata` which effectively means vignette build will ERROR. I will continue my efforts to move to Bioconductor's ExperimentHub. I will let you know once this is done, sorry for the confusion.

**Comment by lshep** [comment] 2022-01-20 12:56
I'm sorry the email did not get through from hubs@bioconductor.org --- can you please email me directly and I can assist with the ExperimentHub  lori.shepherd@roswellpark.org

**Comment by mcjmigdal** [comment] 2022-01-25 14:25
@vjcitn hi I am back. Both xcore and additional package xcoredata are passing R's check and BiocCheck on my local enviroment. I am looking forward to see how it goes on your servers. Please kindly reevaluate my submission.
Cheers MM

**Comment by mcjmigdal** [comment] 2022-02-03 14:55
Hi @vjcitn What's the status? Cheers mm

**Comment by vjcitn** [comment] 2022-02-08 12:21
devtools::load_all() should not be at the top of the vignette.  it makes it hard for me to do the preliminary evaluation.  please take it out.

**Comment by mcjmigdal** [comment] 2022-02-08 13:43
@vjcitn should be fixed, let me know if I should bump package version

**Comment by lshep** [comment] 2022-02-08 14:12
bare with us for a few minutes.  Since you submitted the software first in order to assign the reviewer I have to process that package first.  The build for that will initially fail because the data package is missing but once the issue is active I can process the data package next -- and then rerun the software once manually for you -- after that both packages will be linked to this issue and you can rebuild either by doing the valid version bump from there -- I hope this makes sense.

**Comment by lshep** [comment] 2022-02-08 15:00
I'm rerunning the software package now with the data package available.  You should be able to make changes to both packages and get new builds with version bumps committed to git.bioconductor.org.

**Comment by mcjmigdal** [comment] 2022-02-08 15:33
@lshep thank you!

**Comment by lshep** [comment] 2022-02-11 14:52
Please correct any TIMEOUT/ERROR/Warning/Notes from build reports before a more in-depth review will continue.  Thank you

**Comment by vjcitn** [comment] 2022-02-22 12:50
MacOS:
```
  > test_check("xcore")
  model.frame(formula = mpg ~ ., data = mtcars)
  [ FAIL 2 | WARN 0 | SKIP 0 | PASS 61 ]
  
   Failed tests 
   Failure (test_processing.R:107:3): addSignatures 
  digest::digest(mae) (`actual`) not equal to "b1493e0edf55d3347b328d6928ab15fb" (`expected`).
  
  `actual`:   "1d7c13819efc13aeab88f34d06dfc5a3"
  `expected`: "b1493e0edf55d3347b328d6928ab15fb"
   Failure (test_stats.R:269:3): modelGeneExpression 
  digest::digest(res) (`actual`) not equal to "d650ad7e3f963bbf4d9e29b4457aa392" (`expected`).
  
  `actual`:   "98d93ead7e362572773d4a6ed7dae6cf"
  `expected`: "d650ad7e3f963bbf4d9e29b4457aa392"
  
  [ FAIL 2 | WARN 0 | SKIP 0 | PASS 61 ]
  Error: Test failures
  Execution halted
```
Do you know why this is happening?

**Comment by vjcitn** [comment] 2022-02-22 13:06
You won't find doMC on windows so you can't use it there.  Please have a look at BiocParallel.  You will be asked to use it unless there are overwhelming counterindications.  On windows a snow-based parallelism is supported.

**Comment by mcjmigdal** [comment] 2022-02-22 13:44
@vjcitn thank you for the comments, I will try to switch to BiocParallel. As for the other issue I am using digest hashes in my automatic test, in such a way that it tells only if outputs of the relevant function are valid. This approach however already showed short for me as these hashes seems to depend on R version and now apparently on the system as well. I will think of some other way to implement those tests.

**Comment by vjcitn** [comment] 2022-02-22 14:15
I like the increased rigor of the testing.  You should raise the issue on slack or bioc-devel.   There may be some simpler approaches.

**Comment by lshep** [comment] 2022-02-22 14:17
Please see long tests -- http://contributions.bioconductor.org/long-tests.html 
Some testing should be done daily and with regular testing but there could be more thorough and length tests implemented on long tests run once a week

**Comment by mcjmigdal** [comment] 2022-03-01 14:20
@vjcitn hi, I've introduced the required changes including the use of BiocParallel. However, the package still fails to build under Windows...

The error is reported from the `foreach` loop:

```
Error: processing vignette 'xcore_vignette.Rmd' failed with diagnostics:
task 1 failed - "object 'runLinearRidge' not found"
```

here `runLinearRidge` is a internal function defined in `xcore` package.

That makes me suspect that something might be wrong with "parallelization" under Windows. Here is how the parallel backend is initialized in the vignette:

```
doParallel::registerDoParallel(2L)
BiocParallel::register(BiocParallel::DoparParam(), default = TRUE)
```

Kindly, let me know if I did something  wrong here.

**Comment by mcjmigdal** [comment] 2022-03-02 14:27
@vjcitn it looks like this might be more of a problem with the `foreach` package that I am using for parallel computing

here are some relevant links:
https://stackoverflow.com/questions/50113694/r-foreach-parallel-and-package-variables
https://github.com/RevolutionAnalytics/foreach/issues/3

I will return when I learn more about this, I will also try asking on bioc-devel

**Comment by vjcitn** [comment] 2022-03-02 14:31
you need to use BiocParallel -- and on windows understand that separate processes are spawned in the snow paradigm and that each process needs to be sure to get all the resources needed.  So you may need to pack more activities of package attachment and data initialization in your client processes on windows than on multicore, where resources are shared.

**Comment by mcjmigdal** [comment] 2022-03-11 17:05
@vjcitn I believe all is working as intended now. 

We had some small changes to README and vignette after the last successful build. These changes should not have much impact, the change in vignette adds `eval=FALSE` chunk showing how data can be loaded directly from `xcoredata` package, instead of `ExperimentHub` we wanted to have it as an option to work with R4.1. However, it seems I can not trigger new build anymore or maybe it is just taking longer than usual. Could you please look into that such that we are clear to proceed?

Cheers MM

**Comment by lshep** [comment] 2022-03-21 18:19
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mcjmigdal.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("xcore")`. The package 'landing page' will be created at

https://bioconductor.org/packages/xcore

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by lshep** [comment] 2022-03-21 18:19
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/mcjmigdal.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("xcoredata")`. The package 'landing page' will be created at

https://bioconductor.org/packages/xcoredata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-03-21 18:19 UTC
Labels: OK, 3a. accepted
