### ISSUE TITLE
dir.expiry

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Contributions#1889] opened 2021-02-15 07:19 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LTLA/dir.expiry

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by LTLA** [comment] 2021-02-15 07:20
This is motivated by the need to clear cached content for **basilisk** and **rebook**, and uses code already present in the former.

To preempt any suggestion to use **BiocFileCache**: yes, I did think about it, but:

- Too may dependencies for features that I didn't need.
- SQL look-up is slow and uses a lock that insufficiently granular.
- Expiry refers to re-downloading rather than deletion.
- Doesn't seem like I'm allowed to store directories rather than files, e.g., `bfcremove()` doesn't do a recursive removal.

**Comment by mtmorgan** [comment] 2021-02-15 13:51
Have you considered submitting this to CRAN since it has not Bioc dependencies (other than for the vignette, is useful outside the Bioc ecosystem, and is not likely to experience the rapid development / bug fix that makes the bioc release model more appealing?

**Comment by LTLA** [comment] 2021-02-15 19:26
Hm. I thought you might say that.

Yes, I did think about it, but the CRAN submission process seems incredibly tedious.

**Comment by nturaga** [comment] 2021-03-12 20:42
> Hm. I thought you might say that.
> 
> Yes, I did think about it, but the CRAN submission process seems incredibly tedious.

Hi @LTLA Are not submitting this to CRAN just because it's tedious? I have to agree with Martin here that I'm not able to find relevance for the package in Bioconductor.

According to the package submission pages, a Bioconductor the package should:

- Address areas of high-throughput genomic analysis, e.g., sequencing, expression, and other microarrays, flow cytometry, mass spectrometry, image analysis; see biocViews.
- Interoperate with other Bioconductor packages by re-using common data structures (see S4 classes and methods) and existing infrastructure (e.g., rtracklayer::import() for input of common genomic files).
- Adopt software best practices that enable reproducible research and use, such as full documentation and vignettes (including fully evaluated code) as well as a commitment to long-term user support through the Bioconductor support site.
- Not exist on CRAN. A package can only be submitted to one or the other.
Comply with Package Guidelines.
- Your package cannot depend on any package (or a version of a package) that is not (yet) available on CRAN or Bioconductor.


Any thoughts?

**Comment by LTLA** [comment] 2021-03-13 19:58
> Are you not submitting this to CRAN just because it's tedious?

Well, it's not just the initial submission process. I'm not encouraged by the CRAN guidelines, which recommend that maintainers limit package updates to monthly intervals. **dir.expiry** is solely designed to provide some infrastructure for **rebook** (and thus the OSCA books) and **basilisk**, both of which are difficult downstream dependencies. Historically speaking, updates to both packages on the BBS come in bursts as I try to identify a functional deployment strategy via trial and error. 

I suspect that incorporation of **dir.expiry** into either of these projects will involve a lot of fine-tuning to **dir.expiry** itself, and I'm not convinced that CRAN will allow me to do that in an expedient manner. Wen I participate in development of other CRAN packages, there always seems to be an inclination to reduce the number of updates, which does not seem very agile.

**Comment by nturaga** [comment] 2021-03-16 13:34
> > Are you not submitting this to CRAN just because it's tedious?
> 
> Well, it's not just the initial submission process. I'm not encouraged by the CRAN guidelines, which recommend that maintainers limit package updates to monthly intervals. **dir.expiry** is solely designed to provide some infrastructure for **rebook** (and thus the OSCA books) and **basilisk**, both of which are difficult downstream dependencies. Historically speaking, updates to both packages on the BBS come in bursts as I try to identify a functional deployment strategy via trial and error.
> 
> I suspect that incorporation of **dir.expiry** into either of these projects will involve a lot of fine-tuning to **dir.expiry** itself, and I'm not convinced that CRAN will allow me to do that in an expedient manner. Wen I participate in development of other CRAN packages, there always seems to be an inclination to reduce the number of updates, which does not seem very agile.

ok @LTLA I'll review the package. It seems that's a fair reason to have it in Bioconductor.

**Comment by nturaga** [comment] 2021-03-30 14:33
# Review dir.expiry

## R CMD build

ok

## R CMD INSTALL

ok

## DESCRIPTION

ok

## NAMESPACE

ok

## vignette

Good

## R

Good!

**Comment by vjcitn** [comment] 2021-04-03 11:15
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LTLA.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dir.expiry")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dir.expiry

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-04-03 11:15 UTC
Labels: 3a. accepted, OK
