### ISSUE TITLE
circRNAprofiler

### ISSUE THREAD

**Issue by Aufiero** [Bioconductor/Contributions#1133] opened 2019-05-28 14:53 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Aufiero/circRNAprofiler

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by Aufiero** [comment] 2019-05-29 11:15
1)
Deleted circRNAprofiler.Rproj from github

2)
Changed package version number from 0.1.1 to 0.99.0

3) 
The CMD CHECK failed because it was not able to load the resource.
I think also 'testthat.R' fails for the same reason.
Downloading seems to be the problem. Maybe that environment does not provide internet 
connection and the example hang waiting for a response.
The liftBSJCoords() retrieves the resource from AnnotationHub service.
There is also another function that uses the AnnotationHub service and it is the annotateRepeats().

I run the CMD CHECK again on my machine and everything works fine, at least locally.
Below I reported the R CMD CHECK results:

* checking examples ... [373s] OK
Examples with CPU or elapsed time > 5s
                  user system elapsed
plotMotifs      114.53   0.38  116.89
getMotifs        61.02   0.22   63.42
plotMiR          51.14   0.23   52.92
liftBSJCoords    22.19   2.58   31.29
mergeMotifs      14.70   0.27   17.19
annotateRepeats  10.69   1.56   18.38
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R' [12m]
 [12m] OK
 
-- R CMD check results ----------------------------- circRNAprofiler 0.99.0 ----
Duration: 25m 5.6s

> checking installed package size ... NOTE
    installed size is  5.0Mb
    sub-directories of 1Mb or more:
      data   3.4Mb
      doc    1.2Mb

0 errors v | 0 warnings v | 1 note x

R CMD check succeeded


I now pushed the changes for point 1) and 2). 
For point 3) I added the comment tag # to the code in the @examples chunk of the functions and test so that the examples are not run. In this way, we can see if the timeout error still persists.

**Comment by Aufiero** [comment] 2019-05-29 12:42
After adding the tag comment # to the code in the @examples chunk I do not get the error due to
the download of the resource.  This means can mean that there is a problem of connection to the AnnotationHub service from your environments.

I still got the error in testthat.R.
I now added the comment tag # to avoid running the test for the function liftBSJcoords().

**Comment by Liubuntu** [comment] 2019-06-05 18:34
Hi @Aufiero 

Thanks for submitting your package to Bioconductor. An official review will be given shortly (within 2 weeks of last successful build). 

Cheers,
Qian

**Comment by Liubuntu** [comment] 2019-06-18 13:57
Hi @Aufiero , 

Here is part of your package review. I will post the 2nd half soon. Please seek to address the issues listed, and comment back here with updates / questions. 

Best,
Qian

## DESCRIPTION 

- `LazyData:` field: For packages that include data, we recommend not including LazyData: TRUE. This rarely proves to be a good thing. In our experience it only slows down the loading of packages with large data.
- `BugReports:` field: It is encouraged to include the relevant links to Github for reporting Issues.
- `URL:` field: This field directs users to source code repositories, additional help resources, etc; It is recommended to include the link here. 

## R/

**initCircRNAprofiler.R** 
- L53: use `file.path()` instead of `paste(sep="/")` here, so that it could automatically adjust the separator based on different OS.
- L97, use the `file.path()` to construct the file path instead of the `paste0()`. Same applies to the ther `get*Tamplate` functions. 
- This is trivial, but is it typo in the `get*Tamplate()` functions? Maybe you meant `Template`? 

**checkProjectFolder.R**

- L137, L157, L176: With your current check using `%in%`, an edge case maybe that the file has 2 or more columns named as `id`, although not very likely, but you never know and may be helpful to test. So maybe just using `colnames()=="id"` or adding `ncol() == 1` to exclude the edge case. 

**getBackSplicedJunctions.R**
- L52: use `if (nrow(experiment))` and remove the `>0` and it will work sufficiently here. 
- L67: use `file.path()` here for constructing a file path. 

**filterCirc.R**
- L68: use `if(nrow(experiment))` to avoid checking twice. 

**General**

- For functions that return a `data.frame` as output, you may consider using `DataFrame` instead, which basically has the same characteristics as `data.frame` and has a better show method. You can try using `DataFrame(data.frame(letters, LETTERS))` and compare with an ordinary `data.frame` to have a feel. 

## man/
- formatGTF.Rd:L10. typo, remove one `the` from the sentence.
- getBackSplicedJunctions.Rd:L17. The list-like format can be generated by using the follow inside the .Rd file: 
\describe{
	\item{1}{description about 1}
	\item{2}{... }
}
```

## vignette
- Installation: you should show users how to download the package as if the package is already included in Bioconductor. E.g., 

```
BiocManager::install("circRNAprofiler")
```

You can also download the development version on github using `BiocManager`: 

```
BiocManager::install("Aufiero/circRNAprofiler")
```

- L301: Based on my understanding, should it be "extendable" instead of "extended" here?

**Comment by Aufiero** [comment] 2019-06-21 08:05
Thanks Qian,
I addressed all of the issues, except for the following 2. 

- About **LazyData**.
If I use LazyData = FALSE, I get an error during the R CMD check when creating the vignettes.
data in the package are used in the vignettes as well as in the @examples section of the functions.
Shall I  keep LazyData = TRUE?

-About the use of **DataFrame**
The show method is indeed better. 
I did a test with the _getBackSplicedJunctions()_ and _mergeBSJunctions()_ functions.
The output of _getBackSplicedJunctions()_ is the input of _mergeBSJunctions()_.
For the _getBackSplicedJunctions()_ I returned a DataFrame object instead of a data.frame.
I gave the DataFrame object to _mergeBSJunctions()_ and I got the following error:

**Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "c('DataFrame', 'DataTable', 'SimpleList', 'DataTable_OR_NULL', 'List', 'Vector', 'list_OR_List', 'Annotated')"**

**mutate** is a method of dplyr package. It seems that it does not work on a DataFrame object. Since I use a lot the dplyr package in the functions of circRNAprofiler I would prefer to keep the object data.frame also because I do not know how many issues it may cause if change it. 

If you agree, I'll push all the changes that you suggested.

S

**Comment by Liubuntu** [comment] 2019-07-08 20:24
Hi @Aufiero , 

Sorry for the delay of responding. I have just reviewed the rest of your package, here are the comments: 

## R/ 

**getDeseqRes.R**
- L83, use `if (nrow(experiment))` only to avoid double checking.
- same for getEdgerRes.R: L87, and annotateRepeats.R: L154.  
- Prefix `.` for the non-exported, utility functions, such as
  `getEdgerResDF` and `getDeseqResDF`. See [here](http://bioconductor.org/developers/how-to/coding-style/) for details.

## unit tests
- Looks good!


For your question about using `DataFrame`, you are fine to use the `data.frame` to get the best interoperability with dplyr grammars. 

Bioconductor usually recommends removing the whole `lazyData` field from `DESCRIPTION` file. Your problem of R CMD CHECK doesn't seem to be related to the `lazyData`. But I'll try to reproduce to see if there is any other problem. 

Best,
Qian

**Comment by Liubuntu** [comment] 2019-07-08 21:30
Hi @Aufiero , 

I couldn't reproduce your error with `R CMD CHECK`. Can you remove the `lazyData: TRUE` field from your `DESCRIPTION` file, and redo the check to see if the result will change? 

Qian

**Comment by Aufiero** [comment] 2019-07-09 06:57
Hi Qian,

-About **lazyData**:
I removed the lazyData field from the DESCRIPTION file and I ran the R CMD check. 
This is the error that I get:

**Quitting from lines 368-382 (circRNAprofiler.Rmd) 
   Error: processing vignette 'circRNAprofiler.Rmd' failed with diagnostics:
   object 'backSplicedJunctions' not found
   --- failed re-building 'circRNAprofiler.Rmd'
   
   SUMMARY: processing the following file failed:
     'circRNAprofiler.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
Calls: <Anonymous> ... eval -> with_envvar -> force -> do.call -> <Anonymous>
Execution halted

Exited with status 1.**

-About the **Prefix .** for the non-exported functions:
shall I rename for example getEdgerResDF to .getEdgerResDF, right? 
Except getEdgerResDF and getDeseqResDF there are also other
non- exported functions in my package, shall I rename all of them using the prefix ''."?

Thanks.

**Comment by Aufiero** [comment] 2019-07-09 11:01
Hi Qian,

-About **lazyData**:
I removed the lazyData field from the DESCRIPTION file and I ran the R CMD check.
This is the error that I get (see attached file)
[check.txt](https://github.com/Bioconductor/Contributions/files/3372597/check.txt)

-About the **Prefix .** for the non-exported functions:
shall I rename for example getEdgerResDF to .getEdgerResDF, right? 
Except getEdgerResDF and getDeseqResDF there are also other
non- exported functions in my package, shall I rename all of them using the prefix ''."?

**Comment by Liubuntu** [comment] 2019-07-09 19:38
Hi @Aufiero , 

For your 2nd question, yes. It would be a good practice in developing R packages, by prefixing "." for non-exported functions. Highly recommended to make updates for all cases.

For the other review points, if you find similar cases, just update them all, not restricted to those I mentioned. 

For the 1st question, first, you need to correct your vignette .Rmd file, L356, into `eval=TRUE`. Rerun the `R CMD check`, you should see some other errors in examples, and test functions as listed below. Fix all until you get a clean report, let me know for any questions.  

1. errors in example and test function, in `getRegexPattern.R` script. the 
- `circRNAprofiler::inpac` usage , what is it? 

2. `getMirSite.R`: remove the `#` comment signal for the example of `getMiRsite()`. 

3. You should never use `setwd` in your scripts!! 
- Instead, use following code to avoid the separator confusion on different building machine. (mac/windows/linux)
```
dir <- system.file("tests", "testthat", "testdata", package = "circRNAprofiler")
system.file(dir, "gencodeVM16.gtf")
```
- test failed in `test_getMirSites.R`. But also update all other functions that including `setwd()`. 

Qian

**Comment by Aufiero** [comment] 2019-07-10 07:34
Hi Qian,

-about **setwd**
for my package to work the user needs to set the project folder as working directory.
The project folder contains project files and the circRNA prediction results. The package circRNAprofiler assumes that the circRNA prediction results are put in specific subfolders of the project folder. The names of the files containing the circRNA prediction results are specified in a file named experiment.txt.

Since I can not use system.file to point to circRNA prediction results I need to set testdata as working directory. 
Can use system.file and then setwd? In this way it should be ok on different building machines.
dir <- system.file("tests", "testthat", "testdata", package = "circRNAprofiler")
setwd(dir)

**Comment by Aufiero** [comment] 2019-07-11 06:27
Hi Qian,

-about **setwd**
for my package to work the user needs to set the project folder as working directory.
The project folder contains project files and the circRNA prediction results. The package circRNAprofiler assumes that the circRNA prediction results are put in specific subfolders of the project folder. The names of the files containing the circRNA prediction results are specified in a file named experiment.txt.

Since I can not use system.file to point to circRNA prediction results I need to set testdata as working directory. 
Can use file.path with setwd? In this way it should be ok on different building machines.
setwd(file.path(getwd(), "testdata"))

**Comment by Liubuntu** [comment] 2019-07-16 16:03
Hi @Aufiero , 

Since the check is OK, and the `setwd` didn't trigger any building error, I'll let it pass. Thank you for the contribution to Bioconductor. 

Cheers,
Qian

**Comment by mtmorgan** [comment] 2019-07-18 14:47
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/Aufiero.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("circRNAprofiler")`. The package 'landing page' will be created at

https://bioconductor.org/packages/circRNAprofiler

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-07-18 14:47 UTC
Labels: 3a. accepted
