### ISSUE TITLE
lefser

### ISSUE THREAD

**Issue by asyakhl** [Bioconductor/Contributions#1695] opened 2020-10-02 19:44 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/waldronlab/lefser

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by LiNk-NY** [comment] 2020-10-13 13:14
Hi Martin, @mtmorgan 
We'd like to have this package in release. 
Thank you. 
-Marcel

**Comment by mtmorgan** [comment] 2020-10-14 19:52
Only a few comments on this package

DESCRIPTION

- OK

vignettes

- lefser.Rmd:66 Please explain this comment!!!!! It is the only line in the vignette that evaluates package function.

R

- data.R:5 -- it's not so useful to provide user documentation that indicates directory `data-raw`, since this is not available to the user. Better to put these scripts in `inst/script` and reference the location using `system.file()`.

- data.R:11 this looks like an incomplete description of the data; please complete.

- lefser.R:63 I'm not sure whether the size of data makes efficiency important, but this code looks very inefficient. Start by 'hoisting' common subsexpressions outside loops

    ```
    c <- 0
    for (i in seq_along(unique(block))) {
        llosc <- logical.list.of.subclasses[[i]]]
        n_i <- rep(0, sum(logical.list.of.subclasses[[i]]))
    ```

**Comment by LiNk-NY** [comment] 2020-10-21 04:07
Hi Martin, @mtmorgan 
Thank you for your comments and the quick review.
Here is our line-by-line response. 

> vignettes
> 
> * lefser.Rmd:66 Please explain this comment!!!!! It is the only line in the vignette that evaluates package function.

We've updated the main `lefser` function and this code chunk is now running. We also removed development
comments.
 
> R
> 
> * data.R:5 -- it's not so useful to provide user documentation that indicates directory `data-raw`, since this is not available to the user. Better to put these scripts in `inst/script` and reference the location using `system.file()`.

We've move this script to `inst/scripts`. 

> * data.R:11 this looks like an incomplete description of the data; please complete.

We weren't sure if you wanted us to document _all_ columns in the data (~25) so we provided
descriptions only for the relevant ones in the analysis.

> * lefser.R:63 I'm not sure whether the size of data makes efficiency important, but this code looks very inefficient. Start by 'hoisting' common subsexpressions outside loops
>   ```
>   c <- 0
>   for (i in seq_along(unique(block))) {
>       llosc <- logical.list.of.subclasses[[i]]]
>       n_i <- rep(0, sum(logical.list.of.subclasses[[i]]))
>   ```

We re-worked many of the for loops in the code based on this comment and saw a marked
speed increase. Thank you. 

See the approximate changes in this comparison: https://github.com/waldronlab/lefser/compare/97287deb1724a0a633db6443796743297d42f407..master

**PS.** Unit tests are failing in the package due to an unknown error. When run locally, the unit tests are
successful but when running `R CMD check` they fail. We are not sure if this is related to the seed
generation. We used `withr::with_seed` to see if this would help but we get the same result as using
`set.seed` before the function call (see above report). Any insight would be appreciated. Thank you. 

-Marcel
cc: @asyakhl

**Comment by LiNk-NY** [comment] 2020-10-22 02:58
Hi Martin, @mtmorgan 

It seems like the tests are passing on GitHub Actions (`r79342`) but not locally on the `r78887` or `r79342`
checkouts of R. 

GHA: R 4.0.3 patched -- OK https://github.com/waldronlab/lefser/actions/runs/321105511
Local: R 4.0.2 patched -- FAILS
Local: R 4.0.3 patched -- FAILS
SPB: R 4.0.3 (2020-10-10) -- FAILS

I should also note that when the tests are run in an R session, they do pass. The value of the
seed is `1` and the documentation says 
> It is intended as a simple way to get quite
     different seeds by specifying small integer arguments, and also as
     a way to get valid seed sets for the more complicated methods
     (especially '"Mersenne-Twister"' and '"Knuth-TAOCP"').
I am not sure if this makes a difference. 

I will keep an eye out on the latest report. 
Any ideas are appreciated. Thanks!

**Comment by mtmorgan** [comment] 2020-10-22 07:01
I think the issue is the collation (sort) order. If I modify the start of the `test_that()` clause to
```
test_that("lefser and lefserPlot work", {
  print(Sys.getlocale())
```
I see
```
> Sys.getlocale()
[1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"
> devtools::test()
Loading lefser
Testing lefser
✔ |  OK F W S | Context
⠏ |   0       | lefser[1] "C/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"
```
so `devtools::test()` has changed the collation order from "en_US.UTF-8" to "C". And indeed setting the collation order and stepping through the individual lines fo the test...
```
> Sys.setlocale("LC_COLLATE", "C")
[1] "C"
> Sys.getlocale()
[1] "C/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"
>   dataenv <- new.env(parent = emptyenv())
>   data("zeller14", package = "lefser", envir = dataenv)
>   zeller14 <- dataenv[["zeller14"]]
>   tol <- 0.2
>   zellersub <- zeller14[1:150, zeller14$study_condition != "adenoma"]
>   expect_error(lefser(zellersub, groupCol = NULL, blockCol = NULL))
>   results <- withr::with_seed(1,
+     lefser(zellersub, groupCol = "study_condition", blockCol = NULL)
+   )
>   expect_equal(colnames(results), c("Names", "scores"))
>   expect_true(checkEnding(results, 1, "Names", "p__Firmicutes`"))

Error: checkEnding(results, 1, "Names", "p__Firmicutes`") isn't true.
```

**Comment by lshep** [comment] 2020-10-22 19:48
Yes we are working on the fix now.  Sorry for the inconvenience.

**Comment by asyakhl** [comment] 2020-10-23 01:12
Hi Martin, @mtmorgan 
`lefser` is ready for a second look.

Thank you,
Asya
cc: @LiNk-NY

**Comment by mtmorgan** [comment] 2020-10-23 17:18
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/asyakhl.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("lefser")`. The package 'landing page' will be created at

https://bioconductor.org/packages/lefser

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-10-23 17:18 UTC
Labels: 3a. accepted
