### ISSUE TITLE
biobtreeR 

### ISSUE THREAD

**Issue by tamerh** [Bioconductor/Contributions#1284] opened 2019-10-10 20:27 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to Bioconductor

- Repository: https://github.com/tamerh/biobtreeR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by tamerh** [comment] 2019-10-22 09:03
Hi @lshep 

I was wondering is there any chance that this package can be reviewed before the new biconductor release?

**Comment by lshep** [comment] 2019-10-22 11:25
I will try to get to reviewing this package.  The package deadline for us to actively try to get package in the fall release was October 4th (and you submitted the  10th) -  and your package only started building cleanly 3 days ago.  I will do my best to get to this as soon as possible perhaps later today -

**Comment by tamerh** [comment] 2019-10-22 12:34
Thanks @lshep. Yes I was late for submission and clean build, just after reading the announcement
email from mailing list I wanted to check if there is any chance. Looking forward to your review.

**Comment by lshep** [comment] 2019-10-22 16:17
Please find the start of the review -  I did not go in an in depth review of the R code yet until some clean up issues are resolved: 

**build report**

- [ ] Fix license note. see description and license below
- [ ] Fix dependency NOTE concerning method and global functions NOTES. The
build report gives the solution to add to NAMESPACE
```
  importFrom("methods", "new")
  importFrom("utils", "download.file", "untar", "unzip")

```
- [ ] Fix Rd line width NOTE
- [ ] We strongly recommend unit tests. 


**DESCRIPTION**

- [ ] MTI + file

**LICENSE**

- [ ] You don't need the explicit detail of the MIT license as it is included
  with base R.  Just your name and year. 

**NEWS**

- [ ] Populate NEWS file or don't included it.  NEWS files capture changes from
  version to version and are utilized when we do our [release
  announcements](http://bioconductor.org/news/bioc_3_9_release/).  See `?news`
  in R for formatting

**inst**
- [ ] What are these tar.gz files. Data for packags should either be in
`inst/extdata` or `data`.  If these are placed in `inst/extdata` there needs to
be a directory `inst/scripts` that describes where and how this data was
generated that could be in text, sudo code, or code. We prefere as much code as
possible so a user could reproduce these data files if necessary.  

**VIGNETTE**

- [ ] So am I correct that this can be used as a webserver as descibed
  initially? and then the other commands - show its use command line? Maybe this
  should be better indicated with subsections. 

- [ ] On the webserve it dosen't look like there is a way to see whats available
  to filter or search? No offered suggestions? Seems like exact match?

- [ ] When running the examples in the vignette, it looks like there are many
  files that end up in the working directory. This should never be the
  case. Please use a `tempdir()` for examples/vignettes  

- [ ] Full datasets can be discovered with `bbConfig` but there is no
  documentation on how to do this. 
```
> bbConfig()
Error in bbConfig() : could not find function "bbConfig"

```

**R / man**

- [ ] Is there a way to discover what datasets and targetDatasets are available
  for bbBuildData? 

I tried to naively run  `bbListGenomes` since it is referenced in the help page
to list the available options. But when I do the example
```
> library(biobtreeR)
> ?bbListGenomes
>     bbStart()
[1] "Starting biobtree..."
2019/10/22 12:11:58 Error while reading meta information file which should be produced with generate command. Please make sure you did previous steps correctly.

```

- [ ] `bbStart()`  always pollutes users working directory. This is a big problem and not allowed - this should be a temporary directory when running examples/vignettes/tests.  The user should be  able to specify where these files are going to be placed on their system. 

Please start with the above changes and I will look more thoroughly at the R code. Thank you

**Comment by tamerh** [comment] 2019-10-23 03:33
Thanks @lshep for your very useful initial review. Please find my responses below.
 
> Please find the start of the review - I did not go in an in depth review of the R code yet until some clean up issues are resolved:
> 
> **build report**
> 
> * [x]  Fix license note. see description and license below
> * [x]  Fix dependency NOTE concerning method and global functions NOTES. The
>   build report gives the solution to add to NAMESPACE
> 
> ```
>   importFrom("methods", "new")
>   importFrom("utils", "download.file", "untar", "unzip")
> ```
> 
> * [x]  Fix Rd line width NOTE
> * [ ]  We strongly recommend unit tests.
> 
I am going to add unit tests asap.

> **DESCRIPTION**
> 
> * [x]  MTI + file
> 
> **LICENSE**
> 
> * []  You don't need the explicit detail of the MIT license as it is included
>   with base R.  Just your name and year.

I am not getting build Note for License after fixing the DESCRIPTION. So I leave the LICENSE file as it is but i can remove the explicit detail of the MIT?

> 
> **NEWS**
> 
> * [x]  Populate NEWS file or don't included it.  NEWS files capture changes from
>   version to version and are utilized when we do our [release
>   announcements](http://bioconductor.org/news/bioc_3_9_release/).  See `?news`
>   in R for formatting

I excluded the NEWS file

> 
> **inst**
> 
> * [x]  What are these tar.gz files. Data for packags should either be in
>   `inst/extdata` or `data`.  If these are placed in `inst/extdata` there needs to
>   be a directory `inst/scripts` that describes where and how this data was
>   generated that could be in text, sudo code, or code. We prefere as much code as
>   possible so a user could reproduce these data files if necessary.
> 

Yes these are sample data packages and now moved to `inst/extdata` with explanation of how to generate. 

> **VIGNETTE**
> 
> * [x]  So am I correct that this can be used as a webserver as descibed
>   initially? and then the other commands - show its use command line? Maybe this
>   should be better indicated with subsections.

Yes basically when data is built with desired dataset only once, then it can be used as a web server to perform queries and start/stop any time. Web server is now indicated with subsections.

> * [x]  On the webserve it dosen't look like there is a way to see whats available
>   to filter or search? No offered suggestions? Seems like exact match?

The search functionality is exact match for identifiers/accessions or special keywords such as gene or species name.  Suggestions like queries can be performed in via filters like in the last gene centric use case "Retrieve all the human gene names which contains TTY". Please let me if you need more clarification about this.

> * [x]  When running the examples in the vignette, it looks like there are many
>   files that end up in the working directory. This should never be the
>   case. Please use a `tempdir()` for examples/vignettes
> * [x]  Full datasets can be discovered with `bbConfig` but there is no
>   documentation on how to do this.
> 
> ```
> > bbConfig()
> Error in bbConfig() : could not find function "bbConfig"
> ```
> 
> **R / man**
> 
> * [x]  Is there a way to discover what datasets and targetDatasets are available
>   for bbBuildData?

I fixed this. Now dataset list can be discovered with `bbListDatasets` function

> 
> I tried to naively run `bbListGenomes` since it is referenced in the help page
> to list the available options. But when I do the example
> 
> ```
> > library(biobtreeR)
> > ?bbListGenomes
> >     bbStart()
> [1] "Starting biobtree..."
> 2019/10/22 12:11:58 Error while reading meta information file which should be produced with generate command. Please make sure you did previous steps correctly.
> ```
> 

This was because bbListGenomes was requiring to call `bbBuildData` before using it. But now based on your review i changed this behaviour and both `bbListGenomes` and `bbListDatasets` functions can be used without building data explicitly.

> * [x]  `bbStart()`  always pollutes users working directory. This is a big problem and not allowed - this should be a temporary directory when running examples/vignettes/tests.  The user should be  able to specify where these files are going to be placed on their system.

Yes this was big problem i fixed this issue and now for examples/vignettes tempdir is used also user have option to specify the directory for these files if not specified by default tempdir is used

> 
> Please start with the above changes and I will look more thoroughly at the R code. Thank you

**Comment by tamerh** [comment] 2019-10-23 17:55
> Thanks @lshep for your very useful initial review. Please find my responses below.
> 
> > Please find the start of the review - I did not go in an in depth review of the R code yet until some clean up issues are resolved:
> > **build report**
> > 
> > * [x]   Fix license note. see description and license below
> > * [x]   Fix dependency NOTE concerning method and global functions NOTES. The
> >   build report gives the solution to add to NAMESPACE
> > 
> > ```
> >   importFrom("methods", "new")
> >   importFrom("utils", "download.file", "untar", "unzip")
> > ```
> > 
> > 
> > 
> > * [x]   Fix Rd line width NOTE
> > * [x]   We strongly recommend unit tests.
> 
Unit tests added
> 
> > **DESCRIPTION**
> > 
> > * [x]   MTI + file
> > 
> > **LICENSE**
> > 
> > * []  You don't need the explicit detail of the MIT license as it is included
> >   with base R.  Just your name and year.
> 
> I am not getting build Note for License after fixing the DESCRIPTION. So I leave the LICENSE file as it is but i can remove the explicit detail of the MIT?
> 
> > **NEWS**
> > 
> > * [x]   Populate NEWS file or don't included it.  NEWS files capture changes from
> >   version to version and are utilized when we do our [release
> >   announcements](http://bioconductor.org/news/bioc_3_9_release/).  See `?news`
> >   in R for formatting
> 
> I excluded the NEWS file
> 
> > **inst**
> > 
> > * [x]   What are these tar.gz files. Data for packags should either be in
> >   `inst/extdata` or `data`.  If these are placed in `inst/extdata` there needs to
> >   be a directory `inst/scripts` that describes where and how this data was
> >   generated that could be in text, sudo code, or code. We prefere as much code as
> >   possible so a user could reproduce these data files if necessary.
> 
> Yes these are sample data packages and now moved to `inst/extdata` with explanation of how to generate.
> 
> > **VIGNETTE**
> > 
> > * [x]   So am I correct that this can be used as a webserver as descibed
> >   initially? and then the other commands - show its use command line? Maybe this
> >   should be better indicated with subsections.
> 
> Yes basically when data is built with desired dataset only once, then it can be used as a web server to perform queries and start/stop any time. Web server is now indicated with subsections.
> 
> > * [x]   On the webserve it dosen't look like there is a way to see whats available
> >   to filter or search? No offered suggestions? Seems like exact match?
> 
> The search functionality is exact match for identifiers/accessions or special keywords such as gene or species name. Suggestions like queries can be performed in via filters like in the last gene centric use case "Retrieve all the human gene names which contains TTY". Please let me if you need more clarification about this.
> 
> > * [x]   When running the examples in the vignette, it looks like there are many
> >   files that end up in the working directory. This should never be the
> >   case. Please use a `tempdir()` for examples/vignettes
> > * [x]   Full datasets can be discovered with `bbConfig` but there is no
> >   documentation on how to do this.
> > 
> > ```
> > > bbConfig()
> > Error in bbConfig() : could not find function "bbConfig"
> > ```
> > 
> > 
> > **R / man**
> > 
> > * [x]   Is there a way to discover what datasets and targetDatasets are available
> >   for bbBuildData?
> 
> I fixed this. Now dataset list can be discovered with `bbListDatasets` function
> 
> > I tried to naively run `bbListGenomes` since it is referenced in the help page
> > to list the available options. But when I do the example
> > ```
> > > library(biobtreeR)
> > > ?bbListGenomes
> > >     bbStart()
> > [1] "Starting biobtree..."
> > 2019/10/22 12:11:58 Error while reading meta information file which should be produced with generate command. Please make sure you did previous steps correctly.
> > ```
> 
> This was because bbListGenomes was requiring to call `bbBuildData` before using it. But now based on your review i changed this behaviour and both `bbListGenomes` and `bbListDatasets` functions can be used without building data explicitly.
> 
> > * [x]   `bbStart()`  always pollutes users working directory. This is a big problem and not allowed - this should be a temporary directory when running examples/vignettes/tests.  The user should be  able to specify where these files are going to be placed on their system.
> 
> Yes this was big problem i fixed this issue and now for examples/vignettes tempdir is used also user have option to specify the directory for these files if not specified by default tempdir is used
> 
> > Please start with the above changes and I will look more thoroughly at the R code. Thank you

**Comment by tamerh** [comment] 2019-10-30 10:30
Hello @lshep, just want to mention that with latest commits i have reorganised the code
and made some improvements with listing functions.

**Comment by lshep** [comment] 2019-11-13 14:07
Sorry for the delay.  I'm looking at the package now and should have a review in the next day or two.

**Comment by lshep** [comment] 2019-11-13 19:35
Please see review below.  As before please work on the changes and when ready do a version bump and comment back here with what has been updated or any clarification/comments: 


**GENERAL**
- [ ] When building locally with R CMD build (creating vignette...) - It causes a pop of the ui which does not get cleaned up upon the completed package build. Please fix this. 
- [ ] The same with running a local R CMD check (in checking examples... and in checking tests... and rebuilding vignette). So it actually opens four different `http://localhost:8888/ui/` windows that don't close. Clean this up. 

**Vignettes**
- [ ] Please remove the `.html` file. It should be generated interactively on the build of the package. 
- [ ] You state:
```
 And once this process is completed it does not require to perform again unless to work on new datasets or fetching the latest version of the datasets
```
Is there a way to check that there has been an update to one or all of the datasets?  Is there a way to only update one dataset (one that has been updated instead of all)? Just curious at the caching mechanism behind this (if there is one - There are useful packages like BiocFileCache that may be of interest - or you could create some system of your own if there isn't one in place) because as
noted the data can take a very long time to download so this should only be done
if necessary or forced by the user. 
- [ ] Assumingly the default to argument outDir is now a temporarily directory (which is correct and should continue in this way) But maybe this should be mentioned as I assume this only download once mentioned/referenced above will be dependent on running the functions in the directory where the datasets are?
- [ ] In examples with real datasets, maybe reference the future section for exploration of what is available for each argument.
- [ ] If you start the web server once and close the window. You cannot get it
to come back up again. I get a message about refreshed but no server pops up.
```
> bbStart()
[1] "biobtreeR started before.Config refreshed"
```
- [ ] Again would be nice to specify that a user can use the web server in 2.2
OR do interactivly with the remaining sections of vignette. It also seems like
bbBuildData needs to be run before activating `bbStart` so maybe it would make
sense to switch the order to show how you find the arguments to bbBuildData.
- [ ] It seems odd that a biobtree would stay running even when an R session
closes.  I ran some code, exited R, opened a new session and tried to start but
still get 
```
Error in bbBuildData(datasets = "sample_data") : 
  There is a running biobtree stop with bbStop()
```
It seems like it should be R session independent; At least when running in
different directories of data.
- [ ] It seems like there should be an option to `bbStart()` without opening the
web server window if a user was planning on working slowly through the command
line. For instance I can't do the following. 
```
> bbBuildData(datasets="sample_data")
> bbSearch("tpi1,vav_human,ENST00000297261")
Error in open.connection(con, "rb") : 
  Failed to connect to localhost port 8888: Connection refused
``` 
I would have to do `bbStart` first but that opens the web server. 
- [ ] So in understanding the connection to doing a search in the web ui for
  `tpi1,vav_human,ENST00000297261` vs doing
  `bbSearch("tpi1,vav_human,ENST00000297261")` .  It lists the top level.  I see
  that if I add showURL it links to the different additional information pages
  that I could also click on from the top level search page on the ui.  It might
  also be nice to include the number of values that you see on the web server in
  the command line 
  ie.  
```
431 Results for Ensembl ENSG00000111669 TPI1
300 Results for Transcript ENST00000297261     
269 Results for Uniprot P15498 VAV_HUMAN
9 Results for HGNC HGNC:12009 TPI1
```
  And it looks like attribute information from the web server result is also
  excluded in the command line interface? 
  It would be nice to be as complete and consistent as possible to what is
  displayed from each.  
  Update after man pages:  Is this what the `lite=FALSE` tries to accomplish?

- [ ] Again I'm trying to compare what can be done in the web server to the
  results in command line.  What would be the equivalent input into the webserve
  to mimic the command line:
```
bbMapping("AT5G3_HUMAN",'map(go)',attrs = "type")
```
  I tried but kept getting no result. 

- [ ] Typo for referencing your function in 3.1. `bbListDataset` does not exist
  `bbListDatasets` is the function name. 
- [ ] The mapping constructions seems complex. Not sure what the solution is but
  just making note. This of course is subjective and will not affect the review.


**R/man**

- [ ] bbConfig-class doesn't seem like it should be exported. It is used
  internally only and there are no access or modifier methods for it.  Either
  expand and show use cases or don't export. 


**man**
_bbBuildData_
- [ ] you mention the helper bbListGenomes maybe also list the helper
bbListDatasets

_bbEntryPage_
- [ ] Not clear what or how confiGured biobtree paging size is set or modified.

_bbUseRemoteServe_
- [ ] What is the point of this?  Not enough information in the man file and not
mentioned in the vignette on where or why this would be used. Its also not
exported so really doesn't need documentation. At the very least mark it as
`@internal`


_general_
- [ ] A lot of the examples if I try to run independent, they ERROR. Because
they start with bbStart: 
```
> library(biobtreeR)
> bbStart()
trying URL 'https://github.com/tamerh/biobtree/releases/download/v1.2.0/biobtree_Linux_64bit.tar.gz'
Content type 'application/octet-stream' length 10038409 bytes (9.6 MB)
==================================================
downloaded 9.6 MB

biobtree
Error in file(con, "rb") : cannot open the connection
In addition: Warning message:
In file(con, "rb") :
  cannot open file '/tmp/RtmpMCPQzm/conf/source.dataset.json': No such file or directory
> 

```

**R code**

_general_

- [ ] You don't need paste0 in stop calls. Please remove. Example with message
  that works the same way:
```
> vl = 3; 
> message("a message ", vl) 
a message 3
```

_buildData.R_  
- [ ] Should there be a check when the directory actually does exist to make
sure you aren't overwriting or polluting by accident? You could create the path
if it doesn't exists; but stopping is okay too.


_config.R_

- [ ] How often do the databases/info/releases/etc on github change?

**Comment by tamerh** [comment] 2019-11-13 21:42
Thanks for the all the comments @lshep. I will address them and let you know.

**Comment by lshep** [comment] 2019-11-13 21:43
Again I apologize for the delay in getting it to you.  Cheers

**Comment by tamerh** [comment] 2019-11-13 21:45
No worries. Cheers

**Comment by tamerh** [comment] 2019-12-05 13:43
Hello @lshep, It took some time but I finally have completed addressing your comments. I essentially restructured package to improve usability and hiding the complexity based on your comments. 

Main change is that again with your suggestion now there are pre built databases like cache for common datasets  and most studied organism genomes. This now also allow me to build the vignettes with real database instead of sample data. But user still can built custom database similarly before which I explained in vignettes. Also I improved the genome coordinates data granularity now internally genomes coordinates are being read from ensembl gff3 files previously it was json. 

Please see my responses to your each comment. Thanks again your comments and looking forward to see your new review.

> Please see review below. As before please work on the changes and when ready do a version bump and comment back here with what has been updated or any clarification/comments:
> 
> **GENERAL**
> 
> * [X]  When building locally with R CMD build (creating vignette...) - It causes a pop of the ui which does not get cleaned up upon the completed package build. Please fix this.
> * [X]  The same with running a local R CMD check (in checking examples... and in checking tests... and rebuilding vignette). So it actually opens four different `http://localhost:8888/ui/` windows that don't close. Clean this up.
>
No popup anymore.
> **Vignettes**
> 
> * [X]  Please remove the `.html` file. It should be generated interactively on the build of the package.
> * [X]  You state:
> 
> ```
>  And once this process is completed it does not require to perform again unless to work on new datasets or fetching the latest version of the datasets
> ```
> 
> Is there a way to check that there has been an update to one or all of the datasets? Is there a way to only update one dataset (one that has been updated instead of all)? Just curious at the caching mechanism behind this (if there is one - There are useful packages like BiocFileCache that may be of interest - or you could create some system of your own if there isn't one in place) because as
> noted the data can take a very long time to download so this should only be done
> if necessary or forced by the user.
> 
Now there are pre-built databases for common datasets and genomes. This reduce processing time significantly. These pre built databases are hosted in [github](https://github.com/tamerh/biobtree-conf/releases/). And user will receive message when running the `bbStart` if there is update and it is up to user to keep existing one or update it. I am going to update these caches monthly with following uniprot and ensembl release. But I would like to point that user still can built the same data without this cache with `bbBuildCustomDB`. But clearly cache is reducing the processing time and hiding the data build complexity.

> * [X]  Assumingly the default to argument outDir is now a temporarily directory (which is correct and should continue in this way) But maybe this should be mentioned as I assume this only download once mentioned/referenced above will be dependent on running the functions in the directory where the datasets are?

I have changed the logic here and now outDir must be explicitly set by user when using the package. I think this will help not to confuse user and user will be more aware where the data is stored. This will also reduce the complexity of the code for handling the temp dir. Though temp directory can be still used as I used in vignettes but it must be explicitly set. Hope this make sense.  

> * [ ]  In examples with real datasets, maybe reference the future section for exploration of what is available for each argument.

Since I changed the data built process it would be great to hear your review with the new structure for this comment.
 
> * [X]  If you start the web server once and close the window. You cannot get it
>   to come back up again. I get a message about refreshed but no server pops up.
> 
> ```
> > bbStart()
> [1] "biobtreeR started before.Config refreshed"
> ```

In fact my idea for pop up was just for easy shortcut but I understand that it is confusing and possibly annoying. After `bbStart` both web interface and command line can be used at the same time which I also mentioned this in vignettes. And url for the web interface is always `localhost:8888/ui` 

> 
> * [X]  Again would be nice to specify that a user can use the web server in 2.2
>   OR do interactivly with the remaining sections of vignette. It also seems like
>   bbBuildData needs to be run before activating `bbStart` so maybe it would make
>   sense to switch the order to show how you find the arguments to bbBuildData.

Hopefully new structure and flow in the vignettes is addressing this?

> * [ ]  It seems odd that a biobtree would stay running even when an R session
>   closes.  I ran some code, exited R, opened a new session and tried to start but
>   still get
> 
> ```
> Error in bbBuildData(datasets = "sample_data") : 
>   There is a running biobtree stop with bbStop()
> ```
> 
> It seems like it should be R session independent; At least when running in
> different directories of data.
> 
> * [ ]  It seems like there should be an option to `bbStart()` without opening the
>   web server window if a user was planning on working slowly through the command
>   line. For instance I can't do the following.
> 
> ```
> > bbBuildData(datasets="sample_data")
> > bbSearch("tpi1,vav_human,ENST00000297261")
> Error in open.connection(con, "rb") : 
>   Failed to connect to localhost port 8888: Connection refused
> ```
> 
> I would have to do `bbStart` first but that opens the web server.

when `bbStart` executed, biobtree lightweight server runs on the background independent from R
session for given outDir. And both web interface and command line queries are responded via this server so command line is also requires first `bbStart()`. User can have multiple datasets built inside different outDir directories but 1 server can be run at the same time.

> 
> * [ ]  So in understanding the connection to doing a search in the web ui for
>   `tpi1,vav_human,ENST00000297261` vs doing
>   `bbSearch("tpi1,vav_human,ENST00000297261")` .  It lists the top level.  I see
>   that if I add showURL it links to the different additional information pages
>   that I could also click on from the top level search page on the ui.  It might
>   also be nice to include the number of values that you see on the web server in
>   the command line
>   ie.
> 
> ```
> 431 Results for Ensembl ENSG00000111669 TPI1
> 300 Results for Transcript ENST00000297261     
> 269 Results for Uniprot P15498 VAV_HUMAN
> 9 Results for HGNC HGNC:12009 TPI1
> ```
I have added results counts now.
> 
> And it looks like attribute information from the web server result is also
> excluded in the command line interface?
> It would be nice to be as complete and consistent as possible to what is
> displayed from each.
> Update after man pages: Is this what the `lite=FALSE` tries to accomplish?
> 
> * [X]  Again I'm trying to compare what can be done in the web server to the
>   results in command line.  What would be the equivalent input into the webserve
>   to mimic the command line:
> 

yes `lite=FALSE` has this purpose. And everything seen in web interface should be accessed via command line. My idea is, web interface is for data explorations and command line is really if user decide to use in their R pipelines with only getting data they are interested and without deep understanding of the tool which is also my motivation for writing this package and providing an alternative to similar packages. Hope this make sense.

> ```
> bbMapping("AT5G3_HUMAN",'map(go)',attrs = "type")
> ```
> 
> I tried but kept getting no result.

This should really work I suspect it was because of the temp dir issue like the next error. Please try again and let me know.

> 
> * [X]  Typo for referencing your function in 3.1. `bbListDataset` does not exist
>   `bbListDatasets` is the function name.

Fixed.

> * [ ]  The mapping constructions seems complex. Not sure what the solution is but
>   just making note. This of course is subjective and will not affect the review.
> 

You mean the mapping query syntax right? Related to this I have now added 3 builtin functions for genome coordinates which I mentioned in the vignettes. Maybe I should provide  more examples for reducing this complexity? 

> **R/man**
> 
> * [X]  bbConfig-class doesn't seem like it should be exported. It is used
>   internally only and there are no access or modifier methods for it.  Either
>   expand and show use cases or don't export.
> 
I removed it.
> **man**
> _bbBuildData_
> 
> * [ ]  you mention the helper bbListGenomes maybe also list the helper
>   bbListDatasets

Again Hopefully new structure and flow in the vignettes is addressing this? I removed the genomes list from vignettes as well to reduce the complexity and point to the ensembl web pages is this ok?
and `bbBuildData` is renamed to `bbBuildCustomDB`
> 
> _bbEntryPage_
> 
> * [X]  Not clear what or how confiGured biobtree paging size is set or modified.
> 

This size is 200 and I mentioned this in the man page. I tested this with different numbers and 200 is the optimum number that I found especially while processing large datasets. Although this number can modified through the file `conf/application.param.json` in the outDir. I think users should not need to change this number. And also current built in databases are built with 200 so I would really keep the 200 as it is.

> _bbUseRemoteServe_
> 
> * [ ]  What is the point of this?  Not enough information in the man file and not
>   mentioned in the vignette on where or why this would be used. Its also not
>   exported so really doesn't need documentation. At the very least mark it as
>   `@internal`
> 

I removed it. It was essentially if a user wants to start `bbStart`  in some other computer and connect to that computer for querying but I guess it is confusing and not useful at this moment.

> _general_
> 
> * [X]  A lot of the examples if I try to run independent, they ERROR. Because
>   they start with bbStart:
> 
> ```
> > library(biobtreeR)
> > bbStart()
> trying URL 'https://github.com/tamerh/biobtree/releases/download/v1.2.0/biobtree_Linux_64bit.tar.gz'
> Content type 'application/octet-stream' length 10038409 bytes (9.6 MB)
> ==================================================
> downloaded 9.6 MB
> 
> biobtree
> Error in file(con, "rb") : cannot open the connection
> In addition: Warning message:
> In file(con, "rb") :
>   cannot open file '/tmp/RtmpMCPQzm/conf/source.dataset.json': No such file or directory
> > 
> ```
> 

I would suspect that these were because of the using automatic temp directory usage. Since now outDir must be explicitly set this error should not happen.

> **R code**
> 
> _general_
> 
> * [X]  You don't need paste0 in stop calls. Please remove. Example with message
>   that works the same way:
> 
> ```
> > vl = 3; 
> > message("a message ", vl) 
> a message 3
> ```
> 

Fixed.

> _buildData.R_
> 
> * [X]  Should there be a check when the directory actually does exist to make
>   sure you aren't overwriting or polluting by accident? You could create the path
>   if it doesn't exists; but stopping is okay too.
> 
> _config.R_
> 
Fixed. If there is a built database in the given directory It stops.

> * [X]  How often do the databases/info/releases/etc on github change?

For built in databases I am going to change every month by following  each uniprot and ensembl releases. But as I pointed if  built in database is not used tool is capable to get the the latest raw data directly from data providers mostly from their ftp locations and build the database. For github releases I am committed to fix bugs or issues as soon as possible also open to ideas/new features from users if the tool is used.

**Comment by tamerh** [comment] 2019-12-23 13:02
Hello @lshep 

I have released a new version. In addition to my previous comments with this release

- examples queries in the web interface added for builtin databases.
- queries are highlighted with colors in web interface
- new builtin database with `chembl` data added especially for drug related analysis. But I haven't included this in vignettes due to the size and 15 minutes build limitation but I am planning to add if this package accepted with your LONG build feature.

Cheers
Tamer

**Comment by lshep** [comment] 2019-12-24 13:51
Thank you.  Code changes look good.   A few minor points 

**General**
- [x] Excellent. I think this is much cleaner and the vignette flows a lot
better. 
- [ ] Clarification question:  How big is the database you currently use in your examples/vignette?  Is it the smallest? I get a an error because my own system actually didn't have enough room in the directory I was trying to write to so maybe it's worth mentioning the minimum requirement needed to run the vignette/examples?  (seems somewhere around 16G but maybe double check this?)

- [ ] Could you add a few lines in the vignette in the stop web serve to explain why it should be done and assumingly that stopping when finished is best practice? 

**README**

- [ ] Please add Bioconductor installation instructions too. 

Cheers,

**Comment by tamerh** [comment] 2019-12-24 16:58
This is awesome @lshep Many thanks for your review. Happy holidays.

**Comment by mtmorgan** [comment] 2020-01-06 16:21
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/tamerh.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biobtreeR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biobtreeR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-01-06 16:21 UTC
Labels: 3a. accepted, OK
