### ISSUE TITLE
Submit DegNorm R package to bioconductor

### ISSUE THREAD

**Issue by jipingw** [Bioconductor/Contributions#1491] opened 2020-04-27 16:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jipingw/DegNorm

Confirm the following by editing each check box to '[x]'

- [ X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X ] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by jipingw** [comment] 2020-04-28 14:21
Hi,

  Thanks for help. I am puzzled, because I don’t see errors/warnings from my computer when I ran R CMD check or R CMD BiocCheck (please see attachment). Could be because you report was based on an earlier upload? I made some changes after my initial upload to GitHub.
Thanks.

jiping

**Comment by mtmorgan** [comment] 2020-04-28 15:14
You show
```
* using R version 3.6.3 (2020-02-29)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)
```
but your package is added to the 'devel' branch of Bioconductor, which uses R 4.0.0 and
```
BiocManager::install(version = "devel")
BiocManager::valid()
```

**Comment by jipingw** [comment] 2020-04-28 15:52
Hi,

  Could you please give me guidance what I could change in this situation to make it work?
Thanks.

jiping

**Comment by mtmorgan** [comment] 2020-04-28 16:14
Consider responding via the github web interface, so there is not long quoted text in your response.

First. update your own system to R-4.0.0 and Bioc-devel, as indicated in the original comment.

Second, restrict the number of cores used in parallel computation to at most 2 -- the builder is a shared resource, and you cannot use all available resources.

**Comment by jipingw** [comment] 2020-04-28 21:42
Hi Martin,

  I updated R and Bioc-devel. I encountered strange errors, which I haven't seen before.
Do you have any clues what could be wrong? Thanks.

jiping


"
...
DegNorm core algorithm starts...
   DegNorm iteration 1 
Error in unserialize(socklist[[n]]) : error reading from connection
Calls: degnorm ... recvOneData -> recvOneData.SOCKcluster -> unserialize
....
"


Jipings-MacBook-Pro-2:Downloads jon$ pic ./DegNorm.Rcheck/00install.out 
.lf 1 ./DegNorm.Rcheck/00install.out
* installing *source* package ‘DegNorm’ ...
** using staged installation
** libs
make: Nothing to be done for `all'.
make: `symbols.rds' is up to date.
installing to /Users/jon/Downloads/DegNorm.Rcheck/00LOCK-DegNorm/00new/DegNorm/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
   ‘DegNorm.Rmd’ using ‘UTF-8’ 
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (DegNorm)
Jipings-MacBook-Pro-2:Downloads jon$ pic ./DegNorm.Rcheck/00check.log
.lf 1 ./DegNorm.Rcheck/00check.log
* using log directory ‘/Users/jon/Downloads/DegNorm.Rcheck’
* using R version 4.0.0 (2020-04-24)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘DegNorm/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘DegNorm’ version ‘1.0.1’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... WARNING
Subdirectory ‘DegNorm/src’ contains apparent object files/libraries
  DegNorm.so RcppExports.o degnormCPP.o
Object files/libraries should not be included in a source package.
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘DegNorm’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... ERROR
Running examples in ‘DegNorm-Ex.R’ failed
The error most likely occurred in:

> ### Name: degnorm
> ### Title: Main function to perform degradation normalization.
> ### Aliases: degnorm
> 
> ### ** Examples
> 
> ## coverage_res_chr21 is a \code{CoverageClass} object from DegNorm Package.
> data(coverage_res_chr21)
> res_DegNorm = degnorm(read_coverage = coverage_res_chr21[[1]],
+                     counts = coverage_res_chr21[[2]],
+                     iteration = 2,
+                     down_sampling = 1,
+                     grid_size=10,
+                     loop = 20)
Filtering out genes with low read counts (x<5)..
Initial estimation of count normalization factors...
Initial degradation normalization without base-line selection...
DegNorm core algorithm starts...
   DegNorm iteration 1 
Error in unserialize(socklist[[n]]) : error reading from connection
Calls: degnorm ... recvOneData -> recvOneData.SOCKcluster -> unserialize
Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ... NONE
  ‘DegNorm.Rmd’ using ‘UTF-8’... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR, 1 WARNING

**Comment by mtmorgan** [comment] 2020-04-28 22:00
there is some kind of instability from your use of parallel evaluation; maybe your 'workers' actually fail and R quits? You should revise your code to run in serial mode first and thoroughly debug, only then enabling parallel evaluation.

**Comment by jipingw** [comment] 2020-04-28 22:25
I have running this package many many times. Other uses also have used my package. We never had such issues. This issue only occurs after I update to R 4.00 today.

**Comment by mtmorgan** [comment] 2020-04-28 22:29
Great that your package has been used before! Since you're able to reproduce the error on your machine, you're in a great position to find out what the problem is!

**Comment by jipingw** [comment] 2020-04-28 22:44
I have no clue about the error. It's definitely related to the update of R. Some packages such as RcppArmadillo cannot be updated to the latest version for some reason (R prompted to install from the source for the latest version, but I always had errors).

Another error from BiocCheck is about subscription to the bioc-devel. I submitted application many times, but I never heard back from the bioc-devel team. Is there any special procedure to follow?

https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by mtmorgan** [comment] 2020-04-28 23:23
Investigate your package to see when, for instance in the example code where the error occurs, parallel evaluation is invoked -- it's your package, so you need to identify the problem!

Usually the 'I never heard back' explanation is because the response has been directed to your spam mailbox. Have you checked there?

**Comment by jipingw** [comment] 2020-04-28 23:29
For the bioc-devel, indeed I found it in the spam folder. That's embarrassing! Sorry for bothering.

 But I still need to figure out why after updating to R4.0.0, the package has such strange errors. Thanks for help.

**Comment by jipingw** [comment] 2020-04-28 23:40
If I R CMD build, and I got the following errors. This error seems to be related to Rcpp or RcppArmadillo. I cannot update the RcppArmadillo for some reason. 

** libs
/usr/local/clang8/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/S4Vectors/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/IRanges/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /usr/local/clang8/bin/../include/c++/v1/cmath:305:
/usr/local/clang8/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘DegNorm’

**Comment by mtmorgan** [comment] 2020-04-29 01:31
It looks like you are on macOS. Install the macOS binary from https://cran.r-project.org/bin/macosx/ and choose NOT to install from source -- only install binary versions of packages.

**Comment by jipingw** [comment] 2020-04-29 11:41
Thanks for your help again. I did the following:

1. I re-installed R binary version. Run R CMD check. I still got the same errors as follows.

> ### Name: degnorm
> ### Title: Main function to perform degradation normalization.
> ### Aliases: degnorm
> 
> ### ** Examples
> 
> ## coverage_res_chr21 is a \code{CoverageClass} object from DegNorm Package.
> data(coverage_res_chr21)
> res_DegNorm = degnorm(read_coverage = coverage_res_chr21[[1]],
                   counts = coverage_res_chr21[[2]],
                    iteration = 2,
                 down_sampling = 1,                    grid_size=10,
                    loop = 20,
                    cores=2)
Filtering out genes with low read counts (x<5)..
Initial estimation of count normalization factors...
Initial degradation normalization without base-line selection...
DegNorm core algorithm starts...
   DegNorm iteration 1 
Error in unserialize(socklist[[n]]) : error reading from connection
Calls: degnorm ... recvOneData -> recvOneData.SOCKcluster -> unserialize
Execution halted
* 

2. I commented out the example in degnorm function, and R CMD check got no errors.
3. However when I run R CMD build, the same errors appear (below). I suspect it might be due to unsuccessful installation related to Rcpp or RcppArmadillo. For example the latest RcppArmadillo is RcppArmadillo 0.9.870.2.0. But only source package is available for mac. Installation always failed when I was prompted to update it from the source.

      -----------------------------------
* installing *source* package ‘DegNorm’ ...
** using staged installation
** libs
/usr/local/clang8/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/S4Vectors/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/IRanges/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /usr/local/clang8/bin/../include/c++/v1/cmath:305:
/usr/local/clang8/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘DegNorm’

**Comment by jipingw** [comment] 2020-04-29 18:54
I updated a few files. I added optional arguments "cores" in a few function. I made a couple minor change of description file.

Could biocondutor team give another test for R CMD test? I cannot get through this. But I suspect my update of R-4.0 encountered some issues in the RCPP and RcppArmadillo.
I had this package running for more than half a year and never had such errors with R3.6.3. I want to make sure whether my update of R4.0 had problem or indeed I have problems in my package. 

thanks.

**Comment by jipingw** [comment] 2020-04-29 21:13
update: I was able to find the c++ compiler problem based on the thread. After R update, I have to manually edit the ./R/Makvers file as suggested in the following. I am keeping test. thanks.

https://stackoverflow.com/questions/58313047/cannot-compile-r-packages-with-c-code-after-updating-to-macos-catalina

**Comment by jipingw** [comment] 2020-04-29 23:35
After fix this error, both R CMD check and R CMD BiocCheck work fine now. One last error from BiocCheck which I cannot figure out why.

---
BiocCheck Error:
...
  This is a software package
    * ERROR: VignetteBuilder listed in DESCRIPTION but not found as
      VignetteEngine in any vignettes:
        rmarkdown
        formatR
...

Here are relevant lines my Description file:

....
Packaged: 2019-12-08 00:10:02 UTC; Ji-Ping Wang
Suggests:knitr,rmarkdown,formatR
VignetteBuilder: knitr,rmarkdown,formatR
...

Here is the header for vignette file:
...

---
title: "DegNorm R package"
author: "Bin Xiong, Ji-Ping Wang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{DegNorm}
    %\VignetteEngine{knitr::rmarkdown::formatR}
    %\VignetteEncoding{UTF-8}
...

I specified \VignetteEngine{knitr::rmarkdown::formatR}, but BiocCheck still complains.

Any clues?

**Comment by Kayla-Morrell** [comment] 2020-04-30 01:28
@jipingw - You should remove `formatR` from the vignette engine line, so it should read:

```
%\VignetteEngine{knitr::rmarkdown}
```

**Comment by jipingw** [comment] 2020-04-30 08:49
This was what I had in the first place. If I only had this line in my vignette. I have the following error:

* Checking vignette directory...
    This is a software package
    * ERROR: VignetteBuilder listed in DESCRIPTION but not found as
      VignetteEngine in any vignettes:
        rmarkdown
        formatR
* Checking library calls...

The error is still there.

**Comment by lshep** [comment] 2020-04-30 12:44
Remove formatR in the Description file from the section VignetteBuilder

**Comment by jipingw** [comment] 2020-04-30 13:02
Thanks for help. I removed formatR from VignetteBuilder section. But it still does not work.


My Description file:
...
Suggests:knitr,rmarkdown,formatR
VignetteBuilder: knitr,rmarkdown
...

My vignette file:

...
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{DegNorm}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
...

error:

* Checking vignette directory...
    This is a software package
    * ERROR: VignetteBuilder listed in DESCRIPTION but not found as
      VignetteEngine in any vignettes:
        rmarkdown

**Comment by Kayla-Morrell** [comment] 2020-04-30 13:05
The 'VignetteBuilder' field in the DESCRIPTION file should just contain knitr.

**Comment by jipingw** [comment] 2020-04-30 13:14
yah!, not error/warnings anymore from both R CMD check and R CMD BiocCheck!
Thanks for help!

**Comment by Kayla-Morrell** [comment] 2020-04-30 15:55
Great! The next step would be to do a version bump, commit, and push. This will trigger another build report on the single package builder.

**Comment by jipingw** [comment] 2020-04-30 16:04
Currently all the files on github are up to date. Do I still need to do anything? I saw there is a pending bump request for my package.

**Comment by Kayla-Morrell** [comment] 2020-04-30 16:10
Yes, you need to include a version bump of the DESCRIPTION file in your commit, e.g., from Version: 0.99.0 to Version: 0.99.1.

**Comment by jipingw** [comment] 2020-04-30 21:51
I did it. I hope I did it successfully. Please give it a check. thanks.

**Comment by Kayla-Morrell** [comment] 2020-05-01 12:58
I see the version bump but no build report was created. Did you set up your web hook as stated in one of the initial comments (see it in the link below)? 

https://github.com/Bioconductor/Contributions/issues/1491#issuecomment-620616037

**Comment by jipingw** [comment] 2020-05-01 13:02
I thought I did in the very first place. Do I need to re-do the wbehook thing? I can take a look.

**Comment by jipingw** [comment] 2020-05-01 13:05
I tried to add webhook again, but I got error message as follows:

There was an error setting up your hook: Hook already exists on this repository

**Comment by Kayla-Morrell** [comment] 2020-05-01 13:14
Is 'http://issues.bioconductor.org/ ' listed under webhooks? If it is then just make sure it's set up properly. Click on the link. A 'Recent Deliveries' area should contain a single request. Click on the Request and view the "Response" tab. There should be a green `200` response code, with body `ping received, Bioconductor/Contributions webhook ok`. If that all looks okay try another version bump and we will see if the hook worked.

**Comment by jipingw** [comment] 2020-05-01 13:30
yes, it's listed under webhooks. I clicked it, but I see many recent deliveries:



10e24270-8b2e-11ea-88a2-b33c9f3915ea …
2020-04-30 17:00:55
0c018bd0-8b2e-11ea-9729-860955e2e83b …
2020-04-30 17:00:47
07427730-8b2e-11ea-8a45-c7751d4e064a …
2020-04-30 17:00:39
8b0d7c60-8b2c-11ea-8446-0854490f761c …
2020-04-30 16:50:01
94ff76a8-8ae4-11ea-90dc-208626268b9b …
2020-04-30 08:14:54
aecec076-8ac5-11ea-824e-2ca2daee8dd3 …
2020-04-30 04:33:43
9e4e7c6e-8ac5-11ea-98c0-db7eb78770ee …
2020-04-30 04:33:15
3d820824-8ac5-11ea-8ab1-1d2fc306b4f3 …
2020-04-30 04:30:33
ead68d98-8ac4-11ea-9353-e46a0d33fe3e …
2020-04-30 04:28:14
e4c67196-8ac1-11ea-803e-657b162e388b …
2020-04-30 04:06:35
b36a78ea-8ac1-11ea-8410-7435520aed9f …
2020-04-30 04:05:13
5d0b74fe-8ac1-11ea-8fe7-4a5020b75823 …
2020-04-30 04:02:48
452e593c-8ac1-11ea-928a-3cbdc681de24 …
2020-04-30 04:02:08
0c51037a-8a4a-11ea-8852-3410e1abf8e1 …
2020-04-29 13:48:42
e198b718-8a49-11ea-8fbc-ffc319c225f9 …
2020-04-29 13:47:31
be6cf45c-8a49-11ea-8310-8a0637a9030f …
2020-04-29 13:46:32
96e4ef00-8956-11ea-9b25-cfbabf47f88b

**Comment by Kayla-Morrell** [comment] 2020-05-01 13:53
Alright, try deleting the webhook and set it up again. Everything seems to be working fine on our end as other issues are posting build reports with no problems.

**Comment by jipingw** [comment] 2020-05-01 13:57
I reset it. thanks. please let me know if it does not work.

**Comment by lshep** [comment] 2020-05-01 13:58
Can you try to do another version bump as well to see if it triggers?

**Comment by Kayla-Morrell** [comment] 2020-05-01 13:59
You'll have to do another version bump to trigger the build.

**Comment by jipingw** [comment] 2020-05-01 14:01
ok.

**Comment by jipingw** [comment] 2020-05-01 17:46
I saw one platform complained about comparison unsigned integer with signed integer in RcppArmadillo but other platforms didn't complain. Computationally no errors. From my mac compiler, also no error. Is there a quick solution? I cannot test it in my computer as I don't see anything coming out wrong. Thanks.

~~~~~~

degnormCPP.cpp: In function 'arma::uvec bin_drop(int, int, arma::rowvec)':
degnormCPP.cpp:27:18: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
   if (drop_bin(0)==bin_number-1){
       ~~~~~~~~~~~^~~~~~~~~~~~~~
degnormCPP.cpp: In function 'Rcpp::List optiNMFCPP(arma::mat, arma::vec, int)':
degnormCPP.cpp:167:40: warning: comparison of integer expressions of different signedness: 'arma::uword' {aka 'unsigned int'} and 'int' [-Wsign-compare]
     if(filter.size()<50||nonZero.size()<num_sample){
                          ~~~~~~~~~~~~~~^~~~~~~~~~~
degnormCPP.cpp: In function 'Rcpp::List optiNMFCPP_grid(arma::mat, arma::vec, int, int)':
degnormCPP.cpp:315:42: warning: comparison of integer expressions of different signedness: 'arma::uword' {aka 'unsigned int'} and 'int' [-Wsign-compare]
       if(filter.size()<50||nonZero.size()<num_sample){
                            ~~~~~~~~~~~~~~^~~~~~~~~~~

**Comment by jipingw** [comment] 2020-05-02 17:17
There is a warning as follows. Should I remove the vignette html from the inst/doc? and only vignette markdown file in vignette folder?

arning: inst/doc file
    DegNorm.html
  ignored as vignettes have been rebuilt.

**Comment by jipingw** [comment] 2020-05-04 16:14
could you please let me know what is the next step?

**Comment by Kayla-Morrell** [comment] 2020-05-04 16:19
As per our Package Submission and Package Guidelines that you should have read through upon submission, I will be preparing an initial review of your package. I will comment back here with any changes that should be made or any suggestions I may have before accepting your package. This process can take any where from 2 to 5 weeks in total.

**Comment by Kayla-Morrell** [comment] 2020-05-13 15:23
Hello @jipingw,

Thank you for submitting to _Bioconductor_. Please see the initial review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: The 'Title:' field should be brief but descriptive, not just the 
name of the package.

- [ ] SUGGESTION: It is encouraged to include the 'BugReports:' field with a 
relevant link to GitHub for reporting Issues.

- [ ] REQUIRED: Do 'stats' and 'data.table' need to be listed under depends? It 
seems that there is only one function that is imported from each of the packages 
in the NAMESPACE file. 'Depends:' should only list packages that provide 
essential functionality for users of the package.

## NAMESPACE

- [ ] SUGGESTION: I would remove the blank lines at the end of the file, for 
neatness sake.

- [ ] SUGGESTION: Generally `importFrom()` is encouraged over importing an 
entire package, however if there are many functions from a single package, 
`import()` is okay. I would reduce the number of `import()` used if possible.

## NEWS

- [ ] REQUIRED: The NEWS file should be competed and formated correctly. Please 
see our information on NEWS files,
https://bioconductor.org/developers/package-guidelines/#news.

## Vignettes

- [ ] REQUIRED: Add an "Installation" section that demonstrates to the user how 
to download and load the package from Bioconductor. The code should look similar 
to the following and should include `eval = FALSE`:

```
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DegNorm")
```

- [ ] SUGGESTION: We strongly encourage including table of contents.

- [ ] REQUIRED: Code sections should not include `eval = FALSE` (except where 
data is saved). It is essential that the vignette embed executed R code, even 
when plotting.

- [ ] REQUIRED: The last section of the vignette should be "Session Info" and 
should include `SessionInfo()`.

## Man pages

- [ ] REQUIRED: Usage of dontrun{}/donttest{} found in man page examples. This 
should not be present for man pages that document exported functions. Found in 
the following files:
	- degnorm.Rd

## inst/script/

- [ ] REQUIRED: There needs to be documentation on the 'inst/extdata' files in 
an 'inst/script' directory. The script(s) in this directory can vary. A related 
script must be present in this directory documenting very clearly how the data 
was generated. It should include source urls and any important information 
regarding filtering or processing. It can be executable code, sudo code, or a 
text description. A user should be able to download the data and be able to 
roughly reproduce the files or objects that are present as data.

## Unit tests

- [ ] SUGGESTION: Consider adding unit tests. We strongly encourage them. See 
http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

Best,
Kayla

**Comment by jipingw** [comment] 2020-05-20 18:39
## DESCRIPTION

- REQUIRED: The 'Title:' field should be brief but descriptive, not just the name of the package.

**Reply: changed to “DegNorm: degradation normalization for RNA-seq data”**

- SUGGESTION: It is encouraged to include the 'BugReports:' field with a relevant link to GitHub for reporting Issues.

**Reply:  BugReports: https://github.com/jipingw/DegNorm/issues added**

-  REQUIRED: Do 'stats' and 'data.table' need to be listed under depends? Itseems that there is only one function that is imported from each of the packagesin the NAMESPACE file. 'Depends:' should only list packages that provide essential functionality for users of the package.

**Reply: moved data.table and stats to Imports secton**


## NAMESPACE

- SUGGESTION: I would remove the blank lines at the end of the file, for neatness sake.

**Reply: removed**

-  SUGGESTION: Generally importFrom() is encouraged over importing an entire package, however if there are many functions from a single package, import() is okay. I would reduce the number of import() used if possible.

**Reply: most import function changed to importFrom except for “methods”.**


##NEWS

- REQUIRED: The NEWS file should be competed and formated correctly. Please see our information on NEWS files, https://bioconductor.org/developers/package-guidelines/#news.

**Reply: corrected.**


##Vignettes

- REQUIRED: Add an "Installation" section that demonstrates to the user how to download and load the package from Bioconductor. The code should look similar to the following and should include eval = FALSE:
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DegNorm")

**Reply: added.**

- SUGGESTION: We strongly encourage including table of contents.

**Reply: added.**

- REQUIRED: Code sections should not include eval = FALSE (except where data is saved). It is essential that the vignette embed executed R code, even when plotting.

**Reply: changed. But it takes much more time to run R CMD check since the core functions is computationally intensive**

- REQUIRED: The last section of the vignette should be "Session Info" and should include SessionInfo().

**Reply: done.**


##Man pages

- REQUIRED: Usage of dontrun{}/donttest{} found in man page examples. This should not be present for man pages that document exported functions. Found in the following files: degnorm.Rd

**reply: again, this is to avoid long time of R CMD check. I have made the change.
inst/script/**

- REQUIRED: There needs to be documentation on the 'inst/extdata' files in an 'inst/script' directory. The script(s) in this directory can vary. A related script must be present in this directory documenting very clearly how the data was generated. It should include source urls and any important information regarding filtering or processing. It can be executable code, sudo code, or a
text description. A user should be able to download the data and be able to roughly reproduce the files or objects that are present as data.

**Reply: done. All data files under inst/extdata were explained how they were generated.**


##Unit tests

- SUGGESTION: Consider adding unit tests. We strongly encourage them. See

http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

**Reply: I didn’t address this. I wish to skip it.**

**Comment by jipingw** [comment] 2020-05-27 12:59
Hi Kayla,

  I just want to follow up that in the current version, I have addressed most of your comments from the review. My detailed replies can be found above. thanks.

jiping

**Comment by Kayla-Morrell** [comment] 2020-05-29 16:55
@jipingw - Thank you for making the necessary changes, I have finished reviewing them and have nothing more that needs to be addressed. With that, I am more than happy to accept that package.

Best,
Kayla

**Comment by jipingw** [comment] 2020-05-29 16:58
Thanks so much for all your help. I am so grateful for everything your Bioconductor people has done for me and other researchers.

**Comment by mtmorgan** [comment] 2020-06-01 21:56
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jipingw.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("DegNorm")`. The package 'landing page' will be created at

https://bioconductor.org/packages/DegNorm

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-06-01 21:56 UTC
Labels: 3a. accepted, OK
