### ISSUE TITLE
NanoStringNCTools

### ISSUE THREAD

**Issue by rvitancol** [Bioconductor/Contributions#1815] opened 2020-12-16 02:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/Nanostring-Biostats/NanoStringNCTools

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by rvitancol** [comment] 2020-12-18 01:50
AdditionalPackage: https://github.com/Nanostring-Biostats/GeomxTools

**Comment by NicoleEO** [comment] 2020-12-18 22:59
AdditionalPackage: https://github.com/Nanostring-Biostats/GeomxTools.git

**Comment by rvitancol** [comment] 2020-12-21 18:37
Hi @nturaga, can we ask for the check.log from the R CMD check for the Windows build for GeomxTools? The error in the build report does not give us a clue where the error happens and this does not appear in our local R CMD CHECK. 
This is the build error report excerpt:
`< * checking whether package 'GeomxTools' can be installed ... ERROR>`
`<Installation failed.>`
`<See>` `<'C:/Users/pkgbuild/packagebuilder/workers/jobs/1815/982d3bc731fbefd4ccd559af0a71a8322404d2da/GeomxTools.Rcheck/00install.out' for details.>`
`<* DONE>`

`<Status: 1 ERROR>`
`<See>`
  `<'C:/Users/pkgbuild/packagebuilder/workers/jobs/1815/982d3bc731fbefd4ccd559af0a71a8322404d2da/GeomxTools.Rcheck/00check.log'>`
`<for details.>`

**Comment by rvitancol** [comment] 2020-12-21 21:31
Notes on warnings and error related to R version:  Tested these packages on the latest version of R, but we also require that they work on an older version (Depends: R (>= 3.6) for a report tool we use internally.  The packages have undergone internal V&V as part of the report that we use internally.
Notes on warnings related to using "<-" in documentation:  Replacement methods with "<-" causes an error in html since these are illegal symbols in file names on windows. Can we set the check to ignore these?

**Comment by nturaga** [comment] 2020-12-23 08:10
> Notes on warnings and error related to R version: Tested these packages on the latest version of R, but we also require that they work on an older version (Depends: R (>= 3.6) for a report tool we use internally. The packages have undergone internal V&V as part of the report that we use internally.
> Notes on warnings related to using "<-" in documentation: Replacement methods with "<-" causes an error in html since these are illegal symbols in file names on windows. Can we set the check to ignore these?

Yes, you can ignore these.

**Comment by nturaga** [comment] 2020-12-23 14:18
# NanoStringNCTools review

## R CMD build

ok

## R CMD check

ok

## DESCRIPTION

ok

## NAMESPACE

- being done manually, instead of by roxygen2. Please make sure
  functions/clases exported are all needed.
  
## Build report warnings

- WARNING: It seems you want to keep using R 3.6, and it's generating
  a warning. So ignore this one. 

- NOTE: These are the NOTES i'm particular about, please address
  these. The rest of them are also solvable for the most part (at
  least the ones you see on the linux builder)
	
-     * NOTE: Avoid sapply(); use vapply()

-     * NOTE: Consider adding runnable examples to the following man
      pages which document exported objects:
      geom_beeswarm_interactive.Rd, SignatureSet.Rd

      * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.

- The windows build machine issue can be addressed by @hpages better.

## R

- There is a NOTE about indentation too(2 spaces vs 4 spaces), please
  check http://bioconductor.org/developers/how-to/coding-style/ .

- Remove commented out lines of code. 

- I'm not sure why your zzz.R has the 'testPackage' function called
  inside of it. This usually isn't the way zzz.R is used. 
  
  ## tests
  
  - ok
  
  ## man
  
-  ok

## vignette

- ok

**Comment by hpages** [comment] 2020-12-30 22:32
Hi @nturaga , @rvitancol ,

The error on Windows seems to have occurred during `R CMD INSTALL`. Unfortunately the SBP doesn't show the output of this command so we don't have any details about this error. FWIW I can run `R CMD INSTALL` on NanoStringNCTools without any problem on riesling1 (another Windows builder, similar to tokay2). So I'd say let's just ignore the error reported by the SPB. We'll see how it goes the next time the SPB tries to build/check the package which should happen the next time its version gets bumped.

H.

**Comment by NicoleEO** [comment] 2021-01-06 22:53
@nturaga I believe our packages are ready to go.
We have addressed the notes you highlighted above with the exception of one sapply that is used in a function that extends sapply to our class for users. 
I did receive the below error in the last build, which seems to be an issue unrelated to our package.
![image](https://user-images.githubusercontent.com/20404635/103827582-300fed80-502e-11eb-953e-28bdc5f1558d.png)
In regards to our Additional Package, GeomxTools, it failed the build at the last check only because of R version requirements (3.6) so this one should also be ready.

**Comment by nturaga** [comment] 2021-01-22 05:29
Hi @NicoleEO ,

- There is still one `sapply()` you have to fix in:        NanoStringRccSet-utils.R (line 75, column 5). I'm otherwise ok with the changes you've made.

- I'm actually not sure how I can accept this package as there is no build tarball produced on the Linux machine. @lshep or @hpages can answer maybe?

**Comment by lshep** [comment] 2021-01-22 11:55
@nturaga  why do you say there is no build tarball produced for Linux? The package only has a check warning for Linux. The package didn't build for Mac and as we explained multiple times this is likely do to Mac binaries not being produced on CRAN yet for Rdevel and should be ignored. This is confirmed by searching for the package not available https://cran.r-project.org/web/packages/ggiraph/index.html .  Please ignore the Mac error and accept based on the other two build reports.

**Comment by NicoleEO** [comment] 2021-01-22 17:27
@nturaga the last sapply is used to extend sapply to our class for users. Would it be possible to pass this one by as it is purposely kept as sapply to allow the user flexibility with unknown data types they may apply on?

**Comment by nturaga** [comment] 2021-01-22 17:37
That's fine. We suggest `vapply()` to specify "return" type rather than input type. Whatever you are writing with sapply, you can write with vapply.

**Comment by NicoleEO** [comment] 2021-01-22 18:22
@nturaga thanks for accepting. Does this also automatically apply to our additional package as well?

**Comment by nturaga** [comment] 2021-01-22 21:07
Yes.

**Comment by mtmorgan** [comment] 2021-01-23 22:33
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rvitancol.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("NanoStringNCTools")`. The package 'landing page' will be created at

https://bioconductor.org/packages/NanoStringNCTools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2021-01-23 22:33
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/rvitancol.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GeomxTools")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GeomxTools

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2021-01-23 22:33 UTC
Labels: 3a. accepted, ERROR, WARNINGS
