### ISSUE TITLE
treekoR

### ISSUE THREAD

**Issue by adam2o1o** [Bioconductor/Contributions#1970] opened 2021-03-16 04:46 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/adam2o1o/treekoR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by vjcitn** [comment] 2021-03-25 10:43
```* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... WARNING
Output for data("COVIDSampleData", package = "treekoR"):
  Warning: namespace ‘CATALYST’ is not available and has been replaced
```

That occurred on my Linux machine.  Do you need to put CATALYST in Suggests?

**Comment by adam2o1o** [comment] 2021-03-26 05:17
I've updated the Suggests, does that help the issue?

**Comment by vjcitn** [comment] 2021-03-31 10:28
Looks like you did not bump version number.

**Comment by vjcitn** [comment] 2021-03-31 10:31
Also you now have two Suggests: fields in your DESCRIPTION.  That's an error.  Lovely vignette.  I think we are close.

**Comment by vjcitn** [comment] 2021-03-31 10:41
Here are results of BiocCheck that should be addressed:
```
 [2] "The Description field in the DESCRIPTION is made up by less than 3\nsentences. Please consider expanding this field, and structure it as a\nfull paragraph"                        
 [3] " Avoid sapply(); use vapply()"                                                                                                                                                     
 [4] " Avoid 1:...; use seq_len() or seq_along()"                                                                                                                                        
 [5] "Recommended function length <= 50 lines."                                                                                                                                          
 [6] "Consider adding a NEWS file, so your package news will be included in Bioconductor release announcements."                                                                         
 [7] "Consider adding unit tests. We strongly encourage them. See\n  http://bioconductor.org/developers/how-to/unitTesting-guidelines/."                                                 
 [8] "Consider shorter lines; 106 lines (7%) are > 80 characters long." 
```
I would say the most important consideration is the unit test suggestion.  Some of the code here is pretty intricate, with double brackets, and one wonders whether vectorization could improve conciseness and reliability.
```
 for (i in (ncol(cutree_list_df)-1):1) {
    # Get parent nodes with more than two children
    unique_nodes <- names(table(cutree_list_df[,i])[which(table(cutree_list_df[,i]) >= 2)])
    # For each parent node, we combine the corresponding children nodes
    for (node in unique_nodes) {
      base_nodes_combo <- base_nodes[which(as.vector(cutree_list_df[,i])== node)]

      if (sum(grepl(paste(base_nodes_combo, collapse="|"), current_nodes)) > 1) {
        nodes_to_combine <- current_nodes[grepl(paste(base_nodes_combo, collapse="|"), current_nodes)]

        current_nodes <- c(current_nodes[!current_nodes %in% nodes_to_combine],
                           paste0("(", paste(nodes_to_combine, collapse=","), ")")
        )
      }
    }
  }
```
nested loops and which() and `x = c(x[!f %in% g], x)` ... these are code patterns that can throw curve balls with intensive use on sketchy data.  It looks like it works and maybe you have good guard rails in the curvy areas.  But even if you do, articulating the exact expected behavior for good data in unit tests will make this a much better package.

**Comment by vjcitn** [comment] 2021-03-31 10:44
Factoring out a task like "get parent nodes with more than two children" into a function with well-defined input, output, and exception handling, would be a good step.  The unit test becomes the task of calling the function with good input, verifying that it gets the right answer, calling it with bad input, verifying that you identify the exception and respond gracefully.

**Comment by vjcitn** [comment] 2021-04-07 23:43
Are you still working on this package?

**Comment by adam2o1o** [comment] 2021-04-09 01:24
Hi Vince, thanks for your feedback so far- I'm still working on the package and get back to you soon after incorporating your comments.

**Comment by vjcitn** [comment] 2021-04-16 12:26
OK.  Just watch the deadlines.  This package is very nice and I hope you can get it into the release.

**Comment by adam2o1o** [comment] 2021-04-22 09:18
Hi Vince, 
Just wondering about the necessity of reducing the function lengths <= 50  and having shorter lines < 80 characters long. Are these necessary to address? If so, how are the lines of the function calculated (does it include the arguments)? 
I'm still going through and adding unit tests.

I also came across the following error when trying to push the changes to upstream:

remote: FATAL: W refs/heads/main packages/treekoR adam2o1o DENIED by fallthru
remote: error: hook declined to update refs/heads/main
To git.bioconductor.org:packages/treekoR.git
! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'git@git.bioconductor.org:packages/treekoR.git
'

Would you have an idea what is happening here? 
Thanks

**Comment by vjcitn** [comment] 2021-04-22 10:13
``` the necessity of reducing the function lengths <= 50 and having shorter lines < 80 characters long. Are these necessary to address? If so, how are the lines of the function calculated (does it include the arguments)?```
The concern here is maintainability.  There are also associations between loosely formatted code and inefficiency.  Here
are some flagged lines:
```
 # Add dimensions for bars
  cluster_freq_df <- cluster_freq_df %>%
    dplyr::mutate(y = tree_df$y[match(cluster_freq_df$cluster, tree_df$label)],
                  ymin = tree_df$y[match(cluster_freq_df$cluster, tree_df$label)] - bar_width,
                  ymax = tree_df$y[match(cluster_freq_df$cluster, tree_df$label)] + bar_width,
```
What's going on here, is that a match and list extraction is done over and over again, contributing to line lengths.  A "bug" in one line is present in all of them.  Now you could just introduce line breaks and no one would be the wiser.  But this length flag should be regarded as an opportunity to improve code in ways that are not just aesthetic.

The hook problem concerns git credentials.  Maybe you are working at a machine that is different from the one you started out with.  Maybe you changed ssh key.  Please see http://bioconductor.org/developers/how-to/git/faq/ and if the issue is not addressed there, email bioc-devel@r-project.org with full details.

**Comment by vjcitn** [comment] 2021-04-22 10:16
As for necessities of revision, I'd say line lengths are much lower priority than unit tests.  I see none.  The presence of unit tests reduces the pressure to format code maintainably.  But both are important.

**Comment by adam2o1o** [comment] 2021-04-23 16:31
Hi Vince,

> I would say the most important consideration is the unit test suggestion. Some of the code here is pretty intricate, with double brackets, and one wonders whether vectorization could improve conciseness and reliability.

I have added some unit tests around the function `hopachToPhylo` that you had quoted earlier in order to make it more robust. The code is very intricate with the nested loops and c(,), I agree. However I believe it works as the inputs are relatively consistent and defined from running the previous function. 

> The concern here is maintainability. There are also associations between loosely formatted code and inefficiency. Here
> are some flagged lines:
> 
>  # Add dimensions for bars
>   cluster_freq_df <- cluster_freq_df %>%
>     dplyr::mutate(y = tree_df$y[match(cluster_freq_df$cluster, tree_df$label)],
>                   ymin = tree_df$y[match(cluster_freq_df$cluster, tree_df$label)] - bar_width,
>                   ymax = tree_df$y[match(cluster_freq_df$cluster, tree_df$label)] + bar_width,
> What's going on here, is that a match and list extraction is done over and over again, contributing to line lengths. A "bug" in one line is present in all of them. Now you could just introduce line breaks and no one would be the wiser. But this length flag should be regarded as an opportunity to improve code in ways that are not just aesthetic.

I've gone through the code and addressed the areas where there is repeated code and redundant calculations to reduce some of the line lengths.

If you could revise again and let me know any further issues, that would be greatly appreciated. 

Thanks,
Adam

**Comment by vjcitn** [comment] 2021-05-03 03:59
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/adam2o1o.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("treekoR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/treekoR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-05-03 03:59 UTC
Labels: 3a. accepted, OK
