### ISSUE TITLE
sparseMatrixStats

### ISSUE THREAD

**Issue by const-ae** [Bioconductor/Contributions#1465] opened 2020-04-03 11:20 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/const-ae/sparseMatrixStats

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment] 2020-04-03 17:06
Shouldn't this (and MatrixGenerics) go into CRAN?

**Comment by const-ae** [comment] 2020-04-03 17:16
I don't necessarily disagree ;)

I guess the case for sparseMatrixStats being on BioConductor is that MatrixGenerics was submitted here and it makes sense to have them together. More generally, a lot of functionality around S4 is here on BioConductor (like S4Vectors), so it felt appropriate for me to submit both packages here as well.
But you are right, that the packages could be of interest for the whole R community :)

@PeteHaitch and @hpages, what would you say about this?

**Comment by PeteHaitch** [comment] 2020-04-03 22:26
> Shouldn't this (and MatrixGenerics) go into CRAN?

I also don't necessarily disagree :)
There's been a fair bit of bike-shedding and going around in circles on this package and its extensions (including very much myself in this; see https://github.com/Bioconductor/MatrixGenerics/issues/2#issue-319268113).
It's good to have an actual implementation of it - I hope this can help clarify where it should live.

**Comment by lawremi** [comment] 2020-04-03 22:31
Thanks for introducing me to the term "bike-shedding" and the law of triviality.

**Comment by PeteHaitch** [comment] 2020-04-04 02:59
@lawremi I didn't mean that to dismiss your suggestion or concerns, which are well-placed. This really reflects my frustrations with myself for not being able to nail down the implementation

**Comment by mtmorgan** [comment] 2020-04-06 15:40
@hpages has advocated for (initial) submission to Bioconductor, where it is much easier to mature packages, pointing to rhdf5 as an example

**Comment by lshep** [comment] 2020-04-06 17:26
I'll do some behinds the scenes stuff too to have this be able to build without waiting for MartrixGenerics to be accepted and without submitting under the other issue.  hand tight and I'll kick off a new build when I have it set up so I can move forward with the review

**Comment by lawremi** [comment] 2020-04-06 17:33
I recognize that Bioconductor wins in terms of developer convenience, but our community should be more proactive about sharing our general solutions and distributing through CRAN. Otherwise, only we will benefit.

**Comment by lshep** [comment] 2020-04-06 18:11
It is our understanding that R doesn't support C++14 on Windows yet. Please update  to C++11

**Comment by const-ae** [comment] 2020-04-07 08:26
Hi Lori, 
thanks for kicking of another build and "do some behinds the scenes stuff". That's highly appreciated :)

> It is our understanding that R doesn't support C++14 on Windows yet

Oh, that is unfortunate. I thought that R 4.0 also meant Rtools 40 and thus finally a modern compiler on windows.
If not, I will see that I how I can rewrite the internals to avoid the C++14 features.

**Comment by PeteHaitch** [comment] 2020-04-07 12:28
> I thought that R 4.0 also meant Rtools 40 and thus finally a modern compiler on windows.

It seems like its still being decided; see https://stat.ethz.ch/pipermail/r-devel/2020-April/079253.html

**Comment by lshep** [comment] 2020-04-07 12:31
We are ready to go with the Rtools40 whenever CRAN decides to switch over but as far as we are aware it is still being discussed.   @hpages Do you know if this is truly the case when we switch to the new toolchain?

**Comment by hpages** [comment] 2020-04-07 15:59
Yep, we should be ready to switch (we have set up [builds](https://bioconductor.org/checkResults/3.11/bioc-testing-LATEST/) with the new toolchain for a small subset of packages).

As for whether or not R core is going to switch in time for the R 4.0.0 release, I don't know more about this than what's being currently discussed on the R-devel mailing list. The thing is that we can't switch before they switch, which means that for now the SPB still has to use the old toolchain. So no C++14 features yet.

So here you go: all the cards are on the table and I let you guys decide the strategy for getting sparseMatrixStats into Bioconductor in time for the release.

**Comment by lshep** [comment] 2020-04-13 15:30
We can wait to see when/if R 4.0.0 gives the official word that they will use the new toolchain.  Until then it is up to you if you decide to modify the code to work in the meantime or temporarily mark as unsupported on windows until the switch happens.   

The package is generally well written and I only have the few minor comments: 

**General**

- [ ] are duplicate copies of the license and readme necessary?

**README**

- [ ] Include Bioconductor installation instructions

**vignette**

- [ ] If the `set.seed` is required for users to reproduce the output in the vignette then this should be shown.


I won't be able to accept this package until MatrixGenerics gets accepted first.

**Comment by const-ae** [comment] 2020-04-14 11:47
I have adapted the C++ code in a way that the C++14 features are not used anymore and it should now build on Windows with Rtools 35.

I have also added the Bioconductor installation instructions to the README and made sure the `set.seed(1)` is visible in the vignette. Thank you for the comments.

>  are duplicate copies of the license and readme necessary?

I have deleted the LICENSE.md file as it was not necessary. The two README files, I would say, are necessary, because the .Rmd file generates the .md file that is then displayed on GitHub.

----------------

However, the `BiocCheck()` is now failing for my package, but I don't understand why:

```
* Checking package NEWS...
Error in file.path(pkgdir, pkg, c("inst", "inst", "inst", ".", "."), c("NEWS.Rd",  : 
  object 'pkg' not found
Calls: <Anonymous> -> BiocCheck -> checkNEWS -> file.path
Execution halted
```

I don't remember that is was an issue before. Is it related to the fact that `MatrixGenerics` is not yet accepted?

**Comment by const-ae** [comment] 2020-04-14 11:52
Ah I see the NEWS error was already fixed with https://github.com/Bioconductor/BiocCheck/commit/27ea5e275a887446d61869832ec924222f5dbce3.
I will just wait and bump the version tomorrow to see if the fix has propagated until then :)

**Comment by lshep** [comment] 2020-04-14 13:27
The NEWS file ERROR is on our end. We have a fix implemented in linux and there will be a fix on windows by later this afternoon. I will kick off a manual build so there is at least an accurate linux build. it should post shortly.

**Comment by lshep** [comment] 2020-04-15 13:28
Great as soon as MatrixGenerics is accepted I will accept this package.  Cheers

**Comment by PeteHaitch** [comment] 2020-04-16 02:23
@const-ae I know you already changed the code, but it looks like the migration to rtools40 is happening: https://twitter.com/opencpu/status/1250452381403398149

**Comment by const-ae** [comment] 2020-04-16 07:17
Hi, thanks for the links :)
In that case, I am wondering if I should just revert commit https://github.com/const-ae/sparseMatrixStats/commit/3c0ea53696c85a856dd6179fb559f8812c9481cc.

@Lori, the MatrixGenerics package has been accepted tonight (https://github.com/Bioconductor/Contributions/issues/1448#issuecomment-614401206) :)

**Comment by lshep** [comment] 2020-04-16 13:53
Yes we updated the R and tool chain on windows last night.  Up to you if you want to revert code.  accepting the package regardless.

**Comment by mtmorgan** [comment] 2020-04-16 15:45
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/const-ae.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("sparseMatrixStats")`. The package 'landing page' will be created at

https://bioconductor.org/packages/sparseMatrixStats

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-16 15:45 UTC
Labels: 3a. accepted, WARNINGS
