### ISSUE TITLE
DMCHMM

### ISSUE THREAD

**Issue by shokoohi** [Bioconductor/Contributions#430] opened 2017-07-27 01:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/shokoohi/DMCHMM

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [x ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x ] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by shokoohi** [comment] 2017-07-27 12:23
Hello,

The issue is solved now. 

Thank you,

Farhad Shokoohi,
Assistant Professor
Concordia University

**Comment by shokoohi** [comment] 2017-08-07 18:59
Hello,

I haven’t received any news regarding my submitted package “DMCHMM”.
The issue is solved and I sent an email long time ago. 
Would you please update me on stage of reviewing my package?

Thank you,
Farhad Shokoohi
Assistant Professor, 
Concordia University

**Comment by nturaga** [comment] 2017-08-07 19:57
@shokoohi Please correct the Error's on your package [build report](http://bioconductor.org/spb_reports/DMCHMM_buildreport_20170727042104.html)
. I will review your package soon.

**Comment by shokoohi** [comment] 2017-08-07 20:52
Hello,

I have already subscribed to bio-devel mailing list after I received the report mentioning the following error:

ERROR: Maintainer must subscribe to the bioc-devel mailing list. Subscribe here: https://stat.ethz.c

**Comment by nturaga** [comment] 2017-08-07 20:55
You have to bump the version in the DESCRIPTION file and commit. Check maintainer name as well.

https://github.com/shokoohi/DMCHMM/blob/master/DESCRIPTION

**Comment by shokoohi** [comment] 2017-08-08 01:13
Hello,

The warnings are not related to my package. 
It happens because of other packages that I cannot solve. 
If you have any solution let me know to fix it. 

Thanks,

**Comment by shokoohi** [comment] 2017-08-08 14:55
I have no idea why your build is not working. 
Everything is fine on my computer.

**Comment by dvantwisk** [comment] 2017-08-11 18:29
Hello,

@nturaga has been busy this week completing a large project, so I will now be reviewing this package.  We'll try to have a review in to you by mid next week.

**Comment by dvantwisk** [comment] 2017-08-15 14:45
We've reviewed your package!  Please address the following issues and message us back when you are finished:

General:
- [REQUIRED] Add DMCHMM.Rproj to `.gitignore`.
- [REQUIRED] Indentation in R files varies greatly and in R files that contain
little to no identation, the code is very difficult to read.  In these files,
use a formatting tool like the `formatR` package to improve readability.  Keep
in mind that using this tool will change the line numbers which we are using to
locate the issues with your code.  For this reason, use the `formatR` package 
after you correct the issues below so you know where to locate the problems.

DESCRIPTION:
- [CONSIDER] L20: Use the package `BiocParallel` instead of `parallel`.
- [CONSIDER] LICENSE: Pick specific GPL version.

NAMESPACE:
- Looks great!

R/AllClasses.R
- [CONSIDER] Consider placing parameters inside individual `roxygen2` headers
instead of placing them all in one block.

R/AllGenerics.R

R/DMCHMM-package.R

R/cBSDMCs-method.R
- [CONSIDER] L1-18: May be better to create private cBSDMCs constructor from
cBSDMCs's `setClass()` function, and use a single private constructor to add
custom input to the private function.  This code block doesn't need to call
`new()`.
```{r}
.cBSDMCs <- setClass("cBSDMCs's", ....)
```

R/cBSData-method.R
- Same as above.

R/combine-method.R

R/data.R
- [CONSIDER] Provide a better description of what the data file contains.
For example, explain more about what it is and how to data is organized.

R/findDMCs.R
- [REQUIRED] L13: Improper use of `paste()` in `stop()` function. What is there 
now will create a character vector with the length of `names(colData(object))`
elements that repeat the initial statement.  Replace with the following the the
desired effect:
```{r}
`stop("The variables ....", paste(names(colData(object)), collpase=", "), ".")
```
- [REQUIRED] L52-59: The `sapply()`'s here are used multiple times and there is
no need to run this command multiple time.  Declare a variable once and reuse
it.
- [REQUIRED] L171-173: Replace inefficient copy pattern with:
```{r}
pval <- vapply(totres3, function(elt) elt$p.val, numeric(1))
```
- [REQUIRED] L183-187: Replace inefficient copy and append pattern with apply's.

- [REQUIRED] L243-248: Similar issue as L171-173.

R/manhattanDMCs-method.R
- [REQUIRED] L77-81:  Code can be vectorized as follows:
```{r}
udCHR <- unique(d$CHR)
i <- seq_along(udCHR)
idx <- match(d$CHR, udCHR)
d[idx, ]$index <- i[idx]
```
- L104-110: [CONSIDER] Similar issue to L77-81.  Try to vectorize it.
- [REQUIRED] L206-211: Replace with:
```{r}
topSNPs <- lapply(unique(topHits$CHR), function(i) {
		chrSNPs <- topHits[topHits$CHR == i, ]
	})
topSNPs <- do.call(rbind, topSNPs)	
```

R/methHMEM-method.R
- [REQUIRED] L41: Vectorize code:
```{r}
Pm <- t(exp(Pm)/rowSums(Pm))
```
- [REQUIRED] L107-108:
```{r}
new.Pm[j, ] <- rowSums(Wijk.Estep[, j, ])/sum(Wijk.Estep[, j,])
```
- [REQUIRED] L165-167: Replace with vectorized code:
```{r}
# I am assuming that all vectors have the same length, here:
mlike <- sum(nw * dbinom(Yv, nv, X.estimate, log=TRUE))
# If they don't have the same length
vals <- seq_len(nPos)
mlike <- sum(nw[vals] * dbinom(Yv[vals], nv[vals], X.estimate[vals], log=TRUE))
```
- [REQUIRED] L304-311: Use applys to remove inefficient copy and append pattern.

R/methHMMCMC-method.R
- [REQUIRED] L87-90: Vectorize like mentioned above in L165-167.
- [REQUIRED] L117-145: All code can be vectorized here.
- [CONSIDER] L159-165: use `aggregate()` here.
- [REQUIRED] L306-318: Vectorize code to avoid expensive copy like mentioned
above in L296-303.

R/methLevel-method.R

R/methReads-method.R

R/methStates-method.R

R/qqDMCs-method.R

R/readBismark-method.R
- [CONSIDER] L9: Use `seq_along()` here instead of `1:length(files)` to avoid
unexpected case where `1:0` results in a vector of `1 0`.
- [CONSIDER] L42: Use `seq_long()` as opposed to `seq(along=....)`.

R/totalReads-method.R

R/writeBED-method.R
- [CONSIDER] Writing to a BED file appears to have already been implemented in
Bioconductor in `rtrackalyers` in the function `asBED()`.  It would be 
better to reuse this function by writing a shorted adapter wrapper that will
allow your object to be written using the function instead of writing new code
reimplement it just for your objects.

R/zzz.R
- [CONSIDER] utils::packageDescription parsed multiple times.  Pull it out of a
variable instead of reading it multiple times.
- [CONSIDER] L6: no paste needed here.


tests
- [CONSIDER] Consider adding tests using the `testthat` package.

vignettes

**Comment by shokoohi** [comment] 2017-08-28 12:50
Hello, 
Most of the comments that I received are implemented.
Here are the things that are implemented and those that are not implemented.

General:

[done] Add DMCHMM.Rproj to .gitignore.
[done] Indentation in R files varies greatly and in R files that contain
little to no identation, the code is very difficult to read. In these files,
use a formatting tool like the formatR package to improve readability. Keep
in mind that using this tool will change the line numbers which we are using to
locate the issues with your code. For this reason, use the formatR package
after you correct the issues below so you know where to locate the problems.
DESCRIPTION:

[done] L20: Use the package BiocParallel instead of parallel. 
[done] LICENSE: Pick specific GPL version.
NAMESPACE:

Looks great!
R/AllClasses.R

[not done] Consider placing parameters inside individual roxygen2 headers
instead of placing them all in one block.
R/AllGenerics.R

R/DMCHMM-package.R

R/cBSDMCs-method.R

[Couldn't figure out what the comment meant] L1-18: May be better to create private cBSDMCs constructor from
cBSDMCs's setClass() function, and use a single private constructor to add
custom input to the private function. This code block doesn't need to call
new().
.cBSDMCs <- setClass("cBSDMCs's", ....)
R/cBSData-method.R

Same as above.
R/combine-method.R

R/data.R

[done] Provide a better description of what the data file contains.
For example, explain more about what it is and how to data is organized.
R/findDMCs.R

[done] L13: Improper use of paste() in stop() function. What is there
now will create a character vector with the length of names(colData(object))
elements that repeat the initial statement. Replace with the following the the
desired effect:
`stop("The variables ....", paste(names(colData(object)), collpase=", "), ".")
[REQUIRED] L52-59: The sapply()'s here are used multiple times and there is
no need to run this command multiple time. Declare a variable once and reuse
it.
[done] L171-173: Replace inefficient copy pattern with:
pval <- vapply(totres3, function(elt) elt$p.val, numeric(1))
[REQUIRED] L183-187: Replace inefficient copy and append pattern with apply's.

[done] L243-248: Similar issue as L171-173.

R/manhattanDMCs-method.R

[done] L77-81: Code can be vectorized as follows:
udCHR <- unique(d$CHR)
i <- seq_along(udCHR)
idx <- match(d$CHR, udCHR)
d[idx, ]$index <- i[idx]
L104-110: [done] Similar issue to L77-81. Try to vectorize it.
[REQUIRED] L206-211: Replace with:
topSNPs <- lapply(unique(topHits$CHR), function(i) {
		chrSNPs <- topHits[topHits$CHR == i, ]
	})
topSNPs <- do.call(rbind, topSNPs)	
R/methHMEM-method.R

[done] L41: Vectorize code:
Pm <- t(exp(Pm)/rowSums(Pm))
[done] L107-108:
new.Pm[j, ] <- rowSums(Wijk.Estep[, j, ])/sum(Wijk.Estep[, j,])
[done] L165-167: Replace with vectorized code:
# I am assuming that all vectors have the same length, here:
mlike <- sum(nw * dbinom(Yv, nv, X.estimate, log=TRUE))
# If they don't have the same length
vals <- seq_len(nPos)
mlike <- sum(nw[vals] * dbinom(Yv[vals], nv[vals], X.estimate[vals], log=TRUE))
[done] L304-311: Use applys to remove inefficient copy and append pattern.
R/methHMMCMC-method.R

[done ] L87-90: Vectorize like mentioned above in L165-167.
[not done since the code is recursive in some lines] L117-145: All code can be vectorized here.
[didn't understand] L159-165: use aggregate() here.
[done] L306-318: Vectorize code to avoid expensive copy like mentioned
above in L296-303.
R/methLevel-method.R

R/methReads-method.R

R/methStates-method.R

R/qqDMCs-method.R

R/readBismark-method.R

[done] L9: Use seq_along() here instead of 1:length(files) to avoid
unexpected case where 1:0 results in a vector of 1 0.
[done] L42: Use seq_long() as opposed to seq(along=....).
R/totalReads-method.R

R/writeBED-method.R

[not done] Writing to a BED file appears to have already been implemented in
Bioconductor in rtrackalyers in the function asBED(). It would be
better to reuse this function by writing a shorted adapter wrapper that will
allow your object to be written using the function instead of writing new code
reimplement it just for your objects.
R/zzz.R

[done] utils::packageDescription parsed multiple times. Pull it out of a
variable instead of reading it multiple times.
[done] L6: no paste needed here.
tests

[done] Consider adding tests using the testthat package.
vignettes

**Comment by shokoohi** [comment] 2017-08-29 12:50
Hello
The package is ready for another review.
Would you please let me know the status?
Thank you.

**Comment by dvantwisk** [comment] 2017-08-29 14:59
Here is our second review, please address these issues and comment back when you are finished.

GENERAL
- [Consider] delete commented out code blocks if they are no longer going to be used.

DESCRIPTION
- [REQUIRED] remove `parallel` from Depends if `BiocParallel` is being used.

R/findDMCs.R
- [REQUIRED] L290: remove all variables but `qval` from declaration. 
- [CONSIDER] L308-324: Inefficient copy and append pattern with `namesPairDMC` and
`namesPairDIR` variables. Replace with applies or vectorized code, if able.

**Comment by shokoohi** [comment] 2017-08-29 20:38
Hello
the multicoreWorkers() in BioParallel detecets less core than detectCores() in parallel package. 
For instance, on my Mac, the total cores are 8, but the multicoreWorkers() detects 6. 
How can I fix this problem if I want to remove parallel package from my package?
Best,

**Comment by shokoohi** [comment] 2017-08-29 23:21
Hello,

I don't understand the error. 
How can I fix it?

Best

**Comment by shokoohi** [comment] 2017-08-29 23:21
Hello 
Following comments are applied:

GENERAL

[Done] delete commented out code blocks if they are no longer going to be used.
DESCRIPTION

[Done] remove parallel from Depends if BiocParallel is being used.
R/findDMCs.R

[Done] L290: remove all variables but qval from declaration.
[Done] L308-324: Inefficient copy and append pattern with namesPairDMC and
namesPairDIR variables. Replace with applies or vectorized code, if able.

Thank you

**Comment by mtmorgan** [comment] 2017-08-30 14:04
`multicoreWorkers()` is friendly, returning by design fewer cores than available. See `?multicoreWorkers`

```
     'multicoreWorkers()'. On windows, the number of multicore workers
     is always 1. Otherwise, the default is the maximum of 1 and
     'parallel::detectCores() - 2'; machines with 3 or fewer cores are
     assigned a single worker. The option 'mc.cores' can be used to
     specify an arbitrary number of workers, e.g.,
     'options(mc.cores=4L)'; the _Bioconductor_ build system enforces a
     maximum of 4 workers.
```

**Comment by mtmorgan** [comment] 2017-08-30 14:16
Windows doesn't support 'fork' processes, so in effect has just 1 multicore worker; your vignette invokes with 2 workers, which is greater than 1.

For this reason, on Windows the default parallel environment is `SnowParam()`, and BiocParallel arranges for this default automatically -- check out `registered()` on different platforms; for Linux the highest priority back-end is `MulticoreParam()`, but for Windows it's `SnowParam()`

As a package developer you could re-create this special handling, but from the vignette the recommend practice is to simply not provide a BPPARAM argument to BiocParallel -- it'll pick up the param that has been `registered()` by default, or by the user (who might have important reasons for choosing, e.g., not to use all 128 cores on their University cluster).

**Comment by shokoohi** [comment] 2017-08-31 17:26
The package is ready for further evaluation. 
Thanks

**Comment by dvantwisk** [comment] 2017-09-06 18:18
Sorry for the delay!  Things look fine now!

**Comment by mtmorgan** [comment] 2017-09-09 19:46
The master branch of your GitHub repository has been added to
Bioconductor's git repository.

To use this repository, we need an 'ssh' key to associate with your github
user name. Please

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build
(check-out from git at about 6 pm Eastern; build completion around 2pm
Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main
landing page are consistent with the addition of your
package). Once the package builds successfully, you package will be
available for download in the 'Devel' version of Bioconductor using
`biocLite("YOUR_PACKAGE_NAME")`. The package 'landing page' will
be created at

https://bioconductor.org/packages/YOUR_PACKAGE_NAME

If you have any questions, please contact the bioc-devel mailing
list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue
will not be monitored further.

**Closed by mtmorgan** 2017-09-09 19:46 UTC
Labels: 3a. accepted, OK
