### ISSUE TITLE
metaboliteIDmapping AnnotationHub package

### ISSUE THREAD

**Issue by boll3** [Bioconductor/Contributions#1497] opened 2020-05-12 07:06 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/yigbt/metaboliteIDmapping

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-05-12 08:27
This looks like an ExperimentHub package.

A very brief vignette ('This package provides ... Scripts used to process the data are available in system.file(package="...", ...)') would be great.

I guess the packages listed in Imports: are used to process the data. Since these are not used in the code in the R/ directory (there is none!) they should be in the Suggests: field instead.

Did you consider section 2.2.4 of http://bioconductor.org/packages/devel/bioc/vignettes/ExperimentHub/inst/doc/CreateAnExperimentHubPackage.html#building-the-data-experiment-package , providing an 'accessor' that retrieves the resource?

**Comment by boll3** [comment] 2020-05-12 11:35
@mtmorgan 
I already discussed the 'location' issue with Lori Sheperd, since I was a bit confused whether to upload the mapping table as AnnotationHub or ExperimentHub package. We both felt that it is more suited as AnnotationHub package. 
What we do is, we collect annotated metabolite IDs from four different databases and combine them into an even larger mapping table. There is no processing of the data, merely a re-organization and joining.

Whats your opinion on that?

Is it also possible to write such an 'accessor' for an AnnotationHub package?

**Comment by mtmorgan** [comment] 2020-05-13 19:06
Sorry, I didn't mean to confuse the previous discussion of 'location'.

I guess I meant to say 'this is not a software package' but still it would be good to have a vignette, etc.

Please point the users of your package to the scripts you've included, that I presume document in a reproducible way (good!) the 're-organization and joining' that you do.

Yes, annotation packages can have accessors (they are just regular R package with specific biocViews terms and standard conventions (limited R code being one of the conventions). I'd encourage you to write and document accessors in the standard way.

**Comment by boll3** [comment] 2020-05-14 13:08
Apparently, the installation of the package failed.
In the .onload function, I try to download the data from the annotationHub resource.
But the snapshot date is Apr 27, but the data is uploaded May 11.


Error: package or namespace load failed for metaboliteIDmapping:
 .onLoad failed in loadNamespace() for 'metaboliteIDmapping', details:
  call: NULL
  error: AH79817 added after current Hub snapshot date.
  added: 2020-05-11
  snapshote date: 2020-04-27


How can I get access to the data from within the .onload function?
It worked in my environment where I used development version of the AnnotationHub.

**Comment by mtmorgan** [comment] 2020-05-14 15:45
Thanks; I think the single package builder is still using an older R / Bioc (waiting for the dust to settle from the release) and that AH resources are only available in the version they were added. @lshep or @Kayla-Morrell can verify.

I'll start a review of the package as-is, running the commands

```
R-4.0.0 CMD build metaboliteIDmapping
R-4.0.0 CMD check metaboliteIDmapping_*gz
R-4.0.0 CMD BiocCheck metaboliteIDmapping_*gz
```

if you are confident this will work?

**Comment by lshep** [comment] 2020-05-14 15:46
Yes this is true.

**Comment by boll3** [comment] 2020-05-14 16:42
I just pushed the package again, since I encountered an error in the DESCRIPTION file.
I have run the command you mentioned on my system, and it worked quite well.

Hope it will also work on your system...

**Comment by boll3** [comment] 2020-05-19 10:09
Is there anything I can do to solve these issues now?

It's the same problem with the snapshot date of the AnnotationHub package.

**Comment by lshep** [comment] 2020-05-19 12:07
We are working on moving the builders to the devel builders this week and next.  In the meantime your review is aware and can test locally.

**Comment by mtmorgan** [comment] 2020-05-30 23:35
- this change is required for the vignette to be built with the package

    ```
    metaboliteIDmapping master$ git diff
    diff --git a/DESCRIPTION b/DESCRIPTION
    index e7261f9..f00dba0 100644
    --- a/DESCRIPTION
    +++ b/DESCRIPTION
    @@ -24,8 +24,10 @@ Suggests:
         XML,
         readxl,
         stringr,
    -    utils
    +    utils,
    +    knitr
     biocViews: AnnotationHub, CustomDBSchema, FunctionalAnnotation
    +VignetteBuilder: knitr
     URL: https://github.com/yigbt/metaboliteIDmapping
     Encoding: UTF-8
     LazyData: true
     ```

**Comment by boll3** [comment] 2020-06-02 09:54
@mtmorgan 
I've run the same checks on my computer without errors, especially regarding the timeout for usage checks (there is also no error on your windows test system):
* checking Rd \usage sections ... ERROR
TIMEOUT: R CMD check exceeded 15 mins

In the BiocCheck there is also an error when downloading the data from AnnotationHub. But again, I do not encounter these problems on my system.
I just emptied the cache from AnnotationHub an run all tests again without any error.

Do you have any advice?

As for the Mac testing system, I do not have such system and thus I am not able to reproduce the error. However, I am wondering why 'R CMD check' is not able to install the package at all but 
'R CMD BiocCheck' runs without error...



Logs of my checks:

## R CMD CHECK

$ R CMD check metaboliteIDmapping_0.99.3.tar.gz 
* using log directory ‘/home/canzler/git-canzler/code/2020_multiGSEA/metaboliteIDmapping.Rcheck’
* using R version 4.0.0 (2020-04-24)
* using platform: x86_64-conda_cos6-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘metaboliteIDmapping/DESCRIPTION’ ... OK
* this is package ‘metaboliteIDmapping’ version ‘0.99.3’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘metaboliteIDmapping’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘metaboliteIDmapping.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: OK


# R CMD BiocCheck 

R CMD BiocCheck metaboliteIDmapping_0.99.3.tar.gz 
This is BiocCheck version 1.24.0. BiocCheck is a work in progress.
Output and severity of issues may change. Installing package...
snapshotDate(): 2020-05-23
downloading 1 resources
retrieving 1 resource
loading from cache
* Checking Package Dependencies...
* Checking if other packages can import this one...
* Checking to see if we understand object initialization...
* Checking for deprecated package usage...
* Checking for remote package usage...
* Checking version number...
* Checking for version number mismatch...
* Checking version number validity...
    Package version 0.99.3; pre-release
* Checking R Version dependency...
* Checking package size...
* Checking individual file sizes...
* Checking biocViews...
* Checking that biocViews are present...
* Checking package type based on biocViews...
    AnnotationData
* Checking for non-trivial biocViews...
* Checking that biocViews come from the same category...
* Checking biocViews validity...
* Checking for recommended biocViews...
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking if DESCRIPTION is well formatted...
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches directory/tarball name...
* Checking for Version field...
* Checking for valid maintainer...
* Checking DESCRIPTION/NAMESPACE consistency...
    This is not a software package, skipping vignette checks...
* Checking library calls...
* Checking for library/require of metaboliteIDmapping...
* Checking coding practice...
* Checking parsed R code in R directory, examples, vignettes...
* Checking function lengths.....
* Checking man page documentation...
* Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
* Checking unit tests...
    * NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
* Checking skip_on_bioc() in tests...
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 12 lines (4%) are > 80 characters
      long.
    First 6 lines:
      R/metabolitesMapping.R:32 #'     \item{ChEBI}{Chemical Entities of Biol...
      vignettes/metaboliteIDmapping.Rmd:6   affiliation: Helmholtz-Centre for...
      vignettes/metaboliteIDmapping.Rmd:24 [Comptox Chemical Dashboard](https...
      vignettes/metaboliteIDmapping.Rmd:26 [CAS Registry numbers](https://www...
      vignettes/metaboliteIDmapping.Rmd:28 [Chemical Entities of Biological I...
      vignettes/metaboliteIDmapping.Rmd:37 A brief description of the utilize...
    * NOTE: Consider multiples of 4 spaces for line indents, 9
      lines(3%) are not.
    First 6 lines:
      vignettes/metaboliteIDmapping.Rmd:6   affiliation: Helmholtz-Centre for...
      vignettes/metaboliteIDmapping.Rmd:10   BiocStyle::html_document:
      vignettes/metaboliteIDmapping.Rmd:12   BiocStyle::pdf_document: default
      vignettes/metaboliteIDmapping.Rmd:14   %\VignetteEncoding{UTF-8}
      vignettes/metaboliteIDmapping.Rmd:15   %\VignetteEngine{knitr::rmarkdown}
      vignettes/metaboliteIDmapping.Rmd:16   %\VignetteIndexEntry{metaboliteI...
    See http://bioconductor.org/developers/how-to/coding-style/
    See FormatR package:
      https://cran.r-project.org/web/packages/formatR/index.html
* Checking if package already exists in CRAN...
* Checking for bioc-devel mailing list subscription...
    * NOTE: Cannot determine whether maintainer is subscribed to the
      bioc-devel mailing list (requires admin credentials).  Subscribe
      here: https://stat.ethz.ch/mailman/listinfo/bioc-devel
* Checking for support site registration...
    Maintainer is registered at support site.


Summary:
ERROR count: 0
WARNING count: 0
NOTE count: 5

**Comment by mtmorgan** [comment] 2020-06-12 19:32
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/boll3.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("metaboliteIDmapping")`. The package 'landing page' will be created at

https://bioconductor.org/packages/metaboliteIDmapping

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-06-12 19:32 UTC
Labels: 3a. accepted

**Comment by lshep** [comment] 2021-05-19 11:11
I assume this is locally on your own system?

**Comment by ag1805x** [comment] 2021-05-19 11:12
> I assume this is locally on your own system?

Yes

**Comment by lshep** [comment] 2021-05-19 11:13
Did you try following the advise in the vignette on corrupt cache as indicated: 
https://bioconductor.org/packages/release/bioc/vignettes/AnnotationHub/inst/doc/TroubleshootingTheCache.html#index-file

**Comment by ag1805x** [comment] 2021-05-19 12:14
> Did you try following the advise in the vignette on corrupt cache as indicated:
> https://bioconductor.org/packages/release/bioc/vignettes/AnnotationHub/inst/doc/TroubleshootingTheCache.html#index-file

Thanks. Solved!
