### ISSUE TITLE
gscreend package

### ISSUE THREAD

**Issue by imkeller** [Bioconductor/Contributions#1228] opened 2019-09-04 16:34 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/imkeller/gscreend

Confirm the following by editing each check box to '[x]'

- [X ] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X ] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X ] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X ] The 'devel' branch for new packages and features.
- [X ] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment] 2019-09-30 16:21
# Initial review

Please correct the NOTES in your build report,

- [ ] Required 

```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
      Found in files:
        GeneRanking.R (line 33, column 20)
        GeneRanking.R (line 61, column 5)
    * NOTE: Avoid 1:...; use seq_len() or seq_along()
      Found in files:
        GeneRanking.R (line 12, column 37)
        GeneRanking.R (line 12, column 47)
        GeneRanking.R (line 17, column 24)
        QualityControl.R (line 40, column 22)
        sgrnaRanking.R (line 78, column 15)
        sgrnaRanking.R (line 105, column 15)
```

- [ ] Consider 

```
* Checking package NEWS...
    * NOTE: Consider adding a NEWS file, so your package news will be
      included in Bioconductor release announcements.
* Checking unit tests...
    * NOTE: Consider adding unit tests. We strongly encourage them. See
      http://bioconductor.org/developers/how-to/unitTesting-guidelines/.
    * NOTE: Consider shorter lines; 17 lines (2%) are > 80 characters
      long.
    First 6 lines:
      R/DataInput.R:31         message("Creating PoolScreenExp object from a ...
      R/DataInput.R:34         message("Error: input data is not of the supor...
      man/PoolScreenExp-class.Rd:15 \item{\code{sgRNAData}}{A SummarizedExper...
      man/PoolScreenExp-class.Rd:17 \item{\code{FittingIntervals}}{A vector d...
      man/PoolScreenExp-class.Rd:20 \item{\code{LFCModelParameters}}{A vector...
      man/PoolScreenExp-class.Rd:23 \item{\code{GeneData}}{SummarizedExperime...
    * NOTE: Consider multiples of 4 spaces for line indents, 45
      lines(4%) are not.
    First 6 lines:
      R/core.R:41                           quant1 = 0.1,
      R/core.R:42                           quant2 = 0.9,
      R/core.R:43                           alphacutoff = 0.05,
      R/core.R:44                           n_cores=1) {
      R/core.R:51                           quant1, quant2)
      R/GeneRanking.R:82                      replicate(n_repl,
    See http://bioconductor.org/developers/how-to/coding-style/
    See FormatR package:
      https://cran.r-project.org/web/packages/formatR/index.html
```

**Comment by imkeller** [comment] 2019-10-01 15:20
Dear @nturaga ,
Thank you for the initial review. I corrected the NOTES in the build report. Based on what I saw for in the reviews of other packages I also replaced 'parallel' by 'BiocParallel' package.

**Comment by Kayla-Morrell** [comment] 2019-10-08 18:58
Hello @imkeller,

Thank you for submitting to _Bioconductor_. Please see the review of the package below. The required changes must be made while the suggested changes do not have to be but we strongly encourage them. Comment back here with updates that have been made and when the package is ready for a re-review.

## DESCRIPTION

- [ ] REQUIRED: 'LazyData' should be set to false. If this field is true it can 
slow down the loading of packages.

- [ ] SUGGESTION: It is encouraged to include the field 'BugReports:' with the 
relevant link to GitHub for reporting Issues. 

## NAMESPACE

- [ ] REQUIRED: The PoolScreenExp class should be exported.

- [ ] SUGGESTION: Generally 'importFrom()' is encouraged over importing an 
entire package, however if there are many functions from a single package, 
'import()' is okay.

## Vignettes

- [ ] REQUIRED: Lines 14-17, I would move this code into the 'Installation' 
section. I will explain further in a later requirement point.

- [ ] REQUIRED: Lines 34-44, in order for these lines to become an ordered list 
there needs to be a blank line between line 33 and line 34. Without that, the 
list just looks like a paragraph of text.

- [ ] REQUIRED: The 'Installation' section should demonstrate to the user how 
to download the package from _Bioconductor_. I would include the following code 
with eval = FALSE, 

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("gscreend")
```

Then I would include the R code chunk from the first vignette requirement above 
(lines 14-17). This will then show the user how to install and load the package 
using _Bioconductor_.

- [ ] SUGGESTION: When talking about specific functions you can put \` \` around 
the function to indicate it as R code. So in line 121, plotModelParameters() 
could become `plotModelParameters()`. It helps to differentiate it from regular 
text.

- [ ] REQUIRED: Line 138, to print out the whole table is just a waste of space 
in the vignette. I would save this function call to a variable and then just 
print the head of the variable. This will give the user an idea of what the data 
looks like without having to print out the whole table. Something like...

```{r}
res <- ResultsTable(pse_an, direction = "negative")
head(res)
``` 

- [ ] REQUIRED: The last section of the vignette should be 'Session Info' and 
should include `sessionInfo()`.

## Man pages

- [ ] SUGGESTION: Only functions that are exported need to have man pages. The 
functions that do have man pages but aren't exported can get the tag 
`@keywords internal` added to them so that the function is removed from the 
documentation index.

## inst/script/

- [ ] REQUIRED: Since there is data included in 'inst/extdata/' there should be 
a related script in this directory documenting how the data was generated. It 
should include source urls and any important information regarding filtering 
or processing. It can be executable code, sudo code, or a text description. A 
user should be able to download and roughly reproduce the file or object that 
is present as data.

## Unit tests

- [ ] SUGGESTION: Consider adding unit test. We strongly encourage them. See
http://bioconductor.org/developers/how-to/unitTesting-guidelines/.

## R code

Overall your code is very well written and organized!

- [ ] REQUIRED: Avoid the use of direct slot access with `@` or `slot()`. 
Accessor methods should be created and utilized instead.

Best,
Kayla

**Comment by imkeller** [comment] 2019-10-10 15:27
Hi @Kayla-Morrell ,

Thank you for the review and your suggestions. I implemented all of them in the new version that I just pushed to github. Below this message I add a detailed response to your comments. The package is ready for a re-review.

Many thanks, Katharina

## DESCRIPTION

REQUIRED: 'LazyData' should be set to false. If this field is true it can
slow down the loading of packages.
      _**Done**_

SUGGESTION: It is encouraged to include the field 'BugReports:' with the
relevant link to GitHub for reporting Issues.
      _**Done**_

## NAMESPACE

REQUIRED: The PoolScreenExp class should be exported.
     _**Done**_

SUGGESTION: Generally 'importFrom()' is encouraged over importing an
entire package, however if there are many functions from a single package,
'import()' is okay.
      _**Done**_

## Vignettes

REQUIRED: Lines 14-17, I would move this code into the 'Installation'
section. I will explain further in a later requirement point.
	_**Done**_

REQUIRED: Lines 34-44, in order for these lines to become an ordered list
there needs to be a blank line between line 33 and line 34. Without that, the
list just looks like a paragraph of text.
      _**Done**_

REQUIRED: The 'Installation' section should demonstrate to the user how
to download the package from Bioconductor. I would include the following code
with eval = FALSE,
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("gscreend")
Then I would include the R code chunk from the first vignette requirement above
(lines 14-17). This will then show the user how to install and load the package
using Bioconductor.
      _**Done**_

SUGGESTION: When talking about specific functions you can put ` ` around
the function to indicate it as R code. So in line 121, plotModelParameters()
could become ``plotModelParameters()``. It helps to differentiate it from regular
text.
      _**Done**_

REQUIRED: Line 138, to print out the whole table is just a waste of space
in the vignette. I would save this function call to a variable and then just
print the head of the variable. This will give the user an idea of what the data
looks like without having to print out the whole table. Something like...
res <- ResultsTable(pse_an, direction = "negative")
head(res)
      _**Done**_

REQUIRED: The last section of the vignette should be 'Session Info' and
should include sessionInfo(). 
      _**Done**_

## Man pages

SUGGESTION: Only functions that are exported need to have man pages. The
functions that do have man pages but aren't exported can get the tag
@keywords internal added to them so that the function is removed from the
documentation index. 
**_I added @keywords internal to the function description (e.g. ``assignGeneData()``) and ran ``devtools::document()``. I am not sure, whether the result I get is the intended one, because the corresponding entries in man/ are still there._**


## inst/script/

REQUIRED: Since there is data included in 'inst/extdata/' there should be
a related script in this directory documenting how the data was generated. It
should include source urls and any important information regarding filtering
or processing. It can be executable code, sudo code, or a text description. A
user should be able to download and roughly reproduce the file or object that
is present as data.
 _**Done**_


## Unit tests

SUGGESTION: Consider adding unit test. We strongly encourage them. See
http://bioconductor.org/developers/how-to/unitTesting-guidelines/. 
_**I added unit tests for some of the functions, especially related to data input and quality control.**_
    
## R code

Overall your code is very well written and organized!
_**Thanks :)**_

REQUIRED: Avoid the use of direct slot access with @ or slot().
Accessor methods should be created and utilized instead.
_**I removed the slot access via @ from most of the code, except the accessor methods.**_

**Comment by Kayla-Morrell** [comment] 2019-10-15 17:53
@imkeller - Thank you for making the changes, everything looks good and I'm happy to accept the package!

Best,
Kayla

**Comment by mtmorgan** [comment] 2019-10-15 21:44
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/imkeller.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("gscreend")`. The package 'landing page' will be created at

https://bioconductor.org/packages/gscreend

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-10-15 21:44 UTC
Labels: 3a. accepted, OK
