### ISSUE TITLE
SimBu

### ISSUE THREAD

**Issue by alex-d13** [Bioconductor/Contributions#2627] opened 2022-04-08 08:17 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/omnideconv/SimBu

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-04-13 09:18
When I try to install:
```
ModuleNotFoundError: No module named 'anndata'

Detailed traceback:
  File "/home/stvjc/R-dev-dist/lib/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(

--- failed re-building ‘simulator_input_output.Rmd’

--- re-building ‘simulator_scaling_factors.Rmd’ using rmarkdown
--- finished re-building ‘simulator_scaling_factors.Rmd’

SUMMARY: processing the following file failed:
  ‘simulator_input_output.Rmd’

Error: Vignette re-building failed.
Execution halted
```
Do you need a SystemRequirements: field?  Are you using basilisk for your python interoperation?  It would be a good idea.

**Comment by vjcitn** [comment] 2022-04-13 09:19
I see your github action is failing.  So please address these issues and then I will re-check.

**Comment by alex-d13** [comment] 2022-04-26 11:09
Hi,

I am now using basilisk to handle the python dependencies and the github actions runs through. Though I have to add, that the vignettes are not checked in this workflow, as there is an issue with the two sample files that come with the package in `inst/extdata/` as they are not found in this workflow, even though I am using `system.file('extdata', 'anndata.h5ad', package='SimBu')`, as recommended [here](http://contributions.bioconductor.org/data.html).
I do not get this issue when running R CMD check locally.

**Comment by lshep** [comment] 2022-05-09 13:41
Please correct ERROR/Timeouts for a in-depth review to occur.

**Comment by alex-d13** [comment] 2022-05-10 07:08
I am receiving an error from BiocCheck:
`ERROR: At least 80% of man pages documenting exported objects must have runnable examples.`

I had to skip some examples as they rely on the basilisk environment (see first moderation comment). If I keep these examples running, the python dependencies are going to be installed and i will receive a timeout error. 
I do not see a way of solving these example issues. 
If you have any suggestions in that direction, i would be glad to hear them @lshep !

Best,
Alex

**Comment by lshep** [comment] 2022-05-10 11:37
Are these example that are skipped run elsewhere in tests or the vignette?

**Comment by alex-d13** [comment] 2022-05-16 06:22
Currently not, as I would expect a timeout error in Bioconductor as well.

**Comment by lshep** [comment] 2022-05-16 12:20
Have you investigated the long tests for these? Long tests might be a solution so these functions get run on some frequency. http://contributions.bioconductor.org/long-tests.html

**Comment by vjcitn** [comment] 2022-05-16 16:17
Apropos https://github.com/Bioconductor/Contributions/issues/2627#issuecomment-1122011106 there are other basilisk-dependent packages that do not time out.  Please follow developer guidelines so that your review can commence.

**Comment by alex-d13** [comment] 2022-06-01 10:48
I am still receiving warnings from BiocCheck in the bioconductor package builder due to an issue where i am apparently missing a conversion from T/F to TRUE/FALSE. When I run BiocCheck locally, this issue does not come up, do you have an idea how this can happen?

@vjcitn @lshep @Kayla-Morrell

**Comment by lshep** [comment] 2022-06-01 13:51
potentially the version you are using locally.  What version of R/Bioconductor and BiocCheck are you using?

**Comment by alex-d13** [comment] 2022-06-06 10:22
R: 4.1.0
Bioconductor: 3.13
BiocCheck: 1.28.0

**Comment by lshep** [comment] 2022-06-06 11:43
You should update your versions of R, Bioconductor and BiocCheck.  All new packages are submitted and checked against the currently released version of R and Bioconductor packages to ensure compatibility and consistency. Using out dated versions may introduce package version mismatch and cannot be guaranteed.  You should be using a minimum of R 4.2.0 for new submissions with the devel versions of all package dependencies.  

Please pay attention to the other code practice warnings as well
```
* Checking coding practice...
    * NOTE: Avoid sapply(); use vapply()
    * NOTE: Avoid 'cat' and 'print' outside of 'show' methods
    * NOTE: Avoid using '=' for assignment and use '<-' instead
    * NOTE: Avoid the use of 'paste' in condition signals
    * WARNING: Avoid T/F variables; If logical, use TRUE/FALSE
* Checking parsed R code in R directory, examples, vignettes...
    * NOTE: Avoid '<<-' if possible (found 1 times)
    * NOTE: Avoid 'suppressWarnings'/'*Messages' if possible (found 1
      times)
```

If you run a latest version of BiocCheck locally you will get a more detailed log file that can point you to the exact line and column.  That being said it does appear that this is a false positive (in a way) since it is flagging `adata$T` for this check @LiNk-NY .  If it is at all possible to name the variable of this object something that is more descriptive it is advisable.

**Comment by LiNk-NY** [comment] 2022-06-06 16:28
@alex-d13 
Just as a reminder, all Bioconductor developers _must_ be using the latest Bioc-devel version 3.16. 

It may be hard to change the `T` to something else because it is part of the file format? 
Either way, using `$` is not safe practice because of fuzzy matching. Perhaps use `adata[["T"]]` and the added benefit is that the false positive goes away.

Best,
Marcel

**Comment by Kayla-Morrell** [comment] 2022-06-13 14:18
@alex-d13 - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## General package development

- [ ] REQUIRED: Installation instructions in the README files should also
  include instructions on how to install from Bioconductor. For the README.Rmd
file, the installation instructions should be in an `eval = FALSE` code chunk.
- [ ] SUGGESTION: Our build system isn't supporting win32 anymore, so if you
  wanted to remove the .BBSoption file you could.

## DESCRIPTION

- [ ] REQUIRED: Licenses cannot be restrictive, GPL-3 should be used. Also since
  you are using a standard license you do not need the LICENSE file included
with the pacakge. If you decide to keep the file it should be a plain LICENSE
file, not LICENSE.md.

## Data

- [ ] REQUIRED: We require data in the `inst/extdata` to be documented. This
  documentation belongs in the `inst/script` directory and the scripts in this
directory can vary. Most importantly the documentation must clearly state how
the data was generated. It should include source URLs and any key information
regarding filtering or processing. It can be executable code, sudo code, or a
text description. Users should be able to download and roughly reproduce the
file or object that is present as data.

## Vignettes

- [ ] SUGGESTION: We encourage the use of the `BiocStyle` package for
  formatting.
- [ ] SUGGESTION: We strongly encourage the use of table of contents.

*SimBu.Rmd*

- [ ] REQUIRED: The installation section should show users how to download and
  load the package from Bioconductor.
- [ ] REQUIRED: There should be a bit more information in the introduction
  section. What distinguishes this package from other packages in the same area?
What is the motivation for this package and why should it be included in
Bioconductor?

## Man pages

- [ ] SUGGESTION: For any function that is documented but not exported I would
  suggest adding the `@keywords internal` tag. This will remove the function
from the documentation index.
- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and link to the main functions. Users should be able to have a
relevant page display with `?SimBu`.
- [ ] REQUIRED: All man pages should have runnable examples. The use of
  `donttest{}` or `dontrun{}` is discouraged and generally not allowed, however
exceptions can be made with proper justification.

## R code

- [ ] REQUIRED: Avoid `sapply()`; use `vapply()` instead.
- [ ] REQUIRED: Avoid using `=` for assignment and use `<-` instead.
- [ ] REQUIRED: Avoid the use of `paste` in condition signals.
- [ ] REQUIRED: Avoid `<<-` if possible.
- [ ] REQUIRED: Avoid direct slot access with `@`. Accessor methods should be
  created and utilized instead.
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 597
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 1217 lines that are not.

Best,
Kayla

**Comment by alex-d13** [comment] 2022-06-15 14:01
Hi @Kayla-Morrell , 

Thanks for your comments.

>REQUIRED: All man pages should have runnable examples. The use of
donttest{} or dontrun{} is discouraged and generally not allowed, however
exceptions can be made with proper justification.

There are two functions, where I skipped the runnable examples due to runtime reasons. I added them in the recent push and get runtime warnings again. Would it be a solution to keep these 2 examples in the dontrun{} option and add them as longtests instead?

> REQUIRED: Avoid using = for assignment and use <- instead.

Is there a way in BiocCheck to tell me where this assignment issue is happening? For other issues i get the exact line and filename, but not for this one. 

Best,
Alex

**Comment by Kayla-Morrell** [comment] 2022-07-05 15:42
@alex-d13 - With regard to your first comment, yes I would keep these two examples in the dontrun{} (or even better donttest{}) and add them as long tests. As far as your second comment, if you run `BiocCheck::BiocCheck()` on your package then check the log you will see the following:

```
* Checking coding practice...
* NOTE:  Avoid using '=' for assignment and use '<-' instead
Found in files:
R/dataset.R (line 786, column 120)
R/dataset.R (line 793, column 146)
```

This is where the `=` is being used for assignment instead of `<-`.

Best,
Kayla

**Comment by alex-d13** [comment] 2022-07-25 08:07
Hi @Kayla-Morrell 
Kindly re-check the changes I made regarding the longtests and `donttest{}` additions.

**Comment by lshep** [comment] 2022-08-08 15:17
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/alex-d13.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SimBu")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SimBu

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-08-08 15:17 UTC
Labels: OK, 3a. accepted
