### ISSUE TITLE
GenomicDistributions submission

### ISSUE THREAD

**Issue by joseverdezoto** [Bioconductor/Contributions#1502] opened 2020-05-25 16:30 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/databio/GenomicDistributions

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by joseverdezoto** [comment] 2020-05-28 16:30
Dear @dvantwisk,
I had a question/comment about the package I was hoping you could help with. I'm not sure if you've had a chance to go over the package yet, but GenomicDistributions is designed to calculate and visualize information about genomic region data. 

Currently, the submitted package can perform said tasks on hg19 files. We have also designed a data package  [GenomicDistributionsData](https://github.com/databio/GenomicDistributionsData) that harbors information pertaining to the hg38 genome assembly, allowing `GenomicDistributions` to work with hg38 files. This package uses functions that generate new information. However, it partially duplicates some information from other Bioconductor packages.  We were wondering whether it would be suitable to upload this data package to Bioconductor or just keep it on our lab server from which people can download it. 


Best,
Jose

**Comment by dvantwisk** [comment] 2020-05-28 17:00
It would be ideal to submit this data to Bioconductor as an Experiment Data Package. Examples of these packages can be found here: http://www.bioconductor.org/packages/release/data/experiment/

 Don't start a new issue to submit your Experiment Data Package. The following documentation will give you details about how to go about making one:
https://bioconductor.org/developers/package-submission/#experPackage
https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#submitting-related-packages

**Comment by joseverdezoto** [comment] 2020-05-28 17:19
@dvantwisk Thank you so much for the prompt reply. I'll inform the other package contributors. I was going over the links you sent me but still have one question. Would the associated Experiment Data package also carry  R >= 4.0 and version 0.99.z requirements?

**Comment by dvantwisk** [comment] 2020-05-28 17:21
Yes, it should have those requirements.

**Comment by joseverdezoto** [comment] 2020-06-01 20:48
Dear @dvantwisk,
I'm looking into the steps to add the data package into Bioconductor. However, there are a couple of clarifications that might actually change things.  [GenomicDistributionsData](https://github.com/databio/GenomicDistributionsData) contains the functions and steps to build the hg38 data used by `GenomicDistributions`. That is, we don't actually have the raw data stored in the Github repository. Moreover, 2 of the files are approximately 100 MB in size, so it's probably not viable to include them in Github.

We could potentially add the smaller files into the data repository but we'd be excluding the larger files. This is why we thought it might be better to keep `GenomicDistributionsData` in our lab server. What's your opinion in the matter? Any input would be really helpful.


Best,
Jose

**Comment by lshep** [comment] 2020-06-03 17:46
There might be some caveats concerning how the files are organized in the server, naming conventions, and constraints on public retrieval url.   -- because of this most contributors opt to store the data in the Bioconductor server utilizing AWS S3 buckets as described in the help document

**Comment by joseverdezoto** [comment] 2020-06-12 15:11
Dear @lshep I just emailed you regarding the credentials.

**Comment by dvantwisk** [comment] 2020-06-25 17:29
Just checking in. Are you having any issue uploading your experiment data?

**Comment by lshep** [comment] 2020-06-25 17:31
@dvantwisk   we are working on getting the data into the experimenthub for the data package.

**Comment by joseverdezoto** [comment] 2020-07-08 16:07
AdditionalPackage: https://github.com/databio/GenomicDistributionsData

**Comment by lshep** [comment] 2020-07-08 17:12
Hi @joseverdezoto  -- You may have seen that we are in a transition period of how we are moderating/reviewing packages [See post](https://support.bioconductor.org/p/132415/).  Since your original submission used the webhook, we would appreciate if you added the webhook to your AdditionalPackage GenomicDistributionsData and continue the submission process as you have been triggering new builds with a version bump triggered by the webhook.    I have triggered a manual first build of the package that should post shortly.   For a reminder here are the instructions for setting up a webhook: 

## Adding a Web Hook

To add a web hook:

1. Go to your repository page on GitHub. The link to it will look
   something like this:

       https://github.com/yourusername/yourpackagename

   Of course, `yourusername` and `yourpackagename` will be different.

2. Click on `Settings`, which is currently located towards the top, on
   the right-hand side of the page.

3. In the left hand `Options` section, click on `Webhooks`.

4. Click on `Add webhook`.

5. Paste the following URL into the `Payload URL` box, leaving the
   other settings alone:

       http://issues.bioconductor.org

6. Confirm that the `Content type` drop-down menu has
   `application/json` selected.

7. Click `Add webhook`.

8. The page will be updated to include a link to the web hook. Click
   on the link. A 'Recent Deliveries' area should contain a single
   request. Click on the Request and view the "Response" tab. There
   should be a green `200` response code, with body `ping received,
   Bioconductor/Contributions webhook ok`.

Subsequent pushes to the default `master` branch of your
repository will now trigger builds (only if the package version
has been bumped), and the build reports will be
posted to the issue you created in this repository.  Note that pushes
to branches that are not `master`, or non-default branches, are ignored.



Thank you

**Comment by joseverdezoto** [comment] 2020-07-08 17:17
Dear @lshep,

I indeed added a webhook in `GenomicDistributionsData` before posting the link in this issue. I'm not sure why that didn't triggered a build.

**Comment by lshep** [comment] 2020-07-08 17:20
It didn't trigger a build because it only triggers on a new version bump.  That is why I had to kick off the manual build.  It should post shortly.  Subsequent version bumps should trigger builds in the future but let me know if you have any issues.

**Comment by lshep** [comment] 2020-07-08 17:21
You can ignore the comments on the bottom of the build report message about pushing to git.bioconductor.org -- this is the new process.  Just continue to do version bumps and commit to github to trigger builds.  Cheers

**Comment by dvantwisk** [comment] 2020-07-08 18:05
It looks like the package is passing build now. I'll try to have a review to you soon.

**Comment by dvantwisk** [comment] 2020-07-29 15:41
I've completed a review of your package. It looks very well written and I only have a few issues. Please address these issues and message me back when you are finished.

GENERAL
- [ ] [REQUIRED] Your repository is 28MB in size. We generally want to see 
repositories less than 5MB large, but we can make exceptions if the developer
attempts to reduce the size. It appears the that `.git` directory is 25MB
large indicating that you may have committed some datasets to your repository and
later deleted them. We request that you use the BFG-repo-cleaner tool to attempt
to reduce the size of the `git` repository.
https://rtyley.github.io/bfg-repo-cleaner/

vignettes/intro.Rmd
- [ ] [REQUIRED] L45-47 Once your package is submitted to Bioconductor it should
be installed as follows.
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GenomicDistributions")
```
Please add this and remove the `github_install()` instructions.

**Comment by mtmorgan** [comment] 2020-08-23 21:24
@joseverdezoto  will you be responding to the review comments?

**Comment by kkupkova** [comment] 2020-08-24 17:11
Hi @mtmorgan, I will take over for @joseverdezoto and address the comments within this week.

**Comment by kkupkova** [comment] 2020-11-10 20:48
Hi, I am sorry for the delay. We did all the required changes - 1) reduced the repository size to minimum, and 2) updated the installation instructions.

**Comment by lshep** [comment] 2020-11-16 17:01
The issue is now reopened.  Please do a version bump on each package GenomicDistributionsData and GenomicDistributions to get an updated build report for each before the review process continues.  Thank you

**Comment by kkupkova** [comment] 2020-11-16 19:21
I am getting following error when I try to push changes to Bioconductor. Is there a way, I can gain access? I am not the original person, who started the review process.
```
$ git push upstream master
git@git.bioconductor.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by mtmorgan** [comment] 2020-11-16 19:39
Your (original) package was not submitted after July 7, so you cannot push to our git repository until after your package has been accepted. Continue pushing only to the github repository.

**Comment by kkupkova** [comment] 2020-12-03 18:47
The warning is following: 
```
Checking R Version dependency...
    * WARNING: Update R version dependency from 4.0 to 4.1.
```
I don't see, how this could be fixed, since the latest stable version is 4.0.3.

**Comment by lshep** [comment] 2020-12-03 18:51
Your package is building in Bioc 3.13  which is using R-devel.  The current R-devel has numeric 4.1 in preparation for the spring release.

**Comment by kkupkova** [comment] 2020-12-03 18:55
> Your package is building in Bioc 3.13 which is using R-devel. The current R-devel has numeric 4.1 in preparation for the spring release.

Thank you for explanation, I will update the DESCRIPTION file then

**Comment by mtmorgan** [comment] 2020-12-17 21:49
I see that Daniel provided an initial review of this package, and that it has been updated appropriately. I've taken a quick look myself and am happy to accept it to Bioconductor; thanks for your perseverance!

**Comment by mtmorgan** [comment] 2020-12-17 22:37
@kkupkova can you clarify who the maintainer ('cre' in the Authors@R field of the DESCRIPTION file) is for each of these packages, so that we can set permissions on our Bioconductor git repository?

**Comment by kkupkova** [comment] 2020-12-18 15:50
I changed the description files - I am there as a maintainer now.

**Comment by mtmorgan** [comment] 2020-12-19 18:20
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kkupkova.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GenomicDistributions")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GenomicDistributions

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by mtmorgan** [comment] 2020-12-19 18:20
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kkupkova.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("GenomicDistributionsData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/GenomicDistributionsData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-12-19 18:20 UTC
Labels: 3a. accepted, OK
