### ISSUE TITLE
Submission of RepViz

### ISSUE THREAD

**Issue by ThomasFaux** [Bioconductor/Contributions#1048] opened 2019-03-19 09:41 UTC
- Repository: https://github.com/ThomasFaux/RepViz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lawremi** [comment] 2019-03-19 15:54
Consider using Rsamtools and `coverage(BamFile(x))` instead of `bamCount()`.

**Comment by ThomasFaux** [comment] 2019-03-22 11:43
Hello, and thank you for your kind help. I updated the code and am using Rsamtools now.

**Comment by lshep** [comment] 2019-03-22 11:49
Please set up your webhook as described [here](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook). After the webhook is initialized please do a version bump to get a new build of the package.

**Comment by lshep** [comment] 2019-03-22 14:53
Please continue to clean up the ERROR/WARNINGS/NOTES in the build report before a more in-depth review occurs.  
Note:  To remove RepViz.Rproj   don't forget to do a `git rm`  not just `rm`.   
Cheers

**Comment by lshep** [comment] 2019-03-26 16:41
It looks like those ERRORs are from websites being unavailable.  I'm rerunning the package manually to see if they now can be accessed

**Comment by ThomasFaux** [comment] 2019-03-27 09:49
It looks like the warnings are about line indentation (which I will fix ASAP) and the other one is about lines being too long. Is the second one cause of rejection? because the maximum size I've seen in my code is under 100.

**Comment by lshep** [comment] 2019-03-27 11:08
No it would not cause rejection. We prefer it for display purpose and readability but it is not required.  Let me know when the line indentation is fixed and I'll look at doing an initial review over the next week.

**Comment by ThomasFaux** [comment] 2019-03-28 08:59
I corrected the indentation now, thank you for your help.

**Comment by lshep** [comment] 2019-04-01 17:22
Thank you for your submission. Please see initial review below: 

**Build Report**
- [ ] Update the R version dependency from 3.4 to 3.6.  We cannot guarantee that older versions of R and older versions of package dependency work well together. The testing environment is R 3.6. There has been significant changes to underlying package dependencies over release cycles so it ensure working copy.
- [ ] Remove non-empty \value section from man/RepViz.Rd. Add this section in even if it just describes the plot  
- [ ] We strongly encourage a NEWS file. Any updates per release will be included in a [release announcement](http://bioconductor.org/news/bioc_3_8_release/#news-from-new-and-existing-software-packages). See [news guidelines](http://bioconductor.org/developers/package-guidelines/#news) 
- [ ] We strongly encourage [unit tests](http://bioconductor.org/developers/how-to/unitTesting-guidelines/) that test the underlying functionality of your package and could indicate any problems with coding. Perhaps create tests for subprocesses performed in the code to ensure proper running. 

**General**
- [ ] Please remove RepViz-manual.pdf in top level directory by `git -rm` if you would like this file for your reference remove, add to .gitignore, and then reintroduce without committing to git. 

**Description**
- [ ] Add Maintainers first and last name not "The package maintainer" 
- [ ] Please remove lazyData: true.  we have rarely found this useful and can actually slow down the installation of packages. 

**Man page**
- [ ] Please provide more detail in the description field
- [ ] Please add value section 
- [ ] Please update the example to write any output to a temporary directory not the user working directory `getwd()` to `tempdir()`

**inst**
- [ ] Please provide an inst/script/ directory that includes a script describing the source information and how the files were generated in inst/extdata. This could be code, sudo code, or text but there should be some indication of how the files were generated. 

**vingette**
- [ ] Please remove `git -rm` the intermediate files .R, .html, and .md.
- [ ] Optional, it is much more intuitive for a user to type `vignette('RepViz')` than `vignette('RepViz-vignette')`. I would recommend renaming.  
- [ ] We recommend having a table of contents. I think you can do an option in the vignette metdata of `toc: true`  to achieve this. 
- [ ] Do not run examples from a users working directory.  Write and execute code from a `tempdir()`

**General**
- [ ] Can the package be used with rtracklayer::BamFile and rtracklayer::BEDfile objects already created or must the raw files be used and why?
- [ ] Might it be useful to give the user the option to save the plot to a file? 

**R code**
- [ ] Update print/cat statements to `message()` or `warning()`
- [ ] For your main function, have some input checks for proper format.  If genome can only be three options the function can be defined with `genome=c(hg19','hg38','mm10')` and utilize a call to `match.arg` or utilize the `stopifnot` function perhaps like `stopifnot(genome %in% c(hg19','hg38','mm10'))`. Another check could be that region is a GRanges object. And so forth for the given arguments.  
- [ ] For something like replicatesNumber, if you know the end length of vec it would be better to preallocate and fill rather than concatenate. 
`vec <- numeric(length(groupnb))
 for(i in groupnb)
     vec[i] <- len` 
`
- [ ] in unitTest, if they are "ERROR" consider using `error()` instead of `cat(paste0(`, regardless these should at least be `message()`
- [ ] In defineLayout, mat would get overwritten depending on if one or both geneTrack and avgTrack were defined? There should be better checking and control of how mat is defined given the arguments. 

Please correct or respond to the above comments.  When you are ready for another review please perform a version bump and comment here with what has been changed. 
Thank you and I look forward to getting your package accepted to Bioconductor.

**Comment by ThomasFaux** [comment] 2019-04-10 08:43
Hi Ishep, thank you for being so fast. Here is the summary of what I did.
I answered the parts that I would like to discuss.

#### Build Report

  - [ ] Update the R version dependency from 3.4 to 3.6. We cannot guarantee that older versions of R and older versions of package dependency work well together. The testing environment is R 3.6. There has been significant changes to underlying package dependencies over release cycles so it ensure working copy.
  	- If I bump the version of R up I can't build the package. if I put my R version to 3.6 I can't install bioconductor packages because I need the 3.5 version to do it with bioC. I guess there is probably a trick that I didn't figure out.
  - [x] Remove non-empty \value section from man/RepViz.Rd. Add this section in even if it just describes the plot
  - [x] We strongly encourage a NEWS file. Any updates per release will be included in a release announcement. See news guidelines
  - [ ] We strongly encourage unit tests that test the underlying functionality of your package and could indicate any problems with coding. Perhaps create tests for subprocesses performed in the code to ensure proper running.
   - Here I will have to think about something to test, the only way that I think to get a sanity test of the code is to actually see the output with another visualisation tool.
 
#### General

  - [x] Please remove RepViz-manual.pdf in top level directory by git -rm if you would like this file for your reference remove, add to .gitignore, and then reintroduce without committing to git.
Description

  - [x] Add Maintainers first and last name not "The package maintainer"
  - [x] Please remove lazyData: true. we have rarely found this useful and can actually slow down the installation of packages.
Man page

  - [x] Please provide more detail in the description field
  - [x] Please add value section
  - [x] Please update the example to write any output to a temporary directory not the user working directory getwd() to tempdir() 

#### inst

  - [x] Please provide an inst/script/ directory that includes a script describing the source information and how the files were generated in inst/extdata. This could be code, sudo code, or text but there should be some indication of how the files were generated.
  
#### vingette

  - [x] Please remove git -rm the intermediate files .R, .html, and .md.
  - [x] Optional, it is much more intuitive for a user to type vignette('RepViz') than vignette('RepViz-vignette'). I would recommend renaming.
  - [x] We recommend having a table of contents. I think you can do an option in the vignette metdata of toc: true to achieve this.
  - [x] Do not run examples from a users working directory. Write and execute code from a tempdir()
 
#### General

  - [ ] Can the package be used with rtracklayer::BamFile and rtracklayer::BEDfile objects already created or must the raw files be used and why?
    - The code could do that with some heavy modifications of the underlying process. But this tool is mainly aimed at biologists to get a quick and efficient way to visualize a genomic region. Having such objects in input woould make the grouping difficult for the biologist as they would have to do it themselves and create the layouts.
  - [ ] Might it be useful to give the user the option to save the plot to a file?
    - Here I guess I could give an option to put a character string that would be used as a file name. But I was thinking that people would use the GUI for that or the different jpeg() png() and svg() function.

#### R code

  - [x] Update print/cat statements to message() or warning()
  - [x] For your main function, have some input checks for proper format. If genome can only be three options the function can be defined with genome=c(hg19','hg38','mm10') and utilize a call to match.arg or utilize the stopifnot function perhaps like stopifnot(genome %in% c(hg19','hg38','mm10')). Another check could be that region is a GRanges object. And so forth for the given arguments.
  - [x] For something like replicatesNumber, if you know the end length of vec it would be better to preallocate and fill rather than concatenate. vec <- numeric(length(groupnb)) for(i in groupnb) vec[i] <- len
  - [x] in unitTest, if they are "ERROR" consider using error() instead of cat(paste0(, regardless these should at least be message()
  - [x] In defineLayout, mat would get overwritten depending on if one or both geneTrack and avgTrack were defined? There should be better checking and control of how mat is defined given the arguments.
  
Please correct or respond to the above comments. When you are ready for another review please perform a version bump and comment here with what has been changed.
Thank you and I look forward to getting your package accepted to Bioconductor.

**Comment by lshep** [comment] 2019-04-12 14:16
Thank you for the updates.  A few further comments below.  I think with these next round of changes it should be ready for acceptance. 


- [ ] You should update your version of R and be developing on the latest version. Bioconductor always uses the latest version of R and latest version of packages. If you really can not update your local version of R, I would suggest creating a separate branch for your personal use to keep the R dependency of 3.4 but update the Bioconductor version to at least 3.5 but preferably 3.6. 


- [ ] NEWS file. Thank you for adding.  Slight formatting issue. Please use + or * to indicate lists
  under the (--------)  
```
CHANGES IN VERSION 0.99.14
-------------------------

RELEASE

    + Implementation of the last comments from reviewers

```

- [x] Unit test.  Okay if you want to skip but something to keep in mind when
  developing.  Many find it useful during the development process to ensure the
  input/output/expected results are as intended. Just as an example
```
# well I can't because the descritpion of the arguments don't seem quite right
  but

# copy BAM files
# internally call makeBAMLayout
# check output of makeBAMLayout to ensure the file was read properly
# put this into getCoverage, check they output of getCoverage is expected
....

```

**man code**
- [ ] The example still runs in the working directory. I see it was updated in
the Roxygen, perhaps you need to run `document()` to have the man page updated?

**General**

- [x] Can the package be used with rtracklayer::BamFile and rtracklayer::BEDfile
  objects already created or must the raw files be used and why?
    + Okay - based on your reply.  It would be nice to consider making both raw
  and from existing object in a future implemnentation or as a future
  improvement.  Not necessarily changing from what you have now completely but
  providing both.  (Okay)
 
- [x] Might it be useful to give the user the option to save the plot to a file?
    + Not all users have or will utilize a GUI, there are other users that work
    solely on commnad line.  But ok.  Users can always run inside their own call
    to favoriate save.  (Okay)  


**R Code**
- [ ] makeBAMLayout actually doesn't use the
  argument region. This should be cleaned up. 

- [ ] For defineLayout and defining a matrix, consider updating to a switch
  statment that might be more appropriate, and could catch the edge case (could
  sum ever be > 3? )

- [ ] For createDataObject, from a completeness point of view, it would probably
  be better to do something along the lines  (and also for BED)
```
    if (!is.null(BAM)) {
        if (verbose == TRUE)  message("loading the BAM related data from ", BAM, "\n")
        
        if(is.character(BAM)){
            files <- utils::read.table(file = BAM, sep = ",", colClasses = c("character", "character"))
            colnames(files) <- c("files", "group")
            return_object$BAM <- files
        } else if(is.data.frame(BAM)){
            return_object$BAM <- BAM
        } else {
	    stop("BAM is not character or data.frame")
	}
        
    }

```
- [ ] Just something to think about, users in the future may request more
control over different plotting options that may be allowed with `...`.  I won't
push this but just something to consider as a possible improvement in the
future. 

- [ ] I suggest moving the input checks more toward the top of the functions to
  avoid running code that cannot continue.  Ie. the check in line 88 of
  plotRegion.R 

- [ ] In geneRanges, can column only be "ENTREZID", or again, check valid input? 

- [ ] In plotGeneTrack.R,  The helper function f is used and the exact same in
 both UTR functions, move this function outside function definition and only
 include once to eliminate as much duplicated code as possible. 

- [ ] getBiomaRt could benefit from a switch statment that than catches a
  default.

- [ ] Consider switch with arrowNumber, this keeps executing and overwritting
  for greater than.  for example, 3 would result it evaluation and overwriting
  of all the value > statements.  if ((value > 0.25) & (value <= 0.75)) ... 

- [ ] I don't think there is an `error()` function in R. You would want to
  replace with `stop()`.  Also `warning(), message(), and stop()` all do a
  paste0 automatically so this is not needed. 
  `vl = 2;  stop("my value: ", vl)` or an example in your case
  `stop("There is no genes in the given region :", region)`


Thank you for your continued effort. I look forward to accepting your package. As before when ready please perform a version bump here and leave some comments on the updates.

**Comment by ThomasFaux** [comment] 2019-04-15 12:38
Hei, thank you for your comments, Here is a summary of the corrections I did.

 * [x]  You should update your version of R and be developing on the latest version. Bioconductor always uses the latest version of R and latest version of packages. If you really can not update your local version of R, I would suggest creating a separate branch for your personal use to keep the R dependency of 3.4 but update the Bioconductor version to at least 3.5 but preferably 3.6.
   * bumped to R >= 3.5.1 	
 * [x]  NEWS file. Thank you for adding.  Slight formatting issue. Please use + or * to indicate lists
   under the (--------)
 
 ```
 CHANGES IN VERSION 0.99.14
 -------------------------
 
 RELEASE
 
     + Implementation of the last comments from reviewers
 ```
 * [x]  Unit test.  Okay if you want to skip but something to keep in mind when
   developing.  Many find it useful during the development process to ensure the
   input/output/expected results are as intended. Just as an example
 
 ```
 # well I can't because the descritpion of the arguments don't seem quite right
   but
 
 # copy BAM files
 # internally call makeBAMLayout
 # check output of makeBAMLayout to ensure the file was read properly
 # put this into getCoverage, check they output of getCoverage is expected
 ....
 ```
 **man code**
 
 * [x]  The example still runs in the working directory. I see it was updated in
   the Roxygen, perhaps you need to run `document()` to have the man page updated?
 
 **General**
 
 * [x]  Can the package be used with rtracklayer::BamFile and rtracklayer::BEDfile
   objects already created or must the raw files be used and why?
   
   * Okay - based on your reply.  It would be nice to consider making both raw
     and from existing object in a future implemnentation or as a future
     improvement.  Not necessarily changing from what you have now completely but
     providing both.  (Okay)
 * [x]  Might it be useful to give the user the option to save the plot to a file?
   
   * Not all users have or will utilize a GUI, there are other users that work
     solely on commnad line.  But ok.  Users can always run inside their own call
     to favoriate save.  (Okay)
 
 **R Code**
 
 * [x]  makeBAMLayout actually doesn't use the argument region. This should be cleaned up.
 * [x]  For defineLayout and defining a matrix, consider updating to a switch
   statment that might be more appropriate, and could catch the edge case (could
   sum ever be > 3? )
 * [x]  For createDataObject, from a completeness point of view, it would probably
   be better to do something along the lines  (and also for BED)
 
 ```
     if (!is.null(BAM)) {
         if (verbose == TRUE)  message("loading the BAM related data from ", BAM, "\n")
         
         if(is.character(BAM)){
             files <- utils::read.table(file = BAM, sep = ",", colClasses = c("character", "character"))
             colnames(files) <- c("files", "group")
             return_object$BAM <- files
         } else if(is.data.frame(BAM)){
             return_object$BAM <- BAM
         } else {
 	    stop("BAM is not character or data.frame")
 	}
         
     }
 ```
 
 * [x]  Just something to think about, users in the future may request more
   control over different plotting options that may be allowed with `...`.  I won't
   push this but just something to consider as a possible improvement in the
   future.
     * This will be implemented in the future versions
 * [x]  I suggest moving the input checks more toward the top of the functions to
   avoid running code that cannot continue.  Ie. the check in line 88 of
   plotRegion.R
     * The check line 28 has been removed as it was already done in the function unitTest() 
 * [x]  In geneRanges, can column only be "ENTREZID", or again, check valid input?
     * removed the function that was not used (also a second not used function)
 * [x]  In plotGeneTrack.R,  The helper function f is used and the exact same in
   both UTR functions, move this function outside function definition and only
   include once to eliminate as much duplicated code as possible.
 * [x]  getBiomaRt could benefit from a switch statment that than catches a
   default.
 * [x]  Consider switch with arrowNumber, this keeps executing and overwritting
   for greater than.  for example, 3 would result it evaluation and overwriting
   of all the value > statements.  if ((value > 0.25) & (value <= 0.75)) ...
     * Couldn't put a switch here because it doesn't take floating numbers but I modified the code so that there is no overwritting
 * [x]  I don't think there is an `error()` function in R. You would want to
   replace with `stop()`.  Also `warning(), message(), and stop()` all do a
   paste0 automatically so this is not needed.
   `vl = 2;  stop("my value: ", vl)` or an example in your case
   `stop("There is no genes in the given region :", region)`

**Comment by ThomasFaux** [comment] 2019-04-16 07:13
Amazing, Thank you for your help and comments, it was a real pleasure.

**Comment by mtmorgan** [comment] 2019-04-19 22:10
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/ThomasFaux.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("RepViz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/RepViz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-04-19 22:10 UTC
Labels: 3a. accepted, WARNINGS
