### ISSUE TITLE
biodbHmdb (biodb extension package)

### ISSUE THREAD

**Issue by pkrog** [Bioconductor/Contributions#2286] opened 2021-09-15 17:02 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/pkrog/biodbHmdb

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lazappi** [comment] 2021-10-07 20:53
Hi @pkrog

Thanks for submitting **biodbHmdb** :tada:! This looks like a really high-quality, well-constructed package. I have a few comments but hopefully they should be pretty quick to address. Below is my review of your package. Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional

## General package development

- [ ] :warning: There are some notes from `BiocCheck::BiocCheck()` in the build report. Please check if it's appropriate to address any of these.

## DESCRIPTION file

- [ ] :green_circle: It is recommended to add ORCiDS to the `Authors@R` field
- [ ] :green_circle: It is recommended to add a `BugReports` field, usually this is a URL for your GitHub issues page or the Bioconductor support site
- [ ] :green_circle: It is recommended to add a `URL` field, this is usually your GitHub repository or the package Bioconductor page (you can have multiple URLs separated by commas)

## NAMESPACE file

- [ ] :warning: Please use `importFrom` instead of importing whole packages with `import` if you can

## Package data

- [ ] :rotating_light: Please document the `hmdb_extract.zip` data file with a file in `inst/script`
- [ ] :green_circle: I saw there was a note about not being able to use `BiocFileCache` for so many files. It seems like the system you are using is part of Bioconductor already so I think that's ok but I'm curious what the issue is (and it might be worth raising with the Bioconductor core if they don't know already).
- [ ] 🚨 Can you please confirm that the licensing for HMDB allows you to distribute part of the database and for users to download it?

## Documentation

### Vignette

- [ ] :rotating_light: Please give the vignette a more specific name, `intro.Rmd` is likely to clash with another package
- [ ] :warning: Bioconductor recommends having an *Introduction* section. I think the information is there but maybe change one of the headings.
- [ ] :rotating_light: Please add an *Installation* section with Bioconductor installation instructions, the code chunk for this section should NOT be evaluated.
- [ ] :rotating_light: Please add a `sessionInfo()` section at the end
- [ ] :green_circle: There are a lot of references in the BibTeX file but they don't seem to be used in the vignette. You can probably reduce the size of this file by only keeping the ones you need.

## Code

### R

- [ ] :green_circle: Please double check you have followed the [Querying Web Resources](http://bioconductor.org/developers/how-to/web-query/) guidelines

### C and Fortran code

- To me this looks ok but I don't have much experience with including C++ code in a package so I might ask one of the core members to double check

## Additional files

- [ ] :green_circle: There are quite a few additional files that I'm not familiar with. I think I can see what they are used for and they are included in `.Rbuildignore` but please double check they are all required.

**Comment by lazappi** [comment] 2021-10-08 12:20
@nturaga, @LiNk-NY, @lshep, @jianhong I've just noticed that we have all been assigned to related packages. Would it make sense for one person to take over all of them to standardise the feedback and avoid suggesting slightly different changes for each one? The first review has been done for some of them at least so hopefully it wouldn't be too much extra work from here.

**Comment by vjcitn** [comment] 2021-10-08 12:30
This is a very good point.  The round robin approach to assignments has some real limitations.  Do you see a way to reassign/swap some of yours away and take the biodb*?

**Comment by lazappi** [comment] 2021-10-08 12:50
I'm on leave next week so that probably doesn't work well for getting things done before the release. I'm also not super comfortable with reviewing the C++ stuff so I was going to ask someone else to look at that part anyway. Sorry, that's probably not very helpful.

**Comment by pkrog** [comment] 2021-10-08 16:12
About the notes from `BiocCheck`:
 * I do not observe the `NOTE: 'sessionInfo' not found in vignette(s)` on my computer, and do not know what it refers to.
 * The long lines are inside generated files.
 * I have corrected the indentations.

**Comment by nturaga** [comment] 2021-10-08 16:42
> @nturaga, @LiNk-NY, @lshep, @jianhong I've just noticed that we have all been assigned to related packages. Would it make sense for one person to take over all of them to standardise the feedback and avoid suggesting slightly different changes for each one? The first review has been done for some of them at least so hopefully it wouldn't be too much extra work from here.

I did ask the author that in my review yesterday https://github.com/Bioconductor/Contributions/issues/2288#issuecomment-938287626 . But it's hard to review this package without taking a look at biodb (which has already been accepted).

**Comment by lazappi** [comment] 2021-10-08 17:07
> * I do not observe the `NOTE: 'sessionInfo' not found in vignette(s)` on my computer, and do not know what it refers to.

This will be the same comment I made about the in the vignette section. Basically just having a chunk at the end which runs `sessionInfo()`.

**Comment by vjcitn** [comment] 2021-10-08 18:48
I am going to take over the review of this suite of packages.  @lazappi thanks and have a good break!

**Comment by pkrog** [comment] 2021-10-12 07:51
> > * I do not observe the `NOTE: 'sessionInfo' not found in vignette(s)` on my computer, and do not know what it refers to.
> 
> This will be the same comment I made about the in the vignette section. Basically just having a chunk at the end which runs `sessionInfo()`.

Done

**Comment by pkrog** [comment] 2021-10-12 08:19
I have written a file `inst/CONTENT.md` that describes `hmdb_extract.zip`.

About HMDB download and distribution, yes it is allowed officially for non-commercial use, please see <https://hmdb.ca/downloads>.

**Comment by pkrog** [comment] 2021-10-12 08:56
ORCID, URL and BugReports in DESCRIPTION file : done.

**Comment by pkrog** [comment] 2021-10-12 09:15
About the @import directive. The only one in this package is `@import R6`.
The reason it exist is because of the following NOTE from `R CMD check` if I omit it:
```
Namespace in Imports field not imported from: ‘R6’
  All declared Imports should be used.
```
In this case, roxygen2 does not write `import(R6)` into the `NAMESPACE` file.
However I do not need myself the import directive, since I always use explicit namespace reference.
I changed the `@import` into `@importFrom` nonetheless.

**Comment by pkrog** [comment] 2021-10-12 09:31
About `BiocFileCache`, I have something to try first, the `action="asis"` option. But I do not believe it will change anything. After that I will post an issue on `BiocFileCache` GitHub page.

**Comment by pkrog** [comment] 2021-10-12 09:33
The BiTeX file has been shrinked.
About querying : the main tests are light as a matter of fact. The heavy tests are in longtests folder.

**Comment by vjcitn** [comment] 2021-10-18 15:47
Do you know what is going on with windows?

**Comment by pkrog** [comment] 2021-10-18 20:46
Not yet. Trying to reproduce on my Windows VM.
The error is weird, because the zip file contains is stored inside the repository and contains only one file.

**Comment by lshep** [comment] 2021-10-22 17:16
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/pkrog.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("biodbHmdb")`. The package 'landing page' will be created at

https://bioconductor.org/packages/biodbHmdb

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-10-22 17:16 UTC
Labels: OK, 3a. accepted
