### ISSUE TITLE
SUITOR

### ISSUE THREAD

**Issue by wheelerb** [Bioconductor/Contributions#2515] opened 2022-01-25 13:49 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/wheelerb/SUITOR

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-02-06 11:28
The vignette includes evaluated installation commands.  These must be removed or disabled.  There is a reference to a github repo.  Installation commands related to the github repo must be disabled in the vignette.  The vignette is taking a very long time to compute.  Can you speed it up either by changing convergence parameters or starting from a "warmed" state?

**Comment by wheelerb** [comment] 2022-02-07 14:15
OK, I will make some changes to the vignette.

**Comment by wheelerb** [comment] 2022-02-08 14:55
I have changed the vignette to start from a warmed state, so it now runs much faster.

**Comment by vjcitn** [comment] 2022-03-01 15:04
I don't think your changes were committed to the https://github.com/wheelerb/SUITOR.git

**Comment by wheelerb** [comment] 2022-03-01 15:18
Thanks, they weren't. I just committed them.

**Comment by vjcitn** [comment] 2022-03-01 17:14
OK.  Seeing the compiled .Rnw was a blast from the past.  Consider using Rmd ... it gives nice HTML ... we don't require it but it is worth getting under your belt eventually.

**Comment by PeteHaitch** [comment] 2022-03-21 22:53
Thank you for your submission.
I have been assigned to review **SUITOR** and will provide my review within 2 weeks.

Cheers,
Pete

**Comment by PeteHaitch** [comment] 2022-04-01 02:04
Hi @wheelerb,

Thank you for your submission to Bioconductor.
Overall, the package is in good shape with clear code.
For acceptance into Bioconductor, I have a few Required points, as well as some Recommended points, that I would ask you to first please address.
Please add your point-by-point replies to the review in this thread.

Cheers,
Pete

## Required

- [ ] `Packaged` should not be appearing in `DESCRIPTION` (see https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file)
- [ ] My Sweave is rusty; is it possible to use an 'unevaluated' code chunk in Sweave rather than relying on commented-out code?
- [ ] For the commented-out code in Sections 5-7 of vignette, I tested out the actual code to see how long it would take to run and obtained slightly different results. Please `set.seed()` to ensure that the results that a user who actually runs the code chunk would obtain by copying+pasting from the vignette match those from the pre-saved results.
- [ ] In the vigentte, the `plot_96_profile(Extract$W, condensed=TRUE, ymax=0.3)` code does not actually generate a figure in the vignette.
- [ ] Please take reasonable steps to address all output of running `BiocCheck::BiocCheck()` on the package.
- [ ] **doParallel**, **foreach**, **parallel**, and **ggplot2** should appear in `Imports`, rather than `Depends`, in the `DESCRIPTION`.

## Recommended

- [ ] Consider using [**BiocStyle**](https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html) for formatting the vignette for consistency with other Bioc; see [Section 1.1.1 of the vignette (pdf)](https://www.bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/LatexStyle2.pdf) for how to use **BiocStyle** with Sweave.
- [ ] Consider using [**BiocParallel**](https://www.bioconductor.org/packages/release/bioc/html/BiocParallel.html) for parallelisation for the reasons mentioned in https://contributions.bioconductor.org/r-code.html?q=parallel#parallel-recommendations.
- [ ] Consider adding a README file.
- [ ] Please add a `BugReports` field to the `DESCRIPTION`. This usually points to the GitHub Issues page, https://github.com/wheelerb/SUITOR/issues.
- [ ] Please be consistent with use of `camelCase` or `snake_case` in naming (exported) functions.
- [ ] Consider adding a citation file `inst/CITATION`; see https://contributions.bioconductor.org/citation.html
- [ ] I asked @hpages, a core member of the Bioconductor team, to take a look at the C code. His comments were, "C code in SUITOR could avoid risks of memory leak by using `R_alloc()` instead of `malloc()`/`free()` but otherwise is clean and well organized so memory management concerns are not a show-stopper (memory leaks would only occur in unusual situations when some functions don't complete because they run into an error).". To my understanding there's nothing in the C code that requires changing, but please consider his advice.

**Comment by wheelerb** [comment] 2022-04-05 13:50
Thanks, I will get started on these.

**Comment by wheelerb** [comment] 2022-04-18 17:32
Hi Pete,

Thanks for reviewing. I have made several changes to the package and my comments are below.

Sincerely,

Bill

Required
 Packaged should not be appearing in DESCRIPTION (see https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file)
**Fixed**

 My Sweave is rusty; is it possible to use an 'unevaluated' code chunk in Sweave rather than relying on commented-out code?
**Fixed**
**The vignette is now in Rmd format.**

 For the commented-out code in Sections 5-7 of vignette, I tested out the actual code to see how long it would take to run and obtained slightly different results. Please set.seed() to ensure that the results that a user who actually runs the code chunk would obtain by copying+pasting from the vignette match those from the pre-saved results.
**Fixed**

 In the vigentte, the plot_96_profile(Extract$W, condensed=TRUE, ymax=0.3) code does not actually generate a figure in the vignette.
**Fixed**

 Please take reasonable steps to address all output of running BiocCheck::BiocCheck() on the package.
**Fixed**
 **One of the NOTES is: " Avoid redundant 'stop' and 'warn*' in signal conditions"
In functions that check input arguments, I have multiple stop() statements that will throw a different error message depending on what is wrong with the input argument. I do not see how they are redundant.**
**Another NOTE is : "Usage of dontrun{} / donttest{} found in man page examples."
These are needed in some examples, because the main functions can take a long time to run.**

 doParallel, foreach, parallel, and ggplot2 should appear in Imports, rather than Depends, in the DESCRIPTION.
**Fixed**

Recommended
 Consider using [BiocStyle](https://www.bioconductor.org/packages/release/bioc/html/BiocStyle.html) for formatting the vignette for consistency with other Bioc; see [Section 1.1.1 of the vignette (pdf)](https://www.bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/LatexStyle2.pdf) for how to use BiocStyle with Sweave.
**Fixed** 
**The format of the vignette has now been changed to Rmd.**

 Consider using [BiocParallel](https://www.bioconductor.org/packages/release/bioc/html/BiocParallel.html) for parallelisation for the reasons mentioned in https://contributions.bioconductor.org/r-code.html?q=parallel#parallel-recommendations.
**No change yet. I have looked at the BiocParallel package, but it is unclear how my code would change in order to use BiocParallel.**

 Consider adding a README file.
**Added**

 Please add a BugReports field to the DESCRIPTION. This usually points to the GitHub Issues page, https://github.com/wheelerb/SUITOR/issues.
**Added**

 Please be consistent with use of camelCase or snake_case in naming (exported) functions.
**Fixed, suitor_extract_WH is now called suitorExtractWH**

 Consider adding a citation file inst/CITATION; see https://contributions.bioconductor.org/citation.html
**Added**

 I asked @hpages, a core member of the Bioconductor team, to take a look at the C code. His comments were, "C code in SUITOR could avoid risks of memory leak by using R_alloc() instead of malloc()/free() but otherwise is clean and well organized so memory management concerns are not a show-stopper (memory leaks would only occur in unusual situations when some functions don't complete because they run into an error).". To my understanding there's nothing in the C code that requires changing, but please consider his advice.
**Fixed**
**I am now using R_Calloc and R_Free instead of malloc and free.**

**Comment by PeteHaitch** [comment] 2022-04-21 01:00
Hi @wheelerb,

Thanks for addressing the comments in the initial review.
There are still some issues that must be addressed for **SUITOR** to be accepted.
Please note that these need to be fixed by the end of this week to ensure that **SUITOR** is included in Biocondcutor 3.15 (see https://bioconductor.org/developers/release-schedule/).

Cheers,
Pete

### Required

- [x] Please limit use of unevaluated code chunks in vignette where feasible.
  - [x] Ideally, all chunks (except installation) in the vignette would be evaluated (perhaps using fewer iterations or a smaller subset of data) but I appreciate that it may be challenging to make an example for the vignette that can complete within the time limits of Bioconductor's build system. If you judge it infeasible to shorten the running time of the examples, then please double-check all unevaluated chunks give the expected output. I strongly recommend that you make these checks automatic (rather than doing them by hand) by including them as 'long tests' (see https://bioconductor.org/developers/how-to/long-tests/). This will ensure that the code is regularly checked by the Bioconductor build machines but you could continue to load pre-computed results in the vignette to save time.
  - [ ] The chunk containing `Extract <- suitorExtractWH(SimData, re$rank)` does not take particularly long to run (40 seconds on my laptop). Please modify this section so that the code is evaluated rather than loading pre-computed results.
  - [x] The vignette code in 'Running suitor() with the different option values' of the vignette contains an error. This chunk is not evaluated and hence this error isn't caught by the automatic checks. Please fix.

``` r
library(SUITOR)
data(SimData)
OP <- list(min.rank=5, max.rank=13, k.fold=5, n.seeds=50, get.summary=0)
set.seed(123)
re2 <- suitor(SimData, op=OP)
#> Error in check_op_valid(op): ERROR: the option(s) n.seeds are not valid
```

- [x] Please take a look through the rendered vignette to check the formatting matches your expectations. Here are some obvious issues I spotted with quick fixes:
  - [x] Fix section numbering in vignette; these should start at 1 not 0 (Use `#` for top-level headings, `##` for second-level headings, etc). There is no need for manual numbering of section headings because Rmarkdown will autogenerate these once you use the correct syntax (this Rmarkdown cheatsheet may be useful https://rmarkdown.rstudio.com/lesson-15.HTML, as too the linked documentation).
  - [x] Most Rmarkdown documents I've read use backticks for function names and arguments when writing Rmarkdown, e.g., `suitor()` and `re$rank` rather than bold (**suitor()**) or italic (*suitor()*). I would recommend following suit on this.
  - [x] Related, the formatting of the paragraph beginning with "By default, the suitor() function returns a list containing the estimate" is messed up. I think this is an unfortunate interaction of `$` being used to denote LaTeX math mode as well as being valid R code. If you change from using **bold** (`**`) or *italic* (`*`) markdown syntax to using `code` (`\``) for the variables then this issue goes away.
  - [x] The chunks that show the output of `str(re)`, `str(re2)`, `re$rank`, `head(Extract$W)`, and `Extract$H[,1:3]` are unclear when reading the rendered vignette because the actual calls to `str(re)`, `str(re2)`, `re$rank`, `head(Extract$W)`, and `Extract$H[,1:3]` aren't shown in the rendered vignette (because the code is in a `echo = FALSE` and/or `eval = FALSE` chunk) and only their output is shown.
  - [x] For future reference, you could create `table1` and `table2` in the vignette as a *data.frame* and then use `knitr::kable()` to create a nicely rendered table.


### Recommended

- [x] It is strongly recommend to keep the Bioconductor-hosted git repo (git@git.bioconductor.org:packages/SUITOR) in-sync with the GitHub-hosted git repo (https://github.com/wheelerb/SUITOR) (please see https://www.bioconductor.org/developers/how-to/git/ for documentation on this topic).
- [x] Consider using `suppressPackageStartupMessages(library(MutationalPatterns))` in the vignette to avoid the verbose output.
- [ ] "I have looked at the BiocParallel package, but it is unclear how my code would change in order to use BiocParallel."
  - @mtmorgan, author of **BiocParallel** may be able to point you in a helpful direction. From what I can tell, you're currently using **foreach** for parallelisation, along with some custom code to detect Windows (PSOCK) vs. non-Windows machines (FORK) machines. I think **BiocParallel** should be able to help simplify your code by taking away some of the 'bookkeeping', but I won't make use of **BiocParallel** a requirement for acceptance of **SUITOR** because it seems you've made some effort to ensure portability of the code across machines.

**Comment by mtmorgan** [comment] 2022-04-21 07:24
Looking briefly at the code, I think you would remove all but the call to `extractWH_par()` from https://github.com/wheelerb/SUITOR/blob/c3ba8de42082e8b0826b420b14c35013fb0e5b6c/R/source_extract_WH.R#L40-L50 and replace https://github.com/wheelerb/SUITOR/blob/c3ba8de42082e8b0826b420b14c35013fb0e5b6c/R/source_extract_WH.R#L109-L119 with
```{r}
res <- bplapply(seq_len(n), function(i, input, op, mat, a, b) {
    extractWH_seq_C(input, op, mat[a[i]:b[i], , drop=FALSE])
}, input, op, mat, a, b)
```
`op$n.cores` and `op$n.type` would be replaced by either `SnowParam()` or `MulticoreParam()`, or maybe default to `bpparam()` (which chooses MulticoreParam (forked) on non-Windows, SnowParam (socket) on Windows).

**Comment by wheelerb** [comment] 2022-04-25 17:12
Hi Pete and Martin,

Thank you for your feedback and code.
Below are the changes made to your points above.

Sincerely,

Bill

Required
 Please limit use of unevaluated code chunks in vignette where feasible.
 Ideally, all chunks (except installation) in the vignette would be evaluated (perhaps using fewer iterations or a smaller subset of data) but I appreciate that it may be challenging to make an example for the vignette that can complete within the time limits of Bioconductor's build system. If you judge it infeasible to shorten the running time of the examples, then please double-check all unevaluated chunks give the expected output. I strongly recommend that you make these checks automatic (rather than doing them by hand) by including them as 'long tests' (see https://bioconductor.org/developers/how-to/long-tests/). This will ensure that the code is regularly checked by the Bioconductor build machines but you could continue to load pre-computed results in the vignette to save time.
**The vignette has been modified to run all chunks instead of loading pre-computed results.**

 The chunk containing Extract <- suitorExtractWH(SimData, re$rank) does not take particularly long to run (40 seconds on my laptop). Please modify this section so that the code is evaluated rather than loading pre-computed results.
**Fixed**

 The vignette code in 'Running suitor() with the different option values' of the vignette contains an error. This chunk is not evaluated and hence this error isn't caught by the automatic checks. Please fix.
**Fixed**

library(SUITOR)
data(SimData)
OP <- list(min.rank=5, max.rank=13, k.fold=5, n.seeds=50, get.summary=0)
set.seed(123)
re2 <- suitor(SimData, op=OP)
#> Error in check_op_valid(op): ERROR: the option(s) n.seeds are not valid

 Please take a look through the rendered vignette to check the formatting matches your expectations. Here are some obvious issues I spotted with quick fixes:
 Fix section numbering in vignette; these should start at 1 not 0 (Use # for top-level headings, ## for second-level headings, etc). There is no need for manual numbering of section headings because Rmarkdown will autogenerate these once you use the correct syntax (this Rmarkdown cheatsheet may be useful https://rmarkdown.rstudio.com/lesson-15.HTML, as too the linked documentation).
**Manual numbering is no longer done**

 Most Rmarkdown documents I've read use backticks for function names and arguments when writing Rmarkdown, e.g., suitor() and re$rank rather than bold (suitor()) or italic (suitor()). I would recommend following suit on this.

**Backticks are now used for function and option names**

 Related, the formatting of the paragraph beginning with "By default, the suitor() function returns a list containing the estimate" is messed up. I think this is an unfortunate interaction of $ being used to denote LaTeX math mode as well as being valid R code. If you change from using bold (**) or italic (*) markdown syntax to using code (```) for the variables then this issue goes away.

**Fixed**

 The chunks that show the output of str(re), str(re2), re$rank, head(Extract$W), and Extract$H[,1:3] are unclear when reading the rendered vignette because the actual calls to str(re), str(re2), re$rank, head(Extract$W), and Extract$H[,1:3] aren't shown in the rendered vignette (because the code is in a echo = FALSE and/or eval = FALSE chunk) and only their output is shown.

**Fixed**

 For future reference, you could create table1 and table2 in the vignette as a data.frame and then use knitr::kable() to create a nicely rendered table.

**knitr::kable() is now used to display tables**

Recommended
 It is strongly recommend to keep the Bioconductor-hosted git repo ([git@git.bioconductor.org](mailto:git@git.bioconductor.org):packages/SUITOR) in-sync with the GitHub-hosted git repo (https://github.com/wheelerb/SUITOR) (please see https://www.bioconductor.org/developers/how-to/git/ for documentation on this topic).

**They are now in sync**

 Consider using suppressPackageStartupMessages(library(MutationalPatterns)) in the vignette to avoid the verbose output.
**Changed**

 "I have looked at the BiocParallel package, but it is unclear how my code would change in order to use BiocParallel."
@mtmorgan, author of BiocParallel may be able to point you in a helpful direction. From what I can tell, you're currently using foreach for parallelisation, along with some custom code to detect Windows (PSOCK) vs. non-Windows machines (FORK) machines. I think BiocParallel should be able to help simplify your code by taking away some of the 'bookkeeping', but I won't make use of BiocParallel a requirement for acceptance of SUITOR because it seems you've made some effort to ensure portability of the code across machines.
**I have tried implementing BiocParallel, but it is not working yet. The problem is that there are R functions that call C functions, and the C functions are not visible to the workers. I got around this problem by using the option .packages="SUITOR" in the foreach() call, but I have not found a solution using BiocParallel yet. **

**Comment by mtmorgan** [comment] 2022-04-25 17:31
For BiocParallel this should 'just work'. For instance, `Rsamtools::idxstatsBam()` calls C code, and
```
> fl <- system.file("extdata", "ex1.bam", package="Rsamtools", mustWork=TRUE)
> bplapply(rep(fl, 2), idxstatsBam, BPPARAM = SnowParam(2))
[[1]]
  seqnames seqlength mapped unmapped
1        *         0      0        0
2     seq1      1575   1482       19
3     seq2      1584   1789       17

[[2]]
  seqnames seqlength mapped unmapped
1        *         0      0        0
2     seq1      1575   1482       19
3     seq2      1584   1789       17
```
shows that the C code is available on the workers.

If you create a branch in your git repository with your attempt at using BiocParallel, and a simple reproducible example then I would be happy to look at it.

Alternatively, if you are using the devel version (I guess you are, since this is a submitted package) you could use
```
bplapply(..., BPOPTIONS = bpotions(packages = "SUITOR"))
```
but this should not be necessary.

**Comment by PeteHaitch** [comment] 2022-04-26 00:51
Thanks @wheelerb.
**SUITOR** is almost ready for acceptance, there are just 2 things to address:

- [ ] Please uncomment the code in Sections 8 & 9.
- [ ] Martin's advice and offer of help will hopefully enable you to switch to using **BiocParallel**. I may also be help with this, but please note that such help may not be immediate owing to the in-progress release of Bioconductor 3.15 (and grant deadlines for myself).

As I mentioned, Bioconductor 3.15 is currently being released (https://bioconductor.org/developers/release-schedule/) and **SUITOR** will not be part of this release.
However, once accepted, **SUITOR** will be available in the new devel version (Bioconductor 3.16) which will then form the next release (in roughly 6 months time).

Cheers,
Pete

**Comment by wheelerb** [comment] 2022-04-27 17:47
Thank you Martin and Pete. The problem was that when I develop R packages, I often just source the R files and shared object file instead of loading the package.
The SUITOR package now uses BiocParallel. The vignette was also updated.
Sincerely,
Bill

**Comment by PeteHaitch** [comment] 2022-04-28 22:54
Thanks, Bill.
I've got grant deadlines this week but I will take a look next week.

Cheers,
Pete

**Comment by PeteHaitch** [comment] 2022-04-29 22:47
- [ ] Please take a read of '§6 For developers' of the **BiocParallel** vignette https://bioconductor.org/packages/devel/bioc/vignettes/BiocParallel/inst/doc/Introduction_To_BiocParallel.pdf
  - [ ] You're hardcoding the **BiocParallel** backend to be `SnowParam()` but the user should be able to choose/control the parallel backend (that's one of the advantages of **BiocParallel** for a user). Instead, your functions that can make use of parallel processing should have a `BPPARAM` argument that accepts a *BiocParallelParam* object. This `BPPARAM` argument could be an element of the existing `op` argument or a separate argument, depending on what you prefer. The default value of `BPPARAM` should be `bpparam()` (which will automatically invoke the user's preferred/registered parallelisation backend) or perhaps `SerialParam()`.
  - [ ] Now that you are using **BiocParallel**, you should no longer be needing `set_op_type()`

**Comment by wheelerb** [comment] 2022-05-03 14:56
Hi Pete,

I added the option BPPARAM and removed the option "type". If BPPARAM is not set and op$n.cores > 1, then BPPARAM will get set to bpparam().

Sincerely,

Bill

**Comment by PeteHaitch** [comment] 2022-05-09 22:08
Hi Bill,

The `BPPARAM` parameter should supersede the `n.cores` parameter.
As I tried to explain in https://github.com/Bioconductor/Contributions/issues/2515#issuecomment-1113846740, functions that use parallelisation should gain a `BPPARAM` argument with default value of `bpparam()`.
The `n.cores` parameter should be removed.

Cheers,
Pete

**Comment by wheelerb** [comment] 2022-05-10 12:54
Hi Pete,

When I call bpparam() on my single core Windows machine, I get the default value of bpnworkers to be 6, not 1. I would bet that most users who use the package will not have a parallel backend set up. I think the default number of cores should be one.

Sincerely,

Bill

**Comment by mtmorgan** [comment] 2022-05-10 15:50
@wheelerb this is surprising. The number of cores is determined by `parallel::detectCores()`. If this returns `NA`, then the value is set to 1, and if not to # of cores - 2. So I guess your `parallel::detectCores()` on your machine is reporting that you have 8 cores? And that `BiocParallel:::.detectCores()` returns 6? If you think most people are not going to use parallel computing, then you could use `SerialParam()` rather than `bpparam()` as a default. But I think most people in bioinformatics are using machines with multiple (sometimes many multiple!) cores; there is no explicit 'set up' required.

Can you clarify `packageVersion("BiocParallel")` in use, and the results of `parallel::detectCores()` and `BiocParallel:::.detectCores()`

**Comment by wheelerb** [comment] 2022-05-10 20:31
Hi Martin and Pete,

Sorry, the Windows machine I ran on actually had 8 virtual processors. 
I have changed the default of BPPARAM to SerialParam() instead of bbparam().

Sincerely,

Bill

**Comment by PeteHaitch** [comment] 2022-05-18 23:31
Hi @wheelerb

Thank for you making the requested changes and engaging constructively in the review process.

I'm pleased to accept **SUITOR** into Bioconductor.
Thank you to you and your co-authors for your contribution!

Cheers,
Pete

**Comment by wheelerb** [comment] 2022-05-19 21:33
Hi Pete,

Thank you very much.

Sincerely,

Bill

**Comment by lshep** [comment] 2022-05-27 16:48
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/wheelerb.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SUITOR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SUITOR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-05-27 16:48 UTC
Labels: OK, 3a. accepted
