### ISSUE TITLE
ROCpAI

### ISSUE THREAD

**Issue by juanpegarcia** [Bioconductor/Contributions#1342] opened 2020-01-15 20:26 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/juanpegarcia/ROCpAI

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-01-15 21:05
This looks like a very general purpose package that might be better suited to CRAN?

**Comment by mtmorgan** [comment] 2020-01-16 15:26
@juanpegarcia will you submit this to CRAN instead? If so please close this issue.

**Comment by juanpegarcia** [comment] 2020-01-16 20:39
Sorry for the late answer. But we think that is better suited for Bioconductor. We development this package after seeing that, when working with data gene expression arrays, there were cases we couldn't analysed. These cases are frequent when working with biologic data. So this package is interesting for investigators and bioinformaticians.
 Moreover, high-throughput data generation techniques have led to the flood of gene expression arrays, protein mass spectrometry and so on, which have become an important challenge for lifescience researchers. This package allows one to simultaneously evaluate and compare thousands of potential biomarkers. This is what that plays an important role in biomarker discovery, ranking classifiers to identifying informative genes or proteins based on differential expression.
 It's due to this that we development the package with Bioconductor's type data like "SummarizedExperiment". It maybe could be used in other fields but we are sure that it will be used in life science investigations.
Finally I wanted to add that I am a bioinformatics and this is part of my master thesis in bioinformatics.

**Comment by mtmorgan** [comment] 2020-01-23 19:59
NOTE: comments are made about specific lines of code, but code should be updated throughout the pacakge.

DESCRIPTION

- Please avoid abbreviatinos in the Title. 
- Please update the Description: field to avoid boiler plate and to clearly indicate how your package provides functionality different from other packages.
- bibtex is not a likely package for 'Depends or even Imports: (NB: the field names is `Imports:`, not "import"); if it is used in your vignette then it belongs in the `Suggests:` field.
- Use `Authors@R: ` with the format you provide, instead of `Authors:`, add `role = c("cre", "aut"))` to your name, and remove the `Maintainer:` field.

vignettes

- The directory name is `vignettes`; it is important to match on for platforms where case is important.
- Remove .Rhistory from your git checkin.
- Remove the build products, e.g., my-Vignette.html, from the git checkin. This is produced from the `.Rmd` file when the package is built (`R CMD build ROCpAI`).
- consider carefully wehter ieee.csl is required; unneccesarily complicated vignette formatting often leads to problems for long-term maintenance.
- I do not understand why the vignette has many functions define but hidden from the user. At least some of these are 'internal' functions and it should not be necessary to define them here.
- In this code
  ```
  strain <- fission@colData@listData$strain
  ```
  one should ALWAYS use the 'accessors' defined on the object, thus `colData(fission)$strain`. But I don't really understand the purpose of constructing `genes` here; the idea of a SummarizedExperiment is to coordinate manipulation of complicated data, but this code undoes this benefit. For instance one might
  ```
  points_curve(colData(fission)$strain, assay(fission)["SPNCRNA.1080",])
  ```
- Again the defintion of complicated functions in the vignette, `points_curve()` and `McpAUC()` seems not helpful -- if these functions are already in the package, they do not need to be re-defined here. If they are not yet in the package, then perhaps they should be added to the package?
- please adopt a standard function naming convention; the Bioconductor recommendation is `lowerCamelCase()` so `pointsCurve()` and `mcpAUC()` might be possible names.
- use `citation("ROCpAI")` for standard package citation format.

R

- make sure that the `@examples` code lines do not exceed 80 characters wide, otherwise the format poorly on some help displays.
- when documenting parameters, adopt a convention where the type of the argument is given clearly and unambiguously, e.g., MCpAUCboot.R
  ```
  #' @param seed Seed
  ```
  might become
  ```
  #' @param seed integer(1) random number seed.
  ```
  HOWEVER, there is no reason for your function to manipulate the random number seed, and this is strongly discouraged. If the user wishes for reproducibility, they may simply `set.seed(123)` in their own script before calling your function.
- please consider using the formatR package or similar to arrive at a more standard representation of your code -- you adopt conventions that make the code difficult to read.
- as a general rule, start each user-facing function with checks on the arguments; provide default values if appropriate, e.g., for MCpAUCboot
  ```
  stopifnot(
      is.data.frame(dataset) || is(dataset, "SummarizedExperiment"),
      is.numeric(low.value), length(low.value) == 1, 
      low.value > 0 && low.value < 1,
      ...
  )
  ```
  by asserting these values first, the user is informed immediately of incorrect arguments, your own code can then focus on implementing the algorithm rather than repeatedly checking for validity, and your code is more robust.
- It is usually better to write simple sequential code rather than 'nesting' for compactness, thus
  ```
  McpNA <-assay(McpAUC(dataset, low.value=low.value, up.value = up.value ))$St_pAUC
  ```
  might be better written (more readable, easier to debug) as
  ```
  value <- McpAUC(dataset, low.value=low.value, up.value = up.value)
  McpNA <-assay(value)$St_pAUC
  ```
- avoid use of `1:XXX`, e.g., `for (i in 1:dim(result_boot$t)[2])` which results in surprises when XXX is 0. Use `seq_len()` or `seq_along()` instead, e.g., `for (i in seq_len(ncol(result_boot$t)))`
- do not use `  if (class(dataset)=="RangedSummarizedExperiment") {` but instead `is(dataset, "RangedSummarizedExperiment")`. Using `class(X) == ` fails when `class()` returns a vector of length greater than 1. Here the requirement is not `RangedSummarizedExperiment` but simply `SummarizedExperiment`.

**Comment by mtmorgan** [comment] 2020-02-10 18:25
Please post a comment here indicating when you hope to have a response available.

**Comment by juanpegarcia** [comment] 2020-02-11 13:54
Thanks for waiting. I think that the February 23th everything should be fixed. However I'll try to do it sooner

**Comment by juanpegarcia** [comment] 2020-02-21 23:34
The package is ready

**Comment by lshep** [comment] 2020-02-28 13:30
Please make sure your [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) is initialized and do a version bump in your package DESCRIPTION to receive a new build report that reflects your changes.

**Comment by mtmorgan** [comment] 2020-03-12 07:28
Please remove the files .RData and .Rpoj.user from your git repository. Please rename the folder Vignettes to 'vignettes' (lower-case). Please remove Vignettes/vignettes.html.

Please briefly summarize the changes you made to your package in response to the earlier comments.

**Comment by juanpegarcia** [comment] 2020-03-27 09:07
@mtmorgan I have done the solicited changes

**Comment by mtmorgan** [comment] 2020-04-06 22:11
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/juanpegarcia.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("ROCpAI")`. The package 'landing page' will be created at

https://bioconductor.org/packages/ROCpAI

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-06 22:11 UTC
Labels: 3a. accepted, OK
