### ISSUE TITLE
curatedAdipoRNA: A Curated RNA-Seq Dataset of MDI-induced Differentiated Adipocytes (3T3-L1)

### ISSUE THREAD

**Issue by MahShaaban** [Bioconductor/Contributions#994] opened 2019-02-06 05:37 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MahShaaban/curatedAdipoRNA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by nturaga** [comment] 2019-02-21 19:42
# curatedAdipoRNA review

## General

* Consider removing the "curated" otherwise, it should match the expectations of the curated(*) set of packages. Please take a look at curatedOvarianCancer package, as follow up. (http://bioconductor.org/packages/release/data/experiment/html/curatedOvarianData.html)

## DESCRIPTION

* The Description section needs to be like a paper abstract, with more information.

## NAMESPACE 

* Not needed, since there are no exported functions.

## NEWS

* The NEWS file needs to be parsable by `utils::news()`.

## inst

* `inst/extdata` is not needed. Just need to provide the actual "data/". The package becomes very heavy because of the `extdata`(51MB)

## data

* The name of the dataset should be more descriptive and not `gene_counts.rda`.

## tests

* You may keep the tests, but it seems like an overhead and just checking if the data are constructed right.

## vignette

* Please add the Bioconductor installation instructions via `BiocManager` as opposed to installing from github.

@lwaldron will be able to better review your package. Please wait for an update from him.

**Comment by MahShaaban** [comment] 2019-02-22 03:00
Thanks @nturaga 

I made the following changes as you suggested

* Updated **Description** field in the `DESCRIPTION` file
* Removed `tests/` and `inst/extdata`
* Renamed `gene_counts.rda` to `adipo_counts.rda`
* Added the package installation instructions to the vignette usign `BiocManager`

A few other things:

* Removing the `NAMESPACE` file caused an error on the build system!
* I am not sure what is wrong with the `NEWS` file. When I use `utils::news(package = 'curatedAdipoRNA')`, the news page opens with no errors or warnings (in Rstudio viewer)
* Is there reference/guidelines of the expectations for the curated* set of packages?

**Comment by lwaldron** [comment] 2019-02-22 06:08
Nice contribution, @MahShaaban! I like your use of a Docker image for the preprocessing, this nifty `bib2df` package, your reproducible scripts, use of `RSE`, and review & inclusion criteria. I do agree that these curated(Ovarian,CRC,Bladder,Metagenomic,TCGA) packages share characteristics that I think have created expectations of:
* as much per-sample metadata as possible in the (`colData/pData`), standardized for consistency across studies, with regexes and unit tests to guarantee there are no syntax errors. Are *time* and *stage* the only per-sample original metadata available for 2+ studies, or are other properties deemed irrelevant widely enough available? 
* documentation of each dataset in man pages, plus tables of summary statistics in the vignette. These allow users to browse through the data before installing the package.
* documentation of all metadata (what is available, what it means)
* data analysis examples in the vignette showing what these data can be used for, demonstrating the rationale for building the data package.

Some more suggestions to make your metadata more accessible and do a bit of clean-up (I was still using the `gene_counts` object). Sorry I hope this isn't overwhelming, and I'm only raising it all because of my expectations for a "curated*" package:
* Currently `metadata(gene_counts)` causes endless scrolling, you could avoid this by using `S4Vectors::SimpleList` objects instead of `list`. Same for the nested `list` objects. 
* The metadata slot contains lists-within-lists-within-a-list - is there a way you could simplify this, or provide an accessor function? I found it difficult to find metadata due to this complexity, especially because some of the list elements are so long. One suggestion is that metadata about samples (like `metadata(gene_counts)$qc`) usually belongs in `colData` not `metadata`.  It's easier to find there and it is then linked to the assay data. Note that a column of `colData` can be a `S4Vectors::SimpleList`, which would allow you store information about whatever these underscored names are (would be good to document what they are, I'm guessing library preps split across lanes?).
* `metadata(gene_counts)[[1]]` has a "FILE" column providing paths to the paper on your computer
* The vignette says "Pre-processed data in `inst/extdata`" but this directory is blank (as it probably should be if these are the `assay` data anyways?)
* There's a lot of metadata in the `qc` list elements, which is great, but some documentation is needed to know what it means or how to use it. A vignette example of setting a some QC thresholds would help a lot.
* Here's an example of what I mean by metadata that is hard for a user to understand. What should I think about these PASS/WARN/FAIL entries, is there some suggested way to use them to set a QC threshold?
```
> metadata(gene_counts)$qc$SRR988310_2$summary
# A tibble: 13 x 1
   Summary
   <chr>  
 1 status 
 2 PASS   
 3 PASS   
 4 WARN   
 5 PASS   
 6 WARN   
 7 WARN   
 8 PASS   
 9 PASS   
10 FAIL   
11 PASS   
12 PASS   
13 FAIL 
```
* What are the "quality" and "reason" columns? I guess these are the recommended things to use for QC, but need documentation:
```
> table(gene_counts$quality)

 0  1 
 4 94 
> table(gene_counts$reason)

           0 low_per_base 
          94            4 
```

Thanks for your hard work, it's great that you're increasing the utility of publicly available data and using `RangedSummarizedExperiment` to do it.

**Comment by MahShaaban** [comment] 2019-02-22 10:53
Thanks, @lwaldron for your review.

I think I can provide more metadata, documentation, and examples in the vignette to meet these expectations. I will commit these changes soon then you can tell me what you think. 
I just have one point to make about this. I only included in `colData` the information about the samples/runs that I think are relevant to the potential future analyses. I didn't include the original metadata associated with the **GSE** and **SRR** IDs since they are reported in different formats and styles and are not expected to be consistent across studies. These metadata can be accessed using other R packages such as `GEOmetadb` and `SRAdb`. So should I collect these metadata and add them to `colData`?

Here is a reply to the issues you raised
* I used the `S4Vectors::SimpleList` instead of `list` for the `qc` item of the metadata.
* The object `metadata(adipo_counts)$qc` is a list of lists of `qc_read` objects as I menstion in the vignette. This is compatible with the `fastqcr` methods which can be used to summarize and visualize the `fastqc` output. That's why I haven't tried to manipulate the object further. Maybe if I add an example in the vignette it would useful. I added `qc` and `studies` to `metadata` rather than `colData` because I wanted to keep them in the original formats for them to be easily used with `fastqcr` and `bib2df` directly. The other reason is the relations to the samples will not be one-to-one since `qc` reports the quality metrics per file and `studies` the information for per study.
* I removed the column `FILE` from `metadata(adipo_counts)[[1]]`.
* The files in `inst/extdata` were removed. I belive I edited the docs accordingly, but will double check that. 

I will add an example of using the package including using `qc` and hopefully this addresses the last three points and improves the documentation in general.

**Comment by nturaga** [comment] 2019-02-23 18:33
Hi @MahShaaban 

Once you have made the changes provided by @lwaldron and me, please leave a detailed reply point by point about each change.

This will help us go through your package quicker for a second review.

**Comment by MahShaaban** [comment] 2019-02-24 01:34
Hi @nturaga 
I described the changes I made in reply to your comments and @lwaldron s' in my previous comment.

**Comment by lwaldron** [comment] 2019-02-24 05:29
@MahShaaban thanks for the improvements, the vignette is much better. The added rationale and DESeq2 example are especially helpful. I still had difficulty telling what your response is to some of the points however (see further below), and noticed a few follow-up or new points:

* you should Depend on `SummarizedExperiment`, not Suggest, since anything you do with the package requires `SummarizedExperiment` from the first step
* also consider adding a `LazyData: TRUE` directive in the DESCRIPTION (e.g. see http://kbroman.org/pkg_primer/pages/data.html)
* For a `SimpleList` object, don't use `lapply(as.list(myS4list, etc))`, just include a `library(S4Vectors)` in the vignette then use `lapply(myS4list, etc)`
* Your current version however (` curatedAdipoRNA * 0.99.7  2019-02-24 [1] Github (MahShaaban/curatedAdipoRNA@1a50c48)`) still has a `list` in the metadata. But before fixing that, I'd really like to know your rationale for the current metadata structure - it seems far more opaque and to result in more complicated downstream code than storing both elements in the colData would.
* you're right that it makes sense to leave the `qc_read` objects intact. But (same point as above) I still don't see the rationale for putting sample-related metadata in the `metadata` slot rather than in `colData`, which would give you formal linkage and subsetting with the rest of the `colData` and `assay` data. It seems like your Vignette lines 275-284, plus `bind_rows(.id = 'run')`, `  group_by(run) %>%`, and `studies$BIBTEXKEY[studies$BIBTEXKEY %in% se3$bibtexkey]` are all work-arounds that are necessary because you didn't group the QC data in the first place and match it to rows in `colData`. What I'm talking about is just this (I have no idea if the samples are correctly aligned to qc in the last line here, but if you align them correctly no one will ever have to worry about that again :) ):
```
> qc <- metadata(adipo_counts)[[2]]
> srr <- sub("_.", "", names(qc))
> adipo_counts$qc <- List(split(qc, srr))
> adipo_counts$qc
List of length 98
names(98): SRR1048170 SRR1048172 SRR1048174 SRR1048176 ... SRR988308 SRR988309 SRR988310
```
The only drawback I see currently is that it makes `colData(adipo_counts)` difficult to view - I've opened an issue at https://github.com/Bioconductor/S4Vectors/issues/29. Is there any other reason not to use the `colData` for your QC data?

* We try to discourage advising:
`devtools::install_github('MahShaaban/curatedAdipoRNA')`, because 1) it circumvents Bioconductor's Continuous Integration system and development/release cycle that tests packages against current versions of their dependencies to help ensure installability and testedness, and 2) when you're doing such circumvention anyways, your suggested line will error unless the Bioconductor dependencies are already installed; `BiocManager::install('MahShaaban/curatedAdipoRNA')` does the same thing (even using devtools) but can install Bioconductor dependencies.

Did you respond to these?
* What are the "quality" and "reason" columns?
* as much per-sample metadata as possible in the (`colData/pData`), standardized for consistency across studies, with regexes and unit tests to guarantee there are no syntax errors. Are _time_ and _stage_ the only per-sample original metadata available for 2+ studies, or are other properties deemed irrelevant widely enough available?
     - It's up to you if you just curate _time_ and _stage_, but the documentation should 
* documentation of each dataset in man pages, plus tables of summary statistics in the vignette. These allow users to browse through the data before installing the package.
     - I still don't see documentation of the datasets in the man pages or vighette?
* documentation of all metadata (what is available, what it means)
     - The idea is to make everything that is provided clear from the documentation, not just _time_ and _stage_. E.g. someone perusing the documentation doesn't know that most of these exist, and someone using the data object won't necessarily know what they all mean:
```
> colnames(colData(adipo_counts))
 [1] "id"               "study"            "pmid"             "time"            
 [5] "stage"            "bibtexkey"        "run"              "submission"      
 [9] "sample"           "experiment"       "study_name"       "library_layout"  
[13] "instrument_model"
```

**Comment by MahShaaban** [comment] 2019-02-25 03:59
Thanks @lwaldron 

Regarding the follow-up points:
* I moved `SummarizedExperiments` to **Depends** field of the `DESCRIPTION` file. This resulted in two new Notes on `devtools::check()`. These might be because of my local setup, so will see if they persist on the build system

```r
❯ checking installed package size ... NOTE
    installed size is 12.0Mb
    sub-directories of 1Mb or more:
      data  11.7Mb

❯ checking dependencies in R code ... NOTE
  Package in Depends field not imported from: ‘SummarizedExperiment’
    These packages need to be imported from (in the NAMESPACE file)
    for when this namespace is loaded but not attached.
```
* I added `LazyData: TRUE` to the `DESCRIPTION` file.
* I updated the vignette to load `S4Vectors` library and use `lapply` on the `SimpleList`, as you suggested before.
* As for the last two points, here is my rational for using `metadata` rather than `colData` for adding `qc` and `studies` to the object.
  1. The data in `qc` and `studies` don't map directly to the samples. Each study could have multiple samples and each sample could have multiple files (and its qc data).
  2. I wanted to preserve the original format of the objects; `qc_read` in case of `qc` and a `data.frame` compatible with `bib2df` in case of the studies. `metadata` as far as I know is the only slot in `SummarizedExperiment` objects that allow adding arbitrary objects that don't map to the sample directly.
That's said I am open to your suggestion to add `qc` to `colData`, however I don't see how this would reduce the need for cleaning up (in the example section of the vignette) since it is done because of how `qc_read` is structured and not due to the mapping or where `qc` is added. Finally, I agree that this issue can be improved if the object can be added directly to `colData` without compromising `colData` itself.
* I removed the install from GitHub instructions from the vignette and the readme.

Here are a few changes I made in response to the original points:
* I removed the "quality" and "reason" columns. Those were part of an analysis I am doing locally and were not supposed to be there in the first place.
* Here, I added a table to the vignette which has a description of each column in `colData`. Also, I referred to using the provided identifiers to query other Bioconductor packages `GEOmetadb` and `SRAdb` to get the metadata provided during the submission of the original data in the repositories. (this might also answer to the fourth point)
* I thought I documented the dataset in a man page. Please, elaborate on what further documentation should be done.

**Comment by lwaldron** [comment] 2019-02-27 00:20
Getting there!

> I thought I documented the dataset in a man page. Please, elaborate on what further documentation should be done.

Did you look at curatedOvarianData vignette and man pages as an example? They provide sample sizes and summary statistics for each curated dataset. The last time I looked, there was no documentation at all of the datasets curated by your package, only citations within the metadata.

Can I ask you more about these responses?

> * The data in `qc` and `studies` don't map directly to the samples. Each study could have multiple samples and each sample could have multiple files (and its qc data).

Doesn't the solution I suggested (using a `SimpleList` to aggregate runs by samples, so that its length is equal to the number of rows in `colData`) resolve the mapping of runs to samples?

> * I wanted to preserve the original format of the objects; `qc_read` in case of `qc` and a `data.frame` compatible with `bib2df` in case of the studies. `metadata` as far as I know is the only slot in `SummarizedExperiment` objects that allow adding arbitrary objects that don't map to the sample directly.

Didn't that solution also preserve the original `qc_read` objects, just placing them within a nested List that has one element per sample, and multiple runs within each element? 

I guess the `bib2df` `data.frame` seems like more of a natural fit for the metadata since it is study-level and you only use it for making bibliographies, not for QC and selection of the assay data.

>   That's said I am open to your suggestion to add `qc` to `colData`, however I don't see how this would reduce the need for cleaning up (in the example section of the vignette) since it is done because of how `qc_read` is structured and not due to the mapping or where `qc` is added. Finally, I agree that this issue can be improved if the object can be added directly to `colData` without compromising `colData` itself.

Presumably you could define a function that takes a `qc_read` object and returns a TRUE/FALSE result of your QC threshold. Then lapply's implicit nested looping makes it easy to apply this over your nested list of `qc_read` objects. For example, pretend `qc_read_list` is a nested SimpleList of `qc_read` objects:
```
> library(S4Vectors)
> (qc_read_list <- List(a=1, b=c(1, -1), c=c(1, 1)))
NumericList of length 3
[["a"]] 1
[["b"]] 1 -1
[["c"]] 1 1
```
And `myqcFun` defines a QC threshold you want to set, involving original `qc_read` functions applied to a `qc_read` object:
```
> myqcFun <- function(x) x > 0
```
`lapply` will apply this function over your nested list:
```
> (pass <- List(lapply(qc_read_list, myqcFun)))
LogicalList of length 3
[["a"]] TRUE
[["b"]] TRUE FALSE
[["c"]] TRUE TRUE
```
And another rule then applied to the resulting list could require e.g. that every run passes QC, or a majority, etc:
```
> (allpass <- vapply(pass, all, TRUE))
    a     b     c 
 TRUE FALSE  TRUE 
```
And as long as your `qc_read_list` was a `SimpleList` column in `colData`, then this `allpass` vector could be used as a column of `colData` or used for subsetting. Isn't that a lot easier and safer than having to use a list in `metadata` where the list elements have no semantic relationship to the `colData` rows?

**Comment by MahShaaban** [comment] 2019-02-27 01:33
Thanks, @lwaldron, and apologies if this is taking longer than it should.

Now I see what you mean by documenting the datasets. If I understand correctly you mean something like table 1 in the vignette of `curatedOvarianData` which I can add to my vignette. The other thing I noticed it that `curatedOvarianData` has each dataset/series as a separate entry in `data/` and a corresponding `man/` page. In my case, I have only one object in `data/` and one `man/` page. So do you think it is necessary to have each series as a separate entry as well? If so, is there a way you suggest to automate the production of these `.Rd`? I know of using `roxygen` but only for documenting datasets that exist as data objects in the package.

I will use the method you suggested to add `qc` nested lists to `colData`. 

I think [`fastqcr`](https://github.com/kassambara/fastqcr) can provide the functionality you suggest I add to the package. The only issue, as far as I can tell, is that `fastqcr` always requires the original `fastqc` output files when dealing with multiple runs. I will open an issue on their page to see if they can allow a list of `qc_read` objects as input.

**Comment by lwaldron** [comment] 2019-03-01 14:43
Thanks @MahShaaban, your table "Summary of the studies in the dataset" fits the need. I only see one more required item, then your package will fit in nicely with the *curated** family:
* update `?adipo_counts` to reflect what is now contained in `@metadata` and `@colData`

And some optional items:
* If you are planning on adding new datasets over time I would suggest generating the numbers in this table from `adipo_counts` instead of hard-coding it, but that's up to you. 
* I agree there's no need for per-dataset man pages since you put everything together in one `SummarizedExperiment`, but I think you should include a reference to this table in the `?curatedAdipoData` man pages.
* If you are planning on adding more datasets, I would strongly recommend a unit test that makes sure all the samples you expect to be present are exactly the ones present in `adipo_counts`, to prevent accidental dropping of samples or adding of unexpected samples during scripted updates (all these things have happened to me!).

**Comment by MahShaaban** [comment] 2019-03-02 06:19
Thanks @lwaldron . In this last push, I made the following changes based on your suggestions:
* Updated the the `colData` and `metadata` parts of `?adipo_counts`
* I add a chunk of code to generate the "Summary of the studies in the dataset" table in the vignette.
* I updated the `?curatedAdipoData` to refer to the documentation of the datasets.

**Comment by lwaldron** [comment] 2019-03-02 13:28
Thanks for your hard work and nice contribution, Mahmoud. It looks ready to
me.

>

**Comment by nturaga** [comment] 2019-03-03 20:20
Thanks @lwaldron for the guiding @MahShaaban through the package submission/development for a "curated" family of packages. This will be useful for future reviews of other curated* data packages. 

Great work @MahShaaban. Your package is accepted to Bioconductor. 

Best,

Nitesh

**Comment by mtmorgan** [comment] 2019-03-05 17:26
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MahShaaban.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("curatedAdipoRNA")`. The package 'landing page' will be created at

https://bioconductor.org/packages/curatedAdipoRNA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2019-03-05 17:26 UTC
Labels: 3a. accepted, OK
