### ISSUE TITLE
(inactive) Optimal p-value weighting with independent information (data and simulations)

### ISSUE THREAD

**Issue by mshasan** [Bioconductor/Contributions#396] opened 2017-06-09 10:51 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: AdditionalPackage: https://github.com/mshasan/OPWpaper

Confirm the following by editing each check box to '[x]'

- [ x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x ] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x ] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x ] The 'devel' branch for new packages and features.
- [ x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment] 2017-06-09 11:13
I don't think this package is appropriate for Bioconductor. It seems from the Description like it is designed for 'reproducible research' rather than software that implements functions that are useful across different analyses. It doesn't have a vignette, which is a really central aspect of reproducible research and requirement for Bioconductor packages. The package contains functions that implement possibly useful calculations, but the interface to these functions is ad hoc and not amenable to reuse or interoperability across Bioconductor work flows.

I also don't understand the relationship between this package and your [earlier submission][]. Please elaborate.

[earlier submission]: https://github.com/Bioconductor/Contributions/issues/395

**Comment by mshasan** [comment] 2017-06-09 11:29
@mtmorgan Actually, when I was reading the instructions about linking webhook that was sent to me earlier, I found that I can add additional packages which are related to the previous package "OPWeight". That's why I added. I have not written the vignettes yet probably by this weekend I will be able to finish developing the vignettes. It was my misunderstanding.

Regarding the relevance of this package to Bioconductor, there are four functions that are reusable and others are helpful if one wants to conduct simulations, especially using my method. In this packages, I essentially demonstrated how to apply the method I developed via simulations and data. I hope that will be more clear once I updated the vignettes.

Thank you

**Comment by mtmorgan** [comment] 2017-06-09 11:30
Why are the functions in this package not included in the earlier submission?

**Comment by mshasan** [comment] 2017-06-09 11:38
Because in the previous package, I solely showed the method that I developed, but in the later one I showed a comparative study between several methods. For your convenience, I can referee two Bioconductor packages "IHW" and "IHWpaper". In the first, the author showed his method and in the second he showed comparative study results. My two packages would be similar.

**Comment by mtmorgan** [comment] 2017-06-09 11:41
So it seems like the main problem here is that your package is missing the central piece -- the vignette?

**Comment by mtmorgan** [comment] 2017-06-09 11:42
I closed this issue. Reopen it with a note to @mtmorgan when your package is complete.

**Comment by mtmorgan** [comment] 2017-06-09 11:44
Please also make sure that has biocViews terms from the [ExperimentData][] ontology.

[ExperimentData]: http://bioconductor.org/packages/release/BiocViews.html#___ExperimentData

**Comment by mshasan** [comment] 2017-06-11 17:04
@mtmorgan package is now complete

**Comment by mshasan** [comment] 2017-06-13 14:39
@mtmorgan I am wondering whether do I need to open a new issue for this package or will you update the existing issue?

**Comment by mshasan** [comment] 2017-06-13 16:56
@lshep This package is an additional package depending on another package "OPWeight", which is currently under review by Bioconductor. That's why it is producing the error.

**Comment by lshep** [comment] 2017-06-14 09:45
@mshasan I am away on vacation this week but will review when I am back.  Keep in mind, we will not accept this package until the dependent OPWeight is accepted, esp since we will not be able to have a full build report until OPWeight is available.  In the meantime, as OPWeight gets reviewed, please apply any similar changes that may be suggested as far as coding standards and syntax in OPWeight to OPWpaper.   I will provide a more detailed review of the package when I get back.

**Comment by vobencha** [comment] 2017-06-23 16:05
Hi @mshasan,
We have reassigned both your data and software packages to me so one person can review both.
For starters, please address these issues in the Single Package Builder output:

1) non-portable paths
```
* checking for portable file names ... NOTE
Found the following non-portable file paths:
  OPWpaper/vignettes/FWER_and_FDR_cache/html/fdr_ey_notequals_et2_9404802ef1bebe4fd4a29a160e5426f5.RData
  OPWpaper/vignettes/FWER_and_FDR_cache/html/fdr_ey_notequals_et_f14ecd09d311ed64884791527da9b689.RData
  OPWpaper/vignettes/FWER_and_FDR_cache/html/fwer_ey_notequals_et2_66785310a27dacda55b0b87bdf4b790d.RData
...
```
2) reduce example runtime
```
* checking examples ... [108s/111s] OK
Examples with CPU or elapsed time > 5s
                              user system elapsed
probRel_filterVstest_effect 77.466  0.495  80.136
simu_fwer                   19.468  0.252  20.472
```
3) use TRUE and FALSE
```
* Checking for T...
    Found T in R/weight_byEffect_cont.R (line 79, column 46)
    * WARNING: Use TRUE instead of T (found in 1 files)
* Checking for F...
    Found F in vignettes/Power.Rmd
    * WARNING: Use FALSE instead of F (found in 1 files)
```
4) man pages need non-empty \value and run-able examples
```
* Checking man pages...
    * WARNING: Add non-empty \value sections to the following man
      pages: man/weightSum_by_c.Rd
* Checking exported objects have runnable examples...
    * ERROR: At least 80% of man pages documenting exported objects
      must have runnable examples. The following pages do not:
      nice_plots.Rd, prob_weight_plots.Rd, ranksProb_compare_plots.Rd,
  ranksProb_compare.Rd
```
When you've made the changes please bump the version to 0.99.2 and resubmit. Once these preliminary errors are cleaned up I'll do a full review.
Thanks.
Valerie

**Comment by mshasan** [comment] 2017-07-22 11:43
@vobencha Would you be able to look at my vignette code, especially the first few lines where I used "load()" to load .RDATA. I tried many different ways but could not figure out the problems. My vignette code passed R CMD check but does not pass in the Bioconductor system. It seems that Bioconductor system is unable to load my saved data from the repository.

**Comment by vobencha** [comment] 2017-07-24 21:45
I'll take a look at this tomorrow.
Valerie

**Comment by vobencha** [comment] 2017-07-25 15:57
Hi,
When you use load() the file type must be saved using save() and must be location in the data/ directory of the package.

I believe this is being submitted as a data package so we need to get it in the correct format. Data packages have a slightly different structure than software. Here are some examples that you can download and look at the source code:
http://www.bioconductor.org/packages/release/BiocViews.html#___ExperimentData

Please re-org the package so it has these directories and files:
R/
tests/
man/
vignettes/
data/: All .rds files go here
inst/extdata/: All non-.rds files go here
external_data_store.txt: This file states where the data files are. For example, here is what the file looks like in the minfiData package:
```
~/minfiData >cat external_data_store.txt 
data
inst/extdata
```

Valerie

**Comment by vobencha** [comment] 2017-07-26 12:12
fyi I'm out of the office July 26 - Aug 2.
Valerie

**Comment by vobencha** [comment] 2017-08-14 12:40
Checking in. Are you planning to submit a new version of this data package?
Valerie

**Comment by mshasan** [comment] 2017-08-14 12:45
@vobencha Thank you for the reminder. Yes, I will modify the package. I am currently writing my Ph.D. dissertation, therefore, struggling finding time.

**Comment by vobencha** [comment] 2017-08-24 13:40
Should we close this issue and you can re-submit when you're ready? There is no rush to add the data package.

**Comment by mshasan** [comment] 2017-08-24 14:05
Yes, you can close. I will reopen once I finish my dissertation defense.
Thank you



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=shakilmohamad7@gmail.com&idSignature=22>

**Closed** 2017-08-24 14:07 UTC
Labels: 2. review in progress, 3b. declined, ERROR, VERSION BUMP REQUIRED
