### ISSUE TITLE
PanViz submission

### ISSUE THREAD

**Issue by LucaAnholt** [Bioconductor/Contributions#2505] opened 2022-01-15 19:21 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/LucaAnholt/PanViz

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-01-18 18:50
```
--- re-building ‘my-vignette.Rmd’ using rmarkdown
Loading required package: igraph

Attaching package: 'igraph'

The following objects are masked from 'package:stats':

    decompose, spectrum

The following object is masked from 'package:base':

    union

Loading required package: foreach
Warning in if (colour_groups == TRUE) { :
  the condition has length > 1 and only the first element will be used
Warning in vattrs[[name]][index] <- value :
  number of items to replace is not a multiple of replacement length
Quitting from lines 112-144 (my-vignette.Rmd) 
Error: processing vignette 'my-vignette.Rmd' failed with diagnostics:
could not find function "hex"
--- failed re-building ‘my-vignette.Rmd’

SUMMARY: processing the following file failed:
  ‘my-vignette.Rmd’

Error: Vignette re-building failed.
Execution halted
```
Please try not to depend on tcltk.  Widgets are popping up during R CMD check.  Please be sure your package passes R CMD check and comment here when committed.

**Comment by LucaAnholt** [comment] 2022-01-30 16:25
Hi, apologies about that! I think it should be passing R CMD now, however, on my windows machine I get the the warning: "qpdf is needed for checks on size reduction of pdfs". I'm not entirely sure what's the best step to troubleshoot this warning, as some what I've read suggests to ignore this problem? https://community.rstudio.com/t/qpdf-is-needed-error-package/75485. Thanks!

**Comment by vjcitn** [comment] 2022-02-06 10:55
This is looking better and can begin review.  Please run BiocCheck in your package root folder.  You will see
```
BiocCheck FAILED.
$error
[1] "At least 80% of man pages documenting exported objects must have runnable examples. The following pages do not:"               
[2] "Maintainer must add package name to Watched Tags on the support site; Edit your Support Site User Profile to add Watched Tags."

$warning
[1] "Import tibble, devtools, svMisc, stringi, hash in NAMESPACE as well as DESCRIPTION."             
[2] "Add non-empty \\value sections to the following man pages: man/reaction_cleanup.Rd, man/retry.Rd"

$note
 [1] "Consider clarifying how 1 object(s) are initialized. Maybe it is part of a data set loaded with data(), or perhaps part of an object referenced in with() or within()."           
 [2] "Update R version dependency from 3.5.0 to 4.2.0."                                                                                                                                 
 [3] "The Description field in the DESCRIPTION is made up by less than 3\nsentences. Please consider expanding this field, and structure it as a\nfull paragraph"                       
 [4] " Avoid sapply(); use vapply()"                                                                                                                                                    
 [5] " Avoid 1:...; use seq_len() or seq_along()"                  
```
and more!  If you address these issues early on it will accelerate the review process.

**Comment by vjcitn** [comment] 2022-02-06 10:55
I'd also ask whether you could interoperate with the gwascat package and BiocParallel.

**Comment by LucaAnholt** [comment] 2022-02-20 15:22
> I'd also ask whether you could interoperate with the gwascat package and BiocParallel.

Hi, I've since realised that my package probably insinuated too much of a reliance on GWAS Catalog as source for summary-level GWAS data, as at the time of writing this package I was unaware of other GWAS databases. To this end, I've updated the package description file and vignette to reflect the broader scope of this package, whereby users can provide summary-level GWAS data from other sources such as GWAS Central, or even provide their own datasets. I hope that's ok.

**Comment by Kayla-Morrell** [comment] 2022-03-08 20:26
@LucaAnholt,
Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION

- [ ] SUGGESTION: The Description field in the DESCRIPTION is made up by less
  than 3 sentences. Please consider expanding this field and structure is as a
full paragraph.
- [ ] REQUIRED: Update R version dependency from 4.1.0 to 4.2.0.
- [ ] REQUIRED: You are submitting a Software package so this should be the only
  term present for 'BiocType'.

## NEWS

- [ ] SUGGESTION: Consider adding a NEWS file so your package news will be
  included in Bioconductor release announcements.

## Data

- [ ] REQUIRED: Since there is raw data included in the `inst/extdata`
  directory there needs to be documentation for this data present in the
`inst/script` directory. Scripts in this directory can vary but should clearly
document how the data was genereated and include source information. It should
include source URLs and any key information regarding filtering or processing.
It can be executable code, sudo code, or a text description. Users should be
able to download and roughly reproduce the file or object that is present as
data. 

## Vignette

- [ ] REQUIRED: The only code block that is allowed to include `eval = FALSE` is
  the Installation code. All other code blocks should be executable.
- [ ] REQUIRED: Bioc.bib doesn't seem to be used here so it should be removed.
  Also the IMON_method_edit.png file doesn't seem to be used and should be
removed.

## Man pages

- [ ] SUGGESTION: We encourage having a package man page with an overview of the
  package and links to main functions. Users should be able to have a relevant
page display with `?<package name>`.
- [ ] REQUIRED: Add runnable examples to the following man pages which documents
 exported objects:
        Get_KEGG_Data.Rd
- [ ] REQUIRED: Usage of dontrun{}/donttest{} found in man page examples. This
  is discouraged and generally not allowed. If it is absolutely necessary
donttest{} should be used over dontrun{}; donttest{} requires valid R code while
dontrun{} does not.
- [ ] SUGGESTION: checking Rd line widths. Rd files 'GWAS_data_reader.Rd' and
  'get_grouped_IMON.Rd' \examples lines wider than 100 characters. These lines
will be truncated in the PDF manual.

## R code

- [ ] SUGGESTION: Undefined global functions or variables:
      all_of from
- [ ] REQUIRED: Avoid sapply(); use vapply().
- [ ] REQUIRED: Avoid 1:...; use seq_len() or seq_along().
- [ ] REQUIRED: Avoid 'cat' and 'print' outside of 'show' method.
- [ ] REQUIRED: Avoid using '=' for assignment and use '<-' instead.
- [ ] REQUIRED: Avoid redundant 'stop' and 'warn*' in signal conditions.
- [ ] REQUIRED: Avoid 'suppressWarnings'/'*Messages' if possible (found 3
  times).
- [ ] SUGGESTION: For formatting reasons, consider shorter lines. There are 384
  lines that are > 80 characters long.
- [ ] SUGGESTION: For formatting reasons, consider multiples of 4 spaces for
  line indents. There are 810 lines that are not.


Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2022-03-29 13:37
@LucaAnholt - Just checking in to see if there has been any progress made on the review I posted. We generally like to see changes made in 2-3 weeks to be sure the package is actively being work on. Please keep in mind that the deadline to accept new packages into the Bioconductor 3.15 release is 4/20. Any packages accepted after this date will be included in the next release.

Best,
 Kayla

**Comment by LucaAnholt** [comment] 2022-03-29 13:52
Hi @Kayla-Morrell, apologies about being so slow! I have actually implemented all of the required changes except for: 

```
"REQUIRED: Add runnable examples to the following man pages which documents
exported objects:
Get_KEGG_Data.Rd"
```
and 

```
`REQUIRED: The only code block that is allowed to include eval = FALSE is
the Installation code. All other code blocks should be executable.
```

I was actually meaning to ask, the Get_KEGG_Data.R function is a bit slow (~10/15 mins), due to the KEGGREST API limiting get requests to only 10 queries at one time. Hence, I wrote it so that this function doesn't have any runnable examples and has eval = FALSE in the vignette. However, I will note that this isn't an essential function to use the package, I've only included it in the case that a user needs the latest image of KEGG. 

Kind regards, 
Luca

**Comment by Kayla-Morrell** [comment] 2022-03-31 17:51
@LucaAnholt - Thank you for clarifying. All exported functions need to be tested in some way to ensure they are working they way they are intended. There should be one runnable example of the function whether that be in a man page example, executable vignette code, or unit testing. I'm not sure the specifics of the function, but if there is a way to test a small subset of data to lessen the queries that would be ideal. Both of the requirements above do not need to be met as long as one is able to be evaluated. Let me know if I can help further.

Best,
Kayla

**Comment by LucaAnholt** [comment] 2022-04-04 06:33
@Kayla-Morrell Thanks for this! Just to let you know that I've updated the function further so that it only queries new biochemical and metabolic data from KEGG (that isn't currently included in the underlying package network), instead of querying these and also querying enzymes and genes (as these are much more stable). This means that the get_Kegg_data() function is much faster and now has a unit test, man example and runnable code chunk in the vignette. 

In order to allow users to still try add genes or enzymes to the network, my plan is to add functionality whereby users can query specific bio-entities (genes/enzymes/reactions/metabolites) in KEGG to try (where possible) integrate them within the KEGG network data underpinning the package. 

I'm now just getting this to pass R CMD and BiocCheck again as the package structure is now throwing errors during tests/examples when trying to access data files within the package. However, this doesn't seem to be the case when running devtools::test(). I'll let you know when I've pushed these changes to git.bioconductor.org

**Comment by LucaAnholt** [comment] 2022-04-09 13:42
@Kayla-Morrell Just as another quick update, I've been trying to implement the said functionalities I mentioned in my previous message, however, this is turning out to be a lot of trouble. I take it altering the internal sysdata.rda file is quite uncommon practice in R packages and troubleshooting the issues relating to R CMD check is becoming quite difficult. I'm now tempted to ditch my attempts to include these user functions for updating the internal data, especially because the enzyme-coding related data in KEGG is really stable (since working on this I noticed nothing has changed in the data in months). Does this sound ok?

**Comment by Kayla-Morrell** [comment] 2022-04-15 14:39
@LucaAnholt - That sounds fine. Should I go ahead with the re-review?

**Comment by LucaAnholt** [comment] 2022-04-30 09:52
@Kayla-Morrell  Apologies, I was on a break and just saw this now! Yes please!

**Comment by Kayla-Morrell** [comment] 2022-05-23 14:21
@LucaAnholt - Thank you for making the necessary changes. I have looked everything over and it all looks good. I'm more than happy to accept the package.

Best,
Kayla

**Comment by lshep** [comment] 2022-05-27 16:48
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/LucaAnholt.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("PanViz")`. The package 'landing page' will be created at

https://bioconductor.org/packages/PanViz

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-05-27 16:48 UTC
Labels: OK, 3a. accepted
