### ISSUE TITLE
granulator package submission

### ISSUE THREAD

**Issue by xanibas** [Bioconductor/Contributions#2036] opened 2021-04-08 23:20 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/xanibas/granulator

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by xanibas** [comment] 2021-04-21 12:41
Hey @lshep ,

I have fixed the previous error and pushed a new verions bump on both github.com and git.bioconductor.org repositories
https://github.com/xanibas/granulator/commit/140913fb59ce3e90574252a6677a48d3a8061c84

following this instructions:
https://bioconductor.org/developers/how-to/git/new-package-workflow/

git shows that both the origin and the upstream are up-to-date, but there was no automatic trigger of the build. Am I missing something?

**Comment by lshep** [comment] 2021-04-21 12:49
That is very odd.  I do see the version bump on the git.bioconductor.org as well.  Can you show the results of `git remote -v`  and Can you try bumping the version once more and show the complete output given.

**Comment by xanibas** [comment] 2021-04-21 14:48
I commited again with a new version bump but nothing
https://github.com/xanibas/granulator/commit/9f7e380b36f7def550b3e72fa49eccb874f014cd

git remote -v
origin  git@github.com:xanibas/granulator.git (fetch)
origin  git@github.com:xanibas/granulator.git (push)
upstream        git@git.bioconductor.org:packages/granulator.git (fetch)
upstream        git@git.bioconductor.org:packages/granulator.git (push)

Quite some time ago my student tried to submit the package, but didnt have time to complete the process
https://github.com/Bioconductor/Contributions/issues/1317

I have initiated a new submission as I'm using a different repository (with the same package name), could it be causing the issue?

**Comment by lshep** [comment] 2021-04-21 14:50
Perhaps -- there might be an issue with keys and repos.  @nturaga  I can check the SPB database, would you be able to cross check keys and access?

**Comment by xanibas** [comment] 2021-04-21 14:52
btw, here is the output from the git.bioconductor push

git push upstream master

Enter passphrase for key '...':
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 288 bytes | 20.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0

**Comment by nturaga** [comment] 2021-04-21 14:53
Have you checked http://bioconductor.org/developers/how-to/git/faq/ ?? (points 14, 15, 16)

Do not resubmit the package.

**Comment by nturaga** [comment] 2021-04-21 14:55
There isn't anything wrong on our end, I've checked the access rights. The issue is on your end. Please add a new key, if it doesn't work and try again.

**Comment by xanibas** [comment] 2021-04-21 14:58
I see. I have already created new SSH keys, and added to github and bioconductor.
I don't have access anymore to the repository of the original submission, so I cannot add keys to that one if that's what you mean.

**Comment by nturaga** [comment] 2021-04-21 15:01
I'm confused here, you say you've added SSH keys to github and the BiocCredentials account? (in line 1)

And you say you cannot add keys (in Line 2). 

To clarify, I'm specifically talking about you adding SSH keys to your https://git.bioconductor.org/BiocCredentials account under your email address @novarits.com

**Comment by lshep** [comment] 2021-04-21 15:04
I deleted issue #1317 out of the SPB database to make sure there wasn't some confusion there.

**Comment by nturaga** [comment] 2021-04-21 15:06
So are you able to push now ? Again, I have to say, there isn't anything wrong on our end.

**Comment by lshep** [comment] 2021-04-21 15:07
It might have been the SPB database.  could you try once more to trigger a build

**Comment by xanibas** [comment] 2021-04-21 15:08
I'm sure the mistake is on my side, but I cannot see where....
The key was already added when I tried to bump and push 2 times, and nothing happened.

**Comment by xanibas** [comment] 2021-04-21 15:08
ok, I give a try now

**Comment by nturaga** [comment] 2021-04-21 15:11
Thanks, let us know if you are able to or not able to push. 

If you aren't able to, please send us the list of commands you are trying and check the permissions on your SSH key as well. If the SSH key doesn't have the right permissions, it'll ask for a password even if you haven't set one.

**Comment by nturaga** [comment] 2021-04-21 15:15
> @nturaga I don't think its on their side completely. I can pull down the version bump from git.bioconductor.org but a build is not triggering

I see, so @xanibas is able to push, but the build isn't triggering? I was under the impression that she wasn't able to push.

**Comment by xanibas** [comment] 2021-04-21 15:15
That's correct. Here is the list of the commands I use:
git add --all
git commit -m "version bump"
git push upstream master
git push origin master

if I check, all remotes have been sucessfully updated but no build triggered

git fetch -v --all
Fetching origin
Enter passphrase for key '....':
From github.com:xanibas/granulator
 = [up to date]      master     -> origin/master
Fetching upstream
Enter passphrase for key '....':
From git.bioconductor.org:packages/granulator
 = [up to date]      master     -> upstream/master

**Comment by lshep** [comment] 2021-04-21 15:18
> > @nturaga I don't think its on their side completely. I can pull down the version bump from git.bioconductor.org but a build is not triggering
> 
> I see, so @xanibas is able to push, but the build isn't triggering? I was under the impression that she wasn't able to push.

Correct.  I can pull down version 0.99.3 from git.bioconductor.org  but there was no build triggered when pushing

**Comment by nturaga** [comment] 2021-04-21 15:36
Hi, Can you send in one last version bump?

**Comment by xanibas** [comment] 2021-04-21 15:38
sure, it's done

**Comment by lshep** [comment] 2021-04-21 15:43
@xanibas  Sorry for the complications.  We are having trouble figuring out why builds are not triggering.  For now would you mind if we closed the issue and have you resubmit under a new issue?

**Comment by xanibas** [comment] 2021-04-21 15:45
that's fine for me. Should I maybe change the name of the package to avaid conflicts with previous submissions?

**Comment by lshep** [comment] 2021-04-21 15:46
You should not have to change the package name.  Please wait until you get confirmation of this issue closing and then try to resubmit.

**Comment by lshep** [comment] 2021-04-21 15:47
Sorry -- I got trigger happy -- Please wait for us to confirm before resubmitting

**Comment by xanibas** [comment] 2021-04-21 15:47
I'll wait

**Comment by xanibas** [comment] 2021-04-21 15:48
thanks for the help!

**Comment by lshep** [comment] 2021-04-21 15:48
Okay.  I think we have reset the system for a resubmit.  Again sorry for this.

**Closed by lshep** 2021-04-21 15:48 UTC
Labels: 2. review in progress, ERROR

**Comment by lshep** [comment] 2021-04-21 15:53
If it continues to happen on resubmit  please ping me on the issue and we will try and debug further.
