### ISSUE TITLE
Bayesian Analaysis Of Compositional Covariance (banocc)

### ISSUE THREAD

**Issue by george-weingart** [Bioconductor/Contributions#145] opened 2016-09-25 05:06 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_
- Repository: https://github.com/george-weingart/banocc
  Confirm the following by editing each check box to '[x]'
- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.
- [x] I have read the _Bioconductor_ [Package Submission](https://bioconductor.org/developers/package-submission/)
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines](https://bioconductor.org/developers/package-guidelines/).
- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.
- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site](https://support.bioconductor.org) for issues that users may
  have, subscribing to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:
- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
    months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion](http://bioconductor.org/developers/how-to/source-control/)
  (optionally [via GitHub](http://bioconductor.org/developers/how-to/git-mirrors/)).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel](https://stat.ethz.ch/mailman/listinfo/bioc-devel) mailing list.

**Comment by mtmorgan** [comment] 2016-09-25 10:52
hpages will provide a formal review. I noticed that

- The Description: field of the DESCRIPTION does not provide enough information for the user to discover what this package does (e.g., what type of data it works on, how it distinguishes itself from other packages with similar capabilities).

-  The only man page I looked at https://github.com/george-weingart/banocc/blob/master/man/banocc.Rd#L9 is inappropriate, implying that all man pages should be fully vetted for content.

- No Bioconductor package are used in the DESCRIPTION file, implying that there is no need for the package to be in Bioconductor and hence more suited to CRAN. If there are particular data types the packages is useful for then it would make sense to interoperate (minimally, use inputs and return outputs) that are commonly used in that domain. For instance, supporting input 'matrix' objects that are SummarizedExperiment or ExpressionSet would be appropriate.

- The final commit message, "Examples partially run to make BiocCheck happy, partially not run to … ￼…
…keep R CMD check happy" doesn't really bode well -- having examples that don't run defeat the dual purposes of providing users with examples that are known to work, and testing code that might otherwise not be tested.

**Comment by hpages** [comment] 2016-10-07 06:32
Hi George,

Thanks for your submission. Can you please address Martin's comments (mtmorgan) as well as the ERRORs and WARNINGs reported by BiocCheck? Thanks.

Cheers,
H.

**Comment by george-weingart** [comment] 2016-10-07 16:46
Hello,

Where can I find the errors and warnings  for banocc ?

I can't see that in
https://www.bioconductor.org/checkResults/3.4/bioc-LATEST/#B
or
https://www.bioconductor.org/checkResults/3.3/bioc-LATEST/#B

Thanks!
George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by mtmorgan** [comment] 2016-10-08 12:05
@george-weingart see the link to the 'build report' in a previous comment on this issue.

**Comment by hpages** [comment] 2016-10-10 07:37
Please follow the link that was posted in this issue by bioc-issue-bot 15 days ago (the issue is on github here https://github.com/Bioconductor/Contributions/issues/145).
Thanks,
H.

**Comment by hpages** [comment] 2017-01-26 17:10
Hi George,

Just wanted to check with you what the status of the package is. Are you planning to follow-up with your submission?

Thanks,
H.

**Comment by hpages** [comment] 2017-02-15 19:28
Hi George,

Just to let you know that I'll close this issue at the end of the month, unless there is a follow-up on this submission.

Cheers,
H.

**Comment by george-weingart** [comment] 2017-02-16 18:02
Hello,

We request you don't close the issue as we are actively working  to enhance
the package and intend to submit a new version soon.

Thank you,

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by hpages** [comment] 2017-02-24 18:23
Hi George,
Thanks for letting me know.
H.

**Comment by george-weingart** [comment] 2017-02-24 18:28
Thanks!
We are actively working on the package

**Comment by george-weingart** [comment] 2017-02-28 01:44
Hello,


Could I trouble you to help me?


We updated banocc in https://github.com/biobakery/banocc

How do we proceed to accept our updates in Bioconductor?  it used to be
Svn, but how do we do it now?

Thanks!
George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by mtmorgan** [comment] 2017-03-02 11:43
Your package needs to be accepted first. To be accepted it needs to be built on the 'single package builder' Usually, commits to your package should trigger a build. It seems that this is not the case for your package. Please ensure that you have the 'web hook' installed correctly, following the instructions at https://github.com/Bioconductor/Contributions#additional-actions 'To debug package commits...'

**Comment by george-weingart** [comment] 2017-03-02 16:24
Hello Martin,

I added the webhook.
Can you look at that and make sure our package ('banocc") gets reviewed ?

Thanks!

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health


[image: Inline image 1]

**Comment by mtmorgan** [comment] 2017-03-02 22:26
Can you please trigger a build by commiting to the master branch? It should show up here as being built by the SPB. If not then likely there is a problem still with the web hook.

**Comment by george-weingart** [comment] 2017-03-08 01:29
Hello Martin,

I forced a commit to the master branch.
Can I trouble you to check if that triggers a build ?

To remind you,  we are talking about an update to the "banocc" package that
is located in https://github.com/george-weingart/banocc

Thank you!

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health


[image: Inline image 1]

**Comment by mtmorgan** [comment] 2017-03-08 10:57
@george-weingart almost! you can see on the issues page that bioc-issue-bot added the 'VERSION BUMP REQUIRED' label, so your web hook is working. A build is triggered when the DESCRIPTION  file Version: field is incremented, for you that means making a commit that changes the version from 0.99.0 to 0.99.1.

**Comment by george-weingart** [comment] 2017-03-08 16:37
Hi Martin,


What do we need to do now?  I don't see yet our package in the Build Report.

Thanks again for your help !

George Weingart PhD
Huttenhower Lab
Harvard School of Publich Health

[image: Inline image 1]

**Comment by mtmorgan** [comment] 2017-03-08 16:59
Look at the github issue you opened when you submitted your package https://github.com/Bioconductor/Contributions/issues/145 .

Notice toward the bottom that the bioc-issue-bot  says that you a 'VERSION BUMP REQUIRED'.

Go to your git package repository, and commit a change that increments the version in the DESCRIPTION file from 0.99.0 to 0.99.1.

Return to the issue https://github.com/Bioconductor/Contributions/issues/145 . bioc-issue-bot will have added a comment indicating that a build has been started.

Wait.

The build will finish, and bioc-issue-bot will add another comment that includes a link to the build report. If there are problems, then fix them in your repository, including another increment (to 0.99.2) of your package version. Each package version increment will trigger another build. Repeat until there are no problems with the build report.

When there are no problems with your package, a person (me) will manually review it. This manual review can take several weeks. You will then respond to the review, probably by updating your code. The reviewer will approve or reject your package based on the review. If approved, the package will be added to Bioconductor, and will be incorporated into the nightly 'devel' build report.

**Comment by mtmorgan** [comment] 2017-03-08 22:07
Looks like there is a small problem that you can fix -- importing functions from a package -- do so and commit your change along with a version bump to 0.99.2.

**Comment by george-weingart** [comment] 2017-03-09 19:59
Hello Martin,

First of all, I want to thank you for your help deploying the package,  you
have been very helpful and it it greatly appreciated.

I have 2 questions:

Question # 1:

When I look at the output of the check  (
http://bioconductor.org/spb_reports/banocc_buildreport_20170308123607.html
 )    I see NOTES about

Consider adding
  importFrom("stats", "cov2cor", "quantile", "rbeta", "rbinom", "rgamma",
             "sd")



But those are NOTES - so we are OK on them ? Or we need to modify anything
in the submission ?

Question # 2:

We have a warning to request R 3.4 -  But we don't need 3.4 - we are OK
with 3.3.

So why do we have to impose on the users to upgrade to 3.4 in prder to use
our package?

Would appreciate your feedback.

Thank you,

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

**Comment by mtmorgan** [comment] 2017-03-10 07:15
Thank you for your contribution. Please update your package in
response to the following comments, including a version bump. Provide
a comment on this issue summarizing your response.

DESCRIPTION

- Please clarify the relationship between the author -- 'Emma
  Schwager' -- and the github account 'george-weingart' that has
  contributed the issue. If these are different people and
  'george-weingart' is going to maintain the package, then add that
  person to the the Authors@R field as the (sole) 'cre'.
- For legibility, please wrap the description file at 80 columns,
  indenting continuation lines, e.g.,
  
        Description: BAnOCC is a package designed for compositional
            data, where each sample sums to one. It infers the
            approximate covariance of the unconstrained data using a
            Bayesian model coded with `rstan`. It provides as output
            the `stanfit` object as well as posterior median and
            credible interval estimates for each correlation element.
R

- use `message()` rather than `cat()` to commnicate with the user
- use `is()` or `inherits()` rather than string matching
  `class(banoccfit) == "stanfit"` to test class identity.
- no need to `stop(paste())` as `stop()` pastes its arguments anyway;
  likewise with `warning()`.
- avoid `1:n` specification of ranges, which are problematic when n ==
  0; use `seq_len(n)` or `seq_along()`.
  
vignette

- update instructions to include Bioconductor standard --

        source("https://bioconductor.org/biocLite.R")
        biocLite("banocc")
- (optional) Consider using [BiocStyle][] to format vignette
- Clean up vignette directory, e.g., remove unused
  'bannoc-landing-page-template.Rmd'. Remove build artifacts (.R, .md,
  .html, automatically generated figures).
  
Other

- please clean up other aspects of the repository, e.g., remove
  `test_utils_dummy.R`

[BiocStyle]: https://bioconductor.org/packages/BiocStyle

**Comment by george-weingart** [comment] 2017-03-21 00:20
Hello Martin,

I would like to request your advice in regards to our package: banocc
located in https://github.com/george-weingart/banocc

Emma Schwager from our Lab is the researcher in charge of the package, she
is doing all the theoretical banocc work  and she developed the R package
that we are pushing to Bioconductor.  My role is very minor and consists in
some QA and deploying the package to Bioconductor.

For that purpose, I created https://github.com/george-weingart/banocc

I am replicating all the changes that Emma developed in the real
repository:  https://bitbucket.org/biobakery/biobakery/wiki/banocc

The question:

We  are using a copy of the real repository (
https://bitbucket.org/biobakery/biobakery/wiki/banocc)

Would you prefer to keep the copy permanently, convert the repository now
or after we get the package accepted into Bioconductor?

Please let Emma and me know,

Thanks !

George Weingart PhD

Huttenhower Lab
Harvard School of Public  Health

**Comment by mtmorgan** [comment] 2017-03-21 07:53
The submission process requires a github repository; in the short term accepted packages end up in our svn repository. Whether you continue to maintain the github repo in sync with your bitbucket repo is really up to you; I'd find it confusing and error-prone.

**Comment by mtmorgan** [comment] 2017-03-21 07:59
Also, somehow I had missed your [earlier questions](https://github.com/Bioconductor/Contributions/issues/145#issuecomment-285463922).

Yes, add `importFrom()` as outlined in the NOTE.

Specifying R-3.4 is not entirely required, but your package will be added to the Bioc devel branch, which uses R-3.4. This means that the successful builds are against R-3.4, and so 'truth-in-advertising' is really to indicate this version.

**Comment by mtmorgan** [comment] 2017-03-27 07:46
Just to be clear, I'm waiting on the minor changes to this package that will respond to the review concerns and clean up the build report.

**Comment by mtmorgan** [comment] 2017-03-31 18:51
Looks like the package is building cleanly. I'll accept it to Bioconductor, adding to the nightly builds and svn repository. You'll receive additional email in a few days.

**Closed** 2017-03-31 19:01 UTC
Labels: 3a. accepted, OK
