### ISSUE TITLE
coMethDMR

### ISSUE THREAD

**Issue by fveitz** [Bioconductor/Contributions#2064] opened 2021-04-21 19:15 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/TransBioInfoLab/coMethDMR

Dear reviewer, I am submitting my package for the very first time. 
I am a master student in the lab of @lxw391 and @gabrielodom
Thank you in advance for your feedback and your patience.

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by gabrielodom** [comment] 2021-04-21 19:18
Dear Bioconductor Review Team,
Thank you for moderating this package. At the time of submission, we have 7 notes (2 from CRAN check and 5 from BioC).
We have relayed them here: https://github.com/TransBioInfoLab/coMethDMR/issues/1
Respectfully yours,
Gabriel

**Comment by Kayla-Morrell** [comment] 2021-05-03 18:54
@fveitz - Thank you for working on your package to get it ready for review. Please keep in mind that the deadline to accept new packages into the Bioconductor 3.13 release is May 12th. Any packages accepted after this date will be included in the next release.

Best,
Kayla

**Comment by gabrielodom** [comment] 2021-05-03 19:00
Hi @Kayla-Morrell!
Thank you so much for checking on us. We are currently deliberating about the best way to reduce the package size (currently, that is our only ERROR because Fernanda just added `coMethDMR` to her watched tags on the support site).

The data files in `inst/extdata/` (11.3Mb) are there to save the users from having to re-compute them in each analysis. We are right now reading the documentation on creating an ExperimentHub package to store these data sets, but we see that this also requires us to get help from someone on the Bioconductor team. 

Should we ask you for help with this?

**Comment by gabrielodom** [comment] 2021-05-05 02:46
We have moved the example data sets to a supplemental GitHub directory. The package now has an install size <5Mb. We will be pushing these changes upstream tomorrow morning.
Thank you for your patience.

**Comment by gabrielodom** [comment] 2021-05-05 22:59
Hi @Kayla-Morrell,
We need help. We have removed the large data files from the package and the .git/ history folder. According to these instructions (<https://bioconductor.org/developers/how-to/git/remove-large-data/>), we are to email you and ask for help forcing the update.

**Comment by Kayla-Morrell** [comment] 2021-05-06 13:22
Hello @gabrielodom - Thank you for reaching out. I believe @nturaga should be able to help with this.

Best,
Kayla

**Comment by nturaga** [comment] 2021-05-06 13:30
Hi,

Please send an email as instructed to ***@***.******@***.***> . We like to keep a track of packages when we manually interfere and make big changes like this, for the purpose of back tracing if needed.

Best,

Nitesh

From: Kayla-Morrell ***@***.***>
Date: Thursday, May 6, 2021 at 9:23 AM
To: Bioconductor/Contributions ***@***.***>
Cc: Nitesh Turaga ***@***.***>, Mention ***@***.***>
Subject: Re: [Bioconductor/Contributions] coMethDMR (#2064)

Hello @gabrielodom<https://github.com/gabrielodom> - Thank you for reaching out. I believe @nturaga<https://github.com/nturaga> should be able to help with this.

Best,
Kayla

**Comment by gabrielodom** [comment] 2021-05-06 13:39
Hi @nturaga,
We emailed bioc-devel@r-project.org yesterday at 7PM Eastern (I also commented here to cover my bases). The email address in your comment has been replaced with "*". Is that the email we were supposed to use, or should we use a different one?

**Comment by gabrielodom** [comment] 2021-05-13 15:06
Hi @Kayla-Morrell,
@fveitz and I worked on removing some of these notes (particularly the LazyData and redundant paste() calls).
Please let us know if there is anything else you would like us to improve.
Best,
Gabriel

**Comment by Kayla-Morrell** [comment] 2021-05-28 14:06
@fveitz - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

## DESCRIPTION
- [ ] REQUIRED: Update R version dependency from 4.0.0 to 4.1.

- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field that  includes the relevant link to GitHub for reporting Issues. 

## Vignettes

*vin1_Introduction_to_coMethDMR_geneBasedPipeline*

- [ ] SUGGESTION: For section headings you include the number in your title so  in the table of contents it looks like '1 1. Quick start'. I would suggest removing the leading 1. or 2. since they will get numbered automatically (you have the right idea in the next vignette).

- [ ] REQUIRED: In the 'Installation' section the package should be installed  from Bioconductor, not your GitHub. The code on line 39 should be changed to`BiocManager::install("coMethDMR")`.

- [ ] REQUIRED: The code section at line 54 should not have `eval = FALSE`.  Code chunks in your vignette (minus the installation ones) should be executable. I think this what is resulting in my local ERRORs when I try to build the vignettes. For example, under section 1.3 I get the following error:

```{r}
system.time(  
   coMeth_ls <- CoMethAllRegions(    
       dnam = betasChr22_df,    
       betaToM = TRUE, #converts to mvalues    
        method = "pearson",
        CpGs_ls = CpGisland_ls,    
        arrayType = "450k",
        returnAllCpGs = FALSE,
        output = "CpGs",
        nCores_int = 1  )
)
## Error in stopAndCache(title): 
## File needs to be cached to be used in sesame.
## Please run
## > sesameDataCache("HM450")
## or cache all platforms by
## > sesameDataCacheAll()
## to retrieve and cache needed sesame data.
## Timing stopped at: 0.013 0.002 0.018# 12 seconds

coMeth_ls
## Error in eval(expr, envir, enclos): object 'coMeth_ls' not found
```

This makes the rest of the vignette almost non-reproducable since objects aren't found.

- [ ] REQUIRED: The last section of the vignette should be 'Session  Information' and should include `sessionInfo()`.

*vin2_BiocParallel_for_coMethDMR_geneBasedPipeline*

- [ ] REQUIRED: Similar to the issue in the first vignette, when running the  code at line 118, I get the error about sesameDataCacheAll() and that objects aren't found because this code is executable. Please fix this code.

- [ ] REQUIRED: The last section of the vignette should be 'Session  Information' and should include `sessionInfo()`.

## Unit tests

- [ ] REQUIRED: Running the tests in 'test/testthat.R' failed. I'm not sure  exactly which test failed, but this is the output I got from R CMD check:

```
* checking tests ... ERROR 
   Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
       4. └─coMethDMR::lmmTestAllRegions(...)
       5.   ├─BiocParallel::bplapply(...)
       6.   └─BiocParallel::bplapply(...)    
       7.     └─base::lapply(X, FUN_, ...)    
       8.       └─BiocParallel:::FUN(X[[i]], ...)    
       9.         └─BiocParallel:::FUN(...)   
       10.           ├─base::withCallingHandlers(...)   
       11.           └─base::tryCatch(...)   
       12.             └─base:::tryCatchList(expr, classes, parentenv, handlers)   
       13.               └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])   
       14.                 └─value[[3L]](cond)
  
[ FAIL 3 | WARN 0 | SKIP 0 | PASS 1 ]  
    Error: Test failures  
    Execution halted
```

## R code

- [ ] REQUIRED: Running examples in 'coMethDMR-Ex.R' failed. This is the output  I got from R CMD check:

```
* checking examples ... ERROR
Running examples in ‘coMethDMR-Ex.R’ failed
The error most likely occurred in:

> ### Name: CloseBySingleRegion
> ### Title: Extract clusters of CpGs located closely in a genomic region. 
> ### Aliases: CloseBySingleRegion 

### ** Examples
>
>
>    CpGs_char <- c(
     "cg02505293", "cg03618257", "cg04421269", "cg17885402", "cg19890033",
      "cg20566587", "cg27505880"
    )
>
>   cluster_ls <- CloseBySingleRegion(
      CpGs_char,
      genome = "hg19",
      arrayType = "450k",
      maxGap = 100,
      minCpGs = 3
    )
Error in stopAndCache(title) :
File needs to be cached to be used in sesame.
Please run
> sesameDataCache("HM450")
or cache all platforms by
> sesameDataCacheAll()
to retrieve and cache needed sesame data.
Calls: CloseBySingleRegion ... capture.output -> withVisible -> .sesameDataGet -> stopAndCache
Execution halted
```

- [ ] SUGGESTION: Avoid redundant 'stop' and 'warn*' in signal conditions. Found in files:        lmmTestAllRegions.R, line 140

- [ ] SUGGESTION: For formating reasons, consider shorter lines. There are 201 lines that are &gt; 80 characters long.

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line indents. There are 1001 lines that are not.

Best,
Kayla

**Comment by Kayla-Morrell** [comment] 2021-08-11 13:20
@fveitz - Just checking in to see where you stand with making the changes to this package that I proposed in my initial review. I understand there is still some investigative work that needs to be done on our end in regard to the caching on the builders, but we would still like to see some of the other changes made in the mean time.

Best,
Kayla

**Comment by gabrielodom** [comment] 2021-08-13 19:21
@Kayla-Morrell , thank you for checking in.
We are currently troubleshooting another install issue for this package that some other users found for us. Also, some of our lab staff was off in the summer. We should be back into the swing of things within a week or two.

**Comment by gabrielodom** [comment] 2021-08-27 16:21
Hi @lshep, @fveitz and I are back to work on this. We should have a new commit pushed upstream today or tomorrow.

**Comment by fveitz** [comment] 2021-08-28 11:41
Hi @lshep and @Kayla-Morrell, please find attached the package's changes that I and @gabrielodom went through yesterday.

[coMethDMR_08272021.xlsx](https://github.com/Bioconductor/Contributions/files/7070642/coMethDMR_08272021.xlsx)

**Comment by lshep** [comment] 2021-09-07 16:19
Thanks for making kayla's suggested updates.  I have reviewed the package again and have found some more concerns or comments that could use some feedback.


**local build**
- [ ] Some operating systems are case sensitive.  Building locally failed in the
vignette

```
Quitting from lines 221-229 (vin1_Introduction_to_coMethDMR_geneBasedPipeline.Rmd) 
Error: processing vignette 'vin1_Introduction_to_coMethDMR_geneBasedPipeline.Rmd' failed with diagnostics:
no file found
```
When I look at this section of code, in the vignette `.RDS` but the file has a
lowercase exention `.rds`

**NEWS**

- [ ] Formatting incorrectly. Please do not have any freeform text. The contents
  of each section should be in lists. Also do not have empty sections. see 
http://contributions.bioconductor.org/news.html


**vigneete**

- [ ] You say in your vignette `We assume quality control and normalization of
  the methylation dataset have been performed, by R packages such as minfi or
  RnBeads`.  But then I don't see any interaction with say the default RnBeads
  object, RnBSet. Bioconductor strongly encourages the reuse of classes and
  interoperability. It seems like minimally you should be able to use the RnBSet
  Object directly as input in your functions as well. Similarly then you should
  be able to reuse minfi classes.

- [ ] I'm also wondering if something like a BiocSet would be helpful instead of
  lists?

- [ ] For genomic ranges we like to see the use of the GenomicRanges, granges
  class. Arguments like regionName_char should also be able to take a grange
  object or grangelist object.


- [ ]  Analyzing a specific gene.  We don't accept additional data on github. Is
  it possible to include this information directly in your package? Or could you
  submit the other package as the associated data package?

- [ ] In vin1 section 2.3. I cannot reproduce your results. After the run where
  we get ##NULL and change to Cgi_ls[5], your results show and answer. Mine are
  still ##NULL and subsequently the rest of the code in 2.4 is also non reproducible. 

```
> coMeth_ls <- CoMethAllRegions(
+   dnam = resid_df,
+   betaToM = FALSE,
+   method = "pearson",
+   CpGs_ls = Cgi_ls[1],
+   arrayType = "450k",
+   returnAllCpGs = FALSE,
+   output = "CpGs"
+ )
> coMeth_ls
NULL
> coMeth_ls <- CoMethAllRegions(
+   dnam = resid_df,
+   betaToM = FALSE,
+   CpGs_ls = Cgi_ls[5],
+   arrayType = "450k",
+   returnAllCpGs = FALSE, 
+   output = "CpGs"
+ )
> 
> coMeth_ls
NULL

 coMethData_df <- CoMethAllRegions(
+   dnam = resid_df,
+   betaToM = FALSE,
+   CpGs_ls = Cgi_ls[5],
+   arrayType = "450k",
+   returnAllCpGs = FALSE, 
+   output = "dataframe"
+ ) [[1]]
Error in CoMethAllRegions(dnam = resid_df, betaToM = FALSE, CpGs_ls = Cgi_ls[5],  : 
  subscript out of bounds

> lmmTestAllRegions(
+   betas = betasChr22_df,
+   region_ls = coMeth_ls[1],
+   pheno_df,
+   contPheno_char = "stage",
+   covariates_char = "age.brain",
+   modelType = "randCoef",
+   arrayType = "450k"
+ )
For future calls to this function, perhaps specify a log file.
      Set the file name of the log file with the outLogFile argument.
Error in lmmTestAllRegions(betas = betasChr22_df, region_ls = coMeth_ls[1],  : 
  object 'outDF' not found
```


**R code**

- [ ] Please remove any commented out/unused code. Comments are fine and
  encouraged but commented out code should be removed.

- [ ] Should there be a match.arg check in CloseBySingleRegion

- [ ] So for GetCpGsInRegion, OrderCpGsByLocation, WriteCloseByAllRegions you don't support HM27?

- [ ] WriteCloseByAllReions probably want to check fileName and regions is also
  correct format.


Please address or comment on the above points.  When ready please do a version bump to trigger a new build and request a re-review. 
Cheers,

**Comment by gabrielodom** [comment] 2021-09-15 18:01
Thank you @lshep. @fveitz, can we make sure these are added to our to-do list?

**Comment by fveitz** [comment] 2021-09-16 13:14
Hi @gabrielodom. Yes, I will  check.

**Comment by lshep** [comment] 2021-10-05 13:40
The next release is fast approaching.  Are there any updates?  We normally like to see progress on packages within 2-3 weeks of the review.

**Comment by gabrielodom** [comment] 2021-10-10 17:19
@lshep, I had a grant submission due to my institution's review office. @fveitz and I are back on this now.

**Comment by lshep** [comment] 2021-10-20 11:22
I'm going to close the issue for now.  When you are ready to push changes please ping me on this issue to reopen it

**Comment by gabrielodom** [comment] 2021-10-20 20:06
Hi @lshep, can you re-open the issue by tomorrow? @fveitz will be pushing at update tomorrow morning. We've been working on updates for the past week.

We have done/explained the following:
- all data sets and references to them use lower case file extensions (.rds instead of .RDS, for instance)
- reformatted the NEWS file per Bioconductor guidelines
- added example code to the vignette using functions from the `minfi::` and `RnBeads::` packages to show how output from their functions can be used as the input to our functions; as a note, the `BiocSet::` package is for gene sets (so I will probably add functionality to use it to our other package `pathwayPCA::`), but it is not necessarily appropriate for regions of the genome.
- We have updated the `CpGsInforAllRegions()`, `CpGsInfoOneRegion()`, and `GetCpGsInRegion()` functions to take in a `GRanges` object as an input.
- Our data sets on GitHub are examples of the output of the `WriteCloseByAllRegions()` function. They are not required for the package to work.
- For the replication error, we believe this may have been caused by the data set file extension error above. We replicated our code in clean Windows, Mac, and Linux environments and were not able to reproduce the second NULL output (the first NULL is correct, however).
- I cleaned up a whole host of the functions and fixed incongruences in coding style, greatly reducing superfluous code and removing all commented code. I am truly sorry that those were missed by internal review. We will tighten up our code review process so that those issues are less likely in the future.
- We added `match.arg()` calls as appropriate. 
- Concerning the older Illumina HM27 format: we believe that the probe clustering routine is more appropriate to a denser topography of probes. As is, even 450k arrays only cover a paltry 0.01% of the human genome, and we are hoping that finding local correlations between these sparse probes will give actionable biological information. We don't think that 27k probes can adequately capture cross-region correlations out of 3.2 billion base pairs to highlight co-methylated regions of the genome.
- We added a class check to confirm that the `regions` input to `WriteCloseByAllRegions()` is a `GRanges` object.

At current, these updates are available on GitHub (see <https://github.com/TransBioInfoLab/coMethDMR/issues/1>), and we will push them upstream to Bioconductor tomorrow morning.

**Comment by fveitz** [comment] 2021-10-21 14:42
Hi @lshep, I am stuck with an authentication issue.

```
Fernandas-MacBook-Pro:coMethDMR fernandaveitzman$ git remote -v
origin  https://github.com/TransBioInfoLab/coMethDMR.git (fetch)
origin  https://github.com/TransBioInfoLab/coMethDMR.git (push)
upstream        git@git.bioconductor.org:packages/coMethDMR.git (fetch)
upstream        git@git.bioconductor.org:packages/coMethDMR.git (push)

Fernandas-MacBook-Pro:coMethDMR fernandaveitzman$ git fetch --all
Fetching origin
Fetching upstream
kex_exchange_identification: read: Operation timed out
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream
```

I confirmed that I can pull and commit+push to GitHub, but I get the error `kex_exchange_identification: read: Operation timed out` when I try to pull from git@git.bioconductor.org. I found this link (<https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port>) to try to troubleshoot the error, but I'm still stuck.

Have you seen this before? I recently had to change from HTTPS authentication to SSH keys. Could that have something to do with it?

**Comment by lshep** [comment] 2021-10-21 14:47
I would try adding a new ssh key to the GitCredentials app

**Comment by nturaga** [comment] 2021-10-21 14:48
Hi,

Please make sure you activate your BiocCredentials account with the email ***@***.*** https://git.bioconductor.org/BiocCredentials/account_activation

Upload a good SSH key, and make sure you are using the correct key pair.

There is nothing wrong on our end regarding this issue, from what I can tell.

Best,

Nitesh 



Nitesh Turaga
Scientist II, Department of Data Science,
Bioconductor Core Team Member
Dana Farber Cancer Institute

**Comment by gabrielodom** [comment] 2021-10-21 14:49
Thank you Lori and Nitesh! Fernanda, please try this as soon as possible.

**Comment by fveitz** [comment] 2021-10-21 16:08
Hi Lori, Nitesh and Gabriel,
Using my internet at home I could push successfully.

"Fernandas-MacBook-Pro:coMethDMR fernandaveitzman$ git push upstream master
Enumerating objects: 179, done.
Counting objects: 100% (179/179), done.
Delta compression using up to 16 threads
Compressing objects: 100% (128/128), done.
Writing objects: 100% (128/128), 32.08 KiB | 290.00 KiB/s, done.
Total 128 (delta 104), reused 0 (delta 0)
remote: Resolving deltas: 100% (104/104), completed with 48 local objects.
To git.bioconductor.org:packages/coMethDMR.git
   507e5d3..3e1e22c  master -> master"

Thank you!

**Comment by gabrielodom** [comment] 2021-10-21 16:12
And we have _another_ build error. Give us a minute. I think it's the sesameData package again.

**Comment by lshep** [comment] 2021-11-05 14:27
Were you ready for a re-review?

**Comment by gabrielodom** [comment] 2021-11-05 15:01
@lshep -- if you have time. We aren't in a huge hurry (the paper was already accepted), and we know you have a million other things.

**Comment by lshep** [comment] 2021-11-12 14:52
In vin1 section 2.3. I still cannot reproduce your results.After the run
where we get ##NULL and change to Cgi_ls[5], your results show and answer. Mine
are still ##NULL and subsequently the rest of the code in 2.4 is also non
reproducible.

```
> Cgi_ls <- readRDS(
+   system.file(
+     "extdata",
+     "CpGislandsChr22_ex.rds",
+     package = 'coMethDMR',
+     mustWork = TRUE
+     )
+ )
> 
> coMeth_ls <- CoMethAllRegions(
+   dnam = resid_mat,
+   betaToM = FALSE,
+   method = "pearson",
+   CpGs_ls = Cgi_ls[1],
+   arrayType = "450k",
+   returnAllCpGs = FALSE,
+   output = "CpGs"
+ )
> 
> coMeth_ls
NULL
> coMeth_ls <- CoMethAllRegions(
+   dnam = resid_mat,
+   betaToM = FALSE,
+   CpGs_ls = Cgi_ls[5],
+   arrayType = "450k",
+   returnAllCpGs = FALSE, 
+   output = "CpGs"
+ )
> 
> coMeth_ls
NULL
> coMethData_df <- CoMethAllRegions(
+   dnam = resid_mat,
+   betaToM = FALSE,
+   CpGs_ls = Cgi_ls[5],
+   arrayType = "450k",
+   returnAllCpGs = FALSE, 
+   output = "dataframe"
+ ) [[1]]
Error in CoMethAllRegions(dnam = resid_mat, betaToM = FALSE, CpGs_ls = Cgi_ls[5],  : 
  subscript out of bounds
```

**Comment by gabrielodom** [comment] 2021-11-12 14:56
@lshep, I know this is a huge ask, but do you have time for a Zoom call? We have tried everything we can think of to replicate this error, but to no avail.

**Comment by lshep** [comment] 2021-11-12 15:01
That can be arranged. When were you thinking?

**Comment by gabrielodom** [comment] 2021-11-12 15:04
Our time is yours to command. I have @fveitz in my office at this instant

**Comment by lshep** [comment] 2021-11-12 15:05
I'm free now if you wanted to set up a zoom and email me or slack me the information to login

**Comment by gabrielodom** [comment] 2021-11-12 15:10
Setting it up now

**Comment by gabrielodom** [comment] 2021-11-12 15:12
I sent it to the roswell park email. Is that still ok?

**Comment by gabrielodom** [comment] 2021-11-12 18:12
@lshep, we have fixed the issue, and the build passes (see above).
Thank you, again, for your patience. I think we are ready for that re-review.

**Comment by lshep** [comment] 2021-11-24 12:53
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/fveitz.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("coMethDMR")`. The package 'landing page' will be created at

https://bioconductor.org/packages/coMethDMR

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by lshep** 2021-11-24 12:53 UTC
Labels: OK, 3a. accepted
