### ISSUE TITLE
picaplot:package submission

### ISSUE THREAD

**Issue by jinhyunju** [Bioconductor/Contributions#316] opened 2017-03-10 17:25 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jinhyunju/picaplot

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by mtmorgan** [comment] 2017-03-10 17:52
@LiNk-NY will review your package but I note that it doesn't interoperate with Bioconductor, e.g., via use of SummarizedExperiment. Please update your package to accept SummarizedExperiment, and to use other Bioconductor packages and classes as appropriate.

**Comment by lawremi** [comment] 2017-03-10 17:55
It's also kind of discouraging that report generation requires pandoc. It seems a major downside of markdown is that there are no widespread native viewers. Why not just use HTML directly?

**Comment by jinhyunju** [comment] 2017-03-10 18:07
Hello, @mtmorgan Thanks for the quick feedback on the package. Just to clarify your point, are you asking for features in the functions that automatically recognizes objects of classes such as SummarizedExperiment? If that is what you are asking for I will implement that functionality as soon as possible. Thanks again!

**Comment by jinhyunju** [comment] 2017-03-10 18:13
Dear @lawremi, Thank you for the feedback! My original thinking was that basing the report generation on knitr would integrate well with the current R community since it is widely used. At the moment I am not quite sure how I would directly implement this feature in HTML and would very much appreciate it if you could point me in the right direction. I will try to reflect your suggestion as soon as possible. Thank you!

**Comment by lawremi** [comment] 2017-03-10 18:19
There are lots of examples of packages generating HTML reports from a template. For example, ShortRead. I think that uses `Biobase::copySubtitute()`. Fancier would be the brew or whisker packages.

**Comment by jinhyunju** [comment] 2017-03-12 22:32
@mtmorgan I have added functionalities to the main functions `run_ica`, `run_pca` and `covariate_association_check` enabling `SummarizedExperiment` objects as direct input.

**Comment by LiNk-NY** [comment] 2017-03-15 21:38
Hi Jin-hyun, @jinhyunju
Please be aware that the Bioconductor naming conventions recommend against using underscores "_" in function names. Please use `camelCase` for naming functions.
Also, please avoid creating/loading global variables inside your functions or non-standard evaluation (see the first note in [R CMD check](http://bioconductor.org/spb_reports/picaplot_buildreport_20170310173044.html#malbec2_check_anchor))
In the latter case, you should be using the internal methods of `ggplot2` to avoid this (e.g., `aes_`). 

Regards,
Marcel

**Comment by jinhyunju** [comment] 2017-03-16 02:06
Hello Marcel, @LiNk-NY 
Thank you very much for your quick feedback. 
I have changed all function names containing underscores to `camelCase` names and addressed the NOTEs related to `ggplot2` variables by using `aes_string()`. The updated 0.99.3 version of picaplot has been pushed to the master branch. Thank you again!

Best Regards,

Jin

**Comment by jinhyunju** [comment] 2017-03-16 02:11
For the record, the ERROR label created during the automated build seems to be originating from a problem on the server related to the availability of "Biobase".

**Comment by LiNk-NY** [comment] 2017-03-31 20:38
Hi Jin-hyun, @jinhyunju
Thank you for submitting to Bioconductor. I have taken a look at your package and please find the review below. 
If you have any questions, feel free to respond here. 

Best regards,
Marcel 

----

# picaplot #316

##  DESCRIPTION

* Move `SummarizedExperiment` to the `Imports` field

## NAMESPACE 

* Looks clean and short :+1: 

## Vignette

* It seems like the example in your vignette should include a `SummarizedExperiment` container rather than a matrix and a data.frame. This should be a serialized dataset that you can load for the example. 
* Avoid using `_` for dataset names and use a more descriptive name for the dataset.
* There's no need to have the `create_example_data.R` script in your package's `inst` folder. That can just be made into another vignette. But it does not seem like it uses the functions available in your package so it might be out of scope. 

## Grammar 

* Avoid the use of `1:n` sequence generation as this is prone to unintended behavior for when `n = 0`
* Avoid the use of `class(x) == "class"` language. If you are testing for S3 class membership, use `inherits()` or use `is()` for S4 classes. 
* Remove any messages that say `Good`. You only want to test for `errors` in the code not both.
* You don't need to annotate error messages with `Error`, use the `stop` function. 
* You also don't need to use `Caution` in messages, use the `warning` function. 
* `input_list` should be an S4 class with validity checks often you are modifying the object but it seems like a more formal definition of the class would help
* Please avoid using the `sapply` function for more robust code
* For functions that are using a random seed, you want to have a seed argument so that the user can set a specific seed and make your code reproducible in the long run. 
* In the function `icaRpar` you may want to rename your `fun` argument into something that does not indicate a functional argument. Perhaps you want to use `type`, `method`, etc.
* Don't use `$` as R's interpreter uses fuzzy matching with this accessor, use the more robust way of element accession via `[["elementName"]]`
* Establish default argument values instead of using `NULL` and changing it later.
* Please be mindful of the argument order. In functions like `runPCA`, `runICA`, you want to have the `SummarizedExperiment` argument as the first one and the matrix and data.frame as second and third optional arguments.
* Please create a helper function for all the "pheno" and "assay" checks that you repeatedly need to perform since you do allow those inputs for some functions. You can reuse this function for whenever you have a function with those arguments and avoid repetitive code. 
* When defining a class, you want to use the S4 system (e.g., pca_result). You class names should not have `_` in their names. 
* Avoid class assignment in the S3 way: e.g., `class(x) <- "newClass"`

## Misc 

* Please consider @lawremi 's comments about using a direct HTML output rather than via rmarkdown.

**Comment by jinhyunju** [comment] 2017-04-21 17:26
Dear Marcel (@LiNk-NY), 

Thank you very much for your feedback and I apologize for the late response. I've recently started a new job which required a big move from the east coast to the west coast, so I had limited time on hand to work on your feedbacks. 

I reflected most of the grammar related comments you have provided (bc_final branch on the picaplot repo) and am now starting the process to change the S3 system that is in place to the S4 system. However, since I am not familiar with the S4 system at all and this change needs broad code modification in almost every script, I think it will take me some time to get it done. Can you please confirm any deadlines or time restrictions if there are any? 

Thank you again for your thorough feedback, and I will try my best to reflect your comments as soon as possible. 


Best Regards,

Jin

**Comment by LiNk-NY** [comment] 2017-04-21 18:46
Hi Jin-hyun, @jinhyunju
There are currently no deadlines to submit the package. The deadline to submit the package to the upcoming Bioconductor release cycle has passed. Once you have made the changes and they have been accepted, your package will go into the development branch of Bioconductor. 
Best regards,
Marcel

**Comment by LiNk-NY** [comment] 2017-05-30 16:33
Hi Jin-hyun, @jinhyunju 
Any updates on the status of your package? Do you intend to work on it? 
Otherwise, I'd be forced to close the issue and possibly expect your resubmission. 

Best regards,
Marcel

**Comment by jinhyunju** [comment] 2017-05-30 16:38
Hi @LiNk-NY,
Apologies for the long radio silence. I've recently moved for a new job and had to devote most of my time in getting settled in (the reason why I asked you about the submission deadline). I think I will be able to work on this again starting the 2nd week of June. Thanks.


Best Regards,

Jin

**Comment by jinhyunju** [comment] 2017-06-11 20:24
Hello @LiNk-NY,

I went through the changes that would be needed in order to reflect the feedback related to changing the current S3 implementation into S4 classes, and came to the conclusion that it would be almost equal to re-writing the whole package. It would be great if the current S3 structure can be kept, since I have another package depending on picaplot, which would be affected by the change. Would it be possible to submit the package on the current S3 implementation (reflecting feedback except S4 changes)? If you think the change to S4 is absolutely necessary, I would like to close the issue and stop the process for bioconductor submission. Thank you very much, and apologies for the delayed response. 


Best Regards,

Jin

**Comment by LiNk-NY** [comment] 2017-06-19 17:01
Hi Jin-hyun, @jinhyunju

There are several reasons why we prefer using S4 classes instead of S3. These include but are not limited to robustness and validity checking. 
Your package would benefit from making classes such as `input_list` and others into S4 classes and avoid adding attributes to list-type classes.

Your argument about having other dependencies is not as strong as your submission is considered alpha at this stage but if you already have strong dependencies, I would have suggested that you first create a robust package. 

Any thoughts on this @mtmorgan ? 

PS. You can combine `matrix` and `SummarizedExperiment` type inputs into one argument and separate within the function (for convenience).

Regards,
Marcel

**Comment by LiNk-NY** [comment] 2017-07-19 21:17
Hi Jin-hyun @jinhyunju,
Any updates on making changes to the package?
There are some benefits that you can take advantage of by switching some
of your data structures to an S4-based class.

Regards,
Marcel

**Comment by jinhyunju** [comment] 2017-07-20 16:01
Hi Marcel, @LiNk-NY 
Thanks for checking on the status. I agree that my package could benefit from adopting the S4 class structure in terms of robustness, however, I honestly don't think I have the bandwidth at the moment to work on such a large change. You can go ahead and close the ticket if necessary.

**Comment by LiNk-NY** [comment] 2017-08-22 15:43
Hi Jin-hyun, @jinhyunju
Do you know more or less when you will have time to work on the package?
If it is a bit into the future, I can close it and you can either reopen it or create another issue.

Regards,
Marcel

**Comment by jinhyunju** [comment] 2017-08-22 15:55
@LiNk-NY ,
You can go ahead and close the ticket. Thank you very much.

**Comment by LiNk-NY** [comment] 2017-08-22 16:12
Hi Jin-hyun, @jinhyunju
Thank you for your submission. We hope to see your package with Bioconductor integration and with further development of your classes in S4 so that it benefits from validity checks and a structured definition. 
Best regards,
Marcel

**Closed by LiNk-NY** 2017-08-22 16:12 UTC
Labels: 2. review in progress, OK
