### ISSUE TITLE
segmenter

### ISSUE THREAD

**Issue by MahShaaban** [Bioconductor/Contributions#2056] opened 2021-04-19 04:16 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/MahShaaban/segmenter

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by MahShaaban** [comment] 2021-04-21 00:19
- I am receiving this error. 
```
ERROR: Package Source tarball exceeds Bioconductor size requirement.
    Package Size: 43.0723 MB
    Size Requirement: 5.0000 MB
```
The package wraps a Java program which I added to the package. In addition, there are data files that are necessary for some of the functions. 
What do you recommend I do in this case?

- I am also receiving an error about Watched Tags on the support site which I added!

```
ERROR: Maintainer must add package name to Watched Tags on the
      support site; Edit your Support Site User Profile to add Watched
      Tags.
```

**Comment by Kayla-Morrell** [comment] 2021-04-21 14:52
@MahShaaban - Please read our documentation [here](https://bioconductor.org/developers/package-guidelines/#data) about including data with a package. To summarize your options are either to create an accompanying data package that contains that data or store the data in our Hubs and access the data from there. 

As far as the Watched Tags, please be sure you have hit "Save" at the bottom of the page to be sure the changes to your profile are actively saved. If you feel you have done this correctly please provide a screenshot of the tags added in your profile and I will have someone check with the database to see what the issue is.

Best,
Kayla

**Comment by MahShaaban** [comment] 2021-04-22 00:42
Thanks, @Kayla-Morrell for the response. The resource you referred to was very helpful.
However, I am still not sure where to keep the Java modules (`.jar`) that the package is wrapping. These files are available as part of `ChromHMM`  on github but I am not sure how to include them otherwise.

**Comment by Kayla-Morrell** [comment] 2021-04-22 16:02
@MahShaaban - I believe the .jar files should go into an 'inst/java/' directory.

**Comment by MahShaaban** [comment] 2021-04-23 02:12
I am only trying to call the `.jar` using `system2`. The files are large, and including them in the package causes the error.

**Comment by MahShaaban** [comment] 2021-04-28 06:53
I created a new annotation package with the data files to keep this one within the size limit. I submitted the new package (https://github.com/Bioconductor/Contributions/issues/2101) and will add this one to the issue as an additional package.
Should I close this issue?

**Comment by Kayla-Morrell** [comment] 2021-04-28 12:41
@MahShaaban - Yes, this issue can be closed.

**Comment by MahShaaban** [comment] 2021-04-28 12:47
Okay. Thanks @Kayla-Morrell

**Comment by MahShaaban** [comment] 2021-05-07 10:05
AdditionalPackage: https://github.com/MahShaaban/chromhmmData

**Comment by MahShaaban** [comment] 2021-05-07 10:06
@hpages Same problem!

**Comment by lshep** [comment] 2021-05-07 12:07
Please try doing the AdditionalPackage line again.  I have deleted the previous issue out of our tracking database and you should be able to link the issue here now.

**Comment by MahShaaban** [comment] 2021-05-08 02:43
AdditionalPackage: https://github.com/MahShaaban/chromhmmData

**Comment by MahShaaban** [comment] 2021-05-08 02:44
Thanks @lshep

**Comment by MahShaaban** [comment] 2021-05-13 11:36
The data package now builds okay. I cannot however trigger the build for the `segmenter` package. I tried to push to the upstream but I got an error
```bash
! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git.bioconductor.org:packages/segmenter.git'
```

**Comment by lshep** [comment] 2021-05-13 11:38
Could you please show the complete command you tried with all the output produced.

**Comment by MahShaaban** [comment] 2021-05-13 11:43
```bash
$ git push upstream master
Enter passphrase for key '<path/to/key>': 
To git.bioconductor.org:packages/segmenter.git
! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git.bioconductor.org:packages/segmenter.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by lshep** [comment] 2021-05-13 11:46
And what do you have set up as remotes  `git remote -v`   ?

**Comment by lshep** [comment] 2021-05-13 11:46
The error seems to suggest your directory you are trying to push is not in sync with the remote.  I would do as it suggests and do a `git pull origin master` and `git pull upstream master`  and resolve any merge conflicts that arise before trying to push again.

**Comment by MahShaaban** [comment] 2021-05-13 12:13
The output of `git remote -v` was
```bash
origin	https://github.com/MahShaaban/segmenter (fetch)
origin	https://github.com/MahShaaban/segmenter (push)
upstream	git@git.bioconductor.org:packages/segmenter.git (fetch)
upstream	git@git.bioconductor.org:packages/segmenter.git (push)
```
I was not able to `git pull upstream master`. 
```bash
From git.bioconductor.org:packages/segmenter
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

This branch was behind for some reason so I used `--rebase` with the same command. 
I was able to push to `upstream/master` afterwards

**Comment by MahShaaban** [comment] 2021-05-15 01:11
I am getting this error in the latest build
```bash
> txdb <- TxDb.Hsapiens.UCSC.hg18.knownGene
> segs <- segment(test_obj)
> segs_annotated <- annotate_segments(segs, TxDb = txdb, verbose = FALSE)
Warning in getGenomicAnnotation(peak.gr, distance, tssRegion, TxDb, level,  :
  internal error -3 in R_decompress1
Error in getGenomicAnnotation(peak.gr, distance, tssRegion, TxDb, level,  : 
  lazy-load database 'C:/Users/biocbuild/bbs-3.13-bioc/R/library/ChIPseeker/R/ChIPseeker.rdb' is corrupt
Calls: annotate_segments ... lapply -> FUN -> annotatePeak -> getGenomicAnnotation
Execution halted
```
This is code is part of an example for one of the functions, and it used to run without errors!
Any advice on how to proceed?

**Comment by Kayla-Morrell** [comment] 2021-05-17 13:53
@MahShaaban - I believe this is an error that was produced after updating the R version on the builders a few days ago. The issue should have since been resolved. If you push a version bump hopefully the next build report will not have this error.

**Comment by MahShaaban** [comment] 2021-05-28 12:49
Since the package is building without errors or warnings. Is it now under review?

**Comment by Kayla-Morrell** [comment] 2021-05-28 12:51
@MahShaaban - Yes, I will be reviewing both packages and will post my initial review within the next few days. Thank you for you patience.

**Comment by MahShaaban** [comment] 2021-05-28 12:52
Thanks, @Kayla-Morrell I was just posting to see if there is anything I missed.

**Comment by Kayla-Morrell** [comment] 2021-06-08 15:11
@MahShaaban - Thank you for submitting to _Bioconductor_. Please see the initial review of
the package below. The required changes must be made while the suggested
changes do not have to be (though we strongly encourage them). Comment back
here with updates that have been made and when the package is ready for a
re-review.

# chromhmmData

## DESCRIPTION

- [ ] REQUIRED: Update R version dependency from 4.0 to 4.1.

- [ ] SUGGESTION: We strongly encourage including the 'BugReports:' field with  the relevant link to Github for reporting Issues.

## Vignette

- [ ] REQUIRED: There should be an 'Installation' section before loading the  package that demonstrates to the user how to install the package fromBioconductor.

```{r}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("chromhmmData")
```

- [ ] REQUIRED: The final section of the vignette should be 'Session  Information' and should include `sessionInfo()`.

# segmenter

## DESCRIPTION

- [ ] REQUIRED: 'LazyData:' should be set to false or removed.

- [ ] REQUIRED: Update R version dependency from 4.0 to 4.1.

- [ ] REQUIRED: The package 'methods' is used but not declared under 'Imports:'  or 'Suggests:'.

- [ ] SUGGESTION: We strongly encourage the use of 'BugReports:' field which  includes the relevant link to GitHub for reporting Issues.

## Data

- [ ] REQUIRED: We do not allow for 'data-raw' directories. It seems that these  files would be better in an 'inst/script/' directory since they somewhatdocument the data files.

- [ ] REQUIRED: Looking quickly at the files in the 'data-raw' directory, just  be sure that the locations for the saved files are correct. It looks like in'get_hg18_files.R' there is suppposed to be a 'hg18' directory within'inst/extdata' where the files are saved, but this directory is not present.Just double check this files to be sure everything is correct.

- [ ] REQUIRED: The docker directory should not be in the 'inst/extdata/'  directory since this location is intended for data only. I would suggestmoving it up to just the 'inst' directory, much like the 'java' directory.

- [ ] REQUIRED: All the data in the 'inst/extdata' directory requires  documentation in an 'inst/script/' directory. The scripts in this directorycan vary. Most importantly there should be documentation that clearly states howthe data was generated. It should include source urls and any importantinformation regarding filtering or processing. It can be exectuable code, sudocode, or a text description. A user should be able to download and roughlyreproduce the file or object that is present as data. 

## Vignettes

- [ ] REQUIRED: The only files that should be present in the directory are the  vignette files (.Rnw or .Rmd) and any necessary static images. The .R fileshould be removed.

- [ ] SUGGESTION: We strongly encouarge the use of table of contents.

- [ ] REQUIRED: All code chunks (minus the installation one) need to be  evaluated. Having static code in a vignette is not acceptable.

## Man pages

- [ ] REQUIRED: Add runnable examples to the following man pages which document exported objects:
        binarize_bed.Rd
        count_reads_ranges.Rd
        merge_segments_bins.Rd
        range_bins.Rd
        range_counts.Rd

## R code

- [ ] SUGGESTION: For formating reasons, consider multiples of 4 spaces for line indents. There are 274 lines that are not.

Best,
Kayla

**Comment by MahShaaban** [comment] 2021-06-09 10:22
Thanks @Kayla-Morrell
I made the required changes with the expectation of the very first and last for `segmenter`
- Removing `lazyData` from `DESCRIPTION` results in the build failure. I am using two data objects `test_obj` and `test_objs` in the tests and examples (about 50 of them). It would require a lot of manual editing to use `data()` instead.
- The functions without examples, although exported, are not intended to be for the end-user. I was not sure whether to export everything or use them as an internal function. I decided to export most of the code to make the review easier. What do you suggest?

**Comment by Kayla-Morrell** [comment] 2021-06-22 15:40
@MahShaaban - Thank you for making those changes. As far as the functions without examples, if they are not intended for the end-user than I would not export them. Once that change is made than I'll be able to accept the packages.

Best,
Kayla

**Comment by MahShaaban** [comment] 2021-06-23 05:12
I am getting this error on windows
```
ERROR: dependency 'chromhmmData' is not available for package 'segmenter'
```
I haven't made any changes to `chromhmmData` recently.

**Comment by lshep** [comment] 2021-06-23 11:30
We added the new devel builder.  chromhmmData probably has not built yet on that machine.  I will kick a manual build of that package now.  When that build report posts, you can kick off a new build of the software package.  Sorry for the inconvenience.

**Comment by Kayla-Morrell** [comment] 2021-07-07 11:43
@MahShaaban - Now that there is a clean build of the chrohmmData package, would you be able to bump the version of segmenter so we can be sure of a clean build for that package as well.

Best,
Kayla

**Comment by MahShaaban** [comment] 2021-07-07 12:03
Thanks @Kayla-Morrell. Done

**Comment by MahShaaban** [comment] 2021-07-07 12:34
Thanks @Kayla-Morrell

**Comment by vjcitn** [comment] 2021-07-08 17:22
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MahShaaban.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("segmenter")`. The package 'landing page' will be created at

https://bioconductor.org/packages/segmenter

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Comment by vjcitn** [comment] 2021-07-08 17:22
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/MahShaaban.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("chromhmmData")`. The package 'landing page' will be created at

https://bioconductor.org/packages/chromhmmData

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by vjcitn** 2021-07-08 17:22 UTC
Labels: 3a. accepted, OK
