### ISSUE TITLE
dpeak

### ISSUE THREAD

**Issue by carter-allen** [Bioconductor/Contributions#1427] opened 2020-03-20 14:40 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/carter-allen/dpeak

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by mtmorgan** [comment] 2020-03-20 16:34
Please provide a more comprehensive description, like a paper abstract providing users with insights into the strengths and weaknesses of your software.

Please remove the build products (e.g., pdf) of the vignettes; these are created during `R CMD build`.

Please update your vignette to include evaluated code chunks that actually use the functionality of your package; this provides both users and developers with the confidence that their package is functioning as intended.

Your assigned reviewer will provide additional comments in due course.

**Comment by LiNk-NY** [comment] 2020-04-06 14:45
Hi Carter, @carter-allen 

Can you explain why you are submitting the package instead of the indicated maintainer? 
The initial instructions state that the maintainer has to affirm to the commitment to long-term
maintenance. You aren't the maintainer as listed in the `DESCRIPTION` file. Please clarify. 

Best,
Marcel

**Comment by carter-allen** [comment] 2020-04-06 14:59
Hi Marcel, @LiNk-NY 

I am currently Dr. Dongjun Chung's (@dongjunchung) PhD student and I am handling the submission process for him. GPA, GGPA, and dpeak are packages that Dr. Chung had written in the past but had never formatted them for Bioconductor, so he asked me to help with getting the packages ready and submitting. He will remain the maintainer of the packages. Please let us know if there is any problem with this.

Thanks!
Carter

**Comment by lshep** [comment] 2020-04-14 13:24
The NEWS file ERROR is on our end. We have a fix implemented in linux and there will be a fix on windows by later this afternoon. I will kick off a manual build so there is at least an accurate linux build. it should post shortly.

**Comment by carter-allen** [comment] 2020-04-14 20:51
Hi @LiNk-NY, the dpeak package is now ready for review. I will refrain from further commits until the review is complete. Thanks!

**Comment by LiNk-NY** [comment] 2020-04-17 00:49
Hi Carter, @carter-allen 
Thank you for your submission. 
Please see the review below. 
Let me know if you have any questions and feel
free to post them below. 

Best,
Marcel

---

# dpeak #1427

Overall, the package demonstrates useful functionality though I am not sure if
these algorithms have been already provided in Bioconductor or on CRAN.
The package uses `IRanges` but it seems like it could go a step further and
make use of existing data representations such as `GRanges`.

## DESCRIPTION

* Submitters should be under the maintainer field and are considered responsible
for the upkeep of the package.
* Otherwise, have the maintainer affirm to responsibility of package maintenance
in the issue.
* It is suggested that you use the `Authors@R` field to provide maintainer and
author information.
* Dr. Chung can still be the author in `Authors@R` field

## NAMESPACE

* `export` (L#15) seems a bit vague, please rename to something more
informative. Are you exporting the data within the class?

## vignettes

* Looks good
* `plot` functions should not have file name arguments
* Remove vignette products such as `eps` and `pdf` files, they should be
created by the vignette code (?). If not, perhaps you can keep one file type
in the folder?

## R

* Can you use a `GRanges` representation for `DpeakData`, `DpeakMotif`?
* These classes look very complicated and perhaps it may be helpful if they
were built from other classes.
* Avoid using `print*` generic / methods. Create a `show` method for your
class(es).
* It's recommended to stay consistent with the naming conventions, this means
sticking to either `camelCase` or `snake_case`
* Avoid code duplication where possible (e.g., in `.combineModelSET` &
`.combineModelPET`)
* Use `message` to output to the console instead of `print` or `cat`
* Use `cat` only for `show` methods.
* We encourage to  find an alternative to using `perl` scripts and use native
R operations where possible.
* Be careful when using position indices instead of character ones. They are
less robust.
* Make sure that conditional statements evaluate to a single logical value,
for example `if (n_group >= 2)` where `n_group <- c(1, 2)`
* Avoid using `@` accessors and use established accessors for your class à la
`SummarizedExperiment::assay` for example.
* Remove old commented code
* `parallel` is a base package and you should not need to check for its
installation
* Avoid setting `nCore`s for the user. Use one or two cores by default
(important)
* It may not be necessary to create generic and methods for single functions
(e.g., `dpeakFit`)
* Avoid emphatic language in error / messages (e.g., 'Inappropriate 'x'
argument!')
* Remove `gc` and `rm` calls as R will take care of unused objects
* There are reservations for having `system` calls for external software such
as `fimo` and `meme`. Perhaps the R code can work with the output of this
software but not work with it directly?
* Provide `verbose` arguments for users who wish to turn of the messages in
functions.

Minor:
* Avoid double logical evaluation (e.g., `if (PET  == TRUE)` use
`if (PET)` or `if (isTRUE(PET))` when 'PET' is not always expected to be
logical.
* Use `identical` when comparing two strings (e.g., `identical(x, "common")`
instead of `estDeltaSigma == "common"`) especially within an `if` statement.
* Why not use `tempdir()` as the default argument to `tempDir` in `dpeakMotif`?

**Comment by LiNk-NY** [comment] 2020-04-17 00:53
BTW Carter, @carter-allen 
It looks like `meme` & `fimo` are only available on Mac and Linux so you will have to mark your package as unsupported on Windows.

Please update the `System requirements: ` so that these software are reflected there with versioning if possible.

**Comment by LiNk-NY** [comment] 2020-04-21 13:52
Hi Carter, @carter-allen 

I see that you made changes but you haven't addressed many of the
comments posted in the review. 
Please respond to each bullet point. 
Thank you.

Best,
Marcel

**Comment by carter-allen** [comment] 2020-04-21 13:57
Hi Marcel, @LiNk-NY 
Yes, the package is not ready for final submission. We are still working on addressing each point. I will tag you in a comment once we have finalized the package. 

Thanks,
Carter

**Comment by LiNk-NY** [comment] 2020-04-21 14:44
Hi Carter, @carter-allen 

Unfortunately, tomorrow is the last day for new packages to be added to the release manifest.
If you'd like to have the package added to the Bioconductor release please let us know.
Otherwise, we will host it in the development branch of Bioconductor until the next release. 

Best,
Marcel

**Comment by carter-allen** [comment] 2020-04-21 14:47
Thanks Marcel, @LiNk-NY  is there a deadline time today where we can still submit changes? I can have a response to each of your comments by the end of the day.

**Comment by LiNk-NY** [comment] 2020-04-21 14:53
@carter-allen 
The deadline to add the package to the manifest is tomorrow COB. If you can have the responses and changes ready by tomorrow, that would be great. Thank you.

**Comment by carter-allen** [comment] 2020-04-21 14:54
@LiNk-NY 
Ok great, we have the changes returned to you by then. Thanks!

**Comment by carter-allen** [comment] 2020-04-22 02:09
Hi Marcel, @LiNk-NY thank you for the helpful feedback on dpeak. We carefully read through each of your comments and made the following changes to the package.
 
DESCRIPTION
- We elected not to use the Authors@R field due to our specific arrangement where Dr. Chung is both first author and maintainer and I (Carter) am second author and submitter. Dr. Chung will reply to this post affirming his maintainer status.
- We updated the SystemRequirements to include dependencies on fimo and meme.
 
NAMESPACE
- export was renamed to exportPeakList to be more informative.
 
Vignette
- For dpeak, we feel it is necessary for plotting functions to write the plots to a file instead of displaying them for the user. The reason is that these plots often contain a large number of pages, making it impractical to display to the user all at once. To address your comment, we renamed the plot function to exportPlot. We feel this compromise allows dpeak to retain this functionality while not conflicting with the standard use of plot().
- In this vignette, plots are exported to a PDF using the function exportPlot() and we tried to show an example page from this PDF output. As a result, we thought that it is somewhat unnatural to make the vignette to generate and include these figure within the vignette. Hence, we decided to load pre-made figure files in the vignette instead. We understand this is not the ideal use of a vignette and will strongly consider ways to address this issue in future versions of dpeak.
 
R
- We will consider using GRanges instead of IRanges in future versions of dpeak as we do not expect this to make a significant change to the package performance and IRanges was used for a relatively limited purpose in this package.
- Unfortunately the nature of dpeak seems to require relatively complicated classes. We will consider ways of simplifying these classes in future versions of dpeak.
- We removed all uses of print methods and instead use show methods.
- We made efforts to unify the naming conventions throughout the package. All user facing functions now present a unified interface.
- The nature of the SET and PET procedures require similar but slightly different code. For this reason we feel it is best to keep the SET and PET methods separate for now, but we will consider more unified approaches in future versions of dpeak.
- We replaced all instances of print/cat with message (except for in show methods which use cat).
- The perl code was implemented and included mostly for the raw sequencing data preprocessing. Because raw sequencing files are large files that mostly consist of characters and this step needs be run only once, we feel that perl scripts can still be an efficient way to handle this task in a computationally efficient way. We will strongly consider ways of implementing these routines in R in future versions of dpeak.
- We verified the validity of all position indexing.
- We verified that all conditional statements evaluate to a single value.
- We replaced all instances of @ with the appropriate accessor method.
- We removed all commented code.
- We removed the check for installation of the parallel package.
- We changed all nCore defaults to 1 and do not set them otherwise unless the user does so explicitly.
- We will consider simplifying use of generics in future versions of dpeak.
- We removed all exclamatory language from messages to the user.
- We removed all uses of gc and rm.
- Since the only part of dpeak that requires fimo and meme is DpeakMotif, we clarified in the README that Windows users who do not have access to fimo and meme will not be able to utilize the DpeakMotif functionality.
- We have included a verbose argument to control message output.
- We avoided the use of double logicals when possible.
- We will consider using identical() and tempdir() in future versions of dpeak.
 
Thank you again for the helpful comments on dpeak. We feel they significantly improved the package. While we were not able to address every comment in this short time window we will certainly continue to work on these points in the future.
 
Thank you,
 
Carter Allen
Cc: @dongjunchung

**Comment by dongjunchung** [comment] 2020-04-22 02:19
Hi Marcel,

Here I confirm what Carter mentioned above. As he said, after Carter
complete the submission process, he will remain as a second author and I
will remain as both first author and maintainer of the dpeak package.

@LiNk-NY <https://github.com/LiNk-NY>
@carter-allen <https://github.com/carter-allen>

Thank you very much in advance!

Best,
Dongjun

**Comment by LiNk-NY** [comment] 2020-04-22 16:36
Hi Carter and Dongjun, @carter-allen @dongjunchung 

Thank you for making those changes and responding to the review. 
Your package has been accepted in time for the release.

* [Important] Please make sure that you add an error message for Windows users in the `dpeakMotif` function so that they are aware.

Best regards,
Marcel

**Comment by carter-allen** [comment] 2020-04-22 18:58
Thank you Marcel @LiNk-NY! I added that error message for DpeakMotif.

cc: @dongjunchung

**Comment by mtmorgan** [comment] 2020-04-22 19:04
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/carter-allen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("dpeak")`. The package 'landing page' will be created at

https://bioconductor.org/packages/dpeak

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2020-04-22 19:04 UTC
Labels: 3a. accepted, OK
