### ISSUE TITLE
mCSEAdata

### ISSUE THREAD

**Issue by jordimartorell** [Bioconductor/Contributions#552] opened 2017-11-13 11:10 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/jordimartorell/mCSEAdata

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/

**Comment by lshep** [comment] 2017-11-14 15:42
I'm rerunning the build check so there is a report using R 3.5 and Bioc 3.7 (the builders were updated today);  I should have a review within the next few days. 
Cheers

**Comment by jordimartorell** [comment] 2017-11-16 13:15
AdditionalPackage: https://github.com/jordimartorell/mCSEA

**Comment by lshep** [comment] 2017-11-17 18:04
Thank you for your submission to Bioconductor. Please see some comments below 

**Data Package**
Could you please be a little more specific on how the data was constructed from the annotation data? 

**Software Package**
- [ ] Can this be integrated with COHCAP?
- [ ] Please add unit tests
- [ ] Input and Output questions:  betaTest is a matrix of probes x samples - can this also be a summarizedExperiment? custom association object between CpG probes and regions - could this be a
GeneSet object?
 
Vignette:
- [ ] We don't encourage direct use of `$` for example `myResults$promoters[,-7]` could be writted as `myResults[["promoters"]][,-7]`
- [ ] Describe what is in each output object of list? what is stored in myResults[["promoters"]] and myResults[["promoters_associations"]]
- [ ] mCSEAPlot  takes a long time!  Reevaluate and try to speed up or at least have some output or progress bar that it is calculating. 

Man:
mCSEA-package and mCSEATest
use myResults[["promoters"]] over myResults$promoters

R Code:
rankProbes: 
- [ ] Are the outpus of minfi and ChAMP matricies?  It seems like minfi has output in a particular class - your function should work with this output. 

mCSEATest:
- [ ] why can't users input their own assocPromoters/assocGenes/assocCGI? what is the purpose of using your data? 
- [ ] Don't repeat code - you essentially do the same chunk of code based on what is defined in region or customAnnotation - this code should be a separate function and pass in appropriate argument for calculation 
- [ ] why is there a set.seed? 
- [ ] you said users can use their own with model of assocGenes450k should also be able to work with GeneSets

mCSEAPlot:
- [ ] need some status message or something that it is working 
- [ ] Don't repeat code - if you use `[[` instead of `$` don't need if/else/if
```
assoc <- mCSEAResults[[paste(regionType, "association", sep="_")]]
leadingCpGs <- strsplit(mCSEAResults[[regionType]][region, "leadingEdge"],",
")[[1]]
```

Please clarify or address the above issues and comment back when you have updates and are ready for a second review. 

Thank you for your submission to Bioconductor.

**Comment by jordimartorell** [comment] 2017-11-27 07:46
Hi Ishep, thanks for your really helpful comments. I modified mCSEA following your suggestions. Here I'll talk about each of your points:

> Data Package
> Could you please be a little more specific on how the data was constructed from the annotation data?

I extended the explanation in the vignettes (Sources section). I hope it is more clear now.

> Software Package
> 
>     Can this be integrated with COHCAP?

Yes, you can get a beta-values matrix with COHCAP.annotate() function and use this object as input of rankProbes() function (data parameter). However, users should modify the COHCAP output to fit the rankProbes() format requirements. Users could also use COHCAP.site() output instead to get some metric (e.g. delta beta, pvalue...) and use it to directly run mCSEATest function skipping rankProbes() step. Users should modify COHCAP output too to satisfy the mCSEATest() input format. Regarding to the analysis itself, COHCAP and mCSEA use very different approaches, so I think that both analysis are complementary, but integrating COHCAP analysis in mCSEA would be quite confusing for the users.

>     Please add unit tests

I added unit tests for rankProbes() and mCSEATest() functions. I don't test mCSEAPlot() and mCSEAPlotGSEA functions because they return a graphical output.

>     Input and Output questions: betaTest is a matrix of probes x samples - can this also be a summarizedExperiment? custom association object between CpG probes and regions - could this be a GeneSet object?

Now, rankProbes() function accepts a SummarizedExperiment object. Regarding custom association object, I think that the use of a GeneSet (or GeneSetCollection) object would be very confusing due to the gene sets should be the genes itselves, and the genes should be the CpG probes. In addition, to  my knowledge there are no methods to easily prepare such particular GeneSet object, so users should make an extra effort to prepare this object. I think that it's easier for users to prepare a list with the required format for the custom association. However, if you think that I should implement GeneSet compatibility despite what I said, I have no problem with trying it.


> Vignette:
> 
>     We don't encourage direct use of $ for example myResults$promoters[,-7] could be writted as myResults[["promoters"]][,-7]
>     Describe what is in each output object of list? what is stored in myResults[["promoters"]] and myResults[["promoters_associations"]]
>     mCSEAPlot takes a long time! Reevaluate and try to speed up or at least have some output or progress bar that it is calculating.

I fixed the use of $ and I better explained the contents of the mCSEATest output objects. mCSEAPlot is slow the first time is executed due to it connects to online servers in order to get genomic information. I improved one of the steps to use cached data, saving some time. Due to it is still slow, I added a progress bar too.

> Man:
> mCSEA-package and mCSEATest
> use myResults[["promoters"]] over myResults$promoters

Done.

> R Code:
> rankProbes:
> 
>     Are the outpus of minfi and ChAMP matricies? It seems like minfi has output in a particular class - your function should work with this output.

Althought minfi uses some special classes (e.g. MethylSet), it includes functions to get a matrix of beta-values (getBeta()) or M-values (getM()). ChAMP output class depends on the type of analysis performed. For instance, champ.norm() function returns a matrix, while champ.load() returns a list of results, and one of them is a beta-values matrix. So rankProbes() function is totally compatible with minfi and ChAMP outputs as long as a matrix with the methylation values is obtained.

> mCSEATest:
> 
>     why can't users input their own assocPromoters/assocGenes/assocCGI? what is the purpose of using your data?

Users can use their own association objects, that's the purpose of the "custom" parameter. I included assocPromoters/assocGenes/assocCGI because these are typical regions to search for DMRs, so users can use these prebuilt associations, saving them the creation of the association object. Of course, users can choose not using these objects (regionsTypes = NULL).

>     Don't repeat code - you essentially do the same chunk of code based on what is defined in region or customAnnotation - this code should be a separate function and pass in appropriate argument for calculation

I implemented that code in the internal function .performGSEA()

>     why is there a set.seed?

fgsea() function performs permutations, so the randomness cause that the calculated P-values are not exactly the same each time the function is run. I added a set.seed() to avoid that behaviour.

>     you said users can use their own with model of assocGenes450k should also be able to work with GeneSets

I talked about GeneSets objects in a previous comment.

> 
> mCSEAPlot:
> 
>     need some status message or something that it is working

I added a progress bar.

>     Don't repeat code - if you use [[ instead of $ don't need if/else/if

Fixed.

**Comment by lshep** [comment] 2017-12-13 15:04
Sorry for the delayed response; I will try to be better about responding more timely. Thank you for your updates.  A few more minor points below: 

**vignette:**
- [ ] show what to convert from minfi or ChAMP to use as examples since you mention them at the top (essentially what you explained to me here would be fine)
- [ ] still takes a long time (assumingly slow the first time is executed due to it connects to online servers in order to get genomic information) where progress bar is not active- maybe make note of this in the vignette that it could take some time to generate so users are aware


**Code:** 

- [ ] What is sysdata.rda in R directory? Seems like this should be deleted or at the very least moved to a data directory and documented. (then ::: call to it in code? - if in data directory change to load)

rankProbes.R / documentation
- [ ] extra 1 typo right at start of file. 
- [ ] should be library(mCSEA) not mCSEAdata in documentation
- [ ] this seems like a quick calculation - why have the dontrun in this documentation ?

mCSEATest.R / documentation
- [ ] I would add to regionTypes documentation:  NULL to skip this step and use customAnnotation. 
- [ ] really a set a seed should never be used inside function code - if you would like reproducible in example or vignettes call it outside of function and explain why. 

mCSEAPlot.R / documentation
- [ ] as mentioned plotting is still slow - perhaps add the progress,2 in between the minfi::RatioSet and minfi::getAnnotation,  as these steps appear to take awhile
- [ ]  what is the bandTable mCSEA:::bandTable? Is that something that was downloaded and saved (seems like this is the sysdata.R) - moved to data directory and load 

mCSEAPlotGSEA.R / documentation
- [ ] use [[""]] rather than '$'

Please address these issues and I will take another look. 
Cheers,

**Comment by jordimartorell** [comment] 2017-12-21 07:38
Hi Ishep. Thank you again for your helpful comments. Here I adress each of the points:

> vignette:
    show what to convert from minfi or ChAMP to use as examples since you mention them at the top (essentially what you explained to me here would be fine)

Added.

>     still takes a long time (assumingly slow the first time is executed due to it connects to online servers in order to get genomic information) where progress bar is not active- maybe make note of this in the vignette that it could take some time to generate so users are aware

Done.

> Code:
    What is sysdata.rda in R directory? Seems like this should be deleted or at the very least moved to a data directory and documented. (then ::: call to it in code? - if in data directory change to load)

Sorry for this, I read somewhere that internal data which it's not nececessary to be accesible for the users should be stored in sysdata.rda and undocumented. This file only contains the bandTable object, which is a downloaded file with chromosomic annotation to avoid the downloading of such file each time mCSEAPlot() is executed. I moved this object to data folder, I documented it properly and I changed the way mCSEAPlot() loads it. I tried to load it with load() function, but several errors occured during the building and checking, so I finally use this object with mCSEA::bandTable instance. I hope this is a correct way to do this.

> rankProbes.R / documentation
    extra 1 typo right at start of file.

Fixed.

>     should be library(mCSEA) not mCSEAdata in documentation

I tried to change this, but I obtained the following warning in BiocCheck: WARNING: The following files call library or require on mCSEA. This is not necessary. man/rankProbes.Rd.
I decided to remove this line.

>     this seems like a quick calculation - why have the dontrun in this documentation ?

It is indeed a quick calculation, but I thought to use the precomputedmCSEA object to save some seconds during the building and checking. I removed the dontrun.

> mCSEATest.R / documentation
    I would add to regionTypes documentation: NULL to skip this step and use customAnnotation.

Added.

>     really a set a seed should never be used inside function code - if you would like reproducible in example or vignettes call it outside of function and explain why.

I removed the set.seed() of the code and included outside the function in functions documentations and vignettes. I explained the purpose of including a set.seed() in vignettes.

> mCSEAPlot.R / documentation
    as mentioned plotting is still slow - perhaps add the progress,2 in between the minfi::RatioSet and minfi::getAnnotation, as these steps appear to take awhile

Added.

>     what is the bandTable mCSEA:::bandTable? Is that something that was downloaded and saved (seems like this is the sysdata.R) - moved to data directory and load

I explained this in a previous point. bandTable object has been moved to data directory, documented and loaded properly.

> mCSEAPlotGSEA.R / documentation
    use [[""]] rather than '$'

Fixed.

**Comment by jordimartorell** [comment] 2017-12-29 11:11
Hi again, Ishep, sorry for double-posting.
I included a new function and some changes:

- mCSEAIntegrate: A new function to integrate results with methylation data.
- _region_ parameter name in mCSEAPlot and mCSEAPlotGSEA has been changed to _dmrName_. I think this new name is more intuitive for the users.
- 2 new inputs are required by mCSEATest: methylation and phenotype data. I added this because the output of mCSEATest now contains those data and the platform (in addition to the results). The aim of that is to simplify mCSEAPlot, mCSEAPlotGSEA and the new mCSEAIntegrate inputs.

Of course, manuals, vignettes and unit tests have been updated according to these changes.

Thanks.

**Comment by lshep** [comment] 2018-01-11 13:26
Hi There, 

Please see the Notes in the build report especially concerning best coding practice and adjust the code accordingly.

While this is the first time you have received a TIMEOUT, it is somewhat problematic.  Generally the linux (malbec2) times are used for the requirement - It seems with recent changes even on the linux machine the build time exceed 7 min and the check time exceeds 6 min.  In the package guidelines the max for checking is 5 min.  Could you please reevaluate the code to try and make it more efficient so that the check time of 5 mins is meet.

**Comment by jordiferretes** [comment] 2018-01-15 13:40
Hi.
I realized that the problem was that downloading the arrays annotation data is much more slow in the Bioconductor servers that in my computer, so I stored these annotations in mCSEAdata package (annot450K and annotEPIC). Build and check times are significantly lower now.

Thanks.

**Comment by jordimartorell** [comment] 2018-01-15 13:44
Sorry, I replied with another account by mistake, but the previous message is mine.

**Comment by lshep** [comment] 2018-01-17 12:47
Thank you!

**Comment by mtmorgan** [comment] 2018-01-17 22:47
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jordimartorell.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"mCSEAdata\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mCSEAdata

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Comment by mtmorgan** [comment] 2018-01-17 22:47
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/jordimartorell.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `biocLite(\"mCSEA\")`. The package 'landing page' will be created at

https://bioconductor.org/packages/mCSEA

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://docs.google.com/forms/d/e/1FAIpQLSdlTbNjsQJDp0BA480vo4tNufs0ziNyNmexegNZgNieIovbAA/viewform

**Closed by mtmorgan** 2018-01-17 22:47 UTC
Labels: 3a. accepted, OK
