### ISSUE TITLE
(inactive) CMEA: An R Package for Systematic Exploration of Single-Cell Morphological Phenotypes from Transcriptomic Profile

### ISSUE THREAD

**Issue by isarnassiri** [Bioconductor/Contributions#344] opened 2017-04-08 00:49 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/isarnassiri/CMEA

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Subversion][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/source-control/
[6]: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by isarnassiri** [comment] 2017-04-08 00:58
Hello,


1.      I uploaded the CMEA package, including the complete repositories of cell morphology and transcriptomic profiles to the Github (https://github.com/isarnassiri/CMEA) through the Bitbucket.

2.      I submitted the CMEA package to the Bioconductor.

Best regards,
Isar

**Comment by isarnassiri** [comment] 2017-04-12 12:38
Hello,
I revised the code, and fixed the warnings. I have pushed the code to git.
Best regards,
Isar

**Comment by isarnassiri** [comment] 2017-04-20 19:01
Hello,

The "WARNINGS" is " 'rgl_init' failed, running with rgl.useNULL = TRUE", and is a problem with the build system itself.

Best regards,
Isar

**Comment by hpages** [comment] 2017-05-25 07:10
Hi Isar,

Thanks for submitting the CMEA package. Please take the time to read carefully our package guidelines here [](https://bioconductor.org/developers/package-guidelines/). CMEA fails to satisfy 2 important criteria from these guidelines: it's too big and the vignette has no real code chunks. Also, the package has usability issues that are so severe that it's almost impossible for me to test it and judge its usefulness. Overall it will need a lot of work to reach an acceptable level. See details below.

Regards,
H.

1. Package is too big: 73M. That's because it contains big data sets of experimental data. The source tarball of a Bioconductor software package should occupy less than 4MB on disk. Please check our package guidelines (at [](https://bioconductor.org/developers/package-guidelines/)) and make sure CMEA satisfies them. One way to reduce the size is to move all the experimental data to a separate data experiment package. Let's call this _solution 1_. If the data is not too big, another way to reduce the size of the package is to explicitly download the data in the examples or vignette. Let's call this _solution 2_.

2. Your data sets are poorly documented. We need to know exactly where the data is coming from and how it was retrieved. For example the man page for `Cell_Morphology_Profile` only says that the data comes from the LINCS database but it doesn't say what data it is exactly from this database or how it was extracted from it. Also the man page doesn't say what the row names of the data frame are. So if you opt for _solution 1_, make sure the data sets are well documented in the data experiment package. If you opt for _solution 2_, then things will be more transparent and reproducible because you'll provide the code for downloading the data sets. Even if you opt for _solution 1_, I would strongly suggest that you make available the code you used to generate the data sets in the data experiment package.

3. Your vignette doesn't contain any _real code chunks_ i.e. code chunks that are evaluated by `R CMD build`. This is called a _static_ vignette. Bioconductor vignettes should never be static i.e. they must contain real code chunks. See our package guidelines for more information on this.

4. None of your functions have arguments. The input they take is unclear. Some of it seems to come from some user defined variables (e.g. `number_of_features` for `Cell_Morphology_Enrichment_Analysis()`). But they also seem to take as input some files produced by other functions. This is very poor software design. Besides, none of this is documented. This makes the package barely usable.

5. One consequence of this design is that I can't run the example in the man page of the `Ranking_Cell_Morphological_features()` function:
```
    > library(CMEA)
    > example(Ranking_Cell_Morphological_features)

    R_C_M_> {
    R_C_M_+ data(Transcriptomic_Profile)
    R_C_M_+ data(Cell_Morphology_Profile)
    R_C_M_+ TOP=20
    R_C_M_+ Ranking_Cell_Morphological_features() 
    R_C_M_+ }
    Error in file(file, "rt") : cannot open the connection
    In addition: Warning message:
    In file(file, "rt") :
      cannot open file '/home/hpages/R/R-3.4.r72630/library/CMEA/TP_subset.txt':
    No such file or directory
```
   That's probably because it requires other things from other examples to run before it. All the examples should work independently from each others.

6. Some of your functions (e.g. `Cell_Morphology_Enrichment_Analysis()`) write their output to the package installation folder. This is a very bad idea. The package installation folder should always be treated as a read-only place.

7. Please use camelCase style for your function names e.g. `crossTabulation()` instead of `crosstabulation()` or `rankCellMorphologicalFeatures()` instead of `Ranking_Cell_Morphological_features()` etc... (Also note that you could use "rank" instead of "ranking".)
  
8. The examples provided in the man pages are all inside curly brackets (`{` ... `}`). These curly brackets have no purpose and should be removed.

9. Use `<-` instead of `=` for assignments.

**Comment by isarnassiri** [comment] 2017-06-20 19:58
Hello,

I am pleased to resubmit the revised version of CMEA package. I appreciated the constructive criticisms of the reviewer.  I have addressed each of his concerns as outlined below.

1.      Package is too big: 73M. That's because it contains big data sets of experimental data. The source tarball of a Bioconductor software package should occupy less than 4MB on disk. Please check our package guidelines (at ) and make sure CMEA satisfies them. One way to reduce the size is to move all the experimental data to a separate data experiment package. Let's call this solution 1. If the data is not too big, another way to reduce the size of the package is to explicitly download the data in the examples or vignette. Let's call this solution 2.

We moved the files of complete experimental data to a separate data experiment package, and used subset of the complete dataset as an example input. The package size now is 2.22MB.

2.      Your data sets are poorly documented. We need to know exactly where the data is coming from and how it was retrieved. For example the man page for Cell_Morphology_Profile only says that the data comes from the LINCS database but it doesn't say what data it is exactly from this database or how it was extracted from it. Also the man page doesn't say what the row names of the data frame are. So if you opt for solution 1, make sure the data sets are well documented in the data experiment package. If you opt for solution 2, then things will be more transparent and reproducible because you'll provide the code for downloading the data sets. Even if you opt for solution 1, I would strongly suggest that you make available the code you used to generate the data sets in the data experiment package.

The input data were explained in vignette/documents with more details. We explained the origin of data with proper citations.

3.      Your vignette doesn't contain any real code chunks i.e. code chunks that are evaluated by R CMD build. This is called a static vignette. Bioconductor vignettes should never be static i.e. they must contain real code chunks. See our package guidelines for more information on this.

We added some real code chunks to the vignette, and improved it thoroughly.

4.      None of your functions have arguments. The input they take is unclear. Some of it seems to come from some user defined variables (e.g. number_of_features for Cell_Morphology_Enrichment_Analysis()). But they also seem to take as input some files produced by other functions. This is very poor software design. Besides, none of this is documented. This makes the package barely usable.

The name of the functions were revised. We added arguments with comprehensive explanations. All functions return the R objects in the global environment after running them.

5.      One consequence of this design is that I can't run the example in the man page of the Ranking_Cell_Morphological_features() function:

    > library(CMEA)

    > example(Ranking_Cell_Morphological_features)



    R_C_M_> {

    R_C_M_+ data(Transcriptomic_Profile)

    R_C_M_+ data(Cell_Morphology_Profile)

    R_C_M_+ TOP=20

    R_C_M_+ Ranking_Cell_Morphological_features()

    R_C_M_+ }

    Error in file(file, "rt") : cannot open the connection

    In addition: Warning message:

    In file(file, "rt") :

      cannot open file '/home/hpages/R/R-3.4.r72630/library/CMEA/TP_subset.txt':

    No such file or directory

That's probably because it requires other things from other examples to run before it. All the examples should work independently.

Revised. All the examples work independently, and return the R objects in the global environment after running them.

6.      Some of your functions (e.g. Cell_Morphology_Enrichment_Analysis()) write their output to the package installation folder. This is a very bad idea. The package installation folder should always be treated as a read-only place.

Revised. All functions return their outputs to the global environment.

7.      Please use camelCase style for your function names e.g. crossTabulation() instead of crosstabulation() or rankCellMorphologicalFeatures() instead of Ranking_Cell_Morphological_features() etc... (Also note that you could use "rank" instead of "ranking".)

Thanks for the comment. We used CamelCase symbol names for function names.

6.      The examples provided in the man pages are all inside curly brackets ({ ... }). These curly brackets have no purpose and should be removed.

Unessential curly brackets in the man pages were removed.

7.      Use <- instead of = for assignments.

Revised.
Best regards,
Isar

**Comment by hpages** [comment] 2017-09-15 16:41
Hi Isar,

Thanks for updating your package. There are still important issues that will need to be addressed before we can add it to Bioconductor. Some of these issues were already reported to you but you apparently ignored them.

1. The vignette is still static i.e. the code chunks in it don't get evaluated and the output produced by the commands was just copy-paste'd from an interactive R session to the code chunk.

2. The `Mapping()` function doesn't take any argument. What datasets to use for input is hard-coded in the function itself. So it will always produce the same output. The situation is similar with all the other functions in the package: they all take as input the 3 datasets included in the package and the user has no control on this. Wouldn't the package be much more useful if one could use it on its own datasets?

3. The description of the value returned by your functions is too minimalist: "Repository of gene sets" for `CellMorphologyEnrichmentAnalysis()` or "gene-gene interaction network" for `GRN()`. You need to provide more details about the data structure that is returned e.g. what its type (matrix or data.frame etc...), what are the dimensions, what are the rows, what are the columns, are they named, what are names, etc... The user needs to know exactly what to expect.

4. After calling `Mapping()`, the vignette says:
```
You can find the results in your current directory.
```
However, after doing this, I don't see any results in my current directory.

5. When you have more than one entry in the references section of a man page, please separate them with a blank line. Otherwise they get displayed in a single paragraph and that hurts readability. See for example `?Cell_Morphology_Profile`.

6. Please remove the 2 following lines from the DESCRIPTION file:
```
  Packaged: 2016-06-02 15:29:15 UTC; inassiri1
  Author: Isar Nassiri [aut, cre], Matthew McCall [aut, cre]
```
These lines will be automatically added to the DESCRIPTION file of the source tarball produced by `R CMD build` (the Author line will be generated from the `Authors@R` line so you will need to add Matthew McCall in the latter if you want him to be credited as one of the authors of the package).

7. The CMEA.html file does not belong to the _package source tree_. Please remove it. The HTML version of the vignette will be built and added to the _package source tarball_ by `R CMD build`.

8. Please use camelCase style for the name of the `CellMorphologyEnrichmentAnalysis()` function i.e. start its name with a lower case c.

9. Please find a more specific name for the `Mapping()` function. The current name is too generic. Also please avoid starting function names with a capital letter.

Thanks,
H.

**Comment by hpages** [comment] 2017-09-29 14:51
Hi Isar,
Are you planning to follow up on this submission? If we don't hear back from you in the next couple of weeks, we'll close this issue.
Regards,
H.

**Comment by isarnassiri** [comment] 2017-11-06 09:04
Hello,
Sorry for my delay to response. I have moved from URMC, and my university email was terminated. Therefore, I did receive your email. 
Please open this issue, and I revise the package based on your comments this week.
Best regards,
Isar

**Comment by isarnassiri** [comment] 2017-11-06 09:07
Hello,
I used an up to date and accessible email address.
Best regards,
Isar

**Comment by mtmorgan** [comment] 2017-11-12 16:24
It makes more sense to make several commits locally, then build and check locally, and THEN push to your github repository.

**Comment by isarnassiri** [comment] 2017-11-12 17:41
Hello,

Thank you for your comments. I revised CMEA package accordingly. 

Sorry for the delayed response. I have move from URMC and my URMC email was terminated, therefore, I did not receive you message (Several days ago, I read it on the web page of package). 

Current version of package has been built without errors or warnings on all platforms, and has improved as follows:

1. The vignette is still static i.e. the code chunks in it don't get evaluated and the output produced by the commands was just copy-paste'd from an interactive R session to the code chunk.
Answer: Thank you for the comment. I revised code chucks, and functions are called in the vignette. 

2. The Mapping() function doesn't take any argument. What datasets to use for input is hard-coded in the function itself. So it will always produce the same output. The situation is similar with all the other functions in the package: they all take as input the 3 datasets included in the package and the user has no control on this. Wouldn't the package be much more useful if one could use it on its own datasets?
Answer: Thanks for your comment. I added the following three arguments to the all functions and now user has more control on inputs: 
1. Transcriptomic Profile
2. Cell Morphology Profile
3. Query Transcriptomic Profile

3. The description of the value returned by your functions is too minimalist: "Repository of gene sets" for CellMorphologyEnrichmentAnalysis() or "gene-gene interaction network" for GRN(). You need to provide more details about the data structure that is returned e.g. what its type (matrix or data.frame etc...), what are the dimensions, what are the rows, what are the columns, are they named, what are names, etc... The user needs to know exactly what to expect.
Answer: Thanks for your comment. I expanded the return part of functions, including information about data structure.

4. After calling Mapping(), the vignette says:
You can find the results in your current directory.
However, after doing this, I don't see any results in my current directory.
Answer: For all functions of package you can find the results in the R object.

5. When you have more than one entry in the references section of a man page, please separate them with a blank line. Otherwise they get displayed in a single paragraph and that hurts readability. See for example ?Cell_Morphology_Profile.
Answer: Thanks for your comment. I added blank lines between references. 

6. Please remove the 2 following lines from the DESCRIPTION file:
Packaged: 2016-06-02 15:29:15 UTC; inassiri1
Author: Isar Nassiri [aut, cre], Matthew McCall [aut, cre]
These lines will be automatically added to the DESCRIPTION file of the source tarball produced by R CMD build (the Author line will be generated from the Authors@R line so you will need to add Matthew McCall in the latter if you want him to be credited as one of the authors of the package).
Answer: I removed the extra lines from the description file of package.
 
7. The CMEA.html file does not belong to the package source tree. Please remove it. The HTML version of the vignette will be built and added to the package source tarball by R CMD build.
Answer: I removed the HTML version of the vignette from the vignette folder.

8. Please use camelCase style for the name of the CellMorphologyEnrichmentAnalysis() function i.e. start its name with a lower case c.
Answer: I used the camelCase to call the functions of package.

9. Please find a more specific name for the Mapping() function. The current name is too generic. Also please avoid starting function names with a capital letter.
Answer: The name of function was replaced with more specific name (mappingQueryTranscriptomic).

Best regards,
Isar

**Comment by isarnassiri** [comment] 2017-11-12 17:56
Hello,
My name is Isar Nassiri, and have developed CMEA package under supervision of Dr. Matthew McCall (University of Rochester - https://github.com/Bioconductor/Contributions/issues/344). You closed the issue because of did not response to your comments. Sorry for the delayed response. I have move from URMC to Oxford university, and my URMC email was terminated, therefore, I did not receive your message (Several days ago, I read it on the web page of package). I revised CMEA package accordingly. Current version of package has been built without errors or warnings on all platforms, and has improved as follows:

  1.  The vignette is still static i.e. the code chunks in it don't get evaluated and the output produced by the commands was just copy-paste'd from an interactive R session to the code chunk.
Answer: Thank you for the comment. I revised code chucks, and functions are called in the vignette.
  2.  The Mapping() function doesn't take any argument. What datasets to use for input is hard-coded in the function itself. So it will always produce the same output. The situation is similar with all the other functions in the package: they all take as input the 3 datasets included in the package and the user has no control on this. Wouldn't the package be much more useful if one could use it on its own datasets?
Answer: Thanks for your comment. I added the following three arguments to the all functions and now user has more control on inputs:
  3.  Transcriptomic Profile
  4.  Cell Morphology Profile
  5.  Query Transcriptomic Profile
  6.  The description of the value returned by your functions is too minimalist: "Repository of gene sets" for CellMorphologyEnrichmentAnalysis() or "gene-gene interaction network" for GRN(). You need to provide more details about the data structure that is returned e.g. what its type (matrix or data.frame etc...), what are the dimensions, what are the rows, what are the columns, are they named, what are names, etc... The user needs to know exactly what to expect.
Answer: Thanks for your comment. I expanded the return part of functions, including information about data structure.
  7.  After calling Mapping(), the vignette says:
You can find the results in your current directory.
However, after doing this, I don't see any results in my current directory.
Answer: For all functions of package you can find the results in the R object.
  8.  When you have more than one entry in the references section of a man page, please separate them with a blank line. Otherwise they get displayed in a single paragraph and that hurts readability. See for example ?Cell_Morphology_Profile.
Answer: Thanks for your comment. I added blank lines between references.
  9.  Please remove the 2 following lines from the DESCRIPTION file:
Packaged: 2016-06-02 15:29:15 UTC; inassiri1
Author: Isar Nassiri [aut, cre], Matthew McCall [aut, cre]
These lines will be automatically added to the DESCRIPTION file of the source tarball produced by R CMD build (the Author line will be generated from the Authors@R line so you will need to add Matthew McCall in the latter if you want him to be credited as one of the authors of the package).
Answer: I removed the extra lines from the description file of package.
  10. The CMEA.html file does not belong to the package source tree. Please remove it. The HTML version of the vignette will be built and added to the package source tarball by R CMD build.
Answer: I removed the HTML version of the vignette from the vignette folder.
  11. Please use camelCase style for the name of the CellMorphologyEnrichmentAnalysis() function i.e. start its name with a lower case c.
Answer: I used the camelCase to call the functions of package.
  12. Please find a more specific name for the Mapping() function. The current name is too generic. Also please avoid starting function names with a capital letter.
Answer: The name of function was replaced with more specific name (mappingQueryTranscriptomic).

Please continue to consider our application. Thanks.

Best regards,
Isar

**Comment by isarnassiri** [comment] 2017-11-12 18:03
Hello,

Thank you for your comments. I revised CMEA package according to the comments. 

Sorry for the delayed response. Unfortunately, my URMC email was terminated, and did not receive your message (Several days ago, I read it on the web page of package). 

Current version of package has been built without errors or warnings on all platforms, and has improved as follows:
1. The vignette is still static i.e. the code chunks in it don't get evaluated and the output produced by the commands was just copy-paste'd from an interactive R session to the code chunk.
Answer: Thank you for the comment. I revised code chucks, and functions are called in the vignette. 

2. The Mapping() function doesn't take any argument. What datasets to use for input is hard-coded in the function itself. So it will always produce the same output. The situation is similar with all the other functions in the package: they all take as input the 3 datasets included in the package and the user has no control on this. Wouldn't the package be much more useful if one could use it on its own datasets?
Answer: Thanks for your comment. I added the following three arguments to the all functions and now user has more control on inputs: 
1. Transcriptomic Profile
2. Cell Morphology Profile
3. Query Transcriptomic Profile

3. The description of the value returned by your functions is too minimalist: "Repository of gene sets" for CellMorphologyEnrichmentAnalysis() or "gene-gene interaction network" for GRN(). You need to provide more details about the data structure that is returned e.g. what its type (matrix or data.frame etc...), what are the dimensions, what are the rows, what are the columns, are they named, what are names, etc... The user needs to know exactly what to expect.
Answer: Thanks for your comment. I expanded the return part of functions, including information about data structure.

4. After calling Mapping(), the vignette says:
You can find the results in your current directory.
However, after doing this, I don't see any results in my current directory.
Answer: For all functions of package you can find the results in the R object.

5. When you have more than one entry in the references section of a man page, please separate them with a blank line. Otherwise they get displayed in a single paragraph and that hurts readability. See for example ?Cell_Morphology_Profile.
Answer: Thanks for your comment. I added blank lines between references. 

6. Please remove the 2 following lines from the DESCRIPTION file:
  Packaged: 2016-06-02 15:29:15 UTC; inassiri1
  Author: Isar Nassiri [aut, cre], Matthew McCall [aut, cre]
These lines will be automatically added to the DESCRIPTION file of the source tarball produced by R CMD build (the Author line will be generated from the Authors@R line so you will need to add Matthew McCall in the latter if you want him to be credited as one of the authors of the package).
Answer: I removed the extra lines from the description file of package.
 
7. The CMEA.html file does not belong to the package source tree. Please remove it. The HTML version of the vignette will be built and added to the package source tarball by R CMD build.
Answer: I removed the HTML version of the vignette from the vignette folder.

8. Please use camelCase style for the name of the CellMorphologyEnrichmentAnalysis() function i.e. start its name with a lower case c.
Answer: I used the camelCase to call the functions of package.

9. Please find a more specific name for the Mapping() function. The current name is too generic. Also please avoid starting function names with a capital letter.
Answer: The name of function was replaced with more specific name (mappingQueryTranscriptomic).

Best regards,
Isar

**Comment by isarnassiri** [comment] 2018-06-12 03:53
Dear Martin,


This is the developer of CMEA package.


You have closed the issue because of my delayed response. As I explained in my commented message on Nov 12, 2017, my URMC email was terminated, and I did not receive your message on time. I read it on the web page of the package and revised the package accordingly. Now the package is ready.


Could you please active the issue?  what is the solution?


Related links:
Bioconductor/Contributions
https://github.com/Bioconductor/Contributions/issues/344<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Bioconductor_Contributions_issues_344&d=DwMFAw&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=fZ4R5tLjDdsMpY0d0TW80LL4oaBT9jWFupMy_9eyUZE2W1ff5VRr472pqfjShWh8&m=gkNPY3Zza5tStI1Y03bp1aZB_YdCMmXJtgRa1U6RuaE&s=UcvxiR8ewWenSGx3HlvCr5uEKxKE6UxURx__ytK4ZE8&e=>
Bioconductor Package Builder - Build History
http://bioconductor.org/spb_reports/CMEA_buildreport_20171117051310.html<https://urldefense.proofpoint.com/v2/url?u=http-3A__bioconductor.org_spb-5Freports_CMEA-5Fbuildreport-5F20171117051310.html&d=DwMFAw&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=fZ4R5tLjDdsMpY0d0TW80LL4oaBT9jWFupMy_9eyUZE2W1ff5VRr472pqfjShWh8&m=gkNPY3Zza5tStI1Y03bp1aZB_YdCMmXJtgRa1U6RuaE&s=mzpW0mqVsV-J-ipa1OA3MHQA_E658x9I_nMKfrhwo2E&e=>
GitHub repository of the package
https://github.com/isarnassiri/CMEA<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_isarnassiri_CMEA&d=DwMFAw&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=fZ4R5tLjDdsMpY0d0TW80LL4oaBT9jWFupMy_9eyUZE2W1ff5VRr472pqfjShWh8&m=gkNPY3Zza5tStI1Y03bp1aZB_YdCMmXJtgRa1U6RuaE&s=knALPlMCouwsO_Oowp39nsGbhjqTlJbso5iKITwIOYI&e=>


Best regards,

Isar

------------------------------------------
Isar Nassiri, PhD.
Researcher
Department of Oncology
MRC Weatherall Institute of Molecular Medicine
University of Oxford
John Radcliffe Hospital
Headington
Oxford OX3 9DS
United Kingdom
Tel: +44 1865 222569
isar.nassiri@oncology.ox.ac.uk
------------------------------------------

**Comment by mtmorgan** [comment] 2018-08-10 21:10
Thank you for your continued work on the package. There are many serious problems remaining, and I feel that the package cannot easily be brought up to Bioconductor standards. I am therefore declining the package in hopes that you identify more appropriate avenues for its distribution. I apologize that it has taken so long to reach this conclusion.

Two brief illustrations of the problems

**How functions return values** For the `cellMorphologyEnrichmentAnalysis()` function you indicate that the return value is 

``` 
#'@return 1. A data frame including 812 cell morphological features
#'     (row) and associated land mark genes with each feature
#'     (column); 2. A data frame including profiles of cell
#'     morphological features of similar drugs/small compound
#'     molecules with query (row drug/small molecule compound ID, and
#'     column cell morphological features); 3. A data frame including
#'     gene expression profiles of similar drugs/small compound
#'     molecules with query (row drug/small molecule compound ID, and
#'     column cell morphological features); 3. A data frame including
#'     gene expression profiles of similar drugs/small compound
#'     molecules with query (row drug/small molecule compound ID, and
#'     column gene symbol).
```

Toward the end of the function you have

```
  cellMorphologyEnrichment <<- as.data.frame(agregatation)
  length(cellMorphologyEnrichment$feature)
  
  #-- Save data --
  return(CMP_subset)
  return(TP_subset)
  return(cellMorphologyEnrichment)

  print("You can find the results in the 'cellMorphologyEnrichment' R objects.")
```

The use of `<<-` in the first line is very bad practice. It creates an object `cellMorphologyEnrichment` in the environment where the function was called, but the user might already have an object `cellMorphologyEnrichment`, e.g., from a previous run, that they were expecting to continue using.

The `length()` function call has no purpose, since the return value is not assigned to a symbol for later use.

The first `return()` statement returns `CMP_subset` to the user as the result of of this function; the remaining three statements are not executed. It's clear that the return value advertised in the documentation is not satisfied (only one data.frame is returned to the user) but at the same time it shows a serious misunderstanding of how _R_ functions work.


**Inefficient _R_ code**  There are many loops that could instead be vectorized calculations; these will be _much_ faster. A couple are illustrated here:

    ```
    diff --git a/R/CMEA.R b/R/CMEA.R
    index 9098071..da1fbc4 100644
    --- a/R/CMEA.R
    +++ b/R/CMEA.R
    @@ -339,16 +339,13 @@ cellMorphologyEnrichmentAnalysis <- function(number_of_features, Query_Transcrip
     
       for(j in 1:dim(repositoyr_binary)[1])
       {
    -    for(i in 1:dim(repositoyr_binary)[2])
    -    {
    -      a <- query_binary[i]  #my standard
    -      b <- repositoyr_binary[j,i]
    +      a <- query_binary  #my standard
    +      b <- repositoyr_binary[j,]
    +      TP <- sum(a + b == 2)
    +      TN <- sum(a + b == 0)
    +      FP <- sum(a == 0 & b == 1)
    +      FN <- sum(a == 1 & b == 0)
     
    -      if(a+b == 2) { TP <- TP + 1 }
    -      if(a+b == 0) { TN <- TN + 1 }
    -      if(a == 0 && b == 1) { FP <- FP + 1 }
    -      if(a == 1 && b == 0) { FN <- FN + 1 }
    -    }
         performance[j,1] <- TP
         performance[j,2] <- TN
         performance[j,3] <- FP
    @@ -373,8 +370,7 @@ cellMorphologyEnrichmentAnalysis <- function(number_of_features, Query_Transcrip
     	  max <- max(CMP_subset[,l])
     	  range <- max-min
     	  
    -	  for(t in 1:dim(CMP_subset)[1])
    -	  {  CMP_subset[t,l] <- ((CMP_subset[t,l]-min)/range) }
    +	  CMP_subset[,l] <- ((CMP_subset[,l]-min)/range)
     	}
     
       for(l in 1:dim(TP_subset)[2])
    ```
    
   the second can be further vectorized using _R_'s rule recycling rules as
   
    ```
    CMP_subset <- t((t(CMP_subset) - min) / range)
    ```
    
**Incorrect code** There seem to be problems with basic elements of the code. One example is 

```
        MCR[[i]] <- "NULL"
  ...

  null_cms <- which(sapply(MCR, is.null))
```

which appears to use the text string `"NULL"` as a stand-in for the symbol `NULL`. But is clearly not correct

```
> sapply(list("NULL"), is.null)
[1] FALSE
```

**Closed** 2018-08-10 21:10 UTC
Labels: 3b. declined

**Comment by isarnassiri** [comment] 2019-05-12 20:54
Hello,

Excuse me, we have a package called SRGnet (https://www.bioconductor.org/packages/release/bioc/html/SRGnet.html), and its full title on Bioconductor is as follows:


SRGnet: An R package for studying synergistic response to gene mutations from transcriptomics data from transcriptomics data

We need to remove the duplicated 'from transcriptomics data' part and revise the full title as follows:

SRGnet: An R package for studying synergistic response to gene mutations from transcriptomics data

I do not have access to the GitHub repository of the package. Could you please guide me in this regard?

Best regards,
Isar
------------------------------------------

Isar Nassiri, PhD.

Postdoctoral researcher

Department of Oncology

MRC Weatherall Institute of Molecular Medicine
University of Oxford
John Radcliffe Hospital
Headington
Oxford OX3 9DS

United Kingdom

Tel: 018 6522 2569

isar.nassiri@oncology.ox.ac.uk

------------------------------------------

**Comment by mtmorgan** [comment] 2019-05-12 21:43
Responded via email:

visit

  https://git.bioconductor.org/BiocCredentials

and choose 'Activate Your Account' using the email address

  isar_nassiri@urmc.rochester.edu

Instructions are available at

  https://bioconductor.org/developers/how-to/git/new-package-workflow/

or

  https://bioconductor.org/developers/how-to/git/maintain-bioc-only/

Further questions should be addressed to the bioc-devel mailing list

  https://stat.ethz.ch/mailman/listinfo/bioc-devel
