### ISSUE TITLE
BOBaFIT package

### ISSUE THREAD

**Issue by bioinformatic-seragnoli** [Bioconductor/Contributions#2345] opened 2021-09-29 14:55 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/bioinformatic-seragnoli/BOBaFIT

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by LiNk-NY** [comment] 2021-10-06 19:18
Hi Gaia, @bioinformatic-seragnoli 

Thank you for your submission. 
Please see the review below. 

Best regards,
Marcel

---

# BOBaFIT #2345

## DESCRIPTION

* (optional) Ensure that the DESCRIPTION file fits within an 80-character
width limit.
* Only specify version requirements for packages where you are using a feature
that is not available in the older version of the package, otherwise it is
not necessary.
* R depends version should be either removed or set to `4.1.0`

## NAMESPACE

* Please use a more descriptive name for `PlotCluster`.
* Consider using the native pipe `|>` to avoid the `tidyr` dependency.

## vignettes

* Please restrict the vignette to 80 character width (in `vim` this can be
done with `gqq`).
* Check for typos, e.g., in the `abstract:`.
* Perhaps you could use that data that is already in Bioconductor such as from
`curatedTCGAData`, `GenomicDataCommons`, `TCGAbiolinks` and others?
* Use a more descriptive argument name (`perc`) for the
`computeNormalChromosome` function.
* Please use a `GRanges` or `GRangesList` representation for
`computeNormalChromosomes` and `DRrefit` to avoid manual calculations such as
those for `width`.
* Separate analysis and graphing functionality. `computeNormalChromosomes`
and `DRrefit` should only perform the computations and not graph. Those should
be a separate functions.

## R

* Please add a description to the `computeNormalChromosomes` documentation.
* Add a `verbose` argument to `computeNormalChromosomes` and `DRrefit`.
* Do not use `cat` or `print` and use `message`.
* Resolve these errors from the example:
```r
Error in as.vector(x, "character") :
  cannot coerce type 'closure' to vector of type 'character'
In addition: Warning messages:
1: In max(DiffLev[, 5], na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
2: In matrix(c(results), nrow = 2, ncol = 26) :
  data length [51] is not a sub-multiple or multiple of the number of rows [2]
3: In matrix(c(results), nrow = 2, ncol = 26, dimnames = list(c("Number_clusters",  :
  data length [51] is not a sub-multiple or multiple of the number of rows [2]
```
* PlotCluster seems to cycle through all the samples. Is this intended?
I am not sure this can easily be interpreted / displayed.
* Please follow our [package guidelines][1] and avoid `1:n` sequences. Use the
more robust `seq_len(n)` or `seq_along(x)`.
* Avoid the copy and append method in `DRrefit`, this can provide significant
performance drawbacks.
* Do not save files for the user. Please remove the `png` & `dev.off()`
function calls from the function and allow the user to choose their own
file and graphics format.

## tests

* Please add unit tests to the package.

## /

* Remove the intermediate `.md` file from the vignettes folder.

[1]: http://contributions.bioconductor.org/

**Comment by LiNk-NY** [comment] 2021-10-19 17:13
Close due to inactivity.

**Comment by bioinformatic-seragnoli** [comment] 2021-10-20 08:07
Sorry if we took a long time  to answer, but we still are working on the comments received. Is it possible to reopen our submission issue? We did a lot of work and we are going to push our last updates in a few days. Sorry again for the inactivity, but we never received any advise about a maximum inactivity time, nor we received any warning about the closing of our submission. Thank you for the attention, we hope that you can help us.

**Comment by bioinformatic-seragnoli** [comment] 2021-10-20 14:53
Dear Marcel,
in the latest version of the package we have applied many fixes you suggested. At the moment we still have to: create the unit tests, fix the "BOBaFIT" vignette with the last changes and add the verbose argument. We hope to conclude as soon as possible.
Best reguards,
Bioinformatics Seragnoli

**Comment by LiNk-NY** [comment] 2021-10-20 20:12
Hi @bioinformatic-seragnoli 
Please make sure to respond to the review line by line. 
We expect maintainers to be responsive; therefore, a two week no-response 
merits the issue to be closed. We will make this more clear in our [submission guidelines](https://bioconductor.org/developers/package-submission/). 
Best,
Marcel

**Comment by bioinformatic-seragnoli** [comment] 2021-11-05 10:50
Hi @LiNk-NY  , 
We are about to complete the improvements to our package. As soon as possible, we will provide a detailed list of all the changes made by replying point by point to your review.
Best,
Bioinformatics Seragnoli

**Comment by LiNk-NY** [comment] 2021-11-22 23:28
Hi @bioinformatic-seragnoli , 
Any updates on the changes? Thank you. 
-Marcel

**Comment by bioinformatic-seragnoli** [comment] 2021-11-24 14:18
Hi @LiNk-NY,
that's the report of all changes made based on your suggestions.
Thank you,
Bioinformatics Seragnoli

**DESCRIPTION**
1.	(optional) Ensure that the DESCRIPTION file fits within an 80-character width limit.  **Done**
2.	Only specify version requirements for packages where you are using a feature that is not available in the older version of the package, otherwise it is not necessary. **Done: all package versions are removed**
3.	R depends version should be either removed or set to 4.1.0. **Done:  version removed **

**NAMESPACE**
1.	Please use a more descriptive name for PlotCluster.  **Done: renamed as `PlotChrCluster`**
2.	Consider using the native pipe |> to avoid the tidyr dependency.
**We would prefer not to use native pipe as it’s available only from R 4.1.0 and we aim to be compatible with all R versions**

**vignettes**
1.	Please restrict the vignette to 80 character width (in vim this can be done with gqq). **Done**
2.	Check for typos, e.g., in the abstract:.  **Done**
3.	Perhaps you could use that data that is already in Bioconductor such as from 
curatedTCGAData, GenomicDataCommons, TCGAbiolinks and others? 
**Done: Thanks for your suggestion, we used the TCGAbiolinks package to download BRCA segments. We also integrated a vignette “Data preparation” where it explained how to process the downloaded data frame, in order to be the perfect BoBafit input .** 
4.	Use a more descriptive argument name (perc) for the computeNormalChromosome function. **Done: we changed it in `tolerance_val`**
5.	Please use a GRanges or GRangesList representation for computeNormalChromosomes and DRrefit to avoid manual calculations such as those for width. 
 **We decided to include the width as one of the fundamental column of the input dataset, in order to avoid the loading of another package**.
6. Separate analysis and graphing functionality. computeNormalChromosomes and DRrefit should only perform the computations and not graph. Those should be a separate functions. 
** Done: We create a new function DRrefit_plot in order to separate the graphic part of the function. However, for computeNormalChromosome, we prefer to leave unchanged the function as the graph it’s a simple support to visualize the vector (main output of the function)**

**R**
1.	Please add a description to the computeNormalChromosomes documentation. **Done**
2.	Add a verbose  argument to computeNormalChromosomes and DRrefit.  **Done**
3.	Do not use cat or print and use message. **Done**
4.	Resolve these errors  from the example: **Done**

```
Error in as.vector(x, "character") : cannot coerce type 'closure' to vector of type 'character'
In addition: Warning messages: 
1: In max(DiffLev[, 5], na.rm = TRUE) : no non-missing arguments to max; returning -Inf
2: In matrix(c(results), nrow = 2, ncol = 26) : data length [51] is not a sub-multiple or multiple of the number of rows [2]
3: In matrix(c(results), nrow = 2, ncol = 26, dimnames = list(c("Number_clusters",  :
data length [51] is not a sub-multiple or multiple of the number of rows [2]
```

5.	PlotCluster seems to cycle through all the samples. Is this intended? I am not sure this can easily be interpreted / displayed.
**Yes, this behavior is intended, as it’s a function parallel to DRrefit that does the same analysis on the samples, but it shows in detail the computed clusters of DRrefit. If you think this is not understandable we can improve the vignettes, but it clearly says that the function “can cluster either a sample cohort or a single sample”.**
6.	Please follow our package guidelines and avoid 1:n sequences. Use the more robust seq_len(n) or seq_along(x).  **Done**
7.	Avoid the copy and append method in DRrefit, this can provide significant performance drawbacks. **Done** 
8.	Do not save files for the user. Please remove the png & dev.off() function calls from the function and allow the user to choose their own file and graphics format. 
 **Done: Thank you for your suggestion, we added the argument `plot_format` into `DRrefit_plot `and `PlotChrCluster `permits to the user to choose their own preferred format for the plots (“png”, “pdf”, “tiff” or “jpg”).**

**tests**
•	Please add unit tests to the package. **Done**
**/**
•	Remove the intermediate .md file   from the vignettes folder. **Done**

**Comment by LiNk-NY** [comment] 2021-11-24 23:28
Hi @bioinformatic-seragnoli, 

> 2. Consider using the native pipe |> to avoid the tidyr dependency.
>    **We would prefer not to use native pipe as it’s available only from R 4.1.0 and we aim to be compatible with all R versions**
> 

After the package is published in Bioconductor, users will not be able to use your package outside of R version `>= 4.2.0`. These constraints are imposed by Bioconductor versioning. I recommend that you create a `legacy` branch in your repository for users who have not updated their version of R and add a disclaimer stating that the package is not guaranteed to work because it was developed with a newer version of R. 

> 6. Separate analysis and graphing functionality. computeNormalChromosomes and DRrefit should only perform the computations and not graph. Those should be a separate functions.
>    ** Done: We create a new function DRrefit_plot in order to separate the graphic part of the function. However, for computeNormalChromosome, we prefer to leave unchanged the function as the graph it’s a simple support to visualize the vector (main output of the function)**

Consider creating modular functions that can accept the output of the analysis function and generate the graphs. This is the recommended way of designing pure and easily testable functions.

* Consider exporting the pipe operator (`%>%`) if you intend users to make use of the pipe with your package. See `?usethis::use_pipe`. 

> 8. Do not save files for the user. Please remove the png & dev.off() function calls from the function and allow the user to choose their own file and graphics format.
>    **Done: Thank you for your suggestion, we added the argument `plot_format` into `DRrefit_plot `and `PlotChrCluster `permits to the user to choose their own preferred format for the plots (“png”, “pdf”, “tiff” or “jpg”).**

I did not mean to provide options for the user but to allow the user to save the graphics device themselves by not having the function save the graphics. This let's the user save to any graphics format not covered by your coding, e.g., `.eps`, `.pdf`, etc. 

* Avoid writing files by default and remove the `plot_save = TRUE` default option. 

Minor: `if (x)` is preferred over `if (x == TRUE)`, when `x` is expected to be logical. 

-MR

**Comment by bioinformatic-seragnoli** [comment] 2021-12-01 13:26
Hi @LiNk-NY ,
we don't know the reason of the error resulting from the BiocCheckGitClone step, as our DESCRIPTION file is the same of previous versions.  Maybe you can give us some advice to fix this error.
However, the following lines are the report for your last review.
Thank you for your work

Bioinformatic Seragnoli 
> 
> > 2. Consider using the native pipe |> to avoid the tidyr dependency.
> >    **We would prefer not to use native pipe as it’s available only from R 4.1.0 and we aim to be compatible with all R versions**
> 
> After the package is published in Bioconductor, users will not be able to use your package outside of R version `>= 4.2.0`. These constraints are imposed by Bioconductor versioning. I recommend that you create a `legacy` branch in your repository for users who have not updated their version of R and add a disclaimer stating that the package is not guaranteed to work because it was developed with a newer version of R.
> 

**Done: we created a "legacy" branch on our repository.**




> > 6. Separate analysis and graphing functionality. computeNormalChromosomes and DRrefit should only perform the computations and not graph. Those should be a separate functions.
> >    ** Done: We create a new function DRrefit_plot in order to separate the graphic part of the function. However, for computeNormalChromosome, we prefer to leave unchanged the function as the graph it’s a simple support to visualize the vector (main output of the function)**
> 
> Consider creating modular functions that can accept the output of the analysis function and generate the graphs. This is the recommended way of designing pure and easily testable functions.
> 

**The newly created  function "DRrefit_plot" works exactly in the way you propose: it's a modular function that takes as input the output of "DRrefit".**  


> * Consider exporting the pipe operator (`%>%`) if you intend users to make use of the pipe with your package. See `?usethis::use_pipe`.
> 

**Done.**

> > 8. Do not save files for the user. Please remove the png & dev.off() function calls from the function and allow the user to choose their own file and graphics format.
> >    **Done: Thank you for your suggestion, we added the argument `plot_format` into `DRrefit_plot `and `PlotChrCluster `permits to the user to choose their own preferred format for the plots (“png”, “pdf”, “tiff” or “jpg”).**
> 
> I did not mean to provide options for the user but to allow the user to save the graphics device themselves by not having the function save the graphics. This let's the user save to any graphics format not covered by your coding, e.g., `.eps`, `.pdf`, etc.
> 

**We dont' understand in practice what do you mean with "allow the user to save the graphics device themselves". That's because the main output of the function are the graphics and the output must include them. In particular, the function consists in a loop that cycles over all the samples, and at each iteration a different graphic is produced, so the user cant possibly open a new graphic device and save his own graphic at each iteration. 
Also, we think that every commonly used graphics format is already included in the current function code, including .pdf**

> * Avoid writing files by default and remove the `plot_save = TRUE` default option.
> 

**Done**

> Minor: `if (x)` is preferred over `if (x == TRUE)`, when `x` is expected to be logical.
> 

**Done**

**Comment by bioinformatic-seragnoli** [comment] 2021-12-07 11:00
Dear @LiNk-NY,
Please can you give us some insights about our error ouput in the build report? Sorry for the insistence but we tryed to reproduce the error without success. We also tried in multiple ways to revert the repository to an old version but the check section in report still returns an error in the untar procedure, and we dont' know what can be the cause behind that. The following is the problematic output:
`tar.exe: Error opening archive: Error reading 'D:/pkgbuild/packagebuilder/workers/jobs/2345/de7589321eb892b6f70a98572dec4bf6813eb441/BOBaFIT'
Warning in untar(pkgname, exdir = tmp_dir) :
  'tar.exe -xf "D:/pkgbuild/packagebuilder/workers/jobs/2345/de7589321eb892b6f70a98572dec4bf6813eb441/BOBaFIT" -C "C:/Users/pkgbuild/AppData/Local/Temp/RtmpuKr5wC/file23a83e157825"' returned error code 1` 

The curious thing is that the untar procedure works well in the linux and macOS machines, but surprising it doesnt in the windows one.
Thank you for the assistance and your attention, 

Bioinformatics Seragnoli

**Comment by LiNk-NY** [comment] 2021-12-08 18:11
Hi @bioinformatic-seragnoli 
I will take a look at this. It is coming from `BiocCheck::BiocCheckGitClone`.
I've made some changes to this and they may be the cause. 
Best,
Marcel

**Comment by LiNk-NY** [comment] 2021-12-08 21:57
I am unable to reproduce this locally with the latest version of `BiocCheck`. 

```r
BiocCheckGitClone("BOBaFIT")
This is BiocCheckGitClone version 1.31.14. BiocCheckGitClone is a
work in progress. Output and severity of issues may change.
* Checking valid files...
* Checking DESCRIPTION...
* Checking if DESCRIPTION is well formatted...
* Checking for valid maintainer...
* Checking CITATION...

Summary:
ERROR count: 0
WARNING count: 0
NOTE count: 0
For detailed information about these checks, see the BiocCheck
vignette, available at
https://bioconductor.org/packages/3.15/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#interpreting-bioccheck-output
$error
character(0)

$warning
character(0)

$note
character(0)
```

**Comment by LiNk-NY** [comment] 2021-12-09 20:15
Hi @bioinformatic-seragnoli 
Can you bump the version for another build on the SPB? 
Thanks.
-Marcel

**Comment by bioinformatic-seragnoli** [comment] 2021-12-13 10:20
> Hi @bioinformatic-seragnoli Can you bump the version for another build on the SPB? Thanks. -Marcel

Hi @LiNk-NY ,
we did the version bump as suggested,  however we can't see the build report. We're waiting for an update from you.
Best,
Bioinformatics Seragnoli

**Comment by LiNk-NY** [comment] 2021-12-14 17:09
Hi @bioinformatic-seragnoli 
Thank you for your contribution. 
Your package has been accepted.
Best regards,
Marcel

**Comment by lshep** [comment] 2021-12-15 17:34
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/bioinformatic-seragnoli.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("BOBaFIT")`. The package 'landing page' will be created at

https://bioconductor.org/packages/BOBaFIT

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-12-15 17:34 UTC
Labels: OK, 3a. accepted
