### ISSUE TITLE
SOMNiBUS

### ISSUE THREAD

**Issue by kkleinoros** [Bioconductor/Contributions#1761] opened 2020-11-09 20:24 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/kaiqiong/SOMNiBUS

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [ X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [ X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [ X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [ X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [ X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [ X] The 'devel' branch for new packages and features.
- [ X] The stable 'release' branch, made available every six
      months, for bug fixes.
- [ X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For help with submitting your package, please subscribe and post questions
to the [bioc-devel][4] mailing list.

[1]: https://bioconductor.org/developers/package-guidelines/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/

**Comment by hpages** [comment] 2020-11-19 00:02
Hi @kkleinoros ,

Thanks for submitting SOMNiBUS. Note that the Single Package Builder reported a test failure (please follow the link to the build report above to see the details). FWIW I can reproduce the failure on my laptop (Ubuntu 16.04 LTS):
```
hpages@spectre:~$ time R CMD check SOMNiBUS_0.99.0.tar.gz 
* using log directory ‘/home/hpages/Desktop/pkgreviews/SOMNiBUS.expressreview/SOMNiBUS.Rcheck’
* using R Under development (unstable) (2020-10-28 r79382)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘SOMNiBUS/DESCRIPTION’ ... OK
* this is package ‘SOMNiBUS’ version ‘0.99.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘SOMNiBUS’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Unexported objects imported by ':::' calls:
  ‘mgcv:::reTest’ ‘mgcv:::testStat’
  See the note in ?`:::` about the use of this operator.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  Time difference of 3.402629 mins
  ── FAILURE (test_groundzero.R:31:3): all values in reference output, saved on di
  isTRUE(all.equal(out_1, ref)) is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  FAILURE (test_binomRegMethModelSummary.R:27:5): binomRegMethModelSummary provides the correct regional p-value summary
  FAILURE (test_groundzero.R:31:3): all values in reference output, saved on disk, equals actual values coming from binomRegMethModel
  
  [ FAIL 2 | WARN 0 | SKIP 0 | PASS 21 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘SOMNiBUS.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR, 1 NOTE
See
  ‘/home/hpages/Desktop/pkgreviews/SOMNiBUS.expressreview/SOMNiBUS.Rcheck/00check.log’
for details.


real	12m30.332s
user	12m20.234s
sys	0m5.541s
```
Please address. When you do so don't forget to bump the version of the package in order to trigger a new build by the SPB.

Thanks,
H.

**Comment by hpages** [comment] 2020-11-19 00:14
Also please remove `SOMNiBUS.html` and `SOMNiBUS.R` from the `vignettes/` folder. These files are build products and thus don't belong to the package source tree.

Thanks,
H.

**Comment by kkleinoros** [comment] 2020-12-14 13:45
Am I able to submit a forked repository?

**Comment by lshep** [comment] 2020-12-18 13:12
At this point your repository has been added to our git.bioconductor.org,  how you keep track on github is entirely up to you. We would not recommend using a forked repository as it could create confusion for users to which repo to potentially report issues or look at code.  You need to push updated code to git.bioconductor.org as described in the links provided about about  [new package workflow](https://bioconductor.org/developers/how-to/git/new-package-workflow/)  and this may require activation of your [git credentials account](https://git.bioconductor.org/BiocCredentials)

**Comment by kkleinoros** [comment] 2020-12-21 13:46
I am having trouble pushing the updated code to git.bioconductor.org as currently the code in not in my repository and the two ssh keys do not match. Any suggestions?

**Comment by lshep** [comment] 2020-12-21 13:49
You could add additional keys manually using the [git credentials app](https://git.bioconductor.org/BiocCredentials)

**Comment by hpages** [comment] 2021-01-20 01:01
Hi @kkleinoros ,

Thanks for submitting SOMNiBUS. Package looks good and is almost ready to go.

One issue with the vignette: The Installation section says:
> Currently, the software package can be installed from github.

This needs to be updated to show the recommended way to install a Bioconductor package: https://bioconductor.org/install/

The reason people should not install Bioconductor packages from GitHub, and always use `BiocManager::install()` instead, is because Bioconductor has 6-month release cycles and a notion of release and devel. So installing from GitHub is very likely to introduce package version incompatibilities. OTOH using `BiocManager::install()` is safe and will always pick up the correct package versions.

Thanks,
H.

**Comment by hpages** [comment] 2021-01-26 10:29
Thanks for making the change. Package is good to go.

Cheers,
H.

**Comment by mtmorgan** [comment] 2021-02-03 20:45
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/kkleinoros.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("SOMNiBUS")`. The package 'landing page' will be created at

https://bioconductor.org/packages/SOMNiBUS

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed by mtmorgan** 2021-02-03 20:45 UTC
Labels: 3a. accepted, WARNINGS
