### ISSUE TITLE
beer

### ISSUE THREAD

**Issue by athchen** [Bioconductor/Contributions#2500] opened 2022-01-14 21:08 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/athchen/beer

Confirm the following by editing each check box to '[x]'

- [x] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [x] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [x] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [x] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [x] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [x] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [x] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [x] The 'devel' branch for new packages and features.
- [x] The stable 'release' branch, made available every six
      months, for bug fixes.
- [x] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by vjcitn** [comment] 2022-01-18 12:59
Your vignette mentions Homebrew.  Are you sure that approach will work for M1 mac?  Based on net chatter I installed JAGS from source for M1 and used R compiled from source and that worked fine.  But you might want to qualify the advice for mac users, for whom those using Rosetta emulation of intel will probably do fine with homebrew; M1 users who don't use Rosetta may not.

**Comment by athchen** [comment] 2022-01-18 16:12
Thanks! This is helpful to know. I'm not sure whether the approach will work for M1 mac, so I'll add the qualification to the vignette and the README.

**Comment by athchen** [comment] 2022-01-20 19:06
@lazappi I added the package to my watched tags list which should fix the Mac error, but I'm not sure how to address the Linux/Windows error. It seems like the error is related to a package dependency, but that package dependency (`PhIPData`) had no errors on the nightly build on devel. Any thoughts?

**Comment by lazappi** [comment] 2022-01-21 07:53
Hmmmm... I'm not quite sure either. Possibly something weird with the build system. Can you try pushing a new version to trigger the build again? Hopefully it's just a one-off thing and a new run will work.

**Comment by athchen** [comment] 2022-01-21 15:24
@lazappi I pushed a new version but it seems like the error is still there.

**Comment by lazappi** [comment] 2022-01-28 10:25
Hi @athchen

I'm still not quite sure what is happening with the build but I have reviewed the package anyway. Hopefully while you are addressing my comments it will sort itself out. I think this is a pretty high-quality package so I don't think you will need to make too many changes.

Please reply here if anything is unclear or needs any further explanation.

**What next?**

Please address the comments as best as you can. When you are ready for me to check the package again please reply to let me know with a summary of changes you have made or any other responses.

Luke

# Review

**Key:** :rotating_light: Required :warning: Recommended :green_circle: Optional :question: Question

## General package development

- [ ] :warning: There are a few notes from `BiocCheck::BiocCheck()`. Please check these and address as many as possible.

## DESCRIPTION file

- [ ] :green_circle: It is recommended to add a `URL` to `DESCRIPTION`. Usually this points to the GitHub repository but it could be another website for the package.
- [ ] :question: Is there a need for setting the `Collates` field? Most of the time this isn't necessary but maybe there was a reason in this case.

## NAMESPACE file

- [ ] :warning: I know the documentation says that `.brew_one()` is not meant to be used directly but I would still name it as an exported function to make it clear it is exported.
- [ ] :warning: I would suggest giving the `edgeR()` function a more descriptive name to avoid confusion between this and the package. Something like `run_edgeR()` would be ok but more specific would be better.
- [ ] :warning: There is a bit of a mix of `camelCase` and `snake_case` for function names. Please try to stick to one style.
- [ ] :warning: Smiliar comment about argument names, sometimes you use `snake_case` and sometimes `dot.case`.

## The NEWS file

- [ ] :green_circle: Just a reminder to keep the `NEWS` file updated as you make changes

## Package data

- [ ] :green_circle: The documentation for `phipseq_model.bugs` could do with a bit more detail. Also reminder to update the bioRxiv link.

## Documentation

- [ ] :warning: I noticed a few typos in various places. Not a bit deal but adding spellchecking with `usethis::use_spell_check()` can help with catching these.

### README

- [ ] :rotating_light: No need for specific instructions for installing `PhIPData`, this should be handled by `BiocManager`
- [ ] :warning: Reminder to update the bioRxiv URL here as well
- [ ] :green_circle: Check that you have the correct citations for `edgeR`, see `citation("edgeR")`

### Vignette

- [ ] :rotating_light: Same comment about instructions for `PhIPData`
- [ ] :green_circle: Some of the code in the vignette is quite complex. You might want to break it down a bit more or maybe even turn it into functions in the package if you think it is something users will want to do.

### Man pages

- [ ] :warning: Recommended to add a package man page, try `usethis::use_package_doc()` or see https://r-pkgs.org/man.html#man-packages
- [ ] :green_circle: I noticed the formatting in `?.getAB_edgeR` was a bit weird, you may want to check that

## Code

### R

- [ ] :rotating_light: It is recommended that Bioconductor package use `BiocParallel` for parallelization rather than another framework
- [ ] :rotating_light: When joining paths use `file.path()` rather than `paste0()`, this should make sure that paths are correct on different platforms
- [ ] :green_circle: When you have an argument with a small set of options it is usually cleaner to use this pattern with `match.arg()` rather than writing an if statement to manually check them. You might also want to think about adding checks for some of the other kinds of arguments.

```r
func <- function(option = c("Option1", "Option2")) {
    option <- match.arg(option)

    # Whatever the function does
    ...
}
```

**Comment by lshep** [comment] 2022-01-28 12:15
Please make sure you are using a devel version of the package dependencies. I'm not sure why it doesn't appear on the other two builders but in the current checkout of git.bioconductor.org version of PhIPData that you are using there is no file `defaults.rda` 

```
pkgbuild@nebbiolo1:/home/biocbuild/bbs-3.15-bioc/R/library/PhIPData/extdata$ ls -lrth
total 397K
-rw-rw-r-- 1 biocbuild biocbuild 1.1M Jan 23 15:18 virscan.tsv
-rw-rw-r-- 1 biocbuild biocbuild  209 Jan 23 21:02 alias.rda
```
Which is the cause of the error.

**Comment by athchen** [comment] 2022-02-04 16:13
Hi @lazappi and @lshep, 

Thanks for the review and feedback. `defaults.rda` should not exist the first time the user installs `PhIPData`, but is created when they first load it. I wondered if it was perhaps the use of `paste0()` instead of `file.path()` but when I made those changes to `PhIPData` and pushed it to Bioconductor, `beer` still fails here. I'm not sure how to fix it since `PhIPData` 1.3.0 builds and passes checks for BioC 3.15 which means it also passes the tests for functions that rely on accessing that `defaults.rda` file. I also can't seem to reproduce the error on another Windows machine. At this point I'm not quite sure how to go about debugging this. Any ideas?

As for the review, I've also addressed the comments as best as I've can (see below for additional details for some of the comments). Please let me know if there are any other changes to be made. Thanks again for all of the help and taking the time to review the package!

Athena 

> # Review
> **Key:** 🚨 Required ⚠️ Recommended 🟢 Optional ❓ Question
> 
> ## General package development
> * [ ]  ⚠️ There are a few notes from `BiocCheck::BiocCheck()`. Please check these and address as many as possible.
> 
> ## DESCRIPTION file
> * [x]  🟢 It is recommended to add a `URL` to `DESCRIPTION`. Usually this points to the GitHub repository but it could be another website for the package.
> * [x]  ❓ Is there a need for setting the `Collates` field? Most of the time this isn't necessary but maybe there was a reason in this case.

In this case it looks like there really isn't need to set the `Collates` field. I've taken it out of the `DESCRIPTION` FILE. 

> ## NAMESPACE file
> * [x]  ⚠️ I know the documentation says that `.brew_one()` is not meant to be used directly but I would still name it as an exported function to make it clear it is exported.

I've changed it to `brewOne()` and have changed the corresponding `.edgeR_one()` function to `edgeROne()`. 

> * [x]  ⚠️ I would suggest giving the `edgeR()` function a more descriptive name to avoid confusion between this and the package. Something like `run_edgeR()` would be ok but more specific would be better.

That makes sense. It's now named `runEdgeR()`.

> * [x]  ⚠️ There is a bit of a mix of `camelCase` and `snake_case` for function names. Please try to stick to one style.

I've changed the function names to use `camelCase`.

> * [x]  ⚠️ Smiliar comment about argument names, sometimes you use `snake_case` and sometimes `dot.case`.

Argument names should now use `dot.case`. 

> ## The NEWS file
> * [x]  🟢 Just a reminder to keep the `NEWS` file updated as you make changes
> ## Package data
> * [x]  🟢 The documentation for `phipseq_model.bugs` could do with a bit more detail. Also reminder to update the bioRxiv link.
> ## Documentation
> * [x]  ⚠️ I noticed a few typos in various places. Not a bit deal but adding spellchecking with `usethis::use_spell_check()` can help with catching these.

> ### README
> * [x]  🚨 No need for specific instructions for installing `PhIPData`, this should be handled by `BiocManager`

Removed in both the `README` and Vignette. 

> * [x]  ⚠️ Reminder to update the bioRxiv URL here as well
> * [x]  🟢 Check that you have the correct citations for `edgeR`, see `citation("edgeR")`
> 
> ### Vignette
> * [x]  🚨 Same comment about instructions for `PhIPData`
> * [ ]  🟢 Some of the code in the vignette is quite complex. You might want to break it down a bit more or maybe even turn it into functions in the package if you think it is something users will want to do.

We're not quite sure if we want to implement it as functions yet, but will think about it for possible future iterations. Thanks for the suggestion!

> ### Man pages
> * [x]  ⚠️ Recommended to add a package man page, try `usethis::use_package_doc()` or see https://r-pkgs.org/man.html#man-packages
> * [x]  🟢 I noticed the formatting in `?.getAB_edgeR` was a bit weird, you may want to check that

Should be fixed now!

> ## Code
> ### R
> * [x]  🚨 It is recommended that Bioconductor package use `BiocParallel` for parallelization rather than another framework
> * [x]  🚨 When joining paths use `file.path()` rather than `paste0()`, this should make sure that paths are correct on different platforms
> * [ ]  🟢 When you have an argument with a small set of options it is usually cleaner to use this pattern with `match.arg()` rather than writing an if statement to manually check them. You might also want to think about adding checks for some of the other kinds of arguments.
> 
> ```r
> func <- function(option = c("Option1", "Option2")) {
>     option <- match.arg(option)
> 
>     # Whatever the function does
>     ...
> }
> ```

Thanks for the suggestion! I'll try using this next time I have a small set of options.

**Comment by lshep** [comment] 2022-02-04 17:06
I don't think you should ever be trying to write to a packages install location after the fact. Users are not necessarily the same account as the install account and I am guessing there is or could be a permission error.  I would recommend creating/using default cache locations for the package for data that is created on load.  See [BiocFileCache.](http://bioconductor.org/packages/release/bioc/html/BiocFileCache.html)

**Comment by athchen** [comment] 2022-02-04 17:20
@lshep Thanks! I didn't think about it that way, and I think may explain the error we see here. I'll work on creating and using default cache locations in `PhIPData`. 

When I push a version bump for beer here, would it use the current version that's passed the nightly builds (1.3.0) or the version of the package on git.bioconductor.org?

**Comment by lshep** [comment] 2022-02-04 17:25
it uses the nightly builder version -- it has to have propagated so as long as the build report is showing the updated version number for [PhIPData](http://bioconductor.org/checkResults/devel/bioc-LATEST/PhIPData/) , it will grab that version

**Comment by athchen** [comment] 2022-02-07 22:03
Hi @lazappi and @lshep, 

Thank you so much for the help! I think the switch to `BiocFileCache` fixed the `PhIPData` dependency problem. I still get an error on windows, but I don't quite see/understand the error message. It looks like the execution just stopped in BiocCheck but I can't find why. Not sure if I'm missing something or just not seeing it here. 

Also on Linux it says the build skipped -- is this something I should be able to fix?

Thanks, 
Athena

**Comment by lazappi** [comment] 2022-02-08 07:37
Hmmm...It does just seem to have stopped. Not sure exactly what is going on there but it seems to be something in **{BiocCheck}** rather than the main checks.

I will have a look at your responses to my first round of comments and then we can see if this is still happening.

**Comment by lazappi** [comment] 2022-02-09 08:38
Thanks for addressing my comments! I'm happy with what you have done except for a couple of minor things:

* Replacing **{future}** with **{BiocParallel}** looks good
	* I would suggest setting `BiocParallel::SerialParam()` as the default for your `bp.param` argument. That way things will just run for anyone who is happy to use a single core but they can set something else if they want to do things in parallel.
	* There is one reference to **{future}** in `README` which you might want to update
* When defining a function the usual convention is to place arguments without defaults first and then arguments with defaults. Not a big deal but could help users know which things are required and which are optional.

If you can push a new version with some of those changes hopefully the build resolves itself. If not we will look more into what is going on there.

**Comment by athchen** [comment] 2022-02-09 17:15
@lazappi No problem! Thanks for taking another look at the package. Also hooray! looks like it passed this time.

I updated the reference to **{future}** in the `README` and checked that the order of arguments is those without defaults go first and those with defaults follows. 

I didn't change the default `bp.param` to `BiocParallel::SerialParam()` since it seems more predictable to me that the default behavior follows the `BiocParallel` defined default backend to use. This way if the user changes their default backend in BiocParallel, the behavior would propagate when the package functions are called. I would also say that in most use cases, I would expect most of the functions to be run in parallel.

**Comment by lazappi** [comment] 2022-02-11 10:11
I think I must have missed that this was the default the first time I looked. This is also reasonable I suppose, only thing is that I think the default is often to do things in parallel which can be an issue on shared servers where you can accidentally take over resources (hence my preference for `SerialParam()` as default). I don't know if the Bioconductor core has a strong position on this though, maybe @lshep can let us know if there is?

One other really minor thing, the parameter for this is usually called `BPPARAM` rather than `bp.param`. I didn't mention this before it's probably not important but just in case it is something else the core want to standardise. 

I am happy with this though, so unless we hear from the core that you should do these I will approve this early next week.

**Comment by vjcitn** [comment] 2022-02-11 11:49
definitely use BPPARAM convention if at all possible   @mtmorgan

**Comment by athchen** [comment] 2022-02-11 16:11
Not sure if this is a dumb question -- but would it be better to use `BPPARAM` in this case rather than `bp.param` even though all the other argument names are in `dot.case`?

**Comment by lazappi** [comment] 2022-02-14 07:49
I think this is a special case, normally you wouldn't have an all uppercase argument so I guess this was chosen to stand out from normal function arguments.

**Comment by athchen** [comment] 2022-02-14 21:58
I've fixed the argument name from `bp.param` to `BPPARAM`!

**Comment by lazappi** [comment] 2022-02-15 08:31
I will mark this as approved, congratulations 🎉 ! It should be picked up by the main build system and part of Bioconductor devel within a few days.

**Comment by lshep** [comment] 2022-02-17 13:48
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/athchen.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("beer")`. The package 'landing page' will be created at

https://bioconductor.org/packages/beer

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2022-02-17 13:49 UTC
Labels: OK, 3a. accepted
