### ISSUE TITLE
 MsBackendRawFileReader Public

### ISSUE THREAD

**Issue by cpanse** [Bioconductor/Contributions#2339] opened 2021-09-27 14:18 UTC
Update the following URL to point to the GitHub repository of
the package you wish to submit to _Bioconductor_

- Repository: https://github.com/fgcz/MsBackendRawFileReader

Confirm the following by editing each check box to '[x]'

- [X] I understand that by submitting my package to _Bioconductor_,
  the package source and all review commentary are visible to the
  general public.

- [X] I have read the _Bioconductor_ [Package Submission][2]
  instructions. My package is consistent with the _Bioconductor_
  [Package Guidelines][1].

- [X] I understand Bioconductor [Package Naming Policy][9] and acknowledge
  Bioconductor may retain use of package name.

- [X] I understand that a minimum requirement for package acceptance 
  is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS. 
  Passing these checks does not result in automatic acceptance. The 
  package will then undergo a formal review and recommendations for 
  acceptance regarding other Bioconductor standards will be addressed.

- [X] My package addresses statistical or bioinformatic issues related
  to the analysis and comprehension of high throughput genomic data.

- [X] I am committed to the long-term maintenance of my package. This
  includes monitoring the [support site][3] for issues that users may
  have, subscribing to the [bioc-devel][4] mailing list to stay aware
  of developments in the _Bioconductor_ community, responding promptly
  to requests for updates from the Core team in response to changes in
  _R_ or underlying software.
  
- [X] I am familiar with the [Bioconductor code of conduct][7] and 
  agree to abide by it.

I am familiar with the essential aspects of _Bioconductor_ software
management, including:

- [X] The 'devel' branch for new packages and features.
- [ X The stable 'release' branch, made available every six
      months, for bug fixes.
- [X] _Bioconductor_ version control using [Git][5]
  (optionally [via GitHub][6]).

For questions/help about the submission process, including questions about
the output of the automatic reports generated by the SPB (Single Package
Builder), please use the #package-submission channel of our Community Slack.
Follow the link on the home page of the [Bioconductor website][8] to sign up.

[1]: https://contributions.bioconductor.org/
[2]: https://bioconductor.org/developers/package-submission/
[3]: https://support.bioconductor.org
[4]: https://stat.ethz.ch/mailman/listinfo/bioc-devel
[5]: http://bioconductor.org/developers/how-to/git/
[6]: http://bioconductor.org/developers/how-to/git/sync-existing-repositories/
[7]: https://bioconductor.org/about/code-of-conduct/
[8]: https://bioconductor.org/
[9]: https://bioconductor.org/developers/package-submission/#naming

**Comment by lshep** [comment] 2021-10-08 16:59
I'm trying to build, install, and check locally and I'm running into the following ERROR:

```
(base) shepherd@jbcj433:~/PkgReviews$ R CMD build MsBackendRawFileReader 
* checking for file 'MsBackendRawFileReader/DESCRIPTION' ... OK
* preparing 'MsBackendRawFileReader':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘MsBackendRawFileReader.Rmd’ using rmarkdown
trying URL 'https://github.com/thermofisherlsms/ThermoRawFileParser/raw/master/packages/ThermoFisher.CommonCore.RawFileReader.4.0.26/lib//ThermoFisher.CommonCore.Data.dll'
Content type 'application/octet-stream' length 360448 bytes (352 KB)
==================================================
downloaded 352 KB

trying URL 'https://github.com/thermofisherlsms/ThermoRawFileParser/raw/master/packages/ThermoFisher.CommonCore.RawFileReader.4.0.26/lib//ThermoFisher.CommonCore.MassPrecisionEstimator.dll'
Content type 'application/octet-stream' length 11264 bytes (11 KB)
==================================================
downloaded 11 KB

trying URL 'https://github.com/thermofisherlsms/ThermoRawFileParser/raw/master/packages/ThermoFisher.CommonCore.RawFileReader.4.0.26/lib//ThermoFisher.CommonCore.RawFileReader.dll'
Content type 'application/octet-stream' length 620544 bytes (606 KB)
==================================================
downloaded 606 KB

trying URL 'http://fgcz-ms.uzh.ch/~cpanse/rawrr/rawrr.1.1.12.exe'
Content type 'application/x-msdos-program' length 26624 bytes (26 KB)
==================================================
downloaded 26 KB

snapshotDate(): 2021-10-06
see ?tartare and browseVignettes('tartare') for documentation
loading from cache
see ?tartare and browseVignettes('tartare') for documentation
loading from cache
see ?tartare and browseVignettes('tartare') for documentation
loading from cache

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
Quitting from lines 94-97 (MsBackendRawFileReader.Rmd) 
Error: processing vignette 'MsBackendRawFileReader.Rmd' failed with diagnostics:
BiocParallel errors
  3 remote errors, element index: 1, 2, 3
  0 unevaluated and other errors
  first remote error: argument is of length zero
--- failed re-building ‘MsBackendRawFileReader.Rmd’

SUMMARY: processing the following file failed:
  ‘MsBackendRawFileReader.Rmd’

Error: Vignette re-building failed.
Execution halted
```
 Please advise

**Comment by cpanse** [comment] 2021-10-08 17:54
@lshep I think mono is not installed on your system.
http://bioconductor.org/packages/release/bioc/install/rawrr/INSTALL 
Christian

**Comment by lshep** [comment] 2021-10-08 18:01
I did follow the instructions suggested of `sudo apt-get install mono-runtime` that was given -- if there is more extensive installation for this package it probably should be noted somewhere to check and reference this installation file. After installing all the recommended system installation of the linux section that indeed fixed.  I will continue with a review

**Comment by lshep** [comment] 2021-10-12 14:07
Thank you for your submission. Please see comments: 

**inst**

- [ ] Please provide an `inst/scripts/` directory that contains a file that
  explains how the data in `inst/extdata` was generated. This can be R code,
  sudo-code, or plain text but minimally should include the source information
  for the data.

**NEWS**

- [ ] (Optional) We highly recommend a NEWS file for keeping track of changes or updates.
  NEWS files are used to create the Bioconductor release announcements.

**Vignettes**

**MsBackendRawFileReader.Rmd**

- [ ] Perhaps put the `stopifnot` for required packages in a `suppressMessage()`
  for easier reading.

- [ ] By hiding code in your vignette I am not able to run the code chunk

```
beRaw <- Spectra::backendInitialize(
  MsBackendRawFileReader::MsBackendRawFileReader(),
  files = c(rawfileEH3220, rawfileEH3222, rawfileEH4547))
```
because the code to generate `rawfileEH####*` is not shown.

- [ ] The data retrieve from the hub is then not utilized in the vignette anywhere?
```
EH3219 <- normalizePath(eh[["EH3219"]])
EH3221 <- normalizePath(eh[["EH3221"]])
EH4547 <- normalizePath(eh[["EH4547"]])
```

- [ ] Please show all necessary code to reproduce. I also cannot run the code
  `Application example`

```
> SF1 <- (beRaw |>  
+    filterScan("ms2 487.2567"))
> 
> SF2 <- beRaw |>  
+    filterScan("ms2 487.25") |>
+    sparceVector() |> 
+    dotProduct(list(mZ=c(1, 2, 3), intensity=c(10, 100, 100)))
Error in dotProduct(sparceVector(filterScan(beRaw, "ms2 487.25")), list(mZ = c(1,  : 
  could not find function "dotProduct"

```

This is why we recommend running as much code as possible in the vignette for
reproducibility.


**tartare.Rmd**

- [ ] Please rename as there is a `tartare.Rmd` in the tartare package.  When
  trying to pull up your vignette if I do `vignette("tartare")` I do not find
  your vignette, I find the tartare package vignette. and when I try to specify
  your package I cannot read the vignette

```
> vignette("tartare", package="MsBackendRawFileReader")
Warning message:
vignette 'tartare' not found 
```

**ForDevelopers**

- [ ] Same issue with ForDevelopers

```
> vignette("ForDevelopers", package="MsBackendRawFileReader")
Warning message:
vignette 'ForDevelopers' not found 

```


**Rcode**

- [ ] Please remove unused commented out code.

Please address the above issues and comment back here.  When ready please remember to do a version bump to trigger a new build and request a re-review. 

Cheers,

**Comment by cpanse** [comment] 2021-10-13 09:06
Dear @lshep; Thank you for your review. I solved all issues.  Thank you, Christian
```
0 cp@leda:~/__checkouts/bioc/MsBackendRawFileReader % git log --oneline                                                                                                                                      (git)-[master]-21-10-13|10:43:18
515f939 (HEAD -> master, origin/master, origin/HEAD) Merge
c3ebfdf Bump 0.99.3
904d9d3 Enhance and correct package vignette
89a585f Remove unused commented R code
a6ba078 Remove tartare.Rmd and ForDevelopers.Rmd files
ba3a002 Add specs.R file in inst/scrtips
45caaa2 Add NEWS.rd file
```

> Thank you for your submission. Please see comments:
> 
> **inst**
> 
>     * [X]  Please provide an `inst/scripts/` directory that contains a file that
>       explains how the data in `inst/extdata` was generated. This can be R code,
>       sudo-code, or plain text but minimally should include the source information
>       for the data.
> 
> 
> **NEWS**
> 
>     * [X]  (Optional) We highly recommend a NEWS file for keeping track of changes or updates.
>       NEWS files are used to create the Bioconductor release announcements.
> 
> 
> **Vignettes**
> 
> **MsBackendRawFileReader.Rmd**
> 
>     * [X]  Perhaps put the `stopifnot` for required packages in a `suppressMessage()`
>       for easier reading.
> 
>     * [X]  By hiding code in your vignette I am not able to run the code chunk
> 
> 
> ```
> beRaw <- Spectra::backendInitialize(
>   MsBackendRawFileReader::MsBackendRawFileReader(),
>   files = c(rawfileEH3220, rawfileEH3222, rawfileEH4547))
> ```
> 
> because the code to generate `rawfileEH####*` is not shown.
> 
>     * [X]  The data retrieve from the hub is then not utilized in the vignette anywhere?
> 
> 
> ```
> EH3219 <- normalizePath(eh[["EH3219"]])
> EH3221 <- normalizePath(eh[["EH3221"]])
> EH4547 <- normalizePath(eh[["EH4547"]])
> ```
> 
>     * [X]  Please show all necessary code to reproduce. I also cannot run the code
>       `Application example`
> 
> 
> ```
> > SF1 <- (beRaw |>  
> +    filterScan("ms2 487.2567"))
> > 
> > SF2 <- beRaw |>  
> +    filterScan("ms2 487.25") |>
> +    sparceVector() |> 
> +    dotProduct(list(mZ=c(1, 2, 3), intensity=c(10, 100, 100)))
> Error in dotProduct(sparceVector(filterScan(beRaw, "ms2 487.25")), list(mZ = c(1,  : 
>   could not find function "dotProduct"
> ```
> 
> This is why we recommend running as much code as possible in the vignette for reproducibility.
> 
> **tartare.Rmd**
> 
>     * [X]  Please rename as there is a `tartare.Rmd` in the tartare package.  When
>       trying to pull up your vignette if I do `vignette("tartare")` I do not find
>       your vignette, I find the tartare package vignette. and when I try to specify
>       your package I cannot read the vignette
> 
> 
> ```
> > vignette("tartare", package="MsBackendRawFileReader")
> Warning message:
> vignette 'tartare' not found 
> ```
> 
> **ForDevelopers**
> 
>     * [X]  Same issue with ForDevelopers
> 
> 
> ```
> > vignette("ForDevelopers", package="MsBackendRawFileReader")
> Warning message:
> vignette 'ForDevelopers' not found 
> ```
> 
> **Rcode**
> 
>     * [X]  Please remove unused commented out code.
> 
> 
> Please address the above issues and comment back here. When ready please remember to do a version bump to trigger a new build and request a re-review.
> 
> Cheers,

**Comment by lshep** [comment] 2021-10-13 17:00
**vignette**
Again -- I'm not sure why you are doing the following as the don't appear to be used in the code for the vignette anywhere?  
```
EH3219 <- normalizePath(eh[["EH3219"]])
EH3221 <- normalizePath(eh[["EH3221"]])
```
And the following is done twice which is unnecessary?
```
EH4547 <- normalizePath(eh[["EH4547"]])
```

I see EH3220 , EH3222 and EH4547 uses with  `files = c(rawfileEH3220, rawfileEH3222, rawfileEH4547))`

Can this be cleaned up?

**Comment by cpanse** [comment] 2021-10-13 20:15
> **vignette** Again -- I'm not sure why you are doing the following as the don't appear to be used in the code for the vignette anywhere?
> 
> ```
> EH3219 <- normalizePath(eh[["EH3219"]])
> EH3221 <- normalizePath(eh[["EH3221"]])
> ```
> 
> And the following is done twice which is unnecessary?
> 
> ```
> EH4547 <- normalizePath(eh[["EH4547"]])
> ```
> 
> I see EH3220 , EH3222 and EH4547 uses with `files = c(rawfileEH3220, rawfileEH3222, rawfileEH4547))`
> 
> Can this be cleaned up?
@lshep  Yes, I fixed that. I might introduce the mzXML files again once I get the mzR package running on my M1 for a MsBackend comparison. C

**Comment by lshep** [comment] 2021-10-13 20:17
And that seems like an intermittent error on our part so I'm okay to accept now. thank you

**Comment by lshep** [comment] 2021-10-14 13:45
The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/cpanse.keys is not empty), then no further steps are required. Otherwise, do the following:

1. [Add an SSH key to your github account][]
1. [Submit your SSH key to Bioconductor][]

See further instructions at

https://bioconductor.org/developers/how-to/git/

for working with this repository. See especially

https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/

to keep your GitHub and Bioconductor repositories in sync.

Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at

https://bioconductor.org/checkResults/

(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsBackendRawFileReader")`. The package 'landing page' will be created at

https://bioconductor.org/packages/MsBackendRawFileReader

If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.

[Add an SSH key to your github account]: https://help.github.com/articles/connecting-to-github-with-ssh/
[Submit your SSH key to Bioconductor]: https://git.bioconductor.org/BiocCredentials/

**Closed as completed by lshep** 2021-10-14 13:45 UTC
Labels: ERROR, 3a. accepted
